### ISSUE TITLE
Smarter symbolType defaults for legend, and add a 'line' symbol

### ISSUE THREAD

**Issue by gwdekker** [altair-viz/altair#1000]
Would it be a good idea to get more appropriate symbol types when creating the legends? For example, when creating a chart with mark_rect, the legend shows circles while squares are more appropriate. For mark_line, a small line stroke would be nice to have as well.

**Comment by jakevdp** [comment]
Yes, and I believe this is an open issue in Vega-Lite.

**Comment by jakevdp** [comment]
Note that legends have been substantially reworked recently in Vega/Vega-Lite, though it hasn't yet made it into a release. See https://github.com/vega/vega-lite/pull/3778 for example

**Comment by jakevdp** [comment]
This works in vega-lite 3; e.g. https://altair-viz.github.io/gallery/multi_series_line.html
