### ISSUE TITLE
Chart Rendering is Blurry on 4K Monitor in JupyterLab

### ISSUE THREAD

**Issue by dbk123** [altair-viz/altair#1002]
I am using the latest version of Altair through JupyterLab on a 4K monitor and the charts appear to be rendered at an inadequate resolution causing them to appear blurry (see attached image).

I am running jupyterlab version 0.32.1.  The chart appears fine in Jupyter Notebook.
![altair plot](https://user-images.githubusercontent.com/16540538/42325548-8e6b01ac-8034-11e8-92d7-304901f62f46.JPG)

Thanks for any help!

**Comment by jakevdp** [comment]
@domoritz @kanitw any ideas why this would be? I believe that Jupyterlab renders with canvas

**Comment by domoritz** [comment]
Vega automatically detects `window.devicePixelRatio`. @dbk123, what do you get when you run this command in your javascript console? It should be `2`.

**Comment by dbk123** [comment]
I get 1.75.  The resolution of my display is 3840 x 2160.  The problem is not 100% repeatable, but I can't determine the set of conditions that causes it to come and go.

**Comment by davidanthoff** [comment]
I just tried this on Windows with 150% display scaling, and things seem to look fine. This is what I get on Edge:
![image](https://user-images.githubusercontent.com/1036561/42341768-7f120ec0-8094-11e8-9b0f-617dde54f209.png)
and Chrome:
![image](https://user-images.githubusercontent.com/1036561/42341787-8c09d41e-8094-11e8-8c36-c6522dc23d3f.png)
Everything looks very crisp.

I generated these plots from julia with [VegaLite.jl](https://github.com/fredo-dedup/VegaLite.jl), but I think the whole display story should be the same for Altair and the julia version.

Might be helpful to know what OS/browser etc. you are using.

**Comment by dbk123** [comment]
I am using Chrome on Windows 10 Pro

**Comment by dbk123** [comment]
Also, I've got my display scaling set to 175%.  (Hence the parameter value of 1.75 for window.devicePixelRatio I suspect.)

**Comment by domoritz** [comment]
Can you try to set it to 200%?

**Comment by dbk123** [comment]
I am away from the computer having the issue for about a week.  Sorry - hate to leave when there is momentum on this!

**Comment by iliatimofeev** [comment]
On Retina display  `'svg'` renderer looks a bit better

```python
import altair as alt
from vega_datasets import data

alt.Chart(data.cars()).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).display(renderer='svg') #use 'svg' renderer 
```

**Comment by jakevdp** [comment]
Yeah, we need to get a 2.2 release out. Still a couple minor blockers (#1060 & #1072)

**Comment by andrewgiessel** [comment]
Just leaving a note for the future googler that installing vega_datasets and altair w/o installing vega (with pip as specified in the docs) caused this for me.  installing vega with pip fixed the issue upon reloading the page.

**Comment by domoritz** [comment]
JupyterLab does not use the `vega` pip package.
