### ISSUE TITLE
expr.format does not accept comma in format string

### ISSUE THREAD

**Issue by KODeKarnage** [altair-viz/altair#1012]
Encountered this problem creating a mark_text chart. The following code causes the chart not too render.
```
    ).transform_calculate(
    text = expr.format( datum.PerDay  / datum.Total), ",.2f")
    )
```
The workaround was to use the format argument in alt.Text. This is workable, but I wanted different formatting for different data fields which meant I had to specify the formatting in multiple encodings instead of the different calculations.

**Comment by jakevdp** [comment]
Can you show an example of where this is working incorrectly? As far as I can tell, altair is generating a correct vega expression in this case:
```python
>>> from altair import expr, datum
>>> expr.format( datum.PerDay  / datum.Total, ",.2f")
format((datum.PerDay / datum.Total),',.2f')
```

**Comment by jakevdp** [comment]
Thanks. Looks like it may be a vega-lite bug, unless I'm misunderstanding what format() is supposed to look like. I'll open an issue there.

**Comment by jakevdp** [comment]
It turns out the issue is that once you have formatted the values, they are strings and not numbers, so you need to use ``'value:N'`` rather than ``'value:Q'`` in order for them to be appropriately displayed:
```python
from altair import Chart, datum, expr
import pandas as pd

data = pd.DataFrame({'name': ['a', 'b', 'c', 'd'], 'raw_value': [1.111, 2222.2, 3, 10000]})

format_in_encoding = Chart(data=data).mark_text().encode(
            y='name:N',
            text=alt.Text('raw_value:Q', format=',.2f')
)

format_in_calculation = Chart(data=data).mark_text().encode(
            y='name:N',
            text='value:N'
).transform_calculate(
    value=expr.format(datum.raw_value, ',.2f')
)

format_in_encoding | format_in_calculation
```
![visualization 7](https://user-images.githubusercontent.com/781659/42616268-6f2ef176-8562-11e8-9c1a-c4b5409b1a46.png)
