### ISSUE TITLE
Log colour scales don't seem to choose sensible default domains/ranges

### ISSUE THREAD

**Issue by claresloggett** [altair-viz/altair#1014]
Summary: If I use a log colour scale by setting colour to `alt.Color('colorvariable:Q', scale=alt.Scale(type='log')`, there is very little variation across the colour range. If I log-transform the variable myself, or, oddly, if set the `range` on the `alt.Scale()` object, I get a much better result.

I assume it is about the range being chosen by default in this case. I don't have this issue with linear colour scales, and don't see any analogous issue with using a log scale on a spatial axis.

I'm guessing this may be a vega-lite issue but don't know how to tell.

Here's a toy example:

```
x = [1,2,3,4]
y = x
c = [1,10,100,1000]
df = pd.DataFrame({'x':x, 'y':y, 'c':c})

logscale_plot = alt.Chart(df).mark_circle(size=90)\
                             .encode(x='x',y='y',
                                     color=alt.Color('c:Q', 
                                                scale=alt.Scale(type='log')))\
                             .properties(title='A: log scale')

logtransform_plot = alt.Chart(df).mark_circle(size=90)\
                       .encode(x='x', y='y',
                               color=alt.Color('logc:Q'))\
                       .transform_calculate(logc='log(datum.c)')\
                       .properties(title='B: log transform, linear scale')

logscale_range_plot = alt.Chart(df).mark_circle(size=90)\
                                   .encode(x='x',y='y',
                                           color=alt.Color('c:Q', 
                                                            scale=alt.Scale(type='log',
                                                                            range=['red','blue'])))\
                                   .properties(title='C: log scale with range set')

logtransform_range_plot = alt.Chart(df).mark_circle(size=90)\
                                       .encode(x='x', y='y',
                                               color=alt.Color('logc:Q',
                                                               scale=alt.Scale(type='linear',
                                                                               range=['red','blue'])))\
                                       .transform_calculate(logc='log(datum.c)')\
                                       .properties(title='D: log transform, linear scale, range set')

logscale_plot & logtransform_plot & logscale_range_plot & logtransform_range_plot
```

![altair_logcolourbug](https://user-images.githubusercontent.com/1815107/42580324-db40524c-84ef-11e8-85c2-753ee6421385.png)

The problem occurs in Plot A, where I use a log colour scale and *do not* set the range. I would expect A to look very similar to B, where I use a log data transform instead of a scale transform. As you can see though the colour bar covers a pretty small range - Plot B, which uses a transform instead of a scale, is much better. Conversely, Plot C *does* look very similar to D. The only difference is in these two plots I have set the scale range explicitly.

**Comment by jakevdp** [comment]
Thanks – I think this is a bug that was introduced in the most recent vega release. Here's the plot with Vega 4:

![visualization 5](https://user-images.githubusercontent.com/781659/42588113-b14f8bb8-84f1-11e8-975d-4eb15003ee21.png)

And here's the plot with Vega 3:

![visualization 4](https://user-images.githubusercontent.com/781659/42588105-ab10f9a8-84f1-11e8-8154-31a3de293307.png)

It would be worth raising this issue in the vega-lite project – let me know if you'd like to do that or if you'd like me to.

**Comment by claresloggett** [comment]
Thanks @jakevdp ! The vega-lite issue tracker asks for an example spec in JSON. Is that something I can easily extract from my altair plot?

**Comment by jakevdp** [comment]
OK - let me know if I can help!

**Comment by domoritz** [comment]
Fixed in https://github.com/vega/vega-lite/pull/4040.
