### ISSUE TITLE
<VegaLite 2 Object>

### ISSUE THREAD

**Issue by Alalalalaki** [altair-viz/altair#1016]
It used to work, but fails after I tried to disable and enable some labextensions.

<img width="867" alt="2018-07-13 0 34 20" src="https://user-images.githubusercontent.com/31154974/42643818-0c41d9c4-8635-11e8-838b-da74edc92ece.png">
<img width="544" alt="2018-07-13 0 35 11" src="https://user-images.githubusercontent.com/31154974/42643829-0eee515c-8635-11e8-8405-970fd8ffc156.png">

**Comment by jakevdp** [comment]
In my experience, once you start mucking around with installing/uninstalling/enabling/disenabling jupyter extensions can lead to strange residual effects that are difficult to debug. I would suggest starting over in a clean virtualenv/conda env.
