### ISSUE TITLE
Pyramid Plot

### ISSUE THREAD

**Issue by hbar137** [altair-viz/altair#1018]
I am trying to construct population pyramid plot but cannot get the bars on left side to invert. My code is below

```
chart_m = alt.Chart(df_age).mark_bar().encode(
    x=alt.X('age_m', type='quantitative',
            axis=alt.Axis(title='count'),
            scale=alt.Scale(domain=(130000,0)),
            ),
    y=alt.Y('index:N',axis=alt.Axis(orient='right')
    ),
    color=alt.Color('age_m')
)

chart_f = alt.Chart(df_age).mark_bar().encode(
    x=alt.X('age_f', type='quantitative', 
            axis=alt.Axis(title='count'),
            scale=alt.Scale(domain=(0,130000))),
    y=alt.Y('index:N',axis=alt.Axis(orient='left')
    ),
    color=alt.Color('age_m')
)

alt.hconcat(chart_m,chart_f)
```

this produces charts like
![image](https://user-images.githubusercontent.com/2086385/42656764-1f16c894-85d5-11e8-8404-4a14d13430ac.png)

I will appreciate if someone can point me to how I can improve. Thanks!

**Comment by ruizdurazo** [comment]
So I'm not sure Vega-Lite explicitly supports this. From the Vega docs, the `axis` object you were trying to move to the right simply refers to the set of ticks, its title, etc. So playing with that won't move the plot's actual content. And I believe the scale's `domain` also won't alter the plot in the way we want.

But not all is lost. A hack that achieves typical the population pyramid might be something like the following:

```
df_age = pd.DataFrame(data=[[36,25,16,9,4],[36,25,16,9,4]], 
                      index=['age_m', 'age_f'],
                      columns=['0-15', '15-30', '30-45', '45-60', '60+']).T.reset_index()

chart_m = alt.Chart(df_age).mark_bar().encode(
    x=alt.X('age_m:Q',
            title='Male',
            sort='descending',
            scale=alt.Scale(domain=(0,40))),
    y=alt.Y('index:N', axis=alt.Axis(title='Age Groups'), sort='descending'),
    color=alt.Color('age_m')
)

chart_f = alt.Chart(df_age).mark_bar().encode(
    x=alt.X('age_f:Q',
            title='Femle',
            sort='ascending',
            scale=alt.Scale(domain=(0,40))),
    y=alt.Y('index:N', axis=None, sort='descending'),
    color=alt.Color('age_m')
)

chart_m | chart_f
```

I would suggest simply playing with the `sort` order of your data. This parameter does dictate the way the data gets plotted.

 Hope it helps.

![visualization](https://user-images.githubusercontent.com/33944811/42672186-fea60566-8629-11e8-8917-7ce5b3bab626.png)

**Comment by hbar137** [comment]
Thank you so much! Your suggestion did the trick! I am still not sure why it works. I will need to study what sorting does.

**Comment by jakevdp** [comment]
Thanks @ruizdurazo - note that we recently merged an example plot similar to this, so this will be better documented in the next release: #1011
