### ISSUE TITLE
set configurations once

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1021]
Hi Jake and all,

Loving Altair and am trying to make a switch over to it from matplotlib when possible.

Is there a way that I can set things like the chart size and other features once at the beginning of an analysis instead of having to use, for example, ".properties(width=200, height=100)"  after every chart? There ends up being a lot of duplication doing that as you could imagine.

I see [here](https://github.com/altair-viz/altair/issues/258) and [here](https://vega.github.io/vega-lite/docs/config.html) that this was addressed but wasn't able to find a clear example of how it can be done in Altair.

I can see [here](https://altair-viz.github.io/user_guide/configuration.html), that I can register a theme, but could I simply add to the default one since I'm mostly just looking to specify colors and size once?

Sincerely,
Al

**Comment by jakevdp** [comment]
The way to set defaults in a chart is to register a custom theme. For example:
```python
import altair as alt

# do this once
def my_theme(*args, **kwargs):
    return {'width': 300, 'height': 300}
alt.themes.register('my-chart', my_theme)
alt.themes.enable('my-chart')

# now every chart will have that theme
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).interactive()
```
![visualization 8](https://user-images.githubusercontent.com/781659/42768626-e39eaaae-88d4-11e8-8433-4420e50a57c0.png)

**Comment by jakevdp** [comment]
Themes can be used to set defaults on any part of the chart specification

**Comment by Alcampopiano** [comment]
This is so awesome. Thanks Jake. Altair is really a refreshing way to do visualization. Thanks for all your hard work.

Allan

**Comment by Alcampopiano** [comment]
I've been working on setting global themes but hit a snag:

@jakevdp Can you think of any reason why I cannot globally set my axis titles? As you can see the plot respects some of the configurations, but not the axis title.

```python
data = pd.DataFrame({
    'a': ['A', 'B', 'C'],
    'b': [28, 55, 43],
    'c': [33, 33, 43]
})

def my_theme(*args, **kwargs):
    return {'config': {'axis': {'domainColor': 'green', 'gridColor': 'red', 'title': 'GLOBAL_TITLE'}}}
                  

alt.themes.register('my_theme', my_theme)
alt.themes.enable('my_theme')

alt.Chart(data).mark_bar().encode(y='b', x='a')
```

![visualization 2](https://user-images.githubusercontent.com/4624246/42919204-cb1cd8aa-8ade-11e8-8ce1-4015ba451781.png)

**Comment by jakevdp** [comment]
Setting title via top-level chart configuration is not supported.

**Comment by jakevdp** [comment]
The ``title`` property of ``config`` should be a mapping of title properties. Themes are more about setting up the style of the chart than the content of the chart.

**Comment by jakevdp** [comment]
You could do something like this if you want:
```python
data = pd.DataFrame({
    'a': ['A', 'B', 'C'],
    'b': [28, 55, 43],
    'c': [33, 33, 43]
})

def my_theme(*args, **kwargs):
    return {'config': {'axis': {'domainColor': 'green', 'gridColor': 'red'}},
            'encoding': {'x': {'axis': {'title': 'my_x_title'}},
                         'y': {'axis': {'title': 'my_y_title'}}}
           }

alt.themes.register('my_theme', my_theme)
alt.themes.enable('my_theme')

alt.Chart(data).mark_bar().encode(y='b', x='a')
```

I'd probably avoid setting encoding properties as part of the theme, though.

**Comment by Alcampopiano** [comment]
This is exactly what I was after. I'm pretty sure I had tried something similar, but probably incorrectly set up the dictionary. 

In my job I have to write very long analytic reports. They usually contain around 50 charts. Pretty well all charts have the same axis labels, color scheme, axis limits, ect. So for me it saves a lot of typing if I can specify a large number set of settings that the charts have in common at the top of the notebook.

Thank you very much Jake,
Al

**Comment by Alcampopiano** [comment]
So, am I just thinking about this all wrong here? In my report, all bars charts should have the same bar width (size). In fact, all charts have many settings in common. I'm using:

```python
def theme_1(*args, **kwargs):
    return {'width': 300, 'height': 300,
            'config': {'mark': {'size': 3}},
            'encoding': {'x': {'axis': {'title': 'options'}},
                         'y': {'axis': {'title': 'percentage of students'}}}}
```
But this does not change the bar size. When looking at the dictionary when `size` is used in the `mark_bar()` method, I see that we get:
```python
...
'mark': {'type': 'bar', 'size': 30}
...
```
But adding the mark 'type' to the theme doesn't work and shouldn't since I'm pretty sure you cant render a chart without eventually using the `mark_bar()` method anyway.

Please let me know if I am just not using the tool correctly. In the past with matplotlib, I had a gigantic dictionary of settings that all charts had in common specified at the top of the notebook. This made the api calls smaller and easier to read. So, I'm looking for a similar sort of set up with Altair.

Thanks Jake,
Al

**Comment by jakevdp** [comment]
Hi – yeah, I don't think this will work because it's not how themes were anticipated to be used.

Perhaps a better approach for you is not a theme, but a custom function you call on charts at the end; e.g.

```python
def finalize_chart(chart):
    chart.x.axis = {'title': 'options'}
    chart.y.axis = {'title': 'percentage of students'}
    chart.mark = {'type': 'bar', 'size': 3)
    return chart
```
and then call that on every chart you create.

**Comment by Alcampopiano** [comment]
Okay great. I will try that.
