### ISSUE TITLE
Plotting density

### ISSUE THREAD

**Issue by apnewberry** [altair-viz/altair#1029]
It'd be awfully nice if I could call `alt.Chart(data).mark_density()` and get a kernel density plot. This would involve calculating some density estimator behind the scenes.

For example, in seaborn, it's `sns.distplot(x, hist=False, rug=True)`:

![](https://seaborn.pydata.org/_images/distributions_12_0.png)

Useful references:
https://seaborn.pydata.org/tutorial/distributions.html#kernel-density-estimation
https://jakevdp.github.io/blog/2013/12/01/kernel-density-estimation/ :smile: 
http://scikit-learn.org/stable/modules/density.html

**Comment by jakevdp** [comment]
Kernel density plots are not supported in Vega-Lite. You can track the feature request here: https://github.com/vega/vega-lite/issues/3442

**Comment by gvikei** [comment]
@jakevdp Now that Vega-Lite has already supported density plots ([https://vega.github.io/vega-lite/docs/density.html]()), is it possible for us to have this feature in Altair as well?

**Comment by jakevdp** [comment]
Yes, see for example https://altair-viz.github.io/user_guide/transform/density.html and https://altair-viz.github.io/gallery/density_facet.html

**Comment by zwanner72** [comment]
Is it possible to generate in altair a horizontal kernel density plot to be used in facetted scatter plot similar to below (where the histograms are replaced by the density plots) ? I was able to create the vertical density plot but not the horizontal one. 

![image](https://user-images.githubusercontent.com/68701241/88304910-dc575500-ccd6-11ea-9e01-af980a3883c5.png)
