### ISSUE TITLE
When summing two charts with identically ordered axis, the order is lost.

### ISSUE THREAD

**Issue by rcalsaverini** [altair-viz/altair#1032]
Hi, 
I'm rather new to the library and this is probably derived from my lack of full understanding of it, but since this behavior is a little bit surprising I wanted to ask if it is expected.

I have two dataframes:
```
import altair as alt
import pandas as pd

laureates = pd.DataFrame({
    'name': ['B', 'D', 'C', 'A'],
    'born': pd.to_datetime(['1900-01-01', '1905-01-01', '1930-01-01', '1960-01-01']),
    'died': pd.to_datetime(['1950-01-01', '1965-01-01', '1970-01-01', '2015-01-01'])
})

prizes = pd.DataFrame({
    'name': ['B', 'B', 'D', 'C', 'A'],
    'date': pd.to_datetime(['1930-01-01', '1935-05-01', '1936-01-01', '1965-01-01', '2000-01-01'])
})
```

![laureates](https://user-images.githubusercontent.com/126856/42888257-3ad2f726-8a7e-11e8-8084-cbe7eb396198.png)

![prizes](https://user-images.githubusercontent.com/126856/42888282-4b073d96-8a7e-11e8-8fb1-fe3d1aaf70be.png)

And I did the following two charts:

```
dots = alt.Chart(prizes.merge(laureates, on='name'))\
    .mark_point(fill='black')\
    .encode(y='date:T', x=alt.X("name:N", sort=["born:T"]))

lines = alt.Chart(laureates)\
    .mark_rule()\
    .encode(y="born:T", y2="died:T", x=alt.X("name:N", sort=["born:T"]))
```

Independently, both graphs render more or less as I intended:
![lines](https://user-images.githubusercontent.com/126856/42888326-661108f6-8a7e-11e8-81c0-a7b387e47822.png)

![dots](https://user-images.githubusercontent.com/126856/42888348-701e9c5a-8a7e-11e8-874b-4926fb60e348.png)

But when I sum them with `lines + dots` the ordering in the x-axis reverts to alphabetical:
![lines + dots](https://user-images.githubusercontent.com/126856/42888366-7b122e88-8a7e-11e8-8a06-de89e8313a6a.png)

Is this expected? If so, how do I keep the original ordering? Or how do I reorder the axis after joining the charts?

**Comment by rcalsaverini** [comment]
Oops, the images are not displaying well here. I'll produce smaller versions as examples.

**Comment by rcalsaverini** [comment]
Hum, thanks. 
I tried your solution adding `(lines + dots).resolve_scale(x='independent')` and it orders it correctly now, but it creates a new x axis on top. Not a problem though.

![image](https://user-images.githubusercontent.com/126856/42888528-d8f849a6-8a7e-11e8-956d-cc44b73ad446.png)

**Comment by jeffbaumes** [comment]
As @jakevdp suggests in #820, you can update one of your `alt.X` specifications to turn off the second axis:

```
alt.X("name:N", sort=["born:T"], axis=alt.Axis(labels=False, ticks=False))
```

**Comment by jakevdp** [comment]
This is a bug in Vega-Lite; see #820 and vega/vega-lite#3710. Closing as a duplicate.
