### ISSUE TITLE
color of bars and text mark on bar chart

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1033]
Hi Jake and all,

Here is an example from the docs where there is text on a bar chart. If I encode the bar mark color to the categorical variable, this forces the text mark to also have these colors, despite selecting a different color in the "mark_text" method.

```
data = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

bars = alt.Chart(data).mark_bar().encode(
    y='a',
    x='b',
    color='a'
)

text = bars.mark_text(
    align='left',
    baseline='middle',
    dx=3,
    color='black'
).encode(
    text='b'
)

bars + text
```
![visualization 7](https://user-images.githubusercontent.com/4624246/42905749-eedfe224-8aa6-11e8-81e3-22b93d15ecfd.png)

If I leave the color option out of both places. Then the bars are blue and the text is black (like in the docs), which makes me think that I can control these colors independently somehow. 

![visualization 8](https://user-images.githubusercontent.com/4624246/42905722-d77bf30c-8aa6-11e8-8a9c-44753035f93c.png)

Using the fill and color options seem to have no effect (if color has been previously encoded for the bars). The stroke option does work, but if the chart is large enough, you can see the inner part of the text still has the colors of the bars.

Is there a way to encode the bar color, but leave the text black or have it set to some other color?

Al

**Comment by jakevdp** [comment]
When you do ``text = bars.mark_text()`` it copies all of ``bars`` and results in ``text`` being a chart that includes every encoding you specified in the bar, including the color. Color encodings take priority over mark properties.

If you don't want text to have a color encoding, then make sure not to include a color encoding. Here's one approach:
```python
base = alt.Chart(data).encode(
    y='a',
    x='b'
)

bars = base.mark_bar().encode(
    color='a'
)

text = base.mark_text(
    align='left',
    baseline='middle',
    dx=3,
).encode(
    text='b',
)

bars + text
```

**Comment by Alcampopiano** [comment]
This is awesome. I see what I was doing wrong. Thanks Jake. I'm slowly learning!
