### ISSUE TITLE
Parallel coordinates with multiple y axes

### ISSUE THREAD

**Issue by jackjackk** [altair-viz/altair#1034]
I would like to plot sth like https://vega.github.io/vega/examples/parallel-coordinates/ with altair.
In issue #382 @jakevdp suggests to use layers for a similar request, but would it be possible to elaborate a bit more on that? Or be redirected to further examples/documentation on how I could reproduce the example above? Thanks.

**Comment by jakevdp** [comment]
Have you seen this example? https://altair-viz.github.io/gallery/parallel_coordinates.html

**Comment by jackjackk** [comment]
Yes, thanks. The main difference is that I would like to have a different scale for each x coordinate, as the variables I want to plot are not necessarily homogeneous (like in the vega example above). It would be great to have an example along these lines, or a hint on how I could change the code of your example.

**Comment by kanitw** [comment]
Yeah that’s not possible of Vega-Lite and we don’t have  plan to support parallel coordinatine any time soon.

**Comment by jackjackk** [comment]
ok, thanks, I've learned vega != vega-lite! So, in matplotlib what I'm doing is normalizing each variable to be in [0,1], plot them like in the altair example, and then add x-labels below and above the plot (using also a secondary x-axis) to show the actual min and max range. How would this labelling work in altair? Thanks.

**Comment by kanitw** [comment]
I think you can use text marks to show min - max for each axis

**Comment by jackjackk** [comment]
Thanks. With a bit of normalizing I got a result close to what desired. (see https://github.com/jackjackk/altair-parallel-coordinates/blob/master/altair-parallel-coordinates.ipynb ) Could you point me where I could find help on 1) renaming the colorbar tick labels 2) hiding the default y-tick labels 3) attempting some interactive brushing of the lines (e.g. focusing on a certain range of values for a certain variables) ?

**Comment by sotte** [comment]
Nice solution @jackjackk!

The problem when normalizing the data is that the data is actually changed, and using the hover tool would show the wrong/normalized data. Is there really no other solution? It's quite common (the default case maybe?) to have variables with different scales. Could be build a transformer for this?

**Comment by domoritz** [comment]
@kanitw made a chart recently: https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4yghSBXATgGxSjkQHoBLHMgZwDoArKgewDtJwwBfAGncgHcy0eAAtCANgAMEnpmEBTMgHNh8QgGYpMqPByxmVAGaMcAW0IBtdhGD8yzaIz4WbjAA6FIAY0ZZmqrlCwVB520HIAHpAcALrcYFZokEZ40BaQrnKIeAAycsyKIpAB6ZmweADqgoXFVHKuZbn51VC19RVVorFa1gmYAvaOFr0YLu6okCZ2RVAGZHIpHgBuZVhy05BBHpOs3MPWkG5bsJHFs-Op48t4q+ub4ybHUcPRAfEYGEm6Jmuo5sxYeDwAX+gJeb3eUEUOB8rgARgBPNIAazkiOi4Igu3e6AhXjKngBCB+UAAFMQsCYaFdVmAALRgcmU7YASjAJDAZIQFJoD3CtMZPLszKKww2wXGzGMJgA+lc2O84glgBiPp58YT4MTIJz4NztmAANQMrlM46s9kAJhFEMC4qgk1SCQ44JevDwsHhchwzgSE1gOCRhBs8HhGQ8OABa2K3jwxg8AGJPEn1vBGIw8PAyGMwCC8FiPnlvNA7Iog6KwogyARUDZYIooXJFESPN5fP5tKGtQBHLB6TOITOLNb596QSI1yAhsMSxjbMrrM4LcYoxEcJ3sOI4zC1PByTyZlhlm2QYSMIfe5DKyedjxUEu7hdzJdQUIRdaH+4+Wpnr3rOQmVwQw8SVmGHJ1untf1A3GPA7CjX1C0YYt8iPXEYzjGs9igbx7DIA9WAnHc93wjxT3PFMbxnOcCFOJ8LhaDJPDmYIR1xaktQbRFhlYzAK1gKsg2vacoElajH3OEJ7DfHioDcWAmKAzCbUwHDixIwj5mIsgPygMjf2KdjCAkGgAHZFWUqBDNQYy1G4iDMHHRIpy1US7HnWiJOXVEonsqBEQnZyPB7Ps8IQMgh3E59IElUxZXcwJwmoQhcxkyc0wzLMfQspI6I8DIskaApRDstAsJyzyoHyspKiEYqbU3MrF3oyBWgaPIivlCEGuyprbzqaqOk6hVonXTFXRUlhZlLJSPmOagAA1BIcB4plQAwylqYp3VheYAEF8gfazikzTwkQAYXTDCoETZNjrww6wHWvBalYyBFjmJxCJ0RgUWSgE8wglqQwercPm2+ZBNhIJ5jgrZBGgB9ijKJQCKgShlHbGBHNpABWY70szbMUt8ycyFOwTjDmPxSMpgAvFgshTAnMtQFLRs4EAOCAA

```json
{
  "data": {
    "url": "data/iris.json"
  },
  "width": 600,
  "height": 300,
  "transform": [
    {"window": [{"op": "count", "as": "index"}]}, 
    {"fold": ["petalLength", "petalWidth", "sepalLength", "sepalWidth"]},
    {
      "window": [
        {"op": "min", "field": "value", "as": "min"},
        {"op": "max", "field": "value", "as": "max"}
      ],  
      "frame": [null, null], 
      "groupby": ["key"] 
    },
    {
      "calculate": "(datum.value - datum.min) / (datum.max-datum.min)",
      "as": "norm_val"
    }, 
    { 
      "calculate": "(datum.min + datum.max) / 2",
      "as": "mid"
    } 
  ],
  "layer": [{
    "mark": {"type": "rule", "color": "#ccc", "tooltip": null},
    "encoding": {
      "detail": {"aggregate": "count", "type": "quantitative"},
      "x": {"type": "nominal", "field": "key"}
    }
  }, {
    "selection": {
      "hover":{ "type": "single", "field": "index", "on": "mouseover", "empty": "none"}
    },
    "mark": "line",
    "encoding": {
      "color": {
        "condition": {"selection": "hover", "type": "nominal", "field": "species"},
        "value": "grey"
      },
      "detail": {"type": "nominal", "field": "index"},
      "opacity": {
        "condition": {"selection": "hover", "value": 0.7}, 
        "value": 0.3
      },
      "x": {"type": "nominal", "field": "key"},
      "y": {"type": "quantitative", "field": "norm_val", "axis": null},
      "tooltip": [{
        "field": "petalLength"
      }, {
        "field": "petalWidth"
      }, {
        "field": "sepalLength"
      }, {
        "field": "sepalWidth"
      }]
    }
  }],
  "config": {
    "axisX": {"domain": false, "labelAngle": 0, "tickColor": "#ccc", "title": false},
    "view": {"stroke": null},
    "style": {
      "label": {"baseline": "middle", "align": "right", "dx": -5, "tooltip": null},
      "tick": {"orient": "horizontal", "tooltip": null}
    }
  }
}
```

**Comment by kanitw** [comment]
This is the improved version of the plot: https://stackoverflow.com/a/54701776/866989.
