### ISSUE TITLE
No 'datum' object defined for Chart.transform_filter() with Chart.mark_geoshape()

### ISSUE THREAD

**Issue by manzt** [altair-viz/altair#1038]
I tried to generate a geo-projection after filtering out Antarctica from an altair topo feature. However, it appears `datum` is not defined for the code below. I am able to specify the field `"id"` and filter using `alt.FieldEqualPredicate()`, but this has the opposite effect.

```python
import altair as alt
from vega_datasets import data

countries = alt.topo_feature(data.world_110m.url, 'countries')

alt.Chart(countries).mark_geoshape(
    stroke='black'
).transform_filter(
    datum.id != 10
).properties(
    width=800,
    height=700
)
```

**Comment by jakevdp** [comment]
Try
```
from altair import datum
```
or alternatively use
```
chart.transform_filter(
    alt.datum.id != 10
)
```

**Comment by manzt** [comment]
Perfect. Thank you!
