### ISSUE TITLE
Hiding Out[1] when chart renders

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1039]
Hi Jake and all,

This may be a JupyterLab question and I'm happy to post over there if need be. 
When I render a chart in Altair I get "Out[1]" printed in the margin. When I use matplotlib, I do not see this.

Do you know a way to get rid of the "Out[1]" ? It makes the final report a bit confusing for my audience.

### Altair example
![alt](https://user-images.githubusercontent.com/4624246/43144656-a91db8cc-8f2b-11e8-90e3-17badcbd565a.png)
### matplotlib example (just an empty plot)
![plt](https://user-images.githubusercontent.com/4624246/43144651-a70876c6-8f2b-11e8-9aec-55c6db3da690.png)

**Comment by Alcampopiano** [comment]
Oh interesting. iPython's `display` seems to work to get rid of the `Out[1]`. Perhaps there is a better way, but this is fine.

```python
from IPython.core.display import display
.
.
.
display(chart)
````

**Comment by jakevdp** [comment]
Glad you figured it out! Note that in the most recent version of Altair, you can use ``chart.display()`` to avoid the extra import (this also lets you display multiple charts in one cell).

**Comment by Alcampopiano** [comment]
Beautiful!
