### ISSUE TITLE
Move selenium/headless rendering to separate package

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#1042]
I think this would make things cleaner, and also be a place to implement features like #1023 / #1025

**Comment by pratapvardhan** [comment]
Any thoughts on using [puppeteer ](https://github.com/GoogleChrome/puppeteer) over selenium? Also, if there could be easier way to ship `vg2png` over selenium.

**Comment by jakevdp** [comment]
In Altair 1.x we used npm-based vg2png & similar tools for programmatic figure export, but it led to huge headaches because of how difficult it is to get npm and python to play together well (in particular, one of the dependencies of vega on npm requires Python 2.7, so you needed to have multiple python environments talking to each other in order to save figures in Python 3... total nightmare)

Selenium has been a huge improvement, because it's conda installable.

I don't know much about puppeteer, but moving the selenium-specific code to a separate package & allowing Altair to access it as a plugin will potentially pave the way for a puppeteer-based plugin as well.

**Comment by SyntaxRules** [comment]
FYI, in work at: https://github.com/SyntaxRules/vega-save

I've been able to pull out the png/svg code and reproduce saving as it is in altair. There are a few more things before its ready for prime time. I have a few questions for this audience:

1. Do you want to move `*.html` creation or serving to another package as well?
2. Would it be preferable to include `*.jpeg` in here as well?
3. Whats the best way to document/handle the 'chromedriver.exe`/`gekodriver` dependecy? (@gwdekker suggested using the `chromedriver_installer` pip package.

**Comment by SyntaxRules** [comment]
See also: https://github.com/altair-viz/altair/issues/1010, progress update over there.
