### ISSUE TITLE
generate inset plots?

### ISSUE THREAD

**Issue by pagpires** [altair-viz/altair#1045]
Hi, is it possible to generate inset plots using Altair (different-size plots overlapped with each other, something like [this](https://stackoverflow.com/questions/45868861/aligning-inset-plots-in-gnuplot))?please let me know if I missed the doc/resource. If no, is it possible to do it with Vega, or we have to go by using D3?  Thanks in advance!

**Comment by jakevdp** [comment]
I'm not aware of any way to do this in Altair or Vega-Lite. You might ask on Vega forums for ideas.

**Comment by pagpires** [comment]
OK! Thanks a lot!
