### ISSUE TITLE
Cross filter a chart with another chart

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1047]
Hi Jake,

Wondering if you can give me a nudge in the right direction here. Very similar to the [IMDB cross filter example in the gallery](https://altair-viz.github.io/gallery/interactive_cross_highlight.html), I'm trying to click a mark on one chart, in order to show corresponding counts in another chart.

Here is an almost working example but as you can see the dot chart does not filter the categories and counts on the bar chart:

```python
df=pd.DataFrame({'id': range(0, 1000), 'school': np.random.randint(9, size=1000), 'university': np.random.randint(25, size=1000), 'program': np.random.randint(15, size=1000)})

selector = alt.selection_multi()

a=alt.Chart(df).mark_circle().encode(
    y='university:N',
    x='school:N',
    size='count(id)',
    color=alt.condition(selector, 'school:N', alt.ColorValue("grey"))
).properties(width=800, height=500, selection=selector)

b=alt.Chart(df).mark_bar().encode(
    y='count(id)',
    x='program:N',
    color=alt.value('lightgray')
).properties(width=500, height=400).transform_filter(selector)

a|b
```
Any help would be much appreciated.

Al

**Comment by Alcampopiano** [comment]
...wait! I think `selector = alt.selection_multi( encodings=['x', 'y'])` did the trick!

**Comment by jakevdp** [comment]
Yep, that's it. Alternatively you could use ``alt.selection_multi(fields=['school', 'university'])``

It would be nice to have something along these lines in the documentation... choosing the encodings or fields that a selection targets is pretty useful, but I'm not certain we mention it anywhere.

**Comment by Alcampopiano** [comment]
This is such an amazing tool. It really feels nearly effortless to make charts.
