### ISSUE TITLE
datetime casting interpreted as aggregation in shorthand  

### ISSUE THREAD

**Issue by iliatimofeev** [altair-viz/altair#1048]
~~~python
df = pd.DataFrame([  {'value': 0, 'date': '2018-02-01 11:00'},
                     {'value': 5, 'date': '2018-02-01 23:00'},
                     {'value': 10, 'date': '2018-02-02 11:00'},
                     {'value': 15, 'date': '2018-02-02 23:00'},
                     {'value': 20, 'date': '2018-02-03 11:00'},
                     {'value': 25, 'date': '2018-02-03 23:00'}])
alt.Chart(df
).mark_bar(
).encode(
    y ='mean(value)',
    x ='day(date)'
)
~~~
![visualization 22](https://user-images.githubusercontent.com/11561581/43314497-c5370384-919b-11e8-8f3f-661d2dee5d83.png)

expected:

![visualization 23](https://user-images.githubusercontent.com/11561581/43314937-2602aafa-919d-11e8-9ee9-d7c3c65b563e.png)

as 
~~~python

alt.Chart(df
).mark_bar(
).encode(
    y ='sum(value)',
    x = alt.X('date',timeUnit='day')
)
~~~

morethen 
~~~python
df['date'] = pd.to_datetime(df.date)
alt.Chart(df
).mark_bar(
).encode(
    y ='sum(value)',
    x = alt.X('date',timeUnit='day')
)
~~~
![visualization 22](https://user-images.githubusercontent.com/11561581/43314497-c5370384-919b-11e8-8f3f-661d2dee5d83.png)

**Comment by jakevdp** [comment]
When you don't specify a type, Altair sees the datetime column and infers that you want the x-axis to be temporal. The output you want is an ordinal, which you can specify explicitly:
```python
df = pd.DataFrame([  {'value': 0, 'date': '2018-02-01 11:00'},
                     {'value': 5, 'date': '2018-02-01 23:00'},
                     {'value': 10, 'date': '2018-02-02 11:00'},
                     {'value': 15, 'date': '2018-02-02 23:00'},
                     {'value': 20, 'date': '2018-02-03 11:00'},
                     {'value': 25, 'date': '2018-02-03 23:00'}])
alt.Chart(df
).mark_bar(
).encode(
    y ='mean(value):Q',
    x ='day(date):O'
)
```
![visualization 19](https://user-images.githubusercontent.com/781659/43335514-406efa56-9184-11e8-804e-cf4f087500c2.png)

**Comment by iliatimofeev** [comment]
for `count()` it change type, but not for `day()` or and other timeUnit shorthand. It is strange.

**Comment by jakevdp** [comment]
Yeah, I was trying to be smart when inferring types... quantitative is a useful default for counts, and temporal is a useful default for timeUnits.

As always, the defaults are only best guesses at what the user intends, and I would encourage you to get in the habit of specifying your types explicitly.
