### ISSUE TITLE
Unable to use interval selection on all points of a line chart

### ISSUE THREAD

**Issue by ZachEd96** [altair-viz/altair#1049]
I'm having an issue creating a parallel coordinate chart that uses an interval selection brush to highlight lines on the chart. The brush only works correctly when highlighting the points for the first element on the x-axis, it doesn't highlight lines when selecting any other point on the line. 

![full_selection_interval_line_chart_example](https://user-images.githubusercontent.com/7441898/43322156-5d39f802-919d-11e8-9e10-80ec4d82339f.png)
![first_point_selection_interval_line_chart_example](https://user-images.githubusercontent.com/7441898/43322164-61807e4a-919d-11e8-93bf-072371307439.png)
![second_point_selection_interval_line_chart_example](https://user-images.githubusercontent.com/7441898/43322171-63139ac6-919d-11e8-8c8e-607ed8d730fd.png)

I'm also struggling to make the text elements 'belong' to the line, so that when highlighting a line all text elements that belong to the line remain. I've layered two charts in this case but ideally I would use text encoding on the line chart but I can't get that to work.

```
    brush = alt.selection_interval()
    
    pCoord = alt.Chart(mergedDF[mergedDF['Procedure_Step'] == mergedDF['Variable']]).mark_line().encode(
        x=alt.X('Procedure_Step:O', sort=alt.SortField(op='sum',field='Sort_Order',order='ascending'), axis=alt.Axis(grid=True)),
        y=alt.Y('Normalised_Val:Q', axis=alt.Axis(grid=False, labels=False, domain=False, ticks=False), scale=alt.Scale(domain=[0,1])),
        detail='Identifier:N',
        opacity = alt.value(0.3),
        color=alt.condition(brush, if_true=alt.value('#005EB8'), if_false=alt.value('lightgray'))
    ).properties(
        height=750,width=1000
    ).add_selection(
        brush
    )
    
    axisText = alt.Chart(mergedDF[mergedDF['Procedure_Step'] == mergedDF['Variable']].drop_duplicates(['Variable','Procedure_Code'])).mark_text().encode(
        x=alt.X('Procedure_Step:O',sort=procSortList, axis=alt.Axis(grid=False, labels=False, domain=False, ticks=False, title='')),
        y=alt.Y('Normalised_Val:Q'),
        detail = 'Identifier:N',
        text=alt.condition(brush,alt.value('ex.'),alt.value(''))
    ).properties(
        height=750,width=1000
    )
    
    display(alt.layer(pCoord,axisText).resolve_scale(x='independent'))
```

**Comment by jakevdp** [comment]
Can you provide data that lets me reproduce your chart?

**Comment by jakevdp** [comment]
Even if it's not "real" data, a toy dataset that illustrates the problem would make it much easier for me to help you.

**Comment by ZachEd96** [comment]
```
import pandas as pd
import numpy as np
import altair as alt

rows = {}
normalisedValues ={}
procedureSteps = ['A','B','C']
stepOrder = pd.DataFrame({'Step':procedureSteps, 'Order':[1,2,3]})
for x in range(1,201):
    rows[x] = [np.random.randint(1,15),np.random.randint(1,10),np.random.randint(1,6)]

df = pd.DataFrame(rows).T
df.columns = procedureSteps

for step in procedureSteps:
    size = df[step].max()
    for ind, row in df[step].iteritems():
        normalisedValues[(step, ind)] = row/(size + 1)

procDF = pd.DataFrame(pd.Series(normalisedValues).reset_index())
procDF.columns = ['Step', 'ID', 'Normalised_Val']
procDF = procDF.merge(stepOrder, how='left', on='Step')
df = df.reset_index().rename(columns={'index':'ID'})
meltedDF = df.melt(id_vars=['ID'],var_name='Step')
procDF = procDF.merge(meltedDF, how='left', on=['ID','Step'])

brush = alt.selection_interval()

pCoord = alt.Chart(procDF).mark_line().encode(
    x=alt.X('Step:O', axis=alt.Axis(grid=True)),
    y=alt.Y('Normalised_Val:Q', axis=alt.Axis(grid=False, labels=False, domain=False, ticks=False), scale=alt.Scale(domain=[0,1])),
    detail='ID:N',
    opacity = alt.value(0.3),
    color=alt.condition(brush, if_true=alt.value('#005EB8'), if_false=alt.value('lightgray'))
).properties(
    height=750,width=1000
).add_selection(
    brush
)

axisText = alt.Chart(procDF.drop_duplicates(['Step','value'])).mark_text().encode(
    x=alt.X('Step:O', axis=alt.Axis(grid=False, labels=False, domain=False, ticks=False, title='')),
    y=alt.Y('Normalised_Val:Q'),
    detail = 'ID:N',
    text=alt.condition(brush,'value:N',alt.value(''))
).properties(
    height=750,width=1000
)

alt.layer(pCoord,axisText).resolve_scale(x='independent')
```

That will generate a similar output with dummy data created in a similar sort of way to how I transformed the data for the original chart.

I've moved to another PC now, and in this example the brush isn't highlighting the line when selecting any of the points (but I'm not sure why).

If this helps your understanding at all - the visualisation is looking at patient flows, and in what order they have procedures. 'ID' in this example would be patients, 'Steps' is procedure order and the 'value' column is the procedure ID. I've enumerated and normalised the procedure IDs so they can all fit on one y-axis.

**Comment by jakevdp** [comment]
What is the desired behavior? You want lines to be included in the selection when the brush touches part of them?

**Comment by ZachEd96** [comment]
Any selected point (procedure) on a step's y-axis should show all lines connected to that procedure. So highlighting a procedure in step B should show all the lines that are connected to that procedure between step B and A, and step B and C.

For the text elements, the procedure's text on any lines that have been highlighted should show up regardless of the step they were selected from.

So in the 2nd picture in my initial post, all the lines highlighted would also have their text items shown. And in the 3rd picture, all the lines attached to the selected point would be highlighted (and have their text shown).

The desired line selection behaviour seems like a feature that should exist and be working with the current code, but the text elements definitely need a different set-up to display the desired behaviour.

**Comment by jakevdp** [comment]
Ah, I see.

You cannot do that as written. In particular, because you are manipulating the data in Pandas before passing it to your chart, Altair treats them as two distinct datasets, and so a signal that triggers on one dataset cannot be propagated to the other dataset.

If you want signals to pass between these two views of your data, you'll have to use Altair's built-in [data transformations](https://altair-viz.github.io/user_guide/transform.html#data-transformations) on a single data source, or provide a [lookup transform](https://altair-viz.github.io/user_guide/transform.html#lookup-transform) to tell Altair how to map between two data sources. Once that's working, we can talk about propagating selections between the different data views.

**Comment by ZachEd96** [comment]
The two charts can use a single data source without manipulation by dropping 'remove_duplicates'  - the only issue is that the text gets darker the more data points have the value. Removing duplicates was just a way to ensure a consistent appearance of text marks, but if there's another way to do that I'm all ears.
I've done that and added a transform_filter field using the selection as the filter and it's still not producing the desired output. I've also removed the 'resolve_scale' from the layer chart to let the filter work properly, but I can't guarantee that this will work on my original data source as it won't sort properly due to this issue #820.

```
brush = alt.selection_interval()

pCoord = alt.Chart(procDF).mark_line().encode(
    x=alt.X('Step:O', axis=alt.Axis(grid=True)),
    y=alt.Y('Normalised_Val:Q', axis=alt.Axis(grid=False, labels=False, domain=False, ticks=False), scale=alt.Scale(domain=[0,1])),
    detail='ID:N',
    opacity = alt.value(0.3),
    color=alt.condition(brush, if_true=alt.value('#005EB8'), if_false=alt.value('lightgray'))
).properties(
    height=750,width=1000
).add_selection(
    brush
)

axisText = alt.Chart(procDF).mark_text().encode(
    x=alt.X('Step:O'),
    y=alt.Y('Normalised_Val:Q'),
    detail = 'ID:N',
    text='value:N'
).properties(
    height=750,width=1000
).transform_filter(
    brush
)

alt.layer(pCoord,axisText)
```
![altair select interval ex](https://user-images.githubusercontent.com/7441898/43345304-d72d5126-91e4-11e8-8bda-9c50e8e9a55c.png)

I still can't work out why the line has to be selected from what altair determines is the 'point of origin' (step C in this instance) for the data and not from any point along the line.

**Comment by jakevdp** [comment]
Do you want to be able to select the text and have it highlight everything with the same ID?

**Comment by jakevdp** [comment]
Or do you want to be able to select the lines?

**Comment by ZachEd96** [comment]
Preferably select lines as opposed to the text itself, sort of like this: http://mbostock.github.io/d3/talk/20111116/iris-parallel.html but with no need for multi-selection.

**Comment by jakevdp** [comment]
I don't think you can generally select lines using an interval selection, but you could do something based on hover, like this:
```python
hover = alt.selection_single(fields=['ID'], on='mouseover', empty='none')

pCoord = alt.Chart(procDF).mark_line().encode(
    x=alt.X('Step:O', axis=alt.Axis(grid=True)),
    y=alt.Y('Normalised_Val:Q', axis=alt.Axis(grid=False, labels=False, domain=False, ticks=False), scale=alt.Scale(domain=[0,1])),
    detail='ID:N',
    opacity = alt.value(0.3),
    color=alt.condition(hover, if_true=alt.value('#005EB8'), if_false=alt.value('lightgray')),
    size=alt.condition(hover, alt.value(5), alt.value(3))
).properties(
    height=750,width=1000
).add_selection(
    hover
)

axisText = alt.Chart(procDF).mark_text().encode(
    x=alt.X('Step:O'),
    y=alt.Y('Normalised_Val:Q'),
    text='min(value):N'
).properties(
    height=750,width=1000
).transform_filter(
    hover
)

alt.layer(pCoord,axisText)
```

**Comment by ZachEd96** [comment]
I don't quite think that will provide the functionality I wanted though - you wouldn't be able to select a group of similar procedures with just a mouse over as it's stuck at one line or set of lines from one point.

I don't need the interval selection to work on the lines themselves, just to be able to select a point or set of points for any given step and highlight all lines attached to the point(s). If it works like that for the start point of the line but not the other points along the line then that must be a deficiency of vega-lite right?

**Comment by jakevdp** [comment]
Yeah, I think what you want is for the interval selection to propagate on the ``"ID"`` field, and I'm not sure if that's possible in Vega-Lite.

That is, you would want to have something like
```python
brush = alt.selection_interval(fields=['ID'])
```
but that leads to an error in the renderer.

Maybe @kanitw or @domoritz would have ideas about how to proceed?

**Comment by domoritz** [comment]
@arvind is the selections guru.

**Comment by amitkaps** [comment]
`interval` selection can be projected over `encodings` not `fields`. You will need to use layering to achieve what you are trying to do...

https://vega.github.io/vega-lite/docs/project.html#current-limitations

**Comment by arberas96** [comment]
Related to this issue, I'm having problems to insert a brush into a nx_altair visualization. I want to select a node with the brush and all the edges that are connected with that node to be colored.

Instead of that, what I obtain is a similar result as it is presented at the top of this issue: the edges are colored only if the selected node is taken by altair as the 'source node'. 

![Foto_1](https://user-images.githubusercontent.com/57488186/82437070-11f17f00-9a97-11ea-9183-f731d22b4f68.png)

I've tried solving it by using layering as @amitkaps has suggested, but I'm not able to solve it properly. I get a different result which is that the edges only get colored if they are completely seleccted by the brush.

![Foto_2](https://user-images.githubusercontent.com/57488186/82437447-ae1b8600-9a97-11ea-8074-05d8a189496c.png)

The code has been taken from nx_altair and I've modified it only to show my main problem. The code below corresponds to the sencond explained case (the layered case).

```bash
# Generate a random graph
H = nx.fast_gnp_random_graph(n=7, p=0.5)

# Compute positions for viz.
pos = nx.kamada_kawai_layout(H,weight='distance')

# Add attributes to each node.
for n in H.nodes():
  H.nodes[n]['name'] = n
    

# Add attributes to edge.    
for e in H.edges():
    H.edges[(e[0],e[1])]['M'] = random.uniform(0, 1)
```

```bash
df_edges = to_pandas_edges(H, pos)

brush = alt.selection_interval(empty='none')

edge_base = alt.Chart(df_edges).properties(
    width=300,
    height=300).mark_line(size=5).encode(
        alt.X('x'),
        alt.Y('y'),
        detail='edge')

edge_color = edge_base.encode(
        color=alt.condition(brush, alt.Color('M',
            scale=alt.Scale(scheme='yelloworangered'),type='quantitative'),alt.value('lightgray'))
    ).add_selection(brush).transform_filter(brush)

edge_grey=edge_base.encode(
    color=alt.value('lightgray'))

viz=[]
viz.append(edge_grey)
viz.append(edge_color)
total=alt.layer(*viz)
```
