### ISSUE TITLE
Chart.save() to variable with JSON

### ISSUE THREAD

**Issue by jploudre** [altair-viz/altair#1052]
In Chart.Save, it says that data could be saved to a file-like object. Is there a way to save to a variable without saving to disk (planning on embedding the JSON into an HTML file. Searching about file-like objects isn't really making sense to me.

**Comment by jakevdp** [comment]
You can use ``chart.to_json()``

**Comment by jakevdp** [comment]
I added a note about this in the docs in 1d4b880
