### ISSUE TITLE
How to jitter x-values while maintaining categorical axis like seaborn swarmplot?

### ISSUE THREAD

**Issue by breadbaron** [altair-viz/altair#1057]
Is it possible to make a seaborn-style 'swarmplot' in Altair? I like being able to see all points for a given category, but I'm not sure how to vary the axis values without losing the categorical labeling.  

The stripplot documented here is close, but I'd like to vary the categorical axis values just enough so that points don't overlap:
https://altair-viz.github.io/gallery/strip_plot.html

https://seaborn.pydata.org/generated/seaborn.swarmplot.html

**Comment by jakevdp** [comment]
No, that's not yet supported in Altair/Vega-Lite. There is some discussion of adding this feature at https://github.com/vega/vega-lite/issues/396

**Comment by jakevdp** [comment]
While not yet fully supported by the vega-lite grammar, you can do something like this with calculate transforms. An example was recently submitted for the gallery here: https://github.com/altair-viz/altair/blob/master/altair/examples/stripplot.py

**Comment by markusschanta** [comment]
> While not yet fully supported by the vega-lite grammar, you can do something like this with calculate transforms. An example was recently submitted for the gallery here: https://github.com/altair-viz/altair/blob/master/altair/examples/stripplot.py

The example cited above seems to have moved. Looks like this is the [new URL](https://altair-viz.github.io/gallery/strip_plot_jitter.html).
