### ISSUE TITLE
Angle not an encoding?

### ISSUE THREAD

**Issue by ryanpeach** [altair-viz/altair#1061]
In Vega, angle can be used with a field to have dynamic angles. This is something I require for a project where we are drawing rectangles of various heights, widths, and angles on the canvas. So far I can only find angle in altair at the mark level, which only allows a constant number. Any advice?

**Comment by kanitw** [comment]
> In Vega, angle can be used with a field to have dynamic angles

According to the documentation, Vega doesn't support angle for [rect marks](https://vega.github.io/vega/docs/marks/rect/). 


In any case, we haven't implemented `angle` encoding in Vega-Lite (and Altair) for supported marks yet.

**Comment by ryanpeach** [comment]
Ok, I'm fine with Text then, maybe just a hyphen character. Any way I can modify the underlying object?

**Comment by ryanpeach** [comment]
Oh, I know, I can use a line with different sizes, and then use the x and y endpoints of the line to control length!
