### ISSUE TITLE
Request: Non-rectangular selections

### ISSUE THREAD

**Issue by HectorM14** [altair-viz/altair#1064]
Is it possible to use non-rectangular selections (like the [lasso in bokeh](https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#lassoselecttool))? 
This would only be possible on scatter-like plots. Not the histograms etc. 
Looking at the Vega-Lite [Selection Transformations](https://vega.github.io/vega-lite/docs/selection.html#selection-transformations) API, this doesn't currently exist. This would be a great feature, but maybe needs to happen on Vega-Lite first.

**Comment by jakevdp** [comment]
I'd suggest requesting this feature in Vega-Lite – Altair has no control over what selections are available.
