### ISSUE TITLE
label of tooltip is "count_*"

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1065]
Hi Jake,

I have a chart that uses `count()` as the tooltip and I was happy to see that this worked perfectly giving the counts. However the label given is `count_*` which is a bit unappealing and confusing to the readers as the asterix can mean something else to them.

Any idea how to rename rid of this?

Here is an example just for the sake of showing something concrete:
```python
import altair as alt
from vega_datasets import data

stocks = data.stocks()

alt.Chart(stocks).mark_line().encode(
    x='date',
    y='price',
    color=alt.Color('symbol', sort=['GOOG']),\
    tooltip=['symbol', 'count()']
)
```

**Comment by jakevdp** [comment]
You can use the ``title`` attribute of the tooltip encoding to change the name to whatever you would like. For example:
```python
import altair as alt
from vega_datasets import data

stocks = data.stocks()

alt.Chart(stocks).mark_line().encode(
    x='date',
    y='price',
    color=alt.Color('symbol', sort=['GOOG']),\
    tooltip=['symbol', alt.Tooltip('count()', title='count')]
)
```

**Comment by jakevdp** [comment]
As an alternative, if you are using the count in several places throughout the chart, you can compute it once within an aggregate transform and refer to it by name elsewhere:
```python
import altair as alt
from vega_datasets import data

stocks = data.stocks()

alt.Chart(stocks).transform_aggregate(
    count='count()',
    groupby=['date', 'price', 'symbol']
).mark_line().encode(
    x='date',
    y='price',
    color=alt.Color('symbol', sort=['GOOG']),\
    tooltip=['symbol:N', 'count:Q']
)
```

**Comment by Alcampopiano** [comment]
So awesome. Thanks very much!
