### ISSUE TITLE
Reverse/invert color scheme

### ISSUE THREAD

**Issue by semiamaurotic** [altair-viz/altair#1068]
I'd like to use the `spectral` color scheme for a heat map I'm working on, but I need to invert the color scheme to more intuitively match my data. (I'm plotting temperature data, and the `spectral` scheme defaults to red=low, blue/purple=high.) Is there a way in Altair to reverse/invert the color scheme?

I've tried adding `reverse=True` to `alt.SchemeParams()` based on a note under "Scheme Properties" in the [Vega docs](https://vega.github.io/vega/docs/schemes/), but apparently this feature isn't supported by Vega-Lite.

The relevant part of my code looks basically like this:
```python
chart = alt.Chart(data).mark_rect().encode(
    ... , 
    color=alt.Color('mean(temperature):Q',
                    scale=alt.Scale(domain=[lower_bound, upper_bound],
                                    clamp=True,
                                    scheme=alt.SchemeParams(name='spectral', reverse=True))))
```

**Comment by jakevdp** [comment]
There is no ``reverse`` property in ``SchemeParams``, so this will not work (the reverse argument you linked to is in the Vega docs, not the Vega-Lite docs, and Altair is built on Vega-Lite).

In your case, the easiest way to reverse the color scale is to reverse the domain: e.g. ``domain=[upper_bound, lower_bound]``.

It seems, though, that allowing SchemeParams to have a ``reverse`` argument that is propagated down to the Vega argument by the same name would be a useful enhancement to Vega-Lite.

**Comment by domoritz** [comment]
Instead of reversing the scheme, you can sort the color encoding. Add `"sort": "descending"`.

**Comment by kanitw** [comment]
This feels like a bug though. We should take a look.

**Comment by semiamaurotic** [comment]
Thank you for the help! Both approaches inverted the color scheme, but I went with the `"sort": "descending"` approach because I preferred its the legend. (The `"sort": "descending"` approach produces a legend with the highest values at the top, whereas swapping the high and low domain values puts the high value at the bottom of the legend.)

![heat map legends](https://user-images.githubusercontent.com/13118282/43659417-fad0322a-9729-11e8-88be-78d42b6e4eee.png)

**Comment by loganpowell** [comment]
> Instead of reversing the scheme, you can sort the color encoding. Add "sort": "descending".
Thank you @domoritz!

**Comment by caleb-lindgren** [comment]
For anyone coming to this with the same problem, but couldn't get the solution above to work. However, I think you can get the same effect by passing `reverse=True` in an alt.Scale object to the alt.Color's `scale` parameter:

```
import altair as alt
import numpy as np
import pandas as pd

# Compute x^2 + y^2 across a 2D grid
x, y = np.meshgrid(range(-5, 5), range(-5, 5))
z = x ** 2 - y ** 2

# Convert this grid to columnar data expected by Altair
source = pd.DataFrame({'x': x.ravel(),
                     'y': y.ravel(),
                     'z': z.ravel()})

alt.Chart(source).mark_rect().encode(
    x='x:O',
    y='y:O',
    color=alt.Color(
        "z:Q",
        scale=alt.Scale(
            scheme="redblue",
            reverse=True
        )
    )
)
```
![image](https://user-images.githubusercontent.com/47534910/108917759-78d73200-75ed-11eb-9452-525a81c999c6.png)

**Comment by firasm** [comment]
Thanks @caleb-lindgren ! This helped me today :-)
