### ISSUE TITLE
Alter legend to  10 rows per labels (Legend Customization)

### ISSUE THREAD

**Issue by smitpate08** [altair-viz/altair#1070]
Hi Jake, 

Great library!  Currently I am working on trying to get 10 labels per column in legend. I was curious if I can do that ? right now I have more than 50 labels in legend and all of them are displaying one after another. I would like to arrange legend labels such that there are 10 labels per column. The Other 10 can go on next column and so on. My code looks like below:

```
alt.Chart(df).mark_line().encode(
y='Total:Q'
,x='Year:N'
,color=alt.Color('County', legend=alt.Legend(title="County"))).properties(width=820)

```
**Legend look like following:**
![image](https://user-images.githubusercontent.com/29586703/43750345-fbd96a6c-99c5-11e8-934b-c725d2d417d7.png)

What I am looking for is "Erie" should start from new column followed by 10 names,then next 10 to new column and so on.

Thanks  in advance for your time and efforts.

**Comment by jakevdp** [comment]
As far as I know, there is no way to make a multi-column legend in vega-lite.

In any case, with this many entries, the viewer probably cannot map plot colors to legend values in any meaningful way, so I don't think this legend would be all that useful even with multiple columns.

I would suggest hiding the legend and instead using a tooltip to communicate this information to the user when they hover over a point; for example:

```python
alt.Chart(df).mark_line().encode(
    y='Total:Q',
    x='Year:N',
    color=alt.Color('County', legend=None),
    tooltip='County'
).properties(width=820)
```

**Comment by smitpate08** [comment]
Great. Thanks!

**Comment by jakevdp** [comment]
The legend now supports a ``columns`` attribute. For example:
```python
import altair as alt
from vega_datasets import data

alt.Chart(data.cars()).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color=alt.Color('Name', legend=alt.Legend(columns=3))
)
```
![visualization - 2020-01-30T183543 339](https://user-images.githubusercontent.com/781659/73507921-542f6d00-438f-11ea-9890-c817b1cf457d.png)
