### ISSUE TITLE
Specifying a custom domain

### ISSUE THREAD

**Issue by palnabarun** [altair-viz/altair#1071]
Hi

I have been trying to specify a custom domain for the `x` encoding on a plot where the data type of the channel is `nominal`. My current notion of a domain is that for `quantitative` channels, it would accept a start and end limit and truncate the specific encoding channel to the values in between the limits, and for `nominal` or `ordinal` channels, it would accept a list of values and only those will be shown in the plot.

Following is a small experiment I did:

```python
import altair as alt
import pandas as pd

df = pd.DataFrame({'a': list('CCCDDDEEE'), 'b': [2, 7, 4, 1, 2, 6, 8, 4, 7]})

alt.Chart(df).mark_point().encode(
    y='b',
    x= {
        'field': 'a',
        'type': 'nominal'
    }
)
```
![visualization 1](https://user-images.githubusercontent.com/10010419/43847395-22a28820-9b4e-11e8-81b1-638d001c73dd.png)

```python
alt.Chart(df).mark_point().encode(
    y='b',
    x= {
        'field': 'a',
        'type': 'ordinal',
        'scale': {
            'domain': ['D', 'E']
        }
    }
)
```
![visualization](https://user-images.githubusercontent.com/10010419/43847397-23c6c9b4-9b4e-11e8-8487-c2d979d10549.png)

I am under the impression that the second plot should not have the data points which have `x='C'` should not be plotted at all since I specified a custom domain.

Coming to my question, is it a bug or am I supposed to specify some more chart configuration parameters?

**Comment by jakevdp** [comment]
I think what you want is a filter operation:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({'a': list('CCCDDDEEE'),
                   'b': [2, 7, 4, 1, 2, 6, 8, 4, 7]})

alt.Chart(df).transform_filter(
    alt.datum.a != "E"
).mark_point().encode(
    y='b',
    x= 'a:O'
)
```
![visualization 33](https://user-images.githubusercontent.com/781659/43861245-1a934892-9b0b-11e8-8712-e12e657ea5bf.png)

In general, Altair/Vega-Lite avoid hiding data from the chart unless you explicitly request it.

**Comment by jakevdp** [comment]
This "don't hide points by default" thing is similar for quantitative domains, where you need to either clip or clamp the data explicitly; see https://altair-viz.github.io/user_guide/customization.html#adjusting-axis-limits

**Comment by palnabarun** [comment]
Thanks @jakevdp for the explanation. That clarifies my doubt.
