### ISSUE TITLE
Is binning with log scale allowed?

### ISSUE THREAD

**Issue by gh-owestesson** [altair-viz/altair#1074]
I would like to bin values along one or both axes while also plotting on log scale. Is this possible? It seems like when I request both binning and log scale axis, the log scale is disabled:

```
import altair as alt
import numpy as np

data = pd.DataFrame( {col: np.random.random_sample(50) for col in 'xy'})
data += 1e-4

chart = alt.Chart( data ).mark_circle().encode(y='y')

naturalBin = chart.encode(
     x = alt.X('x', bin=True, axis=alt.Axis(title = 'Binning, natural scale')))

log = chart.encode(
    x = alt.X('x', bin = False, scale = alt.Scale(type='log'), axis=alt.Axis(title = 'No Binning, log scale')))

logBin = chart.encode(
    x = alt.X('x', bin = True, scale = alt.Scale(type='log'), axis=alt.Axis(title = 'Binned, log scale')))

naturalBin & log &  logBin
```
![visualization 1](https://user-images.githubusercontent.com/130067/43913518-14b3514c-9bba-11e8-9d5b-9520545662b6.png)

**Comment by jakevdp** [comment]
Hi @breadbaron – I don't think log-spaced bins are supported in Vega-Lite. In particular, it's not clear to me what the right binning would even be...

One way you could proceed is to precompute the log and bin that:

```python
alt.Chart(data).transform_calculate(
    logx = 'log(datum.x)/log(10)'
).mark_circle().encode(
    alt.X('logx:Q', bin=True, title='log_10(x)'),
    y='y:Q'
)
```
![visualization 35](https://user-images.githubusercontent.com/781659/43919646-6bfeb2e6-9bcb-11e8-9c58-120632ed56d6.png)

**Comment by kanitw** [comment]
This is actually doable with some extra work. 

See https://github.com/vega/vega-lite/pull/4795 for an example in Vega-Lite. 
We may also improve this in the future -- see https://github.com/vega/vega-lite/issues/4792.

**Comment by stephencwelch** [comment]
This would be nice to have - any updates on the altair side?

**Comment by kanitw** [comment]
@stephencwelch see https://vega.github.io/vega-lite/examples/histogram_log.html.
