### ISSUE TITLE
Using a symlog scale?

### ISSUE THREAD

**Issue by mattpitkin** [altair-viz/altair#1077]
Is there any way to use a [symlog](https://matplotlib.org/gallery/scales/symlog_demo.html) scale for axes in Altair. If not would it be possible/relatively simple to add this in the future?

**Comment by jakevdp** [comment]
I don't think this is supported in Vega-Lite. It might be worth doing a feature request there.

**Comment by mattpitkin** [comment]
@jakevdp - thanks. I'll do as you suggest and see if there's the possibility of adding this to Vega-Lite.

**Comment by willwhitney** [comment]
This appears to be supported now in Vega-Lite (see https://vega.github.io/vega-lite/docs/scale.html#symlog).

**Comment by jakevdp** [comment]
The current docs on the Vega-Lite website are for the version 3.0 pre-release. Once Vega-Lite 3 is released we will work to update altair to incorporate new features like this one.

**Comment by willwhitney** [comment]
Ah, got it. Sorry for the false alarm!

**Comment by mattpitkin** [comment]
Now that vega-lite v3 has been released has the symlog support been incorporated into Altair?

**Comment by jakevdp** [comment]
Yes, for example:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'x': range(-50, 50),
    'y': range(100),
})

alt.Chart(df).mark_line().encode(
    alt.X('x', scale=alt.Scale(type='symlog')),
    alt.Y('y')
)
```
![visualization (31)](https://user-images.githubusercontent.com/781659/69761038-0726e480-111b-11ea-9cca-36250e1eb304.png)

**Comment by mattpitkin** [comment]
Excellent, thanks.
