### ISSUE TITLE
the href encoding

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1084]
Hi Jake and all,

Is the href encoding supported in Altair? I can't tell by the docs how I would use it. Vega lite docs uses "as" in the spec and of course that is a key work in Python: 

```
{
  "data": {"url": "data/cars.json"},
  "mark": "point",
  "transform": [{
    "calculate": "'https://www.google.com/search?q=' + datum.Name", "as": "url"
  }],
  "encoding": {
    "x": {"field": "Horsepower", "type": "quantitative"},
    "y": {"field": "Miles_per_Gallon", "type": "quantitative"},
    "color": {"field": "Origin", "type": "nominal"},
    "tooltip": {"field": "Name", "type": "nominal"},
    "href": {"field": "url", "type": "nominal"}
  }
}
```

**Comment by jakevdp** [comment]
Yes, it is supported. For example, here we modify a scatter plot of car properties so that clicking on any point opens a google search for the car name:
```python
import altair as alt
from vega_datasets import data

try:
    # Python 3
    from urllib.parse import urlencode
except ImportError:
    from urllib import urlencode

def make_google_query(name):
    return "https://www.google.com/search?" + urlencode({'q': '"{0}"'.format(name)})

cars['url'] = cars['Name'].apply(make_google_query)

alt.Chart(cars).mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    href='url',
    tooltip=['Name', 'url']
)
```
This would probably be worth adding as an example in the docs

**Comment by jakevdp** [comment]
#1085 adds this as an example in the docuementation

**Comment by Alcampopiano** [comment]
That is a big help Jake and an extremely useful feature. Thank you very much. I see that the hyperlinks work perfectly when the chart is saved as an html file; however, in the JL notebook I just get a blank screen even when saving the chart and loading it into an Iframe. Perhaps I am doing something wrong. Either way, I'm quite happy using the standalone html file if need be.

```python
import altair as alt
from vega_datasets import data
from IPython.display import HTML, display, IFrame

c=alt.Chart(data.cars.url).transform_calculate(
    url='https://www.google.com/search?q=' + alt.datum.Name
).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color='Origin:N',
    href='url:N',
    tooltip='Name:N'
)

c.save('test_chart.html')
IFrame('test_chart.html', 500, 500)
```

**Comment by Alcampopiano** [comment]
Sorry for the confusion. If I do the following in a JL notebook, the hyperlink works (in other words, I don't need to save the chart and then load it into an iframe). However, in a Colab notebook, I do get a blank cell and no errors in the JS console. 


```python
alt.Chart(data.cars.url).transform_calculate(
    url='https://www.google.com/search?q=' + alt.datum.Name
).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color='Origin:N',
    href='url:N',
    tooltip='Name:N'
)
```

**Comment by jakevdp** [comment]
Are you using http://colab.research.google.com/?

I pasted your code into a comment in a Colab notebook there, and it works correctly.

**Comment by Alcampopiano** [comment]
Yes, I get the blank cell. How odd.

![ss](https://user-images.githubusercontent.com/4624246/44051788-c78cd86e-9f08-11e8-8d27-6db75533844d.png)

**Comment by jakevdp** [comment]
Just so I'm clear: the chart doesn't render at all when you execute the cell?

**Comment by jakevdp** [comment]
Because it works fine for me:
<img width="857" alt="screen shot 2018-08-13 at 12 00 43 pm" src="https://user-images.githubusercontent.com/781659/44052092-91fdae98-9ef0-11e8-9316-954be9bf8bc3.png">

**Comment by jakevdp** [comment]
Could you share the link to the notebook where the chart fails to render?

**Comment by Alcampopiano** [comment]
No no, the chart reders perfectly. The blank cell appears when the hyper link is clicked.

**Comment by jakevdp** [comment]
Ah, I see. That was not clear to me.

That is due to the fact that Colab renders outputs in their own iframe, and so the hyperlink is being followed in that iframe, but http://google.com returns a blank page if you try to load it in an iframe.

To follow the hyperlinks when using colab, you can shift + click to open them in a new window.

Unfortunately, Vega-Lite has no way to specify the href target to make hyperlinks open a new window by default; a previous request about that was closed as will-not-fix: https://github.com/vega/vega-lite/issues/3795

**Comment by jakevdp** [comment]
Awesome – best of luck with the workshop!

**Comment by odoublewen** [comment]
Is it possible to turn off `href` for some of the points?  For example, if some of the points have links, but some do not.  

I tried setting my url variable to `None` but then I wind up with a hyperlink to `null`.

Apologies for posting to this old thread, but it seemed somewhat germane.  Happy to open an issue if called for.

**Comment by odoublewen** [comment]
Ah, I see if I set the masked rows to an empty string, it's effectively what I want (the hyperlink seems active in the browser, but it's a non-op when you click it.)   This is good enough for me!  Thanks so much for a great tool.

**Comment by nraw** [comment]
Does href no longer work on mobile?
I tried it on the example shared above and it works, but when I recreated the chart locally it didn't, that is, I can click on it through my laptop, but if I try going in mobile mode it doesn't execute the action.

**Comment by joelostblom** [comment]
There were some changes lately in Vega affecting mobile tooltips described in https://github.com/vega/vega/issues/3893#issuecomment-1998790778. Maybe the behavior you are seeing is related to the same changes?

**Comment by nraw** [comment]
I've noticed that difference as well, but I'm not able to tell whether the issue or the solution that they implemented is directly affected by this, as they talk about hover and tooltips rather than the url clicks. [This referenced issue](https://github.com/vega/vega/pull/3907) seems to specifically address the tooltip behaviour.
