### ISSUE TITLE
Altair 2.2 losses format property of InlineData object

### ISSUE THREAD

**Issue by iliatimofeev** [altair-viz/altair#1091]
~~~python
data = alt.InlineData(
    values={'a':[{'b': 0}, {'b': 1}, {'b': 2}]},
    format=alt.DataFormat(
            type='json',
            property='a',
    ))
chart = alt.Chart(
            data
       ).mark_tick(
       ).encode(
            x='b:N'
       )

chart
~~~
![visualization 36](https://user-images.githubusercontent.com/11561581/44123732-63aeb738-a032-11e8-9ee2-d3ced575296d.png)

**but**
~~~python 
alt.data_transformers.enable(consolidate_datasets=False)
chart

~~~
![visualization 37](https://user-images.githubusercontent.com/11561581/44123818-b9c2fefe-a032-11e8-91a8-53a262ef8989.png)

**Comment by jakevdp** [comment]
Thanks – looks like dataset consolidation ignores extra properties of the inline data. I think it should be a fairly straightforward fix.

**Comment by jakevdp** [comment]
I pushed a 2.2.1 release a few minutes ago that includes the fix for this bug.

Thanks for the report!
