### ISSUE TITLE
Custom order of points drawing a line 

### ISSUE THREAD

**Issue by jmansilla** [altair-viz/altair#1096]
Hi there folks.
@jakevdp I'm happy I found your comment here #689

> ordering of points in a line as well. I used that in an example here: 2098f8d

Right now I'm having trouble drawing a line exactly because of the ordering issue.
My problem is that I have to specify the ordering by providing the values, more or less like this:

```
alt.Chart(data).mark_line().encode(
        x='x:Q',
        y='y:Q',
        order=alt.Order('topic:N', sort=['Some Topic', 'Amazing Topic', 'Some Other', 'Minor Topic'])
    )
```
but I'm getting:

```
altair.vegalite.v2.schema.channels.Order->sort, validating 'anyOf'

['Some Topic', 'Amazing Topic', 'Some Other', 'Minor Topic'] is not valid under any of the given schemas
```

Is there any workaround for this?

**Comment by jakevdp** [comment]
The ``order`` field can only use ascending or descending... I'm not certain it's possible to do what you want in Vega-Lite.

**Comment by jmansilla** [comment]
Thanks folks.

Solved.

**Comment by ihightower** [comment]
can someone explain how this is solved clearly with example code. I also want to sort the stacked bars in a custom order. Lower stack say is 'Leave', Middle stack is 'Roster', Upper stack is 'OT' for Work Types. just ascending and descending for sort order doesn't cut it.

**Comment by jakevdp** [comment]
Currently you can control the stack order using an ``order`` encoding, and the legend order using the ``sort``:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'label': ['Leave', 'OT', 'Roster'],
    'hours': [5, 6, 7]
})

alt.Chart(df).transform_calculate(
    order="{'Leave': 0, 'Roster': 1, 'OT': 2}[datum.label]"
).mark_bar().encode(
    x='hours',
    color=alt.Color('label', sort=['Leave', 'Roster', 'OT']),
    order='order:Q'
)
```
![visualization - 2020-03-01T063033 916](https://user-images.githubusercontent.com/781659/75627576-2a33bb00-5b86-11ea-9e2e-92af46dea5ac.png)

When https://github.com/vega/vega-lite/issues/1734 is addressed, this will be easier.
