### ISSUE TITLE
legend for layered charts

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1099]
Hi Jake,

In the gallery there are a few examples that show a layered chart as a comparison line. It is often the case that the comparison line needs a legend to explain what it is. What is the most Altair-ic way of doing this? As you can see below, I can get close, but not all the way.

```python
import pandas as pd
from vega_datasets import data
import altair as alt

stocks = data.stocks()
google = stocks.query("symbol=='GOOG'")
others = stocks.query("symbol!='GOOG'")


bars=alt.Chart(google).mark_bar().encode(
    x='year(date):N',
    y='average(price)',
    
).properties(title='Google stock prices')

others=alt.Chart(others).mark_line().encode(
    x='year(date):N',
    y='average(price)',
    color=alt.Color('average(price)', scale=alt.Scale(range=['red', 'red'], domain=[1,2]), title='competitors')
)

bars + others
```

**Comment by jakevdp** [comment]
Since the legend is constructed from a color encoding, I think the best way to do this is to create a field that you can use to encode what you want to show. For example:
```python
chart = alt.LayerChart(stocks).transform_calculate(
    company = 'datum.symbol == "GOOG" ? "goog" : "competitors"'
)

google = alt.Chart().transform_filter(
    alt.datum.company == "goog"
).mark_bar().encode(
    x='year(date):N',
    y='price:Q',
).properties(title='Google stock prices')

others = alt.Chart().transform_filter(
    alt.datum.company == "competitors"
).mark_line(color='red').encode(
    x='year(date):N',
    y='average(price):Q',
    color=alt.Color('company:N',
                    scale=alt.Scale(range=['red']))
)

chart + google + others
```
![visualization 41](https://user-images.githubusercontent.com/781659/44217122-92998380-a12b-11e8-9a77-84882313a4ad.png)

**Comment by Alcampopiano** [comment]
This looks great. Thanks so much Jake. I will look at that syntax you are using for transform_calculate as I didn't immediately understand it. In case it helps others, it seems like it works similarly to `np.where` as the following works the same.

```python
import numpy as np
stocks['companies'] = np.where(stocks['symbol']=='GOOG', 'google', 'competitor')
chart = alt.LayerChart(stocks)

google = alt.Chart().transform_filter(
    alt.datum.companies == "google"
).mark_bar().encode(
    x='year(date):N',
    y='price:Q',
).properties(title='Google stock prices')

others = alt.Chart().transform_filter(
    alt.datum.companies != "google"
).mark_line(color='red').encode(
    x='year(date):N',
    y='average(price):Q',
    color=alt.Color('companies',
                    scale=alt.Scale(range=['red']))
)

chart + google + others

```

**Comment by jakevdp** [comment]
Yeah, sorry about that. The difference here is that you are explicitly storing the new column in the data, whereas my version was telling the renderer to calculate the new value from the data, which leads to a more compact chart specification.

**Comment by Alcampopiano** [comment]
No apologies necessary. This is all good to know. Thanks Jake.
