### ISSUE TITLE
VConcat chart and HConcated chart

### ISSUE THREAD

**Issue by yupenghegh** [altair-viz/altair#1101]
I am trying to generate a figure with multiple charts. The issue is that when I vconcat a chart with a chart generated by hconcating two charts, the alignment is not what I expected. On the first row, the single chart is on the left instead of center. Is it possible to do center alignment in vconcatation using altair? Thanks in advance.

Below is the code of a simple example for this.

```import pandas as pd
import altair as alt
import numpy as np
df = pd.DataFrame()
df["x"] = range(5)
df["y"] = np.random.rand(5)

c = alt.Chart(df).mark_bar().encode(
    x = "x",
    y = "y")
c & (c | c)
```

**Comment by jakevdp** [comment]
The ``alt.vconcat`` function lets you specify additional arguments to control the concatenation (note that ``a & b`` is essentially a shortcut for ``alt.vconcat(a, b)``).

To center the concatenated charts, specify ``center=True``:
```python
import altair as alt
import numpy as np
df = pd.DataFrame()
df["x"] = range(5)
df["y"] = np.random.rand(5)

c = alt.Chart(df).mark_bar().encode(
    x = "x",
    y = "y")

alt.vconcat(c, c | c, center=True)
```
![visualization 42](https://user-images.githubusercontent.com/781659/44227564-cf737380-a147-11e8-9c58-19bb8a8b2d37.png)

**Comment by yupenghegh** [comment]
Thanks! But the code does not seem to work on my end, which is weird. I am using altair 2.2.1 and jupyter notebook (alt.renderers.enable('notebook')). I did not get any error message and the figure generated is: 

![image](https://user-images.githubusercontent.com/41090131/44227853-94257480-a148-11e8-97b6-de311d19b04f.png)

**Comment by jakevdp** [comment]
Ah, yes the ``center`` argument was only added in Vega-Lite 2.6. If you have an older vega-lite extension in your jupyter notebook, you will have to update it (``pip install -U vega``)
