### ISSUE TITLE
Format legend in multiline plot

### ISSUE THREAD

**Issue by floringogianu** [altair-viz/altair#1104]
I tried using the `format` argument on `alt.Legend` to change the format of the plots listed in the legend but it doesn't seem to be working. Any suggestion on what I might be doing wrong? Or this might be a bug?

```python
alt.Chart(reg_data).mark_line(strokeWidth=1).encode(
    x='x',
    y='predict',
    color=alt.Color('λ:O',
                    scale=alt.Scale(scheme='reds'), 
                    legend=alt.Legend(title='λ values', format='.3f'))
)
```

![image](https://user-images.githubusercontent.com/1670348/44309832-3194d880-a3d5-11e8-91c7-6e0fa99a0d47.png)

**Comment by jakevdp** [comment]
This looks like a Vega-Lite bug; I've opened an issue there: https://github.com/vega/vega-lite/issues/4138

**Comment by floringogianu** [comment]
@jakevdp thanks for looking into this.
@domoritz indeed the legend is properly formatted with quantitative types.

**Comment by jakevdp** [comment]
Fixed in Vega-Lite 3
