### ISSUE TITLE
domain=[min, max] not adjusting axis limits

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1108]
Hi Jake,

Do you know why the following isn't working to adjust the x limits?

```python
stocks = data.stocks()

alt.Chart(stocks).mark_line().encode(
    x=alt.X('year(date):Q', 
            scale=alt.Scale(domain=(2004, 2010))
           ),
    y='average(price)',
)
```
When I comment out `Scale` the chart shows the full range as expected. In the documentation you show an example like this with the cars dataset, and that works perfectly fine for me.

```python
stocks = data.stocks()

alt.Chart(stocks).mark_line().encode(
    x=alt.X('year(date):Q', 
            #scale=alt.Scale(domain=(2004, 2010))
           ),
    y='average(price)',
)
```
In the vega editor it also works fine (with `clip = true`)

**Comment by jakevdp** [comment]
Yes, that should do it. I'll try to get the Colab altair version updated as well.

**Comment by Alcampopiano** [comment]
Thanks Jake.

**Comment by Alcampopiano** [comment]
Just letting you know that I upgraded JL inside of Colab thinking that the Vega lite extension would be updated as well. The issue with the axis limits was still present. Should I be upgrading something else?

JL version 0.34.0
Altair version 2.1.0

**Comment by jakevdp** [comment]
In colab, if you update Altair to version 2.2 I think it should fix the issue.

**Comment by jakevdp** [comment]
If you are using jupyterlab, you would need to update jupyterlab to get the most recent vega renderer.

**Comment by Alcampopiano** [comment]
Yep, `!pip install altair -U` and restarting the runtime in Colab did the trick. Thanks again Jake!
