### ISSUE TITLE
Single Selection Mouseover Nearest

### ISSUE THREAD

**Issue by hassenmorad** [altair-viz/altair#1110]
In the second example of single selection in the docs, illustrating the functionality provided by the 'nearest' flag [https://altair-viz.github.io/user_guide/selections.html#single-selections](url) it seems that the 'nearest' point is based on the upper left-hand corner of each box, whereas a more intuitive point of nearness would probably be the center. Is there any way to adjust this?

**Comment by jakevdp** [comment]
No, I don't think that is adjustable.
