### ISSUE TITLE
NoSuchEntryPoint: No 'notebook' entry point found in group 'altair.vegalite.v2.renderer'

### ISSUE THREAD

**Issue by mbookman** [altair-viz/altair#1114]
I have followed the installation instructions here:

  https://altair-viz.github.io/getting_started/installation.html#quick-start-altair-notebook

This appears to be a problem with the [2.0 version of vega being published](https://github.com/vega/ipyvega/releases/tag/v2.0.0) an hour ago. This notebook was working previously with 1.3.0. In fact, if I change the install line to:

```
!pip install --upgrade altair vega_datasets notebook vega==1.3.0
```

things work.

Here's my output without the vega version restriction.

```
# Install Altair (for visualizations)
!pip install --upgrade altair vega_datasets notebook vega

<snip>

Installing collected packages: altair, notebook, vega
  The scripts jupyter-bundlerextension, jupyter-nbextension, jupyter-notebook and jupyter-serverextension are installed in '/home/jupyter-user/.local/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
Successfully installed altair-2.2.2 notebook-5.6.0 vega-2.0.0

<snip>

import vega
import altair as alt

# for the notebook only (not for JupyterLab) run this command once per session
print(vega.__version__)
alt.renderers.enable('notebook')

2.0.0
---------------------------------------------------------------------------
NoSuchEntryPoint                          Traceback (most recent call last)
~/.local/lib/python3.4/site-packages/altair/utils/plugin_registry.py in _enable(self, name, **options)
    133             try:
--> 134                 ep = entrypoints.get_single(self.entry_point_group, name)
    135             except entrypoints.NoSuchEntryPoint:

~/.local/lib/python3.4/site-packages/entrypoints.py in get_single(group, name, path)
    185 
--> 186     raise NoSuchEntryPoint(group, name)
    187 

NoSuchEntryPoint: No 'notebook' entry point found in group 'altair.vegalite.v2.renderer'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-4-152d9ee0b52b> in <module>()
      4 # for the notebook only (not for JupyterLab) run this command once per session
      5 print(vega.__version__)
----> 6 alt.renderers.enable('notebook')

~/.local/lib/python3.4/site-packages/altair/utils/plugin_registry.py in enable(self, name, **options)
    169         if name is None:
    170             name = self.active
--> 171         return PluginEnabler(self, name, **options)
    172 
    173 

~/.local/lib/python3.4/site-packages/altair/utils/plugin_registry.py in __init__(self, registry, name, **options)
     23         self.options = options
     24         self.original_state = registry._get_state()
---> 25         self.registry._enable(name, **options)
     26 
     27     def __enter__(self):

~/.local/lib/python3.4/site-packages/altair/utils/plugin_registry.py in _enable(self, name, **options)
    135             except entrypoints.NoSuchEntryPoint:
    136                 if name in self.entrypoint_err_messages:
--> 137                     raise ValueError(self.entrypoint_err_messages[name])
    138                 else:
    139                     raise

ValueError: 
To use the 'notebook' renderer, you must install the vega package
and the associated Jupyter extension.
See https://altair-viz.github.io/getting_started/installation.html
for more information.
```

Let me know if you need more information.

**Comment by jakevdp** [comment]
When you run ``!pip install`` from a notebook, it doesn't necessarily install packages in the kernel being used by the notebook (I wrote about the details behind that [here](https://jakevdp.github.io/blog/2017/12/05/installing-python-packages-from-jupyter/))

What you need to do is to install the vega package **in the same kernel** that you're using to run code.

**Comment by jakevdp** [comment]
It looks like the 2.0 release of the vega package only supports vega-lite version 3, which hasn't been released yet.

In the meantime, please use vega=1.3 and things will work.

cc/ @domoritz – could we revert the ipyvega 2.0 release, or at least make the vega-lite 2 renderer available beside the vega-lite 3 renderer until vega-lite 3 and its altair wrapper are released?

**Comment by domoritz** [comment]
Hmm, I can revert the release but in the future we should make sure to fix the major version of the Vega dependency.

**Comment by jakevdp** [comment]
Altair doesn't have any dependency on vega, so there's nowhere to pin the version.

**Comment by domoritz** [comment]
Ohhh, I see. Alright, I reverted the pip and conda packages.

**Comment by scharron** [comment]
I just had the same error with the newly released 2.0 / 2.0.1 vega versions. With the 1.4.0 version, no error.

**Comment by domoritz** [comment]
Yes, the new Vega package is for Altair 3.

**Comment by jakevdp** [comment]
> Yes, the new Vega package is for Altair 3.

I plan to release Altair 3 some time this week... depending on how much time I can find in the evenings after kids go to sleep :smile:

**Comment by kurtosis** [comment]
I just saw this issue, worked fine for me with v1.4.0.
Would it be worth updating the installation instructions (at least the troubleshooting page)?
https://altair-viz.github.io/getting_started/installation.html#installation-notebook

**Comment by domoritz** [comment]
Yeah, do you want to send a PR to update the troubleshooting guide?

**Comment by jakevdp** [comment]
I updated the docs last night... just haven't done a docs build yet.

**Comment by domoritz** [comment]
Do you want to close this issue then?

**Comment by SeaCelo** [comment]
I just got this error after installing Altair 4.0.0

`conda install -c conda-forge altair vega_datasets`

>  All requested packages already installed.

`---------------------------------------------------------------------------
NoSuchEntryPoint                          Traceback (most recent call last)
~/anaconda3/lib/python3.7/site-packages/altair/utils/plugin_registry.py in _enable(self, name, **options)
    133             try:
--> 134                 ep = entrypoints.get_single(self.entry_point_group, name)
    135             except entrypoints.NoSuchEntryPoint:

~/anaconda3/lib/python3.7/site-packages/entrypoints.py in get_single(group, name, path)
    216 
--> 217     raise NoSuchEntryPoint(group, name)
    218 

NoSuchEntryPoint: No 'notebook' entry point found in group 'altair.vegalite.v4.renderer'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-1-a60fa0867c28> in <module>
      5 sns.set_style("whitegrid")
      6 import altair as alt
----> 7 alt.renderers.enable("notebook")
      8 
      9 # Code for hiding seaborn warnings

~/anaconda3/lib/python3.7/site-packages/altair/utils/plugin_registry.py in enable(self, name, **options)
    169         if name is None:
    170             name = self.active
--> 171         return PluginEnabler(self, name, **options)
    172 
    173 

~/anaconda3/lib/python3.7/site-packages/altair/utils/plugin_registry.py in __init__(self, registry, name, **options)
     23         self.options = options
     24         self.original_state = registry._get_state()
---> 25         self.registry._enable(name, **options)
     26 
     27     def __enter__(self):

~/anaconda3/lib/python3.7/site-packages/altair/utils/plugin_registry.py in _enable(self, name, **options)
    135             except entrypoints.NoSuchEntryPoint:
    136                 if name in self.entrypoint_err_messages:
--> 137                     raise ValueError(self.entrypoint_err_messages[name])
    138                 else:
    139                     raise

ValueError: 
To use the 'notebook' renderer, you must install the vega package
and the associated Jupyter extension.
See https://altair-viz.github.io/getting_started/installation.html
for more information.`

**Comment by jakevdp** [comment]
In Altair 4.0, you do not need to use a special renderer in the Jupyter notebook. Just delete all references to ``alt.renderers`` and run your code again. More information in https://altair-viz.github.io/user_guide/display_frontends.html

**Comment by jakevdp** [comment]
Another note: once ipyvega is updated to support Altair 4 (v2.6 or newer) then you'll be able to use the notebook renderer if you wish. But at the moment ipyvega does not support Altair 4.

**Comment by feisalaswad** [comment]
im just downgrading altair from 4.0 to 3.0 its workfine

**Comment by jakevdp** [comment]
> just downgrading altair from 4.0 to 3.0 its work fine

No need to downgrade: use the default renderer (i.e. delete ``alt.renderers.enable('notebook')`` from your code) and Altair 4.0 will work fine with Jupyter Notebook.
