### ISSUE TITLE
add vertical line faceted chart

### ISSUE THREAD

**Issue by XaviFar** [altair-viz/altair#1124]
Hello, 
I'm struggling with something that I can't solve.
let's say we have the example from the Becker’s Barley Trellis Plot [https://altair-viz.github.io/gallery/beckers_barley_trellis_plot.html](url)
What I want to do is add a dashed vertical line from x=30 so I can easily see if the value from the plots i over or under that value. 

thanks!
```python
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_point().encode(
    alt.X('median(yield)', scale=alt.Scale(zero=False)),
    alt.Y(
        'variety',
        sort=alt.EncodingSortField(field='yield', op='median', order='descending'),
        scale=alt.Scale(rangeStep=20)
    ),
    color='year:N',
    row='site'
)

```

**Comment by afonit** [comment]
Currently it is not possible to do facets(what the 'row' is doing) on a layered chart.

**Comment by afonit** [comment]
```python
import altair as alt
from vega_datasets import data

source = data.barley()
source['a'] = 30
chart_one = alt.Chart().mark_point().encode(
    alt.X('median(yield)', scale=alt.Scale(zero=False)),
    alt.Y(
        'variety',
        sort=alt.EncodingSortField(field='yield', op='median', order='descending'),
        scale=alt.Scale(rangeStep=20)
    ),
    color='year:N'
)

chart_two = alt.Chart().mark_rule().encode(
    x='a')

(chart_one+chart_two).facet(row='site', data=source)
```

**Comment by jakevdp** [comment]
If you don't want to add a column to your dataframe, you can also put the value for the vertical line in the schema with a calculate transform:
```python
import altair as alt
from vega_datasets import data

source = data.barley()

points = alt.Chart().mark_point().encode(
    alt.X('median(yield)', scale=alt.Scale(zero=False)),
    alt.Y(
        'variety',
        sort=alt.EncodingSortField(field='yield', op='median', order='descending'),
        scale=alt.Scale(rangeStep=20)
    ),
    color='year:N'
)

vertline = alt.Chart().mark_rule().encode(
    x='a:Q')

alt.layer(
    points, vertline,
    data=source
).transform_calculate(
    a="30"
).facet(
    row='site'
)
```

**Comment by XaviFar** [comment]
Awesome, thanks for the answers, it worked like a charm!

**Comment by tuxassault** [comment]
How can i apply the transform_calculate to put the vline on a datetime encoded field? The code below gives me a JS error about parsing

`ufo_sightings_over_time = ufo_df['date_witnessed'].groupby(ufo_df['date_witnessed'].dt.to_period("M")).agg('count').reset_index(name='count')
ufo_sightings_over_time.date_witnessed = ufo_sightings_over_time.date_witnessed.astype('str')
over_time = alt.Chart(ufo_sightings_over_time,height=600,width=800).encode(x='date_witnessed:T',y='count:Q').mark_line()
x_files = alt.Chart().mark_rule().encode(x='a:T')
alt.layer(over_time,x_files,data=ufo_sightings_over_time,background='white').transform_calculate(a='1993-07')`

**Comment by tuxassault** [comment]
How can i apply the transform_calculate to put the vline on a datetime encoded field? The code below gives me a JS error about parsing

`
ufo_sightings_over_time = (ufo_df['date_witnessed']
.groupby(ufo_df['date_witnessed']
.dt.to_period("M"))
.agg('count')
.reset_index(name='count')

ufo_sightings_over_time.date_witnessed = ufo_sightings_over_time.date_witnessed.astype('str')

over_time = (alt.Chart(ufo_sightings_over_time,height=600,width=800)
.encode(x='date_witnessed:T',y='count:Q')
.mark_line())

x_files = alt.Chart().mark_rule().encode(x='a:T')
alt.layer(over_time,
x_files,
data=ufo_sightings_over_time,
background='white').transform_calculate(a='1993-07')
`

**Comment by sterlinm** [comment]
Thanks for the tip above. I'm confused about something that indicates there's an issue with how I'm understanding part of Altair. Why doesn't the following work?

```python
vertline = alt.Chart().mark_rule().encode(
    x='a:Q'
)
```
Thanks!

**Comment by jakevdp** [comment]
I'm not certain what exactly you're asking. If you provide data, it draws a line correctly:
```python
import pandas as pd
import altair as alt

data = pd.DataFrame({'a': [2]})

alt.Chart(data).mark_rule().encode(
    x='a:Q'
).interactive()
```
![visualization (24)](https://user-images.githubusercontent.com/781659/58195178-3ea06a00-7c7c-11e9-8e26-9676389d324b.png)

**Comment by sterlinm** [comment]
Sorry, I came across this issue because whenever I want to add a horizontal line to a chart, my first instinct is to try to specify `x=alt.value(3)` or whatever the position of the line I want is. For other encodings I can use `alt.value(n)` to hardcode a value. For example, I can control the size and the color of the line:

```python
import altair as alt
from vega_datasets import data

source = data.cars()

alt.Chart(source).mark_rule().encode(
    x='a:Q',
    size=alt.value(3),
    color=alt.ColorValue('red')
).transform_calculate(
    a="2"
).interactive()
```
![visualization (1)](https://user-images.githubusercontent.com/1461273/58215940-33742b00-7cca-11e9-8cc2-5b8bbdfaa60e.png)


I can control the size and color using alt.value and alt.ColorValue, but if I try to set the encoding for `x` using alt.value I get an error:

<img width="627" alt="Screen Shot 2019-05-22 at 7 46 29 PM" src="https://user-images.githubusercontent.com/1461273/58215986-64546000-7cca-11e9-82dc-c26eb4bdeb3f.png">

I just don't have a good handle on why I can set size to `alt.value(3)` but not `x`.

**Comment by jakevdp** [comment]
(Please in the future paste the actual text of your code rather than a screenshot)

Your code works for me in the current version of Altair, though it's not a very exciting chart on its own. Perhaps you're using an older version of the library?

```python
import altair as alt
from vega_datasets import data

source = data.cars()

alt.Chart(source).mark_rule().encode(
    x=alt.XValue(2),
    size=alt.SizeValue(3),
    color=alt.ColorValue("red")
).transform_calculate(
    a="2"
)
```
![visualization (92)](https://user-images.githubusercontent.com/781659/58225456-fa8e8300-7cd6-11e9-88e5-86b799051e21.png)

**Comment by sterlinm** [comment]
Sorry will edit the image or when I have a chance. I didn't know about alt.XValue. Thanks!

**Comment by jakevdp** [comment]
Oh, the ``alt.XValue`` vs. ``alt.value`` here is not important – they lead to the same result. I just made an error when transcribing your code screenshot (one reason it's important to paste actual code, not an image of the code)

The operative issue I believe is that you are using an old version of the library.

**Comment by firasm** [comment]
Trying to reproduce the example from [above](https://github.com/altair-viz/altair/issues/1124#issuecomment-417714535) on Altair 3.2.0 :

```import altair as alt
from vega_datasets import data

source = data.barley()

points = alt.Chart().mark_point().encode(
    alt.X('median(yield)', scale=alt.Scale(zero=False)),
    alt.Y(
        'variety',
        sort=alt.EncodingSortField(field='yield', op='median', order='descending'),
        scale=alt.Scale(rangeStep=20)
    ),
    color='year:N'
)

vertline = alt.Chart().mark_rule().encode(
    x='a:Q'
)

alt.layer(
    points, vertline,
    data=source
).transform_calculate(
    a="30"
).facet(
    row='site'
)```

but I get no chart with three dots. I can display a single chart with the line if I remove the .facet()... 

Does this have something to do with [this comment](https://github.com/altair-viz/altair/issues/668#issuecomment-476779595) about the change in where data is specified in Altair 3.1+ ?

**Comment by jakevdp** [comment]
It works fine for me in Altair 3.2. I suspect your frontend renderer is out of date – this is not controlled by the Altair version you have installed in the Python backend, but rather by the frontend extension (i.e. the vega nbextension for jupyter notebook, or the vega labextension for jupyterlab). Update your frontend extension and the chart should work.

**Comment by jakevdp** [comment]
Info on the frontend requirements can be found on the installation page: https://altair-viz.github.io/getting_started/installation.html

**Comment by firasm** [comment]
Thanks for confirming it worked for you. 

Prompted me up to update my full stack (don't think the renderer was out of date after all) and dig deeper.

Problem seems to be (of all things!!) in Safari. If I open the same jupyterlab notebook in Chrome, everything looks as it should:

<img width="1433" alt="Screen Shot 2019-10-27 at 8 18 00 AM" src="https://user-images.githubusercontent.com/2507459/67636885-654d7700-f892-11e9-9550-b47a3e895160.png">

Weird and bizarre. 

Safari version: Version 13.0.2 (15608.2.30.1.1)
macOS 10.15.
(I also tried to reload and run without content blockers, same issue. Other charts render fine, it' just this one!)

Cheers.

**Comment by jakevdp** [comment]
Strange... if you want to follow up, you could raise this issue in the Vega-Lite repository. Javascript errors reported in the browser's console may give clues as to what's going on...

**Comment by dsandber** [comment]
If you want multiple vertical lines at different places, do you need a separate layer for each one?

**Comment by jakevdp** [comment]
No, you can specify multiple rule marks in a single layer by using a multiple-row dataset:
```python
import altair as alt
import pandas as pd
df = pd.DataFrame({'x': [2, 3, 5, 7, 11]})
vert_lines = alt.Chart(df).mark_rule().encode(x='x')
```

**Comment by dsandber** [comment]
Perfect, thank you!

**Comment by Mohammadreza20** [comment]
Hello, Happy New Year
I want to add a couple of vertical lines to my chart but I don't know how could you please help me? 
vertical lines for two different date


Code :
``

highlight = alt.selection(
    type='single', on='mouseover', fields=['DOY'], nearest=True)

base = alt.Chart(NO2).encode(
    x=alt.X('monthdate(Timestamp):Q', title='Date'),
    y=alt.Y('mean(T_NO2):Q', title='NO2 Khorasan (mol/m^2)'),
    color=alt.Color('Year:O', scale=alt.Scale(scheme='magma')))

points = base.mark_circle().encode(
    opacity=alt.value(0),
    tooltip=[
        alt.Tooltip('Month:O', title='Month'),
        alt.Tooltip('DOY:Q', title='DOY'),
        alt.Tooltip('T_NO2:Q', title='NO2')
    ]).add_selection(highlight)

lines = base.mark_line().encode(
    size=alt.condition(~highlight, alt.value(3), alt.value(3)))




rule1 = base.mark_rule(color='red').encode(
    x={'Timestamp': "2020-11-09"},
    size=alt.value(5)
)

rule2 = base.mark_rule(color='orange').encode(
    x={'Timestamp': "2020-11-20"},
    size=alt.value(5),
)

    

(points + lines).properties(width=600, height=350).interactive()

``
![Untitled](https://user-images.githubusercontent.com/31747767/103459859-1bc6aa80-4d27-11eb-848c-ca8f5b866a9b.jpg)


![visualization](https://user-images.githubusercontent.com/31747767/103459866-31d46b00-4d27-11eb-8b01-ed45b5cdebd7.png)

**Comment by vtnate** [comment]
@Mohammadreza20 I'm struggling with the same problem. I'd like to put two vertical lines at specific dates, or perhaps shade between two dates, and haven't figured out what I need to do. Did you find a solution?

**Comment by firasm** [comment]
If someone provides some sample code and a minimum working example of your plot, I can probably help you get vertical lines. 

In the meantime, [here is an example](https://altair-viz.github.io/gallery/us_employment.html) from the Altair gallery on how to create vertical lines

![visualization-8](https://user-images.githubusercontent.com/2507459/116594267-e007b000-a8d6-11eb-84db-beb1f3083af3.png)


For saving files, I suggest looking at the [Chart.save()](https://altair-viz.github.io/user_guide/generated/toplevel/altair.Chart.html?highlight=save#altair.Chart.save) method, in particular the `scale_factor` parameter.

**Comment by vtnate** [comment]
Thanks @firasm, I appreciate the additional brainpower. I have a horizontal line. I'd like to also include 2 vertical lines at arbitrary datetimes, or even better shading between two arbitrary datetimes. This is what my code looks like:

Sample df:

> df = pd.DataFrame([
>     {
>         "Time": pd.to_datetime("2007-01-01 00:00:00"),
>         "Temp": 66
>     },
>     {
>         "Time": pd.to_datetime("2007-01-01 01:00:00"),
>         "Temp": 66.3
>     },
>     {
>         "Time": pd.to_datetime("2007-01-01 02:00:00"),
>         "Temp": 66.2
>     },
>     {
>         "Time": pd.to_datetime("2007-01-01 03:00:00"),
>         "Temp": 66.4
>     },
>     {
>         "Time": pd.to_datetime("2007-01-01 04:00:00"),
>         "Temp": 66.1
>     }
> ])

Chart code:

> demo = alt.Chart(df).mark_line().encode(
>     alt.X("Time:T", title="Time of event"),
>     alt.Y('Temp:Q', title='Temp during event', scale=alt.Scale(domain=(65, 67))),
>     
> )
> 
> df['Threshold'] = 66.3
> horzline = alt.Chart(df).mark_rule(color='red').encode(
>     y='Threshold:Q'
> )
> 
> (demo + horzline)
