### ISSUE TITLE
Wrapping timeseries chart

### ISSUE THREAD

**Issue by brylie** [altair-viz/altair#1126]
A Redditor posted a seemingly simple chart design, [asking how to produce the design](https://reddit.com/comments/9cifqe):

![chart design sketch](https://i.redd.it/25ajib1bbyj11.jpg)

Initial responses about how to produce the chart were in three main flavors:
- gantt
- stacked bar
- calendar heatmap

In practice, each of the above chart types present unique challenges for, and may be incapable of rendering, the desired output.

The data structure might be, in effect, an array of two-tuples where each tuple contains a start and end Datetime.

What are some ideas on how this chart could be created with Altair?

**Comment by curran** [comment]
This could be done with straight D3, but I'm not sure the Altair/Vega abstraction can support it.

**Comment by jakevdp** [comment]
It depends how your data is represented, but something like this can definitely be done in Altair. For example:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'start': pd.to_datetime(['2018-09-03T08:00', '2018-09-03T16:00',
                             '2018-09-04T10:00', '2018-09-04T15:00',
                             '2018-09-05T09:00', '2018-09-05T12:30']),
    'end': pd.to_datetime(['2018-09-03T14:00', '2018-09-03T18:00',
                           '2018-09-04T12:00', '2018-09-04T17:00',
                           '2018-09-05T11:00', '2018-09-05T17:30'])
})

alt.Chart(df.reset_index()).mark_bar().encode(
    y='day(start):O',
    x='hoursminutes(start)',
    x2='hoursminutes(end)',
    detail='index'
)
```
![visualization 50](https://user-images.githubusercontent.com/781659/45033054-3ded7800-b008-11e8-9a29-f1988b023062.png)

**Comment by brylie** [comment]
OK, that is elegant!

Thanks @jakevdp :-)

**Comment by curran** [comment]
That's fantastic!
