### ISSUE TITLE
layer then facet 

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1128]
Hi Jake,

I followed your instructions [here](https://github.com/altair-viz/altair/issues/920) and got really close.

If you look at my example below, do you know a way to get the text marks to show the overall count on the x axis rather than for each colored segment? I'm sure I'm missing something obvious.
![visualization 18](https://user-images.githubusercontent.com/4624246/45118797-8485c400-b127-11e8-8517-9ed344474c6f.png)

```python
import altair as alt
import pandas as pd

df=pd.DataFrame({'gender': ['male', 'male', 'male', 'female', 'female', 'other', 'other', 'female', 'female', 'female', 'male', 'male', 'female',  'other', 'other', 'female', 'male', 'male'], 
                 'grade': ['9-10', '11-12', '11-12', '9-10', '11-12', '9-10', '9-10', '9-10', '11-12', '11-12', '9-10', '11-12', '9-10', '9-10', '9-10', '9-10', '11-12', '11-12'], 
                 'like_school': ['yes', 'no', 'yes', 'neutral', 'neutral', 'no', 'yes', 'no', 'neutral', 'no', 'yes', 'no', 'yes', 'yes', 'neutral', 'neutral', 'no', 'yes']})

bars=alt.Chart().mark_bar().encode(
    y='like_school',
    x='count()',
    color='gender',
    tooltip=[alt.Tooltip('count()', title='number of records')]
).properties(
    width=180,
    height=180
)

text=bars.mark_text(color='black').encode(
    text='count()',
).properties(
    width=180,
    height=180
)

alt.layer(bars, text, data=df).facet(
    column='grade:N'  
)#.resolve_scale(color='independent')
```

**Comment by jakevdp** [comment]
I think the way to do this is with a [Stack Transform](https://vega.github.io/vega-lite/docs/stack.html#transform), but unfortunately that won't be available until Vega-Lite 3.0 is released.

**Comment by Alcampopiano** [comment]
Thanks for letting me know. I will keep fooling around with it in case I get lucky. I hope it's okay to post on the VL slack in case others have insights. Take care and thank you.

**Comment by jakevdp** [comment]
> post on the VL slack

That's a good idea

**Comment by Alcampopiano** [comment]
Okay, I was looking for this:
![im](https://user-images.githubusercontent.com/4624246/45128195-b8261580-b14a-11e8-80ad-6c19c7a522d0.png)

Which is possible using the code above *only* if you define each chart separately. Sorry if I was not clear about what I was trying to accomplish.

```python
df=pd.DataFrame({'gender': ['male', 'male', 'male', 'female', 'female', 'other', 'other', 'female', 'female', 'female', 'male', 'male', 'female',  'other', 'other', 'female', 'male', 'male'], 
                 'grade': ['9-10', '11-12', '11-12', '9-10', '11-12', '9-10', '9-10', '9-10', '11-12', '11-12', '9-10', '11-12', '9-10', '9-10', '9-10', '9-10', '11-12', '11-12'], 
                 'like_school': ['yes', 'no', 'yes', 'neutral', 'neutral', 'no', 'yes', 'no', 'neutral', 'no', 'yes', 'no', 'yes', 'yes', 'neutral', 'neutral', 'no', 'yes']})

bars=alt.Chart().mark_bar().encode(
    y='like_school',
    x='count()',
    color='gender',
    tooltip=[alt.Tooltip('count()', title='number of records')]
).properties(
    width=180,
    height=180
)

text=alt.Chart().mark_text(dx=10).encode(
    text='count()',
    y='like_school',
    x='count()',
).properties(
    width=180,
    height=180
)

alt.layer(bars, text, data=df).facet(
    column='grade:N'  
)
```

**Comment by jakevdp** [comment]
Oh, I see. From the way you phrased the question, I thought you were trying to put a number at the top of each sub-bar, which would require a stack transform to correctly place all the cumulative sums.

**Comment by Alcampopiano** [comment]
Apologies for the confusion and thanks for the help.
