### ISSUE TITLE
how to sort in altair 2.2

### ISSUE THREAD

**Issue by manojkumargandikota** [altair-viz/altair#1129]
Hi @jakevdp , I have started using altair for data analysis since two months. 

I was using the below code in altair 2.1 to sort the bars.

```
alt.Chart(matches).mark_bar().encode(
    alt.X('toss_winner', sort=alt.SortField(field='count():Q', op='count', order='descending'), axis=alt.Axis(title='Toss Winning Team')),
    alt.Y('count()', axis=alt.Axis(title='Number of Toss Wins')),
    color = alt.Color('toss_winner', scale=alt.Scale(scheme='viridis')),
    order = alt.Order( 'count()', sort = 'ascending'),
    tooltip = ['toss_winner','count(id)']
).configure_axis(
    domainWidth=1,
    labelFontSize=15,
    titleFontSize=20
).properties(height=400, width=600
            ).interactive()
```
It was working properly. 

But if I am using the same code in altair 2.2, it is throwing the following error. 

        SchemaValidationError: Invalid specification

        altair.vegalite.v2.schema.core.SortField, validating 'additionalProperties'

        Additional properties are not allowed ('op' was unexpected)
        
Is there anyway I can sort the bars in altair 2.2?

But strangely, I created the above code as json object using the below code and display the chart, it is displaying with sorted bars.

```
import json
with open('../input/testvegalitejson/test.json') as f:
    spec = json.load(f)
chart = alt.Chart.from_dict(spec)
```

Not sure if that is the way to do it in Altair version 2.2. Please clarify.

**Comment by afonit** [comment]
@manojkumargandikota ,
perhaps you are running into this:
```
Backward-incompatible changes
alt.SortField renamed to alt.EncodingSortField 
```
See here:
https://github.com/altair-viz/altair/issues/1106

**Comment by manojkumargandikota** [comment]
Thanks for the quick response. But somehow it is working when I give the same code in json format to Altair.

**Comment by jakevdp** [comment]
> somehow it is working when I give the same code in json format to Altair.

That makes sense – the JSON encoding has no reference to the class name, and Altair only evaluates its contents. The class name is the only thing that changed here.

**Comment by manojkumargandikota** [comment]
Thanks folks. Got it.
