### ISSUE TITLE
Is there any method to export Chart spec without data?

### ISSUE THREAD

**Issue by tamuhey** [altair-viz/altair#1130]
Hi, I am new to altair.

Is there any method to export Chart spec without data?

Now, I  write the below and do this, but it is pain.
```python
d=chart.to_dict()
d.pop("datasets")
```

So I want to do this with one method, like `chart.spec`.

**Comment by jakevdp** [comment]
You can export a chart without data if you don't supply any data to the chart in the first place. For example:
```
>>> chart = alt.Chart().mark_point().encode(x='column:Q')
>>> chart.to_dict(validate=False)
{'$schema': 'https://vega.github.io/schema/vega-lite/v2.6.0.json',
 'config': {'view': {'height': 300, 'width': 400}},
 'encoding': {'x': {'field': 'column', 'type': 'quantitative'}},
 'mark': 'point'}
```
Note that we need ``validate=False`` because according to the schema, a vega-lite spec is not valid without data specified.

**Comment by tamuhey** [comment]
Thank you for your kind reply!

I would like a method to export spec conveniently, even after plotting with chart, so that save as a template.

**Comment by jakevdp** [comment]
Thinking about it a bit, I could see how this would be a useful feature to have. We could probably implement it as a custom data transformer, though it might involve some subtle issues with nested datasets within compound charts.
