### ISSUE TITLE
`vega` version 3

### ISSUE THREAD

**Issue by domoritz** [altair-viz/altair#1132]
I’d like to make a new vega package release because I want to build things with Vega-Lite 3. Would it make sense to update the docs to ask people to install `vega>=1.0.0`? How should we go about this issue in the future? I don't want to make a new package just because of the version change.

**Comment by jakevdp** [comment]
Maybe we could wrap more than one version of vega/vega-lite into the ipyvega package, so we can provide entrypoints for both versions at once. It would double the size of the install, but I think the installation is not too large at the moment.

**Comment by domoritz** [comment]
I'm worried about how this will work in the future when we have more than two versions. We would still need a policy for deprecating old versions so I wonder what would be the cleanest way forward. Or do you think this is temporal and thus warrants an exception?

**Comment by jakevdp** [comment]
Yeah, that's an issue... My first thought is that we could plan to make certain the vega package supports whatever vega-lite versions are available in Altair (currently v1 and v2, changing to v2 and v3 in the next release) then it would mostly be transparent to users.

**Comment by domoritz** [comment]
My hope was that we could ask people to install the right vega package.

Altair 2 would work with vega >=1 <2. Altair 3 would work with vega >=2. Npm addresses this issue with peer dependencies but I'm not aware of any equivalent in Python.

**Comment by jakevdp** [comment]
OK, makes sense.

**Comment by domoritz** [comment]
Another problem is Jupyterlab. They already updated to Vega-Lite accidentally.

**Comment by domoritz** [comment]
I reverted to Vega-Lite 2 in https://github.com/jupyterlab/jupyterlab/pull/5342. 

I see that the docs in https://altair-viz.github.io/user_guide/display_frontends.html#display-notebook still expect users to install any version of the `vega` package. Should we update this and then in a week or so make a release of a new `vega` package with Vega-Lite 3?

**Comment by stonebig** [comment]
a new release with vega3 would be really nice.

**Comment by domoritz** [comment]
@jakevdp can I update without breaking Altair users?

**Comment by domoritz** [comment]
Oh, I didn't know we can just make a prerelease version. I'll do that.

Instructions: https://packaging.pypa.io/en/latest/version/
