### ISSUE TITLE
alt.Repeat - create a grid of charts

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1133]
Hi Jake,

In the docs you have a nice [repeating example](https://altair-viz.github.io/user_guide/compound_charts.html) that I am trying to learn from. But suppose I have a simple dataFrame like this:

```python
df=pd.DataFrame({'year': [1,2,3], 'school 1': [10,20,30], 'school 2': [15,6,25], 'school 3': [120,202,302], 'school 4': [152,6,225]})
```
and I would like a 2x2 grid where for each chart "year" is on the x axis and each charts show a line for a given school. So basically, one field is held constant. I can accomplish this by doing the following, but is there a better, more "Altair-ic" way to do this?

![visualization 19](https://user-images.githubusercontent.com/4624246/45380456-be941180-b5d0-11e8-983c-fe039e94b603.png)

```python
y1=alt.Chart().mark_line(point=True).encode(
    x='year',
    y='school 1',
)

y2=alt.Chart().mark_line(point=True).encode(
    x='year',
    y='school 2',
)

y3=alt.Chart().mark_line(point=True).encode(
    x='year',
    y='school 3',
)

y4=alt.Chart().mark_line(point=True).encode(
    x='year',
    y='school 4',
)

alt.vconcat((y1|y2), (y3|y4), data=df)
```

**Comment by jakevdp** [comment]
Yep, what you're describing is more or less a wrapped facet, and it's not yet available in Vega-Lite or Altair.

**Comment by Alcampopiano** [comment]
Thanks Jake.

**Comment by Alcampopiano** [comment]
For anyone looking for an example until this functionality is in VL/Altair. There are various solutions [here](https://stackoverflow.com/questions/50164001/multiple-column-row-facet-wrap-in-altair/52299898#52299898) and my attempt is the following. Note that the DataFrame in this case has three columns and is in long form (see `df.melt`)

```python
numcols=3 # specify the number of columns you want 
all_categories=df['Category_Column'].unique() # array of strings to use as your filters and titles

rows=alt.vconcat(data=df)
numrows=int(np.ceil(len(all_categories) / numcols))
pointer=0
for _ in range(numrows):

  row=all_categories[pointer:pointer+numcols]
  cols=alt.hconcat()

  for a_chart in row:

     # add your layers here
     # line chart
     line=alt.Chart().mark_line(point=True).encode(
        x='variable',
        y='value'
     ).transform_filter(datum.Category_Column == a_chart).properties(
        title=a_chart, height=200, width=200)

     # text labels
     text=alt.Chart().mark_text().encode(
        x='variable', 
        y='value'
     ).transform_filter(datum.Category_Column == a_chart)

     both = line + text
     cols |= both

  rows &= cols
  pointer =+ numcols

rows

```
![visualization 22](https://user-images.githubusercontent.com/4624246/45440494-6c172b80-b68a-11e8-8393-4274a07bbf0d.png)

**Comment by mattijn** [comment]
I haven't seen this documented on SO of GitHub issues, but one can also use `repeat` instead of  `column` or `row` in `repeat`:

```python
import altair as alt
from vega_datasets import data

cars = data.cars.url

alt.Chart(cars, width=200, height=150).mark_bar().encode(
    x=alt.X(alt.repeat('repeat'), type='quantitative', bin=alt.Bin(maxbins=20)),
    y='count()'
).repeat(
    repeat=["Horsepower", "Miles_per_Gallon", "Acceleration", "Displacement"], 
    columns=2
)
```
<img width="511" alt="image" src="https://user-images.githubusercontent.com/5186265/110169136-87e18f80-7df8-11eb-8fce-fc5beca66bce.png">
