### ISSUE TITLE
specify the shape based on data

### ISSUE THREAD

**Issue by cubicme** [altair-viz/altair#1135]
Hi,
Is there a way to specify the mapping between the values and marker shape? Right now i think it's if i use a series for shape channel, they will be picked automatically. Is it possible for example to say use 'triangle-up' for positive value and 'triangle-down' for the negative ones? Or just specifying what marker to use for each possible value?

Thanks

**Comment by iliatimofeev** [comment]
```python
import altair as alt
import pandas as pd 

df = pd.DataFrame({"val_x":np.random.randint(-100,100,30),
                   "val_y":np.random.randint(-100,100,30)})
alt.renderers.enable('notebook')

alt.Chart( df ).mark_point(
).encode(
    x='val_x',
    y='val_y',
    shape = alt.Shape(
       "val_y:N",
        bin=alt.BinParams(maxbins=2),
        scale = alt.Scale(range=["triangle-down", "triangle-up"])),
)
```
![visualization 54](https://user-images.githubusercontent.com/11561581/45563274-7f2a2700-b855-11e8-9656-d4cfd16b345e.png)

**Comment by cubicme** [comment]
Nice. Thank you! I couldn't find any usage of Shape class anywhere.

**Comment by jakevdp** [comment]
It's probably not all that well documented – if you want to contribute that to the documentation it would be appreciated!
