### ISSUE TITLE
set different label color for dual y axis

### ISSUE THREAD

**Issue by cathyhyz** [altair-viz/altair#1138]
I have this code that produces a plot with two y-axes sharing the same x-axis.

```
base = alt.Chart(RevenueAll).encode(
    alt.X('stat_date:T', axis=alt.Axis(grid=False, title='Date'))
)

line = base.mark_line(point=True).encode(
    alt.Y('Revenue:Q', axis=alt.Axis(format='$')),
    alt.Color('rev_type:N', legend=alt.Legend(title=""), scale=alt.Scale(scheme='tableau20'))
).interactive()

point = base.mark_point().encode(
    alt.Y('QTD:Q', stack=None, axis=alt.Axis(format='$', grid=False, title='QTD Revenue')),
    alt.Color('qtd_type:N', legend=alt.Legend(title=""))
).interactive()

alt.layer(
    line,
    point
).resolve_scale(
    y='independent'
).configure_axis(labelColor='orange')
```

![image](https://user-images.githubusercontent.com/42592966/45774830-e69ff800-bc02-11e8-80a8-996ecf140e3f.png)

The end goal is the two y-axes should have two different colors (corresponding to the color of the lines) so that people will be clearer which axis they are looking at. More specifically, here I want to set the color on the left y-axis as orange and blue for the right y-axis.

Right now I' setting `configure_axis(labelColor='orange')` on the LayerChart object because I was not able to set it on individual layers, it gave me this error `Objects with "config" attribute cannot be used within LayerChart.`

In addition to that, it would be even better if the tick colors could be tethered to whatever color it is for the line (left y-axis)/point (right y-axis). 

Thanks in advance!

**Comment by cathyhuiyuzheng** [comment]
The first problem solved by setting:
`.configure_axisLeft(labelColor='orange').configure_axisRight(labelColor='blue')` at the LayerChart object. 

So my question now reframed to how to set the color automatically instead of specifying 'orange' or 'blue'. Since I'm using `tableau20` as color palette, it would be good if there's some functionality like this:
```.configure_axisLeft(labelColor=alt.Scale(scheme='tableau20')[0]).configure_axisRight(labelColor=alt.Scale(scheme='tableau20')[2])```

where I can extract the color name from the color palette and set the labelColor equals to that color.

**Comment by cathyhyz** [comment]
alright, I'm using matplotlib colormaps to pick colors first. Thank you!
