### ISSUE TITLE
Chrome version must be >= 68.0.3440.0

### ISSUE THREAD

**Issue by c0nn3r** [altair-viz/altair#1139]
I was attempting to save a graph using the following code taken from the overview section in the altair documentation:

```python
import altair as alt
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).save('chart.png')
```

However, I get an error when this code is ran from a ipython REPL (it also fails when run in a Python script)...

```python
SessionNotCreatedException: Message: session not created: Chrome version must be >= 68.0.3440.0
  (Driver info: chromedriver=2.42.591059 (a3d9684d10d61aa0c45f6723b327283be1ebaad8),platform=Mac OS X 10.13.6 x86_64)
```

I installed both `chromedriver` and `geckodriver` using brew (in the case of `chromedriver` I used `brew cask install`, but it should be the same). My Python version is `3.6.6` and I installed altair using `pip`.

Any help would be appreciated and please let me know if you need any additional information.

**Comment by jakevdp** [comment]
I don't have any suggestions beyond the one in the error message.

**Comment by c0nn3r** [comment]
Sorry for bothering you, seems like my work laptop cannot upgrade to the version of Chrome needed.

**Comment by jakevdp** [comment]
Maybe an older version of chromedriver would be compatible with an older version of Chrome?

**Comment by c0nn3r** [comment]
That's a good idea, I will give that a try!
