### ISSUE TITLE
render Altair using reticulate in jupyter-lab

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#1141]
Hi! 

We succesfully used Altair from within RStudio using [reticulate](https://rstudio.github.io/reticulate/) and [vegawidget/altair](https://github.com/vegawidget/altair). Now we tried to do the same, but now from within JupyterLab. It seems there are some issues regarding rendering.

We have tried the following:

```R
require(reticulate)
    Loading required package: reticulate
```

```R
library(altair)
alt$renderers$enable('jupyterlab')
    RendererRegistry.enable('jupyterlab')
```

```R
vega_data <- import_vega_data()
cars <- vega_data$cars()
```

```R
chart <- alt$Chart(cars)$mark_point()$encode(
    x = "Horsepower:Q",
    y = "Miles_per_Gallon:Q",
    color = "Origin:N"
)
```

```R
chart
    No renderer could be found for output. It has the following MIME types: 
```

```R
chart$encoding
    EncodingWithFacet({
      color: Color({
        shorthand: 'Origin:N'
      }),
      x: X({
        shorthand: 'Horsepower:Q'
      }),
      y: Y({
        shorthand: 'Miles_per_Gallon:Q'
      })
    })
```
Screenshot:

![reticulate_lab](https://user-images.githubusercontent.com/5186265/45824974-73c17a80-bcf1-11e8-9206-4c692e228dd4.PNG)

**Comment by jakevdp** [comment]
Hmmm... is there any mechanism within reticulate for mimetype-based output?

I think the way to go is to somehow get it to output the same thing that ``chart._repr_mimebundle_()`` does in Python. Then it should be able to tap into the existing jupyterlab-vega display mechanism.

**Comment by mattijn** [comment]
I don't know if it is possible to access a private module using reticulate. Upon first sight not, posted an issue at https://github.com/rstudio/reticulate/issues/355

**Comment by mattijn** [comment]
Accessing private modules is possible using 
```
chart$`_repr_mimebundle_`
```
Trying the following
<img width="696" alt="repr_mimebundle" src="https://user-images.githubusercontent.com/5186265/45846093-25c76980-bd27-11e8-8380-adbd0812a269.png">
and got some output! 

But not sure how to continue to serve this into the 'existing jupyterlab-vega display mechanism'

**Comment by jakevdp** [comment]
``_repr_mimebundle_`` is a function that returns a mimebundle.

Somehow you need to teach the reticulate object how to represent itself as a mimebundle.

**Comment by jakevdp** [comment]
I'm not certain whether mimebundle representations are supported in the R kernel.

**Comment by mattijn** [comment]
how you call this `_repr_mimebundle_()` in Python? It needs some arguments:
```Python
TypeError: _repr_mimebundle_() missing 2 required positional arguments: 'include' and 'exclude'
```

**Comment by jakevdp** [comment]
Here's an example:
```python
class Foo(object):
    def _repr_mimebundle_(self, include, exclude):
        return {'text/html': "<font color='red' size=20>FOO</font>"}
    
Foo()
```
If you run this in Jupyterlab, it will recognize the ``text/html`` mimetype, and render the output as HTML.

For Altair objects, the mimetype is ``'application/vnd.vegalite.v2+json'`` and the JupyterLab vega-lite extension knows how to take the output and render it with vega-lite.

**Comment by jakevdp** [comment]
You can pass ``include=None, exclude=None`` if you want to call the method explicitly.

**Comment by jakevdp** [comment]
The trick will be to figure out how to get the R kernel to recognize mimebundle rendering.

**Comment by jakevdp** [comment]
The issue is not in printing the mimebundle... the issue is in making the kernel recognize that there is a mimebundle-based rendering available. In the Python kernel, the presence of the ``_repr_mimebundle_()`` method is the key to this: any object that defines that method will be displayed in that way rather than via the normal ``__repr__()`` mechanism.

In the R kernel, there may or may not be an existing path to that, but that will be the key to making Altair plots display natively.

**Comment by jakevdp** [comment]
The Jupyter extension is here: https://github.com/jupyterlab/jupyterlab/tree/c3fff81d3f053c4f94e84263ae785eda56cb55aa/packages/vega4-extension

It is enabled by default and will display any object that supports mimetype-based rendering and has an appropriate vega mimetype.

**Comment by jakevdp** [comment]
I'd start with the simple ``Foo`` class I defined above. It you can wrap that in reticulate and make it so that it displays the correct HTML in the frontend, then I imagine the rest will come for free.

**Comment by mattijn** [comment]
Got it!
<img width="725" alt="ouputewf" src="https://user-images.githubusercontent.com/5186265/45914853-222d0300-be4b-11e8-98d9-1e2a07b06798.png">
full notebook: https://github.com/mattijn/pynotebook/blob/master/r_altair_reticulate_mimebundle.ipynb

**Comment by mattijn** [comment]
Mobile-friendly notebook: https://nbviewer.jupyter.org/github/mattijn/pynotebook/blob/master/r_altair_reticulate_mimebundle.ipynb

**Comment by flying-sheep** [comment]
Hi guys, I made a notebook that seems to work as far as I can understand:

https://gist.github.com/flying-sheep/ff67d4a37a59785b7b0875dbb521dd1b

What doesn’t work is rendering.
