### ISSUE TITLE
Stacked Area Chart Tooltip Not Working

### ISSUE THREAD

**Issue by cathyhyz** [altair-viz/altair#1142]
I think the stacked area chart tooltip is broken since the value was wrong and it doesn't change as you hover across different x. Here are some screenshots from the Example Gallery:

https://altair-viz.github.io/gallery/simple_stacked_area_chart.html

![image](https://user-images.githubusercontent.com/42592966/45838602-f8e36a00-bcc6-11e8-92ac-6c44e630245f.png)

![image](https://user-images.githubusercontent.com/42592966/45838666-23cdbe00-bcc7-11e8-95e9-99f2666a5f9a.png)

Plus, it would be really nice if there could have an aggregation value in the tooltip.

**Comment by jakevdp** [comment]
There is no tooltip specified in that chart.

The reason the tooltip shows up in Jupyterlab is that it mistakenly included a pre-release of Vega-Lite 3 in the latest jupyterlab vega extension release.

If you want to control the content of the tooltip, you can use the ``tooltip`` encoding; see an example here: https://altair-viz.github.io/gallery/scatter_tooltips.html

**Comment by jakevdp** [comment]
The jupyter extension fix is here: https://github.com/jupyterlab/jupyterlab/pull/5342

**Comment by dmohns** [comment]
> There is no tooltip specified in that chart.

@jakevdp Would it be possible to add tooltips to Area charts or were they left out intentionally in Altair? As far as I can see Vega-lite has this functionality.

**Comment by jakevdp** [comment]
Vega-Lite 3 has this functionality, but not Vega-Lite 2. The current release of Altair is based on Vega-Lite 2. When Altair 3 is released, it will have this functionality as well.

**Comment by jakevdp** [comment]
Default tooltips existed briefly in Vega-Lite 3, but then the decision was made to remove them. In Altair, you can continue to specify tooltips explicitly.
