### ISSUE TITLE
sorting with interaction - potential bug

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1145]
Hi Jake,

The example below shows a bar chart on the left cross filtering a bar chart on the right. 

The issue is that the chart on the right is only sorted in the initial and filtered views. Once I "click off" to return to the original view, the chart on the right is no longer sorted. This is not an issue in the VL editor. Any idea what is happening here?

#### initial view (looks great)
![visualization 46](https://user-images.githubusercontent.com/4624246/45977540-ef843580-c017-11e8-95b8-80155ec02394.png)
---
#### filtered view (looks great)
![visualization 47](https://user-images.githubusercontent.com/4624246/45977619-2ce8c300-c018-11e8-9523-3085690c3382.png)
---
#### full view after filtering (not looking sorted anymore)
![visualization 48](https://user-images.githubusercontent.com/4624246/45977641-370ac180-c018-11e8-929b-0ae1ed1edb82.png)
---

```python
import altair as alt
import pandas as pd

df=pd.DataFrame({'student name': ['allan', 'john', 'paul','george','ringo','yoko','keith','mick','charlie'], 
                 'school_code': ['sch1', 'sch2', 'sch3', 'sch1', 'sch2', 'sch3', 'sch1', 'sch2', 'sch3'], 
                 'totals_absences': [3,3,3,4,4,5,6,7,11]})
df=df.sort_values('totals_absences')
single=alt.selection_single(encodings=['color'])
cond=alt.condition(single, 'school_code', alt.value('lightgray'),legend=None)
max_val=int(df['totals_absences'].max())

sch=alt.Chart().mark_bar().encode(
    x=alt.X('sum(totals_absences)', title=None),
    y=alt.Y('school_code', sort=alt.EncodingSortField(op='sum', field='totals_absences', order='descending'), title=None),
    color=cond,
    size=alt.Size('mean(totals_absences)', legend=None)
).add_selection(single).properties(title='Number of Absences by School')

stud=alt.Chart().mark_bar().encode(
    x=alt.X('totals_absences', title=None, scale=alt.Scale(domain=[0,max_val])),
    y=alt.Y('student name', sort=alt.EncodingSortField(op='count', field='totals_absences', order='descending'),title=None),
    color=alt.Color('school_code', legend=None),
    tooltip=['school_code', 'student name']
).transform_filter(single).properties(title='Number of Absences by Student')

text=alt.Chart().mark_text(color='black', align='left').encode(
    x=alt.X('totals_absences', scale=alt.Scale(domain=[0,max_val])),
    y=alt.Y('student name', sort=alt.EncodingSortField(op='count', field='totals_absences', order='descending')),
    text='totals_absences',
    tooltip=['school_code', 'student name']
).transform_filter(single)

stud_text=alt.layer(stud,text)
alt.hconcat(sch,stud_text, data=df)
```

**Comment by jakevdp** [comment]
Hi,
This looks like a vega-lite issue. You can report it in that repository if you'd like – if you're not comfortable with that, please let me know and I can do it myself.

**Comment by Alcampopiano** [comment]
Thanks Jake. I'm happy to post it over there. Thanks for getting back.

ps) I've done two Altair workshops in the past two months and people are really loving it.

**Comment by Alcampopiano** [comment]
Apparently fixed in VL 3 as suspected. So I assume once Altair is updated this won't be an issue.
https://github.com/vega/vega-lite/issues/4172

**Comment by jakevdp** [comment]
Yep, as soon as VL3.0 is released we'll work on getting an Altair release that supports it,

**Comment by joelostblom** [comment]
@Alcampopiano I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
