### ISSUE TITLE
Does altair allow you to add datapoints via clicking?

### ISSUE THREAD

**Issue by tumble-weed** [altair-viz/altair#1146]
I have a use case where:
1. on a time chart, I'd like to click to add various types of input (multiple choice, linear scale etc.). on the time chart this just shows up as a marker. but i can click on it to see details
2. I'd like it let me pan to the past and the future and add points, and see previously added points.
3. I can drag the points in case i misplaced them, or double click to see the detailed input.

**Comment by Alcampopiano** [comment]
Jake may correct me if I'm wrong but I don't believe Altair/Vega-lite allow you to add arbitrary marks to a chart via clicking. 

Check out [bqplot](https://github.com/bloomberg/bqplot). For example, here is an example where you can add or move points in a scatterplot, and the corresponding model is updated automatically.

[scatter binder](https://hub.mybinder.org/user/bloomberg-bqplot-380nygar/notebooks/examples/Marks/Pyplot/Scatter.ipynb)

**Comment by jakevdp** [comment]
No, there's no mechanism for that kind of interaction at the moment.

**Comment by mattijn** [comment]
In Vega this is possible btw. A few months ago I made a use-case where you can:
- drag a point when mouse-down on point
- insert a point with shift+click on a location in the chart
- remove a point with alt+click on a point (on Mac this is option+click).

Vega-editor [long-url](https://vega.github.io/editor/#/url/vega/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6SgBY6AK1jcAdpAA04KAHdGAExbYwADgAMuxREgpG1fFoBM+w1ELo1axjOpaArDchr0eTDgDaShCgECFQMuioyFqe3ugA+oTcTniwCoEhkBToADasyKn+wJAAHpYGUACeWgDsdK4AvvJgRaU4AGzlkFXtdG2NzSVaAJwWTV1a2vUAujahkLJaAaGhRXgATqbUyGvRsGvwClCo3I4AZt1QewdjWbn50Wpr6C6N6SuQ65vb0fZqAApJGR4Q6QJywbbAnCQX4A5KQV7LEKrDbULY7KFrNCwoEgzHHKjRPHY4H1N5gKbpUkQGZKSCwUzhbIFMBLJFkyDhSK7fZpRGZHJ5aIAQi8eFYqF5y3mcn8ZKCkGQVCBzMgAAFRfFEslYAlAXgsMdWOC1NxlHIxqxCKKolDReL4bNlkVFchldFVDITcoDdwjchLSDLdbhXaJVTlhTQgi2XzOTaoI9npK5rdBbbvPbHUYFrLEUE5RkXW6oR6vT6-fjkE1S6by8bTeaC0Yg9545BgMUcE4qGs8AAKADkxQQOWQA6a8GyEUIfeKfYAlE1yqoNIh54uwBUuzIe-2BxUR9kxxOp6gZxUF-IDCYzHh1-VIAXw6FIyFo-nYxE2zC9cmMjmWQLYI8yMIsUmiQ16zNPwwLodhWAIWRYDAAAyFCwFg2BEEYU48AAaWQCpUPQoVYJyfDCKmYArAfLMpRbPA2w7bdd0HYd4FHccwDndcmi3MBuwhQcDw4o8uIve9HxA58QlfCB32adk40JLFfzo6VFiApsoDAlVIOQL0ZBgpU8DghC8CQ4iwFIky6CwnCKKItCMNs8iCIqKiaL-PkGLbUMpLzGTqUpUIlBpIxD3uXMYylZSoXY0dvKgPAKkINtsicZB0B2dSnmcNsV00dSAC9tm4LRThycF1JNDAnEWcoAEZ9DksAFOAuY4sqSKko+VL0sy7LeryrZohvcx1JkRh4HjdY8hKsqtDmqt2Vq9B6v8JrdFa8NwqgdBiiiwCVnZbgNldSEoHYbhEIldSevinr1LwaaAGsAGFfRxHBmue5gj2iAARRhYB8GQZpZVApl66gNjUJa1nm9lXXgE54w6qVYfULQMZ8q1Wxxul1m4V70f5O5ogAYiGGmHUuYnSYAdXUTQcCKVN410OhGvqIK3zoowXvgV7mSKXzCdBtYSbJjnonYKdhfhXmBagKd2GQJkce0yBxbZ7SjFORhsmyQnZaheX0EVhSQOhZwAbZ8m0zAXRrbzSBTlkPAAGVGFK02BXjRqLD5qMnxVj5-rJ3WBg9oEfb9h2zbARrRF512jDWjbFJA5t8cYiWGZlgO5YV166aJqWmZZxB-Ypn7eafMkZPa07zu+1XkFw3qHu60Soj+4XPtYdu2j+vB7agAAJZBTHwSGAGoADkAEE-mh9SsfhnBlvUlG0a1m3N4PnOdbzsnJel2uncganaf6CvpeZ1cr857mG+k8OhZFwno6KC-SZfiXS2Zc07hzVhrUW2tf76ygIbY2gDzalwdDA221AJ7s2LjgF2Ks5ix29r7Iuddk7B20iHNqn9I4-zPoTPB8dCFOxTqAgsnhuB1RlNnE+v8H4AMTpgq6SD77-2QE-VmAwk48zIXzZuYUPAYDWN-aKH4pQpTStEDKMh+7smSNsS2L0CQ4EqkyFafJThSwlA7DUDxYi6m1Mgvk0hew0MYBrLeUBSiuwVODfeesbbQJzm4iWfdogJQBmMQ2Ljgl2JPhcP+QSoQiUSmE5x2RXHjHThkIRCCoCU1OKceA8A2htCiTbIRIia68KISQ6STdKSOlxmEL8VifA2OVC04Ez1+q7AqKga6Jt1KmNYYTSx6ZmlajdB4hxl0ijhJSZEjxe81Do2YX4k+rQBg9xKE9WByTUnuJwZUQJiV4lbPdjs6IVR0kRULlkm+uT8mFOKW7OBJsKnXxyXkgpRTLn00rsI6uWSeZh2YYgbgPZj4lMLmUrJDR9ncPoW2TE8NvmnPga8hFBl4SN0RM3Op7IVHfkxJgdS2injwD0fGQx1V2QDPMQMYZCZrFjPAhMs6UzTkRPio80CXjFngvotQnxqzDkT02UEpJHKAnIpiXSOJvdEnbIlWk2FFQLDCrbAk0JUAk7YO1s8m57zckPORc8gA8nYeAzBpXau5g0LFyxpHBXqEAA)

**Comment by Alcampopiano** [comment]
@mattijn that's awesome

**Comment by joelostblom** [comment]
Closing as this feature would need to be added in Vega-Lite, and there is nothing we can do on the altair side of things.
