### ISSUE TITLE
Is there a way to make squares and circles with a size actually that size relative to the axis?

### ISSUE THREAD

**Issue by tweakimp** [altair-viz/altair#1148]
![imgname](https://i.imgur.com/MDIOtS2.png)

I have this image. I want the squares to be exactly as wide and tall as their size says (which i assumed was the case), but they are just way smaller.
Is it possible to make a 5 size square actually 5 units wide and tall compared to the axis?

**Comment by Alcampopiano** [comment]
Not really an answer but have you tried fooling around with `legend` in the size encoding channel? 

```python
.
.
.
    size=alt.Size('your_column',
                  scale=alt.Scale(domain=[0,100], range=[1,300]),
                  legend=alt.Legend(values=[0, 50, 100]))

```

It would be nice if there was a small but complete example you could share as well if possible.

**Comment by jakevdp** [comment]
The legend scale is definitely the place to do this. I don't know of an easy way to automativally sync this to the axis scale... you might be able to hack it by adjusting both the legend scale and axes scales to match.

**Comment by tweakimp** [comment]
What I actually want to do is to map buildings with their sizes on a grid so see where there are spaces between them. Here is the code so far. Maybe you have a better idea on how to do this :)

```python
import altair as alt
import pandas as pd

d = {
    "medium1": [31.5, 113.5, 3],
    "medium2": [31.5, 116.5, 3],
    "medium3": [31.5, 119.5, 3],
    "medium4": [31.5, 124.5, 3],
    "medium5": [38.5, 113.5, 3],
    "medium7": [38.5, 119.5, 3],
    "small1": [29.0, 114.0, 2],
    "small2": [29.0, 116.0, 2],
    "small3": [29.0, 118.0, 2],
    "small4": [29.0, 120.0, 2],
    "small5": [29.0, 124.0, 2],
    "small6": [29.0, 126.0, 2],
    "small7": [36.0, 113.0, 2],
    "small8": [36.0, 115.0, 2],
    "small9": [36.0, 117.0, 2],
    "big": [25.5, 117.5, 5],
}
df = pd.DataFrame(data=d).T
df.columns = ["x", "y", "size"]
print(df)
chart = (
    alt.Chart(df)
    .mark_square()
    .encode(
        alt.X("x:Q", scale=alt.Scale(domain=(24, 40))),
        alt.Y("y:Q", scale=alt.Scale(domain=(110, 128))),
        alt.Size("size:Q"),
    )
)
```

**Comment by joelostblom** [comment]
@tweakimp I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
