### ISSUE TITLE
Display issue in Jupyter Lab with faceted charts: align = 'none' not working

### ISSUE THREAD

**Issue by lcvriend** [altair-viz/altair#1150]
Thank you for this amazing library.

I ran into an issue using Altair in Jupyter Lab (v0.32.1) when trying to remove the space between faceted charts. It is unclear to me from where this issue arises, but if it can be resolved I would really like to know how.

The issue can be illustrated with the following simple example:

```
import pandas as pd
import altair as alt

data = pd.DataFrame(data={'cat':['A', 'A', 'A', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'C', 'C'],
                          'att':['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l'],
                          'val':['x', 't', 'x', 'z', 'x', 'u', 'y', 'v', 'w', 's', 's', 't']})

alt.Chart(data).mark_rect().encode(
    x='val:N',
    y='att:N',
).facet(
    column='cat:N',
    align='none',
).resolve_scale(
    x='independent',
    y='independent',
)
```

Jupyter notebook outputs this for me as:
![visualization-jupyter](https://user-images.githubusercontent.com/43742775/46278507-9dd33200-c566-11e8-92e3-d0da00ae946b.png)
The `align='none'` does nothing.

When I open the graph in the Vega editor, this is the output:
![visualization-vega](https://user-images.githubusercontent.com/43742775/46278589-decb4680-c566-11e8-979d-f8b54644b9a5.png)
Now `align='none'` properly removes the spacing between the faceted graphs.

Any ideas on what causes this quirk in Jupyter Lab and how it may be resolved?

**Comment by Alcampopiano** [comment]
@lcvriend you could try updating jupyterlab as this chart works as expected in JL 0.33.4 and Altair 2.2.2

**Comment by lcvriend** [comment]
Thank you very much. I have upgraded Jupyter Lab and now the graph is displayed as expected.
