### ISSUE TITLE
`domain` doesn't work with histogram?

### ISSUE THREAD

**Issue by dhuppenkothen** [altair-viz/altair#1151]
I am not sure whether this is a bug or not, but I've been trying to format several plots to have the same x-axis, and have been running into trouble with the histograms. 

Here's an example of the code I've been using:

```
np.random.seed(42)
x = np.random.normal(0.0, 1.0, size=4000)

df = pd.DataFrame({"x":x})

nbins = 30 # number of bins
min_x = -5.0
max_x = 5.0

step = (max_x - min_x)/nbins

xrange = (min_x, max_x)

alt.Chart(df).mark_bar().encode(
    x = alt.X("x:Q", bin=alt.Bin(step=step), scale=alt.Scale(domain=xrange)),
    y = alt.Y("count()")
)
```

I would have expected that this shows me 30 bars between -5 and 5 (some of which are zero), but instead it shows me 22 bars between -3.3 and 4.0 (see image below). So it looks like it might actually make the 30 bins, but doesn't plot all of them.

Is this expected behaviour? Is there a way to force the x-axis in this case to have the range I need it to have?

![image](https://user-images.githubusercontent.com/5237391/46384335-2f779800-c66a-11e8-936d-daecc29ffc3a.png)

**Comment by jakevdp** [comment]
Reminds me of https://github.com/vega/vega-lite/issues/3575, though this should be fixed in the most recent release.

**Comment by jakevdp** [comment]
I just tried this with a recent version of vega-lite, and it works correctly. You may have to update your frontend extension: ``pip install -U vega`` for jupyter notebook, or ``pip install -U jupterlab`` for jupyter lab.

**Comment by domoritz** [comment]
@dhuppenkothen Does updating `vega` fix your issue?

**Comment by jakevdp** [comment]
Domain works in Altair 3
