### ISSUE TITLE
thickness is additional Property

### ISSUE THREAD

**Issue by HCelion** [altair-viz/altair#1154]
Hi, according to the documentation of mark_tick, the thickness keyword should be able to change the thickness of the tick marks.
When running for example

```
import altair as alt
from vega_datasets import data

df = data.iris()

alt.Chart(df).mark_tick(thickness = 5).encode(x = 'petalLength', y = 'petalWidth')`
```

I do get the error message
```
        altair.vegalite.v2.schema.core.MarkDef, validating 'additionalProperties'  
Additional properties are not allowed ('thickness' was unexpected)       
```

The altair version is `altair==2.1.0`  from pip. 

Is this a versioning issue or perhaps a bug?  
Thanks for a great package!

**Comment by afonit** [comment]
@HCelion ,
I am on altair: '2.2.2'
I ran your code and it worked fine and produced the plot, so it may be a version issue.

**Comment by jakevdp** [comment]
Yes, @afonit is correct. The thickness property was added in Altair version 2.2

**Comment by HCelion** [comment]
Thanks!
