### ISSUE TITLE
Altair - `impute` in encodings

### ISSUE THREAD

**Issue by tjbergst** [altair-viz/altair#1157]
I am new to Altair, and so far I am really enjoying it (coming from matplotlib).

I am working with a time series dataset spanning a year where I have irregular occurrences of ~150 different strings. I used pandas to aggregate by week and count the number of occurrences for each string in a new column. 
```         
   date       string  count
0  2017-10-01   str1   1
1  2017-10-01   str2   2
2  2017-10-08   str7   1
3  2017-10-15  str22   4
4  2017-10-15  str78   1
```

I would like to be able to view these as a continuous line vs time but since there are no entries for weeks where a string did not occur, the lines appear broken and disconnected. I tried using pandas to unstack the strings, fillna's and melt back in but this took my dataset from ~8000 lines to well over a million.

I managed to find something in the Vega-Lite documentation, [impute](https://vega.github.io/vega-lite/docs/impute.html), but I couldn't find it anywhere under the Altair API. I tried exporting my chart as html and manually adding the Vega encodings and it gets very close to what I am looking for.

Is `impute` part of the Altair API or is there a plan to add it?
Is there another solution with the existing Altair API to achieve something like this?

I appreciate any help and all of the amazing work you guys have done so far.

**Comment by jakevdp** [comment]
The ``impute`` attribute is part of Vega-Lite version 3, which has not yet been released. Once Vega-Lite 3 is released, we plan to update Altair to version 3 and include the new features.

**Comment by jakevdp** [comment]
You can read about the impute transform in Altair 3.0 here: https://altair-viz.github.io/user_guide/transform.html#user-guide-impute-transform
