### ISSUE TITLE
Adding text to bar chart throws 'data is a required property' error

### ISSUE THREAD

**Issue by tzbaris** [altair-viz/altair#1158]
When I run this code, I get a 'data is a required property' error (pasted below the code). When I just try to run the bar graph with data specified within Chart() it works. 

```python
bars = alt.Chart().mark_bar(stroke='transparent').encode(
    alt.X('model', scale=alt.Scale(rangeStep=12), axis=alt.Axis(title='')),
    alt.Y('ratio:Q', axis=alt.Axis(title='ratio', grid=False)),
    color=alt.Color('model:N', scale=alt.Scale(range=["#EA98D2", "#659CCA", '#5bb3a4'])),
    column='time:O', 
)

text = alt.Chart().mark_text(
    align='left',
    baseline='middle'
).encode(
    y = alt.Y('ratio'), 
    x = 'model',
    text='ratio')

alt.layer(bars, text, data=df_concat).configure(
    legend=LegendConfig(labelFontSize=16, titleFontSize=16, symbolSize=100, labelFont='Lato'), axis=AxisConfig(labelFontSize=16, tickSize=16, labels=True, titleFontSize=16))
```

Error Message:

```
SchemaValidationError: Invalid specification

        altair.vegalite.v2.api.Chart, validating 'required'

        'data' is a required property
```

**Comment by jakevdp** [comment]
I cannot reproduce this error, though it takes a bit of guesswork on my end because you did not specify what ``df_concat`` is.

That error would happen, for example, if you tried to display ``text`` by itself, rather than in a layer with specified data. Is it possible that you were executing different code than you pasted here?

In either case, if you could create a self-contained script that reproduces this error, that would be helpful in tracking down what's happening. Thanks!

**Comment by tzbaris** [comment]
@jakevdp Thanks for your response, here is a sample of the data

df_concat = pd.DataFrame({
    'credit_qr_hr': [87, 88, 89, 87, 88, 89, 87, 88, 89],
    'ratio': [0.27, 0.39, 0.35, 0.39, 0.51, 0.38, 0.20, 0.35, 0.47],
    'model': ['b3b', 'b3b', 'b3b', 'baseline', 'baseline', 'baseline', 'truth', 'truth', 'truth']
})

I ran it exactly as posted, so I'm not sure what's going on. Could it be possible that there is a version issue?

Here is what the bar chart alone looks like

![image](https://user-images.githubusercontent.com/6526450/46683011-12d4e600-cbbd-11e8-8bba-5e8b221483fd.png)

**Comment by jakevdp** [comment]
Ah, I see now. The error is unfortunately not particularly informative here, but the core issue is that you cannot use a faceted chart within a layer (from the perspective of the renderer, it's ill-defined what the user intends in that case).

The alternative is to create a layered chart first, and then facet it. For example:
```python
import altair as alt
import pandas as pd

df_concat = pd.DataFrame({
'time': [87, 88, 89, 87, 88, 89, 87, 88, 89],
'ratio': [0.27, 0.39, 0.35, 0.39, 0.51, 0.38, 0.20, 0.35, 0.47],
'model': ['b3b', 'b3b', 'b3b', 'baseline', 'baseline', 'baseline', 'truth', 'truth', 'truth']
})

bars = alt.Chart().mark_bar(stroke='transparent').encode(
    alt.X('model', scale=alt.Scale(rangeStep=12), axis=alt.Axis(title='')),
    alt.Y('ratio:Q', axis=alt.Axis(title='ratio', grid=False)),
    color=alt.Color('model:N', scale=alt.Scale(range=["#EA98D2", "#659CCA", '#5bb3a4'])),
)

text = alt.Chart().mark_text(
    align='left',
    baseline='middle'
).encode(
    y = alt.Y('ratio'), 
    x = 'model',
    text='ratio'
)

alt.layer(bars, text, data=df_concat).facet(
    column='time:O'
).configure(
    legend=alt.LegendConfig(labelFontSize=16, titleFontSize=16, symbolSize=100, labelFont='Lato'),
    axis=alt.AxisConfig(labelFontSize=16, tickSize=16, labels=True, titleFontSize=16)
)
```
![visualization](https://user-images.githubusercontent.com/781659/46688006-28dca980-cbb1-11e8-85f3-4092a87cb354.png)

**Comment by tzbaris** [comment]
I see, thank you so much!

**Comment by lcyraphael** [comment]
If it's alright to piggyback off of the above issue, is there a way to configure the labels of the facet's row/ column? In the above example it'd be trying to change the label font size, angle, limit, positioning etc of 87, 88, 89.

Some potentially related attempts 
- https://stackoverflow.com/questions/52360965/change-facet-title-position-in-altair
- https://github.com/altair-viz/altair/issues/720#issuecomment-381340052

Thanks

**Comment by Alcampopiano** [comment]
@lcyraphael Off the top of my head I think you want to configure the header if I understand correctly.

import altair as alt
from altair.expr import datum
from vega_datasets import data
iris = data.iris.url

```python
alt.Chart(iris).mark_point().encode(
    x='petalLength:Q',
    y='petalWidth:Q',
    color='species:N'
).properties(
    width=180,
    height=180
).facet(
    column='species:N'
).configure_header(titleFontSize=40, labelFontSize=40

)
```

![visualization 52](https://user-images.githubusercontent.com/4624246/47588578-a126c700-d934-11e8-9216-f7260f5ff2a1.png)

**Comment by lcyraphael** [comment]
Ah of course. Thank you!

**Comment by jakevdp** [comment]
With #1521 this error should no longer arise in this situation.
