### ISSUE TITLE
Selection with grouped bars

### ISSUE THREAD

**Issue by rrjadhav82** [altair-viz/altair#1176]
I am bit new to altair. I am trying code below - 

```
import altair as alt
from vega_datasets import data

cars = data.cars.url
chart = None
def disp():
    selection = alt.selection_multi(fields=['Origin'], resolve=SelectionResolution('global'))
    color = alt.condition(selection,
                          alt.Color('Origin:N', legend=None),
                          alt.value('lightgray'))

    scatter = alt.Chart(cars).mark_bar().encode(
        x='Horsepower:Q',
        y='Miles_per_Gallon:Q',
        #column=Column(field='Origin:N', title='Origins', type='nominal'),
        color=color,
        tooltip='Name:N'
    ).add_selection(
        selection
    )
    
    legend = alt.Chart(cars).mark_point().encode(
        y=alt.Y('Origin:N', axis=alt.Axis(orient='right')),
        color=color
    ).add_selection(
        selection
    )
    global chart
    chart = scatter | legend
    chart.display()
    
disp()
```

This works fine with output - 

![chart](https://user-images.githubusercontent.com/44297296/47225537-f6665400-d3db-11e8-8bad-6e7a3d01a524.png)

Legend interaction also works correctly as expected. But if I try to group the bars under categories by uncommenting the 
`column=Column(field='Origin:N', title='Origins', type='nominal')`  line, I start getting an error: 

> SchemaValidationError: Invalid specification
>         altair.vegalite.v2.schema.channels.Color, validating 'additionalProperties'
>         Additional properties are not allowed ('selection' was unexpected)

I tried creating such grouping with Vega-Lite editor and it worked with the json attached. 

[vega-json.txt](https://github.com/altair-viz/altair/files/2496310/vega-json.txt)

**Comment by jakevdp** [comment]
The issue is that a concatenation cannot contain a faceted chart according to the Vega-Lite schema.

This restriction is actually a bug... the good news is it's been fixed in https://github.com/vega/vega-lite/pull/3965. The bad news is the fix has not yet made it into a vega-lite release, so the only antidote is to wait until version 3.

**Comment by rrjadhav82** [comment]
Thanks a lot for such a super quick response!!
