### ISSUE TITLE
Boolean operations silently wrong in transform_calculate()

### ISSUE THREAD

**Issue by tmelconian** [altair-viz/altair#1177]
In transform_calculate, "or" and "and" don't work as expected.  "or" seems to return its LHS and "and" seems to return its RHS.  Easiest to show with an example:

```Python
import pandas as pd
import altair as alt
from altair import datum
import site

# This is the standard tips example dataset; load it however you want
tips1=pd.read_csv(site.getsitepackages()[0]  + '/pandas/tests/data/tips.csv')

alt.Chart(tips1).mark_point().encode(
    x='total_bill',
    y='tip_pct:Q',
    color='weekend:N'
).transform_calculate(tip_pct=datum.tip/datum.total_bill, weekend=datum.day == 'Sat' or datum.day == 'Sun')
```

This example should show both weekend days in a different color, but in fact it shows only Saturdays.  If I change the "or" to an "and", it should then show no days because of course the day string cannot be simultaneously equal to "Sat" and "Sun", but in fact it then shows Sundays.  Compare to the correct graph, which can be generated by doing the calculations in Pandas:

```Python
alt.Chart(tips1.assign(tip_pct=tips1.tip/tips2.total_bill,
                      weekend=tips1.day.isin(['Sat','Sun']))).mark_point().encode(
    x='total_bill',
    y='tip_pct',
    color='weekend'
)
```

I dug around in expr to see if there was some other functions I was supposed to use for logical operations instead of the Python ones, but I couldn't find anything.

**Comment by jakevdp** [comment]
This is expected behavior for Python's ``or`` and ``and`` keywords.

If you want the correct boolean operations in Altair, use ``|`` and ``&`` instead.
