### ISSUE TITLE
bind a list of strings to range input

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#1178]
I see myself oftenly having a list of strings that I want to connect to a range slider. Like this:

![bind_range_list_of_strings](https://user-images.githubusercontent.com/5186265/47294348-1a5cac00-d60d-11e8-87cd-69d6791f0329.gif)

But reading the [documentation](https://altair-viz.github.io/user_guide/generated/api/altair.binding_range.html) it only allows for the properties `min`, `max` and `step`, meaning it only can be used for consecutive numbers

Any idea if/how this can be achieved?

**Comment by jakevdp** [comment]
I don't think that's currently possible within Vega-Lite's binding specification.

**Comment by joelostblom** [comment]
Closing as this feature would need to be added in Vega-Lite, and there is nothing we can do on the altair side of things.
