### ISSUE TITLE
Add "How to cite" to the README.md and to the docs.

### ISSUE THREAD

**Issue by draperjames** [altair-viz/altair#1179]
I would like to know how the maintainers would prefer to cite this package for peer reviewed journals. Please let me know at your soonest convenience.

Thank you for your time.

**Comment by jakevdp** [comment]
Once the [JOSS review](https://github.com/openjournals/joss-reviews/issues/1024) goes through, we can add that info to the README

**Comment by draperjames** [comment]
@jakevdp thanks for the quick response. Is there anything that we can use in the interim? I'm working on a paper that is currently in review and I would like to make sure you guys get credit for your work.

**Comment by jakevdp** [comment]
For the time being, you can cite it as in prep. Here's the partial citation:

> VanderPlas et al., (2018; in prep). Altair: Interactive Statistical Visualizations for Python. Journal of Open Source Software

**Comment by draperjames** [comment]
@jakevdp perfect! Thanks for that. I'll keep you updated about our paper it may be nice to put a few of the interactive figures into your gallery or something.

**Comment by domoritz** [comment]
Done in https://github.com/altair-viz/altair/commit/372454abef5a6a9898ca928ba26d64d3b6d903ce
