### ISSUE TITLE
binding - initial selection is empty

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1184]
Okay, seems like this is a duplicate of https://github.com/altair-viz/altair/issues/599

If I use two dropdown menus that are bound to selections, the chart comes up empty on the first selection, but if I toggle off and back on again the data show up. For example:

```python
import altair as alt
import pandas as pd
from vega_datasets import data

df=data.cars()
df['Cylinders_str']=df['Cylinders'].astype(str)

sel_box_1 = alt.binding_select(options=list(df['Cylinders_str'].unique())) # selection of type "interval"
selection_1 = alt.selection_single(name='Cylinders', fields=['Cylinders_str'], bind=sel_box_1)

sel_box_2 = alt.binding_select(options=list(df['Origin'].unique())) # selection of type "interval"
selection_2 = alt.selection_single(name='Country of Origin',fields=['Origin'], bind=sel_box_2)

alt.Chart(df).mark_point().encode(
    x='Horsepower',
    y='Displacement',
    color='Origin',
    tooltip=['Origin', 'Cylinders']
).add_selection(
    selection_1, selection_2
).transform_filter(
    selection_1 & selection_2
)

```

### just changing Cylinders to 4
![sc](https://user-images.githubusercontent.com/4624246/47737549-89f31c80-dc47-11e8-8c9e-c06c82d4dfd9.png)

### Now changing to Europe and then back to USA

![sc2](https://user-images.githubusercontent.com/4624246/47737554-8eb7d080-dc47-11e8-8ec6-511c836c557a.png)

Perhaps I am not setting the bindings up correctly. Any help would be appreciated. It appears that in VL this is also an issue as you can see in the example from the docs. That is, a change on one slider does not interact with the other until both have been moved around first.

https://tinyurl.com/yck2bq8c

**Comment by jakevdp** [comment]
Closing in favor of #599
