### ISSUE TITLE
Name the binding widget

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1186]
Hi all,

In the VL editor `name` can be passed to the `bind` property to give the widget a custom name.

You can see that here:
https://tinyurl.com/ybugzrc9

Is this possible in Altair v2? (I have tried but it seems that the "_columnName"  suffix is forced.

I assume this is something that will change when Altair switches to VL3 but please correct me if I am wrong.

**Comment by jakevdp** [comment]
I think that is a feature of Vega-Lite 3. The vega editor has been upgraded to an unreleased vega-lite version, and so some of the features there are not available in the current Altair release.

Once vega-lite 3 is actually released, we'll work on creating an Altair release with those new features.

**Comment by Eduard-gan** [comment]
As a workaround in Altair v2.3.0 one can try to alter already finished spec to display "Name" parameter:

```
     selection = altair.selection_single(fields=['region_id'], bind=input_dropdown, name=u'SELECTOR_NAME')

     chart = altair.Chart(data_frame).mark_line().encode(
            x=altair.X(...some definitions),
            y=altair.Y(...some definitions)
            color=altair.Color(...some definitions),
            tooltip=altair.Tooltip(...some definitions)
        ).add_selection(selection
        ).transform_filter(selection
        )

        additional_charts = [chart.transform_filter(altair.datum.search_engine == x) for x in ['Yandex', 'Google']]
        chart = altair.vconcat(*additionals)

spec = chart.to_json()
        ### Dangerous low level alteration of spec's Bind name
        import json
        alt_spec = json.loads(spec)
        key = next(alt_spec['vconcat'][0]['selection'].iterkeys())
        alt_spec['vconcat'][0]['selection'][key]['bind']['name'] = key
```

I suspect that it just works in my case but it worked. Perhaps with other chart setups there will be nasty bugs, so use it as a last resort(In my case i just cant present a chart with awkward selector names as ______region_id ).
