### ISSUE TITLE
Documentation plots are not working with activated AdBlocker

### ISSUE THREAD

**Issue by FlorianWetschoreck** [altair-viz/altair#1199]
I am using the AdBlock extension in Google Chrome.
This is blocking the loading of the external dataset. For example in
https://altair-viz.github.io/user_guide/compound_charts.html

The data and the plot is shown, if the data is loaded directly like in #1198

**Comment by FlorianWetschoreck** [comment]
This was already an issue in #986 

- It is hard for new visitors/users to understand that it actually might be the fault of their client.
- If we dont fix it, people will think Altair is broken which is too bad because it is such an awesome library!
- Also, AdBlockers are very widely used. So, we should definitely fix it.

Solution proposals:
1) change the data import to be direct like in #1198 Downside is that the performance might be a little worse. Most of the times, this will be no problem. If it is a problem, the dataset could be exchanged for a smaller one.
2) on a graph that is broken: detect the AdBlocker and then show a hint where the graph is missing. This shows the error right where it occurs. Documenting this hint somewhere else wont be as effective and still a lot of people won't see it
3) do nothing like in #986

I would prefer 1) because it is less effort than 2). Nevertheless, we should not do 3) because it has quite a big impact on the experience of new users.

**Comment by FlorianWetschoreck** [comment]
For solution 1:
#1198 is not complete because there are some other examples in altair/vegalite/v2/examples/... which have the same problem.
I will fix the missing graphs as well if we agree that solution 1 should be the way to go...

**Comment by jakevdp** [comment]
Another detail with #1: we deliberately avoid directly embedding any data that is not included as a local dataset in [vega_datasets](https://github.com/altair-viz/vega_datasets), because otherwise the unit tests depend on an external HTTP download which makes them flaky.

**Comment by FlorianWetschoreck** [comment]
Hi @jakevdp , thank you for your fast response and for providing the bigger picture for this issue.

Thank you for hinting towards the mobile users. You are right, that the #1198 might be worse for them. Do we know the ratio of desktop to mobile device users who visit the documentation?

And do you have any other solution idea?

2 other solution ideas that I had (to be added to the ones in my previous post):
5) for each documentation page: add a textual hint to the first graph which might fail
6) "AdBlock detector": embed a small javascript which also tries to load the CSV data and will show an error message to the user if it fails. This wont clutter the page, will only be shown in the right context, and wont increase the import burden due to browser caching. However, I am uncertain if this is easily possible in the current form of the documentation? Do you have experience with this?

I am looking forward to your hint of how to solve this. And I am happy to implement it :)

**Comment by FlorianWetschoreck** [comment]
> Another detail with # 1: we deliberately avoid directly embedding any data that is not included as a local dataset in [vega_datasets](https://github.com/altair-viz/vega_datasets), because otherwise the unit tests depend on an external HTTP download which makes them flaky.

If I understand correctly, then this would be an issue if we try to embed external datasets which are not part of vega_datasets. (is this correct?)
For graphs who use such data sets (how many are those roughly?) we could just not implement the direct import? Or exchange the data for another dataset?

**Comment by jakevdp** [comment]
> For graphs who use such data sets (how many are those roughly?)

zero, I think

**Comment by jakevdp** [comment]
Also, keep in mind for all of these proposed solutions that the pages are generated from RST source via sphinx, so adding custom javascript, etc. is a WHOLE lot more work than just pasting some code in a file.

**Comment by jakevdp** [comment]
I think it makes more sense to try to address this at its root cause in vega-embed, rather than to treat the symptom here.

**Comment by FlorianWetschoreck** [comment]
Yes, however, vega-embed cannot determine if the data for the visualization was loaded from an external or inline dataset. Or can it?
Because it does not make sense to show this warning to every user with an AdBlocker even if the code uses inline data imports.

So, maybe there should be an option for the developer who embeds code with vega-embed to trigger this alert or not. What do you think about this?

Where and how do you specify vega-embed to render your plots in the sphinx documentation?

**Comment by domoritz** [comment]
As explained in https://github.com/vega/vega-embed/issues/109, the issue is https://github.com/hoshsadiq/adblock-nocoin-list/issues/332

**Comment by FlorianWetschoreck** [comment]
Thank you @jakevdp and @domoritz for your comments and help!
The issue is now resolved with https://github.com/hoshsadiq/adblock-nocoin-list/issues/334
