### ISSUE TITLE
Is it possible to add more shapes to mark_point?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#1200]
I was trying to recreate [an official government chart](https://twitter.com/palewire/status/1063490750741012480) today and learned that Altair's "shape" option on marks does not support X's. It might be nice if it did.

**Comment by jakevdp** [comment]
You can define any shape you'd like with SVG paths; here is an example: https://altair-viz.github.io/gallery/isotype.html

**Comment by palewire** [comment]
Very nice!

**Comment by diallobakary4** [comment]
Is there any resource to have a set of SVG paths?
