### ISSUE TITLE
Fill circle in Legend

### ISSUE THREAD

**Issue by luerhard** [altair-viz/altair#1206]
Hello everyone,
i am currently working on a visualization of some data and have come to a point where the documentations cannot help me anymore. After 1 hour of trying, I herewith surrender and hope for some advice.

I have a working visualization and the only thing i want to do is: `fill out the circles in the legend` to have a better visibility of the colors.

I cannot find any shape that is filled and I have run out of ideas of what so search in the documentation.

Here is the code to the chart so far:
```python
import altair as alt

alt.Chart(d).mark_line().encode(
    x = alt.X("Year:T", axis=alt.Axis(format="%Y")),
    y = alt.Y("Percent:Q", axis=alt.Axis(format="%")),
    color = alt.Color("Orientation:N", scale=alt.Scale(
        domain=["FP Financial", "FP Non-Financial", "NP Private", "NP Public"], 
        range=["#7E1718", "#E56242", "#13486B", "#3B8689"]
        ) 
    )
).configure_view(
    width = 800
).configure_legend(    
    symbolType = "circle",
    symbolSize = 70
)
```

![visualization](https://user-images.githubusercontent.com/24412608/48788550-5b6add80-eceb-11e8-95fb-6f44ea1c02f5.png)

Maybe someone can help - I would be forever grateful !

Regards,
Lukas Erhard

**Comment by afonit** [comment]
@luerhard ,
```python
.mark_line(filled=True)
```
Does passing filled=True get you to where you want to be?

**Comment by luerhard** [comment]
Sadly, no. If I change the line to `alt.Chart(d).mark_line(filled=True).encode(` the legend looks like I want it, but the lines in the chart look kind of akward...

![visualization 2](https://user-images.githubusercontent.com/24412608/48789587-b1d91b80-eced-11e8-9b26-3222d6476ebd.png)

**Comment by Alcampopiano** [comment]
This is the best I could do:

```python
import altair as alt
from altair.expr import datum
from vega_datasets import data

source = data.jobs.url

alt.Chart(source).mark_line().encode(
    alt.X('year:O'),
    alt.Y('perc:Q', axis=alt.Axis(format='%')),
    color=alt.Color('sex:N'),
).properties(
    title='Percent of work-force working as Welders'
).transform_filter(
    datum.job == 'Welder'
).configure_legend(symbolSize=80, symbolStrokeWidth=20)

```

**Comment by afonit** [comment]
@luerhard ,
No luck yet.  But one workaround you could use if you are tight on time - create two plots:
 * the line plot
 * a mark_point(filled=True)

And make them both show:

```python
import altair as alt
from altair.expr import datum
from vega_datasets import data

alt.themes.enable('opaque')

source = data.jobs.url

a = alt.Chart(source).mark_line().encode(
    alt.X('year:O'),
    alt.Y('perc:Q', axis=alt.Axis(format='%')),
    color=alt.Color('sex:N'),
).properties(
    title='Percent of work-force working as Welders'
).transform_filter(
    datum.job == 'Welder'
)#.configure_legend(symbolType='square', symbolfillcolor='red')  


a + a.mark_point(filled=True)
```

![visualization 5](https://user-images.githubusercontent.com/1798497/48793790-184a4380-ecc6-11e8-8643-c43b78e37dc5.png)

**Comment by Alcampopiano** [comment]
and, to come full circle, `a + a.mark_point(filled=True, size=0)` will get rid of the points if you like:

![visualization 58](https://user-images.githubusercontent.com/4624246/48794171-28aeee00-ecc7-11e8-9e0f-62476a29bc60.png)
)`

**Comment by hassenmorad** [comment]
@luerhard, I had the same question with a line plot recently and just played around with _symbolSize_ & _symbolStrokeWidth_ in _configure_legend_ (like @Alcampopiano referenced earlier) until the legend symbols were filled and the size was appropriate.

**Comment by jakevdp** [comment]
Related: #1000 & vega-lite references therein

**Comment by jakevdp** [comment]
Another possibility is to create a second view of the data and use that for the legend, hiding the default line legend. For example:
```python
import altair as alt
from vega_datasets import data
stocks = data.stocks()

points = alt.Chart(stocks).mark_circle(size=0).encode(
  color='symbol'
)

lines = alt.Chart(stocks).mark_line().encode(
  x='date:T',
  y='price',
  color=alt.Color('symbol', legend=None)
).interactive(bind_y=False)

lines + points
```
![visualization 7](https://user-images.githubusercontent.com/781659/48801442-40837380-ecc1-11e8-9e2e-02a02d4705c3.png)

**Comment by jakevdp** [comment]
Ah, I gues @Alcampopiano beat me to that :smile:

**Comment by Alcampopiano** [comment]
Thanks to @afonit who suggested the layer workaround.

**Comment by luerhard** [comment]
@Alcampopiano, @jakevdp and everyone else thank you so much!! I haven't thought of that. 

Maybe adding some filled shapes would be an idea for future version of this (great) library :)
