### ISSUE TITLE
Saved image has grey/white checkered background

### ISSUE THREAD

**Issue by hassenmorad** [altair-viz/altair#1208]
I'm trying to figure out why saved charts have a grey & white checkered background. I used the following format: chart.save('chart_name.png'). Altair, Vega, and Selenium are up to date. I can't figure out what's causing this. Any ideas?
For some reason it shows fine here, but when I upload it to google drive or github the checkered background shows up...

![out_migration_bar](https://user-images.githubusercontent.com/30246854/48838767-35225d80-ed3e-11e8-86ab-a4977df7f8b2.png)

![checkered](https://user-images.githubusercontent.com/30246854/48838878-87637e80-ed3e-11e8-873c-3820649f0b8b.JPG)

**Comment by curran** [comment]
I believe it's a transparent background. Some image viewing programs use a checkered background to show you where the transparency is. Try opening it with various programs, I bet each one adds a slightly different checkered background, and some will show the background as white.

Maybe specifying the background color explicitly in your probram would make this go away.

**Comment by Alcampopiano** [comment]
@hassenmorad If you want to make the background a specific color you can do so using a theme, or using the properties of an individual chart.

### using a theme
```python
def my_theme(*args, **kwargs):
    return {
            "background": "white"
          }
          
alt.themes.register('my_theme', my_theme)
alt.themes.enable('my_theme');

```

### using properties
```python
data = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

alt.Chart(data).mark_bar().encode(
    x='a',
    y='b'
).properties(background='black')
```

**Comment by hassenmorad** [comment]
Thank you @curran & @Alcampopiano ! Setting the background property as 'white' fixed it and I'm glad I understand the reason why.
