### ISSUE TITLE
Dataset consolidation example in docs gives error in Vega Editor

### ISSUE THREAD

**Issue by atlasstrategic** [altair-viz/altair#1209]
I was reading the [dataset consolidation](https://altair-viz.github.io/user_guide/data_transformers.html#dataset-consolidation) docs when I noticed the following:

After clicking on the "Open in Vega Editor" link (see image below), there is a JavaScript Error: `Duplicate data set name: "data-137453ccbb3f929636eb2f9dd7052f16"` in the `https://vega.github.io/editor/` produced view.
![image](https://user-images.githubusercontent.com/81103/48838694-ca027680-ed91-11e8-8513-b3ebc474b9a6.png)

Similar examples work fine if the data is represented via `url` e.g. the [horizontal-concatenation](https://altair-viz.github.io/user_guide/compound_charts.html#horizontal-concatenation) example in the docs, `"data": { "url": "https://vega.github.io/vega-datasets/data/iris.json",`. However if one would rewrite the example like so:
```python
import altair as alt
from vega_datasets import data
import pandas as pd

iris = data.iris()

chart1 = alt.Chart(iris).mark_point().encode(
    x='petalLength:Q',
    y='petalWidth:Q',
    color='species:N'
).properties(
    height=300,
    width=300
)

chart2 = alt.Chart(iris).mark_bar().encode(
    x='count()',
    y=alt.Y('petalWidth:Q', bin=alt.Bin(maxbins=30)),
    color='species:N'
).properties(
    height=300,
    width=100
)

chart1 | chart2
```
The Vega Editor will give the same error.

**Comment by jakevdp** [comment]
Fixed in Vega-Lite 3
