### ISSUE TITLE
Why are there two similar scatterplots in the simple examples?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#1210]
![screenshot from 2018-11-21 06-56-54](https://user-images.githubusercontent.com/9993/48849214-bf78ba80-ed5a-11e8-8087-c8463df37a62.png)

You can see them above, [Scatter Plot with Tooltips](https://altair-viz.github.io/gallery/scatter_tooltips.html) and [Simple Scatter Plot](https://altair-viz.github.io/gallery/simple_scatter.html). They both have tooltips. The first breaks from our naming convention of starting all titles in this section with "Simple." 

Seems like a wrinkle we should iron out. Why do we even have two in the first place? My hunch is they should be combined into one "Simple Scatter Plot."

**Comment by jakevdp** [comment]
Yes, I think it makes sense to remove one of them. I'll take care of it.

**Comment by jakevdp** [comment]
Closed by #1215
