### ISSUE TITLE
Version 2.3 release

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#1216]
I'd been waiting for Vega-Lite 3.0 in order to do an altair 3 release, but I think enough time has passed (and there have been enough improvements/bug fixes in the code) that a new release is warranted prior to Vega-Lite 3.0.

**Comment by palewire** [comment]
:+1:

**Comment by eitanlees** [comment]
A 2.3 release should also alleviate the hangups in https://github.com/openjournals/joss-reviews/issues/1057

**Comment by eitanlees** [comment]
Done in https://github.com/altair-viz/altair/commit/193473d94e72dbdecb48af9c9a4f3e57285de3ea
