### ISSUE TITLE
Interactive charts - from a map!

### ISSUE THREAD

**Issue by AnneEstoppey** [altair-viz/altair#1232]
Hello there,

I was wondering if it would be possible to have interactive chart also working on a map.

Meaning that by selecting a group of points on my map, I would be able to see the corresponding data in my bar chart, for instance. Similarly as below, just that the scatter point would be, in fact, a map.

I don't think I have seen that in any other package (but I should perhaps investigate). I think it would be a really great additional interactive feature.

If you need sample datasets (in my case in the exploration well public data of Norway), please let me know.

Thanks in advance,
Cheers
Anne

![interactive_chart](https://user-images.githubusercontent.com/35219455/49073610-23a3ee80-f233-11e8-870a-cc659cd83490.jpg)

**Comment by jakevdp** [comment]
Currently, no, that's not possible. This would require adding interval selection support to geographic projections in Vega-Lite. This is an open issue in Vega-Lite: https://github.com/vega/vega-lite/issues/3306

**Comment by jakevdp** [comment]
though note that some interactions (based on single/multi selections rather than interval selections) do work currently, e.g. https://altair-viz.github.io/gallery/us_state_capitals.html

**Comment by AnneEstoppey** [comment]
Oh ok I see. Hmm. I hope 'they' find a way. That would be really cool. 

Yes the utility from your link, I can do that in mapbox. 
I am intensively using mapbox for more elaborate maps. 
Maybe I should also ask them about interactivity between a map and a graph...

Cheers
Anne

**Comment by jakevdp** [comment]
No, we don't really have control over any of that in Altair. Altair just produces JSON specifications that are interpreted and rendered by the vega stack... so all aspects of the rendering are in the domain of vega & vega-lite.

**Comment by AnneEstoppey** [comment]
Ok, I understand, thanks a lot for information, that makes sense.

I'll check the vega github :-)

Cheers
Anne

**Comment by joelostblom** [comment]
@AnneEstoppey is this what your are looking for https://stackoverflow.com/a/65948144/2166823?

**Comment by binste** [comment]
This was added in Vega-Lite 5.7 and hence is available in Altair 5. See https://github.com/vega/vega-lite/pull/6953 for a Vega-Lite example.
