### ISSUE TITLE
Store transformed json data in separate folder

### ISSUE THREAD

**Issue by JarnoRFB** [altair-viz/altair#1235]
Hi,

Not sure if this is already possible, but at least I could not figure it out from the docs/function signatures. I usually enable the json data transformer

`alt.data_transformers.enable('json')`

Hoever, after making a few plots this starts to clutter the working directory. Is there any way to store the files in a separate directory?

Cheers

**Comment by JarnoRFB** [comment]
Ok sorry, just figured this out right after I opened the isssue.

```python
import os
import altair as alt

os.mkdir('altdata')

def custom(data):
    return alt.pipe(data, alt.to_json(filename='altdata/{prefix}-{hash}.{extension}') )
alt.data_transformers.register('custom', custom)
alt.data_transformers.enable('custom')
```

Probably, I could add some documentation for this if it seems appropriate.

**Comment by jakevdp** [comment]
This would be a great example for the documentation, if you're willing to contribute it! You could add it to this page: https://github.com/altair-viz/altair/blob/master/doc/user_guide/data_transformers.rst

I think that doc page could use a little work to make it more helpful, and a nice compact example like this would be a great place to start.

**Comment by JarnoRFB** [comment]
Sure #1237 is out. If the idea is welcome, one might consider adding a `datadir` option to the default json transformer. For now I am fine with the solution though.
