### ISSUE TITLE
Improve grouped bar example

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#1236]
This example is too complicated (mixed filtering, etc.): https://altair-viz.github.io/gallery/grouped_bar_chart.html

We need to change this to a simpler dataset that focuses just on the creation of a grouped bar chart, without adding the distraction of transforms.

**Comment by eitanlees** [comment]
How about 

```python
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_bar().encode(
    x='year:O',
    y='sum(yield):Q',
    color='year:N',
    column='site:N'
)
```
![visualization 13](https://user-images.githubusercontent.com/2041969/49195558-94dbc280-f355-11e8-9c52-44726d1ea3ee.png)

**Comment by eitanlees** [comment]
Done in https://github.com/altair-viz/altair/pull/1238
