### ISSUE TITLE
facetted and grouped bar chart

### ISSUE THREAD

**Issue by fkuehnel** [altair-viz/altair#1242]
I like to plot 2 grouped bar charts next to each other via facets. Each of the bar charts is also grouped.
I can't get the following example to work, it results in a cryptic error message:

altair.vegalite.v2.api.FacetChart->spec, validating u'anyOf'

```
import altair as alt
import pandas as pd

t_df = pd.DataFrame({'x':[0.05, 0.1] * 4,
                     'm':[False] * 4 + [True] * 4,
                     'c':['BR','BR','IN','IN'] * 2,
                     'y':[0.3,0.4,0.2,0.3,0.1,0.2,0.3,0.4]})

base = alt.Chart(t_df).encode(
    x=alt.X('c:N', sort=['BR', 'IN']),
    y=alt.Y('y:Q', axis=alt.Axis(format='%')),
    color=alt.Color('c:N', sort=['BR', 'IN']),
    column=alt.Column('x:Q', header=alt.Header(format='.2p'))
).transform_filter(
    alt.FieldOneOfPredicate(field='c', oneOf=['IN','BR'])
)
    
chart = base.mark_bar(stroke='transparent')

chart.facet(
    column="m:O", data=t_df
)
```

**Comment by jakevdp** [comment]
Unfortunately, faceted charts cannot be faceted within Altair. That is not supported in the Vega-Lite grammar.

**Comment by fkuehnel** [comment]
I see, so the only option is to use columns and rows then.

**Comment by jakevdp** [comment]
In altair 3 it will be possible to concatenate facets, but due to a bug in vega-lite that's not available currently.

**Comment by jakevdp** [comment]
Confirmed that the script above works correctly in Altair 3.

**Comment by swanderz** [comment]
@jakevdp this code chunk doesn't work for me with `altair==4.1.0` and `pandas=1.0.3`

**Comment by jakevdp** [comment]
Vega-Lite 4 deliberately removed the ability to facet a facet chart because they couldn't support all corner cases. This chart is no longer possible, unfortunately.
