### ISSUE TITLE
How to keep bars in original order

### ISSUE THREAD

**Issue by caseyahlan** [altair-viz/altair#1245]
I am creating a bar chart:

`incidents = alt.Chart(off_by_bias).mark_bar().encode(
    x='Bias motivation',
    y='incidents + offenses',
    color='Type'
)`

And when I do this, it's sorting x alphabetically.  However, I want the bars to retain their original order from the data. Is this possible?

**Comment by jakevdp** [comment]
Axes are sorted by default. If you would like them to be ordered differently, you can specify the ``sort`` keyword. For example:
```python
import altair as alt
import pandas as pd

data = pd.DataFrame({
  'x': ['B', 'A', 'C'],
  'y': [1, 2, 3]
})

alt.Chart(data).mark_bar().encode(
  x=alt.X('x', sort=['A', 'B', 'C']),
  y='y'
)
```
![visualization 11](https://user-images.githubusercontent.com/781659/49350538-34ee6000-f664-11e8-983e-4e04536edea4.png)
