### ISSUE TITLE
Sharing axes in a facet plot

### ISSUE THREAD

**Issue by romainmartinez** [altair-viz/altair#1253]
Hello Jake and thank you for the amazing work on Altair.

My problem is related to the axis scale in a facet figure (relative to [this issue](https://github.com/altair-viz/altair/issues/428)).

Let's say I have the following dataset:

```python
import pandas as pd

data = pd.DataFrame({
    'group': ['group 1', 'group 2', 'group 3', 'group 1', 'group 2', 'group 3', 'group 1', 'group 2', 'group 3', 'group 1', 'group 2', 'group 3'],
    'label': ['a', 'a', 'b', 'b', 'c', 'c', 'a', 'a', 'b', 'b', 'c', 'c'],
    'variable': ['var 1', 'var 1', 'var 1', 'var 1', 'var 1', 'var 1','var 2', 'var 2', 'var 2', 'var 2', 'var 2', 'var 2'],
    'value': [25, 57, 23, 19, 8, 47,625, 647, 630, 627, 638, 619]}
)
```

and I assign this plot:

```python
bar = alt.Chart().mark_bar().encode(x='label', y='value')

bar.facet(data=data, row='variable', column='group').resolve_scale(y='independent')
```

![visualization 2](https://user-images.githubusercontent.com/17710617/49615007-28c31500-f97a-11e8-9d3b-45dc20b0e557.png)

Do you know a way to share the axes only between columns and keep them independent for each rows?

**Comment by domoritz** [comment]
In your chart, the x-axis is shared but the y-axis is independent. The chart you created seems looks like the answer to your question, no? Can you explain to me how you want the output to be different?

**Comment by romainmartinez** [comment]
I would like the graphs of the first line (`var 1`) to share the same y-axis (e.g., something like `[0, 60]`) and the same thing for the graphs of the second line (`var 2`) (`[0, 650]`). 

I manually created the graph I want with Inkscape to give you an example:
![next_game_abs](https://user-images.githubusercontent.com/17710617/49704456-61b0f300-fbe1-11e8-9a2b-46de8e4f9a9d.png)

As you can see, the axes are only shared between the lines.

**Comment by domoritz** [comment]
Like this? https://colab.research.google.com/drive/1pOaJ4ljwXD46x9KlZ-FmpkR7WcUR1UKT

**Comment by domoritz** [comment]
Ahh, I see. Thank you for the example. 

What you want is a facet inside a facet where only one of them uses an independent y scale. Unfortunately, we don't allow this in Vega-Lite right for various reasons that are a bit hard to get into right now. 

The easiest workaround for now is to use a facet inside a repeat.

**Comment by domoritz** [comment]
The interesting thing is that it actually works in Vega-Lite right now

```json
{
  "config": {"view": {"width": 400, "height": 300}},
  "data": {"values": [
    {"group": "group 1", "label": "a", "value": 25, "variable": "var 1"},
    {"group": "group 2", "label": "a", "value": 57, "variable": "var 1"},
    {"group": "group 3", "label": "b", "value": 23, "variable": "var 1"},
    {"group": "group 1", "label": "b", "value": 19, "variable": "var 1"},
    {"group": "group 2", "label": "c", "value": 8, "variable": "var 1"},
    {"group": "group 3", "label": "c", "value": 47, "variable": "var 1"},
    {"group": "group 1", "label": "a", "value": 625, "variable": "var 2"},
    {"group": "group 2", "label": "a", "value": 647, "variable": "var 2"},
    {"group": "group 3", "label": "b", "value": 630, "variable": "var 2"},
    {"group": "group 1", "label": "b", "value": 627, "variable": "var 2"},
    {"group": "group 2", "label": "c", "value": 638, "variable": "var 2"},
    {"group": "group 3", "label": "c", "value": 619, "variable": "var 2"}
  ]},
  "facet": {
    "column": {"type": "nominal", "field": "group"}
  },
  "spec": {
    "facet": {
      "row": {"type": "nominal", "field": "variable"}
    },
    "spec": {
      "mark": "bar",
      "encoding": {
        "x": {"type": "nominal", "field": "label"},
        "y": {"type": "quantitative", "field": "value"}
      }
    },
    "resolve": {
      "scale": {
        "y": "independent"
      }
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json"
}
```

![image](https://user-images.githubusercontent.com/589034/49704715-45a25700-fbcb-11e8-9691-14d5b6eb3bdb.png)

But it's not a valid spec according to the schema and so Altair cannot generate it.

**Comment by domoritz** [comment]
This would be the Vega-Lite spec you want

```json
{
  "config": {"view": {"width": 400, "height": 300}},
  "data": {"values": [
    {"group": "group 1", "label": "a", "value": 25, "variable": "var 1"},
    {"group": "group 2", "label": "a", "value": 57, "variable": "var 1"},
    {"group": "group 3", "label": "b", "value": 23, "variable": "var 1"},
    {"group": "group 1", "label": "b", "value": 19, "variable": "var 1"},
    {"group": "group 2", "label": "c", "value": 8, "variable": "var 1"},
    {"group": "group 3", "label": "c", "value": 47, "variable": "var 1"},
    {"group": "group 1", "label": "a", "value": 625, "variable": "var 2"},
    {"group": "group 2", "label": "a", "value": 647, "variable": "var 2"},
    {"group": "group 3", "label": "b", "value": 630, "variable": "var 2"},
    {"group": "group 1", "label": "b", "value": 627, "variable": "var 2"},
    {"group": "group 2", "label": "c", "value": 638, "variable": "var 2"},
    {"group": "group 3", "label": "c", "value": 619, "variable": "var 2"}
  ]},
  "facet": {
    "column": {"type": "nominal", "field": "group"}
  },
  "spec": {
    "facet": {
      "row": {"type": "nominal", "field": "variable"}
    },
    "spec": {
      "mark": "bar",
      "encoding": {
        "x": {"type": "nominal", "field": "label"},
        "y": {"type": "quantitative", "field": "value"}
      },
      "resolve": {
        "scale": {
          "y": "shared"
        }
      }
    },
    "resolve": {
      "scale": {
        "y": "independent"
      }
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v3.json"
}
```

**Comment by domoritz** [comment]
See https://github.com/vega/vega-lite/pull/2977 for context.

**Comment by romainmartinez** [comment]
All right, thanks for the explanation @domoritz. I'm going to test the workaround.

On the other hand, the figure you generated with vega-lite is still not correct (the axes are not shared between the rows).

What I was looking for was something like `chart.resolve_scale(row='shared', column='independent')`; maybe it should be supported in the future.

**Comment by domoritz** [comment]
> On the other hand, the figure you generated with vega-lite is still not correct (the axes are not shared between the rows).

The spec does not work (we don't support facet of facet) but this is how you would specify it. 

> `chart.resolve_scale(row='shared', column='independent')`

That would not describe whether the y-scale or x-scale should be resolved. It might not seem like it but faceting is one of the most mind-bending things to support in Vega-Lite.
