### ISSUE TITLE
Defining colors per-point programmatically

### ISSUE THREAD

**Issue by willwhitney** [altair-viz/altair#1255]
Altair's color encoding system is very simple to use, but due to its simplicity it fails to cover a variety of long-tail specific use cases. In order to make it more flexible, while preserving the simplicity of the API, I think it would be useful to be able to pass a DataFrame with a column which is a literal color value:

```python
data = pd.DataFrame({'x': np.random.uniform(0, 1, size=1000), 'y': np.random.uniform(0, 1, size=1000)})
data['color'] = '#' + np.floor(data['x'] * 10).astype(int).astype(str) + '00000'

scale_x = alt.Scale(range=['black', 'red'])
alt.Chart(data).mark_point(opacity=0.3).encode(
    x='x',
    y='y',
    color=alt.Color('color')
)
```
![screen shot 2018-12-07 at 12 01 53 pm](https://user-images.githubusercontent.com/597829/49661822-24e5d000-fa18-11e8-9403-35b4bf62987e.png)

This would allow the user to construct any arbitrary mapping between their data and colors, without burdening Altair/Vega with having to represent these mappings. As far as I can tell this is not currently possible.

As an example of the utility of such an API, here's my current problem: I'm looking to make a chart where the color of each point is based on the values of two different (numerical) columns. For a simple case, here are samples from a Gaussian where each point is colored with its green channel determined by its `x` position and its red channel determined by its `y` position.

![2d_color_big](https://user-images.githubusercontent.com/597829/49661515-40041000-fa17-11e8-8113-1d55e913df39.png)

As far as I could tell there isn't a way to do this at the moment. The API I'm proposing would let me construct the right color for each point in Python, then just render them with Altair. 

Please correct me if there's already a way to do any of this!

**Comment by jakevdp** [comment]
You can do this by setting ``scale=None``. For example:
```python
import pandas as pd
import altair as alt

data = pd.DataFrame({
    'x': [1, 2, 3, 4, 5, 6],
    'y': [5, 2, 4, 3, 7, 4],
    'color': ['#FF0000', '#00FF00', '#0000FF', '#FF00FF', '#FFFF00', '#00FFFF']
})

alt.Chart(data).mark_point(filled=True, size=300).encode(
    x='x',
    y='y',
    color=alt.Color('color', scale=None)
)
```
![visualization 13](https://user-images.githubusercontent.com/781659/49663865-d5e26f80-fa04-11e8-9d5d-72da75892fa8.png)

**Comment by willwhitney** [comment]
Right on. Is this documented anywhere, or should I add it?

**Comment by jakevdp** [comment]
I'm not sure it is... it would be a great addition!

**Comment by willwhitney** [comment]
![screen shot 2018-12-07 at 1 16 44 pm](https://user-images.githubusercontent.com/597829/49665486-06390680-fa23-11e8-91fc-5344cd2bfc4d.png)

This is awesome, thanks for the help!

**Comment by rafa-guedes** [comment]
When we use this approach the legend is suppressed. Is it possible define colors this way and set a legend based on corresponding values from another column? For example, modifying a bit the snippet from @jakevdp, is it possible to set a legend using the values from the "label" column?

```python
import pandas as pd
import altair as alt

data = pd.DataFrame({
    'x': [1, 2, 3, 4, 5, 6],
    'y': [5, 2, 4, 3, 7, 4],
    'color': ['red', 'green', 'blue', 'green', 'blue', 'red'],
    'label': ["REDS", "GREENS", "BLUES", "GREENS", "BLUES", "REDS"]
})

alt.Chart(data).mark_point(filled=True, size=300).encode(
    x='x',
    y='y',
    color=alt.Color('color', scale=None)
)
```

![image](https://github.com/altair-viz/altair/assets/7799184/87d2bcbb-b4dd-42e5-b7dc-0870708c65b9)

**Comment by joelostblom** [comment]
One workaround could be to set the range to the unique list of colors in that dataframe column. I believe this should assign the colors to the correct points as long as the list is sorted the same as the color assignment (which is alphabetical by default), but double check using the tooltip for your data.

```python
import pandas as pd
import altair as alt

data = pd.DataFrame({
    'x': [1, 2, 3, 4, 5, 6],
    'y': [5, 2, 4, 3, 7, 4],
    'color': ['red', 'green', 'blue', 'green', 'blue', 'red'],
})

alt.Chart(data).mark_point(filled=True, size=300).encode(
    x='x',
    y='y',
    color=alt.Color('color').scale(range=sorted(data['color'].unique())),
    tooltip='color'
)
```

![image](https://github.com/altair-viz/altair/assets/4560057/a77cca1d-a793-4ffc-a752-623b45603daa)

**Comment by rafa-guedes** [comment]
Thanks @joelostblom but I'm afraid this still does not solve my issue as I need the `label` column to define the labels in the legend. My example was not very helpful in that the values for `color` and `label` columns look similar / interchangeable but in the real case I'm trying to implement those columns are different and I need the unique values in `label` to be used.

**Comment by joelostblom** [comment]
Ah I see. Fortunately that works similarly. You can replace the encoding with you label column while keeping the range the same:

```python
import pandas as pd
import altair as alt

data = pd.DataFrame({
    'x': [1, 2, 3, 4, 5, 6],
    'y': [5, 2, 4, 3, 7, 4],
    'color': ['red', 'green', 'blue', 'green', 'blue', 'red'],
    'label': ["REDS", "GREENS", "BLUES", "GREENS", "BLUES", "REDS"]
})

alt.Chart(data).mark_point(filled=True, size=300).encode(
    x='x',
    y='y',
    color=alt.Color('label').scale(range=sorted(data['color'].unique())),
    tooltip='color'
)
```

![image](https://github.com/altair-viz/altair/assets/4560057/1ff73bf9-d4db-4a59-8b65-cbe2628da6fc)

**Comment by rafa-guedes** [comment]
That works great @joelostblom thank you :)
