### ISSUE TITLE
centred text marks on sorted heat map

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#1263]
Hi Jake,

I assume that Altair 2.3 does not yet have the VL 3 sorting functionality mentioned [here](https://github.com/altair-viz/altair/issues/1137).

I am following a workaround involving making the x axis independent. This fixes the sorting but makes the text marks misaligned. 

### altair version 2.3
```python
se=pd.DataFrame({'estimator': ['mean', 'mean', 'mean', 'mean',
                                'median', 'median', 'median', 'median',
                                'trim_mean', 'trim_mean', 'trim_mean', 'trim_mean'], 
                  'distribution': ['normal', 'lognormal', 'one-wild', 'slash',
                                  'normal', 'lognormal', 'one-wild', 'slash',
                                  'normal', 'lognormal', 'one-wild', 'slash'],
                  'se': [.1, .4658, 1.90, np.nan,
                        .138, .1727, .1679, .7048,
                        .113, .177, .1433, .9649]})


c=alt.Chart().encode(
    y=alt.Y('estimator'),
    tooltip=['estimator', 'distribution', 'se']
)

a=c.mark_rect().encode(
    x=alt.X('distribution', sort=['normal', 'lognormal', 'one-wild', 'slash'], axis=alt.Axis(labelAngle=0)),
    color=alt.Color('se', scale=alt.Scale(domain=[0,.5]))
)

b=c.mark_text(align='center').encode(
    x=alt.X('distribution', sort=['normal', 'lognormal', 'one-wild', 'slash'], 
            axis=alt.Axis(title=None, labels=False, ticks=False)),
    text='se',
)

alt.layer(a,b,data=se).resolve_scale(x='independent')
```

![visualization 61](https://user-images.githubusercontent.com/4624246/49749184-9f5f5b80-fc75-11e8-9210-e79923fe09d5.png)

Is there a way to centre the text while maintaining the custom sort?

**Comment by jakevdp** [comment]
> I assume that Altair 2.3 does not yet have the VL 3 sorting functionality mentioned [here](https://github.com/altair-viz/altair/issues/1137).

No, Altair 2.3 is still tied to Vega-Lite 2.6, as Vega-Lite 3 has yet to be released:
```python
>>> import altair as alt
>>> alt.VEGALITE_VERSION
'2.6.0'
```

Regarding your question, I'm not sure how to answer it. When I run your code I get the following:
![visualization 15](https://user-images.githubusercontent.com/781659/49773935-e9f9cb80-fca7-11e8-9ee1-3c6caa64af72.png)

**Comment by Alcampopiano** [comment]
Thanks Jake. Yes, I should have mentioned that my above example was made in the traditional notebook. Perhaps that is why it shows up oddly. In JL I get the same as you.

Thanks again.

**Comment by jakevdp** [comment]
It might be that you're using an older version of the vega extension in the notebook, in which case an older version of vega-lite is being used to render your chart.

**Comment by jakevdp** [comment]
The rendering should be identical between notebook and jupyterlab if the vega extensions are up to date.

**Comment by Alcampopiano** [comment]
Hmm, I have Vega-Lite 2.6.0 and Altair 2.3.0 in the notebook. Does that tell us that I have the vega extension up-to-date?

**Comment by jakevdp** [comment]
The relevant package for the *notebook renderer* is not Altair, but vega.

It's actually quite difficult to figure out what vega-lite version is being used by the notebook to render your charts (see https://github.com/vega/ipyvega/issues/97 for the open issue on this subject... cc/ @domoritz: this is an example of a situation where that enhancement would be important for users).

You need to update the [vega](https://pypi.org/project/vega/) package in order to update your renderer... version 1.4 is the most recent version.

**Comment by Alcampopiano** [comment]
Thanks Jake. Will do.
