### ISSUE TITLE
when a column of data only have one value, mark_bar failed to plot

### ISSUE THREAD

**Issue by g13** [altair-viz/altair#1269]
mark bar does not plot a single bar, when the elements in the column all have the same value.
Encountered this problem when try to explore the difference between two column of data.
          
          import pandas as pd
          import numpy as np
          import altair as alt
          test = pd.DataFrame({'difference': np.zeros(r.n) + 1})
          alt.Chart(test).mark_bar().encode(alt.X('difference:Q', bin=True), y = 'count()')

**Comment by Alcampopiano** [comment]
Hi there,
Try removing 'bin=true' so that you are not asking for a histogram. I'm away from a computer so I haven't actually tested it.

**Comment by jakevdp** [comment]
The default binning chooses a number of steps between the minimum and maximum value, which in this case leads to bars of width zero.

If you want a different binning rule, you can use the ``alt.Bin`` arguments. For example:
```python
import pandas as pd
import numpy as np
import altair as alt

test = pd.DataFrame({'difference': np.ones(1)})

alt.Chart(test).mark_bar().encode(
    alt.X('difference:Q', bin=alt.Bin(extent=[0, 2])),
    y = 'count()'
)
```
![visualization 17](https://user-images.githubusercontent.com/781659/49874217-c54e4280-fdd2-11e8-93be-e5a285626b93.png)

**Comment by g13** [comment]
I see, it's just that I didn't dig deep enough into the documentation.

Thanks for the help.
