### ISSUE TITLE
rangeStep: warning not returned when using time scale

### ISSUE THREAD

**Issue by alexgmcm** [altair-viz/altair#1272]
**Issue:** 

It seems that rangeStep does not work with time scales (i.e. temporal axes) and the Vega editor returns a warning informing the user of this - but this is not returned to the user by Altair. (it is visible in the Vega Editor)

**Expected Behaviour:** 

When setting the rangeStep parameter with a temporal axis the warning given by Vega is returned to the user. 

This should also be added to the Altair documentation/examples (I am happy to do this but I am unaware of the procedure for doing so.)

**Current Behaviour:**

 No warning is received via Altair and the user can supply the rangeStep parameter but it has no effect on the graph produced.

**Example Code:**

```
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import altair as alt

test={'dt':['2018-12-01','2018-12-02','2018-12-03','2018-12-04','2018-12-05'],
      'val':[1,2,3,4,5]}
test_df=pd.DataFrame.from_dict(test)
test_df['dt']=pd.to_datetime(test_df.dt)

bar = alt.Chart(test_df).mark_bar().encode(
    x=alt.X('dt:T',scale=alt.Scale(rangeStep=50)),
    y=alt.Y('val:Q')
)

bar
```

Note that varying the rangeStep parameter has no effect upon the graph and a warning is given in the Vega Editor.

**Workaround**: 

Convert datetime to string and use nominal or ordinal encoding.

**Comment by jakevdp** [comment]
The vega editor uses a prerelease version of Vega-Lite 3; I think that once Vega-Lite 3 is released and Altair is updated to depend on it, Altair will show this warning as well.

**Comment by jakevdp** [comment]
Altair now reflects this warning in the JSConsole.
