### ISSUE TITLE
share axis within a concat chart for interactivity

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#1273]
I've the following reproducible python code that present my issue:

```python
import altair as alt

# some data
df_url = 'https://raw.githubusercontent.com/mattijn/datasets/master/comb_chart_interactive.json'
states = ['ParkerenKw', 'HorizontaalOpenen', 'Spuien', 'Opdrijven', 'Keren', 'AfzinkenBodem', 'AfzinkenCPSE', 'HorizontaalSluiten', 'Paraat', 'Stremmen', 'Alert', 'Gemobiliseerd', 'Rust']

# charting
top = alt.Chart(df_url).mark_line().encode(
  x = alt.X('index:T', timeUnit = 'yearmonthdatehoursminutes', title = None),
  y = alt.Y('value:Q', title = 'waterlevel [m+NAP]'),
  color = alt.Color('location:N'),
  tooltip = ['state:O', 'comp1:O', 'comp2:O', alt.Tooltip('index:T', format = '%Y-%m-%d %H:%M')]
).properties(
  title = 'Q3_H5_U5_D1 Failuremodus - 0'
).interactive(bind_y = False)

bottom = alt.Chart(df_url).mark_line().encode(
  x = alt.X('index:T', timeUnit = 'yearmonthdatehoursminutes', title = None),
  y = alt.Y('state:O', sort = states),
  order = alt.Order('index:T'),
  tooltip = ['state:O', 'comp1:O', 'comp2:O', alt.Tooltip('index:T', format = '%Y-%m-%d %H:%M')]
).interactive(bind_y = False)

chart = (top & bottom).configure_legend(labelLimit = 0).configure_axisY(grid=True)
chart
```

![interactive_double_chart](https://user-images.githubusercontent.com/5186265/50246577-1616fa00-03d6-11e9-99ea-1ba133f310b8.gif)

Since the `'VConcatChart' object has no attribute 'interactive'` I have to add the interactivity on the `Chart` object, but this keeps me from combined zoom options. 

I would like the zoom capability connected, so when zooming in the bottom chart the top chart will zoom to the same extent (and vice versa).

But currently I am only capable of including zoom options on the chart separately. 
Any hints or suggestions are much appreciated!

**Comment by jakevdp** [comment]
The ``.interactive()`` method is a convenience routine that adds an interval selection that is bound to the scales (see the source [here](https://github.com/altair-viz/altair/blob/3cc554e677b35e80b7e286b5391b08a9a5ced0bb/altair/vegalite/v2/api.py#L1376-L1408)). If you want to do something more fancy than basic interaction, it's possible to create and use  such a selection directly.

In this case, the solution is to create a single interval selection bound to scales, and add that selection object to each chart:
```python
import altair as alt

zoom = alt.selection_interval(bind='scales', encodings=['x'])

# some data
df_url = 'https://raw.githubusercontent.com/mattijn/datasets/master/comb_chart_interactive.json'
states = ['ParkerenKw', 'HorizontaalOpenen', 'Spuien', 'Opdrijven', 'Keren', 'AfzinkenBodem', 'AfzinkenCPSE', 'HorizontaalSluiten', 'Paraat', 'Stremmen', 'Alert', 'Gemobiliseerd', 'Rust']

# charting
top = alt.Chart(df_url).mark_line().encode(
  x = alt.X('index:T', timeUnit = 'yearmonthdatehoursminutes', title = None),
  y = alt.Y('value:Q', title = 'waterlevel [m+NAP]'),
  color = alt.Color('location:N'),
  tooltip = ['state:O', 'comp1:O', 'comp2:O', alt.Tooltip('index:T', format = '%Y-%m-%d %H:%M')]
).properties(
  title = 'Q3_H5_U5_D1 Failuremodus - 0'
).add_selection(zoom)

bottom = alt.Chart(df_url).mark_line().encode(
  x = alt.X('index:T', timeUnit = 'yearmonthdatehoursminutes', title = None),
  y = alt.Y('state:O', sort = states),
  order = alt.Order('index:T'),
  tooltip = ['state:O', 'comp1:O', 'comp2:O', alt.Tooltip('index:T', format = '%Y-%m-%d %H:%M')]
).add_selection(zoom)

chart = (top & bottom).configure_legend(labelLimit = 0).configure_axisY(grid=True)
chart
```

**Comment by jakevdp** [comment]
More about interval selections & binding here: https://altair-viz.github.io/user_guide/interactions.html#interval-selections

**Comment by jakevdp** [comment]
A useful feature might be to add an ``interactive()`` method to concatenated charts that does this, though we'd have to be careful about the implementation (e.g. what happens if you call interactive and then add more subcharts?)

**Comment by mattijn** [comment]
Thanks for the answer and links regarding documentation interval selections!
