### ISSUE TITLE
Rendering with json in colab

### ISSUE THREAD

**Issue by manhnguyen48** [altair-viz/altair#1276]
I'm trying to chart a fairly large dataset (~200k rows) in colab: 
![image](https://user-images.githubusercontent.com/24793324/50355766-a88adb00-0547-11e9-98e5-2c72eb8d4fe2.png)

```
import altair as alt
import os

alt.renderers.enable('colab')
def json_dir(data, data_dir='altairdata'):
    os.makedirs(data_dir, exist_ok=True)
    return alt.pipe(data, alt.to_json(filename=data_dir + '/{prefix}-{hash}.{extension}') )


alt.data_transformers.register('json_dir', json_dir)
alt.data_transformers.enable('json_dir', data_dir='mydata')


alt.Chart(df).mark_bar().encode(
    y='How_Long_Delayed:N',
    x='count()',
)
```

However the output is nothing. I've checked the browser console and turns out the fetch request to the json file was 500 and 404: 
![image](https://user-images.githubusercontent.com/24793324/50355819-d2440200-0547-11e9-8541-52a75c6b4c5e.png)

I've checked the json file via pd.read_json and it's the same as the original dataset.

**Comment by jakevdp** [comment]
The json data transformer does not work in Colab, because the filesystem is not accessible to the frontend. The best approach for visualizing large datasets in colab is to use the default transformer with max_rows=None:
```
alt.data_transformers.enable('default', max_rows=None)
```

**Comment by manhnguyen48** [comment]
Thanks for the quick reply! 

However, after changing to default data transformer, running my chart causes 'Runtime disconnected'. 
```
import altair as alt
import os

alt.renderers.enable('colab')

alt.data_transformers.enable('default', max_rows=None)

chart = alt.Chart(df).mark_bar().encode(
    y='How_Long_Delayed:N',
    x='count()',
)
chart.display()
```

The runtime simply reconnects afterwards and all the variables are still there. 
I'm not using any VPN. 

The runtime info I was able to get: 
Python 3
CPU: Intel(R) Xeon(R) CPU @ 2.30GHz
MemTotal:  13.3GB

Could this purely be Colab's error when rendering?

**Comment by jakevdp** [comment]
I would ask in the Colab help forums.

It may be that your dataset is just too large to render with Altair in Colab.

**Comment by jakevdp** [comment]
Even in the best of circumstances, Vega-Lite gets quite slow on datasets with more than a few tens of thousands of rows. I wouldn't recommend Vega-Lite/Altair as a charting solution for datasets with hundreds of thousands of rows.
