### ISSUE TITLE
Disable to_values data transformer

### ISSUE THREAD

**Issue by domoritz** [altair-viz/altair#1277]
I would like to get an Altair chart where the datasets are still in the original format (e.g. Pandas).

```python
chart = alt.Chart(cars).mark_point().encode(
    x="Horsepower",
    y="Miles_per_Gallon",
    color="Origin",
).interactive()

with alt.data_transformers.enable(to_values=False):
    chart_dict = chart.to_dict()
    # at this point chart_dict should not have the datasets transformed
```

Is this already possible?

**Comment by domoritz** [comment]
```python
alt.data_transformers.register('identity', lambda data: data)

with alt.data_transformers.enable('identity'):
   ...
```

Doesn't seem to work as it fails schema validation.

**Comment by domoritz** [comment]
Ahh, this works

```
def empty(data):
    return {
        "values": []
    }

alt.data_transformers.register("empty", empty)

with alt.data_transformers.enable("empty"):
    ...
```

**Comment by jakevdp** [comment]
Not sure what you mean... if you have the Python object, the data attribute is whatever you passed to the chart. Once you serialize the chart to vega-lite, the data must be serialized to JSON as well...

**Comment by domoritz** [comment]
My goal or to transfer the data separately (with thrift etc) and then insert it through the view API.

**Comment by jakevdp** [comment]
Makes sense... I think a custom data transformer is probably the best bet, but you'll also have to figure out some other mechanism to pass the data to the renderer if it's not going to be part of the spec. Maybe the renderer could support it like it currently supports embed options?
