### ISSUE TITLE
Get the names of consolidated datasets

### ISSUE THREAD

**Issue by domoritz** [altair-viz/altair#1278]
Is there a way to get the mapping from dataset -> consolidated name? 

Related to https://github.com/altair-viz/altair/issues/1277

**Comment by jakevdp** [comment]
It's based on a hash of the serialuzed dataset. See the '_compute_data_hash' function here: https://github.com/altair-viz/altair/blob/master/altair/utils/data.py

**Comment by domoritz** [comment]
Hmm, I don't see `_compute_data_hash` being called in `to_values`, though. How does the dataset consolidation use `_compute_data_hash`?

**Comment by domoritz** [comment]
Ahh, I think I figured out a way to address my problem. I wrote a transformer that creates a named dataset with the id of the python object. I can then transfer the data separately and inject it through the Vega view API. 

Demo: https://colab.research.google.com/drive/1GYE9lAQV7JyKE-NCtaNi7gNzPddbUx_3#scrollTo=HCWBU9UgIlXB

**Comment by jakevdp** [comment]
Nice - that seems like a good solution.
