### ISSUE TITLE
Building rows of charts in for loop to create data dashboards

### ISSUE THREAD

**Issue by dbk123** [altair-viz/altair#1281]
I have an application that begs for building a row (or grid) of charts inside a for loop where the iterated value might a column label in the pandas dataframe.  I've read the documentation for hconcat and repeat methods and repeat is well suited to this, however, my application demands that each chart contain an overlay of data from two different dataframes which (I think) precludes the use of the repeat function.  Is there anyway to iteratively build a list a charts within the for loop and then display them in a row or grid after the loop is done executing?

Thanks in advance!

**Comment by jakevdp** [comment]
I think it's possible to do what you're asking about, but it's hard to say without more information.

Regarding the repeat operator and multiple dataframes, you could use the [lookup transform](https://altair-viz.github.io/user_guide/transform.html#lookup-transform) if it applies to the way you're combining the multiple dataframes.

Otherwise, you can always use a Python loop to create multiple charts, and then concatenate them when finished. Something like this:

```python
charts = []
for i in range(4):
    charts.append(alt.Chart(df).mark_point())
alt.layer(*charts)
```

**Comment by dbk123** [comment]
Hi Jake,
Super helpful information - thanks!  I will give that a try.
-Dave

PS - I am giving some presentations to university computer science and engineering departments in the Northeast in the coming months (Dartmouth and Lehigh to start) and will be mentioning altair as one of the exciting new packages to investigate.  Please keep up the awesome work!

**Comment by jakevdp** [comment]
Thanks, and let me know if you have other questions!

**Comment by Alcampopiano** [comment]
@dbk123 see this for a workaround to maintain interactivity in HTML

https://github.com/altair-viz/altair/issues/329

**Comment by dbk123** [comment]
Thanks!

**Comment by joelostblom** [comment]
@dbk123 I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Comment by dbk123** [comment]
Hi Joel - This for the follow-up this can be closed!

-dbk123
