### ISSUE TITLE
How to specify a custom TimeUnit Transform?

### ISSUE THREAD

**Issue by tylere** [altair-viz/altair#1282]
Is there a way to specify a custom TimeUnit Transform? I would like to group data by half-years, but that is not an option with the set of [TimeUnit Transform](https://altair-viz.github.io/user_guide/transform.html#timeunit-transform)s.

**Comment by jakevdp** [comment]
Altair only supports the time units that Vega-Lite supports. There is an issue in Vega-Lite tracking this sort of question, if you'd like to follow there: https://github.com/vega/vega-lite/issues/3290

**Comment by joelostblom** [comment]
Closing as this is something that needs to be implemented at the Vega-Lite side of things and we can't do anything to fix it in altairl
