### ISSUE TITLE
Example charts with non-linear scale

### ISSUE THREAD

**Issue by jimmywan** [altair-viz/altair#1283]
I wanted to contribute an example for axis customization and was wondering if you thought others might find that helpful. Happy to do what it takes to finish this off and drag it over the finish line as I'm been very happy with Altair and would like to keep giving back.

Thoughts?

A quick search of the existing docs only turned up this example with a log scale in it:
https://altair-viz.github.io/gallery/gapminder_bubble_plot.html?highlight=log%20scale

I was thinking it might be well suited in a section somewhere under here:
https://altair-viz.github.io/user_guide/customization.html#

#### Example snippet:
```python
chart_df = pd.DataFrame(
    {
        'x': list(range(0,20)),
        'y': [2** x for x in range(0,20)],
    }
)
base_chart =  alt.Chart(chart_df).mark_line().encode(
    x=alt.X('x', type='quantitative'),
).properties(
    height=200,
    width=200,
)
chart1 = base_chart.encode(
    y=alt.Y('y', type='quantitative'),
)
chart2 = base_chart.encode(
    y=alt.Y('y', type='quantitative', scale=alt.Scale(type='log', base=2)),
).properties(title='log base 2')
chart3 = base_chart.encode(
    y=alt.Y('y', type='quantitative', scale=alt.Scale(type='log', base=np.e)),
).properties(title='log base e')
chart4 = base_chart.encode(
    y=alt.Y('y', type='quantitative', scale=alt.Scale(type='log')),
).properties(title='log base 10')
display(chart1 | chart2 | chart3 | chart4)
```
Output:
![image](https://user-images.githubusercontent.com/10406673/50730230-38b34d80-110e-11e9-8bf6-f1c6c19fac1c.png)

**Comment by jakevdp** [comment]
This looks great! It would be a welcome addition to the example gallery. Are you comfortable opening a pull request with these changes?  If so, you can add a new file to https://github.com/altair-viz/altair/tree/master/altair/examples, using one of the existing examples as a template.

Let me know if you have questions about that process.

**Comment by jimmywan** [comment]
@jakevdp let me know if #1290 is sufficient.
