### ISSUE TITLE
try to detect correct renderer

### ISSUE THREAD

**Issue by noragen** [altair-viz/altair#1291]
Hi, this is more a proposal then an issue for a little bit more user-friendly behaviour.

I suggest to define the renderer by adding something like this, needs surely to be rewritten when applied internally:

```
import altair as alt

try:
    import re
    import psutil
    if alt.renderers.active=='default':
          renderer={**{'jupyter-lab': 'default'}, **{}.fromkeys( ['jupyter-notebook','beakerx-script'], 'notebook')}.get( re.search(r'\bjupyter-(lab|notebook)\b|\bbeakerx-script\b', ",".join(psutil.Process().parent().cmdline())).group(0) , "default" )
    else:
          renderer = alt.renderers.active
except:
    print ("Could not determine renderer, switched to 'default', please set it manually: alt.renderers.enable('default|notebook|etc..')")
    renderer='default'
finally:
    alt.renderers.enable(renderer)
```

**Comment by jakevdp** [comment]
We've discussed this sort of thing before, but I can't find the reference. By design, Jupyter kernels are agnostic to the frontend that is executing them, and there's generally no robust way to sniff-out the flavor of the frontend from the kernel. Hacks like this work in some situations, but I'm not comfortable relying on them inside the package itself.

**Comment by noragen** [comment]
Hi Jake, thank you for your reply. It is not only that it makes the user code more reliable, the users are also more independent for exchange the users-code with other users in jupyter notebook / lab. Also it makes it more comfortable to work with altair. If the automatic renderer does not match or however could not be used, it can be changed as in past, easily.
I don't insist on the fact, that this is a complete solution covering all possibilities and UI' and surely could be enhanced, but in every case it can make collaboration damn easier. ;)
Although not all is covered I suppose at least 80%, maybe more then 90% cases are covered.

**Comment by jakevdp** [comment]
I think the place for this sort of code would be in the IPython kernel itself. If an API to inspect the frontend were available there, I would be excited for Altair to use it.

**Comment by noragen** [comment]
Hi Jake actually a very good idea. Let's try to get this realized. 😊

**Comment by binste** [comment]
The `html` renderer is now the default and it is supported across a wide range of frontends and therefore seems to address the original issue here. But feel free to reopen if I missed anything!
