### ISSUE TITLE
How to use alt.Scale with alt.SelectionDomain

### ISSUE THREAD

**Issue by jakubczakon** [altair-viz/altair#1293]
I am working with temporal `T` x domain and I want to filter the chart by some selection on another chart and adjust the x range based on that selection.

```python
line = alt.Chart().mark_line(interpolate='step-after', size=5).encode(
    x=alt.X('time:T', scale=alt.Scale()),
    y=alt.Y('count:Q', scale=alt.Scale(zero=False))
).transform_filter(
    brush
)
```

I've read that you can pass `alt.SelectionDomain` object to the `alt.Scale(domain=)` parameter but I cannot figure how can I instantiate the `alt.SelectionDomain` class.

I tried `alt.SelectionDomain(brush)` to no avail.
Please help.

**Comment by jakevdp** [comment]
You can use ``alt.Scale(domain=brush.ref())``

There is an example here: https://altair-viz.github.io/gallery/interval_selection.html

**Comment by jakubczakon** [comment]
Awesome, it helped!

Thanks for such a great job on this lib by the way. I've been working on some stuff for the past few days and I have to say I am positively surprised. It is just so easy to talk to!

**Comment by jakevdp** [comment]
Thanks for the feedback :smile:
