### ISSUE TITLE
Question, crossfilter two datasets with a common field ?

### ISSUE THREAD

**Issue by djouallah** [altair-viz/altair#1295]
does altair support cross filtering of two datasets with a common key

let say df1=category, day, revenue
          df2=category, week, budget

is it possible to to have a chart 1 based on df1, when i select on category, it will filter on chart 2 ?

I can do it now but appending the two datasets just wondering if there is a transformation that can link two datasets

**Comment by jakevdp** [comment]
Yes, the way to do it would be to use a [lookup transform](https://altair-viz.github.io/user_guide/transform.html#lookup-transform) along with a filter operation.

**Comment by djouallah** [comment]
What if category is not unique, does the left joint return multiple values
