### ISSUE TITLE
Force Altair to Share Axis / Get Domain Range

### ISSUE THREAD

**Issue by ajennings6767** [altair-viz/altair#1298]
Hi,

I am looking to figure out how to either:
a) Force a concatenated chart to share an axis
b) Retrieve the domain (y and/or x limits) of another chart

You can see in the below that I have concatenated a series of charts. I would like the histograms on the right to have the same y domain as the line charts on the left.

Any ideas?

Thanks!
```
chart1 = alt.Chart(temp.loc[temp['Series'] != 'Error', :]).mark_line().encode(
    alt.X('index:T'),
    alt.Y('value:Q'),
    alt.Color('Series:N', legend=alt.Legend(orient='left')),
).properties(
    height=400,
    width=1000
)

chart2 = alt.Chart(temp.loc[temp['Series'] == 'Error', :]).mark_line().encode(
    alt.X('index:T'),
    alt.Y('value:Q'),
    color='Series:N'
).properties(
    height=200,
    width=1000
)

chart3 = alt.Chart(temp.loc[temp['Series'] == 'Error', :]).mark_bar().encode(
    alt.X('count()'),
    alt.Y('value:Q', bin=alt.Bin(maxbins=100)),
    alt.Color('Series:N')
).properties(
    height=200,
    width=200
)

chart4 = alt.Chart(temp.loc[temp['Series'] != 'Error', :]).mark_bar(opacity=.4).encode(
    alt.X('count()'),
    alt.Y('value:Q', bin=alt.Bin(maxbins=100)),
    alt.Color('Series:N')
).properties(
    height=400,
    width=200
)

alt.vconcat(
    alt.hconcat(
        chart1,
        chart4
        ),
    alt.hconcat(
        chart2,
        chart3
        )
)
```
![visualization 8](https://user-images.githubusercontent.com/30580411/51201390-eae6d400-18c9-11e9-8465-93a9d15f8d22.png)

**Comment by jakevdp** [comment]
You can use the ``resolve_scale`` method to specify shared scales. Here is a quick example:
```python
import altair as alt
import pandas as pd
import numpy as np

np.random.seed(42)

df = pd.DataFrame({
    'x': np.linspace(0, 10, 500),
    'y': np.random.randn(500).cumsum()
})

line = alt.Chart(df).mark_line().encode(
    x='x',
    y='y'
)

hist = alt.Chart(df).mark_bar().encode(
    x='count()',
    y=alt.Y('y', bin=alt.Bin(maxbins=10), title=None)
).properties(
    width=100
)

alt.hconcat(
    line,
    hist
).resolve_scale(
    y='shared'
)
```
![visualization 2](https://user-images.githubusercontent.com/781659/51203655-7191b600-18b6-11e9-917d-96d0bd0118cc.png)

**Comment by jakevdp** [comment]
Another way you can approach it is to bind the scales of both plots to a single selection object, which results in a dynamic scale:
```python
import altair as alt
import pandas as pd
import numpy as np

np.random.seed(42)

y_domain = alt.selection_interval(bind='scales', encodings=['y'])

df = pd.DataFrame({
    'x': np.linspace(0, 10, 500),
    'y': np.random.randn(500).cumsum()
})

line = alt.Chart(df).mark_line().encode(
    x='x',
    y='y'
).add_selection(
    y_domain
)

hist = alt.Chart(df).mark_bar().encode(
    x='count()',
    y=alt.Y('y', bin=alt.Bin(maxbins=30), title=None)
).properties(
    width=100
).add_selection(
    y_domain
)


alt.hconcat(
    line,
    hist
)
```

**Comment by ajennings6767** [comment]
Thanks this is exactly what I needed!

![visualization 9](https://user-images.githubusercontent.com/30580411/51207389-a6166980-18d8-11e9-9db3-8906ada77644.png)

For reference, is there any way to get the x/y limits from one of the other charts in order to apply it to the related charts on the right.

Clearly, you could just write a function to gather/set the ranges based on the "parent" data set (as you outlined), but I'm just curious.

**Comment by jakevdp** [comment]
Not really... the x/y limits are determined by the renderer, and so they are not accessible within Python.

**Comment by ajennings6767** [comment]
Ah - that's too bad.

Thanks so much for your help!
