### ISSUE TITLE
mark_rect opacity

### ISSUE THREAD

**Issue by romainmartinez** [altair-viz/altair#1302]
It seems that the `opacity` parameter has no effect on `mark_rect`:

```python
df = pd.DataFrame({"value": np.arange(10)}).assign(lower=1, upper=3)

line = alt.Chart().mark_line().encode(x="value", y="value")
area = alt.Chart().mark_rect(opacity=0.5).encode(x="lower", x2="upper")

(line + area).facet(data=df)
```
![visualization](https://user-images.githubusercontent.com/17710617/51432589-fad32080-1c07-11e9-9ce5-696e38b6e238.png)

I also tried the `fillOpacity` and `strokeOpacity` parameters, but without success.

Using `mark_area` works but requires to define `y` and `y2`. 

Thanks for Atlair!

**Comment by romainmartinez** [comment]
Oh ok that makes sense, thank you Jake!

Working solution:

```python
line = (
    alt.Chart(pd.DataFrame({"value": np.arange(10)}))
    .mark_line()
    .encode(x="value", y="value")
)
area = (
    alt.Chart(pd.DataFrame({"lower": 1, "upper": 3}, index=[0]))
    .mark_rect(opacity=0.5)
    .encode(x="lower", x2="upper")
)

line + area
```

**Comment by jakevdp** [comment]
Great!

**Comment by luna7** [comment]
Hi @jakevdp, what would be the method to achieve a rectangular shaded area with a modified opacity in a layered chart where the other component of the layered chart is a line chart drawing from a DataFrame with multiple rows, with the additional requirement that the layered chart will be faceted and thus the rectangle chart needs to also reference the same multi-row DataFrame?

I'm trying the following:

```
        line = alt.Chart(data).mark_line().encode(
            x='x',
            y='y',
        )

        rectangle = alt.Chart().mark_rect().encode(
            y=alt.YDatum(-6).scale(domain=[-12,-4]),
            y2=alt.Y2Datum(-4),
            color=alt.ColorValue("#FF0000"),
            opacity=alt.OpacityValue(0.3)
        )
        
        layered = rectangle + line

        faceted = layered.facet('facet', columns=32, spacing=1)
```

And you can assume that `data` has columns `'x'`, `'y'` and `'facet'`, and multiple rows.

When I run the above code, I get:
```
ValueError: Facet charts require data to be specified at the top level. If you are trying to facet layered or concatenated charts, ensure that the same data variable is passed to each chart or specify the data inside the facet method instead.
```

But if I pass `data` to the rectangle chart, the correct opacity is no longer displayed, namely for the reason you describe above.

Thanks for the help!
