### ISSUE TITLE
Space between rectangles / bars?

### ISSUE THREAD

**Issue by breadbaron** [altair-viz/altair#1305]
Sorry if this is covered elsewhere, but I wasn't able to find it anywhere. When using mark_bar() or mark_rect() to create a heatmap, is it possible to remove the spacing between rectangles/bars? 

In my case I'm plotting a 2-D density and the rectangle boundaries distract from the density.
thanks!

![visualization 366](https://user-images.githubusercontent.com/130067/51570475-f3a05280-1e53-11e9-8e08-73d5c2f382db.png)

**Comment by breadbaron** [comment]
Thanks for looking into that @jakevdp . This solution works great

**Comment by mattijn** [comment]
A better solution would be to adjust the inner padding for x and y band-ordinal scales using the `bandPaddingInner`, which defaults to `0.1`.

```python
alt.Chart(data).mark_rect().encode(
  x='x:O',
  y='y:O',
  fill='z:Q'
).configure_scale(bandPaddingInner=0)
```

**Comment by jakevdp** [comment]
Thanks @mattjin – I didn't know about that configuration.

**Comment by caleb-lindgren** [comment]
Just a quick note for anyone else who comes across this--the `bandPaddingInner` solution didn't work for me, but the `fill` and `stroke` solution worked fine. Either there was some change in the code, or there's something different about my plot.

**Comment by suddenlyfleck** [comment]
I use altair's `mark_rect()` to display a heatmap of data. The data I display originates from microscope images with an aspect ratio of (roughly) 16:10.

Therefore I chose `mark_rect(width=16, height=10)`, hoping to get an undistorted heatmap.

I see white borders (as op does). The stroke-workaround of @jakevdp does not fix the aspect ratio problem. The solution by @mattijn seems like what I need, but does not work. 


What I would need - in other words - is something toe the effect of matplotlib's axis option 'image':

https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.axis.html


I'll use matplotlib for the time being.

**Comment by mattijn** [comment]
One option is to define the width and height of each rect like you did in combination with defining the overall with and height of the chart. 
```python
alt.Chart(data).mark_rect(width=16, height=10).encode(
  x='x:O',
  y='y:O',
  fill='z:Q'
).properties(width=16*30, height=10*30)
```
(In this example the source array is 30x30). 
![image](https://user-images.githubusercontent.com/5186265/113193733-9a68b080-9260-11eb-963a-5338dca725e4.png)

**Comment by mfouesneau** [comment]
Still having this issue. The trick of resizing the figure does not work when you have a lot of pixels.
making the stroke follow the fill property renders weird pixels.

Any idea how to clean the figure from the line/padding issue?

**Comment by joelostblom** [comment]
@mfouesneau You might be running into this VegaLite issue which sometimes creates gaps between marks https://github.com/vega/vega-lite/issues/9307. See there for workarounds

**Comment by joelostblom** [comment]
The only workarounds I'm aware of are those mentioned above and in the issue I linked. Feel free to thumbs up that issue to indicate that it is important to you that a fix is implemented (or contribute to the discussion if you have some additional info/suggestion of how to fix it).
