### ISSUE TITLE
how to configure the `domain` of color in a heatmap at top level

### ISSUE THREAD

**Issue by xujiboy** [altair-viz/altair#1307]
Hi,

I have constructed a heatmap chart with numerical data and now I would like to control the heatmap color domain at the top level. The `Chart.configure_range()` seems to be a possible way but so far I haven't figured out how it can work. However, I do notice that in the vega-lite spec, I can easily change the domain to say, from 0 to 10000 like this:
```
...
"scales": [
...
   {
      "name": "color",
      "type": "sequential",
      "domain": [0,10000],
      "range": {"scheme": "redyellowblue"},
      "zero": false,
      "reverse": true
    }
],
...
```
My question is, is there an equivalent way to do the same thing with a constructed `Chart` instance? Thanks.

**Comment by jakevdp** [comment]
Yes, every Vega-Lite command maps directly to an Altair command. The snippet above appears to be part of a Vega spec rather than vega-lite spec, though, so there is no altair equivalent.

The way you can control scales within Altair/Vega-Lite is via the scale property of the encoding; for example:

```python
alt.Chart(data).encode(
    color=alt.Color('color:Q', scale=alt.Scale(domain=[0, 10000]))
)
```

**Comment by xujiboy** [comment]
@jakevdp Thanks a lot for the explanation. But is there a way to do it at the top level? Meaning that a chart is already constructed and saved as, for example, chart.json, and I would like to read this json file back into Altair to reconstruct a `Chart` instance, and then manipulate the `domain` property from there.

**Comment by xujiboy** [comment]
@jakevdp I understand your point, which makes sense for chart that is composed of multiple, independent sub-charts. Sorry that I didn't explain my case better earlier. So what I have is a collection of already-produced heatmaps in json format, and they all have their own color bars which marks the min and max of the data. I would like to normalize and align the color bars to the same data range, so that I look at all the charts together and compare. One way of course is to do some pre-analysis of all the data and normalize the `domain` during `Altair` charting, but I wonder if there's another way to do this retrospectively.

**Comment by xujiboy** [comment]
> Each of these encodings have a scale, and setting the domain globally (so that the x axis, y axis, color, and size all have the same domain) does not make sense.

Now I get what you mean and I completely agree.
Theme is another interesting aspect that I haven't explored much but definitely worth looking into. And after some experimenting I just found that concatenating multiple heatmap charts together actually gives what I wanted: the color bar and the color in the heatmaps are automatically aligned, very nice.

**Comment by jakevdp** [comment]
Great!

Just some extra info: the reason those scales align is because the default ``resolve`` setting for color scales is ``"shared"``. If you don't want the scales to be shared, you can change this through the ``resolve_scale()`` method; e.g.
```python
alt.layer(chart1, chart2).resolve_scale(
  color='independent' # default is 'shared'
)
```
