### ISSUE TITLE
Aggregate functions on Boolean and categorical values

### ISSUE THREAD

**Issue by HarvsG** [altair-viz/altair#1308]
Lets say I have a dataframe as such - with a boolean endpoint

```
d = {
    'patient': [1,2,3,4,5,6,7,8,9], 
    'drug received': ['a','a','a','a','b','b','b','c','c','c',], 
    'cured':['True','False','True','False','True','False','True','False','True','False'],
    'Gender':['M','F','M','F','M','F','M','F','M','F']}
df = pd.DataFrame(data=d)
```
And i want to see the proportions cured on each drug
```
alt.Chart(df).mark_bar().encode(
        x = 'drug received:N',
        y = 'count(cured)',       
)
```
Just generates 3 bars with lengths equal to the number of patients on each drug, as it treats True and False as just the same.

The work around I have to do is

```
df['cured'] = df['cured'].map({False:0, True:1})
alt.Chart(df).mark_bar().encode(
        x = 'drug received:N',
        y = 'mean(cured):Q',       
)
```
or
```
df['cured'] = df['cured'].map({False:np.nan, True:True})
alt.Chart(df).mark_bar().encode(
        x = 'drug received:N',
        y = 'count(cured):Q',       
)
```

Which seems a little odd, whats more if I add  `color = 'Gender:N'` to the encoding, I get very weird results.

Is there a more elegant way of performing aggregate functions for Boolean values - and further to this, are there any for categorical functions.

**Comment by jakevdp** [comment]
Your data consist of strings ``"True"`` and ``"False"``. If you use boolean ``True`` and ``False`` instead, I think it will work as you expect.

**Comment by jakevdp** [comment]
Here is an example (using a ``sum`` rather than a ``count`` aggregate; ``count`` will simply count all the values):
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'patient': [0, 1, 2, 3, 4, 5, 6, 7, 8, 9], 
    'drug received': ['a','a','a','a','b','b','b','c','c','c',], 
    'cured':[True, False, True, False, True, False, True, False, True, False]
})

alt.Chart(df).mark_bar().encode(
   x='drug received:N',
   y='sum(cured):Q',       
)
```
![visualization 27](https://user-images.githubusercontent.com/781659/51704607-5289d700-1fce-11e9-9b7a-1c20c0ca7317.png)

**Comment by jakevdp** [comment]
An alternative is to filter-out the false values and show the count:
```python
alt.Chart(df).mark_bar().encode(
   x='drug received:N',
   y='count(cured):Q',       
).transform_filter(
   alt.datum.cured
)
```

**Comment by HarvsG** [comment]
Yes, this worked perfectly, and with `mean()` as well.
I used this code to convert my binary `1`,`0` columns into `True` `False` columns.

```
io_only = df.loc[:, ((df == 1) | (df == 0)).all(axis=0)]
io_columns = io_only.columns
del io_only
for col in io_columns:
    df[col] = df[col].map({0:False, 1:True}, na_action = 'ignore')
```

Thank you for your help.
