### ISSUE TITLE
Is there a way to rotate the y-axis label and sit in the upper left corner?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#1310]
Many news charts rotate the y-axis label so it can be read left to right and lift it to sit above the top of the axis. I've roughly recreated this in Altair, but longer axis titles generate this bug. Any idea how to fix it? I don't see a text anchor setting in Vega-Lite I can use.

![visualization 2](https://user-images.githubusercontent.com/9993/51712469-aeab2600-1fe3-11e9-91aa-c3efd90d04bd.png)

```python
import altair as alt
from vega_datasets import data

source = data.iowa_electricity()

alt.Chart(source, title="Iowa's renewable energy boom").mark_line().encode(
    x=alt.X(
        "year:T",
        axis=alt.Axis(title="Year")
    ),
    y=alt.Y(
        "net_generation:Q",
        title="Net generation (in thousand megawatthours)",
    ),
    color=alt.Color(
        "source:N",
        legend=alt.Legend(title="Electricity source"),
    )
).configure_axisY(
    titleAngle=0,
    titleY=-10,
    titleX=-10,
)
```

**Comment by jakevdp** [comment]
Not that I know of... it might be worth asking in the Vega-Lite forums.

**Comment by palewire** [comment]
I've filed a ticket with Vega-Lite.

https://github.com/vega/vega-lite/issues/4492

**Comment by palewire** [comment]
Looks like there's an axis setting now called `titleAlign`. If I put "left" in there it seems to work.

![download](https://user-images.githubusercontent.com/9993/51815102-9f420c00-2273-11e9-8467-20c2302ea34c.png)
```python
import altair as alt
from vega_datasets import data

source = data.iowa_electricity()

alt.Chart(source, title="Iowa's renewable energy boom").mark_line().encode(
    x=alt.X(
        "year:T",
        axis=alt.Axis(title="Year")
    ),
    y=alt.Y(
        "net_generation:Q",
        title="Net generation (in thousand megawatthours)",
    ),
    color=alt.Color(
        "source:N",
        legend=alt.Legend(title="Electricity source"),
    )
).configure_axisY(
    titleAngle=0,
    titleAlign="left",
    titleY=-10,
    titleX=-10,
)
```

**Comment by jakevdp** [comment]
Cool, I didn't know about that 😄

**Comment by palewire** [comment]
I guess I can close the ticket now. I doubt anyone cares, but IMHO this should be the y-axis's default title position. Commonplace in media. Much more legible.
