### ISSUE TITLE
Vega renames my columns

### ISSUE THREAD

**Issue by HarvsG** [altair-viz/altair#1313]
My chart code is as below
```
cols_for_chart = ['column_A', 'column_B', 'column_C', 'number', 'location']

chart = alt.Chart(df[cols_for_chart]).mark_point().encode(
        x = 'column_B:Q',
        y = 'column_A:Q',
        color = 'location:N',
        tooltip = 'number:N'
)
chart
```
However, when I run the code I get a blank chart that doesn't seem to be any of the issues [here](https://altair-viz.github.io/user_guide/troubleshooting.html). When I look at the underlying vega I see that some, but not all, of the columns have been renamed in the format `_x` for no discernible reason.

I am running [this](https://github.com/kleinee/jns) install of Jupyter on a raspberry pi 3 running python 3.5
```
 "values": [
        {
          "number": 74,
          "_1": 0.407222977488288,
          "location": "XXX_IP",
          "column_C": "severe",
          "_0": 0.868440022280233
        },
```
However, when I run the same code on my ubuntu install (anaconda) then I get a perfect graph :) and the vega is as below. Python 3.6
```
      "values": [
        {
          "column_A": 0.868443337280233,
          "column_B": 0.407303973338288,
          "column_C": "severe",
          "number": 76,
          "location": "XXX_IP"
        },
```
When I put the whole df in to see what the vega output was I saw that about 2 thirds of the columns had been renamed in this fashion. It looked as if it was all column names with whitespace in, but replacing this with underscores did not fix the issue.

Edit: it seems to be doing this with any special character - so far I have identified `' ', ')', '(', '/'` as characters that cause this behaviour.

**Comment by jakevdp** [comment]
Several characters have special meanings in vega-lite. If your columns contain those, they should be renamed. See the description of the ``"field"`` property here: https://altair-viz.github.io/user_guide/encoding.html#encoding-channel-options

**Comment by jakevdp** [comment]
Looking closer at this, it seems like the issue is in different versions of the vega/vega-lite javascript dependencies. These are packaged with the jupyterlab/jupyter notebook installation itself, rather than with Altair. I suspect fixing this will require an update of the version of jupyter notebook used in https://github.com/kleinee/jns.

**Comment by HarvsG** [comment]
On the pi running jns (graphing error)
```
(jns) $ jupyter notebook --version
> 5.7.4
(jns) $ jupyter --version
> 4.4.0
(jns) $ jupyter lab --version
> 0.35.4
(jns) $ python --version
> 3.5.3
```
On my laptop running conda (no graphing error)
```
(py36) $ jupyter notebook --version
> 5.7.0
(py36) $ jupyter --version
> 4.4.0
(py36) $ jupyter lab --version
> 0.35.4
(py36) $ python --version
> 3.6.4
```

**Comment by jakevdp** [comment]
Unfortunately, it's currently quite difficult to inspect the javascript versions in your currently-installed extensions. See https://github.com/vega/ipyvega/issues/97

But if your vega JS is behaving differently between machines, I think it's reasonable to guess that you have different library versions installed on each machine.

**Comment by jakevdp** [comment]
More details: if you're using JupyterLab, the vega JS libraries are bundled with JupyterLab itself. If you're using jupyter notebook, the vega JS libraries are provided by the [vega](https://github.com/vega/ipyvega) package. Different versions of the vega package imply different versions of the vega/vega-lite javascript:
```python
>>> import vega
>>> vega.__version__
```

**Comment by HarvsG** [comment]
pi:
```
import vega
vega.__version__
'2.0.0'
```
laptop:
```
import vega
vega.__version__
--------------------------------------------------------------------------
ModuleNotFoundError                      Traceback (most recent call last)
<ipython-input-4-ab83a66286da> in <module>()
----> 1 import vega
      2 vega.__version__

ModuleNotFoundError: No module named 'vega'
```
weird.

**Comment by jakevdp** [comment]
I suspect you're using JupyterLab rather than Jupyter notebook on your laptop. The vega package is only required for the classic notebook.

Vega version 2.0 contains a prerelease of vegalite.js version 3.0, which has a number of bugs. If you downgrade the vega python package to 1.4, it should work identically to JupyterLab on your own laptop.

**Comment by jakevdp** [comment]
So, to summarize the reason for your issue: on the machine where your chart worked, you were rendering the plot with vegalite.js v2.6 via JupyterLab. On the machine where your chart didn't work, you were rendering the plot with the unstable vegalite.js v3.0 prerelease candidate, via a mistakenly-released version of the Jupyter notebook extension.

Downgrade the vega package (which includes the vega notebook extension) to version 1.4, and things should work properly.
