### ISSUE TITLE
Plotting legend below chart

### ISSUE THREAD

**Issue by maxgerma** [altair-viz/altair#1327]
Dear all,

first I want to say that I love Altair's logic of creating charts!
Now the issue: I have concatenated several charts to a 2x2 plot and need the (single) legend to be placed below the entire 2x2 plot. Is there a way of doing so in Altair? I really don't want to have to redo plotting in matplotlib (using fig.legend or bbox_to_anchor as proposed for such cases) or other packages.

Best, Maximilian

**Comment by jakevdp** [comment]
You can see the available options for controlling the legend appearance in the [``alt.Legend`` documentation](https://altair-viz.github.io/user_guide/generated/core/altair.Legend.html#altair.Legend), which should be passed as an argument to the color encoding, for example:
```
chart.encode(
    #...
    color=alt.Color('value', legend=alt.Legend(orient='right'))
    #...
)
```
The available options for controlling the legend appearance are relatively limited in the current release of Altair; these will be greatly expanded in Altair v3, which is built on Vega-Lite 3 (you can read about the options in Vega-Lite 3 [in the vega-lite docs](https://vega.github.io/vega-lite/docs/legend.html#properties).

Once vega-lite 3 is released, we will work on an Altair release that will also provide these options.

**Comment by maxgerma** [comment]
Thanks for the prompt reply. I am looking forward to the next release then.

**Comment by jakevdp** [comment]
In Altair 3, the current release, you can use ``orient='bottom'``. For example
```python
import altair as alt
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_point().encode(
  x='Horsepower',
  y='Miles_per_Gallon',
  color='Origin'
).configure_legend(
  orient='bottom'
)
```
![visualization (99)](https://user-images.githubusercontent.com/781659/58382431-e79ddc00-7f7e-11e9-9bf6-85b300275aa6.png)
