### ISSUE TITLE
grouped bar with text labels

### ISSUE THREAD

**Issue by python152** [altair-viz/altair#1329]
hi - I am trying to follow the example of bar chart with label - only difference here is grouped bar.
and I got invalid schema errors. 

```
import altair as alt
from vega_datasets import data

source = data.barley()

bars = alt.Chart(source).mark_bar().encode(
    x='sum(yield):Q',
    y='year:O',
    color='year:N',
    row='site:N'
)

texts = bars.mark_text(
    align='left',
    baseline='middle',
    dx=3  # Nudges text to right so it doesn't appear on top of the bar
).encode(
    text='sum(yield):Q'
)

bars + texts
```

Either bars or texts can be displayed correctly on their own, just not both?

![visualization 1](https://user-images.githubusercontent.com/17506882/52639450-5066ba00-2ea2-11e9-89a6-c4858eedc57f.png)

![visualization](https://user-images.githubusercontent.com/17506882/52639418-3cbb5380-2ea2-11e9-822c-384cab43c211.png)

**Comment by jakevdp** [comment]
Faceted charts cannot be layered, but layered charts can be faceted:
```python
import altair as alt
from vega_datasets import data

source = data.barley()

bars = alt.Chart().mark_bar().encode(
    x='sum(yield):Q',
    y='year:O',
    color='year:N',
)

texts = bars.mark_text(
    align='left',
    baseline='middle',
    dx=3  # Nudges text to right so it doesn't appear on top of the bar
).encode(
    text='sum(yield):Q'
)

alt.layer(bars, texts, data=source).facet(row='site:N')
```
![visualization 34](https://user-images.githubusercontent.com/781659/52643383-c6165a00-2e91-11e9-84f2-159ffb31a596.png)

**Comment by python152** [comment]
got it. Thanks a lot!
