### ISSUE TITLE
missing .serve() .save() methods 

### ISSUE THREAD

**Issue by maliky** [altair-viz/altair#1330]
Hi,

It's seems that something changed since the docs were written.
the  https://altair-viz.github.io/user_guide/display_frontends.html#display-notebook mention a `.serve()` method to the chart object but this method is missing.

Same with the end of the tutorial https://altair-viz.github.io/getting_started/starting.html mentionning a `.save()` but also missing.

**Comment by jakevdp** [comment]
These methods are present in the current version of Altair. If you update your Altair installation, you should be able to use them.

**Comment by maliky** [comment]
Sorry, settled. I just needed to update my pipenv.  
Thank you. and the svg output renders well in emacs :o)
