### ISSUE TITLE
Trellis Stacked Bar Chart not Displaying on Jupyter Lab v0.35.4

### ISSUE THREAD

**Issue by allenjlee** [altair-viz/altair#1334]
Has anyone encountered this issue with the trellis plot not displaying? The scatter plot displays fine, and most other plots do. Just this plot I'm having trouble with. I also tried using an older version (IPython version 5.5.0) and it works fine there.

Specs:
IPython version = 7.0.1
Jupyter Lab version = 0.35.4
Jupyter Notebook version = 5.5.0
Jupyter version = 4.4.0

<img width="773" alt="problem" src="https://user-images.githubusercontent.com/24996586/52741552-9788a400-2fa3-11e9-8ed0-129df0cbd5a2.png">

**Comment by jakevdp** [comment]
This is an issue with pandas 0.24.0; see #1314. It's fixed in Altair master, but not yet in a release. If you downgrade pandas to 0.23.0 for the time being, it should fix the issue.
