### ISSUE TITLE
Mouse Hover effect does not work in Jupyter Lab?

### ISSUE THREAD

**Issue by noklam** [altair-viz/altair#1335]
When I open it in vega-editor, it show tooltips when my mouse hover over it.
![image](https://user-images.githubusercontent.com/18221871/52801847-ba0ce100-30b9-11e9-9748-3b17d6d96e97.png)

Inside Lab environment, the interactive plot still work but it will not show values automatically when I hover over it.
![image](https://user-images.githubusercontent.com/18221871/52801886-cb55ed80-30b9-11e9-8b14-d992514e130e.png)
![image](https://user-images.githubusercontent.com/18221871/52801903-d3ae2880-30b9-11e9-801d-18759be22075.png)

**Comment by jakevdp** [comment]
The vega editor uses vega-lite version 3 (which is not yet released). Vega-Lite 3 introduced the behavior of adding tooltips by default.

The jupyterlab renderer uses Vega-Lite version 2.3, which does not add tooltips by default, and so you must specify a tooltip encoding if you'd like to use tooltips, as in [this example](https://altair-viz.github.io/gallery/scatter_tooltips.html).
