### ISSUE TITLE
No errors but graph doesn't display (other graphs work)

### ISSUE THREAD

**Issue by mcrone** [altair-viz/altair#1337]
I'm hoping to please get some feedback on a problem that I've been having. I have my data in the following format:

Dataframe (long)
![image](https://user-images.githubusercontent.com/4923807/52914677-99b47080-32cb-11e9-87f2-bbb741e65176.png)

I then try to plot my data and although there are no errors the graph doesn't display. Is there a problem with my data formatting? It's quite tricky to troubleshoot because of the lack of errors here!

```
source = alt.Chart(long).interactive()

source.mark_line().encode(
      x='index',
      y='mean',
      color='sample'
)
```

**Comment by jakevdp** [comment]
It's hard to tell if there's a problem with your data formatting from a screenshot and an incomplete code snippet (e.g. there's no way to tell what the ``long`` variable refers to).

Could you post a complete code snippet that reproduces the issue?

**Comment by mcrone** [comment]
Sorry about that! Here is the complete code snippet with my datafile.

I started off with a csv with data in this format (output from a platereader).

![image](https://user-images.githubusercontent.com/4923807/52919516-70afd200-3303-11e9-9d62-2cf93f716058.png)

Here's the data file:
[datafile.xlsx](https://github.com/altair-viz/altair/files/2873442/datafile.xlsx)

```
#read the file
file = r'datafile.xlsx'
df = pd.read_excel(file,index_col=False)

#select the fluorescence channel
selectchannel = 'Raw Data (483-14/530-30 3)'

filter_col=[col for col in df if (col.startswith('Content')) or (col.startswith(selectchannel))]

df = df[filter_col]

df = df[np.isfinite(df[selectchannel])]

#remove the first row and set the first row as the the new "index"
df.columns = df.iloc[0]
df = df.reindex(df.index.drop(0)).reset_index(drop=True)
df.columns.name = None

```

```
long = df.T

#remove the first row and set the first row as the the new "index"
long.columns = long.iloc[0]
long = long.reset_index()
long = long[1:]

long = long.melt(id_vars='index', var_name='sample', value_name='value')

#gets rid of the error where all values were objects instead of numbers so couldn't work out mean and std
long.value = long.value.astype(float)
#group samples together to get the mean and standard deviation
long = long.groupby(['index','sample']).agg(['mean', 'std'])

long.columns = long.columns.droplevel()

long= long.reset_index()

print(long)

source = alt.Chart(long).interactive()


source.mark_line().encode(
      x='index',
      y='mean',
      color='sample'
)
```

I apologise if this is a bit of a "hacky" way of working with the dataframe, but I get it to work with plotly with some additional hacky stuff. Would be great to see if anyone has any additional suggestions! It seems to have all the correct column names etc after my pandas processing steps.

**Comment by jakevdp** [comment]
Your code works for me in JupyterLab.

Try not printing the dataframe in the same cell that you display the chart. In some frontends that short-circuits the display mechanism.

**Comment by mcrone** [comment]
Thank you! I pasted it into a new code block and it worked (I'm also using JupyterLab). It seems that perhaps the fact that I was generating two graphs in the same code block there was a problem? I'll close this now and work out if that was the case.

**Comment by jakevdp** [comment]
If you want to display a chart that is not at the end of a codeblock, you can use the ``.display()`` method. This stackoverflow answer has some relevant discussion: https://stackoverflow.com/a/51543464/2937831
