### ISSUE TITLE
how to change a figure with the shape (18*1) into the shape (3*6) using altair?

### ISSUE THREAD

**Issue by chaoshengt** [altair-viz/altair#1338]
how to change a figure with the shape (18 X 1) into the shape (3X6)? Thank you  ：）
![visualization](https://user-images.githubusercontent.com/7035642/52915439-1a489080-330f-11e9-81c2-37b14ac643d2.png)

**Comment by jakevdp** [comment]
There's no easy way to do this in Altair/Vega-Lite; the issue where it's being discussed is here: https://github.com/vega/vega-lite/issues/4457

**Comment by chaoshengt** [comment]
Not a very happy news, but thank you all the same @jakevdp
