### ISSUE TITLE
Sphinx: Get path to the page current altair-plot is on?

### ISSUE THREAD

**Issue by jdillard** [altair-viz/altair#1341]
I was playing around with trying to dynamically load local files into reused altair charts (using the sphinx include directive to embed the same altair code on several different pages).

I thought one method might be to grab the file path of the page the current altair-plot directive is on and put a json file in that same directory, so that way the local (and unique) json file is called every time. I'm basically looking for how to dynamically get `path/to/current/rst/page/` in the code below and was wondering if anyone had any ideas.

I was able to grab the path of the file the python interpreter was called from, but that is the location of my conf.py so it only gets me so far. This is what I have so far:

```python
.. altair-plot::
    :hide-code:

    import altair as alt
    import pandas as pd
    import sys

    data = pd.read_json('file://localhost'+sys.path[0]+'/path/to/current/rst/page/chart-type-1.json', orient='records')

    alt.Chart(data).mark_bar().encode(
        x=alt.X('Model', scale=alt.Scale(rangeStep=8), axis=None, title=None),
        y=alt.Y('sum(Speed)', title='Speed'),
        color='Model',
        column='Size',
        tooltip=['Speed']
    ).configure_view(
        stroke='transparent'
    )
```

**Comment by jakevdp** [comment]
I don't know of any way to do that... you might ask in the sphinx help forums.
