### ISSUE TITLE
Completely remove all bottom axis and top axis (e.g. in Charts)?

### ISSUE THREAD

**Issue by jona-sassenhagen** [altair-viz/altair#1342]
I can turn off grids, labels, ticks, ... but the line is still there. My axes are in arbitrary units - is there a way to get rid of the lines completely?

**Comment by jakevdp** [comment]
Is something like this what you have in mind?
```python
import altair as alt

# load a simple dataset as a pandas DataFrame
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_point().encode(
    alt.X('Horsepower', axis=None),
    alt.Y('Miles_per_Gallon', axis=None),
    color='Origin',
).configure_view(strokeOpacity=0)
```
![visualization 37](https://user-images.githubusercontent.com/781659/53124905-7844c600-3511-11e9-9df2-cc35c42c42a7.png)

**Comment by jona-sassenhagen** [comment]
Exactly, thanks. Feel free to close, although it might be useful to have an example like this (I couldn't find any).

**Comment by jakevdp** [comment]
There's some info in the docs here: https://altair-viz.github.io/user_guide/configuration.html#removing-the-border

**Comment by jona-sassenhagen** [comment]
I think it would make sense to add another example with axis=None right there. What do you think? I could make a PR.

**Comment by jona-sassenhagen** [comment]
Also, doesn't that passage incorrectly switch between strokeOpacity and strokeWidth?

**Comment by jakevdp** [comment]
yep to both :smile:

**Comment by jona-sassenhagen** [comment]
I'll do it.

**Comment by firasm** [comment]
In case anyone comes across this issue, the removing the border section is now here in the docs: https://altair-viz.github.io/user_guide/customization.html#removing-the-chart-border
