### ISSUE TITLE
how to get the tooltip from code when hovering?

### ISSUE THREAD

**Issue by mingyangShang** [altair-viz/altair#1351]
Hi, I want to get the content of tooltip when hover over a point, how can i make it by python code, thanks!

**Comment by jakevdp** [comment]
The tooltip is generated by the javascript renderer, and so there is no easy way to get its value from the Python code.

**Comment by sfc-gh-cheliu** [comment]
@jakevdp What is the source data structure for tooltip? I'm wondering if I can filter out some fields.
