### ISSUE TITLE
Feature Request:  Multi-Line Tooltip with multiple y-axes

### ISSUE THREAD

**Issue by raybellwaves** [altair-viz/altair#1356]
I have data with three variables at different scales (wave height, wind speed and mean sea level pressure; if interested).

e.g.
```
source = pd.DataFrame(np.cumsum(np.random.randn(100, 3), 0).round(2),
                    columns=['A', 'B', 'C'], index=pd.RangeIndex(100, name='x'))
source['A'] = source['A'] * 100
source['B'] = source['B'] * 1000
```

I would like to use the Multi-Line Tooltip as given [here](https://altair-viz.github.io/gallery/multiline_tooltip.html)
To see how they are related over time. However, I will have to add two additional y axes as the data are scaled differently.

**Comment by jakevdp** [comment]
I don't think this requires any new features; you can do something like this:
```python
import altair as alt
import pandas as pd
import numpy as np

source = pd.DataFrame(np.cumsum(np.random.randn(100, 3), 0).round(2),
                      columns=['A', 'B', 'C'], index=pd.RangeIndex(100, name='x'))
source['A'] = source['A'] * 100
source = source.reset_index().melt('x')

lines = alt.Chart().mark_line().encode(
    x='x:Q',
    y='value:Q',
    color='variable:N'
).properties(
    height=100,
    width=600
)

nearest = alt.selection(type='single', nearest=True, on='mouseover',
                        fields=['x'], empty='none')
selectors = alt.Chart().mark_point().encode(
    x='x:Q',
    opacity=alt.value(0),
).add_selection(
    nearest
)

points = lines.mark_point().encode(
    opacity=alt.condition(nearest, alt.value(1), alt.value(0))
)

text = lines.mark_text(align='left', dx=5, dy=-5).encode(
    text=alt.condition(nearest, 'value:Q', alt.value(' '))
)

rules = alt.Chart().mark_rule(color='gray').encode(
    x='x:Q',
).transform_filter(
    nearest
)

alt.layer(lines, selectors, points, text, rules).facet(
    row='variable:N',
    data=data
).resolve_scale(
    y='independent'
)
```
<img width="795" alt="screen shot 2019-03-02 at 8 33 11 pm" src="https://user-images.githubusercontent.com/781659/53691009-7c9b8b00-3d2a-11e9-89b6-faf2ebe8117a.png">

**Comment by raybellwaves** [comment]
Awesome thanks! Mind if a make a PR to add this in the gallery in the docs?

**Comment by jakevdp** [comment]
I think it's a bit duplicative to be its own example... it's essentially just taking the existing example and adding adding a facet and a resolve on the final line.

**Comment by hhxxttxs-tang** [comment]
> I don't think this requires any new features; you can do something like this:
> 
> ```python
> import altair as alt
> import pandas as pd
> import numpy as np
> 
> source = pd.DataFrame(np.cumsum(np.random.randn(100, 3), 0).round(2),
>                       columns=['A', 'B', 'C'], index=pd.RangeIndex(100, name='x'))
> source['A'] = source['A'] * 100
> source = source.reset_index().melt('x')
> 
> lines = alt.Chart().mark_line().encode(
>     x='x:Q',
>     y='value:Q',
>     color='variable:N'
> ).properties(
>     height=100,
>     width=600
> )
> 
> nearest = alt.selection(type='single', nearest=True, on='mouseover',
>                         fields=['x'], empty='none')
> selectors = alt.Chart().mark_point().encode(
>     x='x:Q',
>     opacity=alt.value(0),
> ).add_selection(
>     nearest
> )
> 
> points = lines.mark_point().encode(
>     opacity=alt.condition(nearest, alt.value(1), alt.value(0))
> )
> 
> text = lines.mark_text(align='left', dx=5, dy=-5).encode(
>     text=alt.condition(nearest, 'value:Q', alt.value(' '))
> )
> 
> rules = alt.Chart().mark_rule(color='gray').encode(
>     x='x:Q',
> ).transform_filter(
>     nearest
> )
> 
> alt.layer(lines, selectors, points, text, rules).facet(
>     row='variable:N',
>     data=data
> ).resolve_scale(
>     y='independent'
> )
> ```
> 
> <img alt="screen shot 2019-03-02 at 8 33 11 pm" width="795" src="https://user-images.githubusercontent.com/781659/53691009-7c9b8b00-3d2a-11e9-89b6-faf2ebe8117a.png">

Can I have multiple columns in one chart of a facet? e.g. "A" and "B" share the same chart while "C" in another chart? Thanks!
