### ISSUE TITLE
Order of heatmap axis is wrong

### ISSUE THREAD

**Issue by noklam** [altair-viz/altair#1358]
![image](https://user-images.githubusercontent.com/18221871/53699806-219b8e00-3e27-11e9-8ff4-e6adaa8b5928.png)

I follow the example from https://altair-viz.github.io/gallery/simple_heatmap.html and only change the range, notice that even the datatype is int and  using  Order data, the axis is still sorted as a string.

    import altair as alt 
    import numpy as np 
    import pandas as pd 
    # Compute x^2 + y^2 across a 2D grid 
    x, y = np.meshgrid(range(-15, 5), range(-15, 5)) 
    z = x ** 2 + y ** 2 
    # Convert this grid to columnar data    expected by Altair 
    source = pd.DataFrame({'x': x.ravel(), 'y': y.ravel(), 'z': z.ravel()})       
    alt.Chart(source).mark_rect().encode( x='x:O', y='y:O', color='z:Q' )

**Comment by jakevdp** [comment]
Could you please paste the full code as text, rather than a screenshot of part of your code? I'll try to help as soon as I can do it without re-transcribing your code and guessing at what's missing :smile:

**Comment by noklam** [comment]
Sorry I forgot to paste the code.  I have edited post.

**Comment by jakevdp** [comment]
When I ran that code snippet I got the expected output:
![visualization 46](https://user-images.githubusercontent.com/781659/53707691-d8c2e580-3de4-11e9-805b-25c9eec82895.png)
What version of Altair are you using? What frontend are you using?
Have you run any other code as part of this session, such as enabling a non-default data transformer?

**Comment by noklam** [comment]
@jakevdp 
I am using altair 2.3.0 with JupyterLab, the behavior appears when I  use 
`alt.data_transformers.enable('csv')`
![image](https://user-images.githubusercontent.com/18221871/53722152-da051880-3e9f-11e9-8a70-2bf1a878f813.png)

**Comment by jakevdp** [comment]
When you save data to CSV, the type is not preserved. Your data are being parsed from the CSV file as strings, and sorted in alphabetical order. If you would like  to parse CSV values as numbers, you can reference the CSV file and use a [`DataFormat`](https://altair-viz.github.io/user_guide/generated/core/altair.DataFormat.html) argument to specify types for the columns.

If you would  like to save your data to file without having to worry about the types of the parsed input, use ``alt.data_transformers.enable('json')`` instead.

**Comment by jakevdp** [comment]
I've removed CSV as a recommended data transformer in #1359. Hopefully others won't stumble on this problem.

**Comment by noklam** [comment]
Thanks!  That explain a lot.
