### ISSUE TITLE
Surprising default sort order for line charts with tied data values

### ISSUE THREAD

**Issue by DGrady** [altair-viz/altair#1361]
If I were to make a line plot of this data of this data by hand

```python
data = pd.DataFrame(
    [
        [0, 0],
        [1, 1],
        [1, 2],
        [2, 3],
    ],
    columns=['x', 'y']
)
```

I would expect to see something like

![image](https://user-images.githubusercontent.com/392172/53848954-1baec580-3f6b-11e9-853e-94e680f52cd7.png)

However,

```python
alt.Chart(data).mark_line().encode(x='x', y='y')
```

instead makes this plot:

![image](https://user-images.githubusercontent.com/392172/53848994-4862dd00-3f6b-11e9-8719-25f362425912.png)

We could fix this by adding an order parameter: `alt.Chart(data).mark_line().encode(x='x', y='y', order='y')` will produce the plot that I expect.

This was raised in #295 as well, and from that issue it seems like the default behavior for Altair (Vega?) is to sort points in order of _decreasing_ x and to break ties by sorting in order of _increasing_ y. In other words, in the presence of ties, we move left and then up across the plot.

This method for breaking ties seems surprising. It seems like most people would expect to break ties by moving to the right and then up across the plot. (Or equivalently, to the left and then down.)

The discussion in #295 suggests that users should not supply data that contains ties. But I think that there are, in practice, legitimate use cases for trying to plot data that contains ties. Just to take one example (which prompted this issue), the output of `sklearn.metrics.roc_curve` will often contain ties. Whether the ties actually need to be there in principle isn't relevant; in practice, the tool produces data with ties, and the data can be plotted in a meaningful way.

- Have I understood Altair's default policy for sorting in the presence of ties correctly?
- How could I configure Altair's policy for sorting data globally?
- Would it be reasonable to change Altair's default policy?

**Comment by jakevdp** [comment]
I think you've summarized Vega-Lite's behavior correctly. Altair has no control over this, aside from the already-mentioned mechanisms for explicitly controlling the order of points. If a particular order is important for your chart, you should explicitly specify the order channel.

**Comment by DGrady** [comment]
Fair enough; thanks!
