### ISSUE TITLE
Example of grouped bar chart with error bars

### ISSUE THREAD

**Issue by mc-robinson** [altair-viz/altair#1362]
It took me a frustratingly long time to figure out how to do this, so I figured I would share an example if it was wanted for the gallery/tutorials/something else. In particular, dealing with the facet strictly after layering is a bit tricky.

Example 1: Grouped Bar Chart with Error Bars (note that color is not used, because then I cannot get the error bars to show up black)
```
import altair as alt
from vega_datasets import data

source = data.barley()

bars = alt.Chart().mark_bar().encode(
    x='year:O',
    y='mean(yield):Q',
    #color='year:N',
)

error_bars = bars.mark_rule().encode(
    x='year:O',
    y='ci0(yield):Q',
    y2='ci1(yield):Q'
)

alt.layer(bars, error_bars, data=source).facet(
    column='site:N'
)
```

Example 2: Grouped Plot with Error Bars (color can now be used easily)

```
import altair as alt
from vega_datasets import data

source = data.barley()

points = alt.Chart().mark_point(filled=True, size=50).encode(
    x='year:O',
    y=alt.Y('mean(yield):Q', title='Mean Yield'),
    color='year:N',
)

error_bars = bars.mark_rule().encode(
    x='year:O',
    y='ci0(yield):Q',
    y2='ci1(yield):Q'
)

alt.layer(points, error_bars, data=source).facet(
    column='site:N'
)
```

**Comment by awbirdsall** [comment]
thank you! I was stuck on this too, so +1 on adding to gallery/tutorials.

I'm able to get black error bars when the bar chart has color if I add `color=alt.value('black')` as an argument to the `encode()` call for the error bars, e.g. for your example,

```python
import altair as alt
from vega_datasets import data

source = data.barley()

bars = alt.Chart().mark_bar().encode(
    x='year:O',
    y='mean(yield):Q',
    color='year:N',
)

error_bars = bars.mark_rule().encode(
    x='year:O',
    y='ci0(yield):Q',
    y2='ci1(yield):Q',
    color=alt.value('black')
)

alt.layer(bars, error_bars, data=source).facet(
    column='site:N'
)
```

I have altair 2.2.2 installed.

**Comment by mc-robinson** [comment]
Glad it helped! And thanks for the color tip. @jakevdp is it best for me to submit a pull request right to the examples folder?

**Comment by jakevdp** [comment]
> because then I cannot get the error bars to show up black

When you do ``bars.mark_rule()``, all encodings from ``bars`` are inherited, including the color encoding: this is why the error bars are not black. This is why @awbirdsall's idea of adding ``color=alt.value('black')`` is necessary.

> is it best for me to submit a pull request right to the examples folder?

Yes! An examples PR would be great. You could put it in the bar charts category, using something like https://github.com/altair-viz/altair/blob/master/altair/examples/bar_chart_with_mean_line.py as a template.

**Comment by mc-robinson** [comment]
Great, will do soon!

**Comment by bbrighttaer** [comment]
How can error bars be made to show on a grouped stacked bar chart using already calculated stdev values?

**Comment by tigercosmos** [comment]
@ bbrighttaer  do you resolve the issue?

**Comment by bbrighttaer** [comment]
Hi @tigercosmos, I was not able to do this. I eventually had to change the chart type.

**Comment by stebaski** [comment]
Hi, same problem here, I think this is really important to be addressed... @bbrighttaer @tigercosmos

**Comment by jakevdp** [comment]
In general, asking new questions within comments on closed issues is not a great way to get an answer.

**Comment by stebaski** [comment]
You're right @jakevdp didn't see it was closed. Let me leave one possible (obvious) solution here:
Assuming you already have column means and stds in your df, just make two new columns 'low' and 'high':

df['low'] = df['means'] - df['stds']/2
df['high'] = df['means'] + df['stds']/2

And then produce error bars which can be combined with mark_bar :

error_bars = alt.Chart().mark_rule().encode(
    x='some_data',
    y= 'low:Q',
    y2 = 'high:Q'
)
