### ISSUE TITLE
Encode point on Map

### ISSUE THREAD

**Issue by noklam** [altair-viz/altair#1366]
I cannot figure out how to encode points/circle with calculation on a map. The exampe https://altair-viz.github.io/gallery/airports.html only works for fix value, what I am hoping is the size can be calculate with mean of a field (Group by long,lat)

(Updated)
Notebook to reproduce (data included):
https://github.com/noklam/Gallery/blob/master/temp.ipynb

![image](https://user-images.githubusercontent.com/18221871/54083831-de2fab00-4363-11e9-9a20-f54e04ac0111.png)

![image](https://user-images.githubusercontent.com/18221871/54083836-ea1b6d00-4363-11e9-9eda-9f05be8ad2e3.png)

![image](https://user-images.githubusercontent.com/18221871/54083844-f3a4d500-4363-11e9-91cd-b2a77a439132.png)

**Comment by mattijn** [comment]
Can you share your data and make some code snippets so I can copy it in a notebook?

**Comment by noklam** [comment]
> Can you share your data and make some code snippets so I can copy it in a notebook?

@mattijn Thank you for offering help, I have included the data and notebook here. It surprise me I can only encode size with no aggregation.
https://github.com/noklam/Gallery/blob/master/temp.ipynb

**Comment by mattijn** [comment]
Sorry, this is a bug at the Vega-lite repository: https://github.com/vega/vega-lite/issues/4368

**Comment by noklam** [comment]
@mattjin I saw it is fixed in vega-lite, any idea when altair will be able to catch up these changes?

**Comment by mattijn** [comment]
Once Vega-Lite releases v3.0, Altair will follow shortly. When this happens? No idea, hopefully before end of Q2!

**Comment by noklam** [comment]
@mattijn Thanks for the quick response, I guess I can only wait then.

**Comment by noklam** [comment]
The issue is fixed now, could it be an example for the gallery? The only problem is I cannot find a good vega dataset with both geolocation and quantitative columns.
https://github.com/noklam/Gallery/blob/master/Circles%20Overlay%20on%20Map.ipynb
![image](https://user-images.githubusercontent.com/18221871/55251638-05efa000-528c-11e9-9ad4-3ca8f2055d03.png)

**Comment by jakevdp** [comment]
This would be a great example to add, if you'd like to work on it!
