### ISSUE TITLE
Timezone based date-hour display

### ISSUE THREAD

**Issue by devogopan** [altair-viz/altair#1367]
hi,

I have customer data from PST which which is UTC-7/8 based on the DST on/off. Actual data collection demarcation is based on UTC, starting 00:00 UTC to next 24 hours.  But I sit in India which is UTC+5:30. 

So when I plot the data, my browser renders the date-hour points on X-axis based on my timezone. Later I was able change this to print UTC date-hour points. But is there a method to  to print customer date-hour points in X-axis ?

Thanks in advance
Gopan

**Comment by jakevdp** [comment]
Are you aware of the UTC timeUnit transforms? I would recommend using these: you can add "utc" to the front of any of the time units listed here: https://altair-viz.github.io/user_guide/transform.html#timeunit-transform

If you can give an example of what chart you are trying to make, and what about the result is not what you expect, that would help me answer your question more concretely.

**Comment by ashermetzger** [comment]
I have a similar issue (code below):
![image](https://user-images.githubusercontent.com/40135170/155322852-bf6defce-cbef-4539-a861-66ac00239230.png)
![image](https://user-images.githubusercontent.com/40135170/155322891-0346fcff-b53c-4e92-b182-a5c4159db817.png)
Notice how the time zone shifts to my timezone (+3 hours from utc) in altair compared to the underlying data and the matplotlib plot.

Ran this in colab.

```
import pandas as pd
import altair as alt
import pytz
import seaborn as sns

df = pd.DataFrame(index=pd.date_range('2018-05-20 08', '2018-05-20 12', freq='1H', tz=pytz.utc),
                  data={'data': np.arange(1,6)})
df = df.reset_index()

alt.Chart(df).mark_point().encode(
    x=alt.X('index'),
    y=alt.Y('data'),
).interactive().display()

sns.scatterplot(x='index', y='data', data=df)
```

**Comment by joelostblom** [comment]
@ashermetzger VegaLite outputs all times as local by default. You can change this by setting `    x=alt.X('index', scale=alt.Scale(type='utc'))` as mentioned here https://vega.github.io/vega-lite/docs/timeunit.html#output
