### ISSUE TITLE
chart.save() doesn't work

### ISSUE THREAD

**Issue by nickcorona** [altair-viz/altair#1368]
Get this error (I have selenium and chromedriver installed): 
----------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-53-978cddd92c59> in <module>
      1 alt.Chart(sample).mark_bar().encode(
      2         alt.X('Body_Style', type='nominal'),
----> 3         y='count()').save('chart.html')

~/miniconda3/lib/python3.7/site-packages/altair/vegalite/v2/api.py in save(self, fp, format, override_data_transformer, scale_factor, vegalite_version, vega_version, vegaembed_version, **kwargs)
    515         if override_data_transformer:
    516             with data_transformers.enable('default', max_rows=None):
--> 517                 result = save(**kwds)
    518         else:
    519             result = save(**kwds)

~/miniconda3/lib/python3.7/site-packages/altair/utils/save.py in save(chart, fp, vega_version, vegaembed_version, format, mode, vegalite_version, embed_options, json_kwds, webdriver, scale_factor)
     66                              "['png', 'svg', 'html', 'json']")
     67 
---> 68     spec = chart.to_dict()
     69 
     70     if mode is None:

~/miniconda3/lib/python3.7/site-packages/altair/vegalite/v2/api.py in to_dict(self, *args, **kwargs)
    400         copy = self.copy()
    401         original_data = getattr(copy, 'data', Undefined)
--> 402         copy.data = _prepare_data(original_data, context)
    403 
    404         if original_data is not Undefined:

~/miniconda3/lib/python3.7/site-packages/altair/vegalite/v2/api.py in _prepare_data(data, context)
     82     # convert dataframes to dict
     83     if isinstance(data, pd.DataFrame):
---> 84         data = pipe(data, data_transformers.get())
     85 
     86     # convert string input to a URLData

~/miniconda3/lib/python3.7/site-packages/toolz/functoolz.py in pipe(data, *funcs)
    550     """
    551     for func in funcs:
--> 552         data = func(data)
    553     return data
    554 

~/miniconda3/lib/python3.7/site-packages/toolz/functoolz.py in __call__(self, *args, **kwargs)
    281     def __call__(self, *args, **kwargs):
    282         try:
--> 283             return self._partial(*args, **kwargs)
    284         except TypeError as exc:
    285             if self._should_curry(args, kwargs, exc):

~/miniconda3/lib/python3.7/site-packages/altair/vegalite/data.py in default_data_transformer(data, max_rows)
     10 @curry
     11 def default_data_transformer(data, max_rows=5000):
---> 12     return pipe(data, limit_rows(max_rows=max_rows), to_values)
     13 
     14 

~/miniconda3/lib/python3.7/site-packages/toolz/functoolz.py in pipe(data, *funcs)
    550     """
    551     for func in funcs:
--> 552         data = func(data)
    553     return data
    554 

~/miniconda3/lib/python3.7/site-packages/toolz/functoolz.py in __call__(self, *args, **kwargs)
    281     def __call__(self, *args, **kwargs):
    282         try:
--> 283             return self._partial(*args, **kwargs)
    284         except TypeError as exc:
    285             if self._should_curry(args, kwargs, exc):

~/miniconda3/lib/python3.7/site-packages/altair/utils/data.py in to_values(data)
    128     if isinstance(data, pd.DataFrame):
    129         data = sanitize_dataframe(data)
--> 130         return {'values': data.to_dict(orient='records')}
    131     elif isinstance(data, dict):
    132         if 'values' not in data:

~/miniconda3/lib/python3.7/site-packages/pandas/core/frame.py in to_dict(self, orient, into)
   1300                 into_c((k, com.maybe_box_datetimelike(v))
   1301                        for k, v in compat.iteritems(row._asdict()))
-> 1302                 for row in self.itertuples(index=False)]
   1303         elif orient.lower().startswith('i'):
   1304             if not self.index.is_unique:

~/miniconda3/lib/python3.7/site-packages/pandas/core/frame.py in <listcomp>(.0)
   1300                 into_c((k, com.maybe_box_datetimelike(v))
   1301                        for k, v in compat.iteritems(row._asdict()))
-> 1302                 for row in self.itertuples(index=False)]
   1303         elif orient.lower().startswith('i'):
   1304             if not self.index.is_unique:

AttributeError: 'tuple' object has no attribute '_asdict'

**Comment by jakevdp** [comment]
If you're saving to HTML, it has nothing to do with selenium or chromedriver. Actually, this appears to not have much to do with Altair at all: the error originates in ``data.to_dict()`` for whatever data you are passing into the chart.

If you could share some code that results in this error, I could try to help more.

**Comment by nickcorona** [comment]
Hey, jakedvp. Sorry, I posted the wrong error message. It occurred when trying to save to .svg. I'll update this tomorrow when I'm back at work.

**Comment by nickcorona** [comment]
Closing for now until I have time to open a proper ticket.
