### ISSUE TITLE
Slicer for selection range

### ISSUE THREAD

**Issue by noklam** [altair-viz/altair#1374]
This is an example from https://altair-viz.github.io/gallery/multiple_interactions.html#gallery-multiple-interactions where we are able to slide through data.

It is strange that I cannot find a way to set both the upper and lower limit of the range? currently, I can only set the step size to control the interval of data that I needed.

![image](https://user-images.githubusercontent.com/18221871/54603971-96560580-4a80-11e9-9cd0-22aa2ac431fb.png)

**Comment by joelostblom** [comment]
The only way of selecting a range is to use a secondary chart like in this example https://altair-viz.github.io/gallery/interval_selection.html.  Adding a range selection to a slider would need to be added in Vega first so I'm closing this issue as there is nothing we can do from the altair side of things.
