### ISSUE TITLE
Add specific errors for common gotchas

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#1375]
The jsonschema validation errors are difficult to interpret. There are a few common cases that we might preemptively check before the jsonschema validation, and raise a more user-friendly error. A few that come to mind:

- attempting to use a facet chart in a layer or concatenation
- attempting to combine charts with top-level configurations
- maybe others?

We also need to make certain these cases still hold with VL 3... false positives would be very annoying here.

**Comment by joelostblom** [comment]
We closed the first one in https://github.com/altair-viz/altair/pull/3264 and the warning for combining top level configs is now also quite clear ("Objects with "config" attribute cannot be used within LayerChart."), so I'm closing this one.
