### ISSUE TITLE
Histogram binning changing upon selection.

### ISSUE THREAD

**Issue by mc-robinson** [altair-viz/altair#1376]
I am trying to submit some additional examples to the gallery which might be helpful for others, and I ran into some issues with this one. 

In particular, the binning changes upon selection, and I don't know how to keep it the same as before selection. This would be ideal, since I don't want the shape of the histograms to change.

```python
# generate fake data
source = pd.DataFrame({'gender': ['M']*1000 + ['F']*1000,
               'height':np.concatenate((np.random.normal(69, 7, 1000),
                                       np.random.normal(64, 6, 1000))),
               'weight': np.concatenate((np.random.normal(195.8, 144, 1000),
                                        np.random.normal(167, 100, 1000))),
               'age': np.concatenate((np.random.normal(45, 8, 1000),
                                        np.random.normal(51, 6, 1000)))
        })

selector = alt.selection_single(empty='all', fields=['gender'])

color_scale = alt.Scale(domain=['M', 'F'],
                        range=['#1FC3AA', '#8624F5'])

base = alt.Chart(source).properties(
    width=250,
    height=250
).add_selection(selector)

points = base.mark_point(filled=True, size=200).encode(
    x=alt.X('mean(height):Q',
            scale=alt.Scale(domain=[0,84])),
    y=alt.Y('mean(weight):Q',
            scale=alt.Scale(domain=[0,250])),
    color=alt.condition(selector,
                        'gender:N',
                        alt.value('lightgray'),
                        scale=color_scale),
).interactive()

hists = base.mark_bar(opacity=0.5, thickness=100).encode(
    x=alt.X('age',
            bin=alt.Bin(maxbins=25),
            scale=alt.Scale(domain=[0,100])),
    y=alt.Y('count()',
            stack=None,
            scale=alt.Scale(domain=[0,350])),
    color=alt.Color('gender:N',
                    scale=color_scale)
).transform_filter(
    selector
)


points | hists
```

**Comment by jakevdp** [comment]
Binnings are computed in response to the data that are being binned, and condrolled by the ``alt.Bin`` parameters. If you set ``maxbins``, that will be respected when the bins are computed, but the bins may be different depending on the data being binned.

If you want a specific set of bins regardless of the input data, you can use a more specific set of bin params. For example, the ``divide`` argument lets you specify the exact bins that will be used, regardless of the input data.

**Comment by morberg** [comment]
I had a similar problem, did some very quick experiments and couldn't get `divide` to work for me. I ended up using `step` instead to set fix bin widths.

**Comment by jakevdp** [comment]
Ah, yes you're right. The best way to have an entirely reproducible set of bins would be using the extent and step arguments. Divide does something different.
