### ISSUE TITLE
Selection Binding raises Javascript Parse Error

### ISSUE THREAD

**Issue by rampDD** [altair-viz/altair#1378]
Hello,

I try to filter a bar graph via a selection box. Without selection added to the graph everything is as expect. When I add the selection following error occurs:

> Javascript Error: Expression parse error: data("License_Name_store").length && {Feature Name: data("License_Name_store")[0].values[0]}
> 
> This usually means there's a typo in your chart specification. See the JavaScript console for the full traceback.

Hopefully you can tell me whats wrong

```
alt.__version__
'2.3.0'
```
```
alt.renderers.enable('notebook')
df = pd.read_csv('license.csv', dtype={'User Name':str,
                                       'Feature Name':str,
                                       'Tag':str,
                                       'Machine Name':str},
                parse_dates=[4,5,6], keep_date_col=True)
    

input_dropdown = alt.binding_select(options=list(df['Feature Name'].unique()))
selection = alt.selection_single(fields=['Feature Name'],  bind=input_dropdown, name='License Name')

alt.Chart('license.csv').mark_bar().encode(
    alt.X('Checkout Date:T', bin=alt.Bin(maxbins=730)),
    y='count(User Name):Q',
    color='Feature Name:N').add_selection(selection).transform_filter(selection)
```

```
df.types
Unnamed: 0                int64
User Name                object
Feature Name             object
Tag                      object
Machine Name             object
Checkout Date    datetime64[ns]
Checkout Time    datetime64[ns]
Total Usage              object
dtype: object
```

Thanks in advance,

**Comment by jakevdp** [comment]
If you could share the first few lines of your dataset, that would help us provide assistance. Without it, we're just guessing.

One observation about your code: you use the filename rather than the dataframe in the chart, despite going to lengths to do column-specific type conversions. Is that intentional?

**Comment by rampDD** [comment]
After removing the white spaces from column names it work. 
I'm sorry for beeing late with my responds.
