### ISSUE TITLE
Combining "Interval Selection" with "Multi-Line Tooltip" examples — the selection does not respect scale

### ISSUE THREAD

**Issue by xpl** [altair-viz/altair#1379]
Hello and thanks for the great project! I am trying to combine the code from the two examples:

https://altair-viz.github.io/gallery/interval_selection.html
https://altair-viz.github.io/gallery/multiline_tooltip.html

But I am getting that erratic behavior of the mouse hover when an interval is selected:

<img width="788" alt="Screen Shot 2019-03-21 at 17 22 05" src="https://user-images.githubusercontent.com/1707/54758895-1fdf1200-4bfe-11e9-8f03-fb75d34d19ae.png">

What am I doing wrong and how to fix it?

The code:

```python
import altair as alt
import pandas as pd
import numpy as np

np.random.seed(42)
source = pd.DataFrame(np.cumsum(np.random.randn(100, 3), 0).round(2),
                    columns=['A', 'B', 'C'], index=pd.RangeIndex(100, name='x'))
source = source.reset_index().melt('x', var_name='category', value_name='y')

# Create a selection that chooses the nearest point & selects based on x-value
nearest = alt.selection(type='single', nearest=True, on='mouseover',
                        fields=['x'], empty='none')

brush = alt.selection(type='interval', encodings=['x'])

x_scaled = alt.X('x:Q', scale={'domain': brush.ref()})

# The basic line
line = alt.Chart().mark_line(interpolate='basis').encode(
    x=x_scaled,
    y='y:Q',
    color='category:N'
).properties (width=600, height=300)

# Transparent selectors across the chart. This is what tells us
# the x-value of the cursor
selectors = alt.Chart().mark_point().encode(
    x=x_scaled,
    opacity=alt.value(0),
).add_selection(
    nearest
)

# Draw points on the line, and highlight based on selection
points = line.mark_point().encode(
    opacity=alt.condition(nearest, alt.value(1), alt.value(0))
)

# Draw text labels near the points, and highlight based on selection
text = line.mark_text(align='left', dx=5, dy=-5).encode(
    text=alt.condition(nearest, 'y:Q', alt.value(' '))
)

# Draw a rule at the location of the selection
rules = alt.Chart().mark_rule(color='gray').encode(
    x='x:Q',
).transform_filter(
    nearest
)

# Put the five layers into a chart and bind the data
alt.vconcat(alt.layer(line, selectors, points, rules, text),
            line.properties(height=60).add_selection(brush),
            data=source)
```

**Comment by afonit** [comment]
What environment are you viewing the plot in?
What version of altair?

The cursor lines up for me - I am on:
altair 2.3.0
jupyterlab 0.35.4

**Comment by jakevdp** [comment]
This is a bug in Vega-Lite (see https://github.com/vega/vega-lite/issues/4603) It has been fixed upstream (https://github.com/vega/vega-lite/pull/4289) but that fix has not yet made it into a vega-lite release. Once the fix is released, we will update Altair and it will work correctly.

For the time being, if you choose "Open In Vega Editor" on your rendered chart, it will pop open a vega editor view that renders with the vega-lite 3.0 prerelease, which will show  the working version of your chart.

**Comment by xpl** [comment]
@jakevdp Is there any way to use altair with vega-lite 3.0 (pre-release) now?

**Comment by jakevdp** [comment]
>  Is there any way to use altair with vega-lite 3.0 (pre-release) now?

No, not easily. There's a work in progress for the python side of things in #1249 (though it's a bit out of date), but the vega-lite 3 compatible frontend extensions for jupyter notebook and jupyterlab do not exist yet.
