### ISSUE TITLE
Selection of x-axis labels for timeseries when plot width is extended

### ISSUE THREAD

**Issue by d-gleeson** [altair-viz/altair#1392]
Hi, Aplogies if this isn't the right place for this sort of thing. I'm struggling with an issue whereby the x-axis tick labels are unhelpful when I extend the width of the plot for a timeseries. Easiest to explain by example:
```python
import altair as alt
import pandas as pd
```

**Create some random timeseries data** 
```python
date_index = pd.date_range('2013-10-01', '2019-02-28')
values = pd.np.random.randn(len(date_index)).cumsum()
df = pd.DataFrame(index=date_index, data=values, columns=['values'])
```

**Chart it with minimal properties defined**
```python
source = df.reset_index()
alt.Chart(source).mark_line().encode(
    x='index:T',
    y='values')
```

![visualization](https://user-images.githubusercontent.com/7363923/55100049-d76d9b80-50b8-11e9-9c3d-b0be21346e41.png)

The chart looks pretty good, with suitable default x-tick labels.

**However - if I extend the width of the chart**

```python
source = df.reset_index()
alt.Chart(source).mark_line().encode(
    x='index:T',
    y='values').properties(width=800)
```

![visualization (1)](https://user-images.githubusercontent.com/7363923/55100207-359a7e80-50b9-11e9-83e6-34af0b6b755d.png)

The labels simply read October & April, they don't tell me the year. 
Any ideas or tips on how to get clearer x-tick labels in this scenario?

**Comment by jakevdp** [comment]
FYI, you can use triple ticks to make formatted code blocks (I edited your question to add them)

Formats of axis labels are determined within Vega based on a set of heuristics. You can control formats using the ``Axis()`` property; for example:
```python
source = df.reset_index()
alt.Chart(source).mark_line().encode(
    x=alt.X('index:T', axis=alt.Axis(format="%B %Y")),
    y='values').properties(width=800)
```
![visualization (7)](https://user-images.githubusercontent.com/781659/55107050-990eb700-508d-11e9-8178-2e309d2469a3.png)

Available formats are described at [D3 Format](https://github.com/d3/d3-time-format#locale_format).

**Comment by d-gleeson** [comment]
Brilliant, thanks! 
(also that's good to know re: the triple ticks)
