### ISSUE TITLE
alt.Scale domain not applied when type='log'

### ISSUE THREAD

**Issue by knaps** [altair-viz/altair#1393]
When setting both the `domain` and `type='log'` on `alt.Scale`, the `domain` seems to be ignored:

```
import altair as alt
_=alt.renderers.enable('notebook')
alt.__version__
```
'3.0.0rc1'
```
from vega_datasets import data
df = data.iris()
alt.Chart(df).mark_point(clip=True).encode(
    x=alt.X('petalLength'),
    y='sepalLength'
)
```
![image](https://user-images.githubusercontent.com/519536/55111852-85b51900-5098-11e9-8f16-c2b14bbd9046.png)
OK
```
alt.Chart(df).mark_point(clip=True).encode(
    x=alt.X('petalLength', scale=alt.Scale(domain=(1.5,5.0))),
    y='sepalLength'
)
```
![image](https://user-images.githubusercontent.com/519536/55111879-95ccf880-5098-11e9-8eda-8c63c423afae.png)
OK
```
alt.Chart(df).mark_point(clip=True).encode(
    x=alt.X('petalLength', scale=alt.Scale(type='log',domain=(1.5,5.0))),
    y='sepalLength'
)
```
![image](https://user-images.githubusercontent.com/519536/55111916-a41b1480-5098-11e9-82d8-5310d823a056.png)
Not ok

**Comment by knaps** [comment]
This is intended behavior for log scale

**Comment by TomBugnon** [comment]
How can one set the domain and use a log scale then?

**Comment by jakevdp** [comment]
To be clear, the domain argument is **not** ignored for log scales. Log scales must start and end at integer powers of the base, and domain limits will be rounded to the next integer power of the base.

So, for example, this works:
```python
from vega_datasets import data
df = data.iris()
alt.Chart(df).mark_point(clip=True).encode(
    x=alt.X('petalLength', scale=alt.Scale(type='log', base=2, domain=[2, 8])),
    y='sepalLength'
)
```
![visualization (36)](https://user-images.githubusercontent.com/781659/68594882-55669300-044d-11ea-8f39-a299c850e638.png)
