### ISSUE TITLE
Docs code does not generate expected output

### ISSUE THREAD

**Issue by ErfPy** [altair-viz/altair#1400]
I was going through the docs and I came at the part [`Bindings, Selections, Conditions: Making Charts Interactive`](https://altair-viz.github.io/user_guide/interactions.html#selections-building-blocks-of-interactions).

The code under the [`Example: Linked-Brush Scatter-Plot`](https://altair-viz.github.io/user_guide/interactions.html#example-linked-brush-scatter-plot) did not generate the output which is shown. It generated an empty plot. I fixed it by changing:

```
cars = data.cars.url
```
To
```
cars = data.cars()
```

Not sure if this is on my end, but thought its worth posting here as an issue.

**Comment by jakevdp** [comment]
This is probably due to some sort of ad blocker or other firewall on your system. If you open the javascript console, there will likely be more information.

**Comment by ErfPy** [comment]
Yes correct @jakevdp its the following error:
```
Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
logger.js:3 

ERROR Loading failed https://vega.github.io/vega-datasets/data/cars.json TypeError: Failed to fetch
```
