### ISSUE TITLE
Filter by size lable respecting the color label

### ISSUE THREAD

**Issue by galloramiro** [altair-viz/altair#1403]
Hi! 

I have a plot with a filter in the color label (genes) that shows what chromosomes are in the genes by the size label.
"Scatter_Dinamico_300.html"

Now I want to invert the filter, and I cant. 

I try:

- Changing  the multi selector from color to size, 
- Change the legend variables from 'genes:N' to 'transcript:N'
- Delete the color value from the label values

And nothing, it's don't respect the color, and only get filtered by the size. 

Here is the code from the first plot that works right:

```python
# Conditional variables
click = alt.selection_multi(encodings=['color'])                                   # U: Can select the genoma and filter the graph

# Chart variables
x_circle = alt.X('sampleID', axis = alt.Axis(title = 'Patients', labelAngle=-90))  # U: The X with de Label Angel
y_circle = alt.Y('TPM', axis = alt.Axis(title = 'TPM')) 

color_circle = alt.Color(shorthand='Genes:N', legend=None)                         # U: The color variable without the legend     
size_circle = alt.Size('transcript:N', scale=alt.Scale(range=[50, 200]))           # U: The size with the range of scale


# Legend variables
y_legend_c = alt.Y('Genes:N', axis=alt.Axis(title='Genes'))                            # U: Y value for the legend
color_legend_c = alt.condition(click, 'Genes:N', alt.value('lightgray'), legend=None)  # U: The color with the condition.


# Chart base
chart = alt.Chart(df).mark_circle().encode(x = x_circle, y = y_circle, color = color_circle, size = size_circle     # U: The basic chart
                                  ).properties(width=1280, height=720                                               # U: The heigth and width
                                  ).transform_filter(click)                                                         # U: A transform filter that let me alterate the graf by the selection in the legend.


# Legend base 
legend = alt.Chart(df).mark_circle().encode(y = y_legend_c, color= color_legend_c, size=alt.value(250)
                                     ).add_selection(click)                                                         # U: The click to select the genomas

file = chart | legend
```

Thnks for reading!

**Comment by jakevdp** [comment]
I'm not certain what you mean by "invert the filter". Do you mean that you should filter by points that aren't part of the selection? If so, instead of `transform_filter(click)` you can use `transform_filter(~click)`

**Comment by galloramiro** [comment]
Sorry Jake, english is not my primary language but i will try to make it sense.

I need to filter by the 'transcript' that is the size label. 
But when I apply the filter that way it's not taking the values of the 'genes' color label. 
The Genes disapere, and apears only one, and I dont know why.

**Comment by jakevdp** [comment]
Ah, I see. If you use ``encodings=['size']``, then it selects based on the size of the point. But you've set the size of the point to a constant value, so that won't do what you want.

I think you probably want to do ``alt.selection_multi(fields=['transcript'])`` and then you'll be sure to select based on the transcript field. Selecting on ``encodings:['color']`` happens to have worked above because both charts have their color encoding bound to the same field.
