### ISSUE TITLE
data.json creation in documentation build

### ISSUE THREAD

**Issue by eitanlees** [altair-viz/altair#1404]
The section about [reducing notebook size](https://altair-viz.github.io/user_guide/faq.html#why-does-altair-lead-to-such-extremely-large-notebooks) in the FAQ user guide saves data to `data.json`. 

When I build the docs this file is created causing my branch to diverge. Should this file be added to the project? Or placed in the `.gitignore`?

**Comment by jakevdp** [comment]
We could add it to ``doc/.gitignore``

**Comment by eitanlees** [comment]
I'm on it!

**Comment by eitanlees** [comment]
Done in #1405
