### ISSUE TITLE
[question] Apache arrow support in altair ?

### ISSUE THREAD

**Issue by djouallah** [altair-viz/altair#1406]
I read that apache arrow is supported now in vega-lite using a separate vega-loader, is this something that altair will support.

for anyone who used Apache arrow, is the performance way better than csv, my current project has a dataset of 60000 line and it is a bit slow, specially for brushing

**Comment by jakevdp** [comment]
Arrow support in Vega/Vega-Lite is an open issue: https://github.com/vega/vega/issues/1300. Once it's available there, we will work to make it available in Altair

**Comment by djouallah** [comment]
Thanks, I was referring to this https://github.com/vega/vega-loader-arrow

**Comment by doug** [comment]
now that there is the vega-loader-arrow. What should support in altair look like?

**Comment by jakevdp** [comment]
It would first have to be supported by Vega-Lite.

**Comment by jakevdp** [comment]
Vega-Lite's schema does not yet allow the arrow format: https://github.com/vega/schema/blob/master/vega-lite/v4.11.0.json#L5526-L5541

**Comment by ivirshup** [comment]
It looks arrow data sources can be used by vega-lite now: https://observablehq.com/@vega/vega-lite-and-apache-arrow-no-plugin. If the data is served from a url and not passed as a javascript object, it looks like [the plugin mentioned above will register the format](https://observablehq.com/@vega/apache-arrow-in-vega-lite) (I think).

 Is it a requirement for altair that this is implemented in the main `vega`/ `vega-lite` code bases?

**Comment by kimmolinna** [comment]
@jakevdp What is the situation with Apache Arrow and Arrow Table?
@domoritz Am I correct that vega-lite supports Arrow nowadays?

**Comment by dhirschfeld** [comment]
I'm not sure what native `arrow` support `altair` has, but the [`vegafusion`](https://github.com/hex-inc/vegafusion) project integrates Apache Arrow DataFusion with `altair`

**Comment by kimmolinna** [comment]
I noticed that but I would like to use [duckdb](https://github.com/duckdb/) as a query engine. DuckdDB supports pandas but I prefer Apache Arrow.

**Comment by domoritz** [comment]
An Arrow JS Table object presents itself as an array of objects and Vega automatically supports it. This has been true for a while now. The arrow loader is only needed when you refer to an arrow file (in IPC format) by url.

**Comment by joelostblom** [comment]
@kimmolinna You can use duckdb via vegafusion as well https://vegafusion.io/duckdb.html. I'm closing this as it seems to me like the use cases requested here are covered by vegafusion, but please comment if I'm missing something.
