### ISSUE TITLE
Config title font size bug

### ISSUE THREAD

**Issue by noklam** [altair-viz/altair#1408]
Bug:
When I change title font size, it changes my title color too

Expected behavior:
It should only change my font size.

The library API of plotting is quite clean, but I found that there is not enough example to demo how to configure chart, which is also important to finetuning.
Searching how to configure chart is difficult, like configure_title, configure_axis, properties. All these methods will not show up with tab completion and often I have to google around.

A gist notebook demo:
https://gist.github.com/noklam/2f2c8b07fe17174ae4107fb486d61f3b

**Comment by jakevdp** [comment]
I think this is an issue in Vega-Lite 3.0.0, which is what is used by the notebook extension. If I use Vega-Lite 3.0.3, the code works as expected.

**Comment by noklam** [comment]
Indeed, I tried open with the Vega Editor and it works fine. Would the extension be updated anytime soon?
