### ISSUE TITLE
Documentation bug: expr.format's second, not first argument, is the format specifier

### ISSUE THREAD

**Issue by xmacex** [altair-viz/altair#1411]
https://github.com/altair-viz/altair/blob/7da67b09383f3c79a8a57fa1dfd428270cc25b31/altair/expr/funcs.py#L63

This matches the documetation but does not work, runs quite a while, and provides loads of NaN

```python
).transform_calculate(
    notweets_humans='format(".2s", datum.notweets)'
)
```

This works fine

```python
).transform_calculate(
    notweets_humans='format(datum.notweets, ".2s")'
)
```

I assume that "first" is not zero-indexed in the documentation, with a "zeroth" argument preceding it ;)

PS. Thanks for bringing _grammar of graphics_ to Python.

**Comment by xmacex** [comment]
Wait, am I misunderstanding what is an "argument" in `expr` because the idea is that the first argument does not "count", and by "first argument must be" means that an argument must be given? This could use some clarification in the docs, I think 🤔

**Comment by jakevdp** [comment]
I think you're right, the documentation should be updated. It was copied from [this page](https://vega.github.io/vega/docs/expressions/) when the ``funcs.py`` module was created, and the source has already been updated to fix this issue.
