### ISSUE TITLE
add support for inline data format as columns.

### ISSUE THREAD

**Issue by djouallah** [altair-viz/altair#1415]
in my use case inline data is the perfect scenario, I have being using for the last six months and thanks for that.

my issue is Vega data format is by record, which is not very efficient and nearly double the size of my html file.

for example my data source is a csv with 2.2 MB
the final size of the HTML is 4.6 Mb

there is a request already in vega

https://github.com/vega/vega/issues/105

I am not familiar with Javascript so not sure how to a apply those rotate transform.

thanks for your help

**Comment by jakevdp** [comment]
This is something that will have to be addressed in Vega-Lite. Altair has no control over the allowable data formats in the chart spec.

**Comment by jakevdp** [comment]
An existing option is to store your data in a CSV, and refererence it by URL rather than embedding the full dataset in the chart spec. Then your spec will be only a few kilobytes plus the size of the CSV file.

**Comment by djouallah** [comment]
@jakevdp I tried the CSV URL approach, Actually, I have embed the whole spec, the issue was I can't load data into the "cloud" and let's not start about the internal IT :(

inline data is easy and convenient and secure, it is the same security model as sending a colleague a pdf.

thanks for your reply, much appreciate it.

**Comment by jheer** [comment]
In case it helps, Vega / Vega-Lite can accept raw CSV text as inline data. Here is an example using the Vega-Lite JavaScript API; Altair should behave similarly: https://observablehq.com/@vega/vega-lite-with-inline-csv-data

**Comment by joelostblom** [comment]
@djouallah I am going through Altair issues to find those that have been resolved and can be closed. Since this is something that needs to be fixed in Vega-Lite rather than in Altair, would you be able to close this issue or add a comment if there is something you don't think is resolved yet on the Altair side of things?

**Comment by djouallah** [comment]
it is all good thank you
