### ISSUE TITLE
.tansform_filter() not working

### ISSUE THREAD

**Issue by MarshallCharles** [altair-viz/altair#1418]
Hello, tansform_filter() is not currently functioning for me locally. 
Here is the callback:
"AttributeError: 'Chart' object has no attribute 'tansform_filter'"

![image](https://user-images.githubusercontent.com/49293173/55593163-34adc080-573b-11e9-9d27-f9d70c4c9cd1.png)

Thanks

**Comment by Alcampopiano** [comment]
It looks like "transform" is spelled incorrectly. Could that be it?
