### ISSUE TITLE
Set boundaries to interactive visualizations

### ISSUE THREAD

**Issue by zufanka** [altair-viz/altair#1419]
I am making an interactive barchart with `Chart.interactive()`. I would like it not to be able to go beyond the 0 and above 1000 on the X axis when zooming in and moving the bars around.
I am trying to set boundaries to the X axis with `alt.X(scale = alt.scale(domain=(0,1000)))` but that does not prevent the visualization going into out of these bounds on the X axis.

I went through I believe all the documentation on this, but I can't seem to figure out whether it is even possible. Is this even possible?

![image](https://user-images.githubusercontent.com/2411066/55618819-b7646900-5797-11e9-8df9-adc30ffd0022.png)

**Comment by jakevdp** [comment]
I don't think there's any way to specify bounded zooming, unfortunately. It would be worth a feature request on Vega-Lite.

**Comment by zufanka** [comment]
thanks, will do!
