### ISSUE TITLE
Binned histograms plot the max within each bin, not the mean

### ISSUE THREAD

**Issue by kuchenrolle** [altair-viz/altair#1421]
Hi.

I just noticed an odd behaviour when I was plotting my data. It seems that in a histogram, binning the x-axis results in the maximum value for each bin determining the height of the bar, rather than the mean. I can't find any documentation on how binning is done, but this is unexpected to me.

Minimal example:
```
df = pd.DataFrame({"y":[0.1, 0.2, 0.3, 0.2, 0.3, 0.4], "x":[1, 2, 3, 4, 5, 6]})

alt.Chart(df).mark_bar().encode(
           alt.X("x:Q", bin=alt.Bin(maxbins=2)),
           y='y:Q'
)
```

Please tell me how to change this without using pandas to do the binning beforehand. Here's the non-optimal function I use to do this, in case others want to do the same thing:
```

def hist_aggs(df, x, y, bin_range, agg="mean", add_mean=False):
    """Function to plot binned histogram, where height of each bin is the agg of the binned values.
    """
    x_aggs = df.groupby([x])[[y]].agg(agg).reset_index()
    x_binned = pd.cut(x_aggs[x], bin_range)
    x_binned_aggs = x_aggs.groupby(x_binned)[y].agg([agg]).reset_index()
    x_binned_aggs.columns = [x, y + agg.capitalize()]
    offset = (bin_range[1] - bin_range[0])/2
    x_binned_aggs[x] = [val + offset for val in bin_range[:-1]]
    x_binned_aggs

    graph = alt.Chart(x_binned_aggs).mark_bar(size=(350/(len(bin_range)-1) - 5)).encode(
        x=alt.X(x, bin=False, scale=alt.Scale(domain=(min(bin_range), max(bin_range)))),
        y=alt.Y(y + agg.capitalize() + ":Q", bin=False)
    )
    
    if not add_mean:
               return graph
    
    average = alt.Chart().mark_rule().encode(
        y='mean:Q'
    )
               
    graph = alt.layer(
        graph, average,
        data=x_binned_aggs
    ).transform_calculate(
        mean=str(np.mean(x_binned_aggs[y + agg.capitalize()]))
    )
    return graph
```

**Comment by jakevdp** [comment]
Your chart is not showing the max in each bin; it's showing *every* point in each bin. This is easiest to see with a point mark:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({"y":[0.1, 0.2, 0.3, 0.2, 0.3, 0.4], "x":[1, 2, 3, 4, 5, 6]})

alt.Chart(df).mark_point().encode(
  alt.X("x:Q", bin=alt.Bin(maxbins=2)),
  y='y:Q'
)
```
![visualization (66)](https://user-images.githubusercontent.com/781659/55802671-8df45780-5a8d-11e9-9aeb-b7ffd6acf09c.png)

If you want your data to be aggregated, you need to specify an aggregate operation. Here's how you can draw a bar chart with the mean of *y* in each bin:
```python
alt.Chart(df).mark_bar().encode(
  alt.X("x:Q", bin=alt.Bin(maxbins=2)),
  y='mean(y):Q'
)
```
![visualization (67)](https://user-images.githubusercontent.com/781659/55802756-bb410580-5a8d-11e9-94a1-c116d9fe5991.png)

**Comment by jakevdp** [comment]
You can find documentation on binning and aggregates in the [Encoding docs](https://altair-viz.github.io/user_guide/encoding.html#binning-and-aggregation) and the [Transform docs](https://altair-viz.github.io/user_guide/transform.html#bin-transforms).

**Comment by kuchenrolle** [comment]
Ah, I see. My bad. I still find this unintuitive, as, at least for the bar plot, practically this is aggregating by the max value, but it does makes sense to separate binning and aggregate transformations on the bins like that.
