### ISSUE TITLE
Multiple Charts in one HTML

### ISSUE THREAD

**Issue by SapoonDutta** [altair-viz/altair#1422]
Is there a way to display multiple charts on the same webpage using Altair? I am currently saving the files individually using chart.to_html("filename.html), but can't figure out a way to show the 5 different visuals into one html page. 

Please let me know if there's a way to do that.

**Comment by setop** [comment]
> (chart1 | chart2).save('charts.html')

It looks like magic, and it works !

However, charts are disposed horizontally.

Is there a way to make Altair to dispose them vertically ?

**Comment by jakevdp** [comment]
See https://altair-viz.github.io/user_guide/compound_charts.html
