### ISSUE TITLE
line chart with different point marker?

### ISSUE THREAD

**Issue by python152** [altair-viz/altair#1423]
How can I give different lines a different type of point marker, say a cross (+) symbol? For example, the following chart with `point=True` will have data points as solid circle, but it won't work well when print black & white.

```
import altair as alt
from vega_datasets import data

source = data.stocks()

alt.Chart(source).mark_line(point=True).encode(
    x='date',
    y='price',
    color='symbol'
)
```

**Comment by Alcampopiano** [comment]
Hi there,

Perhaps you could add the shape encoding. I imagine that adding a layer with `mark_point()` might give you more control over the points. 

```python
alt.Chart(source).mark_line().encode(
    x='date',
    y='price',
    color='symbol',
    shape='symbol'
)
```

![visualization (2)](https://user-images.githubusercontent.com/4624246/55896328-0e00e700-5b8c-11e9-8640-e3efb3c3e0b1.png)

**Comment by python152** [comment]
It is exactly what I am hoping for. thanks. 
The default symbol size does seem small, `alt.Shape` doesn't seem to have any option to set it though, is there anyway to change it?

**Comment by Alcampopiano** [comment]
Hi there,

Just as you can specify a `shape` encoding, you can also specify a `size` encoding. You can find the Altair encoding options [here in the docs](https://altair-viz.github.io/user_guide/encoding.html).

One way to have more control over the shapes, apart from the lines, is to use layers ([docs here](https://altair-viz.github.io/user_guide/compound_charts.html)):

```python
import altair as alt
from vega_datasets import data

source = data.stocks()

c=alt.Chart(source).encode(
    x='date',
    y='price',
    color='symbol'
)

l=c.mark_line()

p=c.mark_point(filled=True).encode(
    shape=alt.Shape('symbol', scale=alt.Scale(range=['cross', 'circle', 'square', 'triangle-right', 'diamond'])),
    size=alt.Size('symbol', scale=alt.Scale(range=[100,500],domain=['AAPL', 'AMZN', 'GOOG', 'IBM', 'MSFT']))
)

l+p
```

![visualization (5)](https://user-images.githubusercontent.com/4624246/55968568-46ff9100-5c4a-11e9-825e-2d41f623587f.png)

**Comment by cmartin-cay** [comment]
> Hi there,
> 
> Perhaps you could add the shape encoding.
> 
> ```python
> alt.Chart(source).mark_line().encode(
>     x='date',
>     y='price',
>     color='symbol',
>     shape=alt.Shape('symbol', scale=alt.Scale(range=['cross', 'circle', 'square', 'triangle-right', 'diamond']))
> )
> ```
> 
> ![visualization (4)](https://user-images.githubusercontent.com/4624246/55897199-11956d80-5b8e-11e9-85b9-7160f9a419af.png)

Is there a way to combine the two legends to include both the color and the shape in a single legend?

**Comment by jakevdp** [comment]
For point charts, this kind of legend combination is done automatically:
```python
import altair as alt
from vega_datasets import data

source = data.stocks()

alt.Chart(source).mark_point(filled=True).encode(
    x='date',
    y='price',
    color='symbol',
    shape='symbol'
)
```
![visualization (11)](https://user-images.githubusercontent.com/781659/56974957-b3243500-6b24-11e9-83a7-523adeb9faca.png)

The reason this doesn't happen for the line chart is because the color legend refers to the line itself.

**Comment by cmartin-cay** [comment]
Thanks Jake. I saw that for the point chart and thought I was mostly finished with a little excel chart replacement project. But, people will want the legend to look like the above, but also have the lines.

I'll have to see what else I can find.

**Comment by Alcampopiano** [comment]
@cmartin-cay 

You might consider layering the points on top of the line chart.

**Comment by jakevdp** [comment]
> I'll have to see what else I can find.

OK, best of luck. Sorry Altair didn't work for you.

**Comment by cmartin-cay** [comment]
Doing that brings me back to the initial situation where I have two separate legends. One with colors and one with shapes.

Maybe I can convince people that it's better this way :)

**Comment by jakevdp** [comment]
You can get the result you want by carefully defining legends and scale resolution:
```python
import altair as alt
from vega_datasets import data

source = data.stocks()

line = alt.Chart(source).mark_line().encode(
    x='date',
    y='price',
    color=alt.Color('symbol', legend=None)
)

points = line.mark_point(filled=True).encode(
    color='symbol',
    shape='symbol'
)

alt.layer(
    line,
    points
).resolve_scale(
    color='independent',
    shape='independent'
)
```
![visualization (12)](https://user-images.githubusercontent.com/781659/56977078-419ab580-6b29-11e9-8eba-7fbaf6b1e33c.png)

**Comment by Alcampopiano** [comment]
I knew there was a way!

**Comment by cmartin-cay** [comment]
All I can say is thank you very much.

**Comment by TomBugnon** [comment]
Is there any way to set the size of the points on a `mark_line` chart with the 'shape' encoding  without overlaying a mark_line and a mark_point chart?

**Comment by JanetMatsen** [comment]
Where can I find a menu of available shapes?   (And thanks for the great thread!)

**Comment by Alcampopiano** [comment]
> Where can I find a menu of available shapes? (And thanks for the great thread!)

Hi Janet. [This link](https://vega.github.io/vega-lite/docs/point.html) to the Vega-Lite docs on the "points" mark may help.

**Comment by jakevdp** [comment]
In Altair's docs, it's under ``shape`` here: https://altair-viz.github.io/user_guide/marks.html#mark-properties
