### ISSUE TITLE
Javascript named selection error

### ISSUE THREAD

**Issue by mercyfulace1** [altair-viz/altair#1425]
Here's the code:
```python
selection = alt.selection_multi(fields=['Priority'])
print(selection)
color = alt.condition(selection,
                      alt.Color('Priority:N', legend=None, scale=alt.Scale(scheme='category10')),
                      alt.value('lightgray'))
print(color)

chart = alt.Chart(df_in).mark_point().encode(
    x='Acronym',
    y='Incident Open Time:T',
    color=color
)

chart
```
-------------------------------------------------------------------------
Here's the output:
```
NamedSelection({
  selector014: SelectionDef({
    fields: ['Priority'],
    type: 'multi'
  })
})
{'condition': {'selection': 'selector014', 'type': 'nominal', 'field': 'Priority', 'legend': None, 'scale': {'scheme': 'category10'}}, 'value': 'lightgray'}
Javascript Error: Cannot find a selection named "selector014"
```
What am I missing?  thanks.

**Comment by jheer** [comment]
I think you need to include `.add_selection(selection)` to your chart definition?

**Comment by mercyfulace1** [comment]
That does work, but would I still do that if I want to use another chart as
a legend?  looking at this example in the Altair user guide:

selection = alt.selection_multi(fields=['Origin'])color =
alt.condition(selection,
                      alt.Color('Origin:N', legend=None),
                      alt.value('lightgray'))
scatter = alt.Chart(cars).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color=color,
    tooltip='Name:N')
legend = alt.Chart(cars).mark_point().encode(
    y=alt.Y('Origin:N', axis=alt.Axis(orient='right')),
    color=color).add_selection(
    selection)
scatter | legend

**Comment by jakevdp** [comment]
You should call ``add_selection()`` on the chart that you want the selection action to take place on.

**Comment by mercyfulace1** [comment]
Got it. Thanks.
