### ISSUE TITLE
Inconsistent date formatting in axis

### ISSUE THREAD

**Issue by tedsanders** [altair-viz/altair#1426]
Not sure if this is a new bug, or even Altair-related, but in case it is:

When using the ':T' suffix for date data, the axis labels seem to mix day of the week and month. Very bizarre. Here's an example of code and the x-axis it outputs:

![image](https://user-images.githubusercontent.com/3196287/55919051-52e74680-5ba9-11e9-938c-bc6151e84112.png)

![image](https://user-images.githubusercontent.com/3196287/55919005-30552d80-5ba9-11e9-9d7d-6f94416938b6.png)

The dates are normal strings

![image](https://user-images.githubusercontent.com/3196287/55919089-75795f80-5ba9-11e9-8567-95a4fc541681.png)

And the graph looks fine if I plot without the ':T' suffix:

![image](https://user-images.githubusercontent.com/3196287/55919117-96da4b80-5ba9-11e9-974f-0c28c37e26dc.png)

![image](https://user-images.githubusercontent.com/3196287/55919107-888c2f80-5ba9-11e9-8ef6-fa2b36018347.png)

Is this known? Expected? A bug?

Sorry for not providing reproducible data and code. Happy to put in the effort if this it's useful.

**Comment by jakevdp** [comment]
Yes, this is expected.

When you specify ``x='date:T'``, you are specifying a temporal data type, and Altair treats the values as dates.

When you specify ``x='date'``, altair must infer the data type. For strings, Altair always chooses the nominal type (i.e. unordered named categories) and so it displays the values in a way that is appropriate for category names. You can confirm this by explicitly setting ``x='date:N'`` and observe the same behavior.
