### ISSUE TITLE
Checkbox with default does not work after first click

### ISSUE THREAD

**Issue by pmacosta** [altair-viz/altair#1428]
A checkbox using the "init" argument works as expected at first, but after the first click it does not seem to work anymore. For example, in the chart produced by the code below, the checkboxes start "checked" and the sets are selected, as expected. Clicking on the checkboxes "unchecks" them and the associated selections are greyed out, again as expected. However, if the checkboxes are clicked again, the checkmark appears but the selection remains greyed out.

    import pandas as pd
    import altair as alt
    data = pd.DataFrame(
        {
            "Block":("A", "A", "B", "A", "B", "A"),
            "X":(10, 15, 11, 30, 45, 9),
            "Y":(1.1, 10, 3.5, 5, 10, 20),
        }
    )
    a_data = data.loc[data["Block"] == "A"]
    b_data = data.loc[data["Block"] == "B"]
    a_filter = alt.binding_checkbox()
    b_filter = alt.binding_checkbox()
    a_select = alt.selection_single(
        fields=["Block"], bind=a_filter, name="A", init={"Block":"A"}
    )
    b_select = alt.selection_single(
        fields=["Block"], bind=b_filter, name="B", init={"Block":"B"}
    )
    a_cond = alt.condition(
        a_select, alt.Color("Block:N"), alt.value("lightgray")
    )
    b_cond = alt.condition(
        b_select, alt.Color("Block:N"), alt.value("lightgray")
    )
    a_chart = alt.Chart(a_data).mark_point(filled=True).encode(
        x="X:Q",
        y=alt.Y(
            "Y:Q", scale=alt.Scale(type="log")
        ),
        color=a_cond
    ).add_selection(a_select)
    b_chart = alt.Chart(b_data).mark_point(filled=True).encode(
        x="X:Q",
        y=alt.Y(
            "Y:Q", scale=alt.Scale(type="log")
        ),
        color=b_cond
    ).add_selection(b_select)
    (a_chart + b_chart)

**Comment by jakevdp** [comment]
This doesn't seem to have anything to do with initialization, but it does appear to be a regression in Vega-Lite 3 (it works correctly in Vega-Lite 2). I've opened an issue here: https://github.com/vega/vega-lite/issues/4870

**Comment by binste** [comment]
Seems like this was addressed in https://github.com/vega/vega-lite/issues/4870.
