### ISSUE TITLE
Adding a text label changes order

### ISSUE THREAD

**Issue by andyreagan** [altair-viz/altair#1429]
It seems like adding a text label changes the ordering.

```
import pandas as pd
import altair as alt
word_vector = pd.DataFrame({"words": ["these", "are", "test", "words", "one", "two", "three"], "delta": [1.5, -1.2, .9, -.7, .8, 0.4, .89]})
word_vector["abs_delta"] = np.abs(word_vector.delta)

alt.Chart(word_vector).mark_bar().encode(
    y=alt.Y("words:N", sort={"op": "sum", "field": "abs_delta", "order": "descending"}),
    x='delta:Q',
    tooltip=["words", "delta"],
).interactive()
```

produces

![visualization (1)](https://user-images.githubusercontent.com/3012361/55990993-30bbfa00-5c77-11e9-99f0-4b687216e661.png)

In the vega editor it works [the same](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgDY6ABjoArWNwB2kADTgo8TQDNG1bGGCQKjZAHczFlCfxmAzIsXaoNxgBMWZgBZ3AF9g3QhIH3Q8TBwLDXRUZDNI6NE5AHY5Q3hDdmRFAE4AVkKXFwBGCuQM9AyM5Bd4AA54CvY5AIz2SDC9VJjYZDxYez0IqJiRTOzc-KLS8qqauoam1vbO7rMAbXGIc0h0dlgAfR9kMRizCrpiz0jL65xb+69uACcfUZxIFmQhr1wgcIBZjmcLldYmBbtIHpDnmARLCHjZPt8UugPsk+iDQUcTucntDlIV4cSzKTUeiflA8AC8ED9vjwUSoZS6BlyeycCJlFz3l9aZA0UKmXjDqyESS6M1uYjlHLBRjfpoccCQWDCdKOQF5TK9crhXg0eK8VqIRScIqyVAddbZbaRTSUixsTj9gBdPS4qDIDQGHyMDSmOL7P7cbhXRiEXbMw7GS4+FKijEPPAAT0IyV+Gm4qGD6DEZs1kETYmTvx16azOagAEdWOgNHhmNFGFRel6NVAAB72MvWCspat02spRvN1sxVud30RDNjCWDpMpl09iLqD6MuIr4e-KUUh7cWO-WCsVA6KDo5AfEcA+D+oMhksHP7j3P5wvF-bBH3AyAMA+ABrFJ2CxHR+iGMRkHgVtNCXN9oNgvBPkUaQKkQkFIHYYNKygBAiwBSDl39QNg2oWkdkgfsHkXT0NygIDQN3YwxGLX4AGJyhcK9B3YgB5Qh0HgZhFwdCppDeSBYDwD5uGAusRUQSRXwiBDfh2VBuFYIYfG4GwNE8bwNH0mwsG03TkFYQhPTAAA+MATLMiydKGbSqAAQhIvFIGxdQxE7X5qDEbhwOLRi-g+ZtYDEaIlK0tzkDMoynLwgzXKsmy7Mc5yMss9zuC8nzsMzbMUmDekPgoIsSrfAAvSNL1+GwUEubzfx9EBgiAA)

while adding a text label

```
base = alt.Chart(word_vector).encode(
    y=alt.Y("words:N",  sort={"op": "sum", "field": "abs_delta", "order": "descending"}),
    x='delta:Q',
)

bars = base.mark_bar().encode(
    tooltip=["words", "delta"],
)

words_right = base.mark_text(align="left", baseline="middle", dx=2).encode(
    text="words",
)

# words_left = base.mark_text(align="right", baseline="middle", dx=-2).encode(
#     text="words",
# )

alt.layer(
    bars,
    words_right,
    # words_left
)
# .resolve_scale(
#     y='independent'
# )
```
produces 

![visualization (2)](https://user-images.githubusercontent.com/3012361/55991019-3f0a1600-5c77-11e9-899a-f108556cac08.png)

although, this [seems to work in the vega-editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAkDODGALApgWwIaQFxUQFzwAdYsB6UgN2QHN0A6agSz0QFcAjOxge1IRQyUa6ALQAbZskoAmOgDY6ABjoArWNwB2kADTgo8TQDNG1bGGCQKjZAHczFlCfxmAzIsXaoNxgBMWZgBZ3AF9g3QhIH3Q8dFhkPFh7PQiomJE5AHY5Q3hDdmRFAE4AVkKXFwBGCuQM9AyM5Bd4AA54CvY5AIz2MwBtZIhzSHR2WAB9H2QxGLMKumLPSKmZnDmFr24AJx9EnEgWZDjIMIGICxHxyenMVbppRauVsBE5+43t3ah0TeRj8MGzsNRhNljcwMpCg9QWYIYsbFsdmZ9oc8H9TkMLiDrjC6BkodicCJlHj3oi9vCPmiAYDMY8wcpmvingy4QjPpBNL8TtSMcC6TiAkz6XRBaT2Xh4VTqec+dCcAzIVB+fK6M1FZAKWSoCwflyBgBdPTcqBidAAT2Qmz6A1APMi0TBFg06FQvz2qVEmWyuXyRVK5SqNTqDSarXanW6UoBkGQGgMPkYGlMOFtPO13G400YhGtacGFmMUx8SM1iUWeDNhDdUA03FQifQYijaYL1jExfd0PLlerkAAjqx0Bo8MxoowqMd0RB9f87QAPeyQQvtpH87tVpEDocjmIjifGu1mpJ5iLLjtinRTwaQdSbVEppdt89Ay5dqDcHN7WCsVA6d-bS1V0OeBYwTJNmztCsNz2Wt62dJsr2CdED2vDBNgAayRdhvkgAYUNTaMPUXZ1XVXB10iyHI8gKEoykqapanqRoWjaDouh6FCIljeNE2Tcwr2ROd7yGM8SzZP99h7JFYIbJtOOvBcH1EztsXXXst2HUc9y5WdqUgI8UyvU8nzEyldLtW9hNbIskVpN8OU-KBv1-RYEUAzsEFA3iIL0qDexk+DcLzJCeXkyA0Mwh9GxMLQ9jEZBDFRRZsLiCQNF7esfB8eKJJ8RSwDeSToO1ZAhMnAEQrAQ1giAA)

**Comment by andyreagan** [comment]
It looks like my jupyter lab is using version 2.6 of vega-lite, which the editor is using 3.1

perhaps this is entirely related to vega-lite...

**Comment by andyreagan** [comment]
I got that I was using 2.6 by looking at "view source" and seeing `"$schema": "https://vega.github.io/schema/vega-lite/v2.6.0.json",`

**Comment by jakevdp** [comment]
This is a known bug in Vega-Lite 2, and is fixed in Vega-Lite 3. See #820

**Comment by andyreagan** [comment]
🙇
