### ISSUE TITLE
multilayer map not showing in web application

### ISSUE THREAD

**Issue by zstatmanweil** [altair-viz/altair#1430]
I am creating a very simple multilayer map of a U.S. county on top of that county's state, and it is working well in Jupyter Lab, but when I try to convert it to a json for my Flask web application, only the state boundary is shown rather than both the county and state boundaries. 

Here is the code in Jupyter Lab that works great:

``` python3
states_topo = alt.topo_feature('https://raw.githubusercontent.com/vega/vega-datasets/master/data/us-10m.json', feature='states')
counties_topo = alt.topo_feature('https://raw.githubusercontent.com/vega/vega-datasets/master/data/us-10m.json', feature='counties')

state_map = alt.Chart(data=states_topo).mark_geoshape(
                fill='lightgrey',
                stroke='white'
            ).transform_filter((alt.datum.id == 6))

county_map = alt.Chart(data=counties_topo).mark_geoshape(
                fill='red',
                stroke='white'
            ).transform_filter(alt.datum.id == 6001)

chart = alt.layer(state_map, county_map)

chart
```

And then here is the code in my Flask app, which only shows the state, and not the county:

```python3
@app.route("/map")
def draw_map()
    states_topo = alt.topo_feature('https://raw.githubusercontent.com/vega/vega-datasets/master/data/us-10m.json', feature='states')
    counties_topo = alt.topo_feature('https://raw.githubusercontent.com/vega/vega-datasets/master/data/us-10m.json', feature='counties')


    state_map = Chart(data=states_topo, height=HEIGHT, width=WIDTH).mark_geoshape(
                fill='lightgrey',
                stroke='white'
            ).transform_filter((alt.datum.id == 6))

    county_map = Chart(data=counties_topo, height=HEIGHT, width=WIDTH).mark_geoshape(
                fill='red',
                stroke='white'
            ).transform_filter((alt.datum.id == 6001))

    chart = alt.layer(state_map, county_map)

    return chart.to_json()
```

Any ideas would be much appreciated! If you need any additional information, I would be happy to provide.

**Comment by jakevdp** [comment]
Perhaps it's due to a difference in vega/vega-lite/vega-embed library versions? In JupyterLab, the javascript is loaded from the vega jupyterlab extension. In your flask app, presumably you're specifying the locations of the vega javascript sources somewhere; you should make certain that you're specifying versions that are compatible with the version of Altair you are using.

**Comment by zstatmanweil** [comment]
That was exactly it. Thank you so much!
