### ISSUE TITLE
Altair selections resolve incorrectly as scale domain values.

### ISSUE THREAD

**Issue by jheer** [altair-viz/altair#1431]
I am observing this issue in Altair 2.x. Apologies if this issue has already been addressed for v3!

The following code for an overview + detail plot fails:

```python
brush = alt.selection_interval(encodings=['x']);

base = alt.Chart().mark_area().encode(
    x=alt.X('date:T', title=None),
    y='price:Q'
).properties(
    width=700
)
  
alt.vconcat(
    base.encode(alt.X('date:T', title=None, scale=alt.Scale(domain=brush))),
    base.add_selection(brush).properties(height=60),
    data='https://vega.github.io/vega-datasets/data/sp500.csv'
)
```

The errors indicate that Altair is expanding the brush to the full selection definition (what you would use for `add_selection`) rather than generating a selection reference. If I add `name='brush'` to the selection definition and then replace `domain=brush` with `domain={'selection': 'brush'}`, the example works.

**Comment by jheer** [comment]
Just ran into this same issue a second time but in a different context: creating a logical `or` predicate for a filter transform:

```python
base = plot.transform_filter(
    # filter to points in either selection
    {'or': [{'selection': 'hover'}, {'selection': 'click'}]}
)
```

Consider this an up-vote for #695 as well! :)

**Comment by jakevdp** [comment]
You need to use ``selection.ref()`` in this context, as demonstrated in this example: https://altair-viz.github.io/gallery/interval_selection.html

Explanation: serialization of Altair objects is context free, and how Vega-Lite references selections depends on the context. The solution we came up with in Altair is to use ``selection`` to refer to the full selection definition, and ``selection.ref()`` to refer to a reference to the selection.

**Comment by jheer** [comment]
Thanks! It seems that direct use as an argument to transform_filter is an exception to this rule? That’s what threw me off in the first place. Perhaps it would help others to consistently distinguish selection defs and refs.

FWIW I implemented context sensitive resolutions in the VL JavaScript API via serialization flags that can be set (or not set) in different contexts. In the case of selections I made refs the default serialization as they show up in many contexts, whereas selection definitions only show up within chart add_selection contexts. Happy to share more if that is of interest.

**Comment by jakevdp** [comment]
The difference there are that ``transform_filter()`` and ``alt.condition`` are functions that are manually defined in the code, whereas ``alt.Scale`` is an auto-generated wrapper of the Vega-Lite ``Scale`` definition. We could certainly do a manual re-definition of ``Scale`` and handle the ``domain`` keyword differently, but then every time Vega-Lite updates we'd have to manually update our scale definition. It's a tug-of-war between maintainability and usability, and because maintenance falls on basically just me, I tend to err toward maintainability.

**Comment by jakevdp** [comment]
One way we could maybe improve this is to not make Altair selections equivalent Vega-Lite selection objects, but rather make them objects with a JSON representation of ``{selection: "name"}`` , but which resolve the same way as selection objects within the context of ``add_selection``. It would take a bit of refactoring, but probably would be better.

**Comment by jheer** [comment]
Sounds good to me! That is the solution the JS API uses (the bit above about serialization flags is just how I implemented it in a reusable fashion in my analogue of schemapi).

**Comment by jakevdp** [comment]
See #1433
