### ISSUE TITLE
Axis labels for years before 1900

### ISSUE THREAD

**Issue by sawula** [altair-viz/altair#1434]
Axis labels incorrect for dates with years before 1900.  Was trying a simple line plot of S&P 500 prices dating back to 1871.  Using Colab, `x='Date:T'` .  Can provide more code but suspect this is sufficient.

Here's a pic:

![image](https://user-images.githubusercontent.com/3756836/56092999-9257b080-5e91-11e9-8a6d-78bb532c7cd6.png)

**Comment by jakevdp** [comment]
Thanks for the report. This appears to have been fixed in Vega-Lite 3, so once you update to Altair 3 it will no longer be a problem.
