### ISSUE TITLE
Stacked charts missing data when selections are made

### ISSUE THREAD

**Issue by alberto139** [altair-viz/altair#1450]
I'm running into an issue when stacking charts with interactive selections. My data looks like this and is loaded into a pandas dataframe called 'traffic' in this example:

```
                       timestamp    id   class  aoi_id      speed direction
0  2019-04-22 10:29:28.077605486    57     car       0   5.497771      left
1  2019-04-22 10:29:30.696949959   102  person       0   9.731984      left
2  2019-04-22 10:29:37.677063465   223     car       0  10.665556      left
3  2019-04-22 10:29:58.947000504   678     car       0  19.667283     right
4  2019-04-22 10:30:43.345098734  1526     bus       0   8.733052      left
```

My code looks like this:
```
base = alt.Chart(traffic).mark_point().encode(
    x = alt.X('timestamp', scale=alt.Scale(zero=False)), 
    color='class').properties(width=800, selection=interval)

hist = alt.Chart(traffic).mark_bar().encode(
    x= alt.X('count()'),
    y='class',
    color='class').properties(width=800).transform_filter(interval)
```
![visualization (1)](https://user-images.githubusercontent.com/5776237/56549577-f59fad80-6537-11e9-8a48-c81a03850db6.png)

Initially the results look fine. However I wanted to change the x-axis of the first chart to be represented as time using `alt.X('timestamp:T')`. After this change the x-axis looks fine but the data of the bar chart disappears when a selection is made

![visualization (2)](https://user-images.githubusercontent.com/5776237/56549762-824a6b80-6538-11e9-83c9-a41626974f7e.png)

Is there a way around this?

**Comment by jakevdp** [comment]
This is a [known bug](https://github.com/vega/vega-lite/issues/3737) in Vega-Lite. The way around it is to specify a timeunit on your temporal data. Here's an example:

```python
import pandas as pd
import numpy as np
import altair as alt

traffic = pd.DataFrame({
    'timestamp': pd.date_range('2019-01-01 12:00', freq='T', periods=20),
    'class': np.random.choice(['car', 'person', 'bus'], 20),
})

interval = alt.selection_interval()

base = alt.Chart(traffic).mark_point().encode(
    x='hoursminutes(timestamp)', 
    color='class'
).properties(
    width=800
).add_selection(
    interval
)

hist = alt.Chart(traffic).mark_bar().encode(
    x='count()',
    y='class',
    color='class'
).properties(
    width=800
).transform_filter(
    interval
)

base & hist
```

**Comment by alberto139** [comment]
Thanks for the quick reply and the example!
It works perfectly!
