### ISSUE TITLE
Plot map data from one dataset based on geodata from other

### ISSUE THREAD

**Issue by Progern** [altair-viz/altair#1451]
Hello! I have a question and I didn't manage to find an answer. Maybe the community could help me.

So, making long story short.

I have a **dataset_1** which contains yearly data for different countries.
I have a **dataset_2** which contains polygon yearly data for different countries.

**What I want to achieve**: 

- World map chart
- Area chart below the map to navigate through years (or other slider) [Example](http://prntscr.com/nfqosv)
- World map data should rely on **dataset_1**, but I want to draw polygons from **dataset_2**
- While we slide area chart I want to update the world map [Example](http://prntscr.com/nfqp4p)

**Comment by mattijn** [comment]
Start by reading these resources:
- https://iliatimofeev.github.io/gpdvega/gallery/map_with_data.html
- Issue: https://github.com/altair-viz/altair/issues/1357

And then try apply similar logic to your data.
If you still get stuck somewhere you should have some reproducible code from where further support might be provided.
