### ISSUE TITLE
3.0.0 not working with jupyterlab 0.35.5

### ISSUE THREAD

**Issue by guenteru** [altair-viz/altair#1459]
Hi,
I just pip installed the new release and and there appears to be a compatibility issue with jupyterlab v0.35.5 because I get the following error message: `<VegaLite 3 object>`.

I quickly downgraded altair to an older version (v.2.4.1) which ran without problems.

**Comment by stonebig** [comment]
It's normal. Altair-3 world with the clasdic notebook  , or with jupyterlab-1.0.0a3

**Comment by jakevdp** [comment]
Altair 3.0 requires JupyterLab 1.0 or newer, as mentioned in the docs: https://altair-viz.github.io/user_guide/troubleshooting.html#jupyterlab-vegalite-3-object

**Comment by poglesbyg** [comment]
`pip install jupyterlab==1.0.0a3` will fix the jupyter lab version for the newest altair

**Comment by ewels** [comment]
I just fell in to the same trap - am I right in thinking that JupyterLab 1.0 is not yet available on conda?

Following the instructions in the docs (`$ conda install -c conda-forge altair vega_datasets jupyterlab`) installs v0.35.5 for me. I read the docs about needing 1.0 but because I couldn't find such a version on conda assumed that I was misunderstanding something.

**Comment by morberg** [comment]
This part of the documentation had me confused: https://altair-viz.github.io/user_guide/display_frontends.html#display-jupyterlab

**Comment by stonebig** [comment]
well, it works exactly as written: 
- type the code in IDLE editor (tcl-Tk) for example,
- run it,
- a 127.0.0.1 page opens up on your browser
![image](https://user-images.githubusercontent.com/4312421/57197185-62696d80-6f64-11e9-8597-b14d729712e0.png)

**Comment by jakevdp** [comment]
> This part of the documentation had me confused: https://altair-viz.github.io/user_guide/display_frontends.html#display-jupyterlab

Thanks - that should be updated

**Comment by jakevdp** [comment]
Updated in #1472; it will be on the website with the next release.
