### ISSUE TITLE
Date Time Axis Formatting 

### ISSUE THREAD

**Issue by ashutosh29** [altair-viz/altair#1462]
Hi,

Have been trying to convert 'month' in axis-label to upper case in below chart

![visualization](https://user-images.githubusercontent.com/13638740/56942971-fc7f7f00-6b3a-11e9-9690-abf6b56a2a7d.png)

To create above visualization, I am using below code:

```
points = alt.Chart(c).mark_circle(size = 0).encode(color = 'company:N')

lines = alt.Chart(c, title = 'Sample'.upper()).mark_line().encode(
                                                                  x = alt.X('index:T', axis = alt.Axis(title = 'Date'.upper(), format = ("%b %Y"))),
                                                                  y = alt.Y('value:Q', axis = alt.Axis(title = 'Value'.upper())),
                                                                  color = alt.Color('company:N', legend = alt.Legend(title = 'Legend')),
                                                                ).interactive()

chart = lines + points

chart

```

But not being able to do so.

Any suggestion is highly appreciable.

The formatting should look like as below for X Axis Months

![Exhibit01](https://user-images.githubusercontent.com/13638740/56943169-ddcdb800-6b3b-11e9-819b-2ae7f6066367.jpg)

And another issue:

As visible there are duplication of labels in the 1st chart.

How to remove the duplication ?

**Comment by jakevdp** [comment]
The available formats for timeunit axes are listed here: https://github.com/d3/d3-time-format#locale_format

If the format you want is not available there, then the best approach would be to use a calculate transform, which allows for a wider range of string formats.
