### ISSUE TITLE
Altair v3 on Colab? Requires Vega 5, not Vega 4.

### ISSUE THREAD

**Issue by jheer** [altair-viz/altair#1464]
_(Apologies if this is the wrong place to post this issue, but at this point I don't yet know if this is an "Altair issue", an "ipyvega issue", or a "Colab issue".)_

I'm trying to use Altair 3.0 on Colab. If I run `pip install --upgrade altair vega` in the notebook, I can update from Colab's default of v2.4.1 to the latest 3.0.0. So far so good!

I can then start creating charts, but then I notice that some are not rendering correctly. Opening the web inspector, I can see that the generated HTML includes imports from jsdelivr for Vega-Lite@3.2.1 (good!) and Vega@4 (not good!). Vega-Lite 3+ requires Vega 5. Without it, a number of 3.x features will not work correctly.

If this is due to Altair's output, consider this a bug fix request. If not, feel free to close the issue, in which case any pointers to patch things up on the ipyvega or Colab side are welcomed! Flagging @domoritz as well.

**Comment by jakevdp** [comment]
Yeah, that was an oversight – I fixed it in #1461.

For the time being, you can hack it by running the following after you import altair:
```python
alt.display.colab_renderer.kwargs.update({'vega_version': '5', 'vegaembed_version': '4'})
```

**Comment by jheer** [comment]
Ok, thanks!

**Comment by jakevdp** [comment]
For anyone coming across this, the hack described above is no longer necessary to use Altair in Colab.

**Comment by lee-werner** [comment]
Thanks for the closure Jake!

- internet person coming across this post a year later
