### ISSUE TITLE
How to set the color of a plotted line directly/manually?

### ISSUE THREAD

**Issue by trllrgn** [altair-viz/altair#1466]
I have found some examples where a color scale is defined and a category variable is chosen based on which the plots are colored. E.g. here:
https://github.com/altair-viz/altair/issues/921

I want the user to be able to plot various lines onto a LayerChart, and select the color manually for each line added (i.e. choose a color from a dropdown list, click plot, and add a new plot to the existing chart with the color chosen). How can I directly tell altair to plot using a certain color?

I tried:
```
lines = alt.Chart(df).mark_line().encode(
    x=alt.X(...),
    y=alt.Y(...),
    color='rgb(255,184,56)'
)
```

but this does not work.
Thanks.

**Comment by trllrgn** [comment]
The following works when I use e.g. 'black' but it does not recognise rgb:

```
lines = alt.Chart(df).mark_line(color='rgb(255,184,56)').encode(
    x=alt.X(...),
    y=alt.Y(...)
)
```
If someone could explain how to use rgb colors then that would also solve my problem.
Thanks.

**Comment by jakevdp** [comment]
Two ways to do this:
```python
alt.Chart(df).mark_line(color="#FFAA00").encode(
  x='x',
  y='y'
)
```
or
```python
alt.Chart(df).mark_line().encode(
  x='x',
  y='y',
  color=alt.value("#FFAA00")
)
```

See [Customizing Visualizations](https://altair-viz.github.io/user_guide/customization.html) for more information.

**Comment by trllrgn** [comment]
Thanks, not sure how I missed that.

**Comment by RajUnikie** [comment]
Thanks. It fit my purpose. Though I tried alt.Scale from [here](https://github.com/altair-viz/altair/issues/921), the color is not consistent for the plots called several times on the same page. Now it is. Probably I missed a common range/domain definition.
