### ISSUE TITLE
Difficulty Linking Charts While Abusing Altair.

### ISSUE THREAD

**Issue by batu** [altair-viz/altair#1467]
Let me start by explaining my madness:

I am working on a gameplaying algorithm. In one of the steps, the algorithm makes a decision to load a specific game state. And in the analysis step -- which I am doing right now -- I have the details of how many times an individual state has been selected and a screenshot that goes along with that state. 

Wanting to learn Altair, because it is the best thing invented since toasted bread, I decided to create a simple visualization:
1) Have a bar chart that shows how many times each state has been selected.
2) When I click on any bar, display the image associated with that state somewhere.

I soon realized that Altair cannot display images. I was a bit bummed, but I REALLY wanted this. Then it hit me. Altair COULD display scatter plots, which is simply a series of colored points. What was an image, if not a series of colored points?

![image](https://user-images.githubusercontent.com/6670976/57168687-aa975d00-6db7-11e9-8fa2-b0dca2b3435f.png)
([Portion of the code to create this](https://gist.github.com/batu/e10b5104e91e9c8a7e13e339d9a0133c))

A data frame that contained (X, Y, Color) later I had it working. Now I just needed to connect it to the bar chart. And this where I am at. (Working with downscaled images for performance)

![Altair](https://user-images.githubusercontent.com/6670976/57169196-390cde00-6dba-11e9-9712-8f371fc29a86.gif)

Let me explain the behavior:
1) On the left, I am showing how many times each state has been selected as a bar chart, on the right our downsampled image scatter plot. I think there are hundreds of bars being drawn on top of each other, which might be a problem.
2) I am drawing ALL the images on top of each other with .5 opacity. 
3) When I click on one, it filters based on the index. (This is why it goes mostly black initially.) 
4) When I click on whitespace all are back with a different z-fighting order.
5) When I hover over both the images and the bar charts I can see the "index" as the tooltip.
6) When I click on the bar chart all the images disappear.

#3 shows me that filtering is working.
#5 shows me that the index selection is correct.

However, I couldn't get it to work beyond what you see here. The code that displays the charts are below. ([If you need to see the DF creation](https://gist.github.com/batu/9adab925896ed3766fe1b63fc9f1e1c5). On the high level, it is similar to the earlier example but joined on all the values, per image.)

```python
clicker = alt.selection_single(empty="all", fields=['index'])

chart = alt.Chart(images_pd).mark_bar().encode(
    # Couldn't get it to work with mod(index):Q
    x='index:Q',
    y='explore_counts:Q',
    tooltip=["index"]
).add_selection(
    clicker
)

img_chart = alt.Chart(images_pd).mark_square(size=400, opacity=.5).encode(
    x="x:Q",
    y="y:Q",
    color=alt.Color('color', scale=None),
    tooltip=["index"]
).transform_filter(
    clicker
).add_selection(
    clicker
)

chart | img_chart`
```

Any help would be appreciated, and thank you very much for this library. I find it incredibly elegant and powerful.

**Comment by jakevdp** [comment]
Abusing libraries is the best way to learn about them 😄 

Without the data it's hard to tell, but I think maybe the issue is that you should not call ``add_selection`` on the image chart.

**Comment by mattijn** [comment]
Seems similar to https://altair-viz.github.io/gallery/select_detail.html

Using `init` in your `selection` variable it's possible to define a start selection and with `empty='none'` nothing is drawn when nothing is selected. 

I think you should be able to extract the needed logic from here.

```python
import altair as alt
import pandas as pd
import numpy as np

np.random.seed(0)

n_objects = 20
n_times = 50

# Create one (x, y) pair of metadata per object
locations = pd.DataFrame({
    'id': range(n_objects),
    'x': np.random.randn(n_objects),
    'y': np.random.randn(n_objects)
})

# Create a 50-element time-series for each object
timeseries = pd.DataFrame(np.random.randn(n_times, n_objects).cumsum(0),
                          columns=locations['id'],
                          index=pd.RangeIndex(0, n_times, name='time'))

# Melt the wide-form timeseries into a long-form view
timeseries = timeseries.reset_index().melt('time')

# Merge the (x, y) metadata into the long-form view
timeseries['id'] = timeseries['id'].astype(int)  # make merge not complain
data = pd.merge(timeseries, locations, on='id')
```


```python
data.head()
```




<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>time</th>
      <th>id</th>
      <th>value</th>
      <th>x</th>
      <th>y</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>0</td>
      <td>0</td>
      <td>-1.048553</td>
      <td>1.764052</td>
      <td>-2.55299</td>
    </tr>
    <tr>
      <th>1</th>
      <td>1</td>
      <td>0</td>
      <td>-1.721013</td>
      <td>1.764052</td>
      <td>-2.55299</td>
    </tr>
    <tr>
      <th>2</th>
      <td>2</td>
      <td>0</td>
      <td>-2.886163</td>
      <td>1.764052</td>
      <td>-2.55299</td>
    </tr>
    <tr>
      <th>3</th>
      <td>3</td>
      <td>0</td>
      <td>-1.003013</td>
      <td>1.764052</td>
      <td>-2.55299</td>
    </tr>
    <tr>
      <th>4</th>
      <td>4</td>
      <td>0</td>
      <td>-0.626587</td>
      <td>1.764052</td>
      <td>-2.55299</td>
    </tr>
  </tbody>
</table>
</div>




```python
# Data is prepared, now make a chart
selector = alt.selection_single(empty='none', fields=['id'], init={'id':8})

base = alt.Chart(data).properties(
    width=250,
    height=250
).add_selection(selector)

bars = base.mark_bar().encode(
    x='id:O',
    y='mean(y)',
    color=alt.condition(selector, 'id:O', alt.value('lightgray'), legend=None),
)

scatter = base.mark_point().encode(
    x='time',
    y=alt.Y('value', scale=alt.Scale(domain=(-15, 15))),
    color=alt.Color('id:O', legend=None)
).transform_filter(
    selector
)

bars | scatter
```

![Kapture 2019-05-04 at 9 23 36](https://user-images.githubusercontent.com/5186265/57175606-5db29580-6e4e-11e9-96b9-15ff5bc7ae12.gif)

**Comment by batu** [comment]
I managed to get it to work! Thank you! 

I believe the problem lied in the way I structured the data -- as mentioned -- and using pd.merge made it click.

![Working](https://user-images.githubusercontent.com/6670976/57242317-106a2b80-6fe8-11e9-97a7-68e9ca6d5b53.gif)

Unfortunately, however this crazy way of showing images doesn't scale.

Do you think there is currently a scalable way of getting this behavior I want from altair? (click on data, see image?) 

Either way, thank you very much for your help!

**Comment by jakevdp** [comment]
Vega-Lite currently doesn't support image marks, but there's an open issue discussing it: https://github.com/vega/vega-lite/issues/3758

One issue with scalability is the fact that currently each image pixel is stored in a row of the dataset, along with a copy of all the metadata associated with the image. You can get around that by storing the image data in a 2D array within a single entry of the data table, and then use a [flatten transform](https://altair-viz.github.io/user_guide/transform.html#user-guide-flatten-transform) within the chart spec to pull it out. That should help push the limit of the pixel resolution in your heatmap.

**Comment by batu** [comment]
Awesome! Wasn't aware of the flatten transform. This should make it much better!

For some replicating the whole data for each pixel wasn't the best... Who knew!

**Comment by batu** [comment]
@jakevdp 
I tried using the flatten transform but couldn't really make it work.

When you have time can you describe the proper way to set up the dataframe? (for any arbitrary numpy image. Currently it is a matrix with hex values, on my end.)

Thank you ~

**Comment by jakevdp** [comment]
It's not all that intuitive and not documented, but you can use a similar strategy to that shown in the [Flatten Transform](https://altair-viz.github.io/user_guide/transform.html#flatten-transform) documentation to unfold a 2D array into rows and colums, by applying the flatten transform twice. For example:
```python
import numpy as np
import pandas as pd

# three 100x100 images
images = np.random.randint(0, 256, (3, 100, 100))

# put images into dense dataframe
data = pd.DataFrame({
    'label': ['A', 'B', 'C'],
    'images': list(images)
})
data


alt.Chart(data).transform_flatten(
    ['images']
).transform_window(
    row='row_number()',
    groupby=['label']
).transform_flatten(
    ['images']
).transform_window(
    col='row_number()',
    groupby=['label', 'row']
).mark_rect().encode(
    x='col:O',
    y='row:O',
    color='images:Q',
    facet='label:N'
).properties(
    width=200,
    height=200
)
```
![visualization (20)](https://user-images.githubusercontent.com/781659/57402394-1ac52a80-718c-11e9-950a-5367f424fb65.png)

It would be nice to add an example like this as part of the flatten transform section.
