### ISSUE TITLE
Improve placement of "click to view actions" button?

### ISSUE THREAD

**Issue by ralexx** [altair-viz/altair#1469]
I very much like the consolidation of the export options into the handy button in v3.0.0. However, the button's placement on the right side of a Jupyter cell is not very ergonomic when I use Altair to draw a chart whose boundaries are larger than the available screen space in my browser window. Jupyter anchors the Altair chart output to the top left corner of cells so the export options button is pushed off the right side of the cell and I have to scroll (a lot, in my case) to reach it.

Could the button be placed in the upper left corner instead?

**Comment by jakevdp** [comment]
Those properties are defined by [vega-embed](https://github.com/vega/vega-embed), and unfortunately there are not currently any knobs to control the menu location. It may be worth a feature request there.
