### ISSUE TITLE
Duplicated axis label if use alt.Axis()

### ISSUE THREAD

**Issue by yoonghm** [altair-viz/altair#1471]
```
import pandas as pd
import altair as alt

data = pd.DataFrame(
    {'Student': list('ABCDEDFG'),
     'GPA': [3.9, 2.5, 3.2, 4.0, 3.7, 2.9, 3.0, 3.1],
     'Diploma': ['CEM', 'EE', 'AVT', 'EE', 'CEM', 'EE', 'AVT', 'CEM']
    }
)
alt.Chart(data, title='Enrollment of Diploma').mark_circle().encode(
    x=alt.X('Diploma', 
            axis=alt.Axis(title='Diploma')),
    y=alt.Y('count(Diploma)', 
            axis=alt.Axis(format='.1', title='Count')
           )
)
```

The VESA json is in [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgolcdXFzI8caIKlIx0wFoArNADsANiZ8GBAExundwBOPgBGACN3AicCSgZXAA4GZldxUNDIAwgxKVksGGRJaCUbVkNIAng4SmR4dCxQCGyAD3NqAE81G3z4WFFa8SVIEXFm5ABnNuRqEtsAEXUlPrNhKBQCJUp5xeXMsqaodrlDA8gOrtte-ssh-YOocVRUSQJUE26oOC14XjvT0Ym5kQsEkEl4+QAdBkRKoZh9IABhWDfXhZe6QdabbZqJYSSAnMCCQxos7TWb5ACi8EkyiU1h+YFgiDACxxuzukAAJONoJw8fkeNQ1OMMAB6UW4V7iCGoaa0LThCHIWCinl88QSqUOJTTAgSvgQ3xQiEAK3GCGG5Xs4nGBGokwaBLsJnEzjcnm8fgCwTCkWisXiSRSaQyWAA2gSIDgAMrULSUSrgqAAQWGUAA4gAFVNYA1BESs3FmfIIikAWT2kbIsfjidsACE05AszmwEanAWdvyoBSKZX7tW4wmfrYEU2W-xDZ22d3IMmAGoAFX79xjQ7r+Tm4+zjGnRdsvZXBzXtZHlO3rYNrj3uxL5aPTRPw6TkC3IgnWCN+aghdvPb7aLHpANbPrYABiF78Des4LsugGPsB65nhmkG5lC0HFlApYVkSBwALrEiAghAA)

The value "2" is repeated.  Also the distance between y-marks are not the same.

**Comment by yoonghm** [comment]
I know the issue now. It was caused by rounding up of `-0.1`.  However, the `0.5` was not rounded up to 1.

**Comment by jakevdp** [comment]
``format=".1"`` specifies that you would only like one significant digit shown. The reason there are duplicate labels is because the first significant digit is the same for some labels.

I suspect what you were intending was to have one digit after the decimal point; the specifier for that is ``format=".1f"``. You can read more about d3 format codes used by Altair here: https://github.com/d3/d3-format#locale_format
