### ISSUE TITLE
Incomplete Documentation for `mark_area`

### ISSUE THREAD

**Issue by ndanielsen** [altair-viz/altair#1475]
I like the really clear syntax and standards based approach in this library. Enjoying diving into it!

I noticed that the documentation for `mark_area` might not be generating correctly.

Here's the URL:
https://altair-viz.github.io/user_guide/generated/toplevel/altair.Chart.html#altair.Chart.mark_area

<img width="757" alt="Screen Shot 2019-05-06 at 12 58 13 PM" src="https://user-images.githubusercontent.com/2944777/57241596-541c5f80-6fff-11e9-9b69-51fc840367fe.png">

**Comment by jakevdp** [comment]
This is the docstring that is explicitly included for the method: https://github.com/altair-viz/altair/blob/cb8062d14c36dcac60ef57402ea643746855df10/tools/generate_schema_wrapper.py#L329-L342

If you want more details, you can look at the documentation of MarkDef by clicking on the link at that page: https://altair-viz.github.io/user_guide/generated/core/altair.MarkDef.html#altair.MarkDef

It would be possible to duplicate the ``MarkDef`` docstring for each of the ``mark_*`` methods, but we haven't done that.

**Comment by ndanielsen** [comment]
@jakevdp thanks so much for the quick response! Great library and enjoying diving into it!

Closing now as question has been answered!
