### ISSUE TITLE
Charts not rendering in Jupyterlab

### ISSUE THREAD

**Issue by SupahNoob** [altair-viz/altair#1479]
```
jupyter lab --version ---> 0.35.6
altair.__version__    ---> 3.0.1
```
both installed into a virtual environment, using the default renderer.

---
```python
import altair as alt
from vega_datasets import data

iris = data.iris()

alt.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species'
)
```
```
<VegaLite 3 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html
```
---

Not sure what other information I should provide, but I can't seem to get it to show up in Jupyter Lab.

\- SN

**Comment by jakevdp** [comment]
As mentioned at https://altair-viz.github.io/user_guide/troubleshooting.html, Altair 3.0 requires jupyterlab 1.0 or newer. Version 0.35 will not work.

Try running:
```
pip install jupyterlab==1.0.0a3
```
And then try again

**Comment by SupahNoob** [comment]
Well don't I feel silly... I didn't consider jupyterlab to be <1.0 even though I was looking directly at the version number :~)
