### ISSUE TITLE
Add formatting documentation

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#1483]
There have been many questions on this (e.g. https://stackoverflow.com/questions/56016547/is-there-a-way-to-show-percentage-0-100-in-an-altair-normalized-stacked-bar-c); we should show some examples and link to the [d3-format](https://github.com/d3/d3-format) docs for more info.

**Comment by betaigeuze** [comment]
Going through some old issues here and saw that the requested documentation was added long ago (7ba7c210582f78f980f3333a98d8c3295c021b20).

Would propose to close this one.

**Comment by mattijn** [comment]
Noted: https://altair-viz.github.io/user_guide/customization.html?highlight=adjusting%20axis%20labels#adjusting-axis-labels
