### ISSUE TITLE
Inability to create plots on the command line/ Altair only works in Jupyter

### ISSUE THREAD

**Issue by deprekate** [altair-viz/altair#1484]
So it is my understanding that Altair can only display plots in Jupyter/Notebooks ? 

I have a command line script that when run, does not show a plot.

_Originally posted by @Juice178 in https://github.com/altair-viz/altair/issues/457#issuecomment-368847604_

**Comment by jakevdp** [comment]
See https://altair-viz.github.io/user_guide/faq.html#does-altair-work-with-pycharm-spyder-my-favorite-ide

**Comment by jakevdp** [comment]
You can also try vegascope: https://groups.google.com/forum/#!msg/altair-viz/xzbitpeXCFc/3tvloR92AgAJ

(we need to add that option to the docs)
