### ISSUE TITLE
Bar chart not handling negative values properly.

### ISSUE THREAD

**Issue by Eternal-127** [altair-viz/altair#1486]
hi, I am trying to plot a chart of captains with number of win and loss, what I am trying to achieve is plotting losses as negative values and total wins and positive values, however negative values are also plotted on the positive side, then I thought it might be a problem because I was plotting both the charts together, thus i tried only plotting negative loss values and still bar is plotted on positive side even though data contains negative values. here is my code and image.

```
captain_loss_bar = alt.Chart(dr.captain_win_loss).mark_bar(color='steelblue', opacity=1).encode(
        x='player:N',
        y='sum(loss):Q',
        tooltip=['player', 'total', 'loss']
    )

```

![altair_issue](https://user-images.githubusercontent.com/50139053/57382618-e6bd2a00-71ca-11e9-8ec5-341413fee994.png)

**Comment by jakevdp** [comment]
If you draw a chart with negative numbers, the bar will reflect the negative number. For example:
```python
import pandas as pd
import altair as alt

df = pd.DataFrame({
    'x': [1, 2, 3, 4, 5],
    'y': [2, -1, 5, -3, -1]
})

alt.Chart(df).mark_bar().encode(
    x='x:O',
    y='y:Q'
)
```
![visualization (84)](https://user-images.githubusercontent.com/781659/57385468-5994b980-7167-11e9-86a8-e0e6b73c7e9a.png)

If you can show me a specific code snippet (including the data) that is not doing what you expect, I'd be happy to help.
