### ISSUE TITLE
Chart doesn't display graph - Rendering issue

### ISSUE THREAD

**Issue by DarricauVert** [altair-viz/altair#1491]
Hi,

I have looked at the other similar issues but the solutions there don't appear to work.
I am running Jupyter Lab, it should be running   2.7.3 and I have the setups in the screenshot below.

Are there any ideas what could be causing this?
I did have this working a while ago, but through installing new environments and other changes, I'm not sure what has happened.

I have commented out the render line because i am using jupyter lab and not notebooks.

Please let me know if there is any other details that would help.

Thank you for the help...
Screenshot with details:

![image](https://user-images.githubusercontent.com/50443835/57441774-88cc2900-7242-11e9-9a6d-6ed33196f06d.png)

**Comment by alteborg** [comment]
Same issue here..

**Comment by jakevdp** [comment]
If running Altair 3 on JupyterLab, you need JupyterLab version 1.0 or newer. See https://altair-viz.github.io/user_guide/troubleshooting.html for details.

**Comment by DarricauVert** [comment]
> If running Altair 3 on JupyterLab, you need JupyterLab version 1.0 or newer. See https://altair-viz.github.io/user_guide/troubleshooting.html for details.

I saw that and created a new environment through Conda earlier, but it still faces the same issue.
This is what I am getting, please let me know if this still looks incorrect to you...

![image](https://user-images.githubusercontent.com/50443835/57456408-5d0e6a80-7265-11e9-9435-5070d0d1dacf.png)

and:

![image](https://user-images.githubusercontent.com/50443835/57456460-7a433900-7265-11e9-8161-641a01fac955.png)

**Comment by welchr** [comment]
It seems as though `pip install -U jupyterlab` still grabs the 0.35.6 release, not 1.0. I had to manually install the latest tagged release from github using `pip3 install git+https://github.com/jupyterlab/jupyterlab.git@v1.0.0a3`.

**Comment by DarricauVert** [comment]
> It seems as though `pip install -U jupyterlab` still grabs the 0.35.6 release, not 1.0. I had to manually install the latest tagged release from github using `pip3 install git+https://github.com/jupyterlab/jupyterlab.git@v1.0.0a3`.

Hi Welchr,
this worked perfectly! Thank you very much for the help. I really appreciate it.

**Comment by jakevdp** [comment]
Sorry about that... I should update the docs.

You're correct that since JupyterLab 1.0 is still a pre-release, you need a special pip invocation. I'd recommend the following:
```
python -m pip install -U --pre jupyterlab
```

**Comment by jakevdp** [comment]
Updating docs in #1492; it will be live on the website with the next release.
