### ISSUE TITLE
Violin plots?

### ISSUE THREAD

**Issue by wmayner** [altair-viz/altair#1494]
Now that boxplots are available in v3 (thank you!), perhaps the next step is to add support for violin plots?

They appear to be [available in Vega](https://vega.github.io/vega/examples/violin-plot/), but not Vega-Lite.

**Comment by jakevdp** [comment]
Violin plots require a KDE transform, which does not yet exist in Vega-Lite, which means it cannot be used in Altair.

I've heard that the Vega-Lite team is aiming to add the KDE transform to Vega-Lite in the next release, at which point they will be possible to create in Altair.

**Comment by romainmartinez** [comment]
Related to vega-lite [#3442](https://github.com/vega/vega-lite/issues/3442).

**Comment by wmayner** [comment]
Thank you for 4.0! I'm trying out the new violin plot example. I'm a bit confused about how to achieve this without using facets. I want to make a faceted set of violin plots, but in the example the faceting mechanism is used to make a violin plot for each category, so I can't use the faceting mechanism for my own purposes.

I guess what I'm looking for is something like the [boxplot example](https://altair-viz.github.io/gallery/boxplot.html), but with violins instead of boxes. Seems that this might depend on vega/vega-lite#3442.

Is there a workaround we can use in the meantime?

**Comment by jakevdp** [comment]
I don't know of any way to make multiple violin plots without faceting.

**Comment by binste** [comment]
It is also my understanding that multiple violin plots currently require faceting. Support for better support for Violin plots is already tracked in https://github.com/vega/vega-lite/issues/3442. Once that is implemented, we can update the Altair example as tracked in #1529.
