### ISSUE TITLE
Heatmap fails to display range of data

### ISSUE THREAD

**Issue by fonnesbeck** [altair-viz/altair#1495]
Building a heatmap of continuous data fails to correctly encode the correct colors. The legend shows the range of the data, but only the color for zero values are displayed:

![](https://d.pr/i/puzyGr+)

Running version 2.4.1 on Python 3.7.3.

**Comment by Alcampopiano** [comment]
Are you able to post a short snippet of the actual data so it is easier to reproduce by copying and pasting? Screenshots are somewhat harder to deal with.

Perhaps you could try specifying an ordinal data type for your coordinates:

```python
alt.Chart(source).mark_rect().encode(
    x='x:O',
    y='y:O',
    color='z:Q'
)
```

That is just a guess, but give it a whirl.

Al

**Comment by fonnesbeck** [comment]
Yeah, that was it. Sorry to bother you.

**Comment by Alcampopiano** [comment]
Never a bother! Take care.
