### ISSUE TITLE
Support in papermill

### ISSUE THREAD

**Issue by dwanneruchi** [altair-viz/altair#1502]
Firstly, Altair is awesome! Trying to get it to work with papermill & jupyter notebooks and running into some issues: 

Unsure if this is the proper way to ask this question, but I have some visualizations done in matplotlib that take different parameters and work with papermill (I can run a script to create various versions of a main notebook with slight shifts in the mean / std used in a plot of the normal distribution for example). 

I have been trying to replicate the papermill run using Altair (altair==3.0.1) but not able to get an actual output. The process runs without any error, but the final image is not showing in the output notebooks. I did include alt.renderers.enable('notebook').

Below is an example of the basic code I have tried: 

```
# top cell for params
x_marker = "petalLength"

# next cell 
import altair as alt
alt.renderers.enable('notebook')
from vega_datasets import data

# ensure injected-params work 
print(x_marker)

# final cell
iris = data.iris()

alt.Chart(iris).mark_point().encode(
    x=x_marker,
    y='petalWidth',
    color='species'
)
```
I then run the following in CL:
```
papermill papermill_altair_test.ipynb pmill_alt_out.ipynb -p x_ma
rker "sepalLength"
```
While it builds a notebook w/ proper parameter the image does not render and I just receive `<vega.vegalite.VegaLite at 0xd793930>`

I know in the documentation it states this could mean I need `alt.renderers.enable('notebook')`, which I have already included. 

Just curious if this is expected behavior or if I might be missing a step?

**Comment by jakevdp** [comment]
That representation is the basic Python ``__repr__`` of the chart, and indicates that the frontend you're viewing it in is not set up to recognize Altair outputs and execute the appropriate javascript to render them. You'll have to figure out what mechanism papermill uses to execute Javascript, and somehow set it up so that Altair outputs trigger that.  I don't know anything about papermill, so I can't offer any concrete suggestions of how to start.

**Comment by Alcampopiano** [comment]
@dwanneruchi 

Papermill works for me in Jupyterlab with the following setup:

Altair version: 3.0.1
Jupyterlab version: 1.0.0a3

AFAIK you must use the following command to get pre-release of JL [at the moment](https://github.com/altair-viz/altair/issues/1491):
```
python -m pip install -U --pre jupyterlab
```

Then, as you may know, you have to set cell's metadata with a "parameters" tag, as follows:

![sc](https://user-images.githubusercontent.com/4624246/57573389-0899f500-73f5-11e9-9340-93d861d3161a.png)

Within a module (or using the CLI), call Papermill to execute the template notebook with the parameterization:

```python
import papermill as pm

pm.execute_notebook(
   'papermill_template.ipynb',
   'papermill_target.ipynb',
   parameters=dict(x_var='Horsepower')
)
```

After that, the target notebook is created and the Altair charts are render as expected.

Al

**Comment by dwanneruchi** [comment]
@Alcampopiano  - this worked perfectly, thank you!

**Comment by dwanneruchi** [comment]
@Alcampopiano - sorry to bother again, but have you noticed weird behavior when pushing to git? Maybe I will just save everything as an HTML in the end, but I ran the process you described above and the notebook created ('papermill_target.ipynb') has the image properly rendered. 

When I push to git 'papermill_template.ipynb' has a plot showing up, but 'papermill_target.ipynb' does not. Really interesting, have you seen this behavior?

I will investigate a bit and post back if I can figure out what is happening.

**Comment by jakevdp** [comment]
Do you mean the static PNG of the plot in the github notebook preview, or something else?

**Comment by dwanneruchi** [comment]
Apologies for the delay @jakevdp - specifically I mean when I push a .ipynb file to github. For whatever reason the file itself has the plot properly rendered when I look in jupyter lab, but when I then commit to git the plot does not render and I get an error. 

Here is the jupyter lab view:  pmill_alt_sepalLength.ipynb is the output notebook. The renderer is set to default (which seems to be appropriate for jupyter lab). 

![image](https://user-images.githubusercontent.com/12676672/57665053-118af200-75c0-11e9-9801-b7d520b54ab3.png)

I then pushed this notebook to git: 

![image](https://user-images.githubusercontent.com/12676672/57665162-721a2f00-75c0-11e9-9df9-5d077367a0e6.png)

In the troubleshooting portion of Altair it looks like this issue usually stems from either: 

- Version of Altair older than 2.0
- Not having the proper renderer enabled. 

Neither of these seems to be the issue in this case, but perhaps there is something I need to do on the Github side?

Thanks again for all of your help!

**Comment by jakevdp** [comment]
Github cannot render javascript. For this reason, the JupyterLab renderer and the notebook renderer also embed a static PNG of the chart along with the dynamic output. I suspect that whatever papermill is doing to the output, it is not passing along this PNG.

**Comment by RoyalTS** [comment]
Sorry to be opening up old cans of worms but using `papermill=2.3.3` and `altair=4.1.0` I'm getting empty output cells in jupyter lab. Do I have to declare any particular renderer to make this work?

**Comment by jakevdp** [comment]
I'm not sure. The person who would be able to answer this would have to be familiar with both altair and papermill, and I don't know if that person exists.

**Comment by jakevdp** [comment]
Maybe you should become that person 😀

**Comment by RoyalTS** [comment]
I have _just_ become that person! Apparently adding `alt.renderers.enable('mimetype')` to the notebook and then running papermill over it will make altair plots visible in the output notebook in Jupyter Lab.

**Comment by Aylr** [comment]
@RoyalTS Thank you for digging in, discovering an existing solution and most importantly posting it! Cheers!

**Comment by RoyalTS** [comment]
Hmm, this turned out to only be a partial solution. When I compile notebooks using papermill using `alt.renderers.enable('mimetype')` and then push notebooks to github and look at the notebooks through the github web UI the altair plots are lost and I see this instead:

```
<VegaLite 4 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html
```

If I just compile the same notebook, also with `alt.renderers.enable('mimetype')`, in Jupyter Lab the plots are visible in the github web UI (rendered to png on the fly, it seems like?).

**Comment by RoyalTS** [comment]
... and if it helps to diagnose: I see the same thing if I skip papermill and go with `nbconvert`.
