### ISSUE TITLE
Brushing breaks when columns are named x and y

### ISSUE THREAD

**Issue by hannahburkhardt** [altair-viz/altair#1503]
In altair 3.0.1, Brush selection seems to break if my dataframe columns are titled "x" and "y". This works correctly in altair 2.4.1.
Here's what my data looks like:
```python
embedding.head()
```

|	|x|	y|	cluster|
|----|----|----|----|
|0|	-0.800567|	-2.932704|	1|
|1|	-0.063906|	9.419857	|0|
|2|	14.998788|	-4.286201|	0|
|3|	4.394603|	2.290342	|3|
|4|	2.756407|	-5.969435	|0|

The following code shows the issue (only in altair 3.0.1):
```python
brush = alt.selection_interval()

scatter = alt.Chart(
    embedding
).mark_circle().encode(
    alt.X('x'), 
    alt.Y('y'), 
    color=alt.condition(brush,'cluster:N',alt.value('lightgray')),
    opacity=alt.value(0.3)
).add_selection(
    brush
)

scatter
```
![image](https://user-images.githubusercontent.com/4624654/57587431-94755500-74b9-11e9-8ede-64162d639285.png)

If I rename the columns to "one" and "two" it starts working:
![image](https://user-images.githubusercontent.com/4624654/57587449-bff83f80-74b9-11e9-9618-9fbf19de38e3.png)

It also works if I remove the brush selection.

**Comment by jakevdp** [comment]
This looks like a Vega-Lite bug. Have you opened an issue there?

**Comment by jakevdp** [comment]
([here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEC2CGBOBrSAuKBjAlvdAbAppADThT4B26A9gCabkDmqYoEEk1uV8zrb7AN1i4AroTSRcmBgAsALg3iwAnsVL8OVcnTmYtvdfyhzlAB3FRyVaPWFqjbSADNM+XDWYdRAZzn4eJA7s3m746Lr6EiEE4dwADHEATJCGEAC+hmmBjgAevJAm5p4AjiKw5LpysLoChERQLm4eEnlZhpCqaMAFZhaQpeWV1Zi1xA2u7p6qGenZkNFhEeT5C7HwCcldPUUS9H7wQriQaW3sNNWwBhqHYt7MANqpLJB5aHH1HczvGD77ngCCx2y-G6rzAAEYPp0IR88CJfP4AUCnqDmIkoWjYb9ERJAacjKi0ABmDHErHwv4SABCyIchLAABZSYzyQieNTaQSXswAKzMvk-Ck4qA0mZsAC6pAyaSAA) is a reproduction in the vega editor)

**Comment by hannahburkhardt** [comment]
I have not, but when I went to do this today, I saw that it has already been reported. Closing this since it's a vega lite bug, which has already been reported there ([issue #4951](https://github.com/vega/vega-lite/issues/4951)) Thanks jakevdp!

**Comment by domoritz** [comment]
Fixed in Vega-Lite.
