### ISSUE TITLE
Using argmax in encode()

### ISSUE THREAD

**Issue by yoonghm** [altair-viz/altair#1506]
I checked the documentation for `alt.X()` and `alt.Y()`, I do not find a way to pass field name to the `argmax` aggregation function.  In other words, how do you generate the following Vega-Lite specification? Thanks.

    {
      "data": {"url": "data/movies.json"},
      "mark": "bar",
      "encoding": {
        "x": {"aggregate": {"argmax": "US_Gross"}, "field": "Production_Budget", "type": "quantitative"},
        "y": {"field": "Major_Genre", "type": "nominal"}
      }
    }

**Comment by yoonghm** [comment]
I could do generate the equivalent Vega-Lite JSON file 

See Argmix/Argmax from https://vega.github.io/vega-lite/docs/aggregate.html#argmin--argmax:

    {
      "data": {"url": "data/movies.json"},
      "transform": [{
        "aggregate": [{"op": "argmax", "field": "US_Gross", "as": "argmax_US_Gross"}],
        "groupby": ["Major_Genre"]
      }],
      "mark": "bar",
      "encoding": {
        "x": {"field": "argmax_US_Gross.Production_Budget", "type": "quantitative"},
        "y": {"field": "Major_Genre", "type": "nominal"}
      }
    }

using the following code:

    import altair as alt
    from vega_datasets import data

    alt.Chart(data.movies.url).mark_bar().transform_aggregate(
        groupby=['Major_Genre'],
        argmax_US_Gross='argmax(US_Gross)'
    ).encode(
        x=alt.X('argmax_US_Gross.Production_Budget:Q'),
        y=alt.Y('Major_Genre:N')
    )

**Comment by jakevdp** [comment]
There is no shorthand syntax for aggregates that take an extra argument, but you can reproduce the spec like this:
```python
import altair as alt

alt.Chart('data/movies.json').mark_bar().encode(
    x=alt.X('Production_Budget:Q', aggregate={'argmax': 'US_Gross'}),
    y='Major_Genre:N'
)
```
