### ISSUE TITLE
Projection's type should be case-insensitive but is not

### ISSUE THREAD

**Issue by kannes** [altair-viz/altair#1510]
https://altair-viz.github.io/user_guide/generated/core/altair.Projection.html#altair.Projection says its `type` parameter is case-insensitive:

`This value is case-insensitive, for example "albers" and "Albers" indicate the same projection type.`

This is not true.

For example trying to use `type="Albers"` will result in the following error:

```
SchemaValidationError: Invalid specification

        altair.vegalite.v3.schema.core.Projection->type, validating 'enum'

        'Albers' is not one of ['albers', 'albersUsa', 'azimuthalEqualArea', 
'azimuthalEquidistant', 'conicConformal', 'conicEqualArea', 'conicEquidistant', 
'equirectangular', 'gnomonic', 'identity', 'mercator', 'orthographic', 'stereographic', 
'transverseMercator']
```

**Comment by joelostblom** [comment]
This should be updated in the Vega-Lite documentation/docstring to indicate that only lower case is allowed or in the schema to allow upper case (it currently works but the schema flags it as an error). Closing it here since there is nothing to do from the altair side of things.
