### ISSUE TITLE
Slow rendering. Lazy loading possible?

### ISSUE THREAD

**Issue by MarshallCharles** [altair-viz/altair#1511]
Hello,

Rendering a large dataframe is quite slow. I'm experimenting with a pipeline to take local data files, as well as some input, and map it using Altair in a browser environment.

These dataframes are rather large and the plots take quite a long time to render. Are there any suggested ways to implement lazy loading with altair. I'll show you an example below.

With something like this, could I sample "data" (a pandas dataframe), and render my plot "a" immediately, and then without redoing any computation, update my plot "a" as I include larger and larger subsets of my dataframe?
![image](https://user-images.githubusercontent.com/49293173/57852219-e3d1c300-77e2-11e9-81b7-a0eb8afb0e94.png)

Thank you!

**Comment by jakevdp** [comment]
Unfortunately no, there's no easy way to do lazy loading. Large datasets are one of the weak points of the current Vega-Lite implementation, though there is some work going on to alleviate that.

You might be able to put something together based on Vega-Lite's [streaming data model](https://vega.github.io/vega-lite/tutorials/streaming.html) along with something like [Altair data server](https://github.com/altair-viz/altair_data_server/), but I think it would take a fair bit of effort.
