### ISSUE TITLE
Values list passed to alt.Axis are ignored / filtered when figure is small?

### ISSUE THREAD

**Issue by trllrgn** [altair-viz/altair#1518]
I am trying to manually set the x tick labels (i.e. alt.Axis values) that are displayed on an altair figure.
If the figure is wide enough, then the following code works fine. But if the width is limited, altair overwrites my custom settings, probably to make the figure look "nicer". 

Is there a way to suppress this behaviour? Thanks.

```
# many data points
wdate = pd.date_range(end='2019-04-10', periods=75, freq='W-SUN')
vals = np.random.randn(75)
df = pd.DataFrame({'date':wdate,'vals':vals})

# show only monthly x tick labels
xticks_daterange = pd.date_range(end='2019-04-10', periods=12, freq='MS')
xticks = list(xticks_daterange.astype(int)/10**6)
print('Expected x tick labels: \n',xticks_daterange.strftime("%b %Y"))

# correctly displays labels if figure is large enough
chart = alt.Chart(df,width=600).mark_line().encode(
    x=alt.X('date:T',axis=alt.Axis(values=xticks, format = ("%b %Y"))),
    y=alt.Y('vals:Q')
)
display(chart)

# displays every second label only if figure is "small"
chart = alt.Chart(df,width=350).mark_line().encode(
    x=alt.X('date:T',axis=alt.Axis(values=xticks, format = ("%b %Y"))),
    y=alt.Y('vals:Q')
)
display(chart)
```

**Comment by jakevdp** [comment]
By default Altair tries to prevent labels from overlapping by removing them if they are too close together. If you would like to disable this, you can set ``labelOverlap=False`` within ``alt.Axis``:

```python
alt.Chart(df,width=600).mark_line().encode(
    x=alt.X('date:T',axis=alt.Axis(values=xticks, format = ("%b %Y"), labelOverlap=False)),
    y=alt.Y('vals:Q')
)
```
![visualization (23)](https://user-images.githubusercontent.com/781659/58110092-b3ec3c00-7ba3-11e9-831d-79deb2c597b9.png)

**Comment by trllrgn** [comment]
Thanks for the suggestion!

I made a mistake in the dummy code I've written yesterday as I forgot to add the label rotation. So I'm not trying to make the labels overlap, just trying to make them more frequent :)

Unfortunately I couldn't get your code to work. Any chance that setting the labelAngle parameter somehow interferes with labelOverlap=False? Otherwise, can this be an issue with running it in a Jupyter notebook?

Thanks a lot for your help, it is greatly appreciated!

```
import pandas as pd
import numpy as np
import altair as alt
alt.renderers.enable('notebook');

# many data points
wdate = pd.date_range(end='2019-04-10', periods=75, freq='W-SUN')
vals = np.random.randn(75)
df = pd.DataFrame({'date':wdate,'vals':vals})

# show only monthly x tick labels
xticks_daterange = pd.date_range(end='2019-04-10', periods=12, freq='MS')
xticks = list(xticks_daterange.astype(int)/10**6)
print('Expected x tick labels: \n',xticks_daterange.strftime("%b %Y"))

# correctly displays labels if figure is large enough
chart = alt.Chart(df,width=600).mark_line().encode(
    x=alt.X('date:T',axis=alt.Axis(values=xticks, labelAngle=-45, labelOverlap=False, format = ("%b %Y"))),
    y=alt.Y('vals:Q')
)
display(chart)

# displays every second label only if figure is "small"
chart2 = alt.Chart(df,width=400).mark_line().encode(
    x=alt.X('date:T',axis=alt.Axis(values=xticks, labelAngle=-45, labelOverlap=False, format = ("%b %Y"))),
    y=alt.Y('vals:Q')
)
display(chart2)
```
![image](https://user-images.githubusercontent.com/42297802/58113870-d0fe2a80-7bf6-11e9-99d1-b6ab0bcdd6c1.png)
