### ISSUE TITLE
labelAngle property ignored in jupyterlab?

### ISSUE THREAD

**Issue by trllrgn** [altair-viz/altair#1526]
I have written a code in jupyter notebook, similar to the simplified dummy code below. In jupyter notebook this works fine, however, it doesn't rotate the label when I try to use the same code in jupyterlab (the only difference being the enable notebook renderer line).

I have also observed in a different example that I created a ['date', 'value'] tooltip which worked fine in the notebook, but the 'date' part was left empty in jupyterlab.

My jupyterlab version is 0.35.5. Any help would be greatly appreciated. 

```
import pandas as pd
import numpy as np
import altair as alt
alt.renderers.enable('jupyterlab');

wdate = pd.date_range(end='2019-04-10', periods=75, freq='W-SUN')
vals = np.random.randn(75)
df = pd.DataFrame({'date':wdate,'vals':vals})

xticks_daterange = pd.date_range(end='2019-04-10', periods=12, freq='MS')
xticks = list(xticks_daterange.astype(int)/10**6)

chart = alt.Chart(df,width=600).mark_line().encode(
    x=alt.X('date:T',axis=alt.Axis(values=xticks, 
                                   labelAngle=-45, 
                                   labelOverlap=False, 
                                   format = ("%b %Y"))),
    y=alt.Y('vals:Q')
)
display(chart)
```

**Comment by jakevdp** [comment]
This appears to be an issue with Altair 2.X.

Update to Altair version 3 to fix the issue (note that this will require a newer version of JupyterLab if you are using that frontend).

**Comment by trllrgn** [comment]
I am a bit confused by Altair 3.0.1 as I get the <VegaLite 3 object> error and the troubleshooting page suggests using JupyterLab 1.0 or newer and asks us to update jupyterlab using conda update. However, conda update only updates to 0.35.6 and version 1.0 does not seem to be ready yet.

Is this a combination that will only work in future or am I missing something?

**Comment by jakevdp** [comment]
Yes, you need to jupyterlab 1.0 pre-release if you want to use the current version of Altair with JupyterLab.
