### ISSUE TITLE
How to display in legend which Y axis curves are plotted to?

### ISSUE THREAD

**Issue by trllrgn** [altair-viz/altair#1528]
I have a chart with several curves and two independent Y axes, each with 2 curves on it. When I generate a legend, a single legend is displayed where all the curves are listed. See figure below.

However, this way the user has no way to know which Y axis each curve is plotted on. Is there a way to have two separate legends, E.g. "Left Legend" and "Right Legend"? I tried just giving different titles to the legend definitions, but this just made a single legend with a list of legend titles. Thanks.

![image](https://user-images.githubusercontent.com/42297802/58264066-7e02af80-7d7d-11e9-9061-e8f460c879ea.png)

**Comment by jakevdp** [comment]
I think ``chart.resolve_legend(color='independent')`` will do what you want. If not, it would be helpful for you to post example code.

**Comment by joelostblom** [comment]
@trllrgn I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
