### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by deep-fried-bacon** [altair-viz/altair#1530]
So this is a super small thing, but it did cause me some frustration and should be easy to fix.

On the saving_charts page in the user_guide [[doc]](https://altair-viz.github.io/user_guide/saving_charts.html)[[github]](https://github.com/altair-viz/altair/blob/master/doc/user_guide/saving_charts.rst),
it says you need to install chromedriver or geckodriver
and that you can use hombrew on OSX:

      $ brew install chromedriver
      $ brew install geckodriver

but to install chromedriver with brew you need to use cask

      $ brew cask install chromedriver
      $ brew install geckodriver

(I did double check geckodriver and it's fine as is)

**Comment by eitanlees** [comment]
Pull requests are welcome!
