### ISSUE TITLE
configure_legend() parameters don't seem to be working 

### ISSUE THREAD

**Issue by ashutosh29** [altair-viz/altair#1532]
Hi,

I am trying to create Heatmaps with Altair.

So far so good. 

With default settings, the visualization is 

![visualization](https://user-images.githubusercontent.com/13638740/58316113-77814000-7e30-11e9-93e1-a675cd24c1e7.png)

The code for above visualisation is 

```python
data = (pd.DataFrame({'a': [1,2,3], 'b': [-1.1111111, -2, -3]}, index=['index1', 'index2', 'index3'])
        .stack()
        .to_frame('tstat')
        .reset_index()
       )

c1  =  alt.Chart(data).mark_rect().encode(
 x = alt.X('level_1',  axis = alt.Axis(title = None)), 
 y = alt.Y('level_0',  axis = alt.Axis(title = None)), 
 color = alt.Color('tstat'), 
 tooltip = 'tstat'
).properties(width = 200,  height = 200)

c2  =  alt.Chart(data).mark_text(color = 'white',  baseline = 'middle').encode(
 x = alt.X('level_1',  axis = alt.Axis(title = None)), 
 y = alt.Y('level_0',  axis = alt.Axis(title = None)), 
 text = alt.Text('tstat',  format = '.2r'), 
).properties(width = 200,  height = 200)

(c1+c2).configure_legend(
    gradientLength=100,
    gradientThickness=10
) 

```

Now what I am trying to achieve is the Legend location to be "Bottom" and Gradient Direction to be "Horizontal". Something like below:

![visualization (1)](https://user-images.githubusercontent.com/13638740/58316300-d5158c80-7e30-11e9-88a0-d9174f8832b5.png)

But adding parameters according to `https://altair-viz.github.io/user_guide/generated/toplevel/altair.Chart.html#altair.Chart.configure_legend` doesn't work.

So, below code with addition parameter in ```configure_legend ``` doesn't show any effect.

```python
c1  =  alt.Chart(data).mark_rect().encode(
 x = alt.X('level_1',  axis = alt.Axis(title = None)), 
 y = alt.Y('level_0',  axis = alt.Axis(title = None)), 
 color = alt.Color('tstat'), 
 tooltip = 'tstat'
).properties(width = 200,  height = 200)

c2  =  alt.Chart(data).mark_text(color = 'white',  baseline = 'middle').encode(
 x = alt.X('level_1',  axis = alt.Axis(title = None)), 
 y = alt.Y('level_0',  axis = alt.Axis(title = None)), 
 text = alt.Text('tstat',  format = '.2r'), 
).properties(width = 200,  height = 200)

(c1+c2).configure_legend(
    gradientLength=100,
    gradientThickness=10,
    gradientDirection ='horizontal'  #<<<<<<<<<
)

```

Suggestions, help appreciated.

**Comment by jakevdp** [comment]
To orient the legend at the bottom of the chart, use ``orient='bottom'``. For example:
```python
(c1+c2).configure_legend(
    gradientLength=200,
    gradientDirection ='horizontal',
    orient='bottom'
)
```
![visualization (98)](https://user-images.githubusercontent.com/781659/58338734-2a37ab00-7dfd-11e9-8ce7-f39e2721a15a.png)

**Comment by ashutosh29** [comment]
Perfect, thanks.

**Comment by ashutosh29** [comment]
It doesn't seem to be working in my notebook. Weird 

```python
(c1+c2).configure_legend(
    gradientLength=200,
    gradientDirection ='horizontal',
    orient='bottom'
)
```
![visualization (2)](https://user-images.githubusercontent.com/13638740/58396814-d383d880-806b-11e9-9049-b8c91eb26957.png)

My Altair Version is :
'3.0.1'

**Comment by jakevdp** [comment]
I suspect you have an older version of the Vega-Lite javascript libraries in your frontend. Are you using Jupyter notebook or JupyterLab?

**Comment by ashutosh29** [comment]
Here are few packages in my Anaconda Environment
```
altair                    3.0.1                    py36_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter_client            5.2.4                      py_1    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyterlab                0.35.4                   py36_0    conda-forge
jupyterlab                1.0.0a3                   <pip>
jupyterlab-server         0.3.0                     <pip>
jupyterlab_launcher       0.10.5                   py36_0    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
notebook                  5.7.8                    py36_0    conda-forge
python                    3.6.6                he025d50_0    conda-forge
vega                      2.1.0                    py36_0    conda-forge
vega_datasets             0.7.0                      py_0    conda-forge

```

**Comment by jakevdp** [comment]
Thanks for the info.

I think that the version of vega-lite bundled with JupyterLab 1.0.0a3 is slightly older than the newest release, and so it is not rendering the chart correctly. Unfortunately, there's not any easy way to see what actual version of the vega frontend is actually installed. Perhaps @domoritz could confirm.

Once https://github.com/jupyterlab/jupyterlab/issues/6403 is fixed this will be easier to address without reinstalling your entire JupyterLab frontend.

**Comment by domoritz** [comment]
We don't have a good way to see the Vega or Vega-Lite version from Python yet. I hope that [soon we can just make a Vega 5 package and install it in parallel](https://github.com/jupyterlab/jupyterlab/issues/6403#issuecomment-496728899).

**Comment by ashutosh29** [comment]
@jakevdp @domoritz thanks for your replies. I think I should roll back to Altair 2.x for now till these issues are sorted.

**Comment by jakevdp** [comment]
>  I think I should roll back to Altair 2.x

I'd discourage that. Every shortcoming of the 3.0 JupyterLab renderer mentioned above is also present in 2.X, and 3.0 does have numerous improvements over 2.X.

If you want to use Altair in an environment where the frontend renderer is always exactly in-sync  with the backend, I'd suggest trying [Colab](http://colab.research.google.com).

**Comment by domoritz** [comment]
We also just resolved https://github.com/jupyterlab/jupyterlab/issues/6403. 

you can also use the `vega` package with the jupyter notebook or Colab.

**Comment by jakevdp** [comment]
This will work with the most recent version of the vega5 jupyterlab extension.
