### ISSUE TITLE
Renderer not working on fresh install

### ISSUE THREAD

**Issue by Marcelo-Lemos** [altair-viz/altair#1534]
Hello, I just installed Altair with JupyterLab by following the quick start guide, but I'm having trouble rendering the plot. I get the following message:

```
<VegaLite 3 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html
```

I tried updating the JupyterLab version as the troubleshooting page suggested (`conda update jupyterlab`), but nothing changed. I'm still getting the same result when I try to render anything.

`jupyter lab --version` shows my current JupyterLab version is 0.35.4. I have no idea what I have done wrong or how I can fix it. Any help would be appreciated.

**Comment by jakevdp** [comment]
You need to install jupyterlab 1.0.0a3

**Comment by Marcelo-Lemos** [comment]
Thanks for the response, but I don't know how to do that. `conda install -c conda-forge jupyterlab` and `conda update jupyterlab` just tell me the package is already installed. Can you point me any guide that explains how to install it?

**Comment by Alcampopiano** [comment]
Hi there,

You can get the pre-release of JL with the following command:

'''python -m pip install -U --pre 
jupyterlab'''

Apologies if the code formatting doesn't show up, I'm on my phone.

**Comment by Marcelo-Lemos** [comment]
Thank you! That solved it.

**Comment by jakevdp** [comment]
Sorry for the unhelpful docs. I published them thinking that Jupyterlab 1.0 was imminent, but the release schedule has been slower than I anticipated. This has actually been fixed in the source for a while: https://github.com/altair-viz/altair/blob/master/doc/user_guide/troubleshooting.rst#jupyterlab-vegalite-3-object but I haven't had a chance to push a new doc build yet.

**Comment by alimcmaster1** [comment]
@jakevdp - thanks! This isn't particularly obvious - hopefully they release soon! Also how do you currently push your doc builds. pandas has started doing it as part of an azure pipeline publishing to github pages https://github.com/pandas-dev/pandas/pull/26591/files perhaps altair could do the same to keep docs up to date what do you think?

**Comment by jakevdp** [comment]
It's harder to do that because Altair doc builds require selenium to generate the gallery thumbnails, and I've not had any success getting that working on any of the doc generation services.
