### ISSUE TITLE
Move x-axis to y-axis zero.

### ISSUE THREAD

**Issue by robertodr** [altair-viz/altair#1536]
First of all, thanks for this fantastic library! I've only recently started using it and I like it much more than other tools I've used so far.

In the [Line Chart with Points example](https://altair-viz.github.io/gallery/line_chart_with_points.html), is it possible to move the x-axis to the zero of the y-axis? And if yes, how? I've searched in the docs, but I can't find any hints. Thanks in advance!

**Comment by Alcampopiano** [comment]
Hi there,

Are asking how to adjust the axis limits?

If so, would this work for you:

```python
import altair as alt
import numpy as np
import pandas as pd

x = np.arange(100)
source = pd.DataFrame({
  'x': x,
  'f(x)': np.sin(x / 5)
})

alt.Chart(source).mark_line(point=True, clip=True).encode(
    x='x',
    y=alt.Y('f(x)', scale=alt.Scale(domain=[0, 1]))
)
```
![visualization (6)](https://user-images.githubusercontent.com/4624246/58485986-0c3ab500-8133-11e9-885a-03b16aa9ed81.png)

If this is what you are looking for, you can find more information [here in the docs](https://altair-viz.github.io/user_guide/customization.html?highlight=domain#adjusting-axis-limits)

**Comment by robertodr** [comment]
Not quite. I want to keep the `y < 0` plot (grid, line, points), but have the x axis in the position your plot shows.

```
import altair as alt
import numpy as np
import pandas as pd

x = np.arange(100)
source = pd.DataFrame({
  'x': x,
  'f(x)': np.sin(x / 5)
})

line = alt.Chart().mark_line(point=True).encode(
    x='x',
    y='f(x)', #alt.Y('f(x)', scale=alt.Scale(domain=[0, 1]))
)

hline = alt.Chart().mark_rule().encode(y='a:Q')

alt.layer(line, hline, data=source).transform_calculate(a="0")
```
This one gets the a line there, but the actual x axis stays at the bottom.
![visualization](https://user-images.githubusercontent.com/3708689/58487104-59387e80-8167-11e9-9dbb-29a74a8cf04a.png)

**Comment by Alcampopiano** [comment]
Hmm, good question. You could try something like this:

```python
import altair as alt
import numpy as np
import pandas as pd

x = np.arange(100)
source = pd.DataFrame({
  'x': x,
  'f(x)': np.sin(x / 5)
})

alt.Chart(source).mark_line(point=True).encode(
    x='x',
    y=alt.Y('f(x)')
).configure_axisX(labelPadding=-150)
```

![visualization (7)](https://user-images.githubusercontent.com/4624246/58488580-9a189f00-8137-11e9-92f7-95b5674e2545.png)

Perhaps there is something else that might help in the [axis config section](https://altair-viz.github.io/user_guide/configuration.html#config-axis) of the docs

**Comment by jakevdp** [comment]
A better way of doing this is with the axis ``offset`` property:
```python
import altair as alt
import numpy as np
import pandas as pd

x = np.arange(100)
source = pd.DataFrame({
  'x': x,
  'f(x)': np.sin(x / 5)
})

alt.Chart(source).mark_line(point=True).encode(
    x=alt.X('x', axis=alt.Axis(offset=-150)),
    y='f(x)'
)
```

**Comment by robertodr** [comment]
Fantastic, thanks! Closing.
