### ISSUE TITLE
Candlestick gaps

### ISSUE THREAD

**Issue by holmesb** [altair-viz/altair#1545]
Candlesticks will often be used to plot financial time-series data.  This usually has no data at weekends.  Currently [Altair's candlestick chart](https://altair-viz.github.io/gallery/candlestick_chart.html#gallery-candlestick-chart) plots with gaps at weekends, which I've depicted using the red boxes below:

![image](https://user-images.githubusercontent.com/5072156/58747112-563ad800-845e-11e9-9780-0f2d94105383.png)

Would be better to plot continuously, with no gaps.

**Comment by jakevdp** [comment]
Temporal scales will always be continuous, and not skip data. If you want data to be skipped, you can use an ordinal scale by changing ``'yearmonthdate(date):T'`` to ``'yearmonthdate(date):O'`` in both places. The result looks like this:
![visualization - 2019-06-01T065957 165](https://user-images.githubusercontent.com/781659/58749430-dfd8ae80-843a-11e9-8482-d08263e07176.png)
