### ISSUE TITLE
hypen used instead of minus sign

### ISSUE THREAD

**Issue by kirkpsmith** [altair-viz/altair#1547]
When displaying negative numbers Altair uses a hyphen `-` instead of a minus sign `−` (unicode 2212). There should be an option (like [this one](https://matplotlib.org/gallery/api/unicode_minus.html) in matplotlib) to specify either option (but defaulting to the minus sign would be optimal).

**Comment by jakevdp** [comment]
Rendering is controlled by vega-lite, so this would be useful to report there.
