### ISSUE TITLE
Chart doesn't display, despite Mime representation enabled

### ISSUE THREAD

**Issue by miguelmorin** [altair-viz/altair#1550]
I have an issue similar to #809 and the solution described didn't work for me. Matplotlib can plot in Jupyter notebook. (I am using Jupyter notebook because Jupyter lab renders an empty page, or a page with only navigation headings, depending on the browser).

I use:

```
import altair as alt
from vega_datasets import data

alt.renderers.enable('notebook')
iris = data.iris()

alt.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species'
)
```

and the output is empty: `Out [1]: `

Other tests that I ran are:

```
import sys
print(sys.version)
# 3.7.3 (default, Mar 27 2019, 09:23:15) 
# [Clang 10.0.1 (clang-1001.0.46.3)]
print(sys.executable)
# /usr/local/opt/python/bin/python3.7

class Test(object):
    def _repr_mimebundle_(self, include, exclude):
        return {'text/plain': "Mimebundle Repr"}
    def __repr__(self):
        return "Normal Repr"
    
Test()
# Mimebundle Repr

import IPython
IPython.__version__
# '7.5.0'
```

**Comment by jakevdp** [comment]
What version of the vega package do you have installed?
```
import vega; print(vega.__version__)
``
This is the package that provides the notebook renderer, and if you're using Altair v3 you will need vega version 2.1.0.

**Comment by miguelmorin** [comment]
I have Vega `2.1.0`. When I relaunched `jupyter notebook` just now (after a few hours) and opened the notebook without computation, the graphics were there, even though they were absent when I quit the notebook. So the graph was computed and rendered, but maybe the Jupyter front-end did not show it.

**Comment by jakevdp** [comment]
If it fails to show again, can you open the Javascript console and share any errors that you see?

**Comment by miguelmorin** [comment]
I tried it again and it is showing fine. I will look at the Javascript console and report the errors there next time.

**Comment by bendoesdata** [comment]
I think I'm experiencing a similar issue here. When running the test code for display, I get any empty output:

```
import altair as alt
from vega_datasets import data

alt.renderers.enable('notebook')
iris = data.iris()

alt.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species'
)
```
and the output is empty: Out [1]:

There is no VegaLite error message so I couldn't find any troubleshooting help on the Altair docs.

Within Chrome developer mode, I see the following error:

```
Failed to load resource: http://localhost:8888/static/@jupyter-widgets/base.js?v=20190614101855the server responded with a status of 404 (Not Found)
```

This is followed by an additional error:

```
Script error for "@jupyter-widgets/base", needed by: nbextensions/jupyter-vega/index
```

I have checked and reinstalled nbextensions in my virtual env using conda. However, at the bottom of the console is a warning message:

```
Widgets are not available.  Please install widgetsnbextension or ipywidgets 4.0
```

I have installed Vega version 2.3.0 and Altair version 3.1.0. I have also tried to render in JupyterLab but I'm seeing the same empty output.

Any ideas why this is happening?

**Comment by jakevdp** [comment]
I think I know what's happening here... this is a new one.

The version 2.3 release of the [vega extension](https://github.com/vega/ipyvega/tree/master) added widget support, and also adds a javascript-side dependency on the jupyter widgets extension. For some reason when you installed vega 2.3, it didn't include the widgets extension. I don't have a great grasp of how notebook extension installation works, so I'm not sure how to debug that.

But I think if you downgrade the vega package to version 2.2 and then restart the jupyter notebook process, it should fix the issue for the time being
```
pip install vega==2.2
```
cc @domoritz

**Comment by bendoesdata** [comment]
Amazing, that did it! Thanks for the quick reply I was really spinning my wheels.

I uninstalled Vega and reinstalled with 2.2 which seemed to solve everything. No errors in the Console now and charts rendering normally. Will continue using 2.2 until any updates come out.

**Comment by domoritz** [comment]
I'm looking into this and will resolve the issue asap.

**Comment by domoritz** [comment]
Please follow https://github.com/vega/ipyvega/issues/105.

**Comment by domoritz** [comment]
Fixed in vega-2.3.2

**Comment by jakevdp** [comment]
Thanks!

**Comment by StevenLi-DS** [comment]
@domoritz are I missing something?
![image](https://user-images.githubusercontent.com/33796896/59972262-f960a800-9559-11e9-8820-a512ed403175.png)

**Comment by domoritz** [comment]
@StevenLi-DS ipyvega (vega in pypi) is not for jupyterlab. Please update jupyterlab to 1.0 instead.

**Comment by StevenLi-DS** [comment]
Is there any workaround? 1.0 doesn't seem like a [stable version](https://pypi.org/project/jupyterlab/#history)

**Comment by domoritz** [comment]
You can install https://github.com/jupyterlab/jupyterlab/releases/tag/%40jupyterlab%2Fvega5-extension%401.0.0-rc.0 but it requires node to be installed and might be more problematic than installing the latest 1.0rc of JL.

**Comment by StevenLi-DS** [comment]
Thx. I guess I just gotta Notebook for the time being. This's a little bit weird since I thought jupyter lab is pretty much like the default env of Altair.

**Comment by jakevdp** [comment]
Jupyter Lab is the recommended environment for Altair. Unfortunately, the JupyterLab release schedule is pretty drawn-out. We're trying to take steps to mitigate this kind of mismatch in the future, but it's pretty difficult given the constraints that the Jupyter ecosystem puts on any project that requires frontend extensions.

**Comment by jakevdp** [comment]
JupyterLab 1.0 has been released, so this should not be a problem now.

**Comment by basheerkafaf** [comment]
I am having the same problem 
![image](https://user-images.githubusercontent.com/61880491/78952999-a29a6f80-7a94-11ea-9265-ef3e98921a4d.png)

**Comment by tonylee3399** [comment]
Hi @basheerkafaf, I think this is related to the behavior of the IPython instead of Vega / Altair.

If you save an object, be it a `pd.DataFrame` or a `alt.Chart`, you need to explicitly call the variable where this object is stored to render it in IPython.

In your example, you could run a cell that contains only `chart` and run the cell to render.

![image](https://user-images.githubusercontent.com/16498167/78958753-9ad1de00-7b1b-11ea-9cda-eddba177feaf.png)

Or you can do it by explicitly call `IPython.display.display` method

```
from IPython.display import display
display(chart)
```

![image](https://user-images.githubusercontent.com/16498167/78958782-ab825400-7b1b-11ea-8638-7b2b1f72abea.png)

**Comment by jakevdp** [comment]
Relatedly, see https://altair-viz.github.io/user_guide/troubleshooting.html#chart-does-not-display-at-all

**Comment by basheerkafaf** [comment]
Thank you very much @jakevdp 
please find below what I am facing now.
![image](https://user-images.githubusercontent.com/61880491/79010504-55afab00-7b1f-11ea-8589-6d09830834af.png)

![image](https://user-images.githubusercontent.com/61880491/79010531-66602100-7b1f-11ea-8121-563edac65b17.png)

**Comment by tonylee3399** [comment]
Hi @basheerkafaf, how many rows of data does the `file` variable contain? Looking at the `CREATED_DATETIME` column, it seems to me that the data is taken every ten seconds which led me to assume this dataset is huge.

I'm not sure if the reason it shows nothing is because of trying to embed an enormous amount of JSON into the HTML.

Have you tried the `altair_data_server` solution? Reference: [link](https://altair-viz.github.io/user_guide/faq.html#local-data-server)

**Comment by basheerkafaf** [comment]
about 17k.
I usually use more than that.
I tried with the data server but it is the same.

![image](https://user-images.githubusercontent.com/61880491/79018633-8ac4f900-7b31-11ea-9a02-7fe110a825dc.png)

**Comment by jakevdp** [comment]
Vega-Lite doesn't really work well with that much data unfortunately. It's not surprising that it would crash when displaying 17,000 rows.

**Comment by basheerkafaf** [comment]
@jakevdp thank you very much!

**Comment by pratikkejriwal** [comment]
> 
> 
> I have Vega `2.1.0`. When I relaunched `jupyter notebook` just now (after a few hours) and opened the notebook without computation, the graphics were there, even though they were absent when I quit the notebook. So the graph was computed and rendered, and probably the Jupyter front-end did not show it.

I am using vega 2.3 and encountered the same issue. I tried a using IPython display but that didn't work for me and even I experienced that when I shutdown my kernel and reopen it, the graph is there but not while compiling. Although, **vega 2.2** seems to be working fine.
