### ISSUE TITLE
How to create a conditional multi-field tooltip

### ISSUE THREAD

**Issue by cwaldbieser** [altair-viz/altair#1552]
I can use a conditional for a tooltip encoding so that only points on my chart in a selection show a tool tip:

    tooltip=alt.condition(selection, "Subject", alt.value(''))

I can also make a tooltip with multiple fields:

    tooltip=['Subject', 'team', 'TicketType', 'HoursWorked']

But how do I create multi-field tooltips for only the points in the selection?  Using the python list of field names as the 2nd argument to alt.condition() raises an exception.

**Comment by jakevdp** [comment]
Multiple conditional values in one encoding are not allowed by the Vega-Lite spec.

There are other ways you could accomplish this, such as layering transparent points filtered on the selection, and tying the multiple tooltips to those; something like this:
```python
from vega_datasets import data
import altair as alt
cars = data.cars.url

selection = alt.selection_single(fields=['Origin'])

base = alt.Chart(cars).mark_point().encode(
  x='Horsepower:Q',
  y='Miles_per_Gallon:Q',
)

chart = base.encode(
  color=alt.condition(selection, 'Origin:N', alt.value('lightgray'))
).add_selection(
  selection
)

overlay = base.encode(
  opacity=alt.value(0),
  tooltip=['Origin:N', 'Name:N']
).transform_filter(
  selection
)

chart + overlay
```
([Try Result in Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgoS8QE8Ck0gG1DEUBHtRK46uLmQtkpaUg9qagM4YAPRBuASo4gB0qMh0WgBGkciwoeHiALROLv4E1P5BWeJB0FL+kQBW-giQBg4QYlKyWJBqsMjwvKw29pAE8HCU7ehYdnX1cEqwFiPdY3jiSloE3krc1KiSppBdYw4wCIOq1TO7dZDUJmrLzfCwou0L27O7kCgESpTeAPKSaO1Ppz2OSUBGgR3g3mBoIUkhYACZIM8HIIkWBai8AB5uC5XbwARy04g6sWcyDC2ygbw+3gAElMcq0iOYajsXiZsZdrlACUTVC5VOSRFTPs0ALLIEH+AD6V0kUoA4gtJhCUWN0UD3tDkhCRpAoWCpvCObjmv4hiCKa9CB9-FZID8-hCALr6brq7DPSCFNweLzNXwBYKpCLRWK0BJJFJhCKZZziHJ5Apx4qlCpVFWsvYSGTeVrtTqevoDIZyVGQWBqcTQWLs3W4BZLUhMd17BTKVQaLDWQFkHFcyC3e7wR5C60iqAOmIZ1G2c6c7yDh5eUfvceQABy4lEy1VuydmbOWN1ffxhOJ-LJyxX1OadMkDNgTIsLZ6td78+aPPPpMFlLH3nFSUZXMBUlWqXdkQPepqE2eB-EQKZRCsHAUBUZldX1cFIU1A1YSYBF9CdN1DH3QxIAAEn8aBOAkbwA0CEJoyiGI4kSZIgiomiiiY9JVmoAhQj4SI4UiABGNNqhAQQgA))

**Comment by cwaldbieser** [comment]
Thanks.  That works!

**Comment by joelostblom** [comment]
@cwaldbieser I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
