### ISSUE TITLE
"op" Method in SortField - for op='sum'? Is there such a thing?

### ISSUE THREAD

**Issue by Jaguar100** [altair-viz/altair#1557]
Hi Altair team. Love what you're doing. Thanks!

Trying to make a sort field create and sort on a cumulative sum in the bar chart on this page:
[https://pbpython.com/altair-intro.html]. Its' towards the bottom of the page just before the "JSON" section. 

I'm getting the following error message: 

> SchemaValidationError: Invalid specification
> 
>    altair.vegalite.v3.schema.core.SortField, validating 'additionalProperties'
> 
>         Additional properties are not allowed ('op' was unexpected)

Here is my code:
```
c = Chart(budget).mark_bar().encode(
    y=Y('category', sort=SortField(field='amount', op='sum', order='descending'),
        axis=Axis(title='Category')),
    x=X('sum(amount)',
         axis=Axis(title='2014 Budget')))
c
```

**Comment by jakevdp** [comment]
You should use ``alt.EncodingSortField`` rather than ``alt.SortField`` in this context, which allows ``op`` to be passed.

**Comment by Jaguar100** [comment]
Perfect! Thanks Jake.
