### ISSUE TITLE
Post aggregation calculations

### ISSUE THREAD

**Issue by trubens71** [altair-viz/altair#1560]
Is there a way to perform calculations on aggregate fields? In this trivial example I want to normalise an aggregated result to drive the colour scale...

```
df = pd.DataFrame({"ss_id" : [1,2,3,4,5], "year":[2000,2000,2001,2002,2002], "pop":[100,100,150,200,200]})

alt.Chart(df).mark_bar().transform_aggregate(
    population='min(pop):Q',
    story_count='distinct(ss_id):Q',
    groupby=['year']
).encode(
    x='year:N',
    y='story_count:Q',
    color=alt.Color('story_count/population:Q')
)  
```

Is it that I am not expressing the division calculation properly? I've looked at join_aggregate etc but don't think that's the answer. I can find one issue related to this on vega-lite but it quickly became a discussion about implementation of box plots.

**Comment by jakevdp** [comment]
Encodings don't support calculations; that is, your chart is specifying a column named ``story_count/population``.

If you want to calculate a new value, you can do it via a calculate transform; for example:
```python
import pandas as pd
import altair as alt
df = pd.DataFrame({"ss_id" : [1,2,3,4,5], "year":[2000,2000,2001,2002,2002], "pop":[100,100,150,200,200]})

alt.Chart(df).mark_bar().transform_aggregate(
    population='min(pop):Q',
    story_count='distinct(ss_id):Q',
    groupby=['year']
).transform_calculate(
    ratio='datum.story_count/datum.population'
).encode(
    x='year:N',
    y='story_count:Q',
    color=alt.Color('ratio:Q')
)  
```

**Comment by trubens71** [comment]
Many thanks Jake. I had been down that path, but convinced myself that transform_calculate only worked on the base data, when in fact I was missing the datum reference.
