### ISSUE TITLE
Vegascope renderer no entry point vegalite v3

### ISSUE THREAD

**Issue by maximegravoueille** [altair-viz/altair#1563]
I am using VS Code with the vegascope renderer for displaying and it seems like there is no entry point in the latest version of altair (with vegalite.v3). It works perfectly fine with altair.vegalite.v2. See the code below for detailed information.

---------------------------------------------------------------------------
NoSuchEntryPoint                          Traceback (most recent call last)
~\Anaconda3\lib\site-packages\altair\utils\plugin_registry.py in _enable(self, name, **options)
    133             try:
--> 134                 ep = entrypoints.get_single(self.entry_point_group, name)
    135             except entrypoints.NoSuchEntryPoint:

~\Anaconda3\lib\site-packages\entrypoints.py in get_single(group, name, path)
    216 
--> 217     raise NoSuchEntryPoint(group, name)
    218 

NoSuchEntryPoint: No 'vegascope' entry point found in group 'altair.vegalite.v3.renderer'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
 in 
      2 import numpy as np
      3 import altair.vegalite.v3 as alt
----> 4 alt.renderers.enable('vegascope')

~\Anaconda3\lib\site-packages\altair\utils\plugin_registry.py in enable(self, name, **options)
    169         if name is None:
    170             name = self.active
--> 171         return PluginEnabler(self, name, **options)
    172 
    173 

~\Anaconda3\lib\site-packages\altair\utils\plugin_registry.py in __init__(self, registry, name, **options)
     23         self.options = options
     24         self.original_state = registry._get_state()
---> 25         self.registry._enable(name, **options)
     26 
     27     def __enter__(self):

~\Anaconda3\lib\site-packages\altair\utils\plugin_registry.py in _enable(self, name, **options)
    135             except entrypoints.NoSuchEntryPoint:
    136                 if name in self.entrypoint_err_messages:
--> 137                     raise ValueError(self.entrypoint_err_messages[name])
    138                 else:
    139                     raise

ValueError: 
To use the 'vegascope' renderer, you must install the vegascope
package; see http://github.com/diana-hep/vegascope/
for more information.

**Comment by jakevdp** [comment]
Yeah, it looks like vegascope hasn't been updated for Vega-Lite 3. I'd raise an issue on the [vegascope package](http://github.com/diana-hep/vegascope/)

**Comment by jakevdp** [comment]
Fixed in vegascope: https://github.com/scikit-hep/vegascope/issues/5
