### ISSUE TITLE
[Not a bug] - thanks!

### ISSUE THREAD

**Issue by ianozsvald** [altair-viz/altair#1564]
No action required from you all - this is a report of Thanks after my talk at PyLondinium 2019. 

My talk went down very well, many folk in the room hadn't seen Altair before (or Voila), the talk was aimed at software engineers who are moving into data science. Many folk said thanks after for letting them know about Altair and they intend to replace matplotlib for the exploratory work. I wanted to pass those thanks on to you here - thanks! Ian.

**Comment by jakevdp** [comment]
Awesome! I added a new label for you.

**Comment by ianozsvald** [comment]
Much obliged Jake, I passed that on to the attendees-slack, hopefully it'll get used in the future :-)
