### ISSUE TITLE
Question: binding color field to a selection (checkbox, radio, etc)

### ISSUE THREAD

**Issue by trubens71** [altair-viz/altair#1569]
Apologies for what is no doubt a trivial question. I would like to bind the color field to a control (checkbox, radio or dropdown). Here's a trivialised example where I want to be able to flip between using Column_A and Column_B as the basis for colouring the marks. Would prefer to use radio buttons, but trying to simplify first...

```
import altair as alt
import pandas as pd

df = pd.DataFrame({"Name": ['Tom','Dick','Harry'],
                   "Column_A": [1,2,3],
                   "Column_B": [10,20,30]})

column_checkbox = alt.binding_checkbox()
column_select = alt.selection_single(bind=column_checkbox, name="column")

column_colour_condition = alt.condition(
    column_select,
    alt.value('Column_A:N'), # <<< have tried alt.Field, alt.FieldName etc
    alt.value('Column_B:N')  #
)

alt.Chart(df).mark_bar().add_selection(
    column_select
).encode(
    x='Name',
    color=alt.Color(column_colour_condition, scale=alt.Scale(domain=[0,30]))
)
```
This is failing schema validation as follows:

```
altair.vegalite.v3.schema.channels.Color->field, validating 'anyOf'
{'condition': {'selection': 'column', 'value': 'Column_A:N'}, 'value': 'Column_B:N'} is not valid under any of the given schemas
```
Have looked closely at the (multiple interactions)[https://altair-viz.github.io/gallery/multiple_interactions.html?highlight=multiple%20interactives] examples, but clearly not understanding how alt.condition works. 

Using altair on Colab.

**Comment by jakevdp** [comment]
Rather than doing
```
color=alt.Color(column_colour_condition)
```
You should do
```
color=column_colour_condition
```
The first argument to ``alt.Color()`` must be a string, and this is why you are getting that error.

**Comment by trubens71** [comment]
Thanks for v.quick response, but whilst that passes the schema validation it does not render any colour at all (all marks are blank). The resulting vega-lite looks like this..

```
  "encoding": {
    "color": {
      "value": "Column_B:N",
      "condition": {"value": "Column_A:N", "selection": "column"}
    },
```
... which I would expect to be referencing a field not a value. I note my mistake that the field type should be :Q but that doesn't make a difference.

Also wondering how I would pass additional color properties such as the scale.

**Comment by jakevdp** [comment]
Oh, I didn't look closely enough. ``alt.value`` tells Altair that you want to use that explicit value, i.e. a color named ``Column_A:N``. That is not a valid color, so it doesn't work.

But unfortunately it's not possible to do what you wish, i.e. use different encodings based on the value of a selection (this is a limitation of the vega-lite renderer). You can switch between an encoding and a value, or switch between two different values, but you cannot switch between an encoding and another encoding.

**Comment by jakevdp** [comment]
So, for example, this should work:
```
column_colour_condition = alt.condition(
    column_select,
    Column_A:N',
    alt.value('lightgray')
)

alt.Chart(df).mark_bar().add_selection(
    column_select
).encode(
    x='Name',
    color=column_colour_condition,
)

**Comment by jakevdp** [comment]
Looking at your question more carefully, what you want to do (choose a column to encode based on a select box) is not supported by Vega-lite or altair.

What you can do with a select box is filter the values in a single column by the selection, and if you reshape your data (see https://altair-viz.github.io/user_guide/data.html#long-form-vs-wide-form-data) you can achieve essentially the same thing.

**Comment by jakevdp** [comment]
For example, something like this:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({"Name": ['Tom','Dick','Harry'],
                   "Column_A": [1,2,3],
                   "Column_B": [10,20,30]})

column_select = alt.selection_single(name="column", fields=['column'],
                                     bind=alt.binding_select(options=['Column_A', 'Column_B']),
                                     init={'column': 'Column_A'})

alt.Chart(df).mark_bar().transform_fold(
    fold=['Column_A', 'Column_B'],
    as_=['column', 'value']
).transform_filter(
    column_select
).encode(
    x='Name:N',
    y='value:Q',
).add_selection(
    column_select
)
```

**Comment by trubens71** [comment]
Many thanks Jake (for this and Altair in general).
