### ISSUE TITLE
Hexagonal Density Plot

### ISSUE THREAD

**Issue by david-waterworth** [altair-viz/altair#1574]
Is it possible to create a hexagonal density plot with altair, i.e. https://datavizproject.com/data-type/hexagonal-binning/ ?

**Comment by jakevdp** [comment]
No, hexagonal binning is not supported in Vega, the renderer behind Altair. This was discussed at one point, but I can't find the reference to it at the moment.

**Comment by joelostblom** [comment]
Closing since this would have to be implemented in Vega-Lite and there is nothing altair can do to fix the issue.
