### ISSUE TITLE
Is it possible to position the slider on top of the chart

### ISSUE THREAD

**Issue by rajesh241** [altair-viz/altair#1575]
Hi,
I have been playing around with the slider. Is it possible to have the slider at the top of the chart instead of the bottom.  
Am trying to create on chart based on the below example
https://altair-viz.github.io/gallery/us_population_over_time.html

rajesh

**Comment by armsp** [comment]
@rajesh241 This [SO post](https://stackoverflow.com/questions/62103632/altair-change-the-position-of-a-slider) will help you. This answers the exact question you've asked.

@jakevdp @eitanlees I think we can close this issue.

**Comment by jakevdp** [comment]
Thanks! I was just about to copy and paste that SO link :grin:
