### ISSUE TITLE
Question ? near real time, what's the best approach ?

### ISSUE THREAD

**Issue by djouallah** [altair-viz/altair#1577]
I have data that get save in a folder every 5 minutes, I am not good at all with real time approach, so excuse my silly question.

from alatir perspective what's the best format for this scenario.

- should load every new csv files.
- better to have a big combined csv file that i feed to altair.
-  is there a different approach ?

thanks for your help

**Comment by jakevdp** [comment]
The best approach will depend on what exactly you want to do.  You might take a look at Vega-Lite's handling of streaming data: https://vega.github.io/vega-lite/tutorials/streaming.html
