### ISSUE TITLE
Javascript Error: Invalid mark type "errorbar"

### ISSUE THREAD

**Issue by Roald87** [altair-viz/altair#1578]
I'm trying to plot some error bars, but get the following error:

`Javascript Error: Invalid mark type "errorbar"`

The error also shows with this example from the gallery:
```
import altair as alt
from vega_datasets import data

source = data.barley()

bars = alt.Chart().mark_bar().encode(
    x='year:O',
    y=alt.Y('mean(yield):Q', title='Mean Yield'),
    color='year:N',
)

error_bars = alt.Chart().mark_errorbar(extent='ci').encode(
    x='year:O',
    y='yield:Q'
)

alt.layer(bars, error_bars, data=source).facet(
    column='site:N'
)
```

I'm using altair version 3.1 in Jupyter Lab v1.0.0rc0. It shows both in Firefox (v67.0.3 (64-bit)) and Chrome (75.0.3770.100 (Official Build) (64-bit)).

**Comment by jakevdp** [comment]
It sounds like your frontend renderer is using an older version of Vega-lite: errorbar marks were added in Vega-Lite version 3.0. How did you install JupyterLab?

**Comment by PeterVerheijen** [comment]
Similar issue can be seen at https://github.com/altair-viz/altair/issues/1579 with solution, hopefully this helps @Roald87

**Comment by jakevdp** [comment]
I think this one is a bug in the JupyterLab 1.0.0rc0 release: https://github.com/jupyterlab/jupyterlab/issues/6709

**Comment by Roald87** [comment]
Thanks for the quick response. 

Is there any work around with the bug from Jupyter Lab? Also I don't see how I could use the solution of #1579.

**Comment by jakevdp** [comment]
No, #1579 is an entirely different issue.

Honestly, I would avoid using Altair on JuptyerLab for the time being. JupyterLab frontend extensions are very opaque and confusing, even to me. If you want a Jupyter notebook platform on which Altair will just work, I'd suggest [Colab](http://colab.research.google.com/).

**Comment by Roald87** [comment]
That is unfortunate to hear. I'd rather not use a cloud based service for analyzing data from our company. 

I now switched to a regular Notebook and there is works. 

Btw [here](https://altair-viz.github.io/getting_started/installation.html#quick-start-altair-notebook) it is mentioned that JupyterLab is preferred over Jupyter Notebook.

**Comment by jakevdp** [comment]
> Btw here it is mentioned that JupyterLab is preferred over Jupyter Notebook.

That is true, and it has been until it stopped working today. Sorry for the out-of-date docs :smile:

**Comment by Roald87** [comment]
Haha ok thanks for the help. Love the tool so far btw! 

I have to change my thinking a bit, comming matplotlib/bokeh, but the tool seems really powerfull.
