### ISSUE TITLE
Confusing JupyterLab install instructions

### ISSUE THREAD

**Issue by dustinmichels** [altair-viz/altair#1580]
Hi!

After struggling to get up & running in Jupyter Lab for a while, I'm wondering if the install instructions could be clarified.

## Issue

The[ "Quick Start: Altair + JupyterLab"](https://altair-viz.github.io/getting_started/installation.html#quick-start-altair-jupyterlab) instructions tell you to run:

```bash
conda install -c conda-forge altair vega_datasets notebook vega
```

or

```
pip install -U altair vega_datasets jupyterlab
```

If I take either approach, first creating a fresh Python 3.7 virtual environment, I end up installing `altair==3.1.0` & `jupyterlab=0.35.6`. And that combination doesn't seem to work right out of the gate.

When I run the subsequent sample code in a Lab notebook, I get the error message:

```
<VegaLite 3 object>

If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html
```

And when I follow [the link](https://altair-viz.github.io/user_guide/troubleshooting.html), I find out I really need Jupyter Lab version 1.0 (pre-release):

> Note: until JupyterLab 1.0 is released, you will need to use the 1.0 pre-release with Altair 3. This can be installed using:
>
> $ pip install -U --pre jupyterlab

Installing the pre-release jupyterlab 1.0 via pip fixes the issue (in either case).

## Suggestion

It seems like what I am doing is the most basic start case, and it shouldn't require a trip to the troubleshooting page.

If Altair 3 requires JupyterLab 1.0+ to work properly, should the initial [quickstart page](https://altair-viz.github.io/getting_started/installation.html#quick-start-altair-jupyterlab) just tell you to run `pip install -U --pre jupyterlab`? Or do the provided instructions work out-of-the-box for others?

## Additional Details

- python 3.7.3
- conda 4.7.5
- MacOS Mojave (10.14.5)

**Comment by dustinmichels** [comment]
Also, I have been unable to install jupyter lab 1.0 with conda instead of pip. If this is an option, perhaps it should be documented, too.

**Comment by jakevdp** [comment]
Thanks – JupyterLab 1.0 will be released imminently, at which point this confusion will go away.

I didn't do a lot of doc updates specific to the time before jupyterlab 1.0 is released, because every change I made would have to be undone after the release, and I'm stretched trying to find the time to support Altair as it is.

Sorry for the confusion.

**Comment by dustinmichels** [comment]
Okay, makes sense. Thanks for your reply (& all your open source work).

**Comment by jakevdp** [comment]
Now that JupyterLab 1.0 has been released, I think this is remedied.
