### ISSUE TITLE
Spacing between hconcat charts

### ISSUE THREAD

**Issue by ghost** [altair-viz/altair#1585]
When using either hconcat or vconcat, is there a way to increase the spacing between the two charts so they are not quite so close together?

Thank you in advance for any help.

**Comment by mattijn** [comment]
Use either the `spacing` variable in [`altair.HConcatSpec`](https://altair-viz.github.io/user_guide/generated/core/altair.HConcatSpec.html):
```python
alt.hconcat(chart1, chart2, spacing=100)
```

Or the `spacing` variable in [`altair.CompositionConfig`](https://altair-viz.github.io/user_guide/generated/core/altair.CompositionConfig.html):
```python
alt.hconcat(chart1, chart2).configure(
    concat=alt.CompositionConfig(spacing=100)
)
```

**Comment by jakevdp** [comment]
Note that a more concise way of accessing the concat configuration is
```python
alt.hconcat(chart1, chart2).configure_concat(
    spacing=100
)
```
