### ISSUE TITLE
alt.Tooltip not behaving the same way as not specifying the object

### ISSUE THREAD

**Issue by kaisengit** [altair-viz/altair#1586]
Excuse the weird title but I am not sure how to properly phrase the issue. This is on Altair 3.1.

Let's take the following example code from another issue: 

```
from vega_datasets import data
df=data.barley()
base = alt.Chart(df).transform_joinaggregate(
    yield_sum='sum(yield)',
    groupby=['year', 'variety']
).transform_calculate(
    yield_norm='datum.yield / datum.yield_sum'  
).mark_bar().encode(
    x=alt.X('yield', stack='normalize', axis=alt.Axis(title='Normalized Yield', format='.0%')),
    y=alt.Y('variety', title='Variety'),
    tooltip=['yield', 'variety', 'year', 'yield_norm:Q'],
    order='site'
)

bars = base.encode(
    detail='site',
    color=alt.Color('site', title='Site')
)

text = base.mark_text(dx=-15, dy=3).encode(
    text=alt.Text('yield_norm:Q', format='.0%'),
)

alt.layer(bars, text).facet(column=alt.Column('year:O', title='Year'))
```

This works fine. However changing the tooltip line to
`tooltip=alt.Tooltip(['yield', 'variety', 'year', 'yield_norm:Q'])`

will throw the following error:

> ValueError: yield encoding field is specified without a type; the type cannot be automatically inferred because the data is not specified as a pandas.DataFrame.

Should the two ways of specifying the tooltip not work interchangeably? Or is it maybe related to this issue #1573?

**Comment by jakevdp** [comment]
Yes, the type should propagate similarly in each case. I suspect internally the ``context`` argument is not being properly propagated in this case.

**Comment by jakevdp** [comment]
#1587 should fix this
