### ISSUE TITLE
StrokeWidth encoding doesn't work with condition

### ISSUE THREAD

**Issue by FlorianGD** [altair-viz/altair#1590]
Hello,
Trying to reproduce [this Vega-lite example](https://vega.github.io/vega-lite/examples/interactive_bar_select_highlight.html), I came onto an error with the encoding of `strokeWidth` and `strokeOpacity`. I use altair 3.1.0.
Below is a minimal example : 
```python
import altair as alt
import pandas as pd

df = pd.DataFrame.from_records(
        [{"a": "A", "b": 28}, {"a": "B", "b": 55}, {"a": "C", "b": 43},
          {"a": "D", "b": 91}, {"a": "E", "b": 81}, {"a": "F", "b": 53},
          {"a": "G", "b": 19},  {"a": "H", "b": 87}, {"a": "I", "b": 52},]) 

highlight = alt.selection_single(encodings=["x"], empty="none")
bars = alt.Chart(df).mark_bar(stroke="black", fill="#4C78A8").encode(
    x="a:N", 
    y="b:Q", 
).add_selection(highlight)

bars.encode(strokeWidth=alt.StrokeWidthValue(3))
```
This code works, but if I change the strokeWidth encoding to a condition, I have an error :
```python
bars.encode(strokeWidth=alt.condition(highlight, alt.StrokeWidthValue(3), alt.StrokeWidthValue(0)))

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
~/miniconda3/envs/altair3/lib/python3.7/site-packages/altair/vegalite/v3/api.py in _wrap_in_channel_class(obj, prop)
   1420             try:
-> 1421                 cls = getattr(channels, clsname)
   1422             except AttributeError:

AttributeError: module 'altair.vegalite.v3.schema.channels' has no attribute 'StrokewidthValue'

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
<ipython-input-90-9c710c91f93a> in <module>
----> 1 bars.encode(strokeWidth=alt.condition(highlight, alt.StrokeWidthValue(3), alt.StrokeWidthValue(0)))

~/miniconda3/envs/altair3/lib/python3.7/site-packages/altair/vegalite/v3/api.py in encode(self, *args, **kwargs)
   1438             else:
   1439                 if condition is not Undefined:
-> 1440                     obj['condition'] = _wrap_in_channel_class(condition, prop)
   1441             if obj is not None:
   1442                 kwargs[prop] = _wrap_in_channel_class(obj, prop)

~/miniconda3/envs/altair3/lib/python3.7/site-packages/altair/vegalite/v3/api.py in _wrap_in_channel_class(obj, prop)
   1421                 cls = getattr(channels, clsname)
   1422             except AttributeError:
-> 1423                 raise ValueError("Unrecognized encoding channel '{}'".format(prop))
   1424 
   1425             try:

ValueError: Unrecognized encoding channel 'strokeWidth'
```

Note that I can create the chart I want in the Vega editor [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgolcdXFzI8caIKlIx0wFpoAJnF8CADgCcAI3FfKAFZKAEYANg8AdiDPFw9KMIFxJj4+SAMIMSlZLHkATzUbLEg-SUgRFF1bAGIGAGFIjwBBD3KoAGdqSVhpIqgfJXFoWQyoAng4SmR4dFzDTM7u3oB1KjpzOHgp1QRzdoIlAmgd+FtabiVuXhFccSUtPr5hKFv7vqZRzIAPc2oCvossFE0zubUgKAOlFsZk+UDyv3+tgAjlpxPBVKZVLgbBVCEoocUfOlDKNIPtDsdkLs5hBMudULRLgzeLlIH9CrZ2tNUIcweNJtz2qQANqQH4AXREBFEaj+tngCBsghJrEMkAAJO1oJwJGdqNQ1O0MAB6Y3Y1DiAB0qGQdC0PktVONWp14jNBAtDku1AIZr4lv9TEtACt2rtVZl7OJ9tQhTTaXYTOInK53N4-AFguEojEPHEEkkUmksML5rScGZik0wUSsM4PLCIBXbAAhGukQKBRtkStQOrtrAMJ4R2lNyC9yAAEQHYC8IW7zeKAFEZx55yPR4uoAAxGeBYdlscTgDiM5CXgX49sAAlV5FLxOAJJ75zK0fikkgQRAA) with the same encoding, so I do not think it comes from the schema.

**Comment by FlorianGD** [comment]
I did not notice when I wrote this issue, but it could be related to #1573.

**Comment by FlorianGD** [comment]
There is a workaroud, using a layer, but it feels less straightforward:
```python
empty_bars = alt.Chart(df).transform_filter(highlight).mark_bar(stroke='black', strokeWidth=2).encode(
    x="a:N", 
    y="b:Q",
    opacity=alt.condition(highlight, alt.value(1), alt.value(0))
).add_selection(highlight)

bars + empty_bars
```
![highlight_issue](https://user-images.githubusercontent.com/9217921/60518015-fa73a100-9ce0-11e9-9886-5e3590dd6a09.gif)

**Comment by jakevdp** [comment]
Yep, this is a consequence of the bug in #1573. It's possible to work around it by constructing the ``alt.condition`` output directly, if you wish.

**Comment by jakevdp** [comment]
Until #1573 is finished, the workaround is this. Insead of
```
chart.encode(
  strokeWidth=alt.condition(highlight, alt.value(3), alt.value(0))
)
```
you'll need to use
```python
chart.encode(
  strokeWidth=alt.StrokeWidthValue(0, condition=alt.StrokeWidthValue(3, selection=highlight.name))
)
```
The latter mirrors the vega-lite schema directly and so it avoids the problematic logic mentioned in #1573.

**Comment by FlorianGD** [comment]
Thanks, it works (and is less verbose than the layer option)
