### ISSUE TITLE
Apply color to outliers in boxplot

### ISSUE THREAD

**Issue by TomBugnon** [altair-viz/altair#1591]
The color scale is not applied to outlier points in boxplots.
Is there any way to apply the colorscheme or set the color manually for the dots?

```
import altair as alt
from vega_datasets import data

source = data.population.url

alt.Chart(source).mark_boxplot(extent=0.5).encode(
    x='age:O',
    y='people:Q',
    color=alt.Color('age:O',
                    scale=alt.Scale(scheme='reds')),
)
```

![image](https://user-images.githubusercontent.com/14128078/60552797-e25a4c80-9cf5-11e9-9a8a-edf8cbaa5193.png)

**Comment by jakevdp** [comment]
I think the only way to apply an encoding to the outliers is to construct the boxplot elements manually.
