### ISSUE TITLE
Set domain for log scale

### ISSUE THREAD

**Issue by TomBugnon** [altair-viz/altair#1592]
In reference to https://github.com/altair-viz/altair/issues/1393 , it is apparently expected that the 'domain' argument is ignored for log scales. Is there any way around that ?

```
from vega_datasets import data
df = data.iris()
alt.Chart(df).mark_point(clip=True).encode(
    x=alt.X('petalLength', scale=alt.Scale(type='log',domain=(1.5,5.0))),
    y='sepalLength'
)
```

![image](https://user-images.githubusercontent.com/14128078/60553071-4a5d6280-9cf7-11e9-86b4-bb0109e2d32b.png)

**Comment by nmichlo** [comment]
I am also encountering this.

**Comment by dmos62** [comment]
@knaps [mentioned](https://github.com/altair-viz/altair/issues/1393#issuecomment-477349287) that this is intented behaviour. How do we control the area charted when using log scale then?

**Comment by jakevdp** [comment]
The domain argument does work with log scales, but domains must start and end on integer powers of the base. For example, here is a default base-10 domain:
```python
import altair as alt
import pandas as pd

data = pd.DataFrame({'x': [1, 10, 100]})

alt.Chart(data).mark_point().encode(
    x=alt.X('x', scale=alt.Scale(type='log'))
)
```
![visualization (33)](https://user-images.githubusercontent.com/781659/68594598-c0fc3080-044c-11ea-8395-c4886af5aeb9.png)


Here is a base-2 domain, with the limits set at 1 and 256:
```python
alt.Chart(data).mark_point().encode(
    x=alt.X('x', scale=alt.Scale(type='log', base=2, domain=[1, 256]))
)
```
![visualization (35)](https://user-images.githubusercontent.com/781659/68594603-c48fb780-044c-11ea-8bc0-540c048f38db.png)

**Comment by pierreaubert** [comment]
[this doesn't look good](https://pierreaubert.github.io/spinorama/Neumann%20KH%2080/CEA2034.html)

I only would like to display the range 20, 20000. Is there a way to force it?

**Comment by jakevdp** [comment]
I don't know of any way to force log domain extents to start and end on values that are not integer powers of the base. You might ask in the Vega-Lite forums to see if anybody knows whether that's possible.

**Comment by pierreaubert** [comment]
I will. Thanks for the answer. I'am new to Altair but it is awesome.
