### ISSUE TITLE
Is it possible to use custom strings for legend labels?

### ISSUE THREAD

**Issue by chriscrawfordTR** [altair-viz/altair#1596]
Is it possible to pass a custom list of strings for the legend labels?  In a chart, I want to show missing values as a part of the total so I use a stacked barchart where the segments/pieces(?) come from two columns: `Missing` and `Difference` , combined together they add up to the total. The legend shows the two variables as `Missing` and `Difference` and I would like to be able to change Difference -> Total somehow.

```
df = pd.DataFrame(
  {'Year': [2014, 2015, 2016, 2017, 2018, 2019],
   'Total': [376, 1198, 1871, 4386, 4920, 2417],
   'Missing': [299, 758, 1063, 233, 32, 11],
   'Difference': [77, 440, 808, 4153, 4888, 2406]}
)
```
![image](https://user-images.githubusercontent.com/50157064/60625540-fad17200-9d9c-11e9-8b38-fbdad143a4a6.png)

```
melted = pd.melt(df, id_vars=['Year'], value_vars=['Difference', 'Missing'])


alt.Chart(
    data=melted,
    background='white'          
).mark_bar(
).encode(
    alt.X('Year:O', title=''),
    alt.Y('value:Q', title=''),
    alt.Color('variable:N', 
              scale=alt.Scale(domain=['Difference', 'Missing'],
                              range=[sand, red])),
    order=alt.Order('variable', sort='descending')
)
```

In the plot below I have the chart I want but the Legend says `Difference` and I would rather it say `Total`. I know I can change the original column names or the values within the melted dataframe, but I was hoping for a cleaner way to change the legend labels.

![image](https://user-images.githubusercontent.com/50157064/60625462-be9e1180-9d9c-11e9-90f9-30192edd5e66.png)

**Comment by jakevdp** [comment]
Altair legends reflect the content of the data. The easiest way to change the values they show is to change the values within the dataset:
```python
import altair as alt
import pandas as pd
df = pd.DataFrame({'Year': [2014, 2015, 2016, 2017, 2018, 2019],
 'Total': [376, 1198, 1871, 4386, 4920, 2417],
 'Missing': [299, 758, 1063, 233, 32, 11],
 'Difference': [77, 440, 808, 4153, 4888, 2406]}
)


melted = pd.melt(df.drop('Total', axis=1).rename({'Difference': 'Total'}, axis=1), id_vars=['Year'], value_vars=['Total', 'Missing'])

alt.Chart(
    data=melted,
    background='white'          
).mark_bar(
).encode(
    alt.X('Year:O', title=''),
    alt.Y('value:Q', title=''),
    alt.Color('variable:N', 
              scale=alt.Scale(domain=['Total', 'Missing'],
                              range=['#ddccbb', 'red'])),
    order=alt.Order('variable', sort='ascending')
)

```
![visualization (34)](https://user-images.githubusercontent.com/781659/60626433-9663e200-9d9f-11e9-8ba4-94c18e4fdc72.png)


If for some reason your input data is fixed, you could alternatively use a [calculate transform](https://altair-viz.github.io/user_guide/transform.html#calculate-transform) within the chart spec to effectively do the same thing.

**Comment by jakevdp** [comment]
Another option is to actually use your ``Total`` entry and set ``stack=None`` to create an unstacked bar chart:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({'Year': [2014, 2015, 2016, 2017, 2018, 2019],
 'Total': [376, 1198, 1871, 4386, 4920, 2417],
 'Missing': [299, 758, 1063, 233, 32, 11],
 'Difference': [77, 440, 808, 4153, 4888, 2406]}
)

alt.Chart(df).transform_fold(
    ['Total', 'Missing'],
    as_=['variable', 'value']
).mark_bar().encode(
    alt.X('Year:O', title=''),
    alt.Y('value:Q', title='', stack=None),
    alt.Color('variable:N', 
              scale=alt.Scale(domain=['Total', 'Missing'],
                              range=['#ddccbb', 'red'])),
    order=alt.Order('variable:N', sort='descending')
).properties(
    background='white'
)
```
![visualization (35)](https://user-images.githubusercontent.com/781659/60626754-a3350580-9da0-11e9-8a0a-85cac0c699be.png)

**Comment by chriscrawfordTR** [comment]
Ah yeah, very slick! This is great, thank you. (and for the crazy fast support!)

**Comment by armsp** [comment]
@jakevdp I can see that there is a `value` parameter for [altair.Legend](https://altair-viz.github.io/user_guide/generated/core/altair.Legend.html)
> values : anyOf(List(float), List(string), List(boolean), List(DateTime))
    Explicitly set the visible legend values.

I tried using this, it does show the provided list of labels, but then the symbols(colors) are not displayed.

**Comment by jakevdp** [comment]
You can use the legend `values` setting to specify a subset of the range to show in the legend; you can't use it to change the scale range to contain different values. Here's an example of how it's intended to be used:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({'Year': [2014, 2015, 2016, 2017, 2018, 2019],
 'Total': [376, 1198, 1871, 4386, 4920, 2417],
 'Missing': [299, 758, 1063, 233, 32, 11],
 'Difference': [77, 440, 808, 4153, 4888, 2406]}
)

alt.Chart(df).transform_fold(
    ['Total', 'Missing'],
    as_=['variable', 'value']
).mark_bar().encode(
    alt.X('Year:O', title=''),
    alt.Y('value:Q', title='', stack=None),
    alt.Color('variable:N', 
              scale=alt.Scale(domain=['Total', 'Missing'],
                              range=['#ddccbb', 'red']),
              legend=alt.Legend(values=['Total'])),
    order=alt.Order('variable:N', sort='descending')
).properties(
    background='white'
)
```
![visualization - 2020-06-17T223818 781](https://user-images.githubusercontent.com/781659/84982294-3fa80300-b0eb-11ea-9e2a-5967f626776b.png)

**Comment by armsp** [comment]
Ah I see, thanks for the info.
