### ISSUE TITLE
Isotype chart

### ISSUE THREAD

**Issue by noklam** [altair-viz/altair#1601]
Sorry if this is not the right place to ask this question. I want to make plots with custom shape, I wonder what are those strings defined with "person"? I do not know what keywords I should google for...

Essentially what I am trying to do is adding custom diagram on heatmap. I have tried 2 approaches:
1. heatmap + text(emoji) 
does not work well, once I add text the rectangle become a long rectangle instead of grid, I cannot find how to configure that.
I want a compact grid with text(emoji), but I get this instead.
![image](https://user-images.githubusercontent.com/18221871/60854649-9a768080-a233-11e9-9639-9cd0271c805d.png)

2. heatmap + mark_point(following below reference), but I do not know how to create this custom marker shape.

https://altair-viz.github.io/gallery/isotype_grid.html

person = (
    "M1.7 -1.7h-0.8c0.3 -0.2 0.6 -0.5 0.6 -0.9c0 -0.6 "
    "-0.4 -1 -1 -1c-0.6 0 -1 0.4 -1 1c0 0.4 0.2 0.7 0.6 "
    "0.9h-0.8c-0.4 0 -0.7 0.3 -0.7 0.6v1.9c0 0.3 0.3 0.6 "
    "0.6 0.6h0.2c0 0 0 0.1 0 0.1v1.9c0 0.3 0.2 0.6 0.3 "
    "0.6h1.3c0.2 0 0.3 -0.3 0.3 -0.6v-1.8c0 0 0 -0.1 0 "
    "-0.1h0.2c0.3 0 0.6 -0.3 0.6 -0.6v-2c0.2 -0.3 -0.1 "
    "-0.6 -0.4 -0.6z"
)

**Comment by jakevdp** [comment]
That is an [SVG path](https://developer.mozilla.org/en-US/docs/Web/SVG/Tutorial/Paths) describing the shape of a person. You can use any SVG path you like to define your own shape.

**Comment by noklam** [comment]
Thx! I have made some progress.
I have no luck aligning the grid with the SVG path though
![image](https://user-images.githubusercontent.com/18221871/60865162-079c0d00-a258-11e9-8b33-683af5b80ed7.png)

**Comment by noklam** [comment]
I have found the properties `dx` and it does not work while `xOffset` does work... What are the difference between this two?

**Comment by jakevdp** [comment]
``dx`` applies to text marks (and is applied after rotation, if any) while ``xOffset`` applies to any mark.
