### ISSUE TITLE
Highlighting points on a faceted chart

### ISSUE THREAD

**Issue by david-waterworth** [altair-viz/altair#1602]
the following is adapted from https://stackoverflow.com/a/54965673/2981639

I want to highlight specific points on a chart. The way I've seen this done is to create 2 layers with the first plotting all points and the 2nd plotting a subset in a different style i.e. cluster members colored by cluster and the cluster centers as black points in the linked example.

I also want to facet the chart, i.e. using `columns=` and I understand from https://github.com/altair-viz/altair/issues/668 that the data should be passed to the facet() function and this gets forwarded to the layers.

But if you want two layers with different data sources and a facet per layer what do you do?

```
import altair as alt
import pandas as pd
from sklearn.datasets import make_blobs

X, labels = make_blobs(20, random_state=1)
points = pd.DataFrame({
    'x': X[:, 0],
    'y': X[:, 1],
    'labels': labels
})
centers = points.groupby('labels').mean()
data = pd.concat([points , centers.reset_index()])

chart1 = alt.Chart(data).mark_point(filled=True, size=150).encode(
    x='x',
    y='y',
    color='labels:N',
    column='labels:N',
)

chart2 = alt.Chart(centers).mark_point(filled=True, size=50).encode(
    x='x',
    y='y',
    color=alt.value('black'),
    column='labels:N',
)

chart1 + chart2
```

**Comment by david-waterworth** [comment]
I just found the example in https://altair-viz.github.io/user_guide/compound_charts.html#faceted-charts

"For example, here is a faceted view of a layered chart with a hover selection:"

I suspect that should help

**Comment by jakevdp** [comment]
As of Altair 3.1, the information in #668 is out of date and you need not specify the data in the facet method itself.

As to your question: if you want to facet a layered chart, you'll need to use a single dataset for both layers. This could be done by joining the two datasets and plotting different columns, or by concatenating the datasets and filtering on the appropriate property within each layer,  or by using transforms to modify the single base dataset within subcharts. Here I think the third option is probably the cleanest approach. It might look something like this:
```python
import altair as alt
import pandas as pd
from sklearn.datasets import make_blobs

X, labels = make_blobs(20, random_state=1)
points = pd.DataFrame({
    'x': X[:, 0],
    'y': X[:, 1],
    'labels': labels
})

chart1 = alt.Chart(points).mark_point(filled=True, size=150).encode(
    x='x',
    y='y',
    color='labels:N',
)

chart2 = alt.Chart(points).transform_aggregate(
    x='mean(x)',
    y='mean(y)',
    groupby=['labels']
).mark_point(filled=True, size=50).encode(
    x='x:Q',
    y='y:Q',
    color=alt.value('black'),
)

alt.layer(chart1, chart2).facet('labels:N')
```
![visualization - 2019-07-09T222903 420](https://user-images.githubusercontent.com/781659/60942845-f6272500-a298-11e9-9046-c5dfafea3da2.png)

**Comment by david-waterworth** [comment]
Excellent thanks, I should be able to find it myself but if I wanted to filter instead of groupby what would I replace `transform_aggregate` with?

**Comment by jakevdp** [comment]
Something like this:
```python
import altair as alt
import pandas as pd
from sklearn.datasets import make_blobs

X, labels = make_blobs(20, random_state=1)
points = pd.DataFrame({
    'x': X[:, 0],
    'y': X[:, 1],
    'labels': labels
})
centers = points.groupby('labels').mean()
points['type'] = 'points'
centers['type'] = 'centers'
data = pd.concat([points , centers.reset_index()])

chart1 = alt.Chart(data).transform_filter(
    "datum.type == 'points'"   
).mark_point(filled=True, size=150).encode(
    x='x',
    y='y',
    color='labels:N'
)

chart2 = alt.Chart(data).transform_filter(
    "datum.type == 'centers'"   
).mark_point(filled=True, size=50).encode(
    x='x',
    y='y',
    color=alt.value('black')
)

alt.layer(chart1, chart2).facet('labels:N')
```

**Comment by jakevdp** [comment]
Actually, it might be simpler in this case to do away with the layers altogether and use conditional encodings:
```python
import altair as alt
import pandas as pd
from sklearn.datasets import make_blobs

X, labels = make_blobs(20, random_state=1)
points = pd.DataFrame({
    'x': X[:, 0],
    'y': X[:, 1],
    'labels': labels
})
centers = points.groupby('labels').mean()
points['type'] = 'points'
centers['type'] = 'centers'
data = pd.concat([points , centers.reset_index()])

alt.Chart(data).mark_point(filled=True, size=150).encode(
    x='x',
    y='y',
    color=alt.condition("datum.type == 'points'", 'labels:N', alt.value('black')),
    size=alt.condition("datum.type == 'points'", alt.value(150), alt.value(50)),
    column='labels:N'
)
```

**Comment by david-waterworth** [comment]
Thanks, I did try conditions. I agree it works for the example but my real word case I have 3+ points I want to highlight so I think the transform_filter probably works better.

**Comment by larsrinn** [comment]
> if you want to facet a layered chart, you'll need to use a single dataset for both layers.

In order to make this clear: Does it mean it's not possible to do a faceted chart with multiple layers from different data sources?

**Comment by jakevdp** [comment]
It is possible, but the datasets need to be joined in the top layer..
