### ISSUE TITLE
Using Categorical Schemes for non-categorical data results in unhelpful error

### ISSUE THREAD

**Issue by david-waterworth** [altair-viz/altair#1603]
When I tried to supply scheme='dark2' for a qualitative column I got

> Javascript Error: e is undefined

Looks like there's an error in an exception handler somewhere

i.e.

`color=alt.Color('Loss', scale=alt.Scale(scheme='dark2'))`

Fails (reasonably) since 'dark2' isn't a continuous scale, but the message could be more informative.

`color=alt.Color('Loss', scale=alt.Scale(scheme='viridis'))`

is ok.

**Comment by jakevdp** [comment]
That exception comes from the Vega-Lite library within the frontend's Javascript runtime, so Altair doesn't have any control over it unfortunately.

**Comment by jakevdp** [comment]
You could propose a more helpful error in http://github.com/vega/vega-lite

**Comment by jakevdp** [comment]
Trying to reproduce this error, and I can't. I'm curious what version of Vega-Lite you are rendering your charts with... what frontend are you using? (JupyterLab, Jupyter Notebook, etc.)

**Comment by david-waterworth** [comment]
I'm using jupyterlab 1.0.1, I have python package vega 2.3.2 installed. Is that Vega-Lite? I thought it was an npm package but there's nothing returned as local or global when I do `npm list`?

**Comment by jakevdp** [comment]
Thanks. The Vega-Lite libraries are part of the vega labextension bundled with Jupyterlab 1.0.

Can you paste a complete snippet that reproduces the error? I've not been able to make it happen by adding the encoding you pasted above to a generic chart.

**Comment by david-waterworth** [comment]
Here you go, I tested this in a new notebook using a Python 3.7 kernel 

```
import altair as alt
import pandas as pd

df = pd.DataFrame(
{
    'ID':[1,2,3],
    'CV(RMSE)':[30.1,25.1,18.1],
    'NMBE':[0.1,0.01,0.0],
    'R^2':[0.99,0.98,0.97],
    'Encoding':['Plain','Plain','Plain'], 
    'Boosting':['Plain','Plain','Plain'], 
    'Loss':[10.0,11.0,12.0]
}
)

base = alt.Chart(df).mark_point().encode(
    x='CV(RMSE)',
    y='NMBE',
    tooltip=['ID','NMBE', 'CV(RMSE)', 'R^2', 'Encoding', 'Boosting', 'Loss'],
    color=alt.Color('Loss', scale=alt.Scale(scheme='dark2'))
).properties(
    title='test'
).interactive()

base
```

![image](https://user-images.githubusercontent.com/5028974/61018758-427a7e00-a3db-11e9-9a2c-93fd0b10f457.png)

**Comment by david-waterworth** [comment]
Or exported as json

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v3.3.0.json",
  "config": {"mark": {"tooltip": null}, "view": {"height": 300, "width": 400}},
  "data": {"name": "data-940db0361ac4a84b9e8fcf0b970950aa"},
  "datasets": {
    "data-940db0361ac4a84b9e8fcf0b970950aa": [
      {
        "Boosting": "Plain",
        "CV(RMSE)": 30.1,
        "Encoding": "Plain",
        "ID": 1,
        "Loss": 10,
        "NMBE": 0.1,
        "R^2": 0.99
      },
      {
        "Boosting": "Plain",
        "CV(RMSE)": 25.1,
        "Encoding": "Plain",
        "ID": 2,
        "Loss": 11,
        "NMBE": 0.01,
        "R^2": 0.98
      },
      {
        "Boosting": "Plain",
        "CV(RMSE)": 18.1,
        "Encoding": "Plain",
        "ID": 3,
        "Loss": 12,
        "NMBE": 0,
        "R^2": 0.97
      }
    ]
  },
  "encoding": {
    "color": {
      "field": "Loss",
      "scale": {"scheme": "dark2"},
      "type": "quantitative"
    },
    "tooltip": [
      {"field": "ID", "type": "quantitative"},
      {"field": "NMBE", "type": "quantitative"},
      {"field": "CV(RMSE)", "type": "quantitative"},
      {"field": "R^2", "type": "quantitative"},
      {"field": "Encoding", "type": "nominal"},
      {"field": "Boosting", "type": "nominal"},
      {"field": "Loss", "type": "quantitative"}
    ],
    "x": {"field": "CV(RMSE)", "type": "quantitative"},
    "y": {"field": "NMBE", "type": "quantitative"}
  },
  "mark": "point",
  "selection": {
    "selector001": {
      "bind": "scales",
      "encodings": ["x", "y"],
      "type": "interval"
    }
  },
  "title": "test"
}
```

**Comment by jakevdp** [comment]
Hmm... It must be something specific to JupyterLab. I can't reproduce the error in other environments (for example, the vega-lite editor: [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgolcdXFzI8caIKlIx0wFoAnM0oAjJnwBsARnHQGcQAOBjcnAiDEaEQmMIB2JicAViZxMwMIMSlZLEg1WGR4XlZDSAJ4OEpC9CxQCEy4JVhJOUN6qGoATzUbXIBHLXEi5FNVXBsS9syUAiVKWwAZWABnZchJqchl6HElXrJtzmtbYxkAJkhBNrAM+sgFZVUNLABta4h5bv3IAaHVUeQ43WUBmc1sAEkACKXDbtT49Wy-YYAoEiUHzXIAOQAsgAhACiMPeZC6CP6g2RJkBExBhDBuQAwgA1AAUACVsQBlfEASiJUxJX0RFP+VNRtNmGKgbIAehdbnD7kLcvBYKJCrtgZB0bZ8RVYFV4OgFfV4d9VerLEotTrcrjFMtVEb+VMzcK-iMxTTtXSpZAlqtLtcALqwqAAD3MpO+SNFY29tqgzPZXN5LsynSjyqgsc98ZtvtsOIJQYgty2swI0FUCFa7Qre2rzRYPjrm2jtkK1AIklwmrDmTchT9212BDWA6g5Uq1TWr0gkZEmeD1yuZY29xGe1s3cd61KABJDgQJLYeNQ1MsMAB6a-jVDiAB0qBGtC0bkfyFg1+PEjvBAfBwlBGAg7z4R9wKYR8ACtllrDd7HEZYCGoOdsGuOwTHEZxXA8bw-ACYJQnCSJoliJwEmSVIzFeYk6gFKAoVIHxJ0yZMOW5PksAER8WOJTJi0JLAoL4hjpTlUgoKcJxWKgPUZ2dXIAAUlHEQp9zEyB7RWJ0aigFS1PgDSGP9FY0J8JhiRND5+MY6EsDOWTIHY1MuLAM4kl4pzBMkx8mFEkzZQuYTHycIInPkg1qlsAz1Kc7THWi5TVLi2zTMDLAfB8KzJ3ogVICY7inJczjmKCLy0p84SnKC3yKIi-VDT0yBYqM+KHV0mKUratKA3Ms4rJDQwrkEIA))

**Comment by david-waterworth** [comment]
Odd, I can reproduce using vega-lite editor following that link so it's not jupyter. I tried both firefox and chrome.

I'm using ubuntu 18.04

**Comment by jakevdp** [comment]
I tried safari and chrome, and I don't see the error at that link.

I think this one will probably have to be chalked up to mysterious operating system differences.

**Comment by david-waterworth** [comment]
Yeah... no worries.

**Comment by domoritz** [comment]
I moved the Vega-Lite issue to Vega: https://github.com/vega/vega/issues/1872
