### ISSUE TITLE
Attempt to format label for temporal data ends with same value

### ISSUE THREAD

**Issue by chrislkeller** [altair-viz/altair#1608]
This could be similar to parsing mentioned in @palewire's #1027, but i don't know.

My time data is unix timestamps, and I'm pretty certain the scale (space) between days is correct. But when I attempt to format, the values are repeated - in case `Sunday` or `Jan. 18 1970` which is so close to the Unix Epoch that it makes me scratch my head.

Any ideas on what might be happening? Full notebook is [here](https://nbviewer.jupyter.org/gist/chrislkeller/23536e5dcaa19111e919b32bd848fc6e)

![visualization](https://user-images.githubusercontent.com/433780/61150480-5fc15200-a498-11e9-8e22-8d84a09f4265.png)

```
# Convert to dataframe
data = pd.DataFrame(source)

# chart title
title = 'Ridgecrest aftershocks tapering off'

tick_range = list(range(1562137200, 1563001180, 86400))

# Configure the chart
frequency_chart = alt.Chart(
    source,
    title=title
).mark_circle().encode(
    size=alt.Size(
        'style_size:Q',
        legend=None
    ),
    opacity=alt.value(1),
    x=alt.X(
        'raw_time:T',
        title=config['alt_sources'],
        scale=alt.Scale(
            domain=[1562137200, 1563001180]
        ),
        axis=alt.Axis(
            ticks=True,
            tickCount=10,
            values=tick_range,
            domain=True,
            grid=False,
            labels=True,
            formatType='time',
            format=('%A'),
        ),
    ),
    y=alt.Y(
        'mag:Q',
        title=None,
        axis=alt.Axis(
            domain=False,
            ticks=True,
            grid=True,
        ),
    )
).properties(
    width=800,
    height=400
).configure_view(
    strokeWidth=0
)

frequency_chart
```

**Comment by jakevdp** [comment]
It looks like your raw timestamps are in seconds since the Unix zero time, while Altair expects timestamps expressed in milliseconds since the Unix zero time. If you multiply all your raw times by 1000, I think the chart will be closer to what you expect.

**Comment by chrislkeller** [comment]
@jakevdp - Changing things to milliseconds crashes the plot in Jupyter and I have to re-start. 

Am going to close this and chalk it up to `user error`. Thank you for so much for the response.

**Comment by jakevdp** [comment]
> Changing things to milliseconds crashes the plot in Jupyter

Maybe you didn't change the step size in your tick range? If you're trying to draw 1000x the ticks you were originally, it can lead to issues with the javascript frontend when it tries to draw and label all of those ticks.
