### ISSUE TITLE
spaces in variable names give javascript parsing errors

### ISSUE THREAD

**Issue by jslmann** [altair-viz/altair#161]
Hoping this is the right place to raise this...

I believe this is a candidate for documentation as it is consistent with Vega-lite behaviour - though
not what I would expect from python and pandas.

The following code produces no chart in a jupyter notebook and Javascript parse errors in the console.

```
Chart(df3[:5]).mark_bar().encode(
    x=X('Leg 3'),
    y=Y('Leg 3'))
```

while this code does produce a chart.

```
 Chart(df4[:5]).mark_bar().encode(
    x=X('Leg3'),
    y=Y('Leg3'))
```

this seems to be consistent with Vega-lite behaviour as introducing spaces into the keys values and
field name in the JSON on the http://vega.github.io/vega-editor/ page also makes the plot vanish.

**Comment by jakevdp** [comment]
Thanks! I recall this being discussed somewhere else as well... Maybe @ellisonbg remembers?

**Comment by ellisonbg** [comment]
The word from the vega lite/vega developers is that it is not supported and that (for now) if we get a space in the column name in Altair we should raise an exception to prevent the spec from being spent for rendering.

**Comment by jheer** [comment]
Vega supports field names with spaces, following JavaScript reference rules for access path strings (e.g., `object['foo bar']` is valid, `object.foo bar` is not).

However, Vega-Lite does not (yet). Personally, I think this is a common enough occurrence that we should fix this sooner rather than later. (@kanitw @domoritz)

**Comment by domoritz** [comment]
There is an open issue in Vega-Lite for spaces in variable names at https://github.com/vega/vega-lite/issues/778

**Comment by ellisonbg** [comment]
I think it makes sense for Altair to support whatever syntax Vega-Lite supports. Column names with spaces is pretty common in Python so having this supported would be nice. If this is fixed soon, then we can just add some tests to Altair to make sure we are handling spaces properly in our shortcut parsing and then wait for VegaLite to support it.

**Comment by jakevdp** [comment]
I think we actually do have tests currently for proper handling of spaces: https://github.com/ellisonbg/altair/blob/master/altair/utils/tests/test_utils.py

**Comment by kanitw** [comment]
FYI, https://github.com/vega/vega-lite/releases/tag/v1.1.3

**Comment by jakevdp** [comment]
Thanks @kanitw! At some point we'll have to decide how ambitious we're going to be in keeping Altair up with minor Vega-Lite releases.

**Comment by kanitw** [comment]
For this one, you can wait for `1.2.0` which I'll try to release this weekend.  ;)

**Comment by domoritz** [comment]
I just released https://github.com/vega/ipyvega/releases/tag/v0.4.2 with vl 1.1.3.

**Comment by jakevdp** [comment]
Closing; this is fixed with the current Vega-Lite/Altair.
