### ISSUE TITLE
Altair not plotting geojson correctly 

### ISSUE THREAD

**Issue by joepropellernet** [altair-viz/altair#1612]
I'm trying to plot a geojson in a notebook and while the geopandas plot looks like this; 

![image](https://user-images.githubusercontent.com/35699115/61279265-af13c500-a7ad-11e9-893c-d42f8d1c7112.png)

the Altair output looks like this;

![image](https://user-images.githubusercontent.com/35699115/61279291-bc30b400-a7ad-11e9-8f1e-bd524b06579b.png)

As the data is pretty big, I'll not copy it out in full here! The full notebook and data are here: https://github.com/joepropellernet/Plotting_Police_areas and should be able to replicate the issue. 

One thought I had is that the geojson alternates between polygons and multipolygons but even filtering out to either one or the other doesn't solve the issue.

**Comment by jakevdp** [comment]
Altair (via Vega-Lite) supports topojson for map shapes. I'm not very familiar with the various geographic data formats, so I don't know what to recommend when it comes to shape files. You might ask on the Vega-Lite issue tracker whether there is a way to visualize shapefiles in Vega-Lite; that answer will apply to Altair as well.

**Comment by mattijn** [comment]
Altair plots by default geographic coordinates in WGS 84 (also known as epsg:4326). Since the coordinates are not coordinates but meters and since you these data represents England I imagined it is projected in the British National Grid (OSGB 1936, [epsg 27700](https://epsg.io/27700)).

Setting the projection and retrojecting it to the default epsg:4326 in geopandas before plotting it by Altair worked for me:

```python
import altair as alt
import geopandas as gpd

# load raw url in geodataframe
url = 'https://raw.githubusercontent.com/joepropellernet/Plotting_Police_areas/master/Police_areas.geojson'
gdf = gpd.read_file(url)

# set projection and reproject
gdf.crs = {'init' :'epsg:27700'}
gdf = gdf.to_crs({'init': 'epsg:4326'})

# define inline geojson data object
data_geojson = alt.InlineData(values=gdf.to_json(), format=alt.DataFormat(property='features',type='json')) 

# chart object
alt.Chart(data_geojson).mark_geoshape(
).encode(
    color="properties.pfa16nm:N"
)
```
<img width="684" alt="image" src="https://user-images.githubusercontent.com/5186265/61301018-ae167e00-a815-11e9-92c6-90ea3a46eb62.png">

**Comment by mattijn** [comment]
Fixed the typos!

**Comment by joepropellernet** [comment]
That's amazing Matt and Jake! Thanks so much, I had no idea of the different types of geojson and the limitations of Vega-lite. Would it be possible to put the specific projection that Altair prefers in the documentation?

**Comment by mattijn** [comment]
This issue can be closed since the projection part is documented here: https://altair-viz.github.io/user_guide/data.html#projections

**Comment by jakevdp** [comment]
Thanks!
