### ISSUE TITLE
doing histogram efficiently

### ISSUE THREAD

**Issue by python152** [altair-viz/altair#1613]
hi -

I have a dataset with around 1.5 million entries, I'd like to draw a histogram on field A and calculate the mean value for field B. The closest example I can find is to calculate mean value of vote for each  movie rating bin, see below. If I inflate the dataset to `range(500)`, this will crash the chrome tab. 

I would have thought all it takes is one iteration, and calculate mean value for each bin, and draw the bar graph, why  is it taking so long and seem so inefficient? I must have done something wrong here.

``` python
from vega_datasets import data
import pandas as pd

alt.data_transformers.disable_max_rows()
movies = data.movies()

mlist= []
for _ in range(100): ## will crash 
    mlist.append(movies)
    
movies = pd.concat(mlist)

alt.Chart(movies).mark_bar().encode(
    x=alt.X('IMDB_Rating', bin=alt.Bin(maxbins=10)),
    y='mean(IMDB_Votes):Q',
)
```

**Comment by jakevdp** [comment]
The reason it takes so long is that your entire dataset is embedded in the output, and so all 1.5 million entries are being encoded to JSON and written to your notebook. This is one reason for the existence of the max rows warning that you disabled: trying to write this much JSON-encoded data to a notebook is  basically never a good idea.

Now, in your case, you are creating a histogram with 10 bins, so writing 1.5 million rows of data to a JSON encoding is a bit wasteful. There is work being done in the Vega-Lite package to handle this large data case more seamlessly (See https://github.com/vega/scalable-vega) but it's not ready for release yet.

In your case, the best option would probably be to pre-bin your data before sending it to the chart to be encoded. Something like this:
```python
import altair as alt
from vega_datasets import data
import pandas as pd

alt.data_transformers.disable_max_rows()
movies = data.movies()

movies['IMDB_Rating_binned'], bins = pd.cut(movies.IMDB_Rating, 10, retbins=True)
histogram = movies.groupby('IMDB_Rating_binned')[['IMDB_Votes']].mean()
histogram['bin_min'] = bins[:-1]
histogram['bin_max'] = bins[1:]

alt.Chart(histogram).mark_bar().encode(
    x=alt.X('bin_min', title='IMDB Rating'),
    x2='bin_max',
    y='IMDB_Votes'
)
```
![visualization - 2019-07-16T082854 544](https://user-images.githubusercontent.com/781659/61307755-c2ba2e00-a7a3-11e9-9de9-2040a54ca577.png)

**Comment by jakevdp** [comment]
I'm working on a way to push these sorts of aggregations to the Python layer more seamlessly, in the [altair-transform](https://github.com/jakevdp/altair-transform) package. But that's still a work in progress.

**Comment by python152** [comment]
I think I read somewhere about json output will encode all the data points, but it didn't drill in my head until now. Apparently that is too wasteful in this case, so the middle layer (altair) do the aggregation and expose a compact form make perfect sense. Without it, then I probably will have to treat Altair as the final presentation layer, not the data exploration tool (for large dataset). 

thanks for the workaround, appreciate it.
