### ISSUE TITLE
ordering by appearance possible?

### ISSUE THREAD

**Issue by python152** [altair-viz/altair#1614]
hi - it appears the sorting behavior is lexical: 

```python
import pandas as pd
import altair as alt
source = pd.DataFrame({
    'labels': ['(0,4]', '(4,8]', '(8,12]', '(12,24]'],
    'nums': [5, 10, 15, 19]
})
alt.Chart(source).mark_bar().encode(
    x='labels',
    y='nums'
)
```
![visualization](https://user-images.githubusercontent.com/17506882/61385288-15691800-a880-11e9-9162-a78e9cf8cf87.png)

it seems the only way I can make it to order by "appearance" is by repeating:
```python
alt.Chart(source).mark_bar().encode(
    x=alt.X('labels', sort= ['(0,4]', '(4,8]', '(8,12]', '(12,24]']),
    y='nums',
    
)
```
Is there an easy way to deal with it? I had thought `labels:O` should make a difference, but it doesn't. 

thanks

**Comment by jakevdp** [comment]
Inputs are sorted by default (alphabetically in this case). If you want them to be unsorted, you can pass ``sort=None``:
```python
import pandas as pd
import altair as alt
source = pd.DataFrame({
    'labels': ['(0,4]', '(4,8]', '(8,12]', '(12,24]'],
    'nums': [5, 10, 15, 19]
})
alt.Chart(source).mark_bar().encode(
    x=alt.X('labels', sort=None),
    y='nums'
)
```
![visualization - 2019-07-17T081330 457](https://user-images.githubusercontent.com/781659/61387316-c49af480-a86a-11e9-8246-4c811dd1067a.png)
