### ISSUE TITLE
Save as image - error:  looks for executable path to webdriver

### ISSUE THREAD

**Issue by Damorck** [altair-viz/altair#1619]
Thx for all the good work and sharing. The docs are spare on this part. Although path to webdrivers (tested successfully both geckodriver and chromedriver) are correct defined, A. fails when saving to png or svg. Either there are more parameters to set, or this lacks in the docs. Can you reproduce this Issue? This is my code: https://pastebin.com/t6UG75Re

**Comment by jakevdp** [comment]
It sounds like your webdriver is not correctly configured. Unfortunately, there's not enough information in your pasted code to help diagnose the problem.

**Comment by Damorck** [comment]
Thx for quick reply. Issue fixed. The code was run in PyCharm Edu version and needed to be restarted updating the set path. Closing.

**Comment by tttgm** [comment]
Just regarding this setup of chromedriver, is there a way to pass a driver explicitly to `Chart.save()`? I'm struggling to get my webdriver configured. I have the PATH added to my .bash_profile such that
```
echo $PATH
 /mnt/c/Users/path/to/drivers
```
However, when I run the following in a notebook:
```
from selenium import webdriver
webdriver.Chrome()
```
I get the `'chromedriver' executable needs to be in PATH` error.
But creating the driver manually with
```
driver = webdriver.Chrome("/mnt/c/Users/path/to/drivers/chromedriver.exe")
```
works fine, so I was wondering if I could pass this driver to altair?
btw: I'm operating on WSL

**Comment by jakevdp** [comment]
No, there's no way in Altair's current implementation to pass a pre-defined webdriver class. That would be a useful addition, though.
