### ISSUE TITLE
Setting aspect ratio of a chart

### ISSUE THREAD

**Issue by ruben-tsui** [altair-viz/altair#1628]
Hi,

Is there a way to force a specific aspect ratio on a chart? I need to display a line chart with both the x-axis and y-axis drawn to the same scale. In Matplotlib, either of the following two statements
```
ax.set_aspect(aspect='equal')
ax.set_aspect(aspect=1)
```
seems to do the trick, but I have yet to find a similar option/method on Altair.

Thank you.

**Comment by jakevdp** [comment]
I don't believe there's any automatic way to fix the aspect ratio in Altair (see https://github.com/vega/vega-lite/issues/4367 for the relevant vega-lite thread). The best you can do is to set the width and height along with the x and y scale domains.

**Comment by paumillet** [comment]
Hi there,
I'm also looking for a solution for setting "equal aspect" on my graph. I was wondering, since this issue is closed, whether there is a solution to do so with Altair now?
Thanks for your help!

**Comment by itsToggle** [comment]
Hey, is there any update on this? Why is this closed?

**Comment by joelostblom** [comment]
This is closed because it would need to be implemented in Vega-Lite before it can become available in Altair. The progress on that is tracked in this issue https://github.com/vega/vega-lite/issues/4367 (linked above).
