### ISSUE TITLE
How to suppress the automatic ordering of x?

### ISSUE THREAD

**Issue by Alalalalaki** [altair-viz/altair#1630]
I find whether I specify ':N' or ':O', it always automatically order the x column of string type. 

I know that I can alternatively set alt.X(sort=), but this will be annoying when working with dataframe that have long chaining methods.

**Comment by Alalalalaki** [comment]
Find the answer.

**Comment by jakevdp** [comment]
For anyone coming across this on Google, the answer is to use ``sort=None``.
