### ISSUE TITLE
Can't set dimension with `configure_view ` for non-quantitave data

### ISSUE THREAD

**Issue by SuperShinyEyes** [altair-viz/altair#1631]
- Altair version: 3.1.0
- Python: '3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) \n[GCC 7.3.0]'

For quantitave data, it's straight-forward to set a dimension:
```python
from vega_datasets import data

iris = data.iris()

alt.Chart(iris).mark_point().encode(
    x='petalWidth',
    y='petalLength',
    color='species'
).configure_axis(
    grid=False
).configure_view(
    strokeWidth=0,
    width=1000
)
```
![visualization](https://user-images.githubusercontent.com/5738363/62032166-ab426280-b1f1-11e9-8663-13c78cf33ea6.png)

However, you can't set a dimension for non-quantitave data:
```python
alt.Chart(iris).mark_point().encode(
    x='petalWidth:N',
    y='petalLength',
    color='species'
).configure_axis(
    grid=False
).configure_view(
    strokeWidth=0,
    width=1000
)
```
![visualization (1)](https://user-images.githubusercontent.com/5738363/62032303-01afa100-b1f2-11e9-9260-2a02ec5dffde.png)

**Comment by jakevdp** [comment]
If you want to directly set the width of the chart, then you should use the ``width`` and ``height`` property:
```python
alt.Chart(iris).mark_point().encode(
    x='petalWidth:N',
    y='petalLength',
    color='species'
).configure_axis(
    grid=False
).configure_view(
    strokeWidth=0,
).properties(
    width=1000
)
```
The width/height properties directly specify the width and height of a single panel chart. This is in constrast to the width/height configurations, which can be thought of as a default that the chart falls back to if other chart elements don't override them.

More details on the precise sizing logic used by the vega-lite renderer can be found here: https://vega.github.io/vega-lite/docs/size.html#default-width-and-height

**Comment by SuperShinyEyes** [comment]
Thank you very much for your quick reply @jakevdp. I'm very excited to use more modern plotting library. Please keep up the great work!
