### ISSUE TITLE
Sorting Colors with errorbars

### ISSUE THREAD

**Issue by deisi** [altair-viz/altair#1635]
Hey, I'm trying to sort a colored plot with error bars and encounter an inconsistency/bug.

``` python
data = pd.DataFrame(
    [[2, 2, 1, 'a'],[3, 5, 1, 'b'],[4, 3, 1, "c"]],
    columns=['pump_freq', 'value', 'error', 'lipid']
)

base = alt.Chart(data).encode(
    alt.X('pump_freq:Q'),
    alt.Y(
        'value', 
    ),
    yError=alt.YError('error:Q'),
    color=alt.Color(
        'lipid', 
        sort=['b']
    )
)
chart = base.mark_point()+base.mark_errorbar()
chart
```

This will not sort due to the `base.mark_errorbar()`. If you remove it it will work though. Any suggestion what is going on?

**Comment by jakevdp** [comment]
This looks a lot like #820, which was fixed, but I suspect this code path was not.

A workaround is to use ``chart.resolve_scale(color='independent')``.

**Comment by deisi** [comment]
Okay this almost gets me there, but now I got a little problem with `mark_point` options. The example I gave was simlified and my real chart is a bit more complex. I need filled marks. Thus I use:

``` python
data = pd.DataFrame(
    [[2, 2, 1, 'a'],[3, 5, 1, 'b'],[4, 3, 1, "c"]],
    columns=['pump_freq', 'value', 'error', 'lipid']
)

base = alt.Chart(data).encode(
    alt.X('pump_freq:Q'),
    alt.Y(
        'value', 
    ),
    yError=alt.YError('error:Q'),
    color=alt.Color(
        'lipid', 
        sort=['b']
    )
)
chart = base.mark_point(size=100, filled=True)+base.mark_errorbar()
chart = chart.resolve_scale(color='independent')
chart
```

But that now gives me two legends for the color.

**Comment by jakevdp** [comment]
- when scales are independent, you'll have two legends. That's why this is not a complete solution, but a workaround for a bug
- To remove one of the legends, set ``legend=None`` for one of the charts
- ``resolve_scale()`` does not transform the chart into a facet chart, it sets the scale resolution on a compound chart.

**Comment by deisi** [comment]
It took me years to understand matplotlib and then you come a long with this crazy Grammer or graphics thing and render all my matplotlib knowledge useless and make me start from scratch again. Thx for the explanation and the help. Also for the project in general. It's really an awesome thing.

**Comment by jakevdp** [comment]
#1636 fixes the issue of defining ``resolve_*()`` for charts where it shouldn't be allowed

**Comment by joelostblom** [comment]
@deisi I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
