### ISSUE TITLE
Using alt.data_transformers.enable on azure notebook

### ISSUE THREAD

**Issue by prasoon2211** [altair-viz/altair#1648]
I had more than 5000 rows of data so I followed the documentation to use the JSON data transformer but with it, I see no data in the plot:
![image](https://user-images.githubusercontent.com/2565248/62777509-115e9d80-baae-11e9-81e5-b5e566b51272.png)

I also tried installing `altair-data-server` with `jupyter-server-proxy` and then using `alt.data_transformers.enable('data_server_proxied')` but it still results in the same problem.

I also tried running the [colab notebook](https://colab.research.google.com/github/altair-viz/altair_data_server/blob/master/AltairDataServer.ipynb) linked on the [altair data server project](https://pypi.org/project/altair-data-server/) but this process fails in the colab notebook as well.

In the end, I ended up using a local jupyterlab instance but it would be nice to be able to use cloud based notebooks with altair

**Comment by jakevdp** [comment]
Please see https://altair-viz.github.io/user_guide/faq.html#maxrowserror-how-can-i-plot-large-datasets

As mentioned there, the local filesystem and dataserver approaches you tried may not work on some cloud-based notebooks, but there are other options available.
