### ISSUE TITLE
Hide top and right axis (gray lines) in a layerChart Altair

### ISSUE THREAD

**Issue by 0lilauro** [altair-viz/altair#1649]
##### I already try to use the solution from [this](https://github.com/altair-viz/altair/issues/975) issues, but i cannot set grid as false coz im using layerChart. 

``` python
import altair as alt
alt.data_transformers.disable_max_rows()
alt.renderers.enable('notebook')


br_states = alt.topo_feature('https://servicodados.ibge.gov.br/api/v2/malhas/35/?formato=application/vnd.geo+json', 'feature')

background = alt.Chart(br_states).mark_geoshape(
    fill='lightgray',
    strokeWidth=1,
    stroke='black',
    strokeOpacity=0
).properties(
    width=400,
    height=300
)

points = alt.Chart(rub_coord).mark_circle(
    size=20,
    opacity=0.3,
    color='steelblue',
    strokeOpacity=0.0,
).encode(
    longitude='lon:Q',
    latitude='lat:Q',
    tooltip=['city']
)

background + points
```

#### The preview is:

![visualization (1)](https://user-images.githubusercontent.com/39709755/62825810-e2b4f580-bb87-11e9-91ed-c8f77d2b0bf9.png)

**Comment by jakevdp** [comment]
You can use ``configure_view(stroke=None)``:
```python
(background + points).configure_view(stroke=None)
```

**Comment by 0lilauro** [comment]
Oh man it's works, Thank you !!!!!

**Comment by IndianBOYinDetroit** [comment]
@jakevdp (stroke=None) works fine if I don't put  background='#F0F0F0'. I mean stroke is working with white background only. Am I doing something wrong ?

**Comment by joelostblom** [comment]
@IndianBOYinDetroit It should work also with background colors, make sure you turn off the grid as well:

```py
import altair as alt
import pandas as pd

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

alt.Chart(source, background='black').mark_bar().encode(
    x='a',
    y='b'
).configure_axis(grid=False).configure_view(stroke=None)
```

![image](https://user-images.githubusercontent.com/4560057/108777109-2a0b9880-7518-11eb-833c-4a8ab25ab997.png)
