### ISSUE TITLE
Javascript Error: Duplicate signal name: "selector011_tuple"

### ISSUE THREAD

**Issue by ivvv** [altair-viz/altair#1652]
Hi,

When using selector, I end up with the javascript error in the subject. Here is a code with toy data.

If I do `alt.vconcat(points,sed1,sed2)` it works, but this is not what I want. I'd like to have both `sed1` and `sed2` in the same subplot, i.e. `alt.vconcat(points,sed1+sed2)`. Any hints on what I'm doing wrong?

Thanks!
```
import pandas as pd
import altair as alt
import numpy as np
#
# create a toy dataset
#
df = pd.DataFrame({'id': np.arange(10)},dtype=np.int8)
df['a1'] = np.linspace(0,5,10)
df['a2'] = df['a1'] + 1
df['a3'] = df['a1'] + 2
#
df['b1'] = np.linspace(5,0,10)
df['b2'] = df['b1']*2
df['b3'] = df['b1']*4
#
# altair viz part
#
selector = alt.selection_single(empty='all', fields=['id'])

base = alt.Chart(df).properties(
    title="Test",width=800,height=200).add_selection(selector).transform_fold(
    ['a1','a2','a3'],
    as_=["key1","value1"]).transform_fold(
    ['b1','b2','b3'],
    as_=["key2","value2"])

points = base.mark_point(filled=True, size=50).encode(
    x=alt.X(
        'id:N',
        axis=alt.Axis(title='Index')
    ),
    y=alt.Y(
        'ratio:Q',
        axis=alt.Axis(title="Ratio (b3-b2)/(a3-a2)")
    ),
    color=alt.condition(selector, 'a1', alt.value('lightgray'), legend=None),
    tooltip=['id']
).transform_calculate(
    ratio="(datum.b3-datum.b2)/(datum.a3-datum.a2)").interactive()

sed1 = base.mark_line(point=True).encode(
    x=alt.X('key1:O'),
    y=alt.Y('value1:Q'),
).transform_filter(
    selector
    )

sed2 = base.mark_line(point=True).encode(
    x=alt.X('key2:O'),
    y=alt.Y('value2:Q'),
).transform_filter(
    selector
    )
#
# this one works
#alt.vconcat(points,sed1,sed2)
#
# this one I want but it does not work
alt.vconcat(points,sed1+sed2)
```

**Comment by jakevdp** [comment]
You're implicitly adding the selector in multiple places (because each time you modify base, the selector comes with it). You should remove the ``add_selection(selector)`` from your base chart, and instead use
```
alt.vconcat(points.add_selection(selector),sed1+sed2)
```

**Comment by ivvv** [comment]
Thanks Jake, this solved the javascript error. Although I still have not found a way to use an index for the x-axis. From my example above, (a1,a2,a3) and (b1,b2,b3) y-axis values are for the same x-axis (index, [1,2,3] or something else [x1,x2,x3]). 

With the current implementation of 'key1' and 'key2' sed1 and sed2 are shown but at the different keys and so I have 6 instead of 3 x-axis data points. I have tried `'key:Q'` or omitting the `alt.X()` , `transform_calculate` with expression with `sequence(3)` etc, but nothing really solved it.

Another way could be to restructure the dataframe with pandas, but I thought a simple plot of values against their index should be possible.

**Comment by jakevdp** [comment]
I'm sorry, it's not clear from your description what you're trying to do and what the problem is. Could you give an example?

**Comment by ivvv** [comment]
OK, I want to get the following figure, after selecting a point from the points panel:

![outut](https://user-images.githubusercontent.com/7148876/63042021-701a8180-bec9-11e9-959f-b76133508743.png)

while with your suggestion and all my attempts I could only get to this one:

![visualization](https://user-images.githubusercontent.com/7148876/63042055-83c5e800-bec9-11e9-9499-8a6af95af2eb.png)

**Comment by jakevdp** [comment]
The easiest way to do this is to use ``base=alt.Chart(df.reset_index())`` and then use ``x='index'`` rather than ``x='key1'`` and ``x='key2'``.

**Comment by ivvv** [comment]
I have tried your suggestion and it seems to work! Thanks.
