### ISSUE TITLE
Data-dependant stroke dash type for line charts

### ISSUE THREAD

**Issue by confusedmatrix** [altair-viz/altair#1653]
From the documentation I don't believe there is a way to set the stroke dash type to be determined based on the data itself. I see you can add a fixed strokeDash as an attribute to the mark_* methods (https://altair-viz.github.io/user_guide/marks.html#mark-properties) but this is quite limiting. For example I wish to create a plot where one field is denoted by color and another denoted by stroke dash length. The vega spec certainly supports stroke dash configuration (https://vega.github.io/vega/docs/marks/line/).

**Comment by jakevdp** [comment]
This is not supported in Vega-Lite. The relevant feature request is here: https://github.com/vega/vega-lite/issues/1855

**Comment by pylang** [comment]
@jakevdp This can be closed.

Use the strokeDash channel and give range, e.g.

    .mark_line(strokeDash=[5, 10])

- Merged into Vegalite https://github.com/vega/vega-lite/pull/5860
- Related issue: https://github.com/altair-viz/altair/issues/845

**Comment by jakevdp** [comment]
The strokedash encoding was added in Altair 4.1. Example here: https://altair-viz.github.io/gallery/multi_series_line.html
