### ISSUE TITLE
Combining fields/encodings in legends

### ISSUE THREAD

**Issue by confusedmatrix** [altair-viz/altair#1654]
I can't seem to understand if it is possible to combine fields/encodings in the legend or not. For example say we have two fields, one denotes the color and the other denotes the opacity. The legend currently groups the distinct options for each field under its own heading in the legend. Is it possible to, instead, list the combinations of the both fields (e.g. red & opacity 0.5, red & opacity 1 etc) under one heading?

**Comment by jakevdp** [comment]
If you use the same field for each encoding, the chart defaults to a shared legend for all encodings. e.g.
```python
import altair as alt
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_point().encode(
  x='Horsepower',
  y='Miles_per_Gallon',
  color='Origin',
  opacity='Origin',
  shape='Origin'
)
```
![visualization](https://user-images.githubusercontent.com/781659/62882693-50c3fe80-bce7-11e9-98f9-6f87f9b54b91.png)
