### ISSUE TITLE
Cancelling the 0.5s on x-axis

### ISSUE THREAD

**Issue by JinjinJanelle** [altair-viz/altair#1655]
Altair automatically added float numbers on the axis between the whole numbers. Is there a way to cancel it?
Thank you!
![Screen Shot 2019-08-12 at 10 24 56 AM](https://user-images.githubusercontent.com/49166499/62884490-8965d700-bceb-11e9-8857-a5ce25e24fde.png)

**Comment by jakevdp** [comment]
You can set the ``tickMinStep`` property of the axis. For example:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'x': range(5),
    'y': range(5)
})

alt.Chart(df).mark_point().encode(
    alt.X('x', axis=alt.Axis(tickMinStep=1.0)),
    alt.Y('y')
)
```
![visualization (1)](https://user-images.githubusercontent.com/781659/62884808-47896080-bcec-11e9-874f-e74d1b3ca8f8.png)

**Comment by JinjinJanelle** [comment]
Thank you! This is very useful!

**Comment by morberg** [comment]
In Altair 4.1.0 the gridlines still remain, although the ticks are no longer shown. Is this a bug? I would expect the gridlines to disappear as well as in your screenshot.

<img width="453" alt="image" src="https://user-images.githubusercontent.com/956034/97585748-c81fa400-19f9-11eb-9521-f7bcf1faf439.png">

**Comment by aurimas-ww** [comment]
It appears that `tickMinStep` no longer works in Altair 5.0.1 - the example from @jakevdp now produces a chart with 0.5 tick labels, too. Is there a different solution for this now? From what I can see, the `tickMinStep` parameter is still valid in Altair 5.

**Comment by zizaozi** [comment]
Using tickCount instead in jakevdp's example works for me
`alt.X('x', axis=alt.Axis(tickCount=len(df)))`
