### ISSUE TITLE
Limitation of ticks

### ISSUE THREAD

**Issue by Amarounek** [altair-viz/altair#1657]
Hello,

I have an issue of the ticks on the x-axis, which contains 365 (366) ticks. If I download the bar chart in SVG and open in Google Chrome - There is no issue with visualisation and there are only a few ticks. However, If I open it in **Affinity Designer**, the ticks on x-axis are one big mess... Is there some solution about how to limit the number of ticks on axis? Thank you!

![image](https://user-images.githubusercontent.com/36733547/63007885-d8de0b80-be81-11e9-8423-62e9106bbf03.png)

My (minimal) dataset is:
```
# Packages
import datetime
import os, sys
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import matplotlib.ticker as plticker
import altair as alt
from vega_datasets import data

data = {'DAY' : ['2019-05-01', '2019-05-02', '2019-05-03', '2019-05-04', '2019-05-05'],
        'RAIN' : [0.9, 0.9, 0.9, 0.9, 0.9],
        'RR_MIDDLE' : [2.80, 2.80, 2.80, 2.80, 2.80],
        'CONDITION_RR' : ['wet', 'wet', 'wet', 'wet', 'wet'],
        'CONDITION_PR' : ['dry', 'dry', 'dry', 'dry', 'dry'],
        'SEASON' : ['Intermittent_Season', 'Dry_Season', 'Intermittent_Season', 'Wet_Season', 'Intermittent_Season'],
        'MONTH' : ['Apr 2019', 'Apr 2019', 'Apr 2019', 'Apr 2019', 'Apr 2019'],
        'SEASON_NUM' : [1.0, 1.0, 1.0, 1.0, 1.0],
        'YEAR' : [2019, 2019, 2019, 2019, 2019],
        'DOY' : [121, 122, 123, 124, 125],
       }
RSDF9 = pd.DataFrame(data)
RSDF9['DAY'] =  pd.to_datetime(RSDF9['DAY'], errors='ignore')
pd.to_numeric(RSDF9['DOY'])
pd.to_numeric(RSDF9['YEAR'])

alt.renderers.enable('notebook')
alt.data_transformers.disable_max_rows()

bar2 = alt.Chart(RSDF9).mark_bar().encode(
    alt.X('DOY:O', title='day', axis=alt.Axis(tickCount=2)),
    alt.Y('year(DAY):O', title='year'),
    color='SEASON:N',
    order=alt.Order("SEASON", sort="ascending")
)
(bar2).properties(width=600).configure_axisX(labelAlign="right", labelAngle=-45, labelPadding=8)
```

Thanks!

**Comment by jakevdp** [comment]
Could you include a full code snippet to reproduce this? Thanks.

**Comment by Amarounek** [comment]
Well, I edited the text in the first message. Hope that will help...

Anyhow, I try to visualize changes in a dry and wet season (and intermittent) through the year from the year 1980 to the present day...

If I open the SVG file in Chrome, it looks normal, however in Affinity it shows every day on x-axis. 
![image](https://user-images.githubusercontent.com/36733547/63080571-b27fa500-bf41-11e9-872b-5f3ee6c817ff.png)

**Comment by jakevdp** [comment]
It would be much more helpful if you provided a code snippet that defines RFDS, rather than a print-out that I'd have to figure out how to parse.

**Comment by Amarounek** [comment]
Hello,

Here is a Jupyter notebook with CSV file if it is what you need! :-)

**Comment by Amarounek** [comment]
Hello

Here is a code snippet (Jupyter notebook) and CVS file with data called RFDS (Rolling sum data frame). I hope that it will help you

BTW: I am newbie on github and also to data science. Is the zp best way how to provide a code snippet? Thx! 

[Snippet.zip](https://github.com/altair-viz/altair/files/3509583/Snippet.zip)

**Comment by jakevdp** [comment]
The best way to provide a code snippet is inline in the comment, like you did initially. If an issue requires me to guess what code someone is running, or to download and extract a zip file, I usually just ignore it. It's helpful if you include a minimal reproducible example (see https://stackoverflow.com/help/minimal-reproducible-example for some tips)

**Comment by Amarounek** [comment]
Okey I've changed the initial message and put here reproducible example... Thx

**Comment by jakevdp** [comment]
OK, when I run your code I see this:
![visualization - 2019-08-19T081729 251](https://user-images.githubusercontent.com/781659/63277213-cbe26300-c259-11e9-94f8-9d315e7e8b57.png)

I tried opening the figure in several SVG viewers, but it looks the same in each.

**Comment by jakevdp** [comment]
I don't have access to Affinity Designer... if the issue only appears there, perhaps you can report it to that tool?

**Comment by Amarounek** [comment]
Well yeah, I also don't have a problem if I use only a few days in Affinity Designer, however, if I use the whole year and 365 (366) records, the affinity overlaps all days over each other and Google chrome not a takes only fiw ticks days. In the end, I don't really how the SVG format works, but I would say so that it will have fixed information about a number of ticks. However, it seems to me that every software works differently with a SVG files and some information are "hidden" inside file and software will make an interpretation and final visualization. 

Matplotlib has some option to handle the ticks and their frequencies. However, I will it to ajdust it by harder way :-)   

Anyway thanks!

**Comment by jakevdp** [comment]
OK - if you can create a reproducible example that reflects the problem you're seeing, I"m happy to try and help.

**Comment by jakevdp** [comment]
I'm closing, because it's been a few months without response. Let me know if you have further questions.
