### ISSUE TITLE
Producing grouped bar plot with Dual Axis

### ISSUE THREAD

**Issue by JuanSampieri** [altair-viz/altair#1659]
Hi team, 

I've been trying to produce a plot like the one below, but I've unable to figure out how
I'm trying to have dual axis.
![Picture1](https://user-images.githubusercontent.com/53542530/63116721-4ebca280-bf68-11e9-8ce0-3ba139d38fac.png)

This is the closest I've got, but I don't know how to separate the bars. 
Any help will be really appreciated!
```python
#Data
performance_summary = pd.DataFrame(columns = ['index', 'Average Annual Return', 'Sharpe Ratio'])
performance_summary.loc[0] = ['Equity',8.5, 0.55]
performance_summary.loc[1] = ['Bond',4.98,0.67]

#Plot
return_plot = alt.Chart(performance_summary).mark_bar(color = "blue",width=50).encode(
    x='index',
    y=alt.Y('Average Annual Return',scale=alt.Scale(domain=[0,10]),stack=None),
)
sharpe_plot = alt.Chart(performance_summary).mark_bar(color = "black",width=100).encode(
    x=alt.X('index'),
    y=alt.Y('Sharpe Ratio', scale=alt.Scale(domain=[0,1]),stack=None),
)
(sharpe_plot+return_plot).resolve_scale(y='independent')
```

![Picture2](https://user-images.githubusercontent.com/53542530/63116852-9d6a3c80-bf68-11e9-9c4a-829f0ff602ea.png)

**Comment by jakevdp** [comment]
Probably best would be to follow https://altair-viz.github.io/gallery/index.html and do something like this:
```python
alt.Chart(
    performance_summary
).transform_fold(
    ['Average Annual Return', 'Sharpe Ratio'],
    ['type', 'value'],
).mark_bar().encode(
    column='type:N',
    color='index:N',
    x='index:N',
    y='value:Q',
).properties(
    width=100
)
```
![visualization (4)](https://user-images.githubusercontent.com/781659/63129682-0eabee80-bf6d-11e9-93cb-93611dd8c24b.png)

I'd probably avoid a dual axis for grouped bar charts, because to my eye the result is very misleading.

**Comment by JuanSampieri** [comment]
> Probably best would be to follow https://altair-viz.github.io/gallery/index.html and do something like this:
> 
> ```python
> alt.Chart(
>     performance_summary
> ).transform_fold(
>     ['Average Annual Return', 'Sharpe Ratio'],
>     ['type', 'value'],
> ).mark_bar().encode(
>     column='type:N',
>     color='index:N',
>     x='index:N',
>     y='value:Q',
> ).properties(
>     width=100
> )
> ```
> 
> ![visualization (4)](https://user-images.githubusercontent.com/781659/63129682-0eabee80-bf6d-11e9-93cb-93611dd8c24b.png)
> 
> I'd probably avoid a dual axis for grouped bar charts, because to my eye the result is very misleading.

Thank you! I'll use this approach :)
