### ISSUE TITLE
Refine data generator support

### ISSUE THREAD

**Issue by jheer** [altair-viz/altair#1660]
Vega-Lite supports _data generators_ for geo spheres, geo graticules, and numeric sequences: https://vega.github.io/vega-lite/docs/data.html#data-generators

Altair includes auto-generated classes (e.g., `alt.GraticuleGenerator`, `alt.GraticuleParams`) corresponding to these features. However, passing a generator class as the data for a Chart can result in warning output:

```
UserWarning: data of type <class ‘altair.vegalite.v3.schema.core.SphereGenerator’> not recognized
warnings.warn(“data of type {} not recognized”.format(type(data)))
```

Moreover, code like `alt.GraticuleGenerator(graticule=alt.GraticuleParams(...))` feels unnecessarily verbose. Perhaps a more concise syntax would be helpful? For example, merging the generator and params into a single call... For comparison, the Vega-Lite JavaScript API includes top-level methods for generators (`vl.graticule()`); https://observablehq.com/@vega/vega-lite-cartographic-projections provides an example of their use.

**Comment by jakevdp** [comment]
Great suggestion! I think something like ``alt.graticule()`` or ``alt.data.graticule()`` would make sense.

What version were these added to Vega-Lite?
