### ISSUE TITLE
y-aggregation with interactivity causes Vega error

### ISSUE THREAD

**Issue by Toxyl** [altair-viz/altair#1663]
For some reason the combination of the `y='count()'` aggregation and `interactive()` mode keeps failing for me with the error `JavaScript Error: e is undefined`. See the code below:

```
import altair as alt
from pandas import DataFrame

data = DataFrame({'A': ['H','T','F','A','H','T','F','A'], 'B': [1, 2, 3, 4, 4, 3, 2, 1]}, columns= ['A', 'B'])

# Interactivity without y-aggregation works:
alt.Chart(data).mark_bar().encode(x = 'B').interactive().serve()

# y-aggregation without interactivity works, too:
alt.Chart(data).mark_bar().encode(x = 'B', y = 'count()' ).serve()

# Interactivity with y-aggregation does NOT work:
alt.Chart(data).mark_bar().encode(x = 'B', y = 'count()' ).interactive().serve()
```

OS: Kali GNU/Linux Rolling 2019.3
Browser: Firefox 60.8.0esr

**Comment by jakevdp** [comment]
It looks like this is a known failure in Vega-Lite, unfortunately.

**Comment by Toxyl** [comment]
Is there a known way / hack to get around it?

**Comment by joelostblom** [comment]
The provided example is working for me on Vega-Lite 4.2.0 so closing, please re-open if you are still seeing the issue.
