### ISSUE TITLE
inline data in html and toggle full screen

### ISSUE THREAD

**Issue by christofer-f** [altair-viz/altair#1669]
Hi all and thank you for an amazing framework... 
I have two questions:

I would like to save my charts using local embedded data in the HTML file
I would like to toggle the charts in the HTML file to show fullscreen

I have this snippet of code:

```
data = pd.DataFrame({
    'timestamp': [pd.Timestamp(2017, 1, i) for i in range(1, 31)],
    'value': np.random.randn(30).cumsum()
})

foo = alt.Chart(data).mark_line().encode(
    x='timestamp:T',
    y='value:Q'
).interactive()

foo.save('foo.html')
```

To use data locally I manually edit the file like this...
```
...
 <script>
    (function(vegaEmbed) {
      var spec = {"config": {"view": {"width": 400, "height": 300}, "mark": {"tooltip": null}}, "data": {"url": "some-local-file.json", "format": {"type": "json"}}, 
...
```

and I change the data to something like this:
```
...
"data": {"values": 
	  [{"timestamp":"2017-01-01T00:00:00","value":-0.1626920958},{"times
...
```

My question is if I can do this without manually edit the HTML file.

My second question:
Can I can toggle a fullscreen view for the generated chart in some way?
It would be great.

**Comment by jakevdp** [comment]
It appears that you have the JSON data transformer enabled, which saves your data to disk before creating the chart. To save the data directly in the HTML, enable the default transformer:
```python
with alt.data_transformers.enable('default'):
    chart.save('foo.html')
```
(if you don't call ``alt.data_transformers.enable('json')`` in the first place, this step is not necessary).
