### ISSUE TITLE
Altair Chart is not showing in Jupyter Notebook

### ISSUE THREAD

**Issue by vbeer008** [altair-viz/altair#1670]
Hi, 
    Tried many times to show the chart in notebook, but didn't work and no error from the code as well. Can someone please help and guide me please?

![github_altair_chart_not_showing](https://user-images.githubusercontent.com/54382484/63478254-73ff6280-c4cc-11e9-86e7-8c29dd9d80e5.jpg)

    

And.. I am using 
C:\>pip show altair
Name: altair
Version: 3.2.0

C\:>pip show notebook
Name: notebook
Version: 6.0.0

**Comment by jakevdp** [comment]
Can you open the javascript developer console and see if there are any errors shown? Also, what version do you see with ``pip show vega``?

**Comment by vbeer008** [comment]
C:\>pip show vega
Name: vega
Version: 2.5.0

**Comment by vbeer008** [comment]
Hi Jake,

     I just installed Google Chrome and open the notebook there. Then, it looks like it is working now. I think the problem is from MS internet Explorer on my machine. :)

**Comment by jakevdp** [comment]
OK, great

**Comment by vbeer008** [comment]
Hi Jake, thanks for your quick response here. Much appreciated..  :)

**Comment by basheerkafaf** [comment]
same thing here 
![image](https://user-images.githubusercontent.com/61880491/78957252-18590800-7aa2-11ea-81b9-5f6aea26c5a5.png)

**Comment by jakevdp** [comment]
See https://altair-viz.github.io/user_guide/troubleshooting.html#chart-does-not-display-at-all
