### ISSUE TITLE
Pandas 'latex' columns cannot be plotted

### ISSUE THREAD

**Issue by david-waterworth** [altair-viz/altair#1671]
It's possible to name and access columns in Pandas using `latex` syntax, i.e. 

`data['$\Delta T$'] = data['$T_r$'] - data['$T_s$']`

It's nice as jupyter and matplotib support this. I understand `altair` won't render this correctly, but it's not working at all
```
alt.Chart(data.reset_index()).mark_point().encode(
    x='$\Delta T$',
    y='P',
    color='equipment',
).interactive()
```

produces a blank chart, not using $$ in the pandas columns fixes the issue.

**Comment by jakevdp** [comment]
The backslash is a special character in encoding names that needs to be escaped. If you change ``x='$\Delta T$'`` to ``x=r'$\\Delta T$:Q'``, it will work.

For more information on escaping and handling of special characters in encoding field names, see https://vega.github.io/vega-lite/docs/field.html. But I find it most convenient to work with column names that do not have special characters.
