### ISSUE TITLE
Group colors a second time

### ISSUE THREAD

**Issue by kaisengit** [altair-viz/altair#1672]
I am wondering about the following situation which I come across quite a few times. Say my data has two main groups like this:
![visualization (1)](https://user-images.githubusercontent.com/29574032/63526274-67e0c880-c4ff-11e9-989d-bff4dbc3ab0c.png)

I've the split the colors among those two groups. Now additionally I'd like to vary the color hues within the two groups according to a second feature like `site` in this example.
So basically I want to have 'nominal' colors between main groups and then 'ordinal' colors within those groups for a second feature. Is there any way to this?
```
from vega_datasets import data

df1=data.barley()

df1['yield_norm'] = df1.groupby(['year', 'variety'])['yield'].transform(lambda x: x/x.sum())

sub_group1_mask = df1['site'].isin(['University Farm', 'Waseca', 'Morris'])
sub_group2_mask = df1['site'].isin(['Crookston', 'Grand Rapids','Duluth'])
df1['main_group'] = 'main'
df1['main_group'][sub_group1_mask] = 'main1'
df1['main_group'][sub_group2_mask] = 'main2'


base = alt.Chart().mark_bar().encode(
    x=alt.X('yield:Q', stack='zero'),
    y=alt.Y('variety:N'),
    tooltip=['yield:Q', 'variety:N', 'year:O', 'yield_norm'],
    order='site:N'
)

bars = base.encode(
    color=alt.Color('main_group:N'),
)

text = base.mark_text(dx=-15, dy=3, color='black').encode(
    text=alt.Text('yield:Q', format='.0f'),
)

alt.layer(bars, text, line).facet(column=alt.Column('year:O'), data=df1)
```

Adding `opacity=alt.Opacity('site:O')` after color works to some degree:
![visualization (2)](https://user-images.githubusercontent.com/29574032/63526503-ce65e680-c4ff-11e9-96b0-f0376fdc0291.png)
But as you can see it varies opacity not only within the two main groups but across all 'sites'. Also, it does not look as nice as for example the the 'blues' color scheme.

**Comment by jakevdp** [comment]
I don't think Vega-Lite has a clean abstraction for this. But it could be done in a kind of hacky way, I think, by using a calculate transform to map your fields to computed color values and then using those directly in the scale. Or alternatively, you could use a calculate transform to combine your inputs into a single field, and then provide a custom color scheme

**Comment by kaisengit** [comment]
Are there any altair commands which would allow me to get the color values for different color schemes and number of features?

In my example, is there a way to get the color values for n=3 for the color schemes blues and greens for example? So basically access to the color values shown here: https://vega.github.io/vega/docs/schemes/

**Comment by jakevdp** [comment]
No,  there's no existing command for that in Altair.

**Comment by joelostblom** [comment]
This would need to be filed as a feature request on the VegaLite issue tracker. Closing as there is nothing that can be done on the altair side of things.
