### ISSUE TITLE
Passing encoding directly as constructor?

### ISSUE THREAD

**Issue by MarshallCharles** [altair-viz/altair#1674]
Hello, could you please provide an example of a chart with the encoding passed as a constructor as in the following example: 

```
chart = alt.Chart(df, mark = 'rect', encoding = '?').properties(\
        title = 'THIS IS MY TITLE').interactive()
```

I'm having trouble creating charts this way, is it possible?
In what format should the data passed to the encoding argument be?

Thanks!

**Comment by jakevdp** [comment]
It's possible; if you look at the doc string for ``alt.Chart`` you'll see that the encoding argument should be of type ``alt.FacetedEncoding``. So you can do something like this:
```python
alt.Chart(
    data='data.txt',
    mark='point',
    encoding=alt.FacetedEncoding(
        x=alt.X(
            field='x',
            type='quantitative'
        )
    ),
    title='MY TITLE'
) 
```
which is equivalent to the more idiomatic
```python
alt.Chart('data.csv').mark_point().encode(
    x='x:Q'
).properties(
    title='MY TITLE'
)
```

**Comment by MarshallCharles** [comment]
Perhaps my question wasn't clear, it was more so regarding what `alt.FacetedEncoding()` and `alt.MarkDef()` do. Perhaps laziness on my part for not looking into it.

In my case, I am trying to automate creation of plots. My current solution involves calling `alt.Chart()` and passing it all the data required to make a variety of different plots. 

As such, I'm generally trying to avoid using additional methods like `alt.FacetedEncoding` which treat data that I already have. This can be done by passing key, values to constructors of `alt.Chart()`, such as : `alt.Chart(mark = 'point', encoding = dic)`, where `dic = {'x': {'type': 'ordinal', 'field': 'x'}, 'y': {'type': 'quantitative', 'field': 'y'}}`.

Generally speaking, it seems I'm not losing much functionality this way, it's just less idiomatic.

**Comment by jakevdp** [comment]
If you want to avoid Altair's API almost entirely, you could just pass a dict containing a vega-lite specification; for example:
```python
alt.Chart.from_dict({
    'data': {'url': 'mydata.csv'},
    'mark': 'point',
    'encoding': {
        'x': {'field': 'x', 'type: 'quantitative'},
    }
})
```


})
