### ISSUE TITLE
How the set x axis to auto scale correctly to display value?

### ISSUE THREAD

**Issue by vbeer008** [altair-viz/altair#1675]
Hi, 
   I setup a chart with properties(width=800,height=400). Chart show correctly, but value of x-axis is not showing due to too much data for x-axis. Is there any way to make the x-Axis to show the value itself within the range of x-value? 

```python
alt.Chart(df, title="Event Class DB Time%").mark_line().encode(
    x=alt.X(
        "SNAP_ID:N",
        title="SNAP ID"       
    ),
    y=alt.Y(
        "PCTDBT:Q",
        title="% DBTIME"
    ),
    color=alt.Color(
        "WAIT_CLASS:N",
        title="Wait Class"          
    )
).properties(width=800,height=400)
```
    
![github_altair_chart_x-axis](https://user-images.githubusercontent.com/54382484/63571725-662d0880-c5c4-11e9-8c17-e54530d2610f.jpg)

**Comment by jakevdp** [comment]
For nominal labels like these, you can set the ``labelOverlap`` axis property to True, and it will remove labels to reduce overlap.

If your data are quantitative, you should use type ``"Q"`` rather than type ``"N"``, in which case the quantitative scale will adjust to your data automatically.

```python
x=alt.X(
        "SNAP_ID:N",
        title="SNAP ID",
        axis=alt.Axis(labelOverlap=True),
    ),
```

**Comment by vbeer008** [comment]
Hi Jake, what if the x-axis is date format, does it scale automatically or can use labeloverlap=true?

**Comment by jakevdp** [comment]
Unbinmed temporal data should scale ticks automatically.

**Comment by vbeer008** [comment]
Hi Jake, it works as expected from your suggestion. Thanks for your  help again.
