### ISSUE TITLE
Best way to get tabular output after applying brush?

### ISSUE THREAD

**Issue by Datamance** [altair-viz/altair#1676]
Hey there! Loving Altair.

It would seem that Altair doesn't have a tabular output mechanism (unless I'm missing something). The situation where this would be useful is in generating an HTML table based off of a selection from a given chart.

Is there a current workaround or suggested way to do this? Eventually I would love to build a two-way integration between [DataTables](https://datatables.net) and the Vega-generated graphs.

Thanks again for a great library!

**Comment by jakevdp** [comment]
Altair doesn't have built-in tables, but you can do something like this: https://altair-viz.github.io/gallery/scatter_linked_table.html
