### ISSUE TITLE
Add shape and text layer with bar chart. 

### ISSUE THREAD

**Issue by joycefly41** [altair-viz/altair#1678]
I am new to Altair, and I'm having issue with add triangle-down shape and text layer with bar chart. 
This is my current dataset, 
![image](https://user-images.githubusercontent.com/54564530/63735908-f5cc0300-c8b3-11e9-892c-d7deed1d2396.png),
 and my idea plot is like this:
![image](https://user-images.githubusercontent.com/54564530/63735965-22801a80-c8b4-11e9-836f-22c856dea776.png),

so far I have the bar plot, but I want to add triangle-down shape and text on the bar chart, I understand I need to use layer, but I am not sure how. Can anyone help me please?

this is my code: 
```python
def to_altair_datetime(dt):
    dt = pd.to_datetime(dt)
    return alt.DateTime(year=dt.year, month=dt.month, date=dt.day,
                        hours=dt.hour, minutes=dt.minute, seconds=dt.second,
                        milliseconds=0.001 * dt.microsecond)


# Pass datetime data to Altair domains 
domain = [to_altair_datetime('2018-07-01'),
          to_altair_datetime('2019-12-01')]

# mouseover
select = alt.selection_multi(fields=['status'])


alt.Chart(data).mark_bar(size=30).encode(
    alt.X('start:T',scale=alt.Scale(domain=domain)),
    alt.X2('end:T'),
    y = alt.Y('status',sort = alt.EncodingSortField(field = 'status', order = 'ascending')),
    color = 'type:O',
    tooltip = ['FPI','LPI','LPLV','PA']
).properties(
    width = 500,
    height = 150
).configure_scale(
    rangeStep=10
).add_selection(
    select
).interactive()
```

**Comment by joelostblom** [comment]
The suggested unicode approach or the follow would work to create downwards pointing triangles:

```python
alt.Chart().mark_point(shape='triangle-down')
```
