### ISSUE TITLE
Meaningless error message for `sort` attribute

### ISSUE THREAD

**Issue by idmit** [altair-viz/altair#168]
I got the following error when passed a dict instead of `SortField`:

```
traitlets.traitlets.TraitError: The 'sort' trait of a Color instance must be any value or any value, but a value of {} <class 'dict'> was specified
```

Shouldn't it mention `SortField` existence? For example, error for `legend` attribute does mention `Legend`:

```
traitlets.traitlets.TraitError: The 'legend' trait of a Color instance must be a Legend or None, but a value of class 'str' (i.e. '') was specified.
```

**Comment by jakevdp** [comment]
That error is the result of having a traitlets Union of two Enums. It's unfortunate – it might be worth reporting upstream in traitlets to see if it can be improved.

**Comment by idmit** [comment]
Got it, thanks! I wasn't aware of the way traitlets work, thought the problem was just with this particular property.

**Comment by jakevdp** [comment]
The fix is pushed into traitlets. As soon as the new traitlets version is released, you can upgrade to get better behavior!

**Comment by ubergarm** [comment]
Just a side comment:

I struggled a bit trying to get an bar chart to sort on a different field.  But between `help(SortField)` and https://vega.github.io/vega-lite/docs/sort.html I got a working example:

http://blog.ubergarm.com/beautiful-graphs-in-python-pandas-jupyter-notebooks-using-altair/

Kudos to the `Altair` team! This is the first open source graphing library that I've been able to cleanly generate pretty sorted bar charts straight from DataFrames! As people catch on the community posts more usage examples `Altair` will get even easier to use!

Thanks!

**Comment by jakevdp** [comment]
Thanks @ubergarm! We'd love for you to contribute that example to Altair's documentation. We've been merging [similar Pull Requests](https://github.com/ellisonbg/altair/pull/174) from other folks.

**Comment by ubergarm** [comment]
Great, 

A few questions on how to contribute examples:

1. Would you recommend updating the existing `notebooks/04-BarCharts.ipynb`?
2. Should it be a stand alone example in `notebooks/auto_examples`
3. Should it be a stand alone example e.g. `12-SortedBarChart.ipynb`?
4. Is it okay to create a simple DataFrame and not use altair `load_dataset`s?

Seems like 1. might churn the repo a bit if my image/png base64 encoded output differs at all.

Seems like 2. is for output generated from the `tests`

Seems like 3. would be ideal but then topics aren't grouped together.

Seems like 4. should be fine as it took me a minute to realize I couldn't work directly with a Pandas Series object.

I'll try the 1st option and see how the merge looks... 

Thanks!

**Comment by jakevdp** [comment]
Options 1 or 3 are fine: the difference is probably just a matter of taste. Also, it's fine to create a simple DataFrame. Regarding 2: you're correct that all these examples are auto-generated from [Vega-Lite's examples](https://vega.github.io/vega-lite/examples/), so they should not be modified by hand.

Thanks!

**Comment by jakevdp** [comment]
Fixed in recent traitlets release
