### ISSUE TITLE
how to create a vega visualization

### ISSUE THREAD

**Issue by idavydov** [altair-viz/altair#1680]
Hi,
Thanks for the great library.

In the docs it's written:
_it is possible to create Vega plots using a very low-level Python interface._

Is there any example available? In particular I'm interested in combining heatmap with a dendrogram, similar to [this](https://python-graph-gallery.com/404-dendrogram-with-heat-map/). Unfortunately, dendrograms are not available in vega-lite, only in vega.

**Comment by jakevdp** [comment]
No, I don't know of any examples of using it, but all the building blocks are in ``altair.vega``. If you're interested in exploring this and adding some examples to the documentation, that would be a welcome contribution.

**Comment by idavydov** [comment]
Is this the right level of abstraction?

```
from altair.vega import Vega
SPEC = {
  "$schema": "https://vega.github.io/schema/vega/v5.json",
  "width": 400,
  "height": 200,

  "data": [
    {
      "name": "table",
      "values": [
        {"category": "A", "amount": 28},
        {"category": "B", "amount": 55},
        {"category": "C", "amount": 43}
      ]
    }
  ],


  "scales": [
    {
      "name": "xscale",
      "type": "band",
      "domain": {"data": "table", "field": "category"},
      "range": "width",
      "padding": 0.05,
      "round": True
    },
    {
      "name": "yscale",
      "domain": {"data": "table", "field": "amount"},
      "nice": True,
      "range": "height"
    }
  ],

  "axes": [
    { "orient": "bottom", "scale": "xscale" },
    { "orient": "left", "scale": "yscale" }
  ],

  "marks": [
    {
      "type": "rect",
      "from": {"data":"table"},
      "encode": {
        "enter": {
          "x": {"scale": "xscale", "field": "category"},
          "width": {"scale": "xscale", "band": 1},
          "y": {"scale": "yscale", "field": "amount"},
          "y2": {"scale": "yscale", "value": 0}
        }
      }
    },
    {
      "type": "text",
      "encode": {
        "enter": {
          "align": {"value": "center"},
          "baseline": {"value": "bottom"},
          "fill": {"value": "#333"}
        }
      }
    }
  ]
}
Vega(SPEC)
```

**Comment by jakevdp** [comment]
Sure, if you want to write vega specs directly, that's a good way to do it.

**Comment by idavydov** [comment]
Ok, sorry my question wasn't clear. I was asking if there is a higher-level abstraction available.

After looking more into the source code of altair, it is clear that there is a higher-level approach to generate a Vega plot. However, it's not yet clear to me how.

In case I find a way I will update this issue. If I will manage to get to a useful example I can update the docs.

**Comment by jakevdp** [comment]
No, there is not a higher-level abstraction available. What is available is a set of low-level schema wrappers, so that instead of defining your vega spec as a set of nested Python dicts, you can define your vega spec as a set of nested Python objects corresponding to those dicts.

At its core, this is exactly what Altair's vega-lite API started as, but we added high-level convenience methods to improve the user experience. Nobody has had the time or inclination to do that for the vega wrappers yet, but you can feel free to explore that if you're interested.
