### ISSUE TITLE
adding a search box

### ISSUE THREAD

**Issue by jpdeleon** [altair-viz/altair#1682]
Not an issue but more of a feature request. 

I am wondering if it is possible to add a simple search box, say in a panel beside a scatter plot which would trigger the plot to e.g. highlight the mathed case(s).

**Comment by jakevdp** [comment]
There is no free-form text widget, but there is a ``alt.binding_radio`` widget that lets you choose from a pre-populated set of values.

Any feature request for support of additional widgets should be directed at http://github.com/vega/vega-lite/
