### ISSUE TITLE
Wrong sorting of rows if 'count()' is used

### ISSUE THREAD

**Issue by gilbus** [altair-viz/altair#1683]
The sorting of rows seems to be broken if one axis is encoded as 'count()'.

Working Example with correct sorting of the rows:
```python
import altair as alt
import pandas as pd

# init dataframe
df = pd.DataFrame({
    "type": ['a', 'b', 'c', 'b', 'c', 'b', 'a'],
    "value": [1,1,1,2,2,2,1]
})

# alt base
base = alt.Chart(df).encode(
    y='value:O',
    x='value',
    color='type',
)

alt.layer(
  base.mark_bar(),
  base.mark_text(dx=5).encode(text='value')
).facet(
  row=alt.Row('type', sort=['a', 'c', 'b'])
)
```
![bug_correct](https://user-images.githubusercontent.com/5910514/64083248-dbaf7c00-cd1c-11e9-8d6f-a603a598d964.png)

Once the encoding of `x` is changed to `count()` the explicit sorting order is ignored:
```python
import altair as alt
import pandas as pd

# init dataframe
df = pd.DataFrame({
    "type": ['a', 'b', 'c', 'b', 'c', 'b', 'a'],
    "value": [1,1,1,2,2,2,1]
})

# alt base
base = alt.Chart(df).encode(
    y='value:O',
    x='count()',
    color='type',
)

alt.layer(
  base.mark_bar(),
  base.mark_text(dx=5).encode(text='value')
).facet(
  row=alt.Row('type', sort=['a', 'c', 'b'])
)
```
![bug_wrong](https://user-images.githubusercontent.com/5910514/64083269-30eb8d80-cd1d-11e9-99c4-cf6f8af5acb1.png)

**Comment by jakevdp** [comment]
This appears to be a vega-lite issue. I've reported it in https://github.com/vega/vega-lite/issues/5366

**Comment by joelostblom** [comment]
The provided example is working for me on Altair 4.2.0 so closing this, please re-open if you are still seeing the issue.
