### ISSUE TITLE
Axis offset

### ISSUE THREAD

**Issue by Amarounek** [altair-viz/altair#1684]
Hello!

I would like to ask you how to offset axis or bars on the figure. You can see that thick bars are overlapping an axis, which is annoying. Unfortunately, I didn't any useful configuration commands.  

Here is my reproducible code:
```
data = {'DAY' : ['2019-05-01', '2019-05-02', '2019-05-03', '2019-05-04', '2019-05-05'],
        'RAIN' : [0.9, 0.9, 0.9, 0.9, 0.9],
        'RR_MIDDLE' : [2.80, 2.80, 2.80, 2.80, 2.80],
        'CONDITION_RR' : ['wet', 'wet', 'wet', 'wet', 'wet'],
        'CONDITION_PR' : ['dry', 'dry', 'dry', 'dry', 'dry'],
        'SEASON' : ['Intermittent_Season', 'Dry_Season', 'Intermittent_Season', 'Wet_Season', 'Intermittent_Season'],
        'MONTH' : ['Apr 2019', 'Apr 2019', 'Jun 2019', 'Jul 2019', 'Apr 2019'],
        'SEASON_NUM' : [1.0, 1.0, 1.0, 1.0, 1.0],
        'YEAR' : [2019, 2019, 2019, 2019, 2019],
        'DOY' : [121, 122, 123, 124, 125],
       }
RSDF9 = pd.DataFrame(data)
RSDF9['DAY'] =  pd.to_datetime(RSDF9['DAY'], errors='ignore')
pd.to_numeric(RSDF9['DOY'])
pd.to_numeric(RSDF9['YEAR'])

alt.renderers.enable('notebook')
alt.data_transformers.disable_max_rows()

baryear = alt.Chart(RSDF9, title="Precipitation sums per month (2017)").mark_bar().encode(
    x=alt.X('month(MONTH):T', title='year'),
    y=alt.Y('sum(RAIN):Q', title='Precipitation [mm/month]'),
    color=alt.Color('month(MONTH):O')
).configure_bar(width=40).configure_axisRight().properties(width=600).configure_axisX(labelAlign="right", labelAngle=-45, labelPadding=8)
(baryear).display()
```

![image](https://user-images.githubusercontent.com/36733547/64166895-62ad4300-ce48-11e9-8927-351f9b7237ad.png)

**Comment by jakevdp** [comment]
The easiest way to make the bar not overlap the axis is to not change the size of the bar.

The easiest way to make the bars wider without having to manually control their width is to use an ordinal encoding `month(MONTH):O` for the x-axis.

If for some reason you want to manually control the bar width and also manually adjust the x-axis limits to account for it, you can follow the [Adjusting Axis Limits](https://altair-viz.github.io/user_guide/customization.html#adjusting-axis-limits) section of the documentation.

**Comment by Amarounek** [comment]
Thank you very much! Thorough answer!
