### ISSUE TITLE
Increase tooltip font or box size

### ISSUE THREAD

**Issue by kparekh1002** [altair-viz/altair#1688]
hi, 

I was wondering if there was a way to increase the font size of the text in a tooltip? I'm making a presentation and the tooltip isn't visible for most people. My code for generating the plot is:

chart = alt.Chart(df,width=500).mark_bar().encode(
x='x',  
y='y',
color='z',tooltip=['y'])

y is a number that I want to show as a tooltip. I looked through Altair's tooltip documentation but I couldn't find anything related to font size or box size.

Thank you

**Comment by jakevdp** [comment]
I don't think there is any way to adjust tooltip font sizes within Altair, becuase this is not supported within native Vega-Lite specifications.

If you're willing to output the chart specification and write custom javascript for the chart rendering, you can use https://github.com/vega/vega-tooltip to add more customizable tooltips.
