### ISSUE TITLE
Additional properties are not allowed ('title' was unexpected)

### ISSUE THREAD

**Issue by joseph-d-p** [altair-viz/altair#1692]
Hi @jakevdp,

I have an error with using `title` when encoding.

Based on [customizing your visualization](https://altair-viz.github.io/getting_started/starting.html#customizing-your-visualization),

```
alt.Chart(data).mark_bar(color='firebrick').encode(
    alt.Y('a', title='category'),
    alt.X('average(b)', title='avg(b) by category')
)
```

I got an error:
> SchemaValidationError: Invalid specification
>        altair.vegalite.v2.schema.channels.X, validating 'additionalProperties'
>        Additional properties are not allowed ('title' was unexpected)

The full code in my jupyter looks like this:

```python
import altair as alt
import pandas as pd

data = pd.DataFrame({'a': list('CCCDDDEEE'),
                     'b': [2, 7, 4, 1, 2, 6, 8, 4, 7]})

alt.Chart(data).mark_bar(color='firebrick').encode(
    alt.Y('a', title='category'),
    alt.X('average(b)', title='avg(b) by category')
)
```

Any ideas?

**Comment by joseph-d-p** [comment]
Not anymore a problem after choosing the correct environment. Restarted my notebook and seems to work now.

**Comment by tempdeltavalue** [comment]
SchemaValidationError: Invalid specification

        altair.vegalite.v4.schema.channels.OpacityValue, validating 'additionalProperties'

        Additional properties are not allowed ('type' was unexpected)
