### ISSUE TITLE
Zooming out from interactive ignore domains

### ISSUE THREAD

**Issue by manhnguyen48** [altair-viz/altair#1693]
Hi, 

I've got an issue when zooming out on interactive() causes an unwanted reset of the domain. 
I initially wanted to have inverted X-axis hence the domain argument. Things seem fine if you reset the chart by double-click but the X-axis is returned to normal every time you zoom. 
Running on: 
Altair: 3.2.0 
Python: 3.7.3
jupyterLab: 1.1.3
jupyter: 1.0
notebook: 6.0.1

Have tested this again on Google Colab and still got the same issue. 

````
data = pd.DataFrame({
    "x" : np.random.uniform(size = 20), 
    "y" : np.random.uniform(size = 20), 
})

(alt.Chart(data, width = 500, height = 500)
.mark_point(color = 'red', size = 45)
.encode(x = alt.X("x:Q", scale = alt.Scale(domain = [data.x.max(), data.x.min()], )), 
        y = alt.Y("y:Q"))
.interactive()
)

**Comment by jakevdp** [comment]
Thanks - this is a Vega-Lite issue; I've reported it here: https://github.com/vega/vega-lite/issues/5386

**Comment by k1m190r** [comment]
Sacrify interaction on the x scale for now... 

```python
.interactive(bind_x=False)

**Comment by joelostblom** [comment]
This has been merged in VL and is now working in altair so closing this issue.
