### ISSUE TITLE
Simple selection on a line chart does not seem to behave correctly

### ISSUE THREAD

**Issue by vhphan** [altair-viz/altair#1698]
![point_working](https://user-images.githubusercontent.com/16729074/65030533-4cd46d80-d972-11e9-8e35-2e25a9467ae8.JPG)
![Line_not_working](https://user-images.githubusercontent.com/16729074/65030534-4cd46d80-d972-11e9-9901-85dc719773e7.JPG)

Hi,

1) When using a simple brush selection on a line chart with just a simple color, the selected line is showing up as grey, which is the same color as the non-selected points.
2) When changing the same plot to mark_point, the color shows up correctly.

See attached files.

**Comment by jakevdp** [comment]
Could you please provide code snippets as text rather than screenshots?

**Comment by jakevdp** [comment]
Selections operate on marks: when your selection includes the entire mark, the row(s) in the data associated with that mark are considered included in the selection.

In the case of a line chart, the line itself is a single mark, and the points that make up the line will not be included in the selection unless the entire line is highlighted.

If you want to be able to highlight part of a line, you'll need to use a different strategy; something like this: https://altair-viz.github.io/gallery/select_mark_area.html
