### ISSUE TITLE
Increase in Font Size not updating.

### ISSUE THREAD

**Issue by benjamincabalona1029** [altair-viz/altair#1699]
```python
    chart =  alt.Chart(source, title="Happiness Level by Department").mark_bar().encode(
    x=alt.X('Votes:Q',axis=alt.Axis(values=[1,2,3,4])),
    color= alt.Color('Votes:O', scale=alt.Scale(domain=[1,2,3,4],range=['red','red','green','green'])),
    row='Department:N'
    ).properties(
        height = 50,
        width = 750
        ).configure_title(fontSize=32).configure_header(labelFontSize=40)
```

I basically want to increase the font size of everything else. 
![Selection_006](https://user-images.githubusercontent.com/51807138/65098248-987e2a00-d9f9-11e9-8c3c-700de99d4970.png)

**Comment by jakevdp** [comment]
There is no global font size setting, but you can control the font size of each individual element as you did above. To see the other font size settings available, search for "fontSize" in this documentation page: https://altair-viz.github.io/user_guide/configuration.html

**Comment by benjamincabalona1029** [comment]
Hi jakevdp, first saw your PyData talk and it's really amazing. 
I tried doing it but the size is not updating. I specifically wanted to increase the text label in row.

**Comment by jakevdp** [comment]
There is an example of changing the font properties for facet labels here: https://altair-viz.github.io/user_guide/configuration.html#header-configuration

**Comment by benjamincabalona1029** [comment]
I don't know why it's not working for me. Maybe because i'm using it in Django? I tried it in a notebook and it works. I found a work around by changing this on the HTML side instead. Thanks

**Comment by jakevdp** [comment]
If you're seeing different behavior between different frontends, you're probably using an older version of the Vega / Vega-Lite javascript libraries in one of them. That is set by the renderer, not neccessarily by Altair.
