### ISSUE TITLE
PACF plot in Altair

### ISSUE THREAD

**Issue by benjcabalona1029** [altair-viz/altair#1702]
I was able to get the PACF and the lower and upper bound for the confidence interval. How do i plot the confidence interval of the PAC in altair?

```python 
alt.Chart(values).mark_bar().encode(
    x = 'Lags',
    y = 'PACF' )
```
Attached is what my dataframe looks like
![Selection_007](https://user-images.githubusercontent.com/55730940/65579581-99d7c580-dfaa-11e9-9da0-81af7d5de59a.png)

**Comment by jakevdp** [comment]
One way to show a confidence interval is with error bars. You could add these by layering a tick chart; e.g. something like this:
```python
bars = alt.Chart(values).mark_bar().encode(
    x = 'Lags',
    y = 'PACF' ,
)

errors = bars.mark_tick().encode(
    y='Lower',
    y2='Upper',
)

bars + errors
```

**Comment by benjcabalona1029** [comment]
Thanks!
