### ISSUE TITLE
Custom order in facet

### ISSUE THREAD

**Issue by HalukaMB** [altair-viz/altair#1703]
Sorry, I have been playing around with this for quite a while and still cannot find a solution. Apologies for that. I have created a chart that I **first layer** and **then facet** into rows which works great thanks to your documentation. However, I would like to customize the facet-order in which the individual plots are shown row by row by passing an array. How can I do that? I have tried to define a sort in the facet()-bracket but that has not worked?

```
combined=alt.layer(ridgeline_mal,ridgeline_fem, data=reduced).facet(
    row='Departement:O' 
    
)
combined.properties(
    bounds="flush"
).configure_facet(
    spacing=0
)
```

![visualization (2)](https://user-images.githubusercontent.com/18502037/65604586-04d3cd00-dfa8-11e9-8d7c-c79653bd587c.png)

**Comment by jakevdp** [comment]
You can specify a ``sort`` property of the row encoding; e.g.
```
row=alt.Row('Department:O', sort=['WBF', 'VBS'])
```
any values left out of the sort array will be appended at the end in alphabetical order.

**Comment by HalukaMB** [comment]
Unfortunately, I tried this as well (also redefined to "Department:N") and it leaves me with this as an output.

```
maxvalue=200
step = 60
overlap = 1
widthX=400



ridgeline_fem = alt.Chart(height=step, width=widthX).mark_area(
     fillOpacity=1, stroke="black", strokeWidth=0.5, fill="#6C43C0"

).encode(
    alt.X(
        "Lohnklasse | Geschlecht:Q",
    ),
    alt.Y(
        "more_female:Q",
        scale=alt.Scale(domain=[0,maxvalue],range=[step, -step * overlap]), 
        
        axis=None
    ),
    
)

ridgeline_mal = alt.Chart(height=step, width=widthX).mark_area(
    interpolate="monotone", fillOpacity=1, stroke="black", strokeWidth=0.5, fill="#24B39C"

).encode(
    alt.X(
        "Lohnklasse | Geschlecht:Q",
    ),
    alt.Y(
        "more_male:Q",
        scale=alt.Scale(domain=[0,maxvalue],range=[step, -step * overlap]), 
        
        axis=None
    ),
    
)

combined=alt.layer(ridgeline_mal,ridgeline_fem, data=reduced).facet(
row=alt.Row('Department:N', sort=['EDA', 'BK', 'EFD', 'EDI', 'EJPD', 'UVEK', 'VBS', 'WBF'])
    
)
combined.properties(
    bounds="flush"
).configure_facet(
    spacing=0
)

```


[reduced.xlsx](https://github.com/altair-viz/altair/files/3656704/reduced.xlsx)

![visualization (4)](https://user-images.githubusercontent.com/18502037/65671988-90049f80-e048-11e9-91df-e1f704a25908.png)

**Comment by jakevdp** [comment]
I can't run your script because it has undefined variables, but here is an example of facet sort working:
```python
from vega_datasets import data
import altair as alt

stocks = data.stocks()

alt.Chart(stocks).mark_line().encode(
  x='date:T',
  y='price',
  color='symbol'
).properties(
  height=50  
).facet(
  row=alt.Row('symbol', sort=['GOOG', 'IBM', 'AAPL', 'AMZN', 'MSFT'])
)
```
![visualization - 2019-09-26T060205 073](https://user-images.githubusercontent.com/781659/65690086-2c1bb000-e023-11e9-9d87-d2d5fd1b483b.png)
