### ISSUE TITLE
Composing Multiple Selections

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#1704]
What is the best approach for combining multiple selections in Altair? 
In Vega-Lite this is [described as such](https://vega.github.io/vega-lite/docs/selection.html#compose) for a combined conditioned color selection:

```json
"color": {
  "condition": {
    "selection": {"and": ["alex", "morgan"]},
    "aggregate": "count", "type": "quantitative"
  },
  "value": "grey"
}
```

And I can create a working example similar to the Vega-Lite docs as such in Altair:
```python
import altair as alt
from vega_datasets import data

source = data.cars()

alex = alt.selection_interval(
    on="[mousedown[!event.shiftKey], mouseup] > mousemove",
    translate="[mousedown[!event.shiftKey], mouseup] > mousemove", 
    name='alex'
)
morgan = alt.selection_interval(
    on="[mousedown[event.shiftKey], mouseup] > mousemove",
    translate="[mousedown[event.shiftKey], mouseup] > mousemove",
    mark={"fill": "#fdbb84", "fillOpacity": 0.5, "stroke": "#e34a33"},
    name='morgan'
)

alt.Chart(source).mark_rect().encode(
    x='Cylinders:O',
    y='Origin:O',
    color=alt.condition({"selection": {"and": [alex.name, morgan.name]}}, 'count()', alt.ColorValue("grey"))    
).add_selection(
    alex, morgan
)
```
![image](https://user-images.githubusercontent.com/5186265/65613071-a4e42300-dfb5-11e9-8f50-2e2321ec6b8f.png)

But it doesn't feel very pythonic. 
I saw there is an `alt.SelectionAnd()` function, but I don't know how it should work. I tried `alt.SelectionAnd([alex.name, morgan.name])`, but this returns:

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-55-409c05815fbc> in <module>
----> 1 alt.SelectionAnd([alex.name, morgan.name])

TypeError: __init__() takes 1 positional argument but 2 were given
```
Some help, advice or insight is appreciated.

(I'm also not sure if the `on` and `translate`  within the `alt.selection_interval()` function should be like this in Altair)

**Comment by jakevdp** [comment]
Bitwise operators are supported for selections: e.g. ``alt.condition(alex & morgan, ...)`` or ``alt.condition(alex | morgan, ...)``

**Comment by jakevdp** [comment]
``alt.SelectionAnd`` is a low-level operator around the ``SelectionAnd`` definition in the vega-lite schema. If you look at the return value of ``alex & morgan``, you'll see that it is a properly constructed ``SelectionAnd`` object.

**Comment by mattijn** [comment]
Wow! Thats neat! Hidden beauty!

**Comment by jakevdp** [comment]
Great! Is there any place in the docs we could add this that you might have found before asking the question?

**Comment by mattijn** [comment]
I guess here: https://altair-viz.github.io/user_guide/interactions.html#selection-types-interval-single-multi.
I should be able to add this example as a PR later this week, but this part:

```json
morgan = alt.selection_interval(
    on="[mousedown[event.shiftKey], mouseup] > mousemove",
    translate="[mousedown[event.shiftKey], mouseup] > mousemove",
    mark={"fill": "#fdbb84", "fillOpacity": 0.5, "stroke": "#e34a33"},
    name='morgan'
)
```
is a bit verbose.
But we can discuss this in that PR.
