### ISSUE TITLE
react-vega : How to hid "click to view more actions" button on Graph

### ISSUE THREAD

**Issue by thilagaCloud** [altair-viz/altair#1705]
Hi Team,

I have imported { Vega } from "react-vega". When i am trying to show the graph, it included a button which is 3 dotted (Click to view more actions). I want to remove this button from visibility. How to do that. Thanks in Advance for your support.

Regards,
ThilagaDas

**Comment by jakevdp** [comment]
These sorts of settings are controlled by the renderer, rather than the chart specification. In Altair, you can hide the actions menu by running:
```python
alt.renderers.set_embed_options(actions=False)
```

**Comment by thilagaCloud** [comment]
Thanks for the Reply jakevdp. But i am using Vega in react directly not thru Altair. Is it right forum to raise?.. Just for your reference i have added my code here:


import React from "react";
import ReactDOM from "react-dom";
import { Vega } from "react-vega";

const spec = {
  width: 40,
  height: 40,
  padding: 2,
  autoscale: "fit",
  title: "safety",
  data: [{ name: "table" }],
  signals: [
    {
      name: "interpolate",
      value: "linear",
      bind: {
...........
};

const barData = {
  table: [
    {
      x: "Jan-19",
      c: "Cum Rate",
      y: 0
    },
    {
      x: "Feb-19",
      c: "Cum  Rate",
      y: 10
    },
    {
      x: "Mar-19",
      c: "Cum Rate",
      y: 20
    }
  ]
};

/*function handleHover(args) {
  console.log(args);
}

const signalListeners = { hover: handleHover };
*/
ReactDOM.render(
  //<Vega spec={spec} data={barData} signalListeners={signalListeners} />,
  <Vega spec={spec} data={barData} />,
  document.getElementById("root")
);

**Comment by jakevdp** [comment]
If you're not using Altair, I'd suggest asking your question in a different forum. This is the Altair repository.

**Comment by jakevdp** [comment]
I'd suggest https://stackoverflow.com/questions/tagged/vega

**Comment by thilagaCloud** [comment]
Thanks jakevddp
