### ISSUE TITLE
Issues with Altair and BINDER notebook

### ISSUE THREAD

**Issue by AnneEstoppey** [altair-viz/altair#1708]
Hello, I have been struggling with this for several hours now. I added a binder button on my readme in my github to launch my notebook. My notebook has some really nice Altair graphs.

My binder notebook is launching properly, but I have error messages concerning my Altair. Please note that I have been running Altair locally on my computer both from jupyter notebook and jupyter lab without any issues.

I cannot find which dependencies to add in my YML file. Whatever I do, this is not working.

Could you please tell me which dependencies are needed in my YML, in a simplified way, so that my Altair can work in the notebook generated by my binder?

Do you have an example of a YML file which is working specifically for Altair for a binder notebook?

Thanks a lot in advance
Cheers
Anne

**Comment by jakevdp** [comment]
>  I have error messages concerning my Altair.

More information would be helpful. What error messages are you seeing? My answer will be less useful to you if I have to guess :smile:

**Comment by AnneEstoppey** [comment]
Hello Jake, yes sorry I had to prepare dinner, so it was a bit short. Here some details. 

In fact, if you wish, you can try yourself from my repository. It's here:
https://github.com/AnneEstoppey/EasyDataTools

Please scroll below the map. The binder button is there :-)

My environment is in the file environment.yml, which is in the root in my repository.
I tried to simplify that file, and besides the Altair library, everything is running fine with it.
(I am aware that there is a lot of stuff in this environment file, but at the end I thought I don't remove too much, because I am not sure which dependencies Altair needs...)

Just in case, here is a picture of my notebook once I click on the binder button:
![notebook_altair_binder](https://user-images.githubusercontent.com/35219455/65708425-d846b080-e08e-11e9-9f43-0e8b7bd47eca.jpg)

Let me know if you need more info :-)
Cheers :-)

**Comment by Alcampopiano** [comment]
Hi there,

In general, while everyone is busy, Jake takes care of Altair issues almost all by himself and so taking extra time to provide an extremely clear description of the problem is a nice way to make things easier for him.

Just some thoughts that may help you to identify the issue:

Did you install the vega package as suggested by the error at the very bottom of your screenshot?

Are you using the most recent versions of Altair and classic Jupyter? If not perhaps you could use those to see if this helps.

Have you followed the[ Altair documentation here](https://altair-viz.github.io/user_guide/troubleshooting.html) that relates to this issue?

I believe that the docs discuss troubleshooting when you see the error you are experiencing:
```
NoSuchEntryPoint: No 'notebook' entry point found ...
```

These are just some things to try. Jake will have a better sense of what is going on but maybe you can make some progress based on the above information.

**Comment by jakevdp** [comment]
My first suggestion would be to follow the instructions at the end of the error message in your screenshot. Let us know if that doesn't work.

**Comment by AnneEstoppey** [comment]
Thanks, I am actually on my way to solve this. 

Yes I read the documentation and as I mentioned I had no issues whatsoever to visualise my Altair graphs in my jupyter notebook or jupyter lab on my local.

Then in the documentation, I read again today that to be able to render Altair in Jupyter notebooks, one has to install vega_datasets (I'll try to find the link to this in the documentation again).

So I added vega_datasets in my yml, and did NOT add vega.
Of course this didn't work.

Then finally I added vega in my yml, and it is working now :-)
I have to simplify my yml (working on it now) because I have way too much stuff in there.
I am down to just a few packages now, I just run the notebook in binder, rerun all the cells and it's good now, my Altair graphs are displaying :-))

So I think I am good, thanks for helping!

**Comment by jakevdp** [comment]
> one has to install vega_datasets

one has to install **vega** not vega_datasets

**Comment by AnneEstoppey** [comment]
Yes here I got confused by re-reading this apparently!
![notebook_altair_doc](https://user-images.githubusercontent.com/35219455/65718302-8ceacd00-e0a3-11e9-8443-f95df1da6ef6.jpg)

**Comment by AnneEstoppey** [comment]
Ok, I can close this now, it's working fine, although it takes a long time to launch the notebook in binder, even after I simplified my yml to the bare minimum. I'll see to that later! Cheers :-)

**Comment by jakevdp** [comment]
I think the baseline binder launch time is several minutes no matter what you do.
