### ISSUE TITLE
Whiskers on boxplot notworking on temporal data

### ISSUE THREAD

**Issue by benjcabalona1029** [altair-viz/altair#1709]
I am trying to make a boxplot with temporal data. I used the timeUnit functionality to check for seasonality. I made the plot using the code below.

```python
alt.Chart(data.reset_index()).mark_boxplot().encode(
    x=alt.X('DATE:T',timeUnit='month'),
    y='Sales')
```

![Selection_008](https://user-images.githubusercontent.com/55730940/65755615-0e933700-e146-11e9-8f97-15762d62c9b2.png)

The whiskers are working for regular quantitative data.

```python
alt.Chart(data.reset_index()).mark_boxplot().encode(x='Sales:Q')
```

![Selection_009](https://user-images.githubusercontent.com/55730940/65755766-56b25980-e146-11e9-8d61-ee674fdc530a.png)

```

**Comment by jakevdp** [comment]
Please include a full code snippet that reproduces the issue. When I run yours I get ``NameError: name 'data' is not defined``

**Comment by mattijn** [comment]
Probably related to this unresolved Vega-Lite issue upstream: https://github.com/vega/vega-lite/issues/4925

**Comment by benjcabalona1029** [comment]
Hi Jake,


```python
from vega_datasets import data
import altair as alt
alt.data_transformers.enable('json')
temps = data.seattle_temps()

alt.Chart(temps).mark_boxplot().encode(
    x=alt.X('date:T',timeUnit='month'),
    y='temp')
```

But as mentioned above this might be a Vega Lite Issue.

**Comment by joelostblom** [comment]
The provided example is working for me on Altair 4.2.0 (with the `data_server` data transformer and by disabling max rows), so I'm closing this, please re-open if you are still seeing the issue.
