### ISSUE TITLE
Empty chart when plotting with Altair

### ISSUE THREAD

**Issue by ergut** [altair-viz/altair#1710]
When I try to plot a simple dataset using Altair I receive an empty output. Matplotlib or Folium outputs are ok.

I created a virtual environment and installed Altair inside that environment with the following pip command

    $pip install altair vega_datasets notebook vega

This is the code:

    import pandas as pd
    import altair as alt
    alt.renderers.enable('notebook')
    
    df = pd.DataFrame(dict(x=[0,1,2,3,4],y=[0,1,4,9,16]))
    print(df)
    chart = alt.Chart(df).mark_point().encode(
        x='x:Q',
        y='y:Q',
    )
    chart
This is the output of `chart.to_dict`

    {'config': {'view': {'width': 400, 'height': 300}, 'mark': {'tooltip': None}},
     'data': {'name': 'data-1bd52798aa5c8fc06ce9b9fcf392e24b'},
     'mark': 'point',
     'encoding': {'x': {'type': 'quantitative', 'field': 'x'},
      'y': {'type': 'quantitative', 'field': 'y'}},
     '$schema': 'https://vega.github.io/schema/vega-lite/v3.4.0.json',
     'datasets': {'data-1bd52798aa5c8fc06ce9b9fcf392e24b': [{'x': 0, 'y': 0},
       {'x': 1, 'y': 1},
       {'x': 2, 'y': 4},
       {'x': 3, 'y': 9},
       {'x': 4, 'y': 16}]}}
Versions:

    $ python --version
    Python 3.6.3

    $jupyter notebook --version
    6.0.1

    alt.__version__
    3.2.0

     vega.__version__
    2.6.0

    IPython.__version__
    7.2.0

**Comment by jakevdp** [comment]
I suspect that your jupyter notebook frontend is using an older version of the vega extension. I'd recommend running [these commands](https://github.com/vega/ipyvega#python-package-index) to ensure that your jupyter frontend is using the correct extension.

**Comment by benjcabalona1029** [comment]
I think it's better if you install Jupyter Lab, in my experience since altair is meant to be interactive, it's run more smoothly in Jupyter Lab than in the regular notebook.

**Comment by jakevdp** [comment]
Altair is interactive in Jupyter notebook as well – there's no difference compared to the experience in JupyterLab.
