### ISSUE TITLE
facet_wrap is not working with altair 3.20 and vega 2.3.0

### ISSUE THREAD

**Issue by sarchak** [altair-viz/altair#1713]
I am trying to get a simple example of facet wrap working and having issue with a very simple example. Am I missing something here?
<img width="1178" alt="Screen Shot 2019-09-28 at 12 06 09 PM" src="https://user-images.githubusercontent.com/839293/65821288-70a47880-e1e8-11e9-94a3-4439d94ba910.png">

**Comment by sarchak** [comment]
Tried to follow what is mentioned here https://stackoverflow.com/questions/50164001/multiple-column-row-facet-wrap-in-altair/56537031#56537031 and on the documentation page.

**Comment by jakevdp** [comment]
Do you see any errors or warnings in the javascript console?

**Comment by sarchak** [comment]
No errors I was using Jupyter Notebook. I watched your pycon 2018 video and just set up a new env along with jupterlab and this seems to work fine now. Closing this issue. Thanks

**Comment by jakevdp** [comment]
Good to hear. I suspect the issue was that you had an older version of the vega notebook extension installed, despite having the newest version of the vega package in your Python environment.
