### ISSUE TITLE
Adding more examples to the gallery

### ISSUE THREAD

**Issue by firasm** [altair-viz/altair#1715]
Hey there,

I'll be teaching a course on data visualization to some graduate students (~125) and I intend to make one of the questions for the "Lab" to contribute an example (that doesn't already exist) to the Altair example gallery.

Still trying to think through the logistics of this activity on my side, but wanted to run the idea by the maintainers of the package first, to see if you support this idea in principle. Of course, I will not tie any marks to the review process done here on github and the submission will first be assessed by the teaching assistants for the course. 

Relevant bits from the docs that gave me this idea:

> Adding Examples
> 
> We are always interested in new examples contributed from the community. These could be everything from simple one-panel scatter and line plots, to more complicated layered or stacked plots, to more advanced interactive features. Before submitting a new example check the Altair Example Gallery to make sure that your idea has not already been implemented.
> 
> Once you have an example you would like to add there are a few guide lines to follow. Every example should:
> 
> be saved as a stand alone script in the altair/examples/ directory.
> have a descriptive docstring, which will eventually be extracted for the documentation website.
> contain a category tag.
> define a chart variable with the main chart object (This will be used both in the unit tests to confirm that the example executes properly, and also eventually used to display the visualization on the documentation website).
> not make any external calls to download data within the script (i.e. don't use urllib). You can define your data directly within the example file, generate your data using pandas and numpy, or you can use data available in the vega_datasets package.
> The easiest way to get started would be to adapt examples from the Vega-Lite example gallery which are missing in the altair gallery. Or you can feel free to be creative and build your own visualizations.

Thanks

Firas

**Comment by jakevdp** [comment]
I can't promise I'll have the bandwidth to quickly review 125 PRs from students, so it may take several months to get through them all. If that's OK with you, then go for it.

**Comment by jakevdp** [comment]
Maybe a more tractable idea would be for the class to have its own examples repo that students submit to, then vote on the top ~10 or so to submit...

**Comment by firasm** [comment]
Sounds good - there will be no time pressure, the assignment will just be to "submit" them and send us a link to their PR. 

Your second suggestion is also reasonable.

Cheers.
