### ISSUE TITLE
Compatibility with JupyterLab

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#172]
I've not been able to get altair plots to show up in JupyterLab – I think @ellisonbg understands the reason for this.

Once we get that working, it would be awesome to have a JupyterLab plugin that lets us simultaneously edit Altair Python code & raw Vega-Lite JSON, with a live view of the result, kept in-sync using Altairs `to_altair()` and `to_dict()` methods.

**Comment by ellisonbg** [comment]
Yes, there are a couple of things we need to do, but let's keep this open to track progress...

**Comment by jakevdp** [comment]
Relevant work:

- https://github.com/altair-viz/altair/pull/216
- https://github.com/vega/ipyvega/issues/60

**Comment by gnestor** [comment]
With the jupyterlab_vega extension, live editing Vega is possible 👍 :

![screencap](http://g.recordit.co/9p1HZcTO5D.gif)

**Comment by gnestor** [comment]
Let's track progress at https://github.com/altair-viz/altair/issues/283

**Comment by ellisonbg** [comment]
Fixed in master, closing.
