### ISSUE TITLE
Scatter plot with arrows?

### ISSUE THREAD

**Issue by robbuckley** [altair-viz/altair#1721]
Is it possible to create a scatter plot with 2 series, with corresponding points in each series connected with arrows?  

Like this, but with each point labelled, similar to https://github.com/altair-viz/altair/issues/715

![image](https://user-images.githubusercontent.com/20515024/66386819-af8db780-e9ba-11e9-88ca-4139ba9de022.png)

The use case is to show the changes in a set of items, where each item is unique, has 2 parameters of interest, and the 2 series represent the properties of the set at 2 time instants (for example)

I cant see anything like this in the gallery

**Comment by jakevdp** [comment]
There are no arrow markers in Altair, but you can draw lines connecting points like this in the style of the [slope graph](https://altair-viz.github.io/gallery/slope_graph.html) example:
```python
import pandas as pd
import altair as alt

df = pd.DataFrame({
    'x': [1, 2, 4, 5, 3, 4, 4, 5, 2, 3],
    'y': [6, 7, 3, 4, 4, 5, 0, 1, 5, 6],
    'class': ['A', 'A', 'B', 'B', 'C', 'C', 'D', 'D', 'E', 'E']
})

alt.Chart(df).mark_line().encode(
    x='x',
    y='y',
    detail='class'
)
```
![visualization - 2019-10-08T054432 589](https://user-images.githubusercontent.com/781659/66396480-b69ed080-e98e-11e9-934b-1daf3df4988e.png)

**Comment by robbuckley** [comment]
thanks for the quick response @jakevdp
