### ISSUE TITLE
Smooth line in facet plot

### ISSUE THREAD

**Issue by kuchenrolle** [altair-viz/altair#1723]
I'm trying to generate a faceted scatter plot with a line for the mean. This code works:
```
scatter = alt.Chart(data).mark_point().encode(
    x="Position",
    y="Value",
    color="Cluster",
)

average = alt.Chart(data).mark_line(color="black").encode(
    x="Position",
    y="mean(Value)")

combined = scatter + average

combined.facet("Cluster")
```
However, as my data is sparse in some areas, I get very spiky lines that don't capture the trend well. My quick fix is to round the values of data.Position for the line, which works okay, but I'm wondering if there's a clever way to make use of statsmodel's lowess smooth? I can only see doing that in pandas, adding a new column with smooths per cluster.

**Comment by jakevdp** [comment]
It sounds like what you want is a rolling mean, which you can do by modifying this example: https://altair-viz.github.io/gallery/scatter_with_rolling_mean.html

**Comment by kuchenrolle** [comment]
Yes, I saw that. But I couldn't get it to work (Using altair version 3.2.0). It works fine if I leave the facetting out, but otherwise I get an error message saying "JavaScript Error: this.transform.groupby is undefined", using this code (have to output an HTML, as I can't use a notebook at the moment):

```
scatter = alt.Chart(data).mark_point().encode(
    x="Position",
    y="Value",
    color="Cluster",
)

average = alt.Chart(data).mark_line(color="black").transform_window(
    running_avg="mean(Value)",
    frame=[-10,10]).encode(
    x="Position",
    y="running_avg")

combined = scatter + average
combined.save("test.html")  # works

combined.facet("Cluster")
combined.save("test_facet.html")  # java error
```

But lo(w)ess is also a bit more clever than the moving average in that it weights each data point by its distance and allows to get an uncertainty estimate. I would like that. (:

**Comment by jakevdp** [comment]
Your code example does not define ``data``, so I can't run it.

Regarding more sophisticated regressions: more options will be added in Altair v4 (based on enhancements to Vega-Lite 4.0). If you need more than what is available, I'd suggest pre-computing the regressions using pandas or another tool before passing the data to altair.

**Comment by kuchenrolle** [comment]
I've updated the code above so that it can be run.

**Comment by jakevdp** [comment]
This looks like a Vega-Lite bug... it appears that any time a layer within a facet defines a transform, the renderer chokes. A workaround is to define the transform at the top level:
```python
scatter = alt.Chart(data).mark_point().encode(
    x="Position",
    y="Value",
    color="Cluster",
)

average = alt.Chart(data).mark_line(color="black", opacity=1.0).encode(
    x="Position",
    y="running_avg:Q"
)

combined_facet = (scatter + average).facet(
    "Cluster:N"
).transform_window(
    running_avg="mean(Value)",
    frame=[-10,10]
).configure_mark(opacity=0.05)
```

**Comment by kuchenrolle** [comment]
That doesn't throw an error anymore, but it also doesn't look right. I added sorting the data by Position to your code, but somehow the running averages do not reflect the trends per cluster (it is, in fact, above the data points for the first cluster) and they look suspiciously similar. Full code that can be copy-pasted:

```
import numpy as np
import pandas as pd
import altair as alt

Position = np.random.ranf(5000).round(2)
Cluster = np.random.randint(1, 4, 5000)
Value = Position * np.random.randint(50, 150, 5000) * Cluster
data = pd.DataFrame(dict(Position=Position,
                         Value=Value.round(),
                         Cluster=map(str, Cluster)))
scatter = alt.Chart(data).mark_point().encode(
    x="Position",
    y="Value",
    color="Cluster",
)

average = alt.Chart(data).mark_line(color="black", opacity=1.0).encode(
    x="Position",
    y="running_avg:Q"
)

combined_facet = (scatter + average).facet(
    "Cluster:N"
).transform_window(
    running_avg="mean(Value)",
    frame=[-10,10],
    sort=[alt.SortField("Position","ascending")]
).configure_mark(opacity=0.8)
combined_facet.save("test_facet.html")
```

**Comment by jakevdp** [comment]
The ``transform_window`` method has a ``sort`` attribute that controls what order the window operates on. If the default is not using the sort order you want, I'd suggest starting there. Details in the docs: https://altair-viz.github.io/user_guide/transform.html#window-transform

**Comment by kuchenrolle** [comment]
As I mentioned, I used the sort argument. For no sorting, however, can the average be higher than all data points.

**Comment by jakevdp** [comment]
Sorry, lost track of this. You are computing the running average of all points; I think you want to compute the running average of each group:
```python

combined_facet = (scatter + average).facet(
    "Cluster:N"
).transform_window(
    running_avg="mean(Value)",
    frame=[-10,10],
    sort=[alt.SortField("Position","ascending")],
    groupby=['Cluster']
).configure_mark(opacity=0.8)
```
