### ISSUE TITLE
Selection Multi Init

### ISSUE THREAD

**Issue by lukesmurray** [altair-viz/altair#1726]
Is there public documentation for how to pass initial values to selection multi. For example in this chart from the [documentation](https://altair-viz.github.io/user_guide/interactions.html#selection-targets-fields-and-encodings) how can I make the initial selection `Japan` and `USA`. Is there a way to pass init to alt.selection_multi to make this happen?

```
selection = alt.selection_multi(fields=['Origin'])
color = alt.condition(selection,
                      alt.Color('Origin:N', legend=None),
                      alt.value('lightgray'))

scatter = alt.Chart(cars).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color=color,
    tooltip='Name:N'
)

legend = alt.Chart(cars).mark_point().encode(
    y=alt.Y('Origin:N', axis=alt.Axis(orient='right')),
    color=color
).add_selection(
    selection
)

scatter | legend
```

I've tried doing something like the following but this appears to have no effect.

```
import altair as alt
from vega_datasets import data

cars = data.cars.url

selection = alt.selection_multi(
    fields=['Origin'],
    init=[{'Origin': 'USA'}, {'Origin': 'Japan'}]
  )
color = alt.condition(selection, alt.Color('Origin:N', legend=None),
                      alt.value('lightgray'))

scatter = alt.Chart(cars).mark_point().encode(
    x='Horsepower:Q', y='Miles_per_Gallon:Q', color=color, tooltip='Name:N')

legend = alt.Chart(cars).mark_point().encode(
    y=alt.Y('Origin:N', axis=alt.Axis(orient='right')),
    color=color).add_selection(selection)

scatter | legend
```

**Comment by victornoel** [comment]
@lukesmurray hi, could you find a solution to this?

**Comment by lukesmurray** [comment]
No i was not able to find a solution @victornoel. I haven't thought about this since I posted the issue, but when I was working on it I was using [the altair docs for init](https://altair-viz.github.io/user_guide/generated/api/altair.selection_multi.html?highlight=selectioninitmapping) and [the vega lite docs on initializing selections](https://vega.github.io/vega-lite/docs/init.html).

The init for single selection is documented in [this example](https://altair-viz.github.io/user_guide/interactions.html#selection-values-in-expressions) and init for selection single takes a [selection init mapping](https://altair-viz.github.io/user_guide/generated/core/altair.SelectionInitMapping.html#altair.SelectionInitMapping).

Since a selection init mapping looks like a dictionary, `init={'cutoff': 50}`, I tried to use a `List of dicts` to make a `List(SelectionInitMapping))`. Thats what I did in my example here `init=[{'Origin': 'USA'}, {'Origin': 'Japan'}]`.

Hopefully that helps you out if you still feel like finding a solution.

**Comment by victornoel** [comment]
@lukesmurray thx.

On my side I tried using something like `init={'Origin': ['USA', 'Japan']}` instead, but I just get an error from altair:
```
sequence item 1: expected str instance, int found
```

**Comment by lukesmurray** [comment]
Alright you got me interested. [In the multi selection tests](https://github.com/vega/vega-lite/blob/aad7ed27660a4b61361ffedf3d0d4ac26def88e9/test/compile/selection/multi.test.ts#L48-L57) the init is computed using a list of selection init mappings. I double checked the [compiled vega lite](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgOceNHG8sAbUMRQEO1AkzSkNbGTxera3cgETsSnd0LFt7HzglWEk5bzCoY0DVBBi4uMhqAE81Amd4WFF3cSVIL1SwyBQCJUpnAHlJNHcS2NTIJQJUPxqsbV1Ssp8AZyqCaCT4Z2H2saiWAA5IFvsDAahcIq0crDbualRJcQzFspXWhWVVDRD0rK2oPIL4IpKoSurnADlxURzTtIAPOQ3bLOACOWnEHmQ1DMyFwOREb26UAAElFhq4iARon9ykdrpkQdtwZDVDDVPCXhVCO9tgBZZDtQYAfWykmZAHEipEJoIWnzlv0bC0xFJZNtXO5PCK-HBAvBgtglvFlFEUgMYAhEshkiFlfZgXdIA9CsUhRqkXUGqgmuaym0Ol1NDolHbWlNRuNJiMZpJ5scBri0uslJtnEpdvtDgG4kGfPiyISjSanmaoOJ-shBkCooQPM5rTxIMJXjTkZB6o1efy3ZAPWMdRM9fb6wo-UwFs2NUnnKIdKpmqtqVVKNnLBXrU0ALpug3uaGkCw4Ss2ptQACqAGUAILF9jLydryAAKXEakhxanyoFYRvEBvM8MkEoZnEQK0kmK2x41DUgwwAD0AHwqg4gAHQ2nQWgAEZgTqwEdOIAC0L4wsM1CDABqHiABpiSIMYEAFaDMkpyQAAJIM0CcBIzg-n+gEIaBEHQrQMFwbAAFUTROEgchEbUAQwF8GBDBgUwREkRMICCEAA) from the example I have and it produced a similar mapping so I assume this is a bug.

**Comment by mattijn** [comment]
Your example is working for me:

```python
import altair as alt
from vega_datasets import data

cars = data.cars.url

selection = alt.selection_multi(
    fields=["Origin"], init=[{"Origin": "Europe"}, {"Origin": "Japan"}]
)
color = alt.condition(
    selection, alt.Color("Origin:N", legend=None), alt.value("lightgray")
)

scatter = (
    alt.Chart(cars)
    .mark_point()
    .encode(x="Horsepower:Q", y="Miles_per_Gallon:Q", color=color, tooltip="Name:N")
)

legend = (
    alt.Chart(cars)
    .mark_point()
    .encode(y=alt.Y("Origin:N", axis=alt.Axis(orient="right")), color=color)
    .add_selection(selection)
)

scatter | legend
```
<img width="545" alt="image" src="https://user-images.githubusercontent.com/5186265/68900136-7c65e300-0733-11ea-8ec3-60b710ed82cd.png">

**Comment by lukesmurray** [comment]
Thats awesome. You've given me hope. Also thank you for topojson 👍
What environment are you running the code in. Here is a colab I just put together where the interaction isn't working. [example colab](https://colab.research.google.com/drive/13ZNT6kT-TUAKSJfAWdCz5ypxpKPUoOY0)

**Comment by mattijn** [comment]
Surely Jupyter-Lab from the Jupyter ecosystem. The greatest thing what happened to mankind. I only use colab for workshops. I'm also on altair 3.2.0 btw. Jake can fix this for you.

**Comment by jakevdp** [comment]
The jupyterlab vega extension uses an older version of vega/vega-lite, I belive. Colab is up-to-date as of the Altair 3.2 release. I checked with the vega-editor, and the chart does not work in Vega-Lite 4 either.

I suspect it was a regression in Vega-Lite somewhere along the way; may be worth opening an issue there.
