### ISSUE TITLE
Concatenating plots with independent binding_select dropdown box

### ISSUE THREAD

**Issue by zhanjiezhu** [altair-viz/altair#1729]
Is it possible to horizontally concatenate 2 plots with independent binding_select dropdown box? Currently the default behaviour of hconcat is combining both dropdown boxes, but I want to separate them. And is it possible to specify the location of the dropdown boxes (e.g. top left instead of the default bottom left)

Thanks in advance.

**Comment by jakevdp** [comment]
Yes, if you create bindings for two different selections, it will result in two dropdowns. If you create two bindings for the same selection, it will be treated as a single binding.

**Comment by zhanjiezhu** [comment]
Hi Jake, thanks for your reply. But my question is when concatenating two plots, how to make the dropdowns appear separately under each plot?

Now I have two plots, the first plot doesn't have dropdown and the second one has dropdown, after horizontally concatenating them, the dropdown of second plot appear under the first plot, which is misleading to the user, so I wonder if it is possible to "resolve" the dropdown or specify the position of the dropdown so that it appears under the second plot. (An easy workaround is to do plot2 | plot1 instead of plot1 | plot2 but I don't want to do that)

**Comment by zhanjiezhu** [comment]
I guess the answer is no, as from the example https://altair-viz.github.io/gallery/multiple_interactions.html, all the buttons or dropdowns are stuck together and appear at the bottom left corner (which is a bit ugly..)

**Comment by zhanjiezhu** [comment]
sorry, this seems to be issue of Jupyter notebook, when I show it in a html page, the dropdown show up in the preferred position.

**Comment by jakevdp** [comment]
It may be that newer Vega-Lite versions place selection widgets differently.
