### ISSUE TITLE
Table creation

### ISSUE THREAD

**Issue by xbbld4x** [altair-viz/altair#1730]
How can you create a table to show your data through Altair? I created a vertical bar chart and would like to have a table directly underneath the chart which shows some additional data.

Thank you in advance for any guidance.

**Comment by jakevdp** [comment]
There is no built-in table element in Altair, but you can create one using the grammar with a bit of work. Here is an example: https://altair-viz.github.io/gallery/scatter_linked_table.html

**Comment by romanzes637** [comment]
Small question about the suggestion.

How can I choose the width of the columns?
When I try to set a different width, all columns set the width of the first column...

```python
import altair as alt
from vega_datasets import data

source = data.cars()

# Brush for selection
brush = alt.selection(type='interval')

# Scatter Plot
points = alt.Chart(source).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color=alt.condition(brush, 'Cylinders:O', alt.value('grey'))
).add_selection(brush)

# Base chart for data tables
ranked_text = alt.Chart(source).mark_text().encode(
    y=alt.Y('row_number:O',axis=None)
).transform_window(
    row_number='row_number()'
).transform_filter(
    brush
).transform_window(
    rank='rank(row_number)'
).transform_filter(
    alt.datum.rank<20
)

# Data Tables
horsepower = ranked_text.encode(text='Horsepower:N').properties(title='Horsepower', width=10)
mpg = ranked_text.encode(text='Miles_per_Gallon:N').properties(title='MPG', width=100)
origin = ranked_text.encode(text='Origin:N').properties(title='Origin', width=500)
text = alt.hconcat(horsepower, mpg, origin) # Combine data tables

# Build chart
alt.hconcat(
    points,
    text
).resolve_legend(
    color="independent"
)
```
![visualization (1)](https://user-images.githubusercontent.com/29516906/84836040-a7077980-b03d-11ea-8115-0404a8b8c599.png)

Thanks

**Comment by tzipperle** [comment]
Hi, Is it possible to remove the grey boxes from the columns of the table?

**Comment by andyreagan** [comment]
@tzipperle yes, like this:

```
import altair as alt
from vega_datasets import data

source = data.cars()

# Brush for selection
brush = alt.selection(type='interval')

# Scatter Plot
points = alt.Chart(source).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color=alt.condition(brush, 'Cylinders:O', alt.value('grey'))
).add_selection(brush)

# Base chart for data tables
ranked_text = alt.Chart(source).mark_text().encode(
    y=alt.Y('row_number:O',axis=None)
).transform_window(
    row_number='row_number()'
).transform_filter(
    brush
).transform_window(
    rank='rank(row_number)'
).transform_filter(
    alt.datum.rank<20
)

# Data Tables
horsepower = ranked_text.encode(text='Horsepower:N').properties(title='Horsepower', width=10)
mpg = ranked_text.encode(text='Miles_per_Gallon:N').properties(title='MPG', width=100)
origin = ranked_text.encode(text='Origin:N').properties(title='Origin', width=500)
text = alt.hconcat(horsepower, mpg, origin) # Combine data tables

# Build chart
alt.hconcat(
    points,
    text
).resolve_legend(
    color="independent"
).configure_view(
    strokeWidth=0
)
```

**Comment by tzipperle** [comment]
@andyreagan Thank you!

**Comment by ravinpoudel** [comment]
@tzipperle Is it possible to make the selected data frame (subset) downloadable?

**Comment by ravinpoudel** [comment]
What I am trying to do is: I am using Altair plots in Streamlit app, and want to subset a data frame and display it in the app. Is it possible to return the list of values (text) based on the brush selection and pass it to Streamlit for subsetting a pandas data frame? Any suggestions on how to do this ?

**Comment by andyreagan** [comment]
@ravinpoudel I don't think this is a great use case for Altair, to be honest. Altair doesn't interact back with Python, it's all done in the JS in Vega/Vegalite. Jake's idea is translating to JS and doing it there.

**Comment by jakevdp** [comment]
I think streamlit specifically has some tools for such things, but they work only in streamlit and are maintained by streamlit developers. You might check with the streamlit help forums to see what's possible.

**Comment by joelostblom** [comment]
@ravinpoudel This is not yet possible for Altair plots in streamlit, but you can give a thumbs up on this issue and subscribe for updates https://github.com/streamlit/streamlit/issues/2263
