### ISSUE TITLE
Empty plot when enabling json data_transformer

### ISSUE THREAD

**Issue by subhashbylaiah** [altair-viz/altair#1732]
Below is my code, I get an empty plot.
I am using JupyterLab

```
import altair as alt
import pandas as pd
alt.data_transformers.enable("json")

size = 10
df = pd.DataFrame(
    {"key": np.random.choice(list("ABC"), size), "val": np.random.rand(size)}
)
alt.Chart(df).mark_point().encode(y="key:N")
```

My versions are:
altair: 3.2.0
jupyterlab: 1.0.4

I tried looking through the page response when inspecting the network activity on Chrome, I am seeing a forbidden error.

```
<div class="error">
    <h1>403 : Forbidden</h1>
    <p>The error was:</p>
    <div class="traceback-wrapper">
    <pre class="traceback"> is not a file</pre>
    </div>
</div>
```

Below is the to_dict() from the altair object.
```
{'config': {'view': {'width': 400, 'height': 300}, 'mark': {'tooltip': None}},
 'data': {'url': 'altair-data-e47f5911f8d2367541736476ae610606.json',
  'format': {'type': 'json'}},
 'mark': 'point',
 'encoding': {'y': {'type': 'nominal', 'field': 'key'}},
 '$schema': 'https://vega.github.io/schema/vega-lite/v3.4.0.json'}
```

and the datafile exists in the local path

**Comment by jakevdp** [comment]
This looks like the same issue as reported in https://github.com/jupyterlab/jupyterlab/issues/7017, which has been fixed as of JupyterLab version 1.1.0. Based on this, I believe that updating Jupyterlab will fix your issue.

**Comment by subhashbylaiah** [comment]
👍 That was for the fastest response ever. I will check that out and update back here.

**Comment by subhashbylaiah** [comment]
So, that worked. Thank you @jakevdp.

**Comment by TomBugnon** [comment]
Same issue with Altair 4.1.0, and updating to JupyterLab >3.0 didn't do the trick.
I remember I had to revert to jupyter notebooks for that very reason a couple years ago...
@jakevdp please reopen?

**Comment by ibayer** [comment]
I'm experiencing the same issue as mentioned above. I would be great to know what the expected
behavior currently is.

Altair is a great library but having a clean way to deal with > 5k rows is quite important for me. :)

- `alt.data_transformers.enable('default')` -> plot shows fine
- `alt.data_transformers.enable('json')` -> plot is empty (no data)
- `alt.data_transformers.enable('csv')` -> plot is empty (no data)

I didn't play any special path tricks and can see that the json / csv files are generated next to my notebook.
I'm running this as local setup.

```
altair = "^4.2.0"
jupyterlab = "^3.2.1"
jupyter-client = "<6.1.13"
```

Please let me know if I can provide further information to track this down.

**Comment by rschwarz** [comment]
I also have the same behavior as the above two posts, using versions:
```
altair               4.2.0
jupyter-client       7.1.2
jupyter-core         4.9.2
jupyter-server       1.13.5
jupyterlab           3.2.9
jupyterlab-server    2.10.3
```
