### ISSUE TITLE
how to download file (svg or png) plot from altair in colab?

### ISSUE THREAD

**Issue by carloder** [altair-viz/altair#1735]
when I download it with the following command:
`chart.save('multi_trellis1.html')`

It generates a very large file(>200mb) that takes time to download and display.
I want to download it in PNG to make viewing faster but i have errors, try to install:
`!pip install selenium`
but i have the next problem:
`WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home`

Please i need your help!!!!
Thanks
![Captura](https://user-images.githubusercontent.com/22362136/67030378-e8bdda00-f0d4-11e9-9392-5c2b3094301d.JPG)

**Comment by jakevdp** [comment]
The userguide covers how to set up selenium: https://altair-viz.github.io/user_guide/saving_charts.html?highlight=selenium#png-and-svg-format
