### ISSUE TITLE
Getting log messages from chromedriver when saving charts

### ISSUE THREAD

**Issue by wanstr** [altair-viz/altair#1738]
It used to not happen, but when I recently moved to a later version of chrome/chromedriver, I started to get messages like "DevTools listening on ws://127.0.0.1..." when trying to save charts as html, which is really annoying when I'm saving a large number of them. After some googling I know this can be turned off by adding the following:

Options().add_experimental_option('excludeSwitches', ['enable-logging'])

Maybe I'm missing something but there doesn't seem to be a way to specify these options for loading the webdriver. Currently I'm just hard coding it into headless.py. Would be great if we can specify these webdriver options somewhere.

**Comment by jakevdp** [comment]
That sounds like it would be a useful contribution to the package.

**Comment by binste** [comment]
Closing this as vl-convert is now the recommended way to save an Altair chart, see https://altair-viz.github.io/user_guide/saving_charts.html. Furthermore the saving functionality with chromium was moved to https://github.com/altair-viz/altair_saver. Feel free to reopen an issue there if this is still relevant!
