### ISSUE TITLE
Color points based on global condition

### ISSUE THREAD

**Issue by Rabeez** [altair-viz/altair#1739]
I have a scatter plot with some points and the global average as a horizontal rule:
![visualization](https://user-images.githubusercontent.com/9392057/67083442-9eac2580-f1b4-11e9-99b5-dcd6c1784088.png)

I want to change the color of the points based on whether they are above or below the global mean. I know I can change color based on conditions like tihs:
```python
trend = alt.Chart(iris).mark_circle(size=60).encode(
    x=alt.X('sepalLength:Q'),
    y=alt.Y('average(sepalWidth):Q'),
    color=alt.condition('datum.sepalLength>6', alt.ColorValue('red'), alt.ColorValue('green'))
)
global_avg = alt.Chart(iris).mark_rule(color='steelblue').encode(
    y='average(sepalWidth):Q'
)

trend + global_avg
```
![visualization (1)](https://user-images.githubusercontent.com/9392057/67083526-bc798a80-f1b4-11e9-8038-329ade5ba069.png)

But I (understandably) can't use aggregate functions like average here. 
Is there a simple solution to this?

**Comment by jakevdp** [comment]
Yes, you can do this using [transforms](). For example:
```python
import altair as alt
from vega_datasets import data
iris = data.iris()

base = alt.Chart(iris).transform_joinaggregate(
    avg_sepalWidth = 'average(sepalWidth)'
).transform_calculate(
    color = 'datum.sepalWidth > datum.avg_sepalWidth ? "red" : "green"'
)

trend = base.mark_circle(size=60).encode(
    x=alt.X('sepalLength:Q'),
    y=alt.Y('average(sepalWidth):Q'),
    color=alt.Color('color:N', scale=None)
)

global_avg = base.mark_rule(color='steelblue').encode(
    y='average(sepalWidth):Q'
)

trend + global_avg
```
![visualization (3)](https://user-images.githubusercontent.com/781659/67101489-903f1900-f176-11e9-99bf-29879e8f547a.png)

**Comment by Rabeez** [comment]
Just so I understand correctly, the `transform_joinaggregate` appends the values calculated for the groups (in this case for the entire df since no grouping field has been specified) and appends that as a new field to the data? So a column containing a single constant value in this case?

Also, the link for transforms you added points to this issue.

**Comment by jakevdp** [comment]
>  appends that as a new field to the data? 

Yes, it effectively adds a new column to the data.

> Why can't I chain the marks? Something like mark_point().encode().mark_rule().encode() and so on.

Because each chart has a single mark, and the methods are not defined in a way that will create a layered chart when they are called multiple times.
