### ISSUE TITLE
plots not rendering with vegascope and json data trasnformer

### ISSUE THREAD

**Issue by chsafouane** [altair-viz/altair#1741]
I'm using altair 3.2.0 from within vscode 1.39.2(the last version as of today). As I'm running code in a notebook within vscode, I use vegascope renderer. Everything seems to work fine.

Yet, when I set the data transformer to **json**, I get plots that are **blank**. Only the names of the x-axis and y-axis appear on the plots.

Here are some more info about my vscode version:
Version: 1.39.2 (user setup)
Commit: 6ab598523be7a800d7f3eb4d92d7ab9a66069390
Date: 2019-10-15T15:35:18.241Z
Electron: 4.2.10
Chrome: 69.0.3497.128
Node.js: 10.11.0
V8: 6.9.427.31-electron.0
OS: Windows_NT x64 10.0.17763

**Comment by jakevdp** [comment]
I don't think vegascope is able to load datasets from the local disk. If you'd like to change that, I'd suggest opening an issue on the vegascope project.

**Comment by chsafouane** [comment]
Thannks Jake
