### ISSUE TITLE
axis format

### ISSUE THREAD

**Issue by anaveenan** [altair-viz/altair#1745]
When use axis=alt.Axis(format='$') for axis 
![image](https://user-images.githubusercontent.com/4349189/67349725-5e2f0d80-f50e-11e9-92b9-57ced6b536f5.png)
How to show dollar number in absolute value with $ sign (w/o the exponent)

**Comment by jakevdp** [comment]
Formats in Altair use [d3-format](https://github.com/d3/d3-format). So, for example, if you want currency in dollars with two digits after the decimal point, you can use ``format='$.2f'``:
```python
import pandas as pd
import numpy as np
import altair as alt

data = pd.DataFrame({
    'x': 10 * np.random.rand(20)
})

alt.Chart(data).mark_tick().encode(
    alt.X('x', axis=alt.Axis(format='$.2f'))
)
```

**Comment by anaveenan** [comment]
This worked. Thanks for the help
