### ISSUE TITLE
Possible to create empty Chart?

### ISSUE THREAD

**Issue by sliem** [altair-viz/altair#1747]
I would like to able to easy define an empty Chart to enable this pattern

```python
import pandas as pd
import altair as alt

class MyModel:
    def __init__(self):
        self.df = pd.DataFrame(
            pd.np.random.randint(0, 100, size=(5, 2)), columns=list("xy")
        )
        
    def plot(self):
        return alt.Chart(self.df).mark_point().encode(
            x="x:Q", y="y:Q"
        )

n = 5 # actually dynamically determined in my usecase.
models = [MyModel() for _ in range(5)]    

sum(
    [m.plot() for m in models],
    alt.Chart(), # Starting value, empty chart
)
```

But sadly it fails with `SchemaValidationError: Invalid specification` as `alt.Chart()` isn't a valid chart. Alternatively one could support addition with `None` so that `chart + None -> chart`.

The "workaround"  isn't that bad, but isn't simple as nice.
```python
charts = [m.plot() for m in models]
sum(charts[1:], charts[0])
```

**Comment by jakevdp** [comment]
Since you're creating a layered chart, it would make sense to start with an empty layer chart:
```python
sum(
    [m.plot() for m in models],
    alt.LayerChart(), # Starting value, empty chart
)
```

**Comment by jakevdp** [comment]
Or even better, avoid the forced use of operator overloading and just construct the layered chart directly:
```python
alt.layer(*(m.plot() for m in models))
```
