### ISSUE TITLE
Is it possible to return/save the current selection?

### ISSUE THREAD

**Issue by YashaPushak** [altair-viz/altair#1749]
Is it possible to save data contained within the a selection? Either to a file, or if using something like streamlit to return it to a python variable? Or alternatively if using, for example, a selection_interval() then to save the values from the interval?

My goal is to create an interactive visualization of some data, allow the user to explore the data, select a subset of (ideally with an altair selection object or something similar), and then based on the selected data do some more analysis and processing before creating a new visualization. 

As far as I can tell, this probably isn't possible, and I suspect it's a limitation of vega-lite rather than altair. However, if there is (or could be) a way, it would be extremely useful.

**Comment by jakevdp** [comment]
No, unfortunately it is not. The selection exists in the frontend (i.e. javascript code running in your browser). There is currently no mechanism by which the frontend can send messages to the backend (i.e. the python code running in your jupyter kernel).

This is possible in principle, but would require modifications across a number of libraries, including vega-embed.js and vega-lite.js (for the javascript-side hooks) the jupyter notebook extension and jupyterlab extension (for the frontend<->backend communication hooks) and Altair itself (for the Python side of things). Nobody has undertaken that project yet, so the functionality does not exist.

volunteers welcome :grinning:

**Comment by th0ger** [comment]
+1, this would be extremely useful

**Comment by th0ger** [comment]
OT: Do you know of any other non-Altair libraries (compatible with Streamlit) that supports this?

**Comment by jakevdp** [comment]
I believe Bokeh supports this kind of thing. I'm not sure if it's compatible with streamlit.

**Comment by YashaPushak** [comment]
I think plotly does too. But I'm not sure if streamlit has a mechanism for capturing this information from any visualization library yet anyways.

**Comment by joelostblom** [comment]
@YashaPushak  It is not currently possible to emit signals from Altair/VegaLite to Ipywidgets (or any other widget framework). There is some work on this for Jupyter in https://github.com/yifanwu/b2 and for Streamlit in https://github.com/streamlit/streamlit/issues/2263.

Since this is not an issue that Altair can solve, would you mind closing this issue and continue discussion in one of the links above or on the Vega-Lite issue tracker?
