### ISSUE TITLE
mark_rect handling handling of missing data

### ISSUE THREAD

**Issue by firasm** [altair-viz/altair#1754]
I'm trying to create a heat map with mark_rect() as described [here](https://altair-viz.github.io/gallery/simple_heatmap.html). 

I've attached the data as a csv to this issue, as well as a snippet of (hopefully) reproducible code as well as a snippet of what I expect it to look like using Seaborn (note the difference in handling of "missing (NaN) data", it's grey in Seaborn and ?? in Altair). 

csv needed to run example: [testdf.csv.zip](https://github.com/altair-viz/altair/files/3776055/testdf.csv.zip)

```import pandas as pd
import seaborn as sns
sns.set(rc={'figure.figsize':(11.7,8.27)})
df = pd.read_csv('testdf.csv')

# Seaborn plot
dff = df.pivot('state','year','annual_rate')
sns.heatmap(dff,vmin=0,vmax=300)
```
![Unknown](https://user-images.githubusercontent.com/2507459/67637085-464fe480-f894-11e9-84c3-402eeac0de15.png)

```
# Altair plot
heatmap = alt.Chart(df).mark_rect(
).encode(x=alt.X('year:O', title=None),
         y=alt.Y('state:O', title=None),
         color=alt.Color('annual_rate:Q',
                         scale=alt.Scale(scheme="yelloworangered",
                                         domain=[0, 300]),
                         legend=alt.Legend(
                             orient='right', title="Incidence rate/100K")
                         ))
alt.layer(heatmap).properties(width=500,
                              title="{0} reported cases / 100K in the U.S".format(
                                  name_disease)
                              ).configure_axisX(labelAngle=0)
```
![visualization-9](https://user-images.githubusercontent.com/2507459/67637096-59fb4b00-f894-11e9-85ad-69e9b09c1a6b.png)

Any ideas?

**Comment by jakevdp** [comment]
For ordinal or categorical encodings, Altair leaves out missing data unless it's explicitly imputed. You can either modify the dataset to add explicit NaNs to the input, or use an [impute transform](https://altair-viz.github.io/user_guide/transform.html#user-guide-impute-transform) to fill in missing values.

**Comment by firasm** [comment]
It seems my input data does have explicit NaNs in it, 

<img width="209" alt="Screen Shot 2019-10-27 at 12 25 05 PM" src="https://user-images.githubusercontent.com/2507459/67640060-dc940280-f8b4-11e9-9c7b-a61bd20578a2.png">

I added the impute parameter from the link you provided like:

```
color=alt.Color('annual_rate:Q',
    impute=alt.ImputeParams(value=0), # also tried np.nan
```

but got the `Schema Validation Error`: 

```
SchemaValidationError: Invalid specification

        altair.vegalite.v3.schema.channels.Color, validating 'additionalProperties'

        Additional properties are not allowed ('impute' was unexpected)
```

**Comment by jakevdp** [comment]
I would bet your data does not have explicit NaNs for the years 1956-1972, which is where the issue is happening.

Regarding the impute transform: this was added to Altair recently, so you'll have to update your installation to the most recent version.

**Comment by jakevdp** [comment]
And from the question, it sounds like you want to impute the y-axis, not the color, correct?

**Comment by firasm** [comment]
Indeed - impute the y-axis was the solution. Thanks!
