### ISSUE TITLE
mark_rect with quantitative axes

### ISSUE THREAD

**Issue by alejandroschuler** [altair-viz/altair#1755]
At the moment it seems that `mark_rect` doesn't like encoding quantitative `x` and `y`:

```
import altair as alt 
import numpy as np 
import pandas as pd 
# Compute x^2 + y^2 across a 2D grid 
x, y = np.meshgrid(range(-10, 10), range(-10, 10)) 
z = x ** 2 + y ** 2 
# Convert this grid to columnar data    expected by Altair 
source = pd.DataFrame({'x': x.ravel(), 'y': y.ravel(), 'z': z.ravel()})       
alt.Chart(source).mark_rect().encode( x='x', y='y', color='z:Q' ) 
```

![visualization (12)](https://user-images.githubusercontent.com/7213095/67641358-ed497600-f8be-11e9-9db4-56449c1c200f.png)

The problem is "solved" by specifying an ordinal encoding:

```
import altair as alt 
import numpy as np 
import pandas as pd 
# Compute x^2 + y^2 across a 2D grid 
x, y = np.meshgrid(range(-10, 10), range(-10, 10)) 
z = x ** 2 + y ** 2 
# Convert this grid to columnar data    expected by Altair 
source = pd.DataFrame({'x': x.ravel(), 'y': y.ravel(), 'z': z.ravel()})       
alt.Chart(source).mark_rect().encode( x='x:O', y='y:O', color='z:Q' ) 
```

But this reverses the y-axis and places ticks on every single value in the data:
![visualization (13)](https://user-images.githubusercontent.com/7213095/67641395-1bc75100-f8bf-11e9-9c75-f050e59c296e.png)

It's presumably possible to re-reverse the axis and reset the ticks manually, but it would be much nicer if `mark_rect` had reasonable defaults when `x` and `y` are quantitative.

**Comment by jakevdp** [comment]
This is working as intended.

For ordinal or nominal axes, ``mark_rect`` draws a rectangle within the bounds of the specified category.

For temporal or quantitative axes ``mark_rect`` draws a rectangle between the origin and the specified point. If you want the rectangle to not be drawn at the origin, you can specify the other corner via the ``x2`` and ``y2`` encodings.

If you instead want a square mark to be drawn at the specified ``x`` and ``y`` location, you can use ``mark_square()``.
