### ISSUE TITLE
OverflowError: int too big to convert

### ISSUE THREAD

**Issue by NovareKingX** [altair-viz/altair#1757]
Anyone having the same issue? When I'm trying to plot the data that contains categorical variable, this error always prompted, saying **OverflowError: int too big to convert**.

Code snippet for Altair
`alt.Chart(ctr_data).mark_bar().encode(
    x = 'banner_pos',
    y = 'count()',
    color = 'click'
)`

The dataset came from kaggle, **banner_pos** and **click** are categorical and target variable respectively. What I'm trying to do is to create a bar chart that count the total number of click ( **0 if not clicked** and **1 if clicked**) per banner_pos. I do not know why I am having this issue which in the first place the data that I fed was categorical variable. Anyway, thank you Sir Jake for this easy approach and wonderful library.

**Comment by jakevdp** [comment]
It's difficult to tell what's happening without more information about the dataset. It would be best if you could paste a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example); i.e. a short block of code with al variables defined that can be run without modification and reproduces the error.

**Comment by NovareKingX** [comment]
Thanks to your quick response, the problem was already solved. I forgot to read the documentation, because I install altair by  **pip install -U altair**, which is not a practical way since I would be using this to jupyter notebook. **pip install -U altair vega_datasets notebook vega** is the appropriate way instead.
