### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by cjbraun** [altair-viz/altair#1760]
In the documentation for renderers (https://github.com/altair-viz/altair/blob/master/doc/user_guide/renderers.rst) there is a typo in the JupyterLab section.

The line

>  for more details on version and system requireements, see :ref:`display-jupyterlab`.

spells requirements wrong.

**Comment by eitanlees** [comment]
Good catch! If you want to submit a PR that would be great. We are always looking for new contributors.
