### ISSUE TITLE
possible to read endpoints of selection interval?

### ISSUE THREAD

**Issue by smacke** [altair-viz/altair#1765]
Suppose I create a brush bound to the x axis as follows:

`brush = alt.selection_interval(name="brush", encodings=['x'])`

Is it possible to access the endpoint / extents within transformations? I seem to recall this is possible within vega via some hacks, but I'm wondering if there's something more convenient I wasn't able to find in the documentation.

**Comment by jakevdp** [comment]
No, results of interactions are not accessible from Python.

**Comment by smacke** [comment]
@jakevdp Thank you for the swift reply!

To clarify, I'm actually not trying to access the results of the interaction from Python but from within transformations encoded as strings to be interpreted in Vega. A toy example might look like:
```
brush = alt.selection_interval(name="brush", encodings=['x'])
alt.Chart(data).mark_line().add_selection(brush).transform_calculate(
    scaled_by_brush_width='datum.y * (brush.right - brush.left)'
).encode(
    x='x:Q',
    y='scaled_by_brush_width:Q'
)
```
I seem to remember this is possible in Vega Lite (or at least Vega), and so it seems like it should be possible from Altair as well, but I could be mistaken. Any pointers are much appreciated!

**Comment by jakevdp** [comment]
Oh, thanks for the clarification. Yes, this is possible; for example:
```python
import altair as alt
import pandas as pd

data = pd.DataFrame({
    'x': range(9),
    'y': [1, 2, 3, 4, 5, 4, 3, 2, 1]
})

brush = alt.selection_interval(name="brush", encodings=['x'])
alt.Chart(data).mark_line().add_selection(brush).transform_calculate(
    scaled_by_brush_width='datum.y * (isDefined(brush.x) ? (brush.x[1] - brush.x[0]) : 1)'
).encode(
    x='x:Q',
    y='scaled_by_brush_width:Q'
)
```
I find that when working with signals and selections at this level, it is helpful to select "Open in Vega Editor" from the menu: this view of the chart includes a data and signals inspector so you can more easily see how to access this kind of thing.

**Comment by smacke** [comment]
@jakevdp this is very helpful -- I didn't know about the "signal viewer" tab; thank you for the tip!

**Comment by yubrshen** [comment]
I wish to be able to somehow capture the endpoint / extents of a selection so that I can use Altair as UI tool record users' selection for annotation of the data.
Is there any solution or work-around?

**Comment by joelostblom** [comment]
@yubrshen Currently the only way to achieve this is to use Altair together with Panel as mentioned in https://github.com/altair-viz/altair/issues/1153#issuecomment-996170916

**Comment by yubrshen** [comment]
> @yubrshen Currently the only way to achieve this is to use Altair together with Panel as mentioned in [#1153 (comment)](https://github.com/altair-viz/altair/issues/1153#issuecomment-996170916)

Thanks! It should be good enough for my use case.
