### ISSUE TITLE
JS error when trying make example interactive

### ISSUE THREAD

**Issue by robbuckley** [altair-viz/altair#1766]
taking one of the examples at https://altair-viz.github.io/case_studies/exploring-weather.html#exploring-weather

namely:

```
alt.Chart(df).mark_bar().encode(
    x=alt.X('month(date):N', title='Month of the year'),
    y='count()',
    color=alt.Color('weather', legend=alt.Legend(title='Weather type'), scale=scale),
)
```

It works fine, but if I add `.interactive()` I get a `Javascript error: t is undefined`

The example immediatly following this one in the docs - which includes `.interactive()` - works fine in the same enivonment

Im running in Jupyterlab in firefox on macOS

**Comment by jakevdp** [comment]
Vega-Lite only supports binding non-binned, non-aggregated scales. In this chart, the x-axis is binned and the y-axis is aggregated, so it results in an error. There is no workaround for this case.

**Comment by robbuckley** [comment]
@jakevdp is this documented somewhere? I had a quick look in the docs but couldnt find any mention. Also, could the error message be made more explicit? that might avoid future bug reports of this nature

**Comment by jakevdp** [comment]
This error comes from javascript via the Vega/Vega-Lite stack. There's no way to control this error text from the Altair package.

Also, I looked a little closer and I think this actually is a bug in Vega-Lite: https://github.com/vega/vega-lite/issues/5514

You can bypass the error by specifying a field in the "count" encoding.

**Comment by robbuckley** [comment]
yes that works, thanks - specifying any field in the `count()` works
