### ISSUE TITLE
log transformation with stripplot

### ISSUE THREAD

**Issue by rita-ni** [altair-viz/altair#1770]
Is there a way to do log transformation on Y-axis when using a stripplot? I tried  adding `scale = alt.Scale(type = 'log')` to alt.Y but it doesn't work.

```python
alt.Chart(sub_data, width=40).mark_circle(size=8).encode(
    alt.X('jitter:Q',
        title = None,
        axis = alt.Axis(values = [0], ticks = True, grid = False, labels = False),
        scale = alt.Scale()),
    alt.Y('Worldwide_Gross:Q', 
          title = "Wordwide Gross",
          scale = alt.Scale(type = 'log')),
    color = alt.Color('Major_Genre:N', legend = None),
    column = alt.Column(
        'Major_Genre:N',
        header = alt.Header(
            labelAngle = -40,
            titleOrient = 'top',
            labelOrient = 'bottom',
            labelAlign = 'right',
            labelPadding = 3,
            title = "Worldwide Gross by Major Genre"
        ),
    ),
).transform_calculate(
    # Generate Gaussian jitter with a Box-Muller transform
    jitter = 'sqrt(-2*log(random()))*cos(2*PI*random())'
).configure_facet(
    spacing = 0
).configure_view(
    stroke = None
)
```

**Comment by jakevdp** [comment]
Log scales work best if your data is positive: if your data have any zero values or negative values, those will need to be filtered out in order to use a log scale.

Here's a basic log scale with a chart that is similar to yours, without the non-positive data:
```python
import numpy as np
import pandas as pd
import altair as alt

df = pd.DataFrame({
    'value': 100 * np.random.rand(1000),
    'category': np.random.randint(0, 6, 1000)
})

alt.Chart(df).transform_calculate(
    jitter = 'sqrt(-2*log(random()))*cos(2*PI*random())'
).mark_point().encode(
    x='jitter:Q',
    y=alt.Y('value:Q', scale=alt.Scale(type='log')),
    column='category:N'
).properties(
    width=40
)
```
![visualization (23)](https://user-images.githubusercontent.com/781659/68178656-b23fe600-ff41-11e9-9139-af4de47f3235.png)

**Comment by rita-ni** [comment]
Thank you! I decided to use a stacked bar chart instead. But I am having trouble ordering the stacked bars in my plot. I want to order the bars in the same order as the legend: negative, avg, and very high, is there a way to do that?

<img width="811" alt="Screen Shot 2019-11-08 at 12 21 14 PM" src="https://user-images.githubusercontent.com/55466310/68508094-5cf62400-0222-11ea-8906-966cb5a5b014.png">

**Comment by rita-ni** [comment]
Th

**Comment by pankajb64** [comment]
I know this is an old, closed issue. I just want to add my 2 cents: if you have zero data, adding a domain and setting `clamp=True` seems to give the desired result. This is useful for some cases where zero is desirable to keep in the data.

For instance, the following dataframe has a zero which causes a problem with the log scale.
```
dft = pd.DataFrame({'x' : [1, 2, 3, 4, 5], 'y' : [0.1, 0.2, 0.3, 0.5, 0]})
alt.Chart(dft).mark_line().encode(
    x='x',
    y=alt.Y('y', scale=alt.Scale(type='log'))
)
```

![visualization (12)](https://user-images.githubusercontent.com/825377/93705119-b5f04300-fae8-11ea-9695-0a9784237dda.png)

setting a domain for y-axis and clamping works

```
dft = pd.DataFrame({'x' : [1, 2, 3, 4, 5], 'y' : [0.1, 0.2, 0.3, 0.5, 0]})
alt.Chart(dft).mark_line().encode(
    x='x',
    y=alt.Y('y', scale=alt.Scale(type='log', domain=(0.005, 1), clamp=True))
)
```

![visualization (13)](https://user-images.githubusercontent.com/825377/93705207-62cac000-fae9-11ea-9023-2dc547330b15.png)

(interestingly, simply setting the domain doesn't work)

Also, I know that this was mentioned as an issue in Vega https://github.com/vega/vega/issues/1334 and apparently fixed, but I didn't get any warning/error message on my end informing me that there were zero values in my data. I'm on the latest version of Altair.
