### ISSUE TITLE
Square brackets in column name can't be plotted in Altair?

### ISSUE THREAD

**Issue by firasm** [altair-viz/altair#1772]
Encountered an interesting bug (?) when trying to plot a new dataset: if your column name has square brackets in it, there's an error somewhere and the plot doesn't render. 

Here's a MWE, with some toy data from the gallery. Col C is the same as Col B but just with [units] in the filename.

```
source = pd.DataFrame({
    'ColA': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'ColB': [28, 55, 43, 91, 81, 53, 19, 87, 52],
    'ColC [units]': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

c1 = alt.Chart(source).mark_bar().encode(
    alt.X('ColA:O'),
    alt.Y('ColB:Q')
)

c2 = alt.Chart(source).mark_bar().encode(
    alt.X('ColA:O'),
    alt.Y('ColC [units]:Q')
)

c1 | c2
```

Output: 
![visualization-14](https://user-images.githubusercontent.com/2507459/68234799-e5708c80-ffb6-11e9-8014-2ec9a807056a.png)

**Comment by jakevdp** [comment]
Brackets (``[]``) and periods (``.``) have special meaning within encoding definitions: they are used to refer to elements within compound data sources. If you want to use them in your column names, they will have to be escaped with a backslashes (more info in the docs here: https://altair-viz.github.io/user_guide/encoding.html#encoding-channel-options)

Altair works best if you avoid these special characters in your column names, so I'd suggest renaming your columns if possible.
