### ISSUE TITLE
Using multiple columns to define "color"

### ISSUE THREAD

**Issue by hjfreyer** [altair-viz/altair#1773]
Let's say I have a dataframe with an x, y, and two categories:

```
df = pd.DataFrame(dict(
    x=[1,2,3],
    cat1=['red', 'red', 'blue'],
    cat2=['apple', 'apple', 'banana'],
    y=[10,11,12]
))
```

I'd like a plot with 2 lines: "red,apple" and "blue,banana", with "red,apple" having two points, and "blue,banana" having 1.

I can do this by combining the two columns into one in the dataframe, but this seems like a very common use case that should be natively supported.

**Comment by jakevdp** [comment]
You can do this with a [Calculate Transform](https://altair-viz.github.io/user_guide/transform.html#calculate-transform); for example:
```python
alt.Chart(df).transform_calculate(
    cat="datum.cat1 + '-' + datum.cat2"
).mark_point().encode(
    x='x:Q',
    y='y:Q',
    color='cat:N'
)
```
![visualization (27)](https://user-images.githubusercontent.com/781659/68327735-c50e0400-0082-11ea-8c78-c5f8d686359f.png)

**Comment by hjfreyer** [comment]
This is nicer than what I had, so thanks for that! But I still think it's legit to support natively. The `tooltip` keyword can accept a list, and the library just does the right thing, creating a nice-looking tooltip. It could require the user build a string column to include in the tooltip, but it's clear what the user wants by default. `color` could also take a list and choose a default delimiter.

**Comment by jakevdp** [comment]
You could open that as a feature request in Vega-Lite, but I doubt they would implement it.

The difference between Tooltip and Color is that Color uses a scale to map inputs to visual attributes, and tooltip doesn't. I don't think there are any scales in vega or vega-lite that map multiple domains onto a single range, which is essentially what you're asking for. And it would be difficult to do in general: your example of two nominal scales mapped to a single nominal scale is easy, but how would you map two quantitative scales? You'd have to start thinking about N-demensional continuous color schemes, which I'm sure *someone* has thought about, but I'm equally sure it's not at all straightforward...

All that to say, using the calculate transform is probably your best bet.

**Comment by lizhoula** [comment]
How can I encode color with a column that specifies the color?
![image](https://user-images.githubusercontent.com/72629263/104961363-08544a00-598b-11eb-991e-13f49fe738b9.png)
I have this column and what to every bar to use this color instead of the auto one.

**Comment by jakevdp** [comment]
See https://altair-viz.github.io/user_guide/customization.html#raw-color-values
