### ISSUE TITLE
Artifact with mark_area() when coloring intervals

### ISSUE THREAD

**Issue by alejandroschuler** [altair-viz/altair#1774]
I am attempting to shade an area under a curve between two points to demonstrate an integral, but I get a strange plotting artifact:

```
import numpy as np
import altair as alt
import pandas as pd

x = np.arange(-1,1,0.01)
y = np.exp(x)
A = (-0.8<=x) & (x<0.8)

data = pd.DataFrame({'x':x, 'y':y, 'A':A})
alt.Chart(data).mark_area().encode(x='x', y='y', color='A:N')
```

![visualization (14)](https://user-images.githubusercontent.com/7213095/68347070-b76c7480-00aa-11ea-8571-741499c9a6dc.png)

The behavior is different if I set different limits for the shaded area:

```
A = (-1<=x) & (x<0)

data = pd.DataFrame({'x':x, 'y':y, 'A':A})
alt.Chart(data).mark_area().encode(x='x', y='y', color='A:N')
```

![visualization (15)](https://user-images.githubusercontent.com/7213095/68347127-d965f700-00aa-11ea-8127-64730d652647.png)

Perhaps I am misusing `mark_area()`, but I can't find anything in the documentation or other issues discussing how to do this correctly, and the fact that the behavior is different in these two cases makes me think it's a bug, not misuse.

**Comment by jakevdp** [comment]
When you encode by a color, it splits the data into parts associated with these colors, and creates a single mark for each part. You can see where this feature is coming from by actually removing the middle data from your chart and plotting just the blue
```python
import numpy as np
import altair as alt
import pandas as pd

x = np.arange(-1,1,0.01)
y = np.exp(x)
A = (-0.8<=x) & (x<0.8)

data = pd.DataFrame({'x':x, 'y':y, 'A':A})
data = data.query('~A')
alt.Chart(data).mark_area().encode(x='x', y='y')
```
![visualization (26)](https://user-images.githubusercontent.com/781659/68352329-f4d8fe00-00ba-11ea-92c1-8f8c69c47853.png)

If you want to draw each side separately, you'll need to use a different approach.

**Comment by jakevdp** [comment]
Probably the easiest way to accomplish what you want is to use an impute transform in the y encoding; something like this:
```python
import numpy as np
import altair as alt
import pandas as pd

x = np.arange(-1,1,0.01)
y = np.exp(x)
A = (-0.8<=x) & (x<0.8)

data = pd.DataFrame({'x':x, 'y':y, 'A':A})
alt.Chart(data).mark_area().encode(
    x='x',
    y=alt.Y('y', impute={'value':None}),
    color='A:N'
)
```
![visualization (27)](https://user-images.githubusercontent.com/781659/68352852-99a80b00-00bc-11ea-8427-ce6d32ee1609.png)

**Comment by alejandroschuler** [comment]
I see. that works, I suppose, but the empty space between the orange and blue regions is dissatisfying. I guess that could be solved by adding some artificial data at the boundary, but that's also inelegant.

**Comment by jakevdp** [comment]
Oh, your working example has space between the sections, so I thought that was what you were expecting.

**Comment by jakevdp** [comment]
The best way to avoid a space between the sections would probably be to use layers rather than encodings:
```python
import numpy as np
import altair as alt
import pandas as pd

x = np.arange(-1,1,0.01)
y = np.exp(x)
A = (-0.8<=x) & (x<0.8)

data = pd.DataFrame({'x':x, 'y':y, 'A':A})
base = alt.Chart(data).mark_area().encode(x='x', y='y')
base + base.transform_filter('datum.A').mark_area(color='orange')
```
![visualization (29)](https://user-images.githubusercontent.com/781659/68363988-75125a00-00e1-11ea-81f3-62b4c5cc2601.png)
