### ISSUE TITLE
Custom `mark_errorband` extent? Or `mark_band()`?

### ISSUE THREAD

**Issue by wmayner** [altair-viz/altair#1776]
Is it possible to set the extents of an errorband with columns in the data? It seems that the `area` mark only takes a single `y` value, so it can't be used to create a band from the data.

The reason I'd like to do this is because I have a very large dataset that will cause the browser to crash, so I need to compute the error band extents outside of Altair (my understanding is that even if you specify aggregate computations like `y='mean(var)'`, all the data is still sent to the browser).

**Comment by jakevdp** [comment]
You can use ``mark_area`` and specify lower and upper limits with the ``y`` and ``y2`` encodings.

For your broader question of performing aggregations before sending the data to the renderer, take a look at https://github.com/altair-viz/altair-transform. The goal is to let you do this without modification to your chart code (the project is still under development, so I'd love your feedback)

**Comment by wmayner** [comment]
🤦‍♂ Thanks, I don't know why I didn't just try that before asking. I did look at the docs but didn't notice it in the list of arguments.

Altair's API never fails! 😁 

`altair-transform` looks like just what I need. Great idea to have it separated and to work on an unmodified chart object. I'll give it a try.

Thanks for the awesome library and the super quick support!
