### ISSUE TITLE
mark_area(): Cannot use `alt.Y` for `y2`

### ISSUE THREAD

**Issue by wmayner** [altair-viz/altair#1778]
This code raises `TypeError: sequence item 1: expected str instance, int found`:
```python
import altair as alt
import pandas as pd

data = pd.DataFrame(dict(x=[1, 2], y=[1, 2], y2=[3, 4]))

alt.Chart(data).mark_area().encode(
    x='x:Q', 
    y=alt.Y('y:Q'),
    y2=alt.Y('y2:Q'),
)
```

But does not throw the error after removing the `alt.Y` for `y2`:
```python
import altair as alt
import pandas as pd

data = pd.DataFrame(dict(x=[1, 2], y=[1, 2], y2=[3, 4]))

alt.Chart(data).mark_area().encode(
    x='x:Q', 
    y=alt.Y('y:Q'),
    y2='y2:Q',
)
```

**Comment by jakevdp** [comment]
Try using ``alt.Y2``

**Comment by jakevdp** [comment]
``alt.Y`` and ``alt.Y2`` have different function signatures, because the properties the schema allows them to contain are different.

**Comment by wmayner** [comment]
Ah. It's probably about time I learn the internals of Altair actually works 😅 Sorry for the noise!
