### ISSUE TITLE
how to save png directly from python script?

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#178]
I note that when I do an Altair visualization (example.html), there's an "export PNG" button beneath it. Can I call this straight from python? I'd like to be able to:

```
open('example.html', 'w').write(chart.to_html())
open('example.png', 'w').write(chart.to_png())
```

but that does not appear to be possible, and I can't obviously see how to export png from python directly.

**Comment by jakevdp** [comment]
It's not possible at the moment.

What Altair does is generated Vega-Lite JSON. The only renderer we support (because, at the moment, it's the only renderer that exists) is ``vega-lite.js``, which is what provides the PNG export. So you could probably find a way to call-out to javascript to do this conversion automatically, but I'm not sure how to do that.

In the long run, we hope that matplotlib, bokeh, plotly, etc. will make efforts to support the vega-lite grammar (devs from each of these projects have expressed support), and then there would be ways to do this from within Python.

**Comment by jakevdp** [comment]
Let's leave this issue open so others can find it; also, this might be a good thing to eventually add to a FAQ in the documentation.

**Comment by jakevdp** [comment]
This is in the docs now

**Comment by johanovic** [comment]
Is there three years later maybe a native way to save altair/vega figures to png/jpeg/svg without a headless browser?

Many thanks for your great work

**Comment by jakevdp** [comment]
Check out the ``altair_saver`` package – it can use either a headless browser approach, or an approach based on vega command-line tools. And the next release of Altair will use this package for ``chart.save()``

**Comment by johanovic** [comment]
Fab! Thanks

**Comment by tildekarthik** [comment]
> Check out the `altair_saver` package – it can use either a headless browser approach, or an approach based on vega command-line tools. And the next release of Altair will use this package for `chart.save()`

I am hitting the issue #13 mentioned earlier by you in wsl when saving PNG . Selenium does not work with chrome crashing and node fails too

I am looking forward to a reliable way to save as it is critical for my email routines

**Comment by jakevdp** [comment]
> I am looking forward to a reliable way to save as it is critical for my email routines

I don't know of anyone actively working on making this more reliable. If it's important to you, you might consider taking that task on, otherwise you'll likely be waiting a long time.

**Comment by tildekarthik** [comment]
The following worked for me...
npm install -g vega-lite vega-cli canvas vega --force

I am not a developer, so dont know the repurcussions of this on other things. Posting it just in case it is useful for anyone else.

**Comment by maynewong** [comment]
Expect to have a simple output image by python, headless browser running in the server is too heavy

**Comment by jakevdp** [comment]
That would be great! The project is open source and maintained by volunteers. Please let me know if you would like to contribute such a solution!

**Comment by jakevdp** [comment]
A possible approach is to save charts using Kaleido; tracking issue is here: https://github.com/altair-viz/altair_saver/issues/85

The main challenge is finding someone who wants to put in the time to try it!
