### ISSUE TITLE
Altair seems to be missing mark_* method for contour

### ISSUE THREAD

**Issue by pnsvinodkumar** [altair-viz/altair#1784]
Can you please let me know when would contours be supported by Altair? Coz, I don't see one, although altair seems to contain "vega-5" in its repo already.

https://vega.github.io/vega/examples/contour-plot/

**Comment by jakevdp** [comment]
Contour will be added in Vega-Lite version 4.0, which has not yet been released (The vega developers tend to keep the documentation aligned with the development version, not the release). Once VL 4 is released, we will work on and Altair release that supports VL 4 features.

**Comment by pnsvinodkumar** [comment]
Thanks a lot for the input.. Would be great if you could point me to any link that has all the new things that would come with Vega-Lite 4? (checked vega-lite releases on its github-repo.. found nothing there)

**Comment by jakevdp** [comment]
Draft from a few months ago, missing a number of things: https://github.com/vega/vega-lite/releases/tag/untagged-0c58f4acd80c30e88904

**Comment by pnsvinodkumar** [comment]
Thank you for taking time to share the link, but its broken..

**Comment by jakevdp** [comment]
Oh, I guess the release draft is only visible to repo owners. Once VegaLite 4.0 is released, the changelig will be available.

**Comment by breadbaron** [comment]
Did support for contours ever get added to Altair?

**Comment by joelostblom** [comment]
I don't think they are added in VegaLite yet, you can follow these two issues for the progress:
- https://github.com/vega/vega-lite/issues/1919
- https://github.com/vega/vega-lite/issues/6043
