### ISSUE TITLE
Color and Shape Legends Not Combined in Line Chart or Multiple Charts

### ISSUE THREAD

**Issue by dovahcrow** [altair-viz/altair#1785]
Code to reproduce:

### In line chart:
```python
df = pd.DataFrame(
    data=[[0, 10, "a"], [1, 20, "a"], [0, 15, "b"], [1, 25, "b"]],
    columns=["x", "y", "c"]
)
alt.Chart(df).mark_line().encode(
    x="x",
    y="y",
    color="c",
    shape="c"
)
```
![image](https://user-images.githubusercontent.com/998606/68646375-dbc3b900-04cf-11ea-9e15-959ba644cfd4.png)

### Multi Charts:
```python
df = pd.DataFrame(data=[[0, 10, "a"], [1, 20, "a"], [0, 15, "b"], [1, 25, "b"]], columns=["x", "y", "c"])
points = alt.Chart(df).mark_point().encode(x="x", y="y", color="c", shape="c")
lines = alt.Chart(df).mark_line().encode(x="x", y="y", color=alt.Color("c", legend=None))
points + lines
```
![image](https://user-images.githubusercontent.com/998606/68646457-175e8300-04d0-11ea-88dd-da92acba1bbe.png)

### Expected behaviour

The legend should be like this:
![image](https://user-images.githubusercontent.com/998606/68646485-280ef900-04d0-11ea-801c-77f4f0bb0a7e.png)

**Comment by jakevdp** [comment]
In the first example, I think this behavior is expected because lines don't have shapes.

The second example surprises me: I'd suggest opening a bug/feature request in Vega-Lite with this example. There's no change we can make in the Altair repository that would change how Vega-Lite renders this specification.

**Comment by jakevdp** [comment]
I think the behavior of the first chart is expected, because lines don't have a shape, and therefore the line legend is separate from the shape legend.

The second example is unexpected to me. You can work around it by making the legend scales independent:

```python
alt.layer(
    points, lines
).resolve_scale(
    color='independent',
    shape='independent'
)
```
![visualization (37)](https://user-images.githubusercontent.com/781659/68676344-b2764d80-050e-11ea-9ef9-b8a1be77e6fa.png)

But I would not expect this to be necessary when the line legend is set to None. It may be worth reporting this as a bug or feature request within the Vega-Lite repository.

**Comment by ilyagr** [comment]
For a sufficiently complicated diagram (layered & faceted), the workaround makes things worse. Before the workaround, I was in the same situation as the OP. After the workaround, I get: 
![image](https://user-images.githubusercontent.com/4123047/71785803-eb83e900-2fb8-11ea-80b8-818ea9c20d05.png)

It also depends on where to put the `resolve_scale`. Putting it after the faceting has no effect at all, putting it before the faceting results in the screenshot above. (Sorry I don't have a nice minimal example at this point).

**Comment by ehudkr** [comment]
If I may add, regarding the comment:
>I think the behavior of the first chart is expected, because lines don't have a shape, and therefore the line legend is separate from the shape legend.

it does seem altair's `mark_line()` treats different property-channels differently, although they are common to all types of marks. This can create a rather inconsistent behavior, especially when combining multiple property-channels.
For example, let's take `mark_line` and examine the following data:
```python
import numpy as np
import pandas as pd
import altair as alt

n = 10
x = np.arange(n)
squared = x ** 2
cubed = x ** 3
squared_shifted = squared + 200
cubed_shifted = cubed + 200

source = pd.DataFrame(
    {"x": np.concatenate([x, x, x, x]),
     "operation": (['squared'] * n + ['cubed'] * n) * 2,
     "shifted": [False]*(n*2) + [True]*(n*2),
     "values": np.concatenate([squared, cubed, squared_shifted, cubed_shifted])}
)
```
which baiscally creates 4 combinations of `operation` (squared/cubed) and `shifted` (shifted/non-shifted).
`print(source.sample(n=5, random_state=2020))` gives:
![image](https://user-images.githubusercontent.com/15989012/71848380-026d2d00-30d8-11ea-8c7b-95a067421d61.png)

Now plotting the data, we can use `operation` and `shift` as property-channels.
My intuition is that the chart should result in 4 curves, 1 for each `operation`-`shift` combination.

This is indeed the case when using common properties that are "inherent" to lines, such as `color` and `size` (and also `opacity`):
```python
alt.Chart(source).mark_line().encode(
    x='x:Q',
    y='values:Q',
    color='operation:N',
    size='shifted:N'
)
```
![visualization](https://user-images.githubusercontent.com/15989012/71848736-051c5200-30d9-11ea-9438-4ba1e68d13e0.png)

However, when using properties that you claim to not be inherent to lines (although `mark_lines` can still use them), such as `shape`, it results in only 2 curves, with a line connecting between different kinds of shapes:
```python
alt.Chart(source).mark_line().encode(
    x='x:Q',
    y='values:Q',
    color='operation:N',
    shape='shifted:N'
)
```
![visualization(1)](https://user-images.githubusercontent.com/15989012/71848921-765c0500-30d9-11ea-87bf-2f909d5f9b18.png)

At first I thought it was a bug, but given Jake's answer I suspect it is by-design, in which case I think better documentation may be needed.

**Comment by jakevdp** [comment]
These are probably questions to raise in the Vega-Lite forums.

One note: the last chart will work as expected if you use a ``detail`` encoding as well, which controls how data is grouped without adding a visual attribute:
```python
alt.Chart(source).mark_line().encode(
    x='x:Q',
    y='values:Q',
    color='operation:N',
    shape='shifted:N',
    detail='shifted:N'
)

```

**Comment by joelostblom** [comment]
The linked issue has been resolved in vegalite, and the examle in the OP now works as expected, so I think this can be closed?

```py
df = pd.DataFrame(data=[[0, 10, "a"], [1, 20, "a"], [0, 15, "b"], [1, 25, "b"]], columns=["x", "y", "c"])
points = alt.Chart(df).mark_point().encode(x="x", y="y", color="c", shape="c")
lines = alt.Chart(df).mark_line().encode(x="x", y="y", color=alt.Color("c", legend=None))
points + lines
```

![image](https://user-images.githubusercontent.com/4560057/97627963-56d7f500-19e9-11eb-9281-70cc72f127e1.png)

**Comment by joelostblom** [comment]
For reference, the corresponding Vega-Lite issue is here https://github.com/vega/vega-lite/issues/5996

**Comment by joelostblom** [comment]
Closing as this is tracked in the VL issue linked above and there is nothing that can be done from the altair side of things to fix it.
