### ISSUE TITLE
output doesn't render for the altair code

### ISSUE THREAD

**Issue by Nishantkumark** [altair-viz/altair#1786]
Hi,
I have been trying to render the output for a long time. Usually, it works well but not sure why it doesn't work. I have all my code in altair and not matplotlib for backup. I have my deliverable tomorrow. Please let me know why it doesn't generate ouput inspite of mentioning alt.renderers.enable('notebook')
![thumbnail](https://user-images.githubusercontent.com/32316946/68816066-26f5dd00-0632-11ea-9ccc-6cc8dbb00f1b.jpeg)

**Comment by Alcampopiano** [comment]
Hello,

Could you please share your JupyterLab or Jupyter Notebook version? If you have not already please read the Altair [docs relevant to these types of issues](https://altair-viz.github.io/user_guide/display_frontends.html). Lastly, it is not recommended to post screenshots since it makes it very difficult to reproduce the issue, not to mention it is just hard to read. Please share a small reproducible example using formatted code (see the toolbar above).

These suggestions will increase your chances of getting a good answer to your question.

**Comment by jakevdp** [comment]
Does a simple chart from the example gallery render correctly?

**Comment by Nishantkumark** [comment]
> Does a simple chart from the example gallery render correctly?

Hi Jake, even a simple chart doesn't produce any output in my notebook. It is so weird. I tried to open a new notebook and it works but the charts doesn't work in my existing notebook. I have production ready code in this notebook :(

**Comment by jakevdp** [comment]
Did you follow the steps at https://altair-viz.github.io/user_guide/troubleshooting.html?

**Comment by Nishantkumark** [comment]
> Did you follow the steps at https://altair-viz.github.io/user_guide/troubleshooting.html?

Yes I did. I have spent an entire day to run the code. I wish Altair worked without much bugs. Have my deliverable tomorrow so will have to code in matplotlib i guess.

**Comment by jakevdp** [comment]
OK - that sort of info would be useful when you pose the question. I'm happy to help you troubleshoot, but you have to help me help you.

Open the Javascript console – do you see any errors there?

**Comment by jakevdp** [comment]
And, for the record, this is the kind of information that would help me help you:
- are you running this in jupyer notebook, jupyterlab, or elsewhere?
- are you setting any renderer (i.e. `alt.renderers.enable(???)`)?
- is there any output at all from running your chart? 
- are there errors in the Javascript console?

Also, please copy and paste the actual code that you are running – blurry cellphone photos of your laptop screen are not at all useful.

**Comment by Nishantkumark** [comment]
> OK - that sort of info would be useful when you pose the question. I'm happy to help you troubleshoot, but you have to help me help you.
> 
> Open the Javascript console – do you see any errors there?

Yes, I am running the jupyter notebook and have enabled 'notebook' renderer
No, I do not get any output running the chart
How do i open the javascript console?

I restarted the kernel again and tried in the notebook. I tried running this example code 
import altair as alt
import pandas as pd
alt.renderers.enable('notebook')

data = pd.DataFrame({'x': ['A', 'B', 'C', 'D', 'E'],
                     'y': [5, 3, 6, 7, 2]})
alt.Chart(data).mark_bar().encode(
    x='x',
    y='y',
)

and still don't get any outputs. outputs are blank.

**Comment by jakevdp** [comment]
Thank you. Regarding the javascript console; here's how to do it in Chrome: https://stackoverflow.com/questions/66420/how-do-you-launch-the-javascript-debugger-in-google-chrome

A bit of googling should give you the answer if you're using another browser.

**Comment by jakevdp** [comment]
Also, what version of the ``vega`` package do you have installed?
```python
import vega
print(vega.__version__)
```

**Comment by Nishantkumark** [comment]
Hi,
The issue got fixed once i switched to Chrome browser from safari. I am still not sure why safari couldn't handle it.

**Comment by jakevdp** [comment]
Probably something related to https://github.com/vega/vega-lite/issues/5317
