### ISSUE TITLE
One Toggle to select value in multiple column

### ISSUE THREAD

**Issue by shun-lin** [altair-viz/altair#1788]
Hi Jake,

I am wondering if it is possible to make a toggle bind to values in 2 columns of the dataframe.

Problem description:
I want to make an interactive violin plot like the one shown in here https://altair-viz.github.io/gallery/violine_plot.html

I have a dataframe of 3 columns, **class1**, **class2**, **distance**, both **class1** and **class2** has same range of classes (for example 0,1,2,...9) and the **distance** column specifies the distance from a data point in **class1** and a data point in **class2**.

A small example of data:

| class1 | class2 | distance |
| --- | --- | --- | 
| 0 | 0 | 0.1 | 
| 0 | 0 | 0.23 |
| 0 | 1 | 0.2 |
| 1 | 1 | 0.2 |
| 1 | 1 | 0.2 |

I want to make a toggle where users can choose which class in **class1** they want to visualize and then have a violin of distances distribution. I was able to get this part but I want to highlight the "self" violin plot (i.e. the violin plot of distances of class1=0 vs class2=0 if toggle is chosen to be 0) and this would acquire me to make another toggle to accomplish, I am wondering if it is possible to bind a toggle to both fields, so I can eliminate one toggle, see code snippet and colab link below. 

Code Snippet:

```Python

# imports
import altair as alt
from altair import datum
import numpy as np
import pandas as pd

# generate data and make a dataframe
random_distances = np.random.normal(loc=10, scale=1, size=1000)
class1 = [i % 10 for i in range(1000)]
class2 = [i // 100 for i in range(1000)]

distance_dict = dict()
distance_dict["class1"] = class1
distance_dict["class2"] = class2
distance_dict["distance"] = random_distances

df = pd.DataFrame(distance_dict)
df["class2"] = df["class2"].apply(str)
df["class1"] = df["class1"].apply(str)

# create toggle
toggle = alt.binding_select(options=[str(i) for i in range(10)])
variable_selection=alt.selection_single(fields=['class1'], bind=toggle, name='select', init={"class1": "1"})
color_selection=alt.selection_single(fields=['class2'], bind=toggle, name='color', init={"class2": "1"})

# create violin plots
alt.Chart(df).transform_filter(
    variable_selection
).transform_bin(
    ['bin_max', 'bin_min'], field='distance', bin=alt.Bin(maxbins=20)
).transform_calculate(
    binned=(datum.bin_max + datum.bin_min) / 2
).transform_aggregate(
    value_count='count()', groupby=['class2', 'binned']
).transform_impute(
    impute='value_count', groupby=['class2'], key='binned', value=0
).mark_area(
    interpolate='monotone',
    orient='horizontal'
).encode(
    x=alt.X(
        'value_count:Q',
        title=None,
        stack='center',
        axis=alt.Axis(labels=False, values=[0],grid=False, ticks=True),
    ),
    y=alt.Y('binned:Q', bin='binned', title='distance'),
    color=alt.condition(color_selection, alt.value('blue'), alt.value('lightgrey'), legend=None),
    column=alt.Column(
        'class2:N',
        header=alt.Header(
            titleOrient='bottom',
            labelOrient='bottom',
            labelPadding=0,
        ),
    ),
).properties(
    width=80
).add_selection(
    variable_selection, color_selection
).configure_facet(
    spacing=0
).configure_view(
    stroke=None
)
```

Screenshot of result from above snippet:
![Screenshot from 2019-11-14 10-41-17](https://user-images.githubusercontent.com/16867893/68886128-6290b580-06cb-11ea-8066-db07ff787163.png)

Colab Link:
https://colab.research.google.com/drive/1zgpM5LfHmgTC7gIMe2GIzxUGtfw8Nq1I

Ideally I want to only have 1 toggle that would 1) filter the **class1** and color base on **class2**, thank you so much for your time!

Sincerely,
Shun Lin

**Comment by jakevdp** [comment]
You can condition the color based on the selection value; something like this:
```
color=alt.condition("datum.class2 == select.class1", alt.value('blue'), alt.value('lightgrey'), legend=None),
```
and then remove ``color_selection``

**Comment by shun-lin** [comment]
Thank you so much @jakevdp !
