### ISSUE TITLE
svg output?

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#179]
Possible to have an svg output path as well, not just png? Hopefully both as an export link and as a direct call from within python (`write(chart.to_svg())`). Thanks!

**Comment by jakevdp** [comment]
As I mentioned in #178, altair doesn't do any rendering – it simply ouputs validated vega-lite JSON. It appears that vegalite.json actually [does support SVG output](https://github.com/vega/vega-lite/blob/c0bd61fd45f64a31c4fb733cc560c1384cb19330/scripts/generate-images.sh) – I'm not sure how to best access that from Altair/Jupyter.

**Comment by jakevdp** [comment]
As for doing it from Python... currently that would probably require some sort of Python package wrapping the vega-lite javascript... maybe it could be done somehow within the [ipyvega](https://github.com/vega/ipyvega) package? Would require Python being able to call-out to Javascript (perhaps via node?) I've never tried anything like that myself.

**Comment by jakevdp** [comment]
Though creating a vega-lite importer for matplotlib would do this much more cleanly!

**Comment by kanitw** [comment]
> Though creating a vega-lite importer for matplotlib would do this much more cleanly!

Possibly, but that will be a lot of work and I'm not sure how would it work with interactions we gonna add in VL 2.0.

**Comment by jowens** [comment]
We've previously done svg output by calling vg2svg from the vega distribution (after calling vl2vg), and will presumably do the same here. This is not a big deal. Altair should stick to what it's good at.

**Comment by jowens** [comment]
I've got this working (kludgily) by piping `chart.to_dict()` through `json.dumps` then `vl2vg` then `vg2svg`. Adding this will make it cleaner, since the last pipe has to go through a tempfile: https://github.com/vega/vega/issues/612

**Comment by jakevdp** [comment]
Hi,
FYI I've added a PR with an experimental utility that streamlines this: https://github.com/ellisonbg/altair/pull/202

It's ugly because of the nodejs dependencies, but it works for me!

**Comment by swayson** [comment]
The references link above is broken but I see the new docs talk about this. Therefore posting it here as others may find this useful.

https://altair-viz.github.io/documentation/displaying.html#saving-figures-programatically

**Comment by jakevdp** [comment]
Thanks @swayson – just FYI, the functionality there requires functionality currently in the master branch, not yet in a release. It should be in the release soon.

**Comment by jakevdp** [comment]
I think this is suitably addressed in docs now.
