### ISSUE TITLE
use slider to set the opacity value

### ISSUE THREAD

**Issue by zanarmstrong** [altair-viz/altair#1790]
I have a scatterplot where there are lots of overlapping points. I want the "user" to be able to use a slider to change the opacity value of all the points, so that they can use interaction to get a sense of the density of the points. 

I found how to set up a slider using [this example[(https://altair-viz.github.io/user_guide/interactions.html#selection-values-in-expressions). However, when I try to use the selector.cutoff to set the opacity directly, I get errors about it not being a value. In short, I want to write something like opacity=selector.opacity, where the selector.opacity is defined by a slider that has a min of 0 and a max of 1. The trouble seems to be that then it's a value, not an expression - maybe?

Is this possible?

**Comment by jakevdp** [comment]
Yep, you can do it this way:
```python
import altair as alt
from vega_datasets import data

selector = alt.selection_single(
    fields=['opacity'],
    bind=alt.binding_range(min=0, max=1, name='opacity'),
    init={'opacity': 1.0}
)

alt.Chart(data.cars.url).transform_calculate(
    opacity=selector.opacity
).mark_point().encode(
    x='Miles_per_Gallon:Q',
    y='Horsepower:Q',
    opacity=alt.Opacity('opacity:Q', scale=None),
).add_selection(
    selector
)
```
Some notes:

- selector fields cannot be used directly in an encoding, so we use a calculate transform to make it one of the data fields.

- the opacity encoding has ``scale=None``, which means that the raw value of the encoded field should be used, rather than having the range of values mapped to an opacity scale.

**Comment by zanarmstrong** [comment]
Thank you for the code and the notes! 

In particular, the notes captured the two key points I was missing.
