### ISSUE TITLE
All properties in altair.Chart.configure_axisRight are Undefined

### ISSUE THREAD

**Issue by domoritz** [altair-viz/altair#1795]
In the docs at https://altair-viz.github.io/user_guide/generated/toplevel/altair.Chart.html?highlight=error%20bars#altair.Chart.configure_axisRight, all properties are defaulting to undefined. 

<img width="809" alt="Screen Shot 2019-11-18 at 15 48 15" src="https://user-images.githubusercontent.com/589034/69103660-d6f48d00-0a1a-11ea-83b2-162717e84f51.png">

**Comment by jakevdp** [comment]
Every property of every function in Altair defaults to Undefined. In Python, the default is normally None, but None translates to ``null`` in JSON, which has special meaning in Vega-Lite. So we created a new sentinel called "Undefined" to denote parameters that are not defined.

A bit confusing? Yes, but it seemed like the best way forward.

**Comment by jakevdp** [comment]
(an alternative would have been for every function signature to just be ``**kwargs``, but then the parameters would not be explicitly listed in the call signature and would not tab complete)

**Comment by domoritz** [comment]
Thanks for the explanation.
