### ISSUE TITLE
SVG Saving Time Varies Significantly from Run to Run

### ISSUE THREAD

**Issue by todpole3** [altair-viz/altair#1796]
I'm trying to save a geo plot to .svg file in Altair but realized that from run to run the plot-saving time differs significantly, for example, the following are measured from 10 consecutive saving calls.
```
Time passed: 3.946197986602783s
Time passed: 5.871866941452026s
Time passed: 4.180978775024414s
Time passed: 3.17307710647583s
Time passed: 4.445468902587891s
Time passed: 3.218013048171997s
Time passed: 4.74577522277832s
Time passed: 3.7256979942321777s
Time passed: 4.468179941177368s
Time passed: 4.8163206577301025s
Avg time = 4.26187949180603s
```
I'm curious about where the large uncertainty comes from. 

Would you please explain? Thanks!!

**Comment by jakevdp** [comment]
I suspect it comes from selenium and its interaction with ChromeDriver/GeckoDriver. There's a lot of moving parts there.

**Comment by todpole3** [comment]
Thank you. Is there a way to create the browser only once and use it for multiple runs, or call the large JS files locally?

**Comment by jakevdp** [comment]
Yes, that is possible with selenium, but no, there is no mechanism to do that in Altair. It would be a useful addition (I've been thinking about that particularly for making doc builds faster and more reliable).

To be quite honest, I'm unlikely to get to it any time soon. Is that something you'd like to work on?

**Comment by todpole3** [comment]
@jakevdp If I'd like to try, could you give me some pointers on where to start? (I may not be able to get to it soon, but want to get more clues about this issue.)

**Comment by jakevdp** [comment]
Sure - the code that interacts with selenium is here: https://github.com/altair-viz/altair/blob/master/altair/utils/headless.py

Currently it's hard-coded such that a new driver is created each time a figure is saved. For saving multiple files, it would be more efficient to set up a single driver for all of them.

One design option would be to make it possible to pass a list of charts to compile_spec, but it's hard to think of a good way to thread this through to chart.save.

Better would be to create some kind of context manager, so you could do something like:

```
with alt.setup_selenium():
    for i, chart in enumerate(charts):
        chart.save(f'chart_{i}.svg')
```
or something similar to that.

Let me know if you have thoughts on that!

**Comment by todpole3** [comment]
Thanks for the pointers, will try to take a deeper look.
