### ISSUE TITLE
Plotting renderer for Azure Databricks notebooks 

### ISSUE THREAD

**Issue by crawforc3** [altair-viz/altair#1797]
I found out that Altair works in Azure Databricsk notebooks with the "colab" renderer. It wasn't a very intuitive process though and I tried almost all the renderers except "colab" (thought I read that somewhere I didn't need to specify it but I guess that's only in colab notebooks).  Anyway, I ended up trying colab and was successful. 

Not sure it makes sense to have a renderer for databricks, but it sure would be nice and easy to remember.

**Comment by jakevdp** [comment]
I think this will probably be the best solution: https://github.com/altair-viz/altair/pull/1793

We will probably make this new renderer the default in the next release, in which case Altair should just work in DataBricks without any additional configuration.

**Comment by jakevdp** [comment]
If you're able to install from master and check if #1793 solves your problem, that would be great!

**Comment by chriscrawfordTR** [comment]
I can't install from Github so need to learn how to make an egg or whl. This is uncharted territory for me -- is there a preference for one over the other?

**Comment by jakevdp** [comment]
Building a wheel is step 8 in https://github.com/altair-viz/altair/blob/master/RELEASING.md

**Comment by chriscrawfordTR** [comment]
Thanks @jakevdp I created the WHL and was able to use the HTML renderer with no issues.

If it matters:
Altair version 3.3.0dev0
DataBricks runtime 6.1

**Comment by jakevdp** [comment]
Great! Thanks for checking on that

**Comment by jakevdp** [comment]
The HTML renderer is now part of the v3.3 release, and will be made the default in v4.0.
