### ISSUE TITLE
Drop Python 2 support in Altair 4.0

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#1799]
Altair 4.0 will be released as soon as possible after Vega-Lite 4.0, and python 2 end of life is six weeks away.

I propose the following:

- in the coming weeks, prepare a Py2-compatible altair 3.3.0 release with the last few months of bug fixes & features
- create a v3.X branch in case we need 3.3.X bug fix releases in the near future
- after that, drop Py2 testing & compatibility code in master
- begin preparations for the 4.0 release with support for only Python 3.5 & newer.

Please let me know if you have thoughts!

**Comment by domoritz** [comment]
I'm fully supportive of dropping Python 2. It reduces the maintenance overhead.

**Comment by tacaswell** [comment]
If you are going to drop python2 you should also adopt NEP 29 (https://numpy.org/neps/nep-0029-deprecation_policy.html) which means if you release after Jan 07, 2020 you can support py3.6 +.

**Comment by jakevdp** [comment]
Done in #1813
