### ISSUE TITLE
How to properly use `facet` and `resolve_scale` together?

### ISSUE THREAD

**Issue by xujiboy** [altair-viz/altair#1800]
Hi I am trying to use `resolve_scale()` and `facet()` in the same chart but either don't get the scale resolved or keep getting an error saying:
```
Javascript Error: Unrecognized scale name: "child_layer_0_y"

This usually means there's a typo in your chart specification. See the JavaScript console for the full traceback.
```
Here is the code:
```python
from vega_datasets import data

cars = data.cars()

chart_base = alt.Chart(cars.sample(20, random_state=42))

chart_mpg = chart_base.encode(
    x='Name:N',
    y=alt.Y('Miles_per_Gallon:Q', scale=alt.Scale(type='linear'))
)

chart_weight = chart_base.transform_filter(
    alt.datum.Weight_in_lbs > 0  
).encode(
    x='Name:N',
    y=alt.Y('Weight_in_lbs:Q', scale=alt.Scale(base=10, type='log')),
    color=alt.value('red')
)

# this errors out
display((chart_mpg.mark_bar() + chart_weight.mark_line()).resolve_scale(y='independent').facet(column='Origin'))

# this works but the scale is not resolved
display((chart_mpg.mark_bar() + chart_weight.mark_line()).facet(column='Origin').resolve_scale(y='independent'))
```
And here is the working but wrong chart (the scale is not resolved, `Miles_per_Gallon` ends up on the same scale as `Weight_in_lbs`):
![visualization](https://user-images.githubusercontent.com/10766549/69459503-baac6500-0d26-11ea-9753-3f748e7a4145.png)
- May I know how to resolve this issue? Thanks~

**Comment by jakevdp** [comment]
Unfortunately, I don't think resolve_scale can be used at this level of granularity within Vega-Lite. It would be worth a bug report / feature request in http://github.com/vega/vega-lite

**Comment by jakevdp** [comment]
Here's a compact Vega-Lite spec based on your example that demonstrates the problem ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBjWLAZwDoArCgewDtIBfAGnCni1kYoDN6WALb4A2ugqxhABxwBTfACYADCwC6HCJH6wS8+PnQl6ODMOap08AJ4zFqSI3rCAlo1h42Ufq-k5ofEgAeSxXAHN3VnZOSAp7EiNObRxYG3kscWSINGycqGFyAGsggCNySC18nMh5RhNod3Ck6urIAA8jSFt7IOc3Dy8fPwCggDlpRRjW-MgbLp6HKABHDF54V0QNgDdFbx0RwMcAWVcFCgB9eywLgHFPHCZWPJyWF+nq0BmC4qCcdz2L20dQaTRa3ygnSs3TsSycLncnkqw38RygE2EUyq3zmC1hQVW602CFcu2RB1RQQA6vIIgALeAXdwXHClCjPb5vVpcnKabKQLDyBg4MnQihkBRdeaOdzQeT2RhyxiGFg8t4sIA)):
```json
{
  "data": {"url": "data/cars.json"},
  "transform": [{"sample": 20}],
  "facet": {"column": {"type": "nominal", "field": "Origin"}},
  "spec": {
    "layer": [
      {
        "mark": "bar",
        "encoding": {
          "x": {"type": "nominal", "field": "Name"},
          "y": {"type": "quantitative", "field": "Miles_per_Gallon"}
        }
      },
      {
        "mark": "line",
        "encoding": {
          "x": {"type": "nominal", "field": "Name"},
          "y": {"type": "quantitative", "field": "Weight_in_lbs"}
        }
      }
    ],
    "resolve": {"scale": {"y": "independent"}}
  }
}
```

**Comment by xujiboy** [comment]
@jakevdp Thank you very much for pointing out the right direction. I did a little research on the vega-lite git repo and found out that a very similar bug was [reported](https://github.com/vega/vega-lite/issues/4373) by you about a year ago and it seems that it is still open. From what I read in the threads, [the faceted dual axis charts have not been supported in vega-lite](https://github.com/vega/vega-lite/issues/4373#issuecomment-447726094), not sure if it will be supported in the future though. The workaround proposed by you using `hconcat` and/or `vconcat` with `filter` works for me as well ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBjWLAZwDoArCgewDtIBfAGnCni1kYoDN6WALb4A2ugqxhABxwBTfABYADCwC6HCJAAWJJmXgoxnUBG05YAT3lZxnc2geOow8gGt8kAEblIWl215Rn1oAEtGAHN8M0DzSAAPGMh4KxlFVEhGemEI2Dw2KH4w+RxoLwA5aUV2Z0DIK2TU9K8ARwxeeDDELoA3RULIYtLyzIBZMIUKAH10rGmAcXycJlYWOrBawNj6tyxPVHRmjMgcCIGofRW7ZEgseXKtuMhg0Ijow43HRKa0jKhsrlGPl-EUSmVKtVWAE4lBGocUn82h1GF0emF+qCvrCwSMvAB1eRhSI6eDTCLTHDeCj+bGwyAUMgKX4tTIraLrHFxFicly8iCaZx3eQMHCYhGM-L-dDwqARaDydKMBWo0E-TIUHTkB5rGFcHh8QQicToYo4eC2LwACkIGGEVAA8lhiREwABeD1gADkAFUAMoAQS9AEpWOpOE8dlBLDYbmATNtsZA9gcoL47Hrvq96OEojE6VAkgjjl5AXkCriIZkqsIapmXA0Wf9IO1Ot0EBiLkNwaMoBMprNbItlqseRsno4o98U02UKdzmqrkI5-dHvWgiEc+981z1WhEayATly2rhlWoDW6wXG8WkZlW6j230LgX6mfe5BCcTSeTGJTqbSXL1JKzK3oepz0Byr58vy5iwYK3z3KK4r7iB0o3nKyqKsEKpGIMRZQJq2qPBO+q8AIQiiKgEjdualqZDaCB2o6zqRK6Hput6ACi2D0OkIZhhGARRqc1j0fGGxTvEM6ZOmgHPNmuYfE4u4EUcd5HkCIKDO+kK1tC16yup4EPmiHaYjpPZeP2IqDvMSw4CszBjoEpEQFJ2gyfuJa3GcjBdkuNzCmuSaKdunyqbOmRlsCFbdni1ZQm5DZGQezamU+nZYkBDa6ZkX4kmSFJUjS644gyTLoT50aQaw0GOC5fLOAh8RIfQYroWhySypA8rYVhqr4V4RGrrqQrcORRpUfGpqTBacaQIx8DMU6LqMO6npegAUrAMi8AJGgRiAnDhusQA)), only that it seems a bit laborious compared with the declarative intent of `facet`.

**Comment by breadbaron** [comment]
Agree that faceted multi-axis charts would be nice 👍

**Comment by blehman** [comment]
This [thread on facets](https://github.com/altair-viz/altair/issues/1934) might be helpful. I used it to solve [this related issue](https://stackoverflow.com/questions/64611577/how-to-build-an-altair-layered-chart-w-dual-axis/64614691#64614691) w/ facets.

**Comment by joelostblom** [comment]
Closing as this is tracked in https://github.com/vega/vega-lite/issues/4373 and there is nothing that can be done on the altair side of things to fix it.
