### ISSUE TITLE
Altair graphs wrapped in ipywidgets.Output not being rendered

### ISSUE THREAD

**Issue by sradomski** [altair-viz/altair#1801]
Dear all,

first of all, thank you for a *very* nice library that produces beautiful, interactive graphs with very little effort.

We are trying to use these graphs in notebooks served via [voila](https://github.com/voila-dashboards/voila) as interactive web applications. We managed to get all the various graphs to show up, when using the `kaggle` renderer, which will work in both, plain jupyter notebooks (not lab) and voila webapps.

However, when we wrap these graphs into an `ipywidget.Output` class, there is no more output in neither plain jupyter, nor the voila webapps. An example adapted from the simplemost altair graph I could find is attached below:

```
from IPython import display
import ipywidgets as widgets
import altair as alt
import pandas as pd

alt.renderers.enable('kaggle',embed_options={'actions': False})

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

chart = alt.Chart(source).mark_bar().encode(
    x='a',
    y='b'
)
output = widgets.Output()
with output:
    display.display(chart)
output
```

Being able to wrap graphs into specific outputs is important to control the content that is displayed to the user when serving notebooks as interactive webapps via voila and we were wondering whether there is some way to achieve this behavior?

**Comment by jakevdp** [comment]
The new HTML renderer from https://github.com/altair-viz/altair/pull/1793 should work for this, and we're planning to make it the default renderer in the 4.0 release.

**Comment by jakevdp** [comment]
Backstory is that JupyterLab started out by forbidding cells from outputting executable Javascript, instead requiring a frontend extension model wherein vetted code is loaded into the JupyterLab frontend at build time, and then libraries can output static specs that are interpreted by these extensions. JupyterLab has since relaxed those restrictions on Javascript outputs, which is why until now we've not provided JupyterLab-compatible HTML outputs.

Hopefully #1793 as a default renderer will make things more straightforward and predictable for users.

**Comment by sradomski** [comment]
We are using plain Jupyter, not the Lab and I am not sure about the approach taken by voila. 

Seeing that the `html` renderer is not yet available for the version of altair in `conda`, I was hoping that you could verify that it is indeed working within a `ipywidgets.Output` as exemplified in the code snippet above before we forfeit the convenience of the conda package manager?

**Comment by jakevdp** [comment]
I merged it 2 days ago... it's not yet part of any release.

I think it would be far more straightforward for you to run ``pip install git+git://github.com/altair-viz/altair.git`` and try it, than for me to try to guess what your entire compute environment is and to try it for you.

**Comment by sradomski** [comment]
I just tried it on my local host with a pretty vanilla [Anaconda3-2019.10](https://repo.anaconda.com/archive/Anaconda3-2019.10-MacOSX-x86_64.sh) installation. Starting the example from above in a Jupyter Notebook (v6.0.1) and changing `kaggle` to `html` will not show any output when wrapped in an `ipywidgets.Output` and the JavaScript console shows nothing with regard to Vega or Altair.

The approach with wrapping output in `ipywidgets.Output` for interactive notebooks works fine with `bqplot` graphs if this is of any help.

**Comment by jakevdp** [comment]
Thanks - it looks like ipywidgets scrub all javascript output from HTML in output widgets. So only the notebook renderer will work for output widgets within notebooks, but that likely won't translate to other frameworks like voila.

The reason bqplot works with widgets is that it only works with widgets.

**Comment by jakevdp** [comment]
I'm honestly not certain what to suggest: it really seems like the Jupyter ecosystem goes out of its way to make things difficult for packages that rely on Javascript outputs.

**Comment by sradomski** [comment]
Thank you for looking into this. I would really like for this to work - voila seems to fill a void with respect to notebooks as simple "self-service" analytics web applications and altair / vega just are the most convenient for polished, dynamic and interactive graphs.

If you could point us into the right direction, maybe we can come up with a pragmatic kludge for the time being?

**Comment by jakevdp** [comment]
I would start by checking if voila scrubs javascript from HTML outputs (i.e. the html renderer may work in voila despite not working in the notebook)

Another option would be to create a widgets renderer, which would essentially output two widgets: an HTML widget containing [this](https://github.com/altair-viz/altair/blob/master/altair/utils/html.py#L85) followed by a javascript widget containing [this](https://github.com/altair-viz/altair/blob/master/altair/utils/html.py#L86-L133)

I suspect that would work in widgets outputs in Jupyter notebook and voila, but probably not in JupyterLab because of its distinct architecture.

**Comment by sradomski** [comment]
The problem is, that the altair `div` is inserted dynamically and does not exist in the DOM yet when the JavaScript block is run and `document.getElementById` will return nothing. I will just hack something together locally with window.setTimeout() for a delayed JS execution with the kaggle renderer and the current version in conda for now.

**Comment by sradomski** [comment]
Having this JavaScript magic at the top of your notebook will allow Altair / Vega graphs to be wrapped in `ipywidget.Output` and be displayed in `voila` with the `kaggle` renderer and the latest version in `conda`:

<pre>
%%javascript
(function() {
    var el = document.getElementById("notebook-container")
    const config = { attributes: false, childList: true, subtree: true };
    const callback = function(mutationsList, observer) {
        for(let mutation of mutationsList) {
            if (mutation.type === 'childList') {
                if ($(mutation.target).hasClass('jupyter-widgets-view')) {
                    $(mutation.target).find("script").each(function() {
                        // make sure we found a script with an accompanying altair-viz
                        if ($(this).prev().attr('id').startsWith('altair-viz-')) {
//                             console.log(this)
                            eval(this.innerHTML);
                        }
                    })
                }
            }
        }
    }
    
    const observer = new MutationObserver(callback);
    observer.observe(el, config);

})();
</pre>

It will register a `MutationObserver` at the Jupyter output container and evaluate all the Javascript that has a corresponding `div` with an altair visualization. It is very much a hack but does the job for my demo on thursday 😄

**Comment by firasm** [comment]
hey @sradomski,

Not directly related to your question, but in case this is helpful, here is a demo of Altair plots served as a stand-alone app using Dash https://firas-dash-demo2.herokuapp.com and deployed on Heroku. 

The code is here: https://github.com/firasm/dash_deployed_app, pretty easy to do!

**Comment by crendl** [comment]
I faced the same issue, and can present a workaround:

I use [Altair Viewer](https://altair-viz.github.io/user_guide/display_frontends.html#altair-viewer) to display my chart via a local HTTP server, then I create an iframe and pass it on as a widget; e.g:

```python
import altair as alt
import pandas as pd
from IPython.display import display, IFrame
alt.renderers.enable('altair_viewer')

source = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

chart = alt.Chart(source).mark_bar().encode(
    x='a',
    y='b'
)
chart
```

Displaying chart at http: // localhost:19826 /

```python
result = widgets.Output()

scr='http://localhost:19826/'

with result:
    display(IFrame(scr,width=300,height=400))
result
```

![image](https://user-images.githubusercontent.com/15796851/96896462-d0be2a80-148d-11eb-9ade-8e61efec7662.png)

**Comment by joelostblom** [comment]
@sradomski I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet?

**Comment by sradomski** [comment]
When we were last working with Altair, we did use the hack with the MutationObserver outlined above. I am not sure that you would call it "resolved" but it was good enough for us at the time. I still consider the inability of altair to be rendered into a ipywidget.Output as an issue but cannot confirm whether this is even still the case as we switched to plot.ly for most of our interactive graphs.

**Comment by joelostblom** [comment]
It is now possible to use the `JupyterChart` class to create Altair charts that can interact with jupyter/ipywidgets directly. See this section in the docs for details https://altair-viz.github.io/user_guide/jupyter_chart.html

**Comment by firasm** [comment]
I love this!! This is so great. Thanks team!
