### ISSUE TITLE
Change highlighted selection area color

### ISSUE THREAD

**Issue by ZisisFl** [altair-viz/altair#1806]
I would like to ask if there is any way to to change the gray color of the selection area in a graph I have searched over documentation and some github issues but found nothing on that.
![image](https://user-images.githubusercontent.com/15019941/69532381-5d125580-0f7e-11ea-85b6-29e669f4ca1f.png)

**Comment by jakevdp** [comment]
This can be controlled via the ``mark`` property of the selection. For example:
```python
import altair as alt
from vega_datasets import data

interval = alt.selection_interval(
    mark=alt.BrushConfig(fill='green')
)

alt.Chart(data.cars.url).mark_point().encode(
  x='Horsepower:Q',
  y='Miles_per_Gallon:Q',
  color=alt.condition(interval, 'Origin:N', alt.value('lightgray'))
).properties(
  selection=interval
)
```
<img width="522" alt="Screen Shot 2019-11-25 at 5 30 05 AM" src="https://user-images.githubusercontent.com/781659/69544490-b1004880-0f44-11ea-9e61-9007a26b37ba.png">

**Comment by ZisisFl** [comment]
@jakevdp Thanks a lot Jake this is great
