### ISSUE TITLE
[Enhancement Idea] auto-encodings

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#181]
I was playing around with Altair recently, and had a thought: what if we provide a method that's something like `Chart.autoencode()` that tries to determine the optimal encodings in a reasonable way. For example, if you have data with columns named `x`, `y`, `color`, etc. it would automatically set the associated encoding.

Absent that, say you pass data with two float columns and a categorical column. It would make sense to make this a colored scatter-chart. If there's one float column and one categorical column, it would make sense to make a bar-chart, and so on.

It certainly wouldn't cover all possible scenarios, but it could be a nice feature for the simplest of cases.

On the other hand, it could prove confusing, as users might see poor results of an auto-plot and assume that's the extent of what altair does.

**Comment by jheer** [comment]
@kanitw is working on something that does (and much more) as part of his thesis: the CompassQL visualization recommender. Let's discuss more next we meet up in person...

**Comment by kanitw** [comment]
I'm happy to show you a demo after I return to Seattle from Thailand after CHI deadline too
(Say sometimes around mid October.) -- if you haven't seen it from Jeff before then.

**Comment by jakevdp** [comment]
Great!
