### ISSUE TITLE
ImputeTransform does not work for my plot 

### ISSUE THREAD

**Issue by KarlosMuradyan** [altair-viz/altair#1815]
Hey this is possibly related to #1768, but I'm not able to get the solution from that issue to work for me.

Here is a reproducible version of my plot. The issue is that the the missing dates do not exist in my original dataframe, so how do I tell Altair to skip plotting lines between those points?

data file and original csv attached

![visualization](https://user-images.githubusercontent.com/18456186/69770266-49f9b400-113d-11ea-8df6-aae8674d26cb.png)

```
data = pd.read_csv('data.csv')

location = 'Crofton Substation' 
width = 800


data= data[data['STATION_NAME'] == location]


alt.Chart(data, title = f'Concentration of selected PMs in {location}').\
            mark_line(width = 10, point=True).\
            encode(
                x=alt.X('index:T', title = 'date', impute=alt.ImputeParams(
                          value=None)),
                y=alt.Y('RAW_VALUE:Q', title = 'Concentration()'),
                color= alt.Color('PARAMETER'),
                tooltip = [alt.Tooltip('index:T', title = 'Date:'),
                            alt.Tooltip('RAW_VALUE:N', title = 'Polution')]).\
            properties(
                width=width,
                height = 600
            )
```
[data.csv.zip](https://github.com/altair-viz/altair/files/3899455/data.csv.zip)

**Comment by jakevdp** [comment]
Two notes:
- you want to impute the y value, not the x value
- if the x values at which you'd like to impute are not part of the dataset, you need to specify them explicitly using ``keyvals``.

For timestamps, the keyvals must be raw unix timestamps. So you can do something like this:
```python
import altair as alt
import pandas as pd

data = pd.read_csv('https://github.com/altair-viz/altair/files/3899455/data.csv.zip')
location = 'Crofton Substation' 
width = 800

data= data[data['STATION_NAME'] == location]
keyvals = pd.date_range(data['index'].min(), data['index'].max(), freq='MS').astype(int) // 1000000

alt.Chart(data).mark_line(
    width = 10,
    point=True
).encode(
    x=alt.X('index:T', title = 'date'),
    y=alt.Y('RAW_VALUE:Q',
        title = 'Concentration()',
        impute=alt.ImputeParams(value=None, keyvals=list(keyvals))
    ),
    color= alt.Color('PARAMETER'),
    tooltip = [alt.Tooltip('index:T', title = 'Date:'),
               alt.Tooltip('RAW_VALUE:N', title = 'Pollution')]
).properties(
    title=f'Concentration of selected PMs in {location}',
    width=width,
    height=600
)
```
![visualization (47)](https://user-images.githubusercontent.com/781659/69777974-673b7c00-1157-11ea-8da4-9370712e044d.png)

**Comment by KarlosMuradyan** [comment]
Thank you very much for the response!! It works now!!
