### ISSUE TITLE
Interactive plot selections and callbacks

### ISSUE THREAD

**Issue by pokrovskyy** [altair-viz/altair#1816]
I'm embedding an Altair choropleth plot in an HTML page. Now I'm interested in a scenario when I click this map and receive the territory under selection (or its ID) I'm aware of simpler selection options in Altair (mostly from the Example Gallery that tie to other charts / aggregation / subsetting), but could not find any options to intercept the produced events on the client side. (which I believe would be JavaScript)

Does Altair offer any ways to register Vega event handlers to help with this implementation?

**Comment by jakevdp** [comment]
Altair does not offer any way to register event handlers. That would have to be done in Javascript via the Vega view API: https://vega.github.io/vega/docs/api/view/#signals
