### ISSUE TITLE
AttributeError: 'Encoding' object has no attribute 'set_trait'

### ISSUE THREAD

**Issue by GeweiWang** [altair-viz/altair#182]
When trying to run the code below, I got an error message:
  AttributeError: 'Encoding' object has no attribute 'set_trait'

```
from altair import datasets, Chart

data = datasets.load_dataset('cars')

c = Chart(data).mark_circle().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
)
```

**Comment by jakevdp** [comment]
I suspect you have an old version of traitlets. What is the result of this?
```
import traitlets
print(traitlets.__version__)
```

**Comment by jakevdp** [comment]
If you want to update traitlets, it's relatively easy.

If you installed Altair via ``pip``, use
```
$ pip install --upgrade traitlets
```

If you installed Altair via ``conda``, use
```
$ conda update traitlets
```

**Comment by GeweiWang** [comment]
Thanks Jake!
I updated traitlets from 4.0 to 4.2.2, and the code works perfectly.

**Comment by jakevdp** [comment]
Closing; traitlets 4.1 is now a pinned requirement
