### ISSUE TITLE
How to set default selected bar

### ISSUE THREAD

**Issue by zouwenjiao** [altair-viz/altair#1820]
Hi, Jake, do you know how to set default selected bar in the interactive Cross-hightlight?
For example, can I set my initial page with Drama selected instead of every bar?
https://altair-viz.github.io/gallery/interactive_cross_highlight.html

**Comment by jakevdp** [comment]
Generally you can initialize selections using the ``init`` keyword within the selection specification; for example:
```python
import altair as alt
from vega_datasets import data

pts = alt.selection(type="single", fields=['Major_Genre'], init={'Major_Genre':'Comedy'})

alt.Chart(data.movies.url).mark_bar().encode(
    x='Major_Genre:N',
    y='count()',
    color=alt.condition(pts, alt.ColorValue("steelblue"), alt.ColorValue("grey"))
).properties(
    width=550,
    height=200
).add_selection(pts)
```
![visualization (50)](https://user-images.githubusercontent.com/781659/69877120-20907380-1276-11ea-8064-6bec3a912ef2.png)

However, selection initialization appears not to be working within concatenated charts; I filed a bug report here: https://github.com/vega/vega-lite/issues/5599.

**Comment by jakevdp** [comment]
Appears that this has already been fixed in Vega-Lite, and the fix should make it into the 4.0 release of Altair.

**Comment by stephenwilliams22** [comment]
As of altair 5.2 `init` should be replaced with `value`, correct?

**Comment by mattijn** [comment]
Yes, in the example above, I think it goes from:
```python
init={'Major_Genre':'Comedy'}
```
To:

```python
value='Comedy'
```
