### ISSUE TITLE
Axis title font size seems to change padding not text

### ISSUE THREAD

**Issue by Zylatis** [altair-viz/altair#1821]
Hi I must be missing something silly: i am using the following code 

```python
chart = alt.Chart(pd.DataFrame(data)).mark_bar(color='#203082', size = 60).encode(
    x='date',
    y='n_bookings',
	).properties(
    width=600,
    height=300
    ).configure_axis(
    grid=False,
    labelAngle=0,
    labelFontSize=30,
    titleFontSize=30,
    titleFontWeight='normal',
    titleFont="Museo Sans 300",
    labelFontWeight='normal',
    labelFont="Museo Sans 300"
    ).configure_view(
	strokeOpacity=0
)

chart.save('test.html')
```

What i am trying to do is increase the font size of the axes labels (date and n_bookings). Based on a (possibly incorrect) reading of the docs it looks like i want to configure the axis to change the titleFontSize (as label font size seems to change the tick labels, which makes sense).

Here is a screenshot with titleFontSize = 30
![size30](https://user-images.githubusercontent.com/1456631/69848752-020a9680-12cf-11ea-8838-e75aac1266b5.png)

Here is a screenshot with titleFontSize = 60
![size60](https://user-images.githubusercontent.com/1456631/69848758-06cf4a80-12cf-11ea-85ff-dff451fcf13a.png)

As far as i can tell all that has changed is some padding, what am I missing?

Thanks!
Z

**Comment by jakevdp** [comment]
I don't think that ``"Museo Sans 300"`` is a valid font. If you change it to something like ``"monospace"`` or "``sans serif``", the configuration works as expected.

I'm not certain why this is happening; it would be worth reporting as a Vega-Lite bug.

**Comment by Zylatis** [comment]
Hmm, weird, as that font definitely works in my D3 code (which I am porting to VegaLite via Altair). Thanks for the info, I will raise it with the V-L folks!

**Comment by Zylatis** [comment]
Apologies for issue spam, but one question based on this issue here
https://github.com/vega/vega/issues/1671

If i wanted to try include a custom font external font link, how would I encode this in Altair?

**Comment by Zylatis** [comment]
Issue resolved once I made sure the header stuff was loaded first.
