### ISSUE TITLE
call to remove redundant fields of output vega-lite?

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#183]
I have a large dataframe that I can plot with Altair. The dataframe has many, many columns. Everything works just fine when I plot what I want to plot. However, the amount of data in the dataframe is much larger than it has to be. Since Altair can likely determine that certain columns will never be used in the plot it generates (those columns never appear in any call to the `Chart` constructor), could there be a call to remove the fields from the output? I'd like the output of `chart.to_dict()` or `chart.to_html()` to be much smaller by removing these columns. `chart.cleanup()`?

(Of course I can do this myself manually, most likely by manipulating the dataframe.)

**Comment by jakevdp** [comment]
This is a nice idea: I could see implementing it either via a ``chart.cleanup_data()`` or similar method, and perhaps also add it as an option on ``to_dict()`` and ``to_html()``, e.g. ``chart.to_dict(cleanup_data=True)``

**Comment by jakevdp** [comment]
It would be made slightly more tricky by the multiple levels of data available in layered charts, but that shouldn't be too much of a problem.

**Comment by jowens** [comment]
:+1:

**Comment by jakevdp** [comment]
I put an initial attempt at this in #186. Still some details to iron-out, though.

**Comment by ellisonbg** [comment]
+1 on this idea. We could also add an option that would implement the filters and transformations in python rather than send all the data to the frontend. That would make a big difference if the filters/transforms reduce the number of rows significantly.

**Comment by ellisonbg** [comment]
After teaching with Altair, I think this is super important.

**Comment by jakevdp** [comment]
We tried this in 1.3, and it backfired badly... because of the data model in Altair and how it interacts with transforms, it's quite difficult to perfectly infer what columns are used, and trying to guess invariably leads to errors in corner cases.

I think the best way forward is to point people to the JSON renderer for use with large dataframes.
