### ISSUE TITLE
Save PNG creates a chart with axis but no other data

### ISSUE THREAD

**Issue by samesand** [altair-viz/altair#1834]
Using Selenium and Chrome Driver and Windows 10.

When I use the .save('plot.png') comand, the saved picture displays only the x and y axes with their titles, but nothing else.

I have tried multiple chart types, including very simple ones, and I get the same result.

Example
```
df = pd.DataFrame({'a':[1,2], 'b':[3,4]})
alt.Chart(df).mark_line().encode(x='a', y='b').save('plot.png')
```
Will produce only a box with a as the x-axis title and b as the y-axis title

**Comment by jakevdp** [comment]
Typically this means you have enabled some data transformer that puts the data in a place selenium cannot access (such as ``"json"`` or ``"data_server"``. Try this:
```python
alt.data_transformers.enable('default')
df = pd.DataFrame({'a':[1,2], 'b':[3,4]})
alt.Chart(df).mark_line().encode(x='a', y='b').save('plot.png')
```

**Comment by jakevdp** [comment]
More info here: https://github.com/altair-viz/altair/issues/1600

**Comment by samesand** [comment]
> Typically this means you have enabled some data transformer that puts the data in a place selenium cannot access (such as `"json"` or `"data_server"`). Try this:
> 
> ```python
> alt.data_transformers.enable('default')
> df = pd.DataFrame({'a':[1,2], 'b':[3,4]})
> alt.Chart(df).mark_line().encode(x='a', y='b').save('plot.png')
> ```

Thanks, that fixed it!
