### ISSUE TITLE
Column name with a dot

### ISSUE THREAD

**Issue by drorata** [altair-viz/altair#1838]
My dataframe, contains a column with the name `Total.Score`. After many frustrating hours, I suspected that the `.` in the name is to blame for the empty render. Indeed, after:

```python
df.rename({"Total.Score": "Total_Score"}, axis=1,inplace=True)
```

I could render the chart:

```python
alt.Chart(df).mark_circle(size=60).encode(x="Total_Score", y="customerId")
```

Did I miss something fundamental? Is it a bug?

**Comment by drorata** [comment]
#284 
Maybe this additional/duplicated ticket will help others to find more easily the issue.

**Comment by jakevdp** [comment]
This should be added to the documentation. Are you interested in contributing?

**Comment by jakevdp** [comment]
(it's in the docs here: https://altair-viz.github.io/user_guide/encoding.html#encoding-channel-options, but clearly that's not discoverable enough)

**Comment by drorata** [comment]
It is documented... I guess I should have found it ;)

**Comment by jakevdp** [comment]
Nah, I think the fact that you didn't find it shows that it's not documented well.
