### ISSUE TITLE
actions menu rendering issues in jupyterlab using alt.renderers.enable('html')

### ISSUE THREAD

**Issue by parodayco** [altair-viz/altair#1845]
Hi, the new HTML rendering output is good in most cases but problematic in Jupyterlab. I'm running a pyenv environment with python 3.7.5, jupyterlab 1.2.3, and altair 3.3.0 on MacOS 10.15.1. My two browsers are Safari 13.0.3 and Firefox 70.0.1. I'll post screenshots separately to clarify.

**Comment by parodayco** [comment]
<img width="478" alt="image" src="https://user-images.githubusercontent.com/42258137/70252938-3e674800-1750-11ea-986e-495da05c93e7.png">
how it appears in Jupyterlab on Firefox

**Comment by parodayco** [comment]
![image](https://user-images.githubusercontent.com/42258137/70252998-59d25300-1750-11ea-98ec-a755561f561c.png)
how it appears in Jupyterlab on Safari

**Comment by parodayco** [comment]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/42258137/70253044-74a4c780-1750-11ea-94e9-0fcf91e9cb07.png">
and correctly rendered by Voila

**Comment by parodayco** [comment]
I switched from /lab to /notebooks and the action menu renders fine like the voila output

**Comment by jakevdp** [comment]
Thanks for the report - I suspect it's some kind of CSS issue. Does it appear the same way in a fresh notebook?

**Comment by parodayco** [comment]
Yes it does even on a single layer chart in a fresh notebook. Let me know what I can do to help troubleshoot the css

**Comment by jakevdp** [comment]
What browser & browser version are you using?

**Comment by parodayco** [comment]
Safari 13.0.3 and Firefox 70.0.1

**Comment by jakevdp** [comment]
I tried in Chrome 78 and Safari 12, and was unable to reproduce the issue.

Are you familiar with browser inspection tools? Can you inspect the element and see if there are any CSS properties that are being overridden?

**Comment by parodayco** [comment]
Yes, I found the actions menu element inside a <summary> tag. Jupyterlab reports the `summary` element in a 450 x 450 Flex Container whereas jupyter notebook shows the same element as 28 x 28 box.

**Comment by parodayco** [comment]
This is the Firefox version I shared above

**Comment by jakevdp** [comment]
Where is that flex property coming from? The only properties coming from the Altair display are via the ``.vega-embet summary`` property.

**Comment by jakevdp** [comment]
This might be due to you having some other labextension installed that sets CSS properties on all ``summary`` outputs in the notebook. You can see what you have installed using
```
$ jupyter labextension list
```

**Comment by parodayco** [comment]
Oh, good point! I installed @jupyter-widgets/jupyterlab-manager and @jupyter-voila/jupyterlab-preview. Let me uninstall the widgets manager first and report back

**Comment by parodayco** [comment]
Bingo! That was the culprit.

**Comment by jakevdp** [comment]
Do you know which of the extensions was causing the issue? It would be worth filing a bug there if they're applying over-zealous CSS styles to the notebook.

**Comment by parodayco** [comment]
Before I uninstalled that widget manager, I saw a different box-sizing set in the CSS. The notebook version showed `box-sizing: border-box` whereas the lab version showed `box-sizing: unset`

**Comment by parodayco** [comment]
Oh wait, that style is still in the lab CSS but not affecting the output. I'm looking but not seeing anything else yet

**Comment by parodayco** [comment]
I'll open a ticket on the extension repo if/when I find it. Thanks, Jake! I love Altair and appreciate everything you do.

**Comment by jakevdp** [comment]
By the way, that's a very cool visualization. Are you interested in adding some variation of that to the example gallery?

**Comment by parodayco** [comment]
Oh, thank you! I'd actually love to contribute (minus the employer data). I have a very nice scatterplot that was tricky to build but I really like the result. The width of each bucket is proportional to the total population, so as people moved into the green, it's x-axis expanded as the others shrunk. Since I could only figure out how to calculate the width based on a fixed value, I concatenated three separate charts. 

<img width="658" alt="image" src="https://user-images.githubusercontent.com/42258137/70268946-687c3280-176f-11ea-9026-ad48edca2409.png">
