### ISSUE TITLE
Improving Documentation

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#185]
We need to think about improving documentation. We've gone back and forth on whether to use notebooks only, or to create stand-alone readthedocs-style docs (perhaps with sphinx). Whatever we choose, these are the things I think we need:
- **A complete description of options in the API** with links between descriptions. Most of this can be auto-generated from the vega-lite specification. (update: done! see #193 – the result is [here](http://nbviewer.jupyter.org/github/ellisonbg/altair/blob/master/altair/notebooks/API.ipynb))
- **Examples with live vega-lite visualizations rather than PNG**. Currently, all the notebooks in nbviewer & on github show static PNG renderings of the visualizations. It's a passable solution now, but when we add interaction this fall this approach will no longer be sufficient.
- **Better access to examples**. In particular, auto-examples currently are not rendered unless someone downloads the notebook and runs them. We should rectify this, and also build some sort of thumbnail gallery that links to them (see [Vega-Lite's gallery](http://vega.github.io/vega-lite/examples/), for example).
- **Searchable Documentation.** Currently, our docs are part of the "dark web" – they can be rendered by github or by nbviewer, but google does not index them. We need to somehow get our docs in a static page, whether that's using something like sphinx, or doing a custom solution involving our notebooks.

Lots of work, but I think I'll have some time to invest in this in the next few months. The most important part is probably including live JS in the docs; I think one approach might be to keep docs in notebooks, but create an nbconvert pipeline that will create HTML views with live javascript, and host these on something like readthedocs.

**Comment by kanitw** [comment]
We also discussed a bit earlier if we have a (javascript) function that translate a Vega-Lite spec to a preferred Altair spec.  We can add easily "Altair" tab to all examples in Vega-Lite docs too.  

(Sometimes there are multiple ways to express things in Altair but this function only needs to return a good one.)

The only potential problem would be when a new feature is introduced in VL, but not yet supported in Altair yet, but we can also make sure to mark some examples as "unsupported in Altair yet" as well.

**Comment by jakevdp** [comment]
The Vega-Lite -> Altair functionality exists in Python; it's a little bit involved, but could probably be translated to javascript.

**Comment by kanitw** [comment]
Oh actually, we can also write a node script that run that python function to generate python script from `.vl.json` files. (Probably easier to maintain this way as we don't have to write the same code twice.)
