### ISSUE TITLE
DOC: Add Link to Changes

### ISSUE THREAD

**Issue by chris1610** [altair-viz/altair#1853]
Unless I'm missing it, I don't see where the docs include a link to the release [history](https://github.com/altair-viz/altair/blob/master/CHANGES.md)

I think it would be useful if there were a releases page that highlighted these changes - especially since the pace of the project moves pretty quickly.

**Comment by jakevdp** [comment]
It's all recorded here: https://github.com/altair-viz/altair/blob/master/CHANGES.md

**Comment by chris1610** [comment]
Yes but I don't think it's linked here - https://altair-viz.github.io/

It's mostly a preference but I like being able to see a What's new or Changes section off the main docs.

**Comment by jakevdp** [comment]
Ah, got it. Are you interested in contributing that? :grinning:

**Comment by chris1610** [comment]
Ha. Sure. I'll take a look at it. 

Do you think the preferred approach is to link to the existing CHANGES.md file or create a new CHANGES.rst one that replaces CHANGES.md?

**Comment by jakevdp** [comment]
I'd probably remove the old ``CHANGES.md`` file, and put the content in ``doc/changes.rst`` or something similar.

**Comment by chris1610** [comment]
Ok. I can do that. Happy to!

**Comment by chris1610** [comment]
Do you have a preference on where the notes show up? Should it look like this:
* Getting Started
* Gallery
* User Guide
* Case Studies
* Advanced Usage
* Release Notes

Or should I just include the release notes under the Bug Reports section on the Index.html file.

Personally, I think a Release Notes heading the TOC looks best but want to double check.

**Comment by jakevdp** [comment]
Sure, a heading in the TOC sounds great

**Comment by chris1610** [comment]
I added a pull request. I built the docs locally and it looks good to me. Please let me know if you have any wording changes or other suggestions.

**Comment by jakevdp** [comment]
Thanks!
