### ISSUE TITLE
Move chart saving to an extension

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#1876]
Currently, saving charts to PNG or SVG requires some additional setup in the form of optional dependencies.

I think a clearer model would be to move this functionality to another package, which could then specify (and test) these dependencies itself.

**Comment by chriscrawfordTR** [comment]
I use Databricks Notebooks and installing browsers and web drivers is a lot of overhead to save a chart. Would be great if I could programmatically save them as part of pipeline runs to send out through slack webhooks or imported in dashboards.

**Comment by jakevdp** [comment]
Take a look at https://github.com/altair-viz/altair_saver

You can save charts via a nodejs stack instead of a selenium/headless driver stack.

**Comment by chriscrawfordTR** [comment]
Installing the nodejs stack on a databricks cluster was _not_ easy. But altair_saver worked for me. Thanks!
