### ISSUE TITLE
Leap year - figure

### ISSUE THREAD

**Issue by Amarounek** [altair-viz/altair#1877]
Hello,
...Again! :-)

I am just thinking if it is possible to find better visualization without _white_ the 29th February.

```

bar3 = alt.Chart(RSDF9).mark_bar().encode(
    alt.X('monthdate(DAY):O', title='day', axis=alt.Axis(tickCount=5)),
    alt.Y('year(DAY):O', title='year'),
    alt.Color('CONDITION_RR:N',
              scale=alt.Scale(
              domain=['Dry', 'Wet'],
              range=['#d62728', '#1f77b4'])),
    order=alt.Order("CONDITION_RR", sort="ascending")
)
(bar3).properties(width=600, title="Dry and Wet season (1983 - 2019)").configure_axisX(labelAlign="right", labelAngle=-45, titlePadding=5)

```

Well, I can use DAY variable as simple ordinal, however than I have numbers on my x-axis and I've read that changing ticks marks is not supported in Altair. So some other options? :-)
![image](https://user-images.githubusercontent.com/36733547/70979795-7eb0b980-20b2-11ea-9548-edae6d1be9b5.png)

**Comment by jakevdp** [comment]
You can use the impute transform to fill-in these values; here is an example (since you didn't provide your data I created some:
```python
import altair as alt
import numpy as np
import pandas as pd

alt.data_transformers.disable_max_rows()

np.random.seed(0)
data = pd.DataFrame({
    'date': pd.date_range('1990-01-01', freq='D', periods=10000),
    'value': np.random.randn(10000).cumsum()
})


alt.Chart(data).transform_timeunit(
    day='monthdate(date)',
    year='year(date)'
).transform_impute(
    'value', key='day', groupby=['year'], method='mean', frame=[-1, 1]
).mark_rect().encode(
    x='monthdate(day):O',
    y='year(year):O',
    color='value:Q',
).properties(
    width=600,
    height=400
)
```
![visualization (76)](https://user-images.githubusercontent.com/781659/71006951-07bbf680-209b-11ea-93c7-e68551f3da89.png)

**Comment by Amarounek** [comment]
Thanks a lot!. Sorry, next time I will use some random example too!
