### ISSUE TITLE
Weird label alignment in stripplot 

### ISSUE THREAD

**Issue by morberg** [altair-viz/altair#1878]
I want a stripplot with the x-axis and y-axis swapped compared to the example in the documentation. When doing this, the alignment of the y-axis labels becomes a bit strange. I did not see this behaviour in Altair 3.

```python
# Based on https://altair-viz.github.io/gallery/stripplot.html

import altair as alt
from vega_datasets import data

source = data.movies.url

stripplot =  alt.Chart(source, width=400, height=40).mark_circle(size=8).encode(
    y=alt.Y(
        'jitter:Q',
        title=None,
        axis=alt.Axis(values=[0], ticks=True, grid=False, labels=False),
        scale=alt.Scale(),
    ),
    x=alt.X('IMDB_Rating:Q'),
    color=alt.Color('Major_Genre:N', legend=None),
    row=alt.Row(
        'Major_Genre:N',
        header=alt.Header(
            labelAngle=0,
            titleOrient='top',
            labelOrient='left',
            labelAlign='right',
        ),
    ),
).transform_calculate(
    # Generate Gaussian jitter with a Box-Muller transform
    jitter='sqrt(-2*log(random()))*cos(2*PI*random())'
).configure_facet(
    spacing=0
).configure_view(
    stroke=None
)

stripplot
```
![visualization](https://user-images.githubusercontent.com/956034/70982964-3eecd080-20b8-11ea-95dc-465780676328.png)

**Comment by jakevdp** [comment]
This is due to a bug introduced in the most recent Vega release; see https://github.com/vega/vega/issues/2233 and https://github.com/vega/vega-lite/issues/5547

Once a fix for that is released, we'll update Altair with the fix.

**Comment by morberg** [comment]
Thank you for the links to the core issue.

If anybody else has problems with this you can use `labelAlign='left'` instead of `labelAlign='right'` until it is fixed in Vega.

**Comment by armsp** [comment]
Adding this [SO post](https://stackoverflow.com/questions/61134669/rotated-column-headers-in-altair-have-uneven-offset) too for documentation on a similar issue and helping those who come across this.

**Comment by joelostblom** [comment]
I'm closing this since it is a bug in VL that is tracked in the issues linked above, and there is nothing that can be done from the altair side of things to fix it.
