### ISSUE TITLE
Unable to change y axis based on Zoom in and Zoom out in bar chart

### ISSUE THREAD

**Issue by kk40014** [altair-viz/altair#1880]
Hi, 

I am trying to implement a bar chart with x-axis as distance and y-axis as count of records.
The functionality, I am trying to achieve is, if user zooms out the chart then it should expand the x axis and relative count of records on y-axis. This will result in showing count on y axis more in depth to expanded buckets/bars. 
 And if user zooms in the chart then it should shrink the x-axis the showing number of less bucket and bar should show the count in the updated range of each bucket which will be higher than default.

Below is the code :
```python
import altair as alt
from vega_datasets import data

source = data.flights_5k()
brush = alt.selection_interval(bind='scales', encodings=['x'])

alt.Chart(source).mark_bar().encode(
    y=alt.Y('count(*):Q', scale=alt.Scale(domain=(0, 371))),
    x=alt.X('distance',scale=alt.Scale(domain=(192, 371)))
).properties(
    width=600,
    height=100
).add_selection(brush)
```

The  issue is above code results in shrink and expand of x-axis but doesnot change bucket range and count according to that.
For e.g. : default view of the chart is: 
![visualization (1)](https://user-images.githubusercontent.com/48593557/71040948-b16fa780-20dc-11ea-9bff-eabe01598c29.png)

and when I zoomed in then:
![visualization (2)](https://user-images.githubusercontent.com/48593557/71041006-cea47600-20dc-11ea-8644-bba27317d886.png)

count is still showing with default bars not by merging the buckets. Similar feature is available if x-axis is by date, it zoomed in and merge the bucket into more higher level buckets and in case of zoomed out, it expanded the bucket into date, time and further scales.

**Comment by jakevdp** [comment]
You are not specifying any binning on the x-axis, so the data will not be binned.

If you want the data to be binned, and for these bins to respond to the selection, you'll need to specify this explicitly. An example of adaptive binning with this dataset can be seen here: https://altair-viz.github.io/gallery/histogram_responsive.html#gallery-histogram-responsive

**Comment by jakevdp** [comment]
For example:
```python
alt.Chart(source).mark_bar().encode(
    y=alt.Y('count(*):Q'),
    x=alt.X('distance', bin=alt.Bin(maxbins=30, extent=brush))
).properties(
    width=600,
    height=100
).add_selection(brush)
```

**Comment by kk40014** [comment]
Hi Jake, 

Thank you for providing the code. I did tried to the same but was getting error due to ", extent=brush" . So, I was not sure if my approach is correct. 
Below is the screen shot attached of  the error:
![2019-12-17](https://user-images.githubusercontent.com/48593557/71047853-0964d900-20f2-11ea-9875-e59e6224ec4f.png)

I am running the code in google colab.

**Comment by jakevdp** [comment]
I suspect you are using Altair version 3.3, which doesn't support selection based binning. Update to  Altair 4.0 using ``!pip install -U altair`` and then it should work.

If you're using a colab Python 3 runtime, Altair 4.0 should be installed by default.

**Comment by kk40014** [comment]
Yes, You were right. It is working now.
Thank you for the help and quick responses.

**Comment by doolingdavidrs21** [comment]
I have related issue with interactivity of mark_bar charts. scroll zooming effects the x-axis as expected, but i am unable to pan up and down on the y-axis, like can be done with mark_point. Here is code that results in everything i need modulo that y-axis interactivity.  Are bar charts just not able to have the same two axis interactive that the scatter plots enable?

```
huh = alt.Chart(what.head(100)).mark_bar().encode(
    alt.X('tenth_percentile:Q',scale=alt.Scale(nice=True,zero=False),
         axis=alt.Axis(title='BT strength')),
    alt.X2('ninetieth_percentile:Q'),
    alt.Y('rank:N'),
    tooltip=['Line_ID','rank','tenth_percentile','mean','ninetieth_percentile']
).interactive() + alt.Chart(what.head(100)).mark_circle(color='red').encode(
    alt.X('mean:Q'),
    alt.Y('rank:N')
).interactive()

huh.properties(
    width=500,
    height=400,
    title='Bradley-Terry "strength" ranking with estimated uncertainty'
)
```

**Comment by mattijn** [comment]
This works for zooming on y-axis

```python
import altair as alt
from vega_datasets import data

source = data.flights_5k()#.url
brush = alt.selection_interval(
    bind='scales', 
    encodings=['y']  # <-- this is important
)

alt.Chart(source).mark_bar().encode(
    x=alt.X('count(*):Q'),
    y=alt.Y('distance:Q').bin(maxbins=30, extent=brush)
).add_params(brush)
```
