### ISSUE TITLE
method to retrieve MultiSelection data

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#1881]
I have been playing with:
https://altair-viz.github.io/gallery/select_detail.html
but using multiselect as shown in here:
https://altair-viz.github.io/user_guide/generated/core/altair.MultiSelection.html

_Is there a way to save the data for the ones you have clicked and output it to a variable in python?_

usecase - I do a lot of mapping with altair and geopandas - I am having success in using multiselect to select census blocks - but now want to save that group to a variable for further analysis.

**Comment by jakevdp** [comment]
No, there is currently no way to save data from a selection within Python.

**Comment by afonit** [comment]
Thanks jake - will close.

**Comment by jakevdp** [comment]
See https://github.com/altair-viz/altair/issues/1749 for details

**Comment by afonit** [comment]
Adding this here in case this workaround is useful to anyone else.
I for the second chart that shows what is selected - I just created a simple chart where the y axis is the value that I want to know.  

Then I save the chart, with selections in it, to svg.
I then parse that file with xml.etree.ElementTree to extract the text from it and I get the list of values I need from the selection.

Not ideal - but it does get me what I need in this moment.
