### ISSUE TITLE
Drawing mark_rect with numeric values in the colored box

### ISSUE THREAD

**Issue by amosbird** [altair-viz/altair#1882]
Hi, is it possible to use altair to draw graph like this?

![image](https://user-images.githubusercontent.com/5085485/71240448-1c6ee780-2344-11ea-8cfa-440863df651c.png)

**Comment by jakevdp** [comment]
Yes, this is possible. See for example https://altair-viz.github.io/gallery/layered_heatmap_text.html

**Comment by amosbird** [comment]
Great!
