### ISSUE TITLE
Delta indicator on line and bar plots

### ISSUE THREAD

**Issue by amosbird** [altair-viz/altair#1883]
![image](https://user-images.githubusercontent.com/5085485/71283486-50292c00-239b-11ea-8990-a08278768dce.png)

Is there a way to indicate value differences on a line or bar plot?

**Comment by jakevdp** [comment]
By "indicate", do you mean "draw an arrow with associated text"?

**Comment by amosbird** [comment]
Yes. But that's just one simple indicator. There are also other fancy ones such as drawing a curly brace with Delta value text

**Comment by jakevdp** [comment]
Altair has no built-in arrow or curly brace marks. You may be able to use rule marks for the kind of indicators you have in mind.
