### ISSUE TITLE
can selection + bind-to-legend have multiple channels?

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#1890]
The [interactive legend example](https://altair-viz.github.io/gallery/interactive_legend.html
) indicates a binding to the color channel of the legend. How can we make multiple channels in the legend (color, shape, size, etc.) interactive in the same way (click, shift-click)? e.g.:

```
import altair as alt
from vega_datasets import data

source = data.iris()

selection = alt.selection_multi(fields=['species', 'petalWidth'], bind='legend')

alt.Chart(source).mark_circle().encode(
    alt.X('sepalLength', scale=alt.Scale(zero=False)),
    alt.Y('sepalWidth', scale=alt.Scale(zero=False, padding=1)),
    color='species',
    size='petalWidth',
    opacity=alt.condition(selection, alt.value(1), alt.value(0.2))
).add_selection(
    selection
)
```

**Comment by jakevdp** [comment]
I think the best way to do this is probably to have multiple selections, each bound to its respective legend. For example:
```python
import altair as alt
from vega_datasets import data

source = data.iris()

color_sel = alt.selection_multi(fields=['species'], bind='legend')
size_sel = alt.selection_multi(fields=['petalWidth'], bind='legend')

alt.Chart(source).mark_circle().encode(
    alt.X('sepalLength', scale=alt.Scale(zero=False)),
    alt.Y('sepalWidth', scale=alt.Scale(zero=False, padding=1)),
    color='species',
    size='petalWidth',
    opacity=alt.condition(color_sel & size_sel, alt.value(1), alt.value(0.2))
).add_selection(
    color_sel,
    size_sel
)
```
(beware that with this approach you'll probably run into a known bug with combining selections: https://github.com/altair-viz/altair/issues/1759 & https://github.com/vega/vega-lite/issues/5553)

**Comment by jowens** [comment]
Thank you, this works nicely, though I have to make the vega-lite fix noted at the end here (https://github.com/vega/vega-lite/issues/5710) and like you say, the selections actually don't work yet.
