### ISSUE TITLE
Question: What kind of Altair user-input should be used to show toggled values / how do we select "all values"?

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#1891]
I'd like to add a user input to a chart (e.g., https://altair-viz.github.io/gallery/multiple_interactions.html). I have data that has an `undirected` field that is either `true` or `false`. I'd like to be able to show three things: `true`, `false`, and `either true or false`. A checkbox thus doesn't seem like the right answer because it has only two states. Doing it in a dropdown seems rather weird. Radio buttons seem right out.  could see having two checkboxes, one for `undirected` and one for `directed`. First question: From a UI perspective, what is the right way to do this?

Second question: For things with multiple selections, how can we support an `all` selector? A pulldown makes sense to show multiple selections, but I don't see (by default) how to make it work with "select everything". Pair it with a checkbox that enables the pulldown? (An example of this would be helpful.)

Third question: If I do use a checkbox, how can I make its default checked rather than unchecked?

**Comment by jakevdp** [comment]
You can use ``alt.selection_multi(empty='all')`` or ``alt.selection(empty='none')`` to control what the empty selection means.

To change the default value of a selection, use ``alt.selection_multi(default={'field': True})`` where ``'field'`` is the field name.

**Comment by jowens** [comment]
@jakevdp That example appears to use `init` not `default` (consistent with https://altair-viz.github.io/user_guide/generated/api/altair.selection_multi.html#altair.selection_multi); perhaps edit your above answer if I'm not mistaken here?

Would you mind opining on my question 1 above? How would you suggest I express this within Altair selections?

**Comment by jakevdp** [comment]
> That example appears to use init not default

Sorry, my mistake. Edited the answer.

> Would you mind opining on my question 1 above?

I'm not entirely clear what the question is. Perhaps a code example would help?

**Comment by jowens** [comment]
I just want a suggestion on the best way to express "show all the data points where `undirected == True`, `undirected == False`, and `undirected == True or False`. Two check boxes, defaulting to true? A pull-down? This is a UI question.

**Comment by jakevdp** [comment]
Maybe an interactive legend? Something like this:
```python
import altair as alt
import numpy as np
import pandas as pd

df = pd.DataFrame({
    'x': np.random.randn(10),
    'y': np.random.randn(10),
    'undirected': np.random.choice(['true', 'false'], 10)
})

selection = alt.selection_multi(fields=['undirected'], bind='legend')

alt.Chart(df).mark_circle().encode(
    x='x',
    y='y',
    color=alt.condition(selection, 'undirected', alt.value('lightgray'))
).add_selection(
    selection
)
```

**Comment by jowens** [comment]
Totally makes sense, but what if I already have `color` and `shape` attributes? I'd be happy to have an interactive legend with a toggle in the legend, that makes lots of sense.

Context: I have tons of variables. I'm currently showing two binary variables as `row` and `column` but if I can use some sort of toggle to select the row/column items, that allows me to have a simpler plot overall (interactive datavis is allowing me to make things simpler).

[gunrock_sssp_bc_1_0_pr.pdf](https://github.com/altair-viz/altair/files/4009117/gunrock_sssp_bc_1_0_pr.pdf)

**Comment by jakevdp** [comment]
So one thing that comes to mind is to use a second chart as a legend. So, say you have data that looks like this, and you're encoding two binary variables by row and column:
```python
import altair as alt
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'x': np.arange(400) % 100,
    'y': np.random.randn(400).cumsum(),
    'A': 200 * [0] + 200 * [1],
    'B': 2 * (100 * [0] + 100 * [1]),
})

alt.Chart(df).mark_point().encode(
    x='x',
    y='y',
    row='A', 
    column='B',
)
```
![visualization (86)](https://user-images.githubusercontent.com/781659/71572211-e42d7e80-2a92-11ea-95e7-bf93e48fb813.png)

You could put all on a single axis, and use a selection based on a concatenated 2D chart to let the user choose which combination to show:
```python
selection = alt.selection_multi(fields=['A', 'B'])

chart = alt.Chart(df).mark_line(point=True).encode(
    x='x:Q',
    y='y:Q',
    detail=['A:O', 'B:O']
).transform_filter(
    selection
)

key = alt.Chart(df).mark_square(size=300).encode(
    x='A:O',
    y='B:O',
    detail='count()',
    color=alt.condition(selection, alt.value('steelblue'), alt.value('lightgray'))
).add_selection(
    selection
)

chart | key
```
![visualization (88)](https://user-images.githubusercontent.com/781659/71572279-1e971b80-2a93-11ea-8754-663afe0dbda5.png)

**Comment by jowens** [comment]
This is pretty amazing. I will give it a whirl. I'll be interested to see how it interacts with also having a legend with selectability (and of course also with how it interacts with https://github.com/altair-viz/altair/issues/1759). Thank you for this thoughtful advice. Selection objects seem to be very powerful and I will endeavor to wrap my mind around 'em!
