### ISSUE TITLE
Manually setting the Y axis range for time (00:00 to 24:00)

### ISSUE THREAD

**Issue by myroslavarm** [altair-viz/altair#1892]
Hi

I have an interactive slider chart and in my Y axis I'm displaying hours of day (in regular datetime format in the dataset), and when using the slider and therefore changing days I'm looking at, my Y axis keeps "jumping" because for some of the data sometimes is missing. I've been trying to scale the axis manually and set the time range in the domain, but haven't been successful (googling brought me to some similar cases but nothing that worked).

Based on slider position I might get:
![image](https://user-images.githubusercontent.com/24677542/71608872-ebd14e00-2b8c-11ea-9afb-2bda4101b24d.png)
And then:
![image](https://user-images.githubusercontent.com/24677542/71608881-fdb2f100-2b8c-11ea-8fd8-6c433749fbba.png)

Code for the axis is
`y = alt.Y('Time:T', timeUnit = 'hours', title = "Time of day", scale=alt.Scale(padding=20))`.

Any way I can set the axis to display the full time range, independent of whether there's data for that hour or not? Thanks!

P.S. visualising plane crash data :)

**Comment by jakevdp** [comment]
It's a little unintuitive, but internally Vega-Lite finds times by translating all dates to a single reference day, namely 2012-01-01. So you can set the time domain this way:
```python
import pandas as pd
import numpy as np
import altair as alt

data = pd.DataFrame({
    'time': pd.date_range('2019-12-30', freq='T', periods=600),
    'value': np.random.randn(600).cumsum()
})

alt.Chart(data).mark_line().encode(
    x=alt.X('hoursminutes(time):T',
        scale=alt.Scale(domain=['2012-01-01T00:00:00', '2012-01-02T00:00:00'])
    ),
    y='value:Q'
)
```
![visualization (89)](https://user-images.githubusercontent.com/781659/71609245-d54ed680-2b3b-11ea-96ac-2d0752893bb6.png)

**Comment by myroslavarm** [comment]
@jakevdp wow, would never have thought... Thanks so much!

**Comment by benjcabalona1029** [comment]
@myroslavarm can i have a look at your code for the above charts? Thanks

**Comment by myroslavarm** [comment]
Hi @benjcabalona1029 I toggled with it later but basically for the font/background you have:
```
.properties(width = 400, height = 250, background = '#F0F1F1', padding = 30, title = alt.TitleParams(text = 'Times of day in each day of the week with most fatalities',
                    font = 'Inconsolata', fontSize = 20, color = '#3E454F')).add_selection(select_year).transform_filter(select_year)
```
and for the time, I transformed it to the regular datetime format to begin with, and then in the visualisation itself just did what Jake wrote. For converting just google the use of `pd.to_datetime()`.
