### ISSUE TITLE
selections with variable names with periods in them are causing JavaScript errors

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#1896]
Sorry to be difficult. I have a column with a `.` in the name (`gpuinfo.name`). I'm using it in a selector. It generates the following vega-lite:

```json
selector003": {"type": "multi", "fields": ["gpuinfo.name"], "bind": "legend"}}
```

but then the resulting JavaScript error is

```
Uncaught (in promise) Error: Unrecognized signal name: "selector003_gpuinfo"
    at i (vega@5:1)
    at MO.DO.getSignal (vega@5:1)
    at vega@5:1
    at Array.forEach (<anonymous>)
    at zB (vega@5:1)
    at yT (vega@5:1)
    at vega@5:1
    at Array.forEach (<anonymous>)
    at vega@5:1
    at vega@5:1
```

There is no apparent instance of `selector003_gpuinfo` in the resulting JSON.

I know `.` in field names is undesirable. Sorry. Here's the rough Altair source for that:

```python
        shape = "gpuinfo.name"
        chart = chart.encode(
            shape=alt.Shape(shape,
                            legend=alt.Legend(title=shape,
                            ))
        selection = alt.selection_multi(fields=[shape], bind='legend')
        chart = chart.add_selection(selection)
```

**Comment by jowens** [comment]
If I pass it in as `[gpuinfo.name]' instead, I get in `chart.save`:

```
ValueError: [gpuinfo.name] encoding field is specified without a type; the type cannot be inferred because it does not match any column in the data.
```

**Comment by jakevdp** [comment]
This is expected. There are several characters that have special meanings within field names (see https://altair-viz.github.io/user_guide/troubleshooting.html#encodings-with-special-characters), and they must be escaped if not being used to refer to nested data types.

The best option is to avoid ``.``, ``[`` and ``]`` in column names.

**Comment by jowens** [comment]
Yeah, it's just ubiquitous in Pandas to have `.` in field names.

The concern here is that it's been working just fine as field names until I used a selection, but I was calling the field `[gpuinfo.name]:N`. I'd just like a little guidance in that doc section on "if you're really stuck with weird characters in your field names, here's what you do", and maybe the answer is `gpuinfo\.name` everywhere, and I can do that (and will try it).

**Comment by jowens** [comment]
`ValueError: gpuinfo\.name encoding field is specified without a type; the type cannot be inferred because it does not match any column in the data.`

**Comment by jowens** [comment]
Anyway, given that I've asked a dozen questions about `.` separators over the past couple of years, I think the sensible thing to do is change my Pandas `json_normalize` call to not use the default `.` separator but instead use `_`. Which I will do. Thanks for putting up with me.

**Comment by jakevdp** [comment]
>  I'd just like a little guidance in that doc section

I added the section to display troubleshooting to try and do exactly that. If you think it could be worded more effectively or located in a different place, please let me know (or better yet, open a pull request updating the docs)

> ValueError: gpuinfo\.name encoding field is specified without a type; the type cannot be inferred because it does not match any column in the data.

you don't have a column named ``gpuinfo\.name`` in your data. You should specify the type explicitly (I'd recommend that in general - type inference only works correctly in very special situations).

**Comment by jowens** [comment]
Well, the guidance that would be useful is "here is the most robust way to deal with this problem". I'm not entirely sure why my `\.` did not work here so I am not able to make a suggestion for what goes in the docs, and I have also used in the past (at your suggestion) bracketing the field name (which is primarily how I dealt with this particular field name in the past, up until I started using selections). I am sure that my surface knowledge of what is going on is frustrating you and your time is better used elsewhere so I suggest you close the issue and let me do the `_` separator and be done with it.

I was always able to leave the type attached to the variable before today :) and removed it at your suggestion for selections but now will put it back in for this.

**Comment by jakevdp** [comment]
Ah, I see... your column is not actually named ``[gpuinfo.name]``, it is named ``gpuinfo.name``? That wasn't clear to me.

I think the core issue here is that the way to refer to columns within encoding shorthands is slightly different than the way to refer to columns within references to field names within selections and transforms... partly that is the fault of Altair trying to give users convenient shorthands for specifying encodings, when those shortcuts do not generalize to other places where fields are used. The right solution, I think, would be to remove those shorthands and have users use the Vega-Lite grammar directly... but I think the ship has sailed on that one.

Regarding attaching the type to the field name: my suggestion would not be to store variable names a strings with types attached; my suggestion would be to specify the type explicitly in the encoding; e.g.

column = "name"

alt.Chart(data).mark_point().encode(
  alt.X('name', type='nominal')
)
```
or perhaps
```
x=f'{column}:N'
```
for short.

You can use ``\.`` everywhere in your spec, but be aware of the difference in how Python treats backslashes in raw strings (``r"\."``) and regular strings (``"\\."``). It gets confusion, which is why my primary recommendation would be to avoid special characters in column names entirely where possible.

I hope that all helps! And please do let me know if you have specific ideas about how documentation could be improved.
