### ISSUE TITLE
How to hide Axis Labels?

### ISSUE THREAD

**Issue by odoublewen** [altair-viz/altair#1899]
I've searched through the docs and online forums, but can't accomplish what I thought should be a simple chart customization:  I would like to remove all **labels** from the axes -- but I still want the axis title and ticks to be drawn (so this is different from #1342).

I'm very sure it's possible and I'm pretty sure it's in your docs (which are very good).  But could this be a worked example on the [customization examples](https://altair-viz.github.io/user_guide/customization.html#adjusting-axis-labels) page? 

Many thanks!

**Comment by jakevdp** [comment]
You can hide the axis labels by setting ``labels=False`` within the axis. For example:
```python
import altair as alt
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x=alt.X('Horsepower', axis=alt.Axis(labels=False)),
    y=alt.Y('Miles_per_Gallon', axis=alt.Axis(labels=False)),
    color='Origin',
).interactive()
```
![visualization (37)](https://user-images.githubusercontent.com/781659/71837446-4b3acc80-306b-11ea-9284-abf462d47e6e.png)

**Comment by jakevdp** [comment]
It would be worth adding an example like this to the docs.

**Comment by odoublewen** [comment]
:Doh:    Right in front of my eyes, sorry to have bothered you.

I'd be happy to make a PR to put this example to your docs, but maybe you've already done it.

Thank you.

**Comment by jakevdp** [comment]
> I'd be happy to make a PR to put this example to your docs

That would be great! Please let me know if you need any help getting started.

**Comment by IndianBOYinDetroit** [comment]
@jakevdp how can I hide alternate label  ?For example if my list has following values(0,5,10,15,20,25,30), on x0axis I want to show 0,  blank, 10, blank, 20, blank 30....

**Comment by jakevdp** [comment]
Set `alt.Axis(tickMinStep=10)`

**Comment by jayanti-disys** [comment]
> You can hide the axis labels by setting `labels=False` within the axis. For example:
> 
> ```python
> import altair as alt
> from vega_datasets import data
> cars = data.cars()
> 
> alt.Chart(cars).mark_point().encode(
>     x=alt.X('Horsepower', axis=alt.Axis(labels=False)),
>     y=alt.Y('Miles_per_Gallon', axis=alt.Axis(labels=False)),
>     color='Origin',
> ).interactive()
> ```
> 
> ![visualization (37)](https://user-images.githubusercontent.com/781659/71837446-4b3acc80-306b-11ea-9284-abf462d47e6e.png)

note useful since in the figure there are still labels :(

**Comment by kgoodrick-uu** [comment]
@jayanti-disys The original post asked to keep axis titles, if you want to remove those too you can set `title=""` in the `X` and `Y` constructors.

````python
import altair as alt
from vega_datasets import data
cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x=alt.X('Horsepower', axis=alt.Axis(labels=False), title=''),
    y=alt.Y('Miles_per_Gallon', axis=alt.Axis(labels=False), title=''),
    color='Origin',
).interactive()
````

**Comment by jayanti-disys** [comment]
> kgoodrick
that did not help. Here is my error message

===========
SchemaValidationError: Invalid specification altair.vegalite.v4.schema.core.FacetedEncoding, validating 'additionalProperties' Additional properties are not allowed ('axis', 'title' were unexpected)
==========
Here is code:
==========
l         
line =  alt.Chart(dF_predict).mark_line().encode(x=date_option,y='Forecast',color=alt.value("#922B21"),axis=alt.Axis(labels=False), title='')

===================

**Comment by kgoodrick-uu** [comment]
Hi @jayanti-disys, please review the code in my comment, `title` is an argument for the encoding object constructor e.g. `alt.X` not the encode function.
