### ISSUE TITLE
Error when trying to use the 'data_server' data transformer on altair 4.0

### ISSUE THREAD

**Issue by subhashbylaiah** [altair-viz/altair#1902]
When I try to use the data_server by enabling with altair.data_transformers.enable('data_server'), I get this error: NoSuchEntryPoint: No 'data_server' entry point found in group 'altair.vegalite.v4.data_transformer'. 

I am on altair version 4.0.0 and altair_data_server version: 0.4.1

**Comment by jakevdp** [comment]
How did you install altair_data_server?

If you run ``from altair_data_server import data_server`` do you see any errors?

**Comment by subhashbylaiah** [comment]
Apparently this turned out to be an installation issue at my end. Thanks for checking on this Jake. I am closing the issue.

**Comment by jakevdp** [comment]
Great!

**Comment by perch97** [comment]
> How did you install altair_data_server?
> 
> If you run `from altair_data_server import data_server` do you see any errors?

it works for me!
