### ISSUE TITLE
Provide example for Django integration

### ISSUE THREAD

**Issue by odoublewen** [altair-viz/altair#1903]
I'm trying to figure out the best practices for using Altair inside of a Django application.  Since a lot of the Altair documentation is focused on notebooks, I'm hoping to spur a little conversation with the experts to understand what is the best way to serve up (potentially big dataset) Altair plots within a Django framework.  

What I'm currently doing is writing a view function for each plot, something like:

```python
def lengths_barplot(request, analysis_id):
    data = Lengths.objects.filter(analysis_id=analysis_id)
    df = pd.DataFrame.from_records(data.values())
    chart = alt.Chart(df).mark_bar().encode(
        x=alt.X('length'),
        y=alt.Y('count'),
        color='type',
        facet=alt.Facet('type', columns=1),
    ).properties(
        width=800
    )
    return HttpResponse(chart.to_json(), content_type='application/json')
```

Then, in the Django HTML template for corresponding page, I have:

```html
    <script src="https://cdn.jsdelivr.net/npm/vega@5.9.0"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-lite@4.0.2"></script>
    <script src="https://cdn.jsdelivr.net/npm/vega-embed@6.2.1"></script>
    <script type="application/javascript">
        vegaEmbed('#charts-lengths', '{% url 'charts-lengths' analysis.pk %}');
    </script>

  <div id="charts-lengths"></div>
```

It's basically working, but I had somehow (naively) assumed that serving up the charts separate from the Django view would somehow get me around the `MaxRowsError`, but it doesn't.   So I can get around this by calling `alt.data_transformers.disable_max_rows()`.

Also, I was also naively assuming the page load performance would not be impacted by large plots, thinking that the plots would render AFTER the page load was complete.  But I was wrong here too.

Do you have recommendations and if so, could something be added to the [FAQ](https://altair-viz.github.io/user_guide/faq.html#maxrowserror-how-can-i-plot-large-datasets)?  

Should I experiment with using [altair_data_server](https://github.com/altair-viz/altair_data_server) somehow on top (or along side) the Django server?  

Incidentally, I recently came across a nice presentation that @mrchrisadams made recently.  I am basically using the same approach he describes [around 18:20 in this video](https://www.youtube.com/watch?v=x6qxpm_SSZ8).  Not sure if this mention will ping him, but I'd love to know if Chris has any specific recommendations on this topic.

(I'd be happy to compile any recommendations into a new section in the docs.)

**Comment by jakevdp** [comment]
Good questions. A few thoughts:

> I had somehow (naively) assumed that serving up the charts separate from the Django view would somehow get me around the MaxRowsError, but it doesn't. 

There's no "getting around" the MaxRowsError, unless you explicitly disable it. I suspect it's relevant for your Django application as well: if you embed a 100MB chart spec in a webpage, it won't be a great experience for folks viewing that page.

> Also, I was also naively assuming the page load performance would not be impacted by large plots, thinking that the plots would render AFTER the page load was complete

Page load will definitely be affected by large plots, or by many small plots (they're part of the DOM, after all). In Altair's docs we use a callback to render the charts only after everything is loaded. Here how it's done: https://github.com/altair-viz/altair/blob/a497cfbc92f8dc6912b9b2701d141527472f1e59/altair/sphinxext/altairplot.py#L78-L94

> Should I experiment with using altair_data_server somehow on top (or along side) the Django server?

If you're using Django, I don't think altair_data_server is relevant: it spins up a localhost server in a background thread, which won't be useful to people viewing your webpage unless they're viewing it on localhost. Instead you can create a handler in your Django app to serve the data, maybe taking cue from ``altair_data_server`` to define a transformer that will extract the data to pass to your app automatically.

Hope that helps get you started!

**Comment by odoublewen** [comment]
Thank you -- Your example showed me a very simple improvement:  wrapping the `vegaEmbed` call in the DOMContentLoaded event listener.  That at least allows the page to load first and permits the user to continue navigating or reading, even if the plot(s) take a moment to load.

If I come up with something radically better, I will share it here.  But I think this solves my immediate issues.  Thanks again!
