### ISSUE TITLE
Any ways to disable interpolation for irregular dates?

### ISSUE THREAD

**Issue by HereticSK** [altair-viz/altair#1904]
## Problem
When plotting times series data with irregular dates, dates would be interpolated in to complete calendar dates and the corresponding values are also interpolated. This interpolation may introduce unexpected "disturbance" into the resulting plot. 

```Python
import pandas as pd
import altair as alt

calendar_dates = pd.date_range('20190101', '20190531')
holidays = pd.date_range('20190301', '20190331')
x = [d for d in calendar_dates if d not in holidays]
df = pd.DataFrame({'x': x, 'y': list(range(len(x)))})

alt.Chart(df).mark_line().encode(x='x', y='y').interactive()
```
![image](https://user-images.githubusercontent.com/17619612/71966395-6d377900-323c-11ea-83a9-f3e072c26812.png)

In the above example, data can only be observed on non-holidays and all the points should lie on  a continuous straight line. There occurs a "twist" in the middle only because of interpolation for holidays, which  is not interested in the analysis. I believe this is a common problem in visualizing time series.

## Similar Issues I have researched
Issue #1768 mentioned `alt.ImputeParams`. But the strange twist still exists since the dates are still interpolated

Issue #1005 mentioned custom domain on datetime axis. This is a promising solution. But for this to work, `altair` needs to accept a list of fixed dates as domain. It seems that this has not been supported yet, according to the documentation of the `domain` parameter
> For temporal fields, domain can be a two-element array minimum and maximum values, in the form of either timestamps or the DateTime definition objects.

Actually, I encounter the same problem in `matplotlib` and `bqplot`. I managed to come up with a solution, but they are quite awkward and hacky.
In `matplotlib`, I use integer as x-axis, and map the integer tick label to a date. This fakes a date axis.
In `bqplot`, I use double axis, one invisible axis of integer scale, the other visible axis of date scale.

So I want to discuss, is there a cleaner way to disable this interpolation behavior for irregular time series? And I wonder, given that this interpolation behavior is default for both `bqplot` and `altair`, does it come from the underlying javascript library? Can we handle this on the python side? I am happy to do a PR if needed.

**Comment by jakevdp** [comment]
You can do this by using an ordinal encoding along with an appropriate time unit:
```python
alt.Chart(df).mark_line().encode(
    x='yearmonthdate(x):O',
    y='y'
).properties(
    width=alt.Step(4)
)
```
![visualization (92)](https://user-images.githubusercontent.com/781659/71985206-f029e680-31de-11ea-842b-f7e9f08acfef.png)

**Comment by HereticSK** [comment]
This can be a handy way to tackle the problem. Thanks!

But it is still kind of hacky. As the data set gets large, the resulting plot gets too wide. Moreover, I think treating irregular timestamps as ordinal may not reflect the nature of the data set. Irregular timestamps can be "continuous" in certain domains, like trading calendar of a stock exchange, business days. 

It would be useful if we could treat these irregular timestamps as a custom calendar. Maybe interaction can be more easily supported in this way. What do you think?

**Comment by jakevdp** [comment]
I don't think it's correct to characterize this as "hacky". Encoding types and timeunit binnings are fundamental components of the Altair API. 

If you think there should be options for treating discontinuous date scales as if they're continuous, you could request that feature in the Vega-Lite forums.

**Comment by HereticSK** [comment]
Thanks for your explaination.

To clarify, By "hacky" I mean "having to treat continuous type as ordinal". I totally agree that encoding types is the fundamental idea of Alatir.

I've had no clue about how Altair implements date scales. Vega-Lite seems to be the right place to look at. Thanks for pointing that out. :)

**Comment by xicocaio** [comment]
Hello,

@jakevdp I have the same issue reported here.

I am dealing with hourly stock data. Thus, for some hours of weekdays and weekends, there are missing data points. In this case, when using a `date` encoding for missing dates, the Interpolation kicks in, and we observe these straight lines in the graph.

![visualization](https://user-images.githubusercontent.com/2607513/120678555-975f8b80-c46e-11eb-90e8-a3b4f0375683.png)

Then, I tried using interpolation as your [answer on StackOverflow suggested](https://stackoverflow.com/questions/60877845/altair-values-are-still-imputed-even-though-they-should-be-deactivated). But, that did not work for me.

Next, I followed your instructions about using ordinal encoding to get the following chart.

> You can do this by using an ordinal encoding along with an appropriate time unit:
> 
> ```python
> alt.Chart(df).mark_line().encode(
>     x='yearmonthdate(x):O',
>     y='y'
> ).properties(
>     width=alt.Step(4)
> )
> ```

![visualization (2)](https://user-images.githubusercontent.com/2607513/120678676-bbbb6800-c46e-11eb-9a60-618ceedff36b.png)

However, as you said, I lose the interactive ability, which is important for me.

Could you please suggest any workaround to get the second image results while still keeping the interactive option?

**Comment by jakevdp** [comment]
If you set missing data to NaN, you can use a continuous scale and there will be breaks rather than linear interpolation.

**Comment by xicocaio** [comment]
> If you set missing data to NaN, you can use a continuous scale, and there will be breaks rather than linear interpolation.

So are you saying I should do something like this?

```
dates = pd.Index([pd.Timestamp('2012-05-01 00:00:00'), 
                  pd.Timestamp('2012-05-01 03:00:00'), 
                  pd.Timestamp('2012-05-01 05:00:00')])
s = pd.Series([1, 2, 3], dates)

print(s.asfreq('H'))
2012-05-01 00:00:00   1.0
2012-05-01 01:00:00   NaN
2012-05-01 02:00:00   NaN
2012-05-01 03:00:00   2.0
2012-05-01 04:00:00   NaN
2012-05-01 05:00:00   3.0
```

I understand the concept, but isn't there another way to make the API not try to fill in these "missing values" (because they are not missing values, the stock market is not open 24/7) on the x-axis, and take into account only the ones being passed? Why is the chart trying to fill in the "missing values"?

Does the x-axis support two encondigs such that I can pass continuous integers, but also use the date as a part of the label?

**Comment by jakevdp** [comment]
The chart is not filling-in missing values; the chart is connecting adjacent values with a line, because you used `mark_line()`. The way to tell the renderer not to connect adjacent values with `mark_line()` is to insert NaNs in the spaces where you don't want connections.

Alternatively, you can use something like `mark_point()` which does not attempt to draw lines between adjacent values.

**Comment by jakevdp** [comment]
Maybe I should back up and ask: what do you want your chart to look like? What lines (if any) do you want drawn in the spaces where no data is available?

**Comment by xicocaio** [comment]
> Maybe I should back up and ask: what do you want your chart to look like? What lines (if any) do you want drawn in the spaces where no data is available?

I want my chart to look like this image below (which I achieved by using your suggestion to adopt an ordinal encoding).

```
alt.Chart(data).mark_line().encode(x=alt.X('yearmonthdatehours(date):O', title='Period'),
                                   y=alt.Y("total_return:Q", stack=None),
                                   color=alt.Color("stg:N", legend=(alt.Legend(title='Strategy', orient='right'))),).properties(width=600,height=300)
```

![visualization (2)](https://user-images.githubusercontent.com/2607513/120714403-87a96c80-c499-11eb-99d2-256fac8cbd95.png)

However, in the x-axis, I have a date value, and by turning it into an ordinal (`x='yearmonthdatehours(date):O'`), i lost the ability to enable `interactive()`, as you said:

> because the x-axis is now categorical rather than continuous, you will not be able to make the scales interactive.

In essence, how do I get the chart in the image I just showed and make it interactive, preferably while keeping the date (`x='yearmonthdatehours(date):T'`) encoding?

**Comment by jakevdp** [comment]
There is no way to have a continuous temporal encoding that leaves out some blocks of time, sorry. Your only option for that is to use an ordinal encoding.
