### ISSUE TITLE
Interval Selection Example Bug

### ISSUE THREAD

**Issue by eitanlees** [altair-viz/altair#1906]
I am having trouble with the the [Interval Selection Example](https://altair-viz.github.io/gallery/interval_selection.html). 
![interval-selection](https://user-images.githubusercontent.com/2041969/72012337-c813a500-3229-11ea-911c-d130c87ce01e.gif)

```python
import altair as alt
from vega_datasets import data

source = data.sp500.url

brush = alt.selection(type='interval', encodings=['x'])

upper = alt.Chart(source).mark_area().encode(
    alt.X('date:T', scale=alt.Scale(domain=brush)),
    y='price:Q'
).properties(
    width=600,
    height=200
)

lower = upper.properties(
    height=60
).add_selection(brush)

upper & lower
```

The example looks correct so I am unsure what is causing this behavior.

**Comment by eitanlees** [comment]
Note the [Overview and Detail](https://vega.github.io/vega-lite/examples/interactive_overview_detail.html) is working from the Vega-Lite examples.

**Comment by eitanlees** [comment]
I figured it out! In the upper chart we bind the domain to the brush and the lower chart is made from a copy of the upper chart with the same binding. 

I will refactor this example and submit a PR.

**Comment by bendoesdata** [comment]
I just encountered this issue myself (locally and on the Altair gallery site). When will this fix be pushed to a recent release?

**Comment by jakevdp** [comment]
This fix has not yet been part of a release. At the next release, the website will be updated.
