### ISSUE TITLE
Composed view add extra values to color legends (even when set to legend=None)

### ISSUE THREAD

**Issue by pabloinsente** [altair-viz/altair#1908]
I'm trying to generate a composed view, where the first chart has legends, and the second one does not. When I concatenate the charts, the color values of chart 2 are added the color legend of chart 1:

```Python
scatter = alt.Chart(data_sample).mark_circle().encode(
    alt.X("num_medications:Q"),
    alt.Y("num_lab_procedures:Q"),
    color='insulin:N'
)
scatter
```
![visualization (2)](https://user-images.githubusercontent.com/35237403/72083019-c0560e00-32c6-11ea-80cb-e4af1cada124.png)

```Python
bar = alt.Chart(data_sample).mark_bar().encode(
    x='mean(num_medications):Q',
    y='race:O',
    color=alt.Color('race:O', scale=alt.Scale(scheme='dark2'), legend=None),
)
bar
```
![visualization (3)](https://user-images.githubusercontent.com/35237403/72083058-d06ded80-32c6-11ea-961a-6037a51538cf.png)

Now, when I use the ```&``` operator, the "race" values are added to the scatter "insulin" values in the legends.
```Python
scatter & bar
```
![visualization (4)](https://user-images.githubusercontent.com/35237403/72083145-ebd8f880-32c6-11ea-8b39-bc73a054ebb7.png)

Is there a way to restrict the legend values to the firs chart?

**Comment by jakevdp** [comment]
See https://altair-viz.github.io/user_guide/scale_resolve.html

If you use ``(scatter & bar).resolve_scale(color='independent')``, the color scales will not be combined.

**Comment by pabloinsente** [comment]
Awesome, thanks!
