### ISSUE TITLE
"Binding" Options for alt.selection_single() and alt.selection_multi()

### ISSUE THREAD

**Issue by ajennings6767** [altair-viz/altair#1917]
Hi,

This is a question rather than an issue. 

Put simply, are we able to 'bind' the `alt.selection_single()` method to widgets other than the altair options (i.e. `alt.binding_range`)?

I'd like to know if is could substitute a Panel widget for `slider` (`alt.binding_range()`) in the below:
```
import altair as alt
import pandas as pd
import numpy as np

rand = np.random.RandomState(42)

df = pd.DataFrame({
    'xval': range(100),
    'yval': rand.randn(100).cumsum()
})

slider = alt.binding_range(min=0, max=100, step=1, name='cutoff:')
selector = alt.selection_single(name="SelectorName", fields=['cutoff'],
                                bind=slider, init={'cutoff': 50})

alt.Chart(df).mark_point().encode(
    x='xval',
    y='yval',
    color=alt.condition(
        alt.datum.xval < selector.cutoff,
        alt.value('red'), alt.value('blue')
    )
).add_selection(
    selector
)
```

As a related question, is there a "cost" difference between doing a transform filter via the built in altair selectors and recreating the chart altogether and passing a different variable to the transform filter (e.g. via a Panel widget)?

An example on Panel [(medium post)](https://towardsdatascience.com/how-to-build-a-time-series-dashboard-in-python-with-panel-altair-and-a-jupyter-notebook-c0ed40f02289) looks to be rebuilding the chart each time we want to change the date range -- which seems inefficient. 

I'm not sure exactly what is going on under the hood, so I'm curious as to if one approach is materially more efficient than the other (altair selector vs rebuild chart on callback).

```
@pn.depends(ticker.param.value, date_range_slider.param.value)
def get_plot(ticker, date_range):
     # Load and format the data
     df = source # define df
     df[‘date’] = pd.to_datetime(df[‘date’])
     
     # create date filter using values from the range slider
     # store the first and last date range slider value in a var
     start_date = date_range_slider.value[0] 
     end_date = date_range_slider.value[1] 
     
     # create filter mask for the dataframe
     mask = (df[‘date’] > start_date) & (df[‘date’] <= end_date)
     df = df.loc[mask] # filter the dataframe
     
     # create the Altair chart object
     chart = alt.Chart(df).mark_line().encode(
                     x=’date’, 
                     y=‘price’,      
                     tooltip=alt.Tooltip([‘date’,’price’])
                 ).transform_filter(
                     (datum.symbol == ticker) # this ties in the filter 
                )
     return chart
```

Thanks in advance! Altair is my go-to!

**Comment by jakevdp** [comment]
> I'd like to know if is could substitute a Panel widget for slider (alt.binding_range()) in the below:

No - Panel and Vega-Lite are entirely separate javascript stacks, and their widgets are not interchangeable.

> is there a "cost" difference between doing a transform filter via the built in altair selectors and recreating the chart altogether

Yes, the serialization of a new dataset takes non-zero computational time, so in that sense there is a cost to using an external widget to re-generate the chart. Whether that cost is prohibitive to your own use case is probably something you can determine empirically.

**Comment by ajennings6767** [comment]
I figured as much, but I wasn't sure if there was some back channel to sneak other values to `alt.single_selection` with a callback or something. 

Thanks for the quick response! You've got to be the fastest gun in the West ... or at least on GitHub!
