### ISSUE TITLE
Impute transform won't work in boxplot of data with NaNs

### ISSUE THREAD

**Issue by wmayner** [altair-viz/altair#1918]
I'm trying to make boxplots of a dataset that contains NaNs. I was expecting the NaN values to be ignored, but instead they cause their box not to be plotted. After reading around a bit I thought maybe I needed to use the impute transform to explicitly set their value to `None`, but this doesn't seem to work either. Neither does imputing to `0`.

How can I make a boxplot while ignoring NaN values?

**MRE:**
```python
import altair as alt
import pandas as pd
import numpy as np

alt.Chart(
    data=pd.DataFrame({
        'x': ['A', 'A', 'B', 'B'],
        'y': [1, np.nan, 3, 4],
    })
).mark_boxplot(
).encode(
    x='x:N',
    y=alt.Y(
        'y:Q',
        impute=alt.ImputeParams(
            value=None,
            keyvals=[np.nan],
        )
    )
)
```
![Output](https://user-images.githubusercontent.com/1775632/72587265-415e6800-38ba-11ea-939f-49a652ae1e2d.png)

Altair version:
```
altair==4.0.1
```

Thanks!

**Comment by jakevdp** [comment]
I'm confused: what do you expect the imputed value to be when you are using ``None`` for both ``keyvals`` and ``imputeValue``?

**Comment by jakevdp** [comment]
If you leave out the impute transform, NaN values will be ignored when constructing the box. But your example only has one data point remaining for ``x='A'``, and you cannot construct a box plot from a single data point, so no box is shown.

**Comment by jakevdp** [comment]
Here's an example that might clarify this:
```python
import altair as alt
import pandas as pd
import numpy as np

alt.Chart(
    data=pd.DataFrame({
        'x': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'C'],
        'y': [1, np.nan, 3, 4, 5, 6, 7, 8],
    })
).mark_boxplot().encode(
    x='x:N',
    y='y:Q',
)
```
![visualization - 2020-01-17T111657 731](https://user-images.githubusercontent.com/781659/72639641-e446ce80-391a-11ea-8525-2c210cf6e133.png)

The box is drawn for A despite the presence of NaNs, because it has enough values. The box is not drawn for C, but this is not related to NaNs – it is because it only has one value, and relevant statistics like the standard deviation are undefined for a single value.

**Comment by wmayner** [comment]
> I'm confused: what do you expect the imputed value to be when you are using empty values for both `keyvals` and `imputeValue`?

I thought there might be special significance to `None` values as opposed to `np.nan` in the handling of missing data.

> If you leave out the impute transform, NaN values will be ignored when constructing the box. But your example only has one data point remaining for x='A', and you cannot construct a meaningful box plot from a single data point, so no box is shown.

I see—looks like my MRE doesn't actually reproduce my problem! In my actual data, there are enough data for each category, but the box still doesn't appear. I guess it's unrelated to the presence of NaNs, though. I'll keep digging into it.
