### ISSUE TITLE
Subtitle Documentation and styling

### ISSUE THREAD

**Issue by mcnuttandrew** [altair-viz/altair#1919]
At last! There are subtitles in for altair charts([via a vega-lite update](https://github.com/vega/vega-lite/issues/4055))! How splendid! This issue identifies a documentation bug and maybe a styling bug revolving around this newly birthed feature:

- I don't believe that there is any documentation of the mechanism for adding subtitles (or multiline titles) to charts! It's a great feature it should be easy to find!

- The [title configuration](https://altair-viz.github.io/user_guide/configuration.html#title-configuration) section of the documentation appears to suggest that there should be various subtitle styling operators  (subtitleColor, subtitleFont, subtitleFontSize, subtitleFontStyle, subtitleFontWeight, subtitleLineHeight, subtitlePadding specifically), but all of the variations that i've tried on them appear not to work? For instance the following should ostensibly produce a chart with a red subtitle 

```py
import altair as alt
from vega_datasets import data

chart = alt.Chart(data.cars.url).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
).properties(
    title={
      "text": ["First line of title", "Second line of title"], 
      "subtitle": ["Cool first line of subtitle", "Even cooler second line wow dang"]
    }
)

chart.configure_title(
    fontSize=20,
    font='Courier',
    anchor='start',
    color='gray',
   subtitleColor='red'
)

```

Unfortunately it produces a chart with an unstyled subtitle:

<img width="461" alt="Screen Shot 2020-01-17 at 12 40 43 AM" src="https://user-images.githubusercontent.com/6854312/72589864-0ceeaa00-38c2-11ea-8632-66001b7d6867.png">

I totally admit that i might be misreading this, but, if not, it seems like a bug. I'm happy to help contribute documentation once a solution is known

**Comment by jakevdp** [comment]
It looks like a bug that should be reported upstream to Vega-Lite

**Comment by mcnuttandrew** [comment]
Reported to upstream!

**Comment by mcnuttandrew** [comment]
Apparently it is both a documentation bug and a regular bug, after a helpful hint from @domoritz  on the upstream issue, I was able to get the styling applied to the subtitle like so:

```py 
import altair as alt
from vega_datasets import data

chart = alt.Chart(data.cars.url).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
).properties(
    title={
      "text": ["First line of title", "Second line of title"], 
      "subtitle": ["Cool first line of subtitle", "Even cooler second line wow dang"],
      "color": "red",
      "subtitleColor": "green"
    }
)
chart
```

**Comment by palewire** [comment]
@jakevdp, I'm interested in the idea of adding examples to the gallery that tackle basic customizations like adding a subtitle. Would you be open to a new section of the docs that showed how to do something like this? It seems like it would pretty tough for a newbie to figure out.

**Comment by jakevdp** [comment]
Sure, that would be great

**Comment by jakevdp** [comment]
I think a narrative documentation section would be better than more gallery examples. The gallery is already pretty crowded, and it's not always easy to find the relevant chart.

**Comment by joelostblom** [comment]
The provided example is working for me on Altair 4.2.0 so I'm closing this, please re-open if you are still seeing the issue.
