### ISSUE TITLE
public documentation / support for altair sphinx plugin

### ISSUE THREAD

**Issue by lukasheinrich** [altair-viz/altair#1920]
We are developing some infrastructure to visualize particle physics statistical models using Altair

https://nbviewer.jupyter.org/github/scikit-hep/pyhf/blob/add_altair_example/docs/examples/notebooks/altair.ipynb?flush_cache=true

and have integrated this notebook into our docs

https://scikit-hep.org/pyhf/examples/notebooks/altair.html

However on that sphinx page the altair plot doesn't render as nicely as in the altair docs. See this issue:

https://github.com/scikit-hep/pyhf/issues/720

would it be possible to receive some public documentation on how to do this properly?

Thanks!

@kratsg @matthewfeickert

**Comment by jakevdp** [comment]
You can see how Altair's sphinx extension works within altair's docs: https://github.com/altair-viz/altair/blob/master/doc/conf.py#L39-L40

It looks like you're embedding an nbconverted notebook within your sphinx output - I'm not aware of anyone who has gotten Altair working that way.

If you make progress, please consider a PR to Altair's documentation to help future people

**Comment by jakevdp** [comment]
I looked at your code: I think this should work with Altair 4.0's default html renderer, which you have  enabled. But there's some sort of issue with requirejs on your generated side, and the code currently does not catch requirejs errors.

**Comment by kratsg** [comment]
> I looked at your code: I think this should work with Altair 4.0's default html renderer, which you have enabled. But there's some sort of issue with requirejs on your generated side, and the code currently does not catch requirejs errors.

That's fine, but does this require a CDN or should we package it in w/ our code manually? The latter worries me only because it's a dependency that might require a version update in the future.

**Comment by jakevdp** [comment]
Yes, current rendering approaches (including Altair's sphinx plugin) loads javascript from CDN. 

If you want to bundle the libraries with your site build, you can set the URLs via the sphinx configuration: https://github.com/altair-viz/altair/blob/master/altair/sphinxext/altairplot.py#L302-L304

**Comment by kratsg** [comment]
> Yes, current rendering approaches (including Altair's sphinx plugin) loads javascript from CDN.

Any concerns about being able to render the docs offline (e.g. no internet access)? That said, we are using mathjax so... I'm ok with the CDN for now.

**Comment by jakevdp** [comment]
No, I haven't been too concerned about that. Many of the datasets are loaded from external URL as well.

**Comment by jakevdp** [comment]
If you're talking about offline rendering in interactive mode rather than while embedded in a static page, this project might be of interest: https://github.com/altair-viz/altair_viewer

**Comment by joelostblom** [comment]
@lukasheinrich I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Comment by matthewfeickert** [comment]
Thanks @joelostblom. Things are working on the `pyhf` side, so we're all good here. :+1:

**Comment by RensDimmendaal** [comment]
@matthewfeickert would you be able to share how you all fixed it over there? 

I'm running into the same situation and I'd love to know how to fix it.
I took a look at the code at `pyhf` but couldn't see what made the difference.

**Comment by matthewfeickert** [comment]
> I'm running into the same situation and I'd love to know how to fix it.

I'm not sure if I can offer any good advice here, as we [just noticed one day that things were working](https://github.com/scikit-hep/pyhf/issues/720#issuecomment-656227299).

Can you share some details or an Issue for your project where this isn't working?
