### ISSUE TITLE
pandas nullable integer type in sanitize_dataframe

### ISSUE THREAD

**Issue by vadella** [altair-viz/altair#1922]
When given an array of [nullable integers](https://pandas.pydata.org/pandas-docs/stable/user_guide/integer_na.html), `sanitize_dataframe` raises a `TypeError: data type not understood`.

Minimal example:

```
>>> import altair as alt
>>> import pandas as pd
>>> df = pd.DataFrame({"x": [1,2,3, None, 5]}, dtype="Int64")
>>> df
     x
0    1
1    2
2    3
3  NaN
4    5
>>> alt.utils.sanitize_dataframe(df)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Miniconda3\lib\site-packages\altair\utils\core.py", line 223, in sanitize_dataframe
    elif np.issubdtype(dtype, np.integer):
  File "C:\Miniconda3\lib\site-packages\numpy\core\numerictypes.py", line 393, in issubdtype
    arg1 = dtype(arg1).type
TypeError: data type not understood
```

I've also tested this with pandas version 0.25 and 1.0.0rc0 and altair 3.2.0 and 4.1.0dev0

`alt.utils.sanitize_dataframe(df.astype(float))` works as expected

**Comment by jakevdp** [comment]
Nullable integers didn't exist when this code was written.

Are you interested in preparing a pull request?
