### ISSUE TITLE
Action Button Fills Chart Viewport

### ISSUE THREAD

**Issue by pjsample** [altair-viz/altair#1923]
After updating to Altair 4.0.1 from 3.3, the action button is now centered and completely covers my plots. Does anyone have any idea why this is happening? I updated via `conda update altair`.

I'm using JupyterLab v1.2.5 and I'm using the default Altair renderer.

![image](https://user-images.githubusercontent.com/13342278/72761959-a6ec7600-3b92-11ea-985c-59296980486a.png)

```
df = pd.DataFrame({'x': np.random.randint(0,100, 100),
                   'y': np.random.randint(0,100, 100)}) 

alt.Chart(df).mark_circle().encode(
            x='x', y='y')
```

**Comment by jakevdp** [comment]
This is due to overzealous CSS elsewhere in your JupyterLab window, either in a front end extension or in the output cell of a notebook (not necessarily the current notebook). See #1845 and #1916 for more information.
