### ISSUE TITLE
Can't read local file on DataBricks, plot is empty.

### ISSUE THREAD

**Issue by n3eo** [altair-viz/altair#1927]
I want to use altair on DataBricks and it works fine, as long as the data is provided as a DataFrame or a publicly available URL.
However if I try to load a local file, stored on the DataBricks FileSystem, the plot is empty beside the lables for the axes.
This is also the case when using `alt.data_transformers.enable('json')`. I tried the solution privided in #1867, but it seems to have no effect.

I can access and read the file without a problem (`with open(path)...`) and I can find it using `os.listdir(path)`

The version doesn't seem to affect it, I tried v3.3.0 and v4.0.0.

I hope I didn't miss anything from the documentation and thank you all for helping.

**Comment by jakevdp** [comment]
The file must be available to your frontend (I.e. the browser you are using to view the visualization). I'd check with DataBricks regarding whether there's some way to access the remote file system via an http request - there's nothing that can be done from Altair itself if DataBricks doesn't provide this.

**Comment by n3eo** [comment]
Thank you for the clarifications! Really helped me to understand, why it it not working.

___________________________________________________________________________________________________________
For anyone who is interested:

I read the DataBricks File System API and it is possible to read files with an HTTP request. 
However there are two problems when using with altair/vega/vegalite:
1. You need to inlcude an header with a Bearer token to access the file. Could be solved by using BasicHTTPAuth and include username and password in the URL. What I dont want to do!
2. The result is delivered as a JSON and the content is available under the "data"-key of the file. However it is encoded in Base64. You would need to decode beforehand.

I don't have a solution for both problems and I am also not really familiar with any of the topics.
Feel free to do your own research and find solutions for my problems or correct me if I missed something.
