### ISSUE TITLE
alt.data_transformers.enable('json') causing issues

### ISSUE THREAD

**Issue by handsome-rockslide** [altair-viz/altair#1929]
Hi I am having trouble with the alt.data_transformers.enable('json') in jupyter notebooks.

alt.__version__ -> 4.0.1
notebook.__version__ -> 6.0.3

if alt.data_transformers.enable('json') **is **not**** enabled then the following plot renders with data.

chart = alt.Chart(ti_df.head(50)).mark_point().encode(
    x='decision_time:Q',
    y='recovery_time:Q'
)

chart

if I enable the json saving (to help with large DataFrames) using `alt.data_transformers.enable('json')` then the axis are drawn without any data.

I really don't want my notebook to get too big so I don't want to remove the row limit.

**Comment by jakevdp** [comment]
I'd recommend avoiding the JSON transformer because it's behavior is dependent on the flavor of Jupyter you are using. Try altair_data_server instead.

**Comment by jakevdp** [comment]
Related: #1867

**Comment by handsome-rockslide** [comment]
Thanks so much for your reply.

I have never come across a WSGI server before. Can you confirm that my data will stay private? I assume this is the case but I would like to be sure.

I will also try and do some research online.

Thanks
