### ISSUE TITLE
Transform filter generates JSON with invalid escaping

### ISSUE THREAD

**Issue by domoritz** [altair-viz/altair#1937]
```py
import altair as alt
alt.Chart(data=alt.Data(url="")).mark_point().transform_filter(alt.datum['foo'] == 2).to_json(indent=0).replace('\n', '')
```

Generates

```json
{"$schema": "https://vega.github.io/schema/vega-lite/v4.0.0.json","config": {"view": {"continuousHeight": 300,"continuousWidth": 400}},"data": {"url": ""},"mark": "point","transform": [{"filter": "(datum[\'foo\'] === 2)"}]}
```

Which causes an error in JSON `Invalid escape character in string.`.

This is fixed by removing the escaping of `'`. 

Discovered by @ldegreef

**Comment by jakevdp** [comment]
Thanks! I will take a look.

As a workaround, I'd suggest using vega expression strings directly, e.g.
```python
import altair as alt
alt.Chart(data=alt.Data(url="")).mark_point().transform_filter("datum['foo'] == 2").to_json(indent=0).replace('\n', '')
```

**Comment by jakevdp** [comment]
I took a look at this: the extra backslashes only happen in the python repr of the JSON string. The actual string itself does not contain the backslashes:
```python
spec = alt.Chart("").mark_point().transform_filter(alt.datum['foo'] == 2).to_json(indent=None)
print(spec)
print(repr(spec))
```
output is:
```
{"$schema": "https://vega.github.io/schema/vega-lite/v4.0.0.json", "config": {"view": {"continuousHeight": 300, "continuousWidth": 400}}, "data": {"url": ""}, "mark": "point", "transform": [{"filter": "(datum['foo'] === 2)"}]}
'{"$schema": "https://vega.github.io/schema/vega-lite/v4.0.0.json", "config": {"view": {"continuousHeight": 300, "continuousWidth": 400}}, "data": {"url": ""}, "mark": "point", "transform": [{"filter": "(datum[\'foo\'] === 2)"}]}'
```

The first line is the actual string content (and shows no extra backslashes) while the second is Python's string repr, which adds backslashes – roughly, the repr is meant to show Python code that can be executed to generate the equivalent of the object.

I believe this is working as intended – please let me know if you have any questions.

**Comment by domoritz** [comment]
Thanks for the clarification. Makes sense.
