### ISSUE TITLE
Altair Plots blocked by the Save Bubble

### ISSUE THREAD

**Issue by MarcoRSousa** [altair-viz/altair#1938]
Plotting an Altair plot looks something like this after newly installing Altair:

![Screenshot from 2020-01-29 17-07-02](https://user-images.githubusercontent.com/47005260/73404503-a739ef00-42bf-11ea-925f-2df0e65381ee.png)

 I am using Python 3.6.9, Ubuntu 18.04 (5.3.0-26), Jupyter Lab 1.2.6.

What can I do to resolve this?

**Comment by jakevdp** [comment]
Try closing all your notebook tabs in Jupyterlab, then reloading the browser window. If that doesn't work, disable frontend extensions that may be affecting CSS styles and re-launch JupyterLab.

More details:  #1845, #1916, #1923

**Comment by eidietrich** [comment]
Seeing the same issue here — in Mac OS, Firefox 73.0, Python 3.8.1, JupyterLab v1.2.4, Altair 4.0.1. A similar issue in Chrome 79.0.3945.130, too, though instead of being oversized the action button is missing its dots.

No JupyterLab extensions or obvious CSS-tweaking front-end browser extensions.

A workaround is to turn off the actions menu via

```python
alt.renderers.enable('default', embed_options={'actions': False})
```

**Comment by jakevdp** [comment]
If you are able to figure out what extension or package is causing this (and what CSS attribute it's adding to cause the issue), that would be really helpful. I've still not seen this issue myself, and nobody who has reported it has been able to provide those details.

**Comment by jakevdp** [comment]
Have you tried closing all notebook tabs, closing the browser window, re-opening Jupyterlab, and then creating a chart in a new notebook? (Unfortunately, the way JupyterLab is architected, that's the only way to ensure that your CSS is clean).
