### ISSUE TITLE
No vegascope entry point found

### ISSUE THREAD

**Issue by rsuhada** [altair-viz/altair#1939]
Hi,

Running:

     import altair as alt
     alt.renderers.enable('vegascope')

Gives:

> entrypoints.NoSuchEntryPoint: No 'vegascope' entry point found in group 'altair.vegalite.v4.renderer'

Tested in python, ipython, and emacs (I don't use jupyter). No errors during installation. I can import vegascope without any errors/warnings.

Config:

    Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
    [GCC 7.3.0] :: Anaconda, Inc. on linux

    alt.__version__
    '4.0.1'

    vegascope.__version__
    '1.0.14'

Thank you!

**Comment by jakevdp** [comment]
vegascope has not yet been updated for use with Altair 4. It is an external project that the Altair team has no control over.

If you want similar functionality that works with Altair 4, try [altair_viewer](https://github.com/altair-viz/altair_viewer). It's a recently-released project that has not yet made it into Altair's documentation, but we plan to replace mentions of vegascope with altair_viewer in an upcoming release.

Install it with:
```
$ pip install altair_viewer
```
...then enable it in your Python script with:
```python
alt.renderers.enable('altair_viewer')
```

**Comment by rsuhada** [comment]
Thanks Jake for the quick response.
altair_viewer seems to work very well!
