### ISSUE TITLE
mark_circle() mishandles NaN data when taking mean

### ISSUE THREAD

**Issue by zeqianli** [altair-viz/altair#1944]
Notice left figure's top right corner: the data point is NaN and should not have been shown. This does not happen when mean is not taken (middle figure) or for mark_line() (right figure). 

The wrong points always appear at the top. It also happens for other operations (e.g. stdev). 

I'm using Altair 4.0.0.

```python
import altair as alt
import numpy as np
import pandas as pd


ts=[0,0,1,1,2,2,3,3]
rs=[1,2,1,2,1,2,1,2]
ys=[1,1,2,2,3,3,np.nan,np.nan]
data=pd.DataFrame({'t':ts,'r':rs,'y':ys})
base=alt.Chart(data,width=200)
scatter_mean=base.mark_circle().encode(x='t',y='mean(y)')
scatter=base.mark_circle().encode(x='t',y='y')
line=base.mark_line().encode(x='t',y='mean(y)')

scatter_mean|scatter|line
```

<img width="932" alt="Screen Shot 2020-02-02 at 12 38 52 AM" src="https://user-images.githubusercontent.com/36593276/73604331-9229be00-4554-11ea-8d38-412cd4b86b28.png">

**Comment by jakevdp** [comment]
Please paste code as text rather than as a screenshot.

**Comment by zeqianli** [comment]
I updated the description with code.

**Comment by jakevdp** [comment]
Thanks! This looks like a bug in Vega and/or Vega-Lite. I've opened an issue there: https://github.com/vega/vega-lite/issues/5837

**Comment by zeqianli** [comment]
Great!

**Comment by joelostblom** [comment]
The provided example is working for me on Altair 4.2.0 so I'm closing this, please re-open if you are still seeing the issue.
