### ISSUE TITLE
Specifying Images as labels along Y-axis

### ISSUE THREAD

**Issue by gowrishankarnath** [altair-viz/altair#1949]
Hi,
Is there a way to specify images as labels along Y-axis in Altair as shown in the image?
(Image Source: https://in.pcmag.com/news/132040/countries-that-spend-the-most-time-on-social-media-face-the-most-consequences)

![Countries](https://user-images.githubusercontent.com/5171251/73908983-5afb3a00-48d1-11ea-81ae-a3ecc42d3fb4.jpg)

**Comment by jakevdp** [comment]
There are two ways to do something like this. Images can be included in the labels if the images can be expressed as unicode emojis; here is an example:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    "country": ["Philippines 🇵🇭", "Nigeria 🇳🇬", "Mexico 🇲🇽"],
    "value": [100, 96, 94]
})

alt.Chart(df).mark_bar().encode(
    y='country:N',
    x='value:Q'
)
```
![visualization - 2020-02-06T055441 783](https://user-images.githubusercontent.com/781659/73943216-3b4e1c80-48a5-11ea-8547-5a9f2e173abd.png)

If the images you want to use are available by URL, you can use chart concatenation to achieve roughly the same effect:
```python
df['flag_image'] = [
    f"https://www.countries-ofthe-world.com/flags-normal/flag-of-{country}.png"
    for country in df['country']
]

flags = alt.Chart(df).mark_image().encode(
    y=alt.Y('country', axis=alt.Axis(domainOpacity=0, ticks=False)),
    url="flag_image"
)

chart = alt.Chart(df).mark_bar().encode(
    y=alt.Y('country', axis=None),
    x='value'
)

alt.concat(
    flags, chart
).configure_concat(
    spacing=0
).configure_view(
    strokeOpacity=0
)
```
<img width="707" alt="Screen Shot 2020-02-06 at 6 03 48 AM" src="https://user-images.githubusercontent.com/781659/73943892-7735b180-48a6-11ea-9cfb-d7f108d62032.png">

**Comment by gowrishankarnath** [comment]
Awesome. Thank you very much, Jake.
