### ISSUE TITLE
Scientific citation

### ISSUE THREAD

**Issue by deisi** [altair-viz/altair#1950]
Hey, I use altair for a plot in an upcoming scientific publication of mine. I want to know if there is any way for me to reference altair in the acknowledgements. Like e.g. matplotlib: https://matplotlib.org/citing.html

**Comment by jakevdp** [comment]
Sure, see https://github.com/altair-viz/altair#citing-altair

**Comment by jakevdp** [comment]
You might also cite https://dl.acm.org/doi/10.1109/TVCG.2016.2599030, which Altair is based on.

**Comment by deisi** [comment]
Ah sry for not finding this. Thx for the link.

**Comment by flaneuse** [comment]
@jakevdp : it might be nice to add these links to https://altair-viz.github.io/. I was trying to find a "how to cite" section there.  Thanks!

**Comment by joelostblom** [comment]
Thanks @flaneuse ! I opened https://github.com/altair-viz/altair/issues/2660 to track this.

**Comment by ianhi** [comment]
Above link has changed to: https://github.com/altair-viz/altair#citing-vega-altair
