### ISSUE TITLE
Reformatting ordinal date value

### ISSUE THREAD

**Issue by chankrista** [altair-viz/altair#1951]
I am trying to reformat the axis for an ordinal date value to show month year as follows:

```
alt.Chart(by_district).mark_rect().encode(
    alt.X('month_year:O', title='Month', axis=alt.Axis(format='%b %Y')),
    alt.Y('DISTRICT', title=['Police District'], axis=alt.Axis(grid=False),
          sort=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
                '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
                '23', '24', '25', '31', '41', '51']),
    alt.Color('isr_count', title=['Total ISRs per Month'])
).properties(
title={
  "text": ["Monthly ISRs by Police District 2016-2018"], 
  "subtitle": ["Total ISRs per month vary across police districts and over time.",
               "Source: Chicago Police Department Investigatory Stop Reports*"]
}
)
```

The above code does not output anything. When I remove the axis argument in alt.X as follows, my I do get output as shown in the image, but my dates are not formatted as I want them to be (Jan 2016, Feb 2016, etc.). Why might this be happening?

```
alt.Chart(by_district).mark_rect().encode(
    alt.X('month_year:O', title='Month'),
    alt.Y('DISTRICT', title=['Police District'], axis=alt.Axis(grid=False),
          sort=['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12',
                '13', '14', '15', '16', '17', '18', '19', '20', '21', '22',
                '23', '24', '25', '31', '41', '51']),
    alt.Color('isr_count', title=['Total ISRs per Month'])
).properties(
title={
  "text": ["Monthly ISRs by Police District 2016-2018"], 
  "subtitle": ["Total ISRs per month vary across police districts and over time.",
               "Source: Chicago Police Department Investigatory Stop Reports*"]
}
)
```
![image](https://user-images.githubusercontent.com/25648501/73975773-a66f1180-48ec-11ea-8a73-2f8fd9ec44bc.png)

**Comment by jakevdp** [comment]
Try using a time unit instead of an axis format string; e.g.
```
alt.X('yearmonth(month_year):O', title='Month')
```
I think the reason the format string didn't work is because you're specifying that your data is of ordinal type, not temporal type.

**Comment by chankrista** [comment]
Right, using temporal does make it work, but how can I prevent Altair from treating the variable as categorical rather than continuous in this case? When I use temporal, I get the following output. Thanks!
![image](https://user-images.githubusercontent.com/25648501/73978270-9efe3700-48f1-11ea-9ee6-7a7808b150a8.png)

**Comment by jakevdp** [comment]
If you use a timeUnit with an ordinal type as I suggested in https://github.com/altair-viz/altair/issues/1951#issuecomment-583104870, it should give you an ordinal axis with proper time formatting.

**Comment by chankrista** [comment]
I believe this is what I am doing in the code below (unless I am misunderstanding), but for some reason the output I get is complete empty.

```
by_district['month_year'] = by_district.month_year.astype('datetime64')
alt.Chart(by_district).mark_rect().encode(
    alt.X('month_year:O', title='Month', axis=alt.Axis(format="%b %Y")),
    alt.Y('DISTRICT', title='Police District'),
    alt.Color('isr_count', title='Total ISRs per Month')
).properties(
title={
  "text": ["Monthly ISRs by Police District 2016-2018"], 
  "subtitle": ["Total ISRs per month vary across police districts and over time.",
               "Source: Chicago Police Department Investigatory Stop Reports*"]
}
)
```

![image](https://user-images.githubusercontent.com/25648501/74106962-0f46cb80-4b31-11ea-9b4d-05420cea3dd1.png)

**Comment by jakevdp** [comment]
Temporal axis formats do not work with non-temporal values. You are specifying an ordinal encoding with a temporal axis format, which is why it does not work.

What you should do is ensure that your ordinal data is treated as temporal by specifying a [time unit](https://altair-viz.github.io/user_guide/times_and_dates.html) with your ordinal encoding. Change your x encoding from
```python
alt.X('month_year:O', title='Month', axis=alt.Axis(format="%b %Y"))
```
to
```python
alt.X('yearmonth(month_year):O', title='Month')
```

**Comment by chankrista** [comment]
Got it, thanks for the speedy assistance!
