### ISSUE TITLE
Does altair work with Jupyter Notebook ONLY? 

### ISSUE THREAD

**Issue by jiapei100** [altair-viz/altair#1952]
Sorry for my naive question.

I just started playing **altair**.

And, it doesn't show the plot if I **ONLY** run from the terminal by
```console
python test.py
```

However, if I convert **test.py** to **test.ipynb**, it shows beautifully in **Jupyter Notebook**.

Does that mean if I still prefer showing the plot from my local computer, I still need to use **matplotlib** instead ?

Cheers
Pei

**Comment by jakevdp** [comment]
No, see https://altair-viz.github.io/user_guide/faq.html#does-altair-work-with-ipython-terminal-pycharm-spyder-my-favorite-ide
