### ISSUE TITLE
Transform filter appears to incorrectly adhere to specified range

### ISSUE THREAD

**Issue by deflaux** [altair-viz/altair#1960]
The code below uses a selected point on a scatter plot to determine the range of data to show in a line plot via a transform filter. It appears to apply the lower bound of the range correctly, but the upper bound of the range is either not enforced or is some value not matching the intended upper bound. 

For example:
* click on a point at time 23 elapsed seconds
* expected: lower plot shows signal data for 18 - 28 elapsed seconds
* actual: lower plot shows signal data for 18 - 100 elapsed seconds where 100 is the end of the data

Tested this on both altair 3.2.0 and 4.0.1.

```
import altair as alt
from altair import datum
import numpy as np
import pandas as pd

phases = ['Pretest'] * 10
phases.extend(['Exercise'] * 70)
phases.extend(['Recovery'] * 20)
heart_rate = np.random.normal(60, 2, 10).tolist()
heart_rate.extend(np.random.normal(90, 10, 70))
heart_rate.extend(np.random.normal(80, 5, 20))

ecg_trend = pd.DataFrame({
    'heart_rate': heart_rate,
    'phase': phases,
    'time': range(0, 100)
})

ecg_signal = pd.DataFrame({
    'signal': np.random.normal(0, 2, 1000),
    'time': np.arange(1000) / 10
})

brush = alt.selection_single(on='mouseover', nearest=True, fields=['time'], init={'time': 200.0})

trend = alt.Chart(ecg_trend).mark_point(opacity=0.8, filled=True, size=100).encode(
    x='time:Q',
    y='heart_rate:Q',
    color='phase:N',
    tooltip=['heart_rate:Q', 'phase:N', 'time:Q']
).properties(
    width=900,
    height=200,
    title='Brush over this subplot to select a 10 second interval.'
).add_selection(brush)

signal = alt.Chart(ecg_signal).mark_line().encode(
    alt.X('time:Q', axis=alt.Axis(labelAngle=15)),
    y='signal:Q'
).properties(
    width=900,
    height=200
).transform_filter(
#    (brush.time - 5.0) <= datum.time & datum.time <= (brush.time + 5.0)
    '(({}.time - 5.0) < datum.time) && (datum.time < ({}.time + 5.0))'.format(brush.name, brush.name)
)

trend &  signal
```

**Comment by jakevdp** [comment]
I don't entirely understand why this is breaking, but I found that if you use ``toNumber()`` within the expression to force the selection value to be parsed as a number, it works as expected:
```
.transform_filter(
    '((toNumber({}.time) - 5.0) < datum.time) && (datum.time < toNumber({}.time) + 5.0)'.format(brush.name, brush.name)
)
```
It may be worth raising this within Vega-Lite itself; I'm not certain what implicit parsing is happening when this is left out.

**Comment by deflaux** [comment]
Thank you for the work-around @jakevdp !
