### ISSUE TITLE
Layered Legends 

### ISSUE THREAD

**Issue by eitanlees** [altair-viz/altair#1965]
I have noticed a few related questions ([1](https://stackoverflow.com/questions/60128774/adding-legend-to-layerd-chart-in-altair), [2](https://stackoverflow.com/questions/59921991/labelling-layered-charts-in-altair-python), [3](https://github.com/altair-viz/altair/issues/1964)) revolving around adding legends and labels to layered charts. 

In many questions asked on this subject the solution is to perform a [fold transform](https://altair-viz.github.io/user_guide/transform/fold.html#user-guide-fold-transform) such that the color can be appropriately encoded but it is not always so straight forward. 

While working on improving the [Scale and Guide Resolution](https://altair-viz.github.io/user_guide/scale_resolve.html) I came up against some difficulty. 

## Example

Let's say using the `cars` dataset I would like to create a chart with a dual y-axis showing the average `Horsepower` and average `Miles_per_Gallon` over time. These two variables have different units so it wouldn't make sense to include them on a single axis. 

From the [Layered Plot with Dual-Axis](https://vega.github.io/vega-lite/examples/layer_dual_axis.html) example on the Vega-Lite docs the solution is to manually specify the mark color and associated axis title color as such:

```python
import altair as alt
from vega_datasets import data

source = data.cars()

base = alt.Chart(source).encode(
        alt.X('year(Year):T')
)

line_A = base.mark_line(color='#5276A7').encode(
    alt.Y('average(Horsepower):Q', axis=alt.Axis(titleColor='#5276A7'))
)

line_B = base.mark_line(color='#F18727').encode(
    alt.Y('average(Miles_per_Gallon):Q', axis=alt.Axis(titleColor='#F18727'))
)

alt.layer(line_A, line_B).resolve_scale(y='independent')
```
![visualization (56)](https://user-images.githubusercontent.com/2041969/74344976-5f18d300-4d7b-11ea-908a-10743f5da8d2.png)

but you are left without a legend. In this case the axis colors are acting as a pseudo-legend.

**Questions**
- If I want to add a legend to this layered chart, is it possible? 
- Are legends only created if an appropriate encoding is made? 
- Can I add a legend for all the marks on a chart regardless of encoding?

Poking around I did find a way to recreate this chart using a fold and filter transform:

```python
import altair as alt
from vega_datasets import data

source = data.cars()

base = alt.Chart(source).mark_line().transform_fold(
    ['Horsepower', 'Miles_per_Gallon'], 
    as_=['Measure', 'Value']
).encode(
    alt.Color('Measure:N'),
    alt.X('year(Year):T')
)

line_A = base.transform_filter(
    alt.datum.Measure == 'Horsepower'
).encode(
    alt.Y('average(Value):Q', axis=alt.Axis(title='Horsepower')),
)

line_B = base.transform_filter(
    alt.datum.Measure == 'Miles_per_Gallon'
).encode(
    alt.Y('average(Value):Q',axis=alt.Axis(title='Miles_per_Gallon'))
)

alt.layer(line_A, line_B).resolve_scale(y='independent')
```

![visualization (55)](https://user-images.githubusercontent.com/2041969/74344928-4c9e9980-4d7b-11ea-986e-d53b63ca6df9.png)

but it feels more obfuscated.

## Conclusions

Personally I think the dual y-axis chart is a bad visualization practice ([further reading](https://blog.datawrapper.de/dualaxis/)) but it's what the people are asking for. 

Any advice on the topic of adding legends to layered charts with dual axis?

**Comment by jakevdp** [comment]
Legends are only created in Vega-Lite to represent an encoding. If https://github.com/vega/vega-lite/issues/1601 is ever implemented, it will be easier to construct legends for layered values.

But for the time being, I don't think there's any better answer than what you've done above.

**Comment by eitanlees** [comment]
The results of this discussion were added to the docs in https://github.com/altair-viz/altair/pull/1975
