### ISSUE TITLE
specifying tooltip causes warning about vegalite type

### ISSUE THREAD

**Issue by odoublewen** [altair-viz/altair#1966]
I have a plot that specifies a list of fields for tooltip (using the [mark configuration option](https://altair-viz.github.io/releases/changes.html?highlight=tooltip#highlights)).   `df` is a pandas dataframe

```
        self.artifact = alt.Chart(df).mark_point().encode(
            x=alt.X('right_index:Q', axis=alt.Axis(labels=False, ticks=False)),
            y=alt.Y('left_index:Q', axis=alt.Axis(labels=False, ticks=False)),
            tooltip=['left', 'right', 'probe_id', 'diagram', 'count'],
            color='type:N',
            size=alt.Size('count:Q', scale=alt.Scale(
                type='log',
                base=2,
            )),
        )
```

When I make this plot, it's all fine, except it throws this warning.   If I remove the tooltip, the warning goes away.  Is this mean I'm doing something wrong, or should I be using the Tooltip class?

`.venv/lib/python3.7/site-packages/altair/utils/core.py:109: UserWarning: I don't know how to infer vegalite type from 'empty'.  Defaulting to nominal.`

https://github.com/altair-viz/altair/blob/5d27c593e749de4f9bdb3df6c1efb5acf14c8b4c/altair/utils/core.py#L108

**Comment by jakevdp** [comment]
You can specify types for your tooltips as you do for other encodings:
```python
tooltip=['left:N', 'right:N', 'probe_id:N', 'diagram:N', 'count:N']
```
This will avoid calling the type inference utility for the problematic columns.

**Comment by odoublewen** [comment]
Indeed, thank you very much.  Not for the first time, I feel chagrinned for posting a question in this space.

I actually had tried that, but I had carelessly written the type specs in lower case (i.e. `left:n`) and so Altair threw a ValueError, so I assumed tooltips didn't work that way.

Sorry for the bother, and thanks again!!

**Comment by jakevdp** [comment]
No problem at all – glad you got it working!

**Comment by Janki-Vallabham** [comment]
data = df["Country"].value_counts()

    fig1, ax1 = plt.subplots()
    ax1.pie(data, labels=data.index, autopct="%1.1f%%", shadow=True, startangle=90)
    ax1.axis("equal")  # Equal aspect ratio ensures that pie is drawn as a circle.

    st.write("""#### Number of Data from different countries""")
    st.pyplot(fig1)

    st.write("""#### Mean Salary Based On Country""")
    data_country = df.groupby(["Country"])["Salary"].mean().sort_values(ascending=True)
    st.bar_chart(data_country)

    st.write("""#### Mean Salary Based On Experience""")
    data_experience = df.groupby(["YearsCodePro"])["Salary"].mean().sort_values(ascending=True)
    st.line_chart(data_experience)  

UserWarning: I don't know how to infer vegalite type from 'empty'.  Defaulting to nominal.
