### ISSUE TITLE
Stroke width not consistent for bar chart with multiple bars overlaid

### ISSUE THREAD

**Issue by kaisengit** [altair-viz/altair#1969]
Hi there,

I am trying to plot a point chart which has a bar chart overlay for style reasons (and for the actual data the bar chart opacity is coupled to some experimental condition, therefore highlighting it). Now my problem is that the stroke width of the bar charts seems to be coupled to the data points per category. 

See this plot:
![visualization](https://user-images.githubusercontent.com/29574032/74537726-f24c3700-4f3a-11ea-998b-5fdab0f8f349.png)

You can see that only category H (which has only one data point) follows the stroke width of 0.3. All other bars seem to add up depending on their number of points. I would really like to have all bars have a consistent stroke width.

To reproduce:
```
import pandas as pd
import altair as alt
import numpy as np
import random

np.random.seed(333)
random.seed(52)

categories = [c for c in 'ABCDEFGH']
values = np.random.uniform(0, 10, 15)
values = np.append(values, 5*[np.nan])

exp_a = [random.choice(values) for i in categories]
exp_b = [random.choice(values) for i in categories]
exp_c = [random.choice(values) for i in categories]
exp_d = [random.choice(values) for i in categories]

df = pd.DataFrame().from_dict({
    'cat': categories,
    'exp_a': exp_a,
    'exp_b': exp_b,
    'exp_c': exp_c,
    'exp_d': exp_d
})

df_melt = df.melt(id_vars=['cat'])
df_melt = df_melt.dropna()

chart_point = alt.Chart(df_melt).mark_point().encode(
    x='cat',
    y='value',
    color='variable'
)

chart_bar = alt.Chart(df_melt).mark_bar(filled=False, color='black', strokeWidth=0.3).encode(
    x='cat',
)

(chart_point + chart_bar).configure_scale(bandPaddingInner=0.5)


```
This is on altair 4.0.1

**Comment by jakevdp** [comment]
This is because you're plotting N identical bars on top of each other, and N is different for each column. In Altair, if you don't provide some sort of aggregate, the renderer will always draw a mark for every row in the dataset.

In your case, when you want to change the grouping of data without changing their visual attributes, you can use the ``detail`` encoding, which is designed for exactly this purpose:
```python
chart_bar = alt.Chart(df_melt).mark_bar(filled=False, color='black', strokeWidth=0.3).encode(
    x='cat',
    detail='count()'
)

(chart_point + chart_bar).configure_scale(bandPaddingInner=0.5)
```
![visualization - 2020-02-14T064448 590](https://user-images.githubusercontent.com/781659/74540932-82678d80-4ef5-11ea-835c-f7a7abc9ae7e.png)

**Comment by kaisengit** [comment]
Hey Jake and again thanks for your help!

This is extremely neat and works fine. However, if I combine my overlaid bars with a condition they all disappear if used with the detail encoding.
First I set the opacity for the bars to be conditional (the bars for A and H are hidden now):
![visualization_cond](https://user-images.githubusercontent.com/29574032/74544478-7e645b80-4f47-11ea-8ab1-2b35f79711d7.png)

Then I set detail='count()':
![visualization_cond_count](https://user-images.githubusercontent.com/29574032/74544511-8ae8b400-4f47-11ea-9643-ad1a7f89c2c8.png)

And all the bars become invisible... Any idea what is wrong here? 

This is the updated code:
```
import pandas as pd
import altair as alt
import numpy as np
import random

np.random.seed(333)
random.seed(52)

categories = [c for c in 'ABCDEFGH']
values = np.random.uniform(0, 10, 15)
values = np.append(values, 5*[np.nan])

condition = np.random.randint(0, 2, len(categories))

exp_a = [random.choice(values) for i in categories]
exp_b = [random.choice(values) for i in categories]
exp_c = [random.choice(values) for i in categories]
exp_d = [random.choice(values) for i in categories]

df = pd.DataFrame().from_dict({
    'cat': categories,
    'condition': condition,
    'exp_a': exp_a,
    'exp_b': exp_b,
    'exp_c': exp_c,
    'exp_d': exp_d
})

df_melt = df.melt(id_vars=['cat', 'condition'])
df_melt = df_melt.dropna()

chart_point = alt.Chart(df_melt).mark_point().encode(
    x='cat',
    y='value',
    color='variable'
)

sel_valid = alt.FieldEqualPredicate(field='condition', equal=1)
cond_opacity_hide = alt.condition(sel_valid, alt.value(1.0), alt.value(0))

chart_bar = alt.Chart(df_melt).mark_bar(filled=False, color='black', strokeWidth=0.3).encode(
    x='cat',
    opacity=cond_opacity_hide,
    detail='count()'
)

(chart_point + chart_bar).configure_scale(bandPaddingInner=0.5)
```

**Comment by jakevdp** [comment]
It's not clear to me from your code what the desired outcome is. Maybe a filter transform rather than an opacity condition would do what you want?

**Comment by kaisengit** [comment]
The desired outcome would be to hide some of the bars depending on some experimental condition (which can be True or False/0 or 1). I don't have much experience with altair filter transforms, so I am not sure how I could reach the same result. And shouldn't the detail encoding still work with the opacity condition?

**Comment by jakevdp** [comment]
OK - you have multiple rows in the dataset associated with each bar. Do you want to hide the bar if *all* of the relevant conditions are False, or if *any* of the relevant conditions are false? Or maybe if the majority of the conditions are False?

The best way to express this in code depends on exactly what you want to do.

**Comment by kaisengit** [comment]
You are right of course that there are multiple rows associated with each bar. Since the condition for each category (or bar) is assigned before the dataframe's melt operation, all conditions will be the same for each category. 
Which basically means it does not really matter: all conditions pointing to one bar should be either False or True (or something is wrong with my data). So if any condition is False that automatically means that all should be False.

Hope this makes some sense...

**Comment by jakevdp** [comment]
OK, in that case I'd probably use a filter transform rather than a conditional opacity. Then only the data you're interested in displaying will be shown in the chart:
```python
chart_bar = alt.Chart(df_melt).mark_bar(filled=False, color='black', strokeWidth=0.3).encode(
    x='cat',
    detail='count()'
).transform_filter(
    'datum.condition == 1'
)

(chart_point + chart_bar).configure_scale(bandPaddingInner=0.5)
```
![visualization - 2020-02-14T114412 224](https://user-images.githubusercontent.com/781659/74562284-54973e80-4f1f-11ea-9429-2e896ee1453a.png)

**Comment by kaisengit** [comment]
Thank you Jake! That is indeed the best approach to my problem.
