### ISSUE TITLE
How can I style the tooltip when creating a custom theme?

### ISSUE THREAD

**Issue by jan-scorl** [altair-viz/altair#1970]
I couldn't find anything in 'Top-Level Chart Configuration' or 'altair.Tooltip'.

**Comment by jakevdp** [comment]
There are no options within Altair to change tooltip styles. If you want more flexible tooltips, you can use vega-embed directly along with the [vega-tooltip](https://github.com/vega/vega-tooltip/) plugin. As far as I know, there is not any documentation or examples of doing this from Altair.

**Comment by jan-scorl** [comment]
Thank you Jake. If I manage to figure it out, I will write a tutorial. 
I have deprioritized it for now though, so it might not happen soon.
