### ISSUE TITLE
conditional formatting mark_text based on variable?

### ISSUE THREAD

**Issue by parodayco** [altair-viz/altair#1976]
I've read the docs on conditions based on interactions but I didn't find a way to format chart text based on conditions. Here's a particularly egregious example where I would like `mark_text(align="left", dx=20)` for `seller_status` up to 50%, over 50% `mark_text(align="right", dx=-20)`. I'd appreciate any ideas you have. 

![visualization(1)](https://user-images.githubusercontent.com/42258137/74679998-6da52700-518d-11ea-9df2-8c19eecdc4fa.png)

**Comment by jakevdp** [comment]
No, unfortunately the only thing that can depend on conditions are encodings, not mark properties. I know the Vega-Lite team has been thinking about ways to relax this restriction, so you might inquire there.

**Comment by parodayco** [comment]
Ok, thanks Jake. I'll bring it up with them. They have an example of conditionally altering text in the first example on https://vega.github.io/vega-lite/docs/text.html and am hoping that's the path to my solution. Have a look and please let me know if that can currently be reproduced with Altair. If not, perhaps I can fork and try to help add the capability.

**Comment by jakevdp** [comment]
Yes, you can conditionally encode the color, because the color is an encoding channel. You cannot conditionally encode offset, because offset is not (yet) an encoding channel.

**Comment by jakevdp** [comment]
The relevant issue to add your +1 is here: https://github.com/vega/vega-lite/issues/4703

**Comment by parodayco** [comment]
Thanks again, Jake! I saw your recommendation and cross-post to the vega issue board.
