### ISSUE TITLE
invisible symbol in legend for mark_trail

### ISSUE THREAD

**Issue by YuliaGazizova** [altair-viz/altair#1977]
Hey guys!
Thank you for Altair. 
Recently, I met a small but quite annoying bug: with mark_trail graph, symbols in a legend are not visible. Not only line thickness but all symbols in a legend. You can see an example of such behavior even on the Altair page https://altair-viz.github.io/gallery/trail_marker.html.
Another example I attached as a print screen:
1. mark_trail graph. Symbols in the legend are not visible
2. mark_line graph with the same data. Symbols in the legend are visible
![1  mark_trail](https://user-images.githubusercontent.com/39081713/74745849-cbf10900-5264-11ea-8032-cf08aaace101.png)
![2  mark_line](https://user-images.githubusercontent.com/39081713/74745864-d01d2680-5264-11ea-9ecc-22f13763c661.png)
Is it because I am stupid or it is a bug?
Yulia

**Comment by jakevdp** [comment]
This is a bug in Vega-Lite that was recently fixed: https://github.com/vega/vega-lite/issues/5879

The fix should make it into the next Altair release.

**Comment by YuliaGazizova** [comment]
Ok. 
Thank you!

**Comment by kaisengit** [comment]
I've just updated to altair 4.1.0 and the bug is still there for me. Should it not be fixed now?

**Comment by jakevdp** [comment]
It should be fixed; for example it works correctly in the documentation now: https://altair-viz.github.io/gallery/trail_marker.html

How are you rendering your Altair charts?

**Comment by kaisengit** [comment]
Ops, I am sorry, it is indeed fixed. Beforehand I was using a square mark which also made big squares in the legend. The trail mark is just using very thin trails indeed for the legend. And that combined with the colors I chose made them very hard to see but they are there now. So this issue can probably be closed.

**Comment by jakevdp** [comment]
Great, thanks for checking!
