### ISSUE TITLE
tooltips not showing for stacked bars with round corners

### ISSUE THREAD

**Issue by bartekpi** [altair-viz/altair#1979]
Hi!
It sounds oddly specific, but looks like the combination of round corners and stacked bars prevent the tooltips from showing.
I am using altair 4.0.1 and I'm not seeing tooltips in the middle chart:
```python
import altair as alt
from vega_datasets import data

source = data.seattle_weather()

chart1 = alt.Chart(source).mark_bar(
).encode(
    x='month(date):O',
    y='count():Q',
    color='weather:N',
    tooltip=['count()']
)

chart2 = alt.Chart(source).mark_bar(
    cornerRadiusTopLeft=3,
    cornerRadiusTopRight=3
).encode(
    x='month(date):O',
    y='count():Q',
    color='weather:N',
    tooltip=['count()']
)

chart3 = alt.Chart(source).mark_bar(
    cornerRadiusTopLeft=3,
    cornerRadiusTopRight=3,
).encode(
    x='month(date):O',
    y='count():Q',
    tooltip=['count()']
)

chart1 | chart2 | chart3
```

![altair_tooltip_issue](https://user-images.githubusercontent.com/7944978/75056764-8d12bb80-54cf-11ea-82ea-cf17b30df7bc.gif)

**Comment by jakevdp** [comment]
Looks like a vega-lite bug - I don't see any existing mention of it in the issue tracker

**Comment by jakevdp** [comment]
https://github.com/vega/vega-lite/issues/5956

**Comment by binste** [comment]
Closing as it works with Altair 5 and Vega-Lite 5.8.
