### ISSUE TITLE
transform_fold() does not work after renaming columns

### ISSUE THREAD

**Issue by jan-scorl** [altair-viz/altair#1980]
Running
```
d1_coll = alt.hconcat()

d1_bvb = bvb.copy()
d1_bvb.rename(columns = {'value' : 'value_renamed', 'fee' : 'fee_renamed'}, inplace=True)

for chart in [
    [0 , 'All players'], 
    [1, 'Excluding free agents'], 
    [1000000, 'Transfers above €1 million']
    ]: 
    
    d1_chart = alt.Chart(
        d1_bvb,
        title = chart[1]
        
    ).transform_filter(
        datum.fee >= chart[0]
        
    ).transform_fold(
        ['value_renamed', 'fee_renamed'], as_ = ['key_fold', 'value_fold']
        
    ).mark_bar(
        clip=True
    ).encode(
        y=alt.Y('mean(value_fold):Q', scale=alt.Scale(domain=(0,14000000)), title='Average in (€)'),
        x=alt.X('key_fold:N', title = 'x-Axis title'),
        color=alt.Color('key_fold:N'),
        column=alt.Column('trans_type', title='column title', spacing=5)
    )
    
    d1_coll |= d1_chart
    
d1_coll
```

returns no chart. 

When I comment out the `d1_bvb.rename()` line and change the first argument in `transform_fold()` to `value` and `fee`, it returns the correct chart.

**Comment by jakevdp** [comment]
Without information about what ``bvb`` is, it will be difficult to help you.

**Comment by jan-scorl** [comment]
Yes, that was the right hint Jake. I forgot to change `datum.fee` to `datum.Fee`. Sorry, I should have caught that one myself. Is it possible to make a donation to the Altair team somewhere?

**Comment by jan-scorl** [comment]
Perhaps a short addition that led to this question:
After `transform_fold()` the column titles become column values in the 'key' column. Since I usually write my column titles in snake_case the resulting values don't look pleasant on a chart. 

Is there a more elegant way to change the snake_case column titles into capitalised column values than renaming the column before running `transform_fold()`?

**Comment by jakevdp** [comment]
The only way to change the names of your columns once they're passed to the chart is to use a calculate transform. You could do something like this:
```python
import numpy as np
import pandas as pd
import altair as alt

rand = np.random.RandomState(0)
data = pd.DataFrame({
    'date': pd.date_range('2019-01-01', freq='D', periods=30),
    'data_a': rand.randn(30).cumsum(),
    'data_b': rand.randn(30).cumsum(),
    'data_c': rand.randn(30).cumsum(),
})

alt.Chart(data).transform_calculate(**{
    'Data A': 'datum.data_a',
    'Data B': 'datum.data_b',
    'Data C': 'datum.data_c',
}).transform_fold(
    ['Data A', 'Data B', 'Data C'],
).mark_line().encode(
    x='date:T',
    y='value:Q',
    color='key:N',
)
```
![visualization - 2020-02-22T062727 596](https://user-images.githubusercontent.com/781659/75094066-68a0f880-553c-11ea-98f2-d6196276911b.png)

**Comment by jan-scorl** [comment]
Thank you!
