### ISSUE TITLE
Multiple views in JupyterLab blank with default html renderer

### ISSUE THREAD

**Issue by jasongrout** [altair-viz/altair#1984]
To reproduce:

1. Create an environment with JupyterLab 1.2.6 and altair 4.0.1:

```
conda create -c conda-forge -yn testenv jupyterlab altair pandas
conda activate testenv
```

2. Start JupyterLab:
```
jupyter lab
```
3. Create a new notebook with an example plot:

```
import altair as alt
import numpy as np
import pandas as pd

# Compute x^2 + y^2 across a 2D grid
x, y = np.meshgrid(range(-5, 5), range(-5, 5))
z = x ** 2 + y ** 2

# Convert this grid to columnar data expected by Altair
source = pd.DataFrame({'x': x.ravel(),
                     'y': y.ravel(),
                     'z': z.ravel()})

alt.Chart(source).mark_rect().encode(
    x='x:O',
    y='y:O',
    color='z:Q'
)
```
4. Right-click on the plot and choose "Create New view for output" to open a new jlab tab for the plot. The new tab is blank:
<img width="622" alt="Screen Shot 2020-02-24 at 11 22 23 AM" src="https://user-images.githubusercontent.com/192614/75183729-f70da980-56f7-11ea-8e25-bf11bfda8b9f.png">

I also see the same issue if opening a new view of the notebook (right-clicking on the file's tab, selecting "New View for Notebook"

I think at least part of the problem is that the plot div has a hard-coded id, and ids should be unique on a page, so viewing the same output multiple times can be a problem. There may be other issues with the js not knowing to redraw the plot in the new jlab tab, etc.

**Comment by jasongrout** [comment]
This is related to https://github.com/altair-viz/altair/pull/1888 - but I think #1888 didn't go far enough in making IDs unique on the client-side, at least for this case.

I think if there is a way to not use the html id attribute, but instead to search in the DOM for a specific nearby div with a given class or data attribute, that may be better.

**Comment by jakevdp** [comment]
Thanks!
