### ISSUE TITLE
`sort` argument doesn't sort categories/colors in stacked bar

### ISSUE THREAD

**Issue by gschivley** [altair-viz/altair#1987]
There are [several](https://github.com/altair-viz/altair/issues/397#issuecomment-496018158) [places](https://altair-viz.github.io/user_guide/generated/channels/altair.Y.html#altair-y) [indicating](https://vega.github.io/vega-lite/docs/sort.html#specifying-custom-sort-order) that the argument `sort` can be used universally to set a custom ordering by passing an array (list) with the desired order. This works for categories on the x-axis of a grouped bar chart but not the y-axis.

Current versions:
```
# Name                    Version                   Build  Channel
altair                    4.0.1                      py_0    conda-forge
jupyterlab                1.2.6                      py_0    conda-forge
```

Example ([vega-lite spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6bYwIAuy8ArrDQM4DqyAJhQBakAsADLwBooceFVr0GACQJoOFUgGZ+AX2UDwUVgEMKW0jnhaAtgVKRtugLTdEvGwS0BOAIwLuCgExaPC362jO0B4AHI7BiIgECoh6ahqQRloATgDWZgBGyZDqEJAE8HCs1OhYoBC5cAA2sEn6GuVQFACeAA6mWJDwsEbUWpXZ9eWQKASVrGYASgQM9EnQBGAAcsamOQ1QDNB97diDDebdWtSkANqQAPLwDBw1Cyzw40KQAMqwlVlPAEI6FARJTdkoIsAOIAYVBkAAumt1lAklp4KgdmcAMTOADs6QI0EQgMgKNYADYPOiQniUdAAKzpXisSnk9LQdKsDweKF7MDKQZxfYAD30kGabTMXR6hn6TxGYzMoK0DFWGxq8iwZ0+eIAglCeUMAaUOYLWjtIABHGgIqi6Ki4Vb6qXjDqylpaaDIZoDWGQGZJZVgM6Xa63MD3R5QV7vWpfH5-AFPEHg9kNLkQbWQAAkmw4BESZjkFBaDAwAHpC9bUFoAHSoV0cGjpcvIWCFjNZrQlghlyyVV0EEvccu8csecsAKxm8Hdmh0coIFAYdX2Fi01ls9icrncXh8fgCQVC4Ui0T0Ko5OCmMxocwWyxMZm+FF+-zxjudrt1YA8T1l8rMmu1DVP0yzPMSwrGYcYQp+WhOi6bpYB4ghQF+Rq-jC5QAeel4gTeHT+jcSR3NQIaQM+MFvs4CHEdOP6QH+aGQGeQFXqBHRhh8iFQS+sFgM4lKQd+HQoSe9GARewHXkad4PjG7HQa+ih8RJNGoRA6GMVhRrgU+HGkaQ5EKbeSlCQxolMdhUC4YGwZabJXFKPpHRqrRKnCRhYnMaGbxsZRNlvh4vHsfxUCOYMkIaFyyhAA)):
```py
import pandas as pd
import altair as alt

resource_order = [
    "Onshore Wind",
    "Solar",
    "Battery",
    "NGCC",
]
resource_color_scale = alt.Scale(
    domain=resource_order, 
    range=[
        "#17becf", # onshore wind
        "#d62728",  # solar 
        '#c5b0d5', # battery
        "#bcbd22", # NGCC
    ]
)
resource_colors = alt.Color("Resource Name", scale=resource_color_scale)
    
data = pd.DataFrame(
    {
        "Resource Name": ["Battery", "NGCC", "Onshore Wind", "Solar"] * 2, 
         "Capacity": [2, 20, 10, 15, 3, 10, 30, 25], 
         "Case": ["A", "A", "A", "A", "B", "B", "B", "B"]
    }
)

alt.Chart(data).mark_bar().encode(
    x=alt.X('Case', sort=["B", "A"]), # Default order is alphabetical "A", "B"
    y=alt.Y('Capacity', sort=resource_order),
    color=resource_colors
)
```
![image](https://user-images.githubusercontent.com/10373332/75251675-1c0e2500-57a9-11ea-9f39-a1ff01983bdd.png)

I did, however, find a workaround by ordering according to a new indexing column ([vega-lite spec](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6bYwIAuy8ArrDQM4DqyAJhQBakAsADLwBooceFVr0GACQJoOFUgGZ+AX2UDwUVgEMKW0jnhaAtgVKRtugLTcFC6AE5urAgCYAHAFYPWj6wBGAOx+Hrx+3ABsiM4EvACM9p6QahqQRloATgDWZn4ZkOoQkATwcKzU6FigEIVwADaw6foa1VAUAJ4ADqZYkPCwRtRatfnN1ZAoBLWsZgBKBAz06dAEYAByxqYFLVAM0EPd2KMt5v1a1KQA2pAA8vAMHA0rLPDTQpAAyrC1eW8AQjoUAjpNr5KCrADiAGFIZAALpbbZQdJaeCoA5XADEsSCBGgiFBkAxrHCLgC7gJGOgHj8vFYHgpfmgflYLhccKOYGUo2SxwazkalUg7S6ZgAjjQUVRdFRcJsoBMpmY2AAPJIIqCqwXCg69fqDYZvBXTHqQrQMOWQBbpeRYK6-AkAQThPLGIK1nR14slyGlyFlBKNZlNHS00B9IK5EBdkAAJLsOAQ0mY5BQOgwMAB6DOy1BaAB0qB9HBofjzyFgGfjia02YIucstR9BGz3DzvDzLjzACsFvARoULGaCBQGE1joPrLYHE5XJ5vL5AsFQhEogQYvFEraOTg5gsaEsVusTGZ-hRAcCCcHQ+HSC43qbzWYnW8VaRYi6Wjv5otlmsNmYIWhS8tBDMN2lvQQoAfHVnygV8sF4D9qi-PcDz-Y8elue5HjAZ5XigkDr3ArBYkgyBoKfAl4LABQkIgFCf0Pf8ek+b5GnvQiwLdMBYg8DjHx6WDIGolw6LIXdGPQnVT3PEEONAm8sAUfjpKo1hNR4sSGP3X8jx1QCYXkojuNIlSTzUjTEPVejIAknSmIwqAsIedInmofDyM4xSaLIiientF91MULTbO-eypLMVifgIhTiLAFw+IIgSoACuCgqwUTRlhDQuWUIA)):
```py
resource_order_idx = {
    resource: idx 
    for idx, resource in enumerate(resource_order[::-1]) # Reverse list to align colors
}                                                        # with legend order

# Create "idx" column with integer values indicating order in stacked bar
data["idx"] = data["Resource Name"].map(resource_order_idx)

alt.Chart(data).mark_bar().encode(
    x=alt.X('Case', sort=["B", "A"]),
    y=alt.Y('Capacity'),
    order="idx",
    color=resource_colors
)
```
![image](https://user-images.githubusercontent.com/10373332/75251711-2defc800-57a9-11ea-908b-cdf715dcb9b3.png)

I'm not sure if this is a bug in vega-lite, an oversight in the API, or the way that it is supposed to work, but I'm providing this example and my work-around to help anyone else who might be searching for for help with the same issue.

**Comment by jakevdp** [comment]
The ``order`` encoding is the [documented way](https://vega.github.io/vega-lite/docs/stack.html#sorting-stack-order) to specify sort order for stacked bars, so I believe this is working as intended.

The docs on the Altair side, as always, could be improved.

**Comment by jakevdp** [comment]
The y encoding's ``sort`` property applies to the axis, not to the marks that appear on the chart. To see why this is not a sensical place to specify sort order, imagine a horizontally-concatenated chart showing two datasets with different stack orders but the same numerical y scale: specifying two different stack orders via one shared axis would not be possible.

**Comment by gschivley** [comment]
> To see why this is not a sensical place to specify stack order, imagine a horizontally-concatenated chart showing two datasets with different stack orders but the same numerical y scale: specifying two different stack orders via one shared axis would not be possible, but each panel can have its own order encoding without any problem.

Ok, I think I see what you mean. A simple way to order stacked bars that accepts an array would be more intuitive (and easier) but it seems that's a Vega-Lite limitation.

As always, thanks for all the effort!

**Comment by jakevdp** [comment]
I believe [this issue](https://github.com/vega/vega-lite/issues/1734) tracks the functionality you want.

**Comment by gilzero** [comment]
i came across this 'issue', as suggested above, a work around is to assign a new order column with quantitative values (or use a numeric index from df) after preprocess with whatever required order in dataframe:

a quick example: 

`import pandas as pd
import numpy as np

data = [
    {"name": "nike", "share": 61, },
    {"name": "adidias", "share": 30, },
    {"name": "asic", "share": 6, },
    {"name": "reebok", "share": 3, }
]

data = pd.DataFrame(data)

df = pd.DataFrame(data).sort_values(by='share', ascending=False)

df['order'] = np.arange(0, df.shape[0])

df`

![Screen Shot 2022-10-31 at 12 21 31](https://user-images.githubusercontent.com/977986/198930494-dd195f90-c4bc-405b-a1ab-59fa290bd9cd.png)



`bars = alt.Chart(data).mark_bar().encode(
    x=alt.X('share:Q', 
            stack='zero', 
           ),
    color=alt.Color('name',
                   sort=df.name.values,
                   ),
    order='order:Q'
)


text = alt.Chart(data).mark_text(dx=-8, dy=3, color='white').encode(
    x=alt.X('share:Q', 
            stack='zero', 
           ),
    text=alt.Text('share:Q'),
    order='order:Q'
)


bars + text`


![Screen Shot 2022-10-31 at 12 21 45](https://user-images.githubusercontent.com/977986/198930515-2fba25c5-40be-488a-963b-7a0957549c95.png)

**Comment by joelostblom** [comment]
Leaving a note that since [Altair 6.1.0](https://github.com/vega/altair/releases/tag/v6.1.0), the default stack order now follows the order of the color domain.
