### ISSUE TITLE
Printing in the same cell as a chart suppresses plot display

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#199]
e.g.

``` python
from altair import Chart, load_dataset

print('hello world')
cars = load_dataset('cars')
Chart(cars).mark_tick().encode(x='Miles_per_Gallon')
```

Comment-out the print statement and the plot will show again.

**Comment by domoritz** [comment]
Is the problem that we use a different output format? Vega-Charts are images and `print` is text.

**Comment by jakevdp** [comment]
I don't think so... generally there can be both a print output and a rich output. For example:
![screen shot 2016-11-17 at 12 37 41 pm](https://cloud.githubusercontent.com/assets/781659/20406569/ad1aeda2-acc2-11e6-966d-13bd9e86ae1d.png)

**Comment by ellisonbg** [comment]
We should check this in the 1.3 release once we migrate to the new MIME based rendering.

**Comment by ellisonbg** [comment]
I have confirmed that in jupyterlab, this works fine, but it looks like it is still an issue with the old rendering that uses ipyvega.

**Comment by joelostblom** [comment]
This works for me in both the classic notebook 6.1.4 and JL (2.2.8) so closing this issue.
