### ISSUE TITLE
How can I set margin-top for a bar chart?

### ISSUE THREAD

**Issue by jan-scorl** [altair-viz/altair#1993]
![visualization-4](https://user-images.githubusercontent.com/17554280/75347187-33e5c600-58db-11ea-98d2-239a83660146.png)

I can set the green margin/padding using
```
scale=alt.ScaleConfig(
                bandPaddingOuter = value,
                bandPaddingInner = value
            )
```

However, I couldn't find any parameter that sets the red margin.
I'm currently solving that with `scale=alt.Scale(domain=(0, highest_value + margin_i_want)` but that feels a bit hacky.

`.configure(padding={ 'top' :  10 })` was the solution I expected but it sets the padding between the whole chart and its surroundings. Is there another way to set the margin-top / margin-bottom of a bar?

**Comment by jakevdp** [comment]
There is no option in Altair/Vega-Lite to add padding to quantitative domains. The full list of available domain specifications is described here: https://vega.github.io/vega-lite/docs/scale.html#domain

The current best option is to use ``alt.Scale(domain=[lowest_value, highest_value])``.

**Comment by joelostblom** [comment]
@jan-scorl I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
