### ISSUE TITLE
Upgrade Altair documentation page

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#1994]
The more I use Altair the more I found myself lost in the documentation [page](https://altair-viz.github.io). Something that I don't feel when I'm on the doc page on the Vega-lite side.

I almost don't dare to say it, but with the continuous growth of possibilities and users, maybe its time to redo the doc page to get it more aligned with the Vega-lite side..

**Comment by jakevdp** [comment]
Sure, what suggestions do you have?

**Comment by mattijn** [comment]
Eventually I'm able to find the information I need, but currently its a bit hidden in the closed directory structure on the left. 

I wish to have a vertical bar on the top to go to specific parts in the documentation. Something like the current Vega-Lite or Pandas docs.
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/5186265/75584137-5d375b00-5a6f-11ea-8d2b-c3b2f49002c1.png">

<img width="1053" alt="image" src="https://user-images.githubusercontent.com/5186265/75584089-4264e680-5a6f-11ea-8e7c-b0e566d17125.png">

This will split the amount of information in the current directory structure significantly.

In the Vega-Lite docs I like the clear minimalistic categorisation of options under Transform, Mark, Encoding, View composition and Selections. Especially the inclusion of the various mark types, which is very much the core of any visualisation.
<img width="151" alt="image" src="https://user-images.githubusercontent.com/5186265/75584966-4f82d500-5a71-11ea-96f6-d446bd213a50.png">

By the way, in the docs of Vega-Lite there are no options under Data / Datasets:
<img width="151" alt="image" src="https://user-images.githubusercontent.com/5186265/75585244-e5b6fb00-5a71-11ea-9bcc-199f15df6433.png">
I think there should be some sub-options, especially for Altair.

Furthermore I won't deny that the adopted font size and usage of white gives a pleasant reading experience in the Vega-Lite docs (vs both Pandas and Altair docs).

**Comment by jakevdp** [comment]
Great! The source is in ``docs`` and a lot of the Altair-specific sphinx functionality is in ``altair/sphinxext``. Give it a whirl and see if you can come up with some tweaks that will bring it closer to how you wish it was.

I won't lie though: fine-tuning sphinx themes is not easy or fun.

**Comment by mattijn** [comment]
How fixed are you on sphinx? Will the fun(potential contributors) increase when using Jekyll / markdown?

**Comment by jakevdp** [comment]
I chose sphinx because it provides the ability to do auto-documentation based on Python code, and makes it easy to define custom directives (for things like embedding Altair plots and generating the gallery)

I wouldn't be opposed to moving to another system if that would be easier to maintain and update.

**Comment by mattijn** [comment]
Ok, thanks for prompt response. I'm not jumping directly on this issue, but at least some info is documented here.

**Comment by mattijn** [comment]
I adopted the pydata-sphinx-[theme](https://github.com/pydata/pydata-sphinx-theme) and made a few changes in the organisation of files and the result is already very clean.

See following animated gif:
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/5186265/109842117-0815c280-7c4a-11eb-8398-8d7faefa0c4d.gif)

By including [nbsphinx](https://nbsphinx.readthedocs.io/en/0.8.2/) as extension we can organise most of the documentation-pages as notebooks (like Jupyter book).

Progress at least!

**Comment by jakevdp** [comment]
Awesome! That would be really great.

Regarding nbsphinx... I recently transitioned another project from nbsphinx to myst-nb, and I'm finding the latter to be a much cleaner way to integrate notebooks into sphinx docs.

**Comment by joelostblom** [comment]
@mattijn Is it ok if I look into updating the docs for 5.0 or do you have some specific changes you want to make that are already in progress? I am thinking of doing something very similar as what you suggest here with changing the theme to look more like the Vega docs and I am curious to what reorganization you had in mind. I don't think I will switch the docs over to notebooks for the time being, but I agree that jupyter books with myst is a very nice way to work with documentation in general and what I use for new projects myself.

**Comment by mattijn** [comment]
Sure, go ahead! I had a try with the suggestions above at that time. At that moment I struggled a bit with 
(1) apply a new theme while maintaining the url-references on the internet still point to the right page, or 
(2) restructure the documentation and accept that references elsewhere on the internet needs to be updated.

I tried 1, but if you improve the structure significantly, just do 2.

**Comment by mattijn** [comment]
You were able to make any progress on this @joelostblom?

**Comment by joelostblom** [comment]
Nope, I got caught up in too many things at work. I'm planning to revisit when I have more time, but probably not until late Feb so feel free to work on this if you have time and think 5.0 will be out before I get back on this.

**Comment by mattijn** [comment]
No problem. Lets see, good to know👍
