### ISSUE TITLE
Ordinal scale turns into point scale when used for opacity encoding

### ISSUE THREAD

**Issue by pgorczak** [altair-viz/altair#1996]
I tried to use my own ordinal scale for opacity and it looks like it's possible in Vega-Lite but Altair overwrites the scale type at some point.

Example
``` python
import altair as alt
from vega_datasets import data

alt.Chart(data.cars()).mark_point(filled=True).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color=alt.Color(
        'Origin',
        scale=alt.Scale(
            domain=['Europe', 'Japan', 'USA'],
            range=['tomato', 'royalblue', 'limegreen']
        )
    ),
    opacity=alt.Opacity(
        'Origin',
        scale=alt.Scale(
            type='ordinal',
            domain=['Europe', 'Japan', 'USA'],
            range=[1, 0.1, 1]
        )
    )
)
```
Instead of assigning the ordinal opacity values to Europe, Japan and USA, the result looks like this:
![](https://user-images.githubusercontent.com/1765698/75450142-8d4b0500-596e-11ea-80ab-2fd7ab7b5b0a.png)
After checking the Vega-Lite output, it turns out that the opacity scale has been turned into a point scale:
``` json
"scales": [
    {
      "name": "color",
      "type": "ordinal",
      "domain": ["Europe", "Japan", "USA"],
      "range": ["tomato", "royalblue", "limegreen"]
    },
    {
      "name": "opacity",
      "type": "point",
      "domain": ["Europe", "Japan", "USA"],
      "range": [1, 0.1, 1]
    }
  ],
```
Manually changing the type of the opacity scale back to *ordinal* makes the plot show up as expected:
![](https://user-images.githubusercontent.com/1765698/75450541-52959c80-596f-11ea-9fdd-46e0d78c4a85.png)

**Comment by jakevdp** [comment]
Thanks for the bug report. It appears that this is an issue with how Vega-Lite is compiled to Vega. I'd suggest raising it in the Vega-Lite repository; there's nothing we can change in the Altair repository that will change how Vega-Lite is compiled to Vega.

**Comment by jakevdp** [comment]
Here's a succinct Vega-Lite specification that takes Altair out of the mix and reproduces the issue ([vega editor](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEAmCGAutIC4zEgVwE4BsVTkQHoBjWLAZwDoArCgewDtIBfAGnCgFtyBrfSFgCmJeJA4RIQxiXrQAlowDm+UBEn0ADrBLz4AT1Wd1UA5qEDG9Loth4JJqADN5QnNAEB5LPKWLxxuqQFGQ4FqhqjpLQ1rD+qADakACi2FoWbFAAUrDazJmQAKoAygCCkAC6DlGCsMrhYAkAjJkADFQtYE1VgSaQZg2Q9FgKjHaQvWAsgeyBkIYR-frmAsOj4wUubh6okN6+-rN9AB6qkLBKSsJKCIOyGIxiBQMCAI4YdfB6CPIAbhbTCDTFhAA))
```json
{
  "data": {"url": "data/cars.json"},
  "mark": "rect",
  "encoding": {
    "opacity": {
      "type": "nominal",
      "field": "Origin",
      "scale": {
        "domain": ["Europe", "Japan", "USA"],
        "range": [1, 0.1, 1],
        "type": "ordinal"
      }
    },
    "y": {"type": "ordinal", "field": "Origin"},
    "x": {"aggregate": "count", "type": "quantitative"}
  }
}
```
![visualization - 2020-02-27T060949 012](https://user-images.githubusercontent.com/781659/75452827-c613bb80-5927-11ea-9931-f711557e1ab3.png)

**Comment by pgorczak** [comment]
Oh wow I didn't realize that there was this intermediate compilation step. Thanks for pinning down the issue so quickly. I've opened an issue over at Vega-Lite (https://github.com/vega/vega-lite/issues/5982) like you suggested.
