### ISSUE TITLE
Question: Plotting different datasets in a subplots

### ISSUE THREAD

**Issue by bapungiri** [altair-viz/altair#1999]
Is their a way one can plot independent datasets in a grid like subplots. Imagine I have 5 x 3 grid, but each subplot will be occupied by an independent dataset plotted by iterating over a loop. I know that one way to do this would be to merge the datasets into one and then using the facet property to make the grid. But can merging datasets be avoided ?

Thanks for this amazing package.

**Comment by jakevdp** [comment]
You can concatenate charts with different datasets:
```python
import altair as alt
import pandas as pd

df1 = pd.DataFrame({
    'a': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'b': [28, 55, 43, 91, 81, 53, 19, 87, 52]
})

df2 = pd.DataFrame({
    'x': ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I'],
    'y': [45, 76, 54, 48, 87, 67, 69, 46, 55]
})

chart1 = alt.Chart(df1).mark_bar().encode(
    x='a',
    y='b'
)

chart2 = alt.Chart(df2).mark_bar().encode(
    x='x',
    y='y'
)

alt.concat(chart1, chart2)
```
![visualization - 2020-02-28T203920 193](https://user-images.githubusercontent.com/781659/75600920-683bbc80-5a6a-11ea-93de-ded9916bfacf.png)

**Comment by bapungiri** [comment]
Yeah this is convenient for few datasets. What i meant was if I have 15 of such datasets, then putting all those charts together using alt.concat will be cumbersome and also won't be in a grid like layout.

**Comment by jakevdp** [comment]
In a perfect world, what API would you want to exist for this use case?

**Comment by bapungiri** [comment]
Yeah I was just wondering if that was at all possible and to avoid modifying my the existing datasets. Something like putting all the chart objects in a list 'X' and then using an argument such as alt.concat(X, row=3, col=4). But anyway I can work around that.

Thanks for your prompt response.

**Comment by jakevdp** [comment]
Yeah, you can do that:
```python
alt.concat(*X, columns=4)
```

**Comment by bapungiri** [comment]
Oh cool. Thant answers my question. Thanks.
