### ISSUE TITLE
Minor suggestion for troubleshooting missing nbextension calls

### ISSUE THREAD

**Issue by cscheid** [altair-viz/altair#200]
Hey folks,

I stumbled on the installation of Altair because (surprise!) I didn't fully read the instructions. I `pip install notebook altair`ed and went to town. Of course that didn't work, and of course I should have read the documentation warnings about typing

```
jupyter nbextension enable vega --py --sys-prefix
```

The issue I have is that without typing this, there's no visible error message anywhere in the notebook console or web client. It took me quite a while to check the javascript console for errors, which was what led me to the right place.

In order to make other similarly reading-challenged people's lives easier, would it be possible to detect the lack of the nbextension somewhere, and pop a big honking alert on the notebook that says "You need to enable the extensions! Go read the docs" or something like that?

It's possible that even adding a minor troubleshooting guide would suffice. But I confess to being minorly annoyed at the lack of visible error messages - it makes it hard to even use google for troubleshooting.

(It's possible that this is supposed to be a jupyter bug report - but it seems like this only bites people when they try fancy extensions, so it hurts Altair too.)

**Comment by jakevdp** [comment]
Thanks, I think this is a good suggestion. I'll take a look at how to print such a warning.

**Comment by jakevdp** [comment]
@ellisonbg what do you think about this? It should probably be added to http://github.com/vega/ipyvega

Is there a good way to list installed nbextensions? I tried looking at the code behind ``jupyter nbextension list``, but for some reason it seems to miss the ``jupyter-vega`` extension that I have installed, so something is not working there.

**Comment by ellisonbg** [comment]
I can have a look at this for 1.3 and the new jupyterlab_vega approach.
