### ISSUE TITLE
Plot discontinuous line chart with Rows

### ISSUE THREAD

**Issue by danhamill** [altair-viz/altair#2001]
How can I specify the `impute` argument `keyvals` for the Y variable when the time series in `df` are separated using a color?

```python
import pandas as pd
import numpy as np
import altair as alt
alt.renderers.enable('altair_viewer')

drng1 = pd.date_range('2018-01-01','2020-08-03') 
drng1 = np.append(drng1[:30], drng1[60:])

drng2 = pd.date_range('2018-01-01','2020-08-03') 

df1 = pd.DataFrame({'date':drng1})
df1.loc[:,'site'] = 'site1'
df1.loc[:,'ds'] = 'Data Source 1'

df2 = pd.DataFrame({'date':drng2})
df2.loc[:,'site'] = 'site2'
df2.loc[:,'ds'] = 'Data Source 2'

df = pd.concat([df1,df2], sort=True)

keyvals = pd.date_range(df.date.min(), df.date.max(), freq='MS').astype(int) // 1000000  
chart4 = alt.Chart(df).mark_line(strokeWidth = 3).encode(
    x = alt.X('date:T', 
              scale= alt.Scale(domain= ['2018-01-01','2021-01-01']), 
              axis = alt.Axis(title=None)),
    y = alt.Y('site:N', 
              axis=alt.Axis(title=None, labelFontSize=10, labelPadding = 1),
              impute = alt.ImputeParams(value=None, keyvals=list(keyvals))),
    color=alt.Color('site', legend=None, 
                    scale = alt.Scale(domain=list(df.site.unique()), range= ['blue' for i in df.site.unique()])),
    row = alt.Row('ds', spacing = 10, 
                  header =alt.Header(title=None))
    ).properties( width = 400).resolve_scale(y = 'independent')

chart4.display()
```

![visualization](https://user-images.githubusercontent.com/11522898/75790623-72470f00-5d39-11ea-9ba7-2b3d5c21af0d.png)

Also, I am not sure why there is a `null` site and `undefined` row at the top of the chart.

**Comment by jakevdp** [comment]
It's not clear to me what your desired outcome is, but the reason you have a null site is that you are imputing values of ``site`` without imputing values of ``ds`` in the same row, so ``ds`` is set to null.

Can you describe the chart you are hoping to see?

**Comment by danhamill** [comment]
I am hoping to see a line chart with two rows (`Data Source 1` and `Data Source 2`).  Within each row, there is one tick (`site1`, `site2`). The line for `site1` will be horizontal, with data spanning from `'2018-01-01'` to `'2020-08-30'` with a discontinuity from `'2008-01-31' to `'2018-03-01'. The line (also horizontal) for `site2` is continuous from `'2018-01-01'` to `'2020-08-30'` 

I am not exactly sure how to do this `altair` since I am plotting a nominal y variable.  In matplotlib, I would do:

```
import matplotlib.pyplot as plt

df.loc[:,'val'] = df.site.map({'site1':1,'site2':1.2})

fig, ax = plt.subplots()

for name, group in df.groupby('site'):
    idx = pd.date_range(group.date.min(), group.date.max())
    group = group.set_index('date')
    group = group.reindex(idx, fill_value = np.nan)
    group = group.reset_index()
    ax.plot_date('index','val', data = group, label=name)
    
plt.yticks(np.arange(2)+1)
ax.set_yticklabels(df.site.unique())
```

![Figure_5](https://user-images.githubusercontent.com/11522898/75805630-2fdcfc80-5d50-11ea-87a1-15eee71c24b4.png)

**Comment by jakevdp** [comment]
Altair is similar to matplotlib, in that if you have a quantitative y-axis and the y-value is NaN, then the line breaks. In Altair, you could do something like this:
```python
alt.Chart(df).transform_calculate(
    y='0'  
).transform_impute(
    'y', key='date', value=None, groupby=['ds', 'site']
).mark_line().encode(
    x='date:T',
    y='y:Q',
    row='ds:N',
    color='site:N'
).properties(height=50)
```
![visualization (69)](https://user-images.githubusercontent.com/781659/75811969-3ebcb280-5d42-11ea-858a-d7ac90639c09.png)

**Comment by danhamill** [comment]
Thanks.  I have to admit, I am still very confused about anything that uses `transform_*`.  

Is there a way to change the tick label 0 to its nominal name?

**Comment by jakevdp** [comment]
You could hide the axis if you want:
```python
alt.Chart(df).transform_calculate(
    y='0'  
).transform_impute(
    'y', key='date', value=None, groupby=['ds', 'site']
).mark_line().encode(
    x='date:T',
    y=alt.Y('y:Q', axis=None),
    row='ds:N',
    color='site:N'
).properties(height=50)
```
![visualization (70)](https://user-images.githubusercontent.com/781659/75815313-09b35e80-5d48-11ea-8088-286ab5916a5b.png)

**Comment by jakevdp** [comment]
Is what you're after something like a [Gantt chart](https://altair-viz.github.io/gallery/gantt_chart.html)? If so, it might be easier to express your data as start and endpoints, rather than relying on missing data to separate connected sequences.

**Comment by danhamill** [comment]
That is an interesting suggestion.  I haven't considered that before in this context.

I am creating this chart to visualize the temporal coverage of precipitation observations at various weather stations.   I will think about how I could reduce my data into an even tidier before I could encode these data in Gantt chart.

Thanks!

**Comment by danhamill** [comment]
Moving forward with the Gantt chart idea, here is a modified example with function to calculate start and end dates of each duration of continuous (i.e. daily) precip observations:

```
import pandas as pd
import numpy as np
import altair as alt
alt.renderers.enable('altair_viewer')

drng1 = pd.date_range('2018-01-01','2020-08-03') 
drng1 = np.append(drng1[:30], drng1[60:])

drng2 = pd.date_range('2018-01-01','2020-08-03') 

df1 = pd.DataFrame({'date':drng1})
df1.loc[:,'site'] = 'site1'
df1.loc[:,'ds'] = 'Data Source 1'
df1.loc[:,'ppt'] = 1

df2 = pd.DataFrame({'date':drng2})
df2.loc[:,'site'] = 'site2'
df2.loc[:,'ds'] = 'Data Source 2'
df2.loc[:,'ppt'] = 1

df = pd.concat([df1,df2], sort=True)


precip_dur = pd.DataFrame()
for name, group in df.groupby('site'):
    # if name == 'USW00094143':
    #     break

    idx = pd.date_range(group.date.min(), group.date.max())
    group = group.set_index('date')
    
    group = group.reindex(idx, fill_value=np.nan)
    group.index.name = 'date'
    group = group.reset_index()

    
    group.loc[:,('site','ds')] = group.loc[:,('site','ds')].fillna(method='ffill')
    
    group.loc[~group.ppt.isna(), 'ppt'] = 1
    group.loc[group.ppt.isna(), 'ppt'] = 0
    
    group.loc[:,'val_grp']  = (group.ppt.astype(bool)).astype(int)
    group.loc[:,'val_grp'] = (group.val_grp.diff(1) != 0).astype('int').cumsum()
    

    res = pd.DataFrame({'BeginDate' : group.groupby('val_grp')['date'].first(), 
              'EndDate' : group.groupby('val_grp')['date'].last(),
              'Consecutive' : group.groupby('val_grp').size(),
              'site': group.groupby('val_grp').site.first(),
              'ds': group.groupby('val_grp').ds.last()
                  }
                       ).reset_index(drop=True)
    precip_dur = pd.concat([precip_dur, res])
```
Where `precip_dur` contains the start and end dates of continious obserbations for each `site` where daily observations were made.  

```python
alt.Chart(precip_dur).mark_bar().encode(
    x=alt.X('BeginDate', axis = alt.Axis(title=None)),
    x2='EndDate',
    y='site',
    color='ds'
)       
```

![gantt_Chart](https://user-images.githubusercontent.com/11522898/75825482-76901e00-5d73-11ea-8eab-92f377a4d353.png)

```python 
alt.Chart(df).transform_calculate(
    y='0'
).transform_impute(
    'y', key='date', value=None, groupby=['ds', 'site']
).mark_line().encode(
    x='date:T',
    y=alt.Y('y:Q', axis=None),
    row=alt.Row('site:N', header=alt.Header(title=None, labelAngle=0), spacing=0),
    color=alt.Color('ds:N')
).properties(height=50).configure_legend(title=None)
```
![imputeed_time_Sereis](https://user-images.githubusercontent.com/11522898/75825497-7d1e9580-5d73-11ea-9f2f-9c4983f11b92.png)


Any ideas why they don't appear the same?

**Comment by jakevdp** [comment]
Your ``precip_dur``  dataframe appears to include start/end points of the null stretches, which is why they're filled-in.

If reshaping your data is proving challenging, it might be cleaner to display the data directly as a heatmap:
```python
alt.Chart(df).mark_rect().encode(
    x='yearmonthdate(date):T',
    y='ds:N',
    color='site:N'
).properties(width=600)
```
![visualization (71)](https://user-images.githubusercontent.com/781659/75828625-1b553000-5d61-11ea-900b-892d6dca0c5d.png)

**Comment by danhamill** [comment]
Great thanks.  The Gantt chart implementation is a lot more elegant and worked very well.
