### ISSUE TITLE
TypeError: 'dict' object is not callable with simple example

### ISSUE THREAD

**Issue by rpalloni** [altair-viz/altair#2003]
Hello, I'm trying to carry out the simplest example provided by docs but I'm getting this error (with all the example I try).
Any hint?
I'm on Ubuntu 18.04 / Python 3.7 / Altair 4.0.2

![altair_dict](https://user-images.githubusercontent.com/17080117/75925075-542bfc80-5e68-11ea-8faf-1cd3b8ffab58.png)

**Comment by jakevdp** [comment]
In the future, please paste your code into the question rather than pasting a screenshot.

It looks like you've registered and enabled an invalid theme. This code reproduces your error:
```python
import altair as alt
alt.themes.register('badtheme', {})
alt.themes.enable('badtheme')
alt.Chart('data.txt').mark_point()
```
To fix it, run
```python
alt.themes.enable('default')
```
To correctly register a theme, you should do
```python
def my_theme():
    return {}  # your theme dict
alt.themes.register('my_theme', my_theme)
```
