### ISSUE TITLE
Creating Tufte's range frames and box plots

### ISSUE THREAD

**Issue by souserge** [altair-viz/altair#2004]
I am interested in recreating the data visualizations from Edward R. Tufte's book "The visual display of quantitative information", like e.g. the range frame, a scatter plot in which the domain of the axes are used to present minimum and maximum values of the data. I was searching the Altair documentation and I could not find any way to tweak the domain in such a way to be capable of doing range frames.

An example of a matplotlib implementation can be found here:
https://github.com/juanshishido/tufte

**Comment by kanitw** [comment]
just turn scale.zero off, then hide axis ticks and grid?

**Comment by jakevdp** [comment]
Maybe something like this?
```python
import numpy as np
import pandas as pd
import altair as alt

df = pd.DataFrame({
    'x': np.random.randn(100),
    'y': np.random.randn(100)
})

alt.Chart(df).mark_point().encode(
    alt.X('x', scale=alt.Scale(zero=False)),
    alt.Y('y', scale=alt.Scale(zero=False)),
).configure_view(
    stroke=None
).configure_axisX(
    translate=20,
    grid=False,
    ticks=False
).configure_axisY(
    translate=-20,
    grid=False,
    ticks=False
)
```
![visualization - 2020-03-06T163223 933](https://user-images.githubusercontent.com/781659/76132473-11813600-5fc8-11ea-801b-a3c5f49bbe5f.png)

**Comment by souserge** [comment]
@jakevdp Thanks for the suggestion, visually it looks very similar, however, the purpose of the range frame is to clearly show the range of the data, i.e. the start of the domain line is exactly at the minimum value of the data, and the end is at the maximum.

**Comment by jakevdp** [comment]
You can set the axis domain to match the data range

**Comment by jakevdp** [comment]
Unfortunately, it looks like there is a [bug](https://github.com/vega/vega-lite/issues/6030) in axis translation at the moment.

**Comment by souserge** [comment]
@jakevdp Aha, I see, thank you very much for letting know!

**Comment by jakevdp** [comment]
So it looks like it's the ``offset`` property rather than the ``translate`` property that we'd use here:
```python
import numpy as np
import pandas as pd
import altair as alt

df = pd.DataFrame({
    'x': np.random.randn(100),
    'y': np.random.randn(100)
})

alt.Chart(df).mark_point().encode(
    alt.X('x',
      axis=alt.Axis(offset=40, grid=False, ticks=False),
      scale=alt.Scale(domain=[df.x.min(), df.x.max()], nice=False)
    ),
    alt.Y('y',
      axis=alt.Axis(offset=40, grid=False, ticks=False),
      scale=alt.Scale(domain=[df.y.min(), df.y.max()], nice=False)
    ),
).configure_view(
    stroke=None
)
```
![visualization - 2020-03-07T132100 769](https://user-images.githubusercontent.com/781659/76152637-7f843680-6076-11ea-9aff-d9a6dfa8969c.png)

**Comment by g3o2** [comment]
The solution in vl is to add layer of rule, text and tick marks to replace the built-in axis domain. After all, in Tufte’s book, the domain lines are described as being data themselves, so that this solution would be consistent. Unfortunately, due to having to add additional transforms for data processing, the said solution is also both more verbose and laborious than simply defining the scale and axis properties.

**Comment by souserge** [comment]
@jakevdp @g3o2 Thank you for the replies!

Yes, I thought to treat it as data and present it accordingly, and this is what I came up with at the end (albeit, without the ticks):
```python
import numpy as np
import pandas as pd
import altair as alt

df = pd.DataFrame({
    'x': np.random.randn(100),
    'y': np.random.randn(100)
})


def range_frame(df, x_prop, y_prop):
    data = alt.Chart(df).mark_point(color='black', filled=True, size=12).encode(
        alt.X(x_prop,
          axis=None
        ),
        alt.Y(y_prop,
         axis=None
        ),
    )
    
    x_min = df[x_prop].min()
    x_max = df[x_prop].max()
    
    y_min = df[y_prop].min()
    y_max = df[y_prop].max()
    
    margin_x = np.abs(x_max - x_min)*0.1
    margin_y = np.abs(y_max - y_min)*0.1
    
    x_domain_data = pd.DataFrame({
        'x': [x_min, x_max],
        'y': [y_min - margin_y, y_min - margin_y]
    })
    
    y_domain_data = pd.DataFrame({
        'x': [x_min - margin_x, x_min - margin_x],
        'y': [y_min, y_max]     
    })
    
    x_domain = alt.Chart(x_domain_data).mark_line(color='black', size=1).encode(
        alt.X('x', axis=None, scale=alt.Scale(zero=False, domain=(x_min, x_max))), 
        alt.Y('y', axis=None, scale=alt.Scale(zero=False, domain=(y_min, y_max)))
    )
    y_domain = alt.Chart(y_domain_data).mark_line(color='black', size=1).encode(
        alt.X('x', axis=None, scale=alt.Scale(zero=False, domain=(x_min, x_max))), 
        alt.Y('y', axis=None, scale=alt.Scale(zero=False, domain=(y_min, y_max)))
    )
    
    res = data + x_domain + y_domain

    return res.configure_view(
        stroke=None
    )

range_frame(df, 'x', 'y')
```
![visualization(2)](https://user-images.githubusercontent.com/15277406/76203520-74a8dd80-61ff-11ea-903b-9a6fbc8bc857.png)

I enjoy using Altair a lot, but perhaps, something more low-level would be more appropriate for such a use-case. Thanks once again for your help.

**Comment by jakevdp** [comment]
In seems like the solution in https://github.com/altair-viz/altair/issues/2004#issuecomment-596138725 is simpler than trying to construct your own axes from scratch.

**Comment by souserge** [comment]
@jakevdp  I've been exploring Altair lately, and I stumbled upon transforms – they're really convenient :)
