### ISSUE TITLE
altair datetime slider

### ISSUE THREAD

**Issue by TimIn2020** [altair-viz/altair#2008]
Hello, 

After playing around with altair, vega-lite and vega we are trying to create a graph with Datetime slider. It is not available in Altair itself, it only offers a single slider. 
We did get this example working: 
[altait plot with panel slider](https://towardsdatascience.com/how-to-build-a-time-series-dashboard-in-python-with-panel-altair-and-a-jupyter-notebook-c0ed40f02289 )
to manipulate the dataset outside of vega. Is it also possible to update signals (xmin & xmax) in a javascript sliders callback to let vega handle the data transformation?

**Comment by jakevdp** [comment]
Can you give an example of what you mean by a "Datetime slider"?

**Comment by TimIn2020** [comment]
Tnx for the quick reply. The idea is to show only the x values between the two timestamps. We can offcourse do this by manipulating the dataset in javascript and updating the view but ideally we would update signal values to let vega update the data (as is sone with a single slider in some examples). I have added both an image and working code example.  

![example_slider](https://user-images.githubusercontent.com/62019052/76318069-7052f200-62dd-11ea-8838-3e42e6d133d4.png)

code:
`
<!doctype html>
<html lang="en">
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

<meta charset="utf-8" />
  <title>jQuery UI Slider - Range slider</title>
  <link rel="stylesheet" href="https://code.jquery.com/ui/1.10.2/themes/smoothness/jquery-ui.css" />
  <script src="https://code.jquery.com/jquery-1.9.1.js"></script>
  <script src="https://code.jquery.com/ui/1.10.2/jquery-ui.js"></script>


  <script>
  $(function() {
    $( "#slider-range" ).slider({
      step: 1,
      range: true,
      min: new Date('2012-01-01T00:00:00').getTime(),
      max: new Date('2019-01-01T00:00:00').getTime(),
      values: [ new Date('2012-03-01T00:00:00').getTime(), new Date('2014-01-01T00:00:00').getTime() ],
      slide: function( event, ui ) {
        $( "#amount" ).val( (new Date(ui.values[ 0 ]).toLocaleString() ) + " - " + (new Date(ui.values[ 1 ])).toLocaleString() );
      }
    });
    $( "#amount" ).val( (new Date($( "#slider-range" ).slider( "values", 0 )).toLocaleString()) +
      " - " + (new Date($( "#slider-range" ).slider( "values", 1 ))).toLocaleString());
   $( "#test").val(new Date('2012-01-01T00:00:00').getTime())
  });
  </script>


</head>
<body>

<p>
  <label for="amount">Date range:</label>
  <input type="text" size="50" id="amount" style="border: 0; color: #f6931f; font-weight: bold;" />
</p>
  <div id="slider-range"></div> 
 
</body>
</html>
`

**Comment by mattijn** [comment]
Vega supports any valid [HTML input type](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input).

Meaning that you are also restricted to these types. 

If other types are required. You have to control your custom external input element using Vega signals without a binded input element. More info here: https://vega.github.io/vega/docs/signals/

**Comment by quantology** [comment]
The following works for me:
```python
df["date2"] = pd.to_datetime(df["date"]).dt.strftime("%Y-%m-%d")
data_start = df["date"].min()
data_end = df["date"].max()

range_start = alt.binding(input="date")
range_end = alt.binding(input="date")
select_range_start = alt.selection_single(name="select_range_start", fields=["date"], bind=range_start, init={"date": data_start})
select_range_end = alt.selection_single(name="select_range_end", fields=["date"], bind=range_end, init={"date": data_end})

alt.Chart(df).transform_filter(
  (datum.date2 >= select_range_start.date) & (datum.date2 <= select_range_end.date)
).add_selection(select_range_start, select_range_end).mark_line().encode(
  x="date:T",
  y="sum(views):Q",
  color="ISO:N"
)
```

It is important to copy the date column into a separate column (here: `date2`), if you are also encoding your date column as temporal. My best guess is that this is because the HTML date element's value is in string form (e.g. "2001-01-01"), which can compare to similar strings, but which doesn't interact well if the column has been coerced into a temporal type.

For min & max on those date selectors, see: https://github.com/altair-viz/altair/issues/2121

**Comment by jfoster17** [comment]
Is it possible to put a (single) date value on a slider within Altair? That is, suppose I want to recreate [the documentation example](https://altair-viz.github.io/user_guide/interactions.html#selection-values-in-expressions) but with dates of the x axis?

`import altair as alt
import pandas as pd
import numpy as np
from datetime import datetime

datelist = pd.date_range(datetime.today(), periods=100).tolist()

rand = np.random.RandomState(42)

df = pd.DataFrame({
    'xval': datelist,
    'yval': rand.randn(100).cumsum()
})

slider = alt.binding_range(name='cutoff:')
selector = alt.selection_single(name="SelectorName", fields=['cutoff'],
                                bind=slider,init={"cutoff": "2020-05-05"})

alt.Chart(df).mark_point().encode(
    x='xval',
    y='yval',
    color=alt.condition(
        alt.datum.xval < selector.cutoff,
        alt.value('red'), alt.value('blue')
    )
).add_selection(
    selector
)`

This doesn't work, and I can't specify the min/max/step in binding_range because:

`SchemaValidationError: Invalid specification

        altair.vegalite.v4.schema.core.BindRange->min, validating 'type'

        '2020-05-01' is not of type 'number'`

The use case is wanting to scrub back and forth between an actual and a predicted time series. A slider seems like the natural interface. A poor workaround is to cast all my dates into offsets from a starting date (so they are integers). This would be okay if I could still display the dates on the chart somehow. 

TimIn2020's solution to do the filtering externally in Pandas or ipywidgets makes the interaction non-smooth since you have to filter the dataset each time.

**Comment by jakevdp** [comment]
Vega-Lite's native range inputs cannot handle dates, but you can do something similar if you're willing to work with timestamps:
```python
import altair as alt
import pandas as pd
import numpy as np
from datetime import datetime

datelist = pd.date_range(datetime.today(), periods=100).tolist()

rand = np.random.RandomState(42)

df = pd.DataFrame({
    'xval': datelist,
    'yval': rand.randn(100).cumsum(),
})

def timestamp(t):
  return pd.to_datetime(t).timestamp() * 1000

slider = alt.binding_range(name='cutoff:', min=timestamp(min(datelist)), max=timestamp(max(datelist)))
selector = alt.selection_single(name="SelectorName", fields=['cutoff'],
                            bind=slider,init={"cutoff": timestamp("2020-06-20")})

alt.Chart(df).mark_point().encode(
    x='xval',
    y='yval',
    color=alt.condition(
        'toDate(datum.xval) < SelectorName.cutoff[0]',
        alt.value('red'), alt.value('blue')
    )
).add_selection(
    selector
)
```

**Comment by jfoster17** [comment]
Thanks -- that's a big improvement. Relatedly -- is there any way to suppress the slider so the value isn't displayed? Or to make the slider control larger so it is the same size as the figure? (I realized these are probably more Vega questions than Altair questions).

**Comment by jakevdp** [comment]
All these kinds of tweaks to slider display would have to be done via CSS

**Comment by kennybui-data-ai** [comment]
> The following works for me:
> 
> ```python
> df["date2"] = pd.to_datetime(df["date"]).dt.strftime("%Y-%m-%d")
> data_start = df["date"].min()
> data_end = df["date"].max()
> 
> range_start = alt.binding(input="date")
> range_end = alt.binding(input="date")
> select_range_start = alt.selection_single(name="select_range_start", fields=["date"], bind=range_start, init={"date": data_start})
> select_range_end = alt.selection_single(name="select_range_end", fields=["date"], bind=range_end, init={"date": data_end})
> 
> alt.Chart(df).transform_filter(
>   (datum.date2 >= select_range_start.date) & (datum.date2 <= select_range_end.date)
> ).add_selection(select_range_start, select_range_end).mark_line().encode(
>   x="date:T",
>   y="sum(views):Q",
>   color="ISO:N"
> )
> ```
> 
> It is important to copy the date column into a separate column (here: `date2`), if you are also encoding your date column as temporal. My best guess is that this is because the HTML date element's value is in string form (e.g. "2001-01-01"), which can compare to similar strings, but which doesn't interact well if the column has been coerced into a temporal type.
> 
> For min & max on those date selectors, see: #2121

this is a great solution. the slider with javascript timestamp is not human readable so this is the best alternative. you get a date dropdown and can select the start/end dates.

**Comment by joelostblom** [comment]
@TimIn2020 I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Comment by fredgi123** [comment]
A last question: do you know how to encode text on top of the chart with slider? that is adding a label. I tried the mark_text() encoding and then concatenation chart+text but it does not work, thank you
