### ISSUE TITLE
Line Chart with Custom Confidence Interval

### ISSUE THREAD

**Issue by benjcabalona1029** [altair-viz/altair#2012]
Suppose i have the data frame below:

![Selection_101](https://user-images.githubusercontent.com/55730940/76497540-25b8ad80-6476-11ea-8cca-7f1a34adbff5.png)

I checked the [documentation](https://altair-viz.github.io/gallery/line_with_ci.html) but it's only based on a single column. 

Reproducible code:

```python
x = np.random.normal(100,5,100)
data = pd.DataFrame(x)
epsilon = 10
data.columns = ['x']
data['lower'] = x - epsilon
data['upper'] = x + epsilon
data

```

**Comment by jakevdp** [comment]
Answered on StackOverflow: https://stackoverflow.com/a/60654627/2937831
