### ISSUE TITLE
Raw Color Values Break Specified Sort Order

### ISSUE THREAD

**Issue by dbk123** [altair-viz/altair#2013]
I am creating a horizontal bar chart and would like to specify the color of each bar.  When following the example described under 'Raw Color Values' the changes in the color bar take effect, however, the specified sort order of the bars is no longer working.  Here is a code snippet:

```python
alt.Chart(df).mark_bar().encode(
    x = 'Deaths',
    y = alt.Y('Country/Region', sort = '-x'),
   color = alt.Color('Color', scale = None)
)
```

Where 'Color' is a column in the dataframe containing a string with a hex color specification.

Thanks!

(Sorry the formatting of my code got trashed...)

**Comment by jakevdp** [comment]
Can you provide a complete example of the error? I tried to reproduce the error by creating some data, and it appears to be working as expected:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'Color': ['red', 'orange', 'yellow', 'green', 'blue'],
    'Country/Region': ['A', 'B', 'C', 'D', 'E'],
    'Deaths': [1, 4, 2, 5, 3],
})

alt.Chart(df).mark_bar().encode(
    x = 'Deaths',
    y = alt.Y('Country/Region', sort = '-x'),
   color = alt.Color('Color', scale = None)
)
```
![visualization - 2020-03-14T151226 696](https://user-images.githubusercontent.com/781659/76691252-3a2bb000-6606-11ea-8221-3bbdbc98495a.png)

**Comment by dbk123** [comment]
Hi Jake,

Here is an example that isn't working.  I believe that the text overlay layer is what is screwing up the sort order (sorry I didn't mention that in my first post - I was trying to keep things as simple as possible).


testDf = pd.DataFrame({
    'Country/Region': ['China', 'France', 'Italy', 'US'],
    'Color': ['#d62728', '#d62728', '#d62728', '#1f77b4'],
    'Total Deaths': [3180, 1266, 133, 8513],
})

bars = alt.Chart(testDf).mark_bar().encode(
    x = 'Total Deaths',
    y = alt.Y('Country/Region', sort = '-x'),
    color = alt.Color('Color', scale = None)
).properties(width = 800, height = 300, title = 'Ten Countries with the Greatest Death Toll')

text = bars.mark_text(
    align = 'left',
    baseline = 'middle',
    dx = 3
).encode(
    text = 'Total Deaths:Q'
)

bars + text

**Comment by jakevdp** [comment]
It looks like some kind of renderer error having to do with merging the sorted domains of the two layers (you can see this in the warning it generates:
```
[Warning] Domains that should be unioned has conflicting sort properties. Sort will be set to true.
```
I don't understand what the conflict is, or why it only arises in the presence of a null color scale.

In any case, as a workaround, you can set the scale resolve to independent so that the scales won't be merged. For example:
```python
import altair as alt
import pandas as pd

testDf = pd.DataFrame({
    'Country/Region': ['China', 'France', 'Italy', 'US'],
    'Color': ['#d62728', '#d62728', '#d62728', '#1f77b4'],
    'Total Deaths': [3180, 1266, 133, 8513],
})

bars = alt.Chart(testDf).mark_bar().encode(
    x = 'Total Deaths',
    y = alt.Y('Country/Region', sort='-x'),
    color = alt.Color('Color', scale = None)
).properties(width = 800, height = 300, title = 'Ten Countries with the Greatest Death Toll')

text = bars.mark_text(
    align = 'left',
    baseline = 'middle',
    dx = 3
).encode(
    text = 'Total Deaths:Q',
    y = alt.Y('Country/Region', sort='-x', axis=None),
)

(bars + text).resolve_scale(y='independent')
```
![visualization - 2020-03-14T210646 317](https://user-images.githubusercontent.com/781659/76695077-ba1e3e00-6637-11ea-9447-36fecd192836.png)

**Comment by dbk123** [comment]
Awesome.  Thanks for your rapid response and providing the work around!

Thanks!
