### ISSUE TITLE
Setting an independent x-axis with different domain when using bins

### ISSUE THREAD

**Issue by firasm** [altair-viz/altair#2015]
Often there are multiple variables in your dataframe each with different ranges, so you want to show the distribution as a histogram with different bin extents (sometimes with the same bin sizes, and sometimes not). 

Here is an example where it would be useful to use the same bin size, but different bin extents

```
import numpy
import altair as alt
import pandas as pd
import random
from vega_datasets import data

list1 = [random.randint(0, 100) for x in range(100)]
list2 = [random.randint(100, 200) for x in range(100)]
list3 = [random.randint(200, 300) for x in range(100)]

xscale = alt.Scale(domain=(40, 300))

df = (
    pd.DataFrame([list1, list2, list3])
    .T.rename(columns={0: "A", 1: "B", 2: "C"})
    .melt()
)

alt.Chart(df).mark_bar().encode(
    alt.X("value", bin=alt.Bin(extent=[0, 300], step=10), scale=alt.Scale(zero=False)),
    alt.Y("count()"),
    alt.Row("variable"),
).resolve_scale(x='independent')
```

Here's what you get:

![visualization-24](https://user-images.githubusercontent.com/2507459/76707698-ae219300-66ae-11ea-9c98-dd3ad0dfe31a.png)

What I'd like instead is the first chart to have a range from [0,100] the second from [100,200], and the third from [200,300]. [This example](https://github.com/altair-viz/altair/issues/428#issuecomment-397768450) works, when there is no binning involved.

I've gotten as far as getting independent x-axes, but of course, since we're using `bins` the typical scale properties (like `zero=False`) will be ignored as shown in the [marginal_hist](https://altair-viz.github.io/gallery/scatter_marginal_hist.html) example.

Is there a preferred way to do this in Altair?

I can easily just create three different Chart objects - manually specify bin extents for each one and then `voncat` them, but this has a very `matplotlib` feel to it...

**Comment by firasm** [comment]
FYI, here's the ugly solution in case it benefits someone:

```
chart1 = (
    alt.Chart(df[df["variable"] == "A"])
    .mark_bar()
    .encode(alt.X("value", bin=alt.Bin(extent=[0, 100], step=10)), alt.Y("count()"))
)

chart2 = (
    alt.Chart(df[df["variable"] == "B"])
    .mark_bar()
    .encode(alt.X("value", bin=alt.Bin(extent=[100, 200], step=10)), alt.Y("count()"))
)

chart3 = (
    alt.Chart(df[df["variable"] == "C"])
    .mark_bar()
    .encode(alt.X("value", bin=alt.Bin(extent=[200, 300], step=10)), alt.Y("count()"))
)

alt.vconcat(chart1, chart2, chart3)
```

![visualization-25](https://user-images.githubusercontent.com/2507459/76707935-600d8f00-66b0-11ea-87fb-9a1528e57657.png)

**Comment by jakevdp** [comment]
The only way to have different bin parameters for each facet is to use concatenation of separate bin operations. For your data, I would probably do something like this:
```python
alt.vconcat(*(
  alt.Chart(df.query(f'variable == {var!r}'))
    .mark_bar()
    .encode(
        alt.X("value", bin=alt.Bin(step=10)),
        alt.Y("count()")
    )
  for var in sorted(df.variable.unique())
))
```
Or, if you want to use a single dataframe and do the filtering within the chart grammar:
```python
alt.vconcat(
  *(alt.Chart()
      .transform_filter(alt.datum.variable == var)
      .mark_bar()
      .encode(
        alt.X("value", bin=alt.Bin(step=10)),
        alt.Y("count()")
      )
    for var in sorted(df.variable.unique())
  ),
  data=df
)
```

**Comment by firasm** [comment]
amazing, thanks! closing.
