### ISSUE TITLE
Fickering chart when using transform_filter and transform_regression together

### ISSUE THREAD

**Issue by arkanoid87** [altair-viz/altair#2016]
I've just added a simple selection_interval brush over the transform_regression altair example code.
I get a chart where the "*polynomial_fit" layers would appear only if one of the two edges of the filter is exactly on one point of "base" layer, creating a flickering effect when moving the filter.

I'm using altair 4.0.1 from conda-forge

```
alt.renderers.set_embed_options(actions=False)

degree_list = [1,3,5]

altair_data = data[["datetime", "total"]].rename({"data":"x", "total":"y"}, axis=1)

brush = alt.selection_interval(encodings=['x'])

base = alt.Chart(altair_data).mark_point(color="black").encode(
    alt.X("x"),
    alt.Y("y")
)

polynomial_fit = [
    base.transform_filter(brush).transform_regression(
        "x", "y", method="poly", order=order, as_=["x", str(order)]
    )
    .mark_line()
    .transform_fold([str(order)], as_=["degree", "y"])
    .encode(alt.Color("degree:N"))
    for order in degree_list
]

alt.layer(base, *polynomial_fit).add_selection(
    brush
)
```

**Comment by jakevdp** [comment]
What is ``.cc()``?

**Comment by arkanoid87** [comment]
that was a wrong copypase, my fault, sorry

s/cc/transform_regression

**Comment by jakevdp** [comment]
This looks like a bug in the Vega-Lite renderer. I've reported it upstream.

**Comment by joelostblom** [comment]
Closing since this is tracked in https://github.com/vega/vega-lite/issues/6121 and need to be fixed in Vega-Lite rather than in Altair.
