### ISSUE TITLE
Controlling colormap and scale on chloropleth plots

### ISSUE THREAD

**Issue by dbk123** [altair-viz/altair#2017]
I am trying to create a chloropleth map showing values of a parameter for just a few states.  I can create a map for just one state using:

```python
import altair as alt
from vega_datasets import data

counties = alt.topo_feature(data.us_10m.url, 'counties')
source = data.unemployment.url

stateMap =(
    alt.Chart(counties)
    .mark_geoshape(
        stroke='black',
        strokeWidth=1
    )
    .transform_lookup(lookup='id', from_=alt.LookupData(source, 'id', ['rate']))
    .encode(color = 'rate:Q')
    .transform_calculate(state_id = "(datum.id / 1000)|0")
    .transform_filter(
        (alt.datum.state_id)==33)
)
stateMap
```

This produces 
<img width="415" alt="g2" src="https://user-images.githubusercontent.com/16540538/76857882-bc95b900-682c-11ea-97bd-9d6ca090bdb5.png">

Which is great.  However, I can't figure out how to change the colormap and set the scale of the colormap so that maps of multiple states will use the same scale.

Any help greatly appreciated!

**Comment by jakevdp** [comment]
The easiest way is to concatenate charts together, in which case the color scale will be shared automatically. For example:
```python
import altair as alt
from vega_datasets import data

counties = alt.topo_feature(data.us_10m.url, 'counties')
source = data.unemployment.url

stateMap1 =(
    alt.Chart(counties)
    .mark_geoshape(
        stroke='black',
        strokeWidth=1
    )
    .transform_lookup(lookup='id', from_=alt.LookupData(source, 'id', ['rate']))
    .encode(color = 'rate:Q')
    .transform_calculate(state_id = "(datum.id / 1000)|0")
    .transform_filter(
        (alt.datum.state_id)==33)
)

stateMap2 = (
    alt.Chart(counties)
    .mark_geoshape(
        stroke='black',
        strokeWidth=1
    )
    .transform_lookup(lookup='id', from_=alt.LookupData(source, 'id', ['rate']))
    .encode(color = 'rate:Q')
    .transform_calculate(state_id = "(datum.id / 1000)|0")
    .transform_filter(
        (alt.datum.state_id)==34)
)

alt.concat(stateMap1, stateMap2)
```
![visualization - 2020-03-17T060430 176](https://user-images.githubusercontent.com/781659/76858684-2e620880-6815-11ea-9062-0770730896f6.png)

If you want to manually specify the scheme and domain limits for the color scale, you can use the scale setting within the color encoding:
```
(
    alt.Chart(counties)
    .mark_geoshape(
        stroke='black',
        strokeWidth=1
    )
    .transform_lookup(lookup='id', from_=alt.LookupData(source, 'id', ['rate']))
    .encode(
        alt.Color('rate:Q', scale=alt.Scale(domain=[0, 0.2], scheme="viridis"))
    )
    .transform_calculate(state_id = "(datum.id / 1000)|0")
    .transform_filter(
        (alt.datum.state_id)==33)
)
```
![visualization - 2020-03-17T060715 536](https://user-images.githubusercontent.com/781659/76858909-90227280-6815-11ea-83e9-5861b77ae542.png)

where the available schemes are listed here: https://vega.github.io/vega/docs/schemes/

**Comment by dbk123** [comment]
Concatenation is a great trick - thanks!
