### ISSUE TITLE
Feature request: Validation for Scale scheme field

### ISSUE THREAD

**Issue by ivirshup** [altair-viz/altair#2018]
Hi! I recently spelled `"greys"` as `"grays"`, and hard time figuring out why my plot suddenly stopped working, but didn't throw an error. Here's an example:

```python
import altair as alt
from vega_datasets import data

iris = data.iris()

c = alt.Chart(iris).mark_circle().encode(x="sepalLength", y="sepalWidth")
```

Using the correct spelling:

```python
c.encode(color=alt.Color("petalWidth", scale=alt.Scale(scheme="greys")))
```

![image](https://user-images.githubusercontent.com/8238804/76928722-77f64480-6936-11ea-9de4-3ef964e5ec1a.png)

But with the wrong spelling:

```python
c.encode(color=alt.Color("petalWidth", scale=alt.Scale(scheme="grays")))
```

<img width="617" alt="image" src="https://user-images.githubusercontent.com/8238804/76929077-577aba00-6937-11ea-8e77-6d7d04ce06ea.png">

It would be nice if this could be validated and let me know what I did wrong instead of silently failing.

### Python package versions

```
altair  4.0.1
vega  3.1.0
```

**Comment by jakevdp** [comment]
The error is in the renderer, and is displayed in the Javascript console. I'm not sure how this error is avoiding the javascript ``catch()`` statement that usually displays Javascript errors in the notebook...

**Comment by ChiaLingWeng** [comment]
In Altair version 5.1.2
below is error message showing valid scheme option:
- One of ['blues', 'tealblues', 'teals', 'greens', 'browns', 'greys', 'purples', 'warmgreys', 'reds', 'oranges']
- One of ['turbo', 'viridis', 'inferno', 'magma', 'plasma', 'cividis', 'bluegreen', 'bluegreen-3', 'bluegreen-4', 'bluegreen-5',......]
- One of ['blueorange', 'blueorange-3', 'blueorange-4', 'blueorange-5', 'blueorange-6',......
- One of ['rainbow', 'sinebow']
- Of type 'object'

**Comment by joelostblom** [comment]
Thanks for pointing this out @ChiaLingWeng, closing this as completed
