### ISSUE TITLE
Silent failures for png backend and filesystem storage

### ISSUE THREAD

**Issue by ivirshup** [altair-viz/altair#2019]
```python
import altair as alt
import pandas as pd
import numpy as np

alt.data_transformers.enable('json')
alt.renderers.enable("png")
alt.data_transformers.disable_max_rows()

(
    alt.Chart(pd.DataFrame(np.random.randn(1000000, 2), columns=["x", "y"]))
    .mark_circle()
    .encode(x="x", y="y")
)
```

<img width="451" alt="image" src="https://user-images.githubusercontent.com/8238804/76930085-c8bb6c80-6939-11ea-8563-14a9ac610cbc.png">

If I don't use the transformer backend, this fails with a broken pipe error similar to #1771.

### Python package versions

```
altair  4.0.1
vega  3.1.0
```

**Comment by jakevdp** [comment]
The JSON transformer is incompatible with the PNG backend.

Use the default data transformer and the chart will work.

**Comment by ivirshup** [comment]
Thanks, good to know!

Could there be an error if a plot tries to render with this configuration?

**Comment by jakevdp** [comment]
Sure - pull requests welcome :)

**Comment by ivirshup** [comment]
Would this probably be a PR to `altair_saver`?

**Comment by jakevdp** [comment]
Note that there have been several duplicate issues over the years: #792, #1600, #1834...

The reason this hasn't been "fixed" is becuase it's difficult to fix this particular issue without causing issues for other use-cases; see https://github.com/altair-viz/altair/issues/1600#issuecomment-509481175 for example.

**Comment by joelostblom** [comment]
Closing this since https://github.com/altair-viz/altair_saver/pull/48 was merged.
