### ISSUE TITLE
Alignment of text differs for value 0

### ISSUE THREAD

**Issue by SorenLaursen** [altair-viz/altair#2021]
For a combined chart (https://towardsdatascience.com/the-confusion-matrix-visualized-e778584c8834, https://github.com/SorenLaursen/confusion_matrix_chart) I made text boxes, which work fine:
![image](https://user-images.githubusercontent.com/24542497/77059265-f4d8fb00-69d6-11ea-986d-f6a2a1a408b2.png)

Except if the number is 0:
![image](https://user-images.githubusercontent.com/24542497/77059375-1cc85e80-69d7-11ea-81a1-2a2d1174b044.png)

Here is the code:

`
    import pandas as pd
    import numpy as np
    import altair as alt
 
    def cf_text(CM, label, format, font_size, w_factor, dy_factor, sf):
        text = alt.Chart(df).mark_text(dy=dy_factor*sf, fontSize=font_size, color='black').encode(
            y=alt.Y('sum(value)', title=None, axis=None),
            text=alt.Text('sum(value)', format=format)
        ).properties(width=w_factor*sf, height=w_factor*sf) 
    
    return text
    
    df = pd.DataFrame({'value':[0]})

    cf_text(df, label='Yy', format='.0f', font_size=36, 
                      w_factor=10, dy_factor=5, sf=15)`

I cannot figure out how 0 can differ from other values in regard to alignment.

**Comment by jakevdp** [comment]
This is working as intended. You are setting the y encoding to the displayed value, and the axis is being adjusted to that displayed value. So when value is zero, the y-axis centers at zero, and the text mark is placed appropriately. When you set the value to 10, the y-axis range is 0 to 10, and the text mark is placed appropriately.

**Comment by jakevdp** [comment]
I suspect the function you're looking for is this:
```python
def cf_text(CM, label, format, font_size, w_factor, dy_factor, sf):
    text = alt.Chart(df).mark_text(fontSize=font_size, color='black').encode(
        text=alt.Text('sum(value)', format=format)
    ).properties(width=w_factor*sf, height=w_factor*sf) 

    return text
```

**Comment by SorenLaursen** [comment]
Thank you very much. You are spot on. 

(And for what it's worth: I really enjoy Altair, I consider it by far the best general purpose viz package for python and recommend it to everyone.)

**Comment by jakevdp** [comment]
Great - glad it's working!
