### ISSUE TITLE
Arrows to make vectors?

### ISSUE THREAD

**Issue by vcuspinera** [altair-viz/altair#2022]
Hi,
I have been looking for vectors in Altair but I didn't find any *mark* that could make them. By now, to 'plot' vectors I have been using **mark_line + mark_point** (triangle-shape) charts, but I think it is not very efficient.  
I found a previous issue related, open 2 years ago (#914) that has not a clear resolution. I was wondering if there is a better way (that the one I am using) to plot vectors with Altair, or if you are already working in this issue to make arrows for vectors possible.
This is an example of what I am doing:
```
# plot a vector in altair
# points
origin = [0,0]
vector1 = [3,-1]
vector2 = [2,3]

v = pd.DataFrame([origin, vector1, vector2], columns=['X','Y'])

# plots
lines = {}
for i in v.loc[v.index!=0].index:
    lines[i] = alt.Chart(v.loc[(v.index==0)|(v.index==i)]).mark_line().encode(
        alt.X('X', scale=alt.Scale(domain=(-4,4))), 
        alt.Y('Y', scale=alt.Scale(domain=(-4,4))))

heads = alt.Chart(v.loc[v.index!=0]).mark_point(
    shape='triangle', size=100, fill='royalblue').encode(x='X',y='Y')

lines[1] + lines[2] + heads
```
<img width="568" alt="image" src="https://user-images.githubusercontent.com/53915521/76712577-6e22d600-66d7-11ea-9d6c-9c846df2951c.png">

**Comment by jakevdp** [comment]
No there's currently no way to create arrows in Vega-Lite, and so there's no way to create arrows in Altair. I'm going to close this in favor of the original issue (#914)
