### ISSUE TITLE
Proper display of Altair charts when exporting to PDF

### ISSUE THREAD

**Issue by souserge** [altair-viz/altair#2024]
I have a Jupyter Notebook which has Altair charts in it for data visualisation. What I would like to do is to export the Notebook together with the charts to PDF using `nbconvert`. However, since Altair charts are JavaScript rendered, the exported document displays only `alt.Chart(...)` instead. Do you have any suggestions on how to set it up properly without having to export the chart to an image format and pasting it in the notebook?

**Comment by jakevdp** [comment]
Yes, you could change the renderer to include static views of the charts. Try installing [altair_saver](http://github.com/altair-viz/altair_saver/) along with either the selenium or node requirements, and then run this at the top of your notebook:
```python
alt.renderers.enable('altair_saver', fmts=["html", "svg"])
```
Using ``"png"`` in place of ``"svg"`` may also work.

**Comment by souserge** [comment]
Thanks, it works! The resulting PDF, however, cuts titles of the charts if they are longer than the chart itself, it is probably not a problem of the renderer. Do you have an idea what could solve this?
<img width="582" alt="image" src="https://user-images.githubusercontent.com/15277406/77156866-eeb34f00-6aa8-11ea-8920-fcec53fadcaa.png">

**Comment by souserge** [comment]
Ok, I found this to be an issue with the way inkscape exports to PDF. A solution would be to overwrite the default inkscape command used by nbconvert to include a `-D` flag which ensures the exported area is the entire drawing:

`jupyter nbconvert --to pdf --SVG2PDFPreprocessor.command="inkscape {from_filename} --export-pdf=\"{to_filename}\" -D" <your_notebook_name>`

**Comment by andyreagan** [comment]
following these suggestions, I got a version that's fully working too.

here's a description of the process from end-to-end if anyone finds this thread too: https://github.com/andyreagan/papermill-altair-pdf

**Comment by yubrshen** [comment]
I have a chart that is rather long, and it must be displayed on multiple pages to be viewed clearly. But with the default settings, it is displayed on one single page, thus it's too small to see.
This problem only happens with exporting to PDF, to HTML, it's no problem.

**Comment by yubrshen** [comment]
> Ok, I found this to be an issue with the way inkscape exports to PDF. A solution would be to overwrite the default inkscape command used by nbconvert to include a `-D` flag which ensures the exported area is the entire drawing:
> 
> `jupyter nbconvert --to pdf --SVG2PDFPreprocessor.command="inkscape {from_filename} --export-pdf=\"{to_filename}\" -D" <your_notebook_name>`
> 
> Tested with inkscape 0.92.1, the 1.0 version might have different flags.

What should be the substitute values of {from_filename} and {to_filename}? A concrete example would be appreciated.

**Comment by franzhaas** [comment]
With the release 5.2.0 the way how graphs are saved changed...

For me using altair 5.2.0 this worked.:

`alt.renderers.enable('png')`

Best regards,
Franz

**Comment by jonmmease** [comment]
Thanks for report @franzhaas. For context, as of version 5.2.0 Vega-Altair's PDF export (along with SVG and PNG) is powered by [vl-convert](https://github.com/vega/vl-convert). Glad to hear it's working well for you!
