### ISSUE TITLE
Support blend-mode in mark properties

### ISSUE THREAD

**Issue by korakot** [altair-viz/altair#2030]
New vega and vega-lite now support blend-mode

https://vega.github.io/vega-lite/docs/mark.html#color

So, I try it with

```python
alt.Chart(stocks).mark_line(blend='multiply').encode(
  x='date:T',
  y='price',
  color='symbol'
).interactive()
```
But it gives an error.

        altair.vegalite.v4.schema.core.MarkDef, validating 'additionalProperties'

        Additional properties are not allowed ('blend' was unexpected)

**Comment by jakevdp** [comment]
The blend mode was introduced in Vega-Lite 4.6; The current Altair release is based on Vega-Lite 4.0. You'll have to wait until the next release of Altair to use blend mode.

**Comment by korakot** [comment]
Would it work if I update Altair now?

    !pip install -e git+https://github.com/altair-viz/altair.git

**Comment by jakevdp** [comment]
No, you will have to wait for the next Altair release.

**Comment by jakevdp** [comment]
If you install from the branch in https://github.com/altair-viz/altair/pull/1990, you will be able to use blend mode.

**Comment by korakot** [comment]
Like this?

    !pip install -e git+https://github.com/jakevdp/altair.git@vl44

**Comment by jakevdp** [comment]
I think that will work, but be aware that that branch is in development and currently fails Altair's unit tests, so I wouldn't recommend using it for anything important.
