### ISSUE TITLE
How to build a classification boundary with Altair?

### ISSUE THREAD

**Issue by ccalobeto** [altair-viz/altair#2031]
Omitting the dot points of the data, how to build a classification boundary like this image?
<img width="445" alt="classifier decision boundary" src="https://user-images.githubusercontent.com/7624391/77260435-00862500-6c56-11ea-8ba0-dffdf141b564.png">

**Comment by joelostblom** [comment]
@ccalobeto Please see https://github.com/altair-viz/altair/issues/2348#issuecomment-735243664 for how to create a shaded region in Altair.

**Comment by joelostblom** [comment]
A general example was added in #3256. A more elaborate support for decision boundaries in particular could become available with [an imshow-like mark](https://github.com/altair-viz/altair/discussions/3125#discussioncomment-6589747), in which case we could do something like this in altair:

![image](https://github.com/altair-viz/altair/assets/4560057/86085f7d-ce01-43d9-b9f8-90802700dad5)
