### ISSUE TITLE
Hiding view border of specific charts within a Concatenated Chart

### ISSUE THREAD

**Issue by dzonimn** [altair-viz/altair#2032]
Hi, I'm trying to achieve a concatenated chart that has charts (obviously) with some image+titles above it. If I specify `.configure_view(strokeOpacity=0)` on the desired chart, it's not possible as concat charts would rather you specify top-level configurations at the end. If I specify it at the end, every single chart in the concatenation will be affected.

Perhaps I am approaching this the wrong way, so I think it would be more helpful to specify what I'm trying to do. I want to be able to generate a concatenated vertical chart something like this:
### 1st Image and Subtitle (encoded as a mark_image + mark_text layered chart, strokeOpacity=0)
1st Chart (with view strokeOpacity=1)
### 2nd Image and Subtitle (back to strokeOpacity=0)
2nd Chart (strokeOpacity=1)

and so on..

I have tried giving each of the chart objects a title, but that gives me no ability (to my knowledge) to append an image/icon to the front of the title. It also leads to strange alignment issues as the system I'm working with (Kibana) works on an older Vega spec that doesn't have text anchors, so I decided to try it this way. At worst, I will just set everything to `strokeOpacity=0` and call it a day. I am curious if there is some other way to approach this.

Other threads I've found that come close to, but not exactly on my problem are #976, but those use the top-level configuration and only involve 1 chart rather than a concatenation of them.

**Comment by jakevdp** [comment]
As far as I am aware, the only way to specify view properties is via the top-level configuration, which applies to all subcharts. Vega-Lite provides no way to control this with more granularity.

**Comment by dzonimn** [comment]
Yes, I thought it would've been helpful if I were able to adjust the strokeOpacity inside a view spec in `mark_text()` or on an encoding level, like I can with individual axes, but I guess if it isn't in the Vega-Lite spec, then it can't really be helped and I understand it might be more productive to see if anyone had requested that in the Vega-Lite github instead. Thanks anyway!

**Comment by dzonimn** [comment]
For anyone who is interested in more info, I think they added a [view configuration for layered charts](https://github.com/vega/vega-lite/pull/4463) last year and seemed to indicate they were going to allow that for concat/facet/repeat charts too, but for now, it is not possible to individual configure view for each concat/facet/repeat chart. Personally for my own use case, I will stick with completely borderless views for all my charts.

**Comment by eboddington** [comment]
Does anyone know if there's any update on this? I've not been able to find anything, but we're having exactly the same issue.
