### ISSUE TITLE
"TypeError: data type not understood" with dtype: string

### ISSUE THREAD

**Issue by Rik-de-Kort** [altair-viz/altair#2036]
Pandas 1.0.2
Altair 4.0.1

Altair will raise an error on being given a DataFrame contain string dtypes. Casting the string columns to object will work fine. Related to #1931 but seems like it's an easier fix. Will try to develop a PR today if I can find the right pieces of code.

Minimal reproducer follows. Uncomment the fourth line to get the expected result.
````python
import pandas as pd
import altair as alt
foo = pd.DataFrame({"a": ["foo", "bar", "baz"], "b": [4, 3, 2]})
foo["a"] = foo["a"].astype("string")
alt.Chart(foo).mark_bar().encode(x="a", y="b")
````

EDIT: It does work in 4.1.0dev0 since that already adds the checks for the dedicated string dtype in Pandas. Accordingly, I've resolved the problem by installing the dev version for now. Any hints on a release date?

**Comment by jakevdp** [comment]
This was fixed by https://github.com/altair-viz/altair/pull/1924, which will be part of the 4.1 release.
