### ISSUE TITLE
Is it possible to remove or change the label of a single selection menu.

### ISSUE THREAD

**Issue by janekg89** [altair-viz/altair#2039]
Hi,
thank you for the great library. 
I could not figure out how to change or remove the label of a dropdown menu. In the example below this would be "Country_of__Origin". Is it somehow possible?
Thank you in advance
Janek

```
input_dropdown = alt.binding_select(options=['Europe','Japan','USA'])
selection = alt.selection_single(fields=['Origin'], bind=input_dropdown, name='Country of ')
color = alt.condition(selection,
                    alt.Color('Origin:N', legend=None),
                    alt.value('lightgray'))

alt.Chart(cars).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color=color,
    tooltip='Name:N'
).add_selection(
    selection
)
```
![example](https://user-images.githubusercontent.com/5961300/77458939-3ca8b980-6dff-11ea-960b-b882aee63cf0.png)

**Comment by jakevdp** [comment]
Yes, you can pass whatever name you want to the ``alt.binding_select`` object, and it will be displayed beside the input element. For example:
```
input_dropdown = alt.binding_select(options=['Europe','Japan','USA'], name="Country")
```
If you don't provide a name, it will be automatically generated from the selection object.

**Comment by janekg89** [comment]
Can I also display the name without the input element? In the above example, I would like to display only "Country" without Origin.

**Comment by jakevdp** [comment]
I think the solution I recommended above does what you want. Here's a full code snippet:
```python
import altair as alt
from vega_datasets import data
cars = data.cars()

input_dropdown = alt.binding_select(options=['Europe','Japan','USA'], name="Country")
selection = alt.selection_single(fields=['Origin'], bind=input_dropdown)
color = alt.condition(selection,
                    alt.Color('Origin:N', legend=None),
                    alt.value('lightgray'))

alt.Chart(cars).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color=color,
    tooltip='Name:N'
).add_selection(
    selection
)
```
<img width="495" alt="Screen Shot 2020-03-25 at 10 20 25 AM" src="https://user-images.githubusercontent.com/781659/77566006-4aebe980-6e82-11ea-876e-c080b9df7b0b.png">

If you want to hide the label altogether, you can set it to a space (empty string is treated as a null label, and the default will be used):
```python
import altair as alt
from vega_datasets import data
cars = data.cars()

input_dropdown = alt.binding_select(options=['Europe','Japan','USA'], name=" ")
selection = alt.selection_single(fields=['Origin'], bind=input_dropdown)
color = alt.condition(selection,
                    alt.Color('Origin:N', legend=None),
                    alt.value('lightgray'))

alt.Chart(cars).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color=color,
    tooltip='Name:N'
).add_selection(
    selection
)
```
<img width="500" alt="Screen Shot 2020-03-25 at 10 20 09 AM" src="https://user-images.githubusercontent.com/781659/77566022-50493400-6e82-11ea-8efd-b488a7eff4cf.png">

**Comment by janekg89** [comment]
Yes, your solution is working for me. Thank you for the great library and support!
