### ISSUE TITLE
Disabling Export to Vega Option

### ISSUE THREAD

**Issue by eamonnmag** [altair-viz/altair#2040]
We have the use case where we don't want users accidentally clicking on export to vega (thinking it's internal to our org) and sending out data to the vega ui. Is there a way to disable this via environment variables or as a flag on installation?

**Comment by jakevdp** [comment]
You can hide the actions menu altogether using
```python
alt.renderers.set_embed_options(actions=False)
```
You can remove the link to the vega editor using:
```python
alt.renderers.set_embed_options(actions={"editor": False})
```
Other options are listed in the [vegaEmbed docs](https://github.com/vega/vega-embed#options) under "actions".

**Comment by eamonnmag** [comment]
Hi! This is great, but we wanted to disable on installation so that the disabling is not done by the user, but by us.

**Comment by jakevdp** [comment]
Altair doesn't provide that type of configuration. How much control do you have over the user's python environment? Can you define import hooks that are set by default for all users?

Also, I'm not entirely certain what the concern is: the vega editor runs entirely in your own browser frontend. Viewing a chart in the editor uses an [HTML5 postMessage](https://developer.mozilla.org/en-US/docs/Web/API/Window/postMessage) to send your data between browser windows; there is no passing of your data to any external service.

**Comment by keesterbrugge** [comment]
Hi @jakevdp , the concern I have is that once somebody is inside the vega editor they can easily create a shareable url, which represents a security risk. The url which contains sensitive data in compressed form may be logged by third parties when it is used. 


We can define import hooks that are set by default for all users. How would we then go about disabling the actions menu for all our users?

Thanks for your work on this awesome library.

**Comment by jakevdp** [comment]
If you're concerned about users having access to the data being visualized, Altair is not the right plotting package for you. It's fundamentally built around a model where the viewer's browser has access to the data.

If this is problematic for your use-case, I'd suggest a static plotting library like matplotlib.
