### ISSUE TITLE
Altair: Values are still imputed, even though the imputation should be deactivated

### ISSUE THREAD

**Issue by iameminmammadov** [altair-viz/altair#2041]
I am having a problem with altair interactive plots. Below is small part of the code.

`anomalies = alt.Chart(dat[dat['anomaly']==True]).mark_line(color='red').encode(x='X', y=alt.Y('col', impute=alt.ImputeParams(value=None))).interactive()
normal = alt.Chart(dat[dat['anomaly']==False]).mark_line(color='blue').encode(x='X',y=alt.Y('col', impute=alt.ImputeParams(value=None))).interactive()
display(alt.layer(anomalies, title='Title_of_the_plot'))`

The resulted graph is
![altair_viz](https://user-images.githubusercontent.com/24482886/77707152-ad380d80-6f9a-11ea-9909-e3beb9ae9251.png)

As it can be seen from the graph, the blue line overlaps red, which means that instead of there being a gap (which is filled by the red line), the values are interpolated.

**Comment by jakevdp** [comment]
Answered on StackOverflow: https://stackoverflow.com/questions/60877845/altair-values-are-still-imputed-even-though-they-should-be-deactivated/60879362#60879362
