### ISSUE TITLE
_repr_mimebundle_() error with jupyter lab and xpython

### ISSUE THREAD

**Issue by josephsmann** [altair-viz/altair#2042]
when attempting to plot
```
alt.Chart(pd.DataFrame({'a': [1, 2, 3], 'b':[4, 0, 9]})).mark_point().encode(
    x='a:Q',
    y='b:Q')
```

I get the error message 

---------------
TypeError                                 Traceback (most recent call last)
In  [11]:
Line 1:     points

TypeError: _repr_mimebundle_() missing 2 required positional arguments: 'include' and 'exclude'

---------------

with my "regular" kernel this would work. Also, xkernel gave no immediate complaints
when using pandas etc.

my config is:
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : not installed
ipython          : 7.13.0
ipykernel        : 5.2.0
jupyter client   : 6.1.1
jupyter lab      : 2.0.1
nbconvert        : 5.6.1
ipywidgets       : not installed
nbformat         : 5.0.4
traitlets        : 4.3.3
altair.            : 4.0.1

hope this helps...

**Comment by iameminmammadov** [comment]
Could you post the whole traceback of the error?

**Comment by jakevdp** [comment]
xpython does not pass the required ``include`` and ``exclude`` arguments to ``_repr_mimebundle_``. This is an xpython bug.

**Comment by jakevdp** [comment]
We could accommodate this sort of bug in non-standard ipython kernels in Altair by setting the default values to None here:

https://github.com/altair-viz/altair/blob/0a62fae7702c234c75fdf4d54817c1a670fcec5a/altair/vegalite/v4/api.py#L1644

**Comment by josephsmann** [comment]
that was the whole traceback. unless there's something else I can do.

**Comment by jakevdp** [comment]
You could raise the issue in xpython.

In the meantime, I'll make the modification to Altair that will accommodate this sort of issue, and it will be available in the next release.

**Comment by josephsmann** [comment]
will do. won't have much expertise though.

**Comment by jakevdp** [comment]
OK, I'll raise the issue

**Comment by josephsmann** [comment]
just about to hit submit - I'll add your @jakevdp ?

**Comment by jakevdp** [comment]
Sure, sounds good.

**Comment by josephsmann** [comment]
done.

**Comment by joelostblom** [comment]
Closing this since #2043 was merged in.
