### ISSUE TITLE
Filling country colours by value of column in other DataFrame

### ISSUE THREAD

**Issue by smu095** [altair-viz/altair#2044]
Hi,

I've just started experimenting with Altair, and am loving it so far. I am, however, struggling somewhat with generating map plots.

### Problem 

I'm trying to plot a world map of confirmed Covid-19 cases, using [data provided by John Hopkins](https://raw.githubusercontent.com/CSSEGISandData/COVID-19/web-data/data/cases_country.csv). I want to colour countries by the number of confirmed cases, but have been unsuccessful.

### Data

The code to retrieve and clean the data is:

```python
import janitor # pip install pyjanitor
import pandas as pd

CASES_WORLDWIDE = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/web-data/data/cases_country.csv"

def get_worldwide_cases(url: str = CASES_WORLDWIDE):
    cases = pd.read_csv(url)
    cleaned = (
        cases.clean_names()
        .rename_column("long_", "lon")
        .transform_column("last_update", lambda x: pd.to_datetime(x).normalize())
    )
    return cleaned

world_source = get_worldwide_cases()
```

The head of the data will look like this:

|    | country_region   | last_update         |      lat |     lon |   confirmed |   deaths |   recovered |   active |
|---:|:-----------------|:--------------------|---------:|---------:|------------:|---------:|------------:|---------:|
|  0 | Australia        | 2020-03-27 00:00:00 | -25      | 133      |        3143 |       13 |         194 |     2936 |
|  1 | Austria          | 2020-03-27 00:00:00 |  47.5162 |  14.5501 |        7317 |       58 |         225 |     7034 |
|  2 | Canada           | 2020-03-27 00:00:00 |  60.001  | -95.001  |        4046 |       40 |         184 |        0 |
|  3 | China            | 2020-03-27 00:00:00 |  30.5928 | 114.305  |       81897 |     3296 |       74720 |     3881 |
|  4 | Denmark          | 2020-03-27 00:00:00 |  56      |  10      |        2163 |       52 |          57 |     2054 |

### Desired output
I would like to produce a plot that looks something like this:

<img width="600" alt="covid19" src="https://user-images.githubusercontent.com/17871168/77760488-b676b800-7036-11ea-88a9-680f7d81458f.png">

### Current output
Since I've been unable to reproduce the above plot, I hacked together a workaround that displays the information in a different way. My current output looks like this:

<img width="737" alt="current" src="https://user-images.githubusercontent.com/17871168/77760552-d3ab8680-7036-11ea-8736-2bb288e4287e.png">

### Current solution
The code that produces my plot is:

```python
# Get data
import altair as alt
from vega_datasets import data

# Map plot
source = alt.topo_feature(data.world_110m.url, "countries")
base_map = (
    alt.Chart(source)
    .mark_geoshape(fill="white", stroke="gray")
    .properties(width=600, height=300)
    .project("naturalEarth1")
)

points = (
    alt.Chart(world_source)
    .mark_point()
    .encode(
        latitude="lat",
        longitude="lon",
        fill=alt.value("red"),
        size="confirmed:Q",
        stroke=alt.value(None),
     )
)

final_map = (
    (base_map + points)
    .configure_view(strokeWidth=0)
    .configure_mark(opacity=0.5,)
)
```

I've understood that using `.transform_lookup()` is one possible way to solve this, but all attempts at looking up the `confirmed` column in `world_source` have failed so far.

I would greatly appreciate any input!

**Comment by jakevdp** [comment]
To do this, you will need to join your dataset to topojson data containing the geometries you want to repesent each data point.

There is an example of this for county-level data in the US here: https://altair-viz.github.io/gallery/choropleth.html

The relevant topojson file can be loaded using
```
source = alt.topo_feature(data.world_110m.url, 'countries')
```
Each country in the data has an ID code, so if you have a dataset with those ID codes, you can use a ``transform_lookup`` to join it to the appropriate geometry.

I'm not sure how these ID codes are generated or what the best way is to add them to your dataset, unfortunately, but you can see what the ID codes are in the tooltips of this chart:
```python
import altair as alt
from vega_datasets import data
source = alt.topo_feature(data.world_110m.url, 'countries')
alt.Chart(source).mark_geoshape(
    fill='lightgreen',
    stroke='grey',
).encode(
    tooltip='id:N' 
).project(
    'naturalEarth1'
).properties(
    width=600, height=400
).configure_view(stroke=None)
```
Hope that helps get you on the right track.

**Comment by jakevdp** [comment]
Ah, actually it looks like these codes are the standard ISO 3166-1 numeric codes: https://en.wikipedia.org/wiki/ISO_3166-1_numeric

So add these codes to your dataset and you'll be able to follow the example from  https://altair-viz.github.io/gallery/choropleth.html

**Comment by smu095** [comment]
Hi @jakevdp, thanks for the reply and useful tips.

You were right, it was just a matter of finding the appropriate ISO 3661-1 codes and performing a lookup on them. This is the (preliminary) result:

<img width="838" alt="Screenshot 2020-03-27 at 20 47 03" src="https://user-images.githubusercontent.com/17871168/77796938-821fed80-7070-11ea-97f5-bc897129d449.png">

In case anyone is interested, this is the code to generate the plot above. It assumes that we have defined a lookup dataset (in my case `world_source`) with the required ISO 3661-1 codes.

```python
source = alt.topo_feature(data.world_110m.url, "countries")

background = alt.Chart(source).mark_geoshape(fill="white")

foreground = (
    alt.Chart(source)
    .mark_geoshape(stroke="black", strokeWidth=0.15)
    .encode(
        color=alt.Color(
            "sick_per_100k:N", scale=alt.Scale(scheme="lightgreyred"), legend=None,
        ),
        tooltip=[
            alt.Tooltip("country_region:N", title="Country"),
            alt.Tooltip("sick_per_100k:Q", title="Cases pr. 100k"),
        ],
    )
    .transform_lookup(
        lookup="id",
        from_=alt.LookupData(world_source, "id", ["sick_per_100k", "country_region"]),
    )
)

final_map = (
    (background + foreground)
    .configure_view(strokeWidth=0)
    .properties(width=700, height=400)
    .project("naturalEarth1")
)
```

Thanks again @jakevdp, stay safe.

**Comment by jakevdp** [comment]
That's a nice visualization – glad you got it working!

**Comment by reidjohnson** [comment]
@ThelmaSilva et al., here's a full working example with the current data:

&nbsp; | country_region | last_update | lat | lon | confirmed | deaths | incident_rate | uid
-- | -- | -- | -- | -- | -- | -- | -- | --
0 | Afghanistan | 2021-12-17 | 33.939110 | 67.709953 | 157734 | 7332 | 405.190655 | 4
1 | Albania | 2021-12-17 | 41.153300 | 20.168300 | 205224 | 3158 | 7131.28084 | 8
2 | Algeria | 2021-12-17 | 28.033900 | 1.659600 | 213745 | 6171 | 487.434244 | 12
3 | Andorra | 2021-12-17 | 42.506300 | 1.521800 | 20549 | 134 | 26595.4831 | 20
4 | Angola | 2021-12-17 | -11.202700 | 17.873900 | 65648 | 1737 | 199.742788 | 24

```
import altair as alt
import janitor
import pandas as pd
from vega_datasets import data

CASES_WORLDWIDE = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/web-data/data/cases_country.csv"


def get_worldwide_cases(url: str = CASES_WORLDWIDE):
    cases = pd.read_csv(url)
    cleaned = cases.clean_names(
    ).rename_column(
        "long_", "lon"
    ).transform_column(
        "last_update", lambda x: pd.to_datetime(x).normalize()
    )
    return cleaned


world_source = get_worldwide_cases()

source = alt.topo_feature(data.world_110m.url, "countries")

background = alt.Chart(source).mark_geoshape(fill="white")

foreground = (
    alt.Chart(source).mark_geoshape(
        stroke="black", strokeWidth=0.15
    ).encode(
        color=alt.Color(
            "incident_rate:N", scale=alt.Scale(scheme="lightgreyred"), legend=None,
        ),
        tooltip=[
            alt.Tooltip("country_region:N", title="Country"),
            alt.Tooltip("incident_rate:Q", title="Cases pr. 100k"),
        ],
    ).transform_lookup(
        lookup="id",
        from_=alt.LookupData(world_source, "uid", ["incident_rate", "country_region"]),
    )
)

chart = (
    (background + foreground)
    .configure_view(strokeWidth=0)
    .properties(width=700, height=400)
    .project("naturalEarth1")
)

chart
```

<img width="721" alt="visualization" src="https://user-images.githubusercontent.com/4712548/146621034-03d17573-793c-4e8b-bcd3-cf9561c0ecab.png">

**Comment by bast** [comment]
I also struggled with this (and this issue discussion helped me out - thanks!) and found a solution where I don't have to put the ISO 3166-1 codes into my data but rather use an [external CSV](https://github.com/lukes/ISO-3166-Countries-with-Regional-Codes) and two consecutive `.transform_lookup()` to map the country codes to a country name and then in my dataset I only use country names.

Maybe my solution will be useful to those who find this issue:
- https://nbviewer.org/github/bast/altair-geographic-plots/blob/fc9c036/choropleth.ipynb
- https://github.com/bast/altair-geographic-plots
