### ISSUE TITLE
How to set different mark shapes for different lines in line graph

### ISSUE THREAD

**Issue by AlwaysKaixuan** [altair-viz/altair#2045]
```
import pandas as pd

import altair as alt

data = pd.DataFrame({'key_length': [64, 128, 256, 512, 1024, 64, 128, 256, 512, 1024, 64, 128, 256, 512, 1024],
                     'spend_time': [0.115, 0.446, 2.397, 25.272, 208, 0.31, 1.129, 8.593, 66, 586, 0.389, 1.701, 13.013, 79, 735],
                     'tn': ['(2, 5)', '(2, 5)', '(2, 5)', '(2, 5)', '(2, 5)',
                                '(2, 10)', '(2, 10)', '(2, 10)', '(2, 10)', '(2, 10)', 
                                '(4, 10)', '(4, 10)', '(4, 10)', '(4, 10)', '(4, 10)']})

alt.Chart(data).mark_line(point=True).encode(
    alt.X('key_length', title='key_length(bit)'),
    alt.Y('spend_time', title='spend_time(s)'),
    alt.Color('tn'),
    alt.Shape('tn')
)
```

**Comment by AlwaysKaixuan** [comment]
I couldn't get the results I wanted.

**Comment by jakevdp** [comment]
Can you elaborate on what you want to be different? When I run this I see different mark shapes for each line:
![visualization - 2020-03-27T141206 826](https://user-images.githubusercontent.com/781659/77800869-f63ca000-7034-11ea-8e4b-4a9fc0761620.png)

**Comment by AlwaysKaixuan** [comment]
> Can you elaborate on what results you want? When I run this I see different mark shapes for each line:
> ![visualization - 2020-03-27T141206 826](https://user-images.githubusercontent.com/781659/77800869-f63ca000-7034-11ea-8e4b-4a9fc0761620.png)

I just don't know why there is one more legend, can there be only one?

**Comment by jakevdp** [comment]
See #1785
