### ISSUE TITLE
Installation issue - ERROR: File "setup.py" not found.

### ISSUE THREAD

**Issue by patrickAUS** [altair-viz/altair#2048]
Hi, pretty much a newbie in development, but really struggling to install Altair properly. I tried with Conda "conda install -c conda-forge altair vega_datasets" which worked, but then couldn't get "conda install -e .[dev]", so I tried pip install -e .[dev], but get "ERROR: File "setup.py" not found." 

when I try running the basic Test.py file below, I get the following error:
```pytb
SchemaValidationError: Invalid specification

        altair.vegalite.v4.api.Chart, validating 'required'

        'mark' is a required property
```

Test.py
```python
import pandas as pd
data = pd.DataFrame({'a': list('CCCDDDEEE'),
                     'b': [2, 7, 4, 1, 2, 6, 8, 4, 7]})
import altair as alt
chart = alt.Chart(data)

alt.Chart(data).mark_bar(color='firebrick').encode(
    alt.Y('a', title='category'),
    alt.X('average(b)', title='avg(b) by category')
)

chart.save('chart.html')
```

Sorry if this is basics, but spend the whole afternoon trying to troubleshoot...

**Comment by jakevdp** [comment]
You never assign the chart you created to a variable, so your code is equivalent to running:
```python
import pandas as pd
data = pd.DataFrame({'a': list('CCCDDDEEE'),
                     'b': [2, 7, 4, 1, 2, 6, 8, 4, 7]})
import altair as alt
chart = alt.Chart(data)
chart.save('chart.html')
```
Your chart does not define a mark property, which leads to the error you saw.

If you want to save the chart you defined, you can do it like this:
```python
import pandas as pd
data = pd.DataFrame({'a': list('CCCDDDEEE'),
                     'b': [2, 7, 4, 1, 2, 6, 8, 4, 7]})
import altair as alt

chart = alt.Chart(data).mark_bar(color='firebrick').encode(
    alt.Y('a', title='category'),
    alt.X('average(b)', title='avg(b) by category')
)

chart.save('chart.html')
```

**Comment by jakevdp** [comment]
Regarding your installation question: ``pip install -e .[dev]`` will only work if you have downloaded the source repository and you run the command from within the repository. Otherwise, the error you saw is the expected result.

**Comment by patrickAUS** [comment]
Thanks so much on both responses, really helpful!
