### ISSUE TITLE
Why so slow from local html page?

### ISSUE THREAD

**Issue by Heimetli** [altair-viz/altair#2050]
I have tried to reproduce https://altair-viz.github.io/gallery/scatter_linked_brush.html in a local html page.

It works, but selection reacts extremely slow.

The online version runs smoothly, the online editor also has no problem at all.

In the end, I even copied the page from altair-viz.github.io to my computer and it still reacts very slow to the selection. Same browser, same computer...

Any ideas?

**Comment by jakevdp** [comment]
I'm not sure what might be causing this. Please let us know if you figure out the issue.

**Comment by joelostblom** [comment]
@Heimetli I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet or you were able to troubleshoot the issue?
