### ISSUE TITLE
How can I customize alt.Tooltip format

### ISSUE THREAD

**Issue by ShukriChiu** [altair-viz/altair#2058]
![image](https://user-images.githubusercontent.com/5136543/78109131-3b911100-742b-11ea-8d96-0a4d1b0f019b.png)

For example, It's a time-series sales data, If I want to compute the percentage change from the previous day and add it into the Tooltip Panel, What should I do? 

Is Tooltip API support such customization.

**Comment by jakevdp** [comment]
The best way to do this would be to use a window transform to compute the percentage in a new field, and then add that new field to the tooltip.

For example:
```python
import altair as alt
from vega_datasets import data

stocks = data.stocks()

alt.Chart(stocks).mark_point().transform_window(
    previous_price = 'lag(price)'
).transform_calculate(
    pct_change = '(datum.price - datum.previous_price) / datum.previous_price'
).encode(
    x='date',
    y='price',
    color='symbol',
    tooltip=['date', 'price', 'symbol', alt.Tooltip('pct_change:Q', format='.1%')]
)
```

**Comment by cjw296** [comment]
@jakevdp - related, and I think what the OP requested: how can you have more than one variable on a line it a tooltip, especially when one is a percentage like this?

I'm thinking of Grafana's functionality where a vertical bar is drawn as you hover, and each point is shown in a tooltip with the values of that point at that time.

**Comment by joelostblom** [comment]
@cjw296 To display multiple variables on a single line a tooltip, you can first concatenate those fields using `transform_calculate`:

```python
import altair as alt
from vega_datasets import data


stocks = data.stocks()

alt.Chart(stocks).mark_point().transform_calculate(
    combined_tooltip = "datum.price + ' ' + datum.symbol"
).encode(
    x='date',
    y='price',
    color='symbol',
    tooltip='combined_tooltip:N')
```
![image](https://user-images.githubusercontent.com/4560057/121394311-10932e80-c906-11eb-9943-364657283bf7.png)

**Comment by ogencoglu** [comment]
A bit random question. How can I specify my data fields (columns) if the fields have whitespace?

` "datum.price of something"` for example if `price of something` is my column name.

**Comment by mattijn** [comment]
does `'datum["price of something"]'` work?

**Comment by ogencoglu** [comment]
`datum['Publication Date']` works indeed. Thanks.

**Comment by ChristopherDavisUCI** [comment]
> Another question would be if it is possible to set the color of the percentage depending on its value, e.g. red for negative values and green for positive values?

Does this example help? https://altair-viz.github.io/gallery/bar_chart_with_negatives.html

**Comment by mahadi** [comment]
I mean the part of the text in the tooltip which shows the percentage.
The example changes the color of the bars instead.

Am 6. Mai 2024 22:40:30 MESZ schrieb Christopher Davis ***@***.***>:

**Comment by jonmmease** [comment]
You can't customize the color of the text in the popup tooltip unfortunately. The only option I'm aware of is to use a text mark that is updated on hover.

See the last example in https://altair-viz.github.io/user_guide/compound_charts.html. This example shows how to show/hide the text based on the point that's hovered. You would want to do this in addition to providing `color = alt.condition(...)` to control the color using a Vega expression.

If you'd like help working through this approach, open a new [discussion thread](https://github.com/vega/altair/discussions) with an example that you'd like to add the tooltip to.
