### ISSUE TITLE
Add an horizontal line to an existent chart

### ISSUE THREAD

**Issue by luistelmocosta** [altair-viz/altair#2059]
Hello, I am using [chime](https://github.com/CodeForPhilly/chime/) project to simulate some numbers to a local hospital and I would like to add a line with the maximum hospital capacity that will work as a threshold. For that I need to add a horizontal line, i.e, `y=100` to this chart. I am having an hard time doing it, though.

What would be the best approach to do this?

Kind regards

```
def build_census_chart(
    *,
    alt,
    census_df: pd.DataFrame,
    max_y_axis: Optional[int] = None,
    hospital_maximum_capacity: Optional[int] = None,
) -> Chart:
    """Build census chart."""
    y_scale = alt.Scale()
    if max_y_axis:
        y_scale.domain = (0, max_y_axis)

    x = dict(shorthand="date:T", title="Date", axis=alt.Axis(format=(DATE_FORMAT)))
    y = dict(shorthand="value:Q", title="Census", scale=y_scale)
    color = "key:N"
    tooltip = ["date:T", alt.Tooltip("value:Q", format=".0f", title="Census"), "key:N"]

    # TODO fix the fold to allow any number of dispositions
    points = (
        alt.Chart()
        .transform_fold(fold=["hospitalized", "icu", "ventilated"])
        .encode(x=alt.X(**x), y=alt.Y(**y), color=color, tooltip=tooltip)
        .mark_line(point=True)
    )
    bar = (
        alt.Chart()
        .encode(x=alt.X(**x))
        .transform_filter(alt.datum.day == 0)
        .mark_rule(color="black", opacity=0.35, size=2)
    )
    '''bar = (
        alt.Chart()
        .encode(y=alt.Y(**y))
        .transform_filter(alt.datum.day == 0)
        .mark_rule(color="red", opacity=0.35, size=2)
    )'''
   
    return alt.layer(points, bar, data=census_df)
```

**Comment by jakevdp** [comment]
The best way to do this is with a rule mark:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'x': np.random.randn(100),
    'y': np.random.randn(100)
})

chart = alt.Chart(df).mark_point().encode(x='x', y='y')
line = alt.Chart(pd.DataFrame({'y': [1]})).mark_rule().encode(y='y')

chart + line
```
![visualization - 2020-04-02T065631 323](https://user-images.githubusercontent.com/781659/78257729-1940d700-74af-11ea-98aa-56130023eb9e.png)

Note that in the next version of Altair (4.2) this will be slightly easier using the datum encoding; the horizontal line will look something like this:
```python
alt.Chart().mark_rule().encode(y=alt.datum(1))
```
(The final API has not been decided yet)

**Comment by luistelmocosta** [comment]
That is perfect, thank you! :) 

Is there any way to make the line dashed?

**Comment by jakevdp** [comment]
Yes, for example
```
mark_line(strokeDash=[10, 10])
```

**Comment by gomezago** [comment]
Hello, 

I'm having a similar issue, but I have hours on my Y axis, and mark_rule doesn't seem to work, is there any way around it? I'm using something similar to this example (https://altair-viz.github.io/gallery/table_bubble_plot_github.html), with the axis inverted.

import altair as alt
from vega_datasets import data

source = data.github.url

alt.Chart(source).mark_circle().encode(
    x='hours(time):O',
    y='day(time):O',
    size='sum(count):Q'
)

**Comment by Ahasanatwork** [comment]
Hey, how would we do this for an interactive scatter plot (with a tooltip)?

**Comment by joelostblom** [comment]
@luistelmocosta I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
