### ISSUE TITLE
Subplots

### ISSUE THREAD

**Issue by PawelKozela** [altair-viz/altair#206]
Hi guys,

any plans to add the ability to generate multiple charts ? (matplotlib's subplot equivalent)

PS. This project is just amazing !

**Comment by jakevdp** [comment]
Yes! This feature will be supported by Vega Lite in the upcoming release, and we'll have Altair bindings for it as soon as possible once that's available.

**Comment by kanitw** [comment]
You can also use `row` and `column` channel to encode your partition field.  (But we do not support wrapped trellis / subplots yet.)

**Comment by simonm3** [comment]
+1 this is a really great project. 

Re subplots , matplotlib requires you specify the layout in advance and the grid coordinates for each chart. One thing I do a lot is to call multiple functions which collectively show 20-40 unrelated charts. I don't know the layout in advance as I don't know how many charts I will have in total; and within a function when I print a chart I don't have the context so I don't know the position in the grid.

I just know that 10 rows of 4 charts is neater than a big long list of 40 charts. So I want a one liner to start "gridprint"; and then all subsequent charts take the next place in the grid. Would be great if you could do that.....Maybe this is in the vega spec but could not see it.

**Comment by ellisonbg** [comment]
Closing as vega-lite-related

**Comment by ronyarmon** [comment]
Seaborn has a one-liner for subplots, no need to specify layout. 
Altair/vega-lite is great but similar functionaliy will be helpful

[seaborn_subplots.txt](https://github.com/altair-viz/altair/files/2053651/seaborn_subplots.txt)

**Comment by ronyarmon** [comment]
Thanks, but reset_index, which is necessary for melting here, is an issue as the data is an excerpt from a time series.

**Comment by jakevdp** [comment]
Why is that an issue? If you want the index to be on the x axis, you need to make it an explicit column (using ``reset_index``). It doesn't matter what the type of the index is.

**Comment by jakevdp** [comment]
If the index is named, then it will keep its original name rather than being called ``index``.

**Comment by jakevdp** [comment]
You might need to switch the order in order to keep the index; e.g.
```python
diff_ccgs.reset_index().melt('index')
```
The point is to get whatever data you want to plot into the appropriate long-form representation. The pandas manipulations are up to you :smile:

**Comment by ronyarmon** [comment]
You're right, no issues!  (I tried pd.melt but your line worked better). However, I'm getting the charts in a long row so to come back to the matplotlib-like question, can we specify a layout? I also draw many plots and want them say in a 2 * 5 layout.

**Comment by jakevdp** [comment]
It can be done, but not easily (you can transform the data in order to generate new encodings that map to the rows & columns you want).

It will be much easier when wrapped facets land in Vega-Lite; see https://github.com/vega/vega-lite/issues/393 to track progress on that.
