### ISSUE TITLE
Rendering in axis x leap year, the dates february 29 and march 1 are overlap

### ISSUE THREAD

**Issue by MauGal** [altair-viz/altair#2060]
Hi,
I'm using altair with streamlit.
All my graphs have this problem: in x I have a date field where the dates are between 2020-02-24 and 2020-04-01 and the dates feb-29 and mar-01 are overlap.
For example my code is:
```python
base_contagi = alt.Chart(df_complete).encode(
        alt.Tooltip(['data:T', 'totale_casi:Q']),
        x=alt.X('monthdate(data):O', axis=alt.Axis(grid=True)),
        y=alt.Y('totale_casi:Q',axis=alt.Axis(title='Totale casi'))
)
st.altair_chart(alt.layer(base_contagi.mark_line(), base_contagi.mark_point()).properties(width=650,height=400).interactive())
```
the result is:
![trend_cont](https://user-images.githubusercontent.com/28858911/78273350-fe9e4a80-750e-11ea-86d2-28cedb8e14a0.png)

Other example are in: [http://covid-19-ita-mg.herokuapp.com/](url)

**Comment by jakevdp** [comment]
What version of Altair are you using? I don't see the issue in version 4.0.1 with the following chart:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
  'date': pd.date_range('2020-02-15', freq='D', periods=30),
  'y': range(30)
})

alt.Chart(df).mark_line(point=True).encode(
    x='monthdate(date):O',
    y='y:Q'
)
```
![visualization - 2020-04-02T095833 820](https://user-images.githubusercontent.com/781659/78276903-8745c800-74c8-11ea-9a17-ef1d17bc07ba.png)

**Comment by MauGal** [comment]
Hi @jakevdp.
Thanks for your quick answer.
I had an older version.
I updated my local version of altair (4.1.0) but the issue is still there.
And with your example I have the same problem using streamlit
```python
import altair as alt
import pandas as pd
import streamlit as st

df = pd.DataFrame({
  'date': pd.date_range('2020-02-15', freq='D', periods=30),
  'y': range(30)
})
st.write('### Test: example by jakevdp')
obj = alt.Chart(df).mark_line(point=True).encode(
    x='monthdate(date):O',
    y='y:Q'
)

st.altair_chart(obj)
```
![test_jakevdp](https://user-images.githubusercontent.com/28858911/78294371-96f5f880-752a-11ea-9df9-c3bdb9506dd8.png)

Instead using jupyter notebook the issue there isn't (It's equal  to your figure)

Could this be a issue generated by streamlit?

**Comment by jakevdp** [comment]
It's possible that streamlit is using an older vega or vega-lite version in the frontend. I've poked around http://github.com/streamlit/streamlit/ but can't find any clue there as to what versions of frontend libraries they use.

Do you see any warnings in the javascript console?

**Comment by MauGal** [comment]
I think that you are right.
In javascript console there is this message:
The input spec uses Vega-Lite v4.8.1, but the current version of Vega-Lite is v4.0.0-beta.10.
I will open a new issue in their project

**Comment by jakevdp** [comment]
Yeah, that looks like the issue. Thanks!
