### ISSUE TITLE
Interactive legends with pre-selected values?

### ISSUE THREAD

**Issue by tomhe** [altair-viz/altair#2061]
I'm using interactive legends, as documented here:

https://altair-viz.github.io/gallery/interactive_legend.html

Question:

Is it possible to have an initial selection of the chart, so that a few chosen values are pre-selected? Like this:

<img width="564" alt="Screenshot 2020-04-02 at 19 51 51" src="https://user-images.githubusercontent.com/2315228/78356479-ecc0b400-75af-11ea-8443-257363ab00a3.png">

**Comment by jakevdp** [comment]
You can use the ``init`` parameter to specify the initial selection:
```python
import altair as alt
from vega_datasets import data

source = data.unemployment_across_industries.url
init = ['Finance', 'Government', 'Self-employed', 'Wholesale and Retail Trade']

selection = alt.selection_multi(fields=['series'], bind='legend', init=[{'series': val} for val in init])

alt.Chart(source).mark_area().encode(
    alt.X('yearmonth(date):T', axis=alt.Axis(domain=False, format='%Y', tickSize=0)),
    alt.Y('sum(count):Q', stack='center', axis=None),
    alt.Color('series:N', scale=alt.Scale(scheme='category20b')),
    opacity=alt.condition(selection, alt.value(1), alt.value(0.2))
).add_selection(
    selection
)
```
![visualization - 2020-04-03T051011 019](https://user-images.githubusercontent.com/781659/78359189-697c6f80-7569-11ea-8eb6-88ad55a2ca52.png)
