### ISSUE TITLE
Legend “inside” line chart?

### ISSUE THREAD

**Issue by tomhe** [altair-viz/altair#2064]
Is it possible to have the legend “inside” a line chart, right next to each line, like in this example?

![839B52A3-06A2-48B2-903F-747CEC122B92](https://user-images.githubusercontent.com/2315228/78421785-aa07e600-765a-11ea-98f7-419da7b39f57.jpeg)

**Comment by jakevdp** [comment]
Yes, it would look something like this:
```python
import altair as alt
import pandas as pd
import numpy as np

np.random.seed(0)

df = pd.DataFrame({
    'x': np.tile(range(100), 4),
    'y': np.random.randn(4, 100).cumsum(1).ravel(),
    'name': np.repeat(list('ABCD'), 100)
})

lines = alt.Chart(df).mark_line().encode(
    x=alt.X('x', scale=alt.Scale(domain=[0, 110])),
    y=alt.Y('y'),
    detail='name'
)

text = alt.Chart(df).mark_text(align='left', baseline='middle', dx=3).encode(
    x='max(x)',
    y=alt.Y('y', aggregate={'argmax': 'x'}),
    text='name'
)

lines + text
```
![visualization - 2020-04-04T055359 938](https://user-images.githubusercontent.com/781659/78451172-b2e7c000-7638-11ea-972c-0998a021c246.png)

**Comment by tomhe** [comment]
Thanks, that worked great! 

One follow-up question:

I'm using [interactive legends](https://altair-viz.github.io/gallery/interactive_legend.html), and when I select a label in the legend it looks like this:

<img width="612" alt="Screenshot 2020-04-04 at 17 41 53" src="https://user-images.githubusercontent.com/2315228/78454958-c5471580-769b-11ea-89c6-fd4b345bc9e4.png">

Is it possible to have the selection include the text labels also, so that they get greyed out? And even better would be if they were also interactive so that they were clickable.

**Comment by jakevdp** [comment]
Yes, you can use ``transform_filter(selection)`` on the text layer.

**Comment by tomhe** [comment]
Yes, that worked!
