### ISSUE TITLE
Financial data - business week plot

### ISSUE THREAD

**Issue by tzipperle** [altair-viz/altair#2065]
Hi, I have a problem to plot financial data. I want to plot the stock price for 3 business weeks without the weekends. I want only xticks at Mondays. But the ordinal option (x-axis: # 3) does not work. Do you have any ideas?

```python

import pandas as pd
import numpy as np
import altair as alt

data = pd.DataFrame({'x': pd.date_range('2020-02-12', periods=30, freq='B'),
                     'y': np.random.randn(30).cumsum()})
dates = pd.date_range(data['x'].min(),data['x'].max(), freq='W-MON').astype(int) / 10 ** 6

alt.Chart(data).mark_line().encode(
    x=alt.X('yearmonthdate(x):O', axis=alt.Axis(grid=True, labelAngle=0)), # 1
    # x=alt.X('x:T', axis=alt.Axis(values=list(dates),format="%d.%m.%Y")), # 2
    # x=alt.X('x:O', axis=alt.Axis(values=list(dates),format="%d.%m.%Y")), # 3
    y='y:Q'
)
```
x-axis: 1 (too many ticks)
![image](https://user-images.githubusercontent.com/6015123/78424517-7afb6f80-766e-11ea-862f-8162d5f3ada0.png)

x-axis: 2 (ticks ok,but interpolation between missing data)
![image](https://user-images.githubusercontent.com/6015123/78424603-07a62d80-766f-11ea-8ce6-8c39050d2354.png)

x-axis: 3 
![image](https://user-images.githubusercontent.com/6015123/78424626-23113880-766f-11ea-9692-fff6f09e9256.png)

**Comment by jakevdp** [comment]
In Altair 4.1 or newer you can use the timestamp array directly:
```python
import pandas as pd
import numpy as np
import altair as alt

data = pd.DataFrame({'x': pd.date_range('2020-02-12', periods=30, freq='B'),
                     'y': np.random.randn(30).cumsum()})
dates = pd.date_range(data['x'].min(),data['x'].max(), freq='W-MON').to_numpy()

alt.Chart(data).mark_line().encode(
    x=alt.X('yearmonthdate(x):O', axis=alt.Axis(values=dates, format='%d.%m.%Y')),
    y='y:Q'
)
```
![visualization - 2020-04-04T060833 962](https://user-images.githubusercontent.com/781659/78451466-baa86400-763a-11ea-90f7-b1ffb2393afd.png)

Alternatively, you can use a ``labelExpr`` to put the logic of what labels to display within the chart:
```python
alt.Chart(data).mark_line().encode(
    x=alt.X('yearmonthdate(x):O', axis=alt.Axis(labelExpr="day(datum.value) == 1 ? timeFormat(datum.value, '%d.%m.%Y') : ''")),
    y='y:Q'
)
```
![visualization - 2020-04-04T060928 124](https://user-images.githubusercontent.com/781659/78451509-dc095000-763a-11ea-939b-e7ce36d98611.png)

**Comment by tzipperle** [comment]
@jakevdp thank you for your quick response!

The first version works perfect.

**Comment by joelostblom** [comment]
@tzipperle I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
