### ISSUE TITLE
I want to plot multi layer area plot with gradient.

### ISSUE THREAD

**Issue by MadushanPathirana** [altair-viz/altair#2066]
I want to plot multilayer area plot with gradient. But as far I found there is no way to do that without compounding charts. When charts are compounded I need to create a separate legend for the chart. Is there way that I can plot a multilayer area plot with gradient including the legend without compounding. I used below function to plot single layer area chart

```def Charts(clm):
    chart=alt.Chart(df_melt[df_melt.Legend==clm]).mark_area(line={'color':'blue'},
        color=alt.Gradient(    gradient='linear',
        stops=[alt.GradientStop(color='white', offset=0),
               alt.GradientStop(color='blue', offset=1)] ,
        x1=1,
        x2=1,
        y1=1,
        y2=0)
        ).encode(
        x='Days',
        y='% of Population:Q',
        
        tooltip='% of Population',
        opacity=alt.value(.5)).properties(
        height=300,
        width=730).interactive()
    return chart `

**Comment by MadushanPathirana** [comment]
Out put should look like this. Points are not required. 
![VNMor](https://user-images.githubusercontent.com/25402794/78441387-a9d90c00-7695-11ea-9432-c7db64444fd3.png)

**Comment by jakevdp** [comment]
It's possible, with some manual configuration of gradients in each layer. Drawing from https://altair-viz.github.io/gallery/area_chart_gradient.html, you could do something like this:
```python
import altair as alt
from vega_datasets import data

source = data.stocks()

def stock_gradient(symbol, color):
  return alt.Chart(source).transform_filter(
      f'datum.symbol==="{symbol}"'
  ).mark_area(
      line={'color': color},
      color=alt.Gradient(
          gradient='linear',
          stops=[alt.GradientStop(color='white', offset=0),
                alt.GradientStop(color=color, offset=1)],
          x1=1,
          x2=1,
          y1=1,
          y2=0
      )
  ).encode(
      alt.X('date:T'),
      alt.Y('price:Q')
  )

alt.layer(
    stock_gradient('GOOG', 'darkgreen'),
    stock_gradient('AAPL', 'darkblue'),
    stock_gradient('MSFT', 'darkorange')
)
```
![visualization - 2020-04-04T061853 391](https://user-images.githubusercontent.com/781659/78451719-2c34e200-763c-11ea-8d0a-9c2698aeffbb.png)

**Comment by MadushanPathirana** [comment]
Thank you for the quick response. But still, I have to add legend manually. Is there another way?

**Comment by jakevdp** [comment]
Oh, your example chart didn't have a legend, so I didn't think you wanted one. You can add a legend by adding a stroke encoding for the lines:
```python
import altair as alt
from vega_datasets import data

source = data.stocks()

def stock_gradient(symbol, color):
  return alt.Chart(source).transform_filter(
      f'datum.symbol==="{symbol}"'
  ).mark_area(
      line={'color': color},
      color=alt.Gradient(
          gradient='linear',
          stops=[alt.GradientStop(color='white', offset=0),
                alt.GradientStop(color=color, offset=1)],
          x1=1,
          x2=1,
          y1=1,
          y2=0
      )
  ).encode(
      alt.X('date:T'),
      alt.Y('price:Q'),
  )

alt.layer(
    stock_gradient('GOOG', 'darkgreen'),
    stock_gradient('AAPL', 'darkblue'),
    stock_gradient('MSFT', 'darkorange')
).encode(
    alt.Stroke('symbol', scale=alt.Scale(domain=['GOOG', 'AAPL', 'MSFT'], range=['darkgreen', 'darkblue', 'darkorange']))
)
```

**Comment by MadushanPathirana** [comment]
Just what I needed. Thank you very much. Love Altair and your books @jakevdp  .

**Comment by MadushanPathirana** [comment]
![download (1)](https://user-images.githubusercontent.com/25402794/78458088-78c7fe00-76cc-11ea-8e1c-bb4885debd86.png)

But still legend is filled with gree, can we fill the legend with white color?

**Comment by joelostblom** [comment]
@MadushanPathirana I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
