### ISSUE TITLE
Calculate Transform within an encoding

### ISSUE THREAD

**Issue by debbes80** [altair-viz/altair#2068]
Is it possible to use transform_calculate within an encoding?
For example, calculate the difference between two plots, split on a color encoding. The left chart is the data, the right chart is the difference between the 'a' and 'b' plot. Can I create the right chart without using pandas?
```python
import pandas as pd
import numpy as np
import altair as alt

df = pd.DataFrame()
df['cat'] = ['a','a','a','a','b','b','b','b']
df['xs'] = [1,2,3,4,1,2,3,4]
df['ys'] = [10,11,12,13,5,4,3,2]

chart1 = alt.Chart(df).mark_line(point=True).encode(
    x='xs:Q',
    y='ys:Q',
    color='cat:N'
)

#Manual creation of 'difference dataframe'
df2 = pd.DataFrame()
df2['xs'] = [1,2,3,4]
df2['ys'] = [5,7,9,11]
chart2 = alt.Chart(df2).mark_line(point=True).encode(
    x='xs:Q',
    y='ys:Q',
)

chart1|chart2
```
![visualization](https://user-images.githubusercontent.com/54935651/78457386-0ba37100-76aa-11ea-8601-19821f1f5fbd.png)

**Comment by jakevdp** [comment]
There is no way to do a calculate transform within an encoding (as there is with, e.g. aggregate, bin, and impute transforms). But you can do what you wish using a [Pivot Transform](https://altair-viz.github.io/user_guide/transform/pivot.html) followed by a [Calculate transform](https://altair-viz.github.io/user_guide/transform/calculate.html) and then use the results in the encoding. For example:
```python
chart2 = alt.Chart(df).transform_pivot(
    pivot='cat', groupby=['xs'], value='ys', op='sum'
).transform_calculate(
    diff='datum.a - datum.b'  
).mark_line(point=True).encode(
    x='xs:Q',
    y='diff:Q'
)
chart1|chart2
```
![visualization - 2020-04-04T135602 832](https://user-images.githubusercontent.com/781659/78461229-0af3e600-767c-11ea-9f79-bf9c6669196a.png)

**Comment by debbes80** [comment]
Works great.
Thanks for the quick response!
