### ISSUE TITLE
Build & host sphinx docs

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#207]
@Carreau – I saw that you registered altair on readthedocs.

I've just merged an initial stab at sphinx documentation... could we get a build of the dev docs up?  Due to the need to generate PNG thumbnails of the altair plots, the doc build requires some marginally nontrivial setup via conda and nodejs. Let me know how to best record those commands for use with readthedocs.

**Comment by Carreau** [comment]
I'll do that as soon as i'm on a stable connection. If you are already
using conda on Travis, may I suggest looking at drdoctr/doctr ? It might be
simpler than RTD. Still young though.

**Comment by Carreau** [comment]
@jakevdp I believe you or Brian have  to visit https://github.com/ellisonbg/altair/settings/hooks/new?service=readthedocs to enable readthe docs.

You should have the right both on RT and on GitHub to do that. I'm not a github owner though.

**Comment by jakevdp** [comment]
I looked into it – it looks like readthedocs would not be able to build the full docs, because of the nodejs dependency for generating thumbnails from Altair images.

I see two options: use doctr to build on github pages (we should probably create an altair-viz org in that case for a better gh-pages URL) or generate and commit thumbnails locally so that the doc build only has Python dependencies.

Thoughts @ellisonbg?

**Comment by jakevdp** [comment]
We have the docs hosted on github pages. Still no auto-build, but we can address that at a later date.
