### ISSUE TITLE
Inconsistent behavior when faceting by rows

### ISSUE THREAD

**Issue by dbk123** [altair-viz/altair#2070]
I am plotting the incidence of new of new C-19 cases and noticed that the y-axis labels in the middle column are offset from the plot frame, while the left and right columns are not.  Does anyone have an explanation?  The behavior remains the same even if I plot the middle column by itself.

Thanks!

Here is the relevant code using to create the plot...

```python
VTplot = alt.Chart(VTSort).mark_bar().encode(
    x = alt.X('date:T', axis = alt.Axis(grid = False), timeUnit='yearmonthdate', scale=alt.Scale(domain=domain), title = 'Date'),
    y = alt.Y('new cases:Q', axis = alt.Axis(labels=False, grid = False), title = ''),
    color = 'new cases:Q',
    row = 'county').properties(width = 300, height = 50, title = 'Vermont - New Cases')

NHplot = alt.Chart(NHSort).mark_bar().encode(
    x = alt.X('date:T', axis = alt.Axis(grid = False), timeUnit='yearmonthdate', scale=alt.Scale(domain=domain), title = 'Date'),
    y = alt.Y('new cases:Q', axis = alt.Axis(labels=False, grid = False), title = ''),
    color = 'new cases:Q',
    row = 'county').properties(width = 300, height = 50, title = 'New Hampshire - New Cases')

MEplot = alt.Chart(MESort).mark_bar().encode(
    x = alt.X('date:T', axis = alt.Axis(grid = False), timeUnit='yearmonthdate', scale=alt.Scale(domain=domain), title = 'Date'),
    y = alt.Y('new cases', axis = alt.Axis(labels=False, grid = False), title = ''),
    color = 'new cases:Q',
    row = 'county').properties(width = 300, height = 50, title = 'Maine - New Cases')
VTplot |  NHplot | MEplot
```

![visualization-6](https://user-images.githubusercontent.com/16540538/78507229-e0259280-774c-11ea-9a2c-857fc1eb3234.png)

**Comment by RobbyJS** [comment]
Hello @dbk123 ,
Looking at the attached image, there seems to be a tiny bar for New Hampshire - Grafton that it is outside (at the left) of your specified date `domain`. I wonder if there is a data point there that is causing the trouble?

**Comment by dbk123** [comment]
@RobbyJS 

Great call!  You were exactly correct.   Thank you!!!
