### ISSUE TITLE
Prevent legend overflow?

### ISSUE THREAD

**Issue by tomhe** [altair-viz/altair#2071]
I have a Country legend below my chart which by default overflows on mobile devices in portrait orientation. To handle this I'm using:

`.configure_legend(orient="bottom", columns=4)`

This sort of works on mobile so that all Countries are visible:

<img width="424" alt="Screenshot 2020-04-06 at 09 59 47" src="https://user-images.githubusercontent.com/2315228/78536018-73160980-77ed-11ea-879e-7a8cc9a37e49.png">

But it does not look so good on desktop:

<img width="977" alt="Screenshot 2020-04-06 at 10 01 26" src="https://user-images.githubusercontent.com/2315228/78536236-cee09280-77ed-11ea-82e0-46fc0680e9b6.png">

Question: 

Are there any other way to solve this problem without using "columns"? I would prefer not using a fixed column count but rather have a dynamic wrapping so that the legend wraps on multiple rows if needed.

**Comment by Juan-132** [comment]
I’m interested in this as well, maybe a ‘wrap around’ setting to make the legend continue on the next line

**Comment by jakevdp** [comment]
I don't think there's any way to set a dynamic width for legends. It would be worth opening a feature request on Vega-Lite.

**Comment by tomhe** [comment]
OK, thanks.
