### ISSUE TITLE
Date axis labels are off by one

### ISSUE THREAD

**Issue by zit-cat** [altair-viz/altair#2077]
I have a time-series chart that I'd like to specify the tick labels for, but I can't seem to get the right dates to show up. An MWE looks like this:
```
import altair as alt
import pandas as pd

axis_dates = ['2020-03-01', '2020-03-08', '2020-03-15', '2020-03-22', '2020-03-29', '2020-04-05']

df = pd.DataFrame({
    'x': axis_dates,
    'y': [1, 3, 5, 6, 4, 2]
})

alt.Chart(df).mark_line().encode(
    x=alt.X('x:T', axis=alt.Axis(title='Date', format=("%b %d"), values=axis_dates)),
    y='y')
```
![image](https://user-images.githubusercontent.com/46611198/78914500-52dd8900-7a3f-11ea-9afc-43e5a9f1ce2d.png)

How can I make the chart use the dates in the DataFrame? Thank you.

I am using 4.1.0.

EDIT: fixed my code

**Comment by tonylee3399** [comment]
Hi zit-cat, I think you can do it this way. It works for me in Altair 4.0

```
import pandas as pd
import altair as alt

df = pd.DataFrame({
    'x': ['2020-03-01', '2020-03-08', '2020-03-15', '2020-03-22', '2020-03-29', '2020-04-05'],
    'y': [1, 3, 5, 6, 4, 2]
})

alt.Chart(df).mark_line().encode(
    x=alt.X('x:T', axis=alt.Axis(title='Date', format=("%b %d"), values=list(df['x'].values))),
    y='y')
```

**Comment by jakevdp** [comment]
The issue is you are not passing ISO8601 strings, so some browsers parse them as UTC time, and then they are displayed in local time by Vega-Lite. This is why Altair always outputs full ISO strings
(e.g. ``2010-01-01T00:00:00``) which javascript parses as local time. In general, the easiest way to deal with this is to always use pandas datetime type for time columns, then Altair takes care of the details for you.

**Comment by jakevdp** [comment]
e.g.
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'x': pd.to_datetime(['2020-03-01', '2020-03-08', '2020-03-15', '2020-03-22', '2020-03-29', '2020-04-05']),
    'y': [1, 3, 5, 6, 4, 2]
})

alt.Chart(df).mark_line().encode(
    x=alt.X('x:T', axis=alt.Axis(title='Date', format=("%b %d"))),
    y='y'
  )
```
![visualization - 2020-04-09T092406 249](https://user-images.githubusercontent.com/781659/78917563-e0bb7300-7a43-11ea-8fbd-7f7b25ded054.png)

**Comment by jakevdp** [comment]
(I suspect @tonylee3399 is at or east of the GMT line, which is why the code worked for him)

**Comment by tonylee3399** [comment]
@jakevdp Correct, i'm at GMT+8 zone.

Btw Jake, I think we still need to use the `values` parameter because @zit-cat wants to specifically use the dates listed in the `df['x']`. Or is it? 🤔

**Comment by zit-cat** [comment]
Thanks. But why does it not show Apr 5?

> ![visualization - 2020-04-09T092406 249](https://user-images.githubusercontent.com/781659/78917563-e0bb7300-7a43-11ea-8fbd-7f7b25ded054.png)

**Comment by zit-cat** [comment]
Actually, this gives me Apr 5.

```
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'x': pd.to_datetime(['2020-03-01', '2020-03-08', '2020-03-15', '2020-03-22', '2020-03-29', '2020-04-05']),
    'y': [1, 3, 5, 6, 4, 2]
})

alt.Chart(df).mark_line().encode(
    x=alt.X('x:T', axis=alt.Axis(title='Date', format=("%b %d"), values=list(df['x']))),
    y='y'
  )
```

**Comment by jakevdp** [comment]
The ticks in your first chart are spaced every two days, so the last point is April 5.

**Comment by jcastanon235** [comment]
I have the same problem, but, it is not entirely solved, because X-axis is solved, but the label of the interaction persists with the shifted -1 days value. Is this because of the use of tooltip? I use `pd.datetime(df['date_column'])` and i have my dates like `2022-06-10T00:00:00`, but still the problem in the tooltip.
![image](https://user-images.githubusercontent.com/88565239/187753642-39be6858-5fca-4feb-acf0-3a63eb3d0c72.png)

```
 lines = (
            alt.Chart(source)
            .mark_line(point="transparent")
            .encode(x=alt.X(f"{x}:T", axis=alt.Axis(
                title='Fecha de Transacción',
                grid=False)), 
            y=alt.Y(y, axis=alt.Axis(title='Monto', grid=False)))
            .transform_calculate(color='datum.amount < 0 ? "red": "green"')
        )

        points = (
            lines.transform_filter(hover)
            .mark_circle(size=65)
            .encode(color=alt.Color("color:N", scale=None))
        )

        tooltips = (
            alt.Chart(source)
            .mark_rule(opacity=0)
            .encode(
                x=alt.X(f"{x}:T"),
                y=y,
                tooltip=[alt.Tooltip(f"{x}:T", title='Fecha Transacción'), alt.Tooltip('amount', title='Monto')],
            )
            .add_selection(hover)
        )
```

**Comment by jakevdp** [comment]
The tooltip issue is a known bug in Vega/Vega-Lite: https://github.com/vega/vega-lite/issues/7185

**Comment by jcastanon235** [comment]
but how can i add `"scale": {"type": "utc"}` in python script

**Comment by jakevdp** [comment]
e.g. `alt.Tooltip(name, scale={'type': 'utc'})`

**Comment by jcastanon235** [comment]
I think scale is not a property because gives me this error:
`SchemaValidationError: Invalid specification altair.vegalite.v4.api.Chart, validating 'required' 'data' is a required property`

**Comment by jakevdp** [comment]
Ah, right, it looks like scale is not available in the version of vega-lite used by Altair.
