### ISSUE TITLE
automatically setting bin size in bar chart with datetime axis

### ISSUE THREAD

**Issue by RobbyJS** [altair-viz/altair#2078]
Hello,
I am relatively new to Python and quite new to Altair and Github, so sorry if my post doesn't completely adhere to what is required. 

I want to plot a bar chart with Altair. For the `x-axis` I use dataframe column which contains a `datetime` object. Each row contains a single day. The problem that I have is that I cannot find a way to adjust the bin size so that it fills the whole place available for the bin. So, if the range of days in the x-axis is small, the bins are separated. But if the range of days is large, the bins overlap between them, as you can see in the images. (in the example each data point is a month but it illustrates my problem).

If I set the x variable type to `"ordinal"`, the bar display is the one I desire (the bar fills the space), but the interactivity is lost for this axis, and the format of the dates is not nice (as it provides hour as well), so that doesn't solve my problem. What I would like is the bars display obtained when setting `type="ordinal"` but with the interactivity and the axis numbers format obtained when setting `type="temporal"`. The code to generate the images is below.

![bins_overlap](https://user-images.githubusercontent.com/53660555/78925862-6a972a80-7a9c-11ea-9fd1-5091e9398c97.png)
![bins_sparse](https://user-images.githubusercontent.com/53660555/78925868-6c60ee00-7a9c-11ea-9242-de27860c233a.png)
![x-ordinal](https://user-images.githubusercontent.com/53660555/78925871-6d921b00-7a9c-11ea-8668-6a52b4e3af69.png)

Code: 
```python
import altair as alt
from vega_datasets import data

source = data.stocks()

source = source[source["symbol"]=="MSFT"]
source = source[source["date"]>'2008-01-01']
alt.Chart(source).mark_bar().encode(
    x='date:T',
    y='price',
    color='symbol',
).properties(
            height=180,
            width=400,
            ).interactive()
```
Thanks in advance

**Comment by tonylee3399** [comment]
Hi @RobbyJS, you could specify a `timeUnit` parameter to bin `temporal` data. You could read this as [reference](https://altair-viz.github.io/user_guide/transform/timeunit.html).

For the `format` parameter, you can see the list [here](https://github.com/d3/d3-time-format#locale_format).

```
import altair as alt
from vega_datasets import data

source = data.stocks()

source = source[source["symbol"]=="MSFT"]
source = source[source["date"]>'2008-01-01']

alt.Chart(source).mark_bar().encode(
    x=alt.X('date:T', axis=alt.Axis(format="%Y", labelOverlap=False, labelAngle=-45, )),
    y='price',
    color='symbol',
).properties(
            height=180,
            width=400,
).interactive() & alt.Chart(source).mark_bar().encode(
    x=alt.X('date:T', timeUnit='month', axis=alt.Axis(format="%Y-%d-%b", labelOverlap=False, labelAngle=-45, )),
    y='price',
    color='symbol'
).properties(
            height=180,
            width=400,
).interactive()
```

![image](https://user-images.githubusercontent.com/16498167/78959462-99091a00-7b1d-11ea-9c5b-d4d97b2794fe.png)

**Comment by tonylee3399** [comment]
Hi @RobbyJS, I think we could tweak the visualization using `mark_bar(size=s)` parameter

Here is the [docs](https://altair-viz.github.io/user_guide/customization.html#adjusting-the-width-of-bar-marks) for your reference.

For the `format` parameter, you can see the list [here](https://github.com/d3/d3-time-format#locale_format).

```
alt.Chart(source).mark_bar(size=10).encode(
    x=alt.X('date:T', axis=alt.Axis(format="%Y-%b-%d", labelOverlap=False, labelAngle=-45)),
    y='price',
    color='symbol',
).properties(
    height=180,
    width=400,
).interactive()
```
![image](https://user-images.githubusercontent.com/16498167/78960279-2baab880-7b20-11ea-9095-4829b1624709.png)


I'm curious if there is a better way to set the margin offset of each bar instead of trial and error resetting the size of the bar. Do you have any suggestion on this @jakevdp ?

**Comment by tonylee3399** [comment]
There is another technique to bin `temporal` data. You could specify a `timeUnit` parameter to bin `temporal` data. You could read this as [reference](https://altair-viz.github.io/user_guide/transform/timeunit.html).

**Comment by jakevdp** [comment]
> There is another technique to bin temporal data. You could specify a timeUnit parameter to bin temporal data. You could read this as [reference](https://altair-viz.github.io/user_guide/transform/timeunit.html).

Agreed - I think time units are what you're looking for when binning temporal data:
```python
import altair as alt
from vega_datasets import data

source = data.stocks()

source = source[source["symbol"]=="MSFT"]
source = source[source["date"]>'2008-01-01']

alt.Chart(source).mark_bar().encode(
    x='yearmonth(date):T',
    y='price',
    color='symbol',
).properties(
    height=180,
    width=400,
).interactive()
```
![visualization - 2020-04-09T215209 830](https://user-images.githubusercontent.com/781659/78963448-62df8200-7aac-11ea-9bf4-81dcd694481f.png)

**Comment by RobbyJS** [comment]
Thank you very much for your answers. I had actually tried to use a `timeUnit` but when I did I used `"day"` or `"month"` as value and that groups all bars that have the same weekday or the same month, respectively. To avoid the data points from being grouped the  parameter value should be  `"yearmonthdate"` or `"yearmonth"`,  as in the example above. I mention this in case it is useful to someone else.

There is one thing though that I would like to modify from the output that can be seen in this last graph from @jakevdp. As you can see, when using the `timeUnit` parameter the ticks and labels are not aligned anymore with the bin, they are at the left of the corresponding bin. However, that is the case in the graph by @tonylee3399. Is there a way of correcting this (while keeping the `timeUnit` parameter for interactivity)?

**Comment by tonylee3399** [comment]
Hi @RobbyJS , i'm not sure if this is the best practice, but I used the `tickCount` to hard-code it. Is this what you were looking for?

```
alt.Chart(source).mark_bar().encode(
    x=alt.X('date:O'),
    y='price',
    color='symbol',
    tooltip='date'
).properties(
    height=180,
    width=400,
).interactive(bind_y=False) & alt.Chart(source).mark_bar(size=10).encode(
    x=alt.X('date:T', axis=alt.Axis(
        format="%Y-%b-%d", 
        labelOverlap=False, 
        labelAngle=-45,
        tickCount=len(source.date),
    )),
    y='price',
    color='symbol',
    tooltip='date'
).properties(
    height=180,
    width=400,
).interactive(bind_y=False)
```

![image](https://user-images.githubusercontent.com/16498167/78996673-a7841f80-7b77-11ea-82ba-965c63ca418c.png)

**Comment by RobbyJS** [comment]
Thanks for the quick answer. I don't necessarily want all ticks to be there. I just want that the ticks  and the labels that are there, are centered on the bars. And at the same time impose the `timeUnit` so that the bars fill the available width.

With the code below, even if x is of `"temporal"` type, the bins are centered on the ticks. However, when you set the `timeUnit` parameter, the bins are not longer centered on the tick, they are at the right of the tick (see the graph of jakevdp above). 

![bins_sparse_v2](https://user-images.githubusercontent.com/53660555/78998201-61fc2e00-7b48-11ea-9a91-af6bc94cf47d.png)

```python
import altair as alt
from vega_datasets import data

source = data.stocks()

source = source[source["symbol"]=="MSFT"]
source = source[source["date"]>'2008-01-01']

alt.Chart(source).mark_bar(size=10).encode(
    x=alt.X('date:T', axis=alt.Axis(
        format="%Y-%b-%d", 
        labelOverlap=False, 
        labelAngle=-45,
    )),
    y='price',
    color='symbol',
    tooltip='date'
).properties(
    height=180,
    width=400,
).interactive()```

**Comment by jakevdp** [comment]
Currently the tick locations are at the first of each month. You might try setting the tick locations at the 15th of each month if you want them to be in the middle of the bar.

Alternatively, you can use an ordinal type on your timeUnit encoding, in which case the bars are no longer represented on a continuous temporal scale, but rather a discrete ordinal scale with the labels at the center of the bar (you lose interactivity in this case, though, because the axis no longer represents a continuous quantity)

**Comment by RobbyJS** [comment]
I see, I will try that. Thanks for the quick answer

**Comment by morberg** [comment]
Is it possible to use weekly binning instead of monthly?

I was thinking [`TimeUnitParams`](https://altair-viz.github.io/user_guide/generated/core/altair.TimeUnitParams.html#altair.TimeUnitParams) might be a way to specify binning every 7 days by setting `step` to 7. Unfortunately I don't understand how to use a `TimeUnitParam` in the API and even Google can't find any examples using it.

**Comment by jakevdp** [comment]
Vega-Lite is working on adding a weekly time binning here: https://github.com/vega/vega-lite/issues/6349

In the meantime you can use parametrized time units; e.g.
```
alt.X('field', timeUnit=alt.TimeUnitParams(unit='day', step=7))
```
but note that this count will reset at the beginning of each month.

**Comment by morberg** [comment]
Thanks Jake, you are a superstar. I don't understand where you find the time to reply to all questions. Much appreciated.
