### ISSUE TITLE
interactive legend does not work for me

### ISSUE THREAD

**Issue by RobbyJS** [altair-viz/altair#2081]
Hello,
I am trying to plot a line graph with an interactive legend, following the code in the example [here](https://altair-viz.github.io/gallery/interactive_legend.html#), and it does not work. The same happens to me if I copy the example code and run it. The selection is applied when I click on a line or on an area element, but it does not work when clicking on the legend.

The graph is part of an app I am building with streamlit, I dont know if that could be the issue. If you want to see the example graph in the app it is [here](http://covid-app-spain.herokuapp.com/#)

My libraries as provided by `conda list`:
```
Name                    Version                      Build  Channel
altair                    4.0.1                      py_0    conda-forge
streamlit                 0.56.0                   pypi_0    pypi
```
I have checked the Vega source code of the graph in the example and on my app and they look the same. So I dont know where the problem might be, any help would be much appreciated.

**Comment by jakevdp** [comment]
Streamlit bundles an old version of the Vega-Lite javascript renderer in its frontend, which means some newer Altair features are not supported. I would suggest requesting that streamlit update their vega and vega-lite libraries; there's nothing that we can do from the Altair side to change how streamlit renders the charts.

**Comment by RobbyJS** [comment]
Alright, thanks a lot for the answer, I will get in touch with Streamlit for the update of their vega and vega-lite libraries.
