### ISSUE TITLE
getting below error while using altair

### ISSUE THREAD

**Issue by Pramod786** [altair-viz/altair#2082]
Error loading script: Unable to get property 'version' of undefined or null reference

The definition of the library is showing as:
Init signature:
alt.Chart(
    data=Undefined,
    encoding=Undefined,
    mark=Undefined,
    width=Undefined,
    height=Undefined,
    **kwargs,
)

**Comment by jakevdp** [comment]
Please post a complete code sample that reproduces the error.

**Comment by Pramod786** [comment]
import altair as alt

# altair plot 
alt.Chart(deaths_long).mark_line(strokeWidth=4, opacity=0.7).encode(
    x='Day',
    y='Deaths',
    color='Country/Region'
).properties(
    width=800,
    height=650
)

**Comment by jakevdp** [comment]
A few more questions:
- what is ``deaths_long``?
- what error are you seeing when you run this code?
-  what frontend are you using? (JupyterLab, notebook, streamlit?)

**Comment by Pramod786** [comment]
what is deaths_long? - is a dataframe i am using to generate the chart
what error are you seeing when you run this code? - Error loading script: Unable to get property 'version' of undefined or null reference
what frontend are you using? (JupyterLab, notebook, streamlit?) - I am using jupyter notebook

**Comment by jakevdp** [comment]
Thanks – context is quite important here. Can you paste the **exact and full** code snippet that leads to this error if you run it in a new notebook?

**Comment by Pramod786** [comment]
I have used the github repository:

https://github.com/hugobowne/COVID-19-EDA-tutorial

**Comment by jakevdp** [comment]
Thanks – I believe the error you're getting indicates that your browser is unable to load some of the necessary javascript libraries. Please confirm that you are online, and are not blocked by any firewall or other browser privacy setting. More information will likely be available in your browser's javascript console.

**Comment by Pramod786** [comment]
thanks. its working in chrome, but not in Microsoft edge and Explorer.

**Comment by jakevdp** [comment]
Ah, right. Having a modern browser matters, as mentioned in the first point here: https://altair-viz.github.io/user_guide/troubleshooting.html#chart-does-not-display-at-all

Glad you figured out the issue.
