### ISSUE TITLE
Colored step chart

### ISSUE THREAD

**Issue by jgonsior** [altair-viz/altair#2083]
I'd like to create a step chart, but color the steps based on a third dimension of the data.

So something like this (which is not working):

```python
import altair as alt
from vega_datasets import data

source = data.stocks()

alt.Chart(source).mark_line(interpolate='step-after').encode(
    x='date',
    y='price',
   step_color='new_dimension',
)
```

How can I achieve that?

**Comment by jakevdp** [comment]
Can you describe the expected result?

**Comment by jgonsior** [comment]
I want all steps which are having `'new_dimension' == 1 ` to be f. e. red, all steps where `'new_dimension' == 2 ` to be blue. So basically a line plot, where part of the line are colored based on a third property.
F. e. if I'm plotting a timeline, I'd like to have all parts of the line which are coming from Weekdays to be blue, and all which are from the Weekend to be red. When I tried that so far I've ended up with one line for Weekdays, and one line for weekends, but in fact I want both lines to be "concatenated".  
In a couple of hours I can also try to manually create such a plot using using Gimp.

**Comment by jakevdp** [comment]
In Altair, any single mark can only have one color. A line is a single mark, so it can only be a single color.

You might be able to achieve what you want by encoding by color and drawing multiple different-colored line segments, but there is no way to directly encode what you want (different colors on a single line) via Altair's grammar.

**Comment by jgonsior** [comment]
OK, thanks a lot, now I know at least that I can stop searching for an "easy way" in the documentation. If I successfully manage to do it with Altair using multiple different line segments I'll post my answer here, maybe it's helpful for other's too.

**Comment by joelostblom** [comment]
@jgonsior I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet or post your solution in the closed issue for others to find.
