### ISSUE TITLE
mark_line() and mark_bar() are leading to different values on the y axis for the same dataframe

### ISSUE THREAD

**Issue by rafaelmaguillaoliveira** [altair-viz/altair#2085]
Hey, folks! 

I'm currently exploring `altair` to compare it against other plotting python libs (such as `matplotlib` and `seaborn`) and I'm really enjoying the experience so far. However, I got stuck w/ a rather weird issue: when I try to plot the exact same data (from [this dataset](https://www.kaggle.com/ntnu-testimon/paysim1)) using `mark_bar()` and `mark_line()`, I get pretty different results on the values on the y axis. Below, you'll have a sample code w/ their respective results:

**1. Imports:**
```
import altair as alt
import pandas as pd
from toolz import curry
```

**2. Function to parse data to a JSON file before plotting (mainly to avoid issues related to huge datasets being plotted):**
```
def to_altair(x):    
    x.to_json('chart.json', orient='records', date_format='iso', default_handler = str)
    return('chart.json')
pd.DataFrame.to_altair = to_altair # attach to DataFrame objects
```

**3. Reading the data and adding a uuid column:**
```
@curry
def with_uuid(df):
    df["transaction__id"] = df.apply(lambda _: uuid.uuid4(), axis = 1)
    return df

transactions = pd.read_csv("PS_20174392719_1491204439457_log.csv")

transactions_with_id = transactions.pipe(with_uuid)
```

**4. Plotting:**
```
transactions_per_type_and_step = (transactions_with_id
                                  .groupby(["step", "type"])
                                  .agg({"transaction__id": "count"})
                                  .reset_index())

transaction_type_order = ["CASH_IN", "CASH_OUT", "DEBIT", "PAYMENT", "TRANSFER"]
transaction_type_colors = ["#48D1CC", "#6495ED", "#008000", "#FFA07A", "#4B0082"]
transaction_type_scale = alt.Scale(domain = transaction_type_order, 
                                   range = transaction_type_colors)

base = (alt
        .Chart(transactions_per_type_and_step.to_altair())
        .encode(
            x = alt.X("step:Q", 
                      axis = alt.Axis(title = "Step (Hour)")), 
            y = alt.Y("transaction__id:Q", 
                      axis = alt.Axis(title = "Total Transactions")),
            color = alt.Color("type:O", 
                              legend = alt.Legend(title = "Transaction Type", 
                                                  labelFontSize = 15, 
                                                  titleFontSize = 17), 
                              sort = transaction_type_order, 
                              scale = transaction_type_scale), 
            tooltip = ["step:Q", "type:O", "transaction__id:Q"])
        .properties(title = "Hourly # of Transactions", width = 1000, height = 500)
        .configure_title(fontSize = 30)
        .configure_axis(labelFontSize = 15, 
                        titleFontSize = 20))
```
**5.1 Running `base.mark_line()`**
![image](https://user-images.githubusercontent.com/31039122/79082235-99aad780-7cfa-11ea-9486-8a70af812b81.png)

**5.2 Running `base.mark_bar()`**
![image](https://user-images.githubusercontent.com/31039122/79082248-adeed480-7cfa-11ea-8789-1ee56a78f1e1.png)

From the images above, we can see 2 issues:
- Why do `PAYMENT` and `DEBIT` appear only on the line plot, but not on the bar plot? My hunch is that the bars are overlaying instead of stacking, but how could this be happening?

**Comment by rafaelmaguillaoliveira** [comment]
[UPDATE] It seems that my hunch was correct: the bars are overlaying instead of stacking... when I add `stack = "normalize"` to the `encoding` part, the `CASH_IN` and`DEBIT` types appear. You can see the result below:

![image](https://user-images.githubusercontent.com/31039122/79086834-e353ec00-7d13-11ea-8950-042205078fd3.png)

However, the chart that I need is the stacked but not normalized one, so I still need a helping hand here

**Comment by jakevdp** [comment]
If the x axis is quantitative rather than ordinal or nominal, stack defaults to False. You can change this by setting ``stack=True`` in the y encoding

**Comment by rafaelmaguillaoliveira** [comment]
@jakevdp oh, I see! setting `stack = True` worked, thank you very much!

IMO, the default for `stack` should always be the same for all data types. In other words, `stack` should always default to either `True` or `False` regardless of the data type on the x axis. 

I believe it would be much more friendly for users - they wouldn't need to memorize the default for each data type. WDYT? Also, if there's a reason for the default to change across data types, where can I find the documentation for that?

**Comment by jakevdp** [comment]
To be clear, that default is set in Vega-Lite, not in Altair, so any change would have to be proposed there.

I think the reasoning behind it is that for quantitative encodings, in general it's not guaranteed that x values would be shared between different categories, so stacking by default is not preferred. For nominal and ordinal encodings, x values generally are shared between categories, so stacking makes the most sense.

**Comment by rafaelmaguillaoliveira** [comment]
@jakevdp ok, I see. Tks for the clarification 😄
