### ISSUE TITLE
Ability to use local js instead of CDN

### ISSUE THREAD

**Issue by armsp** [altair-viz/altair#2086]
I think because of restrictions and firewall on my work laptop whenever I try plotting anything in Juyterlab, I get the following error -
```
Error loading script: https://cdn.jsdelivr.net/npm//vega@5?noext
```
I can however download those vega js libraries and have them locally. So I was wondering if it is possible to configure altair to provide paths to local js libraries instead of using a CDN?

If not, then I'd like to help. Maybe we can have this as a configuration or subclass the code responsible for adding these CDNs to change the path to local files. Let me know the code that is responsible for that I would take a look.

**Comment by jakevdp** [comment]
You can do this in a couple ways: You can use altair_viewer for offline viewing on any frontend; see https://altair-viz.github.io/user_guide/display_frontends.html#altair-viewer. if you are on Jupyter Notebook or JupyterLab, another approach is to use the appropriate frontend extension (see https://altair-viz.github.io/user_guide/display_frontends.html#displaying-in-jupyterlab).

**Comment by armsp** [comment]
I installed `node.js` using conda.
I installed the extension - `$ jupyter labextension install @jupyterlab/vega5-extension`
also installed `altair_viewer` and `vega`, then I tried `alt.renderers.enable('mimetype')` and `alt.renderers.enable('notebook')`  too for viewing in VSCode but it didn't work. I get the following message -
```
<vegalite 4 object>
If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see
https://altair-viz.github.io/user_guide/troubleshooting.html
```
In my JupyterLab though, when I look at the extension manager I see that nothing is installed. Also searching for `@jupyterlab/vega5-extension` leads me to `ibis-vega-transform` extension.  

I also tried `jupyter labextension list` from terminal which says that **nothing** is installed despite running `$ jupyter labextension install @jupyterlab/vega5-extension` multiple times.

My lupyterlab version is **1.2.6**. I tried to update it using conda but it looks like the version is locked.

In JupyterLab, I tried with all i.e 'default`, 'html`, `mimebundle`, `mimetype`, `notebook` but none of them worked. I guess since the extension is not installing nothing will matter.

When I try `$ jupyter labextension install vega5-extension` I see that its not a valid extension.

I tried it in Spyder, however I get the following error when I do `chart.show()` -
`AttributeError: 'Chart' object has no attribute 'show'`

Kinda lost over here.

**Comment by jakevdp** [comment]
The vega-5 extension is here: https://jupyterlab.github.io/jupyterlab/vega5-extension/ If you're having trouble installing it, I'd suggest asking on the jupyterlab forums.

If ``alt.Chart`` has no ``show()`` attribute, it means that you're using an older version of Altair. Update to version 4.1 and it should work.

**Comment by armsp** [comment]
`chart.show()` works after upgrading to altair 4.1.0. But the jupyterlab issue remains.

**Comment by jakevdp** [comment]
Frontend extensions are tricky (it's one of the reasons we moved away from requiring them). Make certain you've installed the extension in the environment used by the kernel manager, not the kernel used by the runtime (though they are often the same) and be sure to restart your jupyterlab process after updating extensions. If you're still having trouble gettig the extension installed, try asking in the Jupyter forums.

**Comment by josecaloca** [comment]
I faced this issue due to firewall on my work laptop on JupyterLab. The solution for that was to enable Altair to work offline.

First make sure you have installed altair in your environment

```python
import altair as alt
alt.renderers.enable('mimetype')
```

Then you'll be able to run your `Aequitas` graphs offline:

```python
ap.absolute(bdf, metrics, 'protected_attribute', fairness_threshold = disparity_tolerance)
```
