### ISSUE TITLE
Apparent incompatibility with interval selection type and fields kwarg

### ISSUE THREAD

**Issue by amcadie** [altair-viz/altair#2090]
Hi - I'm trying to create a panel of two plots with cross-filtering.  I'd like to use the interval selection to brush an area, and have the selected points filter the second plot with values from a third column.  I'm able to get the desired behavior with the "single" or "multi" selection types, but the interval type causes a JavaScript Error:

Javascript Error: Expression parse error: ? selector006_scale_trigger : {}
This usually means there's a typo in your chart specification. See the javascript console for the full traceback.

Here is a minimal reproducible example (run on Python 3.7.7, Altair 4.0.0):

```
import altair as alt
import pandas as pd

df = pd.DataFrame({'col1':[1, 2, 3, 4, 5, 6], 'col2':['a', 'a', 'a', 'b', 'b', 'b']})
df['col3'] = df['col1'] * 2

selector = alt.selection(#type = 'single', #works
                         #type = 'multi', #works
                         type = 'interval', #Javascript Error: Expression parse error...
                         empty = 'all',
                         fields = ['col2'])

points = (alt.Chart(df)
          .mark_point()
          .encode(x = 'col1', y = 'col3')
          .add_selection(selector)
          .properties(height = 300, width = 300)
         )

lines = (alt.Chart(df)
         .mark_line()
         .encode(x = 'col1', y = 'col3', color = 'col2')
         .transform_filter(selector)
         .properties(height = 300, width = 300)
        )

points | lines
```
Thanks for looking, and thanks for all your work on Altair!  I'm really enjoying it so far.

**Comment by jakevdp** [comment]
I don't think interval selections support projection to anything but the x and y coordinates. This is a known issue in Vega-Lite, but I'm not able to find the reference at the moment.

**Comment by amcadie** [comment]
Thanks for the quick response Jake!  I can figure out another strategy for the chart that I'm trying to put together.

Do you think it would be helpful to raise a ValueError, or perhaps a warning, that the fields kwarg is currently unsupported in the IntervalSelection class?  I was just poking around in the source code, and the fields kwarg is currently included in the IntervalSelection [constructor](https://github.com/altair-viz/altair/blob/17e340633929242f9e80ebd29920abae7867ca05/altair/vegalite/v4/schema/core.py#L13783).

If it would be a help to put in some kind of error handling, I could take a stab at it.

**Comment by jakevdp** [comment]
No, the policy of Altair is to pass any specifications that are valid according to the vega-lite schema to Vega-Lite. Early on we tried doing input checking on the Python side, but this turned out to be very brittle and hard to maintain as the Vega-Lite library evolved.

**Comment by jakevdp** [comment]
(Note that ``IntervalSelection``, and everything in the ``core.py`` module, is automatically generated from the schema)

**Comment by amcadie** [comment]
Oh, ok, that makes sense.  Well thanks again for the help!
