### ISSUE TITLE
Add blank dropdown option that doesn't filter

### ISSUE THREAD

**Issue by ZaxR** [altair-viz/altair#2096]
I have a chart with a dropdown selector, and  the selection is responsible for filtering the data displayed in the chart. I'm trying to add a "blank" option to the binding_select that will result in no filtering (i.e. "display all data"). Is there an easy way to do that? 

I was looking at alt.condition and filter predicates, but wasn't able to figure it out. I was playing with the following example, where i'd want an "All" selection in the binding_select:

```
import altair as alt
from vega_datasets import data


cars = data.cars.url

input_dropdown = alt.binding_select(options=['All', 'Europe','Japan','USA'])
selection = alt.selection_single(fields=['Origin'],
                                 bind=input_dropdown,
                                 name='Country of ',
                                 init={'Origin': 'Europe'})
color = alt.condition(selection,
                    alt.Color('Origin:N', legend=None),
                    alt.value('lightgray'))

alt.Chart(cars).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color='Origin:N',
    tooltip='Name:N'
).add_selection(
    selection
).transform_filter(
    selection
   # Looking for something like <no filter> if selection == 'All' else selection
)
```

Thanks for the library and for the help!

**Comment by jakevdp** [comment]
It's a bit hacky, but this works:
```python
alt.Chart(cars).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color='Origin:N',
    tooltip='Name:N'
).add_selection(
    selection
).transform_filter(
   f"({selection.Origin}[0] == 'All') || ({selection.Origin}[0] == datum.Origin)"
)
```
It would be nice to update the altair expression syntax so that this condition could be written like this instead:
```python
(selection.Origin[0] == 'All') | (selection.Origin[0] == alt.datum.Origin)
```

**Comment by ZaxR** [comment]
Thanks for the quick response. 


That syntax doesn't seem to be working for me - am I doing something wrong? Here's what I get when I try (w/ Altair 4.1.0, vega 3.2.0):
![Screen Shot 2020-04-18 at 2 18 57 PM](https://user-images.githubusercontent.com/19669890/79669211-9478dd00-817f-11ea-9c68-5fc0d2c63a77.png)

**Comment by ZaxR** [comment]
Looks like adding `None` as an option works, and the associated label is `null`. Not ideal, but does the right thing it looks like:

![Screen Shot 2020-04-18 at 2 39 08 PM](https://user-images.githubusercontent.com/19669890/79669620-65b03600-8182-11ea-8f66-f263f445ec72.png)

**Comment by jakevdp** [comment]
Oh, sorry, you have to use selection names that are valid identifiers. Try this:
```python
import altair as alt
from vega_datasets import data

cars = data.cars.url

input_dropdown = alt.binding_select(options=['All','Europe','Japan','USA'], name="country")
selection = alt.selection_single(fields=['Origin'],
                                 bind=input_dropdown,
                                 init={'Origin': 'Europe'})

alt.Chart(cars).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color='Origin:N',
    tooltip='Name:N'
).add_selection(
    selection
).transform_filter(
   f"({selection.Origin}[0] == 'All') || ({selection.Origin}[0] == datum.Origin)"
)
```

**Comment by ZaxR** [comment]
Awesome - thanks!

**Comment by joelostblom** [comment]
@ZaxR I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
