### ISSUE TITLE
Theme with color scheme doesn't apply to concat/layer charts

### ISSUE THREAD

**Issue by debbes80** [altair-viz/altair#2098]
I want to set a different default color scheme for all charts in my notebook. It works on single charts, but as soon as I do concat or layer, the default color scheme is applied (viridis) for some reason.
How can I change the global color scheme for all charts?

```python
def coolwarm():
    return {"encoding": {"color": {"scale": {"scheme": "redblue"}}}}
alt.themes.register('coolwarm', coolwarm)
alt.themes.enable('coolwarm')

# Compute x^2 + y^2 across a 2D grid
x, y = np.meshgrid(range(-5, 5), range(-5, 5))
z = x ** 2 + y ** 2
w = x ** 3 + y ** 3

# Convert this grid to columnar data expected by Altair
source = pd.DataFrame({'x': x.ravel(),'y': y.ravel(),'z': z.ravel(),'w' : w.ravel()})

base = alt.Chart(source).mark_rect().encode(
    x='x:O',
    y='y:O',
)

display((base.encode(color='z:Q') | base.encode(color='w:Q')).resolve_scale(color='independent'))
display(base.encode(color='z:Q'))
}
```

![visualization_scheme](https://user-images.githubusercontent.com/54935651/79670052-62d43600-81c0-11ea-9b09-8ecc536ec76b.png)
![visualization_scheme2](https://user-images.githubusercontent.com/54935651/79670081-ac248580-81c0-11ea-9ecd-1c30bbefffd7.png)

**Comment by jakevdp** [comment]
I think what you're looking for is this:
```python
def coolwarm():
    return {"config": {"range": {"heatmap": {"scheme": "redblue"}}}}
```
More information on configuration options here: https://altair-viz.github.io/user_guide/configuration.html

The reason your approach worked for a single chart and not a layered chart is that you were not setting the configuration, you were setting the encoding. For a single chart, specifying an encoding is valid. For a layer chart, specifying an encoding at the top level is not valid.

**Comment by debbes80** [comment]
OK, that indeed works! Thanks.

I was looking into the themes as I wasn't able to find out how to use configure_scale(), so now I figured out it was:
```python
.configure_range(heatmap = alt.RangeScheme(scheme='redblue'))
```
