### ISSUE TITLE
Scale Units

### ISSUE THREAD

**Issue by chris-b1** [altair-viz/altair#210]
It's possible I missed this in the examples/documentation, but is there a way to change the plain numerical units used in scales?

Example below - instead of the `'m'`, which I guess is per/1000s, I'd like either %s or plain floats (`[0.03, 0.04, 0.05]`)  Thanks!

``` python
import pandas as pd
from altair import Chart
df = pd.DataFrame({'x': [0.03, 0.04, 0.05], 'y': [10, 35, 39]})
Chart(df).mark_circle().encode(x='x', y='y')
```

![vega 1](https://cloud.githubusercontent.com/assets/1924092/18790042/e42ed69e-8172-11e6-8559-14dbb40cc9bc.png)

**Comment by chris-b1** [comment]
Turns out I needed the `format` attribute of the `Axis`.  Format codes follow the d3 spec here
https://github.com/d3/d3-format/blob/master/README.md#format
https://vega.github.io/vega-lite/docs/axis.html

```python
from altair import Axis, X

(Chart(df).mark_circle()
 .encode(X('x', axis=Axis(format='%')), y='y'))
```

![vega 2](https://cloud.githubusercontent.com/assets/1924092/18791356/0118bc16-8178-11e6-98cb-788e2abfdc20.png)

Feel free to close this, or can use this as case needing docs

**Comment by jakevdp** [comment]
Thanks – glad you figured it out! Scales seem to be a common confusion (see also https://github.com/altair-viz/altair/issues/191) so we'll have to add a doc section on that. I'm going to keep this open as a reminder.

**Comment by jakevdp** [comment]
docs added in 1f6d1aaaba74b807430b8452592a3635336644cf
