### ISSUE TITLE
Options of `point` argument

### ISSUE THREAD

**Issue by echasnovski** [altair-viz/altair#2100]
Documentation of `point` argument in marks isn't very easily discoverable.

Recently I tried to create a chart with colored line and points. My first try was with `mark_line(color="red", point=True)`, similarly to [this example](https://altair-viz.github.io/gallery/line_chart_with_points.html), but it produced red line with blue points. This turned out to be current default behavior of Vega-lite (found in [this issue](https://github.com/vega/vega-lite/issues/6111)).

After some digging, I found that `point` can be "an object defining the properties of the overlayed points." (which seems to imply `OverlayMarkDef`, but simple dictionary showed to be enough). I think it would be really helpful to have this slightly easier to find. A "Line chart with points" example seems like a good place.

So, what do you think about adding some sort of variation of the following code snippet in that example?
```python
import altair as alt
import numpy as np
import pandas as pd

x = np.arange(100)
source = pd.DataFrame({"x": x, "f(x)": np.sin(x / 5)})

# Only this part will be added
alt.Chart(source).mark_line(
    color="red", point={"color": "red"}
).encode(
    x="x",
    y="f(x)"
)
```
![issue_altair_point-argument_example](https://user-images.githubusercontent.com/24854248/79694414-c5890880-8278-11ea-884b-ab9d4969b717.png)

If this is OK, I would like to help with PR. Thanks.

**Comment by jakevdp** [comment]
Sure, sounds good. I'd have a slight preference for using
```
point=alt.OverlayMarkDef(color='red')
```
because then people who are using editors with docstring/tab completion support can more easily see all the available options.
