### ISSUE TITLE
Multiple conditions for changing chart colors

### ISSUE THREAD

**Issue by rafaelmaguillaoliveira** [altair-viz/altair#2101]
Hey, folks!

I was following [this example](https://altair-viz.github.io/gallery/bar_chart_with_highlighted_bar.html) on how to highlight values on a bar chart and it works just fine. However, I'd like to have multiple conditions to change chart colors, so to highlight multiple values using multiple different colors. For instance, I have this example that generates a waterfall chart:

**- Generating the DataFrame**
```
components = [ 
    "Historical Peak",
    "Effect 1", 
    "Effect 2", 
    "Effect 3", 
    "Regular Levels"]
waterfall = pd.DataFrame(
    {"component": components, 
     "start": [.0, .1, .02, .03, .0], 
     "end": [.1, .02, .015, .015, .03]
    })

waterfall = waterfall.assign(**{"red": waterfall["component"].isin(["Effect 1", 
                                                                    "Effect 2"])})
```
**- Plotting**
```
(alt.Chart(waterfall)
 .mark_bar()
 .encode(
     y2=alt.Y2("end:Q"),
     y=alt.Y("start:Q", axis = alt.Axis(grid=False, title = "Level")),
     x=alt.X("component:N", 
             sort = components,
             axis = alt.Axis(title = "Components", 
                             labelAngle = 0)), 
     color = alt.condition(alt.datum.red == True, 
                           alt.value("red"), 
                           alt.value("blue")))
 .properties(title = "Impacts", 
             width = 1000, 
             height = 500)
 .configure_title(fontSize = 30)
 .configure_axis(labelFontSize = 15, 
                 titleFontSize = 25))
```

**- Result**
![image](https://user-images.githubusercontent.com/31039122/79701868-db95c980-8276-11ea-85ed-e2405cd54fa1.png)

How can I add a condition that makes the values for `Effect 3` green, for instance? Whilst still making the values for `Effect 1` and `Effect 2` red, of course

**Comment by jakevdp** [comment]
Once you start having multiple if-then statements for a condition, it makes more sense to use the color scale functionality to encode colors. You can specify custom colors using the scale domain and range:
```python
(alt.Chart(waterfall)
 .mark_bar()
 .encode(
     y2=alt.Y2("end:Q"),
     y=alt.Y("start:Q", axis = alt.Axis(grid=False, title = "Level")),
     x=alt.X("component:N", 
             sort = components,
             axis = alt.Axis(title = "Components", 
                             labelAngle = 0)), 
     color=alt.Color('component',
                     scale=alt.Scale(
                         domain=waterfall.component.tolist(),
                         range=['blue', 'red', 'red', 'green', 'blue'])))
 .properties(title = "Impacts", 
             width = 600, 
             height = 300)
 .configure_title(fontSize = 30)
 .configure_axis(labelFontSize = 15, 
                 titleFontSize = 25))
```
![visualization - 2020-04-19T163111 641](https://user-images.githubusercontent.com/781659/79702627-328da580-825b-11ea-931b-476af8fb1f6f.png)

**Comment by rafaelmaguillaoliveira** [comment]
oh, I didn't realize that `colors` could be used like that - I'm still getting the hang of it. Thanks for the clarification 😃

**Comment by patriciatiffany** [comment]
Is it possible to have multiple if-statements, though? I have a case where the color scale functionality doesn't apply / is already being used for something else. I've been trying this and running into errors (i.e., SchemaValidationError: "Invalid specification
altair.vegalite.v4.api.Chart, validating 'required'
'data' is a required property")

**Comment by patriciatiffany** [comment]
@jakevdp Is there a way to add multiple conditions, though? 

I have a case where the color scale functionality isn't appropriate / is already being used by something else. (Specifically, I want the condition to switch between different color scales.)

I've been running up against this error when I try nesting multiple conditions: 
SchemaValidationError: Invalid specification
altair.vegalite.v4.api.Chart, validating 'required'
'data' is a required property

**Comment by jakevdp** [comment]
No, unfortunately Vega-Lite does not support having multiple color scales. You can only switch between a color scale and a constant.

**Comment by patriciatiffany** [comment]
@jakevdp Okay. Thanks for the quick reply. Can you switch between one color scale and 2 constants (on 2 different conditions)?

**Comment by dmf95** [comment]
@jakevdp thanks for the clarification on the support of multiple color scales. Nonetheless, I am still wondering if there is a method to achieve my multi-condition color issue...

I have successfully implemented a simple condition on value "a" to set color "1" and color "2" through the below color params:
`color=alt.condition(alt.datum.avg_compound_score > 0,
                            alt.value("#99D9D9"),  # The positive color
                            alt.value("E9072B"))  # The negative color`

I would like to add another condition on value "b" to set color "3", regardless of value "a".

Below is the current & desired output. 
![image](https://user-images.githubusercontent.com/48701668/125383863-f0afba00-e34c-11eb-9e78-2ca06bb9bdf4.png)

Any feedback is welcome!

**Comment by joelostblom** [comment]
@dmf95 VegaLite supports multiple selections in the same condition, but I don't think it is possible to write within alt.Condition. However, you can see the alt.Condition returns a dictionary so you could write this directly passing a list of selections. [I gave an example here for selections previously](https://stackoverflow.com/questions/66108224/combine-hover-and-click-selections-in-altair/66109641#66109641), you can try adapting it to your needs by studying how the output dictionary from `alt.condition(alt.datum.avg_compound_score > 0, alt.value("#99D9D9"), alt.value("E9072B"))` looks.
