### ISSUE TITLE
Is it possible to add conditions for combining multiple selections?

### ISSUE THREAD

**Issue by TristanK27** [altair-viz/altair#2108]
I want to create an interactive 'legend' that allows me to select combinations of the data in different columns.
For example if we have this data:
```
data = {
    'type1': [1, 0, 0, 1, 0, 1],
    'type2': [1, 1, 1, 1, 0, 0],
    'type3': [1, 0, 0, 1, 1, 0],
    'id': ['test1', 'test2', 'test3', 'test4', 'test5', 'test6'],
    'fuel': [1, 10, 30, 50, 25, 20]
}
df = pd.DataFrame(data, columns=['id', 'fuel', 'type1', 'type2', 'type3'])
```
which results in:
![image](https://user-images.githubusercontent.com/20356336/79977610-d74bf500-849e-11ea-8142-ba4c1e4234af.png)
I now want the ability to visualize the combinations of different 'types'.
Something like this:
![image](https://user-images.githubusercontent.com/20356336/79977927-60fbc280-849f-11ea-9c3b-25869dba9ebc.png)
So if I toggle only type1, only test6 should be shown. If I toggle all the types, only test4 and test1 should be shown.
The ideal solution would be to do this with a single legend, is it possible to achieve this?
Also Is this possible to achieve this with multiple charts like I am trying to do in the image above?
I can't seem to figure this out.

**Comment by jakevdp** [comment]
Answered on StackOverflow: https://stackoverflow.com/questions/61364509/altair-cant-create-combination-of-selections/61365345#61365345

**Comment by TristanK27** [comment]
Thank you so much!!
