### ISSUE TITLE
Compound chart fails with faceted sub chart 

### ISSUE THREAD

**Issue by mansenfranzen** [altair-viz/altair#2109]
Hi together,

first I would like to thank you for all the efforts on this great library. It is my favorite tool for exploratory data analysis.

The problem I'm encountering is related to compound charts. Basically, there are two sub plots (bar and rect) which share the same data but are encoded differently. More specifically, the bar plot uses row faceting which might be the issue here. Here is a toy example:

```python

import numpy as np
import pandas as pd
import altair as alt

# create some dummy data
size = 30
data = dict(
    dates=pd.date_range(start="2020-01-01", freq="d", periods=size),
    categorical=np.random.randint(0, 5, size=size),
    quantitive=np.random.rand(size),
)

df = pd.DataFrame(data)

# bar plot
plot_bar = (
    alt.Chart(df, width=400, height=40).mark_bar()
    .encode(
        alt.X("yearmonthdate(dates):O"),
        alt.Y("quantitive:Q", title=None),
        alt.Row("categorical:O"))
)

# rect ploct
plot_rect = (
    alt.Chart(df, width=400, height=100).mark_bar()
    .encode(
        alt.X("yearmonthdate(dates):O"),
        alt.Color("quantitive:Q", title=None),
        alt.Y("categorical:O"))
)

# vconcat
compound = plot_bar & plot_rect

```

Each subplot by itself displays as expected:

![image](https://user-images.githubusercontent.com/18086180/80193426-11410680-8619-11ea-9a3c-ace93d3bc4f7.png)

![image](https://user-images.githubusercontent.com/18086180/80193467-2322a980-8619-11ea-8c83-8642b710be4c.png)

However, the compound chart breaks:

![image](https://user-images.githubusercontent.com/18086180/80193520-3b92c400-8619-11ea-8b0f-058a396c80f4.png)

I was surprised by this behavior because I believe it that it used to work in the past with other examples. Hence, I tested a different vega lite version:

```python

compound.save("SOME_PATH.html", vegalite_version='3.1.0')

```

![image](https://user-images.githubusercontent.com/18086180/80193664-8f051200-8619-11ea-939e-fafb65486dd5.png)

All vega lite versions starting with 4.0.0 break, so I guess this issue is rather related to vega lite than to altair.

**Comment by jakevdp** [comment]
Yes, this appears to be an issue in Vega-Lite. Would you like to report it there?

**Comment by jakevdp** [comment]
I reported it, using a built-in dataset so the reproduction is more concise.: https://github.com/vega/vega-lite/issues/6397

**Comment by joelostblom** [comment]
The provided example is working as expected for me on Altair 4.2.0 so I'm closing this, please re-open if you are still seeing the issue.
