### ISSUE TITLE
Format text when displaying an aggregate

### ISSUE THREAD

**Issue by nneibaue** [altair-viz/altair#2112]
I have a dashboard containing many linked plots, and I want to display the total count of the number of points selected. I can do this easy enough via the following:

```
counts = alt.Chart(cu_points).transform_filter(selection).mark_text(
      dy=-20,
      baseline="top",
      align="left"
  ).encode(
      x=alt.value(100),
      y=alt.value(5),
      text='count()',
  )
```

However, I want to have some other text along with the count, something along the lines of:
`text="Number of points selected" + 'count()`

I have tried using `transform_calculate` to accomplish this, but it creates one copy of the text for each point and renders them on top of each other. The only workaround I have had any success with is by layering a separate chart using fake data that only has a single point

```
counts = alt.Chart(cu_points).transform_filter(selection).mark_text(
      dy=-20,
      baseline="top",
      align="left"
  ).encode(
      x=alt.value(100),
      y=alt.value(5),
      text='count()',
  ) + alt.Chart(pd.DataFrame.from_dict({"data": {"foobar": None}})).mark_text(
    align="left",
    baseline="top",
    dy=-20
).encode(
    x=alt.value(0),
    y=alt.value(5),
    text=alt.value("# Pixels Selected: ")
)
```

This (along with the rest of the chart's code) produces the following dashboard, however it doesn't _feel_ like a very elegant solution. Is there another, less hacky way to accomplish this?

![image](https://user-images.githubusercontent.com/9022917/80252556-b3bab300-8634-11ea-870c-982ce49fea3a.png)

**Comment by jakevdp** [comment]
``transform_calculate`` is the way to do this. It would look something like this (untested because I don't have the data):
```python
counts = alt.Chart(cu_points).transform_filter(
      selection
  ).transform_aggregate(
      count='count()'
  ).transform_calculate(
      text="Number of points selected: " + alt.datum.count
  ).mark_text(
      dy=-20,
      baseline="top",
      align="left"
  ).encode(
      x=alt.value(100),
      y=alt.value(5),
      text='text:N',
  )
```

**Comment by nneibaue** [comment]
Thanks...this worked great! The part I was missing was the `transform_aggregate` function. Also I didn't realize I could use the `alt.datum` syntax. That's pretty handy!
