### ISSUE TITLE
Is it possible to replicate this tick chart from New York Times?

### ISSUE THREAD

**Issue by armsp** [altair-viz/altair#2115]
I am trying to get as close as possible with the tick graph [here](https://www.nytimes.com/interactive/2020/world/coronavirus-maps.html) -
![image](https://user-images.githubusercontent.com/12681262/80309132-96cadf00-87f0-11ea-9958-0fd9c9b34b73.png)
I have got around to this -
![nyt-us](https://user-images.githubusercontent.com/12681262/80309214-38523080-87f1-11ea-84dc-be4f8a509f73.png)
using the same dataset with the following code  -
```py
# Data Preparation
url = "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us.csv"
udf = pd.read_csv(url)
udf['new_cases'] = udf['cases'].diff()
# Charting
q = alt.Chart(udf).mark_tick(size=20, thickness=4).encode(
    x='date:T',
    color=alt.Color('new_cases:Q', scale=alt.Scale(scheme='oranges'), bin=alt.Bin(divide=[2]))
).configure_view(
    strokeWidth=0
)
q
```
As you can see that the looks are not that great.
I tried with ` blend='luminosity'` and `blend='darken'` following too, blend darken doesn't look great, blend luminosity looks better - but the color is lost.

Can you suggest any further improvements or is this the best we can have with the latest version?

**Comment by jakevdp** [comment]
What specifically are you hoping to change in the chart you produced?

**Comment by armsp** [comment]
1. Is it a good idea to let the bars overlap and blend or to keep them separate with 0 distance? I haven't understood blend properly from the docs.
2. I haven't figured out how to have 0 distance between the ticks(bars).
3. Also the colors look off.
4. Can we also specify custom bins? The issue is that for the EXACT same data our graphs look incredibly different. Perhaps being able to change that would help.

**Comment by jakevdp** [comment]
Rather than using overlapping ticks, it is probably better to use time-binned data with a rect mark. Something like this:
```python
import altair as alt
import pandas as pd

# Data Preparation
url = "https://raw.githubusercontent.com/nytimes/covid-19-data/master/us.csv"
udf = pd.read_csv(url)
udf['new_cases'] = udf['cases'].diff()

# Charting
alt.Chart(udf).mark_rect(size=20, thickness=4).encode(
    x='yearmonthdate(date):O',
    color=alt.Color('new_cases:Q', scale=alt.Scale(scheme='oranges'), bin=alt.Bin(divide=[3]), legend=None)
).configure_view(
    strokeWidth=0
).properties(
    width=600
)
```
![visualization - 2020-04-26T131354 100](https://user-images.githubusercontent.com/781659/80318551-cd3c3600-87bf-11ea-96bd-d57bb1d05675.png)

You can then adjust the axis properties and color scale to match the original more closely if you wish.

**Comment by armsp** [comment]
This works great, thanks !!
