### ISSUE TITLE
Create dashed line based on condition

### ISSUE THREAD

**Issue by rafaelmaguillaoliveira** [altair-viz/altair#2116]
Hey, folks!

Is there a way to use conditions do change the `strokeDash` on a line chart? 

I have a dataframe w/ some projections for 2020, including (1) a baseline scenario and (2) several other stressed scenarios. I'd like to plot them on a single chart (that is, one line per scenario), and highlight the baseline one by making it dashed. Is it possible?

**Comment by jakevdp** [comment]
You can use the ``strokeDash`` encoding with a condition. For example:
```python
import altair as alt
from vega_datasets import data

source = data.stocks()

alt.Chart(source).mark_line().encode(
    x='date',
    y='price',
    color='symbol',
    strokeDash=alt.condition(
        alt.datum.symbol == 'GOOG',
        alt.value([5, 5]),  # dashed line: 5 pixels  dash + 5 pixels space
        alt.value([0]),  # solid line
    )
)
```
![visualization - 2020-04-26T201243 979](https://user-images.githubusercontent.com/781659/80330555-51131400-87fa-11ea-8d6d-0bfcf540bd3e.png)

**Comment by rafaelmaguillaoliveira** [comment]
@jakevdp I imagined that I could use conditions for that, but didn't know exactly how... tks for the quick response!

Where is this behaviour documented, btw? For me, it's not obvious that `alt.value([5, 5])` corresponds to a dashed line w/ 5 pixels  dash + 5 pixels space (or that `alt.value([0])` corresponds to a solid line). What if I wanted a dotted line, for instance? How would it work?

And final comment (but not a big deal, IMO): when using conditions to set the `strokeDash` property, the "type" of line is not reflected in the legend - on your example above, for instance, the `GOOG` is a solid red line on the legend, instead of a dashed red line. However, in [this example in the gallery](https://altair-viz.github.io/gallery/multi_series_line.html), the line types are properly reflected on the legend (that is: dashed line on the charts appear as dashed lines on the legend). Any reason for `altair` (or `Vega-Lite`) to behave like that?

**Comment by jakevdp** [comment]
> Where is this behaviour documented, btw? 

It's not, unfortunately. The ``strokeDash`` encoding is a relatively recent addition to Vega-Lite, and nobody has stepped up yet to contribute Altair documentation for it (are you interested?)

> when using conditions to set the strokeDash property, the "type" of line is not reflected in the legend 

Conditional properties are never reflected in the legend (the same is true with conditional colors, shapes, etc.) To make a legend, you should use an encoding as in the example you linked to. You can then adjust the scale domain and range to adjust how data maps to visual properties.

**Comment by rafaelmaguillaoliveira** [comment]
Oh, I see... yes, I'd love to document it properly - specially because this feature can be super useful. I might take a while, though, because I'm not that familiar w/ the lib yet and I'd need to learn some other stuff before.

Oh, and sorry for taking so long to answer - I completely missed your response 😢

**Comment by rafaelmaguillaoliveira** [comment]
I'm closing the issue for now, as the problem was already solve and the final documentation will take longer to be in place

**Comment by ethanabrooks** [comment]
I'm just curious (and I can start a new issue if you prefer) but how would you get _two_ lines to show up dashed? When I use

```
alt.Chart(source).mark_line().encode(
    x='date',
    y='price',
    color='symbol',
    strokeDash=alt.condition(
        alt.datum.symbol == 'GOOG' or alt.datum.symbol == 'AMZN',
        alt.value([5, 5]),  # dashed line: 5 pixels  dash + 5 pixels space
        alt.value([0]),  # solid line
    )
)
```
Only GOOG gets the dash.

**Comment by joelostblom** [comment]
@ethanabrooks You can see [an example of the syntax vega-lite required for multiple comparison at the end of this page in the docs](https://vega.github.io/vega-lite/docs/condition.html#value). For altair to create the same expression you need to use `(alt.datum.symbol == 'GOOG') | (alt.datum.symbol == 'AMZN')` as the condition. You could also [manually type out the comparison dictionary instead of using alt.condition to generate it as shown here](https://stackoverflow.com/a/66109641/2166823).
