### ISSUE TITLE
Empty chart when Saving altair chart as png/svg

### ISSUE THREAD

**Issue by subhashbylaiah** [altair-viz/altair#2117]
I am trying to create altair density plots as below and then render them as svg/png.
Although the html rendering works fine, the svg/png rendering produces an empty chart.

I am on altair version '4.1.0' and altair_saver version '0.5.0' and jupyter lab version '1.2.14'
> Code to produce the chart 
```
import altair as alt
alt.data_transformers.enable("data_server")

xs = np.random.randn(100)
plt_data = pd.DataFrame({"x": xs})
c = (
        alt.Chart(plt_data, width=300, height=300)
        .transform_density(
            density="x", as_=["x", "density"]
        )
        .mark_area(opacity=0.3)
        .encode(x=alt.X("x:Q"), y="density:Q")
        .properties(title="Distribution of x")
        .configure_title(anchor="middle")
)
```

> Code to render as html
```
alt.renderers.enable("html")
c
```

> Code to render as png
```
alt.renderers.enable("png")
c
```
While the html rendering produces the output as expected, the png rendering produces an empty chart.
Also, there are these warnings as below.
```
WARN Ignoring an invalid transform: {"as":["x","density"],"density":"x"}.
WARN Infinite extent for field "density": [Infinity, -Infinity]
```
However, another interesting thing is that when I save the image as png using the context menu enabled on the html rendered chart, it gets saved just fine (as attached below).

![image](https://user-images.githubusercontent.com/9262331/80507259-4a8cb580-893c-11ea-844c-a7e85ea4372d.png)

**Comment by jakevdp** [comment]
This error:
```
WARN Ignoring an invalid transform: {"as":["x","density"],"density":"x"}.
```
indicates that your PNG is being saved with an older version of Vega-Lite (the density transform was added in version 4.0)

Given this, I suspect you are using the nodejs saver, and you'll need to update your installations of the vega-cli tools. See https://github.com/altair-viz/altair_saver#nodejs

**Comment by subhashbylaiah** [comment]
Thanks a bunch Jake. That fixed the problem.

On a related note, not with the above code though, I also see a bunch of messages like below.
These are when I make box_plots, and only show up when I use the SVG rendering option (html option serves fine, without warnings)

`WARN Missing type for channel "tooltip", using "nominal" instead.`

`WARN Infinite extent for field "bin_maxbins_10_<<MYVARIABLENAMEGOESHERE>>": [Infinity, -Infinity]
`
However the plots are rendered fine, but the messages are bothersome.

**Comment by jakevdp** [comment]
Those warnings are coming from the vega-cli packages. For the html view, no javascript is executed until you view the chart with a browser; I suspect you'll see equivalent warnings in the javascript console when you view it.

**Comment by subhashbylaiah** [comment]
Thanks for the explanations @jakevdp 
Closing the ticket, as my problem was addressed.
