### ISSUE TITLE
bind='scales' ignores shift-click requirement

### ISSUE THREAD

**Issue by ljmartin** [altair-viz/altair#2118]
Hi all - example code below. 

I'm trying to get a plot that will pan on shift-click but highlight a region on regular click (or vice versa!). Before combining them, I went to test the shift-clicking activity for each by themselves. 

The highlighting part obeys the `on=` direction to require the click-only or shift-click, but when bind='scales' is present, that seems to stop working. Perhaps it has something to do with the `scales` binding also affecting the zoom by scroll. I couldn't find an example in vega to go off.

Here's some example code:
```
import altair as alt
movies = 'https://vega.github.io/vega-datasets/data/movies.json'

###These events describe a click-and-drag with or without shift key
require_shift='[mousedown[event.shiftKey], mouseup] > mousemove'
require_noshift = '[mousedown[!event.shiftKey], mouseup] > mousemove'

#Highlighting the selection interval works when you change between 'require_shift' to 'require_noshift'
#selector = alt.selection_interval(on=require_shift)

#Pan and zoom is unaffected by changing 'require_shift' to 'require_noshift'
selector = alt.selection_interval(on=require_noshift, bind='scales')

alt.Chart(movies).mark_circle().add_selection(
    selector
).encode(
    x='Rotten_Tomatoes_Rating:Q',
    y=alt.Y('IMDB_Rating:Q', axis=alt.Axis(minExtent=30)), # use min extent to stabilize axis title placement
).properties(
    width=600,
    height=400
)
```
Any comments whatsoever would be appreciated - Thanks for your time and for Altair!

**Comment by ljmartin** [comment]
I threw the following code into the vega-lite editor and it didn't work either. So perhaps it just doesn't work. 

The bit I added was `"on":"[mousedown[!event.shiftKey], mouseup] > mousemove",`
https://vega.github.io/editor/#/edited
```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v4.json",
  "data": {"url": "data/cars.json"},
  "selection": {
    "grid": {
      "type": "interval", 
      "on":"[mousedown[!event.shiftKey], mouseup] > mousemove",
      "bind": "scales"
    }
  },
  "mark": "circle",
  "encoding": {
    "x": {
      "field": "Horsepower", "type": "quantitative",
      "scale": {"domain": [75, 150]}
    },
    "y": {
      "field": "Miles_per_Gallon", "type": "quantitative",
      "scale": {"domain": [20, 40]}
    },
    "size": {"field": "Cylinders", "type": "quantitative"}
  }
}
```

**Comment by jakevdp** [comment]
You need to also add `translate=require_noshift` to prevent translation when the shift key is down.

**Comment by ljmartin** [comment]
That was easy - thankyou!
