### ISSUE TITLE
Saved chart in html format will not display all the plots in the browser for large composite plot (Hconcat)

### ISSUE THREAD

**Issue by dchatterjee172** [altair-viz/altair#2119]
![image](https://user-images.githubusercontent.com/10482742/80590215-2662ce80-8a39-11ea-9a18-18618d4c7e6c.png)

I have verified that this does not happen for small plots.
I am saving with `svg` renderer.
I am using version 4.1.0
Also, I do not see any errors in the console

**Comment by jakevdp** [comment]
Please share code that reproduces the issue.

**Comment by dchatterjee172** [comment]
closing this, as the problem was related to the Type of the data. The column `classes` were of type `Quantitative` in the compiled Vega and it should be `Nominal`.
