### ISSUE TITLE
Logo for Website

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#212]
It would be nice to have a logo for the website. I'm personally horribly unskilled at such things...

**Comment by stsievert** [comment]
I'm not great at this but here's a rough version of what I created:
<img width="145" alt="screen shot 2016-11-01 at 10 43 24 pm" src="https://cloud.githubusercontent.com/assets/1320475/19916061/a616a8f6-a084-11e6-82c7-f4e35fc53a91.png">


* This is a (flat) image of a space telescope observing some stars. The telescope corresponds to the data visualization tool.
* The stars are colored by constellations. This corresponds to the data visualization tool pulling out previously unseen relationships.
* It shows the big dipper, cancer and the summer triangle (of which stars vega and altair are members)

**Comment by jakevdp** [comment]
I like the astronomy theme, but then again I would :smile: 🌠

**Comment by domoritz** [comment]
I think the final logo should be a bit less busy but this is a great start!

**Comment by ellisonbg** [comment]
I am having a new designer start right now and will have them look at this.

**Comment by ellisonbg** [comment]
Two options for logos. Trying to evoke "Alt" visually while also communicating visualization. 

First with overlapping bars:

![frame 5](https://user-images.githubusercontent.com/27600/31855392-3eaa5d42-b65f-11e7-9980-2b3da45185a7.png)

And a flatter version:

![frame 4](https://user-images.githubusercontent.com/27600/31855390-36914238-b65f-11e7-8f7e-d0e44d028283.png)

**Comment by ellisonbg** [comment]
@domoritz this visual language could be adapted for Vega-Lite too:

![frame 6](https://user-images.githubusercontent.com/27600/31855431-16f2af9c-b660-11e7-9b58-08da6d226240.png)

I would do some color variation though.

**Comment by jakevdp** [comment]
That's really nice! I think I prefer the overlapping one
