### ISSUE TITLE
Binding Min/Max SchemaValidationError on Custom Input Types

### ISSUE THREAD

**Issue by quantology** [altair-viz/altair#2121]
The following works:
```python
date = alt.binding(input="date")
select_date = alt.selection_single(name="select_date", fields=["date"], bind=date, init={"date": "2010-01-01"})
```
But the following yields an error:
```python
date = alt.binding(input="date", min="2000-01-01")
select_date = alt.selection_single(name="select_date", fields=["date"], bind=date, init={"date": "2010-01-01"})
```

```
SchemaValidationError
...
TypeError: sequence item 1: expected str instance, int found
```

However, modifying the underlying JSON in Vega-Lite also works. That is, with:
```
"bind": {"input": "date", "min": "2000-01-01"},
```
...Vega-Lite propagates the attribute to the underlying HTML tag, which restricts the range.

So it seems to me like this `SchemaValidationError` is a bug? Thanks for any clarification.

(Altair version: 4.0.1)

**Comment by jakevdp** [comment]
The ``SchemaValidationError`` comes from the Vega-Lite schema, defined in the Vega-Lite package. At times, the vega-lite code is able to execute without error on specifications that fail its own schema validation; that is a possible bug in Vega-Lite and could be reported there. Altair itself has no mechanism to modify the vega-lite schema.
