### ISSUE TITLE
Select multiple months with selector

### ISSUE THREAD

**Issue by domsl** [altair-viz/altair#2122]
Hi,
I am very new to altair and vega, but I really like it - thanks for the great work!

I want to plot data with a monthly and daily time axis using a selection filter. What I managed to come up with using various examples and the docs is something like that:

```python
source = df #pandas data frame

#brush = alt.selection(type='interval', encodings=['x'])
brush = alt.selection_multi(fields=['Date']) 

base = alt.Chart(source).mark_bar().encode(
    x='month(Date):T',    
    y='Value:Q',
).properties(
    width=600
)

top = base.encode(
    alt.X('month(Date):T', scale=alt.Scale(domain=brush)),
    color = alt.Color('Category:N', scale=alt.Scale(scheme="category20b")),
    tooltip=['Acc-Number', 'Date', 'Value', 'Category', 'Text'],
)

rule = base.mark_rule(color='red').encode(
    alt.Y('mean(Value):Q'),
    tooltip=['mean(Value)']
)

bottom = base.properties(
    height=60
).add_selection(brush)

layer = (rule + top) & bottom
layer.save('single_chart.html')
```
I get this:
![image](https://user-images.githubusercontent.com/10066244/80640560-dea56c80-8a63-11ea-9948-07e0578f601e.png)
When I click one of the months on the bottom I get:
![image](https://user-images.githubusercontent.com/10066244/80640673-07c5fd00-8a64-11ea-8f2a-6c4ec06f0113.png)

Why does it not show any bar anymore?
Why are my tooltips not working (anymore)?
How can I make the red rule line more visible? It's behind "top".
I actually want to calculate the monthly mean and I played around with `month( )`, but to no avail.

Ideally I would like to have something where I could select one or mutliple months (similar to [this](https://altair-viz.github.io/user_guide/transform/filter.html#selection-predicates)) and see the values plotted daily and aggregated monthly.

I am not sure how I would begin to debug this, I guess my selection does not return what I want. Would I debug this on the javascript level?

Could someone point me in the right direction? I would really appreciate that! :)

**Comment by jakevdp** [comment]
It would be helpful if you could include a full code snippet to reproduce the issue.

**Comment by domsl** [comment]
Thanks for you answer. 
I am confused - do you mean like how I create and fill the pandas dataframe?

**Comment by jakevdp** [comment]
I mean a block of code that I can run and see a chart that demonstrates the issue you’re having. Otherwise I’m left guessing as to exactly what’s causing the behavior you describe and won’t be able to answer your question effectively.

**Comment by domsl** [comment]
Hi, sorry for the late reply, but here it is, I made some sample data that shows the same problem as above:
```python
import pandas as pd
import numpy as np
import yaml
import re

import matplotlib.pyplot as plt

import altair as alt

l = 300
df2 =  pd.DataFrame({'Acc-Number': "Test-Acc-Num",
                     'Date': pd.date_range(start='20170301', end ="20200302", periods=l),
                     'Value': np.random.randn(l)*500,
                     'Text': ["Whatever Text {}".format(i) for i in range(l)],
                     'Category': (["Cat1", "Cat2", "Cat3", "Cat4", "Cat5","Cat6", "Cat7", "Cat8", "Cat9", "Cat10"]*(int)(l/10))
                     })

source = df2

#brush = alt.selection(type='interval', encodings=['x'])
brush = alt.selection_multi(fields=['Date']) 

base = alt.Chart(source).mark_bar().encode(
    x='month(Date):T',    
    y='Value:Q',
).properties(
    width=600
)

top = base.encode(
    alt.X('month(Date):T', scale=alt.Scale(domain=brush)),
    color = alt.Color('Category:N', scale=alt.Scale(scheme="category20b")),
    tooltip=['Acc-Number', 'Date', 'Value', 'Category', 'Text'],
)

rule = base.mark_rule(color='red').encode(
    alt.Y('mean(Value):Q'),
    tooltip=['mean(Value)']
)

bottom = base.properties(
    height=60
).add_selection(brush)

layer = (rule + top) & bottom 
layer.save('overview_chart.html')
```
I also noticed that it aggregates the months, adding the month January 2017 and 2018 together, which I do not want.

What I want to achieve is a monthly timeline where I can inspect data more closely by clicking through the bottom smaller preview plot. So I could select mutliple years, months and it shows me the appropriately scaled version of that timeline, including averages. (For example on click March 2018 or select Jan-Mar 2018 or the whole year 2018 etc.)

Thank you for spending time to help me out in any form! I'd like to learn more about vega/altair :)

**Comment by domsl** [comment]
Hi, anyone got any ideas?

Maybe I can move it around inside the pandas dataframe, but I would loose the interactive part.

**Comment by jakevdp** [comment]
I don't think you can set a domain to a single selection. Try changing ``alt.selection_multi`` to ``alt.selection_interval``.

**Comment by domsl** [comment]
It works, thank you! :)
