### ISSUE TITLE
Subtitle configuration bug dx

### ISSUE THREAD

**Issue by noklam** [altair-viz/altair#2124]
# Expected
![image](https://user-images.githubusercontent.com/18221871/80731943-27c9ef00-8b3e-11ea-80ea-34f3681d31ca.png)
According to the documentation, it should align both Title and Subtitle, but it only changes dx of Title but not subtitle.

![image](https://user-images.githubusercontent.com/18221871/80731847-036e1280-8b3e-11ea-9fd9-d363399574d8.png)

# Code Snippet
```python
import altair as alt
from vega_datasets import data

source = data.cars()

alt.Chart(source).mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).properties(title={'text': 'Title',
                     'subtitle': 'Subtitle'}
).configure_title(anchor='start', dx=30)
```

**Comment by noklam** [comment]
I get it to work when I configure with properties directly, I suspect this is bug with the `configure_title` function?  I try to register `subtitleFontSize` for custom theme and it also fail, the only way I can change is through .properties

import altair as alt
from vega_datasets import data

source = data.cars()

alt.Chart(source).mark_circle(size=60).encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
).properties(title={'text': 'Title',
                     'subtitle': 'Subtitle',
                   'dx':30}
).configure_title(anchor='start')

![image](https://user-images.githubusercontent.com/18221871/80732135-76778900-8b3e-11ea-98fe-45d8c52047c3.png)

**Comment by jakevdp** [comment]
Thanks for the report. This looks like a vega-lite issue.

**Comment by joelostblom** [comment]
The provided example is working as expected for me on Altair 4.2.0 so I'm closing this, please re-open if you are still seeing the issue.
