### ISSUE TITLE
Grouped bar chart shared label

### ISSUE THREAD

**Issue by XaviFar** [altair-viz/altair#2126]
The question might be silly, but I haven't managed to solve it.
Following the example from [Grouped bar chart](https://altair-viz.github.io/gallery/grouped_bar_chart.html), is there a way to show the x labels only once?

```python
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_bar().encode(
    x='year:O',
    y='sum(yield):Q',
    color='year:N',
    column='site:N'
)
```
![canvas](https://user-images.githubusercontent.com/7207214/80798951-dd7c5880-8ba5-11ea-89db-da4e86602a48.png)

Is there a way to show the label "year" just once?

thank you!

**Comment by jakevdp** [comment]
No, there's no way to do that, but you can abuse the chart title to do so:
```python
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_bar().encode(
    x=alt.X('year:O', title=None),
    y='sum(yield):Q',
    color='year:N',
    column='site:N',
).properties(
    title='year',
).configure_title(
    orient='bottom',
    anchor='middle',
)
```
![visualization - 2020-05-02T182144 564](https://user-images.githubusercontent.com/781659/80896307-ce7ad080-8ca1-11ea-9db8-df22a15dec5d.png)

**Comment by XaviFar** [comment]
It will do the trick! thanks!
