### ISSUE TITLE
Facetted grouped boxplot

### ISSUE THREAD

**Issue by hohlb** [altair-viz/altair#2127]
In the `seaborn` plotting library exists [catplot()](https://seaborn.pydata.org/generated/seaborn.catplot.html) that allows facetted grouped boxplots:

```python
import pandas as pd

## the following code needs the "xlrd" library installed for reading Excel files.
## alternatively, you can use the attached data.csv which contains the same data using:
# dataProp = pd.read_csv('https://github.com/altair-viz/altair/files/4565572/data.zip')

link = 'https://assets.publishing.service.gov.uk/government/uploads/system/uploads/attachment_data/file/812408/Gas_and_Electric_Consumption_Multiple_Attributes_Table_2019.xlsx'
data = pd.read_excel(link,'2017 Consumption')
dataGas = data.loc[data['Gas present']=='Yes',]
dataProp = dataGas.loc[dataGas['Electricity type']=='Standard',]
```

```python
import seaborn as sns

sns.catplot(x='Number of bedrooms',
            y='Median - Gas', 
            col='Region', 
            hue='Property age',
            kind="box",
            data=dataProp,
            col_wrap=4,
            hue_order=['Pre 1919','1919-44','1945-64','1965-1982','1983-92','1993-99'])
```

![grafik](https://user-images.githubusercontent.com/35731400/80825964-b17ec880-8be1-11ea-8967-f148b84bc717.png)

I tried to replicate this using `altair`, but the boxplots get stacked on themselfs:

```python
import altair as alt

alt.Chart(dataProp).mark_boxplot().encode(
    x='Number of bedrooms:O',
    y='Median - Gas',
    color=alt.Color('Property age:O',
                    sort=['Pre 1919','1919-44','1945-64','1965-1982','1983-92','1993-99']),
    facet=alt.Facet('Region:N', 
                    columns=4),
).interactive()
```

![visualization](https://user-images.githubusercontent.com/35731400/80826212-24883f00-8be2-11ea-86f2-3356bf1947b7.png)

I tried to combine `facet=...` and `column=...` parameters in `encode()` and tried my hands on the `repeat()` method without success. Is there a way to show the grouped boxplots next to each other like in `seaborn`'s `catplot()`?

Thank you for you help.

**Comment by jakevdp** [comment]
No, there's no way to do this yet in Altair/Vega-Lite (the way to make grouped boxplots is to use facet, and vega-lite does not support facets of facets).

A future vega-lite release will hopefully include an [offset encoding](https://github.com/vega/vega-lite/pull/4969) which will make this type of chart possible.

**Comment by joelostblom** [comment]
@hohlb I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Comment by VietTralala** [comment]
Is there any update on this feature? It seems x/yOffset was already introduced in [vega-lite](https://github.com/vega/vega-lite/pull/7684)

**Comment by joelostblom** [comment]
Yup, this had been added to altair so this issue can be closed. Here is how you could recreate the seaborn plot in the OP:

```python
box_order = ['Pre 1919','1919-44','1945-64','1965-1982','1983-92','1993-99']
alt.Chart(dataProp).mark_boxplot().encode(
    x='Number of bedrooms:O',
    y='Median - Gas',
    color=alt.Color('Property age:O', sort=box_order),
    xOffset=alt.XOffset('Property age:O', sort=box_order),
).facet(
    'Region:N',
    columns=4
)
```

![image](https://user-images.githubusercontent.com/4560057/182539045-95327873-73ee-4668-b80e-14f137e5f35d.png)

**Comment by VietTralala** [comment]
> Yup, this had been added to altair so this issue can be closed. Here is how you could recreate the seaborn plot in the OP:
> 
> ```python
> box_order = ['Pre 1919','1919-44','1945-64','1965-1982','1983-92','1993-99']
> alt.Chart(dataProp).mark_boxplot().encode(
>     x='Number of bedrooms:O',
>     y='Median - Gas',
>     color=alt.Color('Property age:O', sort=box_order),
>     xOffset=alt.XOffset('Property age:O', sort=box_order),
> ).facet(
>     'Region:N',
>     columns=4
> )
> ```
> 
> ![image](https://user-images.githubusercontent.com/4560057/182539045-95327873-73ee-4668-b80e-14f137e5f35d.png)

with what kind of version of altair are you generating this plot? My current altair version is  `4.2.0` and fails with `AttributeError: module 'altair' has no attribute 'XOffset'`. I also tried importing altair with `import altair.vegalite.v4 as alt` but was still unsuccessfull.

**Comment by joelostblom** [comment]
@VietTralala Sorry I should have mentioned that this has been added in the development version on GitHub, but it has not yet been released. As you noticed, you can install directly from GitHub to get access to the X/YOffset encodings. I am not sure why it is not working for you, but you should not have to do anything special with the import, so try importing as usual `import altair as alt`. It is important that you close down all notebooks (or clear their output) and the reopen jupyterlab. If there is a plot open that has been created by an with an old version of vegalite, that can create issues.

**Comment by VietTralala** [comment]
@joelostblom perfekt thanks! Closing all notebooks and restarting them resulted in the correct plot.

**Comment by hohlb** [comment]
> Yup, this had been added to altair so this issue can be closed. Here is how you could recreate the seaborn plot in the OP:
> 
> ```python
> box_order = ['Pre 1919','1919-44','1945-64','1965-1982','1983-92','1993-99']
> alt.Chart(dataProp).mark_boxplot().encode(
>     x='Number of bedrooms:O',
>     y='Median - Gas',
>     color=alt.Color('Property age:O', sort=box_order),
>     xOffset=alt.XOffset('Property age:O', sort=box_order),
> ).facet(
>     'Region:N',
>     columns=4
> )
> ```
> 
> ![image](https://user-images.githubusercontent.com/4560057/182539045-95327873-73ee-4668-b80e-14f137e5f35d.png)

awesome, thank you all very much!
