### ISSUE TITLE
use of x2=alt.X('foo') generates invalid JSON

### ISSUE THREAD

**Issue by eamoore** [altair-viz/altair#2128]
in the chart below, the json emitted in both case 1 and case 2 triggers a schema validation error.
```
altair.utils.schemapi.SchemaValidationError: Invalid specification
        altair.vegalite.v4.schema.core.FacetedEncoding->0, validating 'additionalProperties'
        Additional properties are not allowed ('type' was unexpected)
```
from:
```
plot = alt.Chart(df).mark_rect(
        color='red',
        opacity=.1
    ).encode( 
        x=alt.X('uc_min:Q'),
        # case 1 x2=alt.X('uc_max:Q')
        # case 2 x2=alt.X('uc_max')
        x2=('uc_max')   # case 3
    )
```
the work around is case 3.

Actually, case 4 is: 
```
       x2=alt.X2('uc_max:Q')     
```

And this works as you'd expect.  So, programmer error, but then in case 1 and case 2 the generated JSON probably should have had two instances of "x", andnot "x" and "x2" ... 

the corresponding JSON is
```
{
      "data": {
        "name": "data-f9fa0c3e7235827989ab614853801b99"
      },
      "encoding": {
        "x": {
          "field": "uc_min",
          "type": "quantitative"
        },
        "x2": {
          "field": "uc_max",
          "type": "quantitative"
        }
      },
      "mark": {
        "color": "red",
        "opacity": 0.1,
        "type": "rect"
      }
    },
```

the relevant Vega-Lite ticket is  https://github.com/vega/vega-lite/pull/4987

thank you, Eric

**Comment by jakevdp** [comment]
``alt.X`` includes a type, which is not valid according to the vega-lite schema. As you mentioned, the correct class for an ``x2`` encoding is ``alt.X2``.

I believe this is working as intended, although it's true that schema validation errors are not always overly informative.
