### ISSUE TITLE
Unsupported operations

### ISSUE THREAD

**Issue by jaseuts** [altair-viz/altair#2129]
When I ran this code 
```
source = alt.topo_feature('https://s3-ap-southeast-1.amazonaws.com/smallmu-sandbox/sydney_LGAs.json', 'sydney_LGAs')

baseMap = alt.Chart(source).mark_geoshape(
    fill='lightgray',
    stroke='white'
).properties(
    width=800,
    height=600
).project('mercator')

points = alt.Chart(subset).transform_aggregate(
    latitude='mean(latitude)',
    longitude='mean(longitude)',
    count='count()',
    groupby=['neighbourhood']
).mark_circle().encode(
    longitude='longitude:Q',
    latitude='latitude:Q',
    size=alt.Size('count:Q', title='Number of Airbnb Listings'),
    color='neighbourhood',
    tooltip=['neighbourhood:N','count:Q']
).properties(
    title='Number of Airbnb Listings'
)

st.altair_chart(baseMap+points)
```
It produced the following graph 

![Graph 1](https://user-images.githubusercontent.com/11934573/80860499-3a156b80-8cab-11ea-93df-926bbde969cb.JPG)

However, when I tried to take square root of variable `count` as follows 
```
size=alt.Size('np.sqrt(count):Q', title='Number of Airbnb Listings')
```
It produced a map without any dots as shown below

![Graph 2](https://user-images.githubusercontent.com/11934573/80860710-dab85b00-8cac-11ea-9d5a-cd4b3b3be37e.JPG)

Is it possible to do calculation such as square root, exponent, or log in altair?

**Comment by mattijn** [comment]
You cannot feed NumPy arguments to Altair/Vega-Lite. Two choices. 
1. compute the values beforehand 
2. set scale type in the channel encoding. In this case something like:
```python
alt.Size('count:Q', scale=alt.Scale(type='sqrt'))
```

More info on accepted scale types here: https://vega.github.io/vega-lite/docs/scale.html#type

**Comment by jaseuts** [comment]
Thank you for your information and instruction, @mattijn. Option 2 is best as it is dynamic.
