### ISSUE TITLE
Save as SVG/PNG buttons not working

### ISSUE THREAD

**Issue by dbk123** [altair-viz/altair#2130]
Running a notebook that I've run frequently over the past few weeks and suddenly the 'Save as SVG' and 'Save as PNG' buttons shown to the upper right of the figure don't do anything.  Tried running the simple bar chart example from the gallery and they don't work with that example either.  Seems really strange. Rebooted my Mac - same thing.    I am running Jupyter Lab 2.0.1 and Altair version 4.1.0

Saving from the command line seems to work.  

Any ideas?

Thanks!

**Comment by dbk123** [comment]
Update - I can open the figures in the Vega editor and download them from there, but the Save as SVG button next to the figure still does nothing.  Strange....

**Comment by jakevdp** [comment]
- what browser are you using?
- what renderer are you using?
- are there any warnings or error messages in the javascript console when you try to save a figure?

**Comment by dbk123** [comment]
I was using Safari, but the problem persists in both Safari and Chrome.
I am using the default renderer.
No warnings or errors appears, but Save As buttons do nothing.  It seems like I can't even select them from the dropdown menu in the figure.  However, I can open the figure in the Vega Editor.

**Comment by jakevdp** [comment]
This may be related to the vega-embed version 6.7 release yesterday.

@domoritz, were there any changes in the new release that might cause the figure saves to fail?

**Comment by domoritz** [comment]
Hm, could be https://github.com/vega/vega-embed/commit/3d5c5c889587a72b76baa691f5571fb7b5643810.

**Comment by domoritz** [comment]
Yep, that's it. Interestingly, the clicks still work for the other buttons. I'll fix it.

**Comment by domoritz** [comment]
Fixed in 6.7.1.

**Comment by dbk123** [comment]
Thanks for the speedy response!  Please let me know how to update and I will test.

**Comment by jakevdp** [comment]
Altair's default renderer is currently configured to display using the most recent v6 release of Vega-Embed. So now that it's released, you can test it by displaying a chart.

**Comment by dbk123** [comment]
Great.  Things are working now so I am closing this.

Thanks @jakevdp  and @domoritz !
