### ISSUE TITLE
Shape not displayed in map

### ISSUE THREAD

**Issue by jaseuts** [altair-viz/altair#2133]
Although I specified the parameter `shape` in the code below, that attribute was not displayed in the resulting map
```
baseMap = alt.Chart(source).mark_geoshape(
    fill='lightgray', stroke='white'
).properties(width=800, height=600
).project('mercator')

points = alt.Chart(subset).mark_circle().encode(
    longitude='longitude:Q',
    latitude='latitude:Q', 
    size=alt.Size('price:Q', title='Price'),
    color='neighbourhood',
    opacity=alt.value(0.6),
    shape='room_type', # there are 4 airbnb room types
    tooltip=['name:N', 'room_type:N', 'price:Q', 'neighbourhood:N']
).properties(title='Number of Airbnb Listings')

st.altair_chart(baseMap+points)
```
Could someone please explain what I did wrong? Thanks in advance.
![Graph 1](https://user-images.githubusercontent.com/11934573/80914171-3eb25080-8d8d-11ea-91da-a98a4c795375.JPG)

**Comment by jakevdp** [comment]
You're using ``mark_circle()``, which always draws circles. Try using ``mark_point()``.

**Comment by joelostblom** [comment]
@jaseuts I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
