### ISSUE TITLE
Color value based on a condition with linear gradient

### ISSUE THREAD

**Issue by dchatterjee172** [altair-viz/altair#2134]
```
base_word_vs_class = (
        alt.Chart(results_word_vs_class)
        .mark_rect()
        .encode(
            alt.X("classes:N"),
            alt.Y("word:N"),
            tooltip=["value:Q", "classes:N", "word:N"],
            color="value:Q"
        .properties(width=700, height=1000)
        .facet("what", align="each")
        .interactive()
    )
```
The above was the code I using, and I wanted the color to be different based on condition.
```
521     base_word_vs_class = (
522         alt.Chart(results_word_vs_class)
523         .mark_rect()
524         .encode(
525             alt.X("classes:N"),
526             alt.Y("word:N"),
527             tooltip=["value:Q", "classes:N", "word:N"],
528             color=alt.condition(
529                 "datum.value>0.0", alt.ColorValue("green"), alt.ColorValue("red")
530             ),
531         )
532         .properties(width=700, height=1000)
533         .facet("what", align="each")
534         .interactive()
535     )
```
Now I can do the above, but I lose the gradient based on the `value`.
Any ideas?

**Comment by jakevdp** [comment]
Have you tried something like this?
```
color=alt.condition(
    "datum.value>0.0", "value:Q", alt.ColorValue("red")
)
```

**Comment by dchatterjee172** [comment]
Hey this worked, I understand the logic here.
What should have been done if I also wanted a gradient, based on the value of `value` if value<=0.0

**Comment by jakevdp** [comment]
Can you show an example of the gradient that you want to keep? None of your code shown above defines a gradient.

**Comment by dchatterjee172** [comment]
okay let me state the problem, 
`color="value:Q"` gives me a linear gradient based on a single base color (white -> base color).
Now I wanted to have two different color gradient, green for `value>0.0` red for `value<=0.0`

I guess I can do that by layering two different charts, one for `value>0.0` and another for `value<=0.0`

**Comment by jakevdp** [comment]
No, there's no way to have two different scales for a single field in a chart. The best workaround would be to layer two charts with filter transforms, where each layer has its own color scale.

**Comment by jakevdp** [comment]
Alternatively, you could define a custom color scale with the characteristics you want it to have
