### ISSUE TITLE
Chart won't display using jupyter notebook. TypeError: document.currentScript is null

### ISSUE THREAD

**Issue by Camq543** [altair-viz/altair#2137]
I'm trying to display some choropleths in a jupyter notebook. Another person's notebook displays them fine, but I get this error whenever I call the chart: 

Javascript error adding output!
TypeError: document.currentScript is null
See your browser Javascript console for more details.

I found this stackoverflow page with the same issue, but didn't see this issue posted. The stackoverflow page is below:

https://stackoverflow.com/questions/61211549/altair-javascript-error-prevents-chart-display

**Comment by jakevdp** [comment]
What browser are you using? Altair requires ECMAScript 6, so it may fail in older browsers; see https://altair-viz.github.io/user_guide/troubleshooting.html#chart-does-not-display-at-all

**Comment by Camq543** [comment]
I'm using up to date Firefox on arch linux. I get the same error when using the Chromium browser.

**Comment by jakevdp** [comment]
Can you try updating your Jupyter notebook package?

**Comment by jakevdp** [comment]
Im unsure what it is about your environment that causes document.currentScript to be null within a running script. You should try things until you figure out what is causing that.

**Comment by Camq543** [comment]
I'm unsure as well. I started a fresh environment and get the same issue. I'll try and do some investigating.

**Comment by joelostblom** [comment]
@Camq543 I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet?

**Comment by joelostblom** [comment]
Closing for now, feel free to reopen and provide additional details to reproduce this issue.
