### ISSUE TITLE
stacked area chart of grouped cumulative sums has unexpected zeros

### ISSUE THREAD

**Issue by robbuckley** [altair-viz/altair#2138]
hi, 
I'm trying to plot time series data as follows:

```
N=20
data = pd.DataFrame({
        'date': pd.date_range('2018-01-01', periods=N, freq='D'),
        'value': np.random.uniform(size=N),
        'class': np.random.choice(['a', 'b', 'c'], N)
                        })
print(data)

             date     value class
    0  2018-01-01  0.692205     b
    1  2018-01-02  0.922879     a
    2  2018-01-03  0.578047     a
    3  2018-01-04  0.034273     a
    4  2018-01-05  0.807709     b
    5  2018-01-06  0.265198     c
    6  2018-01-07  0.000666     c
    7  2018-01-08  0.994985     a
    8  2018-01-09  0.610826     a
    9  2018-01-10  0.892722     c
    10 2018-01-11  0.003579     c
    11 2018-01-12  0.190279     a
    12 2018-01-13  0.631945     b
    13 2018-01-14  0.654595     a
    14 2018-01-15  0.353098     a
    15 2018-01-16  0.490040     c
    16 2018-01-17  0.577373     b
    17 2018-01-18  0.701564     a
    18 2018-01-19  0.182825     b
    19 2018-01-20  0.973451     c
```
Using this:

```
    alt.Chart(data
    ).transform_window(
        cuml='sum(value)',
        groupby=['class'],
        sort=[{'field':'date'}],
        frame=[None, 0]
    ).mark_area(
    ).encode(
        x='date:T',
        y=alt.Y('cuml:Q'),
        color='class'
    )
```
And get this:

![image](https://user-images.githubusercontent.com/20515024/81124579-b8814000-8f2d-11ea-8e02-3ada67991942.png)

What seems to be happening is that at time series points where there is no data for a particular class, a zero is plotted. Since this is the output of a cumulative sum, I'd like to see it stay at the value for the previous point. Strangely enough, if I plot the same data unstacked changing the `y=..` line to
```
        y=alt.Y('cuml:Q', stack=None),
```
I get this:
![image](https://user-images.githubusercontent.com/20515024/81124542-9c7d9e80-8f2d-11ea-9fd9-d15ec973f13d.png)

Which behaves as I would expect in respect of the cumulative sum, but is no longer the stacked area chart Im looking for. 

Is there anything I get do in altair to get the stacked chart working as I'd like? thanks

PS im running version 4.1.0

**Comment by ritamds** [comment]
Hello, I am having the same issue. Did you manage to find a solution for this?

**Comment by jakevdp** [comment]
Missing values are set to zero by default. If you want to control this behavior, the best way is to use an [impute transform](https://altair-viz.github.io/user_guide/transform/impute.html).

**Comment by joelostblom** [comment]
@robbuckley I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
