### ISSUE TITLE
Setting only a min or max for a scale domain?

### ISSUE THREAD

**Issue by debbes80** [altair-viz/altair#2140]
Is it possible to only set a fixed minimum or maximum for a scale domain instead of declaring the whole domain?
I don't want to filter my data.

**Comment by Rik-de-Kort** [comment]
The easiest way to accomplish this is to simply set (for some data `df` with a column `x`) `scale=alt.Scale(domain=[-3, df.x.max()])`.

The fact that you don't want to filter your data makes it seems plausible that filtering your data would be the best solution, though. Maybe you can provide some more details to your specific problem?

**Comment by debbes80** [comment]
A simple example below. I want to y-axis max to adjust dynamically to the data of the selection, but I want the min of y-axis to always be 256.

Filtering corrupts the shape of the plot.
Capping the data with calculate, corrupts the shape a bit less, but makes it more complex when using more complex charts.
If you alter the data, the plot will not show the real data anymore, so I'm not fond of that.

This feels like a normal/useful property to specify for an axis. The following code would feel logical to me for accomplishing this:
```python
scale=alt.Scale(domain=[256, ])
```

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3RgTABDccgDaoALZKATgGs8IQgE8ADphQgANiQvdTEEqsI7SmOSExRIdEklQ8VhA6hmhKVm6WCDqYXiAeAB6GJuaWwb5Q4SDc8JhWdJZJHsbJZhbIIACOpEpEcIQqcGh2ILn5liXclMpW5aAARkqU5QBM3Cnl1hBIsh7DvWDE0IbzmIvBbACMbKWpFZR+vdmtWPmUKGrgKiAAutz9JAUBJKakqiCri8cQpktQ5+oQEpjv1bh4SPVDMp3sDZuMdLVKDBgpoLqB4FZCJgQgFPn9LHiNtt4tI7iBsPQmJIZJwtLoDAEJpYbFAWg4nCgXG4PF4fH4oRAgjj0OFIhV+hELIldpN0iQsjlTk8QEVuCVGWVLNVasQGsRmsc2srOh8en0QINhigxkZNRUgjNZF08mt8biXesdFsdhq9h9Di0jQDLtDbvdHoYXm8CR7xNwfn9g0CQWDuBDVPhrhVYU6jAj-sidKj1Oi4JjsStY3BlvtY0Sdk7S+WcSAABR0FSkTQAOmMAAIAHx9kYAVgAbABKeJkikMZjIKRsOR0-Qy5m2Y7soic1zubi8iAZfz4QXBUKiyYxArS32ynQZBUnPLK1UgdWgJkVbV1PVNQNKjplFMY5unCc1LVGcY7SmR05irGtQEJL1iVvAkA0NJUk1DMkHigJ5QCjd48W+X5q3+C5k3uVMQHTKEs2TOE80RQtiw0E5m0rBY3Q+OtkIbZcrisMBSCsFRJnbTse2MAAeUcxz7AB+Ydxz7ZA+w7Qgu17KduCGQClGA0luFnKkFxkMkNOBAJMk0SZLIAWgATgkTARjAMcAHYAA4PMwCQJDofoRhGfowC8-oYEcryWEckcRgkNylDAeJuAAEm6RhMG0SwxEIUxKGQAB6QrmgQJRuwQepGFIfpu2rQqMqypQSswMr7JsLESpYbsvO7TZuwAK0oZZuEs4ZCABUAHOc1z3O83z-MC4LQvCyLoti+LEuSksVRQTY1T2jhuFDbMUtAJJkBtdVtiOq4YTO3aFwO5Abtuk6GNpR6WGexcuDuyxYU+i6R2e9hjvowHzpQMdnpHN6IYei79rfQ74feUEBIuq7UbRywMaByRnte3HxUR1gfo4EmLTJ5AQZR5Awf+0nMeh2HKfB9Hp1kIA)

```python
import numpy as np
import pandas as pd
import altair as alt
from altair import datum

df = pd.DataFrame()
df['x'] = [1,2,3,4,5,6,1,2,3,4,5,6]
df['y'] = [100,1000,10000,3000,40,500]+[1000,10000,100000,30000,40,5000]
df['cat'] = ['a']*6 + ['b']*6

drop = alt.binding_select(options=['a','b'])
sel = alt.selection_single(fields=['cat'], bind=drop, init={'cat': 'a'})

base = alt.Chart(df).mark_line(point=True).add_selection(
    sel
).transform_filter(
    sel
).encode(
    x='x:O',
    y=alt.Y('y:Q', scale = alt.Scale(type='log', base=2)),
    color=alt.value('green')
).properties(
    width=300)

filt = base.transform_filter(
    datum.y > 256
).encode(
    color=alt.value('blue')
)

cap = base.transform_calculate(
    ycap = '(datum.y<256 ? 256 : datum.y)'
).encode(
    y=alt.Y('ycap:Q', scale = alt.Scale(type='log', base=2)),
    color=alt.value('red')
)

base|filt|cap
```
![visualization](https://user-images.githubusercontent.com/54935651/81324261-02396a00-9097-11ea-869d-65d2181a5dbe.png)

**Comment by drgould** [comment]
I have a slightly different use case (layered lines for dual y axis) and am running into this as well. [`domainMin/Max` is supported in vega-lite directly](https://vega.github.io/vega-lite/docs/scale.html#domain) so it makes sense this should also be possible in altair either with discrete args to match vega-lite's or by specifying None for the missing dimension (e.g. `domain=[None, 50]` -- currently this raises an error btw).

**Comment by jakevdp** [comment]
`domainMin`/`domainMax` was added in a recent version of Vega-Lite that Altair does not yet support.

**Comment by joelostblom** [comment]
This has been added in Altair 4.2.0
