### ISSUE TITLE
Line disappears when encoding size or strokeWidth

### ISSUE THREAD

**Issue by Rik-de-Kort** [altair-viz/altair#2141]
My end goal is to recreate Minard's famous graph of Napoleon's march into Russia. To do this, I have a dataset of latitudes and longitudes, with the number of survivors at those lats and longs. Ideally, I would mark a line and encode the latitude and longitude as x and y, with strokeWidth being the number of survivors. However, while this line works, the strokeWidth makes parts of the line disappear.

Below is a reproducer of the same problem on a toy dataset:
````python
import altair as alt
import pandas as pd
import numpy as np

df = pd.DataFrame([(x, 1, x) for x in range(10)], columns=["x", "y", "z"])

# Works, plots a line
alt.Chart(df).mark_line().encode(x="x", y=alt.Y("y", scale=alt.Scale(domain=[0, 2])))

# Line disappears!
alt.Chart(df).mark_line().encode(x="x", y=alt.Y("y", scale=alt.Scale(domain=[0, 2])), size="z")
alt.Chart(df).mark_line().encode(x="x", y=alt.Y("y", scale=alt.Scale(domain=[0, 2])), strokeWidth="z")
````

Why is this occurring, and how can I fix it?

**Comment by jakevdp** [comment]
When you encode by ``z``, it groups the data by the z-value before plotting it. You have one row per z-value, so you are drawing 10 lines of 1-point each. A line with only one point has nothing to display.

If you want something to be displayed, try using a dataset with more than one value per z category.

**Comment by jakevdp** [comment]
For example:
```python
import altair as alt
import pandas as pd
import numpy as np

df = pd.DataFrame([(x, 2 * x + x % 3, x % 3) for x in range(10)], columns=["x", "y", "z"])
alt.Chart(df).mark_line().encode(x="x", y=alt.Y("y"), strokeWidth="z:O")
```
![visualization (3)](https://user-images.githubusercontent.com/781659/81319213-32a3e880-9044-11ea-8be6-a7aedd780d01.png)
