### ISSUE TITLE
Default settings for interactive plot

### ISSUE THREAD

**Issue by alexatartaglini** [altair-viz/altair#2142]
I'm trying to create an interactive plot using data from a bunch of large CSV files. Once the user selects all of the options, the number of points being plotted is quite small. However, when the plot first loads, it attempts to plot every data point from the files. This causes the whole program to crash because it requires too much memory to plot so many points.

Is there any way to create some sort of default setting for the various options for the plot when it first loads?

**Comment by debbes80** [comment]
You can set an initial value for the interactive selections:
```python
genres = ['Action', 'Adventure', 'Black Comedy', 'Comedy']

genre_dropdown = alt.binding_select(options=genres)
genre_select = alt.selection_single(fields=['Major_Genre'], bind=genre_dropdown,
        name="Genre", init={'Major_Genre': 'Action'})
```

**Comment by joelostblom** [comment]
@alexatartaglini I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
