### ISSUE TITLE
Line in boxplot when there is just one value

### ISSUE THREAD

**Issue by XaviFar** [altair-viz/altair#2144]
I'll take this example posted in another thread to try to illustrate my comment. When you use the boxplot function if there is only one value in one group it doesn't plot anything since you cant compute the statistics. Maybe it could be useful to plot a line in the cases in which this happens, like seaborn does, since it is kind of weird to have an empty group.

I don't know if there is a way to do this.

Thanks!

Here's an example that might clarify this:
```python
import altair as alt
import pandas as pd
import numpy as np

alt.Chart(
    data=pd.DataFrame({
        'x': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'C'],
        'y': [1, np.nan, 3, 4, 5, 6, 7, 8],
    })
).mark_boxplot().encode(
    x='x:N',
    y='y:Q',
)
```
![visualization - 2020-01-17T111657 731](https://user-images.githubusercontent.com/781659/72639641-e446ce80-391a-11ea-8525-2c210cf6e133.png)

The box is drawn for A despite the presence of NaNs, because it has enough values after the NaN is removed. The box is not drawn for C, but this is not related to NaNs – it is because the group only contains one value, and relevant statistics like the standard deviation are undefined for a single value.

_Originally posted by @jakevdp in https://github.com/altair-viz/altair/issues/1918#issuecomment-575759414_

**Comment by joelostblom** [comment]
@XaviFar This would need to be added in VegaLite rather than in Altair. Would you mind opening an issue there, link it here, and then close this issue?

**Comment by joelostblom** [comment]
Closing this as there is nothing to do on the Altair side of things. Once the functionality has been implemented in VL, it will be in an upcoming Altair release.

**Comment by xinmingxu** [comment]
I see that Altair 5.4 has updated Vega-Lite to version 5.20.1, which has fixed the issue [https://github.com/vega/vega-lite/pull/8339](url), however, Altair 5.4 still doesn't plot anything when there is just one value

**Comment by joelostblom** [comment]
I see a horiztonal line when I run the following code:

```py
import altair as alt
import pandas as pd
import numpy as np

alt.Chart(
    data=pd.DataFrame({
        'x': ['A', 'A', 'A', 'A', 'A', 'B', 'B', 'C'],
        'y': [1, np.nan, 3, 4, 5, 6, 7, 5.5],
    })
).mark_boxplot().encode(
    x='x:N',
    y='y:Q',
)
```

![image](https://github.com/user-attachments/assets/536a2e86-f9af-47fc-a343-73a16a2f8de1)


Make sure that you have closed all notebook (or cleared all output) and restart jupyterlab/vscode after installing 5.4.

**Comment by xinmingxu** [comment]
thanks! see it now
