### ISSUE TITLE
Setting Independent Legends on Layer Chart

### ISSUE THREAD

**Issue by zacharylawrence** [altair-viz/altair#2146]
Hi, I'm trying to plot a line chart with a surrounding error band but the legend is behaving unexpectedly.

As I understand it (https://stackoverflow.com/a/61547455/2522041), a legend can only be created in this case by encoding color/size/etc. to a constant value.

Here's an example:

```python
import datetime
import pandas as pd
from vega_datasets import data
import altair as alt

stocks = data.stocks()

stocks["year"] = stocks["date"].dt.year
metric = stocks.groupby("year")["price"]

stocks = pd.DataFrame()
stocks["value"] = metric.median()
stocks["upper_bound"] = metric.quantile(.75)
stocks["lower_bound"] = metric.quantile(.25)
stocks["year"] = stocks.index.map(lambda year: datetime.datetime(year, 1, 1))


base = alt.Chart(stocks).transform_calculate(
    line="'Median'",
    shade="'Bounds'",
)

chart_line = base.mark_line().encode(
    x='year',
    y='value',
    color=alt.Color('line:N', scale=alt.Scale(range=['black']), legend=alt.Legend(symbolType="stroke"), title=""),
)

chart_band = base.mark_errorband(color="black").encode(
    x='year',
    y=alt.Y('upper_bound', title="price"),
    y2='lower_bound',
    color=alt.Color('shade:N', scale=alt.Scale(range=['steelblue']), legend=alt.Legend(symbolType="circle"), title=""),
)
```

When I plot either `chart_line` or `chart_band`, it's as expected:
![image](https://user-images.githubusercontent.com/4469505/81440732-85fa6180-913e-11ea-8745-cbfd44d8bab2.png)
![image](https://user-images.githubusercontent.com/4469505/81440742-885cbb80-913e-11ea-9ba7-1f7a8cea6cf1.png)

In both of these cases, the colors are as specified in the `scale` and the legend takes on either `stroke` or `circle` depending on the chart.

However, when I plot `chart_line + chart_band`, I am surprised by the colors and the legend. I would expect the colors to be black and blue. I would also expect the legend to show a black dash for the median and a blue circle for the errorband.

![image](https://user-images.githubusercontent.com/4469505/81440886-c3f78580-913e-11ea-8c5e-bc64701c73be.png)

It appears like the legend is being combined and somehow "overwritten" by the other chart. Do you have advice on the correct way to approach a problem like this?

Thanks for your help with this!

**Comment by jakevdp** [comment]
Use ``resolve_scale(color='independent')``. See https://altair-viz.github.io/user_guide/scale_resolve.html for more details.

**Comment by zacharylawrence** [comment]
> Use `resolve_scale(color='independent')`. See https://altair-viz.github.io/user_guide/scale_resolve.html for more details.

Worked perfectly. Thanks for your help & the fast response!
