### ISSUE TITLE
Add Pie Chart

### ISSUE THREAD

**Issue by Delaunay** [altair-viz/altair#2148]
I am building a dashboard with flask & altair and I feel the pie chart is missing.
I tried hacking it in following this [spec](https://vega.github.io/vega/examples/pie-chart/).
But it was harder than expected.

Would be great if that was builtin

**Comment by jakevdp** [comment]
Vega-Lite recently added pie chart support in [version 4.9](https://github.com/vega/vega-lite/releases/tag/v4.9.0), but Altair has not yet been updated to support this release. The next version of Altair should make this possible.

**Comment by austinorr** [comment]
Looks like Vega-Lite added significant new features at the end of March, including enabling pie charts _and_ marker rotation (arrows are now possible!). If one were interested in contributing to help update `altair` incorporate these new capabilities, how would one help @jakevdp and his other core devs with that process? I looked for a development branch, or one tagged with a Vega-Lite version number but most branches appear to be merged PRs from long ago. 

I've read the maintainer instructions and I can follow along, but I'm new to `altair` and I'm wondering if there's an update already in progress that needs more help, or if it would be useful for me to start one. Not wishing to step on any toes (release branches are not usually started by new contributors), just hoping to help, and/or hear that this process is underway and well supported.

**Comment by jakevdp** [comment]
The big blocker in this case is updating the code generation tools to handle the new datum encoding. There are no docs because a new encoding type has not been added since Altair was created.

**Comment by austinorr** [comment]
Thanks for the reply, I should have known it wouldn’t be trivial. Is there a path forward or is this one of those road blocks that ends up requiring a time consuming & paradigm shifting refactor? Also, maybe this thread is not the best place for tracking this discussion any more. Does this new encoding warrant its own issue?

**Comment by jakevdp** [comment]
Roughly, the idea is this: we will need a ``DatumChannelMixin`` similar to the ``ValueChannelMixin``: https://github.com/altair-viz/altair/blob/52732ab3660392c0c41786683f4ba8a276ee00ad/tools/generate_schema_wrapper.py#L145-L159

and a ``DatumSchemaGenerator`` similar to the ``ValueSchemaGenerator``: https://github.com/altair-viz/altair/blob/52732ab3660392c0c41786683f4ba8a276ee00ad/tools/generate_schema_wrapper.py#L176-L186

Then these will have to be constructed as part of the loop further down in the file, which may not be straightforward depending on the vega-lite schema's conventions regarding how these definitions are named.

**Comment by austinorr** [comment]
I have some catching up to do if I’m going to be of any use in helping with this; I’ll need to better understand the Vega and VegaLite json schemas, and I’ll need more time with the code generation patterns to get my head around the arguments that are passed to the code templates. 

Thanks taking time to show me where to begin.

**Comment by soundquiet** [comment]
hi, is pie chart now available in altair?

**Comment by jakevdp** [comment]
No, Altair does not yet support Vega-Lite 4.9 features.

**Comment by kstathou** [comment]
Hi @jakevdp, thanks for maintaining/developing Altair, it's my go-to data visualisation library! Is there a roadmap for supporting newer versions of Vega-Lite?

**Comment by jakevdp** [comment]
Not sure... the update is a bit complicated because Vega-Lite 4.9 added the `"datum"` encoding specification alongside `"field"` and `"value"`, so a bunch of the assumptions in `tools/generate_schema_wrapper.py` are broken by the new version.

**Comment by mattijn** [comment]
I played around a bit, just to get a start of an understanding what this `generate_schema_wrapper` is trying to do. Over there: https://github.com/mattijn/altair/tree/vl_v5 (not worth a PR, but maybe inspiration for others who are brave and clever😉). 

I got it to work a bit:

```python
import pandas as pd
import altair as alt

df = pd.DataFrame({'category': [1, 2, 3, 4, 5, 6], 'value': [4, 6, 10, 3, 7, 8]})

alt.Chart(df).mark_arc().encode(
    theta=alt.Theta(field='value', type='quantitative'), 
    color=alt.Color(field='category', type='nominal')
)
```
<img width="483" alt="image" src="https://user-images.githubusercontent.com/5186265/107829725-a240c400-6d8a-11eb-8ad3-eaceed958d07.png">

```python
# this also works
alt.Chart(df).mark_arc().encode(
    theta=alt.PositionFieldDefBase(field='value', type='quantitative'), 
    color=alt.PositionFieldDefBase(field='category', type='nominal')
)

# this creates an empty chart
alt.Chart(df).mark_arc().encode(
    theta=alt.PositionDatumDefBase(datum='value', type='quantitative'), 
    color=alt.PositionDatumDefBase(datum='category', type='nominal')
)
```

Now I also understand what you mean with:

> Then these will have to be constructed as part of the loop further down in the file, which may not be straightforward depending on the vega-lite schema's conventions regarding how these definitions are named.

Since you check for `if "Value" in basename:` here:https://github.com/mattijn/altair/blob/vl_v5/tools/generate_schema_wrapper.py#L435, but you cannot do this for `Datum` since `Datum` is never included in basename. So the `DatumSchemaGenerator` [function](https://github.com/mattijn/altair/blob/vl_v5/tools/generate_schema_wrapper.py#L206:L216) is never called

**Comment by jeet183** [comment]
Is mark_arc supported by altair in the latest version? I am getting 'Chart object has no attribute mark_arc'

**Comment by mattijn** [comment]
No. This issue is still open

**Comment by 1081** [comment]
Is there some workaround to use pie charts? maybe with a specific version of vega light

**Comment by jakevdp** [comment]
Pie charts are part of Altair 4.2 which is not yet released, but a release candidate is available:
```
pip install altair==4.2.0rc1
```
You can see some examples here: https://altair-viz.github.io/gallery/index.html#circular-plots

**Comment by joelostblom** [comment]
Closing since 4.2 is now released.
