### ISSUE TITLE
Modifying X Labels in Normalized Grouped Stacked Bar Plots

### ISSUE THREAD

**Issue by sudheesh001** [altair-viz/altair#2149]
Hi Maintainers,

I am trying to create a normalized grouped stacked bar plot using altair and was struggling to work with labels. The data is of the format `['A', 'B', 'C', 'D']` where `A` is the grouping category, `B` is the values of the `x` axis and `C` is the stacking values and `D` is the value. I want to create a graph which looks as follows:

![image](https://user-images.githubusercontent.com/4545925/81836795-d2f08600-94f8-11ea-81ee-28cc3c2084ee.png)

There are two objectives I want to achieve with the styling here:

1. Ensure that there's only one x label across all the groups called Type (B) instead of having it displayed multiple times (unique(A) times) below each stacked group.
2. Format the x labels in each group to include the value of N i.e. replace Type 1 as Type 1 (N=20) AND Type 2 (N=22) for Category 1 etc.., (N values are computed according to the example below)

```py
import pandas
import altair as alt


def populate_data():
    data = [
        ['Category 1', 'Type 1', True, 10],
        ['Category 1', 'Type 1', False, 5],
        ['Category 1', 'Type 1', 'V3', 5],
        ['Category 1', 'Type 2', True, 10],
        ['Category 1', 'Type 2', False, 8],
        ['Category 1', 'Type 2', 'V3', 4],
        ['Category 2', 'Type 1', True, 10],
        ['Category 2', 'Type 1', False, 5],
        ['Category 2', 'Type 1', 'V3', 5],
        ['Category 2', 'Type 2', True, 10],
        ['Category 2', 'Type 2', False, 8],
        ['Category 2', 'Type 2', 'V3', 4],
        ['Category 3', 'Type 1', True, 10],
        ['Category 3', 'Type 1', False, 5],
        ['Category 3', 'Type 1', 'V3', 5],
        ['Category 3', 'Type 2', True, 10],
        ['Category 3', 'Type 2', False, 8],
        ['Category 3', 'Type 2', 'V3', 4],
    ]
    header = ['A', 'B', 'C', 'D']
    df = pandas.DataFrame(data=data, columns=header)
    return df


def plot_grouped_stacked_bars():
    df = populate_data()
    chart = alt.Chart(df).mark_bar().encode(
        x=alt.X('B:N', axis=alt.Axis(title='Type (B)')),
        y=alt.Y('D', axis=alt.Axis(grid=False, title='Percentage', format='%'), stack='normalize', sort="-x"),
        column=alt.Column('A:N'),
        color=alt.Color('C:N'),
    )
    chart.save('sample_plot.png')


plot_grouped_stacked_bars()
```
How do I modify the `x label` in each category to include the size? `Type 1` --> `Type 1 (N=20)`

Cross posted from SO: https://stackoverflow.com/questions/61764794/

**Comment by jakevdp** [comment]
There's no easy way in the Vega-Lite grammar to add data-dependent x labels in a faceted chart. Can you display the information another way, for example using an appropriate text mark?

**Comment by joelostblom** [comment]
Closing this as there is nothing to do on the Altair side of things. Once the functionality has been implemented in VL, it will be in an upcoming Altair release.
