### ISSUE TITLE
Multi selection without pressing shift key?

### ISSUE THREAD

**Issue by morberg** [altair-viz/altair#2151]
Is it possible to do a [multi selection](https://altair-viz.github.io/user_guide/generated/api/altair.selection_multi.html) without holding down the shift key?

I would like to single click on fields in the legend chart to toggle selection. Normal behavior is shift-click.

```python
import altair as alt
from vega_datasets import data

cars = data.cars.url

selection = alt.selection_multi(fields=['Origin', 'Cylinders'])

color = alt.condition(selection,
                      alt.Color('Origin:N', legend=None),
                      alt.value('lightgray'))

scatter = alt.Chart(cars).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color=color,
    tooltip='Name:N'
)

legend = alt.Chart(cars).mark_rect().encode(
    y=alt.Y('Origin:N', axis=alt.Axis(orient='right')),
    x='Cylinders:O',
    color=color
).add_selection(
    selection
)

scatter | legend
```
<img width="636" alt="image" src="https://user-images.githubusercontent.com/956034/81902484-7b1d5200-95c0-11ea-9644-ce41a7a741e6.png">

Things I have tried that had no effect:
```python
selection = alt.selection_multi(on='click', fields=['Origin', 'Cylinders'])
selection = alt.selection_multi(on='mousedown', fields=['Origin', 'Cylinders'])
```

Using either of
```python
selection = alt.selection_multi(on='click[event.altKey]', fields=['Origin', 'Cylinders'])
selection = alt.selection_multi(toggle='event.altKey', fields=['Origin', 'Cylinders'])
```
I can change the modifier from shift to alt, but I don't understand how I can enter no modifier. If I use `toggle=''` the legend reacts as if using `toggle=False`.

**Comment by jakevdp** [comment]
You can use:
```
selection = alt.selection_multi(fields=['Origin', 'Cylinders'], toggle="true")
```
See https://vega.github.io/vega-lite/docs/toggle.html: the ``toggle`` setting is a vega expressions that defaults to ``event.shiftKey``. Setting it to ``true`` makes it toggle on every click.

**Comment by morberg** [comment]
Thank you, that does the trick. I actually tried:
```
selection = alt.selection_multi(fields=['Origin', 'Cylinders'], toggle=True)
```
but that didn't work.

The current [documentation in Altair](https://altair-viz.github.io/user_guide/generated/api/altair.selection_multi.html) for `toggle:anyOf(string, boolean)` says:

> Default value: true, which corresponds to event.shiftKey (i.e., data values are toggled when a user interacts with the shift-key pressed).

Should that be changed?

**Comment by jakevdp** [comment]
don't use ``toggle=True``. Use ``toggle='true'`` (toggle is a string that contains a javascript expression).

**Comment by morberg** [comment]
> don't use `toggle=True`. Use `toggle='true'` (toggle is a string that contains a javascript expression). The default value, `toggle=True`, corresponds to `"event.shiftKey"`, as mentioned in the documentation.

Yup, that was clear in your first reply. Thank you for clarifying, though.

I was trying (and failing) to explain my confusion about the documentation.

The altair docs talks about `true` and `false` (lower case), which I thought was a javascript expression for Vega-lite. I think the documentation should use `True` and `False` (capitalized) instead to convey that it is referring to Python?

In my mind I translated the Default value `true` mentioned in the documentation to javascript `’true’`, not Python `True`. This also made me think that setting `toggle=’true’` would have no effect since that was already the default.

I now (think I) understand the default value is `True`? If this is not the case I am so confused I might be beyond saving.

**Comment by jakevdp** [comment]
This part of the docs is generated directly from the descriptions within the Vega-Lite schema, and we have no mechanism to make altair-specific spot-corrections like this. But the docs do mention that toggle takes a string containing a vega expression. Perhaps its not clear that ``'true'`` (the vega expression) is different from ``true`` (the boolean default). If you're interested, you could send a pull request to the Vega-Lite project clarifying that, and it would be reflected in Altair once Altair wraps the Vega-Lite release containing that update.

**Comment by morberg** [comment]
The doc modification is now in the latest vega-lite release (4.12.2)
