### ISSUE TITLE
Showing both x and y value in multi-line tooltip

### ISSUE THREAD

**Issue by robertodr** [altair-viz/altair#2152]
Hello, thanks for your work on this awesome visualization library.

I am looking to adapt the multi-line tooltip example (https://altair-viz.github.io/gallery/multiline_tooltip.html) to plot molecular spectra. I would like the tooltip to also  show the value of the x axis. I've added another text mark:
```
x_text = spectrum.mark_text(align="right", dx=-5, dy=-25).encode(
      text=alt.condition(nearest, "x:Q", alt.value(" "), format="3.4f")
   )
```
but was wondering:
a. Is there a better way to do this? 
b. How can I have the displayed x-value always appear at the bottom (or top) of the chart without fiddling with `dx` and `dy`?

**Comment by jakevdp** [comment]
Yes, I've been meaning to replace that example because it's overly verbose and confusing. With the pivot transform in Altair 4+, you can do something a bit more cleanly:
```python
import altair as alt
from vega_datasets import data

source = data.stocks.url

hover = alt.selection_single(
    fields=["date"],
    nearest=True,
    on="mouseover",
    empty="none",
    clear="mouseout"
)

lines = alt.Chart(source).mark_line().encode(
    x='date:T',
    y='price:Q',
    color='symbol:N',
)

points = lines.transform_filter(hover).mark_circle()

tooltips = alt.Chart(source).transform_pivot(
    "symbol", "price", groupby=["date"]
).mark_rule().encode(
    x='date:T',
    opacity=alt.condition(hover, alt.value(0.3), alt.value(0)),
    tooltip=["AAPL:Q", "AMZN:Q", "GOOG:Q", "IBM:Q", "MSFT:Q"]
).add_selection(hover)

lines + points + tooltips
```
This makes it trivial to add another tooltip field: just add an item to the list.

**Comment by robertodr** [comment]
Thanks. This _does_ look like what I'd like to achieve, but I can't make it work with my (much) simpler dataset [foo.zip](https://github.com/altair-viz/altair/files/4629026/foo.zip)
The Jupyter notebook actually freezes with my modifications to the example:
```
import altait as alt
import pandas as pd 

source = pd.read_csv("foo.csv")

hover = alt.selection_single(
    fields=["x"],
    nearest=True,
    on="mouseover",
    empty="none",
    clear="mouseout"
)

lines = alt.Chart(source).mark_line().encode(
    x='x:Q',
    y='y:Q',
)

points = lines.transform_filter(hover).mark_circle()

tooltips = alt.Chart(source).transform_pivot(
    "x", "y", groupby=["x"]
).mark_rule().encode(
    x='x:Q',
    opacity=alt.condition(hover, alt.value(0.3), alt.value(0)),
    tooltip=["x:Q", "y:Q"]
).add_selection(hover)

lines + points + tooltips
```

**Comment by jakevdp** [comment]
It will be difficult to help without knowing what the contentx of ``foo.csv`` are.

**Comment by robertodr** [comment]
Indeed! I attached the zipped CSV to my previous message. Its contents are the x and y for a single line.

**Comment by jakevdp** [comment]
You're pivoting x while grouping by x, which constructs an NxN data representation. Here N is 5000, so you're telling the browser to construct a data object with 25,000,000 elements.

That is... not recommended.

There's no reason to pivot a value while grouping by that same value. Remove the pivot transform and it should work.

**Comment by robertodr** [comment]
Thank you for pointing this silly mistake out! Closing this issue as I was able to make it work.
