### ISSUE TITLE
Support for Polar encoding channel

### ISSUE THREAD

**Issue by jayemar** [altair-viz/altair#2153]
I would like to use the Polar encoding channel described by [Vega Lite](https://vega.github.io/vega-lite/docs/encoding.html#channels) with Altair but it doesn't not seem to be [currently supported](https://altair-viz.github.io/user_guide/encoding.html#encoding-channels)

**Comment by jakevdp** [comment]
This will be available when Altair is updated to support Vega-Lite 4.9; See #2148 for a similar request

**Comment by jayemar** [comment]
Awesome, great work and thanks for the quick reply!

**Comment by joelostblom** [comment]
This has been added in Altair 4.2.0
