### ISSUE TITLE
Adding color attributes removes sorted order

### ISSUE THREAD

**Issue by ariel-j-w** [altair-viz/altair#2154]
It seems that when I add color to my bar chart, the sorted order disappears. Here's the full code:
```
import pandas as pd
import altair as alt

df = pd.DataFrame({
    'country': [
        'Bahrain',
        'Denmark',
        'Estonia',
        'Iceland',
        'Israel'
    ],
    'number':  [
        120,
        60,
        50,
        163,
        55
    ],
    'color': [
        'Salmon',
        'LightSteelBlue',
        'LemonChiffon',
        'Salmon',
        'LemmonChiffon'
    ]
})

bars = alt.Chart(df).mark_bar().encode(
    x = 'number',
    y = alt.Y('country', sort='-x'),
    color=alt.Color('color', scale=None)
)

text = bars.mark_text(
        align = 'left',
        color = 'gray',
        dx = 3
).encode(
    text = 'country'
)
```

With the above definition, `bars + text` produces the following visualization. The colors are working, but my data isn't sorted.
![visualization (2)](https://user-images.githubusercontent.com/36253822/82059874-9c4f7280-9694-11ea-86cf-a2301c2d27a2.png)

If I comment out the line with the color specification, my sorted order returns (though obviously without color):
![visualization (1)](https://user-images.githubusercontent.com/36253822/82059775-7fb33a80-9694-11ea-8307-351a2e0ff649.png)

Even more confusingly,  I can leave all code as is, and then just `bars` (without `text`) is still sorted and colorful (but without labels):
![visualization (3)](https://user-images.githubusercontent.com/36253822/82060154-f94b2880-9694-11ea-8831-7b4fd9b848d4.png)

**Comment by mattijn** [comment]
Please make your problem as small as possible and include data to avoid guessing. Something like:

```python
import pandas as pd
import altair as alt

df = pd.DataFrame([
    ['a', 2, 'z'],
    ['a', 3, 'z'],
    ['b', 4, 'y'],
    ['b', 5, 'y'],
    ['b', 4, 'y'],
    ['c', 8, 'x'],
    ], columns=['x', 'y', 'c'])

alt.Chart(df).mark_bar().encode(
    x=alt.X('x:N', sort=alt.EncodingSortField(field='x', order='ascending')), 
    y=alt.Y('y:Q'),
    color=alt.Color('c')
)
```
I'm just guessing about your data structure here, so no answers yet

**Comment by ariel-j-w** [comment]
Edited for clarity! Sorry about that.

**Comment by mattijn** [comment]
Others can probably better explain whats going on, but doing this:
```python
bars = alt.Chart(df).mark_bar().encode(
    x = 'number',
    y = alt.Y('country', sort=alt.EncodingSortField(field='number', op='sum', order='descending')),
    color=alt.Color('color', scale=None)
)

text = bars.mark_text(
        align = 'left',
        color = 'gray',
        dx = 3
).encode(
    text = 'country'
)

bars + text
``` 
Results for me in this:
<img width='500px' src='https://user-images.githubusercontent.com/5186265/82062559-94aac080-96ca-11ea-8104-0695e4d29cb9.png'>

**Comment by morberg** [comment]
Note that `color = 'gray'` does not affect anything in the current code. If you want gray text it should be moved to `encode`:

```python
text = bars.mark_text(
    align='left',
    dx=3
).encode(
    text='country',
    color=alt.value('gray')
)
```
