### ISSUE TITLE
Multiple Conditions for coloring points

### ISSUE THREAD

**Issue by hathawayj** [altair-viz/altair#2156]
## Problem

I am trying to simply color by two numerical conditions.  I can get the chart to work with one condition.  However, my inexperience with conditioning in Python and JavaScript leaves me wondering what I am doing wrong when I add two conditions.

## Import packages and load data

```python
import pandas as pd
import altair as alt
```

```python
mpg = pd.read_csv("https://github.com/byuidatascience/data4python4ds/raw/master/data-raw/mpg/mpg.csv")
```

I want this subset of data to be colored red

```python
mpg[mpg.displ.gt(5) & mpg.hwy.gt(20)]
```

## First color one condition chart that works

```python
(base.
  encode(x = 'displ',
         y = 'hwy',
         color = alt.condition((datum.displ > 5), 
                                alt.ColorValue('red'), 
                                alt.ColorValue('black'))).
  mark_point()
)
```
## Second plot with two conditions doesn't color according to the condition

```python
(base.
  encode(x = 'displ',
         y = 'hwy',
         color = alt.condition((datum.displ > 5) & (datum.mpg > 20), 
                                alt.ColorValue('red'), 
                                alt.ColorValue('black'))).
  mark_point()
)
```

**Comment by hathawayj** [comment]
Well...

there is not an `mpg` variable in my data frame. Mapping to the correct column fixes my issue.  I wish an error reported.

```python

(base.
  encode(x = 'displ',
         y = 'hwy',
         color = alt.condition((datum.displ > 5) & (datum.hwy > 20), 
                                alt.ColorValue('red'), 
                                alt.ColorValue('black'))).
  mark_point()
)
```

**Comment by jakevdp** [comment]
Glad you figured it out – no error is reported because ``datum.mpg`` is evaluated in Javascript, where missing attributes return ``undefined``, and ``undefined`` is not greater than 5.

There's no way to pre-empt this in Altair without potentially raising extraneous errors in cases where users depend on this behavior.
