### ISSUE TITLE
Facet layered charts from different data sources

### ISSUE THREAD

**Issue by johny-c** [altair-viz/altair#2158]
Hi all, first of all thanks a lot to the creators and contributors to this awesome library. 

I have the following use case. I want to layer a number of horizontal rules from data source A with some lines from data source B and then facet per some column (dataset).

```
base_lines = alt.Chart(df_baselines).mark_rule().encode(
    y='accuracy',
    color='algorithm',
)
new_lines = alt.Chart(df_new).mark_line().encode(
    x='grad_steps',
    y='accuracy',
    color='algorithm'
)

alt.layer(base_lines, new_lines).facet('dataset:N')
```

When I do this, I get the error:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-144-b1cb0f3510cc> in <module>
     14 )
     15 
---> 16 alt.layer(base_lines, new_lines).facet('dataset:N')

~/soft/miniconda3/envs/exp/lib/python3.8/site-packages/altair/vegalite/v4/api.py in facet(self, facet, row, column, data, columns, **kwargs)
   1861         if data is Undefined:
   1862             if self.data is Undefined:
-> 1863                 raise ValueError(
   1864                     "Facet charts require data to be specified at the top level."
   1865                 )

ValueError: Facet charts require data to be specified at the top level.
```

I found these related issues #282, #668, #785 but I couldn't make it work. Removing either data source from their base chart did produce a copy on every chart of the facet chart. And if I remove both, then which one should the facet data source be? The library is changing relatively fast, so perhaps these answers are obsolete?

I guess the problem is that df_baselines does not have a 'grad_steps' column. One way to solve this is to concatenate the data sources at the pandas level (and somehow impute the NaNs).

Is there a better / recommended way to do this without concatenating?

**Comment by debbes80** [comment]
You can use Transform_Lookup to 'merge' 2 dataframes:
[https://altair-viz.github.io/user_guide/transform/lookup.html](https://altair-viz.github.io/user_guide/transform/lookup.html)

If I facet the example, I get this:
```python
alt.Chart(groups).mark_circle().encode(
    x='age:Q',
    y='group:O'
).transform_lookup(
    lookup='person',
    from_=alt.LookupData(data=people, key='name',
                         fields=['age', 'height'])
).facet(
    row='height:O'
)
```
![visualization (2)](https://user-images.githubusercontent.com/54935651/82240519-d80b6600-993a-11ea-8cc9-5274b37b139e.png)

**Comment by jakevdp** [comment]
The only way to facet on multiple data sources is to use a ``transform_lookup`` to combine them into a single data source. Can you include a minimal example of the data?

**Comment by johny-c** [comment]
Hi, thanks for the reply. I'll look into this. A minimal example:

```
df_baselines = pd.DataFrame({
    'algorithm': ['nearest_neighbor', 'nearest_neighbor', 'random_forest', 'random_forest'],
    'dataset': ['cifar', 'mnist', 'cifar', 'mnist'],
    'accuracy': [0.876, 0.578, 0.456, 0.78]
})
df_new = pd.DataFrame({
    'algorithm': ['CNN1', 'CNN1', 'CNN1', 'CNN1', 'CNN1', 'CNN1'],
    'dataset': ['cifar', 'cifar', 'cifar', 'mnist', 'mnist', 'mnist'],
    'accuracy': [0.761, 0.784, 0.797, 0.456, 0.68, 0.89],
    'epoch': [32, 64, 96, 32, 64, 96]
})
```

I want to have one subplot per dataset and in each subplot the baselines as horizontal dashed lines and the new as "normal" lines.

**Comment by jakevdp** [comment]
So you want two panels, one for "cifar" and one for "MNIST", with two baselines in each panel and 3 "new" lines in each panel?

**Comment by johny-c** [comment]
Almost. In each panel, not 3 "new" lines, but one line that goes through n points (n=3 in this example).

**Comment by jakevdp** [comment]
The best way to do this will be to concatenate your datasets in pandas, and then create an Altair chart from the single dataset. The kind of multi-join required to do this from within Vega-Lite is going to be far too involved to be useful for you.

**Comment by johny-c** [comment]
Thanks for the quick reply :) 
Ok. It feels a bit wrong to do it with pandas because I have to set some x-range entries for the "baselines", which I don't need to with mark_rule. Is this kind of facet something that will be supported in the future or is it not "Grammar of Graphics"-friendly?

**Comment by jakevdp** [comment]
No, I don't think there are any plans to support faceting of multiple datasets without joining them either in the input or in the chart spec.

**Comment by johny-c** [comment]
Ok. Thanks :)
