### ISSUE TITLE
Duplicate signal name: "selector080_Fiscal_Week"

### ISSUE THREAD

**Issue by anshulcool1989** [altair-viz/altair#2159]
I am trying to create a regression line using Altair and Streamlit and I am getting the following error while trying to execute the same:
Duplicate signal name: "selector080_Fiscal_Week"

Below is the code I am using:
```python
import streamlit as st
import pandas as pd
import numpy as np
import altair as alt

def scatter_chart(f, col1, col2):
    scatter = alt.Chart(f).mark_point().encode(
    x=col1,
    y=col2,
    tooltip=[col1, col2]).interactive()
    reg = scatter.transform_regression(col1,col2).mark_line()
    return scatter

st.altair_chart(scatter_chart(df, scatter_opt1, scatter_opt2), use_container_width = True)
```

Please let me know the issue and how to resolve it ?

**Comment by jakevdp** [comment]
Working around the streamlit-specific portions of your code, the chart renders correctly. I would suggest raising the issue with the streamlit project: their chart rendering is a closed-source black box, so something must be going on under the hood that we cannot see.

**Comment by jakevdp** [comment]
Just for reference, the common way this error comes up is by layering two copies of an interactive chart; something like this:
```python
import altair as alt
chart = alt.Chart('data.csv').mark_point().interactive()
chart + chart
```
I don't see that in the code you pasted, so if this code reproduces the error it means that streamlit is doing something fishy under the hood.

**Comment by anshulcool1989** [comment]
I am returning "**return scatter + reg**" in my code.  May be this error is due to streamlit.

**Comment by jakevdp** [comment]
OK, in that case the issue is that you are layering two charts with the same interaction signal, exactly as in my snippet above. The solution is to put the interaction in only one of the layers, like this:
```
import altair as alt
chart = alt.Chart('data.csv').mark_point()
chart + chart.interactive()
```

**Comment by anshulcool1989** [comment]
Thanks a lot for the help. Your solution worked.
