### ISSUE TITLE
Can't pass in alt.Color() as a color for alt.condition()

### ISSUE THREAD

**Issue by ariel-j-w** [altair-viz/altair#2161]
I'm trying to impose brush selection on a dataset where the color values for each point are a column in the dataset. In general, I can use `alt.Color('color', scale=None)`, but in the context of brush selection, this hasn't played nice as a parameter in `alt.condition()`. To illustrate this, I adapted an example from the documented [Example Gallery](https://altair-viz.github.io/gallery/scatter_linked_table.html). I put comments `# CHANGED`where my code differs from the example.

```
import pandas as pd
import altair as alt
from vega_datasets import data

source = data.cars()

# CHANGED: Extra wrangling here to add a color column
origin_color_df = pd.DataFrame({
    'Origin': [
        'USA',
        'Europe',
        'Japan'
    ],
    'color': [
        'red',
        'orange',
        'blue'
    ]
})
data = source.merge(origin_color_df,on='Origin')

# Brush for selection
brush = alt.selection(type='interval')

# Scatter Plot
points = alt.Chart(source).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color=alt.condition(brush, alt.Color('color',scale=None), alt.value('grey')) # CHANGED: using alt.Color()
).add_selection(brush)

# Base chart for data tables
ranked_text = alt.Chart(source).mark_text().encode(
    y=alt.Y('row_number:O',axis=None)
).transform_window(
    row_number='row_number()'
).transform_filter(
    brush
).transform_window(
    rank='rank(row_number)'
).transform_filter(
    alt.datum.rank<20
)

# Data Tables
horsepower = ranked_text.encode(text='Horsepower:N').properties(title='Horsepower')
mpg = ranked_text.encode(text='Miles_per_Gallon:N').properties(title='MPG')
origin = ranked_text.encode(text='Origin:N').properties(title='Origin')
text = alt.hconcat(horsepower, mpg, origin) # Combine data tables

# Build chart
alt.hconcat(
    points,
    text
).resolve_legend(
    color="independent"
)
```

I get the following error: 
**ValueError:** color encoding field is specified without a type; the type cannot be automatically inferred because the data is not specified as a pandas.DataFrame.

**Comment by jakevdp** [comment]
You should specify the encoding type: ``alt.Color('color:N')``. This is not required in some circumstances, but it's a good idea to get in the habit of doing it because the default is not always what you want.

Also, it look like you meant to pass ``data`` to the chart, rather than ``source``.
