### ISSUE TITLE
Slope Graph Higllight

### ISSUE THREAD

**Issue by kejid** [altair-viz/altair#2162]
Hello there,

I was playing with this example of slope graph

```
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_line().encode(
    x='year:O',
    y='median(yield)',
    color='site'
).properties(
    width=300,
    height=300
)
```

And failed to do:
- highlight just **one line**, I was to make focus on
- make positive/negative slopes with different colors

Is there is any way to make such color conditions for slope graph? 

Thank you for awesome lib

**Comment by Rik-de-Kort** [comment]
For the highlight, you could use the size encoding to highlight. Normally we would use opacity, but it doesn't work very well when charts are coloured.

````python
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_line().encode(
    x='year:O',
    y='median(yield)',
    color='site',
    size=alt.condition(alt.datum.site=="Crookston", alt.value(3.0), alt.value(1.0))
).properties(
    width=300,
    height=300
)
````

To highlight the slopes of different colours, you can add a slope column to the DataFrame and use that. I've faceted the charts by site so you can still see the different relationships.

````python
df = source.pivot_table(index=["site"], columns="year", values="yield")
df["slope"] = (df[1932] - df[1931]).apply(lambda x: "negative" if x < 0 else "positive")
df = df.reset_index().melt(id_vars=["site", "slope"], value_name="yield")

alt.Chart(df).mark_line().encode(
    x='year:O',
    y='median(yield)',
    color='slope:N',
    facet='site'
)
````

Does that answer your question?

**Comment by kejid** [comment]
@Rik-de-Kort thanks for a response!
i was hoping to do something with colors, because it's more obvious for viewer if only one line is highlighted and other are gray.
If there is no way to do it with altair, then your workaround will do

**Comment by jakevdp** [comment]
Are you looking for something like this?
```python
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_line().encode(
    x='year:O',
    y='median(yield)',
    color=alt.condition(alt.datum.site == 'Duluth', 'site', alt.value('lightgray'))
).properties(
    width=300,
    height=300
)
```
![visualization - 2020-05-25T070353 082](https://user-images.githubusercontent.com/781659/82819837-ee8f5100-9e55-11ea-9c79-e3e3363bc593.png)

**Comment by kejid** [comment]
@jakevdp you are magician. So the trick was
`alt.datum.site == 'Duluth', 'site',`
with second attribute.
