### ISSUE TITLE
Tooltips don't work in Firefox

### ISSUE THREAD

**Issue by carderne** [altair-viz/altair#2164]
Just getting started transitioning new viz work to Altair.

The [scatter plot tooltip example](https://altair-viz.github.io/gallery/scatter_tooltips.html) from the docs doesn't seem to work properly in Firefox (but fine in Chrome). No matter how hard I hover no tooltips show up.

OS: Ubuntu 20.04
Browser: Firefox 76.0.1 with all addons disabled

**Comment by jakevdp** [comment]
Thanks – this is an issue with the Vega-Lite renderer. I'd suggest reporting it at http://github.com/vega/vega-lite.

**Comment by carderne** [comment]
Thanks will do. Suspected so but wasn't sure.

**Comment by carderne** [comment]
Two notes:
- it was caused by Firefox blocking canvas data extraction, see [comment](https://github.com/vega/vega-lite/issues/6521#issuecomment-632222470)
- I didn’t have the same issue with vega-lite’s examples, domoritz suggested (subsequent comment) this has something to do with (not) using the SVG renderer

**Comment by joelostblom** [comment]
@carderne This is working fine for me in Firefox 85, are you still experience the issue or could we close this ticket?

**Comment by carderne** [comment]
See my comment above. If canvas data extraction is disabled (which I think is the default in the more stringent Firefox privacy settings), then the issue persists.

But this is a purely vega-lite issue, and even then not at all restricted to vega-lite (I see similar with Mapbox and some other libraries), so more a Firefox issue (or maybe some things are just impossible without access canvas data).

Feel free to close.

**Comment by joelostblom** [comment]
Thanks for clarifying @carderne!
