### ISSUE TITLE
Trouble with json data transformer

### ISSUE THREAD

**Issue by eitanlees** [altair-viz/altair#2165]
I am having trouble using the json data transformer. For example

```python 
import altair as alt
from vega_datasets import data

alt.data_transformers.enable('json')

temps = data.seattle_temps()

alt.Chart(temps).mark_line().encode(
    x='date:T',
    y='temp:Q'
)
```
![visualization](https://user-images.githubusercontent.com/2041969/82611015-8c042f80-9b8d-11ea-82ca-6afe25830678.png)

I don't know why this is blank. If I instead use the URL, then everything works as expected

```python
alt.Chart(data.seattle_temps.url).mark_line().encode(
    x='date:T',
    y='temp:Q'
)
```

![visualization (1)](https://user-images.githubusercontent.com/2041969/82611046-9e7e6900-9b8d-11ea-834c-f78f4b94302a.png)

I checked the dict output and it's got the name correct. 

```python
alt.Chart(temps).mark_line().to_dict()
```

```
{'$schema': 'https://vega.github.io/schema/vega-lite/v4.8.1.json',
 'config': {'view': {'continuousHeight': 300, 'continuousWidth': 400}},
 'data': {'format': {'type': 'json'},
  'url': 'altair-data-724d6426c5eb0a15708f1ea6286b0a8d.json'},
 'mark': 'line'}
```

**Comment by jakevdp** [comment]
The issue is that different Jupyter frontends access the local filesystem in different ways. In general I'd recommend avoiding the JSON data transformer because of this.

**Comment by jakevdp** [comment]
See #1867 for more information

**Comment by eitanlees** [comment]
Good to know! 

Is
```python
alt.data_transformers.enable('data_server')
```
what you would recommend for datasets with more than 5000 rows?

If so I can add some more information to the documentation to make that more clear.

**Comment by jakevdp** [comment]
Yeah, that's probably better, though its usage must also be adjusted for remote Jupyter instances.

Unfortunately, with all the different ways that Jupyter is run in the world, I've not been able to find any one-size-fits-all solution (and every time I think do, something changes somewhere and it stops working).

But generally I think the gotchas for``data_server`` are less common than the ones for ``json``.
