### ISSUE TITLE
Color Condition with current Average

### ISSUE THREAD

**Issue by AndreasBuc** [altair-viz/altair#2166]
Hi everyone, 
I have found these two beautiful Altair Charts in the example Gallery and I would like to combine them:
https://altair-viz.github.io/gallery/bar_chart_with_negatives.html
https://altair-viz.github.io/gallery/selection_layer_bar_month.html
in a way, that the color changes due to the current average. 

Unfortunately I have no clue how to grab the current average value to compare it with in the color condition statement. 
Has anyone a clue? 
Thanks 
Andreas

**Comment by jakevdp** [comment]
Use a [joinaggregate](https://altair-viz.github.io/user_guide/transform/joinaggregate.html) transform to compute the mean, then use this new field in the condition; something like this:
```python
import altair as alt
from vega_datasets import data

source = data.us_employment()

alt.Chart(source).transform_joinaggregate(
    mean_change='mean(nonfarm_change)'
).mark_bar().encode(
    x="month:T",
    y="nonfarm_change:Q",
    color=alt.condition(
        alt.datum.nonfarm_change > alt.datum.mean_change,
        alt.value("steelblue"),  # The positive color
        alt.value("orange")  # The negative color
    )
).properties(width=600)
```

**Comment by AndreasBuc** [comment]
Thanks a lot, just what I was looking for. 
I had to bind the scaling and then it worked just fine

Example using the Car Dataset:
_______________________________________
# Selection
    brush = alt.selection_interval(encodings=['x'])
# Line for Average
    line = alt.Chart(df).mark_rule(color='grey').encode(
        y='mean(Miles_per_Gallon):Q',
    ).transform_filter(
        brush
    )
# Text for Average
    text = line.mark_text(align='left', dx=5, dy=-5, color='grey').encode(
        text='mean(Miles_per_Gallon):Q',
        size=alt.SizeValue(14)
    )
# Base Chart
    chart= line.mark_point().transform_joinaggregate(
        mean_mpg_dyn='mean(Miles_per_Gallon)'
        ).encode(
        alt.X('Horsepower:Q', scale=alt.Scale(domain=(40, 240))),
        alt.Y('Miles_per_Gallon:Q', scale=alt.Scale(domain=(0, 50))),
        color=alt.condition(
            alt.datum.Miles_per_Gallon > alt.datum.mean_mpg_dyn,
            alt.value("steelblue"),  # The positive color
            alt.value("orange")  # The negative color
        )
    ).add_selection(
        brush
    ).properties(
        width=400,
        height=400
    )

    chart= alt.layer(chart, line, text)
