### ISSUE TITLE
customizing widgets

### ISSUE THREAD

**Issue by sbonaretti** [altair-viz/altair#2167]
Hi,

Where can I find info on how to customize widgets? E.g. slider length or position wrt to graph?

Thanks!

**Comment by jakevdp** [comment]
The only way to customize widgets is using CSS. I'd suggest using your browser's DOM inspector to see what the relevant class and id names are.

**Comment by sbonaretti** [comment]
Thanks! How do I connect the CSS to a Jupyter notebook? Is there any example around?

**Comment by jakevdp** [comment]
You can use IPython's HTML display:
```python
from IPython.core.display import display, HTML
display(HTML('<style>...</style>'))
```
