### ISSUE TITLE
Chart interaction and brush selection interfering

### ISSUE THREAD

**Issue by Rik-de-Kort** [altair-viz/altair#2168]
I am trying to have a pannable and zoomable chart with a brush selection. If we just add `interactive()` to a chart, it will interfere with the brush selection and make things weird. So I thought I'd bind the scales separately with an "on" kwarg like in the [user guide for multiple selections](https://altair-viz.github.io/user_guide/interactions.html#composing-multiple-selections). Code below as a copy-pastable example.  
However, this doesn't behave well: even without holding the shift key, dragging will still move the chart around. Is this a vega-lite/vega issue, and is there a workaround?

````python
from vega_datasets import data
df = data.disasters()
df.Year = pd.to_datetime(df.Year, format="%Y")

brush = alt.selection(
    type="interval",
    encodings=["x"],
    on="[mousedown[event.altKey], mouseup] > mousemove",
)

interaction = alt.selection(
    type="interval",
    bind="scales",
    on="[mousedown[event.shiftKey], mouseup] > mousemove",
)

alt.Chart(df).mark_bar().encode(
    x="Year",
    y="sum(Deaths)",
    color="Entity",
    opacity=alt.condition(brush, alt.OpacityValue(1), alt.OpacityValue(0.7)),
).add_selection(
    brush,
    interaction
)
````

**Comment by jakevdp** [comment]
You need to set additional properties if you want ``translate`` and ``zoom`` behavior to require a particular key to be held:
```python
brush = alt.selection(
    type="interval",
    encodings=["x"],
    on="[mousedown[event.altKey], mouseup] > mousemove",
    translate="[mousedown[event.altKey], mouseup] > mousemove!",
    zoom="wheel![event.altKey]",
)

interaction = alt.selection(
    type="interval",
    bind="scales",
    on="[mousedown[event.shiftKey], mouseup] > mousemove",
    translate="[mousedown[event.shiftKey], mouseup] > mousemove!",
    zoom="wheel![event.shiftKey]",
)
```

**Comment by Rik-de-Kort** [comment]
That works, thanks!

**Comment by Luttik** [comment]
@jakevdp would it also be possible to use a negation in the mousedown filter? It would be lovely if we can modify your example to something where the brush is applied when the altKey is down and the interaction is applied when the altKey is not down.

**Comment by jakevdp** [comment]
@Luttik Sure, it would look something like this:
```python
brush = alt.selection(
    type="interval",
    encodings=["x"],
    on="[mousedown[event.altKey], mouseup] > mousemove",
    translate="[mousedown[event.altKey], mouseup] > mousemove!",
    zoom="wheel![event.altKey]",
)

interaction = alt.selection(
    type="interval",
    bind="scales",
    on="[mousedown[!event.altKey], mouseup] > mousemove",
    translate="[mousedown[!event.altKey], mouseup] > mousemove!",
    zoom="wheel![!event.altKey]",
)
```

**Comment by Luttik** [comment]
Great @jakevdp, big respect for how insanely responsive you are. 

Since the `!` was also used to prevent the default behaviour I didn't think to try this. (although it is then placed in a different position).

I have another question.  If you want another option than the alt, shift or control key say the space key. How would you go about that. I've tried `[mousedown[event.keyCode==32], mouseup] > mousemove!` but that doesn't work :/. The [documentation](https://vega.github.io/vega/docs/event-streams/#selector) does state that the filter is an "expression" but the [expression documentation](https://vega.github.io/vega/docs/expressions/) doesn't seem to describe an equality check (it does state that `event.keyCode` is an concept. 

(I purely ask this here and not in another place since this now contains the best examples concerning selection filters that I could find)

**Comment by jakevdp** [comment]
I don't know how to do that. You might find the answer in the Vega event stream docs: https://vega.github.io/vega/docs/event-streams/#selector

**Comment by VietTralala** [comment]
> You need to set additional properties if you want `translate` and `zoom` behavior to require a particular key to be held:
> 
> ```python
> brush = alt.selection(
>     type="interval",
>     encodings=["x"],
>     on="[mousedown[event.altKey], mouseup] > mousemove",
>     translate="[mousedown[event.altKey], mouseup] > mousemove!",
>     zoom="wheel![event.altKey]",
> )
> 
> interaction = alt.selection(
>     type="interval",
>     bind="scales",
>     on="[mousedown[event.shiftKey], mouseup] > mousemove",
>     translate="[mousedown[event.shiftKey], mouseup] > mousemove!",
>     zoom="wheel![event.shiftKey]",
> )
> ```

This solution somehow disables tooltips for the selected data. Unfortunately I dont understand why this happens. Is this intended? 

Here is a slightly adopted minimal working example with tooltips:

```
import pandas as pd
import altair as alt
from vega_datasets import data
df = data.disasters()
df.Year = pd.to_datetime(df.Year, format="%Y")

brush = alt.selection(
    type="interval",
    encodings=["x"],
    on="[mousedown[event.altKey], mouseup] > mousemove",
    translate="[mousedown[event.altKey], mouseup] > mousemove!",
    zoom="wheel![event.altKey]",
)

interaction = alt.selection(
    type="interval",
    bind="scales",
    on="[mousedown[event.shiftKey], mouseup] > mousemove",
    translate="[mousedown[event.shiftKey], mouseup] > mousemove!",
    zoom="wheel![event.shiftKey]",
)


alt.Chart(df).mark_bar().encode(
    x="Year",
    y="sum(Deaths)",
    color="Entity",
    opacity=alt.condition(brush, alt.OpacityValue(1), alt.OpacityValue(0.7)),
    tooltip=['Entity', 'Year', 'Deaths',]
).add_selection(
    brush,
    interaction
).interactive()
```
