### ISSUE TITLE
CI: Possible mismatch between google-chrome-stable and chromium-chromedriver

### ISSUE THREAD

**Issue by dsaxton** [altair-viz/altair#2174]
I noticed the CI seems to be failing with an error about the Chrome version so that may need to be synced with the Chrome driver somehow.

**Sample pipeline**

https://github.com/altair-viz/altair/pull/2171/checks?check_run_id=704880466

**Error message**

```python
>       raise exception_class(message, screen, stacktrace)
E       selenium.common.exceptions.SessionNotCreatedException: Message: session not created: This version of ChromeDriver only supports Chrome version 81
```

**Relevant workflow**

https://github.com/altair-viz/altair/blob/52732ab3660392c0c41786683f4ba8a276ee00ad/.github/workflows/build.yml#L22

**Comment by jakevdp** [comment]
Yeah, this kind of thing can happen. It's likely due to github updating what's installed in the linux actions container.

**Comment by dsaxton** [comment]
Looks like there's a script for this kind of thing in a GitHub Actions repo: https://github.com/actions/virtual-environments/blob/master/images/linux/scripts/installers/google-chrome.sh. I tried lifting a few lines from this in another PR and was getting some errors, but it seems doable.
