### ISSUE TITLE
Composing predicates in alt.condition() is tedious

### ISSUE THREAD

**Issue by dechamps** [altair-viz/altair#2176]
I want to OR two predicates in an `alt.condition()` call.

Initially I just assumed I could use a similar syntax as for [`transform_filter()`](https://altair-viz.github.io/user_guide/transform/filter.html#logical-operands):

```python
(alt.Chart(data=None)
    .mark_circle()
    .encode(color=alt.condition({'or': [
                    alt.FieldEqualPredicate(field='field1', equal='value1'),
                    alt.FieldEqualPredicate(field='field2', equal='value2'),
                ]}, alt.value('red'), alt.value('green'))))
```

But that doesn't work:

```
SchemaValidationError: Invalid specification
        altair.vegalite.v4.schema.channels.ColorValue, validating 'additionalProperties'
        Additional properties are not allowed ('or' was unexpected)
```

Then I thought maybe the operators would work:

```python
(alt.Chart(data=None)
    .mark_circle()
    .encode(color=alt.condition(
            alt.FieldEqualPredicate(field='field1', equal='value1') |
            alt.FieldEqualPredicate(field='field2', equal='value2'),
        alt.value('red'), alt.value('green'))))
```

But nope:

```
TypeError: unsupported operand type(s) for |: 'FieldEqualPredicate' and 'FieldEqualPredicate'
```

After fumbling around in the dark for some time, this is the best I came up with:

```python
(alt.Chart(data=None)
    .mark_circle()
    .encode(color=alt.condition(alt.LogicalOrPredicate(**{'or': [
                    alt.FieldEqualPredicate(field='field1', equal='value1'),
                    alt.FieldEqualPredicate(field='field2', equal='value2'),
                ]}), alt.value('red'), alt.value('green'))))
```

This actually works, but the syntax is contrived and this approach doesn't seem documented. Should the API be improved, or am I missing something here?

**Comment by jakevdp** [comment]
That works; a clearer option is probably this:
```python
(alt.Chart(data=None)
    .mark_circle()
    .encode(color=alt.condition(
        (alt.datum.field1 == 'value1') | (alt.datum.field2 == 'value2'),
        alt.value('red'), alt.value('green')))
)
```
Adding operator support to other predicates is tracked here: #695

**Comment by joelostblom** [comment]
@dechamps I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
