### ISSUE TITLE
Display both a bottom and top title for facet chart

### ISSUE THREAD

**Issue by taralloc** [altair-viz/altair#2177]
I have the following plot
![visualization (3)](https://user-images.githubusercontent.com/13621287/82897950-be7ca680-9f58-11ea-8d70-63e7c687e187.png)
obtained from this code:
```python
import altair as alt
from vega_datasets import data
import pandas

data1 = data.cars()[data.cars()['Year'] <= pandas.to_datetime(1970)]
data2 = data.cars()[data.cars()['Year'] > pandas.to_datetime(1970)]

boxplot = alt.Chart().mark_boxplot(color='black').encode(
    alt.Y(f'Miles_per_Gallon:Q')
).properties(width=200)

violin = alt.Chart().transform_density(
    'Miles_per_Gallon',
    as_=['Miles_per_Gallon', 'density'],
    extent=[5, 50],
    groupby=['Origin']
).mark_area(orient='horizontal').encode(
    y='Miles_per_Gallon:Q',
    color=alt.Color('Origin:N', legend=None),
    x=alt.X(
        'density:Q',
        stack='center',
        impute=None,
        title=None,
        scale=alt.Scale(nice=False, zero=False),
        axis=alt.Axis(labels=False, values=[0], grid=False, ticks=True),
    ),
)

facet = lambda data: alt.layer(violin, boxplot, data=data).facet(column='Origin:N').resolve_scale(x=alt.ResolveMode("independent"))

alt.hconcat(facet(data1),facet(data2)).configure_facet(
    spacing=0,
).configure_header(
    titleOrient='bottom',
    labelOrient='bottom'
).configure_view(
    stroke=None
).show()
```
I would like to add a title above the left facet and above the right facet, like so:
![visualization (3)](https://user-images.githubusercontent.com/13621287/82898207-26cb8800-9f59-11ea-837f-f55fbf6f4117.png)

How to do that? I tried setting the Header of each facet, but doing that replaces the 'Origin' title at the bottom of each facet.

**Comment by taralloc** [comment]
Slight improvement:
![visualization (4)](https://user-images.githubusercontent.com/13621287/82906480-9a739200-9f65-11ea-8b0b-790bb6060b05.png)
now using
```python
facet = lambda data, title: alt.layer(violin, boxplot, data=data).facet(column='Origin:N').\
    resolve_scale(x=alt.ResolveMode("independent")).properties(title=alt.TitleParams(text=title, anchor="middle", align="center"))

alt.hconcat(facet(data1, "Until 1970"),facet(data2, "After 1970")).configure_facet(
    spacing=0,
).configure_header(
    titleOrient='bottom',
    labelOrient='bottom'
).configure_view(
    stroke=None
).show()
```
However, the two titles are not horizontally well aligned with the 'Origin' title at the bottom, nor with the subcharts themselves. Is there some grammar to make them automatically correctly aligned?

**Comment by jakevdp** [comment]
Using the ``title`` property is the way to create titles for concatenated charts. I'm not aware of any way in Vega-Lite to specify that chart titles should be aligned with facet header titles.

**Comment by taralloc** [comment]
Thanks! I'll use the `dx` property then.
