### ISSUE TITLE
Bar chart not responding to width argument

### ISSUE THREAD

**Issue by rubik** [altair-viz/altair#218]
I don't understand why this bar chart does not change in size when I pass different values to the `width` parameter of the `configure_cell` method:
```python
Chart(most_important).mark_bar().encode(
    x=X('Features:O',
        sort=SortField(field='Features')),
    y='Importance:Q',
).configure_cell(width=1500).display()
```

Result:
![vega](https://cloud.githubusercontent.com/assets/238549/19122344/545ebdec-8b2a-11e6-994b-1e168305e16f.png)

All my other charts correctly set their width. The one difference between this chart and others is that this one has text labels on the X axis, but that shouldn't be an issue.

**Comment by jakevdp** [comment]
Hi @rubik – this is a bit confusing. The width of bar elements is fixed and does not scale with the cell width. You can adjust the width of these bars using the ``bandSize`` argument of the scale:

```python
Chart(data).mark_bar().encode(
    x=X('Features:O',
        sort=SortField(field='Features')),
    y='Importance:Q',
).configure_scale(bandSize=40)
```

I don't find this all that intuitive personally, but I think I recall some discussion in Vega-Lite about making the bandSize scale to the cell width.

**Comment by jakevdp** [comment]
I'll add one thing: in a future release, you'll be able to set ``bandSize="fit"`` in order to fit the band size to the overall plot size.

**Comment by rubik** [comment]
@jakevdp Thanks for the quick reply. Indeed, that's what I was looking for! I do find it confusing, so +1 from me for `bandSize='fit'`.

**Comment by jakevdp** [comment]
I've added #219 to remind me to put sizing info in the docs once we upgrade Vega-Lite. I'm going to close this one now.

**Comment by jakevdp** [comment]
Thanks for the question/report!
