### ISSUE TITLE
Date sort graph

### ISSUE THREAD

**Issue by coSaari** [altair-viz/altair#2181]
For some reason I am trying to graph a series of date on my x axis, and I believe it is sorting on another feature. Is there anyway I can sort by ascending for the date axis??

![visualization](https://user-images.githubusercontent.com/59755050/83065906-7f665800-a021-11ea-8f20-75e8a1533415.png)

```python
source = newDF.copy()
base = alt.Chart(source).encode(x='Date').properties(
title={
    "text": ["Average Deals Per Dealership","Month of : May"],
    "subtitle" : ["(Excluding Sundays)"," ", "Black : ACT", "Red : BCA", "Green : GRV"]}
)
bar = base.mark_bar().encode(y='Total Deals')

#ACT
line1 =  base.mark_line(color='black').encode(
    alt.Y("average(ACT):Q")
)
#BCA
line2 =  base.mark_line(color='red').encode(
    alt.Y("average(BCA):Q")
)
#GRV
line3 =  base.mark_line(color='green').encode(
    alt.Y("average(GRV):Q")
)

(bar + line1 + line2 + line3).properties(width=600)
```

**Comment by jakevdp** [comment]
What is ``newDF``? The answer to your question will depend on the content of the dataframe, and in particular the dtype of the ``Date`` column.

**Comment by coSaari** [comment]
#Deals
from datetime import datetime

newDF["Date"] = pd.to_datetime(newDF["Date"])

newDF = pd.DataFrame()

newDF["Date"] = x["Date"].iloc[52:]
newDF["index"] = newDF.index

newDF["ACT"] = x["Deals"]
newDF["BCA"] = x["Deals.1"]
newDF["GRV"] = x["Deals.2"]

newDF["Total Deals"] = x["Total Deals"]

newDF.head(50)
<img width="391" alt="Screenshot 2020-05-27 14 14 16" src="https://user-images.githubusercontent.com/59755050/83067728-69a66200-a024-11ea-8f52-0dd37a053794.png">

**Comment by coSaari** [comment]
I converted it to a datetime object and it is sorted in the dataframe

**Comment by coSaari** [comment]
never mind I fixed it !! thank you for your response!!!

**Comment by joelostblom** [comment]
@coSaari I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
