### ISSUE TITLE
Transform_lookup on TopoJSON file with nested objects

### ISSUE THREAD

**Issue by josepzhang** [altair-viz/altair#2182]
Is it possible to perform a transform_lookup data transformation on a TopoJSON file with nested objects?

I've tried running the below code:

Gap_2019 being a pandas dataframe.

SA3 = alt.topo_feature("https://raw.githubusercontent.com/josepzhang/DVN/master/SA3_2016_AUST%20(2).json", "SA3_2016_AUST")

Gap_chart_SA3 = alt.Chart(SA3).mark_geoshape().encode(
    color = 'properties.SA3_NAME16:Q'
).transform_lookup(
    lookup='properties.SA3_NAME16',
    from_=alt.LookupData(Gap_2019, 'SA3_NAME16', ['Gap in required places'])
).properties(
    width=600,
    height=600
).project('mercator')

**Comment by mattijn** [comment]
Your example is not reproducible. But more information can much likely be found in https://github.com/altair-viz/altair/issues/1357. 

If it solves your issue, please include a small working code here before closing this issue. 

If it did not solve the problem please return with a small reproducible example (data included, preferably from the example datasets).

**Comment by josepzhang** [comment]
Thanks Matt, I used #588 to fix my issue - merged data through geopandas and then converted geopandas file to json which ran through altair. Cheers.
