### ISSUE TITLE
.interactive() unresponsive in Jupyter Notebook after updating to Altair 4.0

### ISSUE THREAD

**Issue by ymagid1** [altair-viz/altair#2183]
I have a number of visualization in Jupyter Notebook for which the .interactive() feature has worked in the past. After updating to Altair 4.0 and updating vega, the interactive zoom feature is no longer responsive in Jupyter Notebook or Jupyter Lab. All other features work as normal. Any assistance getting this resolved would be much appreciated.

**Comment by jakevdp** [comment]
I'm not aware of any other reports of this since v4.0 came out half a year ago. What browser are you using? What frontend are you using (jupyterlab? jupyter notebook?) Are you enabling any renderers? Do you see any warnings or errors in the browser's javascript console?

**Comment by ymagid1** [comment]
-> I am using Altair v4.1. 
-> I am using Chrome.
-> I am using Jupyter Notebook, I have also tried Jupyterlab, but I get the same result.
-> I have tried enabling the 'notebook' renderer, but when I do so I do not get any output when running the cell. I switched to the 'default' renderer and I can now get the output with all other features, but the interactive zoom feature is unresponsive. 

I get the following warnings in the console:
1) WARN Cannot project a selection on encoding channel "x" as it uses an aggregate function ("sum").
2) WARN Scale bindings are currently only supported for scales with unbinned, continuous domains.
3) kernel.js:1008 Couldn't process kernel message SyntaxError: Unexpected end of JSON input

This is the code I am using:

selection = alt.selection_multi(fields=['mode'], bind='legend')
chart = alt.Chart(df).mark_bar().encode(
    y=alt.Y('region', title='Governorates', sort=alt.EncodingSortField(field="event", op="sum", order='ascending')),
    x=alt.X('sum(event)', stack='zero', title='Number of Attacks'),
    color=alt.Color('mode', legend=alt.Legend(title="Type of attack"), scale=alt.Scale(scheme='Dark2')),
    opacity=alt.condition(selection, alt.value(1), alt.value(0.2)),
    tooltip=['region', 'mode', 'event']
).properties(
    projection={'type': 'identity', 'reflectY': True},
    width=400,
    height=300,
    title='Settler Attacks by Type and Governorate (Jan, 2010 - May, 2020)'
).configure_axis(
    gridColor='lightgrey',
    gridOpacity=.5,
    gridWidth=.5
).configure_title(fontSize=16
).interactive(
).add_selection(
    selection
)
#chart.save('chart_test.html')
chart

**Comment by jakevdp** [comment]
"scale bindings" are what creates interaction. The warning you pasted is telling you why this is not working.

**Comment by ymagid1** [comment]
OK, I see, thanks for your response. I was confused since this had worked in the past, but no longer works after coming back to it a few months later and updating Altair. 

Is there a way to use the interactive zoom feature with a categorical Y axis?

**Comment by jakevdp** [comment]
No, Altair has never supported interactive zoom for ordinal or nominal axes.

**Comment by joelostblom** [comment]
@ymagid1 I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
