### ISSUE TITLE
Maintaining Lookup_transform data in a Transform_filter

### ISSUE THREAD

**Issue by Murtz5253** [altair-viz/altair#2186]
I have the following code:

> slider = alt.binding_range(min=0, max=60, step=1)
select_day = alt.selection_single(name="day", fields=['day'],
                                   bind=slider, init={'day': 0})

> alt.Chart(states).mark_geoshape().encode(
>     alt.Color('interventionFootprint:Q', scale=alt.Scale(domain=(0.0, 1.02)))
> ).transform_filter(
>     select_day
> ).transform_lookup(
>     lookup='id',
>     from_=alt.LookupData(extended_state_df, 'id',  ['interventionFootprint'])
> ).properties(
>     width=500,
>     height=300
> ).add_selection(
>     select_day
> ).project(
>     type='albersUsa'
> ).resolve_scale(
>     color='independent'
> )
> 

The states data is a pointer to a json from vega_datasets, and the lookup_transform dataframe is of my own making. This code works without the time slider (if I edit the dataframe a bit). The issue with the time slider is that I need to filter on data in the lookup_transform dataframe, but Altair does not appear to allow it. I also tried a workaround by reading in the states json file separately so that I could just merge the dataframes beforehand, but that also did not work (pd.read_json does not work on the states json file; I do not understand how it is formatted).

Is there a way to get around this?

**Comment by Murtz5253** [comment]
I'd like to follow up that what I am trying to do is similar to this:

https://github.com/altair-viz/altair/issues/1357

However, I cannot quite get the spec to work.

**Comment by joelostblom** [comment]
@Murtz5253 I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to add a comment with a reproducible example so that we can try to resolve the issue or close it if it is no longer affecting you?
