### ISSUE TITLE
"Hole" in area plot when data contains missing values

### ISSUE THREAD

**Issue by LeCyberDucky** [altair-viz/altair#2187]
Hi, 

I have been having some trouble in trying to stack some area plots on top of each other. 
Basically, I have two data sets of spectrum data for different light sources. One is AM1.5G (can be downloaded [here](https://www.nrel.gov/grid/solar-resource/assets/data/astmg173.xls)), and the other is from an LED (data found [here](http://galileo.graphycs.cegepsherbrooke.qc.ca/app/en/lamps/2545)).

I basically want to plot these two data sets as areas on top of each other, so I have been following what is shown here: [Altair Horizon Graph](https://altair-viz.github.io/gallery/horizon_graph.html). I load both data sets into pandas data frames and then I merge them into one, filling missing entries with NaN. See my code below:

```
import altair as alt
import pandas as pd
import numpy as np

# Altair config
alt.renderers.enable("svg") # Only non-blurry way to show plots in hydrogen

### Indoor light
# Solar spectrum
AM15 = pd.read_excel("astmg173.xls", header = 1)
AM15.columns.values[0] = "wavelength"
AM15.columns.values[2] = "Global"

# LED_A19_domestic-use_softwhite-color_Philips-brand_11W_120V_75.5Lum_2700K
LED = pd.read_csv("LED - Philips - A19.txt", sep = "\t", header=0)
LED.columns.values[1] = "LED relInt"

# https://stackoverflow.com/questions/53645882/pandas-merging-101
spectrums = AM15.merge(LED, on = "wavelength", how = "outer")
```
Now to my problem. If I use just the AM1.5 data for an area plot, by doing this:

```
alt.Chart(AM15).mark_area(
).encode(
    x = "wavelength:Q",
    y = "Global:Q",
)
```
I get this: 

![image](https://user-images.githubusercontent.com/19520383/83521823-0b73f600-a4e0-11ea-9636-c60bdbb1b884.png)

If I, however, use the merged data frame to plot the same thing as follows:

```
alt.Chart(spectrums).mark_area(
).encode(
    x = "wavelength:Q",
    y = "Global:Q",
)
```
I get this: 

![image](https://user-images.githubusercontent.com/19520383/83521845-14fd5e00-a4e0-11ea-94dc-e5ac464e6114.png)

I can't figure out what's going wrong here. I assume something's up because merging the two data sets introduces missing values, but I'm not sure how I should be handling that differently. 

I have since figured out that I can circumvent this problem by making two separate charts using the original data and adding them like this: `area1 + area2`, but I would still like to know what's going on with my original attempt. As a side note, I feel like a bit more explanatory text could be useful for the documentation I linked, since it doesn't really explain why it is doing things the way it is. Based on that documentation page I thought that merging my data was necessary.

**Comment by jakevdp** [comment]
Without looking at the data, I suspect what's happening is that the two datasets are defined on different wavelength grids, so when you apply an outer join you end up with NaNs alternating with defined values. An area chart of a single defined value between two undefined values draws nothing (an area under a single point has width zero and is invisible). You could address this using an [impute transform](https://altair-viz.github.io/user_guide/transform/impute.html) to specify what you want shown in place of undefined values.

**Comment by LeCyberDucky** [comment]
Yes, that sounds plausible. Thanks for your response! Trying the different possible impute options, I still can't quite get the wanted behavior this way, so I'll just keep going with the work around of combining two separate charts. But I'm glad to have the insight into why the original attempt broke :)
