### ISSUE TITLE
Issue with X axislabes/ticks disappearing in layered chart

### ISSUE THREAD

**Issue by gschlossnagle** [altair-viz/altair#2188]
I have a layered chart with custom sorting that I'm generating like this:
```
a = alt.Chart(source).mark_point(opacity=0.05).encode(
  y=alt.Y('asn:N', title='ASN', sort=sort),
  x=alt.X('median:Q', 
          axis=alt.Axis(title='', format='%', orient='bottom'), 
          scale=alt.Scale(domain=(-1,1), clamp=True))
)
b = alt.Chart(s2).mark_point(color='red').encode(
  y=alt.Y('asn:N', 
          sort=sort, title='', axis=alt.Axis(labels=False, ticks=False)),
  x=alt.X('median:Q', axis=alt.Axis(labels=False, ticks=False))
)
(a+b).properties(
    title='Inboxing Performance for Self-Hosted Senders, by ASN (top 20)', 
    width=600, background='white'
).resolve_scale(y='independent')
```

![visualization (77)](https://user-images.githubusercontent.com/4212973/83566951-cacfa900-a4ee-11ea-9e51-78006c3da19e.png)

Despite having the X axis oriented to the bottom, it is entirely clipped off. If I display it using a non-layered version, that one chart looks correct:
```
(a).properties(
    title='Inboxing Performance for Self-Hosted Senders, by ASN (top 20)', 
    width=600, background='white'
).resolve_scale(y='independent')
```

![visualization (78)](https://user-images.githubusercontent.com/4212973/83566985-db801f00-a4ee-11ea-8683-4c8ca538a1ee.png)

I'm using the resolve_scale() to work-around the issue of sort not working in layered charts (which I observe if I remove it).

The expected result is that I could orient the axis in a layered graph to appear on the bottom.

**Comment by eitanlees** [comment]
I would pass the sort explicitly using `alt.EncodingSortField`. Here is a [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) which I think is similar. 

```python
import altair as alt
import pandas as pd
import numpy as np
import uuid

n = 5
m = 100
ids = [uuid.uuid4().hex[:6] for _ in range(n)]
rng = np.random.RandomState(0)
samples = np.stack([rng.normal(size=(m)) for _ in range(n)]).T
df = pd.DataFrame(data=samples, columns=ids)

median_sort = alt.EncodingSortField('value', op='median', order='descending')

base = alt.Chart(df).transform_fold(ids, as_ = ['group', 'value']).encode(
    alt.Y('group:N', sort=median_sort)
)

alt.layer(
    base.mark_circle(opacity=0.25).encode(x='value:Q'), 
    base.mark_circle(color='red').encode(x='median(value):Q')
)
```

![visualization (5)](https://user-images.githubusercontent.com/2041969/83573854-3a976100-a4fa-11ea-9564-9d95abd528a0.png)

The example "[Sorted Error Bars showing Confidence Interval](https://altair-viz.github.io/gallery/sorted_error_bars_with_ci.html)" uses a similar method.

**Comment by gschlossnagle** [comment]
Perfect.  Thank you.
