### ISSUE TITLE
interactive between multiple datasets sharing with one index column

### ISSUE THREAD

**Issue by Zakk-Yang** [altair-viz/altair#2189]
Hi,

Is it possible to highlight or filter data based on the same index column between different dataframe?

**Comment by jakevdp** [comment]
You can only do this if you join the datasets using a [lookup transform](https://altair-viz.github.io/user_guide/transform/lookup.html)

**Comment by joelostblom** [comment]
@Zakk-Yang I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
