### ISSUE TITLE
Altair 4.1 "scale_factor" seems to do nothing

### ISSUE THREAD

**Issue by zacharylawrence** [altair-viz/altair#2191]
Using Altair 4.0, I'm able to adjust the resolution of an output PNG with `scale_factor`:
```python
chart.save("filename.png", scale_factor=2.0)
```

In Altair 4.1, adjusting `scale_factor` doesn't seem to change the output resolution.

Is this possibly related to altair_saver?

As referenced here: https://altair-viz.github.io/user_guide/saving_charts.html#figure-size-resolution

**Comment by jakevdp** [comment]
Altair 4.1 changed it's `save` to use `altair_saver` under the hood, so this bug is likely related to failing to plumb that value through correctly.

**Comment by jasonrwang** [comment]
@taralloc's PR fixes the resolution issue for me, but now I get weird spacing between characters.

New
<img width="288" alt="image" src="https://user-images.githubusercontent.com/6628281/122518907-11dfed80-cfcf-11eb-8f9d-34ff587a0a1e.png">
Old
<img width="161" alt="image" src="https://user-images.githubusercontent.com/6628281/122518970-245a2700-cfcf-11eb-8bb5-1636379f5ef7.png">

(I'm on Node v10.24.1, Altair 4.1, Altair Saver 0.5.0 with adjustment; macOS 11.2.3).

**Comment by baldwint** [comment]
Using @taralloc's branch also fixed it for me. I did not observe any strange spacing between characters.

node v15.4.0, altair 4.2.0, python 3.9.2, macOS 10.14.6.

**Comment by joelostblom** [comment]
This has been fixed in Altair's development branch by switching to vl-convert for saving images. It is still an issue for altair_saver which is tracked in https://github.com/altair-viz/altair/issues/2191
