### ISSUE TITLE
Categorical heatmap hack - how to add row-titles?

### ISSUE THREAD

**Issue by tobsecret** [altair-viz/altair#2192]
## Aim
I am looking to make a categorical heatmap, made up of individual strips with different categorical columns in a dataframe, somewhat similar to this figure:
![image](https://user-images.githubusercontent.com/10303623/83704516-48271680-a5e0-11ea-84f8-c07fb7bfb1ad.png)
taken from [this paper](https://www.cell.com/cell/fulltext/S0092-8674(19)30292-2).
## What I need help with
I cannot figure out how to add row labels to the heatmap.

## Making the heatmap
I use `mark_rect` and only give it an `x` and a `color`. Then I remove the legend, vconcat and remove the spacing between the individual plots. The legend would provide the row label I am looking for but I have to remove it, otherwise I cannot put the individual heatmap strips together tightly.

## Making the legends
For the legends, I do the same as for the heatmap, except I don't give an `x` in `encode()`, just a `color`. 

## Configuring
Finally, I `configure_concat` to make the heatmap strips snugg and `configure_view` to remove the outline of the empty plots that each of the legends comes with.

```python
import pandas as pd
import altair as alt
#### Generating some Data ####
source = pd.DataFrame(
    {'fruits':['apple', 'banana', 'orange'], 
     'shape':['round', 'long', 'round'], 
     'weight':[0.3, 0.1, 0.25]})
#### Making the Heatmap ####
heatmap = alt.vconcat(
    alt.Chart(source).mark_rect().encode(
        x = alt.X('fruits', axis=None),
        color = alt.Color('shape', legend=None),
    ),
    alt.Chart(source).mark_rect().encode(
        x = 'fruits',
        color = alt.Color('weight', legend=None),
    )
)
#### Making the Legends ####
legends = alt.vconcat(
    alt.Chart(source).mark_rect(
        fillOpacity=0, 
        strokeOpacity=0
    ).encode(
        color = alt.Color('shape'),
    ), 
     alt.Chart(source).mark_rect(
        fillOpacity=0, 
        strokeOpacity=0
    ).encode(
        color = alt.Color('weight'),
    ), 
)

#### Configuring the concat ####
(
    heatmap | legends
).configure_concat(spacing=0 #makes strips of heatmap snugg
).configure_view(strokeOpacity=0) #removes plot border for the empty plots with the legends
```
This gives me the following heatmap:
![visualization (3)](https://user-images.githubusercontent.com/10303623/83709782-3ac45900-a5ed-11ea-9a96-41cd4e74609d.png)

## Adding Row labels
The row labels here should be `'shape'` and `'weight'` but I cannot get that to work.
My idea was to use the title as a row label with `orient='left'` and `angle=90` but that doesn't seem to work. 
```
alt.Chart(source, title="shape").mark_rect().encode(
        x = alt.X('fruits', axis=None),
        color = alt.Color('shape', legend=None),
).configure_title(
    orient='left',
    angle=90
)
```
![visualization (4)](https://user-images.githubusercontent.com/10303623/83714103-d5299a00-a5f7-11ea-9918-6946a73450d2.png)

I don't think I understand what the `angle` argument does in `configure_title`, because it doesn't seem to rotate the title text, whether I give `orient` or not. From the docstring of `configure_title`:
>angle : float
>    Angle in degrees of title and subtitle text.

## Thanks
Thank you for all the awesomeness in altair, the library is a true delight!

**Comment by jakevdp** [comment]
One way to do this kind of thing is to use a fold transform, and then use either a row encoding or a y-encoding; something like this:
```python
import altair as alt
import pandas as pd

source = pd.DataFrame(
    {'fruits':['apple', 'banana', 'orange'], 
     'shape':['round', 'long', 'round'], 
     'weight':[0.3, 0.1, 0.25]})

alt.Chart(source).transform_fold(
    ["shape", "weight"]
).mark_rect().encode(
    x='fruits:N',
    y='key:N',
    color=alt.Color('value:N', legend=None)
)
```
![visualization (4)](https://user-images.githubusercontent.com/781659/83715192-b3bdb380-a5e1-11ea-8921-a2fe38402f62.png)

This only works if you're OK with all values being represented by the same color scale.

**Comment by tobsecret** [comment]
Wow, so fast! thanks for the reply!

Hmmm, yes that does look very pretty (both code and plot) but the color scale is the issue. 
I should have mentioned this in the OP, but one nice thing about making the rows of the heatmap individually is that altair rolls an individual color palette for each row. 
That is relevant in this example because we have `shape` which is categorical and `weight` which is continuous. 

When I was sleeping, I thought of a hacky way to get what I wanted, using a dummy column with the column name as the y-axis (new lines marked with #):
```python
 import pandas as pd
import altair as alt
example_data = pd.DataFrame(
    {
        'fruits':['apple', 'banana', 'orange'],
        'shape':['round', 'long', 'round'], 
        'shape_col': ['shape']*3, ########
        'weight':[0.3, 0.1, 0.25],
        'weight_col':['weight']*3 ########
    }
)
heatmap = alt.vconcat(
    alt.Chart(example_data).mark_rect().encode(
        x = alt.X('fruits', axis=None),
        y = alt.Y('shape_col', title=None), ########
        color = alt.Color('shape', legend=None),
    ),
    alt.Chart(example_data).mark_rect().encode(
        x = 'fruits',
        y = alt.Y('weight_col', title=None), ########
        color = alt.Color('weight', legend=None),
    )
)
legends = alt.vconcat(
    alt.Chart(example_data).mark_rect(
        fillOpacity=0, 
        strokeOpacity=0
    ).encode(
        color = alt.Color('shape'),
    ), 
     alt.Chart(example_data).mark_rect(
        fillOpacity=0, 
        strokeOpacity=0
    ).encode(
        color = alt.Color('weight'),
    ), 
)

(
    heatmap | legends
).configure_concat(spacing=0
).configure_view(strokeOpacity=0)
```

![visualization (5)](https://user-images.githubusercontent.com/10303623/83775803-5ebb8500-a655-11ea-8019-c432ecd540fa.png)

**Comment by jakevdp** [comment]
You could also use a calculate transform in place of the dummyh column. It will be even easier once Altair supports the `datum` specification that was recently added in Vega-Lite.

**Comment by tobsecret** [comment]
Oooh, yes that would make it a lot more elegant!
Which option would I best use then? Browsing the `alt.expr`, I stumbled on toString, but I'm not quite sure I'm using it correctly. I thought it would just fill in the specified data with the string I provided:
```python
import pandas as pd
import altair as alt
example_data = pd.DataFrame(
    {
        'fruits':['apple', 'banana', 'orange'],
        'shape':['round', 'long', 'round'], 
        'shape_col': ['shape']*3,
        'weight':[0.3, 0.1, 0.25],
        'weight_col':['weight']*3
    }
)
############ Plot ############
alt.Chart(example_data).mark_rect().encode(
        x = alt.X('fruits'),
#         y = alt.Y('shape_col', title=None),
        color = alt.Color('shape'),
    ).transform_calculate(
    y=alt.expr.toString('shape')
)
```
![visualization (6)](https://user-images.githubusercontent.com/10303623/83885188-00a1a700-a714-11ea-88e2-ba7475ce3907.png)

**Comment by jakevdp** [comment]
Unless you reference the calculation in an encoding, it will not be used in the chart:
```python
alt.Chart(example_data).mark_rect().encode(
        x = alt.X('fruits'),
        y = alt.Y('y:N', title=None),
        color = alt.Color('shape'),
    ).transform_calculate(
    y='"shape"'
)
```

**Comment by tobsecret** [comment]
Oooh, wow! Thanks a ton! I had just made the individual rows of the DataFrame in a list comprehension and assigned the dummy column to `'y'` in each iteration, using `pd.DataFrame.assign`, but this seems a lot sleeker.

**Comment by tobsecret** [comment]
Thank you again for all the help! This way, I have been able to code up a function for plotting a heatmap with mixed categorical and numerical annotations as a heatmap.
