### ISSUE TITLE
alt.expr cannot represent arrays

### ISSUE THREAD

**Issue by dechamps** [altair-viz/altair#2194]
Consider the following, which uses an array-valued field to make a multiline color key (although array-valued fields could be used for a variety of other purposes as well):

```python
(alt.Chart(data=pd.DataFrame([{'value': 0}, {'value': 1}]))
    .mark_circle()
    .transform_calculate(label='["value", datum.value]')
    .encode(alt.Color('label', type='nominal')))
```
![visualization(100)](https://user-images.githubusercontent.com/866859/83945466-b3e8c980-a802-11ea-89b7-9c62fd841320.png)

It doesn't look like that that calculate transform can be expressed using `alt.expr`. For example the following doesn't work in Altair 4.1.0:

```python
(alt.Chart(data=pd.DataFrame([{'value': 0}, {'value': 1}]))
    .mark_circle()
    .transform_calculate(label=['value', alt.datum.value])
    .encode(alt.Color('label', type='nominal')))
```
```
SchemaValidationError: Invalid specification
        altair.vegalite.v4.schema.core.CalculateTransform->calculate, validating 'type'
        ['value', 'datum.value'] is not of type 'string'
```

**Comment by jakevdp** [comment]
Yep, ``alt.expr`` is a convenience wrapper for creating simple expressions, but cannot represent all possible vega expression strings. In the cases that it doesn't cover, the recommended approach is to write the vega expression string directlyl
