### ISSUE TITLE
Subtitle should be a top-level kwarg

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#2195]
Subtitles are so commonly used that it seems a shame, if I have it right, that you need to write something this intricate to make one.

```python
import altair as alt
from vega_datasets import data
source = data.iowa_electricity()
alt.Chart(source).mark_area().encode(
    x="year:T",
    y=alt.Y("net_generation:Q", stack="normalize"),
    color="source:N"
).properties(
    title={ 
      "text": "Iowa's green energy boom",
      "subtitle": "A growing share of the state's energy has come from renewable sources"
    }
)
```
![visualization (10)](https://user-images.githubusercontent.com/9993/83955562-ef869200-a808-11ea-868c-d1f7b6752f88.png)

In my mind, something like this would be preferable.

```python
alt.Chart(source).mark_area().encode(
    x="year:T",
    y=alt.Y("net_generation:Q", stack="normalize"),
    color="source:N"
).properties(
    title="Iowa's green energy boom",
    subtitle="A growing share of the state's energy has come from renewable sources"
)
```

 In my line of work, we put subtitles on nearly every chart we publish. So I'd like to see access this option be as easy as possible. If I can help devise and implement a tweak, please let me know.

**Comment by johnmdonich** [comment]
While at first glance it may seem like subtitle should be a top level view specification object if you look at how the [title spec](https://vega.github.io/vega-lite/docs/title.html) is constructed in Vega Lite it makes more intuitive sense to group all the subtitle properties in same object as the title because there are properties that apply to both the title and the subtitle. 

For instance the title `align` prop applies to both the title and the subtitle. It would be redundant to have to set those properties twice.

**Comment by jakevdp** [comment]
Altair’s tip-level Chart arguments aren’t drawn directly from Vega-Lite’s schema. For a variety of reasons, I am strongly against diverging from this. You might request this change at the Vega-Lite level if you think it would be beneficial.

**Comment by joelostblom** [comment]
Closing as there is nothing to do on the Altair side of things here. Also note that this works, which is quite convenient:

```py
# alt.TitleParams instead of alt.Title in 4.2.0 and below
alt.Chart(source, title=alt.Title('Main title', subtitle='Subtitle')).mark_area().encode(
    x="year:T",
    y=alt.Y("net_generation:Q", stack="normalize"),
    color="source:N"
)
```

**Comment by palewire** [comment]
That's a great example, @joelostblom. Is it represented anywhere in the official documentation? If not, I'd be happy to work it in as a PR.

**Comment by joelostblom** [comment]
Yes, that would be great! There is an open issue for this in https://github.com/altair-viz/altair/issues/2748 which links some examples I posted on SO earlier, so if you want to build on that it would be very welcome!
