### ISSUE TITLE
Text Overlay on % Stacked Chart

### ISSUE THREAD

**Issue by anshulcool1989** [altair-viz/altair#2196]
Hi,

I want to create a % stacked chart with a "%" number written as text on top of it.
```
alt.Chart(df).mark_bar().encode(
            x=alt.X(col1+":N"),
            y=alt.Y('sum(col2)', stack = 'normalize' , axis=alt.Axis(format='%')),
            color=alt.Color(col3)) 
```

Request you to please help me with this.

Thanks in advance.

**Comment by jakevdp** [comment]
Here is an example of a stacked bar chart with a text overlay: https://altair-viz.github.io/gallery/stacked_bar_chart_with_text.html

Does that answer your question?

**Comment by joelostblom** [comment]
@anshulcool1989 I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
