### ISSUE TITLE
How do I change the font size of the column title in a grouped bar chart?

### ISSUE THREAD

**Issue by 4MangoTrees** [altair-viz/altair#2197]
I'm working on JupyterNotebook, and I have this sample code to try and learn a concept if possible. My sample dataframe looks like this:

```python
df = pd.DataFrame([['Cat', 3, 'F', 'red'], 
                   ['Dog', 5, 'F', 'blue'], 
                   ['Cat', 4, 'M', 'red'], 
                   ['Dog', 6, 'M', 'blue']], 
                  columns=['Pet', 'Age', 'Gender', 'color'])
```

I will visualize using altair with this code:

```python
chart = alt.Chart(df).mark_bar(size = 60).encode(
   column='Pet',
   x = "Gender",
   y = "Age",
   color=alt.Color('color', scale=None),
).properties(
    width=125,
    height=300,
).configure_title().configure_axis(
    labelFontSize = 12,
    titleFontSize = 14
)
chart
```

I want to increase the size of the column title (I think thats the name?) "Pet" to be larger. How can I do that?

Edit: This is my first time using this to ask a question, I'm unsure how to format the code to make it look right

**Comment by jakevdp** [comment]
Column header properties can be adjusted with the ``header`` attribute of the `column` encoding; for example:
```python
column=alt.Column('Pet', header=alt.Header(titleFontSize=20))
```
You can read about all the available properties in the [`alt.Header` documentation](https://altair-viz.github.io/user_guide/generated/core/altair.Header.html).

You can format code on github in blocks surrounded by three backticks.
