### ISSUE TITLE
Charts not displaying on Jupyter Notebbok

### ISSUE THREAD

**Issue by hugo-pires** [altair-viz/altair#220]
Hello

I have tried to run your tutorials on Jupyter Notebook. It doesn't return any error, but I can't see any charts.

Could you help? Thanks.

**Comment by jakevdp** [comment]
Hi – how did you install the library? This sounds like the ipyvega Jupyter plugin is not correctly configured. This configuration is set automatically if you install altair with conda, but there's an extra step required if you install altair with pip. See the installation instructions here: https://altair-viz.github.io/installation.html

**Comment by hugo-pires** [comment]
It works. Thank you very much.

**Comment by jakevdp** [comment]
Great! FYI, we're exploring how to offer more useful error messages for this problem, as it's come up several times. See #200
