### ISSUE TITLE
Previous solution to flip color scale no longer works

### ISSUE THREAD

**Issue by caleb-lindgren** [altair-viz/altair#2204]
I have the same problem presented in #1068, but the solution given there no longer works. I am using the ["redblue"](https://vega.github.io/vega/docs/schemes/#redblue) diverging color scheme, and I want to flip it so that red corresponds to higher values and blue corresponds to lower values. (Unfortunately there's no "bluered" color scheme in Vega.)

Here is what I'm currently getting (colors not mapped the way I want):
```
...
color=alt.Color(
        "mean_expr:Q",
        scale=alt.Scale(
            scheme="redblue"
        ),
...
```
![wrong_mapping](https://user-images.githubusercontent.com/47534910/84311936-61b8e880-ab21-11ea-8ec2-747fb5c130b5.png)

As suggested in #1068, you can kind of fix things by reversing the domain. However, this doesn't solve the problem, because the color legend is still upside down, even though the colors are now mapped to the correct values:
```
...
color=alt.Color(
        "mean_expr:Q",
        scale=alt.Scale(
            scheme="redblue",
            domain=[1, -1]
        ),
...
```
![upside_down_scale](https://user-images.githubusercontent.com/47534910/84311934-61205200-ab21-11ea-9686-7f24930cc05d.png)

The solution given previously was to pass `sort="descending"` to the `alt.SchemeParams` object, but this no longer works. Based on https://github.com/vega/vega-lite/issues/4116, it looks like this was due to some change in Vega-Lite.

```
...
color=alt.Color(
        "mean_expr:Q",
        scale=alt.Scale(
            scheme=alt.SchemeParams(
                name="redblue",
                sort="descending"
            ),
        ),
...
```
![param_error](https://user-images.githubusercontent.com/47534910/84311938-61b8e880-ab21-11ea-850a-64246afcc2ed.png)

Based on #268, I did try passing the desired colors to the `range` parameter of `alt.Color`, but because the data are continuous, not discrete, that made just it look weird:
```
...
    color=alt.Color(
        "mean_expr:Q",
        scale=alt.Scale(
            domain=[-1, 0, 1],
            range=["blue", "white", "red"]
        ),
...
```
![weird_colors](https://user-images.githubusercontent.com/47534910/84313130-54046280-ab23-11ea-8726-6141649e2ca3.png)

I also tried reversing the domain, and then using the `direction` and `orient` parameters for `alt.Legend` to print the color legend right side up instead of upside down, but all the argument combinations I tried passing didn't have any effect, for some reason--the color legend was printed the same every time.

Is there a replacement for the `sort="descending"` option that will produce the same results--that is, invert the color scale mapping, but not print the scale upside down?

**Comment by joelostblom** [comment]
@caleb-lindgren I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to add a comment with a reproducible example so that we can try to resolve the issue or close it if it is no longer affecting you?

**Comment by caleb-lindgren** [comment]
Definitely, sorry I didn't provide reproducible examples before. The one below is derived from the [Altair Simple Heatmap example](https://altair-viz.github.io/gallery/simple_heatmap.html).

This is the plot I want to create--red is mapped to positive values, blue to negative values, and white to zero. However, unlike the plot below, I would like the legend scale to be flipped, so the red and positive numbers are at the top instead of the bottom.

```
import altair as alt
import numpy as np
import pandas as pd

# Compute x^2 + y^2 across a 2D grid
x, y = np.meshgrid(range(-5, 5), range(-5, 5))
z = x ** 2 - y ** 2

# Convert this grid to columnar data expected by Altair
source = pd.DataFrame({'x': x.ravel(),
                     'y': y.ravel(),
                     'z': z.ravel()})

alt.Chart(source).mark_rect().encode(
    x='x:O',
    y='y:O',
    color=alt.Color(
        "z:Q",
        scale=alt.Scale(
            scheme="redblue",
            domain=[25, -25]
        )
    )
)
```
![image](https://user-images.githubusercontent.com/47534910/108909797-3fe59000-75e2-11eb-879b-aae26642e6d7.png)

**Comment by caleb-lindgren** [comment]
The methods I explored above still don't work.

**Comment by joelostblom** [comment]
Ah I see, does changing `domain=[25, -25]` to `reverse=True` do what you want?

**Comment by caleb-lindgren** [comment]
Yep that does it! Thanks. Is there somewhere in the documentation where I can find this sort of thing?

**Comment by joelostblom** [comment]
Hmmm I don't think there is a section about it, it is only mentioned in the API reference from what I can see. I opened #2418
