### ISSUE TITLE
stroke opacity in legend on layered charts

### ISSUE THREAD

**Issue by kegl** [altair-viz/altair#2207]
Hi Everyone,

Thanks to all the developers form the wonderful library!

I am combining `mark_line` and `mark_area` in two layers and it seems that the legend "inherits" the opacity from the are plot. I would like to have opacity 1 for the legend stroke. Here is a minimum example:
```
import pandas as pd
import altair as alt

data_df = pd.DataFrame(
    [[0, 0.5, 0.4, 0.6, 'A'],
     [1, 0.5, 0.45, 0.55, 'A'],
     [0, 0.3, 0.25, 0.35, 'B'],
     [1, 0.3, 0.2, 0.4, 'B']],
    columns=['step', 'mean', 'cil', 'ciu', 'method'])

error_band_fig = alt.Chart(data_df).mark_area(opacity=0.2).encode(
    x='step:Q',
    y='cil:Q',
    y2='ciu:Q',
    color=alt.Color('method:N'),
)

mean_fig = alt.Chart(data_df).mark_line(size=1).encode(
    x=alt.X('step:Q'),
    y=alt.Y('mean:Q'),
    color=alt.Color('method:N', scale=alt.Scale(scheme='category10')),
)

alt.layer(error_band_fig, mean_fig).configure_axis(
    labelFontSize=20,
    titleFontSize=20
).configure_legend(
    titleColor='black', titleFontSize=20, labelFontSize=20, labelLimit=1300,
    symbolSize=500, symbolStrokeWidth=3, symbolType='stroke', symbolOpacity=1.0) 
```

![image](https://user-images.githubusercontent.com/703722/84597148-19bbfd80-ae62-11ea-80cc-f81ad102364b.png)

Setting legend to None in the area makes the legend disappear. I could change the symbol type from the inherited circle to stroke in `configure_legend` but the opacity doesn't seem to take effect. I also tried to change the order of the layers, no success.

**Comment by jakevdp** [comment]
You can set ``resolve_legend(color='independent')`` so the two charts have separate rather than shared legends, then set `legend=None` for the legend you want to be hidden:
```python
error_band_fig = alt.Chart(data_df).mark_area(opacity=0.2).encode(
    x='step:Q',
    y='cil:Q',
    y2='ciu:Q',
    color=alt.Color('method:N', legend=None),
)

mean_fig = alt.Chart(data_df).mark_line(size=1).encode(
    x=alt.X('step:Q'),
    y=alt.Y('mean:Q'),
    color=alt.Color('method:N', scale=alt.Scale(scheme='category10')),
)

alt.layer(error_band_fig, mean_fig).configure_axis(
    labelFontSize=20,
    titleFontSize=20
).configure_legend(
    titleColor='black', titleFontSize=20, labelFontSize=20, labelLimit=1300,
    symbolSize=500, symbolStrokeWidth=3, symbolType='stroke', symbolOpacity=1.0
).resolve_legend(color='independent') 
```
![visualization - 2020-06-14T110404 077](https://user-images.githubusercontent.com/781659/84600538-c4b2c400-ae2e-11ea-875b-85be22b633d2.png)

**Comment by kegl** [comment]
Thanks a lot @jakevdp
