### ISSUE TITLE
'==' not working in transform_filter when using value from selection

### ISSUE THREAD

**Issue by MattJBritton** [altair-viz/altair#2209]
I am trying to create a chart in which the user can make a selection, and the selection is used to filer the output of another chart. In the basic example below, the user can click a stock in a line chart, and see the symbol of the stock in a "details pane" to the right of the line chart. 

In order to do this, the second chart (which displays the filtered output) needs to access the filter value directly from the selection, and then use that calculated value in a `transform_filter()`. Oddly, when I do this using `==`, the filter does not work! When I use `<=` and `>=` together (basically creating `==` from the intersection), then it does work as intended.

I am aware that in this simplified scenario, I could have used the selection directly in `transform_filter()`. However, in my original use case the two charts use different data sets with different field names, and the selected value is used in a calculation before being filtered on, so this solution does not work in general.

```py
import altair as alt
from vega_datasets import data

selector = alt.selection_single(fields = ["symbol"])
line = alt.Chart(data.stocks.url).mark_line().encode(
    x='date:T',
    y='price:Q',
    color='symbol:N',
    opacity = alt.condition(selector, alt.value(1), alt.value(.5))
).add_selection(
    selector
)

selected_symbol = alt.Chart(data.stocks.url).mark_text().encode(
    text = "symbol",
).transform_calculate(
     selected_val = selector["symbol"]
).transform_filter(
     #alt.datum.symbol == alt.datum.selected_val #does not work, but should
     (alt.datum.symbol >= alt.datum.selected_val) & (alt.datum.symbol <= alt.datum.selected_val)
).properties(
     width = 100
)

line | selected_symbol
```

**Comment by jakevdp** [comment]
The expression
```
selector["symbol"]
```
returns a length-1 list, e.g. `["GOOG"]`.

When you create a vega expression using ``==``, it is translated to a javascript strict equality (`===`) because this is closest to Python's equality semantics. Evaluating ``'GOOG' === ['GOOG']`` in javascript returns `false`.

When you create a vega expression using `>=`, it is translated to javascript's `>=`, which uses non-strict equality semantics. Evaluating ``'GOOG' == ['GOOG']`` in javascript returns `true`.

That's the source of the strange behavior... so what's the best approach to fix it? I would probably recommend using a vega expression string directly with the semantics you want:
```
# ...
).transform_filter(
     "datum.symbol == datum.selected_val"
)
# ...
```

**Comment by MattJBritton** [comment]
Thanks for the quick reply and the solution. I'm sure there are good reasons for this, but why does the expression to get the selector value (`selector["symbol"]`) return a length-1 list?

Would it be possible to add some guidance on this to the documentation? I based my example off of this [section](https://altair-viz.github.io/user_guide/interactions.html#selection-values-in-expressions), which uses a `<` in the vega expression (not as a string), and so led me to believe that `==` would work there too.

**Comment by jakevdp** [comment]
> why does the expression to get the selector value (selector["symbol"]) return a length-1 list?

This is a decision made by vega-lite. I'm not certain what the reasoning is.

> Would it be possible to add some guidance on this to the documentation? 

Yes – anyone is able to add to the documentation via pull request.

**Comment by joelostblom** [comment]
@MattJBritton I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
