### ISSUE TITLE
Downsample / window size for large graphs

### ISSUE THREAD

**Issue by kaustavha** [altair-viz/altair#2211]
Hi for graphs with very large numbers of data points is there a way to downsample or window the graph? 

So only a subset of bars/X-axis points are rendered at one time, with others being rendered on scroll or something. 
e.g. a bar chart with 1000 bars, only rendering 10 at a time

The interactivity is very slow with all the data points rendered.

**Comment by jakevdp** [comment]
Yes, you can make binnings respond to selections. There is an example here: https://altair-viz.github.io/gallery/histogram_responsive.html#gallery-histogram-responsive

**Comment by kaustavha** [comment]
Ah perfect, appreciate the help @jakevdp ! 
Will give it a shot early this week and try to resolve this issue.   
Really grateful for the prompt and helpful response.       

---

Fun fact: i worked at ibm cognos bi for a bit and was one of 2 core devs implementing thier auto-grouping/downsampling/clustering/of data point or window sizing  feature(s). 
it was also called "binning" under the hood!

But i do miss the laziness/idiocy support of just being able to drag and drop data groups and just let it guesstimate the best graph for you. hoping i can eventually emulate that here.  
will be trying to use this for:
- grafana replacement in databracks
- vizes for understanding and knowledge
- vizes for bi and ml
- audit tracking for database changes
- performant long timeline graphs with lots of datapoints
