### ISSUE TITLE
Inconsistent behaviour of line chart - shows negative y-axis in one chart but not in other, when both have only positive values

### ISSUE THREAD

**Issue by armsp** [altair-viz/altair#2214]
Asking it here since it does look like an issue. Let me know if i should ask it on SO.

I will show two different graphs to illustrate this issue.
## How I noticed this problem?
```py
import altair as alt
import pandas as pd
alt.data_transformers.enable('json')
state_data_uri = 'https://raw.githubusercontent.com/nytimes/covid-19-data/master/us-states.csv'
states_raw = pd.read_csv(state_data_uri)
c = states_raw[states_raw['state'] == 'California']
c['cpd'] = c['cases'].diff()

#Plot
base = alt.Chart(c).mark_bar(opacity=1, width=6.5).encode(
    x='date:T',
    y=alt.Y('cpd:Q'),#,scale=alt.Scale(domain=(0, 4000))),
    color = alt.condition(alt.datum.date > alt.expr.toDate('2020-06-07') , alt.value('rgba(186,37,62,.8)'), alt.value('#c8c8c8'))
)

start = pd.DataFrame([{'start': '2020-03-19', 'end': c['date'].max()}])
rect = alt.Chart(start).mark_rect(opacity=0.2, fill='grey').encode(
    x = alt.X('start:T'),
    x2 = 'end:T',
)

line = base.mark_line(stroke='black', opacity=0.5).transform_window(cpd_avg = 'mean(cpd)', frame = [-6,0]).encode(
    x = 'date:T',
    y = 'cpd_avg:Q'
)

(rect+base+line).configure_axis(
    grid=False,
    title=None
).configure_view(
    strokeWidth=0
).properties(width=1000)
```
![error1](https://user-images.githubusercontent.com/12681262/85223829-6a43d580-b3e3-11ea-8394-a0e0eaa25895.png)
This shows -500 at y-axis and the shaded region goes below 0. I have to use ```xOffset=5, x2Offset=5, y=0, y2=268``` to push the shaded area up.

However, when I do the same with different data I do not see the negative space at y-axis -
```py
data = pd.DataFrame({'time':pd.date_range(start='1/1/2018', end='1/13/2018'), 'value':[0,0,0,1,2,4,8,16,15,14,13,12,11]})
num_items = 2

base = alt.Chart(data).transform_window(
    rank='rank()',
    sort=[alt.SortField('time', order='descending')]
)

bar = base.mark_bar(opacity=1, width=15).encode(
    x='time:T',
    y='value:Q',
    color = alt.condition(alt.datum.rank<=num_items, alt.value('red'), alt.value('steelblue'))
)

line = base.transform_window(avg = 'mean(value)', frame=[-2,0]).mark_line().encode(
    x='time:T',
    y='avg:Q'
)
start = pd.DataFrame([{'start': '1/9/2018', 'end': data['time'].max()}])
rect = alt.Chart(start).mark_rect(fill='grey', opacity=0.5).encode(
    x='start:T',
    x2='end:T'
)
text = bar.mark_text(align='center', dy=-10).encode(
    text='value:Q'
)

rect+bar+text+line
```
![okay](https://user-images.githubusercontent.com/12681262/85223845-95c6c000-b3e3-11ea-9b35-9aae8aeac4a9.png)

## Diving in deep
If you just plot the individual plots, then you realize that the issue is with the line plot -
```base``` from first plot -
![ok1](https://user-images.githubusercontent.com/12681262/85223872-d6263e00-b3e3-11ea-96ad-80ae9be3a519.png)

```line``` from first plot -
![line](https://user-images.githubusercontent.com/12681262/85223882-e76f4a80-b3e3-11ea-9cc7-85d181d5acae.png)

```line``` from second plot -
![line2](https://user-images.githubusercontent.com/12681262/85223896-fb1ab100-b3e3-11ea-96d2-588fd130d124.png)

Any idea why this is happening, as I checked and there is NO negative values in the data.

**Comment by jakevdp** [comment]
Default axis limits are determined by vega-lite using a heuristic procedure based on the input data, the encoding, and the mark. If the results of the heuristic are not suitable, you can manually specify the axis limits [as outlined in the docs](https://altair-viz.github.io/user_guide/customization.html#adjusting-axis-limits).

If you find a bug or issue in Vega-Lite's heuristic procedure, you can report it in the Vega-Lite project.

**Comment by armsp** [comment]
@jakevdp Sure, I will try the vega-lite team. Right now there is no way to just specify the lower bound of the limit right? We must specify both the lower and the upper bound?
