### ISSUE TITLE
Examples in Density Transforms do not work

### ISSUE THREAD

**Issue by zufanka** [altair-viz/altair#2215]
https://altair-viz.github.io/user_guide/transform/density.html 

![image](https://user-images.githubusercontent.com/2411066/85283264-5654ae00-b48d-11ea-8623-c6a5a48d322d.png)

I tried different browsers as well as the Vega Editor, the graph stays blank

**Comment by johnyrufus** [comment]
@zufanka , to make this work, you need to change all places where 'IMDB_Rating'  is mentioned to 'IMDB Rating'. This is due to a recent column name change in the underlying vega dataset.

**Comment by jakevdp** [comment]
We're working on getting this fixed. See #2213
