### ISSUE TITLE
Issue in concatenation of repeated chart

### ISSUE THREAD

**Issue by johnyrufus** [altair-viz/altair#2216]
when trying to execute the code below, which is based on the suggestion here by Jake, on concatenating repeated charts: https://stackoverflow.com/questions/56484618/repeated-charts , 
the following error occurs:

"
Javascript Error: Duplicate scale or projection name: "child__row_IMDB_Rating_x"
This usually means there's a typo in your chart specification. See the javascript console for the full traceback.
"

```
import altair as alt
from vega_datasets import data

movies = data.movies.url

def make_column(maxbins):
    return alt.Chart(movies).mark_bar().encode(
        alt.X(alt.repeat("row"), type='quantitative',  
              bin=alt.Bin(maxbins=maxbins)),
        alt.Y('count()')
    ).properties(
        width=200,
        height=150
    ).repeat(
        row=['IMDB Rating', 'IMDB Votes'],
    )

make_column(10) | make_column(50)
```

**Comment by jakevdp** [comment]
I don't think Vega-Lite supports concatenation of repeated charts.

**Comment by johnyrufus** [comment]
Thanks Jake for your reply. Was this working before and got recently broken ? one of our programs which was not breaking earlier started breaking now.

**Comment by jakevdp** [comment]
When you say "earlier", what do you mean? Using the same version of Altair, or on a different version of Altair? And if it's on the same version, how are you displaying the charts?

**Comment by johnyrufus** [comment]
It was on a previous version of Altair for sure, Summer/Fall 2019, (sorry not sure exactly what version of Altair was being used, most probably v3.0 or v3.1)

**Comment by jakevdp** [comment]
OK - yeah I believe that Vega-Lite previously supported concat-of-repeat in version 3.X, but does not support it in version 4.X.

**Comment by johnyrufus** [comment]
Thanks for the information. should we go ahead and close this issue.
