### ISSUE TITLE
How to create a legend based on pre-calculated inputs from visualized data?

### ISSUE THREAD

**Issue by Luchkata** [altair-viz/altair#2218]
Please help with creating a legend based on pre-calculated inputs from visualized data?

**Comment by jakevdp** [comment]
Can you give an example of the kind of data you have and what you want to do with it?

**Comment by Luchkata** [comment]
Sure, for example I am plotting a stock's closing price and I would like to calculate the last value of the stock, the mean value of the stock and probably the zscore. And I want to plot those values in the legend on the left corner of the graph, like this:    Zscore: 1.45  Mean: 5.5  LastValue:  45

Thanks appreciate it!

**Comment by jakevdp** [comment]
THe only way I know to do this is to create a layer with a text mark containing the text you want to show.

**Comment by Luchkata** [comment]
Thanks! would you be able to help with a small example?

**Comment by jakevdp** [comment]
Sure, for example:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'x': range(5),
    'y': [1, 3, 2, 5, 4]
})

points = alt.Chart(df).mark_point().encode(x='x', y='y')
text = alt.Chart(df).mark_text(
    align='left',
    baseline='top'
).encode(
  x=alt.value(5),
  y=alt.value(5),
  text=alt.value("My Value: 4.0"),   
)

points + text
```
![visualization (6)](https://user-images.githubusercontent.com/781659/85450320-819ed200-b54d-11ea-9b1d-355901acee63.png)

**Comment by Luchkata** [comment]
Thanks a lot, Jake!
