### ISSUE TITLE
'Chart' object has no attribute 'transform_regression'

### ISSUE THREAD

**Issue by banshanren** [altair-viz/altair#2219]
When I run the example in https://altair-viz.github.io/user_guide/transform/regression.html
![image](https://user-images.githubusercontent.com/7794465/85516284-a0c26000-b630-11ea-9ad9-87d762de07e6.png)
I just got the error as below:
![image](https://user-images.githubusercontent.com/7794465/85516082-6c4ea400-b630-11ea-843d-e4f243e3a3fe.png)

**Comment by jakevdp** [comment]
The regression transform was added in Altair’s version 4 release. I suspect you’re using an older version of the library.

**Comment by banshanren** [comment]
Thank you!
