### ISSUE TITLE
color=alt.Color(sort=[...]) only sorts legend and colors but not the color slice position in stacked bar graphs. 

### ISSUE THREAD

**Issue by agostini01** [altair-viz/altair#2220]
First of all, amazing work! I really like this library!

Now with the issue: "Color slices do not respect the sort order."

I am trying to change the order of slices of a stacked colored bar.

By default "color slice position IN the bars", "color assignment" and "legend order" are all sorted in alphabetical ascending order.
```
# load an example dataset
from vega_datasets import data
cars = data.cars()

# plot the dataset, referencing dataframe column names
import altair as alt
alt.Chart(cars).mark_bar().encode(
  x=alt.X('Miles_per_Gallon', bin=True),
  y='count()',
  color=alt.Color('Origin:N'),
)
```
![Imgur](https://i.imgur.com/gLyLq9Q.png)

When I try to sort with `color=alt.Color(sort=[...])`...

```
# load an example dataset
from vega_datasets import data
cars = data.cars()

# plot the dataset, referencing dataframe column names
import altair as alt
alt.Chart(cars).mark_bar().encode(
  x=alt.X('Miles_per_Gallon', bin=True),
  y='count()',
  color=alt.Color('Origin:N',
                    sort=['Europe', 'USA', 'Japan'], # SORTING
                    ),
)
```
only  "color assignment" and "legend order" respect the sort. Note how USA still comes last in the "color slice position IN the bars":

![Imgur](https://i.imgur.com/smdQnZr.png)

Is it possible to change how the colors in the bar are plotted without having to pre-append numbers and force a particular alphabetical order to the "color slice position IN the bars"?

EDIT (Based on comment below):
Correct! By `color slice position IN the bars` I mean `stack order`

**Comment by jakevdp** [comment]
If I understand correctly, you want to adjust the stack order of the bars, yes? You can do this using the `order` encoding. See https://altair-viz.github.io/gallery/stacked_bar_chart_sorted_segments.html for an example.

**Comment by agostini01** [comment]
Precisely! This is the behavior I want to modify.

Is there a way to define arbitrary orders?

```
# load an example dataset
from vega_datasets import data
cars = data.cars()

# plot the dataset, referencing dataframe column names
import altair as alt
alt.Chart(cars).mark_bar().encode(
  x=alt.X('Miles_per_Gallon', bin=True),
  y='count()',
  color=alt.Color('Origin:N',
                    sort=['Europe', 'USA', 'Japan'], # SORTING
                    ),
  order=alt.Order(
      # Sort the segments of the bars by this field
      'Origin:N',
      sort=['Europe', 'USA', 'Japan'] # Arbitrary instead of 'ascending', 'descending'
    )
)
```

Produces the error:

SchemaValidationError: Invalid specification

```
        altair.vegalite.v4.schema.channels.Order->sort, validating 'enum'

        ['Europe', 'USA', 'Japan'] is not one of ['ascending', 'descending']
```

**Comment by jakevdp** [comment]
The `order` can only be assigned to a field. You can use a transform to specify arbitrary orders; something like this:
```python
order= ['Europe', 'USA', 'Japan']

alt.Chart(cars).transform_calculate(
  order=f"-indexof({order}, datum.Origin)"
).mark_bar().encode(
  x=alt.X('Miles_per_Gallon', bin=True),
  y='count()',
  color=alt.Color('Origin:N', sort=order),
  order="order:Q"
)
```
![visualization (7)](https://user-images.githubusercontent.com/781659/85622767-2f78b200-b61c-11ea-84e7-04e823ed424e.png)

**Comment by agostini01** [comment]
This works for me! Thank you very much.

I will close the issue.

**Comment by joelostblom** [comment]
For reference, [also see this for sorting bar segments according to the color order](https://stackoverflow.com/questions/66347857/sort-a-normalized-stacked-bar-chart-with-altair/66355902#66355902).
