### ISSUE TITLE
How does color scale merge with 2 graphs?

### ISSUE THREAD

**Issue by pierreaubert** [altair-viz/altair#2222]
```python
import pandas as pd
import altair as alt

df1 = pd.DataFrame({'x': [1,2,3,4], 'y': [0,1,4,9], 'c': [0,1,0,1]})
df2 = pd.DataFrame({'x': [1,2,3,4], 'y': [9,1,4,0], 'c': [3,2,3,2]})
```

This is working as expected, i get 4 colors one per 'c':
```python
c1 = alt.Chart(df1).mark_line().encode(x='x:Q', y='y:Q',
    color=alt.Color('c:N'))
c2 = alt.Chart(df2).mark_line().encode(x='x:Q', y='y:Q',
    color=alt.Color('c:N'))
alt.layer(c2, c1) 
```

[![visualization (3)](https://user-images.githubusercontent.com/1709343/85867262-eb76e000-b7c8-11ea-98a9-787abf1d4276.png)
](url)

I expected to get 4 different colors not 2. It looks like the scale from the first graph is overriding the second one.
```python
g1 = alt.Chart(df1).mark_line().encode(x='x:Q', y='y:Q',
    color=alt.Color('c:N', 
                    scale=alt.Scale(range=['red', 'green'], domain=[0,1])))
g2 = alt.Chart(df2).mark_line().encode(x='x:Q', y='y:Q',
    color=alt.Color('c:N', 
                    scale=alt.Scale(range=['blue', 'black'], domain=[2,3])))
alt.layer(g2, g1) 
```

![visualization (4)](https://user-images.githubusercontent.com/1709343/85867312-00ec0a00-b7c9-11ea-8abe-750dcbbe7e71.png)

Another question: why setting the legend on the first graph applies to both graphs. I guess that's the same as the previous question. How can I prevent this?
```python
z1 = alt.Chart(df1).mark_line().encode(x='x:Q', y='y:Q',
    color=alt.Color('c:N', 
                    scale=alt.Scale(range=['red', 'green'], domain=[0,1])))
z2 = alt.Chart(df2).mark_line().encode(x='x:Q', y='y:Q',
    color=alt.Color('c:N'))
alt.layer(z2, z1) 
```

![visualization (5)](https://user-images.githubusercontent.com/1709343/85867320-077a8180-b7c9-11ea-9f66-1741b17c1af2.png)

**Comment by pierreaubert** [comment]
Answering myself https://altair-viz.github.io/user_guide/scale_resolve.html

**Comment by joelostblom** [comment]
@pierreaubert I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Comment by pierreaubert** [comment]
Yes this has been resolved, thanks for reaching out.
