### ISSUE TITLE
Altair and Datatables

### ISSUE THREAD

**Issue by tzipperle** [altair-viz/altair#2223]
Hi,
do you know is there a option to combine Altair and [Datatables](https://datatables.net/)?

**Comment by Rik-de-Kort** [comment]
Datatables is a JQuery plug-in, and Altair is a Python package, so I feel like what you're asking is rather ill defined. Are you perhaps looking to use [vega-lite](https://vega.github.io/vega-lite/) (on which Altair is based) in your website?

**Comment by joelostblom** [comment]
@tzipperle I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
