### ISSUE TITLE
Bouncy / Noisy / Jittery / Ragged graph depending on rounding

### ISSUE THREAD

**Issue by dsandber** [altair-viz/altair#2224]
I'm making a simple graph like this:

chart = alt.Chart(source).mark_line().encode(x='x', y='data')

The data displays like this, which is surprising because the data itself is quite smooth:

![Screenshot 2020-06-30 at 19 53 05](https://user-images.githubusercontent.com/5387753/86159937-5e56c280-bb0b-11ea-8a6c-bedd9d74b5ab.png)

If I round it to the 3rd digit (round(x, 3)) then the graph appears smooth.  If I round it to the fourth digit, then it appear jagged again.

The "noisiness" shown on the graph is a lot more than what could be caused by a varying fourth digit.  Any ideas?

**Comment by joelostblom** [comment]
Could you provide a self-contained example that we can run to reproduce this behavior and help you figure out what is wrong? Or if this issue is not affecting you anymore, would you be able to close it?

**Comment by dsandber** [comment]
Will close for now, will re-open if/when I make a self-contained example.

**Comment by jakevdp** [comment]
Rounding digits in x may affect the order of the points. Remember that in Altair, the lines by default are connected in the order of the sorted x-value, not in the order of the rows in the data.

**Comment by dsandber** [comment]
[jagged.zip](https://github.com/altair-viz/altair/files/6049799/jagged.zip)

Ok, I got a test-case.  If the y-axis values are rounded at the third decimal point:

`y_axis = [round(y, 3) for y in y_axis]`

The graph looks jagged (see picture below).  This happens even though the maximum difference between y-axis points is 0.001, and the x axis is non-decreasing (so sorting shouldn't matter). 

![image](https://user-images.githubusercontent.com/5387753/109304198-322b4700-783c-11eb-88d9-08c9f0166486.png)

If the rounding is two digits, the graph looks jagged as one would expect:

![image](https://user-images.githubusercontent.com/5387753/109304381-7b7b9680-783c-11eb-9420-64db40dcbc34.png)

If the rounding is 4 or above, the graph is smooth.

**Comment by jakevdp** [comment]
Looking at the data, I see that  your y values are jittery, which causes the graph to be jittery. The jitter is smaller than 0.01, so when you round to the nearest 0.01, the jitter goes away.

The situation is essentially this: rounding makes the jitter go away:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'x': range(5),
    'y': [0.02, 0.01, 0.013, 0.00, 0.002],
})

df2 = df.copy()
df2['y'] = df2['y'].round(2)

alt.hconcat(
  alt.Chart(df).mark_line().encode(x='x', y='y'),
  alt.Chart(df2).mark_line().encode(x='x', y='y')
)
```
![visualization - 2021-02-26T053014 668](https://user-images.githubusercontent.com/781659/109306212-b60d1100-77f3-11eb-9d67-4af42e6f1aa6.png)

**Comment by dsandber** [comment]
You're right, thanks for the help.  I'm not sure the original graph I posted stemmed from the same "issue", but I'll close until I can make a more convincing case for a real problem.  Thanks again!
