### ISSUE TITLE
Avoid selenium TimeOutException when saving charts

### ISSUE THREAD

**Issue by TomBugnon** [altair-viz/altair#2226]
Hi,
Is there any way to get around the TimeOutException when saving large plots using the firefox webdriver?
Thanks, Tom

**Comment by jakevdp** [comment]
I've never come across this, so I'm not sure. You might look into what configuration options are available in selenium

**Comment by TomBugnon** [comment]
It seems like the altair_saver sets a default driver timeout at 20s:

https://github.com/altair-viz/altair_saver/blob/31febb5faf7c3d6d27c2f5fe4045635099143042/altair_saver/savers/_selenium.py#L170

https://github.com/altair-viz/altair_saver/blob/31febb5faf7c3d6d27c2f5fe4045635099143042/altair_saver/savers/_selenium.py#L143

Maybe setting this as an optional argument to the chart.save methods would do the trick?

**Comment by jakevdp** [comment]
Yes, that would work. You can also instantiate your own driver and pass that to the save function, if you need to configure something that the altair_saver interface doesn't expose.

**Comment by TomBugnon** [comment]
actually, digging into the code it seems like ``altair.Chart.save`` already accepts an undocumented `driver_timeout` kwarg (in seconds) that is eventually passed to ``driver.set_page_load_timeout``. Thanks for the response Jake
