### ISSUE TITLE
Using a chart aggregation appears to display different data than that calculated using Pandas

### ISSUE THREAD

**Issue by devChad** [altair-viz/altair#2228]
Hi, I'm a day-old user of Altair so this could very much be user error. I'm using Altair '4.1.0'

I'm following the Altair video tutorial and notebooks from PyCon 2018 (available from https://youtu.be/ms29ZPUKxbU?t=6016 and https://github.com/altair-viz/altair-tutorial respectively). 

Notebook '03-Binning-and-aggregation' includes the following code that exemplifies Time Binning and aggregation. This code plots hourly average temperature as a function of month (allowing us to compare an average day in January vs July, for example).

```python
import altair as alt
from vega_datasets import data

temps = data.seattle_temps()
alt.data_transformers.enable('data_server')

alt.Chart(temps).mark_rect().encode(
    x=alt.X('date:O', timeUnit='hours'),
    y=alt.Y('date:O', timeUnit='month'),
    color='mean(temp):Q'
) 
```

In the tutorial video, the following output is obtained (screenshot from video):

![expected_output](https://user-images.githubusercontent.com/23214173/86534367-93e41d00-bf0a-11ea-92c0-83a8b050fdd4.png)

However, the following is the output I get:

![visualization-2](https://user-images.githubusercontent.com/23214173/86534391-b5dd9f80-bf0a-11ea-8e99-7b7eb6904215.png)

I have confirmed the expected output by explicitly calculating the aggregation using Pandas:

```python
import pandas as pd

transformed_temps_df = temps.groupby([pd.Grouper(freq='M', key='date'),
                                      pd.Grouper(freq='H', key='date')])['temp'].mean().to_frame()
transformed_temps_df.index.names = ['date', 'time']
transformed_temps_df.reset_index(inplace=True)

transformed_temps_df['date'] = transformed_temps_df['date'].dt.date
transformed_temps_df['time'] = transformed_temps_df['time'].dt.time

alt.Chart(transformed_temps_df).mark_rect().encode(
    x='time:O',
    y='date:O',
    color='temp:Q'
)

```
which yields
![visualization-3](https://user-images.githubusercontent.com/23214173/86534421-ef160f80-bf0a-11ea-88f1-18e3ea638191.png)

As a side issue, if I try to plot time and date as temporal type I get axes but no data.

```python
alt.Chart(transformed_temps_df).mark_rect().encode(
    x='time:T',
    y='date:T',
    color='temp:Q'
)
``` 

Where am I going wrong?
Cheers

**Comment by jakevdp** [comment]
The reason the colors are different is because Vega-Lite version 4.0 (released December 2019) changed the default color schemes and heatmap styles.

The reason the aggregates are different might be a time-zone thing, but I'm not sure.

**Comment by devChad** [comment]
Thanks for your input Jake.

Interesting - I don't know how Google Colaboratory timezones are set, but if I use a Colab notebook I also get the shifted output.

```python
import altair as alt
from vega_datasets import data

temps = data.seattle_temps()
alt.data_transformers.disable_max_rows()

alt.Chart(temps).mark_rect().encode(
    x=alt.X('date:O', timeUnit='hours'),
    y=alt.Y('date:O', timeUnit='month'),
    color='mean(temp):Q'
) 
```
![image](https://user-images.githubusercontent.com/23214173/86554428-2672d380-bf80-11ea-9359-86235994ee20.png)

**Comment by devChad** [comment]
I have done some further testing, and it appears that this issue appears when using Safari (I'm using version 13.1.1). When using Chrome (version 83.0.4103.116), the correct output is produced. In the image below, Chrome is on the left and Safari on the right.

![image](https://user-images.githubusercontent.com/23214173/86559759-5d041a80-bf8f-11ea-9008-a55ffa436b64.png)

I wonder why different browsers are providing rendering different results. Would this have something to do with Vega/Vega-Lite?

**Comment by jakevdp** [comment]
If it's a browser-dependent difference, it's likely due to differences in how the browsers' javascript implementations parse date strings.

**Comment by jakevdp** [comment]
Do you see the same issue when directly viewing [this chart](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygK4CcA28QAspQA4Gc4B6IgNwFMBzCAOkoEspNEAjG+gezKogFpIY+clHxEBEIkOhRU5XgHdy0TOWS9MHFKgCevAHYdkAWwip8NAMb5SIAL4AaECeQBrDMnIWoIR+T0WOMHo9SnhQANRDMJAobVxyDABHRAg9KEZoegofEAhKSg9qKAS4JyU9HIAzenJUMAxio3jkaBQEhxAAD2jY+IxDIL1TKpq6jAEEx3SjcgBVPUYMDRR8O0dtHriSkAHg4cdq2vrSiZzpuYXvUqMONMw7W1sgA) in the vega editor?

**Comment by jakevdp** [comment]
I can confirm I see a timezone-dependent difference in date parsing behavior between chrome and safari in the above link. It looks like this is a known issue: https://stackoverflow.com/questions/6427204/date-parsing-in-javascript-is-different-between-safari-and-chrome

**Comment by devChad** [comment]
Thanks Jake. I can confirm I see the same issue when viewing the chart you linked in the Vega editor. 

![image](https://user-images.githubusercontent.com/23214173/86795277-f91d4700-c09f-11ea-869e-9b6598d80476.png)

It also looks like this difference in browser behaviour is already noted in the Altair documentation here: https://altair-viz.github.io/user_guide/times_and_dates.html

As such, I think this issue can be closed. Thanks very much for your input Jake - much appreciated.
