### ISSUE TITLE
Displaying the real value instead of the shorthand on the axis

### ISSUE THREAD

**Issue by rubik** [altair-viz/altair#223]
In many plots I see that the values from my dataset are replaced with [metric prefixes](https://en.wikipedia.org/wiki/Metric_prefix) from the international system. For example, `0.123` is displayed on the axis as `123m`.

This helps the readability, but in some cases I'd like to have the original value displayed. I searched for terms like 'prefix', 'postfix', 'unit', 'measure', 'shorthand' in the API reference but I couldn't find anything relevant. How is it done?

**Comment by jakevdp** [comment]
Great question – this default is a choice made in the Vega-Lite library, and I believe it's being reconsidered by the Vega team. The default can be changed by using the ``format`` atttribute of ``Axis``. For more information, see #191

**Comment by jakevdp** [comment]
I'd add something to the documentation, but it's not clear at the moment what the default behavior will be as of the next release.

**Comment by rubik** [comment]
Oh thanks, I hadn't found that issue. For now `format` will do, thanks a lot.

**Comment by jakevdp** [comment]
I'm going to close as this is similar to #210
