### ISSUE TITLE
json data transformer issue at altair >= 4

### ISSUE THREAD

**Issue by tjbergst** [altair-viz/altair#2230]
When using the json data transformer (`alt.data_transformers.enable('json')`) the charts always come back blank, the browser console shows the following error:
> WARN Loading failed altair-data-XXXXXX.json SyntaxError: Unexpected token < in JSON at position 0

## system info

- windows 10 
- conda 4.8.3
- python 3.7.6
- altair 4.1.0 py_1 conda-forge | altair 4.1.0 py_0 conda-forge | altair 4.0.1 py_0 conda-forge

## sample code

```python
import pandas as pd
import altair as alt
alt.data_transformers.enable('json')

tdf = pd.DataFrame({'one': range(10), 'two': range(0, 20, 2)})
alt.Chart(tdf).mark_circle().encode(x='one:Q', y='two:Q')
```

## notes
This charts render fine with any altair 3.X release. 
I also tested the above snippet in a RHEL7 docker container (installing with `pip`) and experienced the same issue with 4.X. 
The json file itself looks fine, I am able to `pd.read_json` on it and load the dataframe.

**Comment by jakevdp** [comment]
This looks like the same issue reported in #1867

Short answer: JSON data transformer is generally unreliable across platforms and frontends; you should use altair_data_server instead.

**Comment by tjbergst** [comment]
Understood, thanks
