### ISSUE TITLE
alt.renderers.enable("mimebundle") returns NoSuchEntryPoint

### ISSUE THREAD

**Issue by piccolbo** [altair-viz/altair#2234]
Hi, 
since altair 4.0 I've been trying to restore inline charts in Atom/hydrogen, The docs (https://altair-viz.github.io/user_guide/display_frontends.html?highlight=hydrogen) read:
   
> The Hydrogen project, which is built on nteract and renders Altair charts via the **mimebundle** renderer.

But with altair 4.1.0 trying to enable it results in the error in the subject. altair.renderers shows this list

```"altair_viewer",
#         "colab",
#         "default",
#         "html",
#         "json",
#         "jupyterlab",
#         "kaggle",
#         "mimetype",
#         "nteract",
#         "png",
#         "svg",
#         "zeppelin",
```

Tried a few to no avail. Using the  nteract renderer results in this error `SyntaxError: Unexpected token o in JSON at position 1`
The chart displays just fine in the altair_viewer. Thanks

**Comment by jakevdp** [comment]
There has never been a tenderer named “mimebundle”. Perhaps you’re looking for “mimetype”?

**Comment by piccolbo** [comment]
The documentation mentions `mimebundle` at least three times. I included a quote above. If I switch to `mimetype` I get the following error: `SyntaxError: Unexpected token o in JSON at position 1`

**Comment by piccolbo** [comment]
Repro:
```
from vega_datasets import data
import altair as alt

alt.renderers.enable("mimetype")

ch = alt.Chart(data=data.iris()).encode(x="sepalLength", y="petalLength").mark_point()
# ch.to_json() checked in online editor; ch.show() displays in browser
ch
#output in atom/hydrogen: SyntaxError: Unexpected token o in JSON at position 1
```

**Comment by jakevdp** [comment]
Ah, I see. It looks like hydrogen is expecting a JSON string, when the mimebundle contains the actual object. I would report this issue to the Hydrogen team.

**Comment by piccolbo** [comment]
Actually, I had reported it about 6 months before reporting it here https://github.com/nteract/hydrogen/issues/1847 Still open. Just FYI, not sure what you could do about it.

**Comment by piccolbo** [comment]
Problem still unchanged for me in 4.2.0.dev0 installed from master moments ago. Same repro.
