### ISSUE TITLE
Radio button text not visible on dark JupyterLab theme

### ISSUE THREAD

**Issue by AAnzel** [altair-viz/altair#2235]
The title says it all. This happens even though I explicitly turned on Altair's dark theme with the command `altair.themes.enable ('dark')`. Radio buttons are added to a plot with the command `altair.binding_radio (...)`.

**Comment by jakevdp** [comment]
This color is controlled by CSS, which is not possible to set via an Altair theme (but would be possible to set via the JupyterLab theme). See https://stackoverflow.com/questions/62843594/altair-change-color-of-label-in-binding-radio for an example of changing the color.

**Comment by AAnzel** [comment]
Thank you for the clarification! I will close the issue.
