### ISSUE TITLE
Compress JSON data in notebooks to decrease size

### ISSUE THREAD

**Issue by ELind77** [altair-viz/altair#2236]
Hi all,

Would it be possible to gzip or otherwise compress the JSON data to allow storing larger data sets directly in notebooks?

I do a fair amount of exploratory analysis and plotting, and I'd love to switch to Altair full time and replace matplotlib entirely but my datasets are usually too large to store directly in my notebook--particularly early on when I'm just getting to know the data--and it can be very inconvenient to store the data externally as I'm often working in a remote environment where it's not always straightforward to load the cached data across multiple sessions (e.g. a docker container on a remote host).  Being able to store larger plots/data sets directly in notebooks would let me make better use of Altair.

-- Eric

**Comment by jakevdp** [comment]
No, I don’t know of any ways to compress data. You could use a png or shh  renderer to only store the rendered charts in the notebook, but then you lose interactivity.

**Comment by joelostblom** [comment]
@ELind77 I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Comment by fbxyz** [comment]
Hi,

Exporting the json with Altair then import + json.dump significantly reduces the size of the json.

I did a test with a (big) chart: 

- Include altchart.to_json() in an HTML file: 9MB
- with the following function minijson() : 1.2MB 

```
def minijson(altchart):
    altchart.save("./json/temp.json")
    with open("./json/temp.json") as fp:
        j = json.load(fp)
        return json.dumps(j,separators=(',', ': '))
   
new_json = minijson(my_altair_chart)

```
