### ISSUE TITLE
Adjust tooltip label limit

### ISSUE THREAD

**Issue by Kylecrif** [altair-viz/altair#2240]
I am wondering how I can set the `labelLimit=0` for tooltip labels. I know this is possible for legends and axis titles through `.configure_legend(labelLimit=0)` and `.configure_axis(labelLimit=0)` respectively, but is there a way to do this same thing for tooltip labels?

Example plot:

<img width="551" alt="Screen Shot 2020-07-15 at 10 23 02 AM" src="https://user-images.githubusercontent.com/41021202/87564641-42642c80-c686-11ea-984a-6f97e12ed1f7.png">

**Comment by joelostblom** [comment]
I believe there is currently no option to achieve this in VegaLite and there is nothing that can be done on the Altair side to support this so I'm closing this. I suggest opening an issue in the VL repo with a minimal reproducible example and the suggestion to add this option.
