### ISSUE TITLE
No Issue, just wanted to say Thanks :)

### ISSUE THREAD

**Issue by FollowTheProcess** [altair-viz/altair#2243]
Altair really is amazing, it's the first time I've used a visualisation library in Python that I've truly been comfortable with and not had to hack around to find what I want to do. The API is super intuitive after a while I found I could correctly guess what the correct input is for all but the most complicated graphs.

On top of that the plots themselves look stunning!

I couldn't keep using it without saying thank you somehow, sorry if this clogs up the Issue list!

Thanks to all the dev team! This really is a fantastic package.

**Comment by jakevdp** [comment]
Awesome! Glad you're enjoying Altair!
