### ISSUE TITLE
zooming on multiline chart with mark_rule does not work on axis of rule

### ISSUE THREAD

**Issue by jandot** [altair-viz/altair#2244]
Hi,

I have multi-line plots with tooltip working based on https://altair-viz.github.io/gallery/multiline_tooltip.html, but including a horizontal rule that represents a threshold (see the picture below).

![Screenshot 2020-07-20 at 13 40 26](https://user-images.githubusercontent.com/10043/87934024-95771e80-ca8e-11ea-91dc-b4f592736e18.png)

```python
threshold = alt.Chart(df).mark_rule(color='red').encode(
    y='threshold:Q'
)
...
alt.layer(
    threshold, plot_itself, selectors, points, rules, text
).interactive()
```

Trying to make the plot interactive for zoom/pan, but it seems that because of the horizontal rule, it is no longer possible to zoom in/out of the plot and pan along the x-axis, but only along the y-axis. Is there a way to bypass this issue?

Thank you!

**Comment by jandot** [comment]
It seems that this can be solved by changing the order of the layers: putting `threshold` _after_ `plot_itself` does allow zooming on the x-axis. But then again, it puts the threshold line on top of the plot instead of behind it.

**Comment by jakevdp** [comment]
Can you include a full code snippet that reproduces the issue? It’s hard to guess what the rest of your code is to reproduce the problem.

**Comment by joelostblom** [comment]
@jandot I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to add a comment with a reproducible example so that we can try to resolve the issue or close it if it is no longer affecting you?

**Comment by joelostblom** [comment]
Closing for now, feel free to reopen and provide the requested details to reproduce this issue.
