### ISSUE TITLE
altair pads x axis, even when domain is set

### ISSUE THREAD

**Issue by jooh** [altair-viz/altair#2245]
I have a line chart where I want the x limits to end at 1.5, the max of the data. Altair 4.1.0 (conda-forge) adds a bit of padding at the end of the x axis instead, even after setting the domain of the X axis directly:

``` python
import numpy as np
import pandas as pd
import altair as alt
x_max = 1.5
alt.Chart(
    pd.DataFrame({"x": np.linspace(0, x_max, 100), "y": np.ones(100)}),
    width=200,
    height=200,
).mark_line().encode(x=alt.X("x", scale=alt.Scale(domain=[0, x_max])), y="y")
```
![example](https://user-images.githubusercontent.com/1559987/87942164-1684e480-ca94-11ea-8c5c-ec92bb983f6a.png)

I found a workaround by disabling nice and setting the x ticks manually:

``` python
alt.Chart(
    pd.DataFrame({"x": np.linspace(0, x_max, 100), "y": np.ones(100)}),
    width=200,
    height=200,
).mark_line().encode(
    x=alt.X(
        "x",
        scale=alt.Scale(domain=[0, x_max], nice=False),
        axis=alt.Axis(values=[0, 0.5, 1, x_max]),
    ),
    y="y",
)
```
![example2](https://user-images.githubusercontent.com/1559987/87942988-500a1f80-ca95-11ea-9065-854ce864e858.png)
 
Is there a better way to control this behaviour? I would rather not hand code the X ticks for every chart. I just don't want the X limits to extend past the last tick, when the data doesn't.

I did some more testing, and the problem appears to be that the x limits get rounded up to an even value. There is no extra padding at the end of the axis for `x_max=1.4` or `x_max=1.6`.

**Comment by jakevdp** [comment]
If you set `nice=False` in the scale, the renderer will use the domain directly and not adjust the axis limits:
```python
import numpy as np
import pandas as pd
import altair as alt
x_max = 1.5
alt.Chart(
    pd.DataFrame({"x": np.linspace(0, x_max, 100), "y": np.ones(100)}),
    width=200,
    height=200,
).mark_line().encode(
    x=alt.X("x", scale=alt.Scale(domain=[0, x_max], nice=False)),
    y="y"
)
```
![visualization (14)](https://user-images.githubusercontent.com/781659/87953352-c9871b00-ca5f-11ea-8354-e08657fd9b28.png)

**Comment by jooh** [comment]
Thanks. I was confused about what nice is intended to do - it's for modifying the domain, and that's exactly what I don't want in this case.

So I think my issue is really with how the Axis ticks are placed by default when nice is off. I much prefer to have the final tick at the end of the domain whenever that number is round-ish, even if that means greater than optimal tick spacing. But I gather this comes from vega-lite so I think you can close this issue.

**Comment by jakevdp** [comment]
I think you’re correct. But think of it this way: Vega-Lite has a heuristic for determining optimal domains and tick spacing for the uncountable infinite number of possible inputs. The fact that the result of the heuristic doesn’t match your aesthetic preference in some cases is probably unavoidable. But for those cases, it gives you hooks where you can fine-tune the behavior.
