### ISSUE TITLE
add regression line to dynamic axis data selection

### ISSUE THREAD

**Issue by dcaohuu18** [altair-viz/altair#2246]
Hello, is there any quick way to add a regression line to this? I tried ```transfrom_regression()``` but it shows me nothing. Thank you.

```python
import altair as alt
from vega_datasets import data


columns = ['Acceleration', 'Cylinders', 'Displacement', 'Horsepower']

select_box = alt.binding_select(options=columns, name='column')
sel = alt.selection_single(fields=['column'], bind=select_box, init={'column': 'Acceleration'})

alt.Chart(data.cars()).transform_fold(
    columns,
    as_=['column', 'value']
).transform_filter(
    sel  
).mark_point().encode(
    x='Miles_per_Gallon:Q',
    y='value:Q',
    color='Origin:N'
).add_selection(
    sel
)
```
![visualization (37)](https://user-images.githubusercontent.com/781659/61567519-b993c000-aa34-11e9-950e-384a1ce40fb3.png)

You can see the live, interactive version [here](https://vega.github.io/editor/#/url/vega-lite/N4KABGBEDGD2B2AzAlgc0gLjMSA3ZApgO6baRHIAmALgBakAsADEwDRS0Fq3WkDMLAL7tIAWwCGAJwDWpHNViwANtWQAHUvACuSpYOHgolcdXFzIWyUtKQe1NQGcMAeme4CqcQDpUyOloAjL2RYNw9xAFpjUwcCagdnaPFnaCkHLwArBwRIAwgxKVksSDVYZHheVkNIAng4SnL0LFAIfLglWElzagBPNQIbeFhRcvFrERQCJUobAHlJNHLcqtaoAA9uvoHigEctcQq-E2R3SAnCaZsAWWQlAgcAfX7JB4BxMY74ZcN8ns3+mx7A6qUyqU7nKYzYq4MZaAaCQx5KCxO7QVQ5Zo-ZFTAhozosABscix+V6AOKDkadzOJKgk2mDlIAG0YMotKIvgBdFarKABcpQ7C0-LlNRaXgUnFomm81qQWBqdHwRlYFkAQWg0BxkmOOREAGEekoBQRJIyRAARZAONRKcRa0S1SpQAASnVipSIpsg3OFUHg4kdNna7K+tKRq0g5T85hDHJsGq1dx1StyWIRECRkGoOuViE6omZWJavMg+cuqsgie1uq+BqNJrNZygVptdodTubkDdZoInu9vtlkHEKrALLjdagMKUcJ96Z5EBwKBU3uakBRuNTktRCkkhNyGbAg6gABIHNBOBIbHZHC4wp4fH5aIFgqFz5fku5PBFjdQCG4+C8QCmEybIw0EIA/view).

_Originally posted by @jakevdp in https://github.com/altair-viz/altair/issues/1617#issuecomment-513390674_

**Comment by jakevdp** [comment]
You can do this with a layer. For example:
```python
import altair as alt
from vega_datasets import data

columns = ['Acceleration', 'Cylinders', 'Displacement', 'Horsepower']

select_box = alt.binding_select(options=columns, name='column')
sel = alt.selection_single(fields=['column'], bind=select_box, init={'column': 'Acceleration'})

chart = alt.Chart(data.cars()).transform_fold(
    columns,
    as_=['column', 'value']
).transform_filter(
    sel  
).mark_point().encode(
    x='Miles_per_Gallon:Q',
    y='value:Q',
    color='Origin:N'
)

alt.layer(
  chart.add_selection(sel),
  chart.transform_regression('Miles_per_Gallon', 'value').mark_line()
)
```

**Comment by dcaohuu18** [comment]
Thank you. I have to say that if I love Altair 1, I must love your helpfulness 10. Plus, Altair has good documentation and simple syntax, which makes me choose it over Bokeh and other libraries when it comes to interactive visualization in the end.
