### ISSUE TITLE
alt.Axis() and the labelOverlap argument

### ISSUE THREAD

**Issue by hathawayj** [altair-viz/altair#2248]
I am trying to recreate the below ggplot2 graphic. However, I can't get the ticks to show all the specified dates. I think the `labelsOverlap` argument is supposed to do this, but it doesn't seem to work.

![](https://d33wubrfki0l68.cloudfront.net/ebee3bb8c5ca82e85cceb216460f57671d372ece/2d716/communicate-plots_files/figure-html/unnamed-chunk-16-1.png)

```python
import altair as alt
import pandas as pd
import numpy as np
alt.data_transformers.enable('json')
```

## load the data

```python
presidential = pd.read_csv("https://github.com/byuidatascience/data4python4ds/raw/master/data-raw/presidential/presidential.csv")

presidential = presidential.assign(
    start = lambda x: pd.to_datetime(x.start),
    end = lambda x: pd.to_datetime(x.end),
    id = lambda x: 33 + x.index
)

presidential_melt = presidential.melt(['name', 'party', 'id'], var_name = 'start_end', value_name = 'date')
```

## The Altair code

```python
lines = (alt.Chart(presidential_melt).
    encode(
        alt.X('date', axis = alt.Axis(labelOverlap=False)), 
        alt.Y('id', scale = alt.Scale(zero = False)), 
        detail = 'id').
    mark_line())

points = (alt.Chart(presidential).
    encode(
        alt.X('start', 
            axis = alt.Axis(
                values = presidential.start.to_list(),
                format = "\\'%y",
                labelOverlap = False),
                title = None),
        alt.Y('id', scale = alt.Scale(zero = False)),
    ).
    mark_circle())

lines + points
```

**Comment by hathawayj** [comment]
I noticed that this issue was skipped.  Did I need to provide more detail?

**Comment by jakevdp** [comment]
There is a `tickCount` property that sets the maximum number of ticks based on the width of the chart. If you set it to zero, it will disable this behavior:
```python
lines = (alt.Chart(presidential_melt).
    encode(
        alt.X('date', axis = alt.Axis(labelOverlap=False)), 
        alt.Y('id', scale = alt.Scale(zero = False)), 
        detail = 'id').
    mark_line())

points = (alt.Chart(presidential).
    encode(
        alt.X('start', 
            axis = alt.Axis(
                values = presidential.start.to_list(),
                format = "\\'%y",
                tickCount=0,
                labelOverlap = False),
                title = None),
        alt.Y('id', scale = alt.Scale(zero = False)),
    ).
    mark_circle())

lines + points
```
![visualization (21)](https://user-images.githubusercontent.com/781659/88422287-dd53b980-cd9e-11ea-98de-e3d50ce125a1.png)

**Comment by hathawayj** [comment]
Awesome.  Thanks!  Your documentation is great, but these small things are sometimes harder for me to find.  I appreciate your quick response.

**Comment by joelostblom** [comment]
@hathawayj I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

**Comment by hathawayj** [comment]
It was resolved.  Thanks.
