### ISSUE TITLE
Horizontal density plot

### ISSUE THREAD

**Issue by zwanner72** [altair-viz/altair#2249]
Is it possible to generate a horizontal kernel density plot to be used in facetted scatter plot similar to below (where the histograms are replaced by the density plots) ? I was able to create the vertical density plot but not the horizontal one. 

![image](https://user-images.githubusercontent.com/68701241/88305310-54be1600-ccd7-11ea-9bc3-2107d3455a25.png)

**Comment by jakevdp** [comment]
Sure, for example:
```python
import altair as alt
from vega_datasets import data

source = data.cars.url

base = alt.Chart(source).encode(
    x='Miles_per_Gallon:Q',
    y='Acceleration:Q',
    color='Origin:N'
)

points = base.mark_point()

density_x = base.transform_density(
    density='Miles_per_Gallon',
    groupby=['Origin'],
    steps=200,
    extent=[0, 50],
    as_=['Miles_per_Gallon', 'density']
).mark_area(orient='vertical', opacity=0.5).encode(
    y='density:Q',
).properties(
    height=100
)

density_y = base.transform_density(
    density='Acceleration',
    groupby=['Origin'],
    steps=200,
    extent=[0, 26],
    as_=['Acceleration', 'density']
).mark_area(orient='horizontal', opacity=0.5).encode(
    x='density:Q',
).properties(
    width=100
)

density_x & (points | density_y)
```
![visualization (20)](https://user-images.githubusercontent.com/781659/88316515-d2c8ef80-cccc-11ea-85ef-109ee4fb5f57.png)

**Comment by joelostblom** [comment]
@zwanner72 I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
