### ISSUE TITLE
Need help with Y x Z grid of charts showing different set of data based

### ISSUE THREAD

**Issue by vbeer008** [altair-viz/altair#2250]
[PandasDFData.txt](https://github.com/altair-viz/altair/files/4977182/PandasDFData.txt)
![visualization](https://user-images.githubusercontent.com/54382484/88472800-15ebc280-cf5a-11ea-8abd-ae990fde4729.png)

Hi, I tried to build Y x Z grid charts based on my data, but not able to find a dynamic way to plot the chart. Then, I need to create multiple charts and join them together with alt.vconcat method.  Attached the sample data and charts I have done with the code below. Would you please help and advise a better way to do it dynamically, so that I don't need to hard coded the fields value.

--- Here is my current code to plot the chart.
```
pointer = alt.selection_single(encodings=['x'], fields=['overall_perc'])

SingleBlockRead_chart=alt.Chart(eventHistogramDF_filter, title="Event Name Wait Peformance Category in (Ms) %").mark_line().encode(
    x=alt.X('time:T', axis = alt.Axis(title='', labelAngle=-45, format=("%d/%m/%Y-%H%M"))),
    y=alt.Y("overall_perc:Q", title="% Wait Time in (MS) For SingleBlockRead",sort=alt.SortField('waittimeinms', order='ascending')),
    color=alt.condition(pointer,alt.Color('waittimeinms:N',title="Wait Time",scale=alt.Scale(scheme='category20')),alt.value('lightgray'),sort=alt.SortField(field="waittimeinms",order='ascending')),
    column=alt.Column('instance_number:N', title="Instance Number"),
    tooltip=[alt.Tooltip('time:T', format='%d/%m/%Y-%H%M', title="Date and Time"),alt.Tooltip('instance_number:N', title="Instance Number"),
             alt.Tooltip('waittimeinms:N', title = "WaitTimeIn(Ms)"), alt.Tooltip('wait_count:N', title="NoOfWaitCount"),alt.Tooltip('overall_perc:Q', title="OverAllPercentage(%)")] 
    ).transform_filter(alt.FieldEqualPredicate(field='event_name',equal='dbfilesequentialread')
    ).properties(selection=pointer,width=250,height=250).resolve_scale(x='independent',y='independent',color='independent')#.interactive()

LogFileSeqRead_chart=alt.Chart(eventHistogramDF_filter, title="Event Name Wait Peformance Category in (Ms) %").mark_line().encode(
    x=alt.X('time:T', axis = alt.Axis(title='', labelAngle=-45, format=("%d/%m/%Y-%H%M"))),
    y=alt.Y("overall_perc:Q", title="% Wait Time in (MS) For LogFile",sort=alt.SortField('waittimeinms', order='ascending')),
    color=alt.condition(pointer,alt.Color('waittimeinms:N',title="Wait Time",scale=alt.Scale(scheme='category20')),alt.value('lightgray'),sort=alt.SortField(field="waittimeinms",order='ascending')),
    column=alt.Column('instance_number:N', title="Instance Number"),
    tooltip=[alt.Tooltip('time:T', format='%d/%m/%Y-%H%M', title="Date and Time"),alt.Tooltip('instance_number:N', title="Instance Number"),
             alt.Tooltip('waittimeinms:N', title = "WaitTimeIn(Ms)"), alt.Tooltip('wait_count:N', title="NoOfWaitCount"),alt.Tooltip('overall_perc:Q', title="OverAllPercentage(%)")] 
    ).transform_filter(alt.FieldEqualPredicate(field='event_name',equal='logfilesequentialread')
    ).properties(selection=pointer,width=250,height=250).resolve_scale(x='independent',y='independent',color='independent') 
 
ControlFileSeqRead_chart=alt.Chart(eventHistogramDF_filter, title="Event Name Wait Peformance Category in (Ms) %").mark_line().encode(
    x=alt.X('time:T', axis = alt.Axis(title='', labelAngle=-45, format=("%d/%m/%Y-%H%M"))),
    y=alt.Y("overall_perc:Q", title="% Wait Time in (MS) For ControlFile",sort=alt.SortField('waittimeinms', order='ascending')),
    color=alt.condition(pointer,alt.Color('waittimeinms:N',title="Wait Time",scale=alt.Scale(scheme='category20')),alt.value('lightgray'),sort=alt.SortField(field="waittimeinms",order='ascending')),
    column=alt.Column('instance_number:N', title="Instance Number"),
    tooltip=[alt.Tooltip('time:T', format='%d/%m/%Y-%H%M', title="Date and Time"),alt.Tooltip('instance_number:N', title="Instance Number"),
             alt.Tooltip('waittimeinms:N', title = "WaitTimeIn(Ms)"), alt.Tooltip('wait_count:N', title="NoOfWaitCount"),alt.Tooltip('overall_perc:Q', title="OverAllPercentage(%)")] 
    ).transform_filter(alt.FieldEqualPredicate(field='event_name',equal='controlfilesequentialread')
    ).properties(selection=pointer,width=250,height=250).resolve_scale(x='independent',y='independent',color='independent')

alt.vconcat(SingleBlockRead_chart, LogFileSeqRead_chart, ControlFileSeqRead_chart ).resolve_scale(x='independent',y='independent', color='independent')
```
Thanks

**Comment by jakevdp** [comment]
Thanks, can you elaborate on

> I tried to build Y x Z grid charts based on my data, but not able to find a dynamic way to plot the chart.

Your code shows vertical concatenation of three charts. I'm not sure I entirely understand what you're trying to do, and what problem you had.

**Comment by vbeer008** [comment]
Hi Jake, 

      Sure. I will try to explain more in details.

      In my pandas data frame, 

      1. It has a column INSTANCE_NUMBER (distinct digit value from range 1 - 4) and would like to use its column distinct value  to plot number of vertical (column) chart.

      2. Also, the dataframe has a column of EVENT_NAME (such as logfilesequentialread, dbfilesequentialread, controlfilesequentialread or so on ). I would this column to plot number of horizontal (row) chart.
 
      3. If my dataframe has 3 distinct INSTANCE_NUMBER  and DISTINCT EVENT_NAME, then the chart should be displayed in 3 x 3 Grid Charts.

      4. As you have seen my code, I have to build this 3 x 3 GRID chart with 3 times of  ( 1 x 3 ) charts and joined them together by using alt.vconcat. If my dataframe has more distinct value of EVENT_NAME, I need to keep modifying the code to build the GRID charts. Is there any way to simplify my method to achieve the same outcome please? I read a bit FACETED CHART or REPEATED CHART, but not sure it is suitable for my scenario.

**Comment by vbeer008** [comment]
I have worked out the method by  using for loop to get the GRID chart working based on my scenario.

**Comment by jakevdp** [comment]
It sounds like you can use `INSTANCE_NUMBER` in the `column` encoding, and `EVENT_NAME` in the `row` encoding. No need to manually filter and stack charts.

**Comment by vbeer008** [comment]
Hi Jake,

      I would like to try and learn your method as well. Would you please show me an example of using both encoding on row and column, but the X and Y Axis are based on time and overall_perc respectively. Thanks

**Comment by vbeer008** [comment]
Hi Jake,

     I just tried the method you have suggested. It works like a charm! Thanks.

**Comment by jakevdp** [comment]
Great!
