### ISSUE TITLE
altair chart save produces a blank image (svg or png) for vconcat of hconcat charts

### ISSUE THREAD

**Issue by colin0brass** [altair-viz/altair#2253]
Issue summary: altair chart save produces a blank image (svg or png) for vconcat of hconcat charts

```
## Issue summary: altair chart save produces a blank image (svg or png) for vconcat of hconcat charts

## platform = iMac, OS = Catalina (v10.15.6)
## Altair version: 4.1.0

## Environment creation commands:
# conda create -y -n py3 python=3.7
# conda activate py3
# conda install -y nb_conda
# pip install altair altair_saver
# pip install wget
# wget https://chromedriver.storage.googleapis.com/83.0.4103.39/chromedriver_mac64.zip
# unzip chromedriver_mac64.zip
# rm chromedriver_mac64.zip
# mv chromedriver /usr/local/bin/

# jupyter notebook altair_saver_png_test.ipynb ## this script/file, as a jupyter notebook

## Environment removal after the test
# conda deactivate py3
# conda env remove -y -n py3


import pandas as pd
import numpy as np
import altair as alt

# Generate Random Data
df = pd.DataFrame({'column1':['A','B','C','D'], 'values':np.random.rand(4)})

# create a simple chart
chart = alt.Chart(df).mark_bar().encode(
    x=alt.X('column1:N', title=None),
    y=alt.Y('sum(values):Q'),
    color=alt.Color('column1:N')
)

print(alt.__version__)
display(df)
chart.display()
chart.save('chart.png') # this works
chart.save('chart.svg') # this works
chart.save('chart.html') # this works

# generating chart 2d concat here, since facet doesn't currently support what I want for real/more-complex cases
# e.g. believe similar to: https://github.com/altair-viz/altair/issues/1800
def facet_wrap(subplts, plots_per_row):
    rows = [subplts[i:i+plots_per_row] for i in range(0, len(subplts), plots_per_row)]
    compound_chart = alt.hconcat()
    for r in rows:
        rowplot = alt.vconcat() #start a new row
        for item in r:
            rowplot |= item #add suplot to current row as a new column
        compound_chart &= rowplot # add the entire row of plots as a new row
    return compound_chart

# replicate same chart multiple times as simple test of facet_wrap and saving to file
chart_list = [chart]*9

compound_chart = facet_wrap(chart_list, 3)
compound_chart.display()
compound_chart.save('compound_chart.png') # this produces a blank image
compound_chart.save('compound_chart.svg') # this produces a blank image
compound_chart.save('compound_chart.html') # this works
```

**Comment by colin0brass** [comment]
Oh, interesting - I realised that I had inadvertently swapped chart type initialisation types inside 'facet_wrap' function, so these lines:
`    compound_chart = alt.hconcat()`
`        rowplot = alt.vconcat() #start a new row`

are better changed to:
`    compound_chart = alt.vconcat()`
`        rowplot = alt.hconcat() #start a new row`

i.e. initialising 'compound_chart' as an empty alt.vconcat (instead of hconcat), and 'rowplot' as an empty alt.hconcat (instead of vconcat).

With those simple changes then it *works*, saving correct compound_chart images to png & svg as well as the previously already working html.

I thought there might be a deeper problem case still, but even nesting 'facet_wrap' calls 2-deep and even 3-deep (to produce (3x3)*3*3 = 27x27 thumbnail plots) all worked, saving correct image files.

I propose to give this a little bit more thought in case I can figure out a remaining problem situation, but otherwise to close this ticket.

**Comment by jakevdp** [comment]
What altair_saver backend are you using? Selenium or Node?

**Comment by colin0brass** [comment]
Selenium.

See the rest of my setup flow at the top of this thread, though somehow I managed to miss documenting the selenium installation step from my instructions.

**Comment by jakevdp** [comment]
It's probably an issue with the Vega/Vega-Lite renderer: in general, hierarchies of compound charts are very incompletely supported (recent Vega-Lite releases have stopped supporting facet-of-facet, for example).

Glad you found a workaround.

**Comment by jakevdp** [comment]
The reason selenium vs. node is relevant, is that selenium always targets the exact Vega-Lite version used by Altair. Node targets whatever version was used to have the vega-cli executable you happen to have installed on your system. In general the two can have different behavior.

**Comment by colin0brass** [comment]
Thanks Jake. It is working fine for me now and I haven”t thought of any more problem cases, so I will close this ticket.
