### ISSUE TITLE
`Only chart objects can be used in ConcatChart` error when `concat` subcharts

### ISSUE THREAD

**Issue by crypdick** [altair-viz/altair#2257]
As per https://github.com/altair-viz/altair/issues/1925#issuecomment-669238407 when I try to horizontally  `alt.concat(three_subcharts)`, Altair raises `ValueError: Only chart objects can be used in ConcatChart`. I find this error confusing, because each of the three subcharts do individually plot correctly.

Code:

```python
    brush = alt.selection(type='interval', resolve='global')
    three_subcharts = []
    hyperparams = [('Learning Rate', "log"), ('L2 Penalty', "log"), ('Dropout', "linear")]

    for hyperparam, scaling in hyperparams:
        color = alt.condition(brush, alt.ColorValue('red'), alt.ColorValue('gray'))

        chart = alt.Chart(data).mark_circle().encode(
            alt.X(hyperparam, type='quantitative', scale=alt.Scale(type=scaling)),
            alt.Y("Score", type='quantitative'),
            row=alt.Row("Metric", type='nominal'),
            color=color,
            tooltip=['Learning Rate', 'L2 Penalty', 'Dropout']
        ).add_selection(
           brush
        )
        three_subcharts.append(chart)

    print(three_subcharts)  # prints: [alt.Chart(...), alt.Chart(...), alt.Chart(...)] (each plots correctly as well)
    alt.concat(three_subcharts)  # ValueError: Only chart objects can be used in ConcatChart.
```

Data is in long format:

| Dropout | Learning Rate | L2 Penalty | Metric | Score
| -- | -- | -- | -- | --

**Comment by jakevdp** [comment]
`alt.concat` does not accept a single argument containing a sequence; it accepts multiple arguments. Try this instead:
```python
alt.concat(*three_subcharts)
```

**Comment by crypdick** [comment]
@jakevdp progress! I unpacked the list, but now I get `Javascript Error: Undefined data set name: "scale_concat_1_child_main"
This usually means there's a typo in your chart specification. See the javascript console for the full traceback.`

I tried removing the `scale=alt.Scale(type=scaling))` -- same error.

I also tested if this was related to https://github.com/altair-viz/altair/issues/1727#issuecomment-649130623 by using the same y-axis limits, i.e. `alt.Y("Score", type='quantitative', scale=alt.Scale(domain=(0,1))),` but got the same error.

**Comment by jakevdp** [comment]
Maybe you have to set `.resolve_scale(x='independent')` on the concatenated chart?

**Comment by crypdick** [comment]
Things I tried:

`alt.concat(*charts).resolve_scale(x='independent')` - same "scale_concat_1_child_main" error

Add `.resolve_scale(x='independent')` to each subchart: outputs a seriously huge blank canvas (no error)

Add  `.resolve_scale(x='independent')`  to both subchart and the concatchart : huge blank canvas, no error

**Comment by joelostblom** [comment]
@crypdick Your approach should work, but it doesn't due to a bug in VegaLite leading to `Undefined data: scale_concat_1_child_main` error. [Details and a workaround here.](https://github.com/altair-viz/altair/issues/1727#issuecomment-782956219). Is it OK for you to close this issue, since it is being tracked upstreams in VegaLite and there is nothing that can be done about it in Altair?

**Comment by crypdick** [comment]
Thanks for the update @joelostblom!
