### ISSUE TITLE
Why is "white" doesn't show as white?

### ISSUE THREAD

**Issue by ma-sadeghi** [altair-viz/altair#2258]
The following code snippet
```python
temp = alt.Chart(source).mark_rect().encode(
    x=alt.X('x:O', sort=alt.EncodingSortField('y', order='descending')),
    y=alt.Y('y:O', sort=alt.EncodingSortField('y', order='descending')),
    color=alt.Color('z:Q', scale=alt.Scale(range=["white", "green"]))
).configure_scale(
    bandPaddingInner=0.1
)
```
produces the following heatmap:
![image](https://user-images.githubusercontent.com/14086031/89617204-c65d9e80-d857-11ea-9028-03515b00609a.png)
Is there a way to force `altair` to show "white" as actual "white"?

**Comment by jakevdp** [comment]
If you want specific values to be exactly white (rather than just on a linear scale that starts at white), you can specify multiple `domain` and `range` values to create a piecewise linear scale. For example:
```python
import altair as alt
import pandas as pd

x, y = np.meshgrid(range(-5, 5), range(-5, 5))
z = 20 * np.random.random(x.shape)
source = pd.DataFrame({'x': x.ravel(),
                       'y': y.ravel(),
                       'z': z.ravel()})


alt.Chart(source).mark_rect().encode(
    x=alt.X('x:O', sort=alt.EncodingSortField('y', order='descending')),
    y=alt.Y('y:O', sort=alt.EncodingSortField('y', order='descending')),
    color=alt.Color('z:Q', scale=alt.Scale(domain=[0, 2, 20], range=["white", "white", "green"]))
).configure_scale(
    bandPaddingInner=0.1
)
```
![visualization (32)](https://user-images.githubusercontent.com/781659/89663653-b57a5080-d88a-11ea-875c-8d19a137d248.png)

**Comment by joelostblom** [comment]
@ma-sadeghi I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
