### ISSUE TITLE
Why is timeUnit `week` not supported in altair?

### ISSUE THREAD

**Issue by Bartcardi** [altair-viz/altair#2259]
I want to plot weekly averaged data and intuitively I assumed `'week'` would be a valid time unit in `transform_timeunit()` since vega-lite [supports it](https://vega.github.io/vega-lite/docs/timeunit.html). However, I noticed it is not implemented in altair. Will this be added in a later version of altair? 

For now I can easily add a week number attribute in my dataframe and aggregate based on that.

**Comment by jakevdp** [comment]
The week timeUnit was added in Vega-Lite 4.14. Altair currently supports Vega-Lite 4.8

**Comment by Bartcardi** [comment]
Check, good to know! Thank you for your quick response. Next time I will have look at the vega-lite's changelog.
