### ISSUE TITLE
Axis values don't adapt to non-linear scale

### ISSUE THREAD

**Issue by baogianghoangvu** [altair-viz/altair#2260]
Hi.

Axis values seem to be evenly & linearly spaced in symlog10 scale, and therefore are bunched up together. (this is not an issue in log scale btw).

```python
import altair as alt
import pandas as pd

df = pd.DataFrame({"x": range(7), "y": [0, 2e1, 2e2, 2e3, 2e4, 2e5, 2e6]})

alt.Chart(df).mark_circle().encode(
    x=alt.X("x"), y=alt.Y("y", scale=alt.Scale(type="symlog"))
)
```
![image](https://user-images.githubusercontent.com/30065865/90238522-500cfd80-de50-11ea-860a-29a3d47cd4e1.png)

For now I'm manually setting the axis values e.g. 
```python
alt.Y(..., axis=alt.Axis(values=[0, 1e1, 1e2, 1e3, 1e4, 1e5, 1e6]))
```
to make them more spaced out.
![image](https://user-images.githubusercontent.com/30065865/90238636-7763ca80-de50-11ea-98fd-6b8596cdd58e.png)

Is there a way for Altair to automatically adapt axis values to scale?

**Comment by jakevdp** [comment]
Can you provide sample code?

**Comment by baogianghoangvu** [comment]
Sorry I should've added earlier.

**Comment by baogianghoangvu** [comment]
Actually it seems [Log scale has its own methods to automatically choose axis values](https://vega.github.io/vega-lite/docs/scale.html#log). So maybe the original issue is a Vega/Vegalite issue rather than Altair's?

**Comment by baogianghoangvu** [comment]
I think this probably is better suggested as an enhancement on Vegalite, so closing this issue and opening https://github.com/vega/vega-lite/issues/6933
