### ISSUE TITLE
altair display incorrect result when using 'sort' in alt.Y()

### ISSUE THREAD

**Issue by banshanren** [altair-viz/altair#2261]
I am running the code over a DataFrame object which has 3 columns:['city_name', 'district_name', 'product_num'].
![image](https://user-images.githubusercontent.com/7794465/90232331-17b8ef80-de4f-11ea-97e3-230c45a1d07e.png)

and I get the incorrect sort result as below.
![image](https://user-images.githubusercontent.com/7794465/90349541-d1d97280-e06c-11ea-86c5-3393e6d64f00.png)

I'd really appreciate if you could point out how to solve the problem. 
Thanks!

**Comment by debbes80** [comment]
Now you are sorting on district name, no?

**Comment by banshanren** [comment]
> Now you are sorting on district name, no?

Yes, axis y is 'district_name' and axis x is 'product_per'

**Comment by debbes80** [comment]
> > Now you are sorting on district name, no?
> 
> Yes, axis y is 'district_name' and axis x is 'product_per'

And you really want to sort on the name (string) and not the product_per (quantity)?

A fully reproducible example (inc data) would be good also. And maybe an example of how you think it should look like.

**Comment by banshanren** [comment]
> > > Now you are sorting on district name, no?
> > 
> > 
> > Yes, axis y is 'district_name' and axis x is 'product_per'
> 
> And you really want to sort on the name (string) and not the product_per (quantity)?
> 
> A fully reproducible example (inc data) would be good also. And maybe an example of how you think it should look like.

So sorry, I may have misunderstood what you mean (my English is not good), the axis x is "product_per" and my sort sentence is "sort='-x'", so I really want to sort on(or by?) the  product_per. Most rows are sorted in right place except that one I marked out.

**Comment by debbes80** [comment]
Might be related to [https://github.com/altair-viz/altair/issues/1963](https://github.com/altair-viz/altair/issues/1963).
Try using the EncodingSortField instead.

**Comment by banshanren** [comment]
> Might be related to #1963.
> Try using the EncodingSortField instead.

Thank you for you advice, but it still doesn't work.
![image](https://user-images.githubusercontent.com/7794465/90364801-50e3a080-e097-11ea-8e60-4689a1a55313.png)

**Comment by baogianghoangvu** [comment]
This looks like a very interesting issue.

I think it's quite hard to find out what went wrong without the actual dataframe. Could you share the data (the names can be anonymized if necessary)?

I random a chart to try to emulate (with some assumptions) your code here, but this works fine.

```Python
import altair as alt
import numpy as np
import pandas as pd

np.random.seed(seed=1)

df = pd.DataFrame(
    {
        "city_name": "City",
        "district_name": list("abcdefghijklmn"),
        "search_num": np.random.uniform(low=0, high=100, size=14),
    }
)

alt.Chart(alt.to_values(df[df["city_name"] == "City"])).transform_joinaggregate(
    total_product="sum(search_num)"
).transform_calculate(
    search_per="datum.search_num / datum.total_product"
).mark_bar().encode(
    x=alt.X("search_per:Q", axis=alt.Axis(format=".0%")),
    y=alt.Y("district_name:N", sort="-x"),
    tooltip=["district_name:N", "search_per:Q"],
)
```
![image](https://user-images.githubusercontent.com/30065865/90381982-5bf2fc80-e0a8-11ea-84e8-78b94c76e3ab.png)



Other than sharing your data, I'd recommend you try to _minimize_ your code bit by bit and see if the issue still persists:

- remove non-critical components e.g. tooltip, axis format, color.
- instead of altair transformations, do the calculations in another dataframe and `alt.Chart(new_df).mark(...)`

**Comment by banshanren** [comment]
> This looks like a very interesting issue.
> 
> I think it's quite hard to find out what went wrong without the actual dataframe. Could you share the data (the names can be anonymized if necessary)?
> 
> I random-ed a chart that tries to emulate (with some assumptions) your code here, but this works fine.
> 
> ```python
> import altair as alt
> import numpy as np
> import pandas as pd
> 
> np.random.seed(seed=1)
> 
> df = pd.DataFrame(
>     {
>         "district_name": list("abcdefghijklmn"),
>         "search_num": np.random.uniform(low=0, high=100, size=14),
>     }
> )
> 
> alt.Chart(alt.to_values(df)).transform_joinaggregate(
>     total_product="sum(search_num)"
> ).transform_calculate(
>     search_per="datum.search_num / datum.total_product"
> ).mark_bar().encode(
>     x=alt.X("search_per:Q", axis=alt.Axis(format=".0%")),
>     y=alt.Y("district_name:N", sort="-x"),
>     tooltip=["district_name:N", "search_per:Q"],
> )
> ```
> 
> ![image](https://user-images.githubusercontent.com/30065865/90382253-b55b2b80-e0a8-11ea-9142-169b8399e77c.png)
> 
> Other than sharing your data, I'd suggest you try to _minimize_ your code bit by bit and see if the issue still persists:
> 
> * remove non-critical components e.g. tooltip, axis format, color.
> * instead of altair transformations, do the calculations in a pandas dataframe and `alt.Chart(new_df).mark(...)`

Thank you for your suggestion, I reviewed the data, and found that there are two rows with same district_name in the dataframe 2333.
