### ISSUE TITLE
Multiline plot custom color

### ISSUE THREAD

**Issue by pranavkansara** [altair-viz/altair#2263]
I am trying to create a multiline plot as described in example given at https://altair-viz.github.io/gallery/multi_series_line.html
```
import altair as alt
from vega_datasets import data

source = data.stocks()

alt.Chart(source).mark_line().encode(
    x='date',
    y='price',
    color='symbol',
    strokeDash='symbol',
)

```
In this code, instead of setting color='symbol', how can I set my custom colors, as well as the strokedash?

**Comment by jakevdp** [comment]
Do you mean you have a single line that you want to set color and strokedash, or do you have a column that you want to encode while controlling the mapping between values and appearance?

**Comment by joelostblom** [comment]
@pranavkansara You can see how to provide a custom color scheme in the documentation https://altair-viz.github.io/user_guide/customization.html#color-domain-and-range. I am going to close this issue for now, but please feel free to reopen it if you want to reply with details to Jake's question above.
