### ISSUE TITLE
Add Texture to Charts with second legend box

### ISSUE THREAD

**Issue by rcolpo** [altair-viz/altair#2268]
Hi all,

Is it possible to add a second legend box with textures, apart from the color legend? In this case, it would be possible to have the color X, with texture Y and Z. Below is an example:

![image](https://user-images.githubusercontent.com/5889181/91362835-945aaf00-e7fb-11ea-997e-e18294b05cdd.png)

Thank you.

**Comment by joelostblom** [comment]
@rcolpo This is something hasn't been implemented in Vega and Vega-Lite yet, and it will unfortunately not be available in Altair until implemented there. You can follow the discussion in https://github.com/vega/vega-lite/issues/6062 and https://github.com/vega/vega/issues/1372. I am going to close this for now but please reopen if you have additional comments.
