### ISSUE TITLE
Column header overlay

### ISSUE THREAD

**Issue by rcolpo** [altair-viz/altair#2270]
Dear all,

Is there a way to prevent column headers/labels/titles to overlay, when plotting grouped bar charts? Maybe to wrap the headers into a new line, instead of overflowing?
Or to automatically increase the distance between the groups when the header is too long, or when there are too few bars in a given group?

```
df = pd.DataFrame([['Lorem ipsum dolor sit amet, consectetur', 5, 'A'],
				   ['Crime', 10, 'B'],
				   ['Lorem ipsum dolor sit amet, consectetur', 3, 'C'],
				   ['Crime', 9, 'D']],
				  columns=['Genre', 'Rating', 'Cartegory'])

chart = Chart(df).mark_bar().encode(
   column=Column('Genre'),
   x=X('Cartegory'),
   y=Y('Rating'),
).resolve_scale(
  x='independent'
)

chart.save('groupedStackedTest1.html')
```

![visualization3](https://user-images.githubusercontent.com/5889181/91551189-13e69c00-e92a-11ea-9347-ec547176de3d.png)

**Comment by armsp** [comment]
I don't know how it works but I had noticed this while filing my own issue #2252

@rcolpo  Use `facet` instead of `column` and it automatically takes care of the spacing -
```py
df = pd.DataFrame([['Lorem ipsum dolor sit amet, consectetur', 5, 'A'],
				   ['Crime', 10, 'B'],
				   ['Lorem ipsum dolor sit amet, consectetur', 3, 'C'],
				   ['Crime', 9, 'D']],
				  columns=['Genre', 'Rating', 'Cartegory'])

alt.Chart(df).mark_bar().encode(
   facet=alt.Facet('Genre'),
   x=alt.X('Cartegory'),
   y=alt.Y('Rating'),
).resolve_scale(
  x='independent'
)
```
![hello](https://user-images.githubusercontent.com/12681262/91898207-05490d80-ecb9-11ea-9028-7252c50c18de.png)

If you insist on using `column` then you can use the `spacing` parameter -
```py
df = pd.DataFrame([['Lorem ipsum dolor sit amet, consectetur', 5, 'A'],
				   ['Crime', 10, 'B'],
				   ['Lorem ipsum dolor sit amet, consectetur', 3, 'C'],
				   ['Crime', 9, 'D']],
				  columns=['Genre', 'Rating', 'Cartegory'])

alt.Chart(df).mark_bar().encode(
   column=alt.Column('Genre', spacing=100),
   x=alt.X('Cartegory'),
   y=alt.Y('Rating'),
).resolve_scale(
  x='independent'
)
```
Same output as above.
@jakevdp feel free to close this with the *question* label.

**Comment by rcolpo** [comment]
Dear @armsp. Thank you so much! It works like a charm :)
