### ISSUE TITLE
Use local vega, vega-lite and vega-embed JS files

### ISSUE THREAD

**Issue by iarabadjiev** [altair-viz/altair#2271]
Following the example of embedding multiple plots into one html page in Issue #1422 , I saved the the vega, vega-lite and vega-embed javascript files locally, so that the html page can be rendered on a computer without internet. I then replaced the script urls

```
	<script src="https://cdn.jsdelivr.net/npm/vega@5"></script>
	<script src="https://cdn.jsdelivr.net/npm/vega-lite@4.0.2"></script>
	<script src="https://cdn.jsdelivr.net/npm/vega-embed@6"></script>
```

 with local files location

```
	<script type="text/javascript" src="vega@5.js"></script>'
	<script type="text/javascript" src="vega-embed@6.js"></script>
	<script type="text/javascript" src="vega-lite@4.0.js"></script>


```

but the plots disappeared, and I got this error message in my browser console:

```
vega-embed@6.js:26 The input spec uses Vega-Lite v4.0.2, but the current version of Vega-Lite is vundefined.
(anonymous) @ vega-embed@6.js:26
TypeError: mr.compile is not a function
    at Object.vega-lite (vega-embed@6.js:26)
    at vega-embed@6.js:26
    at Generator.next (<anonymous>)
    at vega-embed@6.js:16
    at new Promise (<anonymous>)
    at i (vega-embed@6.js:16)
    at vega-embed@6.js:26
    at vega-embed@6.js:26
    at Generator.next (<anonymous>)
    at a (vega-embed@6.js:16)
```

I downloaded the js files directly from the links that produced a working chart. Does anyone have any idea how to make this work?

Thanks,
Ivo

PS: here are all the files. Replace the vega files file format by .js and the charts by .html if you want to test them.

[charts_with_local_files.txt](https://github.com/altair-viz/altair/files/5149612/charts_with_local_files.txt)
[charts_with_links.txt](https://github.com/altair-viz/altair/files/5149615/charts_with_links.txt)
[vega@5.txt](https://github.com/altair-viz/altair/files/5149621/vega%405.txt)
[vega-embed@6.txt](https://github.com/altair-viz/altair/files/5149622/vega-embed%406.txt)
[vega-lite@4.0.txt](https://github.com/altair-viz/altair/files/5149628/vega-lite%404.0.txt)

**Comment by jakevdp** [comment]
I think the `@` sign in the filenames may be problematic.

**Comment by jakevdp** [comment]
If your goal is to be able to view charts offline, you might consider [altair_viewer](https://github.com/altair-viz/altair_viewer), which does this more automatically.

**Comment by iarabadjiev** [comment]
Thanks for the reply!

> I think the `@` sign in the filenames may be problematic.
> 
> Also, javascript files typically use a `.js` extension.

I tried changing the names, but unfortunately it was unsuccessful.
 

> If your goal is to be able to view charts offline, you might consider [altair_viewer](https://github.com/altair-viz/altair_viewer), which does this more automatically.

I wanted to avoid having to use a python kernel if possible, and just have a static web page.


I also posted this issue in the vega-lite github (https://github.com/vega/vega-lite/issues/6827), and I will update this issue if I find a solution.

**Comment by domoritz** [comment]
You need to reorder the script tags.

```html
		<script type="text/javascript" src="vega@5.js"></script>
		<script type="text/javascript" src="vega-lite@4.0.js"></script>
		<script type="text/javascript" src="vega-embed@6.js"></script>
```

**Comment by joelostblom** [comment]
@iarabadjiev I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
