### ISSUE TITLE
Zoom behaviour in a strip plot

### ISSUE THREAD

**Issue by claresloggett** [altair-viz/altair#2275]
I'm trying to enable pan and zoom on a strip plot.

I am creating a strip plot using what I think is the standard trick in Altair/Vega, i.e. by using a faceted plot where each facet is a category and we create jitter using the leftover y (or x) axis. For example:

```
df = pd.DataFrame({'Category': ['A']*100 + ['B']*100,
                   'Value': np.random.randn(200)})

alt.Chart(df)\
    .mark_circle()\
    .transform_calculate(jitter='sqrt(-2*log(random()))*cos(2*PI*random())')\
    .encode(row='Category:N',
            y=alt.Y('jitter:Q', 
                    title=None,
                    axis=alt.Axis(labels=False)),
            x='Value:Q')\
    .properties(width=600,height=60)\
    .configure_view(strokeWidth=0)\
    .configure_facet(spacing=0)\
    .interactive()
```

The `.interactive()` call here allows me to pan and zoom, but zooming has an unfortunate effect on the strip plot. The (quantitative) x-axis zooms fine, but the y-axis is actually a set of facets, and the real y-axes are inside the facets. So zooming in by binding to 'scales' causes each facet to zoom in *independently* rather than zooming in on the plot as a whole. The means that the jittered data points get clipped by the edges of each facet, so zooming in actually causes data points to disappear. Of course zooming a plot *always* causes data points to disappear, but usually they disappear off the edge of the plot, which is intuitive and expected, wheras here they are disappearing off the edges of the facet, which to the user looks like the middle of the plot. 

Fundamentally the problem is that the strip plot is not really a single plot, even though it conceptually would like to be - we're using facets to work around the fact that we can't add jitter to a categorical variable. 

Is there any way round this? What I would like is the natural zoom behaviour, i.e. for zooming in to cause each category to take up more room on the plot so that some categories (in this case facets) disappear off the edges of the plot.

**Comment by bartekpi** [comment]
If you have only two categories there's a fairly easy hack, but it can get a bit messy if there's a lot of them.

If you move `transform_calculate()` into the DataFrame
```python
df = pd.DataFrame({
    'Category': ['A']*100 + ['B']*100,
    'Value': np.random.randn(200),
    'jitter': np.sqrt(-2*np.log(np.random.random(200)))*np.cos(2*np.pi*np.random.random(200))
}
)
```
And calculate the min/max jitter within groups `A` and `B`, you can then find offsets that would spread them enough:
```python
grouped = df.groupby('Category').agg(
    vmin=('jitter', 'min'),
    vmax=('jitter', 'max')
    )
B_max = grouped.loc['B', 'vmax']
A_min = grouped.loc['A', 'vmin']
extra_space = 1.25  # magic number to increase spread in case it's "too adjacent"
offset_A = extra_space * (B_max - A_min)/2
offset_B = -offset_A

labels = pd.Series([offset_A, offset_B], index=['A', 'B'])

df['CategoryValue'] = df['Category'].map(labels.to_dict()) + df['jitter']
```

Then instead of a faceted chart this can be a regular scatterrplot with custom y-axis labels
```python
alt.Chart(df).mark_circle(
).encode(
    x='Value:Q',
    y=alt.Y('CategoryValue:Q',
            title='Category',
            axis=alt.Axis(
                values=[labels.A, labels.B],
                labelExpr=f"datum.value == {labels.A} ? 'A' : datum.value == {labels.B} ? 'B' : null"
            )),
).properties(
     width=600,
     height=120
).configure_view(
    strokeWidth=0
).interactive()
```

**Comment by claresloggett** [comment]
Thank you @bartekpi ! I considered the alternative hack you're describing - i.e. making the field numeric - but had never tried it. The axis labels are fiddlier than I realised they'd be, since I hadn't considered that you can't set the axis labels using simple strings, you have to set them from the data using a labelExpr. Having the example code is helpful, cheers,

**Comment by joelostblom** [comment]
@claresloggett I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet?

**Comment by claresloggett** [comment]
@joelostblom thanks for following up! bartekpi's workaround works, but is pretty verbose if there are more than a very small number of categories. My question (as a question) has been answered, but the answer is that the functionality I was looking for doesn't exist. Unless something new has been implemented that I don't know of, I think there is still an open feature request here, to either:

* allow "jitter" to be added to a categorical variable, or
* allow the zoom behaviour to bind to the rows instead of the y-axis

The first of those actually sounds conceptually easier to me. Categorical variables are not numeric, and jitter is, but it would seem possible to adopt a convention where the jitter scales as a fraction of the category (i.e. where the categories are treated as if they are a distance 1 apart on the axis), so that a jitter of 0.1 has a spread of 10% of the distance between categories on the axis.

I believe there was some work started way back, within the altair team, on adding dx and dy encoding channels to allow easier jitter (as well as to enable some other things) - I don't remember where I saw this but I can hunt it down if you haven't seen it.

**Comment by joelostblom** [comment]
Thanks for clarifying! I'll leave this open until there is a better way to achieve this behavior. The relevant Vega-Lite ticket for jitter plots is here https://github.com/vega/vega-lite/issues/4703, I'm also very excited for it to be implemented =)

**Comment by joelostblom** [comment]
This is now possible using the offset encodings as in [this example](https://altair-viz.github.io/gallery/strip_plot_jitter.html) to jitter points. For the code in the OP this could now e.g. become something like this which makes the zooming work as expected:

```python
import pandas as pd
import numpy as np


df = pd.DataFrame({'Category': ['A']*100 + ['B']*100,
                   'Value': np.random.randn(200)})

alt.Chart(df)\
    .mark_circle()\
    .transform_calculate(jitter='sqrt(-2*log(random()))*cos(2*PI*random())')\
    .encode(y='Category:N',
            yOffset=alt.YOffset('jitter:Q'),
            x='Value:Q')\
    .properties(width=600,height=60)\
    .interactive()
```
