### ISSUE TITLE
Error exporting to SVG

### ISSUE THREAD

**Issue by biotemon** [altair-viz/altair#2276]
I am trying to export a figure to SVG by the following command. 

```
fig3A.save("fig3A_pca_beta-taxonomic_diversity.svg")
```

The output is not empty, there are axis and legends. But there is no data plotted.
On the console, I get this too. 

```
WARNING:tornado.access:404 GET /altair-data-89e6a73ac534817e04e67ceef5cff984.csv (::1) 0.29ms
WARNING:tornado.access:404 GET /altair-data-5e77bb66a6b0e7c2530f13a178019c1b.csv (::1) 0.21ms 
```

I have reinstalled jupyter again and again, I don't get it to fix it. 

Any idea is greatly appreciated.

**Comment by DataKhukhua** [comment]
Where can i find this code in repo , there's no matches

**Comment by biotemon** [comment]
The code is not public yet.

**Comment by jakevdp** [comment]
It looks like you've enabled the CSV data transformer, which is not compatible with saving charts.
```
alt.data_transformers.enable('default')
```
and then save your chart again.

The issue is similar to this one: https://github.com/altair-viz/altair/issues/2110

**Comment by biotemon** [comment]
Thank you very much. It worked.
