### ISSUE TITLE
Altair choropleth map, color highlight based on line chart selection

### ISSUE THREAD

**Issue by angelrps** [altair-viz/altair#2277]
Hi!

I am plotting a choropleth map colored by the field ``Passenger_0_`` and a line chart showing the evolution of ``Passenger_0_`` throughout a day by ``zone``.

I would like to select a line (``zone``) in the line chart and have it highlighted in the map and vice versa (select a zone in the map and have it highlighted in the line chart).

For now, I am able to change the whole color of the map when selecting the line, but have no clue of how to only change the color of the selected area.

I would appreciate any help. This is the code:

```python
dict_json = json.loads(long_df[long_df['hour']==0].to_json())

colours_obj = alt.Color('properties.Passenger_0_:Q',
              scale=alt.Scale(scheme='yelloworangered'),
             title = "Pickups")

sel_line_hover = alt.selection_single(on='mouseover', empty='none')
sel_line_col = alt.selection_single()
sel_line_size = alt.selection_single(empty='none')

base = alt.Chart(alt.Data(values=dict_json['features'])).mark_geoshape(
    stroke='black',
    strokeWidth=1
    ).encode(
    color=alt.condition(sel_line_col, colours_obj, alt.value('lightgray')),
    tooltip = ['properties.zone:O',
               'properties.Passenger_0_:Q']
    ).properties(
    width=350,
    height=750,
    ).add_selection(
    sel_line_col
    )

line = alt.Chart(long_df).mark_line().encode(
    x='hour',
    y='Passenger_0_',
    color=alt.condition(sel_line_hover|sel_line_col, 'zone', alt.value('lightgray')),
    size=alt.condition(sel_line_hover|sel_line_size, alt.value(4),alt.value(1)),
    tooltip = ['zone:O']
    ).properties(
    width=250,
    height=750,
    ).add_selection(
    sel_line_hover,sel_line_col,sel_line_size
    )

base | line
```
![altair_map_and_linechart_st](https://user-images.githubusercontent.com/57810653/92301965-664a3d00-ef68-11ea-945e-9a40d16dc51a.gif)

**Comment by armsp** [comment]
@angelrps Are the datasets used here publicly available?

**Comment by angelrps** [comment]
@armsp yes they are. You can download them from here https://opendata.cityofnewyork.us/, why?

**Comment by armsp** [comment]
@angelrps the kind of highlighting you are talking about looks like change in opacity. Since you haven't provided the exact link to dataset, I would suggest you try replacing `color` with something like `fillOpacity` or `opacity` and replacing the color values with a numerical in [0,1].

**Comment by angelrps** [comment]
Thank very much @armsp , I will try your suggestion.

**Comment by joelostblom** [comment]
[Answered on SO.](https://stackoverflow.com/a/65948144/2166823). @angelrps if my reply there solves your problem, could you close this issue?

**Comment by angelrps** [comment]
Thank you very much for your answer @joelostblom I haven´t had time to try your solution but I will close this issue until I test it.
