### ISSUE TITLE
Altair not rendering in Jupyter notebook

### ISSUE THREAD

**Issue by Duane321** [altair-viz/altair#2279]
Hi there,

I'm running into an issue that popped out seemingly out of no where. As of this morning, when I try to run a simple Altair plot, it fails to render in the jupyter notebook. Like:

```
import pandas as pd
import altair as alt
df = pd.DataFrame(dict(a=[1], b=[2]))
alt.Chart(df).mark_point().encode(x='a', y='b')
```

which yields:

```
Error loading script: Script error for "vega-util", needed by: vega-embed http://requirejs.org/docs/errors.html#scripterror
```

In the command line of the notebook, I also see:

```
 404 GET /static/vega-util.js?v=20200908081432 (::1) 2.82ms referer=http://localhost:8888/notebooks/bug_demo.ipynb
```

I'm running on Windows 10, which may have updated itself last night. I'm at a loss. I've tried a few things: uninstalling/install jupyter, notebook, altair and vega, but none of that seems to work. Any help would be huge!

**Comment by domoritz** [comment]
I'm fixing it. Please follow https://github.com/vega/vega-embed/issues/557.

**Comment by domoritz** [comment]
Hmm, it looks like the browser is trying to load vega-util from `/static` but it's not there. I can probably make a change to Embed to load vega instead.

**Comment by domoritz** [comment]
Please try Vega-Embed 6.12.2

**Comment by Duane321** [comment]
Thanks @domoritz - I ran the build process for vega-embed, but it's not solving the issue. I'm guessing it's b/c Altair isn't pointing to this updated version. Do we have to wait for altair to rely on Vega-Embed 6.12.2?

**Comment by domoritz** [comment]
Can you make sure to clear the browser cache? Altair didn't specifically rely on the version I pushed this weekend either.

**Comment by rpavon** [comment]
Clearing browser cache did not solve the issue

**Comment by domoritz** [comment]
Which embed version is being loaded? Maybe the CDN caches just need to update.

**Comment by jakevdp** [comment]
Altair's default renderer loads vega-embed@6 from the CDN. You should get the newest version unless your browser is cacheing an older one.

**Comment by Duane321** [comment]
Oh great - it works now, thanks!

**Comment by rpavon** [comment]
Using Altair 4.1.0 in Jupyter.  As of this morning, not showing graph due to the following error: 
 Error loading script: Script error for "vega-util", needed by: vega-embed http://requirejs.org/docs/errors.html#scripterror

The error message is displayed when the notebook is opened and where the output graph would be rendered.




    On Tuesday, September 8, 2020, 01:23:51 PM CDT, Dominik Moritz <notifications@github.com> wrote:  
 
 


Which embed version is being loaded? Maybe the CDN caches just need to update.

**Comment by kangluxin** [comment]
I got the same error since yesterday. I upgraded Altair to the latest version. Now it does not show the error, but it does not show the chart neither. Any idea how to fix it?

**Comment by domoritz** [comment]
Do you see any warnings in the browser console? Can you try installing Altair again?
