### ISSUE TITLE
Altair not showing the chart

### ISSUE THREAD

**Issue by kangluxin** [altair-viz/altair#2287]
Altair started not showing the chart since around 3 days ago. I use the same code which have been working in the past, but it started to show the error:
"Error loading script: Script error for "vega-util", needed by: vega-embed http://requirejs.org/docs/errors.html#scripterror"

I followed https://github.com/altair-viz/altair/issues/2279 and upgrade to the latest version. Now the error disappeared, but it does not show the chart neither. I run the code in Sagemaker (Jupyter Notebook), and it shows empty cell basically. 

I plan to use Altair in our production code, could anyone help as soon as possible? Thanks!

**Comment by jakevdp** [comment]
This is the same problem reported in #2280; it's already been fixed, but you need to clear your browser's cache to remove the problematic vega-embed javascript library.

**Comment by kangluxin** [comment]
Okay, thanks. I think the installation file messed up when I upgraded in the same Sagemaker instance. I started a new Sagemaker instance and install the package again. It is working now.
