### ISSUE TITLE
Color Legend shows negative infinity as null

### ISSUE THREAD

**Issue by pankajb64** [altair-viz/altair#2288]
I'm new to Altair so apologies if I'm doing an obvious mistake here. I'm trying to generate a multi-(line + scatter) plot, and to achieve color I am using an ordinal variable that contains negative infinity as one of the values. When I  render the plot, the legend for negative infinity shows up as `null`.

I am using the following code.
```
circle = alt.Chart(dfca).mark_circle(size=60)
line = alt.Chart(dfca).mark_line().encode(opacity=alt.value(0.2))

(circle + line).encode(
    x=alt.X('logmstar_low:Q', scale=alt.Scale(zero=False)),
    y='red_fraction:Q',
    color=alt.Color('log_Sigma_5_low:O', sort='descending', scale=alt.Scale(scheme='turbo', reverse=True))
).properties(width=900, height=600)
```

which generates this plot

![visualization (4)](https://user-images.githubusercontent.com/825377/93045940-89d74c80-f626-11ea-947f-a3a0879e205d.png)

If it helps, the color variable `log_Sigma_5_low` represents lower bound of an interval and can be one of the following values: `[-np.inf, -1. , -0.8, -0.6, -0.4, -0.2,  0. ,  0.2,  0.4,  0.6,  0.8, 1. ]`

Happy to provide more information if needed.

**Comment by jakevdp** [comment]
JSON has no way to represent infinity, so when Altair encodes data to JSON it converts infinities to nulls. One way around this is to explicitly encode your data as strings rather than numbers, in which case you can use any value you'd like. For example:
```python
import altair as alt
import pandas as pd
import numpy as np

df = pd.DataFrame({
    'd': np.arange(5),
    'c': [-np.inf, 0, 1, 2, 3]
})

df['c'] = df['c'].astype(str)

alt.Chart(df).mark_point().encode(
    x='d',
    y='d',
    color='c:N'
)
```
![visualization (35)](https://user-images.githubusercontent.com/781659/93111887-207a2c80-f66c-11ea-911c-58556934fef6.png)

**Comment by pankajb64** [comment]
Thanks for the response.  Your suggestion worked, except that the ordering was all messed up. I fixed that by passing in an array specifying the exact ordering I want, to the `sort` attribute.

The final code looks like this (apologies for all the non-intuitive column names)

<pre><code>
circle = alt.Chart(dfca).mark_circle(size=60)
line = alt.Chart(dfca).mark_line().encode(opacity=alt.value(0.2))

(circle + line).encode(
    x=alt.X('logmstar_low:Q', scale=alt.Scale(zero=False)),
    y='red_fraction:Q',
    color=alt.Color('log_Sigma_5_low_str:N', <b>sort=np.flip(dfca['log_Sigma_5_low_str'].unique()), </b> scale=alt.Scale(scheme='turbo',reverse=True))
).properties(width=900, height=600)
</code></pre>

which produces the following plot.

![visualization (6)](https://user-images.githubusercontent.com/825377/93161047-b56a3d80-f6df-11ea-955d-81aa3a68cacd.png)

**Comment by jakevdp** [comment]
Yeah, once you convert to strings the default order is alphabetical. Glad you figured it out!
