### ISSUE TITLE
Using altair with jupyter lab offline

### ISSUE THREAD

**Issue by ketulm** [altair-viz/altair#2289]
I'm using Altair in an isolated/offline environment with no CDN access.

With Altair 4.1.0, I started getting the following error and can no longer produce and view Altair charts inside the Jupyter Lab.
`Error loading script: https://cdn.jsdelivr.net/npm//vega@5?next`

I have no issues with version 3.2 (just recently updated to 4.1). 

Is this use-case no longer supported? do we have to switch to `altair_viewer` to be able to use Altair in always-offline-mode (inside notebooks)?

**Comment by jakevdp** [comment]
The default renderer changed in version 4.X.

To get offline behavior, you need to install the altair labextension and use `alt.renderers.enable('jupyterlab')`. See https://altair-viz.github.io/user_guide/display_frontends.html for more information.

**Comment by ketulm** [comment]
That works, thanks @jakevdp!
