### ISSUE TITLE
Support for vega custom projections

### ISSUE THREAD

**Issue by vectro** [altair-viz/altair#2294]
Vega supports the use of custom projections using [vega.projection](https://vega.github.io/vega/docs/api/extensibility/#projection), and third-party d3 projections are available (see e.g., [this library](https://github.com/stamen/geo-albers-usa-territories#readme)). But, Altair has a hard-coded list of supported projections, meaning it's not possible to use Altair with custom Vega projections. There should be a way to override the check of known projections in Altair, so that one can use other custom projections.

**Comment by jakevdp** [comment]
Thanks for the request!

This can be done by changing the Javascript embedding code for the vega-lite specifications that altair produces.

That said, Altair is fundamentally a tool to create vega-lite specifications, and vega projections are not expressible in vega-lite. Given that, I'm going to close this feature request as out-of-scope for the project.

**Comment by vectro** [comment]
Hi Jake, thanks for the super fast response.

I don't really claim to understand the distinction between vega and vega-lite, but I note that if one updates the definition of ProjectionType in vega-lite-schema.json to include a custom projection name registered using vega.projection, then the new projection can be used and it works fine.  Does that cause you to update your beliefs about this issue at all?

**Comment by jakevdp** [comment]
Altair's only control over a chart comes from what is defined in the Vega-Lite specification. Yes, you can specify a custom projection in the specification, but in order for it to do anything, that custom projection has to be defined in the renderer.

So where is the renderer? It's in the JuptyerLab frontend code... the nteract frontend code... the VSCode frontend code... the Streamlit frontend code. Except in the simplest circumstances, Altair has no control over how the chart is rendered, beyond what can be specified in the Vega-Lite spec.

Theoretically, would it be possible to coordinate all these disparate projects and decide on a standard whereby Javascript extensions could be injected into them? Maybe. Probably not, though, given how problematic user-generated Javascript can be security-wise. At best, it would be a feature that works in some frontends and not in others.
