### ISSUE TITLE
QUESTION: proxy URLs to CSV files are being interpreted as JSON

### ISSUE THREAD

**Issue by dmoore247** [altair-viz/altair#2295]
I'm working on a solution to #1927. The solution requires a proxy and a token parameter and a custom renderer.

When I use the proxy & token parameter, I'm finding `https://...../airports.csv?token=aed48293f38293` is being interpreted as a json rather than a .csv. How does altair/vega determine the type? 
Does altair/vega go by the file extension (last 3 chars of URL) or by the mime type response header (which isn't set) from the proxy.

I know the `https://...../airports.csv?token=aed48293f38293` is being mis-interpreted because when I look at the compiled Vega it says: json as the type.  When using the github source `https://...github.../airports.csv`, the data type shows up as csv.

**Comment by jakevdp** [comment]
I'm not sure how Vega determines the default, but `alt.UrlData` has a `format` parameter that can be used to specify the format.

**Comment by joelostblom** [comment]
@dmoore247 I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet?

**Comment by joelostblom** [comment]
Closing this, feel free to reopen if something is not resolved yet.
