### ISSUE TITLE
Question: Can you plot a Gaussian distribution?

### ISSUE THREAD

**Issue by davidpickup** [altair-viz/altair#2297]
Is it possible to plot a normal distribution based on the mean/stddev of some data using altair?

**Comment by jakevdp** [comment]
Sure, for example:
```python
import altair as alt
import numpy as np
import pandas as pd
from scipy.stats import norm

x = np.linspace(-5, 5, 1000)
df = pd.DataFrame({'x': x, 'y': norm.pdf(x)})
alt.Chart(df).mark_line().encode(
    x='x',
    y='y'
)
```
![visualization - 2020-09-23T195702 765](https://user-images.githubusercontent.com/781659/94095620-f4327e80-fdd6-11ea-8b6c-513c0281071d.png)

**Comment by joelostblom** [comment]
@davidpickup I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
