### ISSUE TITLE
Altair Error

### ISSUE THREAD

**Issue by Feesvife** [altair-viz/altair#2302]
Hi, I am trying to find a solution to this below, but everyone told me that they had never seen this error:

<<

Javascript Error: 'ShadowRoot' is not defined
This usually means there's a typo in your chart specification. See the javascript console for the full traceback.>>

Thanks for your help.

**Comment by Feesvife** [comment]
This is what I trying to encode:

data = accidentes.groupby(['Rango edad', 'Sexo'])['Expediente'].count().reset_index()

alt.Chart(data, width=300, height=150, title='Accidentes en Madrid durante 2019').mark_bar().encode(
    x = alt.X('Rango edad:O', sort = rango_edad.categories.to_list(), title = None),
    y = alt.Y('Expediente:Q', title = 'Numero de implicados'),
    facet=alt.Facet('Sexo:N', title = None))

**Comment by jakevdp** [comment]
Which browser are you using?

**Comment by Feesvife** [comment]
I´m using Microsoft Edge

**Comment by jakevdp** [comment]
It sounds like you're using an older version of Edge that does't support features used by the Vega renderer. See https://vega.github.io/vega/usage/internet-explorer/ for details. I suspect if you update Edge to the latest version, the charts will work correctly.

**Comment by Feesvife** [comment]
Great, you were right!! it Works, I changed to Google Chrome.

I did this:

Launch Anaconda Prompt
Type jupyter notebook --generate-config
Type notepad path_to_file/jupyter_notebook_config.py to open it (change path_to_file)
Modify #c.NotebookApp.browser = '' to c.NotebookApp.browser = 'C:/Program Files (x86)/Google/Chrome/Application/chrome.exe %s'

and now it works.

Thanks for your help.

**Comment by joelostblom** [comment]
@Feesvife I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet?

**Comment by joelostblom** [comment]
@Feesvife Feel free to reopen if you think this issue is not yet resolved.
