### ISSUE TITLE
Using impute with count()

### ISSUE THREAD

**Issue by ov212** [altair-viz/altair#2303]
Hi All,

Is it possible to use impute with data aggregation? I'm drawing a line graph with time on the x axis and count of records on the y axis. I want the line to return to 0 when there are no records for that year. 

Taking the example from https://github.com/altair-viz/altair/issues/1768#issuecomment-549370312 :

```
data = pd.DataFrame({
    'x': [1, 2, 3, 5, 6, 7, 9, 10],
    'y': [1, 2, 3, 4, 5, 6, 7, 8],
})

alt.Chart(data).mark_line(point=True).encode(
  x='x',
  y=alt.Y('y',
    impute=alt.ImputeParams(
      value=None,
      keyvals=list(range(11))
    )
  )
)
```

![graph_image](https://user-images.githubusercontent.com/781659/68126834-7c5f1b00-fec9-11e9-84ff-4fd316ff521d.png)

Instead, showing the count of records

```
alt.Chart(data).mark_line(point=True).encode(
  x='x',
  y=alt.Y('count()'
))
```

![visualization](https://user-images.githubusercontent.com/10629004/94458128-6e834a00-01ad-11eb-9f5f-b1eed2bfb346.png)

But trying to use impute to miss x=4 and x=8 gives an error.

```
alt.Chart(data).mark_line(point=True).encode(
  x='x',
  y=alt.Y('count()',
    impute=alt.ImputeParams(
      value=None,
      keyvals=list(range(11))
    )
  )
)
```
"Javascript Error: Missing required "impute" parameter: "field"
This usually means there's a typo in your chart specification. See the javascript console for the full traceback."

Thanks

**Comment by jakevdp** [comment]
The problem is that within encodings, imputation is evaluated before aggregation.

If you want the aggregation to happen first, you can do this by explicitly computing the count transform outside the encoding. For example:
```python
import altair as alt
import pandas as pd

data = pd.DataFrame({
    'x': [1, 2, 3, 5, 6, 7, 9, 10],
    'y': [1, 2, 3, 4, 5, 6, 7, 8],
})

alt.Chart(data).transform_aggregate(
  y_count = 'count()',
  groupby=['x']  
).mark_line(point=True).encode(
  x='x',
  y=alt.Y('y_count:Q',
    impute=alt.ImputeParams(
      value=None,
      keyvals=list(range(11))
    )
  )
)
```
![visualization (40)](https://user-images.githubusercontent.com/781659/94462216-05311600-0170-11eb-9892-e44efa319ca5.png)

**Comment by ov212** [comment]
Brilliant - thanks for such a speedy reply
