### ISSUE TITLE
Javascript error adding output!

### ISSUE THREAD

**Issue by alra7867** [altair-viz/altair#2304]
Hi,

I am new to Altair. I tried making a chart with Altair. It gives me the error below. Although my Pandas is working perfect.

Error:

Javascript error adding output!
TypeError: Cannot read property 'previousElementSibling' of null
See your browser Javascript console for more details.

**Comment by jakevdp** [comment]
Thanks. A couple questions:

- what browser are you using? (firefox, chrome, edge, etc.)
- what frontend are you using? (jupyter notebook, jupyterlab, streamlit, etc.)
- have you enabled any renderers? (e.g. `alt.renderers.enable('jupyterlab')`)

**Comment by alra7867** [comment]
Thanks so much for the prompt response!
--> I am running Google Chrome (Version 85.0.4183.121 (Official Build) (64-bit))
--> I am using Jupyter Notebook
--> No, I haven't enabled any renderers yet. Don't know about it.

**Comment by alra7867** [comment]
I just enabled the renderer, by copy-pasting the code you shared "alt.renderers.enable('jupyterlab')". I am not sure, what I did is right.
And it gave me this output: 
<VegaLite 4 object>
If you see this message, it means the renderer has not been properly enabled
for the frontend that you are using. For more information, see https://altair-viz.github.io/user_guide/troubleshooting.html

**Comment by jakevdp** [comment]
The JupyterLab renderer does not work with Jupyter Notebook (surprisingly, it is designed to work with JupyterLab :grin:)

There seems to be some issue with the javascript environment in which the notebook is executing the code; I'd suggest trying the notebook renderer; see https://altair-viz.github.io/user_guide/display_frontends.html#displaying-in-the-jupyter-notebook for more information.

**Comment by alra7867** [comment]
It turns out, I was using older version of jupyter notebook. So I had to run this in terminal: jupyter nbextension install --sys-prefix --py vega

Thanks so much, Jake for the help. Have a great week.

**Comment by oyinfaith** [comment]
Please am also facing the challenges and i have followed the guidelines but not still working

**Comment by jakevdp** [comment]
Please open another issue, paste the exact code you’re running and describe the problem you’re having.
