### ISSUE TITLE
Empty chart displays in Jupyter Lab when using URL pointing to local file

### ISSUE THREAD

**Issue by nelsonuhan** [altair-viz/altair#2308]
Altair displays an empty chart in Jupyter Lab when specifying data as a URL string pointing to a local file. 

For example, I tried running the following code in Jupyter Lab, to no avail:

```python
import altair as alt
from vega_datasets import data

cars = data.cars()
cars.to_json('./cars.json', orient='records')

alt.Chart('./cars.json').mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color='Origin:N'
)
```

I've included a screenshot below, showing the empty chart, as well as the output from the Google Chrome console.

If I include `alt.renderers.enable('jupyterlab')` before `alt.Chart...` in the code above, then the chart displays as expected.

Is this expected behavior, with URLs pointing to local files? Do I always need to configure the renderer in this use case?

Version information: `jupyterlab==2.2.6`, `altair==4.1.0`

Thanks for your help!

![screenshot](https://user-images.githubusercontent.com/7253603/95130079-0347f380-072a-11eb-9d84-fb76452bfe83.png)

**Comment by jakevdp** [comment]
JupyterLab's server does not necessarily make files in the Python working directory accessible to the browser. I would post a question to the JupyterLab user group regarding how to construct a valid URL to a particular file on your system.

**Comment by nelsonuhan** [comment]
@jakevdp, thank you for your quick reply!

I wanted to specify data as a URL pointing to a local file as a way around the `MaxRowsError`.

Looking at the [documentation](https://altair-viz.github.io/user_guide/faq.html#maxrowserror-how-can-i-plot-large-datasets) and #1867, I see that one way of working with large local files (especially in JupyterLab) is:

1. Read the large local file into a DataFrame.
2. Use `alt.data_transformers.enable('data_server')`. (I couldn't get `alt.data_transformers.enable('json')` to work in JupyterLab, either.)

Is this the "recommended" way to work with large local files?

**Comment by jakevdp** [comment]
There really is no good way to work with large datasets in Altair, but the suggestions at https://altair-viz.github.io/user_guide/faq.html#maxrowserror-how-can-i-plot-large-datasets are probably your best bet.

**Comment by joelostblom** [comment]
@nelsonuhan I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet?
