### ISSUE TITLE
Line plot Markers

### ISSUE THREAD

**Issue by brentonmallen1** [altair-viz/altair#231]
Is it possible to add markers to a line plot? I couldn't seem to figure out how to go about doing this.

**Comment by jakevdp** [comment]
Yes, you can do that through the layer interface. Layers are still a bit clunky at the moment (they're only experimentally supported in the current Vega-Lite release), but they should work for simple plots. Here's an example:

```python
from altair import *
import pandas as pd
import numpy as np
data = pd.DataFrame({'x': np.arange(50)})
data['y'] = np.sin(data['x'] / 5)

chart = LayeredChart(data)

chart += Chart().mark_line().encode(x='x', y='y')
chart += Chart().mark_circle().encode(x='x', y='y')

chart
```
![vega 1](https://cloud.githubusercontent.com/assets/781659/19402872/90d2636a-9218-11e6-8045-ea0a443c53b7.png)

We'll probably revisit the API for layering before the 2.0 release, so if you have any thoughts on the subject let us know!

**Comment by brentonmallen1** [comment]
ah, that makes sense.  I was mistakenly trying to mess with the MarkConfig().  Thanks for the demo, it's appreciated and if I come up with any thoughts/ideas I'll pass them along.

**Comment by jakevdp** [comment]
Added to FAQ in 29b5d86d2292a96a9f36656168e49b3fdf1f7b52
