### ISSUE TITLE
Viewing vega / altair plots in Jupyter notebooks on GitHub

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2311]
GitHub (and ReviewNB) renders Jupyter notebooks quite nicely, including plots outputted as images. However, it does not seem to have support for rendering plots from vega specs. What is the preferred way to view changes of plots generated in vega/altair in Jupyter notebooks on GitHub? Do you use `alt.renderers.enable('png')` before committing and comment it out when working with interactive visualizations locally or are there more efficient approaches?

If there is an issue open about supporting the rendering of vega specs on GitHub, I would be happy to `+1` it, but I couldn't find one when searching so I might just send them this as a suggestion (although I have no idea if this is a straightforward request...).

**Comment by jakevdp** [comment]
If you use the vega nbextension (on notebook) or labextension (on JupyterLab), all charts will be saved along with a PNG preview that will be rendered in Github's notebook view

**Comment by joelostblom** [comment]
Ah smart, how convenient! I noticed that it does not work with the default `'html'` renderer for me. I need to change it to either `'jupyterlab'` or `'mimetype'` to get the png blob in the notebook. Does that sound correct?

**Comment by jakevdp** [comment]
Yes, if you're using JupyterLab, you must use the `'mimetype'` renderer (or its alias, `'jupyterlab'`). If you're using Jupyter Notebook, you must use the `'notebook'` renderer, and also install the vega nbextension.

**Comment by joelostblom** [comment]
Thank you! I was a bit confused by what I think is an old part of the docs, which I opened a PR for #2313. Closing this.
