### ISSUE TITLE
Legend selection_multi clear behavior can't be modified

### ISSUE THREAD

**Issue by BielStela** [altair-viz/altair#2312]
Hi,

I'm trying to change the clear behavior of a legend selection. The docs say that the behavior is a `dblclick` but in reality you have to click around an empty region of the legend to clear the selection.

I've tried to define a clear EventStream that reproduces the default behavior:

```python
alt.selection_multi(fields=["group"], bind="legend", toggle="event.ctrlKey", clear=alt.EventStream(type='dblclick'))
```
but it fails with the JS error:
```
Uncaught (in promise) TypeError: t.events is not iterable
```
Also the docs are wrong:

```
clear:anyOf(Stream, string, boolean)
	Clears the selection, emptying it of all values. Can be a Event Stream or false to disable.
	Default value: dblclick.
	See also: clear documentation.
```
since any string or boolean gives the same error as before.

My versions are:
altair == 4.1.0
vega-embed@6.12.2
vega-lite@4.16.8

Thanks!

**Comment by BielStela** [comment]
looks like it is a vega-lite issue https://github.com/vega/vega-lite/issues/6553

**Comment by joelostblom** [comment]
This is tracked in the VL issue linked above. Closing since there is nothing that can be done from the altair side of things.
