### ISSUE TITLE
Bootstrapped Confidence Intervals

### ISSUE THREAD

**Issue by sophiefsadler** [altair-viz/altair#2315]
Hi, I'd really like to know how many samples are used by default during bootstrapping of the mean for confidence intervals? https://altair-viz.github.io/gallery/errorbars_with_ci.html

I've trawled the source code and cannot find the answer myself.

**Comment by jakevdp** [comment]
I believe it uses 1000 samples; you can see the source here: https://github.com/vega/vega/blob/8d6793f4ca7eaaf2d22186764e9ce2dae687cf52/packages/vega-transforms/src/util/TupleStore.js#L127

**Comment by sophiefsadler** [comment]
Thank you!
