### ISSUE TITLE
seeking workaround for cdn.jsdelivr.net in air-gapped environment

### ISSUE THREAD

**Issue by erikerlandson** [altair-viz/altair#2316]
I'm trying to run some notebooks using altair charts in an environment with no internet connectivity.  So far I haven't been able to persuade altair to not fail on trying to download `vega-embed` over `cdn.jsdelivr.net`.

I have tried pre-installing the vega js deps on an image, like `npm install -g altair ...`, and also` altair_saver`, like:
https://stackoverflow.com/questions/63101246/altair-offline-rendering

It is possible I've gotten the mechanics wrong on these, but wondering if any other workarounds exist.

**Comment by jakevdp** [comment]
If you use a jupyter notebook or jupyterlab frontent extension and the appropriate renderer, charts can be viewed offline. See https://altair-viz.github.io/user_guide/display_frontends.html for more.

Another option for offline viewing that doesn't require Jupyter is to use `altair_viewer`; see https://github.com/altair-viz/altair_viewer.

**Comment by erikerlandson** [comment]
@jakevdp thanks!   Another solution we are testing is doing a local mirror of the JS deps. That would require us to tell altair to look at a new url different than cdn.jsdeliver.net  -  do you know what the best way is to override that default url?  In my perfect world this would be something I could change with an environment variable but I don't think the code currently does that.

**Comment by jakevdp** [comment]
The best way is probably to enable the renderer with a new `base_url`. For example:
```python
import altair as alt
alt.renderers.enable('default', base_url="https://localhost:8000")
 
# _repr_mimebundle_ is the method that Jupyter frontends use to decide how to display a chart.
HTML = alt.Chart('foo.csv').mark_point()._repr_mimebundle_()['text/html']

print(HTML[:1000])
# <div id="altair-viz-abd5ddc95cbf4bc3874a6a7bfc318020"></div>
# <script type="text/javascript">
#   (function(spec, embedOpt){
#     let outputDiv = document.currentScript.previousElementSibling;
#     if (outputDiv.id !== "altair-viz-abd5ddc95cbf4bc3874a6a7bfc318020") {
#       outputDiv = document.getElementById("altair-viz-abd5ddc95cbf4bc3874a6a7bfc318020");
#     }
#     const paths = {
#       "vega": "https://localhost:8000/vega@5?noext",
#       "vega-lib": "https://localhost:8000/vega-lib?noext",
#       "vega-lite": "https://localhost:8000/vega-lite@4.8.1?noext",
#       "vega-embed": "https://localhost:8000/vega-embed@6?noext",
#     };
```

**Comment by erikerlandson** [comment]
I see, that makes sense, it's a parameter of the rendering config. thanks!

**Comment by carlmes** [comment]
Thanks for the tips on using `base_url`. Is it possible to explicitly set the individual paths and file names (instead of just a base URL)? Those libraries are stored on the internal Nexus server as:

```
https://nexus.<company domain>.com/repository/npm-all//vega/latest
https://nexus.<company domain>.com/repository/npm-all//vega-lib/latest
https://nexus.<company domain>.com/repository/npm-all//vega-lite/latest
https://nexus.<company domain>.com/repository/npm-all//vega-embed/latest
```

So I'm wanting to set the individual file names, e.g. instead of `vega@5?noext"` I would use `vega/latest`. 

Also, are altair.renderers parameters documented anywhere? I took a look at the [altair docs](https://altair-viz.github.io/user_guide/display_frontends.html#renderer-api) but didn't find any references to parameters such as `base_url`, perhaps there is another document source where I might find this?

**Comment by erikerlandson** [comment]
I think we'll need to run our own registry server api (not just serving raw files), maybe `verdaccio` in a container

**Comment by joelostblom** [comment]
@erikerlandson I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet?

**Comment by erikerlandson** [comment]
@joelostblom  I'll close it.  Technically I don't think I ever quite verified this was working, but it was because I had some logistic difficulties attaching a proper trusted TLC cert to my verdaccio server, and my browser refused to connect to an npm server using a self-signed certificate, for security reasons. By the time I got verdaccio working correctly, my original use case had become obsoleted for completely unrelated reasons.

If I ever re-try this and run into problems with altair, I can always re-open it.
