### ISSUE TITLE
Empty chats in facet documentation

### ISSUE THREAD

**Issue by iliatimofeev** [altair-viz/altair#2317]
[Repeated Charts](https://altair-viz.github.io/user_guide/compound_charts.html#repeated-charts)  or [Faceted Charts](https://altair-viz.github.io/user_guide/compound_charts.html#faceted-charts) documentation is broken. 

Seems like Dominik [removed](https://github.com/vega/vega-datasets/commit/d9757c890f53c2950a79327a362b5651aa4f5946#diff-3a6eb0790f39ac87c94f3856b2dd2c5d110e6811602261a9a923d3bb23adc8b7) `iris.json` from `vega-datasets` .

He recommends using `penguins_size.csv` instead.

**Comment by joelostblom** [comment]
This is being tracked here https://github.com/altair-viz/altair/issues/2213

**Comment by jakevdp** [comment]
Fixed, sorry for the delay.
