### ISSUE TITLE
Scatter plot matrix of only one corner

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2321]
Is it possible to only create the bottom corner of a scatter matrix / splom? Or in some other way create a full pairwise comparison without repeating the same plot twice (and without plotting variables against themselves as on the diagonal)?

```python
import altair as alt
from vega_datasets import data

source = data.cars()

(alt.Chart(source).mark_circle().encode(
    alt.X(alt.repeat("column"), type='quantitative'),
    alt.Y(alt.repeat("row"), type='quantitative'),
    color='Origin:N')
 .properties(width=150, height=150)
 .repeat(
    row=['Horsepower', 'Acceleration', 'Miles_per_Gallon'],
    column=['Horsepower', 'Acceleration', 'Miles_per_Gallon']))
```

![image](https://user-images.githubusercontent.com/4560057/96358794-19f23100-10c0-11eb-8eb7-67e827910ea1.png)

I can get closer by removing one of the values from the row or col list, but there is still at least one plot against self where all the points are in a diagonal line. I am looking for something like this:

![image](https://user-images.githubusercontent.com/4560057/96359056-fed4f080-10c2-11eb-9a8e-00f95322d9ff.png)

**Comment by harabat** [comment]
Hope this adds to the discussion:

The [Seaborn implementation](https://seaborn.pydata.org/generated/seaborn.pairplot.html) is quite elegant:
```python
from vega_datasets import data
sns.pairplot(
    data=data.cars()[['Horsepower', 'Acceleration', 'Miles_per_Gallon']],
    kind='scatter',
    diag_kind='kde',
    corner=True
)
```
---
R's [GGally](https://www.rdocumentation.org/packages/GGally/versions/1.5.0/topics/ggpairs) package also has an interesting layout:

```r
visitors %>%
  pivot_wider(values_from=Trips, names_from=State) %>%
  GGally::ggpairs(columns = 2:9)
```
---
<img src="https://user-images.githubusercontent.com/45575009/108234775-096cc880-713d-11eb-888a-ac4de823e60b.png" height="300">

**Comment by joelostblom** [comment]
Actually, this issue probably fits better in the VegaLite repo, so I will close it here. I also started working on a few wrapper functions for common EDA plots with Altair (including a scatter matrix), I will post it here when/if I make it into a package that I think would be beneficial to others than myself.

**Comment by joelostblom** [comment]
If anyone stumbles across this you can [check out this wrapper package I made](https://joelostblom.github.io/altair_ally/examples.html) to make it quicker to create some exploratory plots of the entire dataframe, including one corner scatter matrices.
