### ISSUE TITLE
Boxplots not sorting

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2322]
Boxplots appears to not be respecting the `sort` parameter, even when using a custom encoding sort field. In addition to enabling this, it would be nice if the shorthand `sort='x'` also worked and sorted based on the median by default (which is what I believe would be the most intuitive sort for a box). For now I am calculating and passing a list separately.

This works for points:

```python
source = data.barley()

alt.Chart(source).mark_point(
    filled=True,
    color='black'
).encode(
    x=alt.X('median(yield)', title='Barley Yield'),
    y=alt.Y(
        'variety',
         sort=alt.EncodingSortField(
             field='yield',
             op='median',
             order='descending'
         )
    )
).properties(
    width=400,
    height=250
)
```

![image](https://user-images.githubusercontent.com/4560057/96369660-30c07400-1110-11eb-9e3c-41d6606a166b.png)

But not for boxes:

```python
import altair as alt
from vega_datasets import data

source = data.barley()

alt.Chart(source).mark_boxplot(
#     filled=True,
#     color='black'
).encode(
    x=alt.X('yield', title='Barley Yield'),
    y=alt.Y(
        'variety',
         sort=alt.EncodingSortField(
             field='yield',
             op='median',
             order='descending'
         )
    )
).properties(
    width=400,
    height=250
)
```

![image](https://user-images.githubusercontent.com/4560057/96369688-5188c980-1110-11eb-93ef-3e0eb310a98c.png)

**Comment by firasm** [comment]
Is there any way to tell if this is a Vega issue or an Altair one? Just ran into this myself when sorting boxes.

**Comment by jakevdp** [comment]
This is a vega issue.

**Comment by joelostblom** [comment]
Sorry I should have closed this and linked those issues. You can still pass a sorted list, and if you are creating repeated charts where the axis differs between subplots, you can pass one long list with all the different categorical axis ticks from every repeated chart.
