### ISSUE TITLE
Insert value from slider to select column for color

### ISSUE THREAD

**Issue by ScampyOwl** [altair-viz/altair#2324]
I'm creating a **scatterplot** and for each data point, the DataFrame has **two x,y columns** for position and **101 columns [0,100] that label** the data points differently. The **slider** should help to **select a column for labeling/coloring**.

Hence, depending on **slider position**, I want to **insert its values as color** like this:
```
color = alt.Color('1:N')
color = alt.Color('40:N')
color = alt.Color('67:N')
```

So far, I couldn't access the slider value in any way to accomplish this and haven't found any solution.
Using .transform_calculate and the variable name 'col' for the color, the string 'col' is used directly and the slider value is the label itself, but I can't use col as a variable name otherwise, because it isn't defined then.

I also tried to use the selector.percentage itself, because it seems to work as a number when comparing to numbers within alt.condition(), but still I get the same issue as with 'col' and I don't get a number out of it.

```
slider = alt.binding_range(name='Perc', min=0, max=100, step=1)
selector = alt.selection_single(name='Percentage', fields=['percentage'], bind=slider, init={'percentage': 5})

base = alt.Chart(source).properties(
    width=600,
    height=600
)

points = base.mark_point(filled=True, size=30
    ).transform_calculate(col=selector.percentage
    ).encode(
        x = 'x:Q',
        y = 'y:Q',
        color = alt.Color('col'+':N')
    ).add_selection(selector
    )
```

This is what I'm getting:
![grafik](https://user-images.githubusercontent.com/28989342/96790296-d9175680-13f6-11eb-857f-d6f1500b7349.png)
I want to get this:
![grafik](https://user-images.githubusercontent.com/28989342/96790367-f9dfac00-13f6-11eb-9756-9863b064c142.png)

Is it possible to do this?

**Comment by ChiaLingWeng** [comment]
Try to reproduce the issue as below:
```
import altair as alt
from vega_datasets import data
import random

#print(len(source.Horsepower))
source = data.cars()

# To generate 5 different color config
for i in range(5):
    random_list = random.sample(range(1, 4), counts=[200,200,200], k=406)
    source[str(i)] = random_list
```
so the dataframe is now:
                          Name  Miles_per_Gallon  Cylinders  Displacement  \
0    chevrolet chevelle malibu              18.0          8         307.0   
1            buick skylark 320              15.0          8         350.0   
2           plymouth satellite              18.0          8         318.0   
3                amc rebel sst              16.0          8         304.0   
4                  ford torino              17.0          8         302.0   
..                         ...               ...        ...           ...   
401            ford mustang gl              27.0          4         140.0   
402                  vw pickup              44.0          4          97.0   
403              dodge rampage              32.0          4         135.0   
404                ford ranger              28.0          4         120.0   
405                 chevy s-10              31.0          4         119.0   

     Horsepower  Weight_in_lbs  Acceleration       Year  Origin  0  1  2  3  4  
0         130.0           3504          12.0 1970-01-01     USA  2  1  3  1  3  
1         165.0           3693          11.5 1970-01-01     USA  3  1  3  1  1  
2         150.0           3436          11.0 1970-01-01     USA  2  2  1  1  1  
3         150.0           3433          12.0 1970-01-01     USA  3  1  3  1  1  
4         140.0           3449          10.5 1970-01-01     USA  1  2  2  3  2  
..          ...            ...           ...        ...     ... .. .. .. .. ..  
401        86.0           2790          15.6 1982-01-01     USA  3  3  3  2  3  
402        52.0           2130          24.6 1982-01-01  Europe  2  3  3  1  3  
403        84.0           2295          11.6 1982-01-01     USA  3  1  3  2  1  
404        79.0           2625          18.6 1982-01-01     USA  2  2  1  1  1  
405        82.0           2720          19.4 1982-01-01     USA  2  1  3  2  3  

[406 rows x 14 columns]

**Comment by joelostblom** [comment]
Thanks for following up on this issue @ChiaLingWeng . If I understand correctly, it seems to me like this is covered by the new section in the docs that you linked so we can close this.
