### ISSUE TITLE
Gridlines not removed when setting tickMinStep

### ISSUE THREAD

**Issue by morberg** [altair-viz/altair#2329]
(I originally made a comment on the closed issue #1655, but it is probably better to handle this as a separate issue.)

When setting `tickMinStep` in Altair 4.1.0 the gridlines remain although the ticks are no longer shown. Is this a bug? I would expect the gridlines to disappear as well as shown in https://github.com/altair-viz/altair/issues/1655#issuecomment-520519501 .

```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'x': range(5),
    'y': range(5)
})

alt.Chart(df).mark_point().encode(
    alt.X('x', axis=alt.Axis(tickMinStep=1.0)),
    alt.Y('y')
)
```
<img width="453" alt="image" src="https://user-images.githubusercontent.com/956034/97585748-c81fa400-19f9-11eb-9521-f7bcf1faf439.png">

**Comment by jakevdp** [comment]
It looks like grid lines don't respond to `tickMinStep`. This may be a Vega-Lite bug – I'd suggest inquiring there.

To work around it, you can specify `tickCount`, e.g.
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'x': range(5),
    'y': range(5)
})

alt.Chart(df).mark_point().encode(
    alt.X('x', axis=alt.Axis(tickMinStep=1.0, tickCount=4)),
    alt.Y('y')
)
```
![visualization - 2020-10-30T071302 875](https://user-images.githubusercontent.com/781659/97715214-5b4eed00-1a7f-11eb-926a-df78917b4a4a.png)

**Comment by joelostblom** [comment]
It seems like this was fixed in VL, but has since then become an issue again. The progress can be followed in https://github.com/vega/vega-lite/issues/9034. I'm closing this since there is nothing altair can do to fix this bug.
