### ISSUE TITLE
Bug: when zero=False in Scale the bar plot is unreadable

### ISSUE THREAD

**Issue by rubik** [altair-viz/altair#233]
Every time I use `zero=False` the chart becomes unreadable. Example:
```python
import pandas as pd
from io import StringIO


csv = StringIO(",education_level,birth_year\n0,5,1961.0\n1,6,1968.0\n2,7,1967.2857142857142\n3,8,1975.2105263157894\n4,9,1970.2608695652175\n5,10,1974.037037037037\n6,11,1971.6818181818182\n7,12,1967.6216216216217\n'")

d = pd.read_csv(csv)
Chart(d).mark_bar().encode(
    x='education_level:N',
    y=Y('birth_year',
        scale=Scale(zero=False),
        axis=Axis(format='f')),
)
```

the result is an absurdly tall plot, completely blank. At the end there are the usual three links 'View source', 'Open in Vega editor', etc. I won't add it here because it would ruin the layout and the readability of the discussion. Chrome reports a canvas with dimensions 253 x 43242 pixels.

This is the result in Vega instead, obtained by clicking 'Open in Vega editor':
![vega](https://cloud.githubusercontent.com/assets/238549/19409904/1e42103a-92df-11e6-9f88-8d3318d8d107.png)

```json
{
  "config": {"cell": {"height": 350,"width": 500}},
  "mark": "bar",
  "data": {
    "values": [
      {
        "education_level": 5,
        "birth_year": 1961,
        "Unnamed: 0": "0"
      },
      {
        "education_level": 6,
        "birth_year": 1968,
        "Unnamed: 0": "1"
      },
      {
        "education_level": 7,
        "birth_year": 1967.2857142857144,
        "Unnamed: 0": "2"
      },
      {
        "education_level": 8,
        "birth_year": 1975.2105263157891,
        "Unnamed: 0": "3"
      },
      {
        "education_level": 9,
        "birth_year": 1970.2608695652173,
        "Unnamed: 0": "4"
      },
      {
        "education_level": 10,
        "birth_year": 1974.037037037037,
        "Unnamed: 0": "5"
      },
      {
        "education_level": 11,
        "birth_year": 1971.6818181818185,
        "Unnamed: 0": "6"
      },
      {
        "education_level": 12,
        "birth_year": 1967.6216216216214,
        "Unnamed: 0": "7"
      },
      {
        "education_level": null,
        "birth_year": null,
        "Unnamed: 0": "'"
      }
    ]
  },
  "encoding": {
    "y": {
      "field": "birth_year",
      "type": "quantitative",
      "axis": {"format": "f"},
      "scale": {"zero": false}
    },
    "x": {"field": "education_level","type": "nominal"}
  }
}
```

Summary:
* the chart is totally blank, and this happens **only** with `mark_bar` and `zero=False`. All else works as expected (es. `mark_point` or `mark_line` with `zero=False`)
* the same JSON works in Vega editor. This is really puzzling.

**Comment by jakevdp** [comment]
Thanks for the report. This is due to a bug in the version of Vega-Lite bundled with ipyvega < 0.4.3. If you ``pip install --upgrade vega`` and then [re-install the jupyter extension](https://altair-viz.github.io/installation.html#installation), you'll see the plot displayed correctly.

**Comment by rubik** [comment]
Thanks a lot, that did it.

**Comment by jakevdp** [comment]
One warning on this: there are a few little corner cases where the spec output by altair 1.0 is not compatible with the vega-lite code in vega 0.4.3. But I'm hoping to get a new altair release out ASAP.
