### ISSUE TITLE
Legend entry limit

### ISSUE THREAD

**Issue by jackyho112** [altair-viz/altair#2333]
I can't find an answer anywhere, so I am seeking some guidance here. Is there any way to expand the number of entries on the legend? 

For example,

```python
alt.Chart(college_data_merged).mark_bar().encode(
    x=alt.X('sum(Electoral college vote count)', stack="normalize", axis=alt.Axis(format='%')),
    y='Year',
    color=alt.Color('State', legend=alt.Legend(columns=2))
).properties(width=600, height=700)

```

<img width="944" alt="Screen Shot 2020-11-05 at 10 15 42 PM" src="https://user-images.githubusercontent.com/25375401/98332925-858b3800-1fb4-11eb-86d7-ac2c34eaae8e.png">

Is there any configuration that would allow the extra entries to be displayed? 

Thanks!

**Comment by jakevdp** [comment]
You can set the `symbolLimit` argument of `alt.Legend()` to the maximum number of symbols you'd like to appear in the legend. If you set it to zero, an unlimited number of entries will be shown.

**Comment by jackyho112** [comment]
Thanks for the answer!
