### ISSUE TITLE
Is there an easier way to combine text and calculation in mark_text() ?

### ISSUE THREAD

**Issue by morberg** [altair-viz/altair#2335]
I want to combine text and a calculated value in mark_text().

```python
import altair as alt
from vega_datasets import data

source = data.cars()

bar = alt.Chart(source).mark_bar().encode(
    x=alt.X('Origin'),
    y=alt.Y('count(Origin)', stack='zero'),
    color=alt.Color('Cylinders:N')
)

text = alt.Chart(source).mark_text(baseline='top', color='white').encode(
    x='Origin',
    y=alt.Y('count(Cylinders)', stack='zero'),
    text='label:N'
).transform_joinaggregate(
    count="count(Cylinders)",
    groupby=["Cylinders", "Origin"]
).transform_calculate(
    label=alt.datum.Cylinders + " Cylinders: " + alt.datum.count
)

(bar + text).properties(width=500, height=600)
```

<img width="628" alt="image" src="https://user-images.githubusercontent.com/956034/98919432-13908280-24cf-11eb-950c-86577dc536a3.png">

This works, but it feels like a hack. Is there a simpler way to achieve this?

It would be nice to say something like `text="Cylinders + ' Cylinders: ' + count(Cylinders)"` instead.

**Comment by jakevdp** [comment]
No, there's no easier way to do this. Using a calculate transform is not a hack: it's the documented way to derive new values from existing values.
