### ISSUE TITLE
Set line chart groupings without setting colors

### ISSUE THREAD

**Issue by evanr70** [altair-viz/altair#2336]
I have a pandas dataframe which I'm using to create a leader board for an event. It has three columns: club, round number and position. Following the multi series line plot example, I can almost get the chart I want. I want to set all of the line colors to be the same (black). However, if I remove the color encoding, the points are no longer grouped by club and so i get a single line joining all of them.

Is there a way of grouping points to create lines between them which doesn't involve setting the color/marker shape?

Additionally, I want use `mark_image` to display a logo for each club. I have this working fine, but is there a way to also plot lines between consecutive points for the same club as in the previous part of the question?

**Comment by jakevdp** [comment]
You can do this using the `detail` encoding.

**Comment by evanr70** [comment]
Thanks so much for your quick reply!
