### ISSUE TITLE
Register Click for Entire Chart Object

### ISSUE THREAD

**Issue by Murtz5253** [altair-viz/altair#2339]
Is there any way in Altair to register a click for an entire chart object? I am building an app using Streamlit, and I want my user to be able to select from a choice of charts, and I want to record the selected chart to the back-end. I am trying to use Altair in combination with this package: https://github.com/domoritz/streamlit-vega-lite

**Comment by jakevdp** [comment]
You could probably do this via javascript & HTML. Each chart is rendered in its own div, and Javascript can be used to register mouse events on a div.

That's entirely outside Altair, though.

**Comment by joelostblom** [comment]
@Murtz5253 I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet?

**Comment by joelostblom** [comment]
Closing for now since this is outside Altair.
