### ISSUE TITLE
Altair Sample Charts in Documentation Not Show

### ISSUE THREAD

**Issue by ihightower** [altair-viz/altair#2341]
Many of the Altair sample charts in documents do not show.. e.g. in this URL: https://altair-viz.github.io/user_guide/compound_charts.html

Order of Layers, HConcat, Repeated and Faceted Charts.. do not show the actual chart. It has been like this several weeks (or months).

I found out that.. it was dataset issue.

example the below works, (but the one shown in sample not work.. see the changes required to make it work in the code comment.

Please fix all chart samples.. as this causes problems for beginners like us to use the documentation to our benefit.

```
import altair as alt
from vega_datasets import data

source = data.movies() # This is the change required together with Column Names were wrong.. need space instead of underscore.

heatmap = alt.Chart(source).mark_rect().encode(
    alt.X('IMDB Rating:Q', bin=True),
    alt.Y('Rotten Tomatoes Rating:Q', bin=True),
    alt.Color('count()', scale=alt.Scale(scheme='greenblue'))
)

points = alt.Chart(source).mark_circle(
    color='black',
    size=5,
).encode(
    x='IMDB Rating:Q',
    y='Rotten Tomatoes Rating:Q',
)

heatmap + points
```

**Comment by jakevdp** [comment]
Reported in #2213
