### ISSUE TITLE
Displaying Selected Data in an Easy-to-View Manner for User

### ISSUE THREAD

**Issue by Murtz5253** [altair-viz/altair#2342]
I have a line chart that my user interacts with (via Streamlit), and it allows the user to select a certain portion of the graph and displays the sum in a bar chart below. However, having the sum show up in a bar chart is not very user-friendly. Is there a way to display the sum in a clearer way? Perhaps via a tooltip or to just have it appear on the graph after the user selects the region? Here is an image of what it currently looks like:

![image](https://user-images.githubusercontent.com/42280297/99932127-fb5d0680-2d0b-11eb-93c9-97536334e1e7.png)

Here is my current code:

```
df = create_state_df(state)
    df = add_image_col_to_df_with_date(df, start_date, end_date)
    df["New_Cases_Rolling"] = df["New_Cases"].rolling(window=7, min_periods=1).mean()
    brush = alt.selection_interval(encodings=['x'], empty='all', mark=alt.BrushConfig(fill='red'))
    base = alt.Chart(df).mark_line().encode(
                x='Day:Q',
                y='New_Cases_Rolling:Q',
                tooltip=['sum(New_Cases_Rolling):Q']
            ).properties(
                width=600,
                height=400
            ).add_selection(
                brush
            )

    img = create_image_layer(df, 'Day', 'New_Cases_Rolling', 'image_url')

    bars = alt.Chart(df).mark_bar().encode(
        alt.Y('Province_State:N'),
        alt.X('sum(New_Cases_Rolling):Q'),
        opacity=alt.value(0.9)
    ).transform_filter(
        brush
    ).properties(
        width=600,
        height=40
    )

    return (base + img) & bars
```

**Comment by jakevdp** [comment]
Instead of `mark_bar()`, you could use `mark_text()` to display the textual value, either in a layer or in another panel.

**Comment by joelostblom** [comment]
@Murtz5253 I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet?

**Comment by joelostblom** [comment]
You can find an example of how to create a table with `mark_text` in this SO question https://stackoverflow.com/questions/67997825/python-altair-generate-a-table-on-selection
