### ISSUE TITLE
Can't compare distributions with Q-Q plots

### ISSUE THREAD

**Issue by HarvsG** [altair-viz/altair#2343]
Altair: 4.1.0
python: 3.7
Raspberrypi 3B+

```python
np.random.seed(42)
df = pd.DataFrame({
    'normal': np.random.randn(200),
    'pareto' : np.random.pareto(1,size=200),
    'uniform' : np.random.uniform(0,1,200)}
)
df.pareto.hist()
```
![image](https://user-images.githubusercontent.com/11440490/100006949-32422380-2dc3-11eb-97c7-1d78b4b0c98f.png)
Then lets say I want to compare the uniform or pareto distributions in altair
``` python
base= alt.Chart(df).transform_quantile(
    'normal', step=0.01,
    as_ = ['prob', 'value']
).mark_point().encode(
    alt.Y('value:Q')
)

base.encode(x='uniform:Q') | base.encode(x='pareto:Q')
```
![image](https://user-images.githubusercontent.com/11440490/100007068-60276800-2dc3-11eb-9848-5dc89e1ebd1a.png)

On a related note:
The [example in the docs](https://altair-viz.github.io/gallery/scatter_qq.html) could be considered misleading because `'v'` has multiple meanings:
it is a columns header
```
            u         v
0   -0.172410  0.007375
1    0.196435  0.132363
2   -0.050039 -0.089104
3   -0.115688  0.378889
4    0.251125  0.100950
..        ...       ...
495  0.065704  0.527776
496 -0.126547 -0.076258
497  0.070698 -0.284781
498 -0.247309  0.162710
499 -0.392565  0.204919
```
and then a the label for the `values` output from the `transform_quantile()` method
```python
base = alt.Chart(source).transform_quantile(
    'u',
    step=0.01,
    as_ = ['p', 'v']
).transform_calculate(
    uniform = 'quantileUniform(datum.p)',
    normal = 'quantileNormal(datum.p)'
).mark_point().encode(
    alt.Y('v:Q')
)

base.encode(x='uniform:Q') | base.encode(x='normal:Q')
```

**Comment by jakevdp** [comment]
When you do a quantile transform on a particular field, it throws out all fields that are not referenced (what else could it do?)

Can you add more detail about what you would expect to happen?

**Comment by HarvsG** [comment]
I think I was misunderstanding the use of Q-Q plots in altair. I was hoping to compare the distributions of two datasets rather than comparing a dataset against an known theoretical distribution (which vega has a limited number of)

I was able to achieve the desired effect by sorting the data and plotting it against one-another.

The issue with this method, where more complex implementations of Q-Q plots succeed, is when the sizes of data sets differ.

I wonder if there would be a way to replicate [this](https://stats.stackexchange.com/questions/77907/generate-qq-plot-for-sets-of-different-size) in python +altair

```python
df = pd.DataFrame({
    'normal': np.random.randn(201),
    'pareto' : np.random.pareto(1,size=201),
    'uniform' : np.random.uniform(0,1,201),
    'unknown' : np.random.pareto(2,size=201)}
)
sorted_df = df.apply(lambda x: x.sort_values().values)

base = alt.Chart().mark_point().properties(
    width=100,
    height=100
)

chart = alt.vconcat(data=sorted_df)
for y_encoding in ['normal:Q', 'pareto:Q', 'uniform:Q', 'unknown:Q']:
    row = alt.hconcat()
    for x_encoding in ['normal:Q', 'pareto:Q', 'uniform:Q', 'unknown:Q']:
        row |= base.encode(x=x_encoding, y=y_encoding)
    chart &= row
chart
```

![image](https://user-images.githubusercontent.com/11440490/100127971-91617000-2e77-11eb-956d-63c5c0cc1189.png)

**Comment by HarvsG** [comment]
I have achieved this using `percs = np.linspace(0,100,100)`  and `np.percentile(series, percs)`

```python
nf = pd.DataFrame({
    'normal': np.random.randn(201),
    'pareto' : np.random.pareto(1,size=201),
    'uniform' : np.random.uniform(0,1,201),}
)
unknown_long = np.random.pareto(2,size=901)
percs = np.linspace(0,100,100)

sorted_df = df.apply(lambda x: np.percentile(x,percs))
sorted_df['unknown'] = np.percentile(unknown_long, percs)

base = alt.Chart().mark_point().properties(
    width=100,
    height=100
)

chart = alt.vconcat(data=sorted_df)
for y_encoding in ['normal:Q', 'pareto:Q', 'uniform:Q', 'unknown:Q']:
    row = alt.hconcat()
    for x_encoding in ['normal:Q', 'pareto:Q', 'uniform:Q', 'unknown:Q']:
        row |= base.encode(x=x_encoding, y=y_encoding)
    chart &= row
chart
```
![image](https://user-images.githubusercontent.com/11440490/100158442-14002480-2ea4-11eb-9d2c-bcc1c8d769d2.png)
