### ISSUE TITLE
Color strips of figure

### ISSUE THREAD

**Issue by Amarounek** [altair-viz/altair#2345]
Hello!

How is possible to disappear the stripes in Figure 1? I need to express by a color when is the best time to plant the crops. I was trying different approaches and no one worked. Deleting `monthdate ` function just gives me a nice color, however bad x-axis (Figure 2). The configure_bar(binSpacing=0) also doesn't work here. Also, is there a possibility to use some form of a stacked figure (No yied y-axis, only color?

My code snippet is here:

```
import altair as alt
import numpy as np
import pandas as pd

alt.data_transformers.disable_max_rows()

np.random.seed(0)
Cumulative_Yield = pd.DataFrame({
    'sowing_date': pd.date_range('1990-01-01', freq='D', periods=366),
    'Cum_Yield': np.random.randn(366).cumsum()
})
Cumulative_Yield['month_date'] = Cumulative_Yield['sowing_date'].dt.strftime('%m-%d')

baryear = alt.Chart(Cumulative_Yield).mark_bar().encode(
    x=alt.X('monthdate(month_date):T', title='Calendar year'),
    y=alt.Y('Cum_yield:Q', title='Cumulative yield'),
    color=alt.Color('Cum_yield:Q',
                    scale=alt.Scale(scheme='redyellowgreen')))              

(baryear).properties(width=700, height = 100).configure_axisX(labelAlign="right", labelAngle=-45).configure_bar(binSpacing=0)

```
Figure 1
![image](https://user-images.githubusercontent.com/36733547/100117357-00899500-2e75-11eb-9acb-b7daa5b27ed2.png)
Figure 2)
![image](https://user-images.githubusercontent.com/36733547/100117659-53634c80-2e75-11eb-874f-7416398cc23f.png)

Many thanks in advance!

**Comment by jakevdp** [comment]
Using a `monthdate` timeunit will bin the data, which you probably don't want. If all you need is to adjust the axis formatting, you can do it via something like `axis=alt.Axis(format="%B %d")`

**Comment by Amarounek** [comment]
Thank you very much! It's beautiful now! 🥇 

Closed!
