### ISSUE TITLE
alt.selection_single does not work as expected in layered chart

### ISSUE THREAD

**Issue by aauss** [altair-viz/altair#2347]
Hi!

I have the following problem. I have two dataframes `box-df` and `point_df` that contain two different observations ("A" and "B") by which I want to filter using a drop down menu. The first plot I create should be plotted like a chloropleth map and is colored by the values for each observation (plot is called `box`). Additional to coloring the boxes, I want to display the value of this observation as text into the box (plot is called `text`). My second dataframe contains dots that too can be filtered for "A" and "B" but show categorical data by which they should be colored (plot is called `points`). However, the drop down menu implemented does not work as expected and will show all points all the time. Is this a bug or did I do a mistake?

I am using Python 3.7, geopands=0.8, altair=4.1.0, and Jupyterlab=2.0.1 on Firefox.

Thank you very much for your help!!

```python 
import altair as alt
import geopandas as gpd
from shapely.geometry import Polygon

c = [(0, 0), (0, 1.5), (1, 1.5), (1, 0), (0, 0)]
d = [(1, 0.5), (1, 2), (2, 2), (2, 0.5), (1, 0.5)]

box_df = gpd.GeoDataFrame(
    {
        "geometry": [Polygon(c), Polygon(d), Polygon(c), Polygon(d)],
        "variable": ["A", "A", "B", "B"],
        "value": [1, 2, 200, 100,],
    }
).assign(lon=lambda x: x.geometry.centroid.x, lat=lambda x: x.geometry.centroid.y)

point_df = gpd.GeoDataFrame(
    {
        "lat": [0.5, 1.1, 1.3,],
        "lon": [0.5, 1.1, 1.3],
        "variable": ["A", "B", "B"],
        "value2": ["y", "x", "x"],
    }
)

input_dropdown = alt.binding_select(options=["A", "B"])
selection = alt.selection_single(
    fields=["variable"], bind=input_dropdown, init={"variable": "A"},
)
boxes = alt.Chart(box_df).mark_geoshape().encode(color="value",)

text = (
    alt.Chart(box_df)
    .mark_text()
    .encode(latitude="lat", longitude="lon", text="value",)
)

points = (
    alt.Chart(point_df)
    .mark_circle(size=100)
    .encode(latitude="lat", longitude="lon", color="value2")
)

(boxes + text + points).add_selection(selection).transform_filter(selection)
```

**Comment by jakevdp** [comment]
Selections cannot filter across separate datasets. You'll have to join your data with a [Lookup transform](https://altair-viz.github.io/user_guide/transform/lookup.html)

**Comment by aauss** [comment]
Hey Jake! Thank you very much for your answer. I wasn't aware of this. So lookup transform basically performs a left join. In my case this inflates the dataframe a lot since I have many of points I want to display over the chloropleth map. This leads to many entries of my dataframe repeating large polygons which makes my computer howl. Is there by any chance another approach that is more efficient?
