### ISSUE TITLE
Highlight area similar to axvspan in matplotlib

### ISSUE THREAD

**Issue by krlng** [altair-viz/altair#2348]
Is there a way to highlight areas between two coordinates along one axis similar, as an matplotlib using [axvspan](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.pyplot.axvspan.html)?

What would be the best way, to achieve something similar?

**Comment by krlng** [comment]
The best I came up till now is using mark_rule in one of two ways, which both do not solve my problem:

1. Place a rule in the middle of the wanted highlight-area and adjust the size in a way, that it is wide enough ([inspiration](https://altair-viz.github.io/gallery/histogram_with_a_global_mean_overlay.html?highlight=mark_rule)):

```
rule = base.mark_rule(color='red').encode(
    x='mean(IMDB_Rating):Q',
    size=alt.value(5)
)
```

**Problem**: In my case the X Axis is of temporal data and `size='max(X)-min(X)` does not work.

2. What axvspan basically does is take two coordinates (x1, x2) and highlight everything between. So I tried:

```
rule = base.mark_rule().encode(
    x='min(x):T',
    x2='max(x):T'
)
```

**Problem:** The wanted time-range is marked correctly, but only with a minimal ruler (line) instead of big area as I want to.

**Comment by jakevdp** [comment]
The best way to achieve this is probably by using a `mark_rect()` with the y limits defined via values. For example:
```python
import altair as alt
import pandas as pd

data = pd.DataFrame({
    'x': np.random.randn(100),
    'y': np.random.randn(100)
})

rect = pd.DataFrame({
    'x1': [0],
    'x2': [1]
})

points = alt.Chart(data).mark_point().encode(x='x', y='y')
span = alt.Chart(rect).mark_rect(
    opacity=0.3
).encode(
    x='x1',
    x2='x2',
    y=alt.value(0),  # 0 pixels from top
    y2=alt.value(300)  # 300 pixels from top
)

(points + span).interactive()
```
![visualization - 2020-11-28T071952 041](https://user-images.githubusercontent.com/781659/100519018-1d121f80-314a-11eb-8fdb-6d87e4c1e223.png)

**Comment by krlng** [comment]
Okay, that actually looks not to bad, thanks @jakevdp . In my case, I also use scale on the X-Axis, which took me some more tries to make it work together. Problem was, that X2 does not accept a scale, how ever, if scale gets applied to X, it seems to automatically work for X2 as well. Will close the issue.
```

import altair as alt
from vega_datasets import data

chart = alt.Chart(data.stocks()).properties(width=850)

line = chart.mark_line().encode(
    y='price',
    color='symbol'
)

rule = chart.mark_area(opacity=0.4).encode(
    y="average(price)",
)

span = chart.mark_rect(
    opacity=0.3
).encode(
    y=alt.value(0),  # 0 pixels from top
    y2=alt.value(300),
    color='symbol'
)

base = (line + rule)
brush = alt.selection(type='interval', encodings=['x'])

upper = base.encode( alt.X('date:T', scale=alt.Scale(domain=brush)))+  span.encode( x=alt.X('min(date):T', scale=alt.Scale(domain=brush)), x2=alt.X2('average(date):T'))

lower = base.encode(x='date').properties(
    height=60
).add_selection(brush)

upper & lower
```

**Comment by jakevdp** [comment]
Yes, X2 always shares the same scale as X.
