### ISSUE TITLE
Layered chart does not accept encoding

### ISSUE THREAD

**Issue by krlng** [altair-viz/altair#2349]
The following Chart should behave similar to [Interval Selection Example](https://altair-viz.github.io/gallery/interval_selection.html)
```
import altair as alt
from vega_datasets import data

source = data.stocks()

base = alt.Chart(source).properties(width=850)

line = base.mark_line().encode(
    alt.X('date:T', scale=alt.Scale(domain=brush)),
    y='price',
    color='symbol'
)

rule = base.mark_area(opacity=0.4).encode(
    x='date',
    y="average(price)",
)

brush = alt.selection(type='interval', encodings=['x'])
brush_encoding_x = alt.X('date:T', scale=alt.Scale(domain=brush))

upper = (line + rule).encode( brush_encoding_x )

lower = (line + rule).properties(
    height=60
).add_selection(brush)

upper & lower
```

How ever, the layered Chart `upper` seems to ignore the new encoding.

A simple work around is to apply the `brush_encoding_x` to the single charts before creating the layered one:

```
upper = (line.encode( brush_encoding_x )
         +rule.encode( brush_encoding_x )) 
```

How ever, this becomes messy if the layered chart gets more complicated.

**Comment by jakevdp** [comment]
When you apply an encoding to a layered chart, it applies to each layer **unless** that layer overrides the encoding. In your case, both layers override the x encoding, and so the encoding on the layer chart has no effect.

Instead, you might do something like this:
```python
line = base.mark_line().encode(
    y='price',
    color='symbol'
)

rule = base.mark_area(opacity=0.4).encode(
    y="average(price)",
)

brush = alt.selection(type='interval', encodings=['x'])
brush_encoding_x = alt.X('date:T', scale=alt.Scale(domain=brush))

upper = (line + rule).encode( brush_encoding_x )
lower = (line + rule).encode(x='date').properties(
    height=60
).add_selection(brush)

upper & lower
```

**Comment by krlng** [comment]
Thank you very much, that explains it. 

I thought I tried it and got an error about x being required when first defining the chart, but probably I just missed it somewhere.
