### ISSUE TITLE
Change the Github repo URL listed in the Altair pypi docs

### ISSUE THREAD

**Issue by dannguyen** [altair-viz/altair#235]
Still lists what I assume is the old fork:

https://pypi.python.org/pypi/altair/1.0.0

![image](https://cloud.githubusercontent.com/assets/121520/19446531/1f18d6f4-944e-11e6-9db5-2230f00af2a2.png)

**Comment by jakevdp** [comment]
Thanks!

That's already fixed in master. Getting it on PyPI requires a new release of the package (one somewhat annoying feature of the system), which we should be doing relatively soon.

**Comment by dannguyen** [comment]
Oops, sorry for not checking. Thanks for this, I hadn't heard about it until seeing it on [HN today](https://news.ycombinator.com/item?id=12722465) but looks like an extremely valuable addition to Python's data libraries
