### ISSUE TITLE
Share scales/axes only across rows/columns of faceted charts

### ISSUE THREAD

**Issue by RoyalTS** [altair-viz/altair#2350]
I would love it if I could share scales and axes only between the rows or between the columns of a faceted chart instead of having them all be `shared` or `independent`.

`ggplot2`, for example, allows the `scales` argument to [facet_grid](https://ggplot2.tidyverse.org/reference/facet_grid.html), for example, to be either `free` or `fixed` but also `free_x` and `free_y`.

**Comment by jakevdp** [comment]
I don't think this is supported by Vega-Lite.

**Comment by RoyalTS** [comment]
This is related to https://github.com/vega/vega-lite/issues/2761?

**Comment by joelostblom** [comment]
I filed https://github.com/vega/vega-lite/issues/8064 for this in the VL repo a while ago. Please follow that for updates. I am closing this since there is nothing that can be done on the Altair side of things to support this feature.
