### ISSUE TITLE
mark_image: size limit on images?

### ISSUE THREAD

**Issue by robna** [altair-viz/altair#2351]
I am trying to get the mark_image working with my images. So far I have found images that are displayed and others that are not. Could this have something to do with image size? Is there a limit?

Here is a simple example that works (just a simplified version of what is in the altair documentation):
```python
import altair as alt
import pandas as pd

source = pd.DataFrame.from_records([
      {"img": "https://vega.github.io/vega-datasets/data/gimp.png"}
])

alt.Chart(source).mark_image(
    width=100,
    height=100
).encode(
    url='img'
)
```

But for these image urls the same code does not work (random ones I tried from the web):

https://simpleicon.com/wp-content/uploads/rocket.png

https://www.fei.com/uploadedImages/FEISite/Pages/Markets/Life_Sciences/Structural_Biology/Sub-Cellular_Imaging/Sriram_001_465x.png

http://man.hubwiz.com/docset/altair.docset/Contents/Resources/Documents/_static/altair-logo-light.png

**Comment by jakevdp** [comment]
It's not a question of image size, it's a question of HTTP access permissions defined by the host sites. If you look in the console log for the first URL, for example, you find this (when run on Google Colab):
```
Access to image at 'https://simpleicon.com/wp-content/uploads/rocket.png' from origin 'https://ot7bspmih9i-496ff2e9c6d22116-0-colab.googleusercontent.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by joelostblom** [comment]
@robna I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to close this issue or add a comment if there is something you don't think is resolved yet?

**Comment by robna** [comment]
I think this can be closed. Jake's answer explains what was the problem here.
