### ISSUE TITLE
One-sided axis domains

### ISSUE THREAD

**Issue by RoyalTS** [altair-viz/altair#2352]
It would be great if one could restrict the domain of an axis on one side only, e.g.

```
alt.Scale(domain=[200, None])
```

which would show all values above 200. Alas, the `None` above currently seems to be interpreted as `0` instead.

**Comment by joelostblom** [comment]
@RoyalTS has been added in a recent version of Vega and is being tracked in https://github.com/altair-viz/altair/issues/2140#issuecomment-669634198 in Altair. Do you mind closing this issue as a duplicate of #2140?

**Comment by RoyalTS** [comment]
dupe of #2140
