### ISSUE TITLE
Allow Paths in save()

### ISSUE THREAD

**Issue by RoyalTS** [altair-viz/altair#2354]
Instead of allowing only string paths or file-likes, allow pathlib.Paths to be passed to `save()`.

Are these two the only places that would have to be changed?

https://github.com/altair-viz/altair/blob/54e03d403c1cec9ce2f2e8b14dc3d936c6686128/altair/utils/save.py#L8
https://github.com/altair-viz/altair/blob/54e03d403c1cec9ce2f2e8b14dc3d936c6686128/altair/utils/save.py#L72

**Comment by jakevdp** [comment]
I think these are the correct places to make the change. Additionally, I think similar changes would be required in [altair_saver](https://github.com/altair-viz/altair_saver), which altair delegates to for png & pdf saves.

**Comment by RoyalTS** [comment]
In that case, let me try to take a crack at this!
