### ISSUE TITLE
natural log

### ISSUE THREAD

**Issue by katiemharding** [altair-viz/altair#2356]
How do you plot with a natural log axis?   Is there a better way than just giving a numeric value for e?
```python
source = data.cars()

alt.Chart(source).mark_point().encode(
    alt.X('Horsepower',scale=alt.Scale(type='log', base=2.718281828459)),
    y='Miles_per_Gallon',
    color='Origin'
)
```

**Comment by jakevdp** [comment]
That's currently the only way to do it.

Recent Vega-Lite releases allow `base` to be passed a vega expression, so in the future you'll be able to do `base=alt.expr.E`, but that doesn't yet work in the current Altair release.

**Comment by RoyalTS** [comment]
Might be worth adding `ln` as a shorthand, this being a pretty common use case.

**Comment by jakevdp** [comment]
That would have to be added to Vega-Lite; Altair doesn't have any control over what keywords or values are available in the chart specification. You could open a feature request there.

**Comment by joelostblom** [comment]
Closing as there is nothing to do on the Altair side of things here
