### ISSUE TITLE
Export data after transformation

### ISSUE THREAD

**Issue by krlng** [altair-viz/altair#2357]
I am trying to debug some charts that use [Transformations](https://altair-viz.github.io/user_guide/transform/index.html). For this purpose, it would be really helpful get the transformed data after the transformation have been applied. Is there some internal function to extract the data without plotting?

**Comment by jakevdp** [comment]
You can do this with the [altair_transform](https://github.com/altair-viz/altair-transform) package.

**Comment by krlng** [comment]
This is just perfect. Checking out the github repo I also discovered https://github.com/altair-viz/altair_pandas. Maybe those projects should be linked in the https://altair-viz.github.io/user_guide/ecosystem.html page instead of the old, archived packages which are linked there.
