### ISSUE TITLE
shared X axis for different datasets of different length

### ISSUE THREAD

**Issue by jschaef** [altair-viz/altair#2358]
Hi,

could somebody please give an advice how to contruct a shared x axis for datasets of different length.
dataset 1 has x values from 0 - 12 PM,  dataset 2 has x values from 0 - 6 PM.
The goal is to share the x axis and show both graphs. I used a layered chart but the outcome looks very uggly.
The labels of the dataset with more x values are packed together as can be seen in the picture.

Thanks

![visualization](https://user-images.githubusercontent.com/5850423/100753485-20c3d180-33ea-11eb-9e7b-c6da180976bd.png)

**Comment by jakevdp** [comment]
See https://altair-viz.github.io/user_guide/scale_resolve.html

**Comment by jschaef** [comment]
Hi Jake,
thanks for your fast reply. I'm not sure which example on the URL exactly you are referencing. I understand that I can solve it somehow by using scale_resolve but it is not clear for me how to do that. I don't want a second independent x-axis.
I tried most of the resolve_scale proberties but without success.
Here the code:

alt.layer(
            title=title,
        ).resolve_scale(
            size="shared",
            stroke="shared"
            fill = "shared",
            y="shared",
            x="shared").configure_axisX(domainColor='black')
...
I assume I need to fill the missing values in datafraem 2 with null or nan values?    

thx

**Comment by jakevdp** [comment]
`"shared"` is the default, so there's no need to specify that manually.

From your question, I thought what you wanted were independent scales for the x encodings, but it sounds like I misunderstood. Can you describe how you want your chart to look?

**Comment by jschaef** [comment]
If you look at the right edge of the x axis you see after 20:00 the legend is ugly somehow the numbers are stucked over. 
I want that the chart ending at 6 PM ends at 6 PM but the other chart continues until 11 PM with the same x axis scale.

thx

**Comment by jakevdp** [comment]
So you want a second chart concatenated to the right side, rather than having both lines in the same chart?

**Comment by jakevdp** [comment]
I also find this confusing because you talk about data ending at 6pm and 11pm, but I don't see any data ending at 6pm or 11pm.

**Comment by jschaef** [comment]
Hi Jake,
I'm wondering how to get rid of the uggly stucked legend on the right corner of the x axis (have a look at the pictue above).
I tried several things but couldn't solve it. In my app I have two sar files. One has collected data until 2PM (reboot hereafter) and the other has data for the whole day. So the x axis should display all 24 hours even if I have less data for the first graph. 
I'm not sure if this is possible with altair or if I need to fill the first data frame with null/nan values starting at 2PM. But this would probably pretent a wrong impression such as if the measured value has gone down to zero instead the graph ends at 2PM.

thanks a lot for your help

**Comment by jschaef** [comment]
Hi Jake,
sorry for the confusion I thought to explain it more abstract but probably reached the opposite. 
Displaying both graphs concatenated (one right, one left) is not the goal and would be easy to accomplish.

The orange graph ends at about 20:00 and the blue one ends 24:00. The last 4 hours have been compressed on the picture  such the legend shows 21:00 - 24:00 tight stacked together instead using the same tick distance as for the range 0 - 20:00. I would like to have the last 3 major ticks on the x axis with the same unit/distance (uncompressed) as the rest of the x axis. 

graph 1:
-+-+-+-+-+-+-++-
graph:2
°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°°

x-axis good:
---|---|---|---|---|---|---|---|---|---|

x-axis bad:
---|---|---|---|---|----|-|-|-|

**Comment by jakevdp** [comment]
OK, I see. Without seeing your code it's hard to answer the question, but this probably comes down to the encoding type you are using on the x-axis. I suspect you are using an ordinal encoding (i.e. ordered categories) and you should be using a temporal encoding to get a regular axis grid across data with different frequencies of measurement.

**Comment by jschaef** [comment]
Hi Jake,
thanks a lot. That gives me the hint into the right direction. At the moment I'm using a nominal ordering. I converted time values into strings to display h:m:s: only. But I probably need to use the correct date objects in pandas and use the temporal encoding. 

Many thanks I think this will do the trick

**Comment by jakevdp** [comment]
Great! Sorry it took so much back and forth for me to understand your question! :grin:

**Comment by jschaef** [comment]
Hi Jake,
it does the trick :-). Thanks a lot
![visualization (1)](https://user-images.githubusercontent.com/5850423/101071319-bbfca880-359c-11eb-8cd6-d1a4a7344949.png)
