### ISSUE TITLE
Getting current selection

### ISSUE THREAD

**Issue by PaVim96** [altair-viz/altair#2359]
Currently I'm trying to make an interactive plot based off of a selector. 
But I need to get the current selection of the selector, for example if the selector has the options [3,4], I'd like to use the current selection (for example 4) in order to use that to filter a column of a DataFrame, also named "Categories". Is this possible? 

My idea was something like this: 
```
input_dropdown = alt.binding_select(options=[3,4]) 
selection = alt.selection_single(fields=['Categories'], bind=input_dropdown)
heatmap = base.mark_rect().encode(
    color= myColor
).add_selection(
    selection
).transform_filter(
    (datum.Categories & selection) > 0
)
```
Thanks in advance!

**Comment by jakevdp** [comment]
There is not currently any way to do this. The selection exists in the javascript frontend and Altair doesn't provide any mechanism to pass that data back to the Python kernel.

**Comment by jakevdp** [comment]
If you're interested in this kind of two-way communication between frontend and backend, you might try tools like Bokeh or Plotly.

**Comment by jakevdp** [comment]
It sounds like you want something similar to the example here: https://altair-viz.github.io/user_guide/interactions.html#selection-values-in-expressions

Does that answer your question?

**Comment by PaVim96** [comment]
Hey Jake, thanks for your very fast reply! 
I tried out the referenced code, and getting the selected value seems to work. What seems to be wrong is getting the "Categories" column of the "base" DataFrame from the Heatmap. When I apply the filter above, about half of the categories should be filtered on a selection, but instead nothing is filtered showing the whole graph.

This is probably just an error on my side, I'll try to see if that is the case.
