### ISSUE TITLE
kde (transform_density + mark_area + facet) does not show data if next to other chart

### ISSUE THREAD

**Issue by krlng** [altair-viz/altair#2360]
I try to plot a [kde plot](https://altair-viz.github.io/gallery/ridgeline_plot.html) next to a simple bar chart. Both charts work on their own, but if plotted next to each other, the area plot shows no more data:
![visualization](https://user-images.githubusercontent.com/1107509/100857824-71d8d180-348d-11eb-96ef-a4d76f512238.png)

Example code:

```
import altair as alt
import pandas as pd 

df = pd.DataFrame({'params_n_estimators_': {0: 262, 1: 87, 2: 1000, 3: 201, 4: 256, 5: 191, 6: 144, 7: 151, 8: 81, 9: 520},
 'set': {0: 'lr_3', 1: 'lr_4', 2: 'lr4_md20', 3: 'lr_3', 4: 'lr_4', 5: 'lr_4', 6: 'lr4_md20', 7: 'lr_4', 8: 'lr4_md20', 9: 'lr_4'}})

n_est_dist = alt.Chart(df, height=40, width=300).transform_density(
    density='params_n_estimators_',
    groupby=['set'],
).mark_area().encode(
    alt.X('value:Q'),
    alt.Y( 'density:Q' )
).facet(
    row=alt.Row(
        'set:N'
    )
)

bar2 =  alt.Chart(df, width=300).mark_bar().encode(y="set:N",x="average(params_n_estimators_)")

(n_est_dist | bar2 )
```

**Comment by ChiaLingWeng** [comment]
Issue solved for me in altair version 5.1.2
![image](https://github.com/altair-viz/altair/assets/75072960/aa8fdfcf-cb60-4018-b3d0-01b627c37280)
