### ISSUE TITLE
Select based off of filtered Column

### ISSUE THREAD

**Issue by PaVim96** [altair-viz/altair#2361]
Hello, for my interactive visualization I need to have a selection that acts on a column 'Categories'. The problem is that the cells of 'Categories' are made up of several Values, ranging from 1-10. For example one of the cells could be 1,5,7. Now I'd like to have a selector with the Options 1-10. The selector would then somehow need to see if in any cell of the column "Categories" contains the selected option and then only show those matched cells. Is this type of complex selection possible in altair?

My idea was something like this, but I don't know how to get the Value of Categories and use it as a string to do matching:
```
base = alt.Chart(heatmapDF).encode(
    alt.X('Game:O', scale=alt.Scale(paddingInner=0)),
    alt.Y('Algorithm:O', scale=alt.Scale(paddingInner=0)),
).add_selection(
    selection
).transform_calculate(
    categories = 1 if (selection in str(datum.Categories)) else 0
).transform_filter(
    'datum.categories == 1'
)
```

**Comment by jakevdp** [comment]
Can you provide a small reproducible example (including the data)?

**Comment by PaVim96** [comment]
Hey Jake, yes here's the example I have:

```
import pandas as pd
import altair as alt 
from altair import datum
import numpy as np
from vega_datasets import data


def makeUniqueCategories(categoriesGames):
    categories = list() 
    categoriesGames = categoriesGames.to_numpy() 
    for categoriesString in categoriesGames:
        categoriesString = categoriesString.replace(" ", "")
        listOfCategories = categoriesString.split(",")
        for category in listOfCategories:
            if len(categories) == 0:
                categories.append(category)
            else:
                if not (category in categories):
                    categories.append(category)
    return categories

heatmapDF = pd.read_csv("HeatmapReducedHard.csv")
uniqueCategories = makeUniqueCategories(heatmapDF['Categories'])

#make selection out of binding
input_dropdown = alt.binding_select(options=uniqueCategories, name="Game Category: ")
selection = alt.selection_single(fields=['Categories'], bind=input_dropdown)

base = alt.Chart(heatmapDF).encode(
    alt.X('Game:O', scale=alt.Scale(paddingInner=0)),
    alt.Y('Algorithm:O', scale=alt.Scale(paddingInner=0)),
).add_selection(
    selection
).transform_filter(
    selection
)

#make scale for coloring 
myScale = alt.Scale(domain=[0, 0.25, 0.5, 0.75, 0.985, 1.0], range=['darkred', 'orange', 'white', 'darkgreen', 'green', 'green'], type='linear')
myColor = alt.Color('Performance:Q', scale=myScale)

heatmap = base.mark_rect().encode(
    color= myColor
)


heatmap
```

Unfortunately I can't attach a csv file, so I can only attach the .txt file: 

[HeatmapReducedHard.txt](https://github.com/altair-viz/altair/files/5642584/HeatmapReducedHard.txt)

**Comment by jakevdp** [comment]
Can you provide an example that doesn't require downloading a file?

For these kinds of questions, the full problem you're working on is often less helpful than a small, representative example with explicitly constructed data.

**Comment by PaVim96** [comment]
Hey Jake, sorry for the late reply:
Of course, I'll provide an example without downloadable files. Sorry for that! 
```
import pandas as pd
import altair as alt 
from altair import datum
import numpy as np
from vega_datasets import data


game = pd.DataFrame(["A", "B", "C", "A", "B", "C", "A", "B", "C"], columns=["Game"])
algo = pd.DataFrame(["AlgA", "AlgA", "AlgA", "AlgB", "AlgB", "AlgB", "AlgC", "AlgC", "AlgC"], columns=["Algorithm"])
performance = pd.DataFrame([0, 0.5, 1, 0.5, 1.0, 0, 1.0, 0, 0.5], columns=["Performance"])
categories = pd.DataFrame(["Any, CatA", "Any, CatA, CatB", "Any, CatC","Any, CatA", "Any, CatA, CatB", "Any, CatC", "Any, CatA", "Any, CatA, CatB", "Any, CatC"], columns=["Categories"])
heatmapDF = pd.concat([game,algo,performance, categories], axis=1)

#make selection out of binding
input_dropdown = alt.binding_select(options=["Any", "CatA", "CatB", "CatC"], name="Game Category: ")
selection = alt.selection_single(fields=['Category'], bind=input_dropdown)

base = alt.Chart(heatmapDF).encode(
    alt.X('Game:O', scale=alt.Scale(paddingInner=0)),
    alt.Y('Algorithm:O', scale=alt.Scale(paddingInner=0)),
).add_selection(
    selection
).transform_filter(
    selection
)

#make scale for coloring 
myScale = alt.Scale(domain=[0, 0.25, 0.5, 0.75, 0.985, 1.0], range=['darkred', 'orange', 'white', 'darkgreen', 'green', 'green'], type='linear')
myColor = alt.Color('Performance:Q', scale=myScale)

heatmap = base.mark_rect().encode(
    color= myColor
)
heatmap
```

As you can see, as soon as one starts to pick a selection, nothing is displayed anymore.
Thanks in advance again!

**Comment by jakevdp** [comment]
The issue is that you're filtering on values that don't exist in your data. So when you choose, e.g. `"CatA"`, the filter statement removes all values with category not equal to `"CatA"`. Because none of the values in your dataset have an entry equal to that value, none are shown. Does that make sense?

**Comment by PaVim96** [comment]
Yes that makes sense. But I was wondering whether there is any possibility to still do the filtering/selection. Suppose that one categories cell has the entry "Any, CatA" and the selection is currently "CatA". If the selection would be able to first filter values of the cells for the selection value "CatA" and then do the filtering, it should work. And I don't know if this kind of "pattern-matching" before selection is possible in Altair. I can't really prevent the multiple values in a cell for my filtering, that's why I'm asking.

I hope I'm clear what I mean with this.

**Comment by jakevdp** [comment]
You could probably do this using a filter based on a [Vega expression](https://vega.github.io/vega/docs/expressions/); I'll try to put together an example later today when I have some time

**Comment by PaVim96** [comment]
Thanks a lot for your answers and dedication! Really appreciate it

**Comment by jakevdp** [comment]
Here's an example of how you can do this kind of filtering with filter expressions. Notice I've modified the input data to remove "Any" (which is now handled within the filter) and to remove spaces between the items:
```python
import pandas as pd
import altair as alt 
from altair import datum
import numpy as np
from vega_datasets import data


game = pd.DataFrame(["A", "B", "C", "A", "B", "C", "A", "B", "C"], columns=["Game"])
algo = pd.DataFrame(["AlgA", "AlgA", "AlgA", "AlgB", "AlgB", "AlgB", "AlgC", "AlgC", "AlgC"], columns=["Algorithm"])
performance = pd.DataFrame([0, 0.5, 1, 0.5, 1.0, 0, 1.0, 0, 0.5], columns=["Performance"])
categories = pd.DataFrame(["CatA", "CatA,CatB", "CatC","CatA", "CatA,CatB", "CatC", "CatA", "CatA,CatB", "CatC"], columns=["Categories"])
heatmapDF = pd.concat([game,algo,performance, categories], axis=1)

#make selection out of binding
input_dropdown = alt.binding_select(options=["Any", "CatA", "CatB", "CatC"], name="Game Category: ")
selection = alt.selection_single(fields=['Category'], bind=input_dropdown, name="selector", init={"Category": "Any"})

alt.Chart(heatmapDF).mark_rect().encode(
    alt.X('Game:O', scale=alt.Scale(paddingInner=0)),
    alt.Y('Algorithm:O', scale=alt.Scale(paddingInner=0)),
    alt.Color('Performance:Q',
              scale=alt.Scale(domain=[0, 0.25, 0.5, 0.75, 0.985, 1.0],
                              range=['darkred', 'orange', 'white', 'darkgreen', 'green', 'green'], type='linear'))
).add_selection(
    selection
).transform_filter(
    "selector.Category[0] == 'Any' || indexof(split(datum.Categories, ','), selector.Category[0]) >= 0"
)
```

**Comment by PaVim96** [comment]
Wow thanks! I've stumbled upon the Vega-Expressions before, but I just couldn't make it happen. I'll try this out with my example, but looks very promising!
