### ISSUE TITLE
How to set horizontal/vertical brick gap in heatmap?

### ISSUE THREAD

**Issue by t-bzhan** [altair-viz/altair#2363]
I am looking for a way to set the horizontal/vertical brick gap for heatmap, just like the "xgap", "ygap" heatmap properties in [Plotly](https://plotly.github.io/plotly.py-docs/generated/plotly.graph_objects.Heatmap.html).

Currently below code snippet:
```
import pandas as pd
import altair as alt
example_data = pd.DataFrame(
    {
        'fruits':['apple', 'banana', 'orange', 'apple', 'banana', 'orange', 'apple', 'banana', 'orange'],
        'location':['Location-1', 'Location-2', 'Location-3', 'Location-2', 'Location-3', 'Location-1', 'Location-3', 'Location-1', 'Location-2'], 
        'quality': ['good', 'bad', 'good', 'bad', 'good', 'bad', 'good', 'bad', 'good']
    }
)
heatmap = alt.vconcat(
    alt.Chart(example_data).mark_rect().encode(
        x = alt.X('fruits:N'),
        y = alt.Y('location:N', title=None), ########
        color = alt.Color('quality:N'),
    ).properties(width=400, height=400)
)

heatmap.configure_concat(spacing=0).configure_view(strokeOpacity=0)
```
will produce a heatmap with very small brick gap and I could not find a way to customize it:
![image](https://user-images.githubusercontent.com/61817681/101139025-e6f20580-364b-11eb-9f23-2b3e8293baa1.png)

It makes it hard to distinguish adjacent cells with the same color property where we have a lot of cells. 
![image](https://user-images.githubusercontent.com/61817681/101139631-caa29880-364c-11eb-88ac-7cd43ab593bc.png)

The desired output is something like below:
![image](https://user-images.githubusercontent.com/61817681/101139509-9c24bd80-364c-11eb-99fd-2332c75e375a.png)

My altair version: 4.1.0

Thanks in advance for any suggestions.

**Comment by jakevdp** [comment]
You can set this using the `bandPaddingInner` configuration, which is a number between 0 and 1:
```python
alt.Chart(example_data).mark_rect().encode(
    x = alt.X('fruits:N'),
    y = alt.Y('location:N', title=None),
    color = alt.Color('quality:N'),
).properties(
    width=400, height=400
).configure_scale(bandPaddingInner=0.05)
```
![visualization - 2020-12-04T055224 949](https://user-images.githubusercontent.com/781659/101171631-e4b08c80-35f4-11eb-865d-7ee8295fd20a.png)

**Comment by t-bzhan** [comment]
@jakevdp Thanks so much!
