### ISSUE TITLE
selection_interval does not work with fields

### ISSUE THREAD

**Issue by krlng** [altair-viz/altair#2365]
The selection_interval seems to work neither with fields nor with encodings which are not numeric. Is this a bug or is there simply no support?

Example code:

```
import altair as alt
from vega_datasets import data as vdata

cars = vdata.cars.url

brush = alt.selection_interval(fields=['Name'])

alt.Chart(cars).mark_point().encode(
    x='Miles_per_Gallon:Q',
    y='Horsepower:Q',
    color='Origin:N',
    tooltip=["Name:N"]
).add_selection(
    brush
)
```

**error message:** Expression parse error: ? selector072_scale_trigger : {}

The same happens if I use `brush = alt.selection_interval(encodings=['color'])`

**Comment by jakevdp** [comment]
This is expected: in Vega-Lite, interval selections only work with x and y encodings, not with fields.

**Comment by krlng** [comment]
Okay, kind of sad because that would have been really cool, but well..
