### ISSUE TITLE
Selector interactivity map and bar chart & combining year selectors

### ISSUE THREAD

**Issue by sammyhajomar** [altair-viz/altair#2367]
1) I have a map with lat, long coordinates plotted for forest fires and a bar chart breakdown by state. I wan to be able to select a state (one of bars) on the bar chart and have it select only those points on the map. I'm getting a JSON error every time looking for a "missing selector".

2) Also the other thing I would like to know if it's possible to combine the year selector to have one slider control both charts
------------------------------
```
slider = alt.binding_range(min=1980, max=2016, step=1, name='Year')
select_year = alt.selection_single(name="SelectorName", fields=['YEAR'], bind=slider, init={'YEAR': 2000})

single = alt.selection_single(empty='all', fields=['CAUSE'])


## Map ##
background = alt.Chart(states).mark_geoshape(
    fill='lightgray',
    stroke='white'
).project(
   'albersUsa'
)
points = alt.Chart(df).mark_circle(  
	).encode(
          longitude='DLONGITUDE:Q',
          latitude='DLATITUDE:Q',
    	  color='CAUSE'
    ).add_selection(
    	select_year
    ).transform_filter(
    	select_year
    ).transform_filter(
    	single
)

## Bar Chart ##
chart = alt.Chart(df).mark_bar().encode(
 	alt.X('STATE',title='State', sort='-y'),
 	alt.Y('sum(TOTALACRES):Q',title='Acres Burned', axis=alt.Axis(format=',.4r')),
 	color=alt.condition(single,'CAUSE:N',alt.value('lightgray')),
 	tooltip=[alt.Tooltip("CAUSE",title='Cause'), alt.Tooltip('mean(TOTALACRES)',title='Acres Burned', format=",.4r")]
    ).add_selection(
    	select_year
    ).transform_filter(
    	select_year
    ).add_selection(
    	single
)
```

**Comment by joelostblom** [comment]
@sammyhajomar Here is an example for how to select on a map and another chart for the first part of your question https://stackoverflow.com/a/65948144/2166823. To have a single selector control two charts, you can add it via `add_selection` to both charts.

**Comment by joelostblom** [comment]
Closing for now, please reopen if there is anything that wasn't resolved in the linked solution I provided.
