### ISSUE TITLE
Concatenation disables tooltips / forces filtering

### ISSUE THREAD

**Issue by lbittarello** [altair-viz/altair#2368]
Sorry if the issue has already been raised elsewhere.

I've been running into trouble with concatenated charts. There are two issues, perhaps best explained by example.

Consider a simple bar chart:
```python
import altair as alt
import pandas as pd

source = pd.DataFrame(
    {
        "a": ["a", "b"],
        "b": [1, 2],
    }
)

bar_chart = (
    alt.Chart(source)
    .mark_bar()
    .encode(x="a", y="b", tooltip=["a"])
)
```
This chart works correctly and display the tooltip.

Now let's concatenate it with an unrelated chart (inspired by [this section of the documentation](https://altair-viz.github.io/user_guide/interactions.html#selection-targets-fields-and-encodings)):
```python
x_selection = alt.selection_multi(fields=["a"])
x_color = alt.condition(x_selection, alt.value("black"), alt.value("lightgray"))
select_x = alt.Chart(source).mark_point().encode(y="a", color=x_color).add_selection(x_selection)

joint_chart = bar_chart | select_x 
```
The bar chart in `joint_chart` doesn't display the tooltip anymore. The selection chart works correctly: if one clicks on `"a"`, `"b"` goes gray.

Now let's add a filter to the bar chart:
```python
joint_chart = bar_chart.transform_filter(x_selection) | select_x 
```
The bar chart still doesn't show the tooltip, but the filter works correctly and the selection chart is still fine.

Now let's pretend to concatenate the bar chart:
```python
joint_chart = alt.hconcat(bar_chart).transform_filter(x_selection) | select_x 
```
The selection chart doesn't work correctly anymore: instead of changing colors, clicking on `"a"`  hides `"b"` completely.

Not sure what's going on or if there's an easy fix. Any insight appreciated. :)

**Comment by jakevdp** [comment]
Looks like a Vega-Lite issue, maybe related to this: https://github.com/vega/vega-lite/issues/6773

**Comment by lbittarello** [comment]
As mentioned [here](https://github.com/vega/vega-lite/issues/5732#issuecomment-653387748), adding some interactivity to the bar chart restores the tooltip (e.g., `.interactive` or `.add_selection(alt.selection_interval(bind="scales"))`). Also, the selection chart works fine in the last example if one moves the filter inside the concatenation:
```python
alt.hconcat(bar_chart.transform_filter(x_selection)) | select_x 
```
This approach extends to multiple plots: just add the selection to each separate chart instead of their concatenation.

**Comment by joelostblom** [comment]
The provided example is working as expected for me on Altair 4.2.0 so I'm closing this, please re-open if you are still seeing the issue.
