### ISSUE TITLE
Limit the nominal x axis

### ISSUE THREAD

**Issue by PeihanDou** [altair-viz/altair#2370]
Hello there! Thanks for the great work! I am trying to draw a bar chart with nominal x axis. there are 100 different ids. I was wondering is there a way that only show 30 records? Thanks!
```
bars2 = alt.Chart(nodes.data).mark_bar().encode(
    y=alt.Y('undecided_nb', scale=alt.Scale(domain=(0,20))),
    x=alt.X('id:N', sort = sort_field),
    color = alt.value('gray')
)
```
That gives:

![image](https://user-images.githubusercontent.com/55855936/101803168-3ae26b80-3ade-11eb-9cf2-e925cd8a5815.png)

The x axis is too much long. By default it show all 100 records. Is there a way to show 30 records only? Could we adjust this number? Thanks for any advice!

**Comment by jakevdp** [comment]
You can do this via a rank & filter transform. There is a relevant example here: https://altair-viz.github.io/gallery/top_k_items.html

**Comment by PeihanDou** [comment]
Thank you! Thay make sense!
