### ISSUE TITLE
Selection Histogram Oriented Vertically

### ISSUE THREAD

**Issue by Murtz5253** [altair-viz/altair#2371]
Is there a way to structure the below interactive chart so that the histogram show up vertically and on the right side of the scatter plot?

![image](https://user-images.githubusercontent.com/42280297/101840380-d7b20280-3af8-11eb-80bf-ecc152a431f7.png)

I was able to make the histogram vertical by switching the X and Y axes, but it still shows up below the scatter plot whenever I use the "&" keyword to link them. I cannot find a way to have it appear on the right side.

**Comment by jakevdp** [comment]
Sure, use `|` as a shorthand for `alt.hconcat()`, rather than `&` as a shorthand for `alt.vconcat()`. See https://altair-viz.github.io/user_guide/compound_charts.html for more information.

**Comment by joelostblom** [comment]
@Murtz5253 I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
