### ISSUE TITLE
Shaded regions using Altair

### ISSUE THREAD

**Issue by ansin218** [altair-viz/altair#2372]
I have spent a lot of time trying to figure this out in Altair. In Matplotlib, I would use the `axvspan` or `axhspan` depending on the axis. I eventually did find a question on StackOverflow but I have not struck gold yet as I am not able to comprehend the answer. My numerous attempts have failed. 

Can someone please help me plot something like this: 
https://stackoverflow.com/questions/43482055/how-to-shade-a-region-with-altair

**Comment by jakevdp** [comment]
Does this issue help you? https://github.com/altair-viz/altair/issues/2348

**Comment by ansin218** [comment]
@jakevdp Lovely, works like a charm. Thanks a ton!

**Comment by ansin218** [comment]
Hello once again @jakevdp , not sure if I should open a new issue for this.

Is there a way to create a custom legend for the rectangle shaded area? I added 3-5 such areas in my graph and would like to add a legend that explains what the shaded regions mean by automatically taking the colours that I've added.

**Comment by jakevdp** [comment]
You can do it via the standard approach to generating a legend: use a color encoding.
