### ISSUE TITLE
DomainMid

### ISSUE THREAD

**Issue by Amarounek** [altair-viz/altair#2373]
Hello!

I would like to ask you what if there are some changes with `DomainMid`.  After a few weeks, I am trying to use this argument again with the same distribution and same installation, however unsuccessfully. It doesn't change the distribution of color.

Is there any change? I cannot find it!

Here's my code snippet
```
domainMid = (cumulative_yield['Cum_yield'].max()) - ((cumulative_yield['Cum_yield'].max())/4) 
baryear = alt.Chart(cumulative_yield).mark_bar().encode(
    x=alt.X('month_date:T', title='Calendar year', axis=alt.Axis(format="%b %d")),
    y=alt.Y('Cum_yield:Q', title='Cumulative yield'),
    color=alt.Color('Cum_yield:Q',
                    scale=alt.Scale(scheme='redyellowgreen', domainMid=domainMid)),
    order=alt.Order("Cum_yield:Q", sort="ascending"))              

(baryear).properties(width=700, height = 100).configure_axisX(labelAlign="right", labelAngle=-45).configure_bar(binSpacing=0)
```

![image](https://user-images.githubusercontent.com/36733547/102250595-04ed1f00-3f04-11eb-82f9-32a8ace4b65d.png)

Thanks

**Comment by jakevdp** [comment]
There hasn't been an Altair release in over eight months... so I suspect if anything changed it would be in your own code.

**Comment by Amarounek** [comment]
Well It is really strange because I was also testing the new installation on different hardware before few hours and It didn't work for me and tells me this:
`Additional properties are not allowed ('domainMid' was unexpected)` 

Now it is working well for both versions and installations. Does Altair need a stable internet connection or more precisely does it connect to some distant server? Once, I was trying to launch some script in a train without a connection and some issues rose up.

**Comment by jakevdp** [comment]
The default renderer uses javascript libraries downloaded from CDN, so it won't work offline. But the `Additional properties are not allowed` comes from the Python library: if you saw that, I suspect you were using an older version of Altair.

**Comment by joelostblom** [comment]
@Amarounek I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
