### ISSUE TITLE
Displaying Dynamic Text Beneath Altair Chart

### ISSUE THREAD

**Issue by Murtz5253** [altair-viz/altair#2374]
I have the following chart:

![image](https://user-images.githubusercontent.com/42280297/102706107-fd02e700-4243-11eb-8baa-999440905c9d.png)

The user can select a period, and then the maroon bar graph updates with the average number over their selection. I want to add dynamic text below the bar graph that updates as the user selects. Essentially, I want it to say "Over the time period you selected, the number of cases is [INSERT VALUE] times the number of cases over the entire period."

So, it dynamically calculates the ratio of the maroon bar graph's value to the navy blue's value, and then inserts that value into the above text, automatically updating with the user's selection. Is there a way to do this? Here is the code for the base chart and bar graphs:

```
brush = alt.selection_interval(encodings=['x'], empty='all', mark=alt.BrushConfig(fill='red'))
base = alt.Chart(df).mark_line().encode(
                x='Day:Q',
                y=alt.Y('New_Cases_Rolling:Q', axis=alt.Axis(title="New COVID-19 Cases per Day")),
            ).properties(
                width=570,
                height=400
            ).add_selection(
                brush
            )

mean_line = alt.Chart().mark_rule(color='#800000').encode(
        y='mean(New_Cases_Rolling):Q',
        size=alt.SizeValue(2.2)
    ).transform_filter(
        brush
    )
    
    mean_bars = alt.Chart(df).mark_bar().encode(
        alt.X('Province_State:N', axis=alt.Axis(title="State")),
        alt.Y('mean(New_Cases_Rolling):Q', axis=alt.Axis(title='Average Cases per Day in Selected Period'),
              scale=alt.Scale(domain=(0, max(df['New_Cases_Rolling'])))),
        opacity=alt.value(0.9),
        color=alt.value('#800000')
    ).transform_filter(
        brush
    ).properties(
        width=25,
        height=400,
        title="Selected Period"
    )
    
    mean_bars_text = mean_bars.mark_text(dx=20, dy=-10, fontSize=15, align='center', color='#000').encode(text=alt.Text('mean(New_Cases_Rolling):Q', format='.0f'))

mean_bars_total = alt.Chart(df).mark_bar().encode(
        alt.X('Province_State:N', axis=alt.Axis(title="State")),
        alt.Y('mean(New_Cases_Rolling):Q', axis=alt.Axis(title='Average Cases per Day in Entire Period'),
                scale=alt.Scale(domain=(0, max(df['New_Cases_Rolling'])))),
        opacity=alt.value(0.9),
        color=alt.value('#000080')
    ).properties(
        width=25,
        height=400,
        title="Entire Chart"
    )
    
    mean_bars_total_text = mean_bars_total.mark_text(dx=20, dy=-10, fontSize=15, align='center', color='#000').encode(text=alt.Text('mean(New_Cases_Rolling):Q', format='.0f'))
    if not show_bar:
        return (base, img, warning)
    return (base + mean_line) | (mean_bars+mean_bars_text) | (mean_bars_total + mean_bars_total_text)
```

**Comment by jakevdp** [comment]
You can do this using a calculate transform to generate the desired text, and display this text via a text mark in a layer.

**Comment by Murtz5253** [comment]
I tried layering with a vertical concatenation, but the graph just shows up blank. Also, how do you extract just the singular value desired with a calculate transform? Should the text mark be its own separate layer?

**Comment by jakevdp** [comment]
If you can provide a minimal self-contained example describing what you want to do, I may be able to help.

**Comment by joelostblom** [comment]
@Murtz5253 I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
