### ISSUE TITLE
Line break or word wrap for labels in axis

### ISSUE THREAD

**Issue by tzipperle** [altair-viz/altair#2376]
Hi,
I have a short question. Why does not working the line break or word wrap for labels in axis like: [vega-lite-line-break-or-word-wrap-for-labels-in-axis](https://stackoverflow.com/questions/64766369/vega-lite-line-break-or-word-wrap-for-labels-in-axis)?

```python
chart = alt.Chart(data).mark_bar().transform_calculate(
        address="split(datum.address, ' ')"
 ).encode(...)
```

**Comment by jakevdp** [comment]
It should work just as written with the most recent release of Altair. For example:
```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'y': ['label one', 'label two'],
    'x': [100, 200],
})

alt.Chart(df).mark_bar().transform_calculate(
    y="split(datum.y, ' ')"
).encode(
    x='x:Q',
    y='y:N',
).properties(
    height=300
)
```
![visualization (25)](https://user-images.githubusercontent.com/781659/103234612-f5eb7100-48f4-11eb-9c19-6048bd4bc5f9.png)

**Comment by tzipperle** [comment]
Your solution works well. But if I want to break the facet label it doesn't work:

```python
import altair as alt
import pandas as pd

df = pd.DataFrame({
    'y': [10, 20],
    'x': [100, 200],
    'z': ['label one', 'label two'],
})

chart = alt.Chart(df).mark_bar().transform_calculate(
    z="split(datum.z, ' ')"
).encode(
    x='x:Q',
    y='y:Q',
    facet='z:N'
).properties(
    height=300
)
```

![image](https://user-images.githubusercontent.com/6015123/103267745-8471f800-49b2-11eb-9d6e-cd1adb8e0b1d.png)

**Comment by jakevdp** [comment]
That looks like an issue with the Vega-Lite renderer: I'd suggest inquiring there.

**Comment by jakevdp** [comment]
I gave this a try with a newer version of Vega-Lite, and it works as expected, so this will likely be fixed in the next Altair release.

**Comment by tzipperle** [comment]
Thanks for the explanation. And sorry for the missing example. Is there a plan for a new Altair release?

**Comment by RoyalTS** [comment]
This is one of those annoying little things that comes up all the time for me, the kind of thing that's tantalizingly close to being fixed and yet isn't. What are the plans for the next altair release, if I may ask?

**Comment by mattijn** [comment]
> This is one of those annoying little things that comes up all the time for me, the kind of thing that's tantalizingly close to being fixed and yet isn't. What are the plans for the next altair release, if I may ask?

Join the discussion at https://github.com/altair-viz/altair/issues/2425

**Comment by cmosguy** [comment]
@RoyalTS and @mattijn I just tried to do a line break and it does not work.  Is there any solutions or workaround when I try to insert `'\n'` into my text labels?

**Comment by jakevdp** [comment]
Use a list of strings in place of the string that you want to appear with a line break. You haven’t shown any example code, so it’s hard to be more specific than that.

**Comment by qunderriner** [comment]
@jakevdp When I try to split text across labels on the y or x axis I can get it work with either the list of strings, or using transform_calculate, but when I try to do the same with column headers I cannot figure out how to get text to wrap. 

Dummy example below: I would love the county names to render as column headers split across two lines, but as you can see in image currently they are both rendering on one line. 

Any advice? Thanks so much! 
``` 
import altair as alt
import pandas as pd

fig1_example = pd.DataFrame({
    'county': [['Marin, San Francisco,'," and San Mateo"], 
               ['Marin, San Francisco,'," and San Mateo"],
              ["Alameda","and Contra Costa"],
              ["Alameda","and Contra Costa"]],
    'year': [1999, 2019,1999,2019],
    'median_income': [14000, 15000,10000,14000]})

alt.Chart(fig1_example).mark_bar().encode(
    alt.X('year:O',title=" ",axis=alt.Axis(labels=False)),
    alt.Y('median_income:Q',title="Median Household Income ($2019)"),
    color=alt.Color('year:O',title="",scale=alt.Scale(domain=[
                        "1999","2019"],range=["#4E748B","#FFB81D"])),
    column=alt.Column('county',title="",spacing=40, 
                      header=alt.Header(labelFontSize=16)))

```
![image](https://user-images.githubusercontent.com/49345850/155261315-c0735d32-e279-4538-adb2-7c70b0241753.png)

**Comment by joelostblom** [comment]
@qunderriner Your example is working as expected for me. Make sure you are on the latest version of Altair (4.2.0).

@tzipperle Your facet example is also working in 4.2.0, so I am going to close this issue.

For anyone else finding this and looking for ways to wrap labels at word boundaries of specific lengths rather than manually creating a list, you can use the `textwrap` package as described here https://stackoverflow.com/questions/71215156/how-to-wrap-axis-label-in-altair


![image](https://user-images.githubusercontent.com/4560057/155366651-648be631-2368-499b-87d6-db1fd0abd2a1.png)

and 

![image](https://user-images.githubusercontent.com/4560057/155367120-285f97c5-d68c-438b-8a6a-21cf35a158a8.png)
