### ISSUE TITLE
Use alt.value for dates

### ISSUE THREAD

**Issue by krlng** [altair-viz/altair#2377]
I would like to add a vertical rule on an time-based x-axis by manually specifying a value. Let's assume this example:

```
import altair as alt
from vega_datasets import data as vdata

bar = alt.Chart(vdata.us_employment()).mark_bar().encode(
    x="month:T",
    y="nonfarm_change:Q"
).properties(width=600)
```

What I can do is something like: 

```
bar + alt.Chart(vdata.us_employment()).mark_rule().encode(
    x="mean(month):T",
)
```

How ever I do not find a way to pass in manually specified values, something like:

```
bar + alt.Chart(vdata.us_employment()).mark_rule().encode(
    x=alt.value("2010-12-12")
)
```

I also tried timestamps (`alt.value(1292108400)`) and similar but without success. 

Is there a way so specify temporal data manually?

**Comment by jakevdp** [comment]
`alt.value()` refers to the range value. For x and y encodings, the range is specified in pixels. So, for example, this draws a rule mark 50 pixels from the left of the chart:
```python
bar + alt.Chart(vdata.us_employment()).mark_rule().encode(
    x=alt.value(50)
)
```
What you want is not a line at a range value, but a line at a domain value; currently the only way to do this in Altair is via a dataset or a transform; I would suggest something like this:
```python
bar + alt.Chart(pd.DataFrame({'month': ["2010-12-12"]})).mark_rule().encode(
    x='month:T'
)
```

**Comment by jakevdp** [comment]
(side-note: recent Vega-Lite versions have added the ability to specify domain values via `{"datum": value}` similar to how range values can be specified via `{"value": value}`. Future Altair versions should be able to make use of that to make it easier to do this kind of thing)

**Comment by krlng** [comment]
Thank you very much, I did missunderstood that alt.value will refer to pixels. Your solution works. And I really look forward to the (in my point of view) more beautiful way of specifying fixed values using vega-lite expressions. 👍
