### ISSUE TITLE
Sticky tooltips or copy-paste info from a tooltip?

### ISSUE THREAD

**Issue by haydenflinner** [altair-viz/altair#2378]
It would be nice to be able to copy-paste the info that is in a tooltip for use in further analysis. For example I have a tooltip which displays a unique key for the data point that can be used to investigate the point further in other charts. If there were a way to set the tooltips to stay displayed after the cursor leaves the point in e.g. a scatter plot, one could select text from them with the mouse cursor and copy paste. Alternatively if someone knew of a hack to make displaying a tooltip or clicking a data point print its contents to the browser console, that would be good enough for my uses as well.

Thanks for the awesome library, it has made data viz much more natural / less Google-heavy for me, and this is the only feature at all that I've been missing.

**Comment by jakevdp** [comment]
Thanks for the suggestion! I don't know of any way to do that currently, but such a feature would have to be implemented in the Vega renderer, so that would be the appropriate place for such a feature request.

**Comment by haydenflinner** [comment]
Will add one there, thanks!
