### ISSUE TITLE
add a vertical line for specific dates

### ISSUE THREAD

**Issue by Mohammadreza20** [altair-viz/altair#2379]
Hello, Happy New Year
I want to add a couple of vertical lines to my chart but I don't know how could you please help me?
vertical lines for two different date e.x: for Dec 09 and Dec 20

How I increase the resolution of the chart image?
when I download chart image they don't have quality

Code :
```python
highlight = alt.selection(
    type='single', on='mouseover', fields=['DOY'], nearest=True)

base = alt.Chart(NO2).encode(
    x=alt.X('monthdate(Timestamp):Q', title='Date'),
    y=alt.Y('mean(T_NO2):Q', title='NO2 Khorasan (mol/m^2)'),
    color=alt.Color('Year:O', scale=alt.Scale(scheme='magma')))

points = base.mark_circle().encode(
    opacity=alt.value(0),
    tooltip=[
        alt.Tooltip('Month:O', title='Month'),
        alt.Tooltip('DOY:Q', title='DOY'),
        alt.Tooltip('T_NO2:Q', title='NO2')
    ]).add_selection(highlight)

lines = base.mark_line().encode(
    size=alt.condition(~highlight, alt.value(3), alt.value(3)))




rule1 = base.mark_rule(color='red').encode(
    x={'Timestamp': "2020-11-09"},
    size=alt.value(5)
)

rule2 = base.mark_rule(color='orange').encode(
    x={'Timestamp': "2020-11-20"},
    size=alt.value(5),
)

    

(points + lines).properties(width=600, height=350).interactive()
```

![Untitled](https://user-images.githubusercontent.com/31747767/103459859-1bc6aa80-4d27-11eb-848c-ca8f5b866a9b.jpg)

![visualization](https://user-images.githubusercontent.com/31747767/103459866-31d46b00-4d27-11eb-8b01-ed45b5cdebd7.png)

**Comment by jakevdp** [comment]
You can create a rule layer that looks something like this:
```lang-python
rules = alt.Chart(pd.DataFrame({
  'Date': ['2020-11-09', '2020-11-20'],
  'color': ['red', 'orange']
}).mark_rule().encode(
  x='Date:T',
  color=alt.Color('color:N', scale=None)
)
```

**Comment by Mohammadreza20** [comment]
Thank you dear @jakevdp 
I used your code but get this result

![visualization (7)](https://user-images.githubusercontent.com/31747767/103512843-b84f9080-4e7e-11eb-9dff-f12475662193.png)

but when I change dates resolved the problem

2019 or 2020 != 2012 :)))

```python
rules = alt.Chart(pd.DataFrame({
  'Date': ['2012-12-01', '2012-12-12'],
  'color': ['red', 'orange']
})).mark_rule().encode(
  x='Date:T',
  color=alt.Color('color:N', scale=None)
)
```

![visualization (8)](https://user-images.githubusercontent.com/31747767/103513137-3a3fb980-4e7f-11eb-94e5-f9c367ca17d1.png)

**Comment by jakevdp** [comment]
If you're using a `monthdate` timeUnit on the data, you can also use a `monthdate` timeUnit on the lines to make them match:
```python
rules = alt.Chart(pd.DataFrame({
  'Date': ['2020-11-09', '2020-11-20'],
  'color': ['red', 'orange']
})).mark_rule().encode(
  x='monthdate(Date):T',
  color=alt.Color('color:N', scale=None)
)
```

**Comment by Mohammadreza20** [comment]
Oh Yeas, I don't care to` monthdate`, THANK YOU
