### ISSUE TITLE
Run CI tests with pip?

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#238]
We currently run CI tests with conda. Should we run with pip as well, to ensure our installation instructions work correctly?

**Comment by jakevdp** [comment]
Pros: more comprehensive testing. Cons: doubles the CI load.

**Comment by stonebig** [comment]
pip is the Python community standard, so you should test with pip.

**Comment by jakevdp** [comment]
conda is far more of a standard in the Python data science community. For altair, it also has the advantage that it can fully set-up the package, where pip can't (we've already had users report issues that boiled down to them ignoring the install instructions and assuming ``pip install altair`` would work). I would prefer to keep conda as the primary recommended installation path.

**Comment by stonebig** [comment]
keeping conda as your "best advice" is fine, but the community standard is still "pip".

**Comment by jakevdp** [comment]
We support both routes of installation, as well as Python 2 and 3, and we provide conda builds on OSX, Linux, and Windows. I'm not choosing sides here. The question in this Issue is whether it's worth the CI resources to test multiple means of installation.

**Comment by jakevdp** [comment]
Closed by #243
