### ISSUE TITLE
resolve_scale does not properly work in combination to multiple subplots

### ISSUE THREAD

**Issue by krlng** [altair-viz/altair#2380]
4 overlayed plots, of which two subgroups should share a y-axis, but the two subgroups should then use two different y-axis:

```
import altair as alt
from vega_datasets import data as vdata

cars = vdata.cars()
base = alt.Chart(cars).mark_point().encode(
        alt.X('Acceleration:Q'),
    )
left_y_axis = (base.encode(alt.Y('Displacement:Q')) + base.encode(alt.Y('Horsepower:Q'))).resolve_scale(y = 'shared')
right_y_axis = (base.encode(alt.Y('Miles_per_Gallon:Q')) + base.encode(alt.Y('Miles_per_Gallon:Q'))).resolve_scale(y = 'shared')
(left_y_axis + right_y_axis).resolve_scale(y = 'independent')
```

**result:**
<img width="503" alt="Screenshot 2021-01-04 at 09 18 11" src="https://user-images.githubusercontent.com/1107509/103514866-d19c1100-4e6d-11eb-8722-6546b483eff3.png">

**expected (but not side-by-side but on-top of each other)**
<img width="947" alt="Screenshot 2021-01-04 at 09 19 50" src="https://user-images.githubusercontent.com/1107509/103514999-1aec6080-4e6e-11eb-90c7-f887215baf5a.png">

**Comment by jakevdp** [comment]
When you care about the nesting details of layers, you should avoid the overloaded `+` operator and instead use
```python
alt.layer(left_y_axis, right_y_axis).resolve_scale(y = 'independent')
```

**Comment by krlng** [comment]
Thanks
