### ISSUE TITLE
Mapping multiple related columns to the same channel

### ISSUE THREAD

**Issue by jonathangjertsen** [altair-viz/altair#2385]
My use case is as follows: I have some CSV data where each row has a device ID, a timestamp, and the received signal strength indication (RSSI) for two antennas (encoded as columns "rssi0" and "rssi1"). For each device, I want to plot both of the RSSI values over time. The device ID should map to the color of each line, and the "antenna ID" should map to the stroke style (see matplotlib example below).

Is there a nice way to achieve this with Altair?

---

Here is some code to generate data in the same general shape as my source data:

```Python
SIZE = 100
times = np.linspace(0, 1, SIZE)
device0_rssi0 = np.random.normal(size=SIZE, loc=-40, scale=0.5)
device0_rssi1 = np.random.normal(size=SIZE, loc=-45, scale=0.5)
device1_rssi0 = np.random.normal(size=SIZE, loc=-70, scale=0.5)
device1_rssi1 = np.random.normal(size=SIZE, loc=-75, scale=0.5)
data = pd.DataFrame([
    { "t": t, "device": 1, "rssi0": rssi0, "rssi1": rssi1 } for t, rssi0, rssi1 in zip(times, device0_rssi0, device0_rssi1)
] + [
    { "t": t, "device": 0,  "rssi0": rssi0, "rssi1": rssi1 } for t, rssi0, rssi1 in zip(times, device1_rssi0, device1_rssi1)
])
```

Which looks like this:

![df](https://user-images.githubusercontent.com/7355797/104324324-9346c780-54e7-11eb-9ce9-a003620d4de5.PNG)

---

Here is some hardcoded matplotlib-code that generates the type of chart that I want to make:

```Python
from matplotlib import pyplot as plt

plt.figure()
plt.plot(data[data.device == 0]["t"], data[data.device == 0]["rssi0"], color="blue")
plt.plot(data[data.device == 0]["t"], data[data.device == 0]["rssi1"], color="blue", linestyle="dashed")
plt.plot(data[data.device == 1]["t"], data[data.device == 1]["rssi0"], color="orange")
plt.plot(data[data.device == 1]["t"], data[data.device == 1]["rssi1"], color="orange", linestyle="dashed")
plt.legend(["Device: 0, Antenna: 0", "Device: 0, Antenna: 1", "Device: 0, Antenna: 1", "Device: 1, Antenna: 1"], loc="upper left")
plt.ylim(-80, 0)
plt.show()
```

![matplot](https://user-images.githubusercontent.com/7355797/104325765-47951d80-54e9-11eb-9817-7ecbdbaa3a06.PNG)

---

The closest I have come with Altair is the following:

```Python
base = alt.Chart(data).mark_line().encode(
    x="t",
    color="device:N"
)
base.encode(y="rssi0") + base.encode(y="rssi1")#.configure_mark(strokeDash=[10, 3])
```

![altair](https://user-images.githubusercontent.com/7355797/104326562-27199300-54ea-11eb-8b85-636fa3dcf559.PNG)

The call to `configure_mark` does what I want if I display the chart by itself, but causes an exception when used with any other chart:

```
ValueError: Objects with "config" attribute cannot be used within LayerChart. Consider defining the config attribute in the LayerChart object instead.
```

**Comment by jakevdp** [comment]
Have you tried using the `stroke` encoding?

**Comment by jakevdp** [comment]
You could also do this:
```python
alt.layer(
  base.encode(y='rssi0:Q'),
  base.mark_line(strokeDash=[10, 3]).encode(y='rssi1:Q')
)
```
![visualization (28)](https://user-images.githubusercontent.com/781659/104349755-2cf68080-54b8-11eb-8a7a-3b67745b3118.png)

See https://altair-viz.github.io/user_guide/customization.html#global-config-vs-local-config-vs-encoding for information about global vs local configurations.

**Comment by joelostblom** [comment]
@jonathangjertsen I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
