### ISSUE TITLE
Typo error generates tons of output

### ISSUE THREAD

**Issue by haydenflinner** [altair-viz/altair#2388]
Minor rough edge to smooth. I don't know how many of these cases you intend to handle specifically in the Python side, but anyway, I did this on accident:
```
alt.Chart(mysample, title=averylargedictionary)
```

which I thought froze the notebook, but eventually, I got this output:
```
SchemaValidationError: Invalid specification
        altair.vegalite.v4.api.Chart->0, validating 'type'
        {'myhugedictionariy': 'whichTakesAMinuteOrTwoToFormat'} is not of type 'string'
```
The dictionary was quite large and included all of the data I was trying to graph (more than just the sample I was intending to submit to altair), so I kept looking elsewhere besides the title argument.

Using %debug makes it instant as the debugger is introduced before the string is formatted for the Exception, apparently? Or could be that %debug was showing me the last time the incident happened. Anyway, a few opportunities for improvement here IMO:

1. Notify of which key was found to be bad in the schema, as all the current error tells me is that I have a dict somewhere that I'm supposed to have a string.
2. Perhaps a timeout on this validation, or maybe the generation of the validation error? Not sure if there is a clean solution here, perhaps best for user who observes freezing just to enable a debugger and then send a KeyboardInterrupt once they decide the bad delay has been entered.
3. It _might_ make sense for the title kwarg to assert that it must be a string, so that user knows they're responsible for formatting into a presentable string, but maybe this isn't viable if there is an object able to be passed to title here rather than using configure_title, I don't know.

Thanks again for the neat library, I may submit a PR for this if find time.

**Comment by jakevdp** [comment]
Thanks for the report. Input validation in Altair comes from `jsonschema`, which only can validate the entire chart spec, so it's not easy to return information on errors with more granularity than Altair currently does. Feel free to play around and send a PR if you find a better way!

**Comment by binste** [comment]
With Altair 5, this error message will now read `'{'myhugedictionariy': 'whichTakesAMinuteOrTwoToFormat'}' is an invalid value for `title`. Valid values are of type 'string' or 'array'.` This addresses your first suggestion. Regarding 3, that would require to rewrite Altair with something like Pydantic which I think is currently out of scope and we should continue to rely on `jsonschema`. 

As this doesn't seem to be a common issue, I'm closing it but it could be revived if someone wants to look at suggestion 2 of truncating the error message. Not sure if a timeout would be possible.

**Comment by haydenflinner** [comment]
Awesome, thank you!
