### ISSUE TITLE
Saving Panel and Altair interactive charts as HTML

### ISSUE THREAD

**Issue by darkknight-187** [altair-viz/altair#2391]
I created a Panel and Altair interactive chart using.
```
from bokeh.resources import INLINE, CDN
from vega_datasets import data
import panel as pn
import pandas as pd
import altair as alt
from altair import datum
cars = data.cars()

alt.renderers.enable('altair_viewer')
alt.data_transformers.enable('default')
pn.extension('vega')
options= cars['Origin'].unique().tolist()
hp_range_slider = pn.widgets.RangeSlider(
    name='Range Slider', start=40, end=250, value=(60, 160), step=10)
country_ticker = pn.widgets.MultiSelect(name='MultiSelect', value=[options[0], options[1]],
    options=options, size=8)
@pn.depends(country_ticker.param.value, hp_range_slider.param.value)
def get_plot(country_ticker, hp_range):
    df=cars.copy()
    start_hp = hp_range_slider.value[0]
    end_hp = hp_range_slider.value[1]
    mask = (df['Horsepower'] > start_hp) & (df['Horsepower'] <= end_hp)  # create filter mask for the dataframe
    df = df.loc[mask]  # filter the dataframe
    print(country_ticker)
    print(start_hp,end_hp)
    # create the Altair chart object
    scatter = alt.Chart(df).mark_point().encode(
        x='Horsepower:Q',
        y='Miles_per_Gallon:Q',
        color='Origin:N'
    ).transform_filter(
        alt.FieldOneOfPredicate(field='Origin', oneOf=country_ticker)
    )
    return scatter
title = '## Horsepower Dashboard'
subtitle = 'This dashboard allows you to select a country and HP range .'


dashboard = pn.Row(
    pn.Column(title, subtitle, country_ticker, hp_range_slider),
    get_plot # draw chart function!
)
dashboard.servable()

dashboard.save("test_altair.html",embed=True,resources=INLINE)
dashboard.show()
```

When I execute dashboard.show command it displays perfectly.
![image](https://user-images.githubusercontent.com/54602821/104828716-eeebba80-5831-11eb-9abf-2f8dc6fc1dd0.png)

But when I save it as html, I dont get the charts , just the panel components. Any help with this @jakevdp ?
![image](https://user-images.githubusercontent.com/54602821/104828746-1d699580-5832-11eb-9cba-5db672f5d574.png)

**Comment by jakevdp** [comment]
The `altair_viewer` renderer requires a live kernel. From the [`altiar_viewer` README](https://github.com/altair-viz/altair_viewer)

> Note that the display based on altair viewer will only function correctly as long as the kernel that created the charts is running, as it depends on the background server started by the kernel.

If you want charts in saved HTML to display without a kernel, you need to use a different renderer, such as the default renderer.

**Comment by darkknight-187** [comment]
@jakevdp Pardon my ignorance, I am just getting a hang of altair and panel visualizations together. Are you suggesting that I use

`alt.renderers.enable('default')`

I tried this and it showed me the same result, or write some kind of custom renderer?

**Comment by jakevdp** [comment]
You may also need the vega extension in panel; see https://panel.holoviz.org/user_guide/Components.html

**Comment by darkknight-187** [comment]
Thanks @jakevdp . I included this in my extension 

`pn.extension('vega','katex')`

At least this is what panel docs says. The result is the same. Is there any other way to do a dashboard with Altair other than Panel. ? 
Thanks

**Comment by joelostblom** [comment]
This is probably something to ask on the Panel issue tracker (please link the issue here). A workaround is to do `dashboard.embed()` and then export the entire notebook as html, that worked for me (you could delete the code cells before exporting it to just get the chart).

**Comment by emsrc** [comment]
I've been playing with Panel and Altair too. Interesting solution. I found the options for running Panel without a server/kernel are rather limited. See the section on [embedding](https://panel.holoviz.org/user_guide/Deploy_and_Export.html#embedding) though. 

To make your example work, you have to disable the Altair viewer as well as the call to show():

```
from bokeh.resources import INLINE, CDN
from vega_datasets import data
import panel as pn
import pandas as pd
import altair as alt
from altair import datum
cars = data.cars()

## alt.renderers.enable('altair_viewer')
alt.data_transformers.enable('default')
pn.extension('vega')
options= cars['Origin'].unique().tolist()
hp_range_slider = pn.widgets.RangeSlider(
    name='Range Slider', start=40, end=250, value=(60, 160), step=10)
country_ticker = pn.widgets.MultiSelect(name='MultiSelect', value=[options[0], options[1]],
    options=options, size=8)
@pn.depends(country_ticker.param.value, hp_range_slider.param.value)
def get_plot(country_ticker, hp_range):
    df=cars.copy()
    start_hp = hp_range_slider.value[0]
    end_hp = hp_range_slider.value[1]
    mask = (df['Horsepower'] > start_hp) & (df['Horsepower'] <= end_hp)  # create filter mask for the dataframe
    df = df.loc[mask]  # filter the dataframe
    print(country_ticker)
    print(start_hp,end_hp)
    # create the Altair chart object
    scatter = alt.Chart(df).mark_point().encode(
        x='Horsepower:Q',
        y='Miles_per_Gallon:Q',
        color='Origin:N'
    ).transform_filter(
        alt.FieldOneOfPredicate(field='Origin', oneOf=country_ticker)
    )
    return scatter
title = '## Horsepower Dashboard'
subtitle = 'This dashboard allows you to select a country and HP range .'


dashboard = pn.Row(
    pn.Column(title, subtitle, country_ticker, hp_range_slider),
    get_plot # draw chart function!
)
dashboard.servable()

## dashboard.save("test_altair.html",embed=True,resources=INLINE)
## dashboard.show()
```

Assuming you saved the above in file named `cars.py`,  execute the command:

```
panel serve --show cars.py
```

This will open the app in your browser. You can add the option `--autoreload` to update the page content every time you make a change to your code.

**Comment by joelostblom** [comment]
I opened an issue about this over at the Panel repo a while ago and it was fixed yesterday, so I am closing this. See https://github.com/holoviz/panel/issues/2367 for details.
