### ISSUE TITLE
[Question] Creating tooltips based on selection

### ISSUE THREAD

**Issue by legendre6891** [altair-viz/altair#2393]
Thanks for your great work on Altair!

I have a question on how to create tooltips that depends on the selection in the legend. I modified the pivot transform example in the documentation and currently have this:

```python
import altair as alt
from vega_datasets import data

source = data.stocks()
base = alt.Chart(source).encode(x='date:T')
columns = sorted(source.symbol.unique())

selection = alt.selection_single(
    fields=['date'], nearest=True, on='mouseover', empty='none', clear='mouseout'
)
legend_selection = alt.selection_multi(fields = ['symbol'], bind = 'legend')

lines = base.mark_line().encode(
    y='price:Q',
    color='symbol:N',
    opacity = alt.condition(legend_selection, alt.value(1), alt.value(0)),
).add_selection(legend_selection)

points = base.mark_point().encode(
        y = 'price:Q',
        color = 'symbol:N',
        opacity = alt.condition(legend_selection, alt.value(1), alt.value(0))
    ).transform_filter(selection)

rule = base.transform_pivot(
    'symbol', value='price', groupby=['date']
).mark_rule().encode(
    opacity=alt.condition(selection, alt.value(0.3), alt.value(0)),
    tooltip=[alt.Tooltip(c, type='quantitative') for c in columns]
).add_selection(selection)

plot = lines + points + rule
plot.save('a.html')
```

[Result in Vega-lite editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3ADYBDAJ6YATigDaoALaK1AaxQh5JTCG6YokOiSSoe8iBoeFlAB3PIQUCDpKK8hYg8JjydMaUyjoARhBBciAQ7opgcG54PFC2xNCZaIGkXgCM3JRhmGC5UJEVVc4cAEwgiQXyRShsiQAemW6exoSYOu7OgcGh4cZ0ikMt3Mp9Hl4gAI6kikTps3Bo5tyTEd7uanBg5rJlddWZ5fKVhA1sza7Lxjqk8sQTWOGUWiAorF4iAALrcGIkI4mTAIKwRWRyXT6IzHCAkcSWawQWxQez4eLOJYDby+fxQcYHX7QoFxBLcZKpdKLBwEHJwPIONodZClQHXDk1bx3B5PZqtQpeLrcXqvEkgIYjMZBKlhaEzOaJFmgfordabYiEHZ7H5q4wnM4XRKENSbSgwZw6LSgeBfdS3AWc-n3epqDjFFrSUFIkB6QzGNSffYgKw2OyZRlpDKs6DsznoSWdAB0EiuPpuwuuTwDEvaUutEHixHczoVb28+q2RuIJtVU28AEEOwAFAAy8x19bWGybxujh2MHYAsgAtAByA7r8sbhrHpvbIAA4gB5bebxe64wr7Yt8fU4wASQAQlOD0Pj83dmezd4pwBlABiABUWuCQLLB3lRVRltFUQnPbwNStPMHkFD182LYkVkoOx7nXOh-mQTQQCgsFuCgTB9EwShxGQG0igZIVQwETAID2DRLBGZMfGgaMwHufR3hoihxEuBVbSge1HVrdxdggUjAWiOlgm5FYLXOYIEDUCh3BiFlsNw4MtO4DVFEyCkdBWXSAFoAE4ADZMAADgAVgAdkUczijAcyYnMxoJBiRQYEwDyWHYOgbKsxpFBsjh5hAAASSgwEYYY9O8MRCHcShkAAejSvYEEULMEHSRhSBiLMOTSmK4r0TLYUUYzTCGTKWCzKys2KLMACtKDyHTZkUcpCEw0ATIs6z7Mc5zXPczzvN8iR-LYQLgtC8KsNAWkQVfT8fy6uZvEaDg2GMthigO4ovw4ZAzvC7h5K8CRTMa4oQ1WoJ1u-YJcJ2vaDsaY7TrYc6-sukBrskcycxsx6pLWkB31eraVl2jgDokH6LoBthgmB5AWAkLNGkaCHgWe6GNre2Z4c+tgWBRtH-ox04FOQRomokOyCekl7NpwsnjAR-a2Bs6n-tpq76a8RobKzFhwc4FbIaJmHOfekBeYO8zBdRunLUkRosxslg2ahhXSe25WKbs9W0c1hmmclg35ZJuGeYpqyLeFoHRZQG39ZlyTCeMI3HY+xG2FM13AcxxoGpsiQ7f9h2uZNlXij5k7UbdiOmueWOOeN8nEeKI7Dt+oXw49xmcZm7PidhhO8-24pvqLtPS613k7Kzczpdlv2c8D03DuOsP0ZF1vI8a73u-Z6vFe5oPC8b1OaZb62J99qeA9rp2B7YZGm6X4f3dHnXxarjelYRwuqb3kuD4j9ubPM0-4-P-0DoF6+NZH62muKVenrjmuL9t5qw-pbL+Ys7qsx9v-Xum854HXNqA9OZdGig1MjHaBcsAEz0Tq-NgLskHLzFjjRoD1ME92nrnLehdQ6ENvigtgjV8bkPXs-We-cjrJyHlbYhHcu5r0Nmw3BA8C7cPAZ7UGDcn6APYRfYyDcxGH2tmg-hMDKF9wRgvRREcJamWYZPQRMjhGNwXsXT+SjeF2QwQY+2Ri86N13ovG+PDPZR2sQI2xOD7EHSvk48xEcWqoOkV4rejd35+LARYz2jC7JkJsdgqhQdG4gIicgo+uNVFYNgUAxuiDUlEJQMUO6Nl9EeISRopoB0CH5Poa3IpWZTJQPidk2RlSQ7aLLsUdudlTLBMSf3b6XC6EuMZi1OymSKFn1ac8eRhcakjI8pLR+LDDEhKSfI0xzdanWxajvPpFSd6D2GeI3kd0JBxLKS04Ru9Nn7xGfUyuKzPH9IRrvRxZjImY3qXZZZzT1FwP7rvXxHy0nW0YVZJplz-lAN3uEkFBTGaMJDvsgFrzVYdNHow9BKKYUIIxTs3WvyoVTOuVU-FYsWqdxxdM3etD5knLxh3XpTzymoo4MjIZ9KomjMlhM1hdit4crmfC7ZFLmrUtJQo453LGUsCJWokledfHks9jrcyzK-mKq3lfW5ziGVjMhQqoRSqkYqsRUsiVJrKZmtIbyy12q342patHe1Qcr4pJFQsnG-lXX9yvnkz1DKK5WV9QjK+1TA0yp1iwQ1WToXTKvnSyNEcdY-NDRwKmnLk0oJxlnFlVyTWiOlRHBq8q41ardRsm1UdSlGoFUHcJ1bmoXLrWs-u79dX+Jzc1PlqyXkcHfu8rZCzj5-3Lcare79gXDqDbjEN+b43CPfnCmdMqcbBXTfzdFxaUE62xQuit7a8U7tHjjcyY7JkTobWSk91sJYSF7c8g578k2rojuu9xrb+1bqzW+7t87NVXqPUWrlOisyxM3QLKVoGUENUaBq4lQGEYpJtZIi9-K23Ia+jaiWlNN0gKHXchl96y2Xvrf3EB06iNRt1vhx1t6xVFLo2wD1f7R4tQA4h8jWG2ABrY9bHWNkW3ju4xwEBEb+NiwasUT9InMNiYOq+6jYHzKca-QctWv7lMoLQaRjD37NPCsk57du5k9N9o01Whjnsf6ybI-J3jRyYOjzurxzdiDO2fJ0x3Oz+mDmIMI3qmVoMH3uZ8Ta5mYWt3WcZndAuUXWPadHu3Uyj7WVAMQXxpL1t75RYk9lsW7dHmAdE459pMWbZ4YPUhjg5stNBcxg+rMezqulbq0Zgr2tmsIfU2yxz0Hs2t2K1xhz1SzXnOar5izfWCGedBWLUGbnWujdNRV9upDN0EKow1lBRX0PTaAQQldnXGbrbSwWreBDEs7dHqDGNm3j3OZXuB87i684EPyzd5ROZzNPpm4pnD4G1Nye-S7erXb2O61jfZ0HsyzX1LMw9gbxneRNVMsJmHBy6Xw9BuZKbf2gG0Lmwi4oEsrIY78312hgWIcMy6Q0nrIOsfhZi-Uqy+2CfTNocdr7YtGE2UZ5jqn26nu8JYLWpnwuyui89jjYowOheE5vTLxmDVsabtoUp3nnsJYsEF5TpX4OvPJclgrg3XO4cVbuo0aH5vhGh2RydqQOYOfpdaZyiLzXXuHt2kM4noqbMd1twd93fMafG+-o1Ku055zfpTma89hLo+zgXAcvm-uRmqcasHomMfU99bDwnnPk4U9x5ZyrmyEsmMLrz2X6LKuWDMwp1DWvaeReDYZhIELzfc+l7b9LjvN1GFSJr33gvyvB+sGdcn2P-ete05uk1H1o-Z-j6N-NkGHcJcUNb2vjr2vVdMpn-noB9cM8nNJ0nlfJ-plzPh0VnvJfV9APnvD4f+uW9j5f6tlXydcb46fxv2EUvnhwljsjN0-2f1v3o1-1xw-17ygOAPbxR1-h7WP2-ULiywPwbklngMAIwInxRzR1d07C-2gPKwrwaWL1IMQLzk4RTkn2QDQQgIQKALoMt1-xagkG3ynl32-0d2wPBR4MgLYNCSc0YNQOrz+T4OmRMXh2k3QIOQcXkJzEUL60bm2wX0KTgLUJyRgIkKag8l0NkOQJO2KFBhPmv2-VyRUKlmMOMUILMIalMhIJABkIcIoIkN0QAJoNEPWXXxJzOV+3wKUI4MYMWVCysNCIEK0NR0ajwN8O-UcSdUale3cLzhuRtR1kOnsIyJ-3CMWx8LcLINJWtQqyanVVyMFX0JRyaysgSOKNoOqJY3GxC2ENYKSMe0YJYEpVcPSOaM+1iLlRzHaJCL61pTNUb0liKP6KDg5QYJRz1mmKqLmLCMWJxkaRWMBSswrzVVGMSIOWVRizCltiiL6x1UmNzUfwOPOPyJR2xjnS2LDXL26LPSeIzRqJOymLSJKKtWu1iKWL6N+IdQH1qLR32MaL8L9UcIPwkB-iBKaMrU8PuPBWCJuKAUzQWKd2kxmOBMrRA0YNug7hYLGIxJ2O6LgwaNmKPW3gbxIQhOpIRg7XGyrxJPROmUHXGzg2oMhO-SnXGx1i73eOix51iKayE2FPfn+IjxulzSpLxJpKwKGKrx+MRJpMGJlNYFTUlIBxiyllULOKASgyxNhLuisjRN5OfTWK+KXwtMZIHXJPuPblJ2FJQz1Iag3UNOmRAXP25RZklgRKhJ43Dw32QC711lxLVJ400M1LDIlg2y9OERAVFNjJmg7muMtL6xAWlNDLhOJNdK6JR1QXiILPwXG3BUjKDIU2RKdx1hH2kIVKwwCIDzDMznlKjIUwJJRJdwLJiNTLujlWFLyXG1Mx5PtLK19Mazi0DO-QC3G0gXbKrLKxjNDKchzErNnM+IP3VWahnP81MO3KXwzPHMyzNXAN1j3L60QQ1NDJ6QaWPMbNq11JV3QTQMTLzjqxNNiPqLfIbI7P6331iNMn5ztMfP60nLLj0Q7kvMO3EJRzsm6WFNmwTzVzHLAoIRDIRViQNL-KXK2zPIqI3IOSOzNXJy3yQoPNiKsXXIotBJOx+R7PfMuxhO-PBQfP-IIXn1jLslTVAo4vkS-NjPslxhgumTB0AtjPF3Awor7NDKE0eKYqDmx2OKak9Nwu-SJxQvA0XI0ruPou9VEvtxeKIP5wZLAu5zPJSx0uZxaJiysjPT4qXNoSVNjNsnA0ct0rLLspaikKhXHM1zNVfKFMUv7gd0EtDILlUvYqcutOwKa3R2FIdwgrqTTJKXeI91Z3Fklmiv7T93h3l1OPUoqSGUwpbIblUohOvFvH7wkoio4F1kqpvDr2SoZigviwXSqrr1KvuRY2bSrk6v7xXIRVMjulS36qav7xTNDIshzAzIGvH1spfOZiKPmtP0LLMPqrslcNWumT5hvJJwKvcnGuqoWq4rqp8oaJ2uEXrnCoRSsialeyurrliu-Ok0apOrWtkqwrux5KeuoTgo2piQtL+vgRmTstGrZJABBo4T0oP3NJ82OoILKN-x3mko6omr60LimpJ3qrUqhWhrkUWokOeDBkRoOUwMCo9N+oxu-y8pfMYUsL+QJrwTOrup1jxrUWZpEVupbMaV1khq5s4VqpxqjjJsxsdI2qCLFr0NpMYL5r1mlpMLBpV3uqYUVo8O6pORcN-PxppqVqGpbPGTVvRo+qVuxsNr3WptNo8JzIRU7lmvVu8Tou3PXWBr1o8P2pbKzzSpNusOfMYOjmazmvdu8WbJGWwrTV9uiOFsNrizduttDpaq8Dsn5wFpDuaJjvDsCXes6OVsYOwpk0duaM1u5WwvsiLtWORvzvbnuyjvGK3NYtNwru2KJvgt1xzoOV3hctvLgzToToGLPKrw7vrprLhqxWDv7tWLDpOTIosmbrRS7JO3suaz7s6K+pbLcv5nno+NlpR3R2a3ju-QuLsqaitqPthteuyu3rKINpGTIqqyZvTqRPNrvudUuqfuhNbqXouuvv9VIvf1-pYu4p-jPsOP9vgrixWo-ueOnu5WCnHkAcXrhudMeugY+PXpGX3vMOvsbTspC3fsnppKTpQDcvAJwYvtctLUPqtKrvgpiVAb62XTPOH1Xpodtq9rRygcIaZPWoPwQojPIbpvztwwYaNPAfooalEY5IErPIsNQe4YdKQe-L3VYcYYlr4dBisWvrdJVyNvqO0ewxiyNuRTrqAQI0suaikaTOMvovbi3tMe9Ibu4tw22rQdsvYfDrrPkYM14aou1IcesaEfgpC28cs1HqovW2oazJkbsrsaibMZetcpUQMYwa1pagIc3N3pO1fJ6Wvo81Ip-lUYywodDJ-OX0foUeXMCuYLyacfOovNqa-sEIZtCavN8djOTl10ac9vuQLgaYCY-PEewJwPiemU-Pyons3KUY6fqoyf3NSe5WThxisfewBsENTVadgrzpQJDmguvowvyvBRWeYtobMPMP-32bqZJyyt-kuaadiILlLTue7uueWdccqY+3yp-lGeEU4vypxhdQGeYtgcxmApEsuemdvLuipSBaDjB2IeQHgZdNhdCrWe-IHJ+bzk0pizBe4Ovup0Ctwzmal1vov0OlxmJaV3r2Jo9M2Yt3uZmauPxfaYivOeG05rcdoR6Yvy6WZfCY6YKsr2ZZBc6XqQVpRYRgd0zovyytyYlY4CSvh2dzxflYyt-1tVsm3rysyudMxadhKvhyyqFYXR3D3HPqCY2sFJ5NNf3DAf5Yivgw7irhtfPpFbqTBfPWdd3FtduMhZJ1nshpdbAYWa+Sgrlb+SDbUayewNS3IpNe9b5MMd-whQZy9bNZoZLq+Ssn5wzMjbEdOYPzxmlAjYTZoZfoZX4ZtzTZ9fzY8YZW1uRZLfTajZeZbKZm6QtLzekYtcLfNOrcTftYRXOTu07dLbUbdc7x4t3P7atL9ZbPYGcNzbHbEZDbLh6I9NHebYSejaGO4I7k3Zrcce2ad3cjjabcPcCczbLlumLahS7cCdJe5R6JS1cPvbzmTJHI4whLfa3mzMmIeSKJ-aDhAVbZGThNxxneiZ7bFPPMBfPZ8cHfnfJYaKA4oxiYbwYtukg4SbnZGUbw9KXa3ccdXdbjlUYUb2w7GbRaEvJde1Q4RnyfdIHLo+Xao8OT1KCmagPcycfcxhjS4MDdY+EUQXLafb5oSvjaI+E8oqEsZWtaE8GedoBOTko+k+g6Esv0ZrvYU63kQVZpbIfnW3k6k8GYneTqW3g-mele5XVUA506DjqwRfVRago8k4vdWZ3aEsTzs5M5OYRf4+akE987hZKYRVmklmM-c5Od47LnskpNU489E8xiCjJwS5Obre5RKTu2-fs-7gIVA5ORjWWZY+C7y6AdDLlRIRQ9y4Rj+b1Pqp9ss-+zM8kAFx+zS5C9w-rb3W4+IvUbFN4z4Q69Rc89zLzLg+09K8laTcJP9JGuG+m-Y5Vxmkzl65JfnN0Ui88qS7XfpyMLc88oy749tQFwW4VZZbC4ePsaa6pe5afbXPMi25sv07w9jc1YO+Zxa+QGjkkRy6m-O668y-srO-aRI4ZicghrO7VYDsdZcKh-TzNSy6jw+7ZQNeOPMgAZrx7H7BqsBzh6x77Gas90RwJ5x4WqvaGw2LSOx7rxi6G12WPJp8mqdWjyZ4WqO+818rUS7EJ-7wK5lV10Z954Wru8a3I7HLZ7WsQ-uXZshp57J8+p5swaB1Z+F8+us8xkMOp7V92v6+4oDNV4V-II186TYsN6RoRbiwZMl-IIp7p12RmJt6QILYedTT6Kd-YOpb3oaTl49-+oZdZbPb8r99Bv59BcKuD51+d9F8gtxgl6j895e5OQ7fN-JvQ8YNPt94T-+sB6+UYRhekJD5hrB5KCxW16N48JN7qUFLtKL80Rm52dSNT-UNC7Ko43d+z-WRd46brI74r6dp27qUpXL79oD7usalr874GQu8NoRtJ9H5j9biKyz-77EOl+T4yWb70K+8zkd6n-r9z7Lm6RH+iIRd1a35pWo9vMC4v9KLP91iF9X8rrt+Tua3j6f5brp4ZmdMf9zsH4ZjRwr9c6HPVuMUj34f80USnGZv00L7792U5XA6g7Xn6d0hmDzRhMFVgEQD4BX3PpuU0j5YDDkh-OpORxP710S+hSfPlSTr470q+9vBSpgPNYIs+mc9ZAbcSW4SEAW1vOATfUNYllWBZJL3k4WazgDzWIAunBYXf7msw+nSSRJILtaL86cZ2W-laiT6LMzkQA4NkrwZQWFlBDqIgZ3gBYiDg2CLPdlwIIG4NluS+Ugfm384btdB16dgfcUpRyCo2X-G6Itkn7mCrmLZIkpHQYFsNWi90ewYqUmJqprB3bBQV4GGL6N+B3bVQclzPS-9Z2WgzLvfCoHcCoMtArwI92Nr+Dx2Z-DjOkIIE6NhGD-YITxic5L4ihCHF-igFPY8Vyh1ZNwSgBTo5hqhYTf-l4Da4IVGh7jRHkZ16Egci8DSTwQh0iF1D2473PIdu3iFH8amsQ6xjv12QaDom+grwPvRJ7TDiOCLdnAgwWGKcshJDMAkYLabHs4apaJIacNqHIAoKEnLYWp2aE3CzSvQkToax-r7DdOMnB1tkT76ZNpBKVMZKMP3LqcIqeZVzvcMU6zC6kgdWuhCM+E4CfyY1D4Q50SYRV4GeMF4XrwiqmRM4KwrZocN5BNYMB+A2HGcNd64YzBpI64b-ABa9D8KrOaikiLhEhdBB2BVWuMjpFfCScOQvAdz2oFeV-hdOTjkyJJF9cQR3IsAZyPX6LMZM+7TkTgMG6ndkRZXNYSgCgqPd5ROw+9OEKMqjdhqw+E4VSx2FnJLhVLakfzGaiUibKjwhuGTkNH0tOhhSOoqaPpZiCSgUldXMqMW6CiSgeONob0K5Y45DCLo3UVCLpxuVIizI1FgiIeoBjURgRUaiGKxZYiEUpCGJPaNwTQ8UCUFFjI0O1Yq5dopaK0aj0LwVZFkWcYMNICAA)

How could I make it so the tooltip displayed only shows those series which are currently active in the legend?  Is this possible?

(I saw the related issue #1552, but the answer there doesn't seem to be directly applicable. (Not sure?))

Thanks!

**Comment by jakevdp** [comment]
I don't know of any way to change the tooltip content based on a selection.

**Comment by legendre6891** [comment]
Ah that’s too bad! Do you know of another method to achieve something equivalent? Basically the tooltip could become a bit busy if there are many different series.

**Comment by swan-gramer** [comment]
Text label could be a solution in this case. Here is an [example](https://altair-viz.github.io/gallery/multiline_tooltip.html)

**Comment by sfc-gh-cheliu** [comment]
@jakevdp Do you mind if I make a PR to add this feature? Basically we want to filter out/hide zero/null values in the tooltip and possibly sort the tooltip by values. Could you give some pointers?

**Comment by joelostblom** [comment]
@sfc-gh-cheliu That feature would need to be contributed upstream to either the https://github.com/vega/vega-lite or https://github.com/vega/vega-tooltip repo. Feel free to open an issue there with your suggestion. I'm going to close this as there is nothign to do on the altair side of things

**Comment by sfc-gh-cheliu** [comment]
@joelostblom Thanks for the info. Just to double confirm, there's no way to modify altair to achieve this feature? I saw that there's a list of Tooltip objects specifying the fields/column names, can we modify some underlying logic so that if a field has zero or null value, don't let it appear in the tooltip? Or we need to modify https://github.com/vega/vega-lite instead?

**Comment by joelostblom** [comment]
It's possible that you could make that modification in Altair, but to me it sounds like this is a better fit for an upstream contribution to Vega-Lite. We generally want fixes like this to be implemented in vega-lite directly, but I'm not familiar enough with the Tooltip code itself to know if there is any special reason to do this in altair instead

**Comment by sfc-gh-cheliu** [comment]
@joelostblom I found that class Tooltip has a parameter called 'condition' and that might potentially satisfy the need of hiding zero/null values. However, when I try to specify it, I got a `SchemaValidationError: `Tooltip` has no parameter named 'condition' Existing parameter names are: shorthand bin format title aggregate condition formatType type bandPosition field timeUnit See the help for `Tooltip` to read the full description of these parameters` error. Why is this the case?

**Comment by joelostblom** [comment]
I am not sure what is going on there, could you post a reproducible example as a new issue? You can base it off https://altair-viz.github.io/gallery/scatter_tooltips.html

**Comment by sfc-gh-cheliu** [comment]
@joelostblom For the feature I want to add I've opened a new issue here. 
Do you mean the repro for the error? It's easy - either `selection_chart.encoding.tooltip[0].condition = alt.condition(alt.datum.type1 > 0, 'type1', alt.value(''))` or specifying `"tooltip": [alt.Tooltip('Date'),
    #             alt.Tooltip('type1:Q', condition=alt.condition(alt.datum.type1 > 0, 'type1', alt.value('')))]` in the encoding will trigger this error. But my point is if we can add that feature we want, this doesn't matter. Also, based on what I found from the previous asks, even `condition` works, the field may still appear in the tooltip. So I guess the best way is just to add that feature instead of using `condition`. It'd be great if you could take a look here https://github.com/vega/vega-lite/issues/9098. Thank you!!

**Comment by joelostblom** [comment]
Thanks @sfc-gh-cheliu , Could you open a new issue in the altair repo regarding the tooltip not working with the condition although the docs say that it should? Your repro is good, we just need to track it in a separate issue.

**Comment by sfc-gh-cheliu** [comment]
Sure, I've opened a new issue for you to track here https://github.com/altair-viz/altair/issues/3196. Thanks.
