### ISSUE TITLE
How can I visualize a small series

### ISSUE THREAD

**Issue by affernan** [altair-viz/altair#2394]
Hi,

I'm new to using _altair_. I have a grouped stacked bar chart, and I have two series DF1 and DF2. It happens that the values of the DF1 series are always in the range from 1000 to 2000, and in the DF2 series they are in the range higher than 100000. 

![image](https://user-images.githubusercontent.com/51060707/105580859-3ffa3200-5d8f-11eb-9b58-bd46a6b8fd3e.png)

How can I make the small series DF1 be displayed in some way?

```
import pandas as pd
import numpy as np
from altair import *

a = []
b = []
i=0
archivo = open("data.csv")
for line in archivo:
    line = line.strip().split(',')
    dataset = line[0]
    h_emission = float(line[1])
    s_emission = float(line[2])
    p_cost = float(line[3]) 
    
    a.append( [ 0, p_cost ] )
    b.append( [ h_emission, s_emission] )
    if i==3:
        break
    i+=1
    
archivo.close()

df1=pd.DataFrame(a,index=["A","B","C","D"],columns=["I","J"])
df2=pd.DataFrame(b,index=["A","B","C","D"],columns=["I","J"])

def prep_df(df, name):
    df = df.stack().reset_index()
    df.columns = ['c1', 'c2', 'values']
    df['DF'] = name
    return df

df1 = prep_df(df1, 'DF1')
df2 = prep_df(df2, 'DF2')

df = pd.concat([df1, df2])

Chart(df).mark_bar().encode(y=Y('values', axis=Axis(grid=False), scale=Scale(domain=[0, 850000], clamp=True)),
                            x=X('c2:N'), 
                            column=Column('c1:N') ,                            
                            #y = alt.Y('count()', scale=alt.Scale(domain=[0, 120]),                            
                            color='DF:N').configure_view( strokeWidth=0.0).configure_view(width=70, height=200).resolve_scale(
    y='independent'
)
```

regards.

**Comment by jakevdp** [comment]
There are any number of options, depending on how you want it displayed: for example, you could use a log scale in the y axis to better show values of different magnitudes, or you could use a row encoding to put the two DF sets in different rows, for example.

**Comment by affernan** [comment]
> There are any number of options, depending on how you want it displayed: for example, you could use a log scale in the y axis to better show values of different magnitudes, or you could use a row encoding to put the two DF sets in different rows.

**Comment by affernan** [comment]
I have tried the logarithmic scale on the y-axis and it has not helped me much. I would rather use the second options: ..a row encoding to put the two DF sets in different rows.

Any links or example ideas for this last option?
