### ISSUE TITLE
[Question] Draw scatterplot of wedges with encoded size and angle

### ISSUE THREAD

**Issue by dkapitan** [altair-viz/altair#2395]
I want to implement [Zan Armstrong's comet chart](https://www.zanarmstrong.com/infovisresearch) in Altair, for which I need to draw a scatterplot of wedges with encoded start-point and end-points.  I used glyphs in [an earlier implementation in Bokeh](https://github.com/dkapitan/comet-chart).

I have read about `wedge` as one of the available marks, and managed to draw wedges, all with the same configuration e.g. just changing the angle.

```python
import altair as alt
import numpy as np
import pandas as pd

df = pd.DataFrame(
    np.hstack((np.random.randn(100, 2), np.random.randint(0, 360, (100, 1)))),
    columns=["x", "y", "angle"],
)

(alt.Chart(df).mark_point(shape='wedge', angle=135).encode(x="x:Q", y="y:Q"))
```

I was wondering whether it is possible to encode the wedges individually, where the length and direction are determined by the start and endpoint in the dataset. As a first test, I tried to encode `angle='angle:Q` in the example above, but that property isn't defined.

Vega-lite shape mark looks like another possible solution (see [this SO post](https://stackoverflow.com/a/62610941/3197404)) and I see it is accessible in Altair as shown [here](https://altair-viz.github.io/gallery/isotype.html)) but I don't know how to connect the dots.

If someone could point me in the right direction, I am happy to try and contribute a comet chart viz to Altair.

**Comment by mattijn** [comment]
Altair compiles to Vega-lite version 4.8, where the `angle` channel encoding was added in Vega-lite 4.9. See release [docs](https://github.com/vega/vega-lite/releases/tag/v4.9.0) and [wind vector map](https://vega.github.io/vega-lite/examples/point_angle_windvector.html) for an example.

**Comment by dkapitan** [comment]
@mattijn 
I think the solution using SVG paths seems do-able. This provides the basic mechanism I am looking for (thanks to @jakevdp solution on SO I found earlier):

```python
df2 = pd.DataFrame(
    {
        "a": [10,20,30,40],
        "b": [10,20,30,40],
        "c": ["M -1 0 L0 10 L1 0", "M -1 0 L0 -5 L1 0", "M -1 0 L0 -20 L1 0", "M -1 0 L0 -1 L1 0"],
    })
alt.Chart(df2).mark_point().encode(x="a", y="b", shape=alt.Shape('c', scale=None))
```

However, since `scale=None`, I can't relate the SVG path pixels to the actual Cartesian coordinates. I need this to be able to draw the path between the start and end-point. Is there a way to access the scale-conversion from pixels to the axis (and vice versa)?

**Comment by mattijn** [comment]
Or a [trail](https://altair-viz.github.io/gallery/trail_marker.html)-mark
```python
df = pd.DataFrame({"x": [10,20,30,40,20,30], "y": [5,15,30,56,25,25], "d": ['a','a','b','b','c','c'], "s": [0,1,0,1,0,1], 'c': ['x','x','x','x','y','y']})
df.head()
```
<div>
<table>
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>x</th>
      <th>y</th>
      <th>d</th>
      <th>s</th>
      <th>c</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>10</td>
      <td>5</td>
      <td>a</td>
      <td>0</td>
      <td>x</td>
    </tr>
    <tr>
      <th>1</th>
      <td>20</td>
      <td>15</td>
      <td>a</td>
      <td>1</td>
      <td>x</td>
    </tr>
    <tr>
      <th>2</th>
      <td>30</td>
      <td>30</td>
      <td>b</td>
      <td>0</td>
      <td>x</td>
    </tr>
    <tr>
      <th>3</th>
      <td>40</td>
      <td>56</td>
      <td>b</td>
      <td>1</td>
      <td>x</td>
    </tr>
    <tr>
      <th>4</th>
      <td>20</td>
      <td>25</td>
      <td>c</td>
      <td>0</td>
      <td>y</td>
    </tr>
    <tr>
      <th>5</th>
      <td>30</td>
      <td>25</td>
      <td>c</td>
      <td>1</td>
      <td>y</td>
    </tr>
  </tbody>
</table>
</div>

```python
alt.Chart(df).mark_trail().encode(
    x="x", 
    y="y", 
    detail='d',    
    size=alt.Size('s', scale=alt.Scale(range=[1,15]), legend=None),
    color='c'
)
```

![image](https://user-images.githubusercontent.com/5186265/105646278-57284500-5e9f-11eb-95e0-539d7b71f5f8.png)

**Comment by dkapitan** [comment]
@mattijn
Sweet, thank you. This works for me!

**Comment by dkapitan** [comment]
@mattijn 
So I am aiming to contribute an example to the Altair doc. This is  how far I got.

For some reason I can't get the color encoding to work like in your example. Any idea what I'm doing wrong? I understand [Vega doesn't support continuos color encoding for trails](https://github.com/vega/vega/issues/1187), so I was aiming to have a discrete color scale, e.g. just two color for less/more delays. But if I use color encoding, the plot doesn't render all trails anymore. 

```python
import altair as alt
import vega_datasets
import numpy as np
import pandas as pd


# Use airline data to assess statistical mix effects of average delay by desination over time
source = vega_datasets.data.flights_20k.url
flights = pd.read_json(source)

grouped = flights.groupby(by=[flights.destination, flights.date.dt.month])
df = (
    grouped.agg(
        number_of_flights=("destination", "count"),
        mean_delay=("delay", "sum"),
        mean_distance=("distance", "mean"),
    )
    .loc[(slice(None),[1, 3]), :]
    .assign(change_delay= lambda df: df.groupby('destination')['mean_delay'].diff(),
            less_delay= lambda df: df.change_delay < 0)
    .fillna(0)
    .replace(True, 'better')
    .replace(False, 'worse')
    .reset_index()
    .round(2)
)


# trails don't support continuous color, see https://github.com/vega/vega/issues/1187
alt.Chart(df, width=800, height=500).mark_trail(stroke='white').encode(
    x=alt.X("number_of_flights", scale=alt.Scale(type='log')),
    y=alt.Y("mean_delay"),
    detail="destination",
    size=alt.Size("date", scale=alt.Scale(range=[0, 10]), legend=None),
    tooltip=['destination', 'number_of_flights', 'mean_delay', 'mean_distance'],
#     color='less_delay'
)
```

![comet-chart-flight-delays](https://user-images.githubusercontent.com/4090894/106025763-596de780-60c9-11eb-9fc0-ffec566fc87b.png)

**Comment by mattijn** [comment]
Looks interesting! There is something wrong with your data.
<img width="354" alt="image" src="https://user-images.githubusercontent.com/5186265/106028334-1c572480-60cc-11eb-80d9-e814b1c372f4.png">
Observe for destination `ALB` there is both `worse` and `better` for less_delay.

**Comment by dkapitan** [comment]
Ah, good catch. I think I made a mistake with the diff function. Will have
a look

**Comment by dkapitan** [comment]
@mattijn 
So here's a new version, I got the colors to work properly. One other question: I there a better way to add the single trail for `TOTAL`? My code is not very DRY, but I can't figure out how to re-use the chart definition from `base` with new data.

Will send a PR to add this as an example. There was an error in the previous version (sum instead of mean aggregate), hence the plot looks totally different.

```python
import altair as alt
import pandas as pd
import vega_datasets


# Use airline data to assess statistical mix effects of delays
flights = vega_datasets.data.flights_20k()

aggregation = dict(
    number_of_flights=("destination", "count"),
    mean_delay=("delay", "mean"),
    mean_distance=("distance", "mean"),
)

# Compare delays by destination between month 1 and 3
grouped = flights.groupby(by=[flights.destination, flights.date.dt.month])
df = (
    grouped.agg(**aggregation)
    .loc[(slice(None), [1, 3]), :]
    .assign(
        change_mean_delay=lambda df: df.groupby("destination")["mean_delay"].diff(),
    )
    .fillna(method="bfill")
    .reset_index()
    .round(2)
)

# Calculate weigthed average of delays for month 1 and 3
total = (
    flights.groupby(flights.date.dt.month)
    .agg(**aggregation)
    .loc[[1, 3], :]
    .assign(
        change_mean_delay=lambda df: df.mean_delay.diff(),
        destination='TOTAL'
    )
    .fillna(method="bfill")
    .round(2)
    .reset_index()
    .loc[:, df.columns]
)

# trails don't support continuous color, see https://github.com/vega/vega/issues/1187
# hence use bins
base = (
    alt.Chart(df, width=700, height=500)
    .mark_trail(stroke="white")
    .encode(
        x=alt.X("number_of_flights", scale=alt.Scale(type="log")),
        y=alt.Y("mean_delay"),
        detail="destination",
        size=alt.Size("date", scale=alt.Scale(range=[0, 10]), legend=None),
        tooltip=[
            "destination",
            "number_of_flights",
            "mean_delay",
            "change_mean_delay",
            "mean_distance",
        ],
        color=alt.Color(
            "change_mean_delay:Q",
            bin=alt.Bin(step=10),
            scale=alt.Scale(scheme="blueorange"),
            legend=alt.Legend(orient="top"),
        ),
    )
)

total = (
    alt.Chart(total, width=700, height=500)
    .mark_trail(stroke="black")
    .encode(
        x=alt.X("number_of_flights", scale=alt.Scale(type="log")),
        y=alt.Y("mean_delay"),
        detail="destination",
        size=alt.Size("date", scale=alt.Scale(range=[0, 10]), legend=None),
        tooltip=[
            "destination",
            "number_of_flights",
            "mean_delay",
            "change_mean_delay",
            "mean_distance",
        ],
        color=alt.Color(
            "change_mean_delay:Q",
            bin=alt.Bin(step=10),
            scale=alt.Scale(scheme="blueorange"),
            legend=alt.Legend(orient="top"),
        ),
    )
)

base + total
```
![comet-chart-flight-delays](https://user-images.githubusercontent.com/4090894/106175335-48d77300-6196-11eb-81a8-e5f2cd9faf03.png)

**Comment by mattijn** [comment]
Great you worked it correctly! A comet chart is visually appealing and deserves to be an example in both Altair and Vega-Lite, especially with the nicely adopted `trail` mark! But your chart and data preparation is likely too complex.

I also had a try, albeit 1D and Vega-Lite, using the Barley dataset from the [Trellis display](https://vega.github.io/vega-lite/examples/trellis_barley.html).
<img width="401" alt="image" src="https://user-images.githubusercontent.com/5186265/106203354-8a2e4980-61bb-11eb-855b-15957e75df6c.png">

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JACyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICTJLrgBPKTPkBfJZjqC4+gEKmn5gAQBNGnEHKnlBsCDimNNaeTHCYAO5wcLKeAIwAnADMAEyeSLKBaenJiiCY2rkQAGZs2ghoANqgODTEbJj65nCmxcRIggzO6OZ+AcVk2mwMOEzm9SA92n6YM0oQIiAAunagVSOodSAFRUoFmRtKSBCzHV1KQ-7KG1sgUL1QDIJqAyVsAHIMCNFtAAKVSYf6Ua7aACUxQu7U62hATxegjeH0wX1B-zqAHITjj1p5+J4sQhcYcCbDLuhlP51Ej1kpkNoANb6UpIGh6JSJYLKGiyMhoUAAD2FIAqwwegwRxSWOC+1X5sl6cscA1k70EdhAM00Eql+nmi2WJXMCv0shCAtVOtp6i54sl9yN4RipvlXytCBteh1qwAXgNtobBob7OavgBHBi5BzqBykYrQXrBkBlQUDOoABgUyWzmyUTjIiWloB6fTg1LqmVzADYCzr405XO4LD4pZ4gUwGBB4IIIAQkFBtHAYU22GxBA4cPUQy6ZTczRb0DG43Q1M1nE9nbtdeHl17rSq-YznlPqk7Qyo6SgIyuQGvZPHN0mVii08oQpzZABZGjStmTbqvovj3J4AAit5dgApOOSjBH0CDyPqu7SiAqwYnKkb6EqvpIjqwSyJKQr6sWpbitUfjPvoTCtJgITFPyo5QA4cj6DAVEBnI6h+jYNhAA)

Thanks for introducing me to these comet charts!

**Comment by dkapitan** [comment]
@mattijn

Thx, just want to check whether you want me to submit a PR or leave it (in which case I'll probably write a blog post or something like that).

Also, could you tell me whether there's a better way to re-use chart definitions so I don't need to copy the whole lot just to add the `TOTAL` mark?

**Comment by mattijn** [comment]
I would say its best to replicate the Vega-Lite example gallery where possible. Since https://github.com/vega/vega-lite/pull/7189 is merged, it would be really nice if you can make a PR based on the following altair code:

```python
import altair as alt
import vega_datasets

(
    alt.Chart(vega_datasets.data.barley.url)
    .transform_pivot("year", value="yield", groupby=["variety", "site"])
    .transform_fold(["1931", "1932"], as_=["year", "yield"])
    .transform_calculate(calculate="datum['1932'] - datum['1931']", as_="delta")
    .mark_trail()
    .encode(
        x=alt.X('year:O', title=None), 
        y=alt.Y('variety:N', title='Variety'),
        size=alt.Size('yield:Q', scale=alt.Scale(range=[0, 12]), legend=alt.Legend(values=[20, 60], title='Barley Yield (bushels/acre)')),
        color=alt.Color('delta:Q', scale=alt.Scale(domainMid=0), legend=alt.Legend(title='Yield Delta (%)')),
        tooltip=alt.Tooltip(['year:O', 'yield:Q']),
        column=alt.Column('site:N', title='Site')

    )
    .configure_view(stroke=None)
    .configure_legend(orient='bottom', direction='horizontal')
    .properties(title='Barley Yield comparison between 1932 and 1931')
)
```
<img width="455" alt="image" src="https://user-images.githubusercontent.com/5186265/106323130-32551880-6277-11eb-9cee-84e36195bae3.png">

To re-use chart definitions I would suggest to read https://altair-viz.github.io/user_guide/compound_charts.html#layered-charts. Thats for multiple chart definition given a single datasource. I've never seen Altair code in the wild where a single spec is used for multiple datasets without wrapping it into a function etc. 

<details><summary>It's possible though, but I would say, very bad practice.</summary>
<p>

_an example, that hopefully stays unseen_

```python
import altair as alt
import pandas as pd
import copy

# multiple datasource
source_A = pd.DataFrame({
    'a': [1, 2, 3],
    'b': [1, 2, 3]
})

source_B = pd.DataFrame({
    'a': [8, 9, 10],
    'b': [8, 9, 10]
})

# single chart definition
chart_A = alt.Chart().mark_bar().encode(
    x='a:Q',
    y='b:Q'
)

# duplicate chart definition
chart_B = copy.deepcopy(chart_A)

# define altair Datasets object
ds = alt.Datasets().from_dict({'data_A':source_A.to_json(orient='records'), 'data_B':source_B.to_json(orient='records')})

# assign data-name to chart
chart_A.data = {'name': 'data_A'}
chart_B.data = {'name': 'data_B'}

# combine charts and include dataset
alt.layer(chart_A, chart_B, datasets=ds)
```
<img width="454" alt="image" src="https://user-images.githubusercontent.com/5186265/106323849-6250eb80-6278-11eb-9934-b51d047bbba9.png">

</p>
</details>

**Comment by dkapitan** [comment]
@mattijn 
Thanks for the suggestions. I have just finished up writing [a short blog post](https://medium.com/de-dataverbinders/comet-charts-in-python-visualizing-statistical-mix-effects-and-simpsons-paradox-with-altair-6cd51fb58b7c).

Happy to contribute. Your plot with the barley yield data, however, is not quite what is meant with a comet chart (although it does borrow elements from it). So just to check, I can submit a PR with the barley yield example, and we'll just leave the rest of my work in the blogpost if that's what you mean.

**Comment by mattijn** [comment]
Nice blog post! Yes, that would be much appreciated!

**Comment by morberg** [comment]
I think @dkapitan’s blog post is really nice and shows a new type of graph not currently in the altair examples. I think it should be added to the case studies section of examples.

**Comment by dkapitan** [comment]
@morberg happy to hear that you like it :smile: Just let me know what I can do to contribute. Perhaps add it as a tutorial or case study somewhere? It helped me to understand and use the different features of Altair, so others may benefit from that, too.

**Comment by morberg** [comment]
It is up to  @jakevdp to decide what goes in and where. This thread might be difficult to follow since it started as a question.

I would close this issue and create a new separate issue offering to create a PR to include your example. Jake will most likely chime in with what is needed.

**Comment by dkapitan** [comment]
Agree, let's close this and open a new issue if required.

**Comment by joelostblom** [comment]
I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved and the PR was merged so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
