### ISSUE TITLE
Text not displaying in bar chart

### ISSUE THREAD

**Issue by Dave-Hdz** [altair-viz/altair#2396]
Hello, 

I'm working with the following dataframe and I'm having an issue with the bars in orange are not displaying the text as if they are not finding a value to display even though the data is there.

my code and data here. this code is only for the left side, the right side is working fine.
```python
l = alt.Chart(mlt).mark_bar().encode(
    y = alt.Y('Top_City', sort=alt.EncodingSortField(field="FARS_PerCapita",order='ascending', op='max'), axis=None),
    x = alt.X('FARS_PerCapita',sort='descending',
             axis=alt.Axis(title=None)),
    color = alt.Color('Type',
                      scale=alt.Scale(domain=['non_fatal', 'fatal'],
                                      range=['blue', 'orange']),
                     legend=alt.Legend(orient='bottom', labelLimit = 200))  
)

text = l.mark_text(
    align='right',
    baseline='middle',
    dx=-15 
).encode(
    text='FARS_PerCapita'
)
```

![image](https://user-images.githubusercontent.com/62393931/105921281-a8067d80-6006-11eb-806c-f36f5700a779.jpeg)

![image](https://user-images.githubusercontent.com/62393931/105921088-6c6bb380-6006-11eb-879b-855fb0b81d40.jpeg)

**Comment by jakevdp** [comment]
Try using `text='max(FARS_PerCapita)'` to match what is used in the y encoding.

**Comment by Dave-Hdz** [comment]
It didn't solve it.  I tried using count `text='count(FARS_PerCapita)'` to see if it was doing something and I can see the count for the blue portion but still nothing on the orange.

**Comment by jakevdp** [comment]
If you could include a minimal reproducible example of the issue, I may be able to help.

**Comment by Dave-Hdz** [comment]
This dataframe replicates the issue with the altair code above.
```
data = {'Top_City':['NY', 'NY', 'Seattle', 'Seattle', 'KC', 'KC', 'Macon', 'Macon'], 
        'Type':['non_fatal', 'non_fatal', 'non_fatal', 'non_fatal', 'fatal', 'fatal', 'fatal', 'fatal'],
        'FARS_PerCapita':[16.17, 16.17, 18.31, 18.31, 171.29, 171.29, 158.66, 158.66]} 

mlt = pd.DataFrame(data) 
```
Thank you for your help!

**Comment by jakevdp** [comment]
The text is there, it is just in the middle of the bars, which you can see by using
```python
text.encode(color=alt.value('black'))
```
Why? Well, there are two values per bar, and bars stack by default while text does not.

How to proceed depends on how you want to display the duplicated data, but I'd suggest an aggregate operation (e.g. `sum` or `mean`) in the x encoding to handle the duplicated values.

**Comment by Dave-Hdz** [comment]
That makes total sense. I didn't realize that the bars were stacked (of course they were, I'm doing a stack bar).  I thought that they were overlaid on top of each other because of the same name of the encoding.

I was able to fix it with your suggestion of using max in the X encoding in the bar chart.

Thank you so much!

![image](https://user-images.githubusercontent.com/62393931/106039228-ddfb3e80-60a6-11eb-923c-37dd2b49b879.png)

**Comment by Dave-Hdz** [comment]
Fixed
