### ISSUE TITLE
Pandas dtype: Float64 is not supported

### ISSUE THREAD

**Issue by tzipperle** [altair-viz/altair#2398]
Hi,

I have installed: python 3.8.6, pandas 1.2.1 and altair 4.1.0.  In the pandas version 1.2.0 they introduced a new "experimental" data type for nullable floats. I know that this type is experimental but a proper handling for nullable data is really convenient. 

When I use this new type with altair I get a type error:

```python
df = pd.DataFrame({'a': [1, 2, 3, 4, 5], 'b': [1.1, 2.5, np.nan, 1, 3.3]})
df = df.convert_dtypes()  # convert b from float64 to Float64
chart = alt.Chart(df).mark_line().encode(
    x='a',
    y='b'
)
```

> TypeError: Cannot interpret 'Float64Dtype()' as a data type

**Comment by jakevdp** [comment]
I cannot reproduce this error with your code using the most recent Altair and Pandas releases (4.1.0 and 1.1.5 respectively). What package versions are you using?

**Comment by jakevdp** [comment]
Thanks - it looks like `np.issubdtype` does not understand pandas nullable dtypes, which is unfortunate.

**Comment by jakevdp** [comment]
Indeed, it seems to have broken dask as well: https://github.com/dask/dask/issues/7156
