### ISSUE TITLE
`DatumType` and `Selection` instances are not deep copyable.

### ISSUE THREAD

**Issue by matthewwardrop** [altair-viz/altair#2402]
Thanks for your work on Altair, which makes generating VegaLite plots in Python super easy.

One issue I've come across is that you cannot deep-copy some of the object types because the `__getattr__` implementations of some objects are too broad (i.e. https://github.com/altair-viz/altair/blob/master/altair/expr/core.py#L14, https://github.com/altair-viz/altair/blob/d862ad494ecc0a5cff7e8b114df14e0796efa108/altair/vegalite/v3/api.py#L196, https://github.com/altair-viz/altair/blob/d862ad494ecc0a5cff7e8b114df14e0796efa108/altair/vegalite/v4/api.py#L196). These methods return a result for *any* request, including Python magic attributes of form `__<name>__`, which causes issues for modules like `copy.deepcopy` which looks for a `__deepcopy__` method on the object being copied to see if the copying behaviour has been overridden.

Would you be willing to accept patches to fix this? Or is this done intentionally?

**Comment by jakevdp** [comment]
This was done intentionally, becuase charts may have a column named `__deepcopy__` in which case `alt.datum.__deepcopy__` is how you would access that attribute within an expression.

But that's probably a rare case, and `alt.datum['__deepcopy__']` is a reasonable workaround. I'd be open to a change that makes `__getattr__` return an `AttributeError` for dunder attributes.
