### ISSUE TITLE
Adding labels to line chart using value from transform_calculate

### ISSUE THREAD

**Issue by morberg** [altair-viz/altair#2405]
Based on  [this SO answer from Jake](https://stackoverflow.com/questions/61194028/adding-labels-at-end-of-line-chart-in-altair) I can make a line chart with a label at the end:
```python
import altair as alt
from vega_datasets import data

source = data.stocks()

base = alt.Chart(source).properties(width=550)

line = base.mark_line().encode(
    x='date',
    y='price',
    color=alt.Color('symbol', legend=None)
)

labels_ok = base.mark_text(align='left', dx=3).encode(
    alt.X('date', aggregate='max'),
    alt.Y('price', aggregate={'argmax': 'date'}),
    alt.Text('symbol')
)

line + labels_ok
```
<img width="667" alt="image" src="https://user-images.githubusercontent.com/956034/107878500-754bf880-6ed3-11eb-9d76-fb4d2044fcb2.png">

But when I include the price in the label with a calculate transform the aggregate function no longer seems to be applied?
```python
import altair as alt
from vega_datasets import data

source = data.stocks()

base = alt.Chart(source).properties(width=550)

line = base.mark_line().encode(
    x='date',
    y='price',
    color=alt.Color('symbol', legend=None)
)

labels_not_ok = base.mark_text(align='left', dx=3).encode(
    alt.X('date', aggregate='max'),
    alt.Y('price', aggregate={'argmax': 'date'}),
    alt.Text('label:N')
).transform_calculate(
    label=alt.datum.symbol + ': ' + alt.datum.price
)

line + labels_not_ok
```
<img width="710" alt="image" src="https://user-images.githubusercontent.com/956034/107878537-a7f5f100-6ed3-11eb-96f3-92210f4512c6.png">

Is it possible to add a label including data and make it look like the first example (i.e. only one label per series).

**Comment by jakevdp** [comment]
Since you didn't aggregate the text, every text entry will be shown. You need to use the argmax there, and add a detail encoding if you want a label for each line:
```python
import altair as alt
from vega_datasets import data

source = data.stocks()

base = alt.Chart(source).properties(width=550)

line = base.mark_line().encode(
    x='date',
    y='price',
    color=alt.Color('symbol', legend=None)
)

labels_not_ok = base.mark_text(align='left', dx=3).encode(
    alt.X('date', aggregate='max'),
    alt.Y('price', aggregate={'argmax': 'date'}),
    alt.Text('label:N', aggregate={'argmax': 'date'}),
    detail=alt.Detail('symbol')
).transform_calculate(
    label=alt.datum.symbol + ': ' + alt.datum.price
)

line + labels_not_ok
```
![visualization - 2021-02-14T094646 337](https://user-images.githubusercontent.com/781659/107884377-91d33b00-6ea9-11eb-97a6-9a9b3a11f2c3.png)

**Comment by morberg** [comment]
Thank you very much, not only for the working code but also for the explanation. Much appreciated!
