### ISSUE TITLE
Support "week" TimeUnit

### ISSUE THREAD

**Issue by xujiboy** [altair-viz/altair#2407]
Hi,

Currently in version 4.1.0 there is no support of "week" (week of year) TimeUnit or transform ([link](https://altair-viz.github.io/user_guide/transform/timeunit.html?highlight=timeunit)), but `vega-lite` does support it ([link](https://vega.github.io/vega-lite/docs/timeunit.html#transform)). May I know if "week" will be supported in the future? Many thanks.

Ji

**Comment by jakevdp** [comment]
The week timeUnit was added in Vega-Lite 4.11; Altair currently supports Vega-Lite 4.8.

**Comment by xujiboy** [comment]
Thank you very much for the explanation @jakevdp . May I know if this info ("Altair currently supports Vega-Lite 4.8") can be found somewhere in the documentation site or the github repo?

**Comment by jakevdp** [comment]
```python
>>> import altair as alt
>>> print(alt.VEGALITE_VERSION)
4.8.1
```

**Comment by xujiboy** [comment]
Thank you so much!

**Comment by suddenlyfleck** [comment]
Is it correct that we are still on Vega-Lite 4.8.1 ?

I, too, have srong need for a 'week' Time Unit.

Thanks for the work on altair! Otherwise it's incredibly amazing!

**Comment by xujiboy** [comment]
> Is it correct that we are still on Vega-Lite 4.8.1 ?
> 
> I, too, have srong need for a 'week' Time Unit.
> 
> Thanks for the work on altair! Otherwise it's incredibly amazing!

Yes I think we are still on vega-lite 4.8.1

**Comment by joelostblom** [comment]
Altair 4.2.0 is using vega-lite 4.17 so closing this
