### ISSUE TITLE
[Questions] How to cancel the automatic sorting during visualization？

### ISSUE THREAD

**Issue by Meng-Ziwei** [altair-viz/altair#2409]
```python
import pandas as pd
import altair as alt
from vega_datasets import data
df=pd.DataFrame({
    'Data':['Friday 8th','Friday 10th','Friday 12th','Friday 14th'],
    'temperature':['8','10','12','14']
})
alt.Chart(df).mark_line().encode(
alt.X('Data'),
alt.Y('temperature')
).properties(
   width=400,
   height=200
)
```
At that time, we can see 
<img width="740" alt="截屏2021-02-18 16 00 06" src="https://user-images.githubusercontent.com/78152357/108324042-61213780-7202-11eb-971b-aeadfadd2e1b.png">

In this chart, axis-x is sorted by the letters of "Date". However, because the sequence of my data is right, I hope Altair stop to help me to sort "Date". Therefore, I change the code and plus "sort=None" like this 
```python
 alt.Chart(df).mark_line().encode(
alt.X('Data',sort=None),
alt.Y('temperature')
).properties(
   width=400,
   height=200
)
```
Finally, I get this 
<img width="667" alt="截屏2021-02-18 16 02 44" src="https://user-images.githubusercontent.com/78152357/108324344-beb58400-7202-11eb-80b2-8d564e19f859.png">

and in this picture, even it follows the sequence in my own data, it actually lines by the order before and we can see the lines overlapping. 

My question is, how can we stop sorting automatically by Altair?

**Comment by jakevdp** [comment]
You can specify the order of the line connections using the `order` channel, as demonstrated in this example: https://altair-viz.github.io/gallery/connected_scatterplot.html

For your data, a useful approach is to create a new field that contains the data order:
```python
alt.Chart(df).transform_window(
  order='count()'  
).mark_line().encode(
  alt.X('Data', sort=None),
  alt.Y('temperature:Q'),
  alt.Order('order:Q')
).properties(
   width=400,
   height=200
)
```
![visualization - 2021-02-18T061332 650](https://user-images.githubusercontent.com/781659/108369436-70779500-71b0-11eb-9c3a-a8598fa733f7.png)

**Comment by Meng-Ziwei** [comment]
Thank you very much for your accurate answer and enthusiasm! You really help me a lot during the use of Altair!!

**Comment by joelostblom** [comment]
I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
