### ISSUE TITLE
Facets / trellis plots with independent-scaled axes

### ISSUE THREAD

**Issue by pteehan** [altair-viz/altair#241]
Hello, 

In R/ggplot2 one can make a trellis chart with independent axes in each chart -- see the 'scales' argument: http://docs.ggplot2.org/0.9.3.1/facet_grid.html

As far as I can tell there is no way to do this in Altair - all charts have common axes.  

A use case for this: I have a dataframe with several related time series, I want to plot them all in a trellis plot to see how they move together, but they have vastly different magnitudes, so I need each y-axis to scale independently.  The only work-around I know is to manually normalize each series before plotting.  I hit this problem a lot.  Is there a way to do this?

**Comment by jakevdp** [comment]
Currently I don't think so, but with the upcoming Vega-Lite 2.0 release (and associated Altair 2.0 release), there are going to be many more options for this type of flexible plot composition. Maybe @kanitw can comment?

**Comment by kanitw** [comment]
We have this kind of the features planned in [the grammar](http://idl.cs.washington.edu/papers/vega-lite).  So very likely we will include the implementation in 2.0.

**Comment by pteehan** [comment]
That's great to hear.  Any rough timeline on the 2.0 release?  It sounds like it's going to be fantastic.  Thanks

**Comment by kanitw** [comment]
Currently we hope to release by the end of the year, but we just started the development so it might slip into Q1 of 2017. (Hopefully not!)

**Comment by ellisonbg** [comment]
Closing as vega-lite-related.
