### ISSUE TITLE
Custom sort in faceted chart not working

### ISSUE THREAD

**Issue by xujiboy** [altair-viz/altair#2416]
Hi,

I have encountered this following problem, which is reproducible as shown in this [Colab](https://colab.research.google.com/drive/168ZV-DRb6K2NUYwAOzC9OmBdOOxE02ii?usp=sharing).

```python
from vega_datasets import data
import altair as alt
import pandas as pd

df = data.cars()

selection = alt.selection_single(fields=["Cylinders"], empty="all", bind="legend")

chart = alt.Chart(df).mark_point().encode(
    x = alt.X("year(Year):T", axis={"labelAngle":-30}),
    y = alt.Y("mean(Horsepower):Q"),
    color = "Cylinders:O",
    row = alt.Row("Origin:O", sort=["USA", "Japan", "Europe"])
).add_selection(
    selection
).transform_filter(
    selection
).properties(height=100, title = 'sort in `row=alt.Row(..., sort=["USA", "Japan", "Europe"])` not working')
```
In the chart the specified order for `row`s is ignored:
![visualization (4)](https://user-images.githubusercontent.com/10766549/108785734-e2d8d400-7526-11eb-9573-da8fd5ee8cbc.png)

I am not sure if this can be addressed by pulling the facet statement out of encoding statement, so I tried the following:
```python
chart2 = alt.Chart(df).mark_point().encode(
    x = alt.X("year(Year):T", axis={"labelAngle":-30}),
    y = alt.Y("mean(Horsepower):Q"),
    color = "Cylinders:O"
).add_selection(
    selection
).transform_filter(
    selection
).facet(
    row = alt.Row("Origin:O", sort=["USA", "Japan", "Europe"])
).properties(height=100)
```
But this time I got an error:
```python
---------------------------------------------------------------------------
SchemaValidationError                     Traceback (most recent call last)
/usr/local/lib/python3.6/dist-packages/altair/vegalite/v4/api.py in to_dict(self, *args, **kwargs)
    380         if dct is None:
    381             kwargs["validate"] = "deep"
--> 382             dct = super(TopLevelMixin, copy).to_dict(*args, **kwargs)
    383 
    384         # TODO: following entries are added after validation. Should they be validated?

5 frames
/usr/local/lib/python3.6/dist-packages/altair/utils/schemapi.py in to_dict(self, validate, ignore, context)
    337                 self.validate(result)
    338             except jsonschema.ValidationError as err:
--> 339                 raise SchemaValidationError(self, err)
    340         return result
    341 

SchemaValidationError: Invalid specification

        altair.vegalite.v4.api.Chart, validating 'required'

        'data' is a required property
```

May I know if this is a bug? Or is there a better way to specify custom sort order for facets in faceted charts?
(`altair` == 4.1.0)

**Comment by joelostblom** [comment]
Thanks for opening this issue @xujiboy , this particular problem has already been reported in https://github.com/altair-viz/altair/issues/1683 and https://github.com/altair-viz/altair/issues/2046. It is due to an issue in Vega-Lite being tracked in https://github.com/vega/vega-lite/issues/5366. For a workaround you can compute the mean in a transform as per this comment https://github.com/altair-viz/altair/issues/2046#issuecomment-605376204. Could you close this issue as it is a duplicate?

**Comment by xujiboy** [comment]
Thank you very much @joelostblom for the expansions and workaround references. Closing as requested.
