### ISSUE TITLE
How can you change color lines color= ? depending on the value of the field?

### ISSUE THREAD

**Issue by fredgi123** [altair-viz/altair#2422]

**Comment by fredgi123** [comment]
Is there a way to change the color of the lines depending on the "symbol value"? 
e.g. if symbol="AAPL" then color is "black", if symbol="AMZ" then it's "green etc.

**Comment by joelostblom** [comment]
If you want to change default color to value pariing you can specify the `sort` parameter to `alt.Color` with a list of your values. You could also set the range of color used or pass a column with raw values, [both are showen here in the docs](https://altair-viz.github.io/user_guide/customization.html#color-domain-and-range)

**Comment by joelostblom** [comment]
@fredgi123 I saw that you added a thumbs up to my comment above so I am going to close this issue as solved. Please feel free to reopen it and add a comment if there is anything still unresolved that you would like help with.
