### ISSUE TITLE
Arranges to run examples from Altair's Density Transform

### ISSUE THREAD

**Issue by vcuspinera** [altair-viz/altair#2426]
I was trying to run the [Density Transform examples](https://altair-viz.github.io/user_guide/transform/density.html) from Altair's users guide, but they didn't work out, so I made some arranges and could run them. I just wanted to share the changes that I made to make them work in case you want to double check the examples and make any corrections.

## First plot -simple example-

__Original code:__
```
import altair as alt
from vega_datasets import data

alt.Chart(data.movies.url).transform_density(
    'IMDB_Rating',
    as_=['IMDB_Rating', 'density'],
).mark_area().encode(
    x="IMDB_Rating:Q",
    y='density:Q',
)
```

__Changes to make it work:__
```
import altair as alt
from vega_datasets import data

alt.Chart(pd.read_json(data.movies.url)).transform_density(
    'IMDB Rating',
    as_=['IMDB_Rating', 'density'],
).mark_area().encode(
    x="IMDB_Rating:Q",
    y='density:Q',
)
```

<img width="346" alt="image" src="https://user-images.githubusercontent.com/53915521/110157821-43310680-7dae-11eb-8741-96298c9d9a82.png">

## Second plot -facet density plots-

__Original code:__
```
import altair as alt
from vega_datasets import data

alt.Chart(
    data.movies.url,
    width=120,
    height=80
).transform_filter(
    'isValid(datum.Major_Genre)'
).transform_density(
    'IMDB_Rating',
    groupby=['Major_Genre'],
    as_=['IMDB_Rating', 'density'],
    extent=[1, 10],
).mark_area().encode(
    x="IMDB_Rating:Q",
    y='density:Q',
).facet(
    'Major_Genre:N',
    columns=4
)
```

__Changes to make it work:__
```
import altair as alt
from vega_datasets import data

alt.Chart(
    pd.read_json(data.movies.url),
    width=120,
    height=80
).transform_filter(
    'isValid(datum["Major Genre"])'
).transform_density(
    'IMDB Rating',
    groupby=['Major Genre'],
    as_=['IMDB_Rating', 'density'],
    extent=[1, 10],
).mark_area().encode(
    x="IMDB_Rating:Q",
    y='density:Q',
).facet(
    'Major Genre:N',
    columns=4
)
```

<img width="448" alt="image" src="https://user-images.githubusercontent.com/53915521/110157884-52b04f80-7dae-11eb-8f40-9571c8a004c2.png">

## Spelling
Also there was a spelling mistake with the words __density__ in the following paragraph:
> _The density can also be computed on a per-group basis, by specifying the groupby argument. Here we split the above __density__ computation across movie genres:_

**Comment by jakevdp** [comment]
I suspect you need to update your version of `vega_datasets`.

I'd prefer not to use your updated versions in the website, because it embeds the entire movies dataset as a JSON string in the page source multiple times, making it work poorly for folks with slower internet connections.

**Comment by firasm** [comment]
@vcuspinera did that fix your issue? I think we can close the issue right? Though I did note that you found a spelling fix  -maybe as a small PR?

**Comment by vcuspinera** [comment]
Yes @firasm, you are right! You can close the issue! Thanks for follow-up to the issue
