### ISSUE TITLE
Include only referenced columns in the data of each chart specification

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2428]
The main goal of this suggestion is to reduce chart sizes, by including only the necessary data.

I read in https://github.com/altair-viz/altair/issues/1250#issuecomment-457318979 that similar initiatives were abandon previously because it would be too complex to determine which columns VegaLite needs from the Python side, especially for complex charts.

However, I noticed that [altair-transformer](https://github.com/altair-viz/altair-transform#example-pre-aggregating-large-datasets) already drops unused columns when preaggregating data. Maybe it is the same limitation that prevents it from working with compound charts etc, but the current functionality is already quite useful. Could it be added as a data transformer, so that it was not needed to be called on each chart separately?

If not, do you think there would room to add something less elegant that is not compatible with arbitrarily complex chart layouts, but still practical in many cases? I am naively imagining parsing the chart dictionary `'field'` keys and any dictionary string values containing `'datum.'` for column names, and filter the data with those.

---

Please follow these steps to make it more efficient to respond to your feature request.

- [x] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most feature requests should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example.
- [x] Search for duplicate issues.
- [x] Describe the feature's goal, motivating use cases, and its expected behavior.

**Comment by jakevdp** [comment]
This is only going to get more difficult with future versions of Vega-Lite, as virtually any chart property can refer to any column via [Expression References](https://vega.github.io/vega-lite/docs/types.html#exprref). I'm very sympathetic to the problem that motivates this (large chart sizes), but the implementation is not going to be trivial.

**Comment by jakevdp** [comment]
As for the partial solution that will break charts in general, you'd also have to look at `groupby` attributes of transforms, and other similar places that columns may be depended on.

**Comment by firasm** [comment]
As a user (and teacher) of Altair, I second @joelostblom's point here:

> ...do you think there would room to add something less elegant that is not compatible with arbitrarily complex chart layouts, but still practical in many cases? I am naively imagining parsing the chart dictionary 'field' keys and any dictionary string values containing 'datum.' for column names, and filter the data with those.

Obviously it's not possible to have your cake and eat it too, so perhaps use of Expression References, and other transforms might be a worthwhile compromise to permit speedy plots of large datasets ?

@domoritz, do you have any thoughts on this? I imagine this particular issue is not limited to just Altair, but all Vega and Vega lite graphs. 

I have been following the progress of [scalable-vega](https://github.com/vega/scalable-vega) ([Demo here](https://vega.github.io/scalable-vega/) and it looks very promising.

**Comment by joelostblom** [comment]
Since this is not possible in VegaFusion and we closed the PR we had in Altair, I am going to close this as well. Please comment if you think this should be re-opened and preferred over the VegaFusion approach:

> The VegaFusion mime renderer can be used to overcome the Altair [MaxRowsError](https://altair-viz.github.io/user_guide/faq.html#maxrowserror-how-can-i-plot-large-datasets) by performing data-intensive aggregations on the server **and pruning unused columns from the source dataset**. First install the vegafusion Python package with the embed extras enabled

**Comment by jonmmease** [comment]
The [VegaFusion Mime Renderer](https://vegafusion.io/mime_renderer.html) supports this functionality for the Vega specifications that are included in notebook files, but we don't have a function yet to apply this logic before writing to HTML files. I opened https://github.com/hex-inc/vegafusion/issues/292 to track this use case.
