### ISSUE TITLE
Error in documentation: Quantitative Encoding

### ISSUE THREAD

**Issue by Make42** [altair-viz/altair#2435]
At https://altair-viz.github.io/user_guide/encoding.html#effect-of-data-type-on-axis-scales there are two images that show the effect of using `quantitative` data (a third one is about using `ordinal` data, but I do not adress this here). One is supposed to show how the graph would look like if the default `alt.Scale(zero=True)` is used and one i`alt.Scale(zero=False)` is used. However, both grahps are identical. I think the first one is actually wrong.

**Comment by jakevdp** [comment]
Thanks - that's something that changed in previous versions of the Vega-Lite renderer, and Altair's documentation has not yet been updated to reflect that.

**Comment by joelostblom** [comment]
There is now an example of the effect of `zero=False` here https://altair-viz.github.io/user_guide/customization.html?highlight=zero%20false#adjusting-axis-limits
