### ISSUE TITLE
Error in documentation: Composing Multiple Selections

### ISSUE THREAD

**Issue by Make42** [altair-viz/altair#2437]
I am sure the graphic in https://altair-viz.github.io/user_guide/interactions.html#composing-multiple-selections should be interactive, but it is not.

**Comment by jakevdp** [comment]
Can you try interacting with it while holding down the shift key or alt key?

**Comment by Make42** [comment]
Yes, I was just about to delete this issue, after noticing that I overlooked the respective note. It's all good. My Linux Kubuntu 20.04, running Brave browser is already using ALT to move the browser window, so I cannot use ALT - but that is not a bug of Altair. It is just unfurtunate.
