### ISSUE TITLE
Get selection as DataFrame

### ISSUE THREAD

**Issue by Make42** [altair-viz/altair#2440]
As Altair allows for quite a bit of interaction, a user can select a subset of data with the vartious selectors. I would like to know what the user selected. In other words, I would like to get the selected data as a pandas DataFrame (or something I can turn into a DataFrame) returned by Altair.

Possible use cases:

- Use Altair as front-end for human-in-the-loop machine learning
- Display the results of an approximative calculation and let the user decide which values should be re-caclulated more accurately.
- Allow the user to create custom - e.g. 2D - datasets that can be used to test algorithms - e.g. by using the "drawing" setup with `toggle=False` in https://altair-viz.github.io/user_guide/interactions.html#multiple-selections

**Comment by jakevdp** [comment]
No, there's no way to do this. See #1153 for details.

**Comment by joelostblom** [comment]
Closing as duplicate.
