### ISSUE TITLE
Configure parameters (here scales) of plot interactively

### ISSUE THREAD

**Issue by Make42** [altair-viz/altair#2442]
Would it be possible to add the possiblity to add a radio button, a checkbox or something similar to allow parametrization of the plot that is not the data directly? I would like to use a checkbox to indicate whether an axis (here the x-axis) should be displayed normally or in log-scale.

**Comment by joelostblom** [comment]
This is something that would need to be added to Vega-Lite before it would be available in Altair. You can ask on their issue tracker to find out if there are anyplans for it (there might already be an open issue).

**Comment by Make42** [comment]
@joelostblom : Is the answer of https://github.com/vega/vega-lite/issues/7361 helping? I am so new, that I am not sure exactly what domoritz is talking about.

**Comment by jakevdp** [comment]
`params` is what `selections` have evolved into in Vega-Lite 5.0. Altair doesn't yet support this.

**Comment by mjohnson11** [comment]
Just checking on this - am I right in understanding that it is not possible to use params in altair as of now?

**Comment by mattijn** [comment]
No. Follow PR https://github.com/altair-viz/altair/pull/2528 for this feature.

**Comment by binste** [comment]
With the release of Altair 5, you can now use Parameters which should address this use case.
