### ISSUE TITLE
Setting custom domain in time axis

### ISSUE THREAD

**Issue by guibor** [altair-viz/altair#2444]
I tried the approach suggested in https://github.com/altair-viz/altair/issues/2296, but it doesn't seem to work for me:

```
>> alt.DateTime('2016-12-15')

SchemaValidationError: Invalid specification

        altair.vegalite.v4.schema.core.DateTime->date, validating 'type'

        '2016-12-15' is not of type 'number'
```

and for the other options here using `domain=['2019-01-01', '2020-01-01']` for example, and get the error:

```
     altair.vegalite.v4.schema.channels.X->0->domain, validating 'type'

        ['2019-01-01', '2020-01-01'] is not of type 'boolean'

```

**Comment by jakevdp** [comment]
Thanks for the report. Can you provide a [Complete working example](https://stackoverflow.com/help/minimal-reproducible-example) of the code that is resulting in an error, to take the guesswork out for the person attempting to answer your question?

**Comment by guibor** [comment]
Understood, I was under the impression that `alt.DateTime` string values were going to be supported in the next version (the thread is from 2018) - sorry for the misunderstanding.
