### ISSUE TITLE
configure_legend being seemingly ignored

### ISSUE THREAD

**Issue by BenAbyss** [altair-viz/altair#2448]
I've been trying to modify my graph such that the color guide is on the left hand side of the graph. However, the configure_legend function seems to be ignored regardless of where used. I have three graphs being used:
```
chart = alt.Chart(self.data).mark_bar(size=20, angle=20).encode(
            x="Tag",
            y="Weighting",
            color="Tag:N"
        ).properties(
            title="Character Tags",
            width=200,
            height=200
        ).transform_filter(self.selector)
```

```
def slope_graph(self):
        chart = alt.Chart(self.data).mark_line().encode(
            x="Tag",
            y="Weighting",
            color="Character:N"
        ).properties(
            title="Characters Compared",
            width=200,
            height=200
        )
        return chart
```

```
def select_radar(self):
            chart = alt.Chart(self.data).mark_bar(size=20).encode(
            x="Weighting",
            y=alt.Y("Character:N", sort="-x"),
            color=alt.condition(self.selector, alt.value("Gold"), "Tag:N")
        ).add_selection(self.selector)
        return chart
```

And was then attempting to combine and change the position of the legend for two of them using:
```
bar_charts = alt.vconcat(chart, self.select_radar())
bar_charts.configure_legend(
    orient='left',
    strokeColor='gray'
)
result = alt.hconcat(bar_charts, self.slope_graph()).resolve_scale(color='independent')
```

**Comment by jakevdp** [comment]
Altair methods are pure: they do not modify a chart in-place, but rather return a modified chart. So if you want to display the chart with the modified legend, you'll have to do something with the result. e.g.
```python
bar_charts =  bar_charts.configure_legend(
    orient='left',
    strokeColor='gray'
)
```
That said, I believe that this will result in an error when used in your code block, because configurations can only be specified at the top level: that is, you'd need to instead call `configure_legend()` on the final `result` chart.

**Comment by BenAbyss** [comment]
Great, thanks for the concise reply, really helped me out.
