### ISSUE TITLE
How to remove Hawaii and Alaska from choropleth?

### ISSUE THREAD

**Issue by duttong** [altair-viz/altair#2449]
I have a data set that only covers the continental U.S. Is there a way to remove Hawaii and Alaska from the map?

**Comment by joelostblom** [comment]
You could remove those entries from the geojson file you are using or use a filter transform in altair to remove id 2 (alaska) and 15 (hawaii): 

```py
import altair as alt
from vega_datasets import data

state_map = alt.topo_feature(data.us_10m.url, 'states')
alt.Chart(state_map).mark_geoshape().project('albersUsa').transform_filter(
    (alt.datum.id != 2) & (alt.datum.id != 15))
```

![image](https://user-images.githubusercontent.com/4560057/113756668-855ba980-96c6-11eb-979d-9efe0758a179.png)
