### ISSUE TITLE
Save PNGs without altair_saver using the same approach as the mimetype renderer fallback?

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2453]
It seems like `alt.renderes.enable('mimetype')` can create a PNG blob without `altair_saver` installed. Could the same mechanism be used to enable saving of charts as PNGs via `.save()` without `altair_saver`?

I discovered this when creating a new env where both `chart.save('chart.png')` and `alt.renderers.enable('png')` complained about missing `altair_saver`, but `alt.renderers.enable('mimetype')` inserts the image blob in the notebook source without issues.

This is what I used to test, the jupyterlab version is 3.0.13.

```py
import altair as alt
from vega_datasets import data

cars = data.cars.url
chart = alt.Chart(cars).mark_circle().encode(
    alt.X('Horsepower:Q'),
    alt.Y('Miles_per_Gallon:Q'))

chart.save('chart.png') # error

alt.renderers.enable('png') # error
chart

alt.renderers.enable('mimetype') # creates png base 64 blob
chart

```

**Comment by jakevdp** [comment]
Creating a PNG requires a javascript runtime: the mimetype extension accesses this via the jupyterlab frontend. That's not generally available for Python runtimes, and even for Python runtimes that are associated with a jupyter frontend, there are security walls that prevent Python from executing frontend code except via standardized mechanisms, such as mimebundle display. There may be a way around it, but if there is, I suspect that would be considered a bug.

**Comment by jakevdp** [comment]
I think a more fruitful approach to improving `altair_saver` would be to wrap Kaleido; see https://github.com/altair-viz/altair_saver/issues/85

**Comment by joelostblom** [comment]
Thank you, I was wondering if the mimetype renderers was using JupyterLab somehow, but wasn't sure why the 'png' renderer was not doing the same thing. But maybe the two renderers are used with different IDEs by convention/design, so it would not make sense to rely on JupyterLab for the png renderer?

The altair_saver works great for me personally, but when teaching altair earlier this year, there were many students who had issues with getting it installed properly and it was tricky to troubleshoot across OSes and python installations.

I agree that Kaleido looks great, I'm excited for there to potentially be a shared way between Python web-viz libraries to handle this!

I will try to add a note in the docs mentioning that mimetype uses jupyterlab for the images, then i'll close this.

**Comment by jakevdp** [comment]
Just for reference, here is the code used by `alt.renderers.enable('notebook')` to embed the PNG in the mimebundle output: https://github.com/vega/ipyvega/blob/master/src/index.ts#L65-L93

For jupyterlab there is a similar code path.

**Comment by joelostblom** [comment]
Closing this as there are now easier ways to save PNGs thanks to vl-convert
