### ISSUE TITLE
Vega Editor export of US population histogram is stacked

### ISSUE THREAD

**Issue by pierre-haessig** [altair-viz/altair#246]
I just noticed that the first example in [Data Transformations](https://altair-viz.github.io/documentation/transform.html) is different when exported to the Vega Editor (bars are stacked in Vega Editor).

**Comment by jakevdp** [comment]
Thanks for pointing that out.

The difference is due to the fact that the website is using an older version of Vega-Lite than the vega editor. When we release version 1.2, the problem should be fixed.

**Comment by pierre-haessig** [comment]
Thanks for the feedback. Just to be sure, when you says "the website", you mean Altair documentation ? And this include `altair` package as well ? (because I ran the example in Jupyter Notebook and got the same result as in Altair doc).

**Comment by jakevdp** [comment]
The current release of Altair and the altair website you linked to both use an older version of Vega-Lite.
