### ISSUE TITLE
Sphinx 4 cannot use altair.sphinxext

### ISSUE THREAD

**Issue by rikardn** [altair-viz/altair#2467]
Sphinx 4 was released a week ago and some functions that the `altair.sphinxext` use have now been removed. The fix #2305 has already been merged, but a new release of altair would be needed to be able to use `altair.sphinxext` with the new Sphinx version.

**Comment by loglund** [comment]
We would also like to use Sphinx 4. Any timeframe on when a new release could be available?

**Comment by joelostblom** [comment]
Closing since version 4.2.0 was release in Dec https://github.com/altair-viz/altair/releases/tag/v4.2.0. Please re-open if I missed something and this is still an issue.
