### ISSUE TITLE
Binned bar charts are weirdly large - resetting height and width?

### ISSUE THREAD

**Issue by hannahburkhardt** [altair-viz/altair#2468]
I recently started getting weirly large charts when binning data. Bin example from the documentation:
```python
import altair as alt
from vega_datasets import data

movies = data.movies.url

alt.Chart(movies).mark_bar().encode(
    alt.X("IMDB Rating:Q", bin=True),
    y='count()',
)
```
![image](https://user-images.githubusercontent.com/4624654/119387723-31108700-bc7e-11eb-8a0e-d4990944ac9c.png)

When opening this example in the Vega Editor I see that the height and width are specified:
```json
{
  "config": {"view": {"continuousWidth": 400, "continuousHeight": 300}},
  "data": {"url": "https://vega.github.io/vega-datasets/data/movies.json"},
  "mark": "bar",
  "encoding": {
    "x": {"type": "quantitative", "bin": true, "field": "IMDB Rating"},
    "y": {"type": "quantitative", "aggregate": "count"}
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v5.1.0.json"
}
```
How can I make altair use calculated heights and widths, so I get the chart that I get in the Vega Editor if I remove the height and width specifications? Like this:
![image](https://user-images.githubusercontent.com/4624654/119387382-b9425c80-bc7d-11eb-8222-7f4f9d7879b7.png)
I've tried setting height and width to None or 0.

python package versions: altair 4.1.0, vega 3.4.0

**Comment by jakevdp** [comment]
Altair's default theme sets the width and height: https://altair-viz.github.io/user_guide/configuration.html#altair-themes

To disable this, you can run
```python
alt.themes.enable('none')
```

**Comment by hannahburkhardt** [comment]
Thank you!
