### ISSUE TITLE
mark_bar with brush not working

### ISSUE THREAD

**Issue by erlebach** [altair-viz/altair#2472]
I created a simple bar chart based off of synthetic data, generated within the code below (generate_dataframe). The image has a top chart with the data and a lower chart that allows me to drag a selection along the horizontal axis. There appears to be an error: the leftmost bar is not affected by the motion of my selection in the lower plot. I use streamlit to display the plot. Here is an image of what is happening. I list the code below the image. Thanks for any advice.

Image produced when running the code, enhanced to illustrate the issue described above:
![image](https://user-images.githubusercontent.com/324708/120929305-8f922800-c6b6-11eb-9c40-c29f708dead7.jpeg)

Here is my MWE using streamlit: 

```python
import streamlit as st
import pandas as pd
import altair as alt
import numpy.random as random

def generate_dataframe():
    nrows = 400
    name = [ 'n' + str(i) for i in range(300) ]
    names = random.choice(name, nrows)

    centrality = random.rand(nrows)
    multiplier = random.choice([.3, 1., 300.], nrows)
    centrality *= multiplier
    df = pd.DataFrame({'x':names, 'y':centrality})
    return df

df = generate_dataframe()
#----------------------------------

brush = alt.selection(type="interval", encodings=['x'])
axis = alt.Axis(labels=False)

base = alt.Chart(df, title="Base view").mark_bar().encode(
    x=alt.X('x:N', axis=axis),
    y='y:Q'
).add_selection(
    brush
).properties(
    width=850,
    height=50
)

zoomed = alt.Chart(df).mark_bar().encode(
    x=alt.X('x:N', scale=alt.Scale(domain=brush), axis=axis),
    y='y:Q'
).properties(
    width=850,
    height=400
)

chart = zoomed & base
st.altair_chart(chart)
```

---

**Comment by joelostblom** [comment]
[Answered on SO](https://stackoverflow.com/a/67860637/2166823)
