### ISSUE TITLE
Tooltip doesn't support "image" key

### ISSUE THREAD

**Issue by ehknight** [altair-viz/altair#2474]
My understanding is that to render tooltips, Altair uses the `vega-tooltip` plugin. Per that project's [README](https://github.com/vega/vega-tooltip), one awesome feature that library has is the ability to render images as part of the tooltip with the image key. From the docs:

> Supports special keys title (becomes the title of the tooltip) and image (used as the url for an embedded image)

Using the tooltip without the `image` key is fine:

```
mydata = pd.DataFrame.from_records([{'a': 1, 'b': 1}, {'a': 2, 'b': 2}])
chart = alt.Chart(mydata).mark_circle().encode(
    x='a',
    y='b',
    tooltip=alt.Tooltip(['a'], title='My Cool Tooltip')
).interactive()

display(chart)
```

However, when I add the `image` key, it stops working:

```
chart = alt.Chart(mydata).mark_circle().encode(
    x='a',
    y='b',
    tooltip=alt.Tooltip(['a'], title='My Cool Tooltip', image='https://picsum.photos/200')
).interactive()

display(chart)
```

```
SchemaValidationError: Invalid specification

        altair.vegalite.v4.schema.channels.Tooltip, validating 'additionalProperties'

        Additional properties are not allowed ('image' was unexpected)
```

Maybe this feature is already supported but the schema is out of date? Thanks.

---

Please follow these steps to make it more efficient to solve your issue:

- [N/A] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [x] Search for duplicate issues.
- [x] Use the latest version of Altair.
- [x] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by jakevdp** [comment]
I don't think Vega-Lite supports that feature of vega-tooltip. I'd suggest reporting the issue there.

**Comment by ehknight** [comment]
Hey @jakevdp, I asked about this vega-lite and the author provided some examples that indicate it's supported. Would you mind taking a quick look? Thanks. 

https://github.com/vega/vega-lite/issues/7635#issuecomment-894821846

**Comment by joelostblom** [comment]
I just discovered that this is actually supported by vega-tooltip and can be used from altair like this:

```py

import altair as alt
import pandas as pd

source = pd.DataFrame.from_records(
    [{'a': 1, 'b': 1, 'image': 'https://altair-viz.github.io/_static/altair-logo-light.png'},
     {'a': 2, 'b': 2, 'image': 'https://avatars.githubusercontent.com/u/11796929?s=200&v=4'}]
)
alt.Chart(source).mark_circle(size=200).encode(
    x='a',
    y='b',
    tooltip=['image']  # Must be a list for the image to render
)
```

I added a PR with this example in https://github.com/altair-viz/altair/pull/2519

**Comment by joelostblom** [comment]
Sorry I missed that this was specifically about using the `image` key inside `alt.Tooltip`, which is not yet supported in altair.

**Comment by jakevdp** [comment]
(Followup in case it helps anyone: to render this requires vega version 5.21.0 or newer)

**Comment by joelostblom** [comment]
> Sorry I missed that this was specifically about using the `image` key inside `alt.Tooltip`, which is not yet supported in altair although images can still be displayed as in the sample above.

Reading my own comment again, the example we added cover the "image" key mechanism mentioned by the OP so once #2570 is merged with that clarification, then this can be closed. I also PRed it to the VL docs https://github.com/vega/vega-lite/pull/8048

**Comment by jparkhilltx** [comment]
Yeah. This really had me going for a while. Altair could benefit from the same documentation.
