### ISSUE TITLE
How to mark lines based on one column value but set the color based on another column?

### ISSUE THREAD

**Issue by DeerWhale** [altair-viz/altair#2475]
First of all, I would like to thanks the Altair community for posting tutorials/questions online! I learned a lot from the previous posts. But I couldn't figure out how to color the line series based on the value of another column. A simple example is let's say I want to make a scatter plot of property1 and property2 from the multi-dimension data set df, and I would like to color the points based on "legend_value", but also want to connect the points from same "obj" (plotted with different shapes). How can I make the lines has the same color as the scattered points in this plot? 

Thanks in advance!!! 

```
df = pd.DataFrame({'Obj':['a','a','a','a','b','b','b','c','c','c','d','d'],
                   'property1':[1,2,3,4,7,8,9,4,5,6,5,6],
                   'property2':[0.1,0.2,0.3,0.4,0.35,0.4,0.45,0.8,1,1.2,0.5,0.8],
                   'legend_value':[1,1,1,1,2,2,2,1,1,1,3,3]})
display(df)
scatter = alt.Chart(df).mark_point().encode(
    alt.X('property1:Q', scale=alt.Scale(zero=False)),
    alt.Y('property2:Q', scale=alt.Scale(zero=False)),
    shape=alt.Shape('Obj:N',legend=None),
    color=alt.Color('legend_value:Q',scale=alt.Scale(scheme='rainbow')),
    opacity=alt.value(0.8) 
)

scatter_objectline = alt.Chart(df).mark_line().encode(
    alt.X('property1:Q',scale=alt.Scale(zero=False)),
    alt.Y('property2:Q',scale=alt.Scale(zero=False)),
    color=alt.Color('Obj:N',legend=None),
    opacity=alt.value(0.2) 
)

scatter+scatter_objectline
```

![image](https://user-images.githubusercontent.com/48139543/124655442-d74ecf80-de6d-11eb-98b1-97db18dd4067.png)

**Comment by jakevdp** [comment]
If you want the points and the lines to share the same color, you can do this by setting the color encoding to the same field, i.e. `color=alt.Color('legend_value:Q')`. Does that work for you?

**Comment by DeerWhale** [comment]
@jakevdp Yes, that is exactly what I pictured in mind!!! Thanks so much for the quick response! I saw your response using `detail` in another related question, but I did the other way around (`color` and `detail` field swapped) so couldn't get what I wanted to plot.  Thanks a lot for your time! 

Can I chase with another question if you don't mind, is there a way to change the legend to be a continuous color bar instead of the distinct points after adding in `detail='Obj:N'`? 
![image](https://user-images.githubusercontent.com/48139543/124662039-45979000-de76-11eb-9282-42ad962d3580.png)

**Comment by jakevdp** [comment]
The legend is created based on the `color` encoding: the `detail` encoding is not relevant here.

Try using a quantitative rather than ordinal or nominal encoding for `color`, e.g. `color='legend_value:Q'`

**Comment by DeerWhale** [comment]
ohhhh you're right thanks for pointing it out :)  I think the problem here is the shape argument that makes the legend not continues then?  The legend is fine if I comment out the line define the shape based on `Obj:N`, but it becomes distinct dots when that line is added:
```
alt.Chart(df).mark_line().encode(
    alt.X('property1:Q', scale=alt.Scale(zero=False)),
    alt.Y('property2:Q', scale=alt.Scale(zero=False)),
    color=alt.Color('legend_value:Q',scale=alt.Scale(scheme='viridis')),
    shape=alt.Shape('Obj:N',legend=None),### this line make the legend not continuous 
    detail='Obj:N',
    opacity=alt.value(0.5) 
).configure_point(
    size=100
)
```
![image](https://user-images.githubusercontent.com/48139543/124802226-b8ac0f80-df25-11eb-91e4-818f0013c631.png)

**Comment by jakevdp** [comment]
Oh, I see: when you use `mark_line(point=True)` (which is the default setting when you apply a `shape` encoding to a line) the legend defaults to showing points. If you want to override this default, you can explicitly ask for a gradient legend like this:
```python
    color=alt.Color('legend_value:Q', legend=alt.Legend(type='gradient'))
```

**Comment by DeerWhale** [comment]
ohhh that makes sense and the output is perfect!! Thank you so much for your patience and the continued help!!

**Comment by jakevdp** [comment]
Awesome! I'll close this issue; feel free to reopen if you run into another problem with this.
