### ISSUE TITLE
Sankey Charts

### ISSUE THREAD

**Issue by don-jil** [altair-viz/altair#2476]
We use sankey charts a lot in our work, and I would love to be able to use altair to make them. It's been done in vega-lite: https://www.elastic.co/blog/sankey-visualization-with-vega-in-kibana.  I've searched for "sankey" and "flow" in requested features; apologies if someone has already requested.

**Comment by joelostblom** [comment]
This is not available in Vega-Lite yet. The post you linked is a workaround for Vega, but they don't provide full support yet either. You can see the issues here for more details https://github.com/vega/vega/issues?q=is%3Aissue+is%3Aopen+sankey

**Comment by joelostblom** [comment]
Closing this as there is nothing to be done on the Altair side of things. If this is added in Vega-Lite it will then be in a following altair release following.
