### ISSUE TITLE
Percentage of bin in bar chart

### ISSUE THREAD

**Issue by LSchueler** [altair-viz/altair#2483]
### Discussed in https://github.com/altair-viz/altair/discussions/2479

<div type='discussions-op-text'>

<sup>Originally posted by **LSchueler** July 20, 2021</sup>
Hi and a big thank you for altair!

I have a table which I want to visualize as a bar chart. On the X axis, I want to bin the values into the given intervals (they are strings). On the Y axis, I want to give the percentage of positive values with respect to the individual bin. As an example for the example table below, for the `51 - 100` bin I want to show `50%`, as there are 2 out of 4 positive values. The examples I found always calculate the relative values with respect to the total number of values.
I am unsure what transform methods to use and how to use them to get the wanted results.
It would be really great if someone could give me a hint!

```
ind  value                                        bins
0    Negative                                    0 - 50
1    Negative                                    0 - 50
2    Negative                                    0 - 50
3    Negative                                    0 - 50
4    Negative                                    0 - 50
5    Negative                                    0 - 50
6    Positive                                  51 - 100
7    Positive                                  51 - 100
8    Negative                                  51 - 100
9    Negative                                  51 - 100
10   Positive                                    0 - 50
11   Positive                                    0 - 50
12   Positive                                    0 - 50
13   Positive                                    0 - 50
14   Positive                                    0 - 50
15   Positive                                    0 - 50

```

If this will run, I could contribute it to the examples, if you are interested.

**Comment by joelostblom** [comment]
Closing in favor of the discussion.
