### ISSUE TITLE
mark_geoshape does not show anything

### ISSUE THREAD

**Issue by krlng** [altair-viz/altair#2487]
I exported a topology of germany using https://pitchinteractiveinc.github.io/tilegrams/.

I try to visualize it using:

`alt.Chart(alt.topo_feature("tiles.topo.json", 'tiles')).mark_geoshape()` 

but only a blank chart is showed.

The json itself looks pretty good to me and I have no idea where to search for the bug.

**Comment by mattijn** [comment]
`alt.topo_feature` is a shorthand for topojson data accessible by URL. Have a look at this SO for more info on geographical data in Altair (both inline and by URL for both GeoJSON and TopoJSON structured data sources): https://stackoverflow.com/a/55950538/2459096

The following works as expected:
```python
import altair as alt
import json

tp_file = '/Users/mattijnvanhoek/Downloads/tiles.topo.json'

with open(tp_file, 'r') as f:
    tp_data = json.load(f)
    
# inline topojson data object
data_topojson = alt.InlineData(values=tp_data, format=alt.DataFormat(feature='tiles', type='topojson')) 

# chart object
alt.Chart(data_topojson).mark_geoshape(
).encode(
    color="properties.name:N"
).properties(
    projection={'type': 'identity', 'reflectY': True}
)    
```
<img width="609" alt="image" src="https://user-images.githubusercontent.com/5186265/129922706-5aeac791-9193-4e44-9581-90ea9deb5f50.png">

When you use TopoJSON structured data in Altair it is serialised as GeoJSON in Vega itself. You also could parse the TopoJSON data into a GeoDandas GeoDataFrame and use that data-object in Altair. The behaviour is near identical to a normal Pandas DataFrame, see for more info here: https://altair-viz.github.io/user_guide/data.html#geopandas-vs-pandas:

Example code-spec for here:
```python
import geopandas as gpd

gdf = gpd.read_file(tp_file, driver='TopoJSON')
# chart object
alt.Chart(gdf).mark_geoshape(
).encode(
    color="name:N"
).properties(
    projection={'type': 'identity', 'reflectY': True}
) 
```
<img width="609" alt="image" src="https://user-images.githubusercontent.com/5186265/129922706-5aeac791-9193-4e44-9581-90ea9deb5f50.png">

This is not a bug, and the issue can be closed.

**Comment by krlng** [comment]
Thank you very much, really good explanation. I don't have much experience with GeoData-formats

**Comment by mattijn** [comment]
No problem!
