### ISSUE TITLE
ENH: Confidence intervals around LOESS or Regressions?

### ISSUE THREAD

**Issue by nickeubank** [altair-viz/altair#2492]
Would it be possible to add confidence intervals around loess or regressions? It's very hard to do serious modeling visualizations without integrating some information about uncertainty. It's something provided by plotnine, seaborn, ggplot2, etc., and I think most of these are implemented in scipy, so I'm hoping could be integrated into `transformation` steps? Sorry, don't know much about altair internals, but seems like this could happen before being passed to Vega.

---

Please follow these steps to make it more efficient to respond to your feature request.

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most feature requests should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example.
- [X] Search for duplicate issues.
- [X] Describe the feature's goal, motivating use cases, and its expected behavior.

**Comment by jakevdp** [comment]
Thanks for the request! I think this would be good, but unfortunately the LOESS transform in vega-lite does not compute confidence intervals. Perhaps send a feature request there?

**Comment by nickeubank** [comment]
Ah, ok — those transformations are taking place at the Vega lite level?
