### ISSUE TITLE
escape special characters in names...

### ISSUE THREAD

**Issue by franzhaas** [altair-viz/altair#2494]
Dear all,

using altair 4.1.0.

I tried to use altair to plot data annotating the data with the dimension. For example volts written as [V]. If i remove the closing ], I even get a javascript error.

Is there a way to use strings with special characters as names with altair? Is thsi related to #1326? Altogh for me a single bacslash did not solve my issue, the javascript error goes away but there is no data plotted...

thanks,
Franz 

---8<---8<---8<---8<---8<---8<---8<---8<---
```python
import altair as alt
import numpy as np
import pandas as pd

x = np.arange(100)

xname = "x [mV"

source = pd.DataFrame({xname: x, 'f(x)': np.sin(x / 5)})

alt.Chart(source).mark_line().encode(
    x=alt.X(field=xname, type="quantitative"),
    y='f(x)'
)
```

**Comment by jakevdp** [comment]
Thanks for the question! There is some documentation around escaping special characters in the `field` attribute here: https://altair-viz.github.io/user_guide/encoding.html#encoding-channel-options

For your example, you can make it work like this:
```python
import altair as alt
import numpy as np
import pandas as pd

x = np.arange(100)

xname = "x [mV"
xname_escaped = "x \\[mV"

source = pd.DataFrame({xname: x, 'f(x)': np.sin(x / 5)})

alt.Chart(source).mark_line().encode(
    x=alt.X(field=xname_escaped, type="quantitative"),
    y='f(x)'
)
```
