### ISSUE TITLE
Chart representation changes after the chart is displayed

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2497]
The representation of the chart object seems to change after the chart is displayed. Take this example

```py
import altair as alt
from vega_datasets import data


cars = data.cars()

scatter = alt.Chart(cars).mark_point().encode(
    x='Weight_in_lbs:Q',
    y='Horsepower',
    color='Origin')
```

It looks like this initially 

```py
scatter.encoding
```

```py
FacetedEncoding({
  color: Color({
    shorthand: 'Origin'
  }),
  x: X({
    shorthand: 'Weight_in_lbs:Q'
  }),
  y: Y({
    shorthand: 'Horsepower'
  })
})
```

But after displaying the chart in JuptyerLab (by just typing `scatter` in a cell and executing it), the encoding representation changes to this longer format:

```py
FacetedEncoding({
  color: Color({
    field: 'Origin',
    type: 'nominal'
  }),
  x: X({
    field: 'Weight_in_lbs',
    type: 'quantitative'
  }),
  y: Y({
    field: 'Horsepower',
    type: 'quantitative'
  })
})
```

There is probably some good reason for this that I don't understand, but for testing/autograding purposes it would be convenient if the representation was always the same and did not change after the chart is displayed.

Edit: It seems like `scatter.to_dict()` will always return the long format so maybe that could be relied on instead.

**Comment by jakevdp** [comment]
Thanks for flagging this - it looks like the `to_dict()` method on encoding channels is not pure; see e.g. https://github.com/altair-viz/altair/blob/8ff06cfbbfb470aba6798999c61128be398c4996/tools/generate_schema_wrapper.py#L134-L142

(this is the template that is used for all auto-generated encoding classes).

I think that we could probably remove this mutation without any noticeable consequences.

**Comment by joelostblom** [comment]
I tried to look into this, but for some reason it seems like the changes I make in the file you linked don't have any effect on my chart objects. Changes I make in other files results in updates to the charts. I tried restarting everything, but maybe I am missing something here...

**Comment by jakevdp** [comment]
Those lines are in the codegen source, so they won't affect the altair code until it is regenerated
