### ISSUE TITLE
The capability of plot time series data of sampling per every 5mins or less? 

### ISSUE THREAD

**Issue by linhc130** [altair-viz/altair#251]
I try to use altair to plot a time series data which samples every 5 min but the line plot is empty.

**Comment by jakevdp** [comment]
It's quite hard to help you without more information. Could you please post the code that led to this error? Thanks!

**Comment by linhc130** [comment]
I reboot my system, restarted my Jupyter and it can plot beautifully.

**Comment by jakevdp** [comment]
OK – glad it works. I suspect that what happened is that the ipyvega plugin was not correctly configured (perhaps you installed within a different virtualenv than your jupyter instance?)

In any case, we need to have more informative errors in this case; see https://github.com/vega/ipyvega/issues/56
