### ISSUE TITLE
Version 4.2 release candidate?

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#2520]
Let's get a version 4.2 release candidate together!

In the past, I always just directly created new releases, but it seems Altair has become pretty popular – https://pypistats.org/packages/altair shows nearly 150,000 daily downloads (yikes!) so doing the release candidate route is probably warranted now.

I think we're in pretty good shape right now on the master branch, but I wanted to check to see if there's anything I'm not thinking of. cc/ folks who have been most active recently: @joelostblom @mattijn @ChristopherDavisUCI 

Have you had a chance to kick the tires with the VL 4.17 features landed this week? Anything you think we should address before a new release?

**Comment by mattijn** [comment]
This PR is not merged: https://github.com/altair-viz/altair/pull/2399, maybe that should be included?

**Comment by ChristopherDavisUCI** [comment]
Exciting!  Nothing left that I'm aware of related to VL 4.17.

**Comment by joelostblom** [comment]
Exciting indeed! I went through the open PRs but didn't see anything other than the PR @mattijn mentioned above. I haven't played around that much with the new 4.10+ features yet.

If everything goes well with the 5.0 PR, I think it would be cool to sync that release with an update to the documentation to organize it more similarly to VL as suggested in this issue https://github.com/altair-viz/altair/issues/1994 and I would be happy to help working on that as well as reviewing the existing PRs relating to the docs.

**Comment by jakevdp** [comment]
Regarding docs: an overhaul for 5.0 sounds great! Let's not plan to change much before the 4.2 release though... it would be nice to get that out relatively soon.

**Comment by jakevdp** [comment]
OK, #2399 is merged. Thanks - sorry I missed that!

**Comment by joelostblom** [comment]
I noticed that since [VL 4.14](https://github.com/vega/vega-lite/releases/tag/v4.14.0), the [encoding type is optional and defaults to 'nominal'](https://vega.github.io/vega-lite/docs/type.html). I can look into [modifying this section accordingly](https://github.com/altair-viz/altair/blob/2dff60b9862adaecdf48b9aebf065be5be7fb3ad/altair/vegalite/v4/schema/channels.py#L27-L51), maybe we can rewrite the error message to indicate that the column name is likely misspelled rather than missing a type (I find that this is something that often happens to my students and they don't realize it is a typo since the error message suggests the type is the problem).

**Comment by jakevdp** [comment]
Yeah I think @ChristopherDavisUCI mentioned this as well. Doesn't Vega-Lite do some sort of type inference now as well? I'm a bit hesitant to change Altair's type inference behavior for a 4.2 release, because it could cause huge differences in charts that rely on the existing inference result. My thought is that we can drop Altair's type inference and rely on Vega-Lite's new defaults starting in version 5.0. What do you think?

**Comment by joelostblom** [comment]
Waiting until 5.0 sounds like a good solution. I don't think VL actually looks at the data values to try to infer the type, [this is what the docs say](https://vega.github.io/vega-lite/docs/type.html):

> For a data field, "nominal" is the default data type unless the field encoding has aggregate, channel, bin, scale type, sort, or timeUnit.

For constant values that use `datum`, VL seems to actually infer the data type.

I think the behavior for typos in column names in VL is not super intuitive, there is no error message raised, instead a chart is created with an undefined entry (see below). But I also imagine that it might be difficult to check if the column exists since it could have been created in a transform also, not just as part of the data, so maybe it is unnecessary to introduce custom error message logic for this in altair.

![image](https://user-images.githubusercontent.com/4560057/141595457-9d2259da-8c83-4e7e-b41e-1c7eaf7e8e10.png)

**Comment by jakevdp** [comment]
Yeah, the custom error message for an undefined column is really tricky. There are a *lot* of ways that columns can be created within transforms, and Vega-Lite's implemetation has some non-trivial rules for what dataset & what columns are available within any level of a hierarchical chart. Implementing that on the Altair side would require duplicating a lot of the Vega-Lite logic in a way that would be quite difficult to keep in sync. The failure mode on one side is not bad (failing to raise an error when one should be raised) but the failure mode on the other side would be quite problematic (raising an error when one shouldn't be raised).

In the earliest versions of Altair we had specific warnings around this, but the latter situation came up enough that we decided it would be better to drop them.

**Comment by mattijn** [comment]
This works:
```python
import altair as alt
from vega_datasets import data

cars = data.cars.url

dots= alt.Chart(cars).mark_circle().encode(
    x='Miles_per_Gallon:Q',
    y='Horsepower:Q'
)

yrule = alt.Chart().mark_rule().encode(
        y=alt.datum(150)
)

dots + yrule
```
![image](https://user-images.githubusercontent.com/5186265/142179052-7045200d-15c9-4b9d-b765-f458e200b959.png)

But this does not:
```python
import altair as alt
from vega_datasets import data

cars = data.cars.url

dots= alt.Chart(cars).mark_circle().encode(
    x='Miles_per_Gallon:Q',
    y='Horsepower:Q'
)

yrule = alt.Chart().mark_rule().encode(
        y=alt.Y(alt.datum(150))
)

dots + yrule
```

> ```
> SchemaValidationError: Invalid specification
> 
>         altair.vegalite.v4.schema.channels.Y->0, validating 'type'
> 
>         {'datum': 150} is not of type 'string'
> ```

Is this something that should be supported?

**Comment by ChristopherDavisUCI** [comment]
This version also works, for whatever that's worth:

```
import altair as alt
from vega_datasets import data

cars = data.cars.url

dots= alt.Chart(cars).mark_circle().encode(
    x='Miles_per_Gallon:Q',
    y='Horsepower:Q'
)

yrule = alt.Chart().mark_rule().encode(
    y=alt.YDatum(150)  # <--
)

dots + yrule
```

**Comment by mattijn** [comment]
Ah, yes, there I see the `axis=Undefined, band=Undefined, impute=Undefined, scale=Undefined, stack=Undefined, type=Undefined` which I was looking for. Now I also see there is `alt.YValue()`. But only `alt.Y()` has the abilities for shorthands. So should `alt.datum()` and `alt.value()` be introduced as shorthands in `alt.Y()`?

**Comment by jakevdp** [comment]
I tend to think of `alt.value(val, **kwargs)` as a replacement for the channel-specific `alt.XValue(val, **kwargs)`, `alt.YValue(val, **kwargs)`, etc. With this in mind, I'd probably lean toward using `alt.datum(val, **kwargs)` in the same way... that is, `alt.X(alt.datum(val))` should not be valid semantics.

**Comment by mattijn** [comment]
Ah! And it is already working properly, since I can do `y=alt.datum(150, type='nominal')`, which resolves into `"y": {"type": "quantitative", "datum": 150}`. All good then.

**Comment by jakevdp** [comment]
Just pushed a release candidate to PyPI 
```
pip install altair==4.2.0rc1
```
Changelog: https://altair-viz.github.io/releases/changes.html#version-4-2-0-unreleased

Thanks all!

**Comment by mattijn** [comment]
Something wrong with the pngs at https://altair-viz.github.io/gallery/index.html:
![image](https://user-images.githubusercontent.com/5186265/142645060-633027ca-455e-4d7f-ad8b-cfda96c204ad.png)

**Comment by jakevdp** [comment]
Thanks - I just pushed a new build that should fix it.

**Comment by leemengtaiwan** [comment]
Hi, I saw from the [Altair Change Log](https://altair-viz.github.io/releases/changes.html#version-4-2-0-unreleased) that there is new support for Pie charts and Radical Chart which is awesome! So I tried installing the version with 

```bash
pip install altair==4.2.0rc1
```

and confirmed the version is correct:

```python
import altair as alt
alt.__version__
'4.2.0rc1'
```

But was not able to make the Radical chart work with the [example code here](https://altair-viz.github.io/gallery/radial_chart.html#gallery-radial-chart):
```
import pandas as pd
import altair as alt

source = pd.DataFrame({"values": [12, 23, 47, 6, 52, 19]})

base = alt.Chart(source).encode(
    theta=alt.Theta("values:Q", stack=True),
    radius=alt.Radius("values", scale=alt.Scale(type="sqrt", zero=True, rangeMin=20)),
    color="values:N",
)

c1 = base.mark_arc(innerRadius=20, stroke="#fff")

c2 = base.mark_text(radiusOffset=10).encode(text="values:Q")

c1 + c2
```

![image](https://user-images.githubusercontent.com/3454980/143226255-a8d9c7d5-a865-42e5-ba2f-084d608d9d2c.png)

The console output shown:
```
vega-embed@6?noext:21 The input spec uses Vega-Lite v4.17.0, but the current version of Vega-Lite is v4.8.1.
```
![image](https://user-images.githubusercontent.com/3454980/143226388-98282318-ebdf-405a-bf76-1a4220545b58.png)

How can I solve this vega-lite version matching issue? Ayn help is highly appreciated 🙏

**Comment by jakevdp** [comment]
How are you displaying your chart?

**Comment by leemengtaiwan** [comment]
@jakevdp thanks for replying, I’m using a jupyter lab for displaying the chart. 

Not sure this answer your question. Please let me know how I can provide more info for diagnosis.

**Comment by jakevdp** [comment]
Thanks - the issue is that you're already displayed an Altair 4.1 chart in your web environment, so an older version of Vega-Lite is already loaded and cached by the browser. I'd suggest you clear all outputs in your notebook, close all unrelated notebooks (because all JupyterLab tabs exist in the same javascript namespace), and then reload the browser page before executing the Altair 4.2 code.

**Comment by leemengtaiwan** [comment]
@jakevdp It works! Thanks for your time and kind explanation ❤️

**Comment by jakevdp** [comment]
The release candidate is about 9 days old now and I've only seen a couple issues reported:

1. Jupyter notebooks with previous Vega-Lite versions already loaded fail to show Altair charts
2. After #2503, Altair no longer works with jsonschema versions older than 3.0 (because of the explicit reference to `jsonschema.Draft7Validator`) We already pin jsonschema>3.0 in requirements, but that's not always respected depending on how people install packages.

I'm thinking about how we might be able to smooth these issues out before a final release...

**Comment by mattijn** [comment]
The 2nd bullet is an issue for Jupyter notebook and Lab isn't it? Probably not in Colab or in VS Code notebooks?
It is an cross-tab state management issue of these Jupyter environments. Meaning that if you can change the state from within one tab, it will impact the behaviour in the other tab. So you can make your new Altair code work in current tab, while breaking your old Altair code in the other tab?

Is this issue https://github.com/jupyter-server/jupyter_server/issues/413 of relevance here? From what I understand Jupyter defaults to not cache files unless you have set the `?v=` parameter in the url, only then it will cache the file. I don't see an `?v=` in Altair code, meaning caching is not done, but it still happens so there is still  another different process going on?

In any case, if we find a method to control caching, then it will be from this point onward, which is nice, but for the remaining it also means documentation in the docs/SO/Github?

**Comment by jakevdp** [comment]
I think this is orthogonal to jupyter-server cacheing, as it's an issue with the javascript environment. It's definitely an issue in JupyterLab, and is particularly pronounced because of the fact that all notebooks opened in a session share the same JS environment. I don't think it is an issue in Jupyter Notebook (because it uses requirejs) and is not an issue in Google Colab (because cell outputs are in their own iframe). It's definitely an issue in nbviewer and other html outputs, which don't usually have requirejs. I'm not certain about the architecture of VSCode notebooks.

**Comment by mattijn** [comment]
> if a single notebook contains charts from multiple Altair versions in its outputs

.., I hope nobody expects that this should work? 

Maybe we can add a `?_={int(time.time())}` to these URLs: https://github.com/altair-viz/altair/blob/8a8642b2e7eeee3b914850a8f7aacd53335302d9/altair/utils/html.py#L18-L22

So each url call is slightly different to the other, so caching is prevented in jupyterlab?

**Comment by jakevdp** [comment]
The relevant URLs for the default display mechanism are here: https://github.com/altair-viz/altair/blob/8a8642b2e7eeee3b914850a8f7aacd53335302d9/altair/utils/html.py#L93-L98

I don't think adding temporal qualifiers to them will change anything as currently written, because new script tags are only added to the document if the libraries are not already loaded in the global namespace: https://github.com/altair-viz/altair/blob/8a8642b2e7eeee3b914850a8f7aacd53335302d9/altair/utils/html.py#L121-L132

We could maybe add a new script tag unconditionally, but I'm not sure what side-effects that would cause. Alternatively, we could try to keep track of script elements that have been previously added, but that sounds overly complicated and error-prone.

**Comment by mattijn** [comment]
I see, reinitiating fulfilled promise objects is not my specialism though. I don't know how to improve this, maybe a JavaScript guru can chime in, if any... 

How did you do this with previous releases? I can't remember seeing this issue popping up frequently for users. 

Maybe a simple solution is to include it in the release notes: _JupyterLab-users: please restart your session_

**Comment by jakevdp** [comment]
The previous time we hit this, the universal renderer was a new thing, so any old charts were using the labextension route to rendering, and thus they didn't interfere with the new charts.

Note that the issue here does not directly have anything to do with fulfilling javascript promises. The issue has to do with the fact that the promise adds a `<script>` tag for a particular version of `vega-lite` when you call it. I'll just link to the whole code: https://github.com/altair-viz/altair/blob/8a8642b2e7eeee3b914850a8f7aacd53335302d9/altair/utils/html.py#L84-L136

In order to load a new version of the package in the same page, we'd have to add another script tag, but I'm not certain how browsers handle that. The brute-force way to do it would be to add a new script tag every time you render a chart, and hope the browser loads only the most recent version. But adding script tags ad infinitum is probably bad, so instead we'd have to somehow track what versions are already loaded, referencing them by version string... and the deeper you think about it, the more it sounds like you need to basically re-implement a bare-bones `requirejs` within every Altair HTML output. And the more complicated a solution you come up with, the more likely you are to hit some browser/OS combination where it doesn't work.

**Comment by mattijn** [comment]
Gentle ping for @jasongrout. We have a question about the javascript envrionment within JupyterLab and I was wondering if you could give us some advice here (again). 

Some context: in the past (and currently in offline-modus) Altair was rendering the chart object using a vega labextension part of JupyterLab, this required introduction of a new labextension for each new vega(-lite) version within JL. Therefor Altair introduced another approach based on a live internet connection where the html object is prepared in Python and rendered within Jupyter. This worked well until now, when preparing for a new release.
Since JL has a shared JavaScript environment for different tabs (same session), a library from the Vega-family might already be loaded and registered using a script tag in the JavaScript environment of this JL session , but when installing the upcoming Altair release it cannot render the charts since the script tag is already taken (eg in another tab was Altair also used). For more insight check @jakevdp comments above.

Current situation of potential solutions:
- Closing and reopening a new JupyterLab session solves it: but this is not so user-friendly.
- Assign a new script tag for every time you render a Altair chart: probably the browser don't like this?
- Use a JL session, cross-tab Altair state, to track which libraries of the Vega-family are loaded (Vega-lite/Embed/Vega)and pick the right one upon rendering: potential problems gallore with browser/OS combinations.

Do you have any other suggestions? Are we thinking wrong? Can JupyterLab do we things that we don't know? Etc..

**Comment by jakevdp** [comment]
I'll add one thing: I think the usual JupyterLab response would be to use a frontend extension, but that has proven very problematic in the past because of (1) the need to ensure the frontend extension version is compatible with the Python package version,  and (2) the general unfamiliarity among users with frontend extensions, how to install them, how to think about them. Given the usability and debuggability challenges involved, I would **definitiely not** consider moving Altair back to a default rendering solution that requires a labextension.

**Comment by jakevdp** [comment]
From what I've seen the best potential solution to these kinds of issues is the js-module idea (https://github.com/Quansight-Labs/jupyter-output-spec) but that's still very experimental, and would have to be widely adopted before it would be useful to a package like Altair.

**Comment by mattijn** [comment]
I tried the following locally and I think this works. I append the `vegalite_version` to `output_div` (default `vis`) upon rendering and then I check in the `else if` statement if this the existing defined `outputDiv.value` (potentially from older Altair package) equals the `output_div` (with the appended `vegalite_version`). 
```
-    } else if (typeof vegaEmbed === "function") {
+    } else if (typeof vegaEmbed === "function" && outputDiv.value === "{{ output_div }}") {
```
and
```
-        output_div=output_div,
+        output_div=f"{output_div}{vegalite_version}",
```
See commit in branch here: https://github.com/mattijn/altair/commit/b239e3ba1e751a8fbd2e975d9b4a929050cd9503
Maybe its too simple thinking?

**Comment by jakevdp** [comment]
The output div is a new, unique uuid each time a chart is displayed, so I think this check will always evaluate to False, and as a result, every time you display a chart, three new `<script>` tags will be appended to the head of the page. It's reasonable that this would work to solve the issue, but I'm not sure it's the solution we want: for example, what happens when you have a long-running session where you create hundreds of charts? Is there any consequence to adding hundreds or thousands of duplicate `<script>` tags to the DOM? I'm not sure, and I don't think it's something we should do lightly.

**Comment by jakevdp** [comment]
Maybe we can do something like define a `VEGA_DEBUG` javascript global (similar to what's defined in the vega editor) that stores the currently-loaded versions of vega, vega_lite, and vega_embed, so we can refer to it when deciding whether to load new ones?

One thing I'm uncertain of: if we do replace the global `vega` & `vegaLite` variables, and a previously-rendered chart is then interacted with, will the new global versions interfere with that code?

Really the issue here is we can only patch over a symptom of JupyterLab's unfortunate frontend design, so I don't think there's really any good solution.

**Comment by mattijn** [comment]
Regarding:
> One thing I'm uncertain of: if we do replace the global vega & vegaLite variables, and a previously-rendered chart is then interacted with, will the new global versions interfere with that code?

The following thing happens when a new script tag is added. Observe the following animated gif:
![ezgif com-gif-maker (3)](https://user-images.githubusercontent.com/5186265/144478128-1757d6c4-f7f9-42a9-9a10-7606af13a786.gif)

The previously-rendered chart which errored is working correctly afterwards. But upon trying the previous Altair version, I could not get the error back popping up. So I think the highest loaded version of vegalite is being used and not the latest added(?).

**Comment by mattijn** [comment]
I have to say, if I re-render the chart many times than my CPU/memory goes to high and my fan goes to loud.

**Comment by jakevdp** [comment]
I think #2530 should fix the issue - take a look and see if it works for you!

**Comment by ChristopherDavisUCI** [comment]
It seems to work for me!  I tested by going to Jupyter Lab and opening a file that was made with version 4.8.1, and then making a new notebook using #2530.  Here's a screenshot showing both versions of vega-lite.  Let me know if showing something else would be more helpful.

<img width="1035" alt="lab" src="https://user-images.githubusercontent.com/82750240/144548893-b77f4214-a64e-46d0-b4b7-3bdf3bdbf6e5.png">

**Comment by fgenoese** [comment]
Do you plan to go for a 4.2rc2? @jakevdp

**Comment by jakevdp** [comment]
Released! https://github.com/altair-viz/altair/releases/tag/v4.2.0
