### ISSUE TITLE
Maintaining order of DataFrame

### ISSUE THREAD

**Issue by daniel55-rc** [altair-viz/altair#2526]
Hi, im trying to plot the data of my DataFarme in a groupedChart and I want the columns to preserve the order I gave them before. The data looks as follows (its not all there but its in the same way organized)
![image](https://user-images.githubusercontent.com/75391163/143132949-40e8dd02-3c37-4641-b7c0-55fc8305191c.png)
 However when I plot it i get the following graph:
![visualization](https://user-images.githubusercontent.com/75391163/143133124-c0908f2c-3bf5-42e3-afd2-53a7875d8a59.png)

So the months were sorted even though I specified not to sort in the chart. I used the following code:
```python
chart2 = alt.Chart(melted).mark_bar().encode(
            column=alt.Column('variable',sort=None),
            x=alt.X('room',sort=None),
            y=alt.Y('value'),
            color='room',
            tooltip= ['room', 'value']
         
        )
```

Doesanyone know how I could fix that?

Thanks!

**Comment by jakevdp** [comment]
You can do this by passing `sort=None`. For example:
```python
import altair as alt
import pandas as pd
df = pd.DataFrame({'y': ['B', 'A', 'D', 'C'], 'x': [1, 2, 3, 4]})

alt.Chart(df).mark_bar().encode(
  alt.X('x'),
  alt.Y('y', sort=None)
)
```

![visualization (75)](https://user-images.githubusercontent.com/781659/143137183-1576bd7b-711a-4e60-9605-b0d3db76dd6e.png)

**Comment by daniel55-rc** [comment]
> You should be able to do this by passing `sort=None`. For example:
> 
> ```python
> import altair as alt
> import pandas as pd
> df = pd.DataFrame({'y': ['B', 'A', 'D', 'C'], 'x': [1, 2, 3, 4]})
> 
> alt.Chart(df).mark_bar().encode(
>   alt.X('x'),
>   alt.Y('y', sort=None)
> )
> ```
> 
> ![visualization (75)](https://user-images.githubusercontent.com/781659/143137183-1576bd7b-711a-4e60-9605-b0d3db76dd6e.png)

Hi, 

Sadly that doesnt work. I already tried setting sort=None to the x,y,columns parameters but the graph still remains as shown before. I used this code and it dint work...

chart2 = alt.Chart(melted).mark_bar().encode(
            column=alt.Column('variable',sort=None),
            x=alt.X('room',sort=None),
            y=alt.Y('value',sort=None),
            color='room',
            tooltip= ['room', 'value']
         
        )

**Comment by jakevdp** [comment]
Oh, I see. Scales in faceted charts are shared by default (meaning they're all forced to the same order). To make the scales not shared, you can use `chart.resolve_scale(x='independent')`.

**Comment by jakevdp** [comment]
By the way, in the future please use triple back-ticks to delineate code blocks. I've edited your posts in the thread so that your code is more readable.

**Comment by jakevdp** [comment]
Simple example of the `resolve_scale` solution:
```python
import altair as alt
import pandas as pd
df = pd.DataFrame({
    'row': [1, 1, 1, 1, 2, 2, 2, 2],
    'y': ['B', 'A', 'D', 'C', 'A', 'C', 'B', 'D'],
    'x': [1, 2, 3, 4, 5, 6, 7, 8]})

alt.Chart(df).mark_bar().encode(
  alt.X('x'),
  alt.Y('y', sort=None),
  row='row'
).resolve_scale(y='independent')
``
![visualization (76)](https://user-images.githubusercontent.com/781659/143139134-0cf0f4b7-f204-45c7-b0cb-2d912095989d.png)
`

**Comment by daniel55-rc** [comment]
Mmhhh Im honestly not sure how exactly that should help my particular case. Bars are  in the right order (the ids) are in the desired order. The problem is that the group of bars was sorted when plotting. The original dataframe has the order october, september, august. 

But the graph shows August, October, September, they were sorted alphabetically I guess

**Comment by daniel55-rc** [comment]
> Simple example of the `resolve_scale` solution:
> 
> ```python
> import altair as alt
> import pandas as pd
> df = pd.DataFrame({
>     'row': [1, 1, 1, 1, 2, 2, 2, 2],
>     'y': ['B', 'A', 'D', 'C', 'A', 'C', 'B', 'D'],
>     'x': [1, 2, 3, 4, 5, 6, 7, 8]})
> 
> alt.Chart(df).mark_bar().encode(
>   alt.X('x'),
>   alt.Y('y', sort=None),
>   row='row'
> ).resolve_scale(y='independent')
> ```
> 
> ![visualization (76)](https://user-images.githubusercontent.com/781659/143139134-0cf0f4b7-f204-45c7-b0cb-2d912095989d.png)

In this example the idea would be if for example you had row = [3,3,5,5,5,1]
that the chart still came in the "group order" 3,5,1.

**Comment by jakevdp** [comment]
Unfortunately, `sort=None` does not work due to a bug in Vega-Lite; see https://github.com/vega/vega-lite/issues/6221

But you can achieve the desired result by explicitly passing the desired sort order:
```python
import altair as alt
import pandas as pd
df = pd.DataFrame({
    'row': [3, 3, 3, 5, 5, 5, 1, 1],
    'y': ['B', 'A', 'D', 'C', 'A', 'C', 'B', 'D'],
    'x': [1, 2, 3, 4, 5, 6, 7, 8]})

alt.Chart(df).mark_bar().encode(
  alt.X('x'),
  alt.Y('y', sort=None),
  alt.Row('row', sort=[3, 5, 1]),
).resolve_scale(y='independent')
```
![visualization (77)](https://user-images.githubusercontent.com/781659/143145715-6bdec852-0a93-471f-94c5-c668f8a13ca5.png)
