### ISSUE TITLE
Altair map chart does not rendered in GitHub

### ISSUE THREAD

**Issue by vcuspinera** [altair-viz/altair#2527]
I am having troubles with maps (`mark_geoshape` charts), while these plots render on my local jupyter notebook, when I upload them to GitHub, these plots doesn't render anymore.

This also happens with map-charts that I upload before and render well on GitHub, and now that I ran them again and up load it, these plots doesn't render anymore.

To show this, I made a jupyter notebook with examples from Altair's Example Gallery: [Choropleth Map](https://altair-viz.github.io/gallery/choropleth.html), [Locations of US Airports](https://altair-viz.github.io/gallery/airports_count.html), and [Repeated Choropleth Map](https://altair-viz.github.io/gallery/choropleth_repeat.html), that can be found in the following link:
https://github.com/vcuspinera/Datasets/blob/main/errors/Altair_map_error_maps_in_github.ipynb

[<img width="701" alt="image" src="https://user-images.githubusercontent.com/53915521/143298709-a54abe79-5d1e-4b29-bb45-264053253d95.png">](https://github.com/vcuspinera/Datasets/blob/main/errors/Altair_map_error_maps_in_github.ipynb)

**Comment by vcuspinera** [comment]
I also tried it on [nbviwer](https://nbviewer.org), and I got a similar result: the map-charts doesn't render.
<img width="866" alt="image" src="https://user-images.githubusercontent.com/53915521/143304233-4e7340f4-974f-4059-b6e5-2a9330dc25d9.png">

**Comment by jakevdp** [comment]
Altair charts render via javascript, and GitHub's notebook views scrub all javascript for security purposes.

If you want a PNG preview of a chart to appear with your notebook, you can display your charts via notebook extensions, which have extra code that embeds a PNG preview image when charts are rendered. The documentation has info on enabling these renderers for [JupyterLab](https://altair-viz.github.io/user_guide/display_frontends.html#displaying-in-jupyterlab) or [Jupyter Notebook](https://altair-viz.github.io/user_guide/display_frontends.html#displaying-in-the-jupyter-notebook).
