### ISSUE TITLE
Show zero-valued data points

### ISSUE THREAD

**Issue by feddevanderlijn** [altair-viz/altair#253]
Is it possible to show zero-valued data points in a chart? Currently these are being ignored.

For example, this would show the green GOOG price in https://altair-viz.github.io/gallery/line_color.html#gallery-line-color as a flat line prior to 2005:
 
![multilineexample](https://cloud.githubusercontent.com/assets/3964971/19890482/46375bae-a03b-11e6-9f41-b93ca25a586d.png)

Ideally it would force vega-lite to show empty facet plots as well.

**Comment by jakevdp** [comment]
If the data contains zero values, the plot will show them. In this case, the data does not contain any zeros (i.e. the google time-series starts in mid-2004) so no zeros are plotted. This is not likely to change, as it is very uncommon to want to plot data that does not appear in your dataset!

The best thing to do if you want this would be to modify the dataset itself.

**Comment by feddevanderlijn** [comment]
Thanks for the quick response - that approach makes a lot of sense!

I was actually trying to draw a chart with a count aggregation, so I do not have access to the pivoted data. Is there a way to solve this in that case? Or is this beyond the scope of Altair and should I do the pivot in pandas myself and plot that transformed data?

**Comment by jakevdp** [comment]
Oh, I see. Could you post an example script showing the problem you're having?

**Comment by joelostblom** [comment]
@feddevanderlijn I am going through Altair issues to find those that have been resolved and can be closed. Would you be able to add a comment with a reproducible example so that we can try to resolve the issue or close it if it is no longer affecting you?
