### ISSUE TITLE
Inaccurate positing of Gantt chart on quantitative y-axis

### ISSUE THREAD

**Issue by danhamill** [altair-viz/altair#2533]
I want to overlay a horizontal bar (Gantt) chart that represents the window where the maximum center moving average was calculated.  Then, I want to add some text indicating what the maximum value is next to the horizontal bar.  In the example below, the `004-month` center moving average window and text are not plotting together.  I would expect to see a horizontal orange line at the y-axis value of 36.9375.

---

Please follow these steps to make it more efficient to solve your issue:

- [X] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor
    - The eample provided here works as intended in [vega-lite editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3ADYBDAJ6YATigDaoALaK1AazwhCygA6YUIAEb6Q3RiIRiUAJjkhMUSHRJJUPPIQGgGmFlZQEDokivL2IPCY8nRWOpiEanBgIB4AHsZhlsgmmDpmwbHxiggIapgIioRFINFQ8YnJVnSNlnmuxtW19T2pivncHSnF3U053MoF5s0AjqSKRHCEjXBolhNYncVmmWC9HpRJmGDE0MYX8leEwRwAbIvhxSRNamiV3NYkKYgShgWKYSjxLw+PwQ5CaEDjEALAC650u12ebAA7O9ml91L84v9AVYQWCIdwoRBfFAELD4YiUbJuBl1pQYMEdFpQPB5N8rAAKGakHQAOjSGSyAAIAIQAXjlUoA5McspglQBKHKozi6fRGUJLKxNXLibixRBtYoPGBmmyKe4kZrROh0B7xOj5ZAARjYHipNP8+AgQRCoEKESiMSJCQOQIlJzmJVNuKsq3WxC2xF2VRqdQas2KekRkysqtOSa94aNxSaZQqMcG+ZGRbG7TjXRGHgWho+IHTGyzOz2ICbw0LoH0CGLndmHlLRxOZxZajZHLUXLhPLgfPUguFYoT0vlipVS812ukyO4M0UxigijSs8UAFowABWb0ADlcigAnK4ti2K4YASJgYFsD+LAvH+YBsGArjQTAMBJgAJCCjh6FYYiEGYlDIAA9ARuwNKKCCbIwpDWKKcAQARGGlIoxHDC+8ibJgxEsKKX6it6ooAFaULcN6NA66SwqAt5vp+P7-oBijAaB4GYJBiEwXBCFIShW4gDMzSuBwbAvmw3rGd6AAqHDIFZHDxEe2SLmq8TlkUEh-tx3pyJJLYgAZHBmWZllsNZwW2dw9lWBwLAvjovDMNwLmSC8op-hIWLvl5uk+X5RkmYFNmhWwdnpImxSvDFcXOUukhca4f6ZXpVg5cZrj5YVIXFZKDkgIlCXVcgEjJRIGW6llha+YZLVtSFHXhSVWSRWwrWxUQ8U9f1bmiliX4jd543NUt00FZ1pUgFFFWrVVTkDclqXpQ12WTYdJlBTNYUtPN3XlStTBXRWA21fVo2NcUB0SEdhUnQtjkVn110sBIoquO4wOPf5bDgy9BWzR9XWLctlVw-9m3bbtY36U9mMWdj70RWVbDRT9a2JTdKVpWTIMTejVOvcdc14-TLwXb9ROuYDD37U90VY+1tOfWW1Wi24PFpRLFPo9L1Oy0V-OnedTN-a5t3s2rTVSxDON02dbBCwbSsA0jQN7eruXvhbcsC+tTn26476iiwHNo677s67jes28LzMbeLqOS+jQsy29odW71XvE64orviwpug09Cda0nUNfRHdtp2Ljs51zuVYiHRcK97ZfK-7lcHV+te69Djc+zx2exy7xl-u3Yed6nLOIZnEgt5NvpDyniuN8grg8UtU-+d6pmJ3zw-daP-WuIjEi987Ztr61m+Qx3O-zyz3pYqKLyB3HG-P7zF-b-XsML+PX5H+TJ8b2fAuW854NzHr-TmfkN48xpsneWMMRxjwzr7VeG9Nav0tnAruX877vheCg4ybtz4YM9rva6S9eLgLRhvfO6CPanVIf9OqW18HYlnpghhRRXDGxYW3IhdCR7Xz3ojVwnk+7-wHmwkhgiyFsG4ijY+uc8ozz4bAqRoChH30furUy69JH0OkYw5K3p5F-0UTowBtDVH6PUWQ26WiT6AL0QImxjC-YAVXmfCxMC67wMNm4RGWJJ5iMUWfaB2sfFYLARPDxxk0HeMvh-BBe8+JcJiWwQhQC34gM-mPWRWJREKK5mfGh8T36+J9kg+xITjI1xUREjhKBvTuXfCYiBHAz68MycQ6xOT+pNJSliNJg86kJPKQvW+W0namKKS+ZRXT+FXxcZwvi91gkzN0SMspkSNHQRicYpxizelkL4hjVeVMDmJL8T6dyEgCnTL8pjLx4TRnbOuv0w+ZzjJhMLi8hp1ytp4LWQ82JFyxm5O4oMoFHBMYZMsfUgxnDZFsCmW0jGxkSnPK2X8gybNPmsM2dkpJxzM6AsKcCyCoLXmML4g-PFwz5lWOcUcxhGcYKfLmXC35CK3B8QDuyl+pTCVXJEbxdlTyflYu5YvDOuyoUMwCgS9hUrkb3xRWjaW4rgFKqWTyrakKyXnTRYqtRzLEX+1Jfcw1cTMVCp9ryqpXNpawsFdq01ur3xBINfKiOxqelEsYYjFglC47S1qQy+FOrF4Hy-KvaWnTOWSsjSqlg+rLXevpQm21X8M5Ygtai6KHKXUmv9ZwxGK85UFoFTa11Ja3BcTzeq2Zmqsk1uFVxFpq8MmUuxVxdenapq+qZbWqNvEHV+UId8rVxbhVIODerQh1qJVZrHsImNcrCHOurdOn2iMfz9p9eGrlSaM6pX3WGzNrad33znSfQh8ai1+uFX7Ya+6M0PqHcK3dnq01u0LVux9V611et-VWpdl6v5+3yf2-Zg7DnDvHnVVe+du3KqMTexRCdm3dI-T7P2DMkNfJQ0m59Da44J0XVOgD2bM4EfSURt1i8+JNNoxisD26v58SA2mhO5731wZnZnO5qKE73v-Thr+vbv3CYkbBy5uH75cek3+tjVGx63VI+rIWGzD2JoY64O+LwNMny01hhZcmv48W9FJtGYb6PwfctiVetTTOMv4z7ZKLxrNx1qZOlt7G1OihfXK2pFG-Oqb3irJzBC7PCvcn24L6KYs+zvn+MdHBam8bE257BNGEsUtk2Cved8Pl5bfVl8zY9l7oa5jXZTlHxMs2GqKU5CXtMXv8xtDOyKoswZ08u6Oq9OlJYXrc3iXn1a8JcxGvTyVHNyt4b57D2Wx53xEYNkFBWqWcOK9VvyvDN0qYa0VpGaX8usfq8tveyUU3rfxX18DUTVlet4aJw7l3bGBaM4o3hZW3sVb3pBxTaM251bC0d4l75U2opB6Bi7-23nuUM+t3r7XwtvJ4n+ITaN6XDZvh58bJ9hlTaPQx70fsvxY7jsMxbZnCtvJS2qqnG37sdYR9xXbHBhkHbh3Txhsj3yM-VsM87YP3sBv9q07HNTccaO-KvYZr2edbbrf7Anijhm-aV9iv2LBBeE9mblFnaPGF3xYEDpnbW+Pw8Ye5fT8um0y+ulIQLHO5mO8YcvNLyjie6fgzxF4UPHrKJp6563nCeIxtRNIIAA)
- [X] Search for duplicate issues.
- [X] Use the latest version of Altair.
- [X] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

```python
import altair as alt
import pandas as pd
from altair import datum
from vega_datasets import data
import numpy as np

df = data.stocks()

df = df.loc[df.symbol == 'MSFT', :]
df = df.set_index('date')

for n_month in [2,4,6]:

    met = f'{n_month}'.zfill(3) +'-month'
    df.loc[:, met] = df.price.rolling(n_month, center=True).mean()

    idx_max = df[met].idxmax()
    max_val = df[met].max()


    begin_date = (idx_max - pd.DateOffset(months = n_month/2)).isoformat()
    end_date = (idx_max + pd.DateOffset(months = n_month/2)).isoformat()
    mask = (df.index >= begin_date) & (df.index<end_date)
    #Mask out all values outside window
    df.loc[(mask ), met] = max_val
    df.loc[df[met] != max_val, met] = np.nan


df = df.drop('symbol', axis=1)
df = df.stack()
df.index.names = ['date','metric']
df.name = 'price'
df = df.reset_index()

rule = alt.Chart(df).mark_bar(height = 2).encode(
        x = 'min(date):T',
        x2 = 'max(date):T',
        y = alt.Y('price',),
        color = 'metric', 
    ).transform_filter(datum.metric != 'price').interactive()

tex = alt.Chart(df).mark_text(align = 'left', baseline = 'middle', dx = 10).encode(
    x = 'max(date):T',
    y = alt.Y('price', aggregate={'argmax':'date'}),
    color = 'metric',
    text = alt.Text('max(price)')
).transform_filter(datum.metric != 'price')

(rule+tex).interactive()
```
which results in:

![gantt_chart_quanitative_yaxis](https://user-images.githubusercontent.com/11522898/146063256-12f3018b-3c0e-4402-84b7-3def4ead99ca.png)

**Comment by jakevdp** [comment]
It looks like a Vega-Lite rendering bug if you install the Altair 4.2 release candidate (`pip install altair==4.2.0.rc1`), it renders correctly. We should be doing a final release of Altair 4.2 very soon.

**Comment by danhamill** [comment]
I tested on altair 4.2.rc1 and the plot is rendered as intended.  Looking forward to the official release of 4.2.
