### ISSUE TITLE
problems adding altair charts in folium

### ISSUE THREAD

**Issue by corti-acs** [altair-viz/altair#2534]
I am trying to add an Altair chart as popup in folium, but this chart is not working and appear empty.

testing below, it looks working well..
chart = alt.Chart(source).transform_fold(['NO2_index', 'Temperature', 'WindSpeed'], 
                                 as_=['indice','NO2']).mark_line().encode(x='TIME:T', y='NO2:Q',
                                                                             color='indice:N')

![image](https://user-images.githubusercontent.com/82566952/146047857-e8621151-a8c4-478e-bdf1-ab4d44869846.png)

but in folium.. 
popup = folium.Popup(max_width=650)
folium.features.VegaLite(chart, height=350, width=450).add_to(popup)

folium.Marker([40.4400457,-3.6392422],
                 icon=folium.Icon(color="gray", icon='atom',prefix='fa'),popup=popup,tooltip="Station15").add_to(map)

appear empty...

![image](https://user-images.githubusercontent.com/82566952/146048175-59783998-109a-4f2b-afba-ca940f403d1f.png)

any clue what is wrong?

thanks!!
---

Please follow these steps to make it more efficient to solve your issue:

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [ ] Search for duplicate issues.
- [ ] Use the latest version of Altair.
- [ ] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by mattijn** [comment]
I'm surprised this works. It seems you are close already! It is probably better to ask in the repo of Folium. Something related to `folium.features.VegaLite()`.

**Comment by joelostblom** [comment]
Closing as folium-related. @corti-acs Please link if you opened an issue in the Folium repo.
