### ISSUE TITLE
module 'altair' has no attribute 'Theta'

### ISSUE THREAD

**Issue by erikfilias** [altair-viz/altair#2536]
Dear, 

I tried to reproduce the radial chart with `Altair 4.1.0`  in `Python 3.9.5`: https://altair-viz.github.io/gallery/radial_chart.html
With the example:
```
import pandas as pd
import altair as alt

source = pd.DataFrame({"values": [12, 23, 47, 6, 52, 19]})

base = alt.Chart(source).encode(
    theta=alt.Theta("values:Q", stack=True),
    radius=alt.Radius("values", scale=alt.Scale(type="sqrt", zero=True, rangeMin=20)),
    color="values:N",
)

c1 = base.mark_arc(innerRadius=20, stroke="#fff")

c2 = base.mark_text(radiusOffset=10).encode(text="values:Q")

c1 + c2
```

But I got: `AttributeError: module 'altair' has no attribute 'Theta'`

Any help will be appreciated.
Thanks.
Erik

---

Please follow these steps to make it more efficient to solve your issue:

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [ ] Search for duplicate issues.
- [ ] Use the latest version of Altair.
- [ ] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by mattijn** [comment]
Currently it is only possible to make a radial/pie chart with the latest release candidate `4.2.0rc1`.

You can try this version by installing it with `python -m pip install altair==4.2.0rc1`.

I think it should be possible to release a stable version before christmas.

**Comment by erikfilias** [comment]
Many thanks, @mattijn!
The release candidate works well.
I'll try to look at the stable version again before Christmas.

**Comment by joelostblom** [comment]
Closing since 4.2.0 is now released
