### ISSUE TITLE
Plot display but the content is empty when the plot is saved as HTML and it is opened in Mozilla Firefox

### ISSUE THREAD

**Issue by erikfilias** [altair-viz/altair#2539]
Dear, 

I tried to open Mozilla Firefox, a plot that is saved as HTML. 
The plot is displayed but the content is empty as it is shown in the next image:
I am using `Altair 4.1.0` in `Python 3.9.5`

![image](https://user-images.githubusercontent.com/8010477/146743718-447656f7-69ff-4333-8075-2c618ac71783.png)
---
Any suggestion will be appreciated.
Thanks in advance.

**Comment by jakevdp** [comment]
Thanks for the report - it's hard to help without more information.

1. Can you include the full code snippet used to create and save the chart? (preferably a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), which may involve creating a chart from a different, simpler dataset)
2. In firefox, can you check the [Browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) for any errors that are displayed?

**Comment by erikfilias** [comment]
> Thanks for the report - it's hard to help without more information.
> 
> 1. Can you include the full code snippet used to create and save the chart? (preferably a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), which may involve creating a similar chart using a different, simpler dataset)
> 2. In firefox, can you check the [Browser console](https://developer.mozilla.org/en-US/docs/Tools/Browser_Console) for any errors that are displayed?

Thanks for the comment.
1. My chart is a time series with an hourly resolution that is opened without any issues in Google Chrome and Microsoft Edge. Sorry, my example is not a minimal reproducible one. It can download [here](https://mega.nz/file/fBU3HQRC#MVW5VZfl7U4doFHyIqYaZKb6W8nrXLK9YCmgH5E6HcQ).
2. In the console appears this error: 
![image](https://user-images.githubusercontent.com/8010477/146817802-1a2504b0-3688-43ab-bcce-3900b1fa3ee7.png)
How could I solve it?
Thanks in advance.

**Comment by jakevdp** [comment]
3rd party download sites are suspicious, and I'm not willing to click on that link. Please edit the original question and paste your minimal reproducible example code. Thanks!

**Comment by binste** [comment]
Closing issue as stale and no response from user.
