### ISSUE TITLE
Missing imports in docs

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#254]
See https://github.com/altair-viz/altair-viz.github.io/pull/1 CC/ @rgbkrk

**Comment by jakevdp** [comment]
The reason this wasn't caught is that we do ``from altair import *`` in the (hidden) setup code. That should probably be removed so that the doc build catches these sorts of errors.

**Comment by jakevdp** [comment]
Actually, now that I look closer, the reason we have ``import *`` is so that the page can look like a continuous session. THe ``altair-plot`` directive is run not in some globally-updated namespace, but in a namespace defined by the setup code. The ``import *`` allows us to operate in the document as if previous imports are available.

**Comment by jakevdp** [comment]
Fixed in 95a42764087bc5791c33c898ac3322cf07590c06

**Comment by rgbkrk** [comment]
Thanks!

**Comment by jakevdp** [comment]
This will make it into the doc build once we push version 1.2, which is basically ready to go.
