### ISSUE TITLE
title align not taking effect

### ISSUE THREAD

**Issue by thatlittleboy** [altair-viz/altair#2544]
I'm slightly modifying the example from the documentation on [Title Configuration](https://altair-viz.github.io/user_guide/configuration.html?highlight=title#title-configuration), see:

```python
import altair as alt
from vega_datasets import data

source = data.cars.url

chart = alt.Chart(source).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
)

(chart & chart).properties(
    title='Cars Data'
).configure_title(
    fontSize=20,
    font='Courier',
    align='center',  # <---- does not take effect, why?
    color='gray'
)
```
produces a viz with title aligned to the left, not to the center. Why is this the case?

<img width="514" alt="image" src="https://user-images.githubusercontent.com/30731072/147845983-7fd208d8-b995-4e51-867d-786a48625925.png">

Note that the other configurations (fontSize, color) have taken effect, but it is only the alignment that has been ignored.

By the way, the example works if: the title was added to any one of the charts, as in 
```python
(chart.properties(title='Cars Data') & chart).configure_title(...)  # gives a centered title as expected
```

### Details

On Jupyter notebook (on Jupyterhub), py3.6, Altair 4.1.0. (latest version on pypi at the moment)
Happy to provide more details if needed.

---

Please follow these steps to make it more efficient to solve your issue:

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [X] Search for duplicate issues.
- [X] Use the latest version of Altair.
- [X] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by thatlittleboy** [comment]
Hmm okay, seems like the right config option to use is `anchor='middle'`

**Comment by asmaier** [comment]
I think this ticket should not be closed. The documentation should explain this in more detail. This is a very basic issue and it is frustrating for newcomers to not be able to center the title of a plot.

**Comment by joelostblom** [comment]
@asmaier The title docs have been extended lately as per https://github.com/altair-viz/altair/pull/2838. There is still no example of the anchor functionality, but feel free to add one building of the structure of that PR.

**Comment by santanubiswasaws** [comment]
similarly - baseline ('bottom') does not work  - need to use - orient('bottom)

**Comment by santanubiswasaws** [comment]
```
    base_chart = alt.Chart(top_10_customers).mark_bar(size=20).encode(
        x=alt.X('customerName', title=None, sort=None),
        y=alt.Y('Total_Sales', title="Total Sales")
    ).properties(
        width=600, 
        height=600, title='Top 10 customers'
    ).configure_title(
        fontSize=40,
        font='Courier',
        color='gray',
        align='center' #<-------------  does not work - use anchor='middle'
        baseline='bottom',  #<--------- does not work - use oreint='bottom' 
        anchor='middle', 
        orient='bottom'
    )
```
