### ISSUE TITLE
Example donut & radial chart does not work

### ISSUE THREAD

**Issue by swartchris8** [altair-viz/altair#2548]
I am trying to create a [donut chart from the altair examples](https://altair-viz.github.io/gallery/donut_chart.html) with the following code:

```python
import pandas as pd
import altair as alt

source = pd.DataFrame({"category": [1, 2, 3, 4, 5, 6], "value": [4, 6, 10, 3, 7, 8]})

alt.Chart(source).mark_arc(innerRadius=50).encode(
    theta=alt.Theta(field="value", type="quantitative"),
    color=alt.Color(field="category", type="nominal"),
)
```

It's failing with the following error:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-14-a3c410647669> in <module>
      4 source = pd.DataFrame({"category": [1, 2, 3, 4, 5, 6], "value": [4, 6, 10, 3, 7, 8]})
      5 
----> 6 alt.Chart(source).mark_arc(innerRadius=50).encode(
      7     theta=alt.Theta(field="value", type="quantitative"),
      8     color=alt.Color(field="category", type="nominal"),

~/.pyenv/versions/3.8.9/envs/nlp/lib/python3.8/site-packages/altair/utils/schemapi.py in __getattr__(self, attr)
    255             except AttributeError:
    256                 _getattr = super(SchemaBase, self).__getattribute__
--> 257             return _getattr(attr)
    258 
    259     def __setattr__(self, item, val):

AttributeError: 'Chart' object has no attribute 'mark_arc'
```

Environment:

Altair installed in Python 3.8.9 env with `pip` trying to run the donut chart example code in a jupyter notebook

Lib versions:
vega-datasets==0.9.0
altair==4.1.0

The https://altair-viz.github.io/gallery/radial_chart.html is also failing there the error is:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-13-1f1e718059b0> in <module>
      5 
      6 base = alt.Chart(source).encode(
----> 7     theta=alt.Theta("values:Q", stack=True),
      8     radius=alt.Radius("values", scale=alt.Scale(type="sqrt", zero=True, rangeMin=20)),
      9     color="values:N",

AttributeError: module 'altair' has no attribute 'Theta'

---
```

Please follow these steps to make it more efficient to solve your issue:

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [x] Search for duplicate issues.
- [x] Use the latest version of Altair.
- [x] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by jakevdp** [comment]
Radial charts were [added in version 4.2](https://altair-viz.github.io/releases/changes.html). If you want to use `mark_arc()`, you'll have to update Altair.

**Comment by swartchris8** [comment]
FYI vega_datasets is still pinned to altair < 4.2 this is the reason it didn't work for me with a clean install

**Comment by jakevdp** [comment]
I'm confused: vega_datasets doesn't declare any dependency on altair (see [setup.py](https://github.com/altair-viz/vega_datasets/blob/master/setup.py) and [requirements.txt](https://github.com/altair-viz/vega_datasets/blob/master/requirements.txt). Can you elaborate?
