### ISSUE TITLE
Half confidence interval error bars

### ISSUE THREAD

**Issue by sparisi** [altair-viz/altair#2549]
Is there a way to plot half confidence interval error bars?
Basically [like this](https://altair-viz.github.io/gallery/errorbars_with_ci.html) but showing only top or bottom half of the bar.
The doc doesn't say anything about it so I think this feature is missing.

**Comment by jakevdp** [comment]
I don't think it can be done with `mark_errorbar()`, but you can always draw the errorbar manually using `mark_tick` with a `y` and `y2` encoding specifying the desired extent.
