### ISSUE TITLE
Add strict option to altair sphinx extension

### ISSUE THREAD

**Issue by jtilly** [altair-viz/altair#2550]
Hi!

I'm a big fan of altair and the sphinx extension that comes with it. 

One thing that I sometimes stumble over is that when I have an rst page the documentation build doesn't fail when the Python code snippets have errors. Would you be open to adding a `:strict:` flag to the code snippets so that they raise when an error occurs instead of skipping the node? I have something like this in mind: https://github.com/altair-viz/altair/compare/master...jtilly:issue-2550

I'm happy to make a PR for this or consider alternative solutions.

Thanks!

**Comment by jakevdp** [comment]
Seems reasonable, but why not use the sphinx `-W` option to do this?

**Comment by jtilly** [comment]
Yes, you're right, the `-W` would also make the build fail. But for me `-W` is a bit _too_ strict. Maybe I'm using sphinx wrong, but I always have various extensions emitting warnings that I find hard to track down.
