### ISSUE TITLE
Consider adding a note about using VegaFusion to work with large data

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2552]
VegaFusion was recently released and [from its release announcement](https://vegafusion.io/posts/2022/2022-01-27_ProjectAnnouncement.html) it seems like a rather convenient way to speed up performance with large aggregated data in Altair (and speeding up rendering for non-aggregated data is suggested on the roadmap). I haven't played around with it yet myself, but let me know if you have any thoughts about adding a note about it in the Altair docs.

Ref https://github.com/altair-viz/altair/issues/1752 for a section with general notes on how to work with big data.

**Comment by nathanneibauer** [comment]
Hi @joelostblom, have you had any time since your post to play around with VegaFusion? I have been using Altair for a couple of years now, but my current visualization challenges require a bit of cleverness (subsetting, aggregation, etc) to continue to leverage Altair for data exploration purposes.

**Comment by joelostblom** [comment]
Sorry I missed your post initially @nathanneibauer . Unfortunately I haven't worked much with VegaFusion yet, so I can't comment on it much more than the info that exists in the VegaFusion docs.

**Comment by joelostblom** [comment]
Fixed in #2738
