### ISSUE TITLE
Some API docs links to Vega Lite are broken

### ISSUE THREAD

**Issue by tillnagel** [altair-viz/altair#2553]
Since Vega Lite released 5+, some of the links to its documentation are outdated. Due to the new signal mechanisms, this sees to be the case specifically for the (old) selection methods and parameters.

e.g.
https://altair-viz.github.io/user_guide/generated/api/altair.selection_interval.html
link for "clear" points to
https://vega.github.io/vega-lite/docs/clear.html 
but should refer to 
https://vega.github.io/vega-lite-v4/docs/clear.html

These occur on the following pages:
https://altair-viz.github.io/user_guide/generated/api/altair.selection_single.html
https://altair-viz.github.io/user_guide/generated/api/altair.selection_interval.html
https://altair-viz.github.io/user_guide/generated/api/altair.selection_multi.html

**Comment by jakevdp** [comment]
This is unavoidable, unfortunately. These docs come directly from the vega-lite schema documentation. Altair currently uses Vega-Lite version 4, but the vega-lite website is built with Vega-Lite version 5, so the links are no longer correct. It should be fixed by #2528

**Comment by binste** [comment]
Closing as Altair is now built against Vega-Lite 5 and so the links should work.
