### ISSUE TITLE
Reproduce table like structure with Altair/Vega-lite

### ISSUE THREAD

**Issue by ThysvdW** [altair-viz/altair#2555]
I'm fairly new to Altair and Vega-lite, and would like to know if something like the attached image is at all possible.
![2022-02-04_155410](https://user-images.githubusercontent.com/45350200/152540651-3e4f6a72-6f58-4671-9a18-76052ec1f4b9.jpg)
I was able to reproduce some of the chart, but am struggling with the grouping. Just wanted to know if this is at all possible in Altair.
![2022-02-04_155945](https://user-images.githubusercontent.com/45350200/152541714-db71ea45-d190-4ee4-8fa2-a9b932df86dd.jpg)

**Comment by joelostblom** [comment]
You can use faceting with a resolved y-scale to create nested labels as in your first image.

```py
import altair as alt
import pandas as pd

source = pd.DataFrame({
    'Activity': ['Sleeping', 'Eating', 'TV', 'Work', 'Exercise'],
    'State': ['Inactive', 'Active', 'Inactive', 'Inactive', 'Active'],
    'Time': [8, 2, 4, 7, 3]
})

alt.Chart(source).mark_bar().encode(
    alt.X('Time:Q'),
    alt.Y('Activity', title='')
).facet(
    row=alt.Row('State', title=''),
).resolve_scale(
    y='independent'
)
```

![image](https://user-images.githubusercontent.com/4560057/152623475-be08ee85-aac2-4c60-a05a-a7803ecece07.png)

**Comment by ThysvdW** [comment]
Thanks, appreciate the feedback.
