### ISSUE TITLE
Extra text in Chart labels

### ISSUE THREAD

**Issue by Nico4108** [altair-viz/altair#2556]
Is it possible to create some extra text or a text-box when using Altairs Chart?
I would like to get the total amount of processed data (see image) to be displayed in the same side as the labels are.

Code looks like the following:

    data = get_automation_metrics(scripts)
    data = data[data.name.isin(['podcast_processed', 'n_unknown_errors', 'n_known_errors','ebook_processed', 'n_errors', 'audiobook_processed'])][['date','value','name']]

    data = data.groupby(['date','name'], as_index=False).sum()
    data_total = data.groupby(['name'], as_index=False).sum() <-- the data is here

    fig = alt.Chart(data, padding={'left': -10, "top": 10, "right": 10, "bottom": 30}).mark_bar(size=15).encode(
            x=alt.X('date:T', axis=alt.Axis(format='%b %-d'), scale=alt.Scale(padding=15), title='Dates processed on'),
            y=alt.Y('value', title='Total amount'),
            color=alt.Color('name', title='', sort=[f'{scripts[0].upper() + scripts[1:]}s processed']),
            tooltip=['name', 'value', 'date'],
            text=alt.value('test123')
        ).configure(
            background='AliceBlue').properties(
                title={'text': [f'{scripts[0].upper() + scripts[1:]}s processed'],'subtitle': ['data from last 25 days']}).configure_title(
                    fontSize=20).configure_axis(
                        labelFontSize=14, titleFontSize=14)

    st.altair_chart(fig, use_container_width=True)

![Screenshot 2022-02-14 at 15 41 10](https://user-images.githubusercontent.com/7727890/153885712-29ce8eb5-bfff-41b0-8f67-dcbcfd5ca3fb.png)

**Comment by joelostblom** [comment]
You can use `mark_text` for this:

```py
import altair as alt
from vega_datasets import data

cars = data.cars()
chart = alt.Chart(cars).mark_circle().encode(
        x='Miles_per_Gallon',
        y='Weight_in_lbs',
        color='Origin'
)

text = alt.Chart().mark_text(
    align="left",
    baseline="bottom",
    fontSize=14,
    fontWeight=600,
    color='coral'
).encode(
    x=alt.value(410),  # pixels from left
    y=alt.value(290),  # pixels from top
    text=alt.value(["Number of observations:", f'{cars.shape[0]}'])
)

text + chart
```

![image](https://user-images.githubusercontent.com/4560057/154853606-632d4f83-2d2c-4cf7-9e67-fdf11ccd3ec0.png)


There is an example with a text box https://github.com/altair-viz/altair/issues/2430#issuecomment-812090575

**Comment by ihightower** [comment]
Hi above did not work as it is.. I needed to add the  `values`..

Is this normal? Hope this helps.

```
text = alt.Chart({'values':[{}]}).mark_text(
    align="left",
    baseline="bottom",
    fontSize=14,
    fontWeight=600,
    color='coral'
).encode(
    x=alt.value(410),  # pixels from left
    y=alt.value(290),  # pixels from top
    text=alt.value(["Number of observations:", f'{cars.shape[0]}'])
)
```

**Comment by jakevdp** [comment]
You need to add values in Altair 4.1 and older; if you update to Altair 4.2 or newer it is not necessary.
