### ISSUE TITLE
faceted chart does not re-size on `transform_filter`

### ISSUE THREAD

**Issue by jbloom** [altair-viz/altair#2560]
When a simple non-faceted chart includes a `transform_filter` that removes some of the data, the chart automatically resizes such that the drop-down selection boxes remain just below the chart.

But when a faceted chart is transformed to just include some facets via a drop down selection, there is a huge gap in whitespace between the remaining chart facets and the drop down as the space for all the empty facets remains.

Is there a way to fix this?

**Comment by joelostblom** [comment]
Could you check if this solves your issue https://github.com/altair-viz/altair/issues/2512#issuecomment-965600160? If not, could you provide a minimal example illustrating our issue?

**Comment by joelostblom** [comment]
Closing for now, please re-open with the requested details if this is still an issue.
