### ISSUE TITLE
Displaying multiple data points with tooltip

### ISSUE THREAD

**Issue by samesand** [altair-viz/altair#2562]
Is there any way to display multiple data points in the tooltip when they are on top of each other? e.g. if I have a scatter plot where I have two data points with the same coordinates x and y but different names, is it possible to display both names in the tooltip when I hover over them?, or maybe displaying two tooltips? one for each point.

Just to be clear, I'm not trying to display multiple fields/columns for the same data point, I'm trying to display multiple points/rows

Than you.

**Comment by joelostblom** [comment]
I *believe* this is not possible since the tooltips are triggered when the mouse pointer hits a mark and technically it cannot hit a mark that is perfectly covered by another mark. You could raise it as a feature request on the VegaLite issue tracker and include an example.

**Comment by samesand** [comment]
Thank you. I will ask for the feature in VegaLite.
