### ISSUE TITLE
Document the differences between `value` and `datum`?

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2572]
I struggle to find a use case for `alt.value` since `alt.datum` was introduced in 4.2.0. It seems like the latter completely covers the function of the former + more. ~~If that is the case, should `value` be deprecated to encourage the usage of the more powerful `datum`? Deprecation or not,~~ I can add something to the documentation once I get more clarity on the relationship between the two.

I just found one difference that I don't know if it is significant. I seems like `datum` constructs an axis when used with a primitive value / constant, whereas as `value` does not (this could possibly be more convenient when trying to place in a single label in  a chart since you don't have to worry about hiding axes?):

```python
alt.Chart().mark_text().encode(
    x=alt.datum(0),
    y=alt.value(0),
)
```

![image](https://user-images.githubusercontent.com/4560057/159953181-cc22b1ab-f6c1-4760-853a-aab46fcfda29.png)

**Comment by jakevdp** [comment]
This would be good to document. `alt.value()` specifies a constant range value, while `alt.datum` specifies a domain value. So `x=alt.value(100)` would place a mark 100 pixels from the left edge of the plot, while `x=alt.datum(100)` would place a mark corresponding to the location of x=100 on the x axis.

**Comment by mattijn** [comment]
Fixed by https://github.com/altair-viz/altair/pull/2735
