### ISSUE TITLE
Sales pitch for variable parameters

### ISSUE THREAD

**Issue by ChristopherDavisUCI** [altair-viz/altair#2579]
What is a good sales pitch for the importance of variable parameters?  I find them significantly harder to motivate than selection parameters.

The [Vega-Lite documentation](https://vega.github.io/vega-lite/docs/parameter.html#variable-parameters) shows some nice examples, which I think make clear how variable parameters could be useful in the design process.  (For example, if asking yourself, "What cornerRadius looks best here?", you could bind the cornerRadius value to some slider.)  But I can't imagine using any of those examples in a finished product.

@jakevdp I learned a lot from your two `value` vs `datum` examples in #2572, and I'm hoping you have a similarly nice example in mind for variable parameters!

(I wanted to add the `documentation` label, but as far as I can tell, I'm not allowed to.)

**Comment by joelostblom** [comment]
I added an example in [parameter-values-in-expressions](https://joelostblom.github.io/altair-docs/user_guide/interactions.html#parameter-values-in-expressions) of how variable parameters can provide a more convenient syntax than selection parameters. But the change in the chart itself is still more about aesthetics as you point out.

**Comment by joelostblom** [comment]
I think I found one great use case based on https://github.com/vega/vega-lite/issues/7365#issuecomment-1058909767!

To use a dropdown to change which column is being plotted on an axis, you previously had to melt the dataframe and filter the "key" column like this:

```python
import altair as alt
from vega_datasets import data


df = data.cars()
dropdown_options = df.select_dtypes('number').columns.tolist()

dropdown = alt.binding_select(
    options=dropdown_options,
    name='X-axis column '
)
selection = alt.parameter(
    name='measure',
    value=[{'value': dropdown_options[0]}],
    bind=dropdown
)

alt.Chart(df).mark_circle().encode(
    x='x:Q',
    y='Horsepower',
    color='Origin'
).transform_calculate(
    x='datum[measure]'
).add_parameter(
    selection
).transform_filter(
    selection
)
```

By using parameters, it is not possible to express this with a syntax that is both briefer and clearer!

```python
dropdown = alt.binding_select(
    options=['Miles_per_Gallon', 'Acceleration', 'Displacement'],
    name='X-axis column '
)
param = alt.parameter(
    name='measure',
    value='Miles_per_Gallon',
    bind=dropdown
)

alt.Chart(data.cars.url).mark_circle().encode(
    x='x:Q',
    y='Horsepower:Q',
    color='Origin:N'
).transform_calculate(
    x='datum[measure]'
).add_parameter(
    selection
).transform_filter(
    selection
)
```

They both give a chart that works like this (although there are different columns in this old gif):

![](https://i.stack.imgur.com/zM6Nz.gif)

It should also work to update the axis title by including `x=alt.X('x:Q', axis=alt.Axis(title=alt.ExprRef('measure')))`, but this leads to a schema validation with Vega-Lite 5.2 that expects only strings, although the dict actually renders fine in the editor: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCFIAnADYoQYwgAdKyAPTGwdKADoAVpTqZNcNOstRMhY1H0BbY2kwICgC0isqU7pQAAmgAjJYATACclmzGoQpmCuqUNpTQIHIg3lkA1jpgcOpgmpgg3JhQkHQkSKg8mhDqqvAOdDoA8uqIJHUghACe+rXIIFAQ3iQK2oUAHqoKK3CUqsSENaqYK-pdM96YCpQatbLcPZp9M2vcE1M6AI6kCkRwysT+Bdxxt0sPcdIJOuF9BBsJgus9JtMQB8vrslE5roV9FkFN5tsgANqgKA4xFnC5XUYAIxID1AJH0pHEM3CNTA4m4EH0xGgePxIAAsnAapQAPpTdQigDiSw6UFGAEEwGAHLC0fluAARLb6TQKZVnIggAC63GJZx0AA0ghstgACSCaUjeKC2gEgNBLUiIwXCsWwqUy-LSE1jdRfSgwTreFCE8BLMCkXWERGhJ34smXdSYI2jC46NZyUDwTTJk6gLFh6Onc6ZjEhgAklDAjEwxR0ekMJj8AQUlgQP0YpEpljgEGMTZbxW7gSCjmTfgArAkUrkg0A)

**Comment by ChristopherDavisUCI** [comment]
Thanks a lot @joelostblom for these examples!  I don't think I was up-to-date on the best way to select columns for an axis, and that way you provided is very nice.  I'll close this issue.
