### ISSUE TITLE
Jupyter notebook is not displaying charts inline.

### ISSUE THREAD

**Issue by dove88** [altair-viz/altair#2594]
Hello, I am trying to render Altair charts in jupyter notebook, but I am getting only blank inline output.
I am using "alt.renderers.enable('notebook')" renderer option in my jupyter notebook.
'Mimetype' renderer is  working fine in jupyter lab.

I have attached browser console for more details, kindly advise me to how can I solve the issue?

Altair version - 4.2.0
Vega version - 3.6.0
Jupyter notebook version - 6.4.10
ipykernel 6.4.1
ipython 8.2.0
ipywidgets 7.6.5
Browser Mozilla Firefox

Please do the needful 
Thank you
![IMG_20220421_201827](https://user-images.githubusercontent.com/85496354/164487541-a331297b-9ae4-4d14-ae19-61df505f283c.jpg)

**Comment by joelostblom** [comment]
Does it work in the notebook with ` alt.renderers.enable('default')`? If that doesn't work, there are some additional tips on this page in the docs that you can try out https://altair-viz.github.io/user_guide/troubleshooting.html

**Comment by dove88** [comment]
@joelostblom 

Hello, I have tried with Google Chrome first, then I shifted to Firefox, to check whether the case of browser issue. In both cases, it doesn't work. Infact I am using latest version of both browsers.
I did change, the renderer option to 'default' before I posted this thread and also gone through the display troubleshot website contents too.
Nothing worked till now.
I was using node 14 version, but yesterday I installed latest stable version for checking the compactibilty issue, however the issue remains the same.

This is for you info please.

I have vscode jupyter notebook and jupyterlab, the Mimetype is working fine in both these applications.

**Comment by joelostblom** [comment]
Hmmm, the only additional thing I can think of is if you have a browser addon that blocks the connection. I would try in a private/incognito window with all addons disabled. It is possible that this could be why you see `blocked due to mimetype mismatch vega`, but there might be other reasons. This seems to be more directly related to Vega and JupyterNotebooks so I would try asking in https://github.com/vega/ipyvega for more help

**Comment by dove88** [comment]
You might be right...
I have gone through the link that you have provided in the reply, and this command,
'pip install jupyter pandas vega'.
Is it a separate installtion than my previous installtion of jupyter notebook, pandas, Vega?
Since I have installed all of these packages, do I need to install again with one line command?

**Comment by joelostblom** [comment]
This error should not be related to your installation of those packages. I am closing this in favor of https://github.com/vega/ipyvega/issues/412 since I am not sure if there is anything additional  to add beyond what is mentioned there regarding the firewall.
