### ISSUE TITLE
Links within interactive figure don't open on click (unless via SVG)

### ISSUE THREAD

**Issue by bmorris3** [altair-viz/altair#2596]
Hi all, 

I'm seeing a similar error to vega/vega#2641 again, where I'm trying to replicate [this altair docs example](https://altair-viz.github.io/gallery/scatter_href.html), but I find that clicking points doesn't trigger the href'ed link. My example figure is hosted [here](https://owls.readthedocs.io/en/latest/owls/sindices.html) on RTD and the source code is [here on GitHub](https://github.com/bmorris3/owls/blob/master/docs/owls/sindices.rst#interactive-plot). If I save the figure as an SVG, the links work properly. 

I tried using a newer version of vega with https://github.com/vega/vega/issues/2641#issuecomment-632459205 but it didn't help. Any tips?

**Comment by joelostblom** [comment]
I just tried the linked docs example and it works fine for me in JupyterLab with Altair 4.2.0. I believe the issue with your example is `nearest=True` which seems to be incompatible with `href`; if you remove that line the clicking works. It might be worthwhile creating a minimal example using the doc sample code from Altair and report on the Vega-Lite issue tracker (with a backlink here).

**Comment by bmorris3** [comment]
Removing `nearest=True` fixed it for me too, thanks!
