### ISSUE TITLE
`transform_fold` does not work if hyphen (`-`) in column name

### ISSUE THREAD

**Issue by jbloom** [altair-viz/altair#2600]
The example of `transform_fold` here (https://altair-viz.github.io/user_guide/transform/fold.html#user-guide-fold-transform) fails if the columns are instead renamed to something like "A-A" and "B-B". I think there is a general problem with hyphens in column names. Is there a solution to this?

**Comment by mattijn** [comment]
Did you try to escape the hyphen? `A\\-A`?

See also https://github.com/altair-viz/altair/issues/2494#issuecomment-919338355

**Comment by jbloom** [comment]
Thanks!
