### ISSUE TITLE
Link to the appropriate "schema wrapper" objects in the API docs

### ISSUE THREAD

**Issue by multimeric** [altair-viz/altair#2608]
Most of the API docs make numerous references to schema wrapper objects, for example [`altair.Chart.configure_axisX()`](https://altair-viz.github.io/user_guide/generated/toplevel/altair.Chart.html#altair.Chart.__init__), but don't actually explain the method options or link to the appropriate wrapper object. This makes it *incredibly* difficult to navigate the docs without constantly using the search or having the Vega schema open in another tab. For example `configure_axisX` should link to [`altair.AxisConfig`](https://altair-viz.github.io/user_guide/generated/core/altair.AxisConfig.html?highlight=axisconfig#altair.AxisConfig). Fixing this would make the API docs a lot more user friendly.

---

Please follow these steps to make it more efficient to respond to your feature request.

- [x] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most feature requests should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example.
- [x] Search for duplicate issues.
- [x] Describe the feature's goal, motivating use cases, and its expected behavior.

**Comment by joelostblom** [comment]
Thanks for this suggestion @multimeric ! I agree that is sounds more helpful to link to the second page you are suggesting. I am not sure if this is autogenerated in the docs though and would need to look into that. Do you have an example of a page that links to [altair.Chart.configure_axisX()](https://altair-viz.github.io/user_guide/generated/toplevel/altair.Chart.html#altair.Chart.__init__) or similar?

**Comment by multimeric** [comment]
Yes, so all the "low level wrappers" link to each other correctly. e.g. [`altair.Legend.direction`](https://altair-viz.github.io/user_guide/generated/core/altair.Legend.html#altair.Legend) links correctly to [`altair.Orientation`](https://altair-viz.github.io/user_guide/generated/core/altair.Orientation.html#altair.Orientation).

My guess as to the cause of this error is that the docstring for `configure_X` is just copied from the docstring for `X`, but it should also *link* to `X` which isn't in `X`'s docstring because it would be redundant there. You can see this behaviour in the decorator here:
https://github.com/altair-viz/altair/blob/fc7f5510d189303aa58e751cb5876fb4929f36c8/altair/utils/core.py#L533-L557

**Comment by multimeric** [comment]
Hi @joelostblom. I've had a go patching the docstrings in #2610. However this only fixes the `configure_X` functions. For things like `aggregate_X`, I'd like to do the same, but it seems like `altair/vegalite/v5/api.py` might be autogenerated, so if I edit the docstring for `def transform_aggregate`, it might not be the right place. If so, where is this generated from? I can't work it out.

**Comment by joelostblom** [comment]
You're right, I mixed up which files are autogenerated. It is only the files within the `schema` directory that are autogenerated. The `api.py` file is not ([as mentioned in the maintainer notes](https://github.com/altair-viz/altair/blob/master/NOTES_FOR_MAINTAINERS.md#updating-the-vega--vega-lite-versions)), so you should be able to make your changes there directly.
