### ISSUE TITLE
Unexpected behaivor combining different pie charts

### ISSUE THREAD

**Issue by krlng** [altair-viz/altair#2618]
Hi :) 

I played a bit with the new pie charts and discovered, that its visualization depends on other pie charts it is displayed with. I guess its a bug in the way the alt.Theta works (it seems to calculate the full circle not for each chart, but the biggest one).
<img width="975" alt="Screenshot 2022-06-17 at 10 37 09" src="https://user-images.githubusercontent.com/1107509/174261281-4fda8e5d-2fba-41ed-bfaa-9b19f15f18ee.png">

**Code for reproduction:**

```
df = pd.DataFrame({'name': {995: 'Oceania', 372: 'Americas'},
 'cement_co2': {995: 3.524, 372: 79.719},
 'coal_co2': {995: 171.30100000000002, 372: 184.12},
 'flaring_co2': {995: 21.362000000000002, 372: 66.902},
 'gas_co2': {995: 89.064, 372: 632.215},
 'oil_co2': {995: 154.49599999999998, 372: 1085.104},
 'other_industry_co2': {995: 4.651, 372: 8.486}})

charts = []
for name in df.name:
    charts.append(alt.Chart(df.loc[df.name == name].melt("name"), title=name).mark_arc().encode(
        theta=alt.Theta("value:Q"),
        color="variable:N"
    ))
    
# img1
charts[0]

# img2
charts[0] | charts[1]
```

**Comment by mattijn** [comment]
```python
(charts[0] | charts[1]).resolve_scale(theta='independent')
```
![image](https://user-images.githubusercontent.com/5186265/174284836-a73fc133-1a69-4202-808e-4ea2fef26237.png)

Default behavior of compound charts is to have shared scales, including `theta`. Use `Chart.resolve_scale()` to adjust the default. As is described here: https://altair-viz.github.io/user_guide/scale_resolve.html#scale-and-guide-resolution

**Comment by krlng** [comment]
Ah, nice and easy fix. Forgot about that.
