### ISSUE TITLE
How to set a multiline title for an axis or legend?

### ISSUE THREAD

**Issue by fredthedead** [altair-viz/altair#262]
Passing a string with '\n' in it doesn't seem to work

**Comment by jakevdp** [comment]
I don't believe this is allowed currently in Vega-Lite.

**Comment by kanitw** [comment]
Yep. This is currently not supported in Vega-Lite due to lack of support for this Vega. 
But there is a feature request in Vega. https://github.com/vega/vega/issues/488.

**Comment by ellisonbg** [comment]
Closing as vega-lite-related.

**Comment by firasm** [comment]
Sorry to comment on a closed issue, but could someone clarify how `vega-lite-related` issues work? I understand it needs to be implemented in Vega-lite first, but will it "automatically" work if it's implemented there or is there a delay while `Altair` features catch up ? It seems there isn't much hope of waiting for it to be implemented in Vega-lite...issue 488 seems pretty inactive.

This functionality is pretty essential (in my opinion) and I'm trying to figure out whether a PR to "hack this functionality" in `Altair` would be supported (assuming I can figure out how to do it).

**Comment by jakevdp** [comment]
"vega-lite related" generally means there is no change you could make to the Altair codebase that would address the issue.

**Comment by firasm** [comment]
ah okay. thanks then

**Comment by nbmorgan** [comment]
Can we reopen this? Looks like vega-lite will support this but requres passing a string array instead of a string.

**Comment by cjbraun** [comment]
For anyone revisiting this, Vega [now supports](https://github.com/vega/vega/issues/488) this multiline functionality. Just pass in a list of strings as the title:

`axis=alt.Axis(title=['Text on the first line', 'and text on the second line'])`

**Comment by NickCrews** [comment]
@fredthedead If you wanted to edit your original post to include this now-working solution, I'm sure people would appreciate it!

**Comment by joelostblom** [comment]
We do currently cover this for chart subtitles in this doc page https://altair-viz.github.io/user_guide/customization.html#adjusting-the-title, but if anyone wants to add an example to that page with an axis title (or chart label for that matter) that covers two pages, then I would be happy to review a PR.
