### ISSUE TITLE
Example gallery should show how to mark and label the final value in a timeseries

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#2622]
Charts like this have become commonplace in the COVID pandemic. It would be great to include an example showing how to do it. I'd submit a pull request, but I don't know how to do it! If someone can show me how, I'll submit an example for the docs.

![Screenshot from 2022-06-29 14-29-55](https://user-images.githubusercontent.com/9993/176548481-3de2dd2e-a90e-4fed-addf-98b94d29f4c2.png)

**Comment by joelostblom** [comment]
Agree! I think direct labeling is often preferred over legends and I recently came across [this example](https://vega.github.io/vega-lite/docs/aggregate.html#example-labeling-line-chart) in the VegaLite docs that uses `argmax` for this, which is nicer than the more manual pandas approaches that I have used myself previously. Would you like to make an attempt at translating that to Altair code in a PR?

**Comment by palewire** [comment]
Good idea. How's this look?

```python
chart = alt.Chart(source).transform_filter(
    alt.datum.symbol != "IBM"  # A reducation of the dataset to clarify our example. Not required.
).encode(
    color=alt.Color("symbol", legend=None)
)

line = chart.mark_line().encode(
    x="date:T",
    y="price:Q"
)

label = chart.encode(
    x=alt.X('date:T', aggregate='max'),
    y=alt.Y('price:Q', aggregate={'argmax': 'date'}),
    text='symbol'
)

text = label.mark_text(align='left', dx=4)

circle = label.mark_circle()

line + circle + text
```
![visualization](https://user-images.githubusercontent.com/9993/176556916-f4850c1c-cfd2-4017-8028-4eb159efe6de.png)

**Comment by palewire** [comment]
The PR is submitted in #2623
