### ISSUE TITLE
Setting title='' for an axis should remove that axis's title

### ISSUE THREAD

**Issue by dhimmel** [altair-viz/altair#264]
Is it possible to suppress the titling of an axis? In other words, no title is displayed next to the axis, and there's no space allocated to the non-existent title. 

I tried passing `title=None` and `title=''` to `altair.Axis()`, but then the axis title falls back to its default. Passing `title=' '` results in extra blank space.

I didn't see [anything in the documentation](https://altair-viz.github.io/documentation/config.html#adjusting-axis-labels) on this matter.

**Comment by jakevdp** [comment]
I always use ``title=" "``

Looking into it, an empty ``title=""`` is actually supported in Vega-Lite, but Altair scrubs it... probably somewhere we have a check that is something like ``if trait`` rather than ``if trait is not None``. Let me look into it.

**Comment by dhimmel** [comment]
Ah yes, I played around with the [live vega previewer](https://vega.github.io/vega-editor/) (very cool). Changing `title=""` to respect the empty string would solve this issue for me.

**Comment by jakevdp** [comment]
Found the spot where it's dropped: https://github.com/altair-viz/altair/blob/master/altair/schema/baseobject.py#L119

Unfortunately the simple fix breaks some of the round-tripping unit tests. I need to figure out why.

**Comment by jakevdp** [comment]
Fixed in #265. Thanks for the report!
