### ISSUE TITLE
Returning the selected string value from selection_single

### ISSUE THREAD

**Issue by JuliusSempio** [altair-viz/altair#2659]
Good day. I've been wrapping my head for hours about solving this issue by searching for the solution online, to no avail. So I decided to try to directly ask from Altair devs.

I am trying to automate the generation of the title of the scatter plot for convenience purposes, but I can't find proper documentation on accessing the selected value in the selection_single dropdown component. The following screenshot should give the idea on what I am trying to achieve.

![Screenshot 2022-07-20 151207](https://user-images.githubusercontent.com/102203004/179920155-5ac2df92-baf3-4146-948d-120cc7e9075e.png)

Any help will be appreciated :)

**Comment by joelostblom** [comment]
To get the string value in the title, Vega-Lite would need to support the use of parameters in title but this is not yet supported as per https://github.com/vega/vega-lite/issues/7365#issuecomment-1059153390

**Comment by JuliusSempio** [comment]
Good afternoon. Thanks for the prompt reply. Then it's the hard way for me for now then :D
