### ISSUE TITLE
when using `sort` on ordinal axes, `Maximum call stack exceeded error`

### ISSUE THREAD

**Issue by jbloom** [altair-viz/altair#2663]
I am trying to sort an ordinal axis using the `sort` keyword. However, when the number of values being sorted is large, I get the following error:

```
Javascript Error: Maximum call stack size exceeded
This usually means there's a typo in your chart specification. See the javascript console for the full traceback.
```

Here is a minimum reproducible example. (This is a toy example, I realize this particular toy plot could be done with a quantitative axis, but the example captures the problem with the real data I want to plot).

Specifically, the following code gives the above error when the value of `n` is large (say 1500), but not when it is smaller (say 200):
```
import altair as alt

import pandas as pd

n = 1500

df = pd.DataFrame({"site": map(str, range(n)), "value": 1})

(
    alt.Chart(df)
    .encode(
        x=alt.X("site:N", sort=list(range(n))),
        y="value",
    )
    .mark_point()
)
```

**Comment by joelostblom** [comment]
This is an issue in Vega-Lite which seems to limit sorting to 1000 elements as you can see by [opening you chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3OgENCCvCCgKAtphQhFygLQBOFpgCMAdjAA2Q5gAcFthMwAmAKwLTMK6YBGvujZzTAkYNhYQORANBQAnAGsdAAcIEnFuTChIOhIkVBAAD1V4TAAbOh1KOEJtbkoIWPFkAG0uU04XTglOFk43TitOc047TkNOUzb2007TbtNe037TQYsJ0dNxly4XdpdOl26XXvcOwZdhl1GXcaku9olOiW6JXol+iUGJYYlRiXH2D12ixOixuixeix+ixBixhixRixxm4uG52m5Om5um5em5+m5Bm5hm5Rm5xlYuD4Bp0rN0rL0rP0rIMrMMrKMbEMuOZ2uZOuZuuZeuZ+uZBuZhuZRuZxnYuA4Rp07N07L07P07IM7MM7KM7ONDFxDO1DJ1DN1jGN+oZBoZhoZRoZxpM2mxpmxZk4JuFvcs2Ksgt6NmxnZMJqZpjNw-MFuHlitw8MIxtNhNtmnpvs0-Njmnli5Vhc0xsbhM7nNpo8y-NXmXlp8y0nfmXnYCFtMQRMwV3FlCu6s4V2NkiJijR9MMaP5jjR8sCaOkyTR86KRMqStZrS14tGWvVqy1xtOY4JjzT7MBafFiLT6sJaeNjL1m0FaY7LNletFur1qttesNn1CZDWA6ZTWA+ZLU2ZYbWApMHWArYOA6N0UIOL1thONh+m2c5A22a4Qw6MNdj2KNdiOWNdhwhNdkuN9iK2dN9j2LN9iOXN9hwgsOiLfZrlLQ4dgkPYq0OI5a0OHCG0OS5m0OLZAWOPZO2OI4IQ6PtjnOQdjmuEd3B2NEOkndwjhndwcPndxLiXdwtlXAs9isA4twLE5dwLc4DwLa5OQuHYzwuA5LwuE4bwuc57wua4nyuHYFSuA5PyuE4fyuc5-yua4gJuHZjQ6cCbiOS0bhw2CbkuBCbluZCpAeD0ui9KQ3mwpqvkDKQ-iIkSuBEh4oxEl5YxEj4ExEn4GJE2500eB4s0eF5c0eD4eMeH4ri6Utnj6kSuirZ4XlrZ4PgbZ4fmbZ5bkBV4Hk7V4Xg014PhhLpB1eP4R3ePrjPeJ4sS6Gd3g+ed3h+Jd3luVdPgeFyui3T43l3T4vgPT4-k5b4+rPb4nkvb43hvb4vnvb4-ifX4+oVX4nk-X43h-X4vn-X4-iA-4+oK-4nnNLpLX+D5YP+H4EP+AFkPYYFGvYcEfXYaF-R6QN2ERIiWDDdXgSjdXwVjdXoQTdX4QY9WAXTEFgSzEFwVzEFoR4kF4U2kEATuMFgSrMFwVrMFoQbMF4WbMEAUBCFgU7CFwQ0iFoVeiF4QRHoRyhLgoWBScoXBGcoWhecoXhJcoQBVcYWBOGYXBekel3GFYQPGFEU5OFU7POFQUvOFIRvOFYXvOFESfBFU4VBFQU-BFIR-BFYX-BFESApFU4KpFQV5pFIUMaFYKReEEKRZFkJRdFGpRbEfRRfFFZRYk2FJIi0VRCM+ijNFsVjNF8QTNFiQYtFkXTDE6IswYmxLmDE+IeIYmJJtDEyI7hYnRFWLE2JaxYnxA2LExJmxYmRICHE6JOw4mxBpHE+JXo4mJInHEyIxx4nRJOPE2IZx4nxPOPExIlx4mRKuAk6I4YEmxFXAk+JmR9APASUknIiSojPESTEl4iS4hvESQk94iSkifCSVECoSSYk-CSXEP4SSEn-CSUkQEySogKmSTEvMyS4k3n0WCZJiQITJOSZCFJ2gUhpF6CkDI2oUhZIGCkHIiI+EpE-HwNI5gDFjD4JkCYfBsgYj4ck6YXLeKzC5OkuYXJMh4i5Nkm0XLkjuLSbxVZaR0lrLSJkDZaRsmbLSckgJ6TeM7PSOkGl6RMlevSNkid6TkjHIybxk5GR0hnIyJk85GRsiXIyckq5mTeLhsyOkVdmRMlEcyNk7IBiclZJSM8rIaSXlZAyG8rIWT3lZByJ87JKQKnZDST87IGQ-nZCyf87IORARsJSAqNgaS8xsAyRxNgWR2gGAhGw4xzDIURbyRqiLBQ+kRaKRWiLJS3y5AisMPJeRRh5IKWMPJRQJh5JKBiPIEXpj5LyLMfJBS5j5KKHifJJSbT5Aiu4ApeRVgFIKWsApRQNgFJKZsAoEWAiFLyTsQpBQaSFKKV6QpJSJyFAiscIpeSThFIKGcIpRTzhFJKJcIoEWrjFLyOGYpBRVzFKKURYpJQHLFAixFQwzwSn5JeCUwobwSnFPeCU0onxSm5AqKU-JPxSmFD+KU4p-xSmlEBGU3ICoyn5LzGUwpHEynFDCmU0onQjGQnKdocolRejlGqNqcotSBjlHqIiDh5RPwcEqWJDg1RLBGAmBwOoGIOFlOmd81aszvhVLmd8GoeLvh1Jtd8so7jKmrVWZUKpazKg1A2ZUOpmzKllICVU1bOyqhVBpVUGpXqqh1InVUsoxzqmrZOdUKoZzqg1POdUOolzqllKuTU1a4aahVFXTUGpRGah1AczUspvXamrXyEYl5tRqhvNqLU95tR6ifLqeUCpdRKk-LqNUP5dRan-LqPUQF9TygKvqJUvN9RqkcfqLUML9R6nLYaI0qFDRmi9IaXohprSK0NPaPFhoDRhmNCaKMxoLSxmNNaBMxp7QMWNAadMpoTRZlNBaXMpprQ8VNPaTapoDR3HNCaKs5oLS1nNNaBs5p7TNnNAaQExgTSdmMBaDSxhrSvWMPaROxgDRjk3iaScm8LQzk3taecm97RLk3gaVcNoTRwxtBaKuNprSiJtPaA5NoDTertCaNDdoLRCjGDeO0tp7x2kdE+B0RoFQOjNJ+B04mfwOltP+B0jogJOiNAVJ0ZpeZOnE44p0toYVOkdE6AAutwQgABPJI2hkBqAgBoEgChSiRG4Ft4oWByg6DQCd0gtQQDbd2zoAAjqQBQRBqhKDgGgbQshuAABJKBgEYJgGIOgxCECSJQZAAB6WHv2EAKAAHQIGqIwUgvhkdwAgLD4HoOYgI8wEj-QpRqiYAR24ZHLhkdsGRwAK3qFAEA8glAKEoJgQglBVB6AUEYEwFhrC2GHU4VwHgvA+H8IEYIoRwgoGaKAKoNQdBsBZyAW7pR7soFMHIRX5OdCmDVxrrXyAdecD18r-bLgjd3b22bi3e2QASBt5ru3uuQBK8dxEbgxu3fm49-r-bbgXcm-twHy3IArAh79w7nQ5ho-a-d57nQdgE+m6T4HkAhg09h+T-tyYOeM8R4jIX-3eeQAzFL7H-Pzufe28T2XzPCwq-h8d0sFv5eVgd6b-HuvruG-V4r6nvvoei9t+zyPmPredDbG7xH3Yc-Hf7EXzP2v6v6-p8b-P736-++b8H+4FfVuo+T4H9Pq3vfd+j630v4fV+p-l5uEfp3qvT-7-P07w3b-c+Z8eM-54-+O+vuZ+5e7w-+J+9+IBv+l+wB7+oBd+sBP+Ee-wz+7AqBX+kBcBmeIIqBa+iBY+OgEIqBwe3+BB+2MIqBMBG+SBXuCB1BZBIASIz+KIzBGB+BN+OgGIzBeB9BHBQeQBvBg+eIzBEB7BQhVBe+NBnBdBkhDBZIz+FIChbBghH+LkChPBshfBkeAhmhg+jIChohKh5erIChMh1+ehE+mBUh+2iKz+PIdh1upBWhAodhOh5hH+IodhhhuhHhEh7h5eUodhlhYhH+coz+Dg4RjhVhDByo4RbhD+me6o4R3h-hiRfhCREeuo4RwRRhmehoz+xoBRURIR5e5oBR8RUBEem8BRKRGRjudoBRZhdROgToz+LobRboHRxRuRxeTgHRFRWBvRJB0RWhkwtRlRbeQQHRTRExBuIYbRBeThg+EYyhPhneleSxH+EYGhqRxezemx6xwxJRTeXeBxJx6Rsx+eb4CxORaxTes+ZxxeC+jxbey+LxBuhwbRxwXxRxPRrx4xgxrxFxgJHxMxIJ+eT+7xNer+IxyxIkbRf+UJFeABSJcwAx1hyJvxdxxenwCJwJGJcwYJBJKBqJaBpJqxuxbeOBpJOxzR+eRBpJWJlJBuFBpJ+JDBCwRJHJTBqJLBvJFJdJFeXBvJtJlxQp6JHJwhvJAJBJRIbRJI8ptxzJ+eihqJPgbRahapop4JFe9IGpTJgpKwMpHJJhapXJoxNgbRthqJ9hNp3R2JbeLhNpEpoxnhNpxprp7Jrp5pyxMobRYRqJERgZ9pypQ+2pBJqo-pBpYpb4Hpyx2o-pPpWx+obR+RqJhR6ZIZhpZR6ZLpyx1R6ZcZWxDR6ZSZnerRSJ2wMJxx8+nRlZHoz+2w4ZDBmEjZ2EbZRZj+Ux9ZZZme2wSpgpuw1ZfxM+JelZGxsJH+FEjZ+xk5j+7e45nZfZFgM5vZ8+mwjZDxc5fZzx258+bxe5S+nxlZ3xJ50ZOp+wS5+5XpB+Vwm5A5YpQkjZ8JlZiJh5q+zZWhhweZU5YBr5V5S+3wz5a5gFD5F5ZJ75Vu6sjZ1JkFIAakMFP5j+UIMFAFM+cIMFIF6FYFGJhkjZaI+FWZj5WI+FSFfZUpcF7gaFVucplZCpdFOFLZqplF6plZmpLFn5B+epbF55uFzIjZppLFWFx+jFX51plFtpElRFF5TpElZF8+bpEl1F8FEojZgRlZfplZAZlFQZOl0luFsRWl8lt+vFLZmojZCZWlwl8FKZlZaZlFGZDl+lLZOZDlxlM+BZDlyllUjZDovlolg+Ugw5DpOg9U-+DZSJUgnFH+LU4VplWhUgylUgN5MVt84VAVMVixcF-U-+E5NZjuQ0uV7l+2o0uVSVK5kV1xlVGVoBW5+VoVu59VJVB5TVTux52Vp5HV8VgVBY-+FwfV1ljwNVv+Ug-+L52Vb5rVh0Y1xVTuf5E1SVQFkVvwY1w1yBEFU10FkVsFm10VoBDJ2VKF21SVGF21g1PJ2VfJl1ApYpf0-+JFkVOI913VMVBI91KVoB9Fl1a1BVzFU1rF2V7F-1e1v+3FgNL1oB-FkVgl-1g1lpkV4lU1klSNzlCVslSNs13wEN0BSVqlCNg1ml2V2lU1ulJNqNgVhlRNmNSRkV5ltNH1v+WRtNP1oV9lU1jl7N5NMVrl7NmNnl7NSVJZ2VflkVFZcF7AwVoZksqBEV4tfRSJ7As18sMtyl7ADNEeKsMtLN5BWVrVms6BXN5eOs6BStC54tpx5t6tXuVV5t2tjBdVI55BjVjt9tht2B7VetnVnt2NGtvVCt-V-t1lLsuBktgp7suBbtGtKJ4trwuBPtXuuJCtS1MdQdJJ4tG1LtYcqBO1mdYI2dStR16dqtp16dQdF1etV1FdN1OpUIkdXuD14tT1CtFFFdqttFjdQd8hCtf1mdANetQNvdINGtYN-d8dhBUN4tMNvdQd8N4tiNmdyNC9ddhB6NC9StiletYolBVtK9QdhNetxNmdpNR9y95BlNB9StNN4tdN19O9Z9Qdtl4tbNmdHNL9p9jBPNL9St-NL9qtQtetItT9dtKIodYpR8zBstrVp8EDs1F8EDyl18ED1lKIwDutLtaI1dGJaI79r8rBsDZtUDFthDd9IAaIyDG5SJGIoDOpgCzBLV6DHtDDsDh+lDftcFUCdDyDkJ7Do1lD41UDk16D0dAjsD81AjCDydAjyDadUDGdIV-BmDchOd8jpDedlDB1sjY9-BCDJdsjyD5d6DldhjijWheIODDdUDTd7DLdhjCD7dljyDXd7DPdKjvCIhODtIIhsD+hlDE9UDU9rj7IIhwD89rji9YTODq9YTsDG96DW9lDeN7D6lSTwDh9rjx96TOD596DkZlDV9UDN9BTJDZizBj9UDz9rjr9lTODn9lTsDP9lTCD-96DgD5TdtFI1DGJXiChkDLtFIQ9ju-iPTWjke-oPTJDoSPT7TaDKjPgJjeheVfTcwShs1CSShylySSh1laSChDtszzt+z79OSuzqzLDcFLkGzAd5zd5SJpS6hnTDBFS6hRzwjfTsdtzYjbzGzkjbz2zMjfTcjoZ7SChyjQLaj5zGjALIz9IGzujAL2zBjszRjSL8zqhwp5zFjfTVjrVMyChb1tz9jWL2zTjOLLjQLfdfTA9sznjtzI9lL0LfjlLEzQTtL7ToTQL4THLRzUTHLqzsTsz8T5ziTOLyTIr7TaTQLGTkrRz2TszuT5z+TfThTSrEzTNCr7TFTQLVTWrRztTWrqzDTWrGzzTszrTfTYtrViKDzzhdZcFiK79aKdhcuSJmKTrylOKTr1liKdtPI1rg+RKdhizKjpKgbs1FKgb7rFVdrNtlrFDdrezoZjKDhDrjDwbXtLt7KDh7rVzlrNz8bPrvDdr-DGbgjwbrzZbYbnzZb7rPzZbXr-zwbgLgp8qrhDr4LlrkLjbIzQo7rcLjbXriLibyLQ7qLAR6LlrmLwb2LGbNjU77rhLU7XrJLGbZLzbFLwbVLibNLdrdLG73bjLG7JDYoXrs9lr7LzbnLF7DrPLF7Yb-LibgrZ7R7orGb+9GbErzbUrn7Drsrib8rlrirwbyrQHR7arAHPrmrzb2rUHDrerUHYbhrUH7rJribZrwbFrLtcofroRtrrVNa4R8tcF9aBHIzTaBHJDraBHdtHa4RY5RHQboZDgAzKes5eHBDmHRDHHFHMbHH1HCbgpk6kR79M6kRs186kRylS6kR1lq64RhbeHxbKjyown5bjH7zRHVbankntbanMnDbjHTbYp56cRwn7bmHnbBnpHrJRHfbBnMng7Anw7jno7iR47mHk7jH07Sns7nnknC7nnMny7Snq7Rn67jHm7An27eHu74XpHB74XFHLLRHp7mH57Rnl76XwnN76XYn97Anj7qXFHL7Snb7SnH7RnX7FXwnv7An-7mHgHjHwHjXFHYH9X1HkHRn0HnXwncHnXYniHnXknKHAnaHjHGHKjAmBRuHLtwmU3zH+2YmU3Izhoyl0mU31lcmBRMzoZimW379KmW3s16mW3q3UbrVxoG3cb53-HYpBmRR+3qbO36bE3Zz13q3ObM3eb13dt5o2HpRinO3pbgP83We6n53mngp5oq3OnkPK1SJ3m5Rf3eRW1cFxg+3ZnE3FnkPhd531nuPJDxgG3Dnt3TnJPLnVRbnE3HnkPXnO3PnNPq3-nNPG3QXO3IXOpOWNR+3UXM3MXkPPjqP8X-PBPSX53KXE3aXHPGXUv+32XUvR3eXt3BXEvBPxXO3pXO35XHPlX2v+3NXt3dXE3DXkPTXJvBPrXRvP3HXHPXXNv+3vXNvR3A3Nvq3w3t3o3kP43o+a2sgQAA). They might be able to increase it if you open an issue there with a compelling use case.

**Comment by jbloom** [comment]
Great, opened issue at Vega Lite: https://github.com/vega/vega-lite/issues/8377
