### ISSUE TITLE
Mark_bar step increase of the bar width

### ISSUE THREAD

**Issue by stebaski** [altair-viz/altair#2668]
The width of the bars in mark_bar plot is not proportional to the given size:
data = pd.DataFrame({'name': ['a', 'b','c','d'], 'value': [8, 9,10,11]})

alt.Chart(data).mark_bar(size=50).encode(
    x=alt.X('name:N'),
    y='value:Q',
    size = alt.Size('value:N'),
).properties(width={"step": 30})
![altair_bug](https://user-images.githubusercontent.com/76164559/183305583-8a66d29e-0775-4c14-83c7-c7d6cdc3b874.png)
No matter what numbers are given as the size values the difference between bar widths will always be the same. I don't like how the smallest width is too tiny. Is there a way to fix this?

Thank you!

**Comment by mattijn** [comment]
I think you like to use the `range` parameter within the `scale` definition. Something as `size = alt.Size('value:N', scale=alt.Scale(range=[10,30])),`?

> For [continuous scales](https://vega.github.io/vega-lite/docs/scale.html#continuous), two-element array indicating minimum and maximum values, or an array with more than two entries for specifying a [piecewise scale](https://vega.github.io/vega-lite/docs/scale.html#piecewise).

<img width="209" alt="image" src="https://user-images.githubusercontent.com/5186265/183308684-a8ad22aa-77d9-4a0e-bd16-e5f33e09608d.png">

**Comment by stebaski** [comment]
I see, that works just perfectly. Thank you!
