### ISSUE TITLE
entrypoints is in maintenance mode

### ISSUE THREAD

**Issue by EdgyNortal** [altair-viz/altair#2675]
![image](https://user-images.githubusercontent.com/108864217/188197431-6f23baa1-9643-4a49-b1b5-937fddbc5d58.png)
Ran into an issue building a Docker image that involved altair, and a conflicting entrypoints version. The work around was to hard pin `entrypoints` in our code. But as that project is in maintenance mode, it might be nice to decouple altair from it.

**Comment by mattijn** [comment]
Closed [#2675](https://github.com/altair-viz/altair/issues/2675) as completed via [#2686](https://github.com/altair-viz/altair/pull/2686).
