### ISSUE TITLE
layer order with defined params

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2685]
I tried to recreate the following Vega-Lite chart with Vega-Altair:
[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQOJACckCCGgDaoWRrhoQATQD6AZQAyASQAiAUQBKikExqyAJmlDucDTEbqsmSGSsgAHmgALAAMMWHuaPEgEJhwOGgAjAC+SsRIggyGqADMcdkAukqCSACecKo6oB5ImCiooPmFcFqouiC2dVlKAGoFRWhiUZQAHLmgg7VoAEyj48WZmcuUOQoLQ6Vr3WgAbCWUJ-MDB1FHE6UA7BdXi5N3xQ8AnJQPLwcn7yyJSenz+S1QD0BqC2MR2YLQMyhmRi5xK8NQnyhJU+0zme2u4ORSM+3zE6M2UIe2zR+Ne0NWIDGx1QYkycNpB0yJSRW3Jt0Z6yyD2mZI5hLESLKlDJFVyIBq9UafVAyFUAGsjEw1C44LIoGwPO4yN4QJEOiAAGY0OCCLzoV5KTC1HDFEBsVSG-SCFxIcI0XqgGpMG0AQWCgmKMWycvBoCtNrtAuOjudroAjgwkLJMHRWjRSCBo1dVRr0FrGo6ghALe6EE1LTRBGklSAWpgGAhKEyigACAB8AF4e2YrHYnIX8VAClAGDU0kYRzYHM4lEheq41zb3IZKkpdfrPcbzWa49bbUYHSAnS6jO7PQUJyBYw2E5rN8JZKEr6mjBmszm2hzAtHToCMjAABQAWW2MQe27HclFqZYTXjc90Hgx99UEd0TS6e4QAAYjgKIxAeMQxELaNZXxNt2k6dZel0So5X3A0jRNZ82w7E04HCHAW0XMdnDla900zbNcyAnc5QVBp6xLQJZwQlU1FLUBRKMNJwgCVdhDIeR0FUGgyCwFwtQgLdP01NhsDYOslA8M1+AZDxwWcpQzRAAB3GgPHoFwtICdAYCQAAvNQPDYBgtCo5igA)

<img width="356" alt="image" src="https://user-images.githubusercontent.com/5186265/192746586-3f2b5916-37a6-4cb7-b7a7-86617191bc56.png">

Using the following code:

```python
!python -m pip install git+https://github.com/ChristopherDavisUCI/altair.git@liftparams
import altair as alt
import pandas as pd

data = [
    {"Day": 1, "Value": 54.8},
    {"Day": 2, "Value": 112.1},
    {"Day": 3, "Value": 63.6},
    {"Day": 4, "Value": 37.6},
    {"Day": 5, "Value": 79.7},
    {"Day": 6, "Value": 137.9},
    {"Day": 7, "Value": 120.1},
    {"Day": 8, "Value": 103.3},
    {"Day": 9, "Value": 394.8},
    {"Day": 10, "Value": 199.5},
    {"Day": 11, "Value": 72.3},
    {"Day": 12, "Value": 51.1},
    {"Day": 13, "Value": 112},
    {"Day": 14, "Value": 174.5},
    {"Day": 15, "Value": 130.5},
]

df = pd.DataFrame.from_records(data)

slider = alt.binding_range(min=0, max=400, step=1)
rule = alt.param(bind=slider, value=177, name='Y_SLIDER')

bar_blue_background = alt.Chart().mark_bar().encode(
    x=alt.X('Day:O',axis=alt.Axis(labelAngle=0)),
    y=alt.Y('Value:Q')
)

bar_red_foreground = (
    alt.Chart().mark_bar()
    .transform_filter(alt.datum.Value >= rule)
    .transform_calculate(baseline=rule.name)
    .encode(
        x=alt.X('Day:O',axis=alt.Axis(labelAngle=0)),
        y=alt.Y('baseline:Q', title="PM2.5 Value"),
        y2=alt.Y2('Value:Q'),
        color=alt.value("#e45755")
    )
    .add_params(rule)
)

rule_base = alt.Chart().encode(
    y=alt.datum(rule, type='quantitative')).add_params(rule)

rule_horizontal = rule_base.mark_rule()

rule_label = rule_base.mark_text(
      align='right',
      baseline='bottom',
      dx=-2,
      dy=-2,
      x='width',
      text='hazardous'
    )

layer_background = alt.layer(bar_blue_background, bar_red_foreground, data=df)
layer_foreground = alt.layer(rule_horizontal, rule_label)
alt.layer(layer_background, layer_foreground)
```
But no matter what I try, it seems I cannot control the order of the bars, the `bar_blue_background` will always appear in front of the `bar_red_foreground`:
<img width="353" alt="image" src="https://user-images.githubusercontent.com/5186265/192748669-03c57c38-c436-40b2-b46f-80c40fa4f8f7.png">

But if I remove the `params` definition from the chart. It will work as expected:
```python
bar_blue_background = alt.Chart().mark_bar().encode(
    x=alt.X('Day:O',axis=alt.Axis(labelAngle=0)),
    y=alt.Y('Value:Q')
)

bar_red_foreground = (
    alt.Chart().mark_bar()
    .transform_filter(alt.datum.Value >= 177)
    .transform_calculate(baseline='177')
    .encode(
        x=alt.X('Day:O',axis=alt.Axis(labelAngle=0)),
        y=alt.Y('baseline:Q', title="PM2.5 Value"),
        y2=alt.Y2('Value:Q'),
        color=alt.value("#e45755")
    )
)

rule_base = alt.Chart().encode(
    y=alt.datum('177', type='quantitative'))

rule_horizontal = rule_base.mark_rule()

rule_label = rule_base.mark_text(
      align='right',
      baseline='bottom',
      dx=-2,
      dy=-2,
      x='width',
      text='hazardous'
    )

layer_background = alt.layer(bar_blue_background, bar_red_foreground, data=df)
layer_foreground = alt.layer(rule_horizontal, rule_label)
alt.layer(layer_background, layer_foreground)
```
<img width="353" alt="image" src="https://user-images.githubusercontent.com/5186265/192748464-703a1249-a435-4e6c-972d-35fb63c1876b.png">

@ChristopherDavisUCI

**Comment by ChristopherDavisUCI** [comment]
Thanks @mattijn!  I see what my mistake was.  I had forgotten that the order of the subcharts needed to be preserved, and this part of the code scrambles it: https://github.com/altair-viz/altair/blob/93892c077be1c963d2c0fac3c0a6e563998e9031/altair/vegalite/v5/api.py#L2806-L2815

It will be easy to fix, I just need to think about where is the best spot for the fix in terms of readability.  (The whole point of the above lines was to avoid yet another if condition in the big for loop.)

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, I think I've fixed this.  Could you take a look and see if it's now working as expected?  Thanks for the catch!

**Comment by mattijn** [comment]
Yes, your update fixed it. Closing this.
