### ISSUE TITLE
Conditionally change axis label appearance (color, opacity)

### ISSUE THREAD

**Issue by Andrej-Marsic** [altair-viz/altair#2687]
I am not sure if this is a feature request or a bug report, but basically I'm having the same request as in this SO question:

https://stackoverflow.com/questions/68113954/python-altair-conditionally-change-axis-label-appearance-color-opacity

How come the conditional works when an expression is passed, but not when it's a selection condition?

**Comment by joelostblom** [comment]
Closing this as nothing can be done on the Altair side. After the vega-lite issue has been fixed this will automatically be included in a following altair release.
