### ISSUE TITLE
Hiding the legend for a channel

### ISSUE THREAD

**Issue by dhimmel** [altair-viz/altair#270]
In vega-lite JSON, under `encoding` I was able to do the following:

```json
"opacity": {
  "field": "positives",
  "type": "quantitative",
  "legend": false
}
```

The `"legend": false` line suppressed the rendering of the opacity legend.

In altair, I tried specifying the following argument for `.encode()`:

```Python
opacity = altair.Opacity('positives', legend=False)
```

This raised the error:

```
TraitError: The 'legend' trait of an Opacity instance must be a Legend or None, but a value of class 'bool' (i.e. False) was specified.
```

Any way to hide the legend for a channel in altair?

**Comment by dhimmel** [comment]
As you may notice from my previous issue (https://github.com/altair-viz/altair/issues/264), most of my plotting customizations consist of getting rid of things :smile_cat:

**Comment by jakevdp** [comment]
The ability to do ``legend=False`` was added in a recent version of Vega-Lite. As of Vega-Lite 1.2.1 the schema [does not support legend=False](https://github.com/vega/vega-lite/blob/v1.2.1/vega-lite-schema.json). Allowing that would require updating Altair to work with Vega-Lite version 1.3.

**Comment by dhimmel** [comment]
Ah yes, I see the [vega-lite v1.3.0 release notes](https://github.com/vega/vega-lite/releases/tag/v1.3.0) mention:

> Make setting `axis` or `legend = null` as the default way to disable them.

For now, I'll try finishing my visualization by editing vega-lite JSON, which in the long term should help me with contributing to altair!

**Comment by kanitw** [comment]
@dhimmel Looks like we forgot to update vega-editor to 1.3.  (It's still 1.2 there.)  

@domoritz will update that together with the new 1.x update soon.

Also note that the next version of vega editor will explicitly list version in the UI.

**Comment by ellisonbg** [comment]
@kanitw is this be fixed in vega-lite latest 1.x?

**Comment by domoritz** [comment]
Looks like in 1.3.1 the only options are an object or null (https://github.com/vega/schema/blob/master/vega-lite/v1.3.1.json#L988). You can pass false but we don't want to add it to the schema.

**Comment by dhimmel** [comment]
> Looks like in 1.3.1 the only options are an object or null

@domoritz does `null` remove the legend entirely?

**Comment by domoritz** [comment]
It should! If not, that's a bug.

**Comment by jakevdp** [comment]
Altair doesn't yet support explicit nulls, so now that they have meaning in Vega-Lite we need to add that.
