### ISSUE TITLE
Wrong height when using hconcat

### ISSUE THREAD

**Issue by raffo85h** [altair-viz/altair#2700]
Using altair version 4.2.0.

In a jupyter notebook, when hconcat 2 plots that are row-faceted the sizes are different. Here these 2 columns were built using the same height and width properties.

Notice that each time the cell is run, a different height is shown.

![image](https://user-images.githubusercontent.com/8588341/197168106-ea99e143-1a5d-4d17-a21b-cbcb865d9879.png)

**I've also downloaded the jupyter notebook as HTML** file to look at the altair/vega code. And in the vega-json I do see the width and height as expected.

Code to reproduce.

```python
import pandas as pd
import numpy as np
import altair as alt

def change_firing_rate(r):
    # The whole point is to have facets with x-scale shared by column but not by row
    # This hack is to make the dataset suitable for the goal
    if r['align'] == 'dots':
        return r.firing_rate
    return r.firing_rate + np.random.normal(150, 10)

dots_df = (
    pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/dots.csv')
    .assign(time=lambda x: x.time.clip(-80, 50))
    .assign(new_firing_rate=lambda x: x.apply(change_firing_rate, axis=1))
)

def strip_plot_row(df, y=True):
    row_header = alt.Header(title='', labelAngle=0, labelAlign='left', labelPadding=0, labelFontSize=14 if y else 0)
    return (
        alt.Chart(df)#, height=45, width=45*8)
        .mark_circle(size=30)
        .encode(
            y=alt.Y('jitter:Q', title=None, axis=alt.Axis(values=[0], ticks=True, grid=False, labels=False)),
            x=alt.X('new_firing_rate:Q', title='Firing Rate'),
            row=alt.Row('time:N', header=row_header),
            column=alt.Column('align:N', header=alt.Header(title='', labelAngle=0, labelAlign='left', labelPadding=0, labelFontSize=14))
        )
        .transform_calculate(jitter='sqrt(-2*log(random()))*cos(2*PI*random())')
    )


(
    alt.hconcat(
        strip_plot_row(dots_df.query('align=="dots"')).properties(height=45, width=45*8), 
        strip_plot_row(dots_df.query('align=="sacc"'), y=False).properties(height=45, width=45*8), 
    )
    .configure_facet(spacing=5)
    .configure_view(stroke=None)
)
```

---

Please follow these steps to make it more efficient to solve your issue:

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [x] Search for duplicate issues.
- [x] Use the latest version of Altair.
- [x] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by joelostblom** [comment]
I see the same issue you describe in the Vega Editor (if you refresh the page the height changes), so I would suggest creating a simpler example and raising it as an issue in their repo. Let me know if you still think there is something altair specific that needs to be done here and we can re-open this issue.
