### ISSUE TITLE
Add tests for all new VegaLite functionality since 4.17

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2703]
This is a reminder to make sure we add tests/gallery examples of the new features introduced since Vega-Lite 4.17.

**Comment by ChristopherDavisUCI** [comment]
I got started on the parameter side of this in #2828.

Also #2811 checked that certain layer properties got moved to the top level.  (This isn't a big feature, but it caused many tests to break during the initial transition to Vega-Lite 5.)

**Comment by ChristopherDavisUCI** [comment]
I went through the the release notes up to Vega-Lite v5.2.0 and I didn't notice anything else major that needed a corresponding test.  (Reminder to myself: A few offset charts have already been added to the example gallery, like `Strip Plot with Jitter` and `Grouped Bar Chart with xOffset`.  I tried to link the corresponding files, but I can't find the gallery on GitHub?  I'm sure I'm missing something obvious.)

If you see anything else where a test should be added, please let me know and I can work on it!

**Comment by joelostblom** [comment]
Great, thank you! I will close this as it was implemented in #2828 then.

Regarding the gallery, I believe all the examples were moved in the to new test directory here https://github.com/altair-viz/altair/tree/master/tests
