### ISSUE TITLE
altair 4.2 `AttributeError: 'list' object has no attribute 'get'` on `chart.projection` with center

### ISSUE THREAD

**Issue by Casyfill** [altair-viz/altair#2707]
with 4.2  Altair fails once I try to pass projection with center as a list:

```python
>>> import altair as alt
>>> basic_chart = alt.Chart().properties(height=800, width=700)
>>> NYC_PRJ = {"type": "mercator", "center": [-73.99, 40.72]}
>>> basic_chart.project(**NYC_PRJ)
```
Raises this:

```
... /site-packages/jsonschema/validators.py", line 101, in _id_of
  return schema.get("$id", "")
AttributeError: 'list' object has no attribute 'get'
```
---

**Comment by jakevdp** [comment]
Hi, thanks for the report - this looks quite similar to https://github.com/altair-viz/altair/issues/2496

Which version of the `jsonschema` package do you have installed?

**Comment by Casyfill** [comment]
`4.17.0`, I assume I have to set it to <4

**Comment by Casyfill** [comment]
PS. confirming that jsonschema<4 fixes the issue

**Comment by joelostblom** [comment]
In addition to #2496, there is another issue with jsonschema 4.17 that is being tracked in #2705 so closing this issue for now but please comment if you think there is something that is not covered by those two issues.

**Comment by Casyfill** [comment]
Sure,  thanks! is fixing altair to `dfschema<4` as a temp patch an option?

**Comment by joelostblom** [comment]
Yeah we might do that (at least temporarily for CI) , but it wouldn't go into effect until the next release anyways so we should also try to figure out what goes wrong and make Altair compatible with newer json schema versions. Doing it locally with 4.2 would be totally ok.
