### ISSUE TITLE
Empty `project()` changes to old default geo-projection

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2708]
```
import altair as alt
from vega_datasets import data
source = alt.topo_feature(data.world_110m.url, 'countries')
```

The following works as expected to show the default projection `equalearth`

```
alt.Chart(source).mark_geoshape()
```

![image](https://user-images.githubusercontent.com/4560057/200100602-0343cc63-6b48-4ff3-ab9c-bf0e282bc920.png)

However, adding an empty `project()` changes to the old default mercator by explicitly adding it to the spec, which seems wrong:

```
alt.Chart(source).mark_geoshape().project()
```

![image](https://user-images.githubusercontent.com/4560057/200100632-34a9d5ff-f1ce-409c-829d-bea7c8c44133.png)

Something similar was reported for layers in https://github.com/vega/vega-lite/issues/7331, not sure if it is related

**Comment by mattijn** [comment]
Its hardcoded in the altair code base, here:
https://github.com/altair-viz/altair/blob/066be255f5e5242592cb7ea486e8c5907da67421/altair/vegalite/v5/api.py#L763-L768
Should probably be `Undefined` as the others.
