### ISSUE TITLE
Heatmaps are non interactive

### ISSUE THREAD

**Issue by josephernest** [altair-viz/altair#2712]
Is it normal that [Altair heatmaps](https://altair-viz.github.io/gallery/simple_heatmap.html) are non interactive, even when specifying `.interactive()`:

```
import altair as alt, numpy as np, pandas as pd
x, y = np.meshgrid(range(-5, 5), range(-5, 5))
z = x ** 2 + y ** 2
source = pd.DataFrame({'x': x.ravel(), 'y': y.ravel(), 'z': z.ravel()})
alt.Chart(source).mark_rect().encode(x='x:O', y='y:O', color='z:Q').interactive().save('test2.html')
```

?

Is there a way to enable interactivity : moving, zooming, etc. in the browser?

**Comment by joelostblom** [comment]
Interactivity does not work with ordinal scales unfortunately (tracked in https://github.com/vega/vega-lite/issues/4369). If you change them to quantitative it will work, but it might not have the appearance you want

**Comment by josephernest** [comment]
Thanks @joelostblom. Would you have an example code, based on my sample code in my post, showing it in quantitative mode?

**Comment by joelostblom** [comment]
Yes, you change the encoding to `x='x:Q', y='y:Q'`

**Comment by josephernest** [comment]
Thanks @joelostblom.

Before this change:

![image](https://user-images.githubusercontent.com/6168083/200676703-84cbac65-c1e7-4ee0-ac91-41e4e85ae4ea.png)

After `x='x:Q', y='y:Q'`, it becomes movable/zoomable indeed, but the appearance is not good indeed, as you suggested:

![image](https://user-images.githubusercontent.com/6168083/200676742-0c611bd6-4438-48f8-93ba-b43b259af1b1.png)

Is there a way to have both interactive + normal rendering?

**Comment by jakevdp** [comment]
I think you're looking for binned quantitative encodings:
```python
alt.Chart(source).mark_rect().encode(
  x=alt.X('x:Q', bin=True),
  y=alt.Y('y:Q', bin=True),
  color='z:Q'
).interactive()
```

**Comment by josephernest** [comment]
Perfect indeed @jakevdp!
Would you have a link to the right documentation page? So I'll learn how to do this and similar modifications. Thanks again :)

PS: would you know if it's possible to do a "rectangle selection" on such a heatmap, to do a Region Of Interest (ROI) selection?

**Comment by betaigeuze** [comment]
> PS: would you know if it's possible to do a "rectangle selection" on such a heatmap, to do a Region Of Interest (ROI) selection?

You can add a rectangular selection with 
```python
sel = alt.selection_interval()
```
So to extend @jakevdp 's example:

```python
sel = alt.selection_interval()

alt.Chart(source).mark_rect().encode(
  x=alt.X('x:Q', bin=True),
  y=alt.Y('y:Q', bin=True),
  color='z:Q'
).add_selection(sel)
```
However, if you do it like this, you're dropping the `.interactive()`. Afaik, you can only assign one function to a mouse click:
Either create a selection window or move the plot.

> Would you have a link to the right documentation page?

You can read more about this kind of selections [here](https://altair-viz.github.io/user_guide/interactions.html#interval-selections)
