### ISSUE TITLE
Not possible to view faceted charts with `altair.selection` after #2702

### ISSUE THREAD

**Issue by wence-** [altair-viz/altair#2713]
Since the merge of #2702, faceted charts with a selection (which used to work, I may have been doing something wrong), now result in an error:

```
JavaScript Error: Duplicate signal name: "selected_tuple"

This usually means there's a typo in your chart specification. See the javascript console for the full traceback.
```

Code to reproduce:

```python
import pandas as pd
import altair as alt

df = pd.DataFrame(
    {"a": [1, 2, 3, 4], "b": [1, 2, 1, 2], "c": [1, 1, 2, 2], "d": [1, 2, 3, 4]}
)

selector = alt.selection(type="point", fields=["d"], bind="legend", name="selected")
chart = (
    alt.Chart(df)
    .add_params(selector)
    .mark_line(point=True)
    .encode(
        x=alt.X("a:Q"),
        y=alt.Y("b:Q"),
        color="d:N",
        opacity=alt.condition(selector, alt.value(1), alt.value(0.25)),
    )
    .facet(facet=alt.Text("c:N"))
)
chart.save("foo.html") # open foo.html
```

**Comment by mattijn** [comment]
Thanks for raising. This seems to be an issue in VL. Let me try to decipher:

In vega-lite this works: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUscAjADQgBG8pIAxlWWFQL4kHwBMZlcnt94HFmzgBmLvzo8G8EUJCEALOKl8VjOAqYBdFiABmEGhijxQegJYYU6vmSgBPAA4Z4IAHYB7ALbm3qELpYzpKgjhAAThBeOHD47lEucCBYVhg0UBiMZCkoaSYIIA7Oro4eviZkFlZgMbgCOly+NrkA5hhujNpkXhEA1qaFTokgKL4uZKXl8FDhmLrtNB5gvi0Diyge4QNV1q5Zg8VJnj5+KAFkAB7blrtJsHZDrgCOaBBuUOYwH4guuvbX1VclAehxALzeHy+5h+5xAHjCNE+-wKiw6n3MHjcA2Q6ES1DCkS8rhyeUysJxmHgAAYAHTsACsTCZZAAJFgaAALDA9VwcqBQRxYOAAemFPxaEBpLU+HLQ5BpGOF7K5PTFGAlAFpRhkxfS6TTaQArLCYgJAA):
Here I define `params` nested within `spec`
```json
{
  "data": {
    "values": [
      {"a": 1, "b": 1, "c": 1, "d": 1},
      {"a": 2, "b": 2, "c": 1, "d": 2},
      {"a": 3, "b": 1, "c": 2, "d": 3},
      {"a": 4, "b": 2, "c": 2, "d": 4}
    ]
  },
  "facet": {"field": "c", "type": "nominal"},
  "spec": {
    "params": [
      {
        "name": "selected",
        "select": {"type": "point", "fields": ["d"]},
        "bind": "legend"
      }
    ],    
    "mark": {"type": "line", "point": true},
    "encoding": {
      "color": {"field": "d", "type": "nominal"},
      "x": {"field": "a", "type": "quantitative"},
      "y": {"field": "b", "type": "quantitative"},
      "opacity": {"condition": {"value": 1, "param": "selected"}, "value": 0.25}
    }

  },
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json"
}
```

But when defining `params` top-level and referring by `views` to the spec by `name` does not work: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJghgLhIFygG4QDYFcCmBneBtUscAjADQgBG8pIAxlWWFQL4kHwBMZlcnt94HFmzgBmLvzo8G8EUJCEALOKl8VjOAqYBdFiABmEGhijxQegJYYU6vmSgBPAA4Z4IAHYB7ALbm3qELqOEABOEF44cPjuYS5wIFhWGDRQGIxkCShJJgggDs6ujh6+JmQWVmARuAI6XL42mQDmGG5pIIiWAO6VbZ0A+kQgOlrpzpKgfl6xPRgd-SBkXiEA1qa5TlMovi5khcXwUMGYus00HmC+DaunKB7Bq2XWrq15U54+figBZAAe95aPcVgdnWrgAjmgIG4oOYYNDEC5dPY-uVXJRgfk4uDIdDYeZ4V8QB4gjQYUicqcWjDzB43KtkOhYtQgqEvK4MllUgT6Zh4AAGAB07AArExRWQACRYGgACwwi1c0qgUEcWDgAHo1fCGhB+Q0YdK0OR+dS1VLZYtNRhtQBaTYpTVCwX8gUAKywNICQA):
```json
{
  "data": {
    "values": [
      {"a": 1, "b": 1, "c": 1, "d": 1},
      {"a": 2, "b": 2, "c": 1, "d": 2},
      {"a": 3, "b": 1, "c": 2, "d": 3},
      {"a": 4, "b": 2, "c": 2, "d": 4}
    ]
  },
  "facet": {"field": "c", "type": "nominal"},
  "params": [
    {
      "name": "selected",
      "select": {"type": "point", "fields": ["d"]},
      "bind": "legend",
      "views": ["view_1"]
    }
  ],
  "spec": {
    "name": "view_1",
    "mark": {"type": "line", "point": true},
    "encoding": {
      "color": {"field": "d", "type": "nominal"},
      "x": {"field": "a", "type": "quantitative"},
      "y": {"field": "b", "type": "quantitative"},
      "opacity": {"condition": {"value": 1, "param": "selected"}, "value": 0.25}
    }
  },
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json"
}
```
Resulting in the error as OP:

> ```cmd
> Duplicate signal name: "selected_tuple"
> ```

And it is the latter approach that Altair is currenlty adopting.. You see any strange things here @ChristopherDavisUCI?

A temporal workaround for you @wence- might be to move the `facet` within the `encoding`, as such:
```python
selector = alt.selection(type="point", fields=["d"], bind="legend", name="selected")
chart = (
    alt.Chart(df)    
    .mark_line(point=True)
    .encode(
        x=alt.X("a:Q"),
        y=alt.Y("b:Q"),
        color="d:N",
        opacity=alt.condition(selector, alt.value(1), alt.value(0.25)),
        facet="c:N"
    )    
)
chart.add_params(selector)
```
not sure if that works for your situation.

**Comment by wence-** [comment]
Thanks, that works for this simple case, but not for my actual use case which is faceting a layered chart (`chart = band + line`) because faceting doesn't commute with layer composition.

**Comment by mattijn** [comment]
Yes, then the suggestion will not work.
The example that we have tested with `params` in combination with faceting a layered chart does work though:
```python
import altair as alt
from vega_datasets import data

cars = data.cars.url

highlight = alt.selection_point(fields=["Origin"], bind='legend', value='Europe')

base = alt.Chart(cars, width=160, height=130).encode(
    x='Miles_per_Gallon:Q',
    y='Horsepower:Q'
)

text = base.mark_text().encode(
    text='Origin:N',
    color=alt.condition(highlight, alt.value("black"), alt.value("transparent"))        
)

dots = base.mark_circle().encode(
    color=alt.condition(highlight, 'Origin:N', alt.value('lightgray')),
    size=alt.condition(highlight, alt.value(250), alt.value(20))
)

(dots + text).facet('Origin:N').add_params(highlight)
```
![image](https://user-images.githubusercontent.com/5186265/201965046-1bf5a68b-fae5-49ab-923c-714fa6fcd082.png)

**Comment by mattijn** [comment]
Oh wait, this is because you have defined `point=True` in `.mark_line(point=True)`. This was discussed in this comment: https://github.com/altair-viz/altair/pull/2684#issuecomment-1278153027.

Apparently when separating this in a `line` + `circle` mark it works:
```python
import pandas as pd
import altair as alt

df = pd.DataFrame(
    {"a": [1, 2, 3, 4], "b": [1, 2, 1, 2], "c": [1, 1, 2, 2], "d": [1, 2, 3, 4]}
)

selector = alt.selection(type="point", fields=["d"], bind="legend", name="selected")
base = alt.Chart(df).encode(
    x=alt.X("a:Q"),
    y=alt.Y("b:Q"),
    color="d:N",
    opacity=alt.condition(selector, alt.value(1), alt.value(0.25)),
)
chart = (
    (base.mark_line() + base.mark_circle())
    .facet(facet=alt.Text("c:N"))
    .add_params(selector)
)
```

**Comment by mattijn** [comment]
Was raised previously at VL here: https://github.com/vega/vega-lite/issues/7854

**Comment by mattijn** [comment]
With the second release candidate of version 5 (`5.0.0rc2`) this issue is resolved.
