### ISSUE TITLE
jsonschema validation error in Graticule Generator example

### ISSUE THREAD

**Issue by mknz** [altair-viz/altair#2715]
Hi, thanks for the awesome project!

I tried to run the example code below, but got `AttributeError: 'list' object has no attribute 'get'` error in jsonschema.

https://altair-viz.github.io/user_guide/data.html

I'm using the latest version of Altair (4.2.0) and jsonschema (4.17.0)

**Example code to reproduce the error**
```
import altair as alt

data = alt.graticule(step=[15, 15])

alt.Chart(data).mark_geoshape(stroke='black').project(
    'orthographic',
    rotate=[0, -45, 0]
)
```
---

Please follow these steps to make it more efficient to solve your issue:

- [x] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [x] Search for duplicate issues.
- [x] Use the latest version of Altair.
- [x] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by joelostblom** [comment]
Hi there, this is the same issue as reported in https://github.com/altair-viz/altair/issues/2504#issuecomment-1265621976 so I will be closing this one. To fix the issue you can either downgrade your jsonschema (as mentioned in the other thread) or install the latest development version of altair from github where the issue has been fixed.
