### ISSUE TITLE
jupyter notebook too slow

### ISSUE THREAD

**Issue by quartermaine** [altair-viz/altair#272]
My jupyter notebook is extremely slow even when I execute an one line piece of code

**Comment by jakevdp** [comment]
What line of code are you executing? Are you certain it's related to Altair?

**Comment by quartermaine** [comment]
I try to apply just a simple function I wrote to an SFrame column and it's taking forever.

**Comment by jakevdp** [comment]
You should probably raise this issue in the jupyter repository.

**Comment by quartermaine** [comment]
ok
