### ISSUE TITLE
heatmap has different behavior in html output vs. png/svg

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#273]
I am using https://altair-viz.github.io/gallery/text_table_heatmap.html#gallery-text-table-heatmap as the template for what I'm doing (note: there is no picture on this webpage, oddly).

My code looks like this:

```
    chart = Chart(dfd).mark_text(applyColorToBackground=True).encode(
        row='do_a:O',
        column='do_b:O',
        color='m_teps',
        text='m_teps',
    )
```

I output to png and svg using `chart.to_dict()` then `vl2vg` then `vg2png`/`vg2svg`. Those color the text but not the background. png attached.

I output to HTML using `chart.to_html`. It looks more what I expect, colored background. Here's a screenshot: https://www.evernote.com/l/AAEiwdg8BfRLeIAOWUaIXepydTqjnPv5w9E

![do_ab_hollywood-2009](https://cloud.githubusercontent.com/assets/976970/20733539/c8c61ee8-b648-11e6-87f5-10388a0f256f.png)

**Comment by jakevdp** [comment]
I suspect that your version of the node-js command line tools is not up-to-date. Can you check the versions you have installed?

**Comment by jowens** [comment]
Top of tree, `On branch v2.x`. Go to origin/master?

**Comment by jakevdp** [comment]
Altair currently output Vega-Lite 1.2 specifications, which won't generally be compatible with Vega-Lite 2.X. If you want PNGs that look the same as what Altair uses in the browser, you'll need version 1.3 of the node-js tools.

Note that 2.X is under active development and changing rapidly, so I wouldn't use it for anything but development at the moment.

**Comment by jowens** [comment]
vega-lite: `git checkout origin/1.x` worked great. Thanks @jakevdp.
