### ISSUE TITLE
Tests involving render

### ISSUE THREAD

**Issue by ChristopherDavisUCI** [altair-viz/altair#2733]
Has anything changed recently involving the render tests?  I have installed `vl-convert-python` 0.5.0.  The tests worked for me about a month ago last time I tried, but tonight all of the render tests were failing.  I'm not sure if it's an issue on my computer's end, or if there is some change to the workflow related to vl-convert.

Here is a typical error message I'm getting:
```
py::test_render_examples_to_png[bar_chart_with_highlighted_segment.py-altair_saver] Failed: [undefined]subprocess.CalledProcessError: Command '['/Users/christopherdavis/miniconda3/envs/alt/bin/npm', 'bin', '--global']' returned non-zero exit status 1.
engine = 'altair_saver', filename = 'bar_chart_with_highlighted_segment.py'
```

My Mac OS did update I think within the last month, so it could also be something like that.

Thanks for any tips!

**Comment by joelostblom** [comment]
I don't see these errors when I run `make test` on my end

**Comment by ChristopherDavisUCI** [comment]
Thanks for checking, @joelostblom !  Can I ask what version of npm you're using?  `npm -v` for me is `9.1.1`.

**Comment by binste** [comment]
I also don't see these errors running the tests in a linux docker container. npm is version `8.19.2` and node `18.12.1` in case this helps.

**Comment by ChristopherDavisUCI** [comment]
Thank you @binste!  It seems to be working now.  I wish I could say what fixed it, but I'm not sure.  Starting with those same npm and node versions was very helpful.
