### ISSUE TITLE
Some tables in documentation are cut off

### ISSUE THREAD

**Issue by binste** [altair-viz/altair#2736]
Some tables in the new documentation design are too wide to be displayed. For example https://binste.github.io/altair-docs/user_guide/encoding.html#color-fill-and-stroke

![image](https://user-images.githubusercontent.com/23366411/205069201-f1dee255-70d8-4a19-af4d-18a7a2ff2544.png)

This happens because some types in the second column are too big and so they push the table beyond 100% width:

![image](https://user-images.githubusercontent.com/23366411/205069358-e79ab463-6193-426d-92fb-34482e4be008.png)

I'm not very familiar with the layout and how these tables are generated so I don't know how to fix this. Some ideas:

* Is it possible to shorten the names of these types? The long ones are not very useful anyway in my opinion. I'm aware that the tables are autogenerated so it would probably require some adjustment in that Sphinx directive. 
* Make the table scrollable horizontally. This is still not very convenient as the scrollbar will be at the bottom and some of the tables are very long.
* Shorten section titles in left navigation bar ("Interactive Charts: Parameters, Conditions, Bindings" -> "Interactive Charts", I prefer this anyway) and then make it narrower. This won't solve it completely but helps.
* If the layout is responsive, we could make the tables wider on bigger screens. On a 13'' laptop screen the documentation has a good size but on a 27'' 2560x1440 monitor it does look rather narrow:

![image](https://user-images.githubusercontent.com/23366411/205070651-a33d4993-4de1-4a08-9106-a71b9c1bd995.png)

---

Please follow these steps to make it more efficient to solve your issue:

- [x] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [x] Search for duplicate issues.
- [x] Use the latest version of Altair.

**Comment by joelostblom** [comment]
This caused an issue in the old documentation as well where it was difficult (but still possible) to read the rightmost column as it became very narrow:

![image](https://user-images.githubusercontent.com/4560057/205127401-657abc40-6188-4dbb-a998-f2e438a5a4eb.png)

I don't know if we can make the names shorter, but what do think of making the left column scrollable horizontally and limiting the max width?

I noticed that we can set `max-width` on the `td` element of the table to make it more narrow, but I wasn't able to add a scrollbar. There are some suggestions here that we could spend some more time on https://stackoverflow.com/questions/19794211/horizontal-scroll-on-overflow-of-table
