### ISSUE TITLE
3 related questions: formatting heatmap axis/internal numbers in scientific notation or other notation?

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#274]
How might one format the (a) axis numbers in, say, scientific notation, (b) the numbers in the heatmap cells, and (c) the width of the cells in the heatmap? The picture attached shows that none of these are optimal (I'd love to get, say, scientific notation with 2 digits after the decimal on the axes; if that can be done in Pandas in some way I can probably do that; the internal cells ought to be integers, I think; and they're too wide.)

vega-lite had a hacky solution for (c) at some point that may have been resolved, `"config": { "textCellWidth": 28 }`. 

Examples of these in the gallery would be great.

![do_ab_indochina-2004](https://cloud.githubusercontent.com/assets/976970/20734202/c0445fce-b64c-11e6-93e5-c16a3a59f8fa.png)

**Comment by jakevdp** [comment]
Regarding Axis formats; it's in the docs on master, but not yet pushed to the website; see https://github.com/altair-viz/altair/commit/1f6d1aaaba74b807430b8452592a3635336644cf

**Comment by jowens** [comment]
Oh, cool, thanks. How about the numbers in the heatmap cells?

**Comment by jakevdp** [comment]
The ``format`` argument to ``Chart.mark_text()`` should let you adjust the format of the text.

**Comment by jowens** [comment]
@jakevdp Forgive any misconfiguration on my part, but I note that `Chart.mark_text()`'s `format` argument does what I want but axis label formatting does not, e.g.:

```
    chart = Chart(dfd).mark_text(format='d',
                                 applyColorToBackground=True).encode(
        row=Row('do_a:O',
                axis=Axis(format='.1',
                          title='do_a',
                          ),
                ),
        column=Column('do_b:O',
                      axis=Axis(format='.1',
                                title='do_b',
                                ),
                      ),
        color='m_teps',
        text='m_teps',
    )
```

This is altair (1.2.0).
![do_ab_soc-orkut](https://cloud.githubusercontent.com/assets/976970/20740182/f22b6c2a-b675-11e6-868f-bdb8a4f93da5.png)

**Comment by jowens** [comment]
Also any nifty trick for setting the width of cells? Esp. when I'm able to make the axis terser, I'd like to be able to shrink the cells to their numerical width (automatically if possible, manually if necessary). It's a wide heatmap.

**Comment by jakevdp** [comment]
Regarding heat maps — this example will probably be helpful: https://github.com/jakevdp/altair-examples/blob/master/notebooks/Measles.ipynb

**Comment by jowens** [comment]
```
.configure_scale(
    textBandWidth=10,
    bandSize=10
)
```

is totally what I wanted. Thanks, @jakevdp. You're the best.

**Comment by kanitw** [comment]
Note that in VL 2.0, we will introduce `rect` mark, which will allow you to create a heatmap without text in a more sensible way. (No need to use the `text` mark and set the `text` channel to empty text!) :)

**Comment by jowens** [comment]
@jakevdp any thoughts on https://github.com/altair-viz/altair/issues/274#issuecomment-263782903 ?

**Comment by jowens** [comment]
Filed the axis/format issue as a separate issue.
https://github.com/altair-viz/altair/issues/276

**Comment by jakevdp** [comment]
You don't need those any more – heatmaps should be based on the rect mark, similar to this: https://altair-viz.github.io/gallery/simple_heatmap.html

**Comment by LukeMathWalker** [comment]
Sorry, I phrased my issue poorly.
I am already using rect for my heatmap, and it works wonderfully. I run into a problem when I try to add a text label on top of each square: they become long rectangles and I haven't been able to "resize" them to be just big enough to contain the text that I am displaying.

I have search the docs and I haven't find anything that could point me in the right direction - I thought those properties (`textBandWitdth` and `bandSize`) were relevant for this issue I am having. @jakevdp
