### ISSUE TITLE
venn diagram

### ISSUE THREAD

**Issue by wangjiawen2013** [altair-viz/altair#2749]
Hi,
Does Altair support venndiagram now ? The following are some examples. The left one is traditional venndiagram, the middle one is plot using upsetR and the third one is super venn diagram.
![image](https://user-images.githubusercontent.com/29703450/206864328-0865a28d-c38b-47fb-8915-1f7501efa453.png)

**Comment by binste** [comment]
I don't think this is currently possible. Altair is a wrapper around the vega-lite library which again in turn produces charts leveraging vega. To my knowledge this is not even straightforward in Vega itself where such a feature would first need to be implemented followed by vega-lite before we can integrate it in Altair. There is already [an open issue](https://github.com/vega/vega/issues/175) in the Vega repo which you can upvote.

**Comment by PBI-David** [comment]
VL uses GoG so you can make your own Venn diagram. e.g. 

I'm sure Altair can do this too. 

![image](https://user-images.githubusercontent.com/86846675/209294196-91634e74-9b23-4a47-b15f-5fbe82666838.png)

```

{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.json",
  "data": {
    "values": [
      {"category": 1, "x": -10, "y": 0},
      {"category": 2, "x": 10, "y": 0},
      {"category": 3, "x": 0, "y": 4}
    ]
  },
  "view": {"stroke":"transparent"},
  "mark": "circle",
  "encoding": {
    "x": {"field": "x", "type": "quantitative"
    ,"axis":null},
    "y": {"field": "y", "type": "quantitative", "axis":null},
    "color": {"field": "category", "type": "nominal",
    "legend": {"orient": "none", "legendX":300, "legendY":-100}},
    "size":{"value":100000}
    
  }
}

```

**Comment by binste** [comment]
Good point! I guess the Vega issue I linked is indeed more about plotting the visual style of a Venn diagram which is also possible in Altair, thanks @PBI-David for the example!

I was more thinking about a way to automatically calculate the necessary data points based on the underlying data as calculating the positions and areas of the circles is not straightforward. So something similar to [`mark_boxplot`](https://altair-viz.github.io/gallery/boxplot.html) (`"boxplot"` mark in vega-lite). See [matplotlib-venn](https://www.python-graph-gallery.com/venn-diagram/) which produces area-weighted diagrams for Matplotlib.

**Comment by joelostblom** [comment]
I think this is something that would need to be introduced in Vega-Lite before it can make it into Altair as a composite/macro mark like mark_boxplot, so closing this for now with the suggested workaround as a way of at least introducing the visual style for now.
