### ISSUE TITLE
color and shape legends when using same data should generate only one legend

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#275]
Hopefully not a duplicate, but it would be nice if a scatter chart with the same data used for color and shape would generate only one legend rather than two (with that legend varying both color and shape):

https://www.evernote.com/l/AAHAm2DVY1JMQaIQz_6BISgeGKNLmgNZ7IQ

https://github.com/altair-viz/altair/blob/273a1fcf9cec1956474af755d5fe32f0e3f0aee8/altair/notebooks/03-ScatterCharts.ipynb ("Scatter chart with color and/or shape")

**Comment by kanitw** [comment]
There is an issue in VL :) https://github.com/vega/vega-lite/issues/821

**Comment by jakevdp** [comment]
Great suggestion. This would have to be implemented in the Vega-Lite layer. @kanitw, do you think this is a possibility?

**Comment by ellisonbg** [comment]
Marking as vega-lite-related. @kanitw
