### ISSUE TITLE
adding Pie Chart "axis title" ?

### ISSUE THREAD

**Issue by fbpyr** [altair-viz/altair#2753]
In order to be able to describe a pie chart in same fashion as other regular charts next to it (e.g. bar charts), 
it would be great if it was possible to add a label at the chart "x-axis" 
(shown as `"x-axis" title?` in screenshot below) to a pie chart:  🙂 

![grafik](https://user-images.githubusercontent.com/73931454/207830551-a5585390-890f-4052-8907-7df1f7ca8ffa.png)

At first I thought it would be possible via title from theta, but that did not seem to have an effect?:

```python
topic_chart = alt.Chart(df).mark_arc(radius=150, innerRadius=50).encode(
    theta=alt.Theta("value:Q", title='"x-axis" title?'),
    color="category:N",
).properties(
    title="chart title above",
)
```

**Comment by joelostblom** [comment]
You could set the `orient` parameter of the chart title to place it at the bottom:

```py
source = pd.DataFrame({"category": [1, 2, 3, 4, 5, 6], "value": [4, 6, 10, 3, 7, 8]})

alt.Chart(source, title=alt.TitleParams(text='Title below', orient='bottom')).mark_arc().encode(
    theta="value", 
    color="category:N",
)
```

![image](https://user-images.githubusercontent.com/4560057/207914358-964772c6-b1f0-420b-b480-9cd17f56f227.png)

**Comment by fbpyr** [comment]
Thank you for the suggestion @joelostblom . I had not thought of that. 🙂 
That works already well for the graphs that only need one title above or below. 
Just not for the pie charts where a regular title above and description below 
x-axis would be needed.

**Comment by binste** [comment]
As such a pie chart has no real "x-axis" I'm not sure what a good use case would be? In case you just need to add additional description, you can provide a subtitle which can span multiple lines (for single line just pass a string instead of a list of strings):
```python
import altair as alt
import pandas as pd

source = pd.DataFrame({"category": [1, 2, 3, 4, 5, 6], "value": [4, 6, 10, 3, 7, 8]})

alt.Chart(
    source,
    title=alt.TitleParams(
        text="Title", subtitle=["Some more text", "on multiple lines"]
    ),
).mark_arc().encode(
    theta="value",
    color="category:N",
)
```
<img width="464" alt="image" src="https://user-images.githubusercontent.com/23366411/209195943-a7db1e61-d08d-4b15-809e-67341af43089.png">

You can also [add labels to the pie segments](https://altair-viz.github.io/gallery/pie_chart_with_labels.html).

**Comment by fbpyr** [comment]
thank you for suggestion and snippet @binste,
an additional subtitle/description is exactly my use-case. 
subtitle works very well for me. 🙂
