### ISSUE TITLE
proper `format` usage in Axis? (includes repro case)

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#276]
Trying to get `format` working with axis. I am using `format='.1'`, which I hope is equivalent to "either decimal or exponent notation, rounded to significant digits" (https://github.com/d3/d3-format/blob/master/README.md#format). It is trying to format the number `9.999999974752427e-07`, which I would hope would give me 1.0e-6 or something like that. Instead it's printing the entire number. 

`format` doesn't appear to do anything (no matter what I set it to). However, `format` works fine in the `mark_text` call.

```
d = {'do_a': [9.999999974752427e-07,
              ],
     'do_b': [9.999999974752427e-07,
              ],
     'm_teps': [859.5197143554688,
                ],
     }

df = pandas.DataFrame(d)

chart = Chart(df).mark_text(format='d',
                            fontSize=5,
                            applyColorToBackground=True).encode(
    row=Row('do_a:O',
            axis=Axis(format='.1',
                      title='do_a',
                      ),
            ),
    column=Column('do_b:O',
                  axis=Axis(format='.1',
                            title='do_b',
                            ),
                  ),
    color='m_teps',
    text='m_teps',
).configure_scale(
    textBandWidth=20,
    bandSize=20
)
```

![do_ab_random](https://cloud.githubusercontent.com/assets/976970/20867793/2be87762-ba01-11e6-927e-9e573b928d1d.png)

**Comment by jowens** [comment]
FWIW, we're trying to put several tables that look like this into an upcoming journal submission. We love the way they look, except for, you know, the axis labels. (We're exporting to svg and using inkscape to convert to PDF ... seems to be working OK.)

[do_ab_random_rmat_n24_e16.pdf](https://github.com/altair-viz/altair/files/629765/do_ab_random_rmat_n24_e16.pdf)
![do_ab_random_rmat_n24_e16](https://cloud.githubusercontent.com/assets/976970/20868732/57f1917a-ba17-11e6-9139-c6e36998e1bb.png)

**Comment by domoritz** [comment]
@jowens Can you send me the json version of that vega-lite program? I can try to find the right formatting.

**Comment by jowens** [comment]
@domoritz this is the altair-viz chart, does that work?

```
{"config": {"mark": {"applyColorToBackground": true, "fontSize": 5.0, "format": "d"}, "scale": {"bandSize": 20.0, "textBandWidth": 20.0}}, "data": {"values": [{"do_a": 9.999999974752427e-07, "do_b": 9.999999974752427e-07, "m_teps": 859.5197143554688}]}, "encoding": {"color": {"field": "m_teps", "type": "quantitative"}, "column": {"axis": {"format": ".1", "title": "do_b"}, "field": "do_b", "type": "ordinal"}, "row": {"axis": {"format": ".1", "title": "do_a"}, "field": "do_a", "type": "ordinal"}, "text": {"field": "m_teps", "type": "quantitative"}}, "mark": "text"}
```

**Comment by domoritz** [comment]
The problem seems to be that row and column are ordinal and thus we don't correctly handle the format. As a word around, can you format the numbers you use for column and row before you use them? 

```json
{
  "config": {
    "mark": {
      "applyColorToBackground": true,
      "fontSize": 5,
      "format": "d"
    },
    "scale": {"bandSize": 20,"textBandWidth": 20}
  },
  "data": {
    "values": [
      {
        "do_a": 9.9e-7,
        "do_b": 9.9e-7,
        "m_teps": 859.5197143554688
      },
      {
        "do_a": 9.9e-7,
        "do_b": 9.8e-7,
        "m_teps": 700.5197143554688
      }
    ]
  },
  "encoding": {
    "color": {"field": "m_teps","type": "quantitative"},
    "column": {
      "axis": {"title": "do_b"},
      "field": "do_b",
      "type": "ordinal"
    },
    "row": {
      "axis": {"title": "do_a"},
      "field": "do_a",
      "type": "ordinal"
    },
    "text": {"field": "m_teps","type": "quantitative"}
  },
  "mark": "text"
}
```

<img width="240" alt="screen shot 2016-12-05 at 20 22 47" src="https://cloud.githubusercontent.com/assets/589034/20912960/9ca98ba8-bb28-11e6-9cd6-6019601081c8.png">

I'll continue looking into why formatting ordinal numbers does not work.

**Comment by domoritz** [comment]
See https://github.com/vega/vega-lite/issues/1763

**Comment by jowens** [comment]
Happy to accept a suggestion of how I could do this within a pandas dataframe. What I tried yesterday was to format them as text (not numbers), but then once they were text, the numbers decided to _sort_ themselves as text so they were out of numerical order on the top and left side of the heatmap, not useful, so I gave up on that approach.

**Comment by ellisonbg** [comment]
Marking this as documentation for 1.3. Relevant code is in the linked vega-lite issue above.

**Comment by wanstr** [comment]
Hi everyone, I'm still having this issue but I can't seem to find anything related to this since the last update two years ago. Is this issue being put on hold or is there a better way to do this?

**Comment by domoritz** [comment]
Please follow https://github.com/vega/vega-lite/issues/5063

**Comment by mattijn** [comment]
Example as such:
```python
d = {
    "do_a": [9.999999974752427e-07],
    "do_b": [9.999999974752427e-07],
    "m_teps": [859.5197143554688],
}
df = pd.DataFrame(d)


alt.Chart(df).mark_rect().encode(
    row=alt.Row("do_a:O", header=alt.Header(format="~e", formatType="number")),
    column=alt.Column("do_b:O", header=alt.Header(format="~e", formatType="number")),
    color="m_teps",
)
```
![image](https://user-images.githubusercontent.com/5186265/198853980-fc66bc7b-8353-429e-bafe-095d2ec82c84.png)
