### ISSUE TITLE
Padding is not working correctily for Y-axis

### ISSUE THREAD

**Issue by tokedo** [altair-viz/altair#2764]
Hi, 

When I set the `padding = 0` for Y axis the range on Y axis still starts  at 0 even  though my data start at 44. Example below 
reproduces the bug: 

```python
import pandas as pd
import altair as alt


df = pd.DataFrame({
    'a': [1, 2, 3, 4, 5, 6, 7],
    'b': [44, 45, 46, 47, 48, 49, 50]
    })


plot = (alt.Chart(df)
        .mark_line()
        .encode(
            x='a',
            y=alt.Y('b', 
                    scale=alt.Scale(
                        nice=False,
                        padding=0
                        )
                    ),
            )         
        )


plot
```

Actual outcome:
<img width="499" alt="image" src="https://user-images.githubusercontent.com/34224827/208465922-6dfbc4d2-8ac3-421c-a00f-9b37c4289ab5.png">

Expected outcome: 
<img width="499" alt="image" src="https://user-images.githubusercontent.com/34224827/208466078-d86ac851-ae55-4dd8-8970-6f11da875f4a.png">

I know it can be solved ad-hoc with `domain=[44, 50]` but I'm looking for a systematic solution, as my data contain many metrics and slices I'm visualizing Altair. I though this is what `padding` for. At least for x-axis it works as intended. Would appreciate any help.

Thanks in advance.

**Comment by joelostblom** [comment]
It sounds like you are looking for `alt.Scale(zero=False)` as in this example https://altair-viz.github.io/user_guide/customization.html?highlight=zero%20false#adjusting-axis-limits, is that correct?

**Comment by tokedo** [comment]
it worked! Thank you very much for the reference. Didn't realize there is such layer of controls specific to Y-axis on top of padding. Closing the issue.
