### ISSUE TITLE
Move "inline" save functionality from altair_saver into altair?

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2765]
Since we now have vl-convert as the main saving functionality, it could make sense to move some functionality from altair_saver that is not covered by vl-convert into the altair library itself. At least functionality pertaining to saving HTML files, since this operation is already possible in altair without any additional library.

For this issue I am mostly thinking of moving the "inline" parameter into core from saver as mentioned in https://github.com/vega/vl-convert/issues/33#issuecomment-1357895491. It seems like there is only string manipulation involved in using the "inline" parameter https://github.com/altair-viz/altair_saver/blob/f5c11bb94562dee73b614255dc1122f948971479/altair_saver/savers/_html.py

**Comment by jonmmease** [comment]
I'll pick this up, feel free to assign me.

**Comment by jonmmease** [comment]
It looks like the inline Vega/Vega-Lite source is currently pulled from [altair_viewer](https://github.com/altair-viz/altair_viewer). Does that still sound like a good idea?  Altair viewer seems like a still useful package, but does it make sense to require it in order for the `chart.save("file.html", inline=True)` to work?

**Comment by jonmmease** [comment]
Looks like it would be about 1MB (uncompressed) to add Vega, Vega-Lite, and Vega-Embed to the Altair package.  Here's a PR that follow altair_saver by pulling the bundles from altair_viewer: https://github.com/altair-viz/altair/pull/2807.

Also happy to look at bringing the bundles over to Altair if that's the direction we want to go.

**Comment by joelostblom** [comment]
Implemented in #2807
