### ISSUE TITLE
Next release of Altair?

### ISSUE THREAD

**Issue by govinda-kamath** [altair-viz/altair#2768]
Hello folks, 
We were running into the issue raised here : https://github.com/altair-viz/altair/issues/2504 with violinplots in altair (even the example violin plot in the [gallery](https://altair-viz.github.io/gallery/violin_plot.html). Restricting our build to `jsonschema==3.2.0` fixed that issue; but seems to be holding back some other packages. Hence, we were wondering when the next release was planned (It looks like the issue is fixed in [master](https://github.com/altair-viz/altair/issues/2504#issuecomment-1315704973))?

**Comment by joelostblom** [comment]
Hello, we don't have a release date for the next version yet. It has involved some major changes, most of which are now included on GitHub, but there are still some we are trying to resolve. You can read more in these issues about the possible release timeline and scope:

- https://github.com/altair-viz/altair/issues/2425
- https://github.com/altair-viz/altair/discussions/2588
- https://github.com/altair-viz/altair/issues/2723#issuecomment-1339487878

**Comment by govinda-kamath** [comment]
Thanks for the quick response!

**Comment by joelostblom** [comment]
@govinda-kamath There is now a release candidate of Altair 5, which supports Vega-Lite 5! Details and info on how to install can be found  in https://github.com/altair-viz/altair/issues/2937
