### ISSUE TITLE
Add dict to allow a mapping from nominal names to what's displayed in a legend (or similar)

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#278]
I'd like to have a little flexibility to specify a mapping between a nominal data type and what's actually displayed. For instance, I might have:

```
    color=Color('first_names:N',
                legend=Legend(title='First Names'),
                ),
```

but my `first_names` are `tom`, `dick`, and `harry` and I want to display `Thomas`, `Richard`, and  `Harrison`. It'd be nice to be able to pass in a dict:

```
d = { 'tom' : 'Thomas', 'dick' : 'Richard', ... }

... legend=Legend(title='First Names', mapping=d), ...
```

It would seem like this is probably already possible, but it's not obvious in the docs or the examples, sorry to have missed it if so.

**Comment by domoritz** [comment]
You have to customize the scale domain.

**Comment by jowens** [comment]
OK, is this a domain-range thing? I don't see an example in either the altair docs or the vega-lite ones.

**Comment by domoritz** [comment]
Yes, something like https://vega.github.io/vega-editor/?mode=vega-lite&spec=stacked_bar_weather.

**Comment by jowens** [comment]
I get it. Thanks @domoritz. I'll post back with actual code shortly.

**Comment by domoritz** [comment]
Similar issue #268

**Comment by jowens** [comment]
This isn't perfect, since I'm trying to do this for a legend in the Color attribute, and the domain-range scale for Color wants to map between the domain and colors, whereas what I want to map is the domain and the text that's displayed in the legend. I'd think logically I could add it to the Legend argument to Color, but no joy.

I am comfortable with the idea of domain-range here. Just not sure where to actually apply them in the Chart object.

**Comment by domoritz** [comment]
Interesting. I created a new issue for this in Vega-Lite. For now, I think you have to rename the columns in your input data.

**Comment by jowens** [comment]
Thanks, and yeah, that's what I did as the workaround. But properly, of course, doing this in Altair > doing this in pandas.

**Comment by ellisonbg** [comment]
I am going to mark this as documentation for 1.3.

**Comment by mattijn** [comment]
Using this altair example as reference: https://altair-viz.github.io/gallery/isotype_emoji.html
This can be written as such:
```python
import altair as alt
import pandas as pd

source = pd.DataFrame([
      {'season': 'q1', 'value': 2, 'first_names': 'tom'},
      {'season': 'q1', 'value': 4, 'first_names': 'dick'},
      {'season': 'q1', 'value': 7, 'first_names': 'harry'},
      {'season': 'q2', 'value': 6, 'first_names': 'tom'},
      {'season': 'q2', 'value': 0, 'first_names': 'dick'},
      {'season': 'q2', 'value': 3, 'first_names': 'harry'},      
    ])

d = {'tom': 'Thomas', 'dick': 'Richard', 'harry': 'Harrison'}

alt.Chart(source).mark_line(point=True, tooltip=True).encode(
    alt.Y('season:O'),
    alt.X('value:O'),
    alt.Color('display_name:N', legend=alt.Legend(title='First Names'))
).transform_calculate(
    display_name=f"{d}[datum.first_names]"
)
```
![image](https://user-images.githubusercontent.com/5186265/198853405-6932ca96-9a80-4856-9dd4-ccf3865b280d.png)
