### ISSUE TITLE
extract the test-files from the Altair folder into a specific test folder

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2788]
Currently all tests are within the Altair package. So once you install the package Altair you also will get all the test files since the test-suite is inclusive.

It is good practice to store your tests outside the application code as is mentioned here: https://docs.pytest.org/en/7.1.x/explanation/goodpractices.html#tests-outside-application-code

**Comment by joelostblom** [comment]
I believe this was merged in #2792 , closing
