### ISSUE TITLE
publication-ready plots (PDF)

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#279]
This is surely more of a vega-lite (or vega) issue than an Altair issue, but:

We have some nice plots that we'd like to actually put into our (LaTeX) publications. We can export to png (which of course is bad, raster plots are bad) or svg. svg does not play with pdflatex (the most common latex package), so we'd have to use a svg-to-pdf (vector) converter. These, in general, are not good (our PDF output from the conversion is subpar). If the pdf looked just like Altair's svg, we'd probably be happy, but it doesn't. (Happy to post some examples.)

For the record, I used inkscape's `--export-pdf`, which generally gets the highest marks from what I could find online. (`inkscape --file=plot.svg --export-area-drawing --without-gui --export-pdf=plot.pdf`) This is what LaTeX's svg package uses under the hood.

I should add my svg viewer on my laptop (http://gapplin.wolfrosch.com/) exports to PDF pretty nicely, so even though it's not cross-platform, and I have to figure out how to make it work with Automator so I can script it (I've never used Automator), this might be what we do in the interim. Appears to use WebKit under the hood.

**Comment by jakevdp** [comment]
Have you tried the rsvg package on nodejs? Since you need node for programmatic figure saves anyway, it might not be too much extra installation overhead.

**Comment by jowens** [comment]
My complete lack of node knowledge makes this intimidating (`88 info rsvg@0.2.5 Failed to exec install script`). 

I used Automator to turn Gapplin's svg->pdf into an application, so at least on my Mac, this is awesome, because this conversion is flawless. So that's my current workflow. I will convince one of the graduate students to figure out the node part on our servers. 

At any rate, now that I know the conversion problem is really just crummy svg->pdf converters, and that you're putting out some great looking svg, I think you ought to close this. But, I'm sure other folks will have a similar need for publication-ready plots, so prepare to have more questions on this topic from other aspects of plotmaking.

Many thanks.

**Comment by jakevdp** [comment]
Let us know if you come across a good solution for this, and we'll put it in the docs.

**Comment by jowens** [comment]
Pretty clear to me that WebKit's svg->pdf is better than any other alternative I've seen. For the record, I've used an Automator recipe (using Gapplin) that looks like this:

https://www.evernote.com/l/AAHsGf9UqnNLSZ0C0PizrIHg-7fScTgCzrI

to duplicate the input svg file and convert it to pdf. Ideally, I could rename the output file back to the right name in Automator, but that doesn't seem to be working properly for me, so it's not in this Automator recipe. 

One would think that there would be an easier way to do this than Automator+Gapplin, but it's working for me. Anyway, I'm calling inkscape as backup (but it doesn't look nearly as good).

```
    elif (fileformat == 'pdf'):
        # check if svg has been generated
        if not os.path.isfile(name + '.svg'):
            savefile(chart, name, 'svg')

        # @TODO:
        # @jakevdp suggests rsvg on node:
        # https://github.com/altair-viz/altair/issues/279#issuecomment-265640244

        osx_svg2pdf = '/Users/jowens/Applications/svg2pdf.app/Contents/MacOS/Application Stub'
        if os.path.isfile(osx_svg2pdf):
            with open(os.devnull, 'w') as devnull:
                # hide stderr
                check_output([osx_svg2pdf, name + '.svg'],
                             stderr=devnull)
                # haven't got Automator to rename the file yet
                os.rename(name + ' copy.pdf', name + '.pdf')

        else:
            with open(os.devnull, 'w') as devnull:
                # hide stderr
                check_output(['inkscape', '--file=%s.svg' % name,
                              '--export-area-drawing', '--without-gui',
                              '--export-pdf=%s.pdf' % name],
                             stderr=devnull)
```

**Comment by ellisonbg** [comment]
Marking as question and closing. Let us know if you have other thoughts/questions.

**Comment by nipunbatra** [comment]
Just pinging to check if `pdf` export got any easier. Is it possible to avoid SVG->PDF route and directly generate a pdf? I wonder if this issue will be addressed properly when the MPL renderer is fully functional?

**Comment by jakevdp** [comment]
No, there's no direct PDF export at the moment. But once Altair 2.0 is out, I'm hoping to tackle the problem of programmatic figure outputs, maybe by drawing from some of the headless JS execution infrastructure that the Bokeh team recently released.

**Comment by jowens** [comment]
For the record @nipunbatra, we've made extensive use of svg->pdf export via the flow I described above with no concerns. (They've gone into publications, presentations, posters, etc.) I'd prefer native-pdf, of course, but svg->pdf is a perfectly cromulent alternative.

**Comment by nipunbatra** [comment]
Thanks @jowens 
For MPL, I use a function called [Latexify](https://nipunbatra.github.io/blog/2014/latexify.html), which does the following :

1. Make all font sizes same as paper LaTeX font size
2. Make prettier spines or despine!
3. Remove extra figure bounding boxes
4. Fix figure size to fit in 1 or 2 columns
5. Using a [better colour scheme](http://www.randalolson.com/2014/06/28/how-to-make-beautiful-data-visualizations-in-python-with-matplotlib/) than default 

I'd love some of these for my publication ready plots. I'd already mentioned about global font sizes in another issue.

Also, some of the plots are difficult. eg: https://altair-viz.github.io/gallery/errorbar_aggregate.html

**Comment by jakevdp** [comment]
Altair 2.0 will have direct support for error bars.

**Comment by jowens** [comment]
vg2pdf is terrific, btw. Great output quality. Thanks for adding that.

**Comment by amosbird** [comment]
It would be perfect to have vg2pdf integrated with altair's Chart save command

**Comment by jakevdp** [comment]
I'm working on that here: https://github.com/jakevdp/altair_savechart

**Comment by amosbird** [comment]
great! Is it already useable now? any manual I can refer to get it work?

**Comment by jakevdp** [comment]
No, I've just added a couple commits to the repo in the past few days. It's not yet published or documented, but yes it's usable. For now, just read the code.

**Comment by jakevdp** [comment]
Work on the package mentioned above is progressing. It now has higher-level functionality and a detailed README: https://github.com/jakevdp/altair_saver

I'm hoping to cut a release soon – give it a spin and let me know if you have any issues.

**Comment by amosbird** [comment]
Great! It works as expected.
