### ISSUE TITLE
cannot print additional items in jupyter

### ISSUE THREAD

**Issue by simonm3** [altair-viz/altair#280]
In a jupyter cell it does not display the charts if there are other print statements either before or after the display call.

```
from altair import Chart, load_dataset
data = load_dataset('cars', url_only=True)
a=Chart(data).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color='Origin:N',
)
print("hhdhddh")
a.display()
```

**Comment by jakevdp** [comment]
Thanks! This is a known issue in ipyvega. See https://github.com/vega/ipyvega/issues/62
