### ISSUE TITLE
Include `vl-convert-python` as a dependency of Altair?

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2816]
Lets open this issue. Title says it all. What are the cons and pros?

Pros:
- easy to save charts to file, svg/png
- other libraries also come included with saving engines

Cons:
- 20mb

**Comment by jonmmease** [comment]
In general, I don't think it's a good idea for a pure Python library like Altair to have a hard dependency on a native library if it can be avoided. This would break the use of Altair in contexts where `vl-convert-python` isn't pre-compiled. One notable example would be pyodide/pyscript. But also various arm architectures that are pre-built yet.

We could add `vl-convert-python` to an `extra_require` group and then update the docs to install using that group.  For example, we could add `vl-convert-python`, `altair-viewer`, and `vega-datasets` to an `extra_require` group named `full` and then instruct people in the docs to install altair with
```
pip install "altair[full]"
```

**Comment by mattijn** [comment]
That sounds good to me 👍.

**Comment by mattijn** [comment]
Thanks @jonmmease for your comment and idea: closed in favor of https://github.com/altair-viz/altair/issues/2818.
