### ISSUE TITLE
create an `extra_require` group for soft dependencies

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2818]
The following quote is _originally posted by @jonmmease in https://github.com/altair-viz/altair/issues/2816#issuecomment-1374603440_:
> We could add `vl-convert-python` to an `extra_require` group and then update the docs to install using that group.  For example, we could add `vl-convert-python`, `altair-viewer`, and `vega-datasets` to an `extra_require` group named `full` and then instruct people in the docs to install altair with
> ```
> pip install "altair[full]"
> ```

**Comment by mattijn** [comment]
Include pyarrow as a soft dependency, https://github.com/altair-viz/altair/pull/2888

**Comment by binste** [comment]
Consider a `pyodide` specific dependency set, see https://github.com/altair-viz/altair/pull/3118#issuecomment-1652731420

**Comment by joelostblom** [comment]
I think also including `vegafusion` in the `extra_require` group would be helpful. And creating a conda package for `altair-full` would also be welcome (although if there is a better way that does not require maintaining a separate meta package then that would be great).

I was reminded about this today when a colleague asks me how to include altair in their env file and I sent them six lines of what to install depending on what they are doing, which is not ideal:


```yaml
dependencies:
    - altair=5.1.2
    - vl-convert-python  # For saving altair charts as static images
    - vegafusion  # For working with charts > 5,000 graphical objects
    - vegafusion-python-embed  # Same as the previous one
    - vegafusion-jupyter  # For working with charts > 100,000 graphical objects
    - vega_datasets  # Example data
```

**Comment by binste** [comment]
I like the idea of the dependency groups! See https://github.com/altair-viz/altair/issues/3309#issuecomment-1953600671

Regarding the naming of the dependency groups, I like the approach of [pandas](https://pandas.pydata.org/docs/getting_started/install.html#optional-dependencies) where they use `all` instead of `full` to refer to installing `all` dependency groups. Feels more natural to me.
