### ISSUE TITLE
Different data sources in different layers of a plot

### ISSUE THREAD

**Issue by ehneilsen** [altair-viz/altair#282]
I can't tell if this is a documentation problem or a limitation in the code, but it isn't clear whether it is possible to use different data sources for different layers. For example, I might want to do something like what is shown in [this FAQ example](https://altair-viz.github.io/faq.html#how-can-i-add-marks-to-my-line-plot), but instead of plotting lines through the actual data, plot a theoretical curve instead, or curves from multiple competing theories. For what it's worth, I have figured out how to do this in vega-lite, just not with altair.

I know I can do something with building a DataFrame which combines the data from all sources I want to plot, but sometimes this is awkward, both practically and conceptually, and there are cases where I think this will be inadequate.

How, for example, can I use altair to generate the vega-lite presented in Fig. 3 in [Satyanarayan et al (2017)](https://idl.cs.washington.edu/files/2017-VegaLite-InfoVis.pdf)?

**Comment by jakevdp** [comment]
It's possible. The reason it's not well documented is that the layering API in Vega-Lite is experimental, and so the behavior has been changing between recent minor releases.
The behavior will be fixed in Version 2.0, which should be released early in the new year.

**Comment by ellisonbg** [comment]
Marking as enhancement and 2.0.

**Comment by jakevdp** [comment]
This is fixed in Altair 2.0, via the layering interface in Vega-Lite 2.X
