### ISSUE TITLE
Brushing over zeros causes NULL values to be selected in linked elements

### ISSUE THREAD

**Issue by nathan-uwlm** [altair-viz/altair#2832]
To reproduce the issue, you can brush over a large region that goes along the x or y axis in the example here: https://altair-viz.github.io/gallery/scatter_linked_table.html
The table will show a number of rows with NULLs even if no points were selected in the brushed region.
This is especially problematic for 2d brushing on histograms that cross over zeros.
If anyone has a good workaround for this issue, it would be very useful to me.

**Comment by joelostblom** [comment]
Thanks for bringing this to our attention. It is an issue in VegaLite and I reported it here https://github.com/vega/vega-lite/issues/8643. To workaround it on the Altair side of things you can drop nan values with pandas when passing the data frame to Altair: `alt.Chart(source.dropna())`

**Comment by joelostblom** [comment]
Closing as there is nothing to do from the altair side of things here
