### ISSUE TITLE
Update release notes with all the PRs since the last release

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#2836]
Although we don't have a date for our next release candidate, I think it would be good to get https://github.com/altair-viz/altair/blob/master/doc/releases/changes.rst up to date. Ideally we would include a line here for each new PR we make, but lately we have fallen a bit behind and it would be great to go through all the merged PRs since the last Altair release and make sure they are properly documented in the change log (ideally with the PR number included on each line so it is easy to find the details of that change).

**Comment by binste** [comment]
Reminder for us to add the release notes from `v4.2.1` (#2844) to `changes.rst` in the master branch in case it gets released.
