### ISSUE TITLE
Ranged dot plot documentation mismatch (between Altair and vega-lite)

### ISSUE THREAD

**Issue by johanneswerner** [altair-viz/altair#2839]
The documentation for the ranged dot plot for [Altair](https://altair-viz.github.io/gallery/ranged_dot_plot.html) and [Vega-lite](https://vega.github.io/vega-lite/examples/layer_ranged_dot.html) shows different outcomes. 

I believe that the plot for Altair is incorrect (as the dots are missing). 

**Altair**

![image](https://user-images.githubusercontent.com/34099811/212946487-46d58456-3a92-48c2-b74c-f75efbec8647.png)

**Vega-Lite**

![image](https://user-images.githubusercontent.com/34099811/212946809-6f033041-b64b-4893-a4c4-dcb63cb26633.png)

Probably not the correct place to ask this question, but how can I produce the lower plot with Altair?

**Comment by debbes80** [comment]
The problem in the Altair example is that the point chart domain is a list of strings while it should be ints. So using ```domain=[1955, 2000],``` instead, gives the correct plot

**Comment by joelostblom** [comment]
@debbes80 There is now a release candidate of Altair 5, which supports Vega-Lite 5! Details and info on how to install can be found  in https://github.com/altair-viz/altair/issues/2937. The docs have also been updated for this example https://altair-viz.github.io/gallery/ranged_dot_plot.html
