### ISSUE TITLE
Prepare an Altair 4.2.1 release with back-ported bug fixes and warnings

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2844]
This issue is on backporting bug fixes for Altair 4.2.

PR: https://github.com/altair-viz/altair/pull/2827 is for the fix on jsonschema and replacing `iteritems` with `items`
PR: https://github.com/altair-viz/altair/pull/2843 is about the deprecation of Vega wrappers and VegaLite 3 wrappers

This preparation is done in the `v4.2.X` as base branch.

I think this would be sufficient, but if there are still things missing we can add them here.

**Comment by binste** [comment]
I went through [all commits in master which are not in `v4.2.X`](https://github.com/altair-viz/altair/compare/v4.2.X...master) and didn't find anything which would need to be added here. Looks good to me and I think it's great to get this release out. Feel free to ping me if I can help with anything.

**Comment by mattijn** [comment]
Thanks for checking @binste.

So the branch [`v4.2.x`](https://github.com/altair-viz/altair/tree/v4.2.X) is publish-ready as Altair v4.2.1. 

Only the release date needs to be changed in the release note for version 4.2.1 when known, see [here](https://github.com/altair-viz/altair/blob/v4.2.X/doc/releases/changes.rst#version-421-released-xxx-xx-2023).

Following the [release notes](https://github.com/altair-viz/altair/blob/master/RELEASING.md) from step 7 it can be tagged and published as version `4.2.1`.

Afterwards it is probably easier to include a single commit in the https://github.com/altair-viz/altair-viz.github.io repository with the change log changes for `4.2.1`, as there are no other changes in the docs.
cc: @jakevdp

**Comment by joelostblom** [comment]
This plan sounds good to me as well. I went through all the merged PRs since the last release and didn't see anything of significance other than what has been mentioned here already.

**Comment by mattijn** [comment]
Done per https://pypi.org/project/altair/4.2.1/
