### ISSUE TITLE
'clear' field for binding_select

### ISSUE THREAD

**Issue by ogencoglu** [altair-viz/altair#2848]
I suppose currently there is no way to clear a dropdown selection by doubleclick.

It would be great to have the `'clear'` field in `binding_select` just like in `selection_interval`.

**Comment by joelostblom** [comment]
You can see an example of how to add an option to "clear" / "select all" in a widget in the radio button example in the updated docs at https://altair-viz.github.io/user_guide/interactions.html#data-driven-lookups. Adding a specific "clear" option is something that would need to be done in Vega-Lite so feel free to open a ticket there if you think this is still needed. I 'm closing this as there is nothing to do on the altair side of things.
