### ISSUE TITLE
naming parameter views of layered repeated charts + interactivity

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2849]
As discussed in this comment: https://github.com/vega/vega-lite/issues/8348#issuecomment-1399528866. It is not really clear how we implemented naming of view in top-level parameters for a layered repeater.

This was partly discussed before here: https://github.com/altair-viz/altair/pull/2684#issuecomment-1287596272, and potentially initially implemented in this commit: https://github.com/altair-viz/altair/pull/2684/commits/f5473234a43b054e778541665544086895d65d9f (this commit was not merged), but this PR https://github.com/altair-viz/altair/pull/2702 was merged where the actual change is included.

Moreover, the behavior we implemented previously does work in the following situation, -example 1- (using altair from main branch on github):

* * *
_Example 1_
```python
import altair as alt
from vega_datasets import data
iris = data.iris.url

alt.Chart(iris).mark_point().encode(
    alt.X(alt.repeat("column"), type='quantitative'),
    alt.Y(alt.repeat("row"), type='quantitative'),
    color='species:N'
).properties(
    width=160,
    height=130
).repeat(
    row=['petalLength', 'petalWidth'],
    column=['sepalLength', 'sepalWidth']
).interactive().to_dict()
```
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "config": {
    "view": {
      "continuousHeight": 300,
      "continuousWidth": 300
    }
  },
  "params": [
    {
      "bind": "scales",
      "name": "param_20",
      "select": {
        "encodings": [
          "x",
          "y"
        ],
        "type": "interval"
      },
      "views": [
        "view_24child__row_petalLengthcolumn_sepalLength",
        "view_24child__row_petalLengthcolumn_sepalWidth",
        "view_24child__row_petalWidthcolumn_sepalLength",
        "view_24child__row_petalWidthcolumn_sepalWidth"
      ]
    }
  ],
  "repeat": {
    "column": [
      "sepalLength",
      "sepalWidth"
    ],
    "row": [
      "petalLength",
      "petalWidth"
    ]
  },
  "spec": {
    "data": {
      "url": "https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/iris.json"
    },
    "encoding": {
      "color": {
        "field": "species",
        "type": "nominal"
      },
      "x": {
        "field": {
          "repeat": "column"
        },
        "type": "quantitative"
      },
      "y": {
        "field": {
          "repeat": "row"
        },
        "type": "quantitative"
      }
    },
    "height": 130,
    "mark": "point",
    "name": "view_24",
    "width": 160
  }
}
```
Specifically note this part within `parameters`:
```json
"views": [
  "view_24child__row_petalLengthcolumn_sepalLength",
  "view_24child__row_petalLengthcolumn_sepalWidth",
  "view_24child__row_petalWidthcolumn_sepalLength",
  "view_24child__row_petalWidthcolumn_sepalWidth"
]
```
* * *
_Example 2_

But the following specification:
```python
source = alt.UrlData(
    data.flights_2k.url,
    format={'parse': {'date': 'date'}}
)

brush = alt.selection(type='interval', encodings=['x'])

# Define the base chart, with the common parts of the
# background and highlights
base = alt.Chart(source).mark_bar().encode(
    x=alt.X(alt.repeat('column'), type='quantitative', bin=alt.Bin(maxbins=20)),
    y='count()'
).properties(
    width=160,
    height=130
)

# gray background with selection
background = base.encode(
    color=alt.value('#ddd')
).add_params(brush)

# blue highlights on the transformed data
highlight = base.transform_filter(brush)

# layer the two charts & repeat
chart = alt.layer(
    background,
    highlight,
    data=source
).transform_calculate(
    "time",
    "hours(datum.date)"
).repeat(column=["distance", "delay", "time"])
```
leads to:
```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v5.2.0.json",
  "config": {
    "view": {
      "continuousHeight": 300,
      "continuousWidth": 300
    }
  },
  "params": [
    {
      "name": "param_26",
      "select": {
        "encodings": [
          "x"
        ],
        "type": "interval"
      },
      "views": [
        "view_29"
      ]
    }
  ],
  "repeat": {
    "column": [
      "distance",
      "delay",
      "time"
    ]
  },
  "spec": {
    "data": {
      "format": {
        "parse": {
          "date": "date"
        }
      },
      "url": "https://cdn.jsdelivr.net/npm/vega-datasets@v1.29.0/data/flights-2k.json"
    },
    "height": 130,
    "layer": [
      {
        "encoding": {
          "color": {
            "value": "#ddd"
          },
          "x": {
            "bin": {
              "maxbins": 20
            },
            "field": {
              "repeat": "column"
            },
            "type": "quantitative"
          },
          "y": {
            "aggregate": "count",
            "type": "quantitative"
          }
        },
        "mark": "bar",
        "name": "view_29"
      },
      {
        "encoding": {
          "x": {
            "bin": {
              "maxbins": 20
            },
            "field": {
              "repeat": "column"
            },
            "type": "quantitative"
          },
          "y": {
            "aggregate": "count",
            "type": "quantitative"
          }
        },
        "mark": "bar",
        "transform": [
          {
            "filter": {
              "param": "param_26"
            }
          }
        ]
      }
    ],
    "transform": [
      {
        "as": "time",
        "calculate": "hours(datum.date)"
      }
    ],
    "width": 160
  }
}
```

Specifically, our `params` looks as such:
```json
"params": [
  {
    "name": "param_26",
    "select": {
      "encodings": [
        "x"
      ],
      "type": "interval"
    },
    "views": [
      "view_29"
    ]
  }
]
```

Where the vega-lite specification should be defined similar to this [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICAM2FksEfgCYA1lJnylxttuSY0oHEm0Q4Hg5h+6KqBIAC+EUpe2kgIEGgA2qCysUEgTNoMEDCKIL6CcFDumiCYAJ44aTSygdrESHpKcLJQbMrVZPGoCSAAHiAAumFKxDRwAO5dCT2wNILKAPoLrYIMCLIL7RDqLX5KgkhlcNoLAAyDCjMwc4vLbKvrm3AHZbkvx2cXVzdLK2sbmBoCD2IHeJ3OAyGAyUmBisggzlciVAUAaUAYB1C6BgbB0EAAFCE1pQQnAAJS5JBdUpAvxhaEgbRwSpqfx-daJFQ0bZIXa5ZTPQ65QHAwbDPKVKD+cY0ZT0NAARjEpyU8Bo5mKCtOKtBh2OyJAKVF6DBnyUyG0Nn0TG8uWarXasjI-n6JWMY3m-iZLOKIHZ8nFTGq-mQvSD8LQVlOkRArxKSDIZCZFCxftxNXCShWLn89VWaQAxAA2EvhSKgWG8hEuBAG92CWr+aKxa2ZbJlhkWq3oG3aO0tNodF3+d3PZRe5lwVnof2Z9LBkqh8NdKMxuOgBNJvip1oMDPi7N9kp5hhpFy8sh0iJDMJAA) as is mentioned in this [comment](https://github.com/vega/vega-lite/issues/8348#issuecomment-1280162030)

Which contains a `params` definition as follows:
```json
"params": [
  {
    "name": "brush",
    "select": {"type": "interval", "encodings": ["x"]},
    "views": [
      ["child__column_distance", "layer_0"],
      ["child__column_delay", "layer_0"],
      ["child__column_time", "layer_0"]
    ]
  }
],
```
As can be observed the `views` object is different. 

We might have missed something here. Maybe this is because example 2 contains a layered repeater object, where example 1 does not contain a layered repeater.

**Comment by mattijn** [comment]
This issue is halted by https://github.com/vega/vega-lite/pull/8663 which will define the strategy that Altair should take.

**Comment by ChristopherDavisUCI** [comment]
https://github.com/vega/vega-lite/pull/8662 might also be worth keeping an eye on.

**Comment by mattijn** [comment]
With VL5.7 released in editor I can see that it now behaves as follows:
```
"params": [
  {
    "name": "brush",
    "select": {"type": "interval", "encodings": ["x"]},
    "views": [
        "child__column_distance_layer_0",
        "child__column_delay_layer_0",
        "child__column_time_layer_0"
    ]
  }
],
```
So there is no list-nesting needed, now `"child__column_distance_layer_0"` vs previous `["child__column_distance", "layer_0"]`. 

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUAVhDYA7EABoQAEySYUqUAwBOgtCrVICAM2FksEfgCYA1lJnylxttuSY0oHEm0Q4Hg5h+6KqBIAC+EUpe2kgIEGgA2qCysUEgTNoMEDCKIL6CcFDumiCYAJ44aTSygdrESHpKcLJQbMrVZPGoCSAAHiAAumFKxDRwAO5dPbA0gsoA+vOtggwIsvPtEOotcPOCSGVw2vMADLkzc4vLq+vKcPtlewdHp+cwswtLbCtr85g0CF2DxeZyGAyUmBisggzlciVAUAaUAY+1C6BgbB0EAAFCFVpQQnAAJS5JBdUoAvxhcEgbRwSpqfzXNaJFQ0LZIHa5O4PXL-QGDYZ5SpQfzjGjKehoACMYhOSngNHMxWlJ3lIGB2nhIBSAvQmteSmQ2hs+iY3lyzVa7VkZH8-RKxjGc38dIZxRAzPkQqY1X8yF6vuhaCsJ0iIDK-iQZDIdIoaM9mJq4SUyxc-nqKzSAGIAGz58KRUCQzkwlwIbVOwS1fzRWJmzLZQs042m9DmrVNFptDr2-xO+7KV30uCM9BelPpP0lANBrqh8ORkrR2N8BOtBjJoVprUlTMMNIuTlkKkRIZhIA)

**Comment by mattijn** [comment]
@ChristopherDavisUCI, do you have time available to work on this in the coming week? Otherwise will try as well.

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn, in terms of looking at the Altair code, I definitely have time this week, it's more getting everything updated to the current place that is the sticking point for me...

@mattijn could you briefly summarize the issue for me?  Was this interactive crossfilter example working in a previous version (using our new parameter naming convention) and then it broke, or was it never working?

**Comment by mattijn** [comment]
Yes will do! The issue is currently (..) only about a
-  _layered repeat charts + interactivity_

From the moment we introduced top-level defined parameters this has never worked (due not proper initiating the `views` object within `params`).

I think the following approach should be adopted, for the [Interactive Crossfilter](https://altair-viz.github.io/gallery/interactive_layered_crossfilter.html) example:

1. Defining a `name` in the first object of the `layer` within the `spec`:
```json
  "spec": {
    "layer": [{
      "name": "view_1",
```
2. Checking what is being repeated.
```json
  "repeat": {"column": ["distance", "delay", "time"]}
```
3. Construct the `views` property in the `params`:
```json
  "params": [
    {
      "name": "param_1",
      "select": {"encodings": ["x"], "type": "interval"},
      "views": [
        "child__column_distance_view_1",
        "child__column_delay_view_1",
        "child__column_time_view_1"
      ]
    }
  ],
```
Where the view is defined as, `child__<repeat-row>_<data-field><repeat-column>_<data-field>_<view-name>`

See here a working specification how it should become: [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUA7JQAMlAFYQ2AOxAAaEFBUAzGmTShiNOAHcDmlZhrKGbBhAAScPVjQBmGTI1blVm3YgAdRoAE3p3TwBfSI0cJAAnJAQINABtUGUkuDQQOMSEAH0ARnUQCDhBOChMczhlLRDrMhTUVJAADxAAXQ1MAE8cbPRrTDh44iRBEBiQI1MWttgaQRCCgq1BBgRlAsaITCR6uAK5k2LSpZW1ja2dkIqkPpPjM5LvGGXV9bZN7YKrBDHU7nLqRHogeJwQZIGqoUA3bZpEB7A5HUr3QSPUoA7KgjQQQZQcwhGEoOEgbRseLIWGgPLlYkwobIpnTGYMeJTdBYXD4IhQELKBQQDE0YjxSjKOCYAjKHAIXgUfgkg7lTAQAACxCKlAATABOWQEFVIAjaYRkLAQfi6gDWwpU0w08BcsKKHg0mL6YzSGSyOWBbxAdQaTXMGyp5gmm2ZAGIQgmnR1zExrOZkO1U8oWrqZDNdBUQuZIdDYRZfqpoho+uYkGQyJCKKMcloGL5sQNmQBHBiHKwHKykNkaZDxW3mfqDHJMBLD0AhtiNZT6cmdclZ9NITPWHN5jQFlbFqFwGEtn63YcgGvkusNvjN9Ct9u9Ts5Ht9ugwsXZKsgUfj8lJ2ZGd4iTTBEmzSlqV9ClllGUDyTyJIciQwoSmiUFwXAw4ICghAYKQFoQBxC5JigBhMQfDA7HiCAAAoVS2SgVTgABKaZwRMUJwlQIoADY80iIA)

* * *

I was re-reading this comment https://github.com/vega/vega-lite/issues/8446#issuecomment-1437517310, but **I'm not** able to get a
- _repeat charts + interactivity_

to work anymore.

The following `views` definition:  `<view-name>child__<repeat-row>_<data-field><repeat-column>_<data-field>` does not give interactivity in the charts anymore with VL5.7 (here zooming through `"bind": "scales"`).

See also this example where the interactivity (zooming) does not work anymore [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEFBUAzGmTShiNOAHcDmlZhrKGbBhAAScPVjQBmGTI1blVm3YgAdRoAE3p3TwBfSI0cJAAnJAQINABtUCZrELQQaCRBOBSNZSS4HLjEhAB9AEZ1XLgCqExzOGUtEOsyFNRUkAAPeoBPEABdDUwhnDL0a0w4eOJ8kBiQI1MevvWTWtgaQRCqqvi2HenMfIAZNrJ6LUEGBGUqiDg4wWvlW5h67d2YfaHY6nKrnK43O5sB5PF5vfLBMI-DR-Gp7A5HE5nOAXQQIyHQ56vd6fb6-Yw7VEA9HArE4vEwe6PQlw3GhcKjSLjEDxN5wJAtVCgRlPNINYkQpFi+Fsn5czGisEfCX1RX0sarCDTKDmEL8lCCkAMeKCHJYXD4IhQELKBQQEKNGjEeKUZTYgjKHAIXgUfi6i6vTAQAACxBqUgAnLICH6kAQaPEaBBbSoVho2h0uuZ7mx4uZdI1suhNXAoMYiiBJtMcso2AhrMtVoMDfmDuYedN+TlhapVpWZiAAI4MJC+Oj8x1lVYjZvGVsG9t8gXc06pitTftDkdWC5WUgrVbwFwCmoeDTIeIAa3KbDm9RKCH7KPqJhlaBqADYZNEgA)

I tried a few things and inspect [this PR](https://github.com/vega/vega-lite/pull/8733/files) at the VL repository, but I can't find a way how to make this work again. Any idea @domoritz?

**Comment by mattijn** [comment]
@ChristopherDavisUCI, I just merged [PR](https://github.com/altair-viz/altair/pull/3022) in the Altair main repo, so the main branch of Altair is on VL5.7.1. I hope this will make it easier to work on this issue.

Here a few steps that maybe helps getting up your local environment again after all the recent changes:

1. Make sure the master branch of your published fork is synchronized with the master of altair main repo.
You can click `Sync fork` on your github page: https://github.com/ChristopherDavisUCI/altair, and click `Update branch`
![sync_branch](https://user-images.githubusercontent.com/5186265/233593379-93940060-4c4f-4818-93e5-393bf5ed6d18.png)
If this succeed, this button will grey out and the row states a message: _This branch is up to date with altair-viz/altair:master_.
You also can use `git` from the terminal by setting up a `remote`, that you can `fetch`, `merge` and `push` from your forked master branch.

2. Make sure your local master branch has the latest changes from step 1.
If you have conflicts, be careful, but if the changes are not recent, its probably easiest to discard your local changes.
Within your development environment (eg. conda); within the cloned altair folder of your fork,  you can do 
``` 
git checkout master
git pull
```

3. Update development dependencies
Make sure have the required dependencies in your development environment.
This should at least add `hatch` as a new dependency and upgrades the packages `altair_viewer` and `vl-convert-python`.
Make sure `altair_viewer` has access to vega-lite 5.7.1
I also had to uninstall `altair_saver` to not pollute the tests-results. 
```
python -m pip install -e .[dev]
python -m pip install vl-convert-python --upgrade --no-deps
```
```python
>>> from altair_viewer import get_bundled_script
>>> get_bundled_script("vega-lite", '5.7.1')
```
```
pip uninstall altair_saver
```

4. Correct Python interpreter within VSCode
If you are running the test-suite within VSCode make sure you also have selected the python interpreter connected to the right environment with the installed dependencies of step 3.

5. Then create a new branch from your local master, named eg, 'fix_gh2849`.

6. Apply your changes
As was mentioned in https://github.com/altair-viz/altair/pull/3022#issuecomment-1517486437, you will need to activate the interactive_layered_crossfilter example in the tests again by removing the trailing `_` from the filename `_interactive_layered_crossfilter.py` in both the `examples_arguments_syntax` and `examples_methods_syntax` folder.

7. Test, commit, push, publish and create a PR
Apply and test your other changes, commit the messages to your branch, push the branch and create a PR from your published branch to the main altair repo. You can also test your changes locally from the altair root folder within your branch of step 5 using:
```python
hatch run test
```

If you need help, just ping!

**Comment by ChristopherDavisUCI** [comment]
Thanks @mattijn, I hope to find some time this weekend!

**Comment by ChristopherDavisUCI** [comment]
Those detailed instructions were very helpful @mattijn, thank you!  I think my development environment is caught up.  I will keep you updated... I need to refresh my memory on the logic of where the view naming is currently happening.

**Comment by mattijn** [comment]
That is a separate issue. 
A repeat chart with params .
Here it is a _layered_ repeat chart with params.
Maybe it should happen in the Layer context?
