### ISSUE TITLE
Limiting axis range

### ISSUE THREAD

**Issue by dlsun** [altair-viz/altair#285]
I've looked all over the documentation, and I can't for the life of me figure out how to limit the x- or y-axis of a plot to a given range. I want to do the equivalent of:

```
plt.plot(np.arange(10), np.arange(10), '-')
plt.ylim(2, 6)
```

I want the plot to cutoff gracefully at the edges. But I only see two possibilities in Altair's Scale() object. clamp=True would set the y values to 6, while clamp=False would allow the lines to go outside the boundaries of the plot. What is the correct way to do this in Altair?

**Comment by kanitw** [comment]
Sounds like you want to adjust scale's domain to [2,6] and set clamp to true?

**Comment by jakevdp** [comment]
Hi,
There's an example of this in the configuration section of the documentation: https://altair-viz.github.io/documentation/config.html#adjusting-axis-limits

Some of the docs for these kinds of things are relatively incomplete right now; the 2.0 release is going to revamp a lot of these types of things, and at that point we'll invest the time to make docs more complete.

**Comment by dlsun** [comment]
Filtering the data only resolves the issue for mark_point(), not for mark_line(). If you filter a point out from a line plot, then the line won't be drawn at all.

Basically I want the line to behave up to the edge as it would if the axis were not truncated. However, I don't actually want the line to show up past the edge of the plot.

**Comment by jakevdp** [comment]
Ah, sorry to misunderstand the issue.

I'm not sure if there's a way to do that at the moment.

**Comment by ellisonbg** [comment]
@kanitw thoughts on this from the Vega-Lite side?

**Comment by ellisonbg** [comment]
@dlsun looks like this is an issue with vega-lite. I am going to close this as a reference issue here - feel free to follow up with the vega-lite devs with an issue over there. Thanks!
