### ISSUE TITLE
Schemapi debug mode always on?

### ISSUE THREAD

**Issue by velochy** [altair-viz/altair#2850]
I was debugging some performance issues in my streamlit application and noticed that Altair schema validation is taking a significant amount of rendering time.

So I dug into the altair code and noticed something rather odd in `altair/utils/schemapi.py`, row 23-33

```
DEBUG_MODE = True


def enable_debug_mode():
    global DEBUG_MODE
    DEBUG_MODE = True


def disable_debug_mode():
    global DEBUG_MODE
    DEBUG_MODE = True
```

So if I read it correctly, debug mode is set by default, and "disable_debug_mode()" will fail to disable it. 

Its hard to believe this is intended behavior, but I'd prefer someone who understand the codebase better have a look.

**Comment by binste** [comment]
I used the `%%timeit` cell magic in Jupyter to time the following example. With `DEBUG_MODE = True` it takes `12.2 ms ± 499 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`. If set to `False`, I get `8.22 ms ± 250 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)`. This is a difference which should not be noticeable for a user.

```python
stocks = data.stocks.url
highlight = alt.selection_point(name="highlight", on="mouseover", clear="mouseout")

line = (
    alt.Chart(height=100, width=200)
    .mark_line(point=True)
    .encode(x=alt.X("date:N", timeUnit="year"), y=alt.Y("mean(price):Q"))
)

rect = (
    alt.Chart(width=200)
    .mark_rect()
    .encode(
        x=alt.X("date:T", timeUnit="year"),
        fill=alt.Y("mean(price):Q"),
        stroke=alt.condition(
            highlight, alt.value("black"), alt.value(None), empty=False
        ),
    )
    .add_params(highlight)
)

alt.vconcat(line, rect, data=stocks)
```

The advantage of the immediate validation with `DEBUG_MODE = True` is that errors can be catched earlier. If I for example introduce an argument `unknown` to `selection_point` I'd immediately get the correct error without having to wait for the chart to be rendered:

```python
highlight = alt.selection_point(name="highlight", on="mouseover", clear="mouseout", unknown="test")
```
```python
altair.vegalite.v5.schema.core.PointSelectionConfig, validating 'additionalProperties'

        Additional properties are not allowed ('unknown' was unexpected)
```

**Comment by mattijn** [comment]
I think you mean https://github.com/altair-viz/altair/pull/2842 and not https://github.com/altair-viz/altair/pull/2824 for the rework of the validation.

**Comment by binste** [comment]
Indeed, thanks! Edited my comment.
