### ISSUE TITLE
infer argument types from vegalite schema

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2854]
Based on these two comments in this PR https://github.com/altair-viz/altair/pull/2846:

> _Originally posted by @mattijn in https://github.com/altair-viz/altair/issues/2846#issuecomment-1401606735_
> 
> I understand that adding another dependency just to reduce 5 lines of code is probably not worth it. I also agree that there may be other recent type-related changes in the core of Python that makes it something to consider if we look a bit broader than this PR alone. 
> 
> We previously had two types of discussions about types in Altair. 
> 
> - One is about improving the existing Python code in the /tools folder in the Altair repository, such as this issue (https://github.com/altair-viz/altair/issues/2493) and related PR (https://github.com/altair-viz/altair/pull/2614, btw I now notice that this PR also uses the `TypeVar` bound approach).
> 
> - The other is about including types in the generated Python code of Altair, originally (https://github.com/altair-viz/altair/pull/2670) adapted to (https://github.com/altair-viz/altair/pull/2681) and then reverted back to the original in (https://github.com/altair-viz/altair/issues/2714). 
> 
> Especially the result of the second bullet has set the type `Any` to anything that is `Undefined` finishing this discussion on, 'what is the type of `Undefined`?'. 
> 
> However, with your impressive PRs regarding jsonschema and types, I was wondering, since types are included in the vega-lite jsonschema, if these types can also be inferred for each argument? Maybe recent type-related changes in the core of Python can make this easier? It is merely an open question from which I don't know enough if it is worthwhile to consider.

and

> _Originally posted by @binste in https://github.com/altair-viz/altair/issues/2846#issuecomment-1404066238_
> 
> Thanks for writing this down! This is very helpful. It should be possible to create Python type hints based on the vl schema, especially given that this parsing is already done for the docstrings, see e.g. https://github.com/altair-viz/altair/blob/master/altair/vegalite/v5/schema/channels.py#L12509 where the `stack` argument to `alt.X` is documented as:
> ```
> stack : anyOf(:class:`StackOffset`, None, boolean)
> ```
> 
> There are probably also synergies with replacing the vega-lite types with Python types in all error messages (suggested by you in https://github.com/altair-viz/altair/pull/2842#issuecomment-1400813951) and docstrings. 
> 
> As more type hints shouldn't break anyones code, I don't think we would need to necessarily include it in the release candidate but I'm definitely intrigued in giving this a try. I really like the development experience you get for a library with well-defined type hints such as better autocompletion as well as early warnings if you pass a wrong value to an argument before even executing the code, for example if you'd pass an integer to `stack`. The same linters could then of course be used in CI/CD pipelines.
> 
> I'll try to get a draft PR going in the coming weeks so we can further explore how well it works.

**Comment by mattijn** [comment]
Type checking from the jsonschema is interesting, but it is likely that the flexibility of python does not always match with the schema. See e.g. https://github.com/altair-viz/altair/issues/2877

**Comment by binste** [comment]
For reference, the Pydantic docs have a mapping of Python types to json schema types: https://docs.pydantic.dev/usage/schema/#json-schema-types
