### ISSUE TITLE
Unrecognized signal name while rendering altair example 'Multiple Interactions' in VL

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2856]
There is an issue with the rendering of example Multiple Interactions in Vega-Lite ([Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3NATABDccgDaoRopUoNIALZKATgGs8IQgE8ADphQhrEEuO7wANm8x0UhI6UxyIJhQkHQkSKgWEBBuxNbm8Jhu3sggACpwhJ4g3Fa29lAQ+iRKbiCBAB4JWMn21BBGydj0mAD6AOJGEJSUOSCUytmRYG5K+vHIvv7cdEVKJLoAjBwrnMsrG2wAuoF5dqkAjqRKRJkqcGh2gZbVSSkgAJIAsgAiAEKtAErnUEi5NvsQEcTsRCOdLuVAowRAgxCgAEwcbiUJKYMDEaDmT6opQogAEAE1MMZWuY9vZKOFstwAEYkFKgEjWUiqEBGE4IOzcQxVZCIxYADm5C2QiwAnAA2MXIwiYCaLQKJZK9dQgbGeXFtInGEA7XaZIYgADKbhaRjxADE4LFMEZwn1fCdKDAGvpdPhSmBSKNZfYYG5okYABR0FSkfQAOme7y+PwQAEo+rj7J8KFA6F5WtGPt8+Eg5B63F6fYDQ4RwxGAApdOikdFwaCtN6kOicwh4gB8ePWmzYEbYeIA-N2OHjkCOkyqQIJSOmjJmntbTY3qxBa-XMQXwJ7vSpAZZicGyxX1cSUa0XnvE9xk6lT5rWtqjOVOKB3LLn6kQ2HI9nY3nOzxNhEy3d9bVuWpUieSsAEEYP-e1uGgTAAHkYF0EB2j6AA5ABhABaRYAHY+krLDuDIwiJD6T5dVkV8QDAz9QBRTwNygFMcXxJ9SVkLZuGaBhmD5GQGMMUwyQBexHGcPp3E8FIpgCbhglCe1IkIaJYjgCY3xqe4MiyLkLCk1JCmKKBShfEBeT0u46gaJoWg6Loej6AZSn2fBRnGHw-EwGY5hFNQeyRULNh2f58kOY5TjBYgIWuCD7j-XNEJM6KgVi0FwSuKEYThESuH6VF2PMdpgnnSTMspX5qUY-SVTUEAniUAArBoOkqux+JAOl03MJkWQpUqXBACBrAxKAmpAGCyu4GC6EuIhSCq7g3lGMATDxXCii8G5uF2-R9r6XaQltQgAHpK1tF0jEMc6+heCAvWOohjAOkAXnZQw+kEBoumfbgnioOBBhouZTjAHa9roT60kYO0PFtS6jSoWxpuM6hMEoD8OL1fUjPsb6JtmbAoEta0P3Sx1prut11ELYs9z9AMGm-ctf1eHM42vEBbzVNMMzoLNuYQ34XyZ3dfVSY9I1XdcpqbFs20A8KVn7IcRwHcdlknewZznBclwbKBWgVuspsl7ci2l-dDw5k8uLaS9ZT5gX73PJ9raY+xHa5mM0t+QDgJ9qnwMiJV7mguDxb+caoFQ9DVXIkA8MIkiKNTyjFmo7haL1BjfciVi0St1IKqgKq+IE+gmARGRIs0bRVD0cSzA00yHCcIg5KXLw-P8QJVLXdT8BiBpzAIMJy7syCWtg+Cg-jzxOQG5AyA8KLAXMkoymRUbTZTONrLQUp-HsU1YUIBB2RuXYtLiZL7EM+ryTMoo9+s2yGvs1J6kaHQQSbROjdF6MiQYXlwA+QmEpQKhhgrhTWL2FYkUMqAmBHFXK1kbiR30vYVKJ9t72EwTlBKeVuDQlEKoRExVS5lUiMvaqgJaoIHqlHGaMcl4n16v1BkIAhqsnZGECAfQJpTRmqndOxFSLZ3aFRGidF6IWANICb4Ii8TNkIJpCmghRBXzEDTdkdNXTuhtszGWjE2ZHh-FGMWy93ZTlTLOYWotA4ny3IMCxpZbEW3YsrVsmB2xdnVhwTWw51hjgnDeKchs6DzhFouDwptzY1ktkfTxO4Sz2APMYf2EZPYuyvPrO8ztHyHjDjaT8IB8mEIAl2UOoFw7MV-vPLhccxGJzQhhKRBEZFZ1kQo-OSjeqCXrkVLc7dmHSR7mNeSA9Jj+WHiEUeEsS5wAAF5QOnpkI+kQz5uAvnyAArAfNi5cQBvEQJolWQTKZuH0L0RU+DUhxISa0JJy4zZ+KtsQmKIIzjkOsppGIT88F-3SKoh0Xdd6WTKJUZ+-9HJAOcqAtyEDPJTxgYPAKIBZgII4uoJBoSOBoPfllAF8ULhXG4LgueKV7FEPQSQ7KgLqWQkoQVGhSISrnL2aAK5CAbmBPbFaB5KpQDktYfVPhg0oDMlZGAaEW0aQQCqLIQmhpcLKpMKqiolpXQqDzA6YxzpTGM3MXbVmgZamMrzI4lMQtMx1PtJk222TZa+LSf45sIq1YoL7AOCJo5dZsBKdOFx7zPkpJ+RkhiXirWpFyTYzmBSymu0wA60pGovYVKaVUv2cs7HuPqUBECRdmmIoXrHJhSEunJ2ar0jOsjBm50UXqUZddhK0OkDsXqZYlDmFWmUVIYhCDWEoMgS6l0wB0CgBGNqlAMymjQEYCMicrryv0JdS4CAlD4QHSiQglAAACaBFgRnhGKfsl0B2XX0BADAOMF2UExK4Q1qhQDWGMCiLE6aWaet9Bq7gAASAY0Jfqju0ROqdO7MB7ojAgTIjBSA0gjA2S64HMCGDg3u-CppZQ7pYBGYi-YX2biAA)).

It renders OK in [current documentation](https://altair-viz.github.io/gallery/multiple_interactions.html) and in the [proposed v5 documentation](https://joelostblom.github.io/altair-docs/gallery/multiple_interactions.html).
But there is this `Big_Budget_Films__vgsid_` option in the parameters. I don't know where this `__vgsid_` comes from.

 If I open the chart in 'Open in Vega Editor' using the three dots then it will present the following error:
```cmd
Unrecognized signal name: "Big_Budget_Films_tuple_fields"
```
I feel this specification requires a bit of reworking.

[Reproduce the Issue in Colab](https://colab.research.google.com/gist/mattijn/783fea12dbf806d208066716057191da/altair_issue_-2856.ipynb)

**Comment by ChristopherDavisUCI** [comment]
Nice catch, @mattijn.  It's a little confusing that it renders fine for us and that the json seems to be okay...

Here is closer to a minimal example that seems to raise the same error:

```
import altair as alt

input_checkbox = alt.binding_checkbox()
checkbox_selection = alt.selection_point(bind=input_checkbox)

c = alt.Chart().mark_point().encode(
    size = alt.condition(checkbox_selection, alt.value(25), alt.value(100))
).add_params(
    checkbox_selection
)

c
```

This renders seemingly fine in Altair, but when opening in the Vega Editor, a similar error shows up.  (I used `c.to_json()`, not the three dots, and then pasted in the Vega editor, so it's not specific to the three dots.) [Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4IgJAzgxgFgpgWwIYgFwhgF0wBwqgegIDc4BzJAOjIEtMYBXAI0poHsDp5kTykBaADZ04JAKyUATJQAMlAFYQ2AOxAAaEFBUAzGmTShiNOAHcDmlZhrKGbBhAAScPVjQBmGTI1blVm3YgAdRoAE3p3TwBfSI0QpEwUVFBlJAQ4NBBEHEwATxAYkDiEiDhMCHMs3LQAbWBIgF0CuGUtEOt9JJAIGgAvdM6fNqsVcxwkACdUjLHJhAB9AEZ1EGIkQQZ+yTEC1fX+haiC5HGAa2m2a0xlmdTy1FqQJmsQ82scBiv0WDgoE6Y2AAe+Q0KTS0wmqUWyxKgh+n1AuRw-RAOAuvnyDUiQA)

I tried the json in my two Vega-Lite PRs, but the same error was raised in both of those.
