### ISSUE TITLE
Not able to change color of text(label) in mutiple stacked bar chart

### ISSUE THREAD

**Issue by sushant7878** [altair-viz/altair#2858]
Type here...
base = alt.Chart(df).encode(
    x=alt.X('sum(values):Q',title=None),
    y=alt.Y('time_slot:N',title=''),
    color=alt.Color('legend:N', scale=alt.Scale(range=['#96ceb4', '#ffcc5c','#ff6f69','#000000','#8601AF'])),
    opacity=alt.value(0.8),
)

alt.layer(
  base.mark_bar(),
  base.mark_text(align='center',fontSize=15,color='coral')).encode(text='sum(values):Q').facet(row='hour')
---

I could change the color of text/label in this though I tried multiple color, it always shows the same color as the color of the bar, that make the contrast of text difficult to read. 

Please follow these steps to make it more efficient to respond to your feature request.

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most feature requests should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example.
- [ ] Search for duplicate issues.
- [ ] Describe the feature's goal, motivating use cases, and its expected behavior.
- 
![altairissues](https://user-images.githubusercontent.com/29767442/215007238-da8235ec-ee1f-4a5a-a3c0-7a20ea58af09.jpg)

**Comment by sushant7878** [comment]
I want the value of each case to be written in the middle of the bar graph for each scenario. will it be possible or not?

**Comment by joelostblom** [comment]
There is an example of this in the documentation https://altair-viz.github.io/gallery/stacked_bar_chart_with_text.html
