### ISSUE TITLE
Python 3 Compatibilty?- No Module Named Altair?

### ISSUE THREAD

**Issue by pgensler** [altair-viz/altair#286]
Hello,

I'm relatively new to the python world, so please forgive me if this post is not descriptive enough.
When I try to load Altair into my notebook, I get an error message saying there is no module named altair, but when run Bash to check what packages I have, I have it loaded.

I am using Python 3 in virtualenv.
Here is my code:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-cb7a8f302186> in <module>()
      1 import pandas as pd
----> 2 from altair import Chart

ImportError: No module named 'altair'

%%bash
pip list
altair (1.2.0)

```
Is Altair not compatible with Python 3? Running it with Python 2 seems to work ok.

**Comment by jakevdp** [comment]
Altair is compatible with Python 3. I suspect the problem here is that the notebook kernel you are using points to a Python instance that does not have the altair package installed. [This StackOverflow question](http://stackoverflow.com/questions/39007571/running-jupyter-with-multiple-python-and-ipython-paths/39022003) might help you sort out what's going on.

**Comment by jakevdp** [comment]
More pointedly: packages are installed for *particular* Python versions. When you run bash commands, it references the Python in your bash path, which may not be the same as the Python used by your notebook. You need to make sure Altair is installed for the Python indicated by this output:

```
import sys; sys.executable
```

**Comment by nembrinj** [comment]
Hello,
I have the same error (in python 2) although I just installed altair to the virtualenv which is used
```
import sys
print(sys.executable)
```
gives `/home/XXX/miniconda2/envs/py2/bin/python`

and if I try to update altair through conda

```
(py2) XXX@yyy:~$ conda update altair
Fetching package metadata .......
# All requested packages already installed.
# packages in environment at /home/XXX/miniconda2/envs/py2:
#
altair                    1.2.1                      py_0    conda-forge
```
Any clue what I did wrong?

**Comment by sebastianbk** [comment]
I have the same issue. Does somebody have a solution for this?

**Comment by jakevdp** [comment]
The solution is to install Altair so that it is visible to the Python installation that you're using.

Unfortunately, with the combination of different ways to install Python and different ways to view Altair plots, there's no single solution that will work in all cases.

To help you diagnose this, can you tell me:

- how did you install Python? (conda? system python? macports? homebrew? yum? apt?)
- how did you install Altair? (with conda? with pip? what actual command did you run?)
- how are you trying to use Altair? (jupyter notebook? jupyterlab? nteract? colab?)

**Comment by joelkalonji** [comment]
I recently encoutered the same issue and I will appreciate your help:

    what operating system are you on? I am using Windows 10 
    how did you install Python? I am using the Anaconda Navigator 
    how did you install Altair? I am running a "Pip Install" on the terminal Jupyter Notebook. 
    how are you trying to use Altair? I am using Jupyter Notebook, I am using Python 3

**Comment by jakevdp** [comment]
If you run ``pip install`` from within the jupyter notebook, it does not necessarily install the package in the currently active kernel.

I'm not familiar with Anaconda Navigator or how package installation with pip works on Windows. You may wish to contact Anaconda support if you are having trouble installing packages.

**Comment by LightWant** [comment]
I have the same issue, too! I have copied the entire package directory to the project directory(Pycharm), but the error still exists. That really bothers me.

**Comment by jakevdp** [comment]
I would not recommend manually copying the package directory into your path. There are often installation steps that involve more than simply copying files from place to place.

The best approach to ensure you are correctly instaling a package is to run ``python -m pip install <packagename>`` with the python executable that your development environment uses.

**Comment by cuspime** [comment]
> The solution is to install Altair so that it is visible to the Python installation that you're using.
> 
> Unfortunately, with the combination of different ways to install Python, different ways to install packages, and different ways to launch and execute Python code, there's no simple list of steps that will work in all cases.
> 
> To help you diagnose this, can you tell me:
> 
> * what operating system are you on? (linux? windows? OSX?)
> * how did you install Python? (conda? pipenv? system python? macports? homebrew? yum? apt?)
> * how did you install Altair? (with conda? with pip? what actual command did you run?)
> * how are you trying to use Altair? (jupyter notebook? jupyterlab? nteract? colab? ipython shell?)

Hi jakevdp.
I am running Windows 10 and installed Python (3.6) with Anaconda, I have already ran the conda command to install both vega and altair but when running it on my Jupyter nb, I have the following error:

---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-8fb0819314f0> in <module>
----> 1 import altair as alt
      2 from vega_datasets import data

ModuleNotFoundError: No module named 'altair'


Have been looking around for a solution but I have no clue on how to proceed.
(By commenting the first line I also get an error stating "ModuleNotFoundError: No module named 'vega_datasets' "

Could you please help?

**Comment by jakevdp** [comment]
It looks like the packages are not installed the packages in that Python environment. See https://packaging.python.org/tutorials/installing-packages/ for help.

**Comment by dasvidanja** [comment]
Hello guys, 
I've encountered the same issue of having all packages and libraries,  but still not being able to run the Altair chart from the Jupyter Notebook. After some trying out, I ran this command on my Jupyter file & everything started to work (it simply downloads Altair on your current kernel). 

import sys
!{sys.executable} -m pip install altair vega_datasets

**Comment by jakevdp** [comment]
If your IPython version is not ancient, there is no need for the ``sys.executable`` hack. Just use the pip install magic:
```
%pip install altair vega_datasets
```

**Comment by docjsha** [comment]
I had the same issue after installing altair in my conda env running on python 3.6.  I solved it by reinstalling jupyter notebook along with altair and vega:

`conda install -c conda-forge altair vega_datasets notebook vega`

**Comment by Tahirhan** [comment]
> For IPython newer than version 7.0, there is no need for the `sys.executable` hack. Just use the pip install magic:
> 
> ```
> %pip install altair vega_datasets
> ```
solved my issue thanks!

**Comment by aditinamdev** [comment]
> For IPython newer than version 7.0, there is no need for the `sys.executable` hack. Just use the pip install magic:
> 
> ```
> %pip install altair vega_datasets
> ```

Works, thankyou!
