### ISSUE TITLE
Show all points on boxplot with groups

### ISSUE THREAD

**Issue by rcolpo** [altair-viz/altair#2862]
As far as I can understand, to visualize all points of a boxplot it is necessary to overlay plots (one with the boxplot, and other with the points). However, plots with groups can not be overlayed. Therefore, I suggest including a feature to show all points in a boxplot (not only the outlier) without overlaying the plots.
Below you can find an example of a plot I could not reproduce using Altair:

![allPoints](https://user-images.githubusercontent.com/5889181/215532791-9ee940a3-8db7-4b60-89ee-77f6d2871215.jpg)

The code for the boxplot made with Altair can be found [here](https://stackoverflow.com/questions/75278994/align-rotated-labels-of-altair-boxplot/75279756#75279756).

**Comment by rcolpo** [comment]
Sure.

```
import seaborn as sns
import altair as alt

tips = sns.load_dataset("tips")

tips = tips.replace('Sun', 'Sunday morning')

chart = alt.Chart(tips).mark_boxplot(ticks=True).encode(
	x=alt.X("smoker:O", title=None, axis=alt.Axis(labels=False, ticks=False), scale=alt.Scale(padding=1)), 
	y=alt.Y("total_bill:Q"), 
	color="smoker:N",
	column=alt.Column('day:N',
					  sort=['Thur','Fri','Sat','Sunday morning'],
					  header=alt.Header(
						  labelPadding=360,
						  labelAngle=-90,
						  orient='bottom',
						  labelOrient='bottom',
						  labelAlign='right'
						  
					  ))
)

chart += chart.mark_point()
```


When I try to overlay the points in the boxplot using `chart += chart.mark_point()`, I get the error `ValueError: Faceted charts cannot be layered.` 
I suppose it is not possible to create a boxplot with groups without using `alt.Column`, and "Faceted charts" seems to be related to the  `alt.Column`.
Do you know of any other way to create a boxplot with categories showing all the points?

**Comment by mattijn** [comment]
this is often confusing, but a layered chart can be faceted:

```python
import seaborn as sns
import altair as alt

tips = sns.load_dataset("tips")

tips = tips.replace('Sun', 'Sunday morning')

chart = alt.Chart(tips).mark_boxplot(ticks=True).encode(
	x=alt.X("smoker:O", title=None, axis=alt.Axis(labels=False, ticks=False), scale=alt.Scale(padding=1)), 
	y=alt.Y("total_bill:Q"), 
	color="smoker:N"
)

chart += chart.mark_point()

chart.facet(
    column=alt.Column(
        "day:N",
        sort=["Thur", "Fri", "Sat", "Sunday morning"],
        header=alt.Header(
            labelPadding=360,
            labelAngle=-90,
            orient="bottom",
            labelOrient="bottom",
            labelAlign="right",
        ),
    )
)
```
<img width="429" alt="image" src="https://user-images.githubusercontent.com/5186265/215552293-f2751b6b-c6f9-4608-8741-f8497302b58c.png">

**Comment by rcolpo** [comment]
Hi Mattijn,

Sorry, but when I create a chart using your code and save it using `chart.save('chart.html')`, I only get one single chart/day:

![chart](https://user-images.githubusercontent.com/5889181/215609978-4107ba66-5efd-4051-892f-e68c234f9632.png)

Have you done anything different from the code above, or my saving method messed with the final image?

**Comment by mattijn** [comment]
did you assign the faceted chart back into a variable?
```python
chart = chart.facet(...)
chart.save('chart.html')
```

**Comment by rcolpo** [comment]
Thank you :)
