### ISSUE TITLE
Make `altair_viewer` and `altair_saver` work with Altair 5

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2866]
As was pointed out in https://github.com/altair-viz/altair/pull/2686#issuecomment-1299080517. Once Altair 5 RC is released `altair_viewer` and `altair_saver` won't work anymore as they are using the entrypoints of altair vegalite 4.

Observe current behaviour using altair from GitHub main branch:
```python
import altair as alt
from vega_datasets import data
import altair_viewer

cars = data.cars.url

op_var = alt.param(value=0.1)

chart = alt.Chart(cars).mark_circle(opacity=op_var).encode(
    x='Miles_per_Gallon:Q',
    y='Horsepower:Q',
    color='Origin:N'
).add_params(
    op_var
)

altair_viewer.display(chart)
```

> ```cmd
> ---------------------------------------------------------------------------
> NoMatchingVersions: No matches for version='5.2.0' among ['4.0.2', '4.8.1', '4.17.0'].
> Often this can be fixed by updating altair_viewer:
>     pip install -U altair_viewer
> ```

_Originally posted by @mattijn in https://github.com/altair-viz/altair/discussions/2599#discussioncomment-4491696_

**Comment by joelostblom** [comment]
Is there any functionality from altair_viewer or altair_saver that we still would like to be usable from altair 5? For altair_saver, I can't think of anything that isn't already covered by vl_convert. Unless I'm missing something, maybe we should add a note to the altair_saver readme that we encourage users to use vl_convert for altair 5 instead?

For altair_viewer, we don't yet have a way to support the [display/show](https://github.com/altair-viz/altair_viewer/blob/dfcfb118e38bba31e2a2564772efd6d7827e2d5d/altair_viewer/_viewer.py#L235-L282) functionality in altair 5. I wonder if we can lift out the browser opening logic from altair_viewer directly into altair and rely on vl_convert to display the chart in a browser tab either online or offline mode. @jonmmease Do you think this would be possible?

**Comment by joelostblom** [comment]
From my side of things, those solutions sounds great! I think the most important part of this feature is to enable  an altair workflow from the terminal; it doesn't have to mimic altair saver exactly. I'm in favor of making the behavior easy to implement/maintain and I don't see a noticeable advantage of reusing the same tab (and if someone really wants to, they could write a chart to file and have that filepath open in a single tab that they refresh). You plotly solution sounds like a good approach to me as well.

**Comment by stefaneidelloth** [comment]
If you include save/export options in altair, you might want to support *.pdf as well. 
https://github.com/altair-viz/altair/issues/2612
In matplotlib a corresponding command would be chart.savefig(file_path, ...)
https://matplotlib.org/stable/api/_as_gen/matplotlib.pyplot.savefig.html

**Comment by jonmmease** [comment]
Hi @stefaneidelloth, PDF export is supported using `chart.save("fig.pdf")`. Starting in Altair 5.2.0, this is now based on [vl-convert] rather than altair_saver. vl-convert has no external dependencies on selenium, node.js, or a web browser, so it's a lot less complex to use.

**Comment by joelostblom** [comment]
I'm closing this since Altair 5.2 brought in PDF export and mentioned above, and since Altair 5.3 the functionality of Altair Viewer is now available in Altair via the [vl-convert](https://github.com/vega/vl-convert) package instead. See [the docs on how to use the browser renderer](https://altair-viz.github.io/user_guide/display_frontends.html#browser-renderer) to display charts via `.show()`, and the PR https://github.com/altair-viz/altair/pull/3379 for more details. I believe that means all the functionality from `altair_viewer` and `altair_saver` are now completely covered by `altair` + `vl-convert`.

Immense thanks to @jonmmease for all your work on `vl-convert` making it simpler to both save and display altair charts!
