### ISSUE TITLE
Altair Crashes on ~700,000 rows of data

### ISSUE THREAD

**Issue by pgensler** [altair-viz/altair#287]
Just wanted to say thank you so much for creating such an easy to use API, it is truly a joy to use as a new python user transition from Excel to the python universe.

Not sure if this is a small dataset or not, but Altair seems to crash when I try to do a very simple graph with the dataset. I have the following code in my jupyter notebook:

```
import pandas as pd
import numpy as np
import altair
from altair import Chart, X, Y, Axis, SortField
from altair.datasets import list_datasets, load_dataset

#Read in Data from URL
streetcheck = pd.read_csv('http://daniels-pull.universityofdenv.netdna-cdn.com/assets/GeneralOccurrencesAll.csv', error_bad_lines=False)

#Simple Bar Graph
chart = Chart(generaloccurances).mark_bar().encode(
    x='UCR_Group',
    y='sum(RIN)',
)
chart

```

Seems like the notebook does not even render a error message, but either outputs nothing, or the notebook crashes. Is this too much data for Altair to support, or is this more of a vega-lite limitation?

The chart seems to render fine up to 300,000 rows, but 400-500k rows seems like where the notebook starts to crash. Granted, this file is 600,000 rows, so I think this is sizeable for some.

```
#Create a Bar Chart with Altair
c = Chart(generaloccurances.head(400000)).mark_bar().encode(
    x=X('UCR_Group', sort =SortField(field='UCR_Group', order ='descending', op='sum'),
        axis=Axis(title='Project')),
    y=Y('sum(RIN)',
        axis=Axis(title='2014 Budget')))

c
```

It would be really helpful to have some more documentation on the aggregate functions, and which ones are currently supported in Altair (sum,count, avg, etc..). Let me know however I can help with this!

**Comment by jakevdp** [comment]
Hi – glad for the feedback!

Regarding large data: with the standard use, Altair embeds the full dataset as a JSON output within the notebook, and this can cause run-time issues with larger datasets. There's a [section in the FAQ](https://altair-viz.github.io/faq.html#id3) that talks about this: the best alternative is to save the data as a CSV and then reference it by URL. There's some further discussion of this at https://github.com/altair-viz/altair/issues/249.

Regarding the aggregations: the available options are listed in the [Binning and Aggregation](https://altair-viz.github.io/documentation/encoding.html#binning-and-aggregation) section of the narrative docs; you can also see them within the appropriate class docstrings:

```
In [1]: from altair.api import AggregateOp

In [2]: AggregateOp?
Init signature: AggregateOp(default_value=traitlets.Undefined, **metadata)
Docstring:      One of ['values', 'count', 'valid', 'missing', 'distinct', 'sum', 'mean', 'average', 'variance', 'variancep', 'stdev', 'stdevp', 'median', 'q1', 'q3', 'modeskew', 'min', 'max', 'argmin', 'argmax']
```
