### ISSUE TITLE
"Open in Vega Editor" does not work in VS Code Notebooks

### ISSUE THREAD

**Issue by JannisKoeksel** [altair-viz/altair#2875]
The actions View Source, View Compiled Vega and Open in Vega Editor provided next to the plot do not work in VS Code. 
The links redirect to the top of the notebook, so I'm guessing the event handlers do not work as intended.
I am using Version 4.2.2.

**Comment by mattijn** [comment]
Thanks for raising @JannisKoeksel! I noticed the same. Are you able to figure out why this is not working? Is there documentation by MS VSCode that can support this issue how we could improve this?

**Comment by ChristopherDavisUCI** [comment]
Does this look related? https://github.com/microsoft/vscode-jupyter/issues/11294

**Comment by JannisKoeksel** [comment]
So there are two problems: 
1) Opening links from VS Code via window.open does not work. I have not found any documentation about this, but all my attempts have failed.
2) Vega Editor gets its definition via window.postMessage 

Problem one could be solved by by e.g. using ipywidgets.widgets.Button and displaying them instead of the vega-embed actions. Then using python webbrowser to open a new tab.
Although I personally find the widgets aesthetically unpleasing they should work for "View Source" and "View Compiled Vega".

Regarding the second issue, the only viable solution I can think of is to dynamically write a html file or use data: base64 encoding with the definition and embedding vega editor as an iframe. Then the postMessage mechanism should work again. 
There seams to be an issue with opening data-links and vscode-remote-links thought.  And I have not found a solution that does not include running a server on the remote host or syncing files. 
Sadly I am not very familiar with the internals of VS Code so best I can do is guessing.

@ChristopherDavisUCI yes is seams to be the same issue.  I would really like to use this feature so disabling it is my least favorite solution.

**Comment by ChristopherDavisUCI** [comment]
This definitely seems worth looking into.

As a not-very-satisfying workaround, do you know about `c.to_json()` or `print(c.to_json())` or `pprint(c.to_json())`, where `c` is the Altair Chart?  That should produce something that can be pasted into the Vega Editor.

**Comment by JannisKoeksel** [comment]
No I wasn't aware, but  `print(c.to_json())`  works for me. For my use case the extra steps required aren't to bad either.

**Comment by joelostblom** [comment]
I opened https://github.com/microsoft/vscode-jupyter/issues/13261 where we can continue this discussion. Since it is an issue with VS Code and not with Altair, I will close this issue.
