### ISSUE TITLE
Repeated values in date axis

### ISSUE THREAD

**Issue by lucasbalponti** [altair-viz/altair#2876]
Hello guys!

I'm trying to make a bar graph which has its X axis's type as time. I formatted it using 'utcyearmonth', but the X axis's label repeats values.

Is it a bug? Is there a way to solve it?

[This is what happens to the graph](https://i.stack.imgur.com/z5qoX.png)

The code I've written is:

```
serie_temporal = alt.Chart(base_filtrada).mark_bar(size=60).encode(
    x=alt.X(
        'utcyearmonth(Data):T', 
        axis=alt.Axis(format="%Y %B"),
        scale = alt.Scale(nice={'interval': 'month', 'step': 1})
    ),
    y='sum(Valor):Q',
    color='Tipo de despesa'
).properties(
    height=400
)
```

I already tried changing the axis type from time to nominal, ordinal and quantitative and removing the scale configuration.

Thank you in advance!

**Comment by ChristopherDavisUCI** [comment]
Hi!  It's a little hard to debug for me without seeing the data.  I looked at a few similar examples from the Altair docs and they seemed to use a little different strategy:

* https://altair-viz.github.io/gallery/bump_chart.html
uses `x = alt.X("date:O", timeUnit="yearmonth")`

* https://altair-viz.github.io/gallery/bar_rounded.html
uses `x='month(date):O'`

I would also start without the `axis` and `scale` arguments, just so at first there are fewer parts making adjustments.

Does that help?  If not, can you post an example of the behavior using one of the datasets from `vega_datasets`, like in the gallery examples?

**Comment by lucasbalponti** [comment]
Hi Cristopher,

Your first suggestion solved my problem ( `x='month(date):O'` ):

![How it looks now](https://user-images.githubusercontent.com/122104166/217256371-7a859994-6be9-414d-9481-8de46ec96cc0.png)

Thank you for the precise and quick answer!

**Comment by lucasbalponti** [comment]
Update: i realized that after i made the change, the dates were off by one day.

But then i just transformed the dates to a string, formatted like ISO 8601, added my timezone info, and everything worked perfectly!

![image](https://user-images.githubusercontent.com/122104166/217261507-a538ff7c-9cea-4444-b5eb-317b4baef5bf.png)

**Comment by joelostblom** [comment]
Closing as resolved. Some more info on the off-by-one dates in this issue https://github.com/altair-viz/altair/issues/2540
