### ISSUE TITLE
Altair + ipywidgets

### ISSUE THREAD

**Issue by SylvainCorlay** [altair-viz/altair#290]
Now that we have a proper way to render widgets on 

- [RTD](http://ipywidgets.readthedocs.io/en/latest/examples/Widget%20List.html) 

and

- [nbviewer](http://nbviewer.jupyter.org/github/ipython/ipywidgets/blob/master/docs/source/examples/Widget%20List.ipynb)

It would be interesting to make an altair widget instead of only using a custom mime type in the output. 

The benefit would be that we would be able to lay out altair charts with other widgets.

**Comment by gnestor** [comment]
I'm sure you've seen this, but if not: https://github.com/altair-viz/altair_widgets

Are you proposing that ipywidgets provide an altair widget or that altair provide an altair widget?

**Comment by SylvainCorlay** [comment]
I am proposing that altair charts can **be** jupyter widgets.

**Comment by ellisonbg** [comment]
Eventually I would like to see regular MIME output and widgets supported.

**Comment by ellisonbg** [comment]
I think the direction to go with this is to have a Vega-Lite rendering widget that is simple and only has data and spec attributes. The difficulty is that the Vega-Lite JS API doesn't have a fine grained JS API that allows you to update things dynamically. But a basic widget like that would be great.

**Comment by choldgraf** [comment]
Hey all - just wondering if there's been any movement on this front? I've been playing around more with Altair and think it's awesome! It would be even more awesome if this could play nicely with the Jupyter Widgets ecosystem, rather than requiring to use one or the other (e.g. make a dropdown in jupyter widgets that, when clicked, changes something in an altair chart)

**Comment by jakevdp** [comment]
> make a dropdown in jupyter widgets that, when clicked, changes something in an altair chart

That would maybe be possible, but it's more of a Vega-Lite question than an Altair question. All Altair does is create JSON specifications that are rendered by the vega javascript stack: Altair itself contains no javascript.

**Comment by choldgraf** [comment]
@jakevdp good to know, thx!

**Comment by joelostblom** [comment]
It is now possible to use the `JupyterChart` class to create Altair charts that can interact with jupyter/ipywidgets directly. See this section in the docs for details https://altair-viz.github.io/user_guide/jupyter_chart.html
