### ISSUE TITLE
PR tests should fail if generate_schema_wrapper produces changes

### ISSUE THREAD

**Issue by binste** [altair-viz/altair#2906]
Altair has many files which are auto-generated based on the Vega-Lite schema. For development, it is often convenient to modify those directly but before merging into master, these changes need to be applied to the relevant scripts in the `tools` folder which is a step that is easy to forget.

It would be great if the tests for a PR fail if changes were applied to auto-generated files. One way could be to add a new step in [build.yml](https://github.com/altair-viz/altair/blob/ef8ff946bf610c19ccbecfbbd6b624004c25fb32/.github/workflows/build.yml) which runs `python tools/generate_schema_wrapper.py` and then checks if any files were changed with `git ls-files --modified`.

**Comment by joelostblom** [comment]
This sounds like a good idea and will make it easier to keep track of which files need changes.

**Comment by binste** [comment]
Great, I will create a PR for this.
