### ISSUE TITLE
is there a way to create a Chart object and pass a 'null' element to an argument?

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#291]
I'd like to create several different charts with similar parameters. So I do it like this:

```
chart = {}
for plot in ['A', 'B', 'C', 'D']:
  chart[plot] = Chart(df).mark_point().encode( ...
```

Then I want to customize one particular bit of each `plot` for each pass through that loop. I can do that with ternary operators (kludgey):

```
title = '%sSpeedup' % ('Normalized ' if (plot == 'A') else '')
```

or I can make a dict:

```
titledict = {
  'A' : 'Normalized Speedup',
  'B' : 'Speedup', ...
```

and then say `title=titledict[plot]`.

What I don't know how to do is to _not_ pass an argument to `Chart`. For instance, if I wanted plots A, B, and C to set shape, I would call the `Chart` constructor with `shape=Shape( ... )`. But if I _didn't_ want plot D to set the shape, is there anything I can pass to `shape=` to tell it "no, I really didn't mean to set Shape", something like `shape=null`?

(What I'm trying to avoid is writing the same `Chart` constructor _n_ times with only tiny changes between those _n_ times.)

**Comment by jowens** [comment]
(I imagine this would be possible if it's possible to add elements to a plot after it is constructed, e.g., `chart = chart.addShape(Shape( ... ))`.)

**Comment by jakevdp** [comment]
The semantics of null values in Vega-Lite has been not well defined, and so we've not provided any interface to them in Altair. But in discussions with the developers it sounds like this will change in Vega-Lite 2.0, so I imagine we'll be putting thought into null values in Altair 2.0.

Also, yes it's possible to modify a chart after it's created. For example,

```python
chart = Chart().encode(x='col1')

chart.encode(x='col2')
```

**Comment by jowens** [comment]
Oh, awesome, this'll help. Thanks!

**Comment by jowens** [comment]
And just to follow up, is there a way to do:

```
chart = Chart().encode(x='col1')

chart.encode(x=null)
```

Your solution can both change `x` from one thing to another or add a new `x` where there wasn't one before, but can you _remove_ an `x` that's in the current Chart object? (I understand if it's "no, because the semantics of null values is not yet well-defined".)

**Comment by jakevdp** [comment]
No, there's no way to pass nulls currently, because the semantics of nulls in Vega-Lite is not well-defined in the current version.

**Comment by jakevdp** [comment]
If you want to remove an encoding, you can do ``chart.encode(x=None)`` but this will not result in a null value being passed to the JSON serialization.

**Comment by jowens** [comment]
I'm just asking to be able to have a chart and make incremental changes to it to make a new chart, which might include, say, "remove the row encoding". Sounds like the `chart.encode(row=None)` is what I want. Awesome!

**Comment by jakevdp** [comment]
Great!

**Comment by jowens** [comment]
@jakevdp can I follow back up on this? Consider:

```
import altair as alt

# to use with Jupyter notebook (not JupyterLab) run the following
# alt.renderers.enable('notebook')

# load a simple dataset as a pandas DataFrame
from vega_datasets import data
cars = data.cars()

chart = alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
)
chart2 = chart.encode(color=None)
```

I'd like to remove `color` from `chart` entirely. Not sure if that's what you meant by "remove an encoding". Anyway, this does not appear to work in python3 / altair4.

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-d556f21dee7e> in <module>
     13     color='Origin',
     14 )
---> 15 chart2 = chart.encode(color=None)

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/altair/vegalite/v4/api.py in encode(self, *args, **kwargs)
   1569     def encode(self, *args, **kwargs):
   1570         # Convert args to kwargs based on their types.
-> 1571         kwargs = utils.infer_encoding_types(args, kwargs, channels)
   1572 
   1573         # get a copy of the dict representation of the previous encoding

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/altair/utils/core.py in infer_encoding_types(args, kwargs, channels)
    561 
    562     return {encoding: _wrap_in_channel_class(obj, encoding)
--> 563             for encoding, obj in kwargs.items()}

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/altair/utils/core.py in <dictcomp>(.0)
    561 
    562     return {encoding: _wrap_in_channel_class(obj, encoding)
--> 563             for encoding, obj in kwargs.items()}

/opt/local/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/altair/utils/core.py in _wrap_in_channel_class(obj, encoding)
    550 
    551         classes = name_to_channel[encoding]
--> 552         cls = classes['value'] if 'value' in obj else classes['field']
    553 
    554         try:

TypeError: argument of type 'NoneType' is not iterable
```

**Comment by jakevdp** [comment]
This is correct: ``None`` is equivalent to the JSON ``null`` value, and ``null`` is not a valid value for an encoding according to the vega-lite schema.

Altair currently does not provide any sentinel value that means "remove the existing value of this from the chart".

We cannot use ``None`` as a placeholder meaning undefined, because ``null`` has meaning in some places (e.g. setting the legend to null is how you specify that the legend should be hidden).

We could possibly special-case things on the Altair side so that None values passed to fields that are not allowed to be null silently result in the field being ignored, but that strikes me as potentially very confusing for users.

If you have suggestions for how to syntactically represent removing a field, please let me know... in the meantime, I'd suggest rearranging your chart construction so that it's additive, not subtractive.
