### ISSUE TITLE
Basic example in documentation shouldn't link to advanced usage as preread

### ISSUE THREAD

**Issue by dylancashman** [altair-viz/altair#2911]
A documentation bug IMO: The *Basic Statistical Visualization* page in the *Getting Started* section of the documentation lists as a preread the *Displaying Altair Plots* page, which is in the *Advanced Usage* section of the documentation.  

> First, you will need to make sure you have the Altair package and its dependencies installed (see [Installation](https://altair-viz.github.io/getting_started/installation.html#installation)) and make sure you understand how altair plots are displayed (see [Displaying Altair Charts](https://altair-viz.github.io/user_guide/display_frontends.html#displaying-charts)).

I think this is a bit misleading and could turn people off of trying out Altair - they'll go to the first example, click the preread, and see it's advanced usage and step away.

I think the wording should be changed so that the display frontends section is optional - "read *Displaying Altair Plots* if you aren't using jupyter as a backend", something like that.

**Comment by joelostblom** [comment]
Thanks for pointing this out, they suggest a change sounds like a good idea to me. Would you like to open a pull request?

**Comment by dylancashman** [comment]
Created the pull request: https://github.com/altair-viz/altair/pull/2925

**Comment by joelostblom** [comment]
closed in #2925
