### ISSUE TITLE
Install altair version 5 candidate 

### ISSUE THREAD

**Issue by rcolpo** [altair-viz/altair#2917]
Hello,

I'm trying to install Altair v5 with "pip install altair==5.0.0rc1" (got the command from [here](https://binste.github.io/altair-docs/gallery/grouped_bar_chart2.html)), but I have an error from pip:

`ERROR: Could not find a version that satisfies the requirement altair==5.0.0rc1 (from versions: 1.0.0rc1, 1.0.0rc2, 1.0.0rc3, 1.0.0rc4, 1.0.0, 1.2.0, 1.2.1, 2.0.0rc1, 2.0.0rc2, 2.0.0, 2.0.1, 2.1.0, 2.2.0, 2.2.1, 2.2.2, 2.3.0, 2.4.1, 3.0.0rc1, 3.0.0, 3.0.1, 3.1.0, 3.2.0, 3.3.0, 4.0.0, 4.0.1, 4.1.0, 4.2.0rc1, 4.2.0, 4.2.1, 4.2.2) 
ERROR: No matching distribution found for altair==5.0.0rc1"`

I want to install the new version to check if it can help me to make [a graph that I described in StackOverflow](https://stackoverflow.com/questions/75522071/altair-plot-using-facet-column-and-shaded-area?noredirect=1#comment133253029_75522071). 

I'm using python 3.11 and pip 23.0.1.

**Comment by mattijn** [comment]
not released yet

**Comment by joelostblom** [comment]
@rcolpo There is now a release candidate of Altair 5, which supports Vega-Lite 5! Details and info on how to install can be found  in https://github.com/altair-viz/altair/issues/2937
