### ISSUE TITLE
Strange behavior (no datasets) when using .to_html from streamlit

### ISSUE THREAD

**Issue by arogozhnikov** [altair-viz/altair#2919]
Chasing a very strange bug that appeared recently, and I see no simple way to minimally reproduce it.

Altair is used within streamlit app.

There are two ways to output altair plot in streamlit.

1. built-in (st.altair_plot) - this works normally
2. using export to html, and then showing with st.components.v1.html   
     I use this second method in some cases, because streamlit uses old vega, and does not support some features.
    Rendered plots shown in this way are each shown in a separate iframe.

Starting from some moment, **all** plots generated with method 2, are not shown, all they look empty:

<img width="400" alt="Screenshot 2023-02-22 at 8 51 35 PM" src="https://user-images.githubusercontent.com/6318811/220823818-34727409-5e21-4e50-963d-6174635dd6a9.png">

Redeploying the app helps for a while. 
So it looks like something changes within altair at some point.
(FYI streamlit uses long-living python processes, so there is no 'reimporting' after app was started)

Looking at generated html, there are **no datasets within spec.**, but I am not sure where to go from here 

[vega editor link](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAFgAY2AacaYsiygAlMiRoRQBmDgF9p3ADYBDAJ6YATigDaoALaK1AaxQg1mMOO6YokOiSSoe8iBofxM8uschO1AfXogCpgIVp7IZPLy3JRgivKYeCB0EHokWlwAjJwATJwSnCycAKycAGycAOycABycAJwAutxqilAhWiAAxIpFGQBG-YFdfTAZozBDnXR12RKzk3QwEn3Lk5gSRZtFkxJ0PYPcnSwVI2OTvdPzh6Usi6uHFdXrmyANciDEhPFeED5DhMoAA4JZAgKApEhxEDvQgQX7EQFaUBuDzGbDueT-IEgsEQqBQ6RNEAAD0SKLCjixwOM4J0kMx72UZKwqNBagguG4AOpoNp9Ohsk4un0Rgc3JxhEwxIsID6iko7hIEogiO4dCZyAAtNkKu8rDY7IlJdLme4KcbCL5KID5HAZeKaXiCVy4fIEUiQOS0RiqTi+fiGUTSa4WRTvL7HXSA9DuBrkaHjOzOR9sZH+bJCWrFIRFIl8TocRl2Bk6o9ShI6nVqpXsjGQIwRAgxJJSlwQNh6EwUBkMhxuAASGINvTGMSEQGUZAAeinaGCigAdAg7YxSH0F3AIFOh5g9LP55rbZLZywFxkKgu2AuAFaUaDQoA)

Env: ubuntu 20.04
Python 3.10
Altair: 4.2.0 and 4.2.2 both affected

**Comment by mattijn** [comment]
Seems not Altair related. Ask streamlit repo?

**Comment by arogozhnikov** [comment]
it has to be altair, because streamlit-based rendering still working.

**Comment by mattijn** [comment]
So give me please a code snippet without usage of streamlit that reproduces the issue you are facing.

**Comment by arogozhnikov** [comment]
can you please help me with this: 

- altair's .to_html() generates broken output by not including datasets. 
- This is a switch-style behavior that happens at some event. 
- Where this behavior can originate from?

**Comment by ChristopherDavisUCI** [comment]
The only idea I have is to maybe add some print statements to display the keyword arguments here https://github.com/altair-viz/altair/blob/32eb97c2595c21554b61bdff527ffea7347fab57/altair/vegalite/v5/api.py#L591-L612 and see if some of those are randomly getting changed at some point?

I tried calling `to_html` on this chart as an example https://joelostblom.github.io/altair-docs/user_guide/interactions.html#selection-parameters and the data was included.

Sorry for not having anything more helpful.

**Comment by mattijn** [comment]
Try forcing data to be included inline. Maybe streamlit uses `altair_data_server`? See https://github.com/altair-viz/altair_data_server#usage?
```python
alt.data_transformers.enable('default')
```
