### ISSUE TITLE
Multi Series Line Chart with Pivoted DataFrame in wide format

### ISSUE THREAD

**Issue by skabbass1** [altair-viz/altair#292]
Hello,  I have a pivoted DataFrame like the following:

![image](https://cloud.githubusercontent.com/assets/7890526/22400015/dcd07518-e56f-11e6-8bc8-2278253bb4dc.png)

I want to  plot each of the columns as a separate series on  the same chart (With The Date column being the X axis).  Is it possible to do so without first unpivoting the data and converting it into long format by using the pandas melt operation for example? 

Thanks,

Syed

**Comment by skabbass1** [comment]
Seems like its doable through LayeredChart. Wondering if there is a more direct way?

**Comment by kanitw** [comment]
Layered chart is the way to go.  Note that LayeredChart is an experimental feature in Vega-Lite 1 and it will be better supported in Vega-Lite 2.0 beta and full release. 

In the future, Vega-Lite 2.x (probably not 2.0) may likely include better "repeat" syntax for layered chart as discussed briefly here https://github.com/vega/vega-lite/issues/1274.

**Comment by ellisonbg** [comment]
You can also use pandas.melt to bring the relevant column names down into a single column with those names as categorical values and a single value column. Then you can create the different series by encoding that new column as color. This is one of the standard transformations in the creation of a tidy data frame. Hope this helps!

**Comment by alf** [comment]
@kanitw When using layer for this, I'm having issues getting a legend. Without that the result isn't very usable since it's impossible to know which line is which.

**Comment by linzhichu** [comment]
here is an example in Altair's official doc. As @ellisonbg pointed out, the melt() functions is the key
https://altair-viz.github.io/gallery/multiline_tooltip.html
