### ISSUE TITLE
installation fails on Anaconda 4.3.0

### ISSUE THREAD

**Issue by mileskrains** [altair-viz/altair#293]
```
~ $conda install altair --channel conda-forge
```

yields:

```
UnsatisfiableError: The following specifications were found to be in conflict:
  - altair -> python 2.7*
  - python 3.6*
Use "conda info <package>" to see the dependencies for each package.
```

**Comment by jakevdp** [comment]
Since Python 3.6 has only been supported by Anaconda for about 24 hours, we have not yet done builds on conda-forge for python 3.6. Until that happens, you can install Altair on Python 3.6 using pip: instructions are listed on the installation page.

**Comment by mileskrains** [comment]
Thanks, should've read / tried more ...

**Comment by afonit** [comment]
Could this issue be reopened now?

**Comment by jakevdp** [comment]
Once [this PR](https://github.com/conda-forge/altair-feedstock/pull/4) is merged, py36 should work.
