### ISSUE TITLE
Altair 5 release candidate info and feedback

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#2937]
Thanks for your interest in the release candidate for Vega-Altair 5!

If you have any general feedback on the direction of the release candidate, please feel free to share it here (e.g. on [the new method-based syntax for setting encoding channel options](https://altair-viz.github.io/user_guide/encodings/index.html#alternative-syntax-for-channel-options)). If you run into specific problems, please open individual issues for those.

Before you get started, make sure that you read the [release notes](https://altair-viz.github.io/releases/changes.html) to see what has changed and take a tour of the revamped documentation pages to learn more about the new features.

---

Please take note of the following limitations present in the release candidate, which we are working to resolve before the official release of Altair 5.0.0.

- Downstream dependencies such as `altair_data_saver`, `altair_viewer` and `altair_saver` are not yet ready for Altair 5. If you are dependent on these, please wait.

You can install the release candidate of version 5 using the following pip-command:
```
pip install altair==5.0.0rc3
```

**Comment by firasm** [comment]
This is very exciting!! Thank you to everyone involved 🥳🥳🤩🤩

**Comment by philippjfr** [comment]
Great work on this! One quick question, what's the timeline for the release? We're going to push out a Panel 0.14.4 patch release with compatibility for selections with older and newer vega-lite/altair versions. I'd like to show the new altair API (`.add_params`) in the docs but if it's a few weeks out I'd probably postpone the docs update.

**Comment by mattijn** [comment]
Its not fixed, but a few weeks sounds likely.

**Comment by philippjfr** [comment]
Thank you, might hold off on the documentation updates for now then.

**Comment by AdamCiuris** [comment]
thank you for docs additions

**Comment by joelostblom** [comment]
Closing this as we have released v5!
