### ISSUE TITLE
why is default line chart sorted by -x?

### ISSUE THREAD

**Issue by kepingwang** [altair-viz/altair#295]
With this data:
```
data = np.array([
        [0,0],
        [0.4,0.4],
        [0.4,0.5],
        [1.0,1.0]
    ])
df = pd.DataFrame(data, columns=['x','y'])
```
The line chart plotted is:
```
Chart(df).mark_line().encode(x="x",y="y")
```
![vega](https://cloud.githubusercontent.com/assets/14341566/22636583/51a619f6-ec0a-11e6-9659-e9e2a65c0df4.png)

The generated Vega-lite code looks like:
```
{
  "data": {
    "values": [
      {"y": 0,"x": 0},
      {"y": 0.4,"x": 0.4},
      {"y": 0.5,"x": 0.4},
      {"y": 1,"x": 1}
    ]
  },
  "encoding": {
    "y": {"field": "y","type": "quantitative"},
    "x": {"field": "x","type": "quantitative"}
  },
  "config": {"cell": {"width": 500,"height": 350}},
  "mark": "line"
}
```

Then I notice that in the compiled Vega code:
```
      "marks": [
        {
          "name": "marks",
          "type": "line",
          "from": {
            "data": "source",
            "transform": [{"type": "sort","by": "-x"}]
          },
          "properties": {
            "update": {
              "x": {"scale": "x","field": "x"},
              "y": {"scale": "y","field": "y"},
              "strokeWidth": {"value": 2},
              "stroke": {"value": "#4682b4"}
            }
          }
        }
      ],
```
there is a transformation of the original data, which sorts it by "-x".

Right now I have to specify the path in altair encoding() explicitly to make it work.  

This is weird to me. Is it something you designed intentionally or just a bug? Thanks.

**Comment by kanitw** [comment]
We sort by -x by default so that users don't have to sort the values manually.  

In general, line chart should not have duplicate values for x anyway.  Thus, in your case it is unclear what users want unless you specify the path channel.
