### ISSUE TITLE
Interactive Crossfilter gallery example broken with Altair 5.0.0rc1

### ISSUE THREAD

**Issue by jonmmease** [altair-viz/altair#2978]
While digging into https://github.com/hex-inc/vegafusion/issues/267, I found that there's a regression in the [Interactive Crossfilter](https://altair-viz.github.io/gallery/interactive_layered_crossfilter.html) gallery example with Altair 5.

If you make a selection on the distance subplot, the bars for the distance and delayed subplots disappear.

<img width="939" alt="Screenshot 2023-03-20 at 9 28 06 AM" src="https://user-images.githubusercontent.com/15064365/226354210-3189261a-01d9-482f-985c-0a3215fa29c2.png">

This works as expected in the Altair 4 gallery: https://altair-viz.github.io/altair-viz-v4/gallery/interactive_layered_crossfilter.html

<img width="766" alt="Screenshot 2023-03-20 at 9 30 56 AM" src="https://user-images.githubusercontent.com/15064365/226354908-aeb2a763-7665-4c16-95e0-6187cfa39ee4.png">

I haven't dug into whether this is an Altair or Vega-Lite issue, but wanted to bring it up ASAP, since it's probably something we need to get worked out before the final release of Altair 5.

**Comment by jonmmease** [comment]
When I click "Open in Vega Editor" from the Altair 5 example, it behaves correctly in the Vega editor 🤔 

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO4AnTAAdMAQ3GoeAG1IBbKCgDaIOnEqFlUMJhDc6mDcoCe1kMW1WAujJCUlYPCHsHTFkDUG1lWQBrf0IHJRQQACMIkC9MCwhjKCR1SA0IEPU0ZS0rZBAAYjpq1O4AD39Ekn9wuqaoShQAJjYveDs6f3klVQS8nT0vWPjygEdSc2IzYjQrLyd1ZQQEeQRVMp5SImdpg-nFuGW4VdSvKGU3BIwcAH0ADlqwiOj1U4TkkJpDJZHKgBrqdotZRtEidZA9PpYDSDdTDFRqTQTWouOJnBZES6qa5rbgbUBbHaYPaEA6QI7ibh-Ob4pZEm7SRmycyUGAFbShEDwDQ0wqgBQRB4JcVc7TvW6edw2VTKfykWQaBJiQgKSjIAD0erAdCgADoAFaUWwaa6yE1QTCEPVQBTaPWrPYAWjoysoDsoAAE0ABGE1dACcJrYeu9Zj1MGtCDElA9XUi5so0GcvNk4TUYoivv8MYOxduXkYIkTaiD7E53Oz-OQ+nwJTApHsNM1FFklAAFDGdCbiwBKZzKOEuOCPSSKkDYehMFBBgBsvW40oecObIHuj3KG9lH24vo0mDAeZxMxAJBFxQ13HSkBBW5ADU83Ge2Bfn7lCu4ABJKDACtwk1QhtV1A13WUE0EEuRhSESE04AgPUgJA5Q3SpZQPWtGk3QAVhNZcTRDC1M0kIA)

The editor says it's on Vega 5.24.0 and Vega-Lite 5.6.1, which I think are the same versions as Altair.

**Comment by jonmmease** [comment]
Huh, even on initial render, the x-axes are messed up. All three x-axis have the same labels, 0 to 24, which is only appropriate for the "time (binned)" subplot.

![Screenshot 2023-03-20 at 9 46 38 AM](https://user-images.githubusercontent.com/15064365/226358895-9128abe0-5e9a-4681-b4f8-782b69e083d0.png)

**Comment by joelostblom** [comment]
I see the behavior in the Vega Editor as well, when generating the example from either altair 5 or 4 (but I don't think the "schema" version specification takes effect in the vega editor if I remember correctly, so we are only seeing the behavior of the latest vega-lite, but at least this suggests that the weirdness is not introduced in altair 5)

It seems like adding the brush to the spec of a layered, repeated chart is causing the limits of the encoding channels specified in the brush to be shared and set to that of the last chart in the repeat. Here is a smaller example to reproduce:

```py
import altair as alt
from vega_datasets import data

source = data.flights_2k.url

brush = alt.selection_interval(encodings=['x'])

alt.layer(
    alt.Chart(source).mark_bar().encode(
        x=alt.X(alt.repeat('column'), type='quantitative'),
        y='count()'
    ).add_params(brush),  # Comment this line to make the x-axes max limits independent and working as expected
).repeat(column=["distance", "delay"])
```

![image](https://user-images.githubusercontent.com/4560057/226403940-3e9438ea-b8da-4a90-ab6a-871b2f3b773b.png)


This is the right chart after removing the brush 

![image](https://user-images.githubusercontent.com/4560057/226404018-5ee606c3-ee81-496e-bfe5-1a971eebb5b1.png)

**Comment by mattijn** [comment]
This is raised in https://github.com/vega/vega-lite/issues/8348 and (one of) the reason why Altair v5 is not yet released.
Luckily this is recently fixed upstream in VL master but it is unfortunately not yet released.

**Comment by mattijn** [comment]
Tracked in Altair through https://github.com/altair-viz/altair/issues/2849
