### ISSUE TITLE
unexpected filter behavior

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#298]
In my Chart constructor I have the following chunk of code:

```
    ).transform_data(
        filter=((expr.df.algorithm != 'DOBFS') or
                (expr.df.idempotent == False))
    )
```

It was unexpected to me that this resulted in the following in the output JSON:

`"transform": {"filter": "(datum.algorithm!='DOBFS')"},`

**Comment by afonit** [comment]
Perhaps this?  works in my example I have:

 filter=(['datum.countof >= 50000', 'datum.countof <= 60000'])

then shows up in the json as:
 "transform": {
    "filter": [
      "datum.countof >= 50000",
      "datum.countof <= 60000"
    ]

**Comment by jowens** [comment]
@afonit First, thank you, but I would expect what you've done would be a logical-and rather than what I need, which is logical-or.

**Comment by kanitw** [comment]
Haven't checked myself, but I guess

`filter=(["datum.algorithm != 'DOBFS' || datum.idempotent == false"])`

might work  as a workaround for now? (You might not even need `[` and `]`.)

**Comment by afonit** [comment]
@kanitw 
Humm, I tried each of those and none worked.

@jowens wondering if they work for you.

Looking in the code these are three filter tyepes:
EqualFilter,
RangeFilter,
OneOfFilter,

Looks like the or is not a type?  I will keep reading and see what I can see.

**Comment by kanitw** [comment]
There is no "OrFilter" in VL but you can manually do `filter: "datum.algorithm != 'DOBFS' || datum.idempotent == false"` in Vega-Lite.  Not sure why it doesn't work for Altair.

**Comment by jakevdp** [comment]
You need to use Python's logical or statement:

```
filter=((expr.df.algorithm != 'DOBFS') |
                (expr.df.idempotent == False))
    )
```

The reason it doesn't work as you wrote it is that Python's ``or`` statement cannot be overridden, and always returns the first variable it encounters that evaluates to ``True`` in a Python sense.

**Comment by jowens** [comment]
Thanks mucho. Might be worth a line in the Altair docs (these are the operators you might want to use, these are the operators you definitely don't want to use).

**Comment by jakevdp** [comment]
Yeah, the docs need a lot of work, but I've been holding off on that until the Vega-Lite 2.0 release, because so much is going to change.

**Comment by jowens** [comment]
Here's my filter command:

```
        filter=((expr.df.algorithm != 'DOBFS') |
                (expr.df.idempotent == False))
```

but vg2svg did not like it:

```
[Vega Err] PARSE DATA FAILED: source Error: Unknown signal "False"
[Vega Err] Error: Unknown signal "False"
[Vega Err] Error: Unknown signal "False"
/Users/jowens/Documents/working/vega/bin/vg2svg:66
```

In the JSON dump, `idempotence` is `true` or `false`, not `True` or `False`. Is that the problem?

One interesting bit is that the no-data JSON ends up with `||` for the or operator in its filter:

```
{'mark': 'point', 'transform': {'filter': u"((datum.algorithm!='DOBFS')||(datum.idempotent==False))"}, 'encoding': {'y': {'field': u'm_teps', 'type': 'quantitative', 'axis': {'title': u'MTEPS'}}, 'color': {'field': u'[gpuinfo.name]', 'type': 'nominal', 'legend': {'title': u'GPU'}}, 'shape': {'field': u'scalability', 'type': 'nominal', 'legend': {'title': u'Scalability Type'}}, 'x': {'field': u'num_gpus', 'type': 'nominal', 'axis': {'title': u'Number of GPUs'}}}}
```

**Comment by jakevdp** [comment]
You are filtering based on the Boolean value ``False``, which is a Python value that cannot be translated to vega-lite. You need to filter based on the values that are in your column, which are (I suspect) strings. Try ``expr.df.idempotent == "false"``

**Comment by jakevdp** [comment]
And yes, the Python operator ``|`` is translated to the javascript operator ``||`` for the JSON output, because that's what Vega expects.

Hope that helps,

**Comment by jowens** [comment]
The values actually in the column are JSON boolean values (true and false), not strings, so the string `"false"` doesn't work.

**Comment by jakevdp** [comment]
Huh... I actually had no idea that booleans were valid JSON. Altair can't handle that currently, as far as I know.

**Comment by jakevdp** [comment]
That would be a great contribution :smile:

**Comment by jowens** [comment]
I must be honest and say that you should not hold your breath waiting for a pull request from me. Sorry.

**Comment by jakevdp** [comment]
No worries :smile: #302 should fix this issue
