### ISSUE TITLE
Add VL example 'Bar Chart Highlighting Values beyond a Threshold' to gallery

### ISSUE THREAD

**Issue by binste** [altair-viz/altair#2996]
I find https://vega.github.io/vega-lite/examples/layer_bar_annotations.html an interesting example which could be added to the Altair Example Gallery:

<img width="395" alt="image" src="https://user-images.githubusercontent.com/23366411/227784506-cc33eddf-948e-4800-a2ae-5fb12907a5f3.png">

I already started [in this comment](https://github.com/altair-viz/altair/issues/2915#issuecomment-1484121673) but the code needs to be cleaned up a bit.

**Comment by mattijn** [comment]
Related: https://github.com/altair-viz/altair/pull/1109#issuecomment-1475015880
