### ISSUE TITLE
encoding Column conditional on another Column

### ISSUE THREAD

**Issue by aavanian** [altair-viz/altair#300]
Assuming a DataFrame with columns ```[Date, Type, Value]``` with ```Type``` being ```Categorical``` and ```Value``` being ```Quantitative```. Is there a way to pass that DataFrame to Altair for a scatter plot and encode on x: ```Value``` conditional on ```Type == Type1``` and on y ```Value``` conditionnal on ```Type == Type2```?

Or the DataFrame needs to be preprocessed to have columns: ```[Date, ValueType1, ValueType2]```?

**Comment by jakevdp** [comment]
No, you can't do that kind of operation in Altair. It assumes that data are in a tidy format, where rows correspond to objects and columns correspond to measurements. I'd suggest using pandas to preprocess your data if it's not in this format.

**Comment by aavanian** [comment]
Ok, thanks for the answer. I read the pdf mentioned in the Readme and it seems there's basically two ways to tidy the data. 

To confirm I'm not missing any subtlety: let's say I have two time-series ```s1(t)``` and ```s2(t)```.
* If I want to plot the timeseries, I need a dataframe with columns ```(t , label , value)``` where ```label``` will be ```s1``` or ```s2``` and ```value``` contains ```label(t)``` and use ```Chart(df1).mark_line().encode(x='t', y='value', color='label')```
* If I want to plot the scatter ```(s1(t), s2(t))```, I need a dataframe with columns ```(t, s1, s2)``` and use ```Chart(df2).mark_circle().encode(x='s1', y='s2', color='t')```

And there is no way to plot both charts from the same dataframe.

**Comment by jakevdp** [comment]
There's a third option: if you have [t, s1, s2] you can do a layered chart to plot t vs s1 and t vs s2 on the same chart. Layered charts are only partially supported in the current release, but will have full support in the 2.0 release.

**Comment by aavanian** [comment]
Ok, thanks

PS: I really appreciate Altair's design.
