### ISSUE TITLE
module 'altair' has no attribute 'param'

### ISSUE THREAD

**Issue by umichhaidn** [altair-viz/altair#3006]
I used to use alt.param() to make selectors for interactive charts, and it's still in the documentation, but now I am getting this error. 

Altair version 4.2.2
Using Google Colab Jupyter Notebook

![image](https://user-images.githubusercontent.com/79999494/228922055-78a74c8b-66ce-4ab5-b649-33a24053b1a9.png)

**Comment by mattijn** [comment]
`alt.param()` is currently only available in the release candidate of Altair version 5.

```python
pip install altair==5.0.0rc1
```
