### ISSUE TITLE
Using transform_regression with method "poly" and order 0 returns 3rd order fit

### ISSUE THREAD

**Issue by thomascamminady** [altair-viz/altair#3012]
I want to use `transform_regression` to fit a constant through my data. My understanding is that I should use `method="poly"` and `order=0`, since a 0th order polynomial is a constant. However, when using `order=0` it seems like `transform_regression` defaults back to `order=3`, at least in the example below (taking from the `altair` examples.)
```python
import numpy as np
import pandas as pd
import altair as alt

# Generate some random data
rng = np.random.RandomState(1)
x = rng.rand(40) ** 2
y = 10 - 1.0 / (x + 0.1) + rng.randn(40)
source = pd.DataFrame({"x": x, "y": y})

# Define the degree of the polynomial fits
degree_list = [0, 1, 5]

base = alt.Chart(source).mark_circle(color="black").encode(alt.X("x"), alt.Y("y"))

polynomial_fit = [
    base.transform_regression(
        "x", "y", method="poly", order=order, as_=["x", str(order)]
    )
    .mark_line()
    .transform_fold([str(order)], as_=["degree", "y"])
    .encode(alt.Color("degree:N"))
    for order in degree_list
]

alt.layer(base, *polynomial_fit)
```
Instead of a constant line for the 0th order polynomial, I get the same fit that I would get for the 3rd order model (which happens to be the default for `order`).

Is this a bug? I think `order=0` is a valid input and should be evaluated as a 0th order polynomial, i.e. a constant function. 

![image](https://user-images.githubusercontent.com/24543638/230366928-72ba90ac-13f8-43bb-b75d-c482c57c1011.jpeg)

**Comment by thomascamminady** [comment]
I also posted this at `vega`: https://github.com/vega/vega/issues/3716

**Comment by domoritz** [comment]
You can close the issue here since it's addressed in Vega.
