### ISSUE TITLE
contributing descriptions for examples is outdated

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#3014]
The documentation for adding examples: https://github.com/altair-viz/altair/blob/master/CONTRIBUTING.md#adding-examples needs updating to reflect changes of current location (examples are in test and not within altair).

Better to wait until https://github.com/altair-viz/altair/pull/3007 is merged to start working on this to avoid potential conflicts.

**Comment by thoemi123** [comment]
In addition to fix this issue,  it would also be worthwhile to think about potential naming conventions when having multiple chart sources, as it would be the case in the example from  https://github.com/altair-viz/altair/pull/3120.  Potentially makes sense to group those changes in the same PR (if there is a need for naming guidelines for multiple sources).
