### ISSUE TITLE
Unable to set width='container' in jupyterlab

### ISSUE THREAD

**Issue by LinuxIsCool** [altair-viz/altair#3019]
Unable to set property width to container as described here: https://altair-viz.github.io/user_guide/customization.html#adjusting-chart-size 

versions:
```
altair==5.0.0rc1
jupyterlab==4.0.0b1
```

```python
alt.Chart(cars).mark_bar().encode(
    x='Origin',
    y='count()',
).properties(
    width='container',
    height=200
)
```

```
Javascript Error: Unrecognized signal name: "container"
This usually means there's a typo in your chart specification. See the javascript console for the full traceback.
```

![image](https://user-images.githubusercontent.com/31582215/232137475-d144ca08-119c-4476-b012-56185adf4af8.png)

**Comment by joelostblom** [comment]
Not sure what is going on. I tested in jupyterlab 3.3.4 and there is no error but the plotly that is displayed is empty.

**Comment by mattijn** [comment]
There is an open PR on the zero-width plot when using `width="container"`: https://github.com/altair-viz/altair/pull/2867#issuecomment-1422429067.

But I think this issue is related to the new v4 beta release of JupyterLab. We have an open issue here to keep an eye on this here: https://github.com/altair-viz/altair/issues/2585#issuecomment-1419820884 because of @ChristopherDavisUCI  his work on this here: https://github.com/jupyterlab/jupyterlab/pull/13893.

Maybe it is also related to this comment and connected discussion https://github.com/jupyterlab/jupyterlab/pull/13893#issuecomment-1417127471.

Can you reproduce this in the v4 beta release of JupyterLab @ChristopherDavisUCI?

**Comment by ChristopherDavisUCI** [comment]
Thanks for reporting this @LinuxIsCool

@mattijn Thanks for pointing this out to me.  I tried running the original code posted [above](https://github.com/altair-viz/altair/issues/3019#issue-1668836937) after `pip install jupyterlab==v4.0.0b0` and `pip install altair==5.0.0rc1` and also got a blank display.

I also tried switching the renderer using `alt.renderers.enable('mimetype')` and JupyterLab (or the web browser tab, it's hard for me to tell the difference) froze.  I tried both Chrome and Safari.

Is this what you had meant for me to try, @mattijn, or did you mean I should try something without the `width="container"` part?

**Comment by mattijn** [comment]
Thanks for checking @ChristopherDavisUCI! So probably something going on with the beta-release of JupyterLab v4?

No, no need to check `width="container"`, that won't work anyway.

**Comment by mattijn** [comment]
Oh wait, I didn't read good enough. It seems you can't reproduce the issue.

**Comment by ChristopherDavisUCI** [comment]
Hi @mattijn I had misunderstood!  I tried just now with
```
alt.Chart(cars).mark_bar().encode(
    x='Origin',
    y='count()',
)
```
both with the default renderer and with the `'mimetype'` renderer and didn't have any problems at first glance.

**Comment by mattijn** [comment]
This is supported in the second release candidate of Altair v5 (`pip install altair==5.0.0rc2`).
See animated gif:
![u5JGlLVizQ](https://user-images.githubusercontent.com/5186265/235376002-3c116bc0-8341-456f-aaa2-f09100838b14.gif)
Resizing in jupyterlab only works by resizing the browser. Resizing by panel handle doesn't work, as far as I can understand ist that a feature of jupyterlab (the code cells are also not changing in width). Suggestions how we can improve this are welcome.
