### ISSUE TITLE
Update to Vega-Lite 5.7

### ISSUE THREAD

**Issue by binste** [altair-viz/altair#3020]
VL 5.7 just got released. Updating Altair should be straight-forward as the changes to the schema itself are very small but haven't done yet as we need to wait for https://github.com/vega/schema/issues/8 to be resolved. Before that, we can't run the schema generation for 5.7 as there is no 5.7 schema file yet available under https://vega.github.io/schema

**Comment by domoritz** [comment]
I fixed the schema release.
