### ISSUE TITLE
Typo in altair/altair/expr/core.py: "columns" misspelled as "colums"

### ISSUE THREAD

**Issue by funwalla** [altair-viz/altair#303]
Sorry, it's my weekend for typos.

In altair/altair/expr/core.py, "columns" is twice misspelled as "colums":

line 218: `<Data Wrapper; colums=[*, density]>`
and
line 264: `return ("<Data Wrapper; colums=[{0}]>".format(', '.join(cols)))`

BTW, I am thoroughly enjoying your Python Data Science Handbook and also Altair. Thank you for writing them.

**Comment by jakevdp** [comment]
Thanks! fixed in https://github.com/altair-viz/altair/pull/304
