### ISSUE TITLE
"'ValidationError' object has no attribute 'json_path'" on interactive legend example in RC	

### ISSUE THREAD

**Issue by nrchtct** [altair-viz/altair#3038]
I have trouble passing the condition passing a point selection into the encode method. The [interactive legend example](https://altair-viz.github.io/gallery/interactive_legend.html) does not work on my end. I tried both RC1 and RC2, and in both cases, I get this:

`'ValidationError' object has no attribute 'json_path'`

… which seems to have been connected with issue #2715.

Is this a known issue? I do not get the error on version 4 with the old 

Thank you,
Marian

**Comment by mattijn** [comment]
Thanks for raising! A few questions:
You are using the syntax as is described in the documentation of altair v5? Including `alt.selection_point()` over `alt_selection_multi`?

It seems that you are still importing an old version of altair, but in that case I would expect an:
```
AttributeError: module 'altair' has no attribute 'selection_point'
```
Which versions are being returned by the following code just before the place where these error occurs?
```python
import importlib.metadata
importlib.metadata.version("jsonschema"), importlib.metadata.version("altair")
```

**Comment by nrchtct** [comment]
Thank you! Yes, I am using the new syntax and RC2. Here is the [notebook on Deepnote](https://deepnote.com/workspace/uclab_potsdam-db926059-78e8-4635-8a95-ba07789de60e/project/interactive-legend-bug-altair502-8408476e-5617-4e27-a12f-44a21642c164/notebook/Notebook%201-8b0c74118dba472ba3adea14fbdc4d60).

**Comment by mattijn** [comment]
Thanks I can reproduce this error with
jsonschema version `3.2.0`
altair version `5.0.0rc2`.

The full error message is 
```cmd
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[2], line 8
      4 source = data.unemployment_across_industries.url
      6 selection = alt.selection_point(fields=['series'], bind='legend')
----> 8 alt.Chart(source).mark_area().encode(
      9     alt.X('yearmonth(date):T').axis(domain=False, format='%Y', tickSize=0),
     10     alt.Y('sum(count):Q').stack('center').axis(None),
     11     alt.Color('series:N').scale(scheme='category20b'),
     12     opacity=alt.condition(selection, alt.value(1), alt.value(0.2))
     13 ).add_params(
     14     selection
     15 )

File D:\Software\Miniconda3\envs\stable\lib\site-packages\altair\vegalite\v5\api.py:2306, in _EncodingMixin.encode(self, *args, **kwargs)
   2303 @utils.use_signature(core.FacetedEncoding)
   2304 def encode(self, *args, **kwargs) -> Self:
   2305     # Convert args to kwargs based on their types.
-> 2306     kwargs = utils.infer_encoding_types(args, kwargs, channels)
   2308     # get a copy of the dict representation of the previous encoding
   2309     # ignore type as copy method comes from SchemaBase
   2310     copy = self.copy(deep=["encoding"])  # type: ignore[attr-defined]

File D:\Software\Miniconda3\envs\stable\lib\site-packages\altair\utils\core.py:730, in infer_encoding_types(args, kwargs, channels)
    726     except jsonschema.ValidationError:
    727         # our attempts at finding the correct class have failed
    728         return obj
--> 730 return {
    731     encoding: _wrap_in_channel_class(obj, encoding)
    732     for encoding, obj in kwargs.items()
    733 }

File D:\Software\Miniconda3\envs\stable\lib\site-packages\altair\utils\core.py:731, in <dictcomp>(.0)
    726     except jsonschema.ValidationError:
    727         # our attempts at finding the correct class have failed
    728         return obj
    730 return {
--> 731     encoding: _wrap_in_channel_class(obj, encoding)
    732     for encoding, obj in kwargs.items()
    733 }

File D:\Software\Miniconda3\envs\stable\lib\site-packages\altair\utils\core.py:725, in infer_encoding_types.<locals>._wrap_in_channel_class(obj, encoding)
    720 cls = classes["value"] if "value" in obj else classes["field"]
    722 try:
    723     # Don't force validation here; some objects won't be valid until
    724     # they're created in the context of a chart.
--> 725     return cls.from_dict(obj, validate=False)
    726 except jsonschema.ValidationError:
    727     # our attempts at finding the correct class have failed
    728     return obj

File D:\Software\Miniconda3\envs\stable\lib\site-packages\altair\utils\schemapi.py:877, in SchemaBase.from_dict(cls, dct, validate, _wrapper_classes)
    875     _wrapper_classes = cls._default_wrapper_classes()
    876 converter = _FromDict(_wrapper_classes)
--> 877 return converter.from_dict(dct, cls)

File D:\Software\Miniconda3\envs\stable\lib\site-packages\altair\utils\schemapi.py:1040, in _FromDict.from_dict(self, dct, cls, schema, rootschema, default_class)
   1038 for key, val in dct.items():
   1039     if key in props:
-> 1040         val = self.from_dict(val, schema=props[key], rootschema=rootschema)
   1041     kwds[key] = val
   1042 return cls(**kwds)

File D:\Software\Miniconda3\envs\stable\lib\site-packages\altair\utils\schemapi.py:1023, in _FromDict.from_dict(self, dct, cls, schema, rootschema, default_class)
   1021 for possible_schema in schemas:
   1022     try:
-> 1023         validate_jsonschema(dct, possible_schema, rootschema=rootschema)
   1024     except jsonschema.ValidationError:
   1025         continue

File D:\Software\Miniconda3\envs\stable\lib\site-packages\altair\utils\schemapi.py:76, in validate_jsonschema(spec, schema, rootschema, raise_error)
     74 if errors:
     75     leaf_errors = _get_leaves_of_error_tree(errors)
---> 76     grouped_errors = _group_errors_by_json_path(leaf_errors)
     77     grouped_errors = _subset_to_most_specific_json_paths(grouped_errors)
     78     grouped_errors = _deduplicate_errors(grouped_errors)

File D:\Software\Miniconda3\envs\stable\lib\site-packages\altair\utils\schemapi.py:142, in _group_errors_by_json_path(errors)
    140 errors_by_json_path = collections.defaultdict(list)
    141 for err in errors:
--> 142     errors_by_json_path[err.json_path].append(err)
    143 return dict(errors_by_json_path)

AttributeError: 'ValidationError' object has no attribute 'json_path'
```
Is this something that you recognize @binste?

**Comment by mattijn** [comment]
Current support is `jsonschema>3`. Where the 3.0.0 version was released February 2019.

I'm leaning towards requiring `jsonschema>=4`, where version `4` (actually `4.0.1`) was released September 2021. 

It's also the first version available on GitHub [releases](https://github.com/python-jsonschema/jsonschema/releases?page=5).

How much do you favor the v3 support of jsonschema @binste

**Comment by nrchtct** [comment]
Good! Thank you for looking into this. Updating jsonschema per `jsonschema>=4.0.1` in requirements.txt is somehow not possible on Deepnote. Is this version requirement for jsonschema something that Altair could enforce with the next RC version?

**Comment by mattijn** [comment]
Yes, per #3039.

**Comment by nrchtct** [comment]
Thank you, @mattijn . This works for me locally, but unfortunately [not on Deepnote](https://deepnote.com/workspace/uclab_potsdam-db926059-78e8-4635-8a95-ba07789de60e/project/interactive-legend-bug-altair500RC3-6a3be476-75a5-44ba-84e3-5d3ad8ea3cb4/notebook/Notebook%201-e47d1900a25f4f0abb60f9fdc023d8f3). Neither `%pip install jsonschema==4.17.3` at the start of the notebook nor `jsonschema==4.17.3` in requirements.txt helps…

**Comment by binste** [comment]
I'm not familiar with deepnote but did you restart the notebook kernel after updating jsonschema? If you use the command that mattijn provided above, what is the version of jsonschema in deepnote?

**Comment by nrchtct** [comment]
Yes, I did restart the kernel and reset the project. Locally it actually works, but on Deepnote the version of jsonschema as reported by importlib.metadata remains 3.2.0. Not sure why… Thank you

**Comment by jonmmease** [comment]
My guess is that Deepnote imports jsonschema for its own use before executing user code. It would be worth asking their support if there's a way around that, or if they could update the version.

**Comment by nrchtct** [comment]
I learned in a [thread on their forum](https://community.deepnote.com/c/ask-anything/jsonschema-4-0-1) that "jsonschema is one of the core packages of Deepnote that make the product work". So this might take some time. In case, there are other Altair users on Deepnote they may run into similar issues when filtering along interactive legends.

**Comment by ChristopherDavisUCI** [comment]
Thank you @nrchtct!  That thread you linked does not seem very reassuring to me in terms of whether this update will happen on the Deepnote side anytime soon.

So if there were a straightforward way to solve this on the Altair side, that would also be helpful for my use of Altair in Deepnote (for teaching).
