### ISSUE TITLE
Unable to save PNG with vl_convert

### ISSUE THREAD

**Issue by StevenLi-DS** [altair-viz/altair#3045]
Unable to save png with vl_convert '0.9.0' in altair '4.2.2'.
I check my `conda list`, and vl_convert '0.9.0'  is installed. 
`Chart.save()` will return
```
ValueError: Saving charts in 'png' format requires the altair_saver package: see http://github.com/altair-viz/altair_saver/
```

Btw, I have to install `vl_convert` via pip since the conda-forge version hasn't supported `osx-arm64` (https://github.com/vega/vl-convert/issues/29)

---

Please follow these steps to make it more efficient to solve your issue:

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [x] Search for duplicate issues.
- [x] Use the latest version of Altair.
- [ ] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by binste** [comment]
Support for `vl_convert` in `Chart.save()` will be added in Altair version 5 which might come out this week. However, you can already use `vl_convert` with Altair 4 as described [here](https://github.com/vega/vl-convert/tree/main/vl-convert-python#convert-altair-chart-to-svg-png-and-vega).

**Comment by StevenLi-DS** [comment]
@binste Thanks for the explanation. I read the doc, and it does not mention it's a new feature in version 5, so I assumed it would work. Is there any reason, why we can't have this as a built-in feature? I read some issues in which @jakevdp explained everything. But since `vl_convert` does not need other dependencies, could it be integrated into Altair directly?

**Comment by StevenLi-DS** [comment]
@binste Thanks for the update. Indeed, it's working now. 

https://github.com/altair-viz/altair/assets/33796896/d120f12e-1d36-4f2f-8fb4-c8dcc66bbf2b
