### ISSUE TITLE
[DOC] `altair-saver` on pypi but `altair_saver` on conda-forge

### ISSUE THREAD

**Issue by StevenLi-DS** [altair-viz/altair#3049]
The altair saver is named as `altair_saver` on conda-forge but `altair-saver` on pypi

https://anaconda.org/conda-forge/altair_saver

https://pypi.org/project/altair-saver/

There might be a type in the doc:
https://altair-viz.github.io/user_guide/saving_charts.html#altair-saver
![CS-Mu5BohDt@2x](https://github.com/altair-viz/altair/assets/33796896/13efc679-8f76-4aba-a2df-2c89fd3c33cb)

---

Please follow these steps to make it more efficient to solve your issue:

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [x] Search for duplicate issues.
- [ ] Use the latest version of Altair.
- [ ] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by binste** [comment]
I just tested this and `altair_saver` can be installed from pypi using both the `-` and `_` syntax, i.e. `pip install altair_saver` works fine and so I think we can leave it in the docs.

**Comment by joelostblom** [comment]
Closing as either syntax works on pypi

**Comment by StevenLi-DS** [comment]
@binste it seems like if you put altair_saver in a conda yml, it will have an issue.
<img width="1422" alt="CS-sTA6P7ZF@2x" src="https://github.com/altair-viz/altair/assets/33796896/695622e6-ea8d-45ca-ab4d-499cb5649f6c">
