### ISSUE TITLE
jupyter lab, altair plots not showing up.

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#305]
I know jupyter lab is still alpha, but I am wondering if anyone has gotten altair plots to work in it?
The plots don't show up for me when I generate them.  I have tried on both a windows and linux box to try varied platforms.

If I run the plots just in the regular notebook, save it, then open that in jupyter lab - the plots will still be there.  However, if I then re-execute the cells the plots disappear.

Note:  I did do all this through conda.  And after the plots did not show up - I then rand that last line on the pip instructions (again only installed through conda) to see if the plots would show up:
jupyter nbextension install --sys-prefix --py vega
And they still did not.

**Comment by jakevdp** [comment]
There are ongoing efforts in this – it requires a different display system for plots to show up in JupyterLab. You can see the progress at https://github.com/altair-viz/jupyterlab_vega

The 2.0 release of Altair later this spring will depend on jupyterlab-vega, and all this should work transparently across both the notebook and jupyterlab.

**Comment by afonit** [comment]
@jakevdp Great thanks for the info and the link.

**Comment by jakevdp** [comment]
This is also relevant: https://github.com/altair-viz/altair/pull/216

**Comment by frmsaul** [comment]
Until the problem is fixed in the 2.0 release, is there a preferred workaround?

**Comment by jakevdp** [comment]
The preferred workaround is to use version 2.0
