### ISSUE TITLE
Add altair sphinx extension back to package?

### ISSUE THREAD

**Issue by jtilly** [altair-viz/altair#3051]
With version 5.0.0 (thank you for the release! 🥳) the altair sphinx extension was removed from the package. It used to be importable from `altair.sphinxext`. Would it be possible to bring that back?

There is a small number of projects on GitHub that use the extension in their own code base: https://github.com/search?q=%22altair.sphinxext%22&type=code including one of [ours](https://github.com/Quantco/glum/blob/4b03683a4c60e82733b721149ee7140d99d928bd/docs/conf.py#L26).

Thank you!

**Comment by jedbrown** [comment]
We also use this, love altair, and would rather not copy `sphinxext` into our project. If this can't be re-added, what is the migration plan for projects that have been using `altair.sphinxext`?

**Comment by binste** [comment]
Move of `sphinxext` to top-level happened in #2792. Honestly, I was simply not aware when reviewing it that other packages use this as well, although I can see now that it makes sense...

I think the main goal of that PR was to get the tests out of the altair module into a separate folder and `altairgallery` needs to import some functionality from the tests to fetch [the example charts](https://github.com/altair-viz/altair/blob/master/sphinxext/altairgallery.py#L26) and so it made sense to lift it out as well. Also, `sphinxext` relies on packages, such as sphinx and docutils, which are not part of the Altair requirements.

How about we only move the `altairplot` directive back into `altair.sphinxext` as it does not depend on the `tests` folder? We can add `ImportError`s with some context if `docutils` or `sphinx` are not installed. `altairgallery` only [shows up in Altair forks](https://github.com/search?q=%22altair.sphinxext.altairgallery%22&type=code) so it could be left in a separate folder. I could work on this.

**Comment by jedbrown** [comment]
Thanks, that would be great. And if you really don't want it included with the rest of altair, it could be a separate package `altair-sphinxext` on PyPI.

**Comment by jtilly** [comment]
> How about we only move the altairplot directive back into altair.sphinxext as it does not depend on the tests folder? 

Yes, that would be great!

**Comment by binste** [comment]
I'll wait for @mattijn to chime in before working on this.

**Comment by mattijn** [comment]
I was unaware that there were other packages depending on the `sphinxext` module when moving it out of Altair package. 

I've seen repositories struggling how to make these Altair plots appear in documentation. If it is a separate package I think it will make it easier to discover, install and use in other projects. 

For the short-term, we can move it back as @binste described including and add a deprecation warning and setup a separate `sphinxext-altair` repository.

**Comment by binste** [comment]
Using GH Search I can find only 5 actively maintained repositories which rely on `altairplot`:

- https://github.com/Quantco/glum
- https://github.com/CEED/libCEED
- https://github.com/bmorris3/owls
- https://github.com/bernardodionisi/differences
- https://github.com/bernardodionisi/plotto

I could move the `altairplot` functionality to `sphinxext-altair` in a few days (maybe this weekend) and so I'm wondering if it's even worth it to move back `altairplot` into `altair` with a deprecation warning. Might be less work for everyone if we directly go for the separate package. `glum` and `libCEED` maintainers are part of the discussion here and for the other 3 repos I can create issues and show how to switch to `sphinxext-altair` once it's out. Ok for you @mattijn or do you see an issue with this approach?

**Comment by jedbrown** [comment]
Agreed. We also use it in projects on GitLab, but people who have been using `altair.sphinxext` in CI will have pinned their versions already and can find the new package when they try to upgrade. A note in the Altair release notes would be helpful as that's the first place I looked to see why our docs CI was broken (before coming here).

**Comment by mattijn** [comment]
@binste, I created https://github.com/altair-viz/sphinxext-altair. I think that should be sufficient to make a start with the transition?

**Comment by binste** [comment]
Published https://github.com/altair-viz/sphinxext-altair on pypi. You can install it with `pip install sphinxext-altair` and use it with:

```python
extensions = [
    ...
    "sphinxext_altair.altairplot",
    ...
]
```

This should give you the same functionality as before. Let me know how it goes! I also added a note to the release on github and will do the same for the docs.

**Comment by jtilly** [comment]
Very cool, thank you! Is it okay if I turn this into a conda package (i.e. I would open a PR at https://github.com/conda-forge/staged-recipes)?

**Comment by binste** [comment]
I've never created a conda package so this would be great, thank you!

**Comment by jtilly** [comment]
PR is here: https://github.com/conda-forge/staged-recipes/pull/22811

**Comment by jtilly** [comment]
Thank you @binste and @mattijn for creating https://github.com/altair-viz/sphinxext-altair/ so quickly! This resolves the issue for me 🥳
