### ISSUE TITLE
Typos in DOC of Ranged Area

### ISSUE THREAD

**Issue by januslian** [altair-viz/altair#3055]
Hi,

I think there is a typo in the manual for ranged area(https://altair-viz.github.io/user_guide/marks/area.html#ranged-area). It says "For example, we can use ranged area with the ci0 and ci0". I think the second ci0 should be ci1.

**Comment by mattijn** [comment]
Thanks @januslian! Well spotted. I also think the example does not match description, as I don't see usage of `c0` and `c1`.
