### ISSUE TITLE
Docs are broken

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#306]
Plots on the [Altair docs](https://altair-viz.github.io/) no longer render. This is because the script at http://vega.github.io/vega/vega.js has been updated to version 3.0, and it's not backward compatible.

Are there persistent URLs for older versions of vega & vega-lite anywhere?

**Comment by jakevdp** [comment]
cc/ @kanitw @domoritz

**Comment by jheer** [comment]
The latest 2.x release is here:
https://vega.github.io/vega/releases/v2.6.5/vega.js

Apologies for the break as we get the new release in place!

**Comment by jakevdp** [comment]
Great, thanks!

**Comment by jakevdp** [comment]
Fixed by a manual find-replace of the current github pages build, also future issues will be mitigated by #308. Thanks @jheer!

**Comment by jheer** [comment]
FYI, I just added URLs to the Vega website that will always point to the _latest_ v2 release:
- https://vega.github.io/vega/releases/v2/vega.js
- https://vega.github.io/vega/releases/v2/vega.min.js
