### ISSUE TITLE
interactive-crossfilter selection mode  enhancement

### ISSUE THREAD

**Issue by wybert** [altair-viz/altair#3062]
I find [this example ](https://altair-viz.github.io/gallery/interactive_layered_crossfilter.html#interactive-crossfilter
)very interesting. However, it lacks a selection mode to enable the cross filter with intersection instead of overwriting the exited selection. Filtering on different graphs should be performed on the basis of existing filters in other graphs, rather than covering previous filters. 

See [one of the  Holoview examples here.](https://holoviews.org/user_guide/Linked_Brushing.html#filter-and-selection-modes).
<img width="930" alt="image" src="https://github.com/altair-viz/altair/assets/5254627/a11a53b5-13aa-4812-b984-2f2ea156aa8e">

**Comment by joelostblom** [comment]
Do you get the desired behavior if you set resolve like so:

```py
alt.selection_interval(encodings=['x'], resolve='intersect')
```

**Comment by wybert** [comment]
That's AWESOME!
