### ISSUE TITLE
Include a suggestion to update frontend (Jupyterlab, ...) in mimetype error

### ISSUE THREAD

**Issue by binste** [altair-viz/altair#3070]
Follow-up that comes out of #2585. Raised by @joelostblom:

> do you think we need to communicate the minimum version of JuptyerLab that support Altair 5 somewhere? I am thinking ideally directly in the error message if possible, but otherwise at least in the docs and release notes, what do you all think?

**Comment by FireEmerald** [comment]
I would had appreciated any hint here as it took me an hour to figure out why my chart's weren't working anymore.
By the way i used in my jupyter notebook the `alt.renderers.enable('jupyterlab')` until today which worked just fine, now i had to switch to `alt.renderers.enable('default')`, no plan what you changed there.
