### ISSUE TITLE
interactivate charts Implementation of Local Area Network 

### ISSUE THREAD

**Issue by linzimu** [altair-viz/altair#3072]
Dear Altair developers. Have you considered implementing the interactivate charts in the local area network?

**Comment by binste** [comment]
Could you elaborate what you mean by "interactive charts in the local area network"?

**Comment by linzimu** [comment]
My computer doesn't have access to the internet, but I want to achieve the effect of an interactive graph

**Comment by binste** [comment]
To display Altair charts offline, you can use the mimetype renderer that comes with JupyterLab or VS Code. Simply run `alt.renderers.enable('mimetype')` once at the top of your notebook. See https://altair-viz.github.io/user_guide/display_frontends.html#displaying-in-jupyterlab for more information.

**Comment by linzimu** [comment]
I am now in an offline environment to achieve the following effect, and the pictures have interactive actions.
![image](https://github.com/altair-viz/altair/assets/22839407/1450621c-bae7-4cd1-b591-7e4f2ba7de11)
When I use the following method, an error is reported, and the picture given in this way has no interactive effect.
![image](https://github.com/altair-viz/altair/assets/22839407/dba15b38-3305-40b3-82df-ee59355aec74)

**Comment by binste** [comment]
The mimetype renderer for Altair 5 requires at least JupyterLab version 4 -> If you stop Juypterlab, upgrade it to version 4, start it again and rerun the notebook, then it should work. See https://jupyterlab.readthedocs.io/en/latest/getting_started/installation.html for installation instructions on Jupyterlab.

**Comment by jonmmease** [comment]
It also looks like you have a release candidate of Altair installed (version `5.0.0rc3`). I recommend updating to the latest version (currently `5.0.1`)

**Comment by linzimu** [comment]
@jonmmease @binste Thank you very much for your kind replies, my problem has been solved
![image](https://github.com/altair-viz/altair/assets/22839407/3270b903-4965-4c5e-af50-a9ebafeca4d9)

**Comment by linzimu** [comment]
my problem has been solved
