### ISSUE TITLE
'Chart' object has no attribute 'add_params'

### ISSUE THREAD

**Issue by jeremyNG-lab** [altair-viz/altair#3078]
Hi

I just tested a easy code:

```python
import altair as alt
from vega_datasets import data


alt.renderers.enable('altair_viewer')

# load a simple dataset as a pandas DataFrame
source = data.cars()

brush = alt.selection_interval(resolve='global')

base = alt.Chart(source).mark_point().encode(
    y='Miles_per_Gallon',
    color=alt.condition(brush, 'Origin', alt.ColorValue('gray')),
).add_params(
    brush
).properties(
    width=250,
    height=250
)

base.encode(x='Horsepower') | base.encode(x='Acceleration')
```

I have an error:
```cmd
Cell In[2], line 5 base = alt.Chart(source).mark_point().encode(

File C:\ProgramData\Anaconda3\lib\site-packages\altair\utils\schemapi.py:257 in __getattr__
    return _getattr(attr)

AttributeError: 'Chart' object has no attribute 'add_params'
```

**Comment by mattijn** [comment]
Thanks for reporting @jeremyNG-lab! 

Your environment is still on Altair version 4, but you are using syntax that was introduced in Altair version 5. 
Eg. `.add_params()` was introduced in version 5, where this was `add_selection()` in v4  ([see release notes](https://altair-viz.github.io/releases/changes.html#grammar-changes)). 

If you are in the position that you are not able to update Altair and have to stay on Altair v4, then please consider changing your specification in accordance with the v4-docs on [interactivity](https://altair-viz.github.io/altair-viz-v4/user_guide/interactions.html).

If you upgrade your Altair version to v5 your code snippet will work. Click [here](See the docs on [interactivity](https://altair-viz.github.io/user_guide/interactions.html) of v5. ) for the v5 docs on interactivity what you can do with `params`.

I'm not sure how your environment is maintained, but you can do (pick the 'right' one to not corrupt your env):
1. using conda:  `conda update altair`
2. using mamba: `mamba update altair`
3. using pip: `python -m pip install altair --upgrade`

To make the situation more complicated: I noticed you are using `altair_viewer` as renderer. The latest released version on pypi and conda are only supporting Altair version 4. If you cannot drop this renderer, but still like to update Altair to v5, you could, for now, consider installing the version of [`altair_viewer`](https://github.com/altair-viz/altair_viewer) directly from the master-repo on github (`python -m pip install git+https://github.com/altair-viz/altair_viewer.git`) which does supports Altair v5.

Again, thanks for reporting and if you run into more issues please do not hesitate to ask!
