### ISSUE TITLE
Ridgeline example is broken on master

### ISSUE THREAD

**Issue by jonmmease** [altair-viz/altair#3079]
Running the ridgeline example from https://altair-viz.github.io/gallery/ridgeline_plot.html results in a faceted empty chart on master.

![visualization](https://github.com/altair-viz/altair/assets/15064365/1656d6d3-24d3-44c6-b04b-10010e0c15e4)

I haven't dug in further, but it seems like the Vega-Lite produced by Altair has changed from:

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYdulQgCcIAa0woyAGxUBfbjACGYTONQhKAB10kkyNppDFCKpYe1QwjCDJQhMUOiHXW62oTaeCCkMioeYoTGlMgA9HFgdFAAdABWlHSYKnBoMilQ+nFQxgC2cWiYCNoAtAFBlPqUAAJoAIwpAEwAnClscfXacY2Bdpg12JiBjJj5YJRovlq6+iFyuIbw2T7IIACyvMzcM9pZ7ptupYEeAKQAQiDcKtoARtkAgjkIUB4youJPV4fKAIewoKzcWxg5CqFSQgCexgcNkwpWMbm0ET8UiRYBCVxk8hChERyO0MimjxA8DUAHlTGA4CTwSkABzcEiEWbo55cjylaAQQjQJRSWQKZFfMQIGTaeFU6RyRS0BjMSwpACs1i8kDo5hCNIimywKh2IFKUygAH0uWiqfYEF4drCpGBMQ5QHQIFcSCgANrsTgagC6rpmFt+mDo8OyKgg2BeKlISmsJKRHgAjqQnLZArkU9wAB4hF6+3alqCFHxaE1mitW0q+yFM6H7bSFuClUilAAEABFtHAVPCewAVVFI2WEMKYHsACgAwgBKKlp5FZnNMvOVJYgeWODuUZSkNQ17YeNCY5MKt3Q0CykEOP2dLg1F-B1OkzPZohb4g77EQBmf4UBfSEH0oGBLn9UAtlNDx6lFGxO0wABVKAmX5Q4qW0I9dgOIhmE0UA0ggEhtAQGUqkCJ9QAgYx+UtKk4LNW1jAbdscLw81LRtCdfFDEAZQoYwXn3P19mwj9OFACsUFkZMz3g3Y2I44tuFw-0QHrK51O0kgG19aTQAoqjqj5ZA-TohjdkgUgiC4i8rxTQThNIUTxMkwiqQtJw+LtbgdKbfTrV0kBjJATtjFICyQEvJMkMUfcQsMn5uDcjytIIpgfN4tjwu4eLr0sdRpO0ihvG4mAk0oI5kLGDwAGUpkIMYe2oFqZncbgABJKBcVFgl2KIYniCpqJSBAmUYUgXhSOAIGGAarnG6oahyLkKg1Nk+nSShoF8IA)

in 5.0.1 (based on the docs), to

[Open the Chart in the Vega Editor](https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYdulQgCcIAa0woyAGxUBfbjACGYTONQhKAB10kkyNppDFCKpYe1QwjCDJQhMUOiHXW62oTaeCCkMioeYoTGlMgA9HFgdFAAdABWlHSYKnBoMilQ+nFQxgC2cWiYCNoAtAFBlPqUAAJoAIwpAEwAnClscfXacY2Bdpg12JiBjJj5YJRovlq6+iHw2T7IIACyvMzcM9pZ7oYq2gBG2QCCUAj2KFwgZ5cqVzkIUB4youJabqWBDwAUgAQksbHAxspSGpuIQAJ7GBw2TClYxubQRawmTBgEIAmTyEIIpEebQyKYgLRwNQAeVMYEh8IeKQAHNwSIRZuizlyPKVoBBCNAlFJZApke8xAgZNpmWK5IpaAxmJYUgBWaxeSB0cxrGkRQzrFSbEClKZQAD6XLRVKeVS8m1UKikYExDlAdAgAJIKAA2uxOOqALqumbmr6YOjw7IqCDYc4qUhKawk5EAR1ITlsgVyKe4AA8QudfchZMnqRsPCWraVfXDIfcttttAW4KVSKUAAQAEW0NPhXYAKqikbLCGFMF2ABQAYQAlHa0x5M9nIbnKuDmY425RobCQMbTWhMcm7ZQ3U3QLLbg4-Z0uDUH8HU4iM1miOviJu-AcRAgxBQB84RvSgYH+f1QCPDx6lFCFzQAVSgSF+T2O1tD3Zs0M0UA0ggEhtAQGUqkCO9QAgYx+QtO1oK2G1jEtAEi24DCqKca1R18UMQBlChjHObc-R2NCX04UAaxQctMErE0PHoxjW3QzChJrBTmJAVS60+UTQEI4jqj5ZA-XIyitkgUgiCUjwTyTFNuN40h+ME4SiH2M0LQ421uE0+sNJINSQB0kB22MUhDJAGyz24RRtz82tfIcpz-Rcpg7XNdj6MC7hIocKxRI0ihvEww8k0oNzbCbEAAGUpkIMYu2oWqZncbgABIL3DYItiiGJ4gqEiUgQSFGFIc4UjgCBhhcVEhkqaoahyLkKnVNk+nSShoF8IA)

on master.

**Comment by binste** [comment]
Just tested it against 5.0.1 and 5.0.0 and they all produce the same spec. Turns out, there is a difference between the `Method syntax` example and the `Attribute syntax` one. The later produces the correct spec, the `Method syntax` produces a wrong spec in two places:

* for x encoding, `bin(True)` should be `bin("binned")`
*  `facet(alt.Row...)` should be `facet(row=alt.Row...)`

For both differences I'm not sure if it makes sense that the former does not work. I'll look into it over the weekend. Thanks for reporting it @jonmmease!
