### ISSUE TITLE
Ridgeline plot example broken ("Method Syntax" version)

### ISSUE THREAD

**Issue by thomascamminady** [altair-viz/altair#3088]
I believe that the "Method Syntax" version of the ridgeline plot example (https://altair-viz.github.io/gallery/ridgeline_plot.html) might be broken in two ways.

## 1) Facet usage

The code for the ridgeline plot example contains this part
```python
.facet(
    alt.Row('Month:T')
        .title(None)
        .header(labelAngle=0, labelAlign='right', format='%B')
)
```
But this renders the different facets as columns. 
This should be fixed to include the `row` keyword.
```python
.facet(
    row=alt.Row('Month:T')
        .title(None)
        .header(labelAngle=0, labelAlign='right', format='%B')
)
```

## 2) Data not rendered
When I just copy the method syntax example, no data is rendered for me, the plot is empty and looks like this (I added the `row`keyword):
![image](https://github.com/altair-viz/altair/assets/24543638/de06efd7-bcbd-411c-b3ea-9a4d6b9ce64f)

I was able to identify this part as the issue:
```python
 alt.X('bin_min:Q')
        .bin(True)
        .title('Maximum Daily Temperature (C)'),
```
If I replace this by
```python
alt.X('bin_min:Q', bin='binned', title='Maximum Daily Temperature (C)'),
```
I get back the original plot that is shown in the "Attribute Syntax" example.
I don't know what happens here though. This seems to have something to do with the binning?

**Comment by thomascamminady** [comment]
I saw that this was already addressed just minutes after posting. My apologies!

**Comment by jonmmease** [comment]
No problem, thanks for taking the time to let us know!
