### ISSUE TITLE
Can I build altair against vega-lite v2.0.0-alpha.x

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#309]
I was wondering if it is possible to build the altair module using the latest alpha release of vega-lite?

**Comment by jakevdp** [comment]
Not without some major changes to the library. Building Altair against a new vega-lite version requires essentially re-generating the package, and the changes in 2.0 are big enough that it will require a lot of tinkering. That's said, it is something I'm hoping to tackle in the coming weeks.

**Comment by jakevdp** [comment]
The Vega-Lite beta is getting stable enough that it may be possible to start on this. I have a meeting with the Vega-Lite developers Monday to discuss some of the challenges introduced by new design decisions in the vega-lite 2.0 schema.

**Comment by ellisonbg** [comment]
@jakevdp how was the meeting. Want to open an issue with a summary ;-)

Closing this one as question...

**Comment by jakevdp** [comment]
Things are stabilizing a bit in the vega-lite beta. It's going to take a few non-trivial modifications to our schema parsing code, but as soon as there's a stable vega-lite 2.0 release I think the path forward will be pretty clear.
