### ISSUE TITLE
Control over bar positions relative to ticks on discretized time axis?

### ISSUE THREAD

**Issue by liquidcarbon** [altair-viz/altair#3090]
Hello,

I'd like to plot a timeline of events using `mark_rect`, with time on X and event category on Y.  I'd like the ticks to be aligned with the middle of the bars - in other words, shift the rectangles to the left by half a day.  I don't think I can use the `:O` type because I need to show gaps in the plot, unless there's a way to fill the timescale with all dates (which I tried).  The commented sections is what I've tried.  Also tried using `yearmonthdatehours` on datetime values set to noon, but that then my bins are too narrow.   It seems like `tickBand` or `bandPosition` arguments to `alt.Axis` could be used by they take no effect.  

Is there a way to make it work?  It's a really a minor thing but it bugs me...

![image](https://github.com/altair-viz/altair/assets/47034358/b87f247d-34c0-4d7a-b43b-76bdf2016778)

```
def plot_timeline(df):
    _date_range = pd.date_range(df.run_day.min(), df.run_day.max()).values
    n_days = len(_date_range)
    chart = alt.Chart(df).mark_rect(width=alt.RelativeBandSize(0.9)).encode(
        x=alt.X(
            'yearmonthdate(run_day):T',
            #'run_day:T',
            axis=alt.Axis(
                # bandPosition=0.5,
                # tickBand='center',
                format='%Y-%m-%d',
                labelAngle=-90,
                # labelOverlap=False,
                # values=_date_range,
            ),
            scale=alt.Scale(nice={'interval': 'day', 'step': 7})
        ),
        y=alt.Y('daily_run_num:O', axis=None),
        fill=alt.Fill(
        ...
```

related: https://github.com/altair-viz/altair/issues/2078

**Comment by joelostblom** [comment]
My first thought was `tickBand` as well. Could you create a minimum reproducible example that shows the unexpected behavior to facilitate further troubleshooting?

**Comment by liquidcarbon** [comment]
Here you go:

```
import altair as alt
import pandas as pd

def plot_timeline(
    df=pd.DataFrame({
        'run_day': ['2023-03-01','2023-03-01','2023-03-04','2023-03-05','2023-03-05','2023-04-02',],
        'run_status': list('AABACA'),
        'y': [1, 2, 1, 1, 2, 1],
    })
):

    chart = alt.Chart(df).mark_rect(width=alt.RelativeBandSize(0.9)).encode(
        x=alt.X(
            'yearmonthdate(run_day):T',
            axis=alt.Axis(
                bandPosition=1,
                format='%Y-%m-%d',
                labelAngle=-90,
                tickBand='center',
            ),
            scale=alt.Scale(nice={'interval': 'day', 'step': 7})
        ),
        y=alt.Y('y:O', axis=None),
        fill=alt.Fill('run_status:N').legend(orient="top"),
    ).configure_view(
        step=15, continuousWidth=450, strokeWidth=1
    ).configure_scale(rectBandPaddingInner=0.1) 
    return chart.interactive()

plot_timeline()
```

![image](https://github.com/altair-viz/altair/assets/47034358/321fd701-53ca-40f3-8b3e-5a8d7fa4c41d)

**Comment by joelostblom** [comment]
It seems like you can use `tickOffset` to make it work. With `tickOffset=-5` I get:

![image](https://github.com/altair-viz/altair/assets/4560057/b66cbe26-8122-4f67-bd30-67cdd26a474e)

I am not sure why some of the other tick options don't work

**Comment by liquidcarbon** [comment]
Wonderful, thank you!  Note to self: look through the list of arguments to the end!
