### ISSUE TITLE
Add 'Distributions and Medians of Likert Scale Ratings' example to gallery 

### ISSUE THREAD

**Issue by binste** [altair-viz/altair#3098]
I really like this example in the Vega-Lite gallery: https://vega.github.io/vega-lite/examples/layer_likert.html It shows a great way to visualise likert scale ratings and at the same time is a good example of how powerful the grammar of graphics of Altair/VL is.

Would be great if someone wants to rewrite it in Altair and add it to the Altair gallery as well, probably under the "Distributions" category.

<img width="618" alt="image" src="https://github.com/altair-viz/altair/assets/23366411/83036e71-18fe-4e83-ac65-d73420623652">

**Comment by thoemi123** [comment]
Glad to work on this issue - will create the PR soon for it
