### ISSUE TITLE
Compute percentage columns in Diverging Stacked Bar Chart example

### ISSUE THREAD

**Issue by jonmmease** [altair-viz/altair#3103]
It would be nice to update the [Diverging Stacked Bar Chart](https://altair-viz.github.io/gallery/diverging_stacked_bar_chart.html) example to include the calculation of the `percentage`/`percentage_start`/`percentage_end` columns.

I worked through this in this discussion answer: See https://github.com/altair-viz/altair/discussions/3101#discussioncomment-6417028

**Comment by joelostblom** [comment]
I agree that this would be helpful
