### ISSUE TITLE
Change SortField default 'op' to 'values'

### ISSUE THREAD

**Issue by ekajjake** [altair-viz/altair#311]
I find myself using a `SortField` on a categorical X axis to specify a sort by the respective Y values quite often. Having to specify an `op` of `'values'` for this case seems superfluous.

The case here:
```
Chart(data).mark_bar().encode(
    X('categoricals', sort=SortField(field='vals', op='values', order='descending')),
    Y('vals')
)
```
could be changed to:
```
Chart(data).mark_bar().encode(
    X('categoricals', sort=SortField(field='vals', order='descending')),
    Y('vals')
)
```
Perhaps this is a stylistic choice, but a change would help to provide a more straightforward expected behavior. Also, this would ease frustrations stemming from providing a `SortField` but ending up with nothing sorted.

**Comment by kanitw** [comment]
I agree that having default `op` would be helpful in the case that there is only one y value for each unique x value.  (This is common but not always true.)

Thai said, [`values`](https://github.com/vega/vega/wiki/Data-Transforms#-aggregate) builds up an array of all input objects in the group.  So I don't think it is a good default for the `op` of `SortField`.  Plus, it seems to be excluded from the list of aggregation operation in [Vega 3](https://vega.github.io/vega/docs/transforms/aggregate/#-aggregate-operation-reference).  

A more reasonable default op would be one of `min`, `max`, `median`, or `mean`.  
However, it was unclear what would really be the best default.  Thus we made `op` a required property of `SortField`.

**Comment by ekajjake** [comment]
Aha! This was a clear misunderstanding of `values` on my part. It must have been a coincidence in my specific case.
