### ISSUE TITLE
Weird behavior when using `mark_line(point=True)` for geo data

### ISSUE THREAD

**Issue by thomascamminady** [altair-viz/altair#3115]
This snippet

```python

import altair as alt
from vega_datasets import data
import pandas as pd

df_storm = pd.read_csv("storm.csv")

storms = alt.Chart(df_storm).encode(
    longitude=alt.Longitude("Longitude:Q"),
    latitude=alt.Latitude("Latitude:Q"),
)

map_background = alt.Chart(
    alt.topo_feature(data.world_110m.url, feature="countries")
).mark_geoshape(stroke="white", strokeWidth=2, color="lightgray")


chart1 = (
    alt.layer(map_background, storms.mark_line(), storms.mark_point())
    .project(translate=[1000, 600], scale=500)
    .properties(width=700, height=700)
)

chart2 = (
    alt.layer(map_background, storms.mark_line(point=True))
    .project(translate=[1000, 600], scale=500)
    .properties(width=700, height=700)
)

chart3 = (
    alt.layer(map_background, storms.mark_line(point=True), storms.mark_point())
    .project(translate=[1000, 600], scale=500)
    .properties(width=700, height=700)
)


chart1 | chart2 | chart3
```

results in this plot

![visualization](https://github.com/altair-viz/altair/assets/24543638/50cc4df5-56f1-4e4e-bb9e-21213c850a84)

Something weird is going on when setting `point=True` in `mark_line()`. 
I want to create the plot in the left column but first did it via the method that then created the middle plot and was confused by that behavior. The third chart confuses me even more. 

The behavior is there even when not concatenating the plots. 

Not sure what's happening here but I thought I just quickly point this out.

I'm using `altair` version `5.0.1`.

Here's the `storms.csv` MWE.
```csv
,Longitude,Latitude,ID
0,-61.6,12.7,AL062006
1,-63.0,13.0,AL062006
2,-64.4,13.3,AL062006
3,-65.8,13.7,AL062006
4,-67.1,14.0,AL062006
5,-68.3,14.3,AL062006
6,-69.5,14.6,AL062006
7,-70.4,15.1,AL062006
8,-71.2,15.7,AL062006
9,-72.0,16.3,AL062006
10,-72.7,16.9,AL062006
11,-73.4,17.4,AL062006
12,-74.0,17.8,AL062006
13,-74.6,18.3,AL062006
14,-75.2,19.1,AL062006
15,-75.5,19.9,AL062006
16,-75.6,20.0,AL062006
17,-76.4,20.8,AL062006
18,-77.4,21.6,AL062006
19,-78.5,22.4,AL062006
20,-79.3,23.2,AL062006
21,-79.9,23.9,AL062006
22,-80.4,24.7,AL062006
23,-80.6,24.9,AL062006
24,-80.7,25.2,AL062006
25,-80.8,25.3,AL062006
26,-81.0,26.1,AL062006
27,-80.9,27.0,AL062006
28,-80.7,28.1,AL062006
29,-80.4,29.4,AL062006
30,-79.9,30.6,AL062006
31,-79.2,31.9,AL062006
32,-78.4,33.2,AL062006
33,-78.1,33.9,AL062006
34,-78.0,34.5,AL062006
35,-77.6,35.8,AL062006
36,-77.2,36.6,AL062006
37,-77.0,37.1,AL062006
38,-76.8,37.6,AL062006
39,-76.7,38.2,AL062006
40,-76.7,38.9,AL062006
41,-76.7,39.9,AL062006
42,-77.1,41.3,AL062006
43,-77.5,43.1,AL062006
44,-77.0,44.5,AL062006
45,-75.8,45.6,AL062006
46,-74.4,46.5,AL062006
```

**Comment by ChiaLingWeng** [comment]
Still working on the problem but have two findings:

```
chart4 = (
    alt.layer(map_background, storms.mark_line(point=True), storms.mark_point(color='red'))
    .project('conicEquidistant',scale=500)
    .properties(width=1300, height=800)
)
chart4
```
results in 
![1](https://github.com/altair-viz/altair/assets/75072960/e38eb102-6d69-4e1f-bb1c-1b4c6e350587)
in which the point part of `mark_line(point=True)` is overlap with `mark_point()`.
I assume that the mismatch in your chart 3 may due to `translate()` and twist the chart.

```
chart5 = (
    alt.layer(map_background, storms.mark_line(point=True), storms.mark_point(color='red'))
    .project('albersUsa',scale=500)
    .properties(width=1300, height=800)
)
chart5
```
results in 
![2](https://github.com/altair-viz/altair/assets/75072960/609c88a1-a60c-4677-b6f9-fcd2e2fabbff)

I found that the line part of `mark_line(point=True)` is at the same position even the project setting is totally different.
So maybe we can investigate in why the line mark is not transform/project once setting mark_line(point=True)

**Comment by thomascamminady** [comment]
I think this is a vega / vega-lite issue, I filed it here: https://github.com/vega/vega-lite/issues/9162.
Happy to close this issue here at altair.

**Comment by joelostblom** [comment]
Thank you @thomascamminady for following up; closing this
