### ISSUE TITLE
Support for D3/Vega's force layout drawing of graphs?

### ISSUE THREAD

**Issue by nthiery** [altair-viz/altair#312]
I am looking for ways to interactively visualize [networkx](https://networkx.github.io/) graphs in the jupyter notebook, using one of the javascript library like D3.js.

D3.py [enables this natively](https://github.com/mikedewar/d3py/blob/master/examples/d3py_graph.py) in a web page. However it does not support directly the notebook. More importantly, it recommends using instead vincent, which itself recommends using Altair.

Hence, I was wondering whether Altair would expose, now or eventually, [D3/Vega's force layout drawing of graphs](https://vega.github.io/vega/examples/force-directed-layout/), ideally with a straightforward export from networkx.

**Comment by habet700** [comment]
I can recommend bokeh for interactive graph visualization meanwhile.

https://ep2016.europython.eu/conference/talks/networkx-visualization-powered-by-bokeh

**Comment by jakevdp** [comment]
This is out of scope for the project, unfortunately. Altair is simply a Python interface to Vega-Lite, and Vega-Lite is focused on different types of problems.

**Comment by nthiery** [comment]
Thanks for the quick answer. I had missed that scope difference between Vega and Vega-Lite, and therefore Altair.
I'll investigate bokeh, though it does not seem out-of-the-box.

**Comment by jheer** [comment]
I can't speak to the networkx graph conversion aspect, but you should be able to use the ipyvega library to directly use Vega specifications (including force-directed layout) in the notebook environment.
