### ISSUE TITLE
trellis layered plots 

### ISSUE THREAD

**Issue by legru** [altair-viz/altair#313]
I would like to compare multiple conditions of an altair (ultimately vega-lite) layered plot. The perfect solution would be to facet/trellis the plot so I can see the different conditions side by side. Unfortunately I cannot figure out how to give the command to plot the different conditions.

Here is my attempt to implement my idea based on the example for layered plots: (https://github.com/ellisonbg/altair/blob/master/altair/notebooks/07-LayeredCharts.ipynb)

```
import pandas as pd
import numpy as np

data = pd.DataFrame({'x':np.random.rand(10), 'y':np.random.rand(10), 'z':['a', 'b']*5})

chart = LayeredChart(data)
chart += Chart().mark_line().encode(x='x:Q', y='y:Q', column='z:Q')
chart += Chart().mark_point().encode(x='x:Q', y='y:Q', column='z:Q')    
chart 
```
When compared with the example I added the column 'z' with the two conditions, and the two column statements in the Chart definitions. This solution generates seemingly good Vega-lite code, but no plot. Alternatively I tried "chart = LayeredChart(data).encode(column='z:Q')" but I then got the error 'LayeredChart' object has no attribute 'encode'

I am wondering whether it is possible to facet (trellis) layered plots at all and whether it will be possible in future Vega-Lite releases.

I am using jupyter with Anaconda 

ps1: I alreeady posted the issue on stackoverflow: http://stackoverflow.com/questions/43003917/trellis-layered-plots-in-altair-vega-lite  I will cross post the answers

ps2:  In case it is not possible within Altair/Vega-Lite to do this,  I woulld be happy to have suggestisons to implement a temporary work-around.  For example,  am wondering whether it is possible to create layered plots where the layers are shifted of X pixels.  (I had seen a plot with two sub-plots,  but I cannot find the example any more)

**Comment by kanitw** [comment]
Layered plot is "experimental" feature in Vega-Lite 1 and won't support this case. 
However, it will be fully available in Vega-Lite 2 and should support this case.  

For "shifted layer", if you have a compelling use case, please feel free to file a feature request and describe your envisioned use case in the Vega-Lite repository.

**Comment by legru** [comment]
Thanks for your answer.  I had guessed that layered plots were not fully worked out.

About "shfted layers" there was nothing deep about it,  I am just looking for a way to make two plots "side by side" either using vega-lite or directly in jupyter.  If I find a solution to do that,  I can implemet a function that mmimics the trellis of complex layered plots (put plot next to the other) and share it.  
If you have an example of plots "side by side" I will be happy to take  it and go further with it.

**Comment by kanitw** [comment]
Vega-Lite 2 will include horizontal and vertical concat operators for creating side-by-side plots.
(Our current version of VL2 alpha does not have concat yet, but it will be included before we release a beta version.)

**Comment by legru** [comment]
Thank you very much  I  will monitor your development and try again when the beta version will be available.  Do you have already a time frame?

**Comment by kanitw** [comment]
For Vega-Lite, we hope to have concat operators and other 2.0 beta features before the end of April.
The Altair team told me that they would start migrating Altair to Vega-lite 2.0 soon after we release beta.

**Comment by ellisonbg** [comment]
Thanks for your question, closing for now, let us know if you need more information.

**Comment by legru** [comment]
Thanks for your info

I will be  happy to beta/alfa test this feature when it will be available.
