### ISSUE TITLE
Can we use `df.select_columns_by_name` to subselect columns coming from `__dataframe__` protocol

### ISSUE THREAD

**Issue by jcrist** [altair-viz/altair#3134]
With #3114 (and some recent work in ibis) we can now pass ibis tables directly to `altair.Chart` and things _just work_.

```python
import ibis
import altair as alt

t = ibis.examples.penguins.fetch()

chart = (
    alt.Chart(t, width=600)
    .mark_circle(size=50)
    .encode(
        x=alt.X("bill_length_mm").scale(zero=False),
        y=alt.Y("bill_depth_mm").scale(zero=False),
        color="species"
    )
    .interactive()
)
```

However, currently it appears the entire table is loaded into memory, even if only a few columns are needed for the plot. For example, the above `penguins` dataset has 8 columns, but only 3 of them are used to generate the plot. Can `altair` make use of this information to subselect columns before conversion when using the `__dataframe__` protocol?

With some recent work in ibis, the following can all happen without loading data into memory:

```python
df = t.__dataframe__()

# subselect columns
df = df.select_columns_by_name(["bill_length_mm", "bill_depth_mm", "species"])

# view dtypes, as needed for altair's type inference
df.get_column_by_name("bill_length_mm").dtype

# convert to pyarrow here. Only this step will actually execute the query
t = pa.interchange.from_dataframe(df)
```

Especially for wide input tables, having altair handle subselecting columns automatically may be useful for improving performance.

**Comment by jonmmease** [comment]
Thanks for recounting the history on that @binste

Yeah, we've basically decided to not try to implement column subsetting in Altair core, and leave that to VegaFusion.

In the case of the Ibis+VegaFusion integration we're talking about over in https://github.com/hex-inc/vegafusion/discussions/355, what this would look like is that the `select` method would be called with the minimum set of columns required as part of building up the query, and so by the time `collect` is called, the columns will be trimmed down to only those that are used in the chart's transforms.

**Comment by jcrist** [comment]
Thanks for the replies y'all, that makes sense. Closing.
