### ISSUE TITLE
Grouped histogram

### ISSUE THREAD

**Issue by rornor** [altair-viz/altair#314]
Hi,

I wanted to generate grouped histogram similar to this plot: 

![bokeh_plot](https://cloud.githubusercontent.com/assets/3144780/24518965/d88669d8-1583-11e7-9508-bdd77050d958.png)

I tried:

```python
c = Chart(df).mark_bar().encode(
    x=X('volume', bin=Bin(maxbins=10)),
    y='count(*)',
    color='color'
)
```
where df.color is the categorical data I'm grouping by, but the result is stacked bar:

![vega 1](https://cloud.githubusercontent.com/assets/3144780/24518908/b6065602-1583-11e7-8408-0031b0997f16.png)

Any tips?

Thanks

**Comment by kanitw** [comment]
You can turn off the stacking 
```
mark_bar(stacked='none')
```

Note that Vega-Lite 1 doesn't support calculating binning separately for each dataset. 
You might want to adjust the bin parameter to have higher `maxbins`.

**Comment by rornor** [comment]
`stacked` parameter should be by default set to none, but I'm not sure as I found other solution...

Not sure if anyone would read this, but my quest was visualization for simple Flask webapp. As Python is my Bible, first I thought to go with Bokeh, but although it provides what I wanted it's not responsive - IMHO it's very stupid to make Python interface to some JS graph library and make it fixed (and I mean I tried all of their available layout options). But it is interactive (shish). 
OTOH Altair says it's interactive but I don't see how it is interactive, because it is not. If by interactivity it's meant generating json data, that just wont cover any but academic assumptions to some virtual schema.

Finally I used plotly (JS API), to my surprise and it just works as anyone would expect.

This post wont be read by many, but I'd wish they spend time on working solutions, and leave this Python to JS interfaces for playground

**Comment by jakevdp** [comment]
Hi @rornor – sorry for the late response: I'm going through a back-log of github issues this morning. A few replies:

> Altair says it's interactive but I don't see how it is interactive, because it is not.

I don't believe we ever claim that the current release of Altair is interactive. Interactivity will come in version 2.0, which will be released later this spring (hopefully!).

> IMHO it's limiting to back on matplotlib

Altair doesn't have any relationship to matplotlib at the moment. If any part of the docs or installation gave you that impression, please let us know and we'll try to make it more clear.

**Comment by ellisonbg** [comment]
@rornor thanks for your feedback! @jakevdp and @kanitw have addressed, you concerns, closing with question label...
