### ISSUE TITLE
Unwanted box appears when adding dropdown to change color scheme

### ISSUE THREAD

**Issue by stephenwilliams22** [altair-viz/altair#3146]
When making a plot which has a dropdown that enables the user to change the color scheme a small but noticeable box appears when any alternate color scheme is selected.

```
import altair as alt
import pandas as pd

layer1_data = pd.DataFrame({"x": [1,2,3,4], "y": [5,6,7,8],  "z": [1,2,3,4]})
layer1 = alt.Chart(layer1_data).encode(x="x", y="y", color="z").mark_circle()

input_dropdown = alt.binding_select(
    options=["cividis", "bluegreen", "yelloworangered"], name="Color Scheme: "
)
color_select = alt.param(name = "schemeselect", bind=input_dropdown, value = "cividis")

chart = layer1.encode(color=alt.Color('z:Q', scale=alt.Scale(scheme={"expr": "schemeselect"}))).add_selection(color_select)
```
Initially the plot looks clean and as it should
![image](https://github.com/altair-viz/altair/assets/24922527/18c8cbda-0b3f-431b-afc3-88e1871199a9)

However, if the user selects another color scheme you can see this thin box being formed around the plot
![image](https://github.com/altair-viz/altair/assets/24922527/cb9eda13-9c9b-4a8d-b752-999223573f62)

The issue persists even when switching back to the original color scheme. 

It's not a huge deal in this toy example but plots that i'm using in production look very bad

for example
![image](https://github.com/altair-viz/altair/assets/24922527/8b35ee39-d7e4-4507-9215-308e5cbb125c)

**Comment by debbes80** [comment]
Your code errors with v5.0.1 (```add_selection``` doesn't exist) or 4.2.2 (```alt.param``` doesn't exist).
If I change ```add_selection``` with ```add_params``` on v5.0.1, I cannot replicate the issue.

**Comment by stephenwilliams22** [comment]
@debbes80 there was an error in my code for the pandas import. `import pandas a pd`  should have been `import pandas as pd` but that doesn't seem to be related to your issue running my code. I'm using altair v5.0.1 and have had co-workers reproduce the plotting issue

```
import altair as alt
import pandas as pd
from importlib.metadata import version
version('altair')
>>> '5.0.1'
```

**Comment by debbes80** [comment]
Yes, sorry, it is a deprecation warning instead of an error. You get that warning? v5 started using params instead of selections.
Even disregarding that, it still runs fine in both JupyterLab as VSCode here. (Looks like you're using VSCode.)

**Comment by stephenwilliams22** [comment]
Interesting this looks like a VSCode issue not an altair one. thanks for your investigation @debbes80!
