### ISSUE TITLE
chart.serve() throws vega error

### ISSUE THREAD

**Issue by SimonTulettIdeaco** [altair-viz/altair#315]
When I try and use the .serve() method in Python 2.7 of Chart I get the following error vg.embed is not a function which appears to be a Vega issue relating to Vega versions that has been resolved in the last few weeks. See issue below

https://github.com/vega/vega-embed/issues/21

**Comment by jakevdp** [comment]
This is due to the fact that the javascript package was silently updated to vega version 3, which is incompatible with the current Altair release. This has been fixed on master; if you install the master version, Altair should work as expected. This fix will be included in the next release.

**Comment by SimonTulettIdeaco** [comment]
When is the next release scheduled? Thanks

**Comment by jakevdp** [comment]
The vega-lite team keeps pushing back the date, but they seem to have committed to having a beta release later this month. I had hoped the Altair release could be soon after that, but it appears they've made some pretty fundamental design changes to the vega-lite schema, which will make the Altair Python wrappers far more difficult to generate. With all that in mind, I don't have any estimate for the date of the next release.
