### ISSUE TITLE
Add an example of reading in years in a convenient manner

### ISSUE THREAD

**Issue by joelostblom** [altair-viz/altair#3162]
As per @mattijn suggestion here https://github.com/altair-viz/altair/discussions/3140#discussioncomment-6714090. Since it is hard to discover it would be great to include it in the docs.

**Comment by ChiaLingWeng** [comment]
Hi, I would like to take this issue, but I'm not sure it's better to put it under [Encoding Data Types]
(https://altair-viz.github.io/user_guide/encodings/index.html#encoding-data-types) or [Times and Dates](https://altair-viz.github.io/user_guide/times_and_dates.html)

**Comment by joelostblom** [comment]
Thank you @ChiaLingWeng ! I think either of those places could technically work, but the data that is used in the Encoding Data Type section is more amenable to show this issue since it already has a column with years as integers. Maybe you could expand upon the example already given there and add another similar example with line charts underneath? Something like:

```python
pop = data.population().assign(year=lambda df: df['year'].astype(str))

base = alt.Chart(pop).mark_line().encode(
    alt.Y('mean(people):Q').title('total population')
).properties(
    width=200,
    height=200
)

alt.hconcat(
    base.encode(x='year:Q').properties(title='year=quantitative'),
    base.encode(x='year:O').properties(title='year=ordinal'),
    base.encode(x='year:T').properties(title='year=temporal')
)
```

![image](https://github.com/altair-viz/altair/assets/4560057/564db957-6a3a-4a9a-be88-23a86dff533a)

But please feel free to modify as you see fit and for what you think will make the best explanation of this feature. It would be helpful to also add a link in the "Times and Dates" section saying something like "If you want to plot four digit years stored as integers as temporal data, please see the ... section".

How does that sound to you?

**Comment by ChiaLingWeng** [comment]
Great, you've almost solved it!
I'll try to make it as clear as possible.
