### ISSUE TITLE
Example in docstring of get_inline_table_names does not work. Blocks conda-forge release.

### ISSUE THREAD

**Issue by binste** [altair-viz/altair#3174]
@jonmmease The example in the docstring of `get_inline_table_names` does not retrieve the table name. I don't know if there is a bug in the function or it's just the docstring that needs to be adapted.

```python
spec = {
    "data": [
        {
            "name": "foo",
            "url": "https://path/to/file.csv"
        },
        {
            "name": "bar",
            "url": "table://inline_dataset_123"
        }
    ]
}
from altair.utils._vegafusion_data import get_inline_table_names
get_inline_table_names(spec)  # Returns an empty set
```
This came up in https://github.com/conda-forge/altair-feedstock/pull/49

Btw, this did not come up in the tests as docstring tests are only run in the `tests` folder. We should probably change the pytest command to include the altair package -> `pytest --doctest-modules altair tests`.

**Comment by jonmmease** [comment]
Fix in https://github.com/altair-viz/altair/pull/3175. This was an error in the doctest itself.
