### ISSUE TITLE
version 5.1.0 on `conda`?

### ISSUE THREAD

**Issue by jbloom** [altair-viz/altair#3176]
Very excited to see version 5.1.0 released. Just a request to ask if you would be willing to put it on conda as well as PyPI.

**Comment by mattijn** [comment]
PyPI: see https://pypi.org/project/altair/5.1.0/
Conda: see https://github.com/conda-forge/altair-feedstock/pull/49

**Comment by binste** [comment]
Thanks for the feedback @jbloom. As linked to by mattijn, there were some minor changes necessary to the conda feedstock. In general, we try to make conda versions available shortly after the pypi releases. Altair 5.1 is now available on [conda-forge](https://anaconda.org/conda-forge/altair).
