### ISSUE TITLE
`sanitize_dataframe` utilizes deprecated Pandas `convert_dtype` param

### ISSUE THREAD

**Issue by cdkini** [altair-viz/altair#3181]
This particular utility function uses a deprecated Pandas codepath: https://github.com/altair-viz/altair/blob/ec13a671d53419f371b629d449f719240d1f1756/altair/utils/core.py#L410C1-L410C76

As this emits a `FutureWarning` and will eventually be removed, could it be replaced with the suggestion?

```
FutureWarning: the convert_dtype parameter is deprecated and will be removed in a future version.  Do ``ser.astype(object).apply()`` instead if you want ``convert_dtype=False``.
```

Versions: Altair 4.2.2 and Pandas 2.1.0
OS: Darwin 22.6.0

**Comment by binste** [comment]
Thanks for reporting this @cdkini. Makes sense, I'll look into it. 

For my own reference, it's deprecated since [version 2.1](https://pandas.pydata.org/docs/whatsnew/v2.1.0.html#deprecations) (search for `convert_type`)
