### ISSUE TITLE
Script error for "vega-embed"

### ISSUE THREAD

**Issue by AnnaGo12** [altair-viz/altair#3184]
Hi, I have an error using altair for plotting images: 

Error loading script: Script error for "vega-embed" https://requirejs.org/docs/errors.html#scripterror

The same code worked perfectly fine last week. Does someone have a similar issue?
Thanks!

**Comment by joelostblom** [comment]
Any chance you were offline when that happened?

**Comment by joelostblom** [comment]
Closing for now, please re-open with more details if the error persists.
