### ISSUE TITLE
Compatibility with ipywidgets got broken in 5+ version

### ISSUE THREAD

**Issue by ataymano** [altair-viz/altair#3186]
Hi,
There was extremely nice and easy way to use ipywidgets together with altair and looks like it got broken in 5+ versions.
Code:
```
from ipywidgets import *
import altair as alt
import pandas as pd
import numpy as np

data = pd.DataFrame({
    'x': np.random.uniform(0, 1, 10),
    'y': np.random.uniform(0, 1, 10),
    'z': np.random.uniform(0, 1, 10)
    })

interact(
    lambda x, y: alt.Chart(data).mark_circle(size=40).encode(
        x=x,
        y=y
    ).interactive(),                    # interactive is essential here - everything works without it, but would be great to be able to use it
    x = data.columns,
    y = data.columns
)
```
4.2.2 output:
![image](https://github.com/altair-viz/altair/assets/41013086/6f89e58b-8bfb-432a-b430-d9eccf97b586)

5.0.0 output:
![image](https://github.com/altair-viz/altair/assets/41013086/a06e8896-8306-4b32-bc5b-1b005356bb60)

Environment:
Windows, python 3.10.11, vs code/notebook/jupyterlab

Please let me know if you need any extra information.

**Comment by binste** [comment]
Hmm I can't replicate this. Your code works for me in VS Code 1.79, Altair 5.1.1, MacOS, ipywidgets 8.1.0

What version of `ipywidgets` are you using? Could you try to
* Update to Altair 5.1.1
* Clear all cell outputs
* Restart the kernel
* and then close and open again the notebook?

**Comment by binste** [comment]
No worries! Glad it works again.
