### ISSUE TITLE
HConcat / VConcat allows separate 'view' configs per chart as per Vega, but Altair gives error when using  `.configure_view()`

### ISSUE THREAD

**Issue by plasmak11** [altair-viz/altair#3216]
Very particular case for me.  I was trying to concat two charts together. One chart without a view box, and one without a view box, to make sure I can use this grid-less, axis-less, and view-border-less `chart1` interactive MTA subway menu with another chart created using `.mark_image()`. 
<img width="93" alt="image" src="https://github.com/altair-viz/altair/assets/10780685/df3ffa24-56df-4c66-83d2-1fb17dee6e59">. 

I wanted a regular `chart2` which looks better with a view border.

The single-chart answer to this is `fig.configure_view(strokeWidth=0)`

But when trying to use HConcat / VConcat, Altair throws an error oddly.

## Example Chart with no `.configure_view(strokeWidth=0)`

```
import altair as alt
from vega_datasets import data

iris = data.iris.url

chart1 = alt.Chart(iris).mark_point().encode(
    x=alt.X('petalLength:Q', axis=alt.Axis(domain=False, grid=False)),
    y=alt.Y('petalWidth:Q', axis=alt.Axis(domain=False, grid=False)),
    color='species:N'
).properties(
    height=200,
    width=200
)

chart2 = alt.Chart(iris).mark_bar().encode(
    x='count()',
    y=alt.Y('petalWidth:Q').bin(maxbins=30),
    color='species:N'
).properties(
    height=200,
    width=100
)

chart1 | chart2
```

<img width="533" alt="image" src="https://github.com/altair-viz/altair/assets/10780685/6d31469c-302d-4d7a-abeb-ad69dac14667">

---------

### Code

```python
chart1.configure_view(strokeWidth=0) | chart2
```

### Result

```bash
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[3], line 1
----> 1 chart1.configure_view(strokeWidth=0) | chart2

File [~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:972](https://vscode-remote+codespaces-002bliterate-002dbroccoli-002d7v976ww6v67fp6j7.vscode-resource.vscode-cdn.net/workspaces/data-expressions/mynewbook/personal-analysis/~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:972), in TopLevelMixin.__or__(self, other)
    970 if not isinstance(other, TopLevelMixin):
    971     raise ValueError("Only Chart objects can be concatenated.")
--> 972 return hconcat(self, other)

File [~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:2897](https://vscode-remote+codespaces-002bliterate-002dbroccoli-002d7v976ww6v67fp6j7.vscode-resource.vscode-cdn.net/workspaces/data-expressions/mynewbook/personal-analysis/~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:2897), in hconcat(*charts, **kwargs)
   2895 def hconcat(*charts, **kwargs):
   2896     """Concatenate charts horizontally"""
-> 2897     return HConcatChart(hconcat=charts, **kwargs)

File [~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:2836](https://vscode-remote+codespaces-002bliterate-002dbroccoli-002d7v976ww6v67fp6j7.vscode-resource.vscode-cdn.net/workspaces/data-expressions/mynewbook/personal-analysis/~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:2836), in HConcatChart.__init__(self, data, hconcat, **kwargs)
   2832 @utils.use_signature(core.TopLevelHConcatSpec)
   2833 def __init__(self, data=Undefined, hconcat=(), **kwargs):
   2834     # TODO: move common data to top level?
   2835     for spec in hconcat:
-> 2836         _check_if_valid_subspec(spec, "HConcatChart")
   2837     super(HConcatChart, self).__init__(data=data, hconcat=list(hconcat), **kwargs)
   2838     self.data, self.hconcat = _combine_subchart_data(self.data, self.hconcat)

File [~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:2586](https://vscode-remote+codespaces-002bliterate-002dbroccoli-002d7v976ww6v67fp6j7.vscode-resource.vscode-cdn.net/workspaces/data-expressions/mynewbook/personal-analysis/~/.cache/pypoetry/virtualenvs/data-expressions-XOHyUNvQ-py3.10/lib/python3.10/site-packages/altair/vegalite/v5/api.py:2586), in _check_if_valid_subspec(spec, classname)
   2584     val = spec.get(attr, Undefined)
   2585 if val is not Undefined:
-> 2586     raise ValueError(err.format(attr, classname))

ValueError: Objects with "config" attribute cannot be used within HConcatChart. Consider defining the config attribute in the HConcatChart object instead.
```

-------

## Hacking the Vega directly: 

After much scouring the internet since I found it ludicrous that we can't do this, I ended up at this solution.

### Code
```python
chart1.view = {'strokeWidth': 0}

chart1 | chart2
```

### Result
<img width="536" alt="image" src="https://github.com/altair-viz/altair/assets/10780685/939dcf34-6aaf-48ea-892c-33a1135d9548">

### Vega Editor JSON
<img width="576" alt="image" src="https://github.com/altair-viz/altair/assets/10780685/b0cdf166-ad7d-4fa0-a9a0-a7b7fd203859">

Link: https://vega.github.io/editor/#/url/vega-lite/N4Igxg9gdgZglgcxALlANzgUwO4tJKAFzigFcJSBnAdTgBNCALFAZgAY2AacaYsiygAlMiRoVYcAvpO6MCYAIbjkAbVABbBQCcA1nhCEAngAdMKEMYglxMkJiiQ6JJKh4AbCFv3xMbuucpTMCxKEG4jU3MoCHUSBTcQWwAPfQUkuFDXOhiFEhQYeMpMbgQtenzCzFsfP3NTQniAGXsEJjCDEzNkEABHUgUiOAbiNDNbQ1T0zNBszTzkArcikrL-BcrqrFru+vjaBmZwzvM+geJhuFHE20YRBDEUACYObgwcfUpCLQgdTH225BsWzYegA55AzgabR6VwRLogABG2kS3Hsjmc+kgHi8rhqaxAgUwwUwoSOkW60ViUHiKJAKVcCgQpUwCCU8MgpCI7ThJ36gwuV3G+gR8yhSRFUEy7E2vnxuzc-0OHXJvT55yUlzGNzuD2Q4O4IIOKAAjFIALrcOhKBT6UhaBLdMSEYyUZAAejdYDoUAAdAArSh0XyXLQ+qCYQhuqDGdRu0asgC0VoaRUIlAAAmhjT7HgBOH1sN3JhRuuBlSj+yjQWkAEkoYFumnMTpd7rjLIUPoQQ0YpARPrgEDd9cbJfjCgTbiGmDjAFYfQAOAuV6uSIA

### Possible Solution
If we can add 'view' as a passable config for concat Schema check it should be good.

**Comment by ChristopherDavisUCI** [comment]
Thanks for raising this issue.  I agree that this does seem a little awkward.  The response here https://github.com/altair-viz/altair/issues/2032 makes me wonder if when `configure_view` was written, there was no alternative to define these view properties on the single-view level in Vega-Lite.

I could see some different alternatives, like if a chart with a `config` property gets put into a multi-view chart, maybe those config settings could get moved into the `view` property?

Or maybe a different method like `set_view`, that doesn't do anything with `config`?  Or the same method `config_view` with a keyword argument like `single=True`?

These are just some first ideas... not sure if any of them are reasonable...

**Comment by joelostblom** [comment]
I agree that it would be nice to support using `configure_view` on individual charts within a concat spec. I have been in the same position where I want to remove the outline of a single chart within a concat spec. Interestingly, this comment https://github.com/vega/vega-lite/pull/4463#issue-401012878 says it is not possible and references a still open issue but clearly it seems to work on the Vega-Lite level now.

**Comment by plasmak11** [comment]
Adding a bit more info: I really think it's a hack that happens to work since `.configure_view()` ends up applying the 'view' config outside the hconcat element. (line 2: `continuousWidth` )

`(chart1 | chart2)['config']['view']`

The hack above places it inside each item of "hconcat": line 19. 

which ends up bypassing the Vega's schema validation since it's in the chart config itself. 

<img width="599" alt="image" src="https://github.com/altair-viz/altair/assets/10780685/49f61fdf-68c5-41e6-90bd-8e171c294f6a">

**Comment by mattijn** [comment]
Then you can define a `ViewConfig` object for `view` within `alt.Chart()`. See the following:
```python
import altair as alt
from vega_datasets import data

iris = data.iris.url

chart1 = alt.Chart(iris, view=alt.ViewConfig(strokeWidth=0)).mark_point().encode(
    x=alt.X('petalLength:Q', axis=alt.Axis(domain=False, grid=False)),
    y=alt.Y('petalWidth:Q', axis=alt.Axis(domain=False, grid=False)),
    color='species:N'
).properties(
    height=200,
    width=200
)

chart2 = alt.Chart(iris).mark_bar().encode(
    x='count()',
    y=alt.Y('petalWidth:Q').bin(maxbins=30),
    color='species:N'
).properties(
    height=200,
    width=100
)

chart1 | chart2
```
![image](https://github.com/altair-viz/altair/assets/5186265/2ce1ae85-1038-487e-8a8c-19dd788252be)

I think that avoids patching the VL-specification

**Comment by joelostblom** [comment]
Neat @mattijn ! That's a great solution that I didn't know about!

**Comment by mattijn** [comment]
Btw, see here for more documentation on the intentional difference between local and global settings: https://altair-viz.github.io/user_guide/customization.html#global-config-vs-local-config-vs-encoding

But I can understand it feels strange that this works:
```
chart1.configure_view(strokeWidth=0)
```
But adding ` | chart2` errors.

I think the suggestion of @joelostblom to improve this alias in #2903 is the most sensible. 

And documentation! Feel free to add a section on this around here: https://altair-viz.github.io/user_guide/customization.html#removing-the-chart-border, that would be awesome!

**Comment by plasmak11** [comment]
@mattijn Thanks for this. 

I'll try to add it to the doc when I get a chance since it's taken me few hours and some stackoverflow luck to get the desired output.

**Comment by ChristopherDavisUCI** [comment]
@mattijn @joelostblom Do you think there's a way to eventually have this single-view chart configuration look more similar to the `configure_view` method?  I kind of feel like the single-view configuration should be the first one users find, but maybe that's not the most natural, I'm not really sure.  What do you think?

**Comment by mattijn** [comment]
Just realized that you should be able to use `.properties()` for this as well. As such:
```python
alt.Chart().properties(
    height=200,
    width=200,
    view=alt.ViewConfig(strokeWidth=0)
)
```
In general, coming from a Vega/VL background it was always a bit hard for me to map this `properties` object as there is no such a thing in VL. But as such, this is probably more in line what you had in mind. 
With this two options available we can close this issue.
