### ISSUE TITLE
Add .save_html() method

### ISSUE THREAD

**Issue by DSLituiev** [altair-viz/altair#322]
I am using example from documenation:
```
html = chart.to_html()
with open('whatever.html', 'w') as f:
    f.write(html)
 ```
here is suggestion: wrap this code into `save_html` method, or accept `to_html(file=)` keyword for saving.

**Comment by jakevdp** [comment]
Currently that's available via ``chart.savechart('filename.html')``. I think you're right though that a ``save_html()`` method would be useful.

**Comment by stsievert** [comment]
What about adding a new function to save arbitrary file types, `chart.save(format=, file=)`? I think that'd be cleaner.

**Comment by jakevdp** [comment]
> What about adding a new function to save arbitrary file types, chart.save(format=, file=)? I think that'd be cleaner.

That's exactly the API provided by ``chart.savechart``. We could provide ``save`` as an alias to that if you think it would be more clear.

**Comment by stsievert** [comment]
> We could provide save as an alias to that function if you think it would be more clear.

I think this a documentation issue, and I'll try to address this with a PR sometime this week.

**Comment by DSLituiev** [comment]
Also it would be nice to have `save` and `savechart` referenced in
`to_html()` document string.

**Comment by jakevdp** [comment]
> Also it would be nice to have `save` and `savechart` referenced in `to_html()` document string.

Good idea. Done in 76f937094701f51984d5c89e8b233d1a4cea1377

**Comment by jakevdp** [comment]
In v2, ``to_html`` is now gone, and ``save('chart.html')`` works.
