### ISSUE TITLE
Cannot reproduce violinplot

### ISSUE THREAD

**Issue by wangjiawen2013** [altair-viz/altair#3229]
Hi,
I copied the code of violinplot from https://altair-viz.github.io/gallery/violin_plot.html, but the x-labels are on the top, how to put them on the bottom ( I am using altair 5.1.1)?

![image](https://github.com/altair-viz/altair/assets/29703450/1d41b875-b96d-45e8-9673-93c24401dcf5)

**Comment by joelostblom** [comment]
I just tried the code and it works for me on altair 5.1.2; I think this used to be an issue that ws fixed in v5. If you recently updated altair, please make sure to clear output in  all your notebooks and then reopen jupyterlab [as mentioned here](https://github.com/altair-viz/altair/issues/3224#issuecomment-1760254091) to make sure the new version of vega-lite is loaded correctly in the browser

**Comment by wangjiawen2013** [comment]
It works, thanks!

**Comment by wangjiawen2013** [comment]
violinplot can also be presented with seaborn. There is a parameter named "density_norm{“area”, “count”, “width”}",
they are method that normalizes each density to determine the violin’s width. If area, each violin will have the same area. If count, the width will be proportional to the number of observations. If width, each violin will have the same width.

In altair, all the violin have the same area, the chart become ugly when the data distribution of the each column differ a lot and we cannot see the distribution clearly, becuase some are too slim! Could we adjust the width of the violins to the same width ? And, could we add edges to the violin ?  then the chart will become more perfect, just like the following one:
![image](https://github.com/altair-viz/altair/assets/29703450/b5a7fd50-45e8-42f1-8f31-a883c86503a3)

**Comment by joelostblom** [comment]
You could add the annotations by creating layers with other plots (boxplot, point plots, etc). You could add edges by setting the `stroke` to a color in the mark. You could scale the area by counts by setting `counts=True` in the density transform, but I don't think there is an easy way to normalize the density to the same width (maybe you could use a calculate transform to normalize the density values of each group each group's max).

**Comment by joelostblom** [comment]
Also see https://github.com/vega/vega-lite/issues/3442 for adding more official support for violin plots in vega-lite which will eventually make some of these things you are asking about easier
