### ISSUE TITLE
investigate if we can switch from `black` to `ruff` for formatting

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#3241]
With the recent introduction of ruff formatter ([docs](https://docs.astral.sh/ruff/formatter/)), we can investigate if we can reduce the number of development dependencies by 1.

All of the `black` related config within `pyproject.toml` can be rewritten to `ruff` style config, but we also use `black` to format code within `tools/update_init_file.py` ([around here](https://github.com/altair-viz/altair/blob/main/tools/update_init_file.py#L60-L61)), as such:
```python
# Format file content with black
new_file_content = black.format_str("\n".join(new_lines), mode=black.Mode())
```
I don't think this usage of `black` is possible with `ruff` yet, but please correct me if I'm wrong.

([initial attempt in this branch](https://github.com/altair-viz/altair/compare/main...ruff-format))

**Comment by binste** [comment]
I'm in favour of moving to ruff! To format strings in the code generation, we can pass the strings through stdin to the `ruff format` command:

```python
import subprocess

code = """import altair as alt

def some_function():
    d = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5, 'f': 6, 'g': 7, 'h': 8, 'i': 9, 'j': 10}
    return
    
def another_function():
    c = {'a': 1, 'b': 2, 'c': 3, 'd': 4, 'e': 5}
    return
"""
r = subprocess.run(
    # Name of the file does not seem to matter but ruff requires one
    ["ruff", "format", "--stdin-filename", "placeholder.py"],
    input=code.encode(),
    check=True,
    capture_output=True,
)
print(r.stdout.decode())
```
