### ISSUE TITLE
Better support for non algined observations

### ISSUE THREAD

**Issue by Delaunay** [altair-viz/altair#3245]
I have data as follow

```
data = [
    {"time": 0, "value": 1, "name": "metric1"},
    {"time": 0.5, "value": 2, "name": "metric2"},
    {"time": 1, "value": 0.25, "name": "metric1"},
    {"time": 1.5, "value": 1, "name": "metric2"},
    {"time": 2, "value": 1, "name": "metric1"},
    {"time": 2.5, "value": 0.25, "name": "metric2"},
]
```

i.e N metrics that have are saved a different time but the time do not always match.

* Simple filter works as expected

```
alt.Chart(data=alt.InlineData(d1)).mark_point().encode(
    alt.X("time", type='quantitative'),
    alt.Y("value", type='quantitative'),
).transform_filter(
    (datum.name == "metric1")
).show()
```
![visualization(9)](https://github.com/altair-viz/altair/assets/4311937/752063f7-3dbe-41d5-b1c1-2bcf20f3ddbc)

* But pivot table fails

```
alt.Chart(data=alt.InlineData(d1)).mark_point().encode(
    alt.X("time", type='quantitative'),
    alt.Y("metric1", type='quantitative'),
).transform_pivot(
    "name",
    value="value"
).show()
```
![visualization(10)](https://github.com/altair-viz/altair/assets/4311937/cd27db1a-e62a-411f-988d-6bc1dccfc3b7)

For reference, pandas pivot table also fails 

```
data = pd.pivot_table(df, index=["time"], columns=["name"]).reset_index()
print(data)

name      metric1 metric2
0     0.0    1.00     NaN
1     0.5     NaN    2.00
2     1.0    0.25     NaN
3     1.5     NaN    1.00
4     2.0    1.00     NaN
5     2.5     NaN    0.25
```

**Comment by joelostblom** [comment]
To use the transform_fold, you need to reference the "key" or "value" column in an encoding as in this example https://altair-viz.github.io/user_guide/transform/fold.html. Try that and if it doesn't work, also let us know what output you are expecting in your chart

**Comment by Delaunay** [comment]
Fold does not help, my data is already `long-form`
I guess the only solution is to `.transform_filter` on each plots and combine them since pivot table seems to require and index, if not it will generate nans.
