### ISSUE TITLE
Add label to the mark_point()

### ISSUE THREAD

**Issue by Tovi163** [altair-viz/altair#325]
hi, thanks a lot for this very promising project
I'd like to add the label to the point, is there some way to make it ? or if I got the wrong way in my work
![odi ls vku j8f23mb5zsr](https://cloud.githubusercontent.com/assets/15190164/25772590/6cbb29c4-32a1-11e7-8abd-cf6cf85130de.png)

**Comment by kanitw** [comment]
Currently, we don't support labeling yet, but we plan to add labeling support in the future.

**Comment by kanitw** [comment]
Please follow the discussion about this feature in Vega-Lite https://github.com/vega/vega-lite/issues/64

**Comment by Tovi163** [comment]
@kanitw thanks a lot for your advices

**Comment by joelostblom** [comment]
Closing this as it is an upstream issue and there is nothing to do on the Altair side of things. When https://github.com/vega/vega-lite/pull/7378 is merged, this will be in a following altair release
