### ISSUE TITLE
saving png with chart.save() is not enabled with vl-convert-python

### ISSUE THREAD

**Issue by HorvathAP** [altair-viz/altair#3254]
I'm trying to save a chart as png on Google Colab. 
altair.__version__==5.0.0
vl-convert-python.__version__==1.0.1

The documentation would suggest that I can use chart.save('chart.png') so long as vl-convert-python is installed, but  I'm still getting this error: 

"ValueError: Saving charts in 'png' format requires the altair_saver package"

I've also tried altair_saver, but got a wide variety of errors and I ultimately found this issue which concluded that vl-convert was recommended: https://github.com/altair-viz/altair_saver/issues/121

**Comment by binste** [comment]
You're right that it should be enough to have vl-convert-python installed and then call `chart.save("chart.png")`. Can you provide a link to a minimal Colab notebook which shows this issue? Without it, it's difficult to know what's going on.

**Comment by jonmmease** [comment]
Hi @HorvathAP,

Could you try checking the versions from Python.

```
import vl_convert as vlc
print(vlc.__version__)
```

And for Altair
```
import altair as alt
print(alt.__version__)
```

I ask because the error message looks like it's coming from Altair 4. Did you have to install Altair 5 manually with `!pip install`, or does Colab ship with Altair 5?

**Comment by HorvathAP** [comment]
Yes, I was installing altair 5 with `!pip install altair==5.0.0` But it looks like I wasn't paying close enough attention to restarting my runtime with each pip install. Verifying the version reminded me that a runtime restart is necessary. Thanks, and sorry for the confusion.

**Comment by binste** [comment]
No worries! Glad it works :)
