### ISSUE TITLE
Vega 5.26.1 breaks `JupyterChart`

### ISSUE THREAD

**Issue by manzt** [altair-viz/altair#3268]
First posted in anywidget:

- https://github.com/manzt/anywidget/issues/381

It seems there is a bug in latest patch release of Vega (https://github.com/vega/vega/pull/3829), that breaks the altair "hello, world":

```python
import altair as alt
from vega_datasets import data

source = data.cars()
brush = alt.selection_interval()

points = alt.Chart(source).mark_point().encode(
    x="Horsepower",
    y="Miles_per_Gallon",
    color=alt.condition(brush, "Origin", alt.value("lightgray"))
).add_params(
    brush
)

bars = alt.Chart(source).mark_bar().encode(
    y="Origin",
    color="Origin",
    x="count(Origin)"
).transform_filter(
    brush
)
```

```python
alt.jupyter.JupyterChart(points & bars)
```

<img width="614" alt="image" src="https://github.com/altair-viz/altair/assets/24403730/2fdb551f-3d33-4e9c-bd3b-4e441d10fe18">

This occurs because the  JS `embed` dependency is coming from a CDN and `vega-embed`'s package.json says the patch fix is within semver. The CDN [esm.sh](https://esm.sh/) let's you pin an exact dependency version in your import URL, so you can fix this bug by changing the import in 

```diff
-- import embed from "https://cdn.jsdelivr.net/npm/vega-embed@6/+esm";
++ import embed from "https://esm.sh/vega-embed@6?deps=vega@5.26.0";
```

**Comment by jonmmease** [comment]
Thanks for the report. Interesting, when I pull 5.26.1 from `https://esm.sh/vega-embed@6?deps=vega@5.26.1` it works as well.

**Comment by manzt** [comment]
Interesting. Maybe something else is going on, sorry I don't have the time to dig into it more deeply.
