### ISSUE TITLE
dips in cumulative sum?

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#327]
I may be glossing over something but I think this is a bug in the plot - showing dips where there aren't any:

```python
import pandas as pd
import altair as alt

data = {
    'link_status': ['O,C','O,X','R,C','O,O','O,R,C','O,R','O,O,C','R,R,C','O,R,R','O,R,R,C',
        'R,R','R,X','O,R,X','O,O,O,C','O,O,R','R,R,R,C','O,R,R,R','R,R,R','R,O','O,R,R,R,C',
        'O,R,O','O,O,X','R,R,X','O,O,O,R','O,O,O,O,C','O,R,R,R,R','O,R,R,X','R,R,O'
    ],
    'cum_sum': [0.642917430986169,0.745416896431425,0.835492184246953,0.87849289323535,
        0.920233178406239,0.935875938284248,0.949763107845013,0.958237207260942,
        0.964291743098617,0.970177472175019,0.97505036068378,0.979585635669994,
        0.982151498441351,0.984233448497057,0.986157845575575,0.987699613995206,
        0.989207621062582,0.990648105425449,0.991874767890703,0.992955131162853,
        0.99393421037824,0.994654452559673,0.995138365275324,0.99558851663872,
        0.996004906649861,0.996410042876917,0.996803925319889,0.99719780776286
    ]}

df = pd.DataFrame(data)

alt.Chart(df).mark_line().encode(
    x='link_status',
    y='cum_sum')
```

Has dips in the plot even though this is a cumulative sum of data.

There should not be any dips in the plot.

![image](https://cloud.githubusercontent.com/assets/1798497/26075162/5059c578-3982-11e7-9968-ff6dd0fd7538.png)

**Comment by jheer** [comment]
The x-axis is being sorted alphabetically by label. Perhaps adjust the sort order for the x encoding?

**Comment by afonit** [comment]
@jheer  oh my,
I now see it changed the sorting from what I had input it as.  Sorry for the false flag, I just did not see that.

**Comment by afonit** [comment]
I have tried doing ascending and descending, it does flip the graph around, but it is still showing the bumps.

'''python
import pandas as pd
import altair as alt

data = {
    'link_status': ['O,C','O,X','R,C','O,O','O,R,C','O,R','O,O,C','R,R,C','O,R,R','O,R,R,C','R,R',
        'R,X','O,R,X','O,O,O,C','O,O,R','R,R,R,C','O,R,R,R','R,R,R','R,O','O,R,R,R,C',
        'O,R,O','O,O,X','R,R,X','O,O,O,R','O,O,O,O,C','O,R,R,R,R','O,R,R,X','R,R,O'
    ],
    'cum_sum': [0.642917430986169,0.745416896431425,0.835492184246953,0.87849289323535,
        0.920233178406239,0.935875938284248,0.949763107845013,0.958237207260942,
        0.964291743098617,0.970177472175019,0.97505036068378,0.979585635669994,
        0.982151498441351,0.984233448497057,0.986157845575575,0.987699613995206,
        0.989207621062582,0.990648105425449,0.991874767890703,0.992955131162853,
        0.99393421037824,0.994654452559673,0.995138365275324,0.99558851663872,
        0.996004906649861,0.996410042876917,0.996803925319889,0.99719780776286
    ]}

df = pd.DataFrame(data)

alt.Chart(df).mark_point().encode(
    x=alt.X('link_status', sort=alt.SortField(field='link_status', op='max', order='ascending')),
    y='cum_sum')
```

**Comment by afonit** [comment]
@jheer , what do you mean by the x encoding?
I tried the 
    y=alt.Y('cum_sum', sort=alt.SortField(field='cum_sum', op='max', order='ascending')))
and
y=alt.X('link_status', sort=alt.SortField(field='link_status', op='max', order='descending')

but doing the y is flipping it vertically from 0 to 1 or 1 to 0, and doing it by x is just doing it by the alpha characters.

is there a way to sort by the values?  Reading through the docs, will post working example if I find one.

**Comment by jheer** [comment]
I think the key bit is that you do **not** want to sort by `link_status`. Have you tried `sort='none'`? I'm not 100% sure of the Altair API here, but the relevant underlying Vega-Lite parts are here: https://vega.github.io/vega-lite/docs/sort.html

Other alternatives might include:
- explicitly add the `link_status` array as the domain setting for the x-axis scale
- add an integer index field with the appropriate order, and sort the x-axis using that field instead

Hope that helps!

**Comment by afonit** [comment]
@jheer 
Thanks for the help - I just chose the second option since I can get that quickly with the reset_index in pandas. and that additional column works.

```python
dff = df.reset_index()

alt.Chart(dff).mark_point().encode(
    x=alt.X('link_status', sort=alt.SortField(field='index', order='ascending', op='sum')),
    y='cum_sum')
```
