### ISSUE TITLE
Multi-line items in legend AND specify colors 

### ISSUE THREAD

**Issue by arogozhnikov** [altair-viz/altair#3279]
Altair has support for multi-line legends and with specifying custom colors. But I don't see a way to use these two together:

Here is an example with just multi-line legend:

```python
import altair as alt
from vega_datasets import data

source = data.barley()[:40]
# tuple is represented as two different lines in the interface
source['site_year'] = [(v, s) for v, s in zip(source['site'], source['year'])]

alt.Chart(source).mark_point().encode(
    x='yield:Q',
    y='site:O',
    color=alt.Color('site_year:O',),
)
```
![visualization (1)](https://github.com/altair-viz/altair/assets/6318811/5d0a8fa6-a188-4727-bb06-f05fd83c99d6)

But alt.Scale does not accept tuples as valid arguments, e.g. this fails:

```python
site_year_unique = list(source['site_year'].unique())
colors = ['red', 'green', 'blue', 'cyan', 'yellow', 'magenta']

alt.Chart(source).mark_point().encode(
    x='yield:Q',
    y='site:O',
    color=alt.Color('site_year:O', scale=alt.Scale(domain=site_unique, range=colors)),
)
```

### Alternative approaches

Another approach I've tried is encoding color with integer - in this case, alt.Scale can be used to map integer to color. 
(that's not super-pretty, but avoid having tuples in domain field).
I did not find a way to map integer to text in legend however.

**Comment by joelostblom** [comment]
It seems like Vega-Lite does not support passing these values as a list of lists to domain; the error is:

```
'['University Farm', 1931]' is an invalid value for `0`. Valid values are of type 'null', 'string', 'number', 'boolean', or 'object'.
```

However, it seems like you could achieve what you want by leaving out `domain`? Like so:

```py
alt.Chart(source).mark_point().encode(
    x='yield:Q',
    y='site:O',
    color=alt.Color('site_year:O', scale=alt.Scale(range=colors)),
)
```

![image](https://github.com/altair-viz/altair/assets/4560057/40aa0ca0-0b6a-4598-8bf0-2edfa843ddd1)

**Comment by arogozhnikov** [comment]
@joelostblom  interesting suggestion. Is order alphabetical in this case?

**Comment by binste** [comment]
To customize legends, I find [Vega expressions](https://vega.github.io/vega/docs/expressions/) very helpful. I often use them to manipulate labels (`labelExpr`) or combine different symbols in the same legend (`symbolType`). For your problem, you could pass a string column to `alt.Color` and then split the label into a list with the `split` Vega expression function:

```python
import altair as alt
from vega_datasets import data

source = data.barley()[:40]
source["site_year"] = [f"{v} - {s}" for v, s in zip(source["site"], source["year"])]

site_year_unique = list(source["site_year"].unique())
colors = ["red", "green", "blue", "cyan", "yellow", "magenta"]

alt.Chart(source).mark_point().encode(
    x="yield:Q",
    y="site:O",
    color=alt.Color("site_year:O")
    .legend(labelExpr="split(datum.label, ' - ')")
    .scale(domain=site_year_unique, range=colors),
)
```

Another useful pattern is to provide a mapping as a dictionary converted to json:

```python
...
label_mapping = {s: s.split(" - ") for s in site_year_unique}
...
    .legend(labelExpr=json.dumps(label_mapping) + "[datum.label]")
```
This gives you the same result.

<img width="501" alt="image" src="https://github.com/altair-viz/altair/assets/23366411/6cdaab92-5110-4191-9e0e-09e1d784caf7">
