### ISSUE TITLE
Display labels on graph for totals or meaningful quantities

### ISSUE THREAD

**Issue by chhenault** [altair-viz/altair#328]
Hi, first of all congratulations on all the work done on Altair, this is really a fantastic project that I look forward to see becoming prevalent in the Data Science community!

One feature that I believe would be tremendously helpful would be to enable the display of data labels onto the graph. 

I can think of 2 categories of labels: 
1) labels coming from the data itself, like f bar totals for bar charts, y values for line charts on each xtick value 
2) labels coming from a transformation done on the data itself, here I am thinking about stats like r² of equation for regression lines on scatter plot as an example

Throughout the examples and litterature I have not found the way to have such data labels easily put onto a graph. Would it be a feature you would consider as a future development of Altair?

Thanks!

**Comment by jakevdp** [comment]
Hi – this is a good suggestion. Any sort of additional visual feature like this would have to come by way of Vega-Lite, and I don't think that Vega-Lite supports this kind of statistical summary. It would be worth bringing this up in the vegalite repo.

**Comment by jakevdp** [comment]
Labels can now be added by layering text charts. For example: https://altair-viz.github.io/gallery/stacked_bar_chart_with_text.html
