### ISSUE TITLE
Polars Dataframe with "date" dtype would not be rendered by Altair. Two workarounds (with and without pandas) are proposed.

### ISSUE THREAD

**Issue by ariewjy** [altair-viz/altair#3280]
## Issue when altair (version 5.2.0) chart would not render if **any of the column** is in ["**date**" temporal data type](https://pola-rs.github.io/polars/user-guide/transformations/time-series/parsing/). 

I found that whenever there is a `date` data type column in the polars dataframe, the altair would not render the chart properly. Only when there is no `date` column, either by removing it completely, or by casting it to pandas or different data type as below.

### Code to reproduce issue

```python
import polars as pl
import altair as alt

# Importing data from vegadataset via url

dfx = pl.read_csv( "https://raw.githubusercontent.com/vega/vega-datasets/main/data/seattle-weather.csv",
try_parse_dates=True)

dfx

```
![CleanShot 2023-12-10 at 18 43 55@2x](https://github.com/altair-viz/altair/assets/73975333/9e6ab7d0-6495-41f4-8a75-a29b71a0811e)

As shown above, `try_parse_dates=True` the date column will be "`date`" format. 

Using altair 5.2.0 version, if plotted using `rect` encoding the output will not be rendered.

```python
import altair as alt

alt.Chart(dfx).mark_rect().encode(
    alt.X("date(date):O").axis(labelAngle=0, format="%e").title("Day"),
    alt.Y("month(date):O").title("Month"),
    alt.Color("max(temp_max):Q", scale=alt.Scale(scheme="redblue")).title("Max Temp"),
)
```

![CleanShot 2023-12-10 at 14 17 58@2x](https://github.com/altair-viz/altair/assets/73975333/e06fef56-baa0-4c40-b10e-03363b80281a)

There are two workarounds to avoid this issue:

### 1. Convert to pandas dataframe using `to_pandas()` before using altair.
This means the altair will use the familiar format (pandas dataframe) instead of polars, however that means we wouldn't get the benefit of using polars dataframe later on (e.g. speed, etc.). 

Perhaps works best if we are not planning to do any data wrangling with polars later on.

```python
dfx = (
    pl.read_csv(
        "https://raw.githubusercontent.com/vega/vega-datasets/main/data/seattle-weather.csv",
        try_parse_dates=True
    )
    .to_pandas()
)

dfx
```
![CleanShot 2023-12-10 at 18 44 23@2x](https://github.com/altair-viz/altair/assets/73975333/d47ec193-3f1f-4467-be72-a47ee6f5a75d)

Using the same code to make a chart from altair would work:

![CleanShot 2023-12-10 at 18 44 57@2x](https://github.com/altair-viz/altair/assets/73975333/b88e4398-1b83-4b62-b134-edf6c488fecf)

However, if we plan to use polars as the main dataframe library, then the second method is better.

### 2.  Parse the date column to `datetime` type instead of `date` data type. 
Casting the str type to `datetime[μs]` before we make the plot in altair.

> This works when the `try_parse_dates=False` (which is the default setting in `read_csv`)

```python
dfx = (
    pl.read_csv(
        "https://raw.githubusercontent.com/vega/vega-datasets/main/data/seattle-weather.csv")
    .with_columns(pl.col("date").str.to_datetime())
)

dfx.head()
```
![CleanShot 2023-12-10 at 18 50 40@2x](https://github.com/altair-viz/altair/assets/73975333/adde060c-93ed-4b51-948b-00ec815b1c54)

Then just do the same chart plotting using altair would then work. 

![CleanShot 2023-12-10 at 18 51 22@2x](https://github.com/altair-viz/altair/assets/73975333/26293768-9116-4753-8571-1e04ed7429bc)

**Comment by jonmmease** [comment]
Thanks for the report @ariewjy, and apologies for the slow response. I'll have to look more closely, but this looks like a limitation in pyarrow's implementation of the DataFrame interchange protocol.  We should be able to work around it, but will take some experimentation to see where it makes sense to do this.

**Comment by jonmmease** [comment]
So I looked into this a bit more, and found that pyarrow doesn't support loading Date32 columns through the dataframe interchange protocol. https://github.com/apache/arrow/issues/39539. I posted a repro of this error in that thread and asked what the best path forward is.

We could work around this by introducing an optional dependency on polars, but we were hoping we could avoid this and focus only on supporting the dataframe interchange protocol.  But I would very much like Altair to work smoothly with Polars, so depending on how likely this is to be resolved in pyarrow, we may need to do this in the short term.

cc @mattijn in case you have thoughts

**Comment by mattijn** [comment]
If the dataframe interchange protocol is undecisive how to support this then we should solve it pragmatic. There is not always a royal road. I'm not in favor to introduce an optional polars dependency just to do an `isinstance` check on the polars dataframe. 

We can do a simple check on the return type of the instance of the `.__dataframe__` and if it is a `PolarsDataFrame` we know we can call the `.to_arrow()` function directly without entering the more complicated and slower dataframe interchange protocol. 

```python
# add new function
def dataframe_instance(obj):
    return obj.__dataframe__.__annotations__["return"]

# adaptations required in https://github.com/altair-viz/altair/blob/main/altair/utils/data.py 
if hasattr(data, "__dataframe__"):
    if dataframe_instance(data) == 'PolarsDataFrame':
        pa_table = data.to_arrow()
    else:
        pi = import_pyarrow_interchange()
        pa_table = pi.from_dataframe(data)
```

By the way for me this issue won't raise an error and also not the example you provided in your comment at the pyarrow repository:

```python
import pyarrow as pa
import polars as pl
import pyarrow.interchange as pi

print(pa.__version__, pl.__version__)

data = pl.DataFrame({"date": [datetime.date(2024, 3, 22)]})
pi.from_dataframe(data)
```

> ```cmd
> 12.0.1 0.20.16
> 
> pyarrow.Table
> date: int32
> ----
> date: [[19804]]
> ```

Where:
```python
data.to_arrow()
```

> ```cmd
> pyarrow.Table
> date: date32[day]
> ----
> date: [[2024-03-22]]
> ```

Even more reason to not use the dataframe interchange protocol here..

**Comment by mattijn** [comment]
Hm, that function I propose will not always work (eg from this issue: https://github.com/vega/vegafusion/issues/386):
```python
import pandas as pd
import vega_datasets

from pandas.core.interchange.dataframe import PandasDataFrameXchg

class NoisyDfInterface(pd.core.interchange.dataframe.PandasDataFrameXchg):
    def __dataframe__(self, allow_copy: bool = True):
        return NoisyDfInterface(self._df, allow_copy=allow_copy)

    def get_column_by_name(self, name):
        print(f"get_column_by_name('{name}')")
        return super().get_column_by_name(name)

cars = vega_datasets.data.cars()
dfy = NoisyDfInterface(cars)

type(dfy).__name__
```

> ```cmd
> 'NoisyDfInterface'
> ```

But:
```python
dataframe_instance(dfy)
```

> ```cmd
> ----> [7]    return obj.__dataframe__.__annotations__["return"]
> 
> KeyError: 'return'
> ```

Initially I thought we can use `type(dfy).__name__`, but for both a pandas DataFrame and a polars DataFrame will this return `'DataFrame'`

**Comment by mattijn** [comment]
It is getting messy:
```python
if hasattr(data, "__dataframe__"):
    if 'polars' in type(data).__module__:
        pa_table = data.to_arrow()
```
Open for other suggestions @jonmmease 😄

**Comment by jonmmease** [comment]
Haha, yeah, that would work. Another option is to lean into duck typing and just check for the existence of a `data.to_arrow()` method on the object and call that instead of using the `__dataframe__` interface.

Looks like cudf has the same method: https://docs.rapids.ai/api/cudf/legacy/user_guide/api_docs/api/cudf.dataframe.to_arrow/

I think vaex uses `to_arrow_table()`, and duckdb supports `.arrow()` and `.to_arrow_table()`.  So maybe we check for the existence of methods named "arrow", "to_arrow", or "to_arrow_table" and call one of these if they exist.

**Comment by mattijn** [comment]
Would the following be a compromise to resolve this?:

If it has a `__dataframe__` attribute then:

> we check for the existence of methods named "arrow", "to_arrow", or "to_arrow_table" and call one of these if they exist.

And else use the formal dataframe interchange protocol.

**Comment by jonmmease** [comment]
Yeah, I think requiring the `__dataframe__` attribute (which we use for encoding type inference), and then allowing the object to provide their own arrow conversion with "arrow", "to_arrow", or "to_arrow_table" makes good sense.

**Comment by jonmmease** [comment]
I updated https://github.com/altair-viz/altair/pull/3377 to include this logic, which now fixes this Date32 issue when using Polars and PyArrow.
