### ISSUE TITLE
IndexSelection in JupyterChart instead of PointSelection

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#3285]
Given the following spec:

```python
import altair as alt
from vega_datasets import data

cars = data.cars()
print(len(cars))

point = alt.selection_point(name='mypoint')
chart = alt.Chart(cars).mark_rect().encode(
    x="Cylinders:O",
    y="Origin:N",
    color=alt.condition(point, 'count()', alt.value('lightgray'))
).properties(
    width=300,
    height=180
).add_params(
    point
)
jchart = alt.JupyterChart(chart)
jchart
```
And then selecting eg Japan for origin and 4 for cylinders, as such:
![image](https://github.com/altair-viz/altair/assets/5186265/07eb333f-f345-4f62-890d-9dfef1134cdd)

Then looking into the selection:
```python
jchart.selections.mypoint
```
It gives me an `IndexSelection`:
```cmd
IndexSelection(name='mypoint', value=[408], store=[{'unit': '', '_vgsid_': 409}])
```
But I was assuming I would get a `PointSelection`, since there is no such index in the source dataframe:
```python
cars.iloc[jchart.selections.mypoint.value]
```
```cmd
IndexError: positional indexers are out-of-bounds
```

**Comment by jonmmease** [comment]
The way things work now is that you get an `IndexSelection` when `alt.selection_point` is called without `encoding` or `fields`, and you get a `PointSelection` if either `encodings` or `fields` are provided.  We mention in the docs that the `IndexSelection` indices will not correspond to the input DataFrame if the chart has any aggregations (as is the case here).

I think what you want in this case is to call `point = alt.selection_point(name='mypoint', encodings=["x", "y"])`. Then a `PointSelection` is returned that includes selections based on Cylinders and Origin.

**Comment by mattijn** [comment]
Thanks! That works perfectly
