### ISSUE TITLE
Set viewport of Chart

### ISSUE THREAD

**Issue by lemoncyb** [altair-viz/altair#330]
I'm wondering how to set the viewport of Chart in altair. The [API reference](https://altair-viz.github.io/API.html#altair.Config) says viewport is like this:
```
Trait	Type	Description
viewport	float	The width and height of the on-screen viewport, in pixels.
```
How could one float value represent both width and height, like "width.height"?
And I tried like this:
```
chart = Chart(cat).configure(viewport=50.30).mark_bar(color='lightgreen').encode(
        X('Name', axis=Axis(title='Sample')),
        Y('Value', axis=Axis(title='Score'))
    )
```
But it didn't work.

**Comment by jakevdp** [comment]
From the schema, it looks like this is a single number specifying both the width and height of the viewport. I've never used this config setting myself, and it looks like it's removed from vega-lite 2.0, and so won't be around for much longer.

**Comment by ellisonbg** [comment]
Yeah I haven't used this either. I would ask on the Vega-Lite github repo for more information.
