### ISSUE TITLE
Example of interactive and non interactive visualisation with bidirectional selection in one altair construct

### ISSUE THREAD

**Issue by franzhaas** [altair-viz/altair#3315]
The interactive method and the selection brush are very powerful features.

I think it would be helpful to have an example showcasing the difference between the "interactive" and the "non interactive" version of the usage of the selection brush side by side, as well as an example of 2 brushes.:

```python

import altair as alt
from vega_datasets import data

source = data.iris()

brush1 = alt.selection_interval()
brush2 = alt.selection_interval()

(alt.Chart(source).mark_circle(size=60).encode(
    x='sepalLength',
    y='sepalWidth',
    color='species',
    tooltip=['species', 'sepalWidth', 'sepalLength', 'petalLength', 'petalWidth']
).add_params(
    brush1
).transform_filter(
    brush2
) | alt.Chart(source).mark_circle(size=60).encode(
    x='petalLength',
    y='petalWidth',
    color='species',
    tooltip=['species', 'sepalWidth', 'sepalLength', 'petalLength', 'petalWidth']
).add_params(
    brush2
).transform_filter(
    brush1
).interactive())
```

I would happily provide a pull request for this, but am unsure where to put it...

**Comment by joelostblom** [comment]
Thanks, could you elaborate on the usefulness of the right-most chart here? When I click and drag it both creates a selection and moves the chart around, which seems undesirable since you can control what you are selecting in an easy way?

**Comment by franzhaas** [comment]
This is what the example demonstrates. 

For this data, the ability to move and zoom a chart in addition to the selection is not helpful. For charts with multiple dense clusters, zooming before selecting actually can be useful.

Maybe i find more suitable data in the example data sets.

**Comment by franzhaas** [comment]
I did not find a more usefull example....
