### ISSUE TITLE
Flicker-free interaction with ipywidgets?

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#333]
I have seen some demos of plots with ipywidgets that are really smooth and flicker-free.  Is that possible with altair 1.0?  or is that more of 2.0 and the jupyter lab integration?

Here is my current simple example that flickers in jupyter notebook:

```python
import pandas as pd
import altair as alt
from ipywidgets import interact
from ipywidgets import IntSlider

data = {'a': ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j'],
       'b':[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]}

df = pd.DataFrame(data)

def some_plot(value):
    chart = alt.Chart(df).mark_line().encode(
    x='a',
    y='b').transform_data(filter='datum.b < %s' % value)
    return chart

interact(some_plot, value=IntSlider(min=1, max=10, step=1))
```

**Comment by ellisonbg** [comment]
A couple of things you are running into:

* The data transfer and rendering time of Vega-Lite is probably not fast enough to have a nice interactive experience.
* We would need to build a full ipywidget version of a Vega-Lite rendering to create nice experience for this.

Building a ipywidget version of a Vega-Lite renderer wouldn't be too difficult, however, Vega-Lite doesn't have many APIs for updating a visualization. Thus, all we could really do is re-render from scratch, which still might be an issue. Something to think about in the long term though.

**Comment by joelostblom** [comment]
It is now possible to use the `JupyterChart` class to create Altair charts that can interact with jupyter/ipywidgets directly and without any flicker. See this section in the docs for details https://altair-viz.github.io/user_guide/jupyter_chart.html
