### ISSUE TITLE
Transmit data in column-format json

### ISSUE THREAD

**Issue by mccullerlp** [altair-viz/altair#3332]
This is partially a request on vega-lite or vega, given their imposed convention of row-format json.

In researching plotting libraries, a common concern raised for altair is the "small" dataset size it can handle. This seems ultimately due to the use of json to carry the tables, over binary formats. My need, for instance, is a lot of line-plots with many points/high resolution. Say 20 lines each with 500 to 2000 points. The use of many data lines like this pairs particularly well with Vega/Altair's selection and interactivity abilities.

Given that Altair more naturally uses long-form tables, why not enable a json that is in column format?

{
"long_col_name" : [1, 2, 3, ...],
"B" : ["x", "y", "z",...]
}
This would cut the memory load for the json by quite a bit, as it would not have many repetitions of the column names between the json rows. Between this and using transform_lookup based joins on a secondary metadata dataset, many typical usecases with high-resolution lines/timeseries might be better accommodated.

One could experiment how much this would improve performance on large datasets by using the csv data entry formats of the javascript interface. I haven't tried this, but will comment if I manage to benchmark the memory need pairing 3-column (X, Y, meta-id) long-format CSV with joins against a metadata table.

---

Please follow these steps to make it more efficient to respond to your feature request.

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most feature requests should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example.
- [x] Search for duplicate issues.
- [x] Describe the feature's goal, motivating use cases, and its expected behavior.

**Comment by mccullerlp** [comment]
Nevermind, I see actually that you can send data effectively in column format using array datatypes which can then be flattened. 

https://altair-viz.github.io/user_guide/transform/flatten.html

Worth noting that using both flatten and join can reduce data sizes a lot.

**Comment by binste** [comment]
Thanks for the inputs! Using  `flatten` sounds like the way to go, as you mentioned, but it's good to have this documented in at least this GitHub issue. At least I was not aware that I could use this workflow to make the Vega-Lite specs smaller :)
