### ISSUE TITLE
Enable privacy-friendly web analytics for documentation

### ISSUE THREAD

**Issue by binste** [altair-viz/altair#3338]
I'd be very curious to see how many users we have on our documentation and what the content is they typically view. It could guide future work on the docs. It seems to be quite easy to [enable for our PyData Sphinx theme](https://pydata-sphinx-theme.readthedocs.io/en/stable/user_guide/analytics.html#analytics-and-usage-services). I'd suggest that we use [plausible.io](https://plausible.io/) as a tracking service as it is very privacy-friendly. It's also what other packages use such as pandas and [scikit-image](https://github.com/scikit-image/scikit-image/blob/main/doc/source/conf.py#L184). 

Plausible has a price tag, except if you self-host it. On the PyData Sphinx theme documentation, they mention that we might be able to get a self-hosted free server at scientific-python.org. I've reached out to them beginning of January via Discord but have not yet heard back.

I'd offer to pay for it myself for at least 3 months ([costs depend on traffic](https://plausible.io/#pricing)) so we get a good picture of what's happening. We can then decide how to continue in case we haven't heard back from the scientific-python.org maintainers.

Any thoughts? :)

**Comment by jonmmease** [comment]
I'm in favor! Thanks for researching how other projects are handling this.

**Comment by mattijn** [comment]
I think it is good idea to collect insight how users are using the documentation. I cannot find it anymore, but I remember the website of vega is using google analytics to collect these insight. I would be a bit hesitant with self-paying with 21M downloads/month on pypi

**Comment by joelostblom** [comment]
Great idea! I'm in favor as long as it is a privacy-respective alternative like the one you suggested. Getting a self-hosted server via scientific-python.org sounds like the ideal solution, so hopefully you will hear back from them.

**Comment by binste** [comment]
Heard back, we can use the service from scientific-python.org for free! :) I'll create a PR soon to configure the docs accordingly. Thank you all for the feedback.

**Comment by binste** [comment]
I've already added it to the live docs (redeployed based on the commit which was last used to build it) and opened #3346 to add it to the main branch.

The stats are accessible via an account on the views.scientific-python.org Plausible server. I'll send invite links to all Altair maintainers.

Thanks again @stefanv for letting us use your server! :)
