### ISSUE TITLE
Only track release notes in one place

### ISSUE THREAD

**Issue by binste** [altair-viz/altair#3339]
We currently track release notes in 2 places, the [documentation](https://altair-viz.github.io/releases/changes.html) and in [GitHub Releases](https://github.com/altair-viz/altair/releases). The docs use restructured text whereas GitHub Releases uses Markdown so we can't just copy-paste content from one into the other but it requires a rewrite. In addition, as it's easier to add images and do formatting in Markdown, the GH Releases pages of the last few releases look much better and are more extensive than what we have in the docs. Thanks @mattijn for taking the time every release to write this!

How about we only maintain the release notes in GitHub Releases? We can simply link to it from the documentation. No information gets lost and it's easier for us to maintain and we can write better release notes which is beneficial for users.

I'm happy to create a PR for the docs and to make sure that everything is captured in GitHub Releases. Thoughts?

**Comment by mattijn** [comment]
I'm okay with either choice.
I agree that the release notes in the Altair docs are limited.

As a user, I often check the Altair docs but not so much the GitHub release page.

But it's really helpful for users to see detailed explanations of the changes in each release.

Right now, there's some repetition on the GitHub page with the auto-generated release description at the bottom.

Maybe we should only have auto-generated release notes on GitHub and more detailed docs on Altair's page.

I like that I can just keep scrolling through the Altair docs' release notes to see all the changes for multiple versions.

But I get your point that using the GitHub page is easier for maintainers and that therefore we actually write more documentation. 

Like I said, I'm fine either way..

**Comment by joelostblom** [comment]
I'm in favor of maintaining release notes just in one place and I don't have a strong preference where that is. A few thoughts/considerations:

- Like @mattijn mentioned, I do also like having most/all notes on one page to be able to search through them quickly with ctrl + f. I guess on GH pages we can still see several releases per page which is pretty good.
- An advantage of GitHub is that we can link PRs and usernames more easily.
- I like the workflow where each PR also includes a line in the changelog/release file of what was changed, so that we don't have to go through and recall what's new in the end just before making a release (although it's harder to add images this way compared to just copy-paste into GH releases). But maybe this is less of an issue than I make it in my head.
- I think the Altair docs look nicer than the GH release page, but this is minor.

None of these are deal-breakers, and I'm generally in favor of most things we do to facilitate maintenance =)

**Comment by jonmmease** [comment]
I don't have strong opinions on this, so happy to defer to others who have thought about it more carefully

**Comment by binste** [comment]
Pro Altair docs:
* All on one page, easier to ctrl+f
* Look a bit nicer, but then again we don't put images in there and do less formatting so that effect might be negated

Pro of GH pages:
* Can link PRs and usernames more easily
* Easier to write and format as it's markdown which makes it easier for us to write longer release notes
* Easier to include images

For me the pros of the GH pages outweigh. Biggest one is that I think it leads to higher-quality release notes as shown in the last few versions.

> As a user, I often check the Altair docs but not so much the GitHub release page.
To address this, I'd suggest that we keep the navigation bar entry in the docs and link to the GH releases.

> I like the workflow where each PR also includes a line in the changelog/release file of what was changed, so that we don't have to go through and recall what's new in the end just before making a release (although it's harder to add images this way compared to just copy-paste into GH releases). But maybe this is less of an issue than I make it in my head.

Same! I also find this very convenient. How about we have a section in the `RELEASING.md` file where we can throw in release notes between versions and then as part of the releasing process, the maintainer doing the release would write some proper release notes based on this, potentially including images and code snippets?

**Comment by joelostblom** [comment]
> How about we have a section in the RELEASING.md file where we can throw in release notes between versions and then as part of the releasing process, the maintainer doing the release would write some proper release notes based on this, potentially including images and code snippets?

I'm on board with that. As long as we keep track of it somewhere on a per PR basis, I don't mind exactly where that is.

**Comment by binste** [comment]
Big +1 from me for using this in PR titles (not individual commits in a branch). I also think that, as you mentioned, the automated release notes are then a great first draft which can be refined. It also gets us to consistently show everything in the release notes.

I'd be on board with having a CI check. Some examples are [VL](https://github.com/vega/vega-lite/blob/main/.github/workflows/check-pr.yml) as you mentioned as well as [Ibis](https://github.com/ibis-project/ibis/blob/main/.github/workflows/pr-title.yml)
