### ISSUE TITLE
type hint for to_json(indent=) should be Optional

### ISSUE THREAD

**Issue by leifwalsh** [altair-viz/altair#3341]
In https://github.com/altair-viz/altair/pull/3071 and https://github.com/altair-viz/altair/pull/3073 types were added to some `to_json()` methods (well, #3071 added the method entirely to `TopLevelMixin`) that specify `indent` as an `int`. In these, `indent` is only passed along to `json.dumps`, where it should be possible to pass `None` or a string as well: https://docs.python.org/3/library/json.html#json.dump

With `indent` typed as `int` and defaulting to 2 in the altair API, there is no way to get the compact `indent=None` serialization in a way that typechecks.

I think the types should be relaxed to `str | int | None` or something similar.

**Comment by binste** [comment]
Thanks for the detailed report @leifwalsh! Fully agree, I'll change it to `Optional[Union[str, int]]` for the next release.
