### ISSUE TITLE
`extent` parameter in `transform_regression not working as expected

### ISSUE THREAD

**Issue by thomascamminady** [altair-viz/altair#3347]
I took this example from the gallary

```python
import altair as alt
import pandas as pd
import numpy as np

np.random.seed(42)
x = np.linspace(0, 10)
y = x - 5 + np.random.randn(len(x))

df = pd.DataFrame({'x': x, 'y': y})

chart = alt.Chart(df).mark_point().encode(
    x='x',
    y='y'
)

chart + chart.transform_regression('x', 'y').mark_line()
```
and got this plot
<img width="347" alt="image" src="https://github.com/altair-viz/altair/assets/24543638/24904283-eef2-4de4-a9d1-b9d5f4ae74a9">

So far, so good. But when I add the `extent` parameter like such
```
chart + chart.transform_regression('x', 'y',extent=[0,20]).mark_line()
```

The plot is wrong:
<img width="347" alt="image" src="https://github.com/altair-viz/altair/assets/24543638/924ab9b9-53ee-4d38-b925-9b611f61d161">

**Comment by jonmmease** [comment]
Hi @thomascamminady, unfortunately this is an upstream bug in Vega-Lite (reported in https://github.com/vega/vega-lite/issues/9230) that hasn't been investigated yet. Going to close here as we won't be able to address it in Vega-Altair.

I added a comment with some observations in https://github.com/vega/vega-lite/issues/9230#issuecomment-1973167062

**Comment by thomascamminady** [comment]
Thanks for the info!
