### ISSUE TITLE
VegaFusion + Polars Error: Cannot create weak reference

### ISSUE THREAD

**Issue by m1hawkgsm** [altair-viz/altair#3349]
Using the minimal reproducible example found [here](https://vegafusion.io/polars.html#polars-as-input):

```python
import polars as pl
import vegafusion as vf
import altair as alt

# Enable Mime Renderer
vf.enable()

# Load 201k movies parquet dataset
source = pl.read_parquet(
    "https://vegafusion-datasets.s3.amazonaws.com/vega/movies_201k.parquet"
)

# Fitler out rows with null ratings
source = source.filter(
    pl.col("IMDB_Rating").is_not_null() & pl.col("Rotten_Tomatoes_Rating").is_not_null()
)

# Create chart
chart = alt.Chart(source).mark_circle().encode(
    alt.X('IMDB_Rating:Q', bin=True),
    alt.Y('Rotten_Tomatoes_Rating:Q', bin=True),
    size='count()'
)
chart
```

I get:
```
TypeError: cannot create weak reference to 'DataFrame' object
```

Narrowing down, I can see it's [this](https://github.com/altair-viz/altair/blob/main/altair/utils/_vegafusion_data.py#L50) line that tries to set a `KeyedRef`/`ReferenceType`, and I can repeat this with an even simpler example:

```python
from weakref import WeakValueDictionary, KeyedRef
import polars as pl
import pandas as pd
my_dict = WeakValueDictionary()
pd_df = pd.DataFrame({'a': [1,2,3], 'b': [4.0,5.0,6.0]})
pl_df = pl.DataFrame({'a': [1,2,3], 'b': [4.0,5.0,6.0]})

my_dict["pandas_df"] = pd_df
my_dict["polars_df"] = pl_df # breaks with the same exception
```

Pandas works, and indeed running `pd_df.__weakref__` gives `<weakref at 0x2a168a890; to 'DataFrame' at 0x298778a10>`, but that won't work for the polars DF.

Any idea what to do here? I could bypass this by not enabling vegafusion since altair can handle polars, but I will have to be careful with row limits (which is why vegafusion is great).

My environment:
Python 3.11.8
altair 5.2.0
vegafusion 1.6.5
Polars 0.20.13

---

Please follow these steps to make it more efficient to solve your issue:

- [ ] Since Altair is a Python wrapper around the Vega-Lite visualization grammar, [most bugs should be reported directly to Vega-Lite](https://github.com/vega/vega-lite/issues). You can click the Action Button of your Altair chart and "Open in Vega Editor" to create a reproducible Vega-Lite example and see if you get the same error in the Vega Editor.
- [x] Search for duplicate issues.
- [x] Use the latest version of Altair.
- [x] Describe how to reproduce the bug and include the full code and data to reproduce it, ideally using a sample data set from `vega_datasets`.

**Comment by jonmmease** [comment]
Thanks for the report and the investigation @m1hawkgsm. Since this used to work, I wonder if something has changed in Polars that prevents the creation of weak references.

I'll take a closer look soon, but if you have a chance in the meantime it would be interesting to try your polars-only repro with some older versions of polars to see if this behavior has changed.

**Comment by m1hawkgsm** [comment]
Yeah it's because of a change [introduced](https://github.com/pola-rs/polars/releases/tag/py-0.20.11) in `0.20.11`, adding `__slots__` (which currently is only `_df` of type `PyDataFrame`). Because it doesn't have a `__weakref__` slot, it won't work, as per the official [docs](https://docs.python.org/3/library/weakref.html):

```
When __slots__ are defined for a given type, weak reference support is disabled unless a '__weakref__' string is also present in the sequence of strings in the __slots__ declaration. See [__slots__ documentation](https://docs.python.org/3/reference/datamodel.html#slots) for details.
```

I imagine this will require an addition to polars' `__slots__` as suggested, not sure how difficult that'd be. I'll cross post an issue on their repo.

**Comment by jonmmease** [comment]
Sounds good, I've subscribed to the issue. Hopefully it's an easy update on the Polars side, but if not we'll need to figure out how to handle it in Vega-Altair.

**Comment by franzhaas** [comment]
https://github.com/pola-rs/polars/pull/14857

**Comment by jonmmease** [comment]
Awesome, thanks for bringing this up and following up on it @m1hawkgsm and @franzhaas. Going to close this issue as the fix has now been merged in Polars (thanks @stinodego!)
