### ISSUE TITLE
Saving with .savechart() or .to_html() gives empty HTML file

### ISSUE THREAD

**Issue by edesz** [altair-viz/altair#335]
I am trying the following code from the [Displaying visualizations](https://altair-viz.github.io/documentation/displaying.html#displaying-and-saving-altair-visualizations) page:

```
from altair import Chart, load_dataset

# load built-in dataset as a pandas DataFrame
cars = load_dataset('cars', url_only=True)

chart = Chart(cars).mark_circle().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color='Origin:N',
)

print(chart.to_json(indent=2))

chart.savechart('filename.html')

# html = chart.to_html()
# with open('chart.html', 'w') as f:
# 	f.write(html)
```
I am running this script through the [SublimeText editor](https://stackoverflow.com/a/8552149/4057186) in Windows and installed `altair` using `pip install altair`. The Altair version is 1.2.0. It appears that I get the [expected output](https://altair-viz.github.io/documentation/displaying.html#displaying-and-saving-altair-visualizations) from the `print()` statement:
```
{
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/cars.json"
  }, 
  "encoding": {
    "color": {
      "field": "Origin", 
      "type": "nominal"
    }, 
    "x": {
      "field": "Horsepower", 
      "type": "quantitative"
    }, 
    "y": {
      "field": "Miles_per_Gallon", 
      "type": "quantitative"
    }
  }, 
  "mark": "circle"
}
```
However, I am trying to save the plot to an `html` file per [here](https://altair-viz.github.io/documentation/displaying.html#outputting-plots-as-html). The script has approaches to saving with `.to_html()` and also (per [here]()) `.savechart('xxx.html')`.

After executing this script in SublimeText, the `filename.html` or `chart.html` file does appear in the working folder. But, when opened in a browser, I see it is blank.

If I remove `url_only=True` in the `load_dataset()` line, the `print()` statement gives:

```
.
.
.
.
      {
        "Acceleration": 19.4, 
        "Cylinders": 4, 
        "Displacement": 119.0, 
        "Horsepower": 82.0, 
        "Miles_per_Gallon": 31.0, 
        "Name": "chevy s-10", 
        "Origin": "USA", 
        "Weight_in_lbs": 2720, 
        "Year": "1982-01-01"
      }
    ]
  }, 
  "encoding": {
    "color": {
      "field": "Origin", 
      "type": "nominal"
    }, 
    "x": {
      "field": "Horsepower", 
      "type": "quantitative"
    }, 
    "y": {
      "field": "Miles_per_Gallon", 
      "type": "quantitative"
    }
  }, 
  "mark": "circle"
}
```

Is it possible to save to HTML if the script is _not_ executed from a Jupyter notebook?

EDIT: This may be a question, and not an issue.

**Comment by jakevdp** [comment]
This is an issue with the vega-lite library version. Vega-Lite 2.0 has been released recently, and the package is not backward compatible. Unfortunately, the vega-lite team did an in-place update of the js URL to the new version, which breaks all previously-produced vega-lite visualizations, including ones created by the current altair release.

This URL has been [updated in Altair master](https://github.com/altair-viz/altair/commit/97ba36858440f20c3cc16eb4846ef257c500bd2d), and we should do a bugfix release in the near future. In the meantime, you can install the development branch of Altair, or you can manually update the URLs in the html file.

**Comment by edesz** [comment]
Great! Thanks for the info.
