### ISSUE TITLE
The documentation makes me create files in current working directory without warnings

### ISSUE THREAD

**Issue by blaiseli** [altair-viz/altair#336]
I wanted to be able to save figures from python, so I tried the instructions given here: <https://altair-viz.github.io/documentation/displaying.html#saving-figures-programmatically>

It turns out that `npm install canvas vega vega-lite` failed as follows:
```
npm WARN enoent ENOENT: no such file or directory, open '/home/bli/src/bioinfo_utils/package.json'
npm WARN bioinfo_utils No description
npm WARN bioinfo_utils No repository field.
npm WARN bioinfo_utils No README data
npm WARN bioinfo_utils No license field.
npm ERR! Linux 4.4.0-75-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "canvas" "vega" "vega-lite"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE

npm ERR! canvas@1.6.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.5 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs canvas
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bli/src/bioinfo_utils/npm-debug.log
```

While looking at this log, I noticed that there were complains about a missing "package.json" file in what is my current working directory.

**Why would these commands expect the presence of such a file there? Aren't things supposed to be installed in some standard location?**

I had the suspicion that some attempts were made to install stuff in my current working directory, and indeed, I found a `node_modules/` and a `npm-debug.log` there.

Such behaviour is unsafe. The documentation should at least include warnings about this.

**Comment by thoo** [comment]
Did you also try this one `npm install -g --save canvas vega vega-lite`? If you are on linux, make sure you also get legacy `apt-get install nodejs-legacy -y` .

**Comment by jakevdp** [comment]
Those npm instructions were essentially copy-pasted from the vega/vega-lite installation page. I don't really know much about npm; perhaps it would be safer for us to remove those commands from the docs and just link to the installation instructions for the packages themselves?

**Comment by blaiseli** [comment]
@thoo After installing things as you suggest, I get different error messages:
```
npm ERR! Linux 4.4.0-75-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "--save" "canvas" "vega" "vega-lite"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! path /usr/local/lib
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access

npm ERR! Error: EACCES: permission denied, access '/usr/local/lib'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bli/src/pyGATB/build/npm-debug.log
```

It seems that I need to perform the install as root, but I'd rather not install stuff as root using other mechanisms than the official `apt` package manager.

Also, this continues to write things in my current working directory. This time only the `npm-debug.log`, though.

**Comment by ellisonbg** [comment]
The `-g` option with npm will save the packages to the global directory, which in your case is `/usr/local/lib`. If you want to install locally, remove the `-g` flag, but then it will create a `node_modules` directory in your cwd and you will need to put its `bin` subdirectory in your `PATH`.
