### ISSUE TITLE
axis type meaning?

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#339]
Could someone enlighten me on what this axis meaning is?

```python
something = {'a': [0.680924, 0.750063],
             'b': ['a', 'b'],
            'cat': ['alpha', 'beta']}
df = pd.DataFrame(something)

alt.Chart(df).mark_point().encode(
    x='b',
    y='a',
    color='cat')
```
results in the axis being 0m to 800m
![image](https://cloud.githubusercontent.com/assets/1798497/26642921/8d565d42-45fd-11e7-96e1-8a66b3497e7f.png)

But if I then declare the range I then get the axis that I expect:
```python
alt.Chart(df).mark_point().encode(
    x='b',
    y = alt.Y('a:Q', scale=alt.Scale(domain=(0, 1))),
    #y='a',
    color='cat')
```
![image](https://cloud.githubusercontent.com/assets/1798497/26643001/d2b114b8-45fd-11e7-975c-97b9780868a6.png)

I have opened this up in the vega editor to understand with is causing the 0m to 800m and I am not getting any hints there.

I have also played with other settings to try to get it to look like the second without explicitly declaring the scale/domain but am not making any headway.

Anyone have ideas on how I can build an understanding and reasoning for why the default is the 'm'

**Comment by kanitw** [comment]
m is millisecond (SI unit).  We are aware that SI unit is confusing for users and thus are working on better default axis format for Vega-Lite 2.0 (https://github.com/vega/vega-lite/issues/1539).

**Comment by afonit** [comment]
@kanitw ,
Thanks for the reply.
I will close this then since it is a known issue.

**Comment by afonit** [comment]
I did not find this through searching, so I am linking here for more context as it has been discussed - and I saw it in the link kanitw had posted.
https://github.com/altair-viz/altair/issues/223
