### ISSUE TITLE
Inconsistencies and breakage in text mark with empty data

### ISSUE THREAD

**Issue by TyIsI** [altair-viz/altair#3391]
### What happened?

While looking into altair so I would be able to answer some of questions my partner had about altair , I ended up doing a deep dive and tried to see whether it was possible to implement a separate text mark without data as a potential workaround for implementing dynamic chart titles.

According to the Vega (Lite v4) specs, it should be possible to create text marks without data and they should be able to be created as separate layers.

I received inconsistent results and errors.

Example code (started from https://altair-viz.github.io/altair-viz-v4/gallery/bar_chart_with_labels.html with a default VSC/Jupyter setup):
```
import altair as alt
from vega_datasets import data

source = data.wheat()

bars = (
    alt.Chart(source)
    .mark_bar()
    .encode(x="wheat:Q", y="year:O")
    .properties(width=420, height=900)
)

text = (
    bars.mark_text(
        align="left",
        baseline="middle",
        dx=3,  # Nudges text to right so it doesn't appear on top of the bar
    )
    .encode(text="wheat:Q")
    .properties(height=900)
)

floating_title = (
    alt.Chart()
    .mark_text(
        text="Custom Graph Title", y=0, baseline="middle", align="center", fontSize=25
    )
    .properties(width=420, height=25)
)
```

The following code renders a data frame in Jupyter:
```
alt.vconcat(
    floating_title,
    alt.layer(bars, text),
)
```
![image](https://github.com/altair-viz/altair/assets/3118952/03662bba-3c1f-4651-a282-6c366cd0b75b)

The following code creates a bit of a mess:
```
alt.layer(
    floating_title,
    alt.layer(bars, text),
).properties(height=1000)
```
![image](https://github.com/altair-viz/altair/assets/3118952/c58567c1-0fec-4fa1-ab77-e4e63ecdb1a3)

And the following code does not like to be rescaled:
```
alt.vconcat(
    floating_title,
    alt.layer(bars, text),
).properties(height=1000)
```
![image](https://github.com/altair-viz/altair/assets/3118952/c5923496-7152-46f0-923f-a7a044255bbb)

Plain text error:
> altair.vegalite.v4.api.Chart, validating 'required'
> 
>        'data' is a required property

### What would you like to happen instead?

Not sure if there's a better way to do it.
Let me know if you want me to create separate issues.

### Which version of Altair are you using?

Python: 3.10.12

Packages:
- altair==4.2.2
- ipykernel==6.29.4
- jupyter_client==8.6.1
- jupyter_core==5.7.2
- vega-datasets==0.9.0

**Comment by joelostblom** [comment]
> whether it was possible to implement a separate text mark without data as a potential workaround for implementing dynamic chart titles

Yes it is, your code snippets work for me in altair 5.3, is is an option for you to upgrade from 4.2.2?

In Altair 5, you can also [use expressions to change the chart titles,](https://altair-viz.github.io/user_guide/interactions.html#inline-expressions-in-titles) instead of an empty mark.

---

Note the second error you are seeing with the layering is an issue with unmatched heights of the layered charts. The error message is not that helpful in 4.2.2 and was improved in altair 5.

Also see [this SO answer](https://stackoverflow.com/questions/71210072/can-i-turn-altair-axis-titles-into-links) for another example of using empty text marks for axis titles in case its helpful

**Comment by joelostblom** [comment]
Thank you for offering to submit a PR! We don't currently do any work on v4, so I'm not sure how responsive we would be in reviewing a PR. We would rather see people migrate to V5 when possible as it has multiple benefits and some of the helper packages for v4 are no longer maintained.

Any chance that the course your partner is taking is via the University of British Columbia's extended learning platform? I know that course is planning to update to v5 in the near future (but maybe not for this immediate cohort). If it is at another university, I would be happy to advise on the benefits of updating and point them to the biggest changes that were made.

**Comment by TyIsI** [comment]
Yeah, it is the UBC dataviz course actually. And I think some of the issues would in fact be solved by upgrading to V5. (But I'm testing that.)

And gotcha. I won't prioritize it, but I might take a look if I feel inspired and go from there.

I'll close as not-planned for now.

**Comment by joelostblom** [comment]
Great, I was part of creating that course and I can confirm that we want to update it to Altair 5 soon. If I remember correctly I believe it should already be close to fully compatible with v5, just that we need to update [some syntax in this repo](https://github.com/UBC-MDS/exploratory-data-viz) and in our private assignment repo to not have deprecation warnings show up before updating the server to altair 5.

Your partner could ask the two course facilitators for the cohort if they would allow for `%pip install -U altair` in the first cell of the notebook, to update altair manually just for the notebook running the code you linked above (if I remember correctly they use a binder setup that should allow for this type of update). That might be the easiest workaround.

**Comment by TyIsI** [comment]
Thanks! I'll relay the message!
