### ISSUE TITLE
Text Annotations

### ISSUE THREAD

**Issue by nipunbatra** [altair-viz/altair#349]
A [SO question](https://stackoverflow.com/questions/44656141/how-to-do-annotations-with-altair) asked by text annotations. Does this fall in the scope of Altair? 

I wonder if a workaround might be to create an additional layer (using another data source?) and add text marks?

**Comment by ellisonbg** [comment]
The actual capabilities of Altair are inherited by Vega-Lite (https://github.com/vega/vega-lite). Can you post a question there?
