### ISSUE TITLE
Additional mark_bar examples

### ISSUE THREAD

**Issue by nipunbatra** [altair-viz/altair#350]
I was looking at a [SO question](https://stackoverflow.com/questions/44920367/pandas-groupby-plot-with-different-x-axis-order), and thought of atleast [3 different visualisations](https://stackoverflow.com/a/44922462/743775) that can be made using mark_bar. 

Wonder if they'd be useful enough above existing docs and plots to make it into the docs.

**Comment by nipunbatra** [comment]
Another [SO question](https://stackoverflow.com/questions/44924711/python-matplotlib-how-to-make-a-stacked-plot-with-given-array) which may serve as a cookbook recipe.

[Altair version](https://stackoverflow.com/a/44925697/743775)

```python
import numpy as np
import pandas as pd
data = np.array([[4, 4, 4],
 [4, 4, 6],
 [4, 3, 4],
 [4, 4, 7],
 [4, 4, 3],
 [4, 4, 1],
 [3, 4, 7],
 [4, 3, 7],
 [4, 4, 5],
 [4, 3, 6]])

columns = ['Col1', 'Col2', 'Col3']
df = pd.DataFrame(data, columns=columns)
df = df.T.stack().reset_index(level=[0,1])
df.columns = ['Col','RowNum','Value']
Chart(df).mark_bar().encode(y='count(*)', x='Col:N', color='Value:N')
```

[Pandas version](https://stackoverflow.com/a/44925224/743775)

```python
import numpy as np
import pandas as pd
data = np.array([[4, 4, 4],
 [4, 4, 6],
 [4, 3, 4],
 [4, 4, 7],
 [4, 4, 3],
 [4, 4, 1],
 [3, 4, 7],
 [4, 3, 7],
 [4, 4, 5],
 [4, 3, 6]])

columns = ['Col1', 'Col2', 'Col3']
df = pd.DataFrame(data, columns=columns)
out = {}
for column in columns:
    out[column] = pd.value_counts(df[column])

uniq_df = pd.DataFrame(out).fillna(0)

uniq_df.T.plot(kind="bar", stacked=True)
```

**Comment by mroswell** [comment]
In general, I find the Altair documentation to be so concise that I find it hard to use. I believe: the more examples the better. BTW, the brevity-to-reality problem was the reason I proposed the hackathon idea. #367     
(The scheduling problem though... at this point... since no date has been announced.)

**Comment by kanitw** [comment]
For now you might find Vega-Lite examples for [bar marks](https://vega.github.io/vega-lite/docs/bar.html) useful (same for other marks). 

I think @jakevdp has a method that can take a Vega-lite spec as input and convert it into an Altair code too.  Maybe if someone invent a semi-automatic way to generate Altair docs from Vega-Lite's markdown docs, that might be pretty handy.

**Comment by jakevdp** [comment]
I agree the documentation is quite weak at the moment. I've been waiting until the 2.0 release to do much more work on that, because the API beyond the simplest examples isn't going to change pretty immensely.

**Comment by jakevdp** [comment]
more examples added in v2
