### ISSUE TITLE
LaTeX text

### ISSUE THREAD

**Issue by nipunbatra** [altair-viz/altair#353]
Opened an issue on Vega: https://github.com/vega/vega/issues/898
Cross-referencing here.

I'm wondering if we need to have LaTeX support in Vega before we can have it in Altair? Or, is it only a matter of including the Mathjax js?

**Comment by domoritz** [comment]
While you could potentially implement a new renderer independent of the existing renderers, with the current setup, Vega first needs to support Mathjax.

**Comment by ellisonbg** [comment]
Closing with Reference milestone.
