### ISSUE TITLE
"scale": {"rangeStep": null}

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#354]
I was looking to increase the width of some of my plots that have an x-axis with an ordinal scale - as the default sizing is quite squeezed.

I found this:
https://vega.github.io/vega-lite/docs/size.html#default-width-and-height
That says this:
```
If the x / y channel has an ordinal scale with rangeStep = null, the width / height is drawn directly from the config.cell.width / config.cell.height property and the band of the scale will be adjusted to fit to the width.
```

I tried this in altair as:
```python
x=alt.X('period', scale=alt.Scale(rangestep=None))
```

But I got the error:
```
KeyError: "Attribute not found: rangestep. Valid keyword arguments for this class: ['bandSize', 'clamp', 'domain', 'exponent', 'nice', 'padding', 'range', 'round', 'type', 'useRawDomain', 'zero']"
```

So I then interrogated altair.Scale?
and got this:
```
Attributes
----------
bandSize: Union(CFloat, BandSize)
    
clamp: Bool
    If true, values that exceed the data domain are clamped to either the minimum or maximum range value.
domain: Union(List(CFloat), List(Unicode), List(DateTime))
    The domain of the scale, representing the set of data values.
exponent: CFloat
    Sets the exponent of the scale transformation.
nice: Union(Bool, NiceTime)
    If specified, modifies the scale domain to use a more human-friendly value range.
padding: CFloat
    Applies spacing among ordinal elements in the scale range.
range: Union(Unicode, List(CFloat), List(Unicode))
    The range of the scale, representing the set of visual values.
round: Bool
    If true, rounds numeric output values to integers.
type: ScaleType
```
Between that and searching on altair's github for 'rangestep' I get 0 results.

I feel it safe to assume it is not implemented.  I know vega-lite is going through a beta for 2.0 so maybe this is a 2.0 feature?  I did not see a way to get docs on their site between the 1.0 release which I think is what vega uses and the upcoming 2.0 release.

Is this currently in altair under another name - or is this indeed a future feature?

**Comment by jakevdp** [comment]
The vega-lite documentation is for Vega-Lite 2.0, and the current Altair release is Vega-Lite 1.0. I'm not sure what the equivalent is in Vega-Lite 1.0, but I am working to release Altair 2.0 and at that point this keyword will be valid.

**Comment by jakevdp** [comment]
fixed in v2
