### ISSUE TITLE
Joyplots with altair

### ISSUE THREAD

**Issue by essicolo** [altair-viz/altair#362]
[`ggjoy`](https://github.com/clauswilke/ggjoy) is a new library in R able to create beatuful joyplots.

![](https://raw.githubusercontent.com/clauswilke/ggjoy/master/man/figures/README-diamonds-1.png)

Can I do it with `altair`? I gisted my unsuccessful attempt [here](https://gist.github.com/essicolo/0461b8043f1f8620bb50c3eb34bb3338).

**Comment by jakevdp** [comment]
Maybe with Altair 2.0. Perhaps @kanitw has some thoughts on this?

**Comment by jheer** [comment]
This should be possible if we support custom modification of scale ranges. A "joy plot" is just a faceted area chart with an exaggerated y-axis scale range. Here is a Vega-Lite 2 example that almost works. (The part where I tried to manually set the y scale range is not respected by Vega-Lite, which instead prints a warning to the console.)

```json
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "width": 300,
  "height": 30,
  "data": {
    "url": "https://vega.github.io/vega-lite/data/unemployment-across-industries.json"
  },
  "mark": {
    "type": "area",
    "interpolate": "monotone"
  },
  "encoding": {
    "x": {
      "timeUnit": "yearmonth",
      "field": "date",
      "type": "temporal",
      "axis": {
        "grid": false,
        "format": "%Y",
        "labelAngle": 0
      }
    },
    "y": {
      "aggregate": "sum",
      "field": "count",
      "type": "quantitative",
      "axis": null,
      "scale": {
        "range": [100, 0]
      }
    },
    "color": {
      "field": "series",
      "type": "nominal",
      "scale": {
        "scheme": "category20b"
      }
    },
    "row": {
      "field": "series",
      "type": "nominal"
    }
  },
  "config": {
    "cell": {"stroke": "transparent"},
    "area": {"fillOpacity": 0.5},
    "title": {"limit": 100}
  }
}
```

**Comment by jheer** [comment]
There is also a potential question of data processing, for example, using KDE to estimate a continuous distribution for discrete data. Vega has KDE built-in and Vega-Lite (in 2.1 or later) should support that to create violin plots, among other examples. (Of course, Altair users could always compute such things directly in Python as well!)
