### ISSUE TITLE
How to get a secondary y-axis?

### ISSUE THREAD

**Issue by drorata** [altair-viz/altair#363]
Is it possible to plot a secondary y-axis? Similar to what [pandas](https://pandas.pydata.org/pandas-docs/stable/visualization.html#plotting-on-a-secondary-y-axis) offers?

**Comment by jakevdp** [comment]
Probably not; see the discussion at #184

**Comment by kanitw** [comment]
Vega-Lite 2's `layer` operator will allow dual axis.  

Here is an example spec: https://github.com/vega/vega-lite/blob/master/examples/specs/layer_bar_dual_axis.vl.json
