### ISSUE TITLE
label width

### ISSUE THREAD

**Issue by mroswell** [altair-viz/altair#368]
I haven't figured out how to get my labels to fully print out. I've explored the altair documentation, the vega documentation, and the d3 documentation
![counts](https://user-images.githubusercontent.com/192568/28992388-4cf0e4e0-7968-11e7-8716-e137d93e2721.png)

https://github.com/d3/d3-format/blob/master/README.md#format
says:
"If not specified, then the width will be determined by the content."
So I guess my content is ellipsed? But the grantor dataframe  definitely has every grant program name fully spelled-out.

```
grantor = pd.DataFrame(df['Name'].value_counts())
grantor.reset_index(inplace=True)
Chart(grantor).mark_bar().encode(y=Y('index', sort=SortField(field='Name', order='ascending'),
        axis=Axis(title='Grant Program')), x='Name')
```

BTW, the oddball "Name" in the X axis is because I converted a series into value_counts which retained the "Name" name for the count column name.

**Comment by mroswell** [comment]
I finally found it!
.configure_axis(labelMaxLength=300)

I kept looking for words like "length" and "padding" and "margin"

So glad!

**Comment by Alcampopiano** [comment]
I wasn't able to find `labelMaxLength` as a possible option. However, `.configure_axis(labelLimit=1000)` seemed to work. Not sure what the recommended method is.

**Comment by jakevdp** [comment]
I think that ``labelMaxLength`` was the available property in Altair 1.0. and labelLimit is the available property in Altair 2.0.

**Comment by Alcampopiano** [comment]
Awesome. Thanks Jake.

**Comment by mroswell** [comment]
I'm returning to this same chart four years later (a surprise when I was Googling for answers to come upon my own original question). I figured out a few updates, wanting to update the x label, and keep the wider Y-axis label.

I replaced this code:
```
Chart(grantor).mark_bar() \
.encode(y=Y('index:N', sort=SortField(field='Name', order='ascending'),
        axis=Axis(title='Grant Program')), x='Name:Q') \
.configure_axis(tickLabelFontSize=12, labelMaxLength=300)
```
With this, for the win:
```
Chart(grantor).mark_bar() \
.encode(y=Y('index:N', sort=SortField(field='Name', order='descending'),
        axis=Axis(title='Grant Program')), x=X('Name:Q', title='Number of Grants')) \
.configure_axis(labelLimit=400)
```
(Not sure why I had to change the order to descending, but it worked.)
