### ISSUE TITLE
infer_dtype FutureWarning

### ISSUE THREAD

**Issue by mroswell** [altair-viz/altair#369]
My first chart always gives me this FutureWarning 

FutureWarning: pandas.lib is deprecated and will be removed in a future version.
You can access infer_dtype as pandas.api.types.infer_dtype
  typ = pd.lib.infer_dtype(data)

This is the chart code... just a standard value_counts() in pandas. (BTW, I didn't know how to use the index as the Y field, so I did a reset_index() to turn it into a column.)
```
grantor = pd.DataFrame(kyf2['Name'].value_counts())
grantor.reset_index(inplace=True)
Chart(grantor).mark_bar().encode(y=Y('index', sort=SortField(field='Name', order='ascending'),
        axis=Axis(title='Grant Program')), x='Name').configure_axis(tickLabelFontSize=12, labelMaxLength=300)
```

Hmmm... I wonder if this is because the field happened to be called "Name" and when it converted via value_counts() into a count field, it was still called Name. Maybe Altair wants a Name to be a string? Any other ideas on why I'm getting this warning?

**Comment by habet700** [comment]
have you tried setting the datatype explicitly by changing y=Y('index:Q', ....) and x='Name:N' ?

https://altair-viz.github.io/documentation/encoding.html#data-types

**Comment by mroswell** [comment]
ah, of course, thanks. I had read about that, and failed to incorporate. (New user here.)
A few comments: 
- FutureWarnings display once, so it can be tricky to see if a given operation resolves the warning. 
- In my case, it'll actually be y=Y('index:N', ....) and x='Name:Q' (The original field was called Name, and when it turned into a count using value_counts() it was still called Name.)
- I'm guessing I'm not the only one who thinks (wrongly!) that N=Numeric and Q equals Qualitative). I wish the letters used my own sense of the  defaults. If anyone sees this message, here's the documentation on these data types, from https://altair-viz.github.io/documentation/encoding.html#data-types

Data Type | Shorthand Code | Description
-- | -- | --
quantitative | Q | a continuous real-valued quantity
ordinal | O | a discrete ordered quantity
nominal | N | a discrete unordered category
temporal | T | a time or date value
