### ISSUE TITLE
In 01-Index.ipynb Graph would not draw  ' chart  '

### ISSUE THREAD

**Issue by BlogBlocks** [altair-viz/altair#371]
Ubuntu 16.04
I updated line 110 - after update the chart was visible

110 #typ = pd.lib.infer_dtype(data)
         pd.api.types.infer_dtype
         typ = pd.lib.infer_dtype(data)

**Comment by jakevdp** [comment]
Thanks – I think this is a combination of a pandas deprecation error and https://github.com/vega/ipyvega/issues/62

It's already fixed in #334; we should be releasing a new version soon.
