### ISSUE TITLE
Use selenium for programmatic figure export

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#373]
We've had trouble with npm dependencies for saving figures. A more robust route (in that it's conda installable and doesn't rely on correctly configuring npm and canvas) would be to follow Bokeh's lead and use selenium: https://github.com/bokeh/bokeh/blob/80fdc90e3852eb2253948d6140bb03464cc85ed0/bokeh/io.py#L627

What they do is render the plot in a headless browser, then take a screenshot and save it. Probably not ideal, but it would at least work as an initial solution.

Further down the road, making vl2png and vl2svg somehow conda installable would be a more complete and robust solution.

**Comment by jheer** [comment]
Given installation issues, potential font rendering issues, and platform inconsistency issues with node canvas, a headless browser-based approach may ultimately be preferable. @arvind put together a headless browser-based approach for VL testing; he might have more insights here.

**Comment by arvind** [comment]
Yes! We use [Headless Chrome](https://developers.google.com/web/updates/2017/04/headless-chrome) which started shipping with Chrome 59. We operate it using [ChromeDriver](https://sites.google.com/a/chromium.org/chromedriver/), which implements Selenium's WebDriver protocol (i.e., can be used as a drop-in replacement for Selenium). In my experience, I've found ChromeDriver easier to get up and running, and more performant than firing up a Selenium server + Firefox (which I believe is the default). 

Once the Vega visualization is rendered, we actually capture the SVG string (using `view.toSVG()`) rather than the rasterized Canvas image (via `view.toCanvas()`). This approach is more resilient to varying platforms/fonts/etc. and allows us to more closely examine changes to the resultant visualization.

Fwiw, vega/vega-lite#2724 is the PR for our runtime integration tests. In particular vega/vega-lite@95ab419, vega/vega-lite@faa56ad, and vega/vega-lite@6b72833 setup ChromeDriver and SVG snapshotting. 

Happy to answer any questions as they come up!

**Comment by jakevdp** [comment]
Thanks @arvind!

**Comment by jakevdp** [comment]
I don't know much about selenium or headless chrome, so this may be a naive question: is there a way in either of these to essentially click the "save to PNG" link to output the file, rather than doing a screen shot?

**Comment by arvind** [comment]
Once you have a WebDriver instance running (be that via Selenium or ChromeDriver directly), you can use it to not only navigate to URLs and traverse the DOM, but execute JavaScript as well. The return value of the commands are then available in your original environment, and can be saved to the filesystem. For example, [here's](https://github.com/vega/vega-lite/commit/6b72833#diff-440b319c0e17fa3773d565a280db8c30R147) the corresponding function in Vega-Lite's runtime tests (where `browser` is a WebDriver instance). We have the browser execute `view.toSVG()`, an SVG string is returned to our test script which then saves it to the file system.

[It would appear](https://stackoverflow.com/questions/5585343/getting-the-return-value-of-javascript-code-in-selenium/5585345#5585345) that Python's WebDriver bindings offer the same functionality as well.

Hope that helps!

**Comment by arvind** [comment]
To get the PNG, you'd instead need to execute something like this (haven't tested it):

```python
png = wd.execute_async_script("""
  view.toCanvas().then(function(canvas) {
    done(canvas.toDataURL('image/png'));
  });
""")
```

**Comment by jakevdp** [comment]
Awesome – thanks! Makes me wonder why the Bokeh folks used the screenshot rather than the bokehjs PNG export... I'll look into this some more once [Altair 2.0](https://github.com/altair-viz/altair/pull/374) is ready to go.

**Comment by normaljosh** [comment]
I've managed to get selenium working with headless chrome and the export_png function built into bokeh, it's significantly faster than export_png with no driver specified. Steps I took: 

- Download chrome webdriver from [https://sites.google.com/a/chromium.org/chromedriver/downloads](https://sites.google.com/a/chromium.org/chromedriver/downloads)
- Save driver file and note path
- run code below: 
```
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from bokeh.plotting import figure, show, output_file
from bokeh.sampledata.iris import flowers
from bokeh.io import export_png

options = Options()
options.add_argument("start-maximized")
options.add_argument("disable-infobars")
options.add_argument("--disable-extensions")
options.add_argument('--headless')
driver = webdriver.Chrome(chrome_options=options, executable_path=r'C:\Users\jleibowitz\Python stuff\Selenium\chromedriver.exe')

(create bokeh figure "p")
         
export_png(p, filename=r"PATH.png",  webdriver=driver)
```

**Comment by jakevdp** [comment]
Here's an initial prototype that I got working this morning. It needs to be streamlined a bit: for example, it would be better to construct the view directly rather than using ``vegaEmbed``. I also tried using promises more directly rather than saving things to ``window.*``, but selenium seems to hang every time I try an async call from Python.

```python
import os
import io
import base64
import tempfile

from PIL import Image
from selenium import webdriver
from selenium.webdriver.chrome.options import Options

HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
  <script src="https://cdn.jsdelivr.net/npm/vega@3.0.10"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-lite@2.1.3"></script>
  <script src="https://cdn.jsdelivr.net/npm/vega-embed@3.0.0"></script>
</head>
<body>
  <div id="vis"></div>
</body>
</html>
"""

EMBED_CODE = """
vegaEmbed("#vis", {spec}).then(function(result) {{
    window.view = result.view;
}}).catch(console.error);
"""

CONVERT_CODE = """
window.view.toCanvas().then(function(canvas) {
    window.png_render = canvas.toDataURL('image/png');
})
"""

EXTRACT_CODE = """
return window.png_render;
"""

def save_spec(spec, filename):
    try:
        chrome_options = Options()  
        chrome_options.add_argument("--headless")  
        driver = webdriver.Chrome(chrome_options=chrome_options)
        try:
            fd, name = tempfile.mkstemp(suffix='.html', text=True)
            with open(name, 'w') as f:
                f.write(HTML_TEMPLATE)
            driver.get("file://" + name)
            driver.execute_script(EMBED_CODE.format(spec=spec))
            driver.execute_script(CONVERT_CODE)
            png_base64 = driver.execute_script(EXTRACT_CODE) 
        finally:
            os.remove(name)
    finally:
        driver.close()
    
    out = io.BytesIO()
    metadata, image = png_base64.split(',')
    base64.decode(io.BytesIO(image.encode()), out)
    out.seek(0)
    image = Image.open(out)
    image.save(filename)
```

```
spec = """
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.0.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
"""

save_spec(spec, 'output.png')
```

**Comment by jakevdp** [comment]
done in v2
