### ISSUE TITLE
404 for vega-lite.js when exporting to html

### ISSUE THREAD

**Issue by dave-gg** [altair-viz/altair#378]
After exporting to html, and opening the file in a web browser, the console shows:
```
404 Loading failed for the <script> with source “https://vega.github.io/vega-lite/vega-lite.js”
```

**Comment by guzbrush** [comment]
Try replacing

	<script src="https://d3js.org/d3.v3.min.js"></script>
  	<script src="https://vega.github.io/vega/vega.js"></script>
  	<script src="https://vega.github.io/vega-lite/vega-lite.js"></script>
  	<script src="https://vega.github.io/vega-editor/vendor/vega-embed.js" charset="utf-8"></script>

with 

	<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.17/d3.js" charset="utf-8"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/vega/2.6.5/vega.js" charset="utf-8"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/vega-lite/1.3.1/vega-lite.js" charset="utf-8"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/vega-embed/2.2.0/vega-embed.js" charset="utf-8"></script>

in

 ...python3.5/site-packages/altair/utils/html.py

**Comment by jakevdp** [comment]
Hi – this has been fixed in master, but those fixes have not yet made it into a release. In the meantime, if you install altair from github it should fix the issue. Thanks!
