### ISSUE TITLE
Add interactions: zooming, panning, selection

### ISSUE THREAD

**Issue by pberkes** [altair-viz/altair#381]
The functionality is available in `vega-lite` https://idl.cs.washington.edu/papers/vega-lite/, but has not been exposed yet in `altair`

**Comment by pberkes** [comment]
I see a `composition-interaction-prototype` branch... is this something that has been discussed already?

**Comment by afonit** [comment]
@pberkes , that sounds like a 2.0 feature,
see here for progress:
https://github.com/altair-viz/altair/pull/374

as @jakevdp has said elsewhere - he is the only one working on this and he is out on leave at the moment.

**Comment by ellisonbg** [comment]
Yes, this will be part of the 2.0 release.

**Comment by jakevdp** [comment]
done in v2
