### ISSUE TITLE
Autogenerate Vega API as well

### ISSUE THREAD

**Issue by falconair** [altair-viz/altair#382]
Vega, unlike vega-lite, supports many more types of charts such as sunburst, arc diagrams, parallel coordinates, etc. Any chance Altair will work with vega?

**Comment by ellisonbg** [comment]
Yes, we now have the ability to autogenerate Python classes for Vega as well. @jakevdp would know more about when we would begin to ship that. I am guessing it would be in 2.0.

**Comment by jakevdp** [comment]
I think it will be possible in the future, though it may be a bit ambitious for 2.0... I'm excited to explore the possibility, though!

**Comment by jakevdp** [comment]
done in v2

**Comment by djarecka** [comment]
anyone can point me to an example of using Altair to plot parallel coordinates?

**Comment by jakevdp** [comment]
It's possible, though you have to transfor the data to turn column names into column values (see https://altair-viz.github.io/user_guide/data.html#converting-between-long-form-and-wide-form for a discussion of data formats).

For example, with the iris data:

```python
import altair as alt
from vega_datasets import data

iris = data.iris()
iris_transformed = iris.reset_index().melt(['species', 'index'])

alt.Chart(iris_transformed).mark_line().encode(
    x='variable:N',
    y='value:Q',
    color='species:N',
    detail='index:N'
).properties(width=400)
```
![visualization 3](https://user-images.githubusercontent.com/781659/40248754-cacfe79a-5a85-11e8-8a1f-eecc7c562b3f.png)

I think it would be worth adding this as an example.

**Comment by jakevdp** [comment]
example added in #869

**Comment by djarecka** [comment]
@jakevdp - thanks, this looks cool! 

I have follow-up questions --  is there a way to add multiple y-axes? Can I have interaction for multiple axes?  i.e. can I choose to show only data for specific `petalWidth` values and specific `sepalLength` values.
Using your PyCon tutorial (thanks a lot, it's great!), I was able to add interaction with y-axis, but it's only using values from the last, `sepalWidth`, axis and couldn't find a way to change it.

```
interval = alt.selection_interval(encodings=["y"])
iris = data.iris()
iris_transformed = iris.reset_index().melt(['species', 'index'])

alt.Chart(iris_transformed).mark_line().encode(
    x='variable:N',
    y='value:Q',
    #color='species:N',
    color=alt.condition(interval, 'species:N', alt.value('lightgray')),
    detail='index:N'
).properties(width=400, selection=interval)
```

I'm just learning Altair, and trying to figure out how much I can do without writing d3 code. Ideally, I'd like to have something similar to [this](http://openneu.ro/metasearch/)...

**Comment by jakevdp** [comment]
You can do mulitple y axes using a [layer](https://altair-viz.github.io/user_guide/compound_charts.html#layered-charts), and each of these can have an independent selection if you wish.
