### ISSUE TITLE
Can we avoid repetition?

### ISSUE THREAD

**Issue by isty2e** [altair-viz/altair#383]
I've used Altair for months, though not very extensively. Somehow I tried to draw a scatter plot with error bars which ended up using [plotnine](https://github.com/has2k1/plotnine) instead of altair. I wrote a [reddit post](https://www.reddit.com/r/Python/comments/704e9f/when_i_tried_to_visualize_my_data_with_python/) about it, if you are interested in which plot I was going to draw.

For this purpose, I looked up examples and when I saw [this](https://altair-viz.github.io/gallery/errorbar_aggregate.html), I was disappointed. It is not because it is hard to plot the data without several transformation, since vega-lite 2.0 supports a more powerful transformation, but because of the amount of code reuse. 

I know that there would be several workarounds, but can we have some kind of native support to minimize repetition?

**Comment by ellisonbg** [comment]
Yep, the error bar support in Vega-Lite 1.x is pretty painful from a user's perspective. I think this is improved in Vega-Lite 2.0 as you mention. But we are constrained in Altair to exposing what Vega-Lite does. At the same time, after the Vega-Lite API stablizes, we could add some addition APIs to make certain things easier.

**Comment by jakevdp** [comment]
addressed in v2
