### ISSUE TITLE
Documentation content updates

### ISSUE THREAD

**Issue by ellisonbg** [altair-viz/altair#402]
Keeping track of the things we need to update in the docs for 1.2.1:

- [ ] Use `import altair as alt`
- [ ] More notes about how to get altair working in JupyterLab/nteract using `enable_mime_rendering`

Feel free to add more...

**Comment by jakevdp** [comment]
This may be for a future milestone, but I think we should eventually make the auto-generated examples less prominent, and create more altair examples by-hand. The problem with the auto-generated code is that it tends to make Altair appear more complicated than it actually is.

**Comment by ellisonbg** [comment]
I am going to work on this on the plane today...
