### ISSUE TITLE
Altair 2.0 Decisions

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#411]
A running list of some decisions we need to make in Altair 2.0

- How to handle Config, which is only valid at the top-level of a compound chart (and should be thought of as a theme for all the underlying charts)
- How to deal with assigning constant values to channels (e.g. ``color=alt.C('red')``)

**Comment by kanitw** [comment]
- [ ] How to handle mark property https://github.com/altair-viz/altair/issues/406
- [ ] View Composition Operator Syntax
- Selection (for interactions)
 - [ ] Declaration Syntax
 - [ ] Application of selections
    - [ ] condition
    - [ ] filter
    - [ ] scale domain

**Comment by jakevdp** [comment]
Superseded by #459
