### ISSUE TITLE
Docs usability/readability issues

### ISSUE THREAD

**Issue by mroswell** [altair-viz/altair#415]
We should fix cell wrap within tables, for instance at:
https://altair-viz.github.io/API.html#encoding-channels

So far have tried solutions offered here without success:
* https://stackoverflow.com/questions/1057574/html-td-wrap-text
* https://stackoverflow.com/questions/6666532/how-to-force-table-cell-td-content-to-wrap

But I found this offered solution that's specific to the ReadTheDocs issue. 
Will see if I can get it to work.
http://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html

(On the plus side, ReadTheDocs theme added or improved the following: Left sidebar, search, much more readable number of characters per line, responsive!)

**Comment by jakevdp** [comment]
Thanks!

**Comment by mroswell** [comment]
So, the fix at:
http://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html
does fix the wrapping problem, but it creates one new problem, which is that the minigallery becomes a single entry per line, with each chart separated by a lot of space. It has nothing to do with the particular CSS and apparently everything to do with the very existence of the new docs/_static/theme_overrides.css file.

in other words, just adding this to conf.py (along with an empty theme_overrides.css file) causes the minigallery to stop looking like a minigallery. I don't see any other impacts from this solution.

```
html_context = {
    'css_files': [
        '_static/theme_overrides.css',  # override wide tables in RTD theme
        ],
    }
```

I could do a Pull Request (and need to set myself up to do that, since I'm currently cloning from the live site), but fair warning, that the home page is impacted.

**Comment by mroswell** [comment]
I propose instead of:

> Note: Altair and the underlying Vega-Lite library are under active development, and the documentation here remains incomplete. We are currently (October 2017) working on support for Vega-Lite 2.0, and plan to significantly improve the documentation once that is released.

that the docs home pages should say:

> Note: Altair and the underlying Vega-Lite library are under active development, and the documentation here, **although extensive** remains incomplete. We are currently (October 2017) working on support for Vega-Lite 2.0, and plan to significantly **expand** the documentation once that is released.

I think the current text underestimates the value of the current documentation

**Comment by mroswell** [comment]
Fixing typo at https://altair-viz.github.io/API.html

> To use this **is** the classic Jupyter Notebook, the ipyvega package must be installed.
(is -->  in)
My PR on the  typo fix for this is combined with cell text wrap PR above. 

Note 1: I can probably use some guidance on staging PRs (everything in branches? how to do separate PRs for unrelated things, etc? PR etiquette, etc.).

Note 2: I'm thinking this issue (415) will involve a miscellany of small DOCs issues. If anything should be split out, let me know that, too.

Margie

**Comment by mroswell** [comment]
I propose this change to the (hopefully) new docs/_static/theme_overrides.css file. The proposed change applies to the `<dt>` elements in https://altair-viz.github.io/API.html
```
.rst-content dl:not(.docutils) dt em {
    font-style: normal;
    line-height: 1.4em;
}
```
I realize the `<em>` tag is usually italicized, but it strikes me as particularly difficult to read the italicized font with all of those parameters in this case. The little extra line spacing also seems helpful. Adding to the two notes above, I am thinking that perhaps even for little things like this, I should create a separate branch, per pull request concept?

**Comment by mroswell** [comment]
The first image in the opening page minigallery is a bit boring. I might suggest replacing it with the GitHub punch card. Perhaps also replace the third image with Becker’s Barley Trellis Plot, since image 3 is so similar to image 4.

**Comment by jakevdp** [comment]
Thanks for the comments here – this would be a great place to try a pull request! Basic workflow is this:

1. Fork the repository (button is at the top of the main [altair page](https://github.com/altair-viz/altair) on github)
2. Clone your fork to get the copy locally
3. Create a new branch
4. Make your changes and commit them to the branch
5. Push that branch to your fork
6. Click the "create pull request" button that then appears on github

Github has some info on parts of this here: https://help.github.com/articles/creating-a-pull-request/
Let me know if you have any questions!

Also, for small changes (like re-wording the Note above) you can do this all via the web interface, by clicking the "edit" button on any file on github. It will then pop-up a dialog box to ask if you want to create a pull request with your edits.

**Comment by jakevdp** [comment]
I've been meaning to do this for a while: I just posted a 5-minute video demonstrating the steps in creating a pull request. Hope this is helpful! https://www.youtube.com/watch?v=rgbCcBNZcdQ

**Comment by mroswell** [comment]
A couple of notes:
- I created a Pull Request for the table fix yesterday https://github.com/altair-viz/altair/pull/418
- I guess my mistakes were not creating a branch first, and not announcing it here (I had figured that referencing it by number in the comments was all I needed to do. But I guess a mention on the issue is also helpful? Also, another small typo fix ended up in the same PR (which would've been addressed had I created a branch)
- The video is helpful, but not quite enough information. Addressing two different approaches to GH PRs below:
  - if I change something in my repo, and do a PR, there will still be all sorts of edits going on in the upstream repo. So at this point I've got:

  ```
  $ git remote -v
  origin	https://github.com/mroswell/altair.git (fetch)
  origin	https://github.com/mroswell/altair.git (push)
  ```
  (Initially I had cloned altair-viz/altair directly, and tried fiddling with git remote add upstream, etc. , but ended up scratching it, and using a straight fork. At one point I created both an upstream and an origin, but i honestly don't know how to use an upstream. I found myself at points having the sublime editor open up, having to manually comment and close the file, which yielded multiple commits. So, yesterday I just went ahead and forked the repo, made the changes again there, and got a more straightforward commit. And I'm using that forked repo moving forward. 

**But once I've forked, how do I keep the repos current?** And I totally agree with you, that a demo video (when possible) helps cut out all the mass of possible web answers.) Yesterday I found myself looking in the depths of git clean commands, and figured that all looked too scary (that I might lose my new rst file, for instance, that I hadn't yet added.

  - The other method (that I've used frequently over the years) is using the web interface for quick typo fixes. But that creates the opposite situation. Now I'd get a patch branch (if I recall) and I'm not sure how to integrate them into my own local repo if the PR is accepted.

In any case, for now, I guess the key summary questions are:
- Should I create a git add remote upstream? if so, how do I use it so that I'm current at all times? 
- Since I already made those commits in the PR to master rather than a branch, what should I do? Do you want to test it out, or should I redo and make two branches, making the changes in each separate branch, and do another PR?
- If I use the web interface for quick typo fixes, how to incorporate those locally?
- Is it a good protocol to reference the issue by number, and add a comment to the issue as well? 
- Are there any naming conventions for branches? for instance if I do a bunch of these little commits, docs1, docs2, docs3, or maybe something more descriptive... I'm guessing all those branches eventually get deleted... do I delete them myself, or somehow figure out how to incorporate everything upstream?

Sorry so long, but hope this post helps describes the current state... and state of understanding/gaps.

**Comment by jakevdp** [comment]
Ah, I missed that PR! I'll take a look. And using master for a PR is OK, it just can complicate keeping your fork up-to-date with the main repository.

**Comment by jakevdp** [comment]
I've reworded the Note and changed the examples at the top of the page. Let me know if that looks good!
