### ISSUE TITLE
to_html() and to_altair() documentation and function issues

### ISSUE THREAD

**Issue by mroswell** [altair-viz/altair#420]
https://altair-viz.github.io/documentation/displaying.html#obtaining-other-representations
has a typo which I aimed to fix, but I wanted to understand the section to be optimally helpful. So, this brought me down a rabbit hole:
- The 'obtaining-other-representation' section notes that charts can be represented as HTML, but no `to_html()` is mentioned
- I thought I would try it anyhow, in a Jupyter notebook, I got:
`ImportError: No module named html`
- I tried `pip install html` and got 
  ```
  Collecting html
  Using cached html-1.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/cr/2m5226bs6qd7p7y4q892d_dh0000gn/T/pip-build-otmns4eg/html/setup.py", line 12, in <module>
        long_description = __doc__.decode('utf8'),
    AttributeError: 'str' object has no attribute 'decode'

    ----------------------------------------
  Command "python setup.py egg_info" failed with error code 1 in 
  /private/var/folders/cr/2m5226bs6qd7p7y4q892d_dh0000gn/T/pip-build-otmns4eg/html/
  ```
- So, that was a dead-end, but makes me wonder why it mentions that `Altair charts can be represented as HTML...` and what I'd have to do to make that work. (I'm working in python 3 in a virtual environment, since I couldn't get sphinx to work in Python 2). I now see the section (above where it mentions that charts can be represented as HTML) that includes: `chart.savechart('plot.html')` but I still get the `ImportError: No module named html`
  
- Additionally, there is another method listed, Chart.to_altair(), but it's hyperlinked to a section of the docs that says `DEPRECATED. Use to_python() instead.`
- The word 'provides' appears twice, and the methods are listed in a manner that splits the sentence down the middle.

A summary:
- should we remove to_altair() and replace with to_python()?
- should the section include to_html()?
- how do we get to_html() to work?
- typo and formatting issues

Any insight welcome.

**Comment by jakevdp** [comment]
I'm unable to reproduce that error.  ``to_html()`` works for me in both python 2.7 and 3.5... I don't know what ``pip install html`` does but that is not a requirement of Altair.

Yes, we've deprecated ``to_altair()`` and ``to_python()`` should be used instead. That should be updated in the docs.

**Comment by jakevdp** [comment]
``to_html`` and ``to_altair`` no longer exist in version 2
