### ISSUE TITLE
Set different Y-axis scale/range for each row

### ISSUE THREAD

**Issue by zml** [altair-viz/altair#428]
Is it possible to define or auto-set different y-axis ranges for different rows ? 
For instance, in the  [trellis_bar](https://altair-viz.github.io/gallery/trellis_bar_histogram.html) example, I would like to display a y-axis range that would better capture the data range. 

In the default implementation (code below), the y-axis is set as the maximum range of all the rows, which in this case all the rows range between  ymin=0 and ymax=80. 

```python
from altair import *

Chart('https://vega.github.io/vega-lite/data/cars.json').mark_bar().encode(
    row='Origin:N',
    x=X('Horsepower:Q',
        bin=Bin(
            maxbins=15.0,
        ),
    ),
    y='count(*):Q',
)
```
Is there any way to change the display for each row?  I would prefer a "zoomed" range for each row like : 
row 1 : [0,40]
row 2:  [0,50]
row 3:  [0,80]

**Comment by kanitw** [comment]
In the underlying Vega-Lite, you can set `"resolve": {"scale": {"y": "independent"}}` to achieve this e.g.,

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "data": {"url": "data/cars.json"},
  "mark": "bar",
  "encoding": {
    "x": {
      "bin": {"maxbins": 15},
      "field": "Horsepower",
      "type": "quantitative"
    },
    "y": {
      "aggregate": "count",
      "type": "quantitative"
    },
    "row": {"field": "Origin", "type": "nominal"}
  },
  "resolve": {"scale": {"y": "independent"}}
}
```

I think Altair probably has a command to generate this resolve specification.

**Comment by jakevdp** [comment]
In Altair you can do this with the ``resolve_scale`` method: ``chart.resolve_scale(axis='independent')``

**Comment by jimmywan** [comment]
> In Altair you can do this with the resolve_scale method

I saw this example which works:
https://altair-viz.github.io/gallery/layered_plot_with_dual_axis.html?highlight=resolve_scale

But I just tried modifying the example from the OP and it fails.
```python
from altair import *

Chart('https://vega.github.io/vega-lite/data/cars.json').mark_bar().encode(
    row='Origin:N',
    x=X('Horsepower:Q',
        bin=Bin(
            maxbins=15.0,
        ),
    ),
    y='count(*):Q',
).resolve_scale(
    y='independent'
)
```

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-20-91888efea29a> in <module>()
     10     y='count(*):Q',
     11 ).resolve_scale(
---> 12     y='independent'
     13 )

/opt/conda/lib/python3.6/site-packages/altair/vegalite/v2/api.py in resolve_scale(self, *args, **kwargs)
    900     @utils.use_signature(core.ScaleResolveMap)
    901     def resolve_scale(self, *args, **kwargs):
--> 902         return self._set_resolve(scale=core.ScaleResolveMap(*args, **kwargs))
    903 
    904     # Display-related methods

/opt/conda/lib/python3.6/site-packages/altair/vegalite/v2/api.py in _set_resolve(self, **kwargs)
    882         if not hasattr(self, 'resolve'):
    883             raise ValueError("{0} object has no attribute "
--> 884                              "'resolve'".format(self.__class__))
    885         copy = self.copy()
    886         if copy.resolve is Undefined:

ValueError: <class 'altair.vegalite.v2.api.Chart'> object has no attribute 'resolve'
```

**Comment by jakevdp** [comment]
You can only set a resolve property for a compound chart (i.e. Layer, hconcat, vconcat, etc.) the chart you use is not a compound chart, so it's not valid to set a resolve property.

**Comment by jakevdp** [comment]
What is it you are trying to accomplish?

**Comment by jimmywan** [comment]
> You can only set a resolve property for a compound chart (i.e. Layer, hconcat, vconcat, etc.) the chart you use is not a compound chart, so it's not valid to set a resolve property.

Right that makes complete sense. Sorry, just coming back to this issue since I missed the response to my original asked and blindly repurposed OP example and hadn't thought through the answer which was to my question. Works like a charm.

facet:
![image](https://user-images.githubusercontent.com/10406673/41360701-fb096a04-6ef2-11e8-97e5-6ec576cb8507.png)
facet w/ scale_independent:
![image](https://user-images.githubusercontent.com/10406673/41360718-0434c34e-6ef3-11e8-8ef2-6fd0f2ccac82.png)

**Comment by jakevdp** [comment]
Great, glad it worked!

**Comment by jimmywan** [comment]
@mkudija Unfortunately I've trashed my example which was an obfuscated version of a dataset I can't share, but if you have a working facet, just do this:
```python
box_and_whisker.facet(data=base_df, column='facet_column').resolve_scale(y='independent')
```

**Comment by mkudija** [comment]
Thanks @jimmywan!

Below are two quick examples of setting independent x- and y- axes for anyone who may stumble upon this in the future:

## Independent X-Axis
```python
import altair as alt
from vega_datasets import data
alt.data_transformers.enable('json')

cars = data.cars()

c=alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Cylinders:O'
).properties(
    title='Independent-X',
    width=300,
    height=150,
).facet(
    row='Origin',
).resolve_scale(
    x='independent'
)
```
<img src="https://user-images.githubusercontent.com/14117837/41493378-9518a4ba-70d4-11e8-95c7-7a5425a8f482.png" width="50%" height="50%">


## Independent Y-Axis

```python
import altair as alt
from vega_datasets import data
alt.data_transformers.enable('json')

cars = data.cars()

c=alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Cylinders:O'
).properties(
    title='Independent-Y',
    width=300,
    height=150,
).facet(
    column='Origin',
).resolve_scale(
    y='independent'
)
```

![image](https://user-images.githubusercontent.com/14117837/41493351-57575c7a-70d4-11e8-9b79-05ca7be56670.png)

**Comment by xujiboy** [comment]
May I know if it's possible to specify "independence" __only__ across certain facet? For example, in the chart shown below, I wonder if it is possible to ask (1) __AND__ (2)
(1) the `y` axis scale to be dependent / aligned within each row
(2) the `y` axis scale to be independent between each row

Currently the scale of `y` axis is independent across both row and column facets.

``` python
import altair as alt

cars = alt.datasets.load_dataset('cars')
chart = alt.Chart(cars).mark_point().encode(
    alt.X('Acceleration:Q'),
    alt.Y('Horsepower:Q')
).properties(
    width=200,
    height=200
).facet(
    row='Cylinders:O',
    column='Origin:N'
).resolve_scale(y='independent')
chart

```
![visualization](https://user-images.githubusercontent.com/10766549/53193735-9b7d7d00-35c6-11e9-8f7a-84276a69bdc4.png)

**Comment by jakevdp** [comment]
> May I know if it's possible to specify "independence" **only** across certain facet?

No, there's no way to specify different resolves within facets. As a workaround, you could facet your data manually (using filter transforms) and vconcat the rows, and then you can set a different resolve property for each row.

**Comment by xujiboy** [comment]
@jakevdp Thanks for the explanation. With reference to the [FacetChart](https://altair-viz.github.io/user_guide/compound_charts.html?highlight=filter%20transform#faceted-charts) documentation, I was able to generate the equivalent column facets with independent `y` axis scale using filter transform. The only problem is that, for data with empty facets the alignment could be off ... 

![visualization](https://user-images.githubusercontent.com/10766549/53204937-c2957800-35e1-11e9-9a6d-8f2677587b23.png)
The chart above is produced with the following code:
``` python
import altair as alt
from altair.expr import datum

def manual_faceting_with_filter_transform():
    cars = alt.datasets.load_dataset('cars')
    base = alt.Chart(cars).mark_point().encode(
        alt.X('Acceleration:Q'),
        alt.Y('Horsepower:Q')
    ).properties(
        width=150,
        height=100
    ).facet(
        column='Origin:N'
    )
    
    chart = alt.hconcat()
    for num_cylinders in cars['Cylinders'].unique():
        chart &= base.transform_filter(datum.Cylinders == num_cylinders) 
    
    return chart
```

**Comment by jowens** [comment]
@jakevdp How might one use `hconcat` and make the y axes _dependent_ (same for both plots I'm putting there)? 

(Why are you using `hconcat` and not facet, John? Well, each of the two plots I need to make have two of the four `tag`s that I care about, so facet isn't so well suited for it.

```
chart = hconcat()
for tags in [
        ["a", "b"],
        ["c", "d"]
]:
    chart |= base.transform_filter(
        FieldOneOfPredicate(field='tag', oneOf=tags))
```
)

**Comment by jowens** [comment]
![coloring_count_vs_runtime_all](https://user-images.githubusercontent.com/976970/53843962-092b9080-3f59-11e9-9391-04c17bd889ac.png)
