### ISSUE TITLE
Float (fraction 0 to 1.0) column displaying with "m" suffix

### ISSUE THREAD

**Issue by desmond-dsouza** [altair-viz/altair#431]
Intermittent strange labels on y-axis ticks.

The data frame:
![image](https://user-images.githubusercontent.com/4407158/32412444-290db48a-c1c6-11e7-8d04-3dc91d8a0ffa.png)

The chart with the strange "m" suffix on y-axis (only shows up intermittently):

![image](https://user-images.githubusercontent.com/4407158/32412448-402cef0a-c1c6-11e7-8438-c75730117740.png)

**Comment by jakevdp** [comment]
Hi – this is a known issue that is fixed in newer versions of Vega-Lite... I searched but couldn't find the previous issue where this is addressed.
