### ISSUE TITLE
Tutorial confusion

### ISSUE THREAD

**Issue by michaelaye** [altair-viz/altair#432]
In `02-Tutorial.ipynb` 
there is this sentence:

> Notice that now in addition to the data, the specification includes information about the mark type.

after assigning this to the `chart` variable:

```python
chart = alt.Chart(data).mark_point()
```
apparently pointing to the JSON element `'mark': 'point'`?

I'm puzzled because already in the previous object creation:

```python
chart = alt.Chart(data)
```
there is the same line in the JSON dictionary? This is the result from `alt.Chart(data).to_dict()`:

```python
{'$schema': 'https://vega.github.io/schema/vega-lite/v1.2.1.json',
 'data': {'values': [{'a': 'C', 'b': 2},
   {'a': 'C', 'b': 7},
   {'a': 'C', 'b': 4},
   {'a': 'D', 'b': 1},
   {'a': 'D', 'b': 2},
   {'a': 'D', 'b': 6},
   {'a': 'E', 'b': 8},
   {'a': 'E', 'b': 4},
   {'a': 'E', 'b': 7}]},
 'mark': 'point'}
```

Has the mark type spec maybe been added as a default in the mean time and the Tutorial needs updating ? If that's the case, I can remove that sentence for you to avoid the confusion? Let me know.

**Comment by jakevdp** [comment]
The default mark is removed in version 2.0
