### ISSUE TITLE
Layer vs layers in vega-lite

### ISSUE THREAD

**Issue by xhochy** [altair-viz/altair#437]
I have been playing around with Altair in the recent days and have noticed that when using the latest  vega-lite Javascript libraries in combination with Altair, everything seems to work except that when using a `LayeredChart`, the layers are the put in the JSON dict in the `layers` array whereas vega-lite expects them in `layer`. Is this a bug either in Altair or vega-lite (either as a real bug or a missing version compatibility layer) or expect as I need to ensure that the vega-lite major version matches the support version of Altair?

**Comment by kanitw** [comment]
In Vega-lite v1, `layers` was an experimental feature (not officially supported) that is renamed to just `layer`in Vega-Lite v2.  Once Altair is upgraded to Vega-Lite v2, layering should be correctly supported.

**Comment by xhochy** [comment]
Is/are there any issue(s) that I can track for the vega-lite v2 upgrade of Altair?

Would a patch to the current Altair version be accepted that would add a flag to `LayeredChart` or a central option so that layers are correctly rendered according to the v2 spec?

**Comment by afonit** [comment]
@xhochy - take a look at this pull request:
https://github.com/altair-viz/altair/pull/403

**Comment by jakevdp** [comment]
Fixed in v2
