### ISSUE TITLE
transform, filter

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#491]
I was working on reproducing some of the more advanced examples - but I was running into an issue of using the transform/filter.

I decided to look for a simpler example that uses filter:
https://vega.github.io/vega-lite/examples/line_step.html

```python
"""
Step Chart
-----------------
This example shows Google's stock price over time.
"""

import altair as alt
from vega_datasets import data

source = data.stocks()

chart = alt.Chart(source).mark_line().encode(
    x = 'date',
    y = 'price'
)

chart.transform = {"filter": "datum.symbol==='GOOG'"}
chart
```
ValidationError: {'filter': "datum.symbol==='GOOG'"} is not of type 'array'

I never really got a hang of this in v1 with the from altair import expr.

So I am looking for how to do this in v2 and build out some good examples around it.  The next example I would like to take is the 'Ranged Dot Plot' in vega-lite where there are multiple fields that need filtering.

Normally I would just do this in pandas before the data gets to the chart - but I recall reading that one of the goals of vega-lite/altair is to handle all this in the code for the visualization.

**Comment by jakevdp** [comment]
In v2, transform must be a list of transforms. So it will work if you do this:

```python
chart.transform = [{"filter": "datum.symbol==='GOOG'"}]
```

or, equivalently,

```python
chart.transform = [alt.FilterTransform('datum.symbol === "GOOG"')]
```

I suspect we'll be adding something along the lines of ``chart.add_filter_transform()`` or something similar to make this more intuitive and discoverable.

**Comment by afonit** [comment]
perfect, thanks.
