### ISSUE TITLE
Change language of timeline-stripplot

### ISSUE THREAD

**Issue by HalukaMB** [altair-viz/altair#505]
Hey dear all,

I really love what you guys provide with Altair and it is a lot of fun to play around with it. I was wondering, if there is a way to change ticks on a timeline-stripplot into another languages datetime-format (in my case German). I have tried just changing the locale but that had no effect on the graph. Is there a way to custom-map axis ticks from the data-values in the dataset to something converted without the order of the ticks being scrambled up?

Again thank you so much for all your work

```
alt.Chart(terrordata,
    description='Shows the frequency of terror attacks between two countries.',
).mark_tick(tickThickness=1.5, font="arial").encode(   
x=alt.X('date:T',axis=alt.Axis(format='%B %Y',title='', labelAngle=0, axisWidth=0,ticks=4, orient="top",)),
    y=alt.Y('country:N',axis=alt.Axis(title='', axisWidth=0), font="Helvetica Neue", fontsize=20),
    color=alt.Color("casualties:Q",
            legend=alt.Legend(
                title='Todeszahlen',
                titleFont="s-font-serif",
                titleFontWeight="12",
            ),
            scale=alt.Scale(
                domain=['0', '5'],
                range=['#ffb6b6', '#e23b3c'],
            ),
        ),).configure_cell( width=800).configure_scale(bandSize=100).configure_axis(
    titleFont="s-font-serif",
    titleFontSize=16,
    tickLabelFont="s-font-serif",
    tickLabelFontSize=12,
    tickSize=0
)
```

![stripplot](https://user-images.githubusercontent.com/18502037/36681517-1a0ec6e8-1b19-11e8-8faf-4260723003f9.jpg)

**Comment by jakevdp** [comment]
I'm not sure... @domoritz or @kanitw, can you help with this?

**Comment by HalukaMB** [comment]
I was literally just changing by using
```

import locale
locale.setlocale(locale.LC_ALL, 'de_DE')

```
hoping this might do it. 

Is there a way to manually change the title of the ticks by using mapping or parsing in a list of strings?

**Comment by domoritz** [comment]
Setting the locale in Python does not set the locale in JavaScript. 

I can add a way to set the locale in ipyvega but I don't know how that would work in JupyterLab. @ellisonbg will know.

**Comment by HalukaMB** [comment]
I hoped that it would transform the data before getting converted into Vega. Anyway, is there a way to custommap values in Altair using something like a dictoinary? Like having values from 0 to 60 in the data but then defining the x-axis with the labels 
{x<20:"low", 20=<x<40: "mid", x>40: "high"}

**Comment by domoritz** [comment]
@HalukaMB I think the cleanest way to do that is to preprocess the data in Pandas and pass it to Altair.

**Comment by HalukaMB** [comment]
Yes, but how do I sort then by date on the altair-axis after changing the English dates to German ones in pandas?

**Comment by domoritz** [comment]
@HalukaMB We should figure out how to set the locale from Altair so you don't have to do that.

**Comment by HalukaMB** [comment]
That would be amazing guys. And also if there is a way to implement Python's apply and map functions into certain parts of the graphics that would be amazing!

**Comment by domoritz** [comment]
@HalukaMB Can you file a separate issue with an example?

**Comment by domoritz** [comment]
@ellisonbg Is there a way to know the locale in a JupyterLab extension? If so, we could pass that information to Vega.

**Comment by lcvriend** [comment]
Like the original poster, I would like to change the language for displaying datetime data.

Is there some way I can pass a specified locale to Vega with Altair? Preferably, I would be able to change the language when rendering to Jupyter Lab. However, if this is currently not possible, then it still would be very useful to know if it is possible to generate a Vega specification that will use my locale when viewed as html. 

Any suggestions are greatly appreciated!

**Comment by domoritz** [comment]
Vega-Embed 6.1.0 supports formatLocale and timeFormatLocale. I think this issue can be closed.

**Comment by victornoel** [comment]
It's not clear though how altair passes the config with this information to vega-embed... well maybe it is but I couldn't find the information in the documentation :)

**Comment by jakevdp** [comment]
Altair cannot currently pass locale information to vega-embed. If you want to adjust locale, I'd suggest exporting the chart as JSON and use vega-embed directly.

**Comment by victornoel** [comment]
@jakevdp that's my point :) that's why this issue cannot be closed (except if the feature is refused of course). It would make sense that altair can pass this information, for example when using it in a notebook environment where one does not have control over vega-embed (if this is possible...).

**Comment by jakevdp** [comment]
It would be great to be able to do that; however, given the fact that the locale is not part of the chart spec, and given the constraints of how Jupyter and JupyterLab display charts, I don't see any viable route forward to allowing the user to control this property from the Python layer.

**Comment by jakevdp** [comment]
The best option would probably be to open a feature request in Vega/Vega-Lite to allow the locale to be set either via the chart spec or the vegaEmbed metadata, rather than requiring a Javascript API call.

**Comment by victornoel** [comment]
> the vegaEmbed metadata

@jakevdp the post above by @domoritz announce the release of a new version of vega-embed that accepts setting the local via its configuration and not an API call.

**Comment by jakevdp** [comment]
Oh, OK, then you should use those :smile:

**Comment by jakevdp** [comment]
This will require your frontend renderer to use Vega-Embed 6.1 or newer, if I'm reading the thread correctly; I believe that Jupyterlab and Jupyter Notebook frontend extensions are still on version 5.

**Comment by jakevdp** [comment]
For Jupyter Notebook, you could open a feature request in github.com/vega/ipyvega. For JupyterLab, you could open a feature request in github.com/jupyterlab/jupyterlab.

**Comment by victornoel** [comment]
@jakevdp sorry I'm new to altair so I may be missing something, but how do you pass those options to vega-embed? I thought altair was responsible of that, but from what you are telling, it's actually the notebook environments that takes care of instantiating vega-embed when altair generates a spec ?

**Comment by jakevdp** [comment]
You can use ``alt.renderers.set_embed_options`` to pass embed options to the renderer to pass to the vegaEmbed options.

But yes, the notebook frontend extensions are repsonsible for loading vegaEmbed and handling these options. Altair has no control over the frontend extension the user has loaded, or what it does with the chart specification.

**Comment by victornoel** [comment]
@jakevdp great, thanks for the clarification :)

**Comment by domoritz** [comment]
I’ll update the notebook renderer with the next major Vega-Lite Version release in the coming weeks.

**Comment by jakevdp** [comment]
Will there be any new 3.X series release, or is Vega-Lite 4.0 the next one?

**Comment by domoritz** [comment]
4 is the next one but it will be backwards compatible with v3.

**Comment by tzipperle** [comment]
> You can use `alt.renderers.set_embed_options` to pass embed options to the renderer to pass to the vegaEmbed options.
> 
> But yes, the notebook frontend extensions are repsonsible for loading vegaEmbed and handling these options. Altair has no control over the frontend extension the user has loaded, or what it does with the chart specification Altair produces.
> 
> This disconnect between backend and frontend is fundamental to the design that the Jupyter developers have chosen for libraries that do rich javascript-based display in the notebook.

Can you give me a concrete example to pass the local settings?

**Comment by jakevdp** [comment]
For time format locale, you can pass a dict object from https://github.com/d3/d3-time-format/tree/master/locale to the embed options. For example:
```python
from urllib import request
import json

# fetch & enable a German time locale.
with request.urlopen('https://raw.githubusercontent.com/d3/d3-time-format/master/locale/de-DE.json') as f:
  de_time_format = json.load(f)
alt.renderers.set_embed_options(timeFormatLocale=de_time_format)

# plot the chart
df = pd.DataFrame({
    'date': pd.date_range('2020-01-01', freq='D', periods=180),
    'value': np.random.randn(180).cumsum()
})

alt.Chart(df).mark_line().encode(
    x='date',
    y='value',
)
```
![visualization - 2020-04-03T135909 993](https://user-images.githubusercontent.com/781659/78404453-52626f80-75b3-11ea-8726-1a31a02a8ce5.png)

It might be worth adding some convenience functions to Altair and put some examples in the documentation.

**Comment by tzipperle** [comment]
@jakevdp Thank you!

**Comment by joelostblom** [comment]
Closing this issue as per https://github.com/altair-viz/altair/issues/505#issuecomment-554698978
