### ISSUE TITLE
legend moves in vconcat if one chart is wider than the other

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#515]
I have been trying to reproduce this example:
https://vega.github.io/vega-lite/examples/interactive_concat_layer.html
In that example you can see the bar chart is wide, and the plot for the heatmap stays close to its own chart.

But when reproducing it (without any of the interactive stuff yet as I am still researching that part) you can see I set the bar to width 600 and that pushes the legend of the plot above out to the right.  Is this intended behavior?

```python
"""
Interactive Dashboard with Cross Highlight
-----------------------
This example shows ...
"""

import altair as alt
from vega_datasets import data

source = data.movies()

point = alt.Chart(source).mark_point(color = '#666').encode(
    x = alt.X('IMDB_Rating:Q', bin= alt.BinParams(maxbins = 10)), 
    y = alt.Y('Rotten_Tomatoes_Rating:Q', bin = alt.BinParams(maxbins = 10), stack = None),
    size = alt.Size('count(IMDB_Rating):Q', legend = alt.Legend(title = 'In Selected Category')))
#point.transform = [{"filter": "datum.year == 2000"},
#                  {"calculate": "datum.sex == 2 ? 'Female' : 'Male'", "as": "gender"}]

rect = alt.Chart(source).mark_rect(color = '#666').encode(
    x = alt.X('IMDB_Rating:Q', bin= alt.BinParams(maxbins = 10)), 
    y = alt.Y('Rotten_Tomatoes_Rating:Q', bin = alt.BinParams(maxbins = 10), stack = None),
    color = alt.Color('count(IMDB_Rating):Q', legend = alt.Legend(title = 'All Movies'),
                     scale=alt.Scale(scheme='greenblue')
                     ))

#combine point and rect into a layered plot
top_plot = rect + point

bar = alt.Chart(source).mark_bar().encode(
    x = alt.X('Major_Genre:N', axis = alt.Axis(labelAngle = -40)),
    y = 'count(Major_Genre)',
#    color = alt.ConditionalSelectionValueDef(alt.ConditionalFieldDef(condition = {"selection": "pts", "value": "steelblue"}))
).properties(height = 150, width = 600)



alt.vconcat(top_plot, bar)
#vconcat if one blot goes to greater width, then the legend of the top one moves out
```

Here is the output:
![vega 18](https://user-images.githubusercontent.com/1798497/36690106-526635ae-1aff-11e8-8a5f-754707e941f2.png)

vs the output from vega-lite:
![image](https://user-images.githubusercontent.com/1798497/36690169-73173f64-1aff-11e8-84d6-4efbabdac0a7.png)

Not sure if this is an issue - or if I am abusing vconcat in a way it was not intended for this example.

**Comment by jakevdp** [comment]
The key there is the ``resolve`` argument, which tells the multi-pane plot how the legend should be handled.

Add this and it will work as expected:

```python
chart.resolve = {
    "legend": {
      "color": "independent",
      "size": "independent"
    }
  }
```

We need to add a better API for specifying top-level resolve, but that's coming :smile:

**Comment by afonit** [comment]
Thanks that did it.
