### ISSUE TITLE
many interactive examples are not working

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#538]
All of the recent interactive examples work fine, except for this one:
https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/interactive_cross_highlight.py

It displays, but when clicking around in the bar chart does not have the effect see when doing it in 'open in vega editor'.

**Comment by eitanlees** [comment]
The clicking is working for me. The only difference is that in the vega editor there is information when you hover over bars.

**Comment by afonit** [comment]
@eitanlees , humm, thanks for checking, I did a reinstall to get the latest items this morning.  I will try it to re-install again.

**Comment by afonit** [comment]
I reinstalled and still have the problem, but since @eitanlees says it is working for him, it must be a mistake in my own environment - so I will go ahead and close.

**Comment by afonit** [comment]
I am reopening as I have narrowed this down.
This is the only example that does not work (the interaction).
https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/interactive_cross_highlight.py

Testing this in my work environment -  it does not work on current Google Chrome on Windows 7.  It does work on Firefox on windows 7.

**Comment by jakevdp** [comment]
Does the version of the chart on this page work? https://vega.github.io/vega-lite/examples/interactive_concat_layer.html

**Comment by afonit** [comment]
Yes, it works fine on that page and when in the 'open with vega editor' link.

It is just within jupyter notebook on chrome on windows 7.

**Comment by afonit** [comment]
I am now going through and opening the other examples on the vega site.
This example:
https://github.com/altair-viz/altair/blob/e37000c8f54bc5e0e98ea8457b9a3c913cd58ccb/altair/vegalite/v2/examples/interval_selection.py
Also does not work in jupyter lab on chrome/firefox on windows 7.  

This particular example - you can drag a selection area and it adjusts the top plot - **however it does not allow you to drag that selection right and left** as it does when you view it on the vega site.

**Comment by jakevdp** [comment]
So this sounds like a Jupyterlab issue rather than an Altair issue.

Have you tried it with the console open, to see if there are any Javascript errors?

**Comment by afonit** [comment]
@jakevdp I agree 100% it is a jupyter lab issue.
I suppose I should open a ticket over there once they merge the rendering component into jupyter master?
I will continue to collect the little things I am noticing.
If that is the plan, I will close this issue.

**Comment by jakevdp** [comment]
ping @ellisonbg – should we report this on Jupyterlab?

**Comment by afonit** [comment]
As an aside - I just got home and tried this on my linux laptop with chrome and the jupyter notebook.  Everything works great.  
I will save the rest of the details depending on what ellisonbg says.

**Comment by afonit** [comment]
Closing since vega-lite team says it works on master.
https://github.com/vega/vega-lite/issues/3494

**Comment by afonit** [comment]
I mistakenly closed this in reference to another issue.
@ellisonbg do you have a preferred location where I should put the odd rendering issues on windows for the interactive examples?

**Comment by afonit** [comment]
I thought it might be helpful to upload some animated gifs to show the behavior.
**The interactive brush example**:
https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/interactive_brush.py
When you draw the rectangle you can only grab it if you select the left 50% of the rectangle, if you select the right 50% it disappears.  When you open the plot in vega-editor you can select anywhere in the drawn rectangle to drag it.
![interactive_brush](https://user-images.githubusercontent.com/1798497/37836553-18267334-2e89-11e8-92c0-547bd1d29540.gif)

**Interactive cross highlight**:
https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/interactive_cross_highlight.py
None of the bars in the bottom chart are selectable.

**Interactive layered crossfilter**:
https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/interactive_layered_crossfilter.py
Same as the first example, one can only grab by the left 50% of the selection.  However on the far right plot grabbing the selection does not work at all.
![layered_crossfilter](https://user-images.githubusercontent.com/1798497/37837127-cf51f0d2-2e8a-11e8-9ae1-faa59e71fe4f.gif)

**Interval Selection**:
https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/interval_selection.py
Grabbing anywhere on the selection does not work.
![interval_selection](https://user-images.githubusercontent.com/1798497/37837364-653a6908-2e8b-11e8-9fee-4bf7db09035e.gif)

**Comment by jakevdp** [comment]
Two questions:

- what browser are you using?
- can you reproduce this outside jupyterlab (e.g. by doing ``chart.savechart('chart.html')`` and then opening the resulting file)?

**Comment by afonit** [comment]
Browser: firefox and chrome
I am unable to reproduce outside of jupyterlab.  chart.savechart('chart.html) and opening the resulting file **works perfectly**.  All interaction works as expected.

Also, using the same browsers and jupyterlab on linux - and it all works great.  It is just on windows that something seems to be going off.

**Comment by jakevdp** [comment]
I'm entirely stumped.

**Comment by jakevdp** [comment]
Leave it open, it's clearly a bug, though it's something to do with JupyterLab and/or vega-lite.

**Comment by afonit** [comment]
Updating this as packages change and time goes on.

Just tried this on the brand new jupyter lab 0.32
The all the same issues still exist on windows.
Everything works fine on linux.

**Comment by afonit** [comment]
With altair 2 officially released I tried all the interactive examples I mentioned above - each of them now work as expected.
