### ISSUE TITLE
Using map/apply to modify axis

### ISSUE THREAD

**Issue by HalukaMB** [altair-viz/altair#539]
Hey everyone,

opening this issue as @domoritz suggested to handle this in a separate thread:

Say I have a dataframe like:
Index, X, Y
1, 2, 41
2, 4, 13
3, 6, 8
4, 7, 21

Now, I would plot X against Y but then I decide to rename the Y-axis, so that at the the ticks 
0->low
20->medium
40->high
is written.

Is there a workaround to do this, so a sort of remapping of values with still keeping the order?

**Comment by afonit** [comment]
@HalukaMB 
if I understand you correctly, you want to sort in a certain way.
See here:
https://github.com/altair-viz/altair/blob/da2ba5b014d7b6615b50a98e5120ee26c53a42a8/altair/vegalite/v2/examples/beckers_barley_trellis_plot.py

You can sort by a different column than what your axis is.

**Comment by afonit** [comment]
@HalukaMB ,
Are you asking about the renaming part or the sorting part?

If it is the sorting, lets say you created a new column with those labels.

You can sort by another column in your data.
Here is an example:
alt.Y('variety', sort=alt.SortField(field = 'yield', op = 'median', order = 'descending')
The axis labels come from 'variety' but is being sorted by another column of 'yield'.

https://github.com/altair-viz/altair/blob/da2ba5b014d7b6615b50a98e5120ee26c53a42a8/altair/vegalite/v2/examples/beckers_barley_trellis_plot.py

**Comment by HalukaMB** [comment]
@afonit Yes, that is exactly what I wanted!!! Thank you so much.

**Comment by afonit** [comment]
@HalukaMB great! glad to help.

**Comment by domoritz** [comment]
I'm glad you could resolve this. We are also working on a simpler way to specify custom sort orders in https://github.com/vega/vega-lite/issues/2915. For now, you might need to add an special field for sorting scale domains.
