### ISSUE TITLE
Two questions on plots, 

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#549]
I am trying to recreate a plot I use often in Bokeh, it looks like this:
![image](https://user-images.githubusercontent.com/1798497/36897512-d469fc06-1de4-11e8-94fa-625bfcd2535d.png)
The point of the plot is to show what the rates are (in the bars) but also to show how many weeks of data there are in each of the buckets(shown by the lines with circles at the end points).  So that if a rate looks off - one can easily tell that there is still x number of weeks in the period eg) still time to improve something.

Here is the current state:
```python
import altair as alt

data = {'actual_color': ['#58D68D', '#58D68D', '#F5B041',
        '#F5B041', '#D7DF01', '#D7DF01'],
        'location': ['ab14', 'ab14', 'ab14', 'ab14', 'ab14', 'ab14'],
        'm_color': [0, 0, 1, 1, 2, 2],
        'm_sorting': [0, 1, 2, 3, 4, 5],
        'period': ['3_weeks_prior', '3_weeks_post', '6_weeks_prior',
        '6_weeks_post', '9_weeks_prior', '9_weeks_post'],
        'period_after': ['3_weeks_post', '', '6_weeks_post',
        '', '9_weeks_post', ''],
        'size_after': [3, '', 6, '', 6, '' ],
        'rate': [0.051948, 0.012821, 0.01633, 0.090129, 0.100279, 0.016212],
        'size': [3, 3, 6, 6, 9, 6]
       }

source = alt.pd.DataFrame.from_dict(data)

bar = alt.Chart(source).mark_bar().encode(
    x = alt.X('period', sort = alt.SortField(field='m_sorting',
                                             op='sum',
                                             order='ascending'),
             axis = alt.Axis(labelAngle=-45)),
    y = alt.Y('rate', axis = alt.Axis(format='%')),
    color = alt.Color('actual_color', legend=None)
    )

rule = alt.Chart(source).mark_rule(color='black').encode(
    x = alt.X('period', sort = alt.SortField(field='m_sorting',
                                             op='sum',
                                             order='ascending'),
             axis = alt.Axis(labelAngle=-45, grid=False)),
    x2 = alt.X2('period_after'),
    y = alt.Y('size', axis=alt.Axis(title='# Months in data', grid=False)),
    y2 = alt.Y2('size_after')
)#.transform_filter("datum.size_after !== Null")

point = rule.mark_point(color='black').encode(
    size=alt.SizeValue(207)
)

chart = bar + rule + point
chart.resolve = {'scale': {'y': 'independent'}}

chart
```

There are two issues currently.

**1st issue**, you can see the x-axis is not obeying the sort. 
If one comments out:
chart.resolve = {'scale': {'y': 'independent'}}
an just show bar or point on their own - the axis is properly sorted eg) all priors appear before their respective posts.

But When putting them together the posts are all before their respective priors.

There is something that I am not understanding of how to combine these properly.

**2nd issue**, I am trying to draw line segments that are separate.  I thought I could filter out the null rows for the rule mark with:
.transform_filter("datum.size_after !== Null")

I have tried some other things that are probably not worth mentioning - so I am seeing if there are any ideas anyone else has.

**Comment by jakevdp** [comment]
I'm not certain about the 1st question (the resolve mechanism is still a bit mysterious for me) but maybe @kanitw or @domoritz can weight-in.

On the second issue, I'd use a line with detail instead:

```
rule = alt.Chart(source).mark_line(color='black').encode(
    x='period',
    y='size',
    detail='m_color'
)
```

**Comment by afonit** [comment]
ah, the line has a detail parameter, I now see that in the vega-lite documentation.  Thank you for pointing that out.

**Comment by afonit** [comment]
Closing as it is a vega-lite issue and they are aware of the problem.
https://github.com/vega/vega-lite/issues/2177
