### ISSUE TITLE
Refactor savechart()

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#557]
Currently, the core logic of ``savechart()`` is defined in ``altair/vegalite/v2/api`` (#556). This should be refactored to a more general utility that can be used by all versions of vega & vegalite wrappers

**Comment by palewire** [comment]
I have another pedantic question. So thank you again in advance for your patience. Why not call this method something more concise like `.save()`?

**Comment by jakevdp** [comment]
Seems fine. I'd be open to renaming & deprecating savechart.
