### ISSUE TITLE
Extending domain of time-based x-axis

### ISSUE THREAD

**Issue by HalukaMB** [altair-viz/altair#558]
Sorry for keep asking questions, but...

I have still been playing around with the stripplot and I am running this code currently:

```
alt.Chart(stripplot,
          width=200,height=300,
    description='Shows the frequency of terror attacks between two countries.',
    config=alt.Config(
        legend=alt.LegendConfig(orient="bottom-left")
                     )
).mark_tick(tickThickness=1.5, font="arial").encode(
    
    x=alt.X('Qdate:T',axis=alt.Axis(format='%m/%Y',title='', labelAngle=0, axisWidth=0,ticks=4, orient="top",
                                   )),
    color=alt.Color('mostrecent:N',
            legend=alt.Legend(
                title='Tote',
            ),
            scale=alt.Scale(
                domain=['Aktuelle Attacke', 'Vorherige Attacken'],
                range=['black', '#e23b3c'],
            ),
            
        ),).configure_scale(bandSize=100)
```

Which produces this output:

![vega 9](https://user-images.githubusercontent.com/18502037/37109206-8de6361a-2239-11e8-8929-2ff879c9be1d.png)

The reason for putting the legend down there is that I want to be able to also display the graphic on mobile. Now, I was wondering how to...
-shorten the grey lines for the ticks
-AND, more importantly: how to set a domain for datetime-values. I would like the whole x-axis start a bit before the first object and end a bit after the last object that is parsed in. However, even just reading in the first and the last element from a pandas dataframe that is sorted by date with something like:

paddedlate=(stripplot["date"].iloc[0])
paddedearly=(stripplot["date"].iloc[-1])

and passing these two dates into altair's domain params results in a failure because the given values are timestamps. Hence, I was wondering, how to customize the x-axis in a way that is described here 
https://altair-viz.github.io/documentation/config.html#adjusting-axis-limits
but just with 
a) a non-hardcoded way
and
b) a time-axis on x.

Again my sincere apologies for all these questions, but I am still relatively new to graphics viz.

**Comment by afonit** [comment]
@HalukaMB , do you have a means of posting the data to ease reproduction?

**Comment by eitanlees** [comment]
If all you want is padding you should be able to pass the `padding` keyword to x encoding scale. 

`x=alt.X('Qdate:T', scale=alt.Scale(padding=20))`

**Comment by jakevdp** [comment]
I recall this coming up in another issue... the date parsing only happens in the encoding channel, and if you want to change the scales I believe you have to pass integer seconds-since-epoch-zero type values, but I don't remember the details.

**Comment by HalukaMB** [comment]
Sorry for the late response, left the csv at work. Link to the dataset is here @afonit : [https://drive.google.com/file/d/1vn9JmMFsZ_YGmpO-CbqZlQbTJoOyohyZ/view?usp=sharing](url) 
@eitanlees suggested padding does not do the job unfortunately.

**Comment by eitanlees** [comment]
Not exactly sure what you are looking for but here is what I have to offer 
```
import altair as alt
import pandas as pd

df = pd.DataFrame({'Qdate': {0: '2018-03-01',
  1: '2018-01-15',
  2: '2017-09-14',
  3: '2017-05-20',
  4: '2017-05-09',
  5: '2017-04-05'},
 'deaths': {0: 12.0, 1: 38.0, 2: 84.0, 3: 35.0, 4: 47.0, 5: 35.0},
 'location': {0: 'Bagdad, Iraq',
  1: 'Baghdad, Iraq',
  2: 'Nasiriyah, Iraq',
  3: 'Baghdad, Iraq',
  4: 'Hawija, Iraq',
  5: 'Tikrit, Iraq'},
 'mostrecent': {0: 'Aktuelle Attacke',
  1: 'Vorherige Attacken',
  2: 'Vorherige Attacken',
  3: 'Vorherige Attacken',
  4: 'Vorherige Attacken',
  5: 'Vorherige Attacken'}})

chart = alt.Chart(df).mark_tick().encode(
    x = alt.X('Qdate:T', scale=alt.Scale(padding=20),
              axis=alt.Axis(format='%m/%Y',title='', orient='top', tickCount=3)),
    color= alt.Color('mostrecent:N', 
                     legend=alt.Legend(title='Tote', 
                                       orient="bottom-left",
                                       offset=-40),
                     scale=alt.Scale(
                                domain=['Aktuelle Attacke', 'Vorherige Attacken'],
                                range=['black', '#e23b3c']
                                    )
                    )
).properties(
    width=200, 
    height = 300
).configure_tick(thickness=1.5, bandSize=100)

chart
```

![visualization](https://user-images.githubusercontent.com/2041969/37157191-1a48f5d0-22b6-11e8-9384-2e7835202362.png)


I am working with `alt.__version__`  '2.0.0dev' so that is why there might be why there are some differences.

**Comment by HalukaMB** [comment]
How do I get the dev-version via pip?

**Comment by afonit** [comment]
@HalukaMB I have been doing:
pip installl git+https://github.com/altair-viz/altair/

**Comment by HalukaMB** [comment]
And what do I need to do to see the vis in Jupyter Notebook? I already installed and enable ipyvega...https://github.com/vega/ipyvega

**Comment by afonit** [comment]
@HalukaMB you need to use jupyter lab to view them.
Here is a great write up Jake did to get people into a state where they can use it.:
https://github.com/altair-viz/altair/wiki/Display-Troubleshooting

**Comment by joelostblom** [comment]
@HalukaMB I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
