### ISSUE TITLE
how to find the version of vega-lite being used in the dev version of Altair

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#563]
@jakevdp , where can I look to see the version of vega-lite being used by altiar dev?
I found a bug https://github.com/vega/vega-lite/issues/3494 and they are wanting to know the version altair is using.

Is the below generated by altair - or is this the schema I should point them to?
https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/vega-lite-schema.json
 "$schema": "http://json-schema.org/draft-04/schema#"

**Comment by jakevdp** [comment]
Yes, that's the schema file we're using at the moment: https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/vega-lite-schema.json

The "draft04" thing is not relevant to vega-lite's version, though.

Unfortunately, the vega-lite version is not recorded in the schema, and I'm not certain what precise version of the schema @ellisonbg used when he added that file.

In the past I've mentioned to the vega-lite team that it would be useful to record the schema version within the schema file, but they haven't seen the need to do that yet. Maybe they will now :smile:

**Comment by jakevdp** [comment]
Before the v2.0 refactor, we had the build script download the schema and record the exact vega-lite version within the generated code. It would be useful to do that again.

**Comment by jakevdp** [comment]
Oh, I should add that the relevant thing is probably what version is used by the *renderer*, not by the code generation.

Altair has no control over that. So I think we'd need to figure out what version is used by the jupyterlab vega-lite plugin, and I don't have any clue how to approach that. @ellisonbg would probably know.

**Comment by domoritz** [comment]
Yeah, the schema is only relevant for the code you generate. The version of the renderer is often more relevant to find bugs. However, it really depends on the renderer so I think you can close the issue here.
