### ISSUE TITLE
Inconsistency in setting titles for channels

### ISSUE THREAD

**Issue by malramsay64** [altair-viz/altair#585]
I completely realise this is most a result of the vega-lite specfication, but I feel I should note that it is difficult to work out how to set the titles of the various channels in the altair 2.0 branch. 

Take the completely contrived example below

```
import altair as alt

cars = alt.load_dataset('cars')

chart = alt.Chart(cars).mark_bar().encode(
    x=alt.X('Horsepower', axis=alt.Axis(title='🐎⚡️'), bin=alt.Bin(maxbins=15)),
    y=alt.Y('count(*):Q', axis=alt.Axis(title='# Cars')),
    row=alt.Row('Origin', header=alt.Header(title='Country of Origin')),
    column=alt.Column('Acceleration', header=alt.Header(title='Acceleration'), bin=alt.Bin(maxbins=3)),
    color=alt.Color('Cylinders', legend=alt.Legend(title='# Cylinders')),
    size=alt.Size('Miles_per_Gallon', legend=alt.Legend(title='MPG'))
)
```
- `X` and `Y`, the title is set through `Axis`,
- `Row` and `Column`, the title is set through `Header`, and
- `Color`, `Size`, the title is set through `Legend`.

I believe there was a `title` keyword argument in altair 1.3 for each channel.

**Comment by jakevdp** [comment]
Yes, you're correct – I hadn't noticed that change yet. I'm not sure there's much we can do about it, given that this change was made in Vega-Lite.

**Comment by kanitw** [comment]
That's a valid point. I'm creating https://github.com/vega/vega-lite/issues/3548 so we can discuss more about it.

**Comment by jakevdp** [comment]
Fixed in Altair 3
