### ISSUE TITLE
Integration with geopandas geometries

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#588]
`geopandas` is a package that reads many type of geometric datasets, including geojson, topojson and shapefiles (albeit through `fiona`) and parses it into a `pandas` dataframe, where the `geometry` is parsed as a separate column. 

It would be great if this is `geometry` type is recognized in Altair to make a map easily.

Problems might arise with projections as Vega doesn’t support all EPSG projections, but EPSG:4326 equals to Mercator and that is supported.

**Comment by jakevdp** [comment]
That's a really interesting idea... I've not done much work with geopandas, so I'm not certain what it would take.

**Comment by kovasb** [comment]
Also interested in this.

**Comment by bnaul** [comment]
Would this be as simple as wrapping `GeoDataframe.to_json()` and passing the GeoJSON along to whatever handles it? I couldn't actually find an `altair` example that plots features from GeoJSON, is it handled natively by VegaLite?

**Comment by Chekos** [comment]
from vega-lite's [website](https://vega.github.io/vega-lite/docs/data.html)
it seems like Vega-Lite uses GeoJSON only (can take a TopoJSON object but will convert it into GeoJSON). 

I think integration with GeoPandas would be a great addition to `Altair`. `GeoPandas` can read (through `fiona`) a lot of different geo files and write them as GeoJSON which `altair` can then use for the illustration. I think a simple wrapper of the `geometry` series in the geodataframe to convert it to json would work. (i.e. `gdf.to_file('example.geojson', driver = 'GeoJSON')`)

**Comment by mattijn** [comment]
Got it working :)
```
import altair as alt
import geopandas as gpd
import pandas as pd
import json
%matplotlib inline
```

##### Load two datasets


```python
counties = r'/Users/mattijnvanhoek/Desktop/us-10m.json'
unemp_data = r'/Users/mattijnvanhoek/Desktop/unemployment.tsv'
```


```python
df = pd.read_csv(unemp_data, sep='\t')
gdf = gpd.read_file(counties, driver='TopoJSON')
gdf.id = gdf.id.astype(int)
```

##### Apply inner-join on GeoDataFrame and DataFrame (`gdf` should be on 'left' side and `df` on the right to maintain `geometry` properties in the resulting joined GeoDataFrame)


```python
gdf_merged = gdf.merge(df, left_on='id', right_on='id', how='inner')
```

##### Plot the GeoDataFrame using `matplotlib` and print the `head()`. The `rate` column is joined to the DataFrame.


```python
gdf_merged.plot()
```




    <matplotlib.axes._subplots.AxesSubplot at 0x119e79128>



![output_7_1](https://user-images.githubusercontent.com/5186265/38706367-282b1210-3ead-11e8-9d52-5b46b04086c8.png)




```python
gdf_merged.head()
```




<div>
<table border="1" class="dataframe">
  <thead>
    <tr style="text-align: right;">
      <th></th>
      <th>geometry</th>
      <th>id</th>
      <th>rate</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>()</td>
      <td>22051</td>
      <td>.065</td>
    </tr>
    <tr>
      <th>1</th>
      <td>(POLYGON ((-90.1077214366575 30.19168413151698...</td>
      <td>22051</td>
      <td>.065</td>
    </tr>
    <tr>
      <th>2</th>
      <td>(POLYGON ((-120.8536146368232 49.0001146177235...</td>
      <td>53073</td>
      <td>.078</td>
    </tr>
    <tr>
      <th>3</th>
      <td>POLYGON ((-106.1123837970986 48.99904031068445...</td>
      <td>30105</td>
      <td>.046</td>
    </tr>
    <tr>
      <th>4</th>
      <td>POLYGON ((-114.0698488011574 48.99904031068445...</td>
      <td>30029</td>
      <td>.088</td>
    </tr>
  </tbody>
</table>
</div>



##### Prepare GeoDataFrame for Altair


```python
# dump as json
json_gdf = gdf_merged.to_json()
# load json to select variable `features` and dump as json
json_features = json.dumps(json.loads(json_gdf)['features'])
```

##### Make the Choropleth Map


```python
# parse json to `alt.Data`
data_geo = alt.Data(values=json_features)

# plot map, where variables ares nested within `properties`, 
alt.Chart(data_geo).mark_geoshape(
    fill='lightgray',
    stroke='white'
).properties(
    projection={'type': 'albersUsa'},
    width=700,
    height=400
).encode(
    color='properties.rate:Q')
```

![choropleth](https://user-images.githubusercontent.com/5186265/38706434-5f30262e-3ead-11e8-9434-cf97b0157f32.png)


👍

**Comment by pagpires** [comment]
1. Thanks a lot! The discussion here is super helpful, esp. the use of `alt.Data()`.  However, I cannot get what's shown here working, can you show me what does your us-10m.json structure look like (I notice you directly assign it to `counties` so I guess the json file is different from the one from example?)  

2. Here is a more-altair, less-pandas way to make the same plot (basically use `alt.Data()` to wrap your local file, and use `transform_lookup` rather than `merge`)

```python
# download file and read into variables
us_10m = vega_datasets.data.us_10m()
unemp_data = vega_datasets.data.unemployment() 

# the original unemp_data has two columns merged, need to split them
unemp_data['id'], unemp_data['rate'] = unemp_data['id\trate'].str.split('\t', 1).str

# key: convert whatever variables to altair-recognizable format by using alt.Data()
# note we need to specify the format and feed it with alt.SomeKindDataFormat()
# we need to specify feature or mesh to extract TopoJSON, the type can only be 'topojson'
counties = alt.Data(
    values=us_10m, 
    format=alt.TopoDataFormat(feature='counties',type='topojson')
)

# plot by lookup 
# same as the example in (https://altair-viz.github.io/user_guide/transform.html#lookup-transform
alt.Chart(counties).mark_geoshape().encode(
    color='rate:Q'
).properties(
    projection={'type': 'albersUsa'},
    width=500, height=300
).transform_lookup(
    lookup='id',
    from_=alt.LookupData(unemp_data, 'id', ['rate'])
)
```

3. Personally I guess `pd.merge` is a better way than `transform_lookup()`, since `pd.merge` separates data processing from the visualization step...

4. I guess it would be great if we have some more examples to show how to plot local, non-pandas type of data (for now I can only think of geo-related data)? Personally I think Altair is really good for exploratory analysis, which will most likely handle private/local data...

**Comment by jakevdp** [comment]
Would it make sense to build some of that data preparation into vega_datasets?

**Comment by mattijn** [comment]
Yes, if the result is a `GeoDataFrame` it would be much cleaner (and people won't run away yet)

**Comment by iliatimofeev** [comment]
I think it's little bit simpler
```python
import altair as alt
import pandas as pd
import geopandas as gpd

alt.renderers.enable('notebook')


world = gpd.read_file(gpd.datasets.get_path('naturalearth_lowres'))
world  = world[world.continent!='Antarctica'] # do not display Antarctica

data  = alt.InlineData(values = world.to_json(), #geopandas to geojson string
                       # root object type is "FeatureCollection" but we need its features
                       format = alt.DataFormat(property='features',type='json')) 
alt.Chart(data).mark_geoshape(
).encode( 
    color='properties.pop_est:Q', # DataFrame fields are accessible through a "properties" object 
    tooltip='properties.name:N'
).properties( 
    projection={"type":'mercator'},
    width=500,
    height=300
)
```
![visualization 1](https://user-images.githubusercontent.com/11561581/39604023-2bc4e8ec-4f33-11e8-9659-60d5f932f5b9.png)

But it will crush if we add Timestamp type field to DataFrame. %(

In general case will be great to support any object with [__geo_interface__](https://gist.github.com/sgillies/2217756)  that is widely supported by python GIS libraries. I suggest to have a special class for this case something like: ``data = alt.GeoData(world)``.  I could make a PR, if it is needed.

**Comment by jakevdp** [comment]
> I suggest to have a special class for this case something like: data = alt.GeoData(world). I could make a PR, if it is needed.

That would be great!

**Comment by iliatimofeev** [comment]
To avoid static dependencies between Altair and GeoPandas I have published `gpdvega` as a connector.
See details in documentation https://iliatimofeev.github.io/gpdvega/

**Comment by JoeGermuska** [comment]
For what it's worth, I installed `gpdvega` and tried this with my own data, and found that it works well and as expected.  

My taste would be for tighter integration rather than yet-another-library, but I recognize that I'm not trying to maintain a rapidly evolving library in a rapidly evolving ecosystem.  If it won't be integrated, at least a reference in the altair docs would be great.

**Comment by jakevdp** [comment]
I agree – sorry this has been so slow, but getting it more tightly integrated depends on a redesign of the data_transformer architecture that hasn't happened yet.

**Comment by JoeGermuska** [comment]
sure, i totally understand... just wanted to verify that it's solid

**Comment by kannes** [comment]
> In general case will be great to support any object with geo_interface that is widely supported by python GIS libraries.

I would like to give a +1 to that. While it surely is a good idea to use geopandas if you are into pandas-like analysis, it is a big dependency. Supporting geo interface would allow users to stay with light-weight things like Fiona and Shapely for the geo analyses.

**Comment by jakevdp** [comment]
To be honest, I don't know much about geographic data and the libraries that support them. This is not going to be solved until someone with more expertise digs in and figures out a good approach.

**Comment by mattijn** [comment]
Isn't this stalled because of https://github.com/altair-viz/altair/pull/887?

**Comment by jakevdp** [comment]
No, that has to do with supporting geopandas as a data transformer. I'm not totally convinced that's the best route (for example, it would be pretty confusing if your geo charts stopped working when you enabled ``data_server``)

I think it would be better to support geo data (be it geopandas, shapely, fiona, etc.) natively as part of the Altair API, but I'm not familiar enough with geo viz libraries to have good ideas on how to do that.

**Comment by mattijn** [comment]
This issue is fixed by https://github.com/altair-viz/altair/pull/1664 🌍!

**Comment by Murtz5253** [comment]
Does anyone know why this does not work with states? When the us10m file is read in with geopandas, why do the state ids not copy over?

**Comment by mattijn** [comment]
It works for me (`geopandas=0.7.0`):

```python
import geopandas as gpd
import altair as alt

gdf = gpd.read_file(
    'https://raw.githubusercontent.com/vega/vega/master/docs/data/us-10m.json', 
    driver='TopoJSON'
)
alt.Chart(gdf).mark_geoshape().encode(color='id:Q').project('albersUsa')
```
<img width="471" alt="image" src="https://user-images.githubusercontent.com/5186265/83630401-0b393080-a59c-11ea-89d2-633526379b95.png">
