### ISSUE TITLE
Collision of vega lite properties with python keywords

### ISSUE THREAD

**Issue by malramsay64** [altair-viz/altair#595]
In #586 I was wrong that there were no additional collisions of concern, I found another in `AggregatedFieldDef`. 

There is also possibly an issue with `as` in transform_lookup [vega-lite docs](https://vega.github.io/vega-lite/docs/lookup.html#lookup-transform)

I am checking for collisions using the shell command below.

```
$ python -c "import keyword; print('\n'.join(keyword.kwlist))" | xargs -I{} grep '"{}":' -B 3 altair/vegalite/v2/schema/vega-lite-schema.json
```

**Comment by jakevdp** [comment]
Yep, this was a known problem. Initially I had done some mapping in the schema to automatically transform reserved keywords, but that proved a bit too heavyweight and brittle. In the end I decided that since schemas are basically dicts, people could define them via the dict interface in the few cases that it comes up. And in the common ones (like ``transform_*``) we'd provide methods that take modified forms of the arguments.

**Comment by jakevdp** [comment]
See also #598 – I modified the code generation so that these invalid identifiers are listed in the docstrings, so they're more visible to the user.

**Comment by malramsay64** [comment]
I think the change in #598 is the appropriate solution to this issue. It is not like `as_='foo'` is a perfect solution and having the dict only arguments makes the code simpler.

As for  `AggregatedFieldDef`, in most cases  `transform_*` (and I believe all the examples) the `as_` is used as a positional rather than keyword argument, so I think drawing the line at `transform_*` is reasonable.

**Comment by ogencoglu** [comment]
I am getting an error for usage of `as` in `transform_regression` to go around the reserved keyword issue. altair version 4.2.0.

```
.transform_regression(
    'Horsepower', 'Miles_per_Gallon', method='linear', **{'as': 'OutputName'}
)
```

`TypeError: transform_regression() got an unexpected keyword argument 'as'
`

Any help would be appreciated.

**Comment by mattijn** [comment]
Please not double posting @ogencoglu, same comment raised in #850.
