### ISSUE TITLE
UnicodeDecodeError when importing

### ISSUE THREAD

**Issue by ajasja** [altair-viz/altair#600]
Hi!

When I import Altair I get a 

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x88 in position 200925: character maps to <undefined>
```
![image](https://user-images.githubusercontent.com/19926/37560509-e657089e-2a39-11e8-81fe-e8b77e0fe5be.png)

I'm using a ipykernel on python 3 from a jupyterlab that's installed in python 2. I'm guessing that I did the installation incorrectly? I activated the correct py3 conda environment and did a `pip install altair==2.0.0rc1`. Pip freeze shows that altair has been installed. 

Python version: 3.6.4 (running a 32bit build on win7 64 bit)
`Python 3.6.4 |Anaconda, Inc.| (default, Mar 12 2018, 20:25:16) [MSC v.1900 32 bit (Intel)] on win32`

[pip freeze](https://pastebin.com/gkbxWEDt)

Example notebook: [Altair-TEST.zip](https://github.com/altair-viz/altair/files/1822149/Altair-TEST.zip)

**Comment by ajasja** [comment]
Same error using jupyter lab from python 3. Actually I get the same error even if I import altair in Ipython or form the command line. 

I think the problem is in my codepage (cp1200), although I have no idea why.
[Backtrace here](https://pastebin.com/UQpvNpp2) (was also present in the notebook). 

The error comes from the file
c:\Programs\Python\Anaconda\envs\py3\lib\encodings\cp1250.py

**Comment by jakevdp** [comment]
Ah, it looks like we need to explicitly specify UTF-8 when loading the schema file (see [this SO question](https://stackoverflow.com/questions/9233027/unicodedecodeerror-charmap-codec-cant-decode-byte-x-in-position-y-character)) UTF-8 is the default in Linux and Mac, but as usual, Windows tries to be special :smile:

I don't have access to a windows machine, so I'm not able to debug this. If you'd like to try, that would be great!

**Comment by ajasja** [comment]
Sure, seems easy enough:) I'll get a PR together, although I don't have a good idea about unit tests for this.

**Comment by ajasja** [comment]
@jakevdp It seems it really was as a one-line fix https://github.com/altair-viz/altair/pull/637 :)

**Comment by jakevdp** [comment]
I think this error was fixed by the pull requests linked here, which have been merged into master. Can you try installing from master and see if it fixes the issue?

**Comment by desilinguist** [comment]
Yes, it does. Thanks! 👍

**Comment by jakevdp** [comment]
Great!

**Comment by ajasja** [comment]
Aha, so windows was not the only exception:)
