### ISSUE TITLE
VegaLite2 chart not showing

### ISSUE THREAD

**Issue by uniele** [altair-viz/altair#601]
The returned value is just VegaLite2 Object as shown below.
![image](https://user-images.githubusercontent.com/13804769/37563858-3720a0a8-2acd-11e8-9e3e-db0f7da01a98.png)

**Comment by jakevdp** [comment]
If you are using the Jupyter notebook (not JupyterLab) you'll need to run ``alt.renderers.enable('notebook')`` in order for the plot to display.

More details at https://altair-viz.github.io/getting_started/installation.html and https://altair-viz.github.io/user_guide/display.html#jupyter-notebook

Please let me know if that fixes the issue for you

**Comment by uniele** [comment]
@jakevdp Thank you very much.

Result turned out to be like this.
![image](https://user-images.githubusercontent.com/13804769/37565394-03c2b56a-2aec-11e8-9d8e-02ba07223d44.png)

**Comment by jakevdp** [comment]
You need to install and activate the ``vega3`` package to use the notebook renderer. Instructions are at https://altair-viz.github.io/user_guide/display.html#jupyter-notebook

**Comment by jakevdp** [comment]
Once you've installed and activated vega3, make sure to restart your jupyter notebook, then things should work.

**Comment by uniele** [comment]
@jakevdp 

Thank you very much sir. Worked out like a charm.
![image](https://user-images.githubusercontent.com/13804769/37565555-a1ca7d9a-2aee-11e8-8090-5016c994390a.png)

**Comment by jakevdp** [comment]
Yes, this is a known issue in the ipyvega/vega3 package: https://github.com/vega/ipyvega/issues/75

We'll try to get that fixed soon.

In the meantime, you might try using JupyterLab: things are much more streamlined there.

**Comment by uniele** [comment]
![image](https://user-images.githubusercontent.com/13804769/38009528-af8bcada-328f-11e8-9cef-e74491b5f54f.png)

It's like me, literally, right there.
I feel bad and very sorry for the troubling sir.

**Comment by jakevdp** [comment]
Oh, it's really no trouble! I hope that tweet doesn't come across as accusatory in any way... it's just me making sense of all the user bug reports I've seen lately and figuring out how to make the docs as useful as possible.

If you have any thoughts on how docs could be improved, I'd appreciate hearing them.

**Comment by tweakimp** [comment]
Maybe you could link the docs in the error messages of the known bugs

**Comment by jakevdp** [comment]
We do now in the case of this issue.
