### ISSUE TITLE
Is altair python 3 only?

### ISSUE THREAD

**Issue by fredthedead** [altair-viz/altair#605]
I'm getting the following error after a clean install of the new release candidate from pip:

```
  File "/Users/me/anaconda/lib/python2.7/site-packages/altair/utils/plugin_registry.py", line 27
    def __init__(self, entry_point_group: str = '', plugin_type=object) -> None:
                                        ^
SyntaxError: invalid syntax
```

the documentation doesn't mention anything about not supporting 2.7 from what I could see

**Comment by jakevdp** [comment]
Yes, Altair is Python 3 only, as mentioned at the top of the installation page: https://altair-viz.github.io/getting_started/installation.html

**Comment by jakevdp** [comment]
There are two main barriers to making it Python 2 compatible:

1) the type annotation syntax
2) the fact that the documentation within the vega & vega-lite schemas are encoded in unicode, and thus the Python code generated from them is full of unicode. We'd need the code generation process to sanitize all those string, replacing unicode characters with their approximate ASCII equivalent.

It's just not been a priority for the development team, given that Python 2 is going to be dead very soon.

**Comment by fredthedead** [comment]
Thank you for the detailed reply, guess it's time to switch
