### ISSUE TITLE
Altair plots not showing in JupyterLab HTML notebook exports.

### ISSUE THREAD

**Issue by climbercarmich** [altair-viz/altair#606]
The altair 2 plots are working very well in the JupyterLab notebook but when I export the notebook as a HTML document the altair plots show as the following in the .html file:

**<VegaLite 2 object>**

Is this a known issue with Altair 2?

**Comment by jakevdp** [comment]
Yes, I think that in general the mimetype output handling (which is how Altair plots get rendered) is not reflected in HTML conversions at the moment. @ellisonbg may be able to give more information on that.

**Comment by jakevdp** [comment]
Here's the relevant nbconvert issue: https://github.com/jupyter/nbconvert/issues/755

**Comment by jakevdp** [comment]
related: #624
