### ISSUE TITLE
Dependency JupyterLab 0.32 not yet available?

### ISSUE THREAD

**Issue by lzamparo** [altair-viz/altair#610]
The [install docs](https://altair-viz.github.io/getting_started/installation.html) suggests that Altair 2.0 works most seamlessly with Jupyterlab version >= 0.32,

`For JupyterLab version 0.32 or newer, nothing else needs to be done to use the main Altair API`

but this version doesn't seem [to exist yet](https://github.com/jupyterlab/jupyterlab/milestone/11).  I guess this issue will gradually fade away, but neither my `default` nor `conda-forge` channels have versions > 0.31.x.  Am I not searching in the right place?

Thanks,

**Comment by lzamparo** [comment]
In particular, this is an issue for me since I get a downstream error post installation of jupyterlab:

```
Package plan for installation in environment /Users/zamparol/anaconda/envs/py3:

The following NEW packages will be INSTALLED:

    jupyterlab:          0.31.12-py35_1 conda-forge
    jupyterlab_launcher: 0.10.5-py35_0  conda-forge

Proceed ([y]/n)? y
Invalid choice: y
Proceed ([y]/n)? y

jupyterlab_lau 100% |##############################################################################################| Time: 0:00:00   3.75 MB/s
jupyterlab-0.3 100% |##############################################################################################| Time: 0:00:01   8.56 MB/s
(py3) mski1743:CD8_effector zamparol$ jupyter labextension install @jupyterlab/vega3-extension

Errored, use --debug for full output:
ValueError: Please install nodejs 5+ and npm before continuing. nodejs may be installed using conda or directly from the nodejs website.
```
Will continue shaving this late afternoon yak, but it would be nice to have a `warning` on the install page informing ppl this might occur.

**Comment by jakevdp** [comment]
Yes, I think you're correct that Jupyterlab 0.32 is not yet available via pip or conda.

If you'd like to use JupyterLab 0.32, please install [from source](https://github.com/jupyterlab/jupyterlab)
