### ISSUE TITLE
Passing in a list of columns to single encoding

### ISSUE THREAD

**Issue by stsievert** [altair-viz/altair#613]
I have often have a case where I return many data from a function:

``` python
def f(x):
    return {'x**1': x**1, 'x**2': x**2, 'x**3': x**3, 'x': x}

data = [f(x) for x in np.linspace(0, 1)]
print(data[25])
# {'x**1': 0.5102, 'x**2': 0.2603, 'x**3': 0.1328, 'x': 0.5102}
```

However, visualizing this data requires that I reformat my data:

``` python
def show(data):
    columns = set(data[0].keys()) - set(['x'])
    new_data = []
    for row in data:
        new_data += [{'x': row['x'], 'f(x)': row[column], 'function': column}
                     for column in columns]
    return new_data

data = show(data)
df = pd.DataFrame(data)
print(data[25])
# {'x': 0.1632, 'f(x)': 0.1632, 'function': 'x**1'}
```

Then, I can visualize my data:

``` python
import altair as alt
alt.Chart(df).mark_line().encode(
    x='x',
    y='f(x)',
    color='function'
)
```

which produces this plot:

<img width="600" alt="screen shot 2018-03-19 at 9 43 10 pm" src="https://user-images.githubusercontent.com/1320475/37632981-7883aae2-2be8-11e8-9635-6fb94defcc14.png">

Is there any way to avoid this data reformatting? I ran into #611 when this issue popped up. Yes, I can always write the function to format my data but that function is hard to read when written generally.

**Comment by stsievert** [comment]
I know Altair is meant to provide a grammar of graphics, but this is a use case I often run into. I see three solutions to this problem:

1. Keep the code as is.
2. Use `transform_lookup` and `alt.data_transformers.enable`.

An idea I had to solve this problem is

``` python
Chart(df).mark_line().encode(
    x='x',
    y=['x**1', 'x**2', 'x**3'],
    color=alt.encoding('y', title='function')
)
```

where `alt.encoding` would be implemented to grab the list passed to `y` and reformat the dataframe behind the scenes. This would mirror the pandas API, which allows `df.plot(x='x', y=['x**1', 'x**2', 'x**3'])`.

Would this be reasonable?

**Comment by jakevdp** [comment]
See #615 for the docs update that addresses this.

**Comment by stsievert** [comment]
Perfect! Thanks for the docs, and I'd rather have external tools anyways.
