### ISSUE TITLE
Should mark_bar automatically shrink the extent to the data values?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#619]
Here's my example. Five "years" of fake data. This is the kind of chart we make in the news business all the time. 

```python
import altair as alt
import pandas as pd
df1 = pd.DataFrame([
        [1990, 1000],
        [1991, 2000],
        [1993, 3000],
        [1994, 4000],
        [1995, 5000],
    ],
    columns=["year", "value"]
)
alt.Chart(df1).mark_bar().encode(
    x="year",
    y="value"
)
```

Here's the chart that's currently returned by altair.

![visualization 2](https://user-images.githubusercontent.com/9993/37690211-c90bc002-2c66-11e8-946e-695f77434a79.png)

As you can see, the x extent has zero as its minimum. You might have some philosophical reason for this being the default that I haven't considered, but I can say that users such as myself -- who are often trying to make many charts quickly on deadline with as little configuration as possible -- being asked to learn and apply an extra setting is a hurdle.

**Comment by eitanlees** [comment]
How about encoding the year as a temporal variable

x=“year:T”

**Comment by palewire** [comment]
Here's what that returns.

```python
import altair as alt
import pandas as pd
df1 = pd.DataFrame([
        [1990, 1000],
        [1991, 2000],
        [1993, 3000],
        [1994, 4000],
        [1995, 5000],
    ],
    columns=["year", "value"]
)
alt.Chart(df1).mark_bar().encode(
    x="year:T",
    y="value"
)
```

![visualization 3](https://user-images.githubusercontent.com/9993/37691042-546f3a0c-2c6c-11e8-8419-1deac9353176.png)

**Comment by eitanlees** [comment]
hmmm, Ordinal?

```python
import altair as alt
import pandas as pd
df1 = pd.DataFrame([
        [1990, 1000],
        [1991, 2000],
        [1993, 3000],
        [1994, 4000],
        [1995, 5000],
    ],
    columns=["year", "value"]
)
alt.Chart(df1).mark_bar().encode(
    x="year:O",
    y="value"
)
```
![visualization 1](https://user-images.githubusercontent.com/2041969/37691435-6cfda70e-2c88-11e8-864c-62c5a07baa88.png)

**Comment by eitanlees** [comment]
I still think it's weird that the temporal encoding doesn't work as expected. 

Maybe @jakevdp knows.

**Comment by palewire** [comment]
That ordinal trick is cool, but it's unclear to me why it wouldn't be the default? Doesn't Vega know my data is ordinal already when it receives a list of integers? Is continuous quantitative encoding the default? And that's what has a 0 base by default?

**Comment by kanitw** [comment]
The underlying Vega-Lite doesn't know whether a value is quantitative, temporal, or ordinal unless you tell it.  (Give a field that have values  1990, 1991, 1993, 1995 -- the field can be any of quantitative, temporal, ordinal, or nominal.)  

For quantitative, ratio between bar length matters, so we automatically include zero in the scale by default. 

Vega-LIte & Vega read temporal values as timestamp by default, hence the weird year 1969.  

![image](https://user-images.githubusercontent.com/111269/37691969-e4e9707e-2c72-11e8-9a0a-7fc3ecd33d8c.png)

In Vega-Lite, you can force the time parsing to parse only year like this: 

```
{
  "$schema": "https://vega.github.io/schema/vega-lite/v2.json",
  "description": "A simple bar chart with embedded data.",
  "data": {
    "values": [
      {"a": 2003,"b": 28}, 
      {"a": 2005,"b": 55}
    ],
    "format": {
      "parse": {"a": "date:'%Y'"}  
    }
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "temporal"},
    "y": {"field": "b", "type": "quantitative"}
  }
}
```

(I'm sure there is a similar syntax in Altair.) 

I wonder if we should revise the scale to have `zero=true` based on mark orientation but that will also introduce another problem.  (We can discuss more about that in https://github.com/vega/vega-lite/issues/3562)

**Comment by jakevdp** [comment]
One note: it you want the data to be interpreted as years, I would change the type to a string and encode as a temporal value:

```python
import altair as alt
import pandas as pd
df1 = pd.DataFrame([
        [1990, 1000],
        [1991, 2000],
        [1993, 3000],
        [1994, 4000],
        [1995, 5000],
    ],
    columns=["year", "value"]
)

df1['year'] = df1['year'].astype(str)

alt.Chart(df1).mark_bar().encode(
    x='year:T',
    y="value"
)
```
![vega 4](https://user-images.githubusercontent.com/781659/37699490-a8b68b92-2cdf-11e8-84fc-a0c851b11ea9.png)


If you use a temporal encoding with an integer, it's treated as a unix time-stamp and you get strange results.

If you want the bars to take up the full year, rather than representing a day, then set ``timeUnit='year'``:
```python
import altair as alt
import pandas as pd
df1 = pd.DataFrame([
        [1990, 1000],
        [1991, 2000],
        [1993, 3000],
        [1994, 4000],
        [1995, 5000],
    ],
    columns=["year", "value"]
)

df1['year'] = df1['year'].astype(str)

alt.Chart(df1).mark_bar().encode(
    alt.X('year', timeUnit='year'),
    y="value"
)
```
![vega 5](https://user-images.githubusercontent.com/781659/37699491-ac790872-2cdf-11e8-9609-8120dc9c8a05.png)

Since there's no data for intervening years, it doesn't show those; if instead you actually specify value=0 in 1992, you get this:
```python
import altair as alt
import pandas as pd
df1 = pd.DataFrame([
        [1990, 1000],
        [1991, 2000],
        [1992, 0],
        [1993, 3000],
        [1994, 4000],
        [1995, 5000],
    ],
    columns=["year", "value"]
)

df1['year'] = df1['year'].astype(str)

alt.Chart(df1).mark_bar().encode(
    alt.X('year', timeUnit='year'),
    y="value"
)
```
![vega 6](https://user-images.githubusercontent.com/781659/37699543-e724afc6-2cdf-11e8-9ef7-40aa52f329a4.png)


If none of those options are what you have in mind, then please let me know and we can figure out how to make the chart you're thinking of.

**Comment by jakevdp** [comment]
on this question
```
That ordinal trick is cool, but it's unclear to me why it wouldn't be the default. Doesn't Altair know my data is ordinal already when it receives a list of integers? Is continuous quantitative encoding the default? And that's what has a 0 base by default?
```

Currently, unless the user specifies otherwise, Altair assumes that numerical data is quantitative. I had experimented with setting it as ordinal based on the number of unique values, but that ended up leading to confusing results (i.e. if you're plotting a line with 20 points, it behaves one way, while if you plot with 19 points, it behaves another way, which is quite confusing).

In the end, I decided that "explicit is better than implicit" and that users should explicitly set the encoding if they want something other than quantitative. All it takes is adding ":O" after the column name, after all :smile:

**Comment by mattijn** [comment]
I would then to suggest that the documentation is explicit as possible with datatype (`field=‘X’, type=‘ordinal`) instead of implicit (`field=X:O`) if the type guessing is imperfect

**Comment by jakevdp** [comment]
I would say that ``x='x:O'`` is explicit: there is no type guessing is involved in this case. It's just a more succinct syntax than ``x=alt.X('x', type='ordinal')``, but it means precisely the same thing.

**Comment by mattijn** [comment]
I see some typos with the quotes in above comment, I will fix that soon

**Comment by palewire** [comment]
Thanks for the explanation. I understand you have to choose a default and it's probably impossible to pick on that will please everyone in every circumstance. 

If quantitative is going to be the default for all integers and floats, I feel like that should be spelled out in the docs. Right now there's a helpful [data types](https://altair-viz.github.io/user_guide/encoding.html#data-types) table. That could be a place to include a note. 

Another place I'd encourage you to integrate this information in the docs is the ["Adjusting axis limits"](https://altair-viz.github.io/user_guide/config.html#adjusting-axis-limits) section. As a newbie, I interpreted it to mean I would be forced to manually set a Scale for every chart I made, which felt like a real drag and encouraged me to file this ticket.

**Comment by jakevdp** [comment]
Thanks!

I agree that the docs are wildly incomplete right now and I'd appreciate any help in making them better.

**Comment by jakevdp** [comment]
Regarding including zero in quantitative scales, that's a decision made within the Vega-Lite library, and Altair has no control over that.

**Comment by jakevdp** [comment]
Closing, as this is a vega-lite issue: https://github.com/vega/vega-lite/issues/3562
