### ISSUE TITLE
Documentation for how to exclude the Legend

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#620]
I'm struggling to find it in the docs right now and would love an example.

**Comment by palewire** [comment]
Is this the recommended way? If so, I can add some documentation.

```python
base = alt.Chart(df).mark_bar().encode(
    x='x',
    y='y',
    color=alt.Color('group', legend=None),
)
```

**Comment by kanitw** [comment]
Try legend=False or None?

**Comment by kanitw** [comment]
If None works, i think that s better. (False isnt included as a part of
VegaLite schema, but works just in case users forget to use null in json)

Cc: @jakevdp — correct me if im wrong

**Comment by jakevdp** [comment]
I think ``legend=False`` here does not work, because the schema doesn't allow the legend value to be boolean.

Use ``legend=None``. This is reflected in the Altair documentation:

```
>>> help(alt.Color)
class Color(altair.vegalite.v2.schema.core.MarkPropFieldDefWithCondition)

<snip>

 |  legend : anyOf(Legend, None)
 |      An object defining properties of the legend. If `null`, the legend for the encoding 
 |      channel will be removed.  __Default value:__ If undefined, default [legend 
 |      properties](https://vega.github.io/vega-lite/docs/legend.html) are applied.

<snip>
```

**Comment by jakevdp** [comment]
It would be useful to have this within the [Configuring Charts](https://altair-viz.github.io/user_guide/config.html) section of the documentation, which is pretty incomplete at the moment.

**Comment by palewire** [comment]
Okay. I'll give that a try.

**Comment by jakevdp** [comment]
Altair 1 lacked support for setting values to explicit nulls. The only way to do this is to export the dict, then explicitly set legend to None, and then convert to JSON.

I'd recommend upgrading to Altair 2.
