### ISSUE TITLE
Controlling chart sizes

### ISSUE THREAD

**Issue by saketkc** [altair-viz/altair#621]
I have a use case where I want to plot stacked text of different heights.

```python
import altair as alt
import pandas as pd
import numpy as np
```

# Plotting text with same font size

Let's plot text with constant fontSize = 1 px
As defined in the [API docs](https://altair-viz.github.io/user_guide/API.html?highlight=transforms#altair.Chart.encode) size refers to font size in pixels for a text mark.

We start of with all fonts having 8px  height.

```python
data = pd.DataFrame({'x': ['1', '1', '1', '1', '2', '2', '2', '2'],
                     'y': ['1', '2', '3', '4', '1', '2', '3', '4'],
                    'yshift': np.array([1, 2, 3, 4, 1, 2, 3, 4]),
                    'heights': np.array([1, 1, 1, 1, 1, 1, 1, 1]) * 8 })
alt.Chart(data).mark_text(baseline='top', font='Monospace').encode(
    x='x',
    y='yshift',
    text='y',    
    size='heights'
)
```

![1](https://user-images.githubusercontent.com/682153/37694680-638fba10-2c86-11e8-8bf3-1ff242e4a25f.png)

The spacing looks a bit weird. Ideally, I would want the stacking to be packed.
Since each font is 8px tall, we restrict the chart height to be 32px.

```python
# height = 32px
alt.Chart(data, height=32).mark_text(baseline='top', font='Monospace').encode(
    x='x',
    y='yshift',
    text='y',    
    size='heights'
)#.properties(60)
```

![2](https://user-images.githubusercontent.com/682153/37694681-67d2f4c0-2c86-11e8-9c0b-f288172f8b85.png)

That doesn't look right either, so let's try to increase the height:

```python
# height = 64px
alt.Chart(data, height=64).mark_text(baseline='top', font='Monospace').encode(
    x='x',
    y='yshift',
    text='y',    
    size='heights'
)
```

![3](https://user-images.githubusercontent.com/682153/37694682-6c6d71fe-2c86-11e8-9c4c-0d9c6d246997.png)

```python
# height = 120px
alt.Chart(data, height=120).mark_text(baseline='top', font='Monospace').encode(
    x='x',
    y='yshift',
    text='y',    
    size='heights'
)
```

![4](https://user-images.githubusercontent.com/682153/37694683-7005d630-2c86-11e8-88c6-0b6e5b23c690.png)

That looks about right. What if we keep going?

```python
# height = 200px
alt.Chart(data, height=200).mark_text(baseline='top', font='Monospace').encode(
    x='x',
    y='yshift',
    text='y',    
    size='heights'
)
```

![5](https://user-images.githubusercontent.com/682153/37694685-745cc4b4-2c86-11e8-953a-3adbcbc7bff5.png)

So 120 px looked about right. What if we then increase the font size?

```python
# fontsize=16
data = pd.DataFrame({'x': ['1', '1', '1', '1', '2', '2', '2', '2'],
                     'y': ['1', '2', '3', '4', '1', '2', '3', '4'],
                    'yshift': np.array([1, 2, 3, 4, 1, 2, 3, 4]),
                    'heights': np.array([1, 1, 1, 1, 1, 1, 1, 1]) * 16 })
alt.Chart(data, height=120).mark_text(baseline='top', font='Monospace').encode(
    x='x',
    y='yshift',
    text='y',    
    size='heights'
)
```

![6](https://user-images.githubusercontent.com/682153/37694691-7980c4d6-2c86-11e8-829d-7a8d50fa65ff.png)

Try with fontsize = 32:

```python
# fontsize=32
data = pd.DataFrame({'x': ['1', '1', '1', '1', '2', '2', '2', '2'],
                     'y': ['1', '2', '3', '4', '1', '2', '3', '4'],
                    'yshift': np.array([1, 2, 3, 4, 1, 2, 3, 4]),
                    'heights': np.array([1, 1, 1, 1, 1, 1, 1, 1]) * 32 })
alt.Chart(data, height=120).mark_text(baseline='top', font='Monospace').encode(
    x='x',
    y='yshift',
    text='y',    
    size='heights'
)
```

![7](https://user-images.githubusercontent.com/682153/37694692-7e48ce50-2c86-11e8-91ca-a6d5d517c5a7.png)

This looks same as font size 16...

There's a related example in vega-lite:
https://vega.github.io/editor/#/examples/vega/word-cloud

It seems the chart size gets overriden if set below a certain threshold. Is there a way to acheive a tight stacking without determining what chart height I should be selecting?

**Comment by jakevdp** [comment]
when you say ``heights=np.ones(8) * 32``, you're not specifying that the height should be 32px. You're specifying that the size of the points should encode a set of values which are identical, and that domain will be mapped to an appropriate range of actual marker sizes.

If you want to actually set the **value** of any channel, then use the ``value`` marker:
```python
data = pd.DataFrame({'x': ['1', '1', '1', '1', '2', '2', '2', '2'],
                     'y': ['1', '2', '3', '4', '1', '2', '3', '4'],
                    'yshift': np.array([1, 2, 3, 4, 1, 2, 3, 4])})
alt.Chart(data,
    width=120,
    height=120
).mark_text(
    baseline='top',
    font='Monospace'
).encode(
    x='x',
    y='yshift',
    text='y',    
    size=alt.value(32)
)
```
![vega 8](https://user-images.githubusercontent.com/781659/37700154-4e7d741c-2ce2-11e8-9bec-cb663482aab4.png)

If you want the data domain mapped to a particular range of values, you can set the ``domain`` and ``range`` explicitly in the channel's scale:

```python
data = pd.DataFrame({'x': ['1', '1', '1', '1', '2', '2', '2', '2'],
                     'y': ['1', '2', '3', '4', '1', '2', '3', '4'],
                    'yshift': np.array([1, 2, 3, 4, 1, 2, 3, 4]),
                    'heights': np.array([8, 16, 32, 64, 8, 16, 32, 64])})


alt.Chart(data,
    width=120,
    height=200
).mark_text(
    baseline='top',
    font='Monospace'
).encode(
    x='x',
    y='yshift',
    text='y',    
    size=alt.Size('heights',
        scale=alt.Scale(domain=(1, 32), range=(1, 32))
    )
)
```
![vega 9](https://user-images.githubusercontent.com/781659/37700293-d7c051c2-2ce2-11e8-9c72-506b8ffadeb5.png)

**Comment by saketkc** [comment]
Thanks @jakevdp!
