### ISSUE TITLE
Typo in an example, can't find where to PR

### ISSUE THREAD

**Issue by jamestwebber** [altair-viz/altair#630]
Apologies if this is the wrong place (pretty sure it is) but I've been searching around to figure out where the example gallery comes from and I'm stymied. I just wanted to correct the typo in [Multi-Lite (sic) Tooltip](https://altair-viz.github.io/gallery/multiline_tooltip.html).

You probably don't need my help for that one, but if you can point me in the right direction I'll know where to go in the future.

**Comment by afonit** [comment]
@jamestwebber 
here you go:
https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/multiline_tooltip.py

**Comment by jamestwebber** [comment]
Aha! I never would have found that, I started looking in other repos...

Created a PR at #631
