### ISSUE TITLE
Why not make the expressions available as attributes on the top level import?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#636]
There might be a good reason for this I'm ignorant of, but wouldn't it be nicer if you could do this:

```python
import altair as alt
print(alt.datum) # <-- Just dummy code to illustrate accessing datum for use
```
Instead of this:

```python
import altair as alt
from altair.expr import datum
print(datum)
```

Why not structure the expressions like `datum` in a way that they are available to the `alt` object without requiring a second import?

**Comment by jakevdp** [comment]
My original thinking in creating the ``expr`` sub-module was that there are a **lot** of functions and constants defined there, most of which are very uncommonly used in the API, and so having them all in the top-level namespace would mostly serve to obfuscate tab-completion of more important functionality.

**Comment by palewire** [comment]
Would it be possible to make this available?

```
import altair as alt
print(alt.expr.datum)
```

**Comment by jakevdp** [comment]
I think that is available currently, no?

```python
>>> import altair as alt
>>> alt.expr.datum.foo < 1
(datum.foo < 1)
```

**Comment by jakevdp** [comment]
Actually, now that I look at it, ``alt.datum`` is available currently as well:
```python
>>> import altair as alt
>>> alt.datum.foo < 1
(datum.foo < 1)
```

**Comment by palewire** [comment]
Ah. I see. I had encountered this error and misinterpreted it then. I guess I just need to provide another attribute. 

![screenshot from 2018-03-22 15-23-13](https://user-images.githubusercontent.com/9993/37801744-fc18af08-2de4-11e8-9f6d-7fc41562d4b4.png)

If that will work, IMHO, it would be a more straightforward way to introduce usage in the docs. This is of course a matter of style and almost certainly subjective, but the fewer imports the better, IMHO, and especially for newbies.

**Comment by jakevdp** [comment]
Fair enough. In context of its normal use, it would be something like this:
```
import altair as alt
alt.Chart(data).transform_filter(
    alt.datum.column1 < alt.expr.sin(alt.datum.column2)
)
```
The alternative is this:
```
import altair as alt
from altair.expr import datum, sin

alt.Chart(data).transform_filter(
    datum.column1 < sin(datum.column2)
)
```
I prefer the latter because it's much easier to understand what's happening at a glance, but I could see the argument for avoiding imports as well.

**Comment by palewire** [comment]
As is obvious, this is a subjective decision. And I'm definitely being pedantic so thank you in advance for indulging me.

That said, IMHO, the first example is more consistent, and in keeping with the import style of pandas, which Altair has already chosen to emulate with the "as alt" convention. If `alt.Chart` is going to be the standard invocation, why shouldn't the expressions be invoked from the `alt` in the same manner?

To me, the second snippet above is offering of a mix of two different import styles, which I fear will confuse newbiews. If that second style aimed for consistency, wouldn't that call for `Chart` to be introduced like this:

```python
from altair import Chart
from altair.expr import datum, sin

Chart(data).transform_filter(
    datum.column1 < sin(datum.column2)
)
```

**Comment by jakevdp** [comment]
Yes, I can see what you're saying. I'd be happy to move to a more uniform import convention if you think that would be clearer.

**Comment by palewire** [comment]
I'm in favor of the style in first example you gave above:

```
import altair as alt

alt.Chart(data).transform_filter(
    alt.datum.column1 < alt.expr.sin(alt.datum.column2)
)
```

Though I wonder why the term "datum" has been selected. Why not the more commonly used "data?" That would also match the convention for the variable submitted to `alt.Chart`.

**Comment by jakevdp** [comment]
We use datum because that's what's used in vega-lite: the output of the above code is literally just a string that looks like

``"datum.column1 < sin(datum.column2)"``

(which, not coincidentally, when you take away the quotes is exactly what you type if you do the imports the way I prefer)

**Comment by jakevdp** [comment]
The reason it should not be symmetric with the ``data`` that you pass to chart is that you're not doing operations on the entire data! You'd doing operations on one element at a time within the data, for which "datum" seems a reasonable choice of nomenclature.

**Comment by jakevdp** [comment]
In any case, I don't think it makes sense to break conventions with the choices made in Vega-Lite, so I'm going to close this.
