### ISSUE TITLE
Simplify count

### ISSUE THREAD

**Issue by domoritz** [altair-viz/altair#640]
Count aggregates are super common and could be simplified a bit in altair. I am proposing two changes. First, remove the field *. We removed the need to that in Vega-Lite a long time ago and I hope we can do the same in Altair. Second, by default Altair could infer the type to be Q. 

`'count(*):Q'` would then be written as just `'count()'`.

To me, the first change (getting rid of *) is more important than the second one.

**Comment by jakevdp** [comment]
Good point! I have a trans-Atlantic flight tomorrow; I'll put this on my list :smile:

**Comment by domoritz** [comment]
Have a good ✈️

**Comment by domoritz** [comment]
@vlandham, I filed this when I saw your blog post about Altair.

**Comment by domoritz** [comment]
I think it would be good to change all examples not to use *.

**Comment by jakevdp** [comment]
> I think it would be good to change all examples not to use *.

I did as part of that PR: 5bc2a3e46ee2c676 Pllease let me know if you find any that I missed.

**Comment by domoritz** [comment]
Ups, I somehow missed that. When this is released, we can update https://github.com/vlandham/vlandham.github.com/blob/master/_posts/2018-03-23-altair_intro.md ;-)

**Comment by jakevdp** [comment]
I think I'll probably do an rc2 release tomorrow...
