### ISSUE TITLE
Should the example gallery be refactored to use alt.load_dataset?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#644]
I just discovered the `alt.load_dataset` convenience method [packaged with the library](https://github.com/altair-viz/altair/blob/master/altair/datasets.py). I think it's a great idea and yet another way to provide a Python wrapper on the lower-level Vega tools.

If this is intended to be the standard way to pull in samples from vega_datasets, shouldn't the examples but updated to use it? That could change something like this:

```python
import altair as alt
from vega_datasets import data

source = data.cars()

chart = alt.Chart(source).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    size='Acceleration'
)
```

To something like this:

```python
import altair as alt

data = alt.load_dataset('cars')

chart = alt.Chart(data).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    size='Acceleration'
)
```

If you agree, I'd be happy to contribute this revision.

**Comment by eitanlees** [comment]
Many of the examples use the url reference to the data which I don't think `alt.load_dataset` can do. I think the reason for using the url was that the specs use it as a reference rather than copying all of the data. 

I understand wanting to cut down on imports. Maybe url functionality can be added to `alt.load_dataset`?  `alt.load_dataset('cars', url=True)`? Or a separate function `alt.load_dataset_url`? I don't know.

**Comment by palewire** [comment]
Perhaps, like [pandas' `read_csv` function](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.read_csv.html), the function could become "smart enough" accept a dataset name or URL as its input. Pandas does this by applying a simple ["is_url"](https://github.com/pandas-dev/pandas/blob/v0.22.0/pandas/io/common.py#L76) test against the argument.

**Comment by jakevdp** [comment]
``load_dataset`` is basically deprecated. Before the existence of ``vega_datasets``, we had some of that code within Altair.

We should not mention or use it anywhere in the documentation, and should probably mark it deprecated.

**Comment by palewire** [comment]
Thank you for sharing this insight. I will close this ticket.
