### ISSUE TITLE
Add minimal HTML export.

### ISSUE THREAD

**Issue by janfreyberg** [altair-viz/altair#656]
I've been using Altair to make plots to embed in my Jekyll blog. I've had the issue that the HTML export includes too much for simple embedding - there's a header that loads the JS libraries (which I do in the header of my blogpost template), and if you embed multiple charts on the same page, you end up with several divs that all have the same ID (`vis`), which doesn't work well.

I think there are two things that could help with this:

1. Adding a "minimal HTML" exporter that only includes the div.

The template for this would I think be something like:

```
  <div id="vis"></div>
  <script type="text/javascript">
    var spec = {spec};
    var opt = {embed_opt};
    vegaEmbed("#vis", spec, opt);
  </script>
```

2. Adding a keyword argument for the div ID or generating a UUID based ID for each export.

What do you think? I'm happy implementing these, but wanted to check that this is something you think would be useful.

**Comment by jakevdp** [comment]
Honestly, this strikes me as something that's better handled by the user. You can use ``chart.to_json()`` to get a JSON string for your chart, and then embed it however is best for your own particular use-case. I think going down the path of trying to provide HTML templates for every possible use-case is a losing proposition.

**Comment by janfreyberg** [comment]
Yeah, that's fair enough.
