### ISSUE TITLE
JavaScript output is disabled in JupyterLab

### ISSUE THREAD

**Issue by desilinguist** [altair-viz/altair#659]
I had jupyterlab from the anaconda `defaults` channel already installed. I then installed the `altair`and `vega` packages from `conda-forge` channel. I tried the basic example from this recent [tutorial](http://vallandingham.me/altair_intro.html) and I get the following message when I try to render the cell

`JavaScript output is disabled in JupyterLab`.

The vega3 extension seems to be properly installed and enabled in the right kernel:

```
$> jupyter labextension list 
JupyterLab v0.31.12
Known labextensions:
   app dir: /Users/nmadnani/anaconda/share/jupyter/lab
@jupyterlab/vega3-extension
        @jupyterlab/vega3-extension v0.14.4  enabled  OK
```

Any ideas? I am not sure what I am doing wrong.

**Comment by pagpires** [comment]
Right now `altair` is available at `pip` but not ready at `conda-forge`. You can also follow this [installation guide](https://altair-viz.github.io/getting_started/installation.html) for installation. Also make sure your are using python3. If still not working, I suggest create a new environment and install them, to make sure there are no potential conflicts.

**Comment by desilinguist** [comment]
Hmm, so does that mean that the [installation instructions](https://altair-viz.github.io/getting_started/installation.html) are incorrect since they say that we can use `conda-forge` as an alternative to `pip`? I think it is because `conda-forge` seems to only have installed v1.2.1 of `altair`. I will re-try with pip and close the issue if it works. Thanks!

**Comment by pagpires** [comment]
Please note there's a warning message on that page "conda installation is not yet available for the version 2.0 release candidate. Please install the release candidate with pip".

**Comment by jakevdp** [comment]
Conda installation will be available for the final release, but currently, as stated on the installation page you linked to, it's not available.

Please install using pip, following the directions at https://altair-viz.github.io/getting_started/installation.html, and it should work.

**Comment by desilinguist** [comment]
Ah, I missed the warning. Sorry about that. I have a whole another issue after installing with `pip` but I will post that in another issue.
