### ISSUE TITLE
support for pd.Series?

### ISSUE THREAD

**Issue by pagpires** [altair-viz/altair#670]
Please correct me if I missed something. But I didn't find a way to make a plot using a pd.Series (no columns). Is it not supported and therefore a pd.DataFrame is required?

**Comment by jakevdp** [comment]
Yes, dataframes are required. All data is referenced by column name, and because series has no column names, there is no way to reference the data.

If you have a series named ``data``, you can use

```
alt.Chart(data.to_frame(column_name))
```

where ``column_name`` is the column name that you'll use to refer to the data within the chart.

**Comment by pagpires** [comment]
Thanks

**Comment by pagpires** [comment]
This may be a related question: what's the best practice to plot a dataframe with the index as the x-axis? The user case can be https://jakevdp.github.io/PythonDataScienceHandbook/03.11-working-with-time-series.html#Resampling-and-converting-frequencies, in which case Date is heavily used for data transformation and is therefore better to be kept in the index. To overlay the three plots in the example, I found 'index:T' is not a valid encoding, so I have used `df.re_index()` to feed into the alt.Chart() after each data transformation, but it seems very tedious. Is there a better way to plot df with an index?

**Comment by jakevdp** [comment]
The best way is to use ``reset_index()`` to explicitly turn the index into a column in the dataframe. For example:

```python
import altair as alt
import pandas as pd
import numpy as np

data = pd.DataFrame({'y': np.random.randn(100).cumsum()})
data = data.reset_index()

alt.Chart(data).mark_line().encode(
    x='index',
    y='y'
)
```
![visualization](https://user-images.githubusercontent.com/781659/40019578-7c97cc82-5774-11e8-8ba4-1c89ec951953.png)
