### ISSUE TITLE
Is it possible to transform_filter with a test against a list?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#676]
Here's what I mean. 

```python
import altair as alt
from vega_datasets import data
df = data.stocks()
alt.Chart(df).mark_line().encode(
    x='date:T',
    y='price:Q',
    color="symbol",
    column="symbol:N"
).transform_filter(alt.datum.symbol in ["AAPL", "AMZN"])
```

I'm trying to spit out a restricted list of two charts, for Apple and Amazon. But this raises an error.

```python-traceback
SchemaValidationError: Invalid specification

        altair.vegalite.v2.schema.core.FilterTransform ->filter, validating 'anyOf'

        True is not valid under any of the given schemas
```

This is a use case I see as pretty common. For instance, after grouping on a field I'd like to spit out mini multiple charts of the top ten ranking values.

**Comment by jakevdp** [comment]
Oh, I should have also mentioned that a wrapper for this exists in Altair:

```
transform_filter(alt.FieldOneOfPredicate(field='symbol', oneOf=['AAPL', 'AMZN']))
```

**Comment by palewire** [comment]
Would it be possible for datum columns to emulate pandas with their own `isin` method? Or would that stray too far from Vega?

**Comment by palewire** [comment]
Give it some thought. Not an glaring flaw in the library, but this is a use case that is common in my work. 

Oftentimes in data journalism we're working with dirty data we've adopted from the government or another outside source. It is common to want to group on a column and then more closely inspect the most frequent variations. It's come up twice in two different contexts since I started using Altair two weeks ago. I can give you more specific examples privately if that would help. But I'm guessing you get what I mean.

**Comment by jakevdp** [comment]
I've added documentation for this in #690; still a work in progress.

**Comment by jakevdp** [comment]
The documentation is now up on the website: https://altair-viz.github.io/user_guide/transform.html#field-predicates

**Comment by leonelcamara** [comment]
> 
> 
> It would not be possible to make this work using something like `alt.datum.symbol in ["AAPL", "AMZN"]`, because in Python `x in y` always returns a boolean, and the language provides no mechanism to overload the behavior of the `in` operator.

Actually it does, you can use __contains__

**Comment by jakevdp** [comment]
You can't override contains on the built-in list type

**Comment by leonelcamara** [comment]
@jakevdp good point. I suggest something like this then:

alt.datum.symbol.in(["AAPL", "AMZN"])
or
alt.datum.symbol.belongs(["AAPL", "AMZN"])

**Comment by jakevdp** [comment]
The alt.datum syntax is a thin wrapper around the vega expression syntax. For the sake of maintainability I'd prefer not to extend the syntax in that way on the Altair side.
