### ISSUE TITLE
Arrange facets in a grid

### ISSUE THREAD

**Issue by kuchenrolle** [altair-viz/altair#681]
How can I arrange the cells in a faceted plot, so that they are not all in one row or one column?

**Comment by jakevdp** [comment]
I'm not certain that's supported in Vega-Lite. @kanitw, @domoritz, any thoughts?

**Comment by kuchenrolle** [comment]
I suppose I could create individual charts (say one per row) on subsets of the data and then stack them, but the problem with that is that I am double coding the variable I use for faceting as color and I want to keep the colors.

(So, side question, if I use the "reds" scheme, how do I get the code points of the corresponding colors so I can set them manually?)

**Comment by domoritz** [comment]
We will add this in Vega-Lite with https://github.com/vega/vega-lite/issues/393.

**Comment by kuchenrolle** [comment]
Is there a hacky way I can do it now?

**Comment by domoritz** [comment]
> Is there a hacky way I can do it now?

Yes, you can modify the generated Vega spec and modify the number of columns in the `layout`.

**Comment by kanitw** [comment]
Another way is to derive two new fields (row and column) based on `calculate` formula.  
For example, if you have a = 0, 1, 2, 3, ..., 14. and you want 5x3 grid

You can do `row = datum.a/3` and `column = datum.a%3`

**Comment by kuchenrolle** [comment]
@domoritz I don't see `layout` in the spec, what exactly do I change?

@kanitw Thanks, that put me on the right track. I couldn't quite get it to work, because if I specify row and column like that altair complains that 
```python
SchemaValidationError: Invalid specification

        altair.vegalite.v2.schema.core.FacetMapping ->row, validating 'type'

        '(datum.a / 3)' is not of type 'object'
```
I got it to work like so:
```
from altair.expr import datum, floor
df["codes"] = df.a.cat.codes

plot = alt.Chart().mark_bar().encode(
    x = "Variable:Q"),
    y = "count(*):Q",
    color = "PLV:N"
).transform_calculate("rowcodes", floor(datum.codes / 3)
).transform_calculate("columncodes", datum.codes % 3)

plot.facet(row="rowcodes:N", column="columncodes:N", data=df)
```
Because the variable is categorical, I had to create a new column to have the code points available for the expressions (and the expressions do float division, which is why floor was necessary). While this works, it comes with two problems: It creates empty plots (my categorical variable has five values, but this creates six plots) and the titles of the facets are just integers, which isn't great, so I would like to suppress them, but I have no idea how to do that.

Also, is there a way to duplicate the axes? It would be useful to have the x- and y-axes on every facet, rather than the whole plot.

**Comment by domoritz** [comment]
> I don't see layout in the spec, what exactly do I change?

It's in the Vega spec. Check out the compiled Vega in the editor.

<img width="1059" alt="screen shot 2018-03-31 at 10 58 05" src="https://user-images.githubusercontent.com/589034/38166067-718a5a5e-34d2-11e8-8644-9941ffd30726.png">

**Comment by sveitser** [comment]
> ... and the titles of the facets are just integers, which isn't great, so I would like to suppress them, but I have no idea how to do that.

@kuchenrolle Did you end up finding a way to set titles for the subplots.

**Comment by jakevdp** [comment]
I'm going to close this issue in favor of #824
