### ISSUE TITLE
Labels on a stacked area chart

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#684]
The stacked area chart [example](https://altair-viz.github.io/gallery/stacked_area_chart.html) is great.

![screenshot from 2018-03-30 15-36-15](https://user-images.githubusercontent.com/9993/38156053-1cfc0f48-3430-11e8-9126-a23fa5ce79e0.png)

But it would be even better if you could put labels on the areas, as the New York Times did [here](https://www.nytimes.com/interactive/2017/12/29/upshot/internationalization-of-pro-sports-leagues-premier-league.html):

![screenshot from 2018-03-30 15-37-14](https://user-images.githubusercontent.com/9993/38156073-3ed966ec-3430-11e8-8f56-2ecc17553d25.png)

Possible?

**Comment by jakevdp** [comment]
I don't think vega-lite makes that kind of labeling possible. You could externally compute the location of the text labels and use ``mark_text``, but that's not a very good solution.

**Comment by kanitw** [comment]
> I don't think vega-lite makes that kind of labeling possible

Yeah, currently Vega-Lite doesn't support this.  
  
But once we add add [explicit `stack` transform](https://github.com/vega/vega-lite/issues/3311), we should be able to reproduce (or at least getting close to) this [vega example](https://vega.github.io/vega/examples/job-voyager/).  

If you want to use this, you're welcome to submit a PR to Vega-Lite :)

**Comment by jakevdp** [comment]
The stack transform is part of Altair 3, so stacked labels like this should be possible now. A relevant example from the gallery is this: https://altair-viz.github.io/gallery/stacked_bar_chart_with_text.html
