### ISSUE TITLE
Two renderers with same name

### ISSUE THREAD

**Issue by sawula** [altair-viz/altair#686]
Working with a fresh Anaconda installation of Jupyter 3.6.  Followed Altair Notebook installation instructions.  Basic example (flower petals scatter plot) rendered but with JSON underneath graph (issue #634).  I thought this might be due to having selected the wrong renderer., so I went to list the available renderers. 

`alt.renderers.names()`
returns
`['default', 'json', 'notebook', 'notebook']`

Secretly hoping the second `notebook` renderer solves  #634.  In any case, I think you shouldn't be able to have two renderers with the same name.  

(hs teacher, maybe I'm missing something)

**Comment by jakevdp** [comment]
Strange... I'll look into it, but it doesn't solve #634. Still waiting for advice from @ellisonbg on that one.

**Comment by jakevdp** [comment]
In the meantime, I'd suggest using JupyerLab... that bug doesn't come up, and there's no need to think about renderers at all.

**Comment by sawula** [comment]
Yup.  JupyterLab solves all the problems including #634 and #687.  Thanks for getting me to move on to Python 3 and JupyterLab.

BTW: Having trouble getting this all working in Azure (which is a safer place for my students), but that's an Azure issue.

**Comment by jakevdp** [comment]
We should try to get it working with Azure... it might take a little tweaking, depending on how they've set things up. A week ago I implemented a Colab renderer. That might actually work out-of-the-box with Azure.

**Comment by jakevdp** [comment]
I can't reproduce this duplicate renderer. What environment are you in?

**Comment by jakevdp** [comment]
got it :smile:

**Comment by sawula** [comment]
thanks!  i was away from my computer all day.

belatedly: anaconda, windows (10) 64-bit, python 3.6
