### ISSUE TITLE
`datum.xxx == None` and similar representations are PEP8 violations

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#705]
The `expr` library includes this test:

```python
def test_json_reprs():
    """Test JSON representations of special values"""
    assert repr(datum.xxx == None) == '(datum.xxx === null)'
    assert repr(datum.xxx == False) == '(datum.xxx === false)'
    assert repr(datum.xxx == True) == '(datum.xxx === true)'
```

This is of course a pedantic concern, but PEP8 says:

> Comparisons to singletons like None should always be done with is or is not, never the equality operators.

This is encoded in the flake8 library as rules E711 and E712, which the library current violates.

**Comment by jakevdp** [comment]
These are forms that actually need to be used in order to generate valid vega-lite expressions, so this is a case of PEP-8 being overly restrictive.

**Comment by palewire** [comment]
Got it. I've tried to address this in #707.

**Comment by jakevdp** [comment]
Is there a way to omit just specific instances? In general we should be following E711 & E712, but not in the case of ``datum`` attributes.

**Comment by jakevdp** [comment]
(I rarely do anything with PEP8 in my repos because I generally find it to be more annoying than useful :smile: )

**Comment by palewire** [comment]
I believe there is. I will look into it.

**Comment by palewire** [comment]
Refactored as requested in https://github.com/altair-viz/altair/pull/707/commits/cb0edcb37b9533e6dab8388eac0b11c16ff6e00a
