### ISSUE TITLE
Axis titleColor and jupyterlab dark theme

### ISSUE THREAD

**Issue by afonit** [altair-viz/altair#717]
Is Axis titleColor implemented?

```python
import altair as alt
from vega_datasets import data

source = data.cars()

chart = alt.Chart(source).mark_point().encode(
    x=alt.X('Horsepower', axis=alt.Axis(title='what', titleColor='white')),
    y='Miles_per_Gallon',
    size='Acceleration'
).configure(background='white')
chart
```
results in:

SchemaValidationError: Invalid specification

        altair.vegalite.v2.schema.core.Axis, validating 'additionalProperties'

        Additional properties are not allowed ('titleColor' was unexpected)

I have been trying to play with the color attributes on the axis to experiment with the dark theme in jupyter lab.
https://vega.github.io/vega-lite/docs/axis.html
Some mentioned in that link are:
gridColor
labelColor
tickColor
titleColor

**Comment by jakevdp** [comment]
Yes, ``titleColor`` is available as an ``AxisConfig`` keyword:
```
chart.configure_axis(
    titleColor='white'
)
```
I'm not certain why Vega Lite 2 no longer makes it available as an ``Axis`` keyword.

**Comment by afonit** [comment]
@jakevdp great thanks.
I see all those now - chart.configure.tick etc I see now too.  Thank you.
