### ISSUE TITLE
changes from altair1 to altair2?

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#720]
I'm taking altair1 code and trying to make it work with altair2 (also a switch to python3). Not asking anyone to debug my code, but chart.savechart fails with a vega-lite schema validation error I've never seen before.

Is there any sort of porting guide that says "if you did this in altair1, it doesn't work any more, do this instead"?

```
    chart.savechart(os.path.join(outputdir, name) + '.' + fileformat)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/altair/vegalite/v2/api.py", line 374, in savechart
    return self.save(fp, format=None, **kwargs)
...
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/altair/utils/schemapi.py", line 237, in to_dict
    raise SchemaValidationError(self, err)
altair.utils.schemapi.SchemaValidationError: Invalid specification

        altair.vegalite.v2.schema.channels.Column, validating 'additionalProperties'

        Additional properties are not allowed ('axis' was unexpected)
```

**Comment by jakevdp** [comment]
Altair 2.0 has a number of backward-incompatible changes. It looks like the issue here is that you tried adding an ``axis`` argument to a ``Column`` encoding, which is not a valid option.

**Comment by jakevdp** [comment]
What were you trying to change in the encoding by setting an ``axis`` property?

**Comment by jakevdp** [comment]
As for a porting guide: we don't have one. The changes are generally at the level that were never documented in Altair 1.0, and are still not well documented in Altair 2.0. I think rather than spending effort writing a porting guide, I'll spend effort writing documentation.

**Comment by jowens** [comment]
> As for a porting guide: we don't have one. The changes are generally at the level that were never documented in Altair 1.0, and are still not well documented in Altair 2.0. I think rather than spending effort writing a porting guide, I'll spend effort writing documentation.

Totally understandable. I got your back!

**Comment by jowens** [comment]
```
    column=Column('algorithm:N',
                  axis=Axis(
                      title='Primitive',
                      orient='top',
                  )
                  ),
```

http://gunrock.github.io/gunrock/doc/latest/md_stats_engines_topc.html has the graph (from Altair 1). Wanna help a brother out on how I should do this?

**Comment by jakevdp** [comment]
As far as I can tell, Vega-Lite 2 no longer provides a way to specify the orient property of a facet. @domoritz or @kanitw might have a better idea.

**Comment by domoritz** [comment]
I think we haven't implemented it yet as we switched from scales to Vega layouts for faceting. We will add it back eventually.

**Comment by jowens** [comment]
OK. Thanks! I'm done with this issue, but maybe @domoritz might want to make a note for future vl development.

**Comment by jowens** [comment]
@domoritz thoughts on how I can do the following without `Axis`?

```
        row=Row('do_a:O',
                axis=Axis(format='.1',
                          title='do_a',
                          ),
                ),
        column=Column('do_b:O',
                      axis=Axis(format='.1',
                                title='do_b',
                                labelAngle=-90.0,
                                labelAlign='left',
                                labelBaseline='middle',
                                offset=0.0,
                                ),
                      ),
```

Altair 1 graphs are here: http://gunrock.github.io/gunrock/doc/latest/md_stats_do_ab_random.html

"This isn't possible" is OK, of course.

**Comment by jowens** [comment]
For posterity, I'll record other Altair 1 calls that disappeared (and were probably replaced with much much better things).

`Chart(df).mark_text(applyColorToBackground=True).encode(`   (no more `applyColorToBackground`)

Chart argument `text=Text(value=' '),`   (`value` no longer valid)

Chart chained argument `Chart().configure_scale(textBandWidth=12, bandSize=12)` (no more `configure_scale`)

As I find solutions I'll fill them in here.

**Comment by jowens** [comment]
@domoritz any chance of commenting on my Apr 14 query above? Thx.

**Comment by domoritz** [comment]
Good timing. We just merged https://github.com/vega/vega-lite/pull/3943, which adds support for `header`. Once this is released and a new version of Altair is out, you can use it.

**Comment by domoritz** [comment]
Vega-Lite 3 rc is out and I will release the corresponding python packages soon.

**Comment by jowens** [comment]
Oh, super, will there be an Altair 2.2 that supports it? @jakevdp 

Good luck with release, @domoritz

**Comment by jakevdp** [comment]
Yes, there will be a release.

I'm currently pushing toward a 2.2 release with Vega-Lite 2.6 functionality.

VL v3.0 has some more substantial changes, and will take a bit more effort to get Altair working with it.

**Comment by jakevdp** [comment]
(providing good APIs for the new transforms is probably the biggest part of the work)
