### ISSUE TITLE
chart.to_html ?

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#721]
`chart.to_html` was part of altair1 and seems to have disappeared. It output a string, which I found useful.

Use case for me was outputting a markdown file that embedded an Altair chart. I used `chart.to_html` to output the HTML string representing the chart into that md file.

**Comment by jakevdp** [comment]
That functionality is now part of the ``save()`` function
```
chart.save('filename.html')
```

**Comment by jowens** [comment]
Sure, but that writes a file. `chart.to_html` returned a string. I can write a file then read the file, I guess.

**Comment by jakevdp** [comment]
Or you can do the normal trick of writing to a file-like object using io.StringIO to avoid touching the file system.

**Comment by jowens** [comment]
News to me! Will do.
