### ISSUE TITLE
BUG: some vega wrappers have name collisions

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#734]
My PyFlakes checks return the following errors:

```bash
./altair/vega/v3/schema/core.py:2246:1: F811 redefinition of unused 'scale' from line 591
./altair/vega/v3/schema/core.py:2697:1: F811 redefinition of unused 'signal' from line 649
./altair/vega/v2/schema/core.py:1296:1: F811 redefinition of unused 'scale' from line 1253
./altair/vega/v2/schema/core.py:1435:1: F811 redefinition of unused 'signal' from line 425
./altair/vega/v2/schema/core.py:1464:1: F811 redefinition of unused 'data' from line 115
```

Following these tracebacks introduced me to classes with identical names in the Vega v2 and v3 core schema files.

There might be a very good reason for this, but I'm ignorant of it. So I thought I'd flag the issue here to make sure you're aware. 

Here is one example. The v3 schema's core file defines `scale` at [line 591](https://github.com/altair-viz/altair/blob/master/altair/vega/v3/schema/core.py#L591-L607):

```python
class scale(VegaSchema):
    """scale schema wrapper

    allOf(Mapping(required=[name]), oneOf(Mapping(required=[type]), Mapping(required=[type]),
    Mapping(required=[type]), Mapping(required=[type, range]), Mapping(required=[type]),
    Mapping(required=[type]), Mapping(required=[type]), not Mapping(required=[]),
    Mapping(required=[type]), Mapping(required=[type]), Mapping(required=[type])))
    """
    _schema = {'$ref': '#/defs/scale'}
    _rootschema = Root._schema

    def __init__(self, name=Undefined, domain=Undefined, domainMax=Undefined, domainMid=Undefined,
                 domainMin=Undefined, domainRaw=Undefined, reverse=Undefined, round=Undefined,
                 type=Undefined, **kwds):
        super(scale, self).__init__(name=name, domain=domain, domainMax=domainMax, domainMid=domainMid,
                                    domainMin=domainMin, domainRaw=domainRaw, reverse=reverse,
                                    round=round, type=type, **kwds)
```

And then defines `scale` again at [line 2246](https://github.com/altair-viz/altair/blob/master/altair/vega/v3/schema/core.py#L2246-L2256):

```python
class scale(VegaSchema):
    """scale schema wrapper

    oneOf(string, oneOf(signal, Mapping(required=[datum]), Mapping(required=[group]),
    Mapping(required=[parent])))
    """
    _schema = {'$ref': '#/refs/scale'}
    _rootschema = Root._schema

    def __init__(self, *args, **kwds):
        super(scale, self).__init__(*args, **kwds)
```

Is there a reason for this? My assumption, which I admit could very well be shortsighted, is that the second class will overwrite the original class and make its inclusion irrelevant. Am I missing something?

**Comment by jakevdp** [comment]
This is because the vega schema uses a nonstandard convention of storing two sets of definitions (``"defs"`` and ``"refs"``). The code generation tool assumes that definitions are stored only in one standard place (``"definitions"``) where there is no possibility for name conflict.

In order to fix this, we'll have to generalize the code generation tools to handle conflicting names within different definition groups.

That hasn't been a priority, because we're not really using the vega wrappers at the moment. But we'll have to figure it out at some point.

**Comment by palewire** [comment]
Alrighty. I believe this is the final obstacle to PyFlakes compliance and being able to add it as a test to the TravisCI routine.

Do you want to hold off on that until you handle this issue, or should I carve out an exception to the PyFlakes routine for this error type?

**Comment by jakevdp** [comment]
Let's do a temporary exception... I think it will be a while before this is addressed. Probably post 2.0 release.

**Comment by binste** [comment]
Closing this issue as the Vega wrappers have been removed in Altair 5
