### ISSUE TITLE
ENH: add a dark theme

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#742]
#740 added theme support along with a few basic themes (default, none, opaque)

It would be useful to add a dark theme: i.e. one with white axes and labels, that would play well with black backgrounds.

**Comment by kanitw** [comment]
These themes seem useful (esp. if someone makes a dark theme) -- so I wonder if it's worth putting these in Vega instead so all users of the Vega ecosystem can benefit from these options.  

cc: @jheer @arvind @domoritz

**Comment by domoritz** [comment]
I like the idea of having a few predefined themes in Vega embed that people could choose from.

**Comment by afonit** [comment]
@jakevdp 
Note - this looks ugly - I know that, just playing with colors and identifying parts of the chart.

I have been trying to put this through its paces to see if I can reach all the attributes.
When I do a faceted chart I can't seem to reach the:
* titles of the facets
* the right most grid line in the facets.

I also can't seem to reach the title's color, I tried putting it both at the top level config, then tried to do it following the hierarchy noted here: https://vega.github.io/vega-lite/docs/title.html#config

See here:
![image](https://user-images.githubusercontent.com/1798497/38615941-5c05ad0a-3d60-11e8-857d-158fa85926f7.png)

```python
import altair as alt
import pandas as pd
alt.theme.register('dark_enhanced', 
                   {'config':
                    {'title': {'color': 'orange'}, #NOT WORKING
                    'axis': {'titleColor': 'orange', #axis titles
                             'domainColor': 'green', #domain color colors the bar on axis labels
                             'gridColor': 'red', #grid color is most of the grid except the right hand side
                             'labelColor': 'orange', #text labels of the axes
                             'tickColor': 'yellow'} #tick marks
                   }}
                  )
alt.theme.enable('dark_enhanced')

from vega_datasets import data

source = data.movies.url

chart = alt.Chart(source).mark_point().encode(
    x='Worldwide_Gross:Q',
    y='US_DVD_Sales:Q',
    column='MPAA_Rating:N'
)
chart
```

**Comment by jakevdp** [comment]
Thanks for looking into this... Maybe one of the Vega-Lite folks can weigh-in.

**Comment by jakevdp** [comment]
Note that ``alt.theme`` has been renamed to ``alt.themes``.

**Comment by domoritz** [comment]
We have created a vega-themes repo with some themes for Vega and Vega-Lite and I think it would be nice to use the same themes in Altair. We can extend the themes offered in vega-themes. Check it out at https://github.com/vega/vega-themes. 

I just sent a PR with some updates and a dark theme: https://github.com/vega/vega-themes/pull/2.

**Comment by domoritz** [comment]
Here is a start of a dark theme: https://github.com/vega/vega-themes/pull/2#issuecomment-381329700. If someone could improve the default data colors, that would be awesome.

**Comment by jakevdp** [comment]
I think in Altair we can support two kinds of themes: named themes that match those in Vega Themes, or custom themes defined within Python.

**Comment by jakevdp** [comment]
We can now use the dark theme from vega-themes:
```python
import altair as alt
from vega_datasets import data
cars = data.cars()

alt.renderers.set_embed_options(theme='dark')

alt.Chart(cars).mark_point().encode(
  x='Horsepower',
  y='Miles_per_Gallon',
  color='Origin'
).interactive()
```
![visualization - 2019-05-27T063004 580](https://user-images.githubusercontent.com/781659/58422981-df11d800-8048-11e9-8ce1-99b93acb406a.png)
