### ISSUE TITLE
example london tube lines not working with `alt.renderers.enable('notebook')`

### ISSUE THREAD

**Issue by mattijn** [altair-viz/altair#747]
Im trying out `altair` examples in `jupyter notebook`. 
It took me some time to figure that I can make the visualization works using `alt.renderers.enable('notebook')`, since this option is not documented in the [Renderer API](https://altair-viz.github.io/user_guide/display.html#renderer-api) section

All examples I tried worked so far, except the example of [London Tube Lines](https://altair-viz.github.io/gallery/london_tube.html). For that one I get the following error:
```

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
c:\python35\lib\site-packages\IPython\core\formatters.py in __call__(self, obj, include, exclude)
    968 
    969             if method is not None:
--> 970                 return method(include=include, exclude=exclude)
    971             return None
    972         else:

c:\python35\lib\site-packages\altair\vegalite\v2\api.py in _repr_mimebundle_(self, include, exclude)
    416             return {}
    417         else:
--> 418             return renderers.get()(dct)
    419 
    420     def repeat(self, row=Undefined, column=Undefined, **kwargs):

c:\python35\lib\site-packages\vega3\vegalite.py in entry_point_renderer(spec)
     19 
     20 def entry_point_renderer(spec):
---> 21     vl = VegaLite(spec)
     22     vl.display()
     23     return {}

c:\python35\lib\site-packages\vega3\base.py in __init__(self, spec, data)
     21         """Initialize the visualization object."""
     22         spec = utils.nested_update(copy.deepcopy(self.DEFAULTS), spec)
---> 23         self.spec = self._prepare_spec(spec, data)
     24 
     25     def _prepare_spec(self, spec, data):

c:\python35\lib\site-packages\vega3\vegalite.py in _prepare_spec(self, spec, data)
     15 
     16     def _prepare_spec(self, spec, data):
---> 17         return prepare_spec(spec, data)
     18 
     19 

c:\python35\lib\site-packages\vega3\utils.py in prepare_spec(spec, data)
     91         # Data is either passed in spec or error
     92         if 'data' not in spec:
---> 93             raise ValueError('No data provided')
     94     else:
     95         # As a last resort try to pass the data to a DataFrame and use it

ValueError: No data provided
``` 

By using;

```
import altair as alt
from vega_datasets import data
alt.renderers.enable('notebook')
```

But the input data contains something

```
print('Boroughs {}\nTubelines {}\n Centroids {}'.format(boroughs, tubelines, centroids))

Boroughs UrlData({
  format: TopoDataFormat({
    feature: 'boroughs',
    type: 'topojson'
  }),
  url: 'https://vega.github.io/vega-datasets/data/londonBoroughs.json'
})
Tubelines UrlData({
  format: TopoDataFormat({
    feature: 'line',
    type: 'topojson'
  }),
  url: 'https://vega.github.io/vega-datasets/data/londonTubeLines.json'
})
 Centroids https://vega.github.io/vega-datasets/data/londonCentroids.json
```

**Comment by jakevdp** [comment]
Sorry about the docs... they're a few weeks old and a lot of recent updates are not yet on the site (I'm hoping to fix that this week).

I think your error is from an old version of the [vega3](https://github.com/vega/ipyvega/tree/vega3/vega3) notebook extension.  Please update to the most recent version (0.6), re-install the notebook extension (see [installation instructions](https://altair-viz.github.io/getting_started/installation.html#installing-altair-with-jupyter-notebook)), then restart the notebook.

Let me know if you have other issues with this!

**Comment by jakevdp** [comment]
Actually, now that I look more closely I see this is a bug in vega3 that I thought had been fixed: it raises an error if you use a layered chart without data at the top level.

**Comment by jakevdp** [comment]
This is what happened: we had a copy of this ``prepare_spec`` code in Altair, and fixed this bug within altair a few months ago. I'd forgotten that the vega3 renderer does its own ``prepare_spec`` process, and that the bug still existed there.

It's fixed in vega3 master, and we'll try to get a release out ASAP. If you use vega3 version 0.6.1 or newer, then this should work.

**Comment by jakevdp** [comment]
If you update to version 0.6.1 of vega3 (``pip install -U vega3``) then this should be fixed.
