### ISSUE TITLE
How to set the axis range on histograms, shared with other subplots?

### ISSUE THREAD

**Issue by mtzl** [altair-viz/altair#754]
Hi, I am trying to make a facetted scatterplot with marginal histograms (similar to the one in https://altair-viz.github.io/user_guide/compound_charts.html?highlight=bin%20scale#horizontal-concatenation), but I can't figure out how to make the scatterplot share its x/y limits with the histograms.

This is what I've got so far:
```python
import altair as alt
from vega_datasets import data

iris = data.iris()

xrange = (3, 9)
yrange = (1, 6)

points = alt.Chart(iris).mark_circle().encode(
    alt.X('sepalLength', scale=alt.Scale(domain=xrange)),
    alt.Y('sepalWidth', scale=alt.Scale(domain=yrange)),
    color='species',
)

top_hist = alt.Chart(iris).mark_area(
    opacity=.4, interpolate='step'
).encode(
    alt.X('sepalLength:Q', 
          bin=alt.Bin(maxbins=20, extent=xrange), 
          stack=None, 
          scale=alt.Scale(domain=xrange),
         ),
    alt.Y('count(*):Q', 
          stack=None, 
         ),
    alt.Color('species:N'),
).properties(height=60)

right_hist = alt.Chart(iris).mark_area(
    opacity=.4, interpolate='step'
).encode(
    alt.Y('sepalWidth:Q', 
          bin=alt.Bin(maxbins=20, extent=yrange), 
          stack=None,
          scale=alt.Scale(domain=yrange),
         ),
    alt.X('count(*):Q', 
          stack=None, 
         ),
    alt.Color('species:N'),
).properties(width=60)

chart = top_hist & (points | right_hist)
```
which yields this (axis limits on the scatterplot are very wide to illustrate the effect better): 
![](https://gist.githubusercontent.com/mtzl/df0ef1a9017a5b577db7d2923b1c12f5/raw/179c2253d7cd6ee2e48890b1c5d5242419f487a1/scatter_marginal_hist.png)

How can I make the marginal histograms share the same x, y axis range `3-9` and `1-6`?

**Comment by jakevdp** [comment]
The spec you used should behave the way you expect, but it does not due to a bug in Vega-Lite: https://github.com/vega/vega-lite/issues/3575

**Comment by mtzl** [comment]
Okay thanks! 

Btw I love how easy this is in altair, compared to seaborn!

**Comment by jakevdp** [comment]
I was just going to ask you about that :smile:

**Comment by jakevdp** [comment]
This is fixed in Altair 3; see e.g. https://altair-viz.github.io/gallery/scatter_marginal_hist.html
