### ISSUE TITLE
API for passing arbitrary statistical functions?

### ISSUE THREAD

**Issue by ashimb9** [altair-viz/altair#761]
As noted in the title, is there a way to pass a stat function name/call which, for instance, can overlay an OLS best-fit line or a lowess curve over a scatterplot? A relevant [example](https://altair-viz.github.io/gallery/poly_fit.html?highlight=polynomial) that I found in the docs (also, see image below) seems to first create a dataframe with the fitted values and then plots it rather than simply passing a function call to the Chart object. Unless I am missing something, please consider this issue as a feature request as it would be a pretty useful feature for users IMO to be able to simply pass a function name/call. Thanks!

![image](https://user-images.githubusercontent.com/22569641/38775807-b08bfdfa-4050-11e8-8f4b-60c6161ae5e7.png)

**Comment by jakevdp** [comment]
Vega-Lite does not contain any way to embed statistical functions, and so Altair does not contain that either.

If you'd like that feature, you could request it in the [vega-lite project](https://github.com/vega/vega-lite)

**Comment by ashimb9** [comment]
Got it. I'll take this over there. Thank you for your response and, of course, for this superb library!

**Comment by ashimb9** [comment]
@jakevdp In case it was of interest to you, the issue has been closed upstream:
> Yes, you are right, we cannot import functions from Python. I think for now the best option is to precompute the data and then pass it to Vega/Vega-Lite.

**Comment by jakevdp** [comment]
Oh, I'd think there would be room in Vega-Lite to add pre-defined common statistical routines to the grammar... that's what I thought you were after here.

But yes, if you're looking to execute arbitrary Python functions within the Altair/Vega-Lite grammar, I don't think that's within the scope of either project.
