### ISSUE TITLE
Charts don't show data in some exemples of the documentation

### ISSUE THREAD

**Issue by francoislauger** [altair-viz/altair#766]
Charts don't show data in some exemples of the documentation in Chrome (65.0.3325.181). It seems to be the ones with data url (i.e. `source = data.github.url)`. For exemple this one : https://altair-viz.github.io/gallery/table_bubble_plot_github.html. It's not working in jupyterlab too. However it's working in vega editor (in Chrome). It's also working in Firefox (59.0.1). I'm under OS X El Capitan (10.11.6)

This is what I see in chrome:
![image](https://user-images.githubusercontent.com/5384977/38950243-e02214b8-4312-11e8-82c9-a2b8d08070b2.png)

**Comment by jakevdp** [comment]
Hmm... I'm on OSX using Chrome 65.0.3325.181 and everything is working perfectly.

Do you see any errors in the Javascript console?

**Comment by francoislauger** [comment]
Oups, it's seems that my AdBlock was blocking the data from https://vega.github.io/vega-datasets/data/github.csv.

**Comment by jakevdp** [comment]
Ah, glad to hear you figured that out.

I may add a note on AdBlock to https://altair-viz.github.io/user_guide/troubleshooting.html... it's come up a couple times for users.
