### ISSUE TITLE
Horizontal Stacked Bar Chart example not showing up

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#773]
At least in my browser. [Take a look for yourself](https://altair-viz.github.io/gallery/horizontal_stacked_bar_chart.html).

![screenshot from 2018-04-24 14-01-07](https://user-images.githubusercontent.com/9993/39214047-10887a7a-47c8-11e8-9453-0d5f17178aad.png)

**Comment by jakevdp** [comment]
I think this is a more general error... see #778. I'll push a fix today.

**Comment by palewire** [comment]
Now working. Thank you.
