### ISSUE TITLE
Are you open to reorganizing the Example Gallery?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#775]
In my humble opinion, [the example gallery](https://altair-viz.github.io/gallery/index.html) -- which I love and see as the most important section of the documentation -- has grown beyond its current structure. 

My proposal: Break it up into sections that are based on chart type.

The "Simple" section at the top, for newbies, could stay in place. It would feature a single, simple example of each chart type, with very little customization and option usage in the altair code.

Following that, the "General" and "Interactive" sections would be removed and their elements reorganized into sections like:

* Bar charts
* Line charts
* Area charts
* Scatterplots
* Histograms
* Maps

My current feeling is that this would provide a more flexible framework for further expanding the examples, and make the page easier to navigate for users. 

If you're interested in this idea, I'd be happy to take the lead in attempting to put together a draft.

**Comment by kanitw** [comment]
I think finer grain taxonomy is useful, but the taxonomy should not omit layered plots and multi-view plots, which is the key benefit of visualization grammars like Altair and Vega-Lite over "chart template" libraries.  

I also just notice that the Vega-Lite gallery is organized a bit differently from Altair.  https://vega.github.io/vega-lite/examples/

There is definitely a room for discussion & improvement and perhaps we can improve the organization of both VL and Altair galleries.

**Comment by kanitw** [comment]
That's true.  One of the thing that I like about the categories in Vega-Lite is that they are quite mutually exclusive.  That said, I wanna split basic into true basic one and another one that's less basic (but can't think of a better name yet.)

**Comment by palewire** [comment]
An excercise that can help think through this kind of challenge is to imagine the "use cases" of the readers we expect to arrive at this page. There are three that occur to me off the top of my head. In no particular order:

1) "Curious chart makers" checking out Altair for the first time, but have never installed it. 
2) "Newbies" who have installed Altair for the first time and are looking to quickly begin experimenting
3) "Regular users" who are looking for reminder or tutorial to answer their question: "How does Altair make chart X?"

To me, each of these cases would be well served by a compact "Basic charts" section at the top of the page, which can serve as quick overview of what's possible. 

Regular users, who I think should be thought of as the most important use case, would be best served, IMHO, by a taxonomy that allows them quickly find the type of chart they're interested in making. Then they can narrow down and scan pick through all the variations for that chart to find the one they're interested in mimicking. These users are not served as well by the current hodge podge of charts.

That said, I wouldn't want to the top of the page to be dominated by rudimentary charts, which could fail to impress the "curious chart makers" we want to wow with demonstrations of Altairs abilities. I believe that they could be satisfied, however, if no chart type section grows too large and each is filled with an impressive set of examples that stretch far beyond the basics.

**Comment by kanitw** [comment]
>  I wouldn't want to the top of the page to be dominated by rudimentary charts, which could fail to impress the "curious chart makers" we want to wow with demonstrations of Altair's abilities.

That's why both https://altair-viz.github.io/ and http://vega.github.io/vega-lite have the gallery on the home page, to show that there are sophisticated examples.

**Comment by palewire** [comment]
If you're happy with the homepage display of the charts intended to impress, I think that creates an even strong case for a more functional approach to categorizing and listing items in the example gallery.

If you all are open to my idea at the top of this thread, I can take a stab at a draft and file a pull request.

**Comment by jakevdp** [comment]
Sure, it would be great if you could tackle this!
