### ISSUE TITLE
Fix vega-embed version for Altair 1

### ISSUE THREAD

**Issue by domoritz** [altair-viz/altair#777]
For example in https://github.com/altair-viz/altair/blob/d4d29ca06e920f71073766c6456d387e682cee17/altair/vegalite/v1/html.py#L7

**Comment by jakevdp** [comment]
What version of vega-embed should we use with vega-lite 1.0 and vega 2.0?

**Comment by domoritz** [comment]
I think embed@2. I'm surprised that embed@3 works.

**Comment by jakevdp** [comment]
It probably doesn't... we don't actually test this anywhere :smile:
