### ISSUE TITLE
facet on a binned field

### ISSUE THREAD

**Issue by enningb** [altair-viz/altair#780]
Hi, 
I'm trying to do a facet on binned data. This results in a faceted chart but the're all the same. Am I missing something or is this simply not possible?

Here's the code:

```python
import altair as alt
from vega_datasets import data
population = data.population.url

alt.Chart().mark_bar().encode(
      x = alt.X('year:Q', bin=True)
    , y = 'count(year:Q)'
).facet(data=population
       , column='sex:N')
```

**Comment by jakevdp** [comment]
There's a small typo in your specification: ``count(year:Q)`` should be ``count(year):Q``

Other than that, it's working correctly. The reason it looks like it's not splitting the dataset is that there are roughly equal numbers of men and women in any given year. This is more clear if you color by sex as well:

```python
import altair as alt
from vega_datasets import data
population = data.population.url

alt.Chart().mark_bar().encode(
    x = alt.X('year:Q', bin=True),
    y = 'count(year):Q',
    color='sex:N'
).facet(data=population, column='sex:N')
```
![visualization 5](https://user-images.githubusercontent.com/781659/39271736-b404b5bc-488e-11e8-8b60-cc4d2d10d0e5.png)

**Comment by jakevdp** [comment]
Actually, another problem: when you do ``count(year):Q``, you are counting the number of years in any given bin, which will actually be identical when dividing across gender. I suspect what you're actually going for is the sum the population within each year:
```python
import altair as alt
from vega_datasets import data
population = data.population.url

alt.Chart().mark_bar().encode(
    x = alt.X('year:Q', bin=True),
    y = 'sum(people):Q',
    color='sex:N'
).facet(data=population, column='sex:N')
```
![visualization 6](https://user-images.githubusercontent.com/781659/39271879-247f548c-488f-11e8-8921-480efeaea077.png)

**Comment by enningb** [comment]
Thanks for your answers! Your remark on the typo put me on the right track!
