### ISSUE TITLE
axisRight & log scale

### ISSUE THREAD

**Issue by Jackalope2K17** [altair-viz/altair#790]
Please, could you provide an example where the plot has the Y axis on the right side of the plot, and another with log scale on Y axis? I tried multiple times to do both but never got any result.

I have been trying among other solutions:
`alt.Y('column', scale=alt.Scale(base=10))` for the log scale
&
`.configure(axisRight)` for the Y axis on the right side of the plot

**Comment by kanitw** [comment]
I think `alt.Y('column', scale=alt.Scale(base=10), axis=alt.Axis(orient='right'))` should work?

**Comment by Jackalope2K17** [comment]
Thanks!
It works for moving the Y axis on the right side of the plot, but not for the log scale. 
I already tried that solution, and I do not even get any error. The plot is done but does not care about the scale.

**Comment by pagpires** [comment]
You should use specify `type` in `scale`:  `scale=alt.Scale(type='log', ....)` and it will work

**Comment by Jackalope2K17** [comment]
Brilliant, thank you, it works!
but now I get an unexpected spike in the plot, totally unrelated to the data, as you can see by the pic and this lines from the Vega editor (plotting the same data with no log scale does not make that spike):
{"years": "1830", "P_expenditure": 52},
      {"years": "1831", "P_expenditure": 51},
      {"years": "1832", "P_expenditure": 51},
      {"years": "1833", "P_expenditure": 49},
      {"years": "1834", "P_expenditure": 49},
      {"years": "1835", "P_expenditure": 48},
      {"years": "1836", "P_expenditure": 50},
      {"years": "1837", "P_expenditure": 51},
      {"years": "1838", "P_expenditure": 52},
      {"years": "1839", "P_expenditure": 53},
      {"years": "1840", "P_expenditure": 53},
![selection_092](https://user-images.githubusercontent.com/26098527/39470403-6b1e0668-4d35-11e8-8909-1e3a9c529f71.png)

**Comment by Jackalope2K17** [comment]
Thanks, this is the code:
`t = alt.Chart(expen).mark_line().encode(
    alt.X('years',timeUnit='year', axis=alt.Axis(title='')),
    alt.Y('P_expenditure', scale=alt.Scale(type='log', base=10), axis=alt.Axis(orient='right')),
    size=alt.value(4)).properties(width=800)

t`
sadly, I had to use matplotlib to be sure the original data are doing right ...no weird spike there

**Comment by jakevdp** [comment]
Could you share what ``expen`` is so we can try to figure out whether there is a bug? Thanks.

**Comment by jakevdp** [comment]
Most useful would be a single block of code, including data and imports, that we could copy and paste to reproduce exactly what you're seeing.

**Comment by Jackalope2K17** [comment]
expen is a panda df, out of a 2 column csv file

here is the the code:

`import altair as alt
alt.renderers.enable('notebook')`

`import pandas as pd`

`expen = pd.read_csv('economic data/mitchell/expeditures.csv')
expen['years'] = pd.to_datetime(expen['years'], format = '%Y')`

`t = alt.Chart(expen).mark_line().encode(
    alt.X('years',timeUnit='year', axis=alt.Axis(title='')),
    alt.Y('P_expenditure', scale=alt.Scale(type='log', base=10), axis=alt.Axis(orient='right')),
    size=alt.value(4)).properties(width=800)`

`t`

**Comment by pagpires** [comment]
It will be important to show some of the data.. If that's not possible, maybe you can try mark_point/mark_circle to see if it's different; or use years:O and turn off timeUnit. Because given your data and code, I didn't see the spike you mentioned.

**Comment by Jackalope2K17** [comment]
It is not possible to upload csv...
however, the data are just these:

years | P_expenditure
1800 | 63
1801 | 65
1802 | 55
1803 | 53
1804 | 63
1805 | 71
1806 | 73
1807 | 73
1808 | 78
1809 | 82
1810 | 82
1811 | 87
1812 | 95
1813 | 111
1814 | 113
1815 | 99
1816 | 71
1817 | 59
1818 | 58
1819 | 58
1820 | 58
1821 | 58
1822 | 56
1823 | 54
1824 | 55
1825 | 54
1826 | 56
1827 | 56
1828 | 53
1829 | 54
1830 | 52
1831 | 51
1832 | 51
1833 | 49
1834 | 49
1835 | 48
1836 | 50
1837 | 51
1838 | 52
1839 | 53
1840 | 53
1841 | 54
1842 | 55
1843 | 55
1844 | 55
1845 | 54
1846 | 55
1847 | 59
1848 | 59
1849 | 55
1850 | 55
1851 | 54
1852 | 55
1853 | 56
1854 | 83
1855 | 93
1856 | 76
1857 | 68
1858 | 65
1859 | 70
1860 | 73
1861 | 72
1862 | 70
1863 | 68
1864 | 67
1865 | 66
1866 | 67
1867 | 72
1868 | 75
1869 | 67
1870 | 68
1871 | 70
1872 | 69
1873 | 75
1874 | 73
1875 | 75
1876 | 76
1877 | 80
1878 | 83
1879 | 82
1880 | 81
1881 | 83
1882 | 87
1883 | 85
1884 | 89
1885 | 92
1886 | 90
1887 | 87
1888 | 87
1889 | 91
1890 | 93
1891 | 96
1892 | 96
1893 | 98
1894 | 101
1895 | 105
1896 | 110
1897 | 112
1898 | 118
1899 | 144
1900 | 193
1901 | 205
1902 | 194
1903 | 155
1904 | 150
1905 | 147
1906 | 144
1907 | 143
1908 | 145
1909 | 157
1910 | 168
1911 | 174
1912 | 184
1913 | 192
1914 | 559
1915 | 1559
1916 | 2198
1917 | 2696
1918 | 2579
1919 | 1666
1920 | 1188
1921 | 1070
1922 | 812
1923 | 749
1924 | 751
1925 | 776
1926 | 782
1927 | 774
1928 | 761
1929 | 782
1930 | 814
1931 | 819
1932 | 833
1833 | 770
1934 | 785
1935 | 829
1936 | 889
1937 | 909
1938 | 1006
1939 | 1401
1940 | 3954
1941 | 4876
1942 | 5726
1943 | 5899
1944 | 6174
1945 | 5592
1946 | 4192
1947 | 3354
1948 | 3314
1949 | 3531
1950 | 3417

**Comment by Jackalope2K17** [comment]
with mark_point/mark_circle the spike remains...
and even with a code as simple as that:

`t = alt.Chart(expen).mark_line().encode(
    alt.X('years'),
    alt.Y('P_expenditure'),
    )`

`t`

**Comment by jakevdp** [comment]
I think the issue is in your data:
```
1932 | 833
1833 | 770
1934 | 785
```
Altair is plotting exactly the data you give it. One point of potential confusion: for a line plot, Altair sorts the x-axis values before plotting, which is why this manifests as a vertical spike rather than a diagonal spike, as it matplotlib.

**Comment by jakevdp** [comment]
For future reference, a single code-block that reproduces your plot would be very helpful. It may take a bit of work (but not too much) to put together something like this:
```python
import altair as alt
import pandas as pd

years = [1800, 1801, 1802, 1803, 1804, 1805, 1806, 1807, 1808, 1809, 1810, 1811,
         1812, 1813, 1814, 1815, 1816, 1817, 1818, 1819, 1820, 1821, 1822, 1823,
         1824, 1825, 1826, 1827, 1828, 1829, 1830, 1831, 1832, 1833, 1834, 1835, 
         1836, 1837, 1838, 1839, 1840, 1841, 1842, 1843, 1844, 1845, 1846, 1847, 
         1848, 1849, 1850, 1851, 1852, 1853, 1854, 1855, 1856, 1857, 1858, 1859, 
         1860, 1861, 1862, 1863, 1864, 1865, 1866, 1867, 1868, 1869, 1870, 1871, 
         1872, 1873, 1874, 1875, 1876, 1877, 1878, 1879, 1880, 1881, 1882, 1883, 
         1884, 1885, 1886, 1887, 1888, 1889, 1890, 1891, 1892, 1893, 1894, 1895, 
         1896, 1897, 1898, 1899, 1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 
         1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 
         1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 
         1932, 1833, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 
         1944, 1945, 1946, 1947, 1948, 1949, 1950]
expenditure = [63, 65, 55, 53, 63, 71, 73, 73, 78, 82, 82, 87, 95, 111, 113, 99, 71, 
               59, 58, 58, 58, 58, 56, 54, 55, 54, 56, 56, 53, 54, 52, 51, 51, 49, 49, 
               48, 50, 51, 52, 53, 53, 54, 55, 55, 55, 54, 55, 59, 59, 55, 55, 54, 55, 
               56, 83, 93, 76, 68, 65, 70, 73, 72, 70, 68, 67, 66, 67, 72, 75, 67, 68, 
               70, 69, 75, 73, 75, 76, 80, 83, 82, 81, 83, 87, 85, 89, 92, 90, 87, 87, 
               91, 93, 96, 96, 98, 101, 105, 110, 112, 118, 144, 193, 205, 194, 155, 
               150, 147, 144, 143, 145, 157, 168, 174, 184, 192, 559, 1559, 2198, 2696, 
               2579, 1666, 1188, 1070, 812, 749, 751, 776, 782, 774, 761, 782, 814, 819, 
               833, 770, 785, 829, 889, 909, 1006, 1401, 3954, 4876, 5726, 5899, 6174, 
               5592, 4192, 3354, 3314, 3531, 3417]

expen = pd.DataFrame({'years': years, 'P_expenditure': expenditure})

# Convert years to string, because vega-lite interprets integers
# as unix timestamps when converting them to dates.
expen['years'] = expen['years'].astype(str)


alt.Chart(expen).mark_line().encode(
    alt.X('years:T', timeUnit='year', axis=alt.Axis(title='')),
    alt.Y('P_expenditure', scale=alt.Scale(type='log', base=10), axis=alt.Axis(orient='right')),
    size=alt.value(4)
).properties(
    width=800
)
```
![visualization 11](https://user-images.githubusercontent.com/781659/39488677-d5212e4e-4d37-11e8-9ea3-301f5a499076.png)

**Comment by Jackalope2K17** [comment]
OMG! thank you everybody!
great to have your help

**Comment by jakevdp** [comment]
And here's info on formatting and highlighting blocks of code in github, in case it comes up again: https://help.github.com/articles/creating-and-highlighting-code-blocks/

Cheers!

**Comment by Jackalope2K17** [comment]
and shame on matplotlib which swept the data error under the carpet ;)
