### ISSUE TITLE
DOC: Broken Links on configuration.html page

### ISSUE THREAD

**Issue by chris1610** [altair-viz/altair#791]
The majority of the links on https://altair-viz.github.io/user_guide/configuration.html that point to other places in the user_guide are broken. For example, here's a subset:
- https://altair-viz.github.io/user_guide/axis.html#config
- https://altair-viz.github.io/user_guide/legend.html#config
- https://altair-viz.github.io/user_guide/mark.html#config

If you are already tracking this, somewhere else, you can close this out but I did not see a ticket on this topic so want to make sure everyone's aware before the next release.

**Comment by jakevdp** [comment]
Thanks!

**Comment by jakevdp** [comment]
So looking closer at this, it's going to be quite difficult to fix.

These links come directly from the source code, which is generated directly from the vega-lite schema, which has a bunch of hyperlinks that basically assume they will be rendered within the HTML tree of the vega documentation (see https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/schema/vega-lite-schema.json#L1579)

Fixing this would require parsing all the docstrings, finding hyperlinks, and adding the appropriate URL context (e.g. a prefix like http://vega.github.io/vega-lite/ )

Even removing the offending links would require parsing the markdown source to remove them.

I'm just not sure how to best approach fixing this.

**Comment by jakevdp** [comment]
Another option would be to restructure Altair's documentation to mirror the structure of vega-lite's documentation, so that these relative URLs will point to the right place.

**Comment by jakevdp** [comment]
These now go to the correct location in the vega-lite docs.
