### ISSUE TITLE
NO viz when using headless renderer with JSON data transformer

### ISSUE THREAD

**Issue by pagpires** [altair-viz/altair#792]
When using 
```python  
alt.renderers.enable('png')  # or alt.renderers.enable('svg') 
alt.data_transformers.enable('json')
```
The viz is empty in the notebook in jupyterlab. Using `default` in either renderer or data_transformer behaves correct. Seems something wrong with the utils.headless (not sure)?

**Comment by jakevdp** [comment]
Yes, I would not expect this to work. The json data transformer is meant for live renderers.

**Comment by pagpires** [comment]
Thanks. So what might be the best practice if we want to plot large dataset in svg/png in the notebook (for data security reason or simply want to turn off the 3 buttons in the vega-based plot)?

**Comment by jakevdp** [comment]
Oh, I see... that's an issue.

As soon as #776 is merged you'll be able to do
```
alt.data_transformers.enable('default', max_rows=None)
```
and it will work.

We should make the headless renderers use that automatically... the max rows error is intended for the live rendering use-case.

**Comment by pagpires** [comment]
Thanks, that will be great. Right now it can be done via setting an arbitrary number:
```python
alt.data_transformers.register('no_limit', lambda data: alt.pipe(data, alt.limit_rows(max_rows=1000000), alt.to_values))
alt.data_transformers.enable('no_limit')
alt.renderers.enable('svg')
```
Just one more thing (not very related): the bottom of the guide in data transformers (https://altair-viz.github.io/user_guide/data_transformers.html) it not correct. I think it should be 
```python
alt.data_transformers.register('s3', lambda data: pipe(data, sample, to_s3('mybucket'))) # not pipe(sample, to_s3('mybucket'))
alt.data_transformers.enable('s3')
```
