### ISSUE TITLE
Format auto-generated code with black?

### ISSUE THREAD

**Issue by jakevdp** [altair-viz/altair#793]
Should we format auto-generated code with [black](https://github.com/ambv/black)? Maybe...

I tried it out, and the main effect is to change single quotes to double quotes, and to make long parameter lists have one parameter per line.

Other detail: it doesn't do any formatting within doc strings, which is one thing I was hoping to be able to fix...

**Comment by jploudre** [comment]
Using a code formatted like black effectively enforces a community coding standard. Reduces variability for new coders. I’ve been using for my stuff lately and it seems like it reduces my cognitive load. Less time tweaking because black will eventually make it consistent.

**Comment by jakevdp** [comment]
I've looked into this and it looks like black is not well-suited to the large numbers of parameters that many altair classes have.
