### ISSUE TITLE
Wrong time format when setting timeUnit in transform_timeunit()

### ISSUE THREAD

**Issue by pagpires** [altair-viz/altair#797]
This is inspired by the last example in this section (https://altair-viz.github.io/user_guide/transform.html#timeunit-within-encoding): I simply want to switch the timeunit from encoding to transformation:
```python
alt.Chart(temps).mark_rect().encode(
    x=alt.X('date_date:O', axis=alt.Axis(format='%d')),
    y=alt.Y('date_month:O', axis=alt.Axis(format='%b')),
    color='max(temp):Q'
).transform_timeunit(
    'date_date', field='date', timeUnit='date'
).transform_timeunit(
    'date_month', field='date', timeUnit='month'
)
```
And I didn't get the correct axis format:
![image](https://user-images.githubusercontent.com/7856031/39445661-c9eb4b4e-4c89-11e8-9a3d-086783ca9db3.png)

If I change the date type from O to T, like:
```python
alt.Chart(temps_url).mark_rect().encode(
    x=alt.X('date_date:T', axis=alt.Axis(format='%d')), # the modified line
    y=alt.Y('date_month:O', axis=alt.Axis(format='%b')),
    color='max(temp):Q'
).transform_timeunit(
    'date_date', field='date', timeUnit='date'
).transform_timeunit(
    'date_month', field='date', timeUnit='month'
)
```
 then the axis format is correct, but somehow the plot became 'not discrete':
![image](https://user-images.githubusercontent.com/7856031/39445771-236d5c0c-4c8a-11e8-830b-ff8a582e4d01.png)

**Comment by jakevdp** [comment]
I ran into similar things and opened a vega-lite issue: https://github.com/vega/vega-lite/issues/3594

This falls into the category of "intended but inconvenient" behavior, I think... I'd suggest not using ``transform_timeunit()``, but rather using the ``timeUnit`` argument to ``alt.X`` and ``alt.Y``. In that case, the encoding knows about the transform and formats labels accordingly.

**Comment by jakevdp** [comment]
There's also a note about this in the vega-lite docs for timeunit transforms: https://vega.github.io/vega-lite/docs/timeunit.html#transform

**Comment by pagpires** [comment]
Great, thanks a lot!
