### ISSUE TITLE
Multiple fields in the tooltip channel

### ISSUE THREAD

**Issue by timtylin** [altair-viz/altair#803]
I came upon a use case today where the simplest solution is to be able to show values of different fields in the default tooltip provided by the tooltip channel. In the Vega-lite schema this seems easy enough by just specifying a list in the `encoding.tooltip` key (https://vega.github.io/vega-lite/docs/tooltip.html), but I couldn't figure out how to replicate this using Altair. Is it possible at this point?

**Comment by jakevdp** [comment]
Hi – the tooltip story in Altair is not well-developed yet, but we're working on it!

The example you link to makes use of the Vega-Tooltip library, which is not currently supported by any of the available Altair renderers. As of a few days ago, that tooltip functionality has been rolled-in to Vega-Embed. Our plan is to make these sorts of multiple tooltips available soon as we can depend on the frontends supporting it, but for the time being they are not.
