### ISSUE TITLE
Selection binder does not filter until value changes

### ISSUE THREAD

**Issue by gschivley** [altair-viz/altair#807]
Filters based on `binding` functions don't do anything until the value is changed. This is apparent from the [US population over time](https://altair-viz.github.io/gallery/us_population_over_time.html) example.

On page load:
![image](https://user-images.githubusercontent.com/10373332/39581778-58925888-4eba-11e8-9d05-63447a89689a.png)

The year shows up below the slider once it is moved. After changing value to 1960 and back to 1950:
![image](https://user-images.githubusercontent.com/10373332/39581833-7df38dfe-4eba-11e8-8562-53552c986f6e.png)

This is a bigger issue for `binding_select` dropdowns, where a value is shown but not applied to the filter.

```Python
import altair as alt
from vega_datasets import data

cars = data.cars.url

binder = alt.binding_select(options=["Europe", "Japan", "USA"])
org = alt.selection_single(name="org", fields=['Origin'], bind=binder, empty='all')

alt.Chart(cars).mark_point().encode(
    x='Horsepower:Q',
    y='Miles_per_Gallon:Q',
    color=alt.condition(org, 'Cylinders:O', alt.ColorValue('gray'))
).properties(
    selection=org
)
```
On chart load:
![image](https://user-images.githubusercontent.com/10373332/39583004-2399cc44-4ebd-11e8-972a-487c6ccbb56c.png)

Directly selecting "Europe" doesn't change anything. Selecting a different value and then "Europe" filters the data.
![image](https://user-images.githubusercontent.com/10373332/39583040-38e1b800-4ebd-11e8-9015-4c16408b4743.png)

When `binding_radio` is used in place of `binding_select` no selection is shown on load. All data are selected though because the default value for `empty` in `selection_single` is `all`.
![image](https://user-images.githubusercontent.com/10373332/39583080-4aa208b0-4ebd-11e8-958f-abb04f7c6b40.png)

I tried to see what the behavior is for `binding_checkbox`, assuming that I could pass a list to `options` and use  `selection_multi` but kept getting errors. I can't find any vega-lite or vega examples with checkboxes either.

**Comment by jakevdp** [comment]
Thanks for the report! This is a known bug in vega-lite, which we're tracking in #599
