### ISSUE TITLE
Scatter plot qualitative labels

### ISSUE THREAD

**Issue by hugo-pires** [altair-viz/altair#821]
Hello

Is it possible to add a list-like label value to scatter plot? It would be specially interest to show PCA or cluster analysis results.

Thank you

**Comment by hugo-pires** [comment]
Some qualitative data like `['item1','item2','item3']`

**Comment by jakevdp** [comment]
Yes, Altair supports that. Here is an example with the iris dataset: https://altair-viz.github.io/gallery/simple_scatter.html

**Comment by pagpires** [comment]
I guess the questions is whether we can feed a custom list as the label for the axis? (something like the matplotlib function `.set_xticklabels()`? I am also having this question...

**Comment by jakevdp** [comment]
If your data consists of strings rather than numbers, then the axis will automatically be labeled with the appropriate strings.

For example:
```python
import altair as alt
from vega_datasets import data

cars = data.cars()

alt.Chart(cars).mark_tick().encode(
    y='Origin',
    x='Horsepower'
)
```
![visualization 15](https://user-images.githubusercontent.com/781659/39738117-0fd4c3f6-523e-11e8-936c-3ac66f6a1386.png)

Does that answer your question?

**Comment by pagpires** [comment]
Probably didn't explain myself clearly.. I am just wondering if it's possible to manually set tick labels. Some use cases are: plotting based on  a 'day_of_week' with values of [0,1,2,3,4,5,6] and just want to arbitrarily set the tick to ['Mon','Tue','Wed',...]. OR, plotting based on some numbers like 0, 10, 20 and want to set the tick labels as 'zero', 'ten', 'twenty'.. Is it possible to achieve by feeding the label list?

**Comment by jakevdp** [comment]
Oh, I see.

No, to my knowledge Altair does not provide a way to set x tick labels directly. To do so would be kind of against the spirit of the API... by design, the labels will reflect the data, so if you want to change the labels, you should change the data.

You can do this either externally (by, e.g. adding a column in the pandas dataframe) or within the chart itself, using a ``transform_calculate()`` to map input data values onto the values you'd like to plot.on the data within the chart to map inputs to outputs.

One example of the latter approach is here, where the 1/2 values are mapped to "Male"/"Female" for use in the plot: https://altair-viz.github.io/gallery/layered_bar_chart.html

**Comment by hugo-pires** [comment]
Thank you. My question was about labeling the points directly on the scatter plot.

**Comment by jakevdp** [comment]
Can you give an example of what you mean by "labeling the points directly on the scatter plot"? I'm still not clear about what you're trying to do.

**Comment by hugo-pires** [comment]
Thank you. This image will help:

![gdp-vs-religion](https://user-images.githubusercontent.com/7768784/39757842-f52669fa-52c5-11e8-8b00-cdb02699175a.png)

**Comment by hugo-pires** [comment]
I am sorry. I should have done a resize

**Comment by jakevdp** [comment]
Oh, I see. The best way to do that would be to add a layer with a text mark. For example:
```python
data = pd.DataFrame({'x': [1, 3, 2, 5, 4],
                     'y': [2, 6, 5, 1, 1],
                     'label': ['A', 'B', 'C', 'D', 'E']})

base = alt.Chart(data).encode(
    x='x',
    y='y',
    text='label'
)

base.mark_point() + base.mark_text(dx=10, dy=5)
```
![visualization 16](https://user-images.githubusercontent.com/781659/39759410-7615cfc2-5287-11e8-92cf-27db4c904ad8.png)

**Comment by hugo-pires** [comment]
Muito obrigado.
