### ISSUE TITLE
facet_wrap in altair?

### ISSUE THREAD

**Issue by smsaladi** [altair-viz/altair#824]
I'd like to suggest the equivalent of ggplot2's [facet_wrap](http://www.cookbook-r.com/Graphs/Facets_(ggplot2)/#facetwrap) in altair.

Right now, it's possible to have facets plot in a single column (`.facet(row`) or in a single column (`.facet(column`), or even as a grid, but often, it's useful to just lay out a ribbon of charts one after another (not necessarily mapping a column or row to variables in the data frame) using more than one column/row. In other words, those that line up in a single column/row don't mean anything in particular.

I asked this question on SO first to see if there was already a way to do this in altair, but it seems rather involved (i.e. not as slick as `facet_wrap`):

https://stackoverflow.com/a/50166485/2320823

**Comment by kanitw** [comment]
This is in the roadmap for Vega-LIte https://github.com/vega/vega-lite/issues/393

**Comment by 1wheel** [comment]
FYI, vega-lite has added facet wrap: https://github.com/vega/vega-lite/pull/4541

**Comment by jakevdp** [comment]
> FYI, vega-lite has added facet wrap: vega/vega-lite#4541

It will be part of the 3.0 release. Once that is out, we'll make an Altair 3.0 release that will include facet wrap.

**Comment by jakevdp** [comment]
This is now part of Altair as of version 3.0. For example:
```python
import altair as alt
from vega_datasets import data

source = data.population.url

alt.Chart(source).mark_area().encode(
    x='age:O',
    y=alt.Y('sum(people):Q', title='Population'),
    facet='year:O'
).properties(
    columns=5,
    width=100,
    height=80
)
```
![visualization - 2019-05-29T201526 047](https://user-images.githubusercontent.com/781659/58605945-80b64680-824e-11e9-81f4-30eebb286ccf.png)

**Comment by odoublewen** [comment]
@jakevdp Thank you for your worked example.  I'm using the recent Altair 4.0.0 release, for which the above example throws the following error:

```
altair.utils.schemapi.SchemaValidationError: Invalid specification
        altair.vegalite.v4.api.Chart, validating 'additionalProperties'
        Additional properties are not allowed ('columns' was unexpected)
```

Is there a new way to accomplish this?

**Comment by jakevdp** [comment]
Yes, the error is due to the one of the changes listed in the [changelog(https://github.com/altair-viz/altair/releases/tag/v4.0.0); ``columns`` has to be specified in the facet encoding itself. I've updated the example above.

**Comment by jakevdp** [comment]
You can see an example in the docs here: https://altair-viz.github.io/gallery/us_population_over_time_facet.html
