### ISSUE TITLE
Transform filter from selection of temporal data is empty

### ISSUE THREAD

**Issue by gschivley** [altair-viz/altair#828]
I'm trying to use `selection_interval` to show a histogram of values selected from a scatterplot. This works fine with quantitative data but fails with temporal data that has not been transformed.

```Python
import altair as alt
import pandas as pd
import numpy as np

# Make dataframe from datetimes, random values, and sequential counts
dates = pd.date_range(start='1-1-2017-01', periods=200, freq='H')
values = np.random.randint(0, 20, size=200)
count = range(len(dates))

data = pd.DataFrame({'dt': dates, 'values': values, 'count': count})

brush = alt.selection_interval(encodings=['x'])

points = alt.Chart(data).mark_point().encode(
# Unmodified datetime, counts, and transformed datatime data for the x-axis
    x='dt:T',
#     x='count:Q',
#     x=alt.X('dt:T', timeUnit='yearmonthdatehours', axis=alt.Axis(title='Transformed dt')),
    y='values:Q',
).properties(
    selection=brush
)

bars = alt.Chart(data).mark_bar().encode(
    x='values:Q',
    y='count()'
).transform_filter(
    brush.ref()
)

points | bars
```
Initial plot with temporal `dt` on the x-axis
![image](https://user-images.githubusercontent.com/10373332/39872726-e6240f76-5436-11e8-8551-0219140edb29.png)

Empty bar chart/histogram when I select data in the scatterplot
![image](https://user-images.githubusercontent.com/10373332/39872747-f56a33d4-5436-11e8-8f9f-1e87f7cd771e.png)

Works fine with quantitative `counts` on the x-axis
![image](https://user-images.githubusercontent.com/10373332/39872897-70cabea4-5437-11e8-9875-98e43ad7cdd8.png)

Also works when `dt` is transformed
![image](https://user-images.githubusercontent.com/10373332/39873005-c71073b2-5437-11e8-883f-f15d1f545789.png)

**Comment by jakevdp** [comment]
Looks like it may be a Vega-Lite issue... I've started a discussion in https://github.com/vega/vega-lite/issues/3737

**Comment by gschivley** [comment]
Thanks. For issues that are possible Vega-Lite should I keep reporting them here, in both, or just there?

**Comment by jakevdp** [comment]
It's up to you: free to just report issues here. I'm happy to echo them upstream where it's appropriate.

**Comment by jakevdp** [comment]
From  vega/vega-lite#3737, it sounds like this is due to a bug in vega-lite, and the recommended workaround is to use the ``timeUnit`` transform approach that you mentioned above.

**Comment by jakevdp** [comment]
Update: still broken in Altair 3.0/Vega-Lite 3.2

**Comment by joelostblom** [comment]
@gschivley I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved in the latest version of Altair so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
