### ISSUE TITLE
Interactive chart not working in jupyterlab

### ISSUE THREAD

**Issue by extraymond** [altair-viz/altair#834]
Hi! I'm trying to use altair in jupyterlab, and the interactive() is not working as expected.

I'm tried altair from both conda-forge and pypi, all ends up in the same result.

This is the error log in the browser console.

```javascript
TypeError: "t._renderer.scene is not a function"
```

**Comment by extraymond** [comment]
Thx for your reply! I've successfully run interactive with a new conda env.

However if I uninstall jupyterlab from a existing conda env and install it again, it will still emit the same error. I'm wondering if there are any cache involved into this issue?

**Comment by jakevdp** [comment]
Maybe... @ellisonbg might know the details.

You might try running ``jupyter labextension install @jupyterlab/vega3-extension`` to force the extension to update (note that this requires nodejs)

**Comment by jakevdp** [comment]
Actually, this looks like exactly the problem that I hit on my own computer in the middle of the tutorial at PyCon. I've tried uninstalling and installing JupyterLab, uninstalling, installing, and re-building the vega3 jupyterlab extension, but have not been able to get interactions to work again in that conda environment.

**Comment by extraymond** [comment]
Ha! I found this during following your pycon video, it was 100% awesome until interactive is not active, still 99% awesome though.

I found that after uninstall and reinstall not only jupyterlab but all the jupyter related package it works.

**Comment by extraymond** [comment]
After further investigation (install and uninstall actually...)

Another potential culprit is multiple nodejs installed.
Since conda have their own nodejs package, if it is not installed but a system-wide nodejs is installed by either os package manager or other package manager (in my case the snap package), the above problem occurs.

It's not happening if I have nodejs installed from conda though.
It seems that jupyterlab (installed from conda) is able to use nodejs outside of conda to build its extension, a miss-match of nodejs version might be the root cause.

**Comment by afonit** [comment]
not sure if this is related - but when using jupyterlab and installing the jupyterlab-manager to install extensions, it does kill the interactivity of plots.

I filed a ticket in their repo three days ago when I ran into this.

https://github.com/jupyter-widgets/ipywidgets/issues/2071
