### ISSUE TITLE
Faceting: Manual approach != keyword approach

### ISSUE THREAD

**Issue by lsternlicht** [altair-viz/altair#835]
Example page: https://altair-viz.github.io/user_guide/compound_charts.html#faceted-charts 

Unlike the keyword faceting example, the manual faceting example using filter transform:

1.  does not yield results with title "Species" above the three charts 
2. and the individual subplots do not contain the respective species title

Is there a manual way to add a suptitle (e.g. "species") and the respective titles to each of the three subplots (e.g. "setosa", "versicolor", and "virginica")?

![manual](https://user-images.githubusercontent.com/128432/40003230-c7b91efa-5760-11e8-8f79-fa6f03f35724.png)

![keyword](https://user-images.githubusercontent.com/128432/40003220-c24942d8-5760-11e8-852c-5b560015fb1d.png)

**Comment by jakevdp** [comment]
Looks like this addressed your question – feel free to reopen if you have other related issues.
