### ISSUE TITLE
Chart not displaying with nbextensions

### ISSUE THREAD

**Issue by pylang** [altair-viz/altair#837]
The [`nbextensions`][0] package appears to conflict with displaying charts build with Altair.

Result

Nothing is rendered in the output:

![2018-05-14 16_46_03-altair](https://user-images.githubusercontent.com/10778668/40022623-87e708e2-5796-11e8-9376-6f88b4d6d862.png)

Error

From the chrome console:
 
![2018-05-14 16_45_39-altair](https://user-images.githubusercontent.com/10778668/40022626-896fded2-5796-11e8-8517-5dc87acf1bb8.png)

Observations

- This is a fresh install of the latest Anaconda (5.1) and brand new kernels. 
- I resolved common warnings using the [troubleshooting guide](https://altair-viz.github.io/user_guide/troubleshooting.html#display-troubleshooting).
- The chart works fine on Jupyterlab.
- `vega3` appears to attempt to load from an nbextensions path.  

I expect these dependencies should work independently, but perhaps something js related is going on.

System

![2018-05-14 17_04_39-altair](https://user-images.githubusercontent.com/10778668/40023388-f2682d02-5798-11e8-96c5-2089c71fea88.png)

  [0]: https://github.com/ipython-contrib/jupyter_contrib_nbextensions

**Comment by jakevdp** [comment]
Did you install the vega3 package?

**Comment by pylang** [comment]
Yes, I have installed:


```
>>> conda list
...
vega3                     0.13.0                   py36_0    conda-forge
...
```

**Comment by jakevdp** [comment]
Ping @ellisonbg - I'm not certain what's going on here.

@pylang, in the meantime, I'd suggest using JupyterLab. It has a newer and better-designed API for the kinds of extensions that Altair needs in order to display plots.

**Comment by pylang** [comment]
@jakevdp  Yes.  I'm using JupyterLab to review your PyCon Tutorial now actually.  Thank you for the help.

**Comment by pylang** [comment]
I see you closed this, but an fyi, I don't think this issue got resolved.

**Comment by jakevdp** [comment]
Oh, sorry.

**Comment by jakevdp** [comment]
Are you using a recent version of notebook? If not you have to manually install the vega3 extension.

**Comment by pylang** [comment]
I was able to resolve it by running `> jupyter notebook`.   This command seems to run some kernel named "Python 3", which is not one of my normal conda env kernels.


  [0]: https://altair-viz.github.io/getting_started/installation.html#installation-notebook

**Comment by jakevdp** [comment]
Python 3 is the name of the default kernel when you're using Python 3. I think the installation instructions explicitly say that this is what you should use.

Glad you got it working!

**Comment by pylang** [comment]
For clarity, yes the docs mention:

> If you have done the above steps and charts still do not render, it likely means that you are using a different Kernel within your notebook. Switch to the kernel named Python 2 if you are using Python 2, or Python 3 if you are using Python 3.
 
but be aware, not all people have this kernel name set up by default.

For instance, I normally use the **Anaconda icon** to start jupyter, which after installing `nb_conda`, changes kernels to look like the following:

![2018-05-19 00_28_19-home](https://user-images.githubusercontent.com/10778668/40264924-0bfce8d2-5afc-11e8-8e8f-a26034aa5d37.png)

The menu show three redundant kernels (related to [this issue][0]) with additional custom kernels.  None explicitly say "Python 3".   

It is not clear why the kernel name matters (since the kernels all run Python 3.6), but the name appears to have an influence.  

1. Running jupyter from the Anaconda shortcut (+ `nb_conda`) did not work, even after choosing a custom kernel with installed dependencies.  
1. Note running the jupyter command alone also did not work.  

The jupyter command had to be run _in the activated conda environment containing the appropriate dependencies_:

```bash
>>> activate <envname>
>>> jupyter notebook
```

Results

![2018-05-19 00_36_41-home](https://user-images.githubusercontent.com/10778668/40264988-6013c62e-5afd-11e8-85e1-a3e0369d6ec9.png)

I don't know why the kernel menu changes or why a specific kernel name is required, but for those with `nb_conda` wondering how to "select Python 3", try this.

  [0]: https://github.com/jupyterhub/jupyterhub/issues/715

**Comment by jakevdp** [comment]
And yes, if you run jupyter frim a different environment from the one where you installed the required extension, things won't work because it's a different environment that doesn't have the required extension installed.

**Comment by jakevdp** [comment]
To be honest, I wasn't aware it was possible to launch the notebook from anywhere but the command line.
