### ISSUE TITLE
DOC: add documentation of themes & customization

### ISSUE THREAD

**Issue by Casyfill** [altair-viz/altair#840]
Hi, we're using our own theme (config) for our charts using vega - if I understand correctly it can be done through the altair by using `Chart.configure()` for each chart.

What I am proposing is to add single method like
```
import altair as alt
altair.configure()  # or altair.defaults()
```
so that we won't need to patch every single chart.
I will be happy to PR (sounds trivial), if you think this is a good idea

**Comment by jakevdp** [comment]
I'll leave this issue open as a reminder that we should document this feature.

**Comment by Casyfill** [comment]
ah, got it, thanks! 
it would be probably nice to add just a little bit on top of that 
- having VegaThemes json object sources somewhere on the web (as part of the github repo?)
- being able to enable either standard (string name) or custom theme with one-liner, like in matplotlib

```
alt.set_theme('ggplot')
alt.set_theme({'config': {'background': 'black'}})
```

**Comment by jakevdp** [comment]
We also plan to make available all the themes here: https://github.com/vega/vega-themes
But it will take a bit of thinking to figure out how to make things transparent to the user.

**Comment by Casyfill** [comment]
Probably Charts can propagate default configs on initialization so that config can be changed manually after? Plus, config will be part of resulting vegalite/vega json specs in this - that sounds pretty transparent to me...

Anyway, thanks for the help, and lmk if I can somehow help with that (or any other python-side issues on altair, for that matter).

**Comment by jakevdp** [comment]
By "transparent" I meant that I don't want users to have to think about the presence of the vega-themes repository, or whether they're using a theme defined there or one defined elsewhere. It's tricky because vega-themes are specified via metadata passed to vega-embed, while other themes are specified by modifying the actual chart specification.

**Comment by joelostblom** [comment]
Can this be closed since https://github.com/altair-viz/altair/pull/900/ was merged or is this open for more docs to be added?

**Comment by joelostblom** [comment]
I am closing this as themes are now documented.
