### ISSUE TITLE
Gallery Maps code is broken

### ISSUE THREAD

**Issue by jtf621** [altair-viz/altair#841]
I have tried to recreate the maps from https://altair-viz.github.io/gallery/index.html#maps.

When the chart is made and `.project(...)` is called I get an `AttributeError: 'Chart' object has no attribute 'project'`

alt.__version__ == '2.0.0rc2'  ( based on the tutorial from PyCon 2018).

``

**Comment by jakevdp** [comment]
The ``project()`` method was added in the final 2.0 release, and is not in the 2.0 release candidate.

Update your altair installation (using either ``pip install -U altair`` if you use pip, or ``conda update altair`` if you use conda) and this issue will go away.

**Comment by jtf621** [comment]
Thank you.  The upgrade to 2.0.1 fixed my issue.
