### ISSUE TITLE
custom image as Mark

### ISSUE THREAD

**Issue by SupahNoob** [altair-viz/altair#848]
Hi!

I stumbled upon your pycon2018 talk and it's brought me here. SUPER cool project, very powerful looking library. I was instantly intrigued! I have as much knowledge of Vega and your project as I could muster in the past couple of hours.

Is it possible to use a custom image (PNG, SVG, etc) as a marker? Ideally as a local path, but optionally a URL resource would work as well. This would go a LONG way in customizing visualizations along with the storytelling aspect you can build via selections.

I was reading through the source, but got lost pretty easily as there's a good amount of abstraction to make the declarative style work. Was naively hoping I might be able to hack it together myself :~)

ala [matplotlib](https://stackoverflow.com/questions/4860417/placing-custom-images-in-a-plot-window-as-custom-data-markers-or-to-annotate-t)

Thanks for your work on all this, it's very exciting stuff!
\- SN

**Comment by jakevdp** [comment]
Hi – no, custom markers are not currently possible.

**Comment by kanitw** [comment]
If you're interested in contributing this feature to the underlying Vega-Lite library, please feel free to file an issue and discuss more there. :)

**Comment by SupahNoob** [comment]
@kanitw I just realized, you're a main contributor to Vega-Lite. Super cool that you're so active in this project as well. Unfortunately, I have no experience with ts, so I probably wouldn't be the best help here. I will keep an eye on both projects though as it's exciting work!

The ease of creation of interactive viz here is great stuff.

**Comment by kanitw** [comment]
No worries. I will create an issue in VL anyway: https://github.com/vega/vega-lite/issues/3758.

**Comment by domoritz** [comment]
Just as a side note, Vega-Lite supports paths as shapes. Elm-Vega has an example: https://github.com/gicentre/elm-vega/blob/master/vlExamples/isotype.html

It will look like this
<img width="605" alt="screen shot 2018-05-31 at 17 54 02" src="https://user-images.githubusercontent.com/589034/40815482-a7460518-64fb-11e8-89bd-09b4458232b3.png">

**Comment by bittremieux** [comment]
It seems like custom image marks have recently been added in [vega/vega-lite#5060](https://github.com/vega/vega-lite/pull/5060). I've been searching for a way to do this in Altair as well, but I don't think it's possible yet?

**Comment by jakevdp** [comment]
https://github.com/vega/vega-lite/pull/5060 has not yet made it into a Vega-Lite release. Once Vega-Lite 4.0 is released, we will work on releasing Altair 4.0, which will support image marks.

**Comment by nehalecky** [comment]
@jakevdp and @kanitw, thanks for the discussion! I've spent time reviewing docs, and while I see this issue open, I also see:
- new version > 4 of altair released:  https://github.com/altair-viz/altair/releases/tag/v4.1.0 released, along with
- the referenced PR merged https://github.com/vega/vega-lite/pull/5060, and finally a
- reference in docs: https://altair-viz.github.io/user_guide/marks.html?highlight=custom%20image#user-guide-image-mark 

I am correct that this issue can be closed? Just making sure I'm not missing something?!

**Comment by jakevdp** [comment]
Yes, I believe this can be closed now. Thanks!
