### ISSUE TITLE
transform_window syntax

### ISSUE THREAD

**Issue by kanitw** [altair-viz/altair#850]
From the window transform documentation,  I just notice that `as` has to be specified via `**{'as': 'TotalTime'}` like 

```py
alt.WindowFieldDef(op='sum', field='Time', **{'as': 'TotalTime'})
```

I guess this is because `as` is a reserved keyword in Python.   

Since it's too late to change the parameter name in Vega-Lite at this point, I wonder if we should introduce an equivalent keyword in Altair instead. 

For example, we could use `output` like:

```py
alt.WindowFieldDef(op='sum', field='Time', output='TotalTime')
```

I also wonder if we introduce a bit shorter alias like `WindowField`?

**Comment by kanitw** [comment]
Actually, I just notice that 

`transform_bin`, `transform_timeUnit` uses the first parameter as the field name while `transform_aggregate` uses parameter key to assign the method name.  

Using parameter key like `transform_aggregate` is probably the way to go for window.

**Comment by jakevdp** [comment]
> Using parameter key like transform_aggregate is probably the way to go for window.

Yes, I agree. I didn't have time to think about a more streamlined API before the last release. It's complicated a bit by the fact that we'd have to either parse strings to extract aggregates, or create aggregate functions like I proposed in #763.

**Comment by jakevdp** [comment]
The current window transform syntax avoids the use of ``as``: https://altair-viz.github.io/user_guide/transform.html#user-guide-window-transform

**Comment by ogencoglu** [comment]
I am getting an error for usage of `as` in `transform_regression` to go around the reserved keyword issue. altair version 4.2.0.

```
.transform_regression(
    'Horsepower', 'Miles_per_Gallon', method='linear', **{'as': 'OutputName'}
)
```

`TypeError: transform_regression() got an unexpected keyword argument 'as'
`

Any help would be appreciated.

**Comment by mattijn** [comment]
I think you have to use `as_`, but I can see it documented as an option of this transform in the Altair docs: https://altair-viz.github.io/user_guide/transform/window.html#transform-options
