### ISSUE TITLE
DOC: Simple scatter mouseover selection

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#852]
I've been talking up Altair to my colleagues and gauging their reactions as they try it out.

Here's one example I don't see in the docs that I've been asked for several times now. What does it take to make a simple scatterplot where a label tooltip appears next to a dot when you hover over it with mouse?

This is a frequent use case in data journalism. A new dataset is gathered and thrown on the page. Then the journalist wants to quickly explore the points to identify the outliers. Matplotlib does not make this easy. If Altair did, we could win some converts for sure.

What is the shortest line to bringing that kind of functionality to the existing `cars` dataset examples? When I mouseover a point, it would be great if it simply printed out the name of the car.

```python
import altair as alt
from vega_datasets import data

cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x="Miles_per_Gallon:Q",
    y="Horsepower:Q",
)
```

![visualization 21](https://user-images.githubusercontent.com/9993/40152487-494dcb34-593a-11e8-82e9-9b1c71373b29.png)

**Comment by jakevdp** [comment]
This works with the most recent notebook and jupyterlab extensions:

```python
import altair as alt
from vega_datasets import data

cars = data.cars()

alt.Chart(cars).mark_point().encode(
    x="Miles_per_Gallon:Q",
    y="Horsepower:Q",
    tooltip='Name:N'
)
```

**Comment by jakevdp** [comment]
The docs are short on this because the tooltip stuff was overhauled in vega-embed right about the time we did the 2.0 release.

**Comment by palewire** [comment]
Glad to hear that! Would you be open to me adding an example?

**Comment by jakevdp** [comment]
That would be awesome. On my TODO list is a section in the docs as well.

**Comment by palewire** [comment]
Ah, I see that the simple scatterplot example has actually [been expanded](https://github.com/altair-viz/altair/blob/master/altair/vegalite/v2/examples/simple_scatter.py) in the master branch to include the tooltip. 

I think my cars example above might be duplicative of that. What else could I help with here.

**Comment by jakevdp** [comment]
The main section of the example gallery now features this: https://altair-viz.github.io/gallery/scatter_tooltips.html
