### ISSUE TITLE
Tooltip doesn't work on saved plot

### ISSUE THREAD

**Issue by cjer** [altair-viz/altair#858]
`altair.__version__ == '2.0.1'`

Toooltip doesn't work on the saved HTML output. Tried both firefox and chrome latest versions.

``` python
import altair as alt
from vega_datasets import data

cars = data.cars()

interval = alt.selection_interval(encodings = ['x', 'y'])

chart = alt.Chart(cars).mark_point().encode(
    x = 'Miles_per_Gallon',
    y = 'Horsepower',
    color = alt.condition(interval, 'Origin', alt.value('lightgray')),
    tooltip = 'Name'
).properties(
    selection = interval
)

(chart | chart.encode(x='Acceleration')).save('cars_select.html')
```

**Comment by ptiflus** [comment]
I think it works, but you have to wait before it appears (and it is much slower than in the notebook for me)

**Comment by jakevdp** [comment]
The html output in v2.0.1 uses an old version of vega-embed that doesn't yet support tooltips. This has already been fixed in master in #838.

So this be fixec in the next release. In the meantime you have two options:

1. switch to Altair master
2. use the 2.0.1 release, but manually change the package versions used by display by running the following:

    ```python
    alt.display.VEGAEMBED_VERSION = '3.9'
    alt.display.VEGA_VERSION = '3.3'
   ```

**Comment by cjer** [comment]
Tried option 2. Kind of works, thanks! 
Chrome seems to work fine, but now I am getting strange behaviour in Firefox - it shows one tooltip once, and then when I keep hovering over other points it doesn't show. Inspecting I see the title <div> title does change when I hover.

**Comment by palewire** [comment]
I'm seeing a similar problem [here](https://nbviewer.jupyter.org/github/datadesk/altair-interactive-scatterplot-example/blob/master/notebook.ipynb)

**Comment by jakevdp** [comment]
> I'm seeing a similar problem here

Rendering tooltips requires the most recent version of vega-embed. You will have to upgrade your vega3 jupyterlab extension in order to make this work.

**Comment by jakevdp** [comment]
I'm going to close this because it's already addressed in master. Thanks!
