### ISSUE TITLE
Legend colors missing

### ISSUE THREAD

**Issue by mozark24** [altair-viz/altair#859]
I have Vega3 installed and using the latest Jupyter notebook I am attempting to plot a bar chart with a legend.  While colors are shown correctly in the chart, the corresponding colors are missing in the legend labels.

```
alt.Chart(df).mark_bar().encode(
    alt.X('subset:O', axis=alt.Axis(title='Subset')),
    alt.Y('sum(sha256):Q', axis=alt.Axis(title='Number of samples')),
    alt.Color('label:N', scale=alt.Scale(range=["#3333ff", "#ff3333"]), legend=alt.Legend(values=["Cat1", "Cat2"]))
)
```

**Comment by jakevdp** [comment]
Can you provide a minimal dataset so that I can run your code and see the output you're seeing?

**Comment by mozark24** [comment]
Here is a minimal dataframe which can be re-created to produce the problem.

[https://imgur.com/a/yjlL1up](https://imgur.com/a/yjlL1up)
