### ISSUE TITLE
Q: Is it possible to modify the strokeWidth of a Strip Plot?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#867]
Here's another question from my newsroom colleagues. One of them was pleased to make a strip chart this morning, but was frustrated by how small and faint the lines were. I thought that perhaps the `strokeWidth` option could fatten them up, but it didn't seem to work.

Is there a way to do it? Here's a rough example with some dummy data I've been playing with.

```python
import pandas as pd
import altair as alt
from datetime import datetime
from vega_datasets import data

source = data.la_riots()
source = source[source.death_date < datetime(1993, 1, 1)]

alt.Chart(source).mark_tick(strokeWidth=50).encode(
    x='death_date:T'
)
```
![visualization 22](https://user-images.githubusercontent.com/9993/40210044-b05ed508-59f7-11e8-813c-811ed30f6e91.png)

**Comment by jakevdp** [comment]
That's strange – I would expect strokeWidth to work. I'm not certain why it doesn't affect the mark. Maybe worth raising in vega-lite?

From playing around a bit, I found that if you set the ``stroke`` encoding to a color, it helps a bit:

```python
alt.Chart(source).mark_tick().encode(
    x='death_date:T',
    stroke=alt.value('steelblue')
)
```

but we should really figure out how to get ``strokeWidth`` working.

**Comment by kanitw** [comment]
Tick is drawn using a rectangle, so strokeWidth won't work.   In the pending VL 2.5, you can use `thickness` to customize this. (There was a bug that this thickness is missing.)   

For now you can customize the thickness via the [tick config](https://vega.github.io/vega-lite/docs/tick.html#config).

**Comment by palewire** [comment]
Thanks for the information. Should `mark_tick` even accept "strokeWidth" as an input then?

**Comment by kanitw** [comment]
If you add stroke to the tick, then strokeWidth still works. (But yes, it's not really useful for practical use case.)

**Comment by palewire** [comment]
Am I crazy to think that passing an unsupported keyword argument to mark functions should raise an error?

**Comment by jakevdp** [comment]
The keyword is supported according to the schema, which by design is all that Altair cares about.

**Comment by jakevdp** [comment]
In Altair 3, thickness is supported:
```python
import pandas as pd
import altair as alt
from datetime import datetime
from vega_datasets import data

source = data.la_riots()
source = source[source.death_date < datetime(1993, 1, 1)]

alt.Chart(source).mark_tick(thickness=4).encode(
    x='death_date:T'
)
``` 
![visualization - 2019-05-29T222401 315](https://user-images.githubusercontent.com/781659/58610494-7735da00-8260-11e9-9a02-b2e021bd0e60.png)
