### ISSUE TITLE
Q: Is it possible to orient the y-axis label on top of the ticks?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#880]
The default y-axis label is now rotated sideways to run alongside the boundary line. This is a standard layout that, IMHO, is a design anti-pattern. Who can read that?

![visualization 28](https://user-images.githubusercontent.com/9993/40319566-6a8f9b14-5cdd-11e8-88ba-ffdc350426d0.png)

You can see that most mainstream news organizations agree. They often rotate the label's text and plant it above the y-axis range at the top of the chart.

NYT:

![screenshot from 2018-05-21 10-00-52](https://user-images.githubusercontent.com/9993/40319697-dff43126-5cdd-11e8-848e-1ffd8b58df4d.png)

WSJ:

![ddavthouqaewgel](https://user-images.githubusercontent.com/9993/40319781-309f3256-5cde-11e8-92ba-756b67d019cb.jpg)

WaPo:

![dcc1iurxcaefljr](https://user-images.githubusercontent.com/9993/40319858-80895d5a-5cde-11e8-9061-9ed6f2d2ae4d.jpg)

FT:

![screenshot from 2018-05-21 10-06-15](https://user-images.githubusercontent.com/9993/40319884-a1e4bc42-5cde-11e8-877b-7c406f6f67da.png)

I'm not sure a higher position with left-to-right text needs to be the default (though perhaps it should be), but it would be great to at least offer the option.

**Comment by kanitw** [comment]
cc: @jheer

**Comment by binste** [comment]
Closing as already answered in #1310
