### ISSUE TITLE
DOC: Some of the examples should be considered for retitling or reorganization

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#883]
IMHO, some of the examples in the Example Gallery are framed too tightly around complex projects to make sense as generic examples in the categories we have now.

The best examples, IMHO, are the ones that have a clear title describing the Altair feature or chart trick being documented, rather than the data content of the chart.  

I believe the titles below should either be regrouped in a "Case Studies" section that features more intricate projects, or retitled with more focus on the techniques they teach.

* Cumulative Wikipedia Donations
* Anscombe’s Quartet
* Becker’s Barley Trellis Plot
* Locations of US Airports
* London Tube Lines
* One Dot Per Zipcode
* U.S. state capitals overlayed on a map of the U.S
* Seattle Weather Interactive
* US Population Over Time
* Binned Movie Rating Heatmap

**Comment by eitanlees** [comment]
- [Falkensee](https://altair-viz.github.io/gallery/falkensee.html)
- [Gapminder Bubble Plot](https://altair-viz.github.io/gallery/gapminder_bubble_plot.html)
- [Natural Disasters](https://altair-viz.github.io/gallery/natural_disasters.html)

might also fall into this category

**Comment by jakevdp** [comment]
I think this was addressed by @palewire's work last year
