### ISSUE TITLE
Javascript error when plotting a column with special characters

### ISSUE THREAD

**Issue by Ezibenroc** [altair-viz/altair#888]
The following code throws an error (tested with Altair 2.0.1):

```python
import pandas
import altair
df = pandas.DataFrame({"A column name with 'quotes'" : [1, 2, 3, 4], "A column name without quotes" : [5, 6, 7, 8]})
altair.Chart(df).mark_bar().encode(
    altair.X(df.columns[0], bin=True),
    y='count()',
)
```
It fails with the error:
```
Javascript Error: Access path missing closing bracket: A column name with 'quotes'. This usually means there's a typo in your chart specification. See the JavaScript console for the full traceback.
```

This does not happen when using a column name without quotes (e.g., if I use `df.columns[1]` instead of `df.columns[0]`). If I put only one quote instead of two, the error is different:
```
Javascript Error: Access path missing closing quote: A column name with 'quotes. This usually means there's a typo in your chart specification. See the JavaScript console for the full traceback.
```

**Comment by jakevdp** [comment]
In Vega-Lite, quotes in field names need to be escaped; see https://vega.github.io/vega-lite/docs/field.html

**Comment by Ezibenroc** [comment]
Should Altair automatically escape the quotes, or is it up to the user to somehow do this?

**Comment by jakevdp** [comment]
I don't think Altair should automatically escape quotes: the reason they need to be escaped is that they have special meaning within field strings when not escaped, and I would not want Altair to prevent that use.

I think it would be worth raising an appropriate warning when single quotes, double quotes, square brackets, dots, or back-slashes are used.

**Comment by jmason86** [comment]
Just ran into this with a dot, square bracket, and % (my column titles are emission lines in nanometer and percent units, e.g., ```'17.1 nm Depth [%]'```).

**Comment by jakevdp** [comment]
If you use special characters like ``[]`` in your column name, you'll have to escape them. Vega-Lite allows a limited form of expressions within string column names in order to access nested data.

The easiest approach is to rename your columns so that you don't have problematic characters.

**Comment by jmason86** [comment]
Yep, that's what I've done now... though I have 24,000 columns and other generation and analysis code that refers to these columns with the special characters in them. Fortunately can convert in just a few lines of code for use with Altair.

**Comment by jakevdp** [comment]
If you do want to use the columns as-is, you just have to escape special characters as described here: https://vega.github.io/vega-lite/docs/field.html

**Comment by jmason86** [comment]
Hm... the escape described there for most things (\\) doesn't seem to be working: 

```
iris.columns = ['a', 'b[]', 'c.0', 'd', 'e']
alt.Chart(iris).mark_point().encode(
    x='a',
    y='c\\.0'
)
```
Results in an error ```ValueError: c\.0 encoding field is specified without a type; the type cannot be inferred because it does not match any column in the data.```

**Comment by jakevdp** [comment]
Because the escaped version of the field name does not match the pandas column name, Altair cannot infer the type of the column so you'll have to specify it explicitly (just as you do when passing data by URL rather than by dataframe):
```python
iris.columns = ['a', 'b[]', 'c.0', 'd', 'e']
alt.Chart(iris).mark_point().encode(
    x='a',
    y='c\\.0:Q'
)
```

**Comment by jakevdp** [comment]
It's good to get in the habit of specifying types explicitly anyway.

**Comment by johnmellor** [comment]
Hmm, in that example the y axis gets labelled "c\.0". And if you add a second dot, you get a blank plot again (in 2.2.2):

```py
iris.columns = ['a', 'b[]', 'c.c.0', 'd', 'e']
alt.Chart(iris).mark_point().encode(
    x='a',
    y='c\\.c\\.0:Q'
)
```

**Comment by joelostblom** [comment]
@Ezibenroc  I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been partially solved with workaround and any source changes would need to happen in VegaLite  so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved here yet.
