### ISSUE TITLE
multiple values in tooltips

### ISSUE THREAD

**Issue by robbie-sp** [altair-viz/altair#889]
Absolutely loving Altair - thanks so much for creating this

One thing I would like to have is the ability to create tooltips which have more than one value.

E.g. for the following example:

```python
from vega_datasets import data

iris = data.iris()

alt.Chart(iris).mark_point().encode(
    x='petalLength',
    y='petalWidth',
    color='species',
    tooltip='species'
)
```

Perhaps I would want to show not only the species in the tooltip but also the petalwidth.

It seems as though this is possible in vega lite [here](https://vega.github.io/vega-lite/docs/tooltip.html):

```json
{
  "data": {
    "values": [
      {"a": "A","b": 28}, {"a": "B","b": 55}, {"a": "C","b": 43},
      {"a": "D","b": 91}, {"a": "E","b": 81}, {"a": "F","b": 53},
      {"a": "G","b": 19}, {"a": "H","b": 87}, {"a": "I","b": 52}
    ]
  },
  "mark": "bar",
  "encoding": {
    "x": {"field": "a", "type": "ordinal"},
    "y": {"field": "b", "type": "quantitative"},
    "tooltip": [
      {"field": "a", "type": "ordinal"},
      {"field": "b", "type": "quantitative"}
    ]
  }
}
```
 but I am struggling to figure out how I would achieve this through Altair.

With some direction I would be happy to contribute to a pull request to either document this feature if it exists already or add in the feature if it doesn't.

**Comment by robbie-sp** [comment]
Sorry, just seen that this has been addressed in #830

**Comment by jakevdp** [comment]
Also see #890

**Comment by robbie-sp** [comment]
thanks!
