### ISSUE TITLE
Cumulative histogram

### ISSUE THREAD

**Issue by hugo-pires** [altair-viz/altair#902]
Hello

Is it possible to have "cumsum" operator that I can use together with bining to produce a cumulative histogram?

Thank you

**Comment by kanitw** [comment]
https://altair-viz.github.io/user_guide/transform.html#window-transform supports this.  

There are a bit more examples in [Vega-Lite docs](https://vega.github.io/vega-lite/docs/window.html#cumulative-running-average) -- you can adapt cumulative average to make cumulative sum.

**Comment by jakevdp** [comment]
It would be good to add an Altair example of a cumulative histogram

**Comment by hugo-pires** [comment]
Thank you both. But I have the same question: is there any `cumsum` operator that I can use?

**Comment by palewire** [comment]
I'd be happy to work on adding one. Is there a simple example out there in Vega or elsewhere you'd recommend working off?

**Comment by hugo-pires** [comment]
You could take an example from this item on seaborn documentation:
https://seaborn.pydata.org/generated/seaborn.distplot.html

or this question on Stackoverflow:
https://stackoverflow.com/questions/39297523/plot-cdf-cumulative-histogram-using-seaborn-python

**Comment by palewire** [comment]
It seems to me that there is a need for a very simple cumulative total example in our line charts.

At my day job at the Los Angeles Times, I edited [a story](http://www.latimes.com/politics/la-pol-ca-antonio-villaraigosa-charter-school-money-governor-20180514-story.html) a few weeks ago only the flood of "Super PAC" money rushing into California's looming primary for governor.

Here's a chart that ran with that story.

![](http://www.trbimg.com/img-5afb43c9/turbine/la-ca-pol-g-villaraigosa-pac-money-20180515/)

If there's not a good data set in vega_datasets currently for a "cumsum" line chart, this could make a good candidate. It's small, it's simple, it clearly fits the example.

**Comment by jakevdp** [comment]
The other issue is that the window transform API is currently very low-level and pretty painful to use (for example, it requires an ``as`` attribute which has to be passed as a kwarg dict because ``as`` is a keyword in Python) so it might be better to wait on user-facing examples until we have a better story for that.

**Comment by jakevdp** [comment]
#850 is where we're tracking window transform syntax.

**Comment by hugo-pires** [comment]
I think this article could be also very interesting for the discussion:
https://www.circonus.com/2018/05/effective-management-of-high-volume-numeric-data-with-histograms/

**Comment by kanitw** [comment]
FYI, I'm adding cumulative frequency plot to Vega-Lite https://github.com/vega/vega-lite/pull/3833

**Comment by hugo-pires** [comment]
Where can I find the vega-lite example? Can I use it on Altair?

**Comment by hugo-pires** [comment]
I guess I am almost there:

`hist = alt.Chart(clientes).mark_bar().encode(
    alt.X("valor:Q", bin=alt.Bin(maxbins=50)),
    y='sum(valor)'
)

soma = alt.Chart(clientes).mark_line(color='red').transform_window(
    window=[alt.WindowFieldDef(op='sum', field='valor', **{'as': 'TotalValor'})],
    frame=[None, 0],
    sort=[{"field": "valor", "order": "ascending"}]
).encode(
    alt.X("valor:Q", bin=alt.Bin(maxbins=50)),
    y='TotalValor:Q'
)

alt.layer(
    hist,
    soma
).resolve_scale(
    y='independent'
)`

**Comment by kanitw** [comment]
@hugo-pires  the example is in the posted PR: https://github.com/vega/vega-lite/pull/3833

**Comment by hugo-pires** [comment]
I am sorry but I still need some help to "smooth" the red cumulative line. I also had some questions to "translate" @kanitw  example to Altair. Could you help me?

Thank you

**Comment by hugo-pires** [comment]
Some more ideas:
https://realpython.com/python-histograms/

**Comment by kdunn926** [comment]
@hugo-pires , better late than never. If you drop the `bin` on your `soma` chart, it should work. Here's one I did:

```
cumu = alt.Chart(df_totals).mark_line(color='black', interpolate='step-after').transform_joinaggregate(
    total='count(*)'
).transform_calculate(
    pct='1 / datum.total'
).transform_window(
    frame=[None, 0],
    sort=[{"field": "return"}],
    cumu='sum(pct)'
).encode(
    alt.X("return:Q")),
    alt.Y('cumu:Q', axis=alt.Axis(title='Cumulative Likelihood'))
).properties(
    title='Distribution of Inflation Adjusted S&P 500 Returns (CAGR)',
    width=700,
    height=450
)

(hist + cumu).resolve_scale(y='independent')
```

![visualization](https://user-images.githubusercontent.com/7925800/74581697-7ddfbb00-4f6f-11ea-99b3-22952d245515.png)

**Comment by hugo-pires** [comment]
Thank you @kdunn926
