### ISSUE TITLE
underscore_case vs camelCase

### ISSUE THREAD

**Issue by apnewberry** [altair-viz/altair#904]
I'm getting started with Altair, and I've noticed most of the API is consistent with PEP 8 in `underscore_case`, but certain elements are in `camelCase`, like `timeUnit`. It looks like these are elements that appear in the Vega JSON spec, which makes sense. I haven't worked enough with Altair to be certain, but I'm wondering if it might be nice to use the Python style of `underscore_case` (e.g. `time_unit='month'`) for consistency with the rest of the Altair Python API, abstracting a bit from the Vega implementation; As a user, I'm not sure if I need to know that Altair is implemented using Vega and JSON. 

Interested in your thoughts!

**Comment by jakevdp** [comment]
Yes, Altair inherits many attribute names from vega-lite, which uses camel case. We don't plan to change or re-map those names, because it would add confusion and be a maintenance nightmare.
