### ISSUE TITLE
Documentation of current limitations

### ISSUE THREAD

**Issue by edschofield** [altair-viz/altair#908]
Amazing job with Altair, Jake! :-)

I've come across some apparent limitations in Vega-Lite 2.x and Altair 2.x while working on this: https://github.com/PythonCharmers/starborn.

I'd like to list and collect current known limitations here, in order to add these to the Altair docs.

## Current limitations:

1. cannot set axis properties of a facet such as 'orient'
2. cannot set the sort order for facets

**Comment by jakevdp** [comment]
Altair is able to produce any valid Vega-Lite specification. Any limitations it has are due to limitations of Vega-Lite, so I would ask there.

**Comment by kanitw** [comment]
These are known issues in Vega-Lite.  We'll try to address them soon!

https://github.com/vega/vega-lite/issues/2176
https://github.com/vega/vega-lite/issues/2446
