### ISSUE TITLE
Export higher DPI PNG

### ISSUE THREAD

**Issue by etra0** [altair-viz/altair#909]
Looking through the documentation, I couldn't find information about how to save higher dpi images (unlike `matplotlib` for example). This issue may be more related to vega than Altair, but I think it's a nice and useful feature for websites where SVG nor HTML are supported.

This issue of vega could be interesting: https://github.com/vega/vega/pull/1234

**Comment by jakevdp** [comment]
The PNG dpi is controlled by the dpi of the screen, so Altair cannot do anything about it.

That vega issue relates to node-js command-line tools. If you're interested in using that approach, you could save your chart to JSON and then use the ``vl2png`` command-line tool to create a PNG using that tool.

In version 1.X we tried making node tools available from Python, but it did not go well (there's not really any robust way to link between Python and node at the moment) so we dropped that in favor of selenium + chrome headless, which has a better compatibility story (but unfortunately does not allow as much customization of png output).

**Comment by jakevdp** [comment]
An easier suggestion is to save to SVG, which is effectively infinite resolution because it uses vector rather than raster graphics.

**Comment by jakevdp** [comment]
We could also address this using a ``scaleFactor``; see #917

**Comment by aldanor** [comment]
#917 added `scale_factor` parameter to `Chart.save()`, wondering if it's possible to do something similar wheen displaying charts inline? (whether it's via `Chart.display()` or in some other way). Use case: having larger (slightly zoomed in) inline plots in notebooks and in the exported HTML.

**Comment by etra0** [comment]
https://github.com/altair-viz/altair/pull/918 Solves my issue. I used it and works very well, thanks!

**Comment by jimmywan** [comment]
> An easier suggestion is to save to SVG, which is effectively infinite resolution because it uses vector rather than raster graphics.

I seem to have lost the option to save to SVG somewhat recently and I'm not entirely sure what I did to lose it. Is this a config issue? This is my basic "startup" code.
```python
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:100% !important; }</style>"))
import pandas as pd
import altair as alt
from altair import pipe, limit_rows, to_values
from altair.expr import datum
t = lambda data: pipe(data, limit_rows(max_rows=60000), to_values)
alt.data_transformers.register('custom', t)
alt.data_transformers.enable('custom')
alt.data_transformers.enable('json')
# for the notebook only (not for JupyterLab) run this command once per session
alt.renderers.enable('notebook')
```

**Comment by jakevdp** [comment]
What do you mean by "lost the option to save to SVG"?

One note on your startup script: you can only have one data transformer enabled at a time, so the following lines can be deleted:
```
t = lambda data: pipe(data, limit_rows(max_rows=60000), to_values)
alt.data_transformers.register('custom', t)
alt.data_transformers.enable('custom')
```
Also, it looks like your ``custom`` data transformer just serves to change the value of ``max_rows``. You can do this without registering a new transformer:
```
alt.data_transformers.enable('default', max_rows=60000)
```
But keep in mind that this will have no effect if you're enabling the json transformer afterward.

**Comment by jimmywan** [comment]
> What do you mean by "lost the option to save to SVG"?

When I first started playing with altair, it used to render with an "Export to SVG" tag at the bottom. Somewhere along the line it went away.

![image](https://user-images.githubusercontent.com/10406673/41258843-275ce7a0-6d97-11e8-8f69-cb1dca504084.png)

**Comment by jakevdp** [comment]
Hmm... I don't think the notebook or jupyterlab ever rendered with "Export to SVG" by default. They've always used the canvas renderer, which includes "Export to PNG".

Are you maybe thinking of the vega editor?

**Comment by jimmywan** [comment]
_Entirely_ possible that I'm completely mistaken. Only been using altair for about a month off/on and there's been a whirlwind of changes (altair RC1, RC2, changed based jupyter because something broke,etc). Would be a nice to have though. :)

**Comment by jakevdp** [comment]
Ah, so it turns out that with more recent versions of Vega-Embed, "Export as SVG" does show up regardless of the renderer.

The current release of the Jupyter notebook will include this, but the current release of JupyterLab will not... you'll have to run JupyterLab from the github master branch to see "Export as SVG" until the next release is out.

Sorry for the confusion there!
