### ISSUE TITLE
Can Altair iterate over dataframes to produce sequential charts?

### ISSUE THREAD

**Issue by ronyarmon** [altair-viz/altair#911]
I'm iterating over a dictionary of dictionaries to produce dataframes to chart using Altair. I can draw each chart [individually](https://github.com/ronyarmon/SFO/blob/master/charts/selected_questions.ipynb) but not when [I iterate over the dataframes ](https://github.com/ronyarmon/SFO/blob/master/charts/plots_iteration_not_working.ipynb). Is this a problem with my code?

**Comment by jakevdp** [comment]
Charts only render if they are evaluated as the output of a notebook cell. Your loop does not produce any output for the same reason this loop produces no output:
```python
for x in range(10):
    x + 1
```
You're not telling the notebook to display anything!

You have two options for displaying multiple charts:

### 1. concatenate the charts together and display them once

For example:
```python
chart = alt.VConcatChart()
for i in range(10):
    chart &= make_a_new_chart()
```
    
### 2. (only for Altair 2.1 or newer) call ``.display()`` on each
```python
for i in range(10):
    chart = make_a_new_chart()
    chart.display()
```

Hope that helps!

**Comment by ronyarmon** [comment]
Thanks. Concatenation worked but with chart.display I got:
AttributeError: 'Chart' object has no attribute 'display' 
Can you [have a look](https://github.com/ronyarmon/SFO/blob/master/charts/plots_iteration_not_working.ipynb) and let me know if I used it correctly (my altair is 2.0.1)?

**Comment by jakevdp** [comment]
The ``display()`` method did not make it into version 2.0.1, which is why I said above that it requires version 2.1 or newer (which has not yet been released, but is available in the master branch).

**Comment by ronyarmon** [comment]
ok, I prefer to wait to the release and can use concat for now
