### ISSUE TITLE
How to use selection_interval with mark_area?

### ISSUE THREAD

**Issue by reckoner** [altair-viz/altair#912]
I am trying to do something like this

    selector = alt.selection_interval(encodings=['x'])

    base = alt.Chart(data).encode(
        x='x:Q',
        y='y:Q',
        color=alt.condition(selector.ref(),'category:N',alt.value('lightgray')),
    ).properties(selection=selector)

    area = base.mark_area(interpolate='basis')

But when the selector chooses something on the plot, the area that is *outside* of the selection box is changed along with whatever is *inside* the selection box. I am trying to change the color of the area that is contained within the selection box *only*.

I hope that made some sense.

**Comment by kanitw** [comment]
Area is a group mark so it is one mark for the whole area so you can't change color for subparts. 

What you can do it to add another layer for area and use the selection to filter the data that feed into the second layer of area mark.  I'm adding an example to Vega-Lite https://github.com/vega/vega-lite/pull/3835.

**Comment by jakevdp** [comment]
It would be nice to get a version of this into the Altair examples :smile:

**Comment by FlorianGD** [comment]
I was attempting to make the vega-lite example, and I ran into a problem: if a use a selection with `empty='all'`, the chart appears all yellow when nothing is selected, but the selection works correctly; and if I use `empty='none'`, the chart is correcly blue when nothing is selectd, but the selection doesn't highlight the chart.
See below for reproducible example
```
import altair as alt
from vega_datasets import data

unemp = data.unemployment_across_industries.url

brush = alt.selection_interval(encodings=['x'])

base = alt.Chart(unemp).mark_area().encode(
    x=alt.X('date:T', timeUnit='yearmonth'),
    y=alt.Y('sum(count):Q')
)

selected = base.transform_filter(brush).mark_area(color='goldenrod')

chart1 = alt.layer(base.add_selection(brush), selected).properties(title="Empty='all'")

brush_empty = alt.selection_interval(encodings=['x'], empty='none')

selected_empty = base.transform_filter(brush_empty).mark_area(color='goldenrod')

chart2 = alt.layer(base.add_selection(brush_empty), selected_empty).properties(title="Empty='none'")
chart1 | chart2
```
When nothing is selected:
![selection_area_2](https://user-images.githubusercontent.com/9217921/48276824-42d80900-e449-11e8-8d61-db92a67a00c4.png)

When selecting:
![selection_area_1](https://user-images.githubusercontent.com/9217921/48276823-42d80900-e449-11e8-883c-ad911e556ace.png)

**Comment by reckoner** [comment]
The chart below creates a nice effect, but I don't have any answers to your original question about  `empty` or `all`.

    unemp = data.unemployment_across_industries.url

    brush = alt.selection_interval(encodings=['x'],empty='all')

    base = alt.Chart(unemp).mark_area(color='goldenrod',opacity=.3).encode(
        x=alt.X('date:T', timeUnit='yearmonth'),
        y=alt.Y('sum(count):Q')
    )

    selected = base.transform_filter(brush).mark_area(color='goldenrod')
    alt.layer(base.add_selection(brush), selected)


![image](https://user-images.githubusercontent.com/173637/53973371-79e7bf80-40b5-11e9-809d-c9f72a86c1d9.png)

**Comment by jakevdp** [comment]
Very nice!

**Comment by jakevdp** [comment]
Would you be willing to contribute that as an example for the gallery?

It would go in the [examples folder](https://github.com/altair-viz/altair/blob/master/altair/examples/) and you could use one of the charts there as a template (e.g. https://github.com/altair-viz/altair/blob/master/altair/examples/interactive_brush.py)

**Comment by reckoner** [comment]
Pull request https://github.com/altair-viz/altair/pull/1364.

Closed.
