### ISSUE TITLE
Reverse engineer vega-lite json to altair code?

### ISSUE THREAD

**Issue by reckoner** [altair-viz/altair#913]
Is it possible to take some vega-lite json and somehow automatically reverse engineer it to get the altair code that can generate the same? I thought @jakevdp  mentioned something like this during one of his early talks about altair.

**Comment by jakevdp** [comment]
Yeah, that used to be possible, but it was pretty brittle and created some unreadable code in the case of compound charts in particular, so we took it out.

You can recreate an Altair object, though, if you wish, using
```python
import json
with open('vega-lite-spec.json') as f:
    spec = json.load(f)
chart = alt.Chart.from_dict(spec)
```

**Comment by ObservedObserver** [comment]
> Yeah, that used to be possible, but it was pretty brittle and created some unreadable code in the case of compound charts in particular, so we took it out.
> 
> You can recreate an Altair object, though, if you wish, using
> 
> ```python
> import altair as alt
> import json
> with open('vega-lite-spec-file.json') as f:
>     spec = json.load(f)
> chart = alt.Chart.from_dict(spec)
> ```

I am wondering how unreadable the code be, is there any examples that are convenient for sharing? just come from #3209 , in pygwalker, we are also discussing whether it is possible to compile vega-lite code generated by pygwalker into Altair code or other chart lib in python.

**Comment by jakevdp** [comment]
We removed these code paths five years ago, when altair and Vega-lite were far simpler. I don’t know of any examples, but imagine a Vega-lite spec translated more-or-less directly from the JSON into Python code with the same structure. It was ugly.
