### ISSUE TITLE
Arrows?

### ISSUE THREAD

**Issue by biotemon** [altair-viz/altair#914]
Is there any way to draw arrows? Imagine a simple vector of (Xo,Yo) --> (Xi, Yi) coordinates. How can I get the head of the arrow?

Thanks!

**Comment by afonit** [comment]
looks like the suggestion here is to use a text mark with a unicode character:
https://github.com/vega/vega/issues/974

**Comment by afonit** [comment]
Here is a small example:

```python
import altair as alt
import pandas as pd

a = {'x': [2,3], 'y': [4,6], 'textof': ['➟', '➟']}
df = pd.DataFrame(a)

point = alt.Chart(df).mark_point().encode(
    x='x',
    y='y')

text = alt.Chart(df).mark_text(dx=-25,dy=19, angle=45, fontSize=35).encode(
    x='x',
    y='y',
    text='textof'
)

point + text
```

![visualization 1](https://user-images.githubusercontent.com/1798497/40846856-c3c9118e-6588-11e8-8e5b-dfa651736042.png)

**Comment by biotemon** [comment]
Thanks, but that is not what I want. Look the eigenvector plots in this link. 
https://cran.r-project.org/web/packages/ggfortify/vignettes/plot_pca.html

The only solution I have found is just to generate flat straight lines, and using and vector image processor I might manually add the heads in the lines.

**Comment by jakevdp** [comment]
Arrows are not yet supported in Vega-Lite, so they are not supported in Altair.

**Comment by firasm** [comment]
It seems some support may have been added arrows/unicode characters was added in Vega-lite - see [here]?(https://vega.github.io/vega/examples/wind-vectors/)

Is this now possible in Altair? 

I guess what I really want is to be able to annotate my plots with arrows - something like this, but much less complex. This is from an old [this issue](https://github.com/vega/vega-lite/issues/4270)

![56088534-ed5cb980-5e37-11e9-93d2-77e85f3a6002](https://user-images.githubusercontent.com/2507459/76140899-d4429580-6013-11ea-81b3-99712956ffac.png)

**Comment by vcuspinera** [comment]
Hi, to 'plot' vectors I have been using mark_line + mark_point (triangle-shape) charts, but it think it is not very efficient. I was wondering if there is a better way to plot vectors with Altair, or if you are already working in this issue to make it possible.
This is an example of what I am doing:
```
# plot a vector in altair
# points
origin = [0,0]
vector1 = [3,-1]
vector2 = [2,3]

v = pd.DataFrame([origin, vector1, vector2], columns=['X','Y'])

# plots
lines = {}
for i in v.loc[v.index!=0].index:
    lines[i] = alt.Chart(v.loc[(v.index==0)|(v.index==i)]).mark_line().encode(
        alt.X('X', scale=alt.Scale(domain=(-4,4))), 
        alt.Y('Y', scale=alt.Scale(domain=(-4,4))))

heads = alt.Chart(v.loc[v.index!=0]).mark_point(
    shape='triangle', size=100, fill='royalblue').encode(x='X',y='Y')

lines[1] + lines[2] + heads
```
<img width="568" alt="image" src="https://user-images.githubusercontent.com/53915521/76712577-6e22d600-66d7-11ea-9d6c-9c846df2951c.png">

**Comment by zacharylawrence** [comment]
> Is this now possible in Altair?

It looks like this was added to vega-lite in [v4.9.0](https://github.com/vega/vega-lite/releases/tag/v4.9.0) while Altair currently uses [v4.8.1](https://github.com/altair-viz/altair/releases/tag/v4.1.0) of vega-lite. I suspect that means that the next release of Altair will include support for this.

**Comment by joelostblom** [comment]
In addition to the workaround above, you can use a wedge mark with the angle encoding as in thie example https://altair-viz.github.io/gallery/wind_vector_map.html. Maybe we should try to add this to the documentation as an annotation too just to make it clearer. If anyone want to have a go at it, feel free. Adding the example with the unicode approach in https://github.com/vega/vega/issues/974 would also be helpful

**Comment by ChiaLingWeng** [comment]
maybe this can work:
```
import altair as alt
import numpy as np
import math

vector1 = [0,0,3,-1]
vector2 = [0,0,2,3]

v = pd.DataFrame([vector1, vector2], columns=['x1','y1','x2','y2'])

# calculate the vector
v['x_'] = v['x2']-v["x1"]
v['y_'] = v['y2']-v["y1"]
# dot = (x_,y_) dot (0,1) = y_
v["norm"] = np.sqrt(v['x_']**2+v['y_']**2)
v["theta"] = np.degrees(np.arccos(v['y_']/v["norm"] ))
#print(v)
lines = alt.Chart(v).mark_line().encode(
    x=alt.X("x1",scale=alt.Scale(domain=(-4,4)),title='x'),
    y=alt.Y("y1",scale=alt.Scale(domain=(-4,4)),title='y'),
    x2="x2",
    y2="y2"
    )

wedge = alt.Chart(v).mark_point(shape="wedge", filled=True).encode(
    alt.X("x2"),
    alt.Y("y2"),
    alt.Angle("theta").scale(domain=[0, 360]),
    size = alt.value(500),
    color=alt.value('#000000')
)
lines+wedge
```
result in:
![image](https://github.com/altair-viz/altair/assets/75072960/54ea1f30-8669-4a04-9ce7-7a8a899ddfbd)
