### ISSUE TITLE
Layered or Facet bar plot with label values in Altair

### ISSUE THREAD

**Issue by Ram-N** [altair-viz/altair#920]
This is related to this [SO question](https://stackoverflow.com/questions/50662831/layered-or-facet-bar-plot-with-label-values-in-altair). I am trying to recreate @jakevdp 's solution, using the `population` dataset.

```
import altair as alt
from altair.expr import datum, if_
from vega_datasets import data

source = data.population.url

bars = alt.Chart(source).mark_bar(stroke='transparent').encode(
    alt.X('gender:N', scale=alt.Scale(rangeStep=12), axis=alt.Axis(title='')),
    alt.Y('sum(people):Q', axis=alt.Axis(title='population', grid=False)),
    color=alt.Color('gender:N', scale=alt.Scale(range=["#EA98D2", "#659CCA"])),
    column='age:O'
).transform_filter(
    datum.year == 2000
).transform_calculate(
    'gender', if_(datum.sex == 2, 'Female', 'Male')
)

text = bars.mark_text(
    color='black',
    dx = 10,
).encode(
    text='sum(people):Q'
)

alt.layer(bars, text).configure_view(
    stroke='transparent'
).configure_axis(
    domainWidth=0.8
)

```

Gives me the following error:
```
SchemaValidationError: Invalid specification

        altair.vegalite.v2.api.LayerChart->layer->items, validating 'anyOf'

        {'data': {'url': 'https://vega.github.io/vega-datasets/data/population.json'}, 'mark': {'type': 'bar', 'stroke': 'transparent'}, 'encoding': {'color': {'type': 'nominal', 'field': 'gender', 'scale': {'range': ['#EA98D2', '#659CCA']}}, 'column': {'type': 'ordinal', 'field': 'age'}, 'x': {'type': 'nominal', 'axis': {'title': ''}, 'field': 'gender', 'scale': {'rangeStep': 12}}, 'y': {'type': 'quantitative', 'aggregate': 'sum', 'axis': {'grid': False, 'title': 'population'}, 'field': 'people'}}, 'transform': [{'filter': '(datum.year === 2000)'}, {'calculate': "if((datum.sex === 2),'Female','Male')", 'as': 'gender'}]} is not valid under any of the given schemas
```

It looks like I cannot use `alt.layer` and `column` together.
When I commented out the line:

        #    column='age:O'
 
It renders.
![image](https://user-images.githubusercontent.com/737241/41075248-ba3f093e-69c0-11e8-993f-ccad1a52090f.png)

Any help on overcoming this error and rendering text on every bar in each age bucket? Thanks.

**Comment by jakevdp** [comment]
Layering only works with single-panel charts, so you cannot layer a faceted charts. The reason why is that, in general, matching panels between different faceted layers is tricky.

The workaround is to facet a layered chart, which is supported, though it's important that you specify the data in the right place. There's some discussion of this in the [documentation](https://altair-viz.github.io/user_guide/compound_charts.html#faceted-charts).

Example:

```python
import altair as alt
from altair.expr import datum, if_
from vega_datasets import data

source = data.population.url

bars = alt.Chart().mark_bar(stroke='transparent').encode(
    alt.X('gender:N', scale=alt.Scale(rangeStep=12), axis=alt.Axis(title='')),
    alt.Y('sum(people):Q', axis=alt.Axis(title='population', grid=False)),
    color=alt.Color('gender:N', scale=alt.Scale(range=["#EA98D2", "#659CCA"])),
).transform_filter(
    datum.year == 2000
).transform_calculate(
    'gender', if_(datum.sex == 2, 'Female', 'Male')
)

text = bars.mark_text(
    color='black',
    dx = 10,
).encode(
    text='sum(people):Q'
)

alt.layer(bars, text, data=source).facet(
    column='age:O'  
).configure_axis(
    domainWidth=0.8
).configure_view(
    stroke='transparent'
)
```

**Comment by Ram-N** [comment]
Thank you. Works perfectly. And thank you for the explanation. Layer first, and *then* facet.

**Comment by rampDD** [comment]
Code was included in the attached pdf-File.

`import altair as alt
import pandas as pd
import numpy as np
alt.renderers.enable('default')

vals_v = list()
vals_w = list()
vals_d = list()
vals_b = list()
vals_bi = list()

for bi in range(1,17):
    for b in [0,1,144,500,1000]:
        for d in range(1,6):
            for w in [6,9]:
                vals_v.append(np.round(np.random.randn(),2))
                vals_w.append(w)
                vals_d.append(d)
                vals_b.append(b)
                vals_bi.append(bi)
                
cols=('wafer_nr', 'dut_n', 'bake_time', 'Bit', 'Vpp')
df = pd.DataFrame(columns=cols)
df['wafer_nr'] = vals_w
df['dut_n'] = vals_d
df['bake_time'] = vals_b
df['Bit'] = vals_bi
df['Vpp'] = vals_v
df.to_csv('testdata.csv')

ch = alt.Chart()
ch = ch.mark_area(opacity=0.3)
ch = ch.encode(
                x = alt.X('Vpp:Q'),
                y = alt.Y('count():O'),
                color=alt.Color('bake_time:N')).interactive()

ch2 = alt.Chart()
ch2 = ch2.mark_line().encode(
                            x = 'mean(Vpp):N',
                            color=alt.Color('bake_time:N')).interactive()
(ch+ch2).facet(data='testdata.csv',        
            row=alt.Row('wafer_nr:O'),
            column=alt.Column('dut_n:O'))`

**Comment by retrojim** [comment]
I know this is a year old thread, but it was very helpful to me. One thing...how do you get the mark_text labels to show up in black instead of the gender encoded color?

**Comment by jakevdp** [comment]
> how do you get the mark_text labels to show up in black instead of the gender encoded color?

Don't include a color encoding in the chart with ``mark_text()`` or the base that it's derived from.

**Comment by retrojim** [comment]
Thanks! That worked.

**Comment by v-gaurav** [comment]
Hi, this helped me. But now I'm getting an error when trying to set width and height of faceted chart -
 .properties(
    # add a title
    title="Title",
    width=240,
    height=180
)

SchemaValidationError: Invalid specification

        altair.vegalite.v3.api.Chart, validating 'required'

        'data' is a required property

**Comment by jakevdp** [comment]
It's difficult to help you without a complete code snippet.
