### ISSUE TITLE
Specify the color

### ISSUE THREAD

**Issue by robalvsan** [altair-viz/altair#921]
```
mv_dict = {'type': ['values', 'values'], 'quantity': [5, 10], 'category': ['mv', 'no_mv']}
df = pd.DataFrame(mv_dict)
alt.Chart(df).mark_bar().encode(
    y='type',
    x='sum(quantity)',
    color='category',
)
```
With this piece of code, the graph is generated automatically using blue for 'mv' and orange for 'no_mv'

![image](https://user-images.githubusercontent.com/10865429/41100112-c0c32c86-6a60-11e8-85dc-2e1bc608077a.png)

Since in some contexts, the color has an implicit connotation...could it be possible to specify what color I want to use for 'mv' (e.g. red) and what for 'no_mv' (e.g. green)?

**Comment by afonit** [comment]
Here you go:
```python
import altair as alt
import pandas as pd
mv_dict = {'type': ['values', 'values'], 'quantity': [5, 10], 'category': ['mv', 'no_mv']}
df = pd.DataFrame(mv_dict)
alt.Chart(df).mark_bar().encode(
    y='type',
    x='sum(quantity)',
    color=alt.Color('category',
                   scale=alt.Scale(
            domain=['mv', 'no_mv'],
            range=['red', 'green'])))
```

**Comment by robalvsan** [comment]
Awesome, thanks!

**Comment by jakevdp** [comment]
You can also use ``alt.Color('category', scheme=scheme_name)`` where ``scheme_name`` is a string that matches any of the available Vega color schemes: https://vega.github.io/vega/docs/schemes/#reference

**Comment by afonit** [comment]
@jakevdp , I tried what you posted:
`alt.Color('category', scheme='accent)`
I got a schema validation error:
Additional properties are not allowed ('scheme' was unexpected)

however doing:
`color=alt.Color('category', scale=alt.Scale(scheme='accent'))`
did work.
I updated to 2.1 to test what you had posted - perhaps I am doing something wrong.

**Comment by Artemis-R** [comment]
@jakevdp Do you have any tips on using vega schemes with log scales? I tried 
     `alt.Color('Name', type = 'quantitative', scale=alt.Scale(scheme=scheme_name, type='log'))`
but this resulted in the scheme command simply being ignored to generate the log scale and the standard colors being utilized.

**Comment by lightalchemist** [comment]
@Artemis-R I have the same issue as you but for the case where I set `type="log"`. Do you have a fix? Thanks.

**Comment by SuperShinyEyes** [comment]
> Here you go:
> 
> ```python
> import altair as alt
> import pandas as pd
> mv_dict = {'type': ['values', 'values'], 'quantity': [5, 10], 'category': ['mv', 'no_mv']}
> df = pd.DataFrame(mv_dict)
> alt.Chart(df).mark_bar().encode(
>     y='type',
>     x='sum(quantity)',
>     color=alt.Color('category',
>                    scale=alt.Scale(
>             domain=['mv', 'no_mv'],
>             range=['red', 'green'])))
> ```
> 
> ![visualization 2](https://user-images.githubusercontent.com/1798497/41101984-b25cc35a-6a33-11e8-8c5c-ede93ac730dd.png)

The specified colors break if you concatenate charts. :\

**Comment by fredgi123** [comment]
Is there a way to specifically have the 0 value returns a white color and the rest in the normal scheme? 
If for instance, I use color=("variable:Q", scale=alt.Scale(scheme="blues")) my 0 values are still displaying blue values not white. thank you!
