### ISSUE TITLE
Encoding documentation sample is broken

### ISSUE THREAD

**Issue by iliatimofeev** [altair-viz/altair#924]
https://altair-viz.github.io/user_guide/encoding.html#effect-of-data-type-on-color-scales
![visualization 11](https://user-images.githubusercontent.com/11561581/41170483-2d94eda0-6b55-11e8-8e41-bb5305fc4eb5.png)
It has `"config": {"mark": {"color": "black", "fill": "black"}}` in a Vega-Lite definition

**Comment by iliatimofeev** [comment]
In my humble opinion, huge part of examples looks less attractive in new style {"filled":"black"} 
:)

**Comment by iliatimofeev** [comment]
>"For example, here we define a theme in which all marks are drawn with black fill unless otherwise specified:" https://altair-viz.github.io/user_guide/configuration.html#defining-a-custom-theme

I think it had a global effect on documentation.

**Comment by jakevdp** [comment]
Thanks – yep, the theme example somehow leaked globally, which was not intended. I'll work on fixing it.

**Comment by jakevdp** [comment]
Fixed in 6b9d5eef7dd850388d7f01ce5eed33bda2100

I'll push a new build of the docs
