### ISSUE TITLE
scale_factor causes chromedriver to timeout intermittently

### ISSUE THREAD

**Issue by jploudre** [altair-viz/altair#929]
I'm generating about 1200 graphs with a loop. When I try to use:

chart.save with scale_factor = 2,

it repeatedly crashes after about 300 graphs -- not at the same spot. Replicated on 2 different computers. Timeouts resolve when removing scale_factor.

(That said, **Love** scale_factor.)

**Comment by jakevdp** [comment]
Thanks for the report

**Comment by jakevdp** [comment]
Fixed in #939
