### ISSUE TITLE
rename axes?

### ISSUE THREAD

**Issue by smsaladi** [altair-viz/altair#930]
Does altair have [`redim`](http://holoviews.org/user_guide/Annotating_Data.html#Setting-properties-with-redim)-like or [`xlab`/`ylab`](http://ggplot2.tidyverse.org/reference/labs.html)-like functionality?

I know it's possible to set axis titles via `alt.Axis(title='NEW TITLE')`, but I'm wondering if it's possible to do this in an alternate way, say if the chart object has already been created, but one just wants to modify the axis labels. For example in ggplot:

```R
p <- ggplot(df) +
    geom_point(aes(x, y))
p

# "curious plot, i wonder what it looks like with axis titles"
p +
    xlab("interesting axis 1") +
    ylab("interesting axis 2")
```

**Comment by jakevdp** [comment]
You could do
```
chart = alt.Chart(data).encode(
    alt.X('foo'),
    alt.Y('bar')
)

chart.encoding.x.title = 'new title'
chart.encoding.y.title = 'another new title'
```

**Comment by jakevdp** [comment]
I don't anticipate us adding new top-level functions to adjust parts of the plot.

**Comment by pagpires** [comment]
Is it possible to change the titles for each sub-chart in repeatChart (e.g. by feeding a list)?

**Comment by adiep2501** [comment]
How do you do this for the main chart as oppose to just the axes?

**Comment by Zylatis** [comment]
Is it possible to pass font family arguments to properties for the title?

**Comment by jakevdp** [comment]
Yes, for example:
```python
chart = alt.Chart(data).encode(
    alt.X('foo', title='Foo', axis=alt.Axis(titleFont="Helvetica Neue"),
)
```
more axis properties can be seen at https://altair-viz.github.io/user_guide/generated/core/altair.Axis.html
