### ISSUE TITLE
.interactive only working with certain data types.

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#933]
Hi Altair users,

Is there a reason why adding ".interactive" does not work for the following example? I'm unable to pan or zoom. However if I use a temporal data type for the dates, then it works (although the rect marks now go on forever in the past).

```
df=pd.DataFrame({'days_between': ['2017-01-01', '2017-01-02', '2017-01-03'], 'variable': ['person_1', 'person_2', 'person_3'], 'value': [1,2,3]})

alt.Chart(df).mark_rect().encode(
    x='days_between:O',
    y='variable:N',
    color=alt.Color('value:Q', scale=alt.Scale(range=['green','yellow','red']))).properties(width=300, height=100).interactive()
```
![visualization 3](https://user-images.githubusercontent.com/4624246/41248362-cf654456-6d7e-11e8-9017-6332e52367a5.png)

With a temporal data type:
```
...
 x='days_between:T',
...
```
![visualization 2](https://user-images.githubusercontent.com/4624246/41248344-c2f8d96c-6d7e-11e8-8093-fd70e694ff22.png)

Any help is appreciated.

Al

**Comment by Casyfill** [comment]
same issue - `.interactive()` does not work with geoshapes for me:
```
alt.Chart(boundaries).project(type="mercator",center=[-73.99,40.72]
).properties(width=500,height=300).mark_geoshape(fill='lightgrey').encode().interactive()

```
results in
```
Javascript Error: Expression parse error: " ? {unit: \"\", intervals: []} : null". This usually means there's a typo in your chart specification. See the JavaScript console for the full traceback.

```

**Comment by Alcampopiano** [comment]
@Casyfill I don't think this is the same issue as mine since I am not getting an error.

**Comment by jakevdp** [comment]
This is a known issue; see https://github.com/altair-viz/altair/issues/679 and https://github.com/vega/vega-lite/issues/3306

**Comment by Alcampopiano** [comment]
Jake, since my issue is not related to geo, should it be closed?

**Comment by jakevdp** [comment]
Sorry, I thought it was related to geo.

Reading more closely, it looks like your issue is that ``interactive()`` does not work on ordinal/nominal scales, is that right? If so, that's by design, so perhaps it just needs to be better documented?

**Comment by Alcampopiano** [comment]
Yes, that was the issue. Thanks for clarifying.

**Comment by jakevdp** [comment]
Vega-Lite achieves pan/zoom behavior by binding an interval selection to ``"scales"``. This is precisely what calling ``chart.interactive()`` does in Altair.

The issue here is that interval selections bound to scales for non-quantitative encodings do not work in Vega-lite, and from the linked issues this appears to be by design. So no, there currently is no way to make this work.
