### ISSUE TITLE
BUG: alt.datum does not support nested properties

### ISSUE THREAD

**Issue by Casyfill** [altair-viz/altair#934]
and those nested properties are typical for topojson/geojson objects; consider example:

```python

boundaries = alt.topo_feature(map_url, 'area')


alt.Chart(boundaries).transform_filter(alt.datum.properties['area_type'] == 'neighborhood').mark_geoshape(fill='red').encode(color='area_id:N').project(
    type="mercator",
    center=[-73.99,40.72]
).properties(width=500,height=300)

```

**Comment by Casyfill** [comment]
`alt.datum['properties.area_type'] == 'neighborhood' ` is being converted to
```
{"filter": "(datum['properties.area_type'] === 'neighborhood')"}
``` and therefor results in false for every element

**Comment by Casyfill** [comment]
had to workaround with

```
MAP = alt.Chart(boundaries).transform_calculate(area_type='datum.properties.area_type',).transform_filter(alt.datum.area_type == 'neighborhood')
MAP.mark_geoshape(fill='red').encode(color='area_id:N').project(
    type="mercator",
    center=[-73.99,40.72]
).properties(width=500,height=300)
```

**Comment by jakevdp** [comment]
What vega expression do you want it to generate?

**Comment by Casyfill** [comment]
It doesn't have to be vega, I am looking for altair equivalent of vega-lite 
```
"transform": [
{"type": "filter", "expr": "datum.properties.area_type == 'neighborhood' "}
]
```; it works fine when I use `alt.datum.property`, but not with `alt.datum.property.nestedproperty`

**Comment by jakevdp** [comment]
Sorry to be unclear; ``"datum.properties.area_type == 'neighborhood' "`` is an example of a [vega expression](https://vega.github.io/vega/docs/expressions/), which is used within vega-lite.

Currently the ``alt.datum`` interface does not support nested properties, but you can pass the vega expression directly as a string, as you found above.

I'll mark this as a bug; we should make the ``alt.datum`` interface support nested expressions.

**Comment by jowens** [comment]
Related: How can `alt.datum` support a field name that is not a valid Python identifier? For instance, if the field is called `acey-ducey`, `alt.datum.acey-ducey` doesn't parse since it thinks the `-` is a minus sign.

**Comment by jakevdp** [comment]
You can pass any string to a getitem, e.g.
```python
alt.datum['acey-ducey']
```

**Comment by manzt** [comment]
Running into this as an issue with topojson with properties, which are stored in `datum.properties.key`.

VegaLite:
```javascript
  "data": {
    "url": "https://gist.githubusercontent.com/manzt/9e0f8301c929b3b95ebcbc664c1e5761/raw/a1527d11fe2bc4a0462d533fd679e216cf09a465/nyschools-topo.json",
    "format": {
      "type": "topojson",
      "feature": "zones"
    },
    "transform": [{"filter": {"field": "properties.dbn", "valid": true}}],
  },
```

Altair:
```python
nyc_url = (
    f"https://gist.githubusercontent.com/manzt/"
    f"9e0f8301c929b3b95ebcbc664c1e5761/raw/"
    f"a1527d11fe2bc4a0462d533fd679e216cf09a465/"
    f"nyschools-topo.json"
)
nyc_zones = alt.topo_feature(nyc_url, 'zones')

alt.Chart(nyc_zones).mark_geoshape(
    fill='lightgray',
    stroke='white'
).transform_filter(
    alt.FieldValidPredicate(field="properties.dbn", valid=True)
).encode(
    fill = "properties.boro:N",
)
# nothing rendered
```

**Comment by jakevdp** [comment]
I don't think your failure is related to this issue: you never use ``alt.datum``. I'd suggest debugging via the vega editor.

**Comment by joelostblom** [comment]
@Casyfill I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
