### ISSUE TITLE
Doc on altair.Scale format broken

### ISSUE THREAD

**Issue by iliatimofeev** [altair-viz/altair#935]
https://altair-viz.github.io/user_guide/API.html?highlight=scale#altair.Scale
![image](https://user-images.githubusercontent.com/11561581/41250199-e6066a6a-6dbe-11e8-9913-9c26ee7fc2e4.png)

**Comment by jakevdp** [comment]
This is a known issue. All of the formats are broken, because this is automatically-generated from documentation that has meaningful line-breaks, and such line breaks are not supported in sphinx as far as I can tell.
