### ISSUE TITLE
Label and text opacity and color

### ISSUE THREAD

**Issue by SyntaxRules** [altair-viz/altair#936]
I would like to change the text color and opacity of text in my charts. I'm using this to create an 'overlay' of sorts to show a watermark.

Thus far, I've attempted to change opacity in the following ways:

```
chart = alt.Chart(fada).mark_line().encode(
    x='x',
    y='sin(x)'
).properties(
    title='Example1',
    width=800,
    height=400
)

watermark = alt.Chart(fada).mark_text(
        align='center', dx=375, dy=0, fontSize=48, fontWeight=200, opacity=0.5, text='foo-baz'
    ).encode(
        opacity=alt.value(0.5)
    )

chart + watermark
```
![image](https://user-images.githubusercontent.com/4117657/41251162-529565ee-6d76-11e8-95ff-175b8da9dee8.png)

The opacity property in `mark_text` or in `encoding` don't seem to have any affect on title or axis' labels. 

Is there a way to: (1) Change the opacity of my text and (2) change the color of the same text.

**Comment by jakevdp** [comment]
The opacity is working as expected, but you're layering ``N`` identical semi-transparent texts on top of each other, which makes them look opaque.

One approach you could use would be to aggregate the data so you only have a single instance:
```python
watermark = alt.Chart(fada).mark_text(
        align='center', fontSize=48, fontWeight=200, opacity=0.5, text='foo-baz'
    ).encode(
        x='mean(x)',
        y='mean(sin(x))',
        opacity=alt.value(0.5)
    )

chart + watermark
```
![visualization 7](https://user-images.githubusercontent.com/781659/41251815-f20f3ebc-6d6f-11e8-8cfa-830383597b39.png)

**Comment by jakevdp** [comment]
If you use ``mark_text(..., color='red')`` you can change the color to anything you wish.

**Comment by SyntaxRules** [comment]
Great catch!

I like the approach because it puts the text in the actual center of the data, however it messes with the axis labels. I can manage to remove the second label with:

```python
x = np.arange(100)
fada = pd.DataFrame({'x': x,
                     'sin(x)': np.sin(x / 5)})

chart = alt.Chart(fada).mark_line().encode(
    alt.X('x', axis=alt.Axis(title='x title')),   # Changed this line
    y='sin(x)'
).properties(
    title='Example1',
    width=800,
    height=400
)

watermark = alt.Chart(fada).mark_text(
        align='center', fontSize=48, fontWeight=200, opacity=0.5, text='foo-baz'
    ).encode(
        alt.X('mean(x):Q', axis=alt.Axis(title='')),  # Changed this line
        y='mean(sin(x))',
        opacity=alt.value(0.5)
    )

chart + watermark
```
Which produces:
![image](https://user-images.githubusercontent.com/4117657/41253346-46cc39b6-6d7d-11e8-87f1-65c2cbee5494.png)

This is alright, but **the x axis still has a trailing comma.**

After some more tests, I determined that I can avoid writing `N` semi-transparent labels on top of each other by changing my watermark chart data set. For good measure, I added in the color to this snippet too.

```python
watermark = alt.Chart(pd.DataFrame([1])).mark_text(
    align='center', dx=400, dy=0, fontSize=48, text='foo-baz', color='red'
).encode(
    opacity=alt.value(0.5)
)
```
Which gives a very similar result:

![image](https://user-images.githubusercontent.com/4117657/41253642-3c7e0650-6d7e-11e8-9a0e-157effa82a6e.png)

While the first way is nicely placed in the middle, the second way requires it to be done manually. However the second way does not require the re-writing of axis formulas or fool around with axis labels. There is a little give and take with both approaches.

Thanks for the quick response, I'm closing this now as my questions have been answered!

**Comment by josephburkhart** [comment]
This helped me, too. Thank you!
