### ISSUE TITLE
using circle mark with long/lat creates huge empty canvas

### ISSUE THREAD

**Issue by Casyfill** [altair-viz/altair#937]
```
Z = alt.Chart(minidata[['job_number', 
                    'longitude',
                    'latitude']]).mark_circle(size=3,
                                              color='blue').encode(longitude='longitude:Q', 
                                                                   latitude='latitude:Q').project(**PRJ)
```
creates tiny-tiny image *~20px square;
adding Z.properties(width=500, heught=500) creates enormously large, yet empty canvas ...

**Comment by jakevdp** [comment]
What is ``minidata`` and ``PRJ``? I can't reproduce this.

**Comment by Casyfill** [comment]
sorry, it is definitely not an altair issue - can reproduce that in online editor, — so closing here. Will raise an issue on vega-lite (vega?) repository
