### ISSUE TITLE
Setting tick labels to list of strings

### ISSUE THREAD

**Issue by Alcampopiano** [altair-viz/altair#938]
Hi everyone,

Is there a way to set the tick labels in a chart to some list of strings? Here is the chart:

```
df=pd.DataFrame({'days_between': [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6],
                 'person': [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,2],
                 'value': [10,11,12,13,14,15,10,11,12,13,14,15]})

alt.Chart(df).mark_square(size=400).encode(
    x=alt.X('days_between:Q', axis=alt.Axis(values=[1,2,3,4,5,6])),
    y=alt.Y('person:Q', axis=alt.Axis(values=[1,2])),
    color=alt.Color('value:Q', scale=alt.Scale(range=['green','yellow','red']))).properties(width=400, height=400).interactive()
```
![visualization 5](https://user-images.githubusercontent.com/4624246/41256355-4edb4a9c-6d97-11e8-8007-35c11a5828a9.png)

I would have thought this would work (similar to matplotlib in some sense):
```
 alt.Axis(..., labels=['string 1', 'string 2', 'string 3', 'string 4', 'string 5', 'sting 6'])
```

Is there a way to do this when using quantitative data types as I am in the above example?

**Comment by jakevdp** [comment]
Altair is designed to properly display whatever data you input regardless of the type, unlike matplotlib which requires you to input quantitative data and then manually re-map the axes to whatever non-quantitative data you want it to represent.

So I'd say the best approach to this for Altair is to actually put the values you're interested in into your data. For example:
```Python
df=pd.DataFrame({'days_between': [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6],
                 'person': [1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2,2],
                 'value': [10,11,12,13,14,15,10,11,12,13,14,15]})
df['days_between'] = df['days_between'].map({i + 1: 'ABCDEF'[i] for i in range(6)})

alt.Chart(df).mark_square(size=400).encode(
    x=alt.X('days_between:O'),
    y=alt.Y('person:Q', axis=alt.Axis(values=[1,2])),# scale=alt.Scale(domain=[1, 2], range=[1, 2])),
    color=alt.Color('value:Q', scale=alt.Scale(range=['green','yellow','red']))
).properties(width=400, height=400).interactive()
```
![visualization 8](https://user-images.githubusercontent.com/781659/41256875-be01c314-6d7f-11e8-9417-3648f7cc22c7.png)

**Comment by Alcampopiano** [comment]
Hi Jake, yes this works, but see now the interaction only works in one direction since the x axis is nominal. I understand that the interaction is designed to respond only to quantitative data types, so I was trying to work around that.

**Comment by jakevdp** [comment]
It sounds like the real solution to your problem is not remapping axis labels, but to somehow allow selections to be bound to non-quantitative scales.

**Comment by Alcampopiano** [comment]
Yes, exactly! Nice way of specifying the issue directly in the spirit of grammar of graphics.

**Comment by domoritz** [comment]
Selections work on categorical axes as well. See https://vega.github.io/vega-lite/examples/interactive_concat_layer.html.

**Comment by jakevdp** [comment]
Do you have an example of selections being *bound to scales* for non-quantitative axes?

**Comment by domoritz** [comment]
Hmm, we can bind to input elements (https://vega.github.io/vega-lite/docs/bind.html#input-element-binding) but not to axes as far as I know. That seems to be missing in the grammar. I created https://github.com/vega/vega-lite/issues/3874.

**Comment by jakevdp** [comment]
I think that example is a bit different... what I have in mind is [this](https://vega.github.io/vega-lite/docs/bind.html#scale-binding) except when the x/y encodings are nominal or categorical.

**Comment by domoritz** [comment]
Do you want zooming and panning?

Binding a selection to the domain of a categorical scale should change the scale's domain, I think.

**Comment by jakevdp** [comment]
Yes, I believe what @Alcampopiano is asking for here is the ability to zoom & pan on non-quantitative scales. Sorry if that was unclear.

**Comment by jakevdp** [comment]
This is a frequent confusion for Altair users... we have that ``interactive()`` method that adds a ``selection: {type: 'interval', bind: 'scales'}`` and most people expect that to result in a zoomable/pannable plot regardless of whether the scales are quantitative or categorical.

**Comment by domoritz** [comment]
We will not resolve this even if we support binding selections to the domain of ordinal scales. We can think about how scrolling changes a multi selection and maybe implement it that way. @arvind said he wanted to think about how the selection grammar can be extended.

**Comment by Alcampopiano** [comment]
Thanks for looking into this guys.

Al

**Comment by arvind** [comment]
Hi folks,

Panning/zooming categorical scales is a really interesting use case. As the interactions are continuous operations (e.g., I could pan/zoom just a little bit or a lot) but would need to map to a discrete domain, what would be the desired behaviour? For example, should we push/pop just a single element regardless of the magnitude of the pan/zoom? If not, how do we define proportionality (especially the default)?

**Comment by Alcampopiano** [comment]
@arvind Apologies for not getting back. I simply don't know enough to be able to offer any guidance. As unhelpful as it might be, as a user, I would enjoy behaviour similar to what plotly does when panning/zooming on a chart with a categorical axis. You can see an example here:

https://plot.ly/python/bar-charts/

Thanks for all your hard work.

Sincerely,
Allan

**Comment by palewire** [comment]
Am I able to do this with date values ala:

```python
axis=alt.Axis(values=[date(2008, 9, 1)]),
```
