### ISSUE TITLE
Format multi tooltip

### ISSUE THREAD

**Issue by ptiflus** [altair-viz/altair#943]
Hello,
I cannot find a way to provide a format for each field of a multi tooltip. Here is a reproducible example : 
```
import pandas as pd
import numpy as np
import altair as alt

np.random.seed(14)
data = pd.DataFrame({"date": pd.date_range("2018-01-01", periods=100),
                     "values": np.random.normal(size=100)})

alt.Chart(data).mark_point().encode(
    x="date:T",
    y="values:Q",
    tooltip=alt.Tooltip(['date:T', 'values:Q'], format='.2f')
)
```
Which formats also the date field:
![screenshot from 2018-06-12 18-06-09](https://user-images.githubusercontent.com/9217921/41302700-730d89a0-6e6b-11e8-80e5-1d11a84c398f.png)
If I try something like 
```
alt.Tooltip(['date:T', 'values:Q'], format=['%d/%m/%Y', '.2f'])
```
I have an error saying that format is not a string.

So, how can I specify the format of each field in this multi tooltip ?

**Comment by jakevdp** [comment]
You can set the encoding to a list of ``alt.Tooltip`` objects, each with their own format string:
```python
import pandas as pd
import numpy as np
import altair as alt

np.random.seed(14)
data = pd.DataFrame({"date": pd.date_range("2018-01-01", periods=100),
                     "values": np.random.normal(size=100)})

alt.Chart(data).mark_point().encode(
    x="date:T",
    y="values:Q",
    tooltip=[alt.Tooltip('values:Q', format='.2f'),
             alt.Tooltip('date:T', format='%A, %B %e')]
)
```

**Comment by ptiflus** [comment]
Oh, great, thanks!

**Comment by firasm** [comment]
Is there any way to add a percent symbol *AND* round using format= ?

From the example above:

`tooltip=[alt.Tooltip('values:Q', format='.2f')`

we tried 

`tooltip=[alt.Tooltip('values:Q', format='{.2f}%')`

but there was a javascript error. 

Any ideas ?

**Comment by jakevdp** [comment]
Format strings must follow [d3-format](https://github.com/d3/d3-format); so you probably want something like ``format='.2%'``

**Comment by firasm** [comment]
Ah! That's it - thanks!

**Comment by tonylee3399** [comment]
Just for additional information, if you need to show `DateTime` format in your tooltip, you could refer to this [d3-time-format](https://github.com/d3/d3-time-format#locale_format)

**Comment by lc0** [comment]
I wonder if I am the only one who does the same formatting. Ex for y-axis as well as for tooltip. 

Is there any feature to just use the same formatting? cc @jakevdp 

Sorry for pushing the old issue 🙈
