### ISSUE TITLE
Reference json data not in current working drive.

### ISSUE THREAD

**Issue by safurrier** [altair-viz/altair#949]
I have a large dataset (100k observations) that I'm trying to plot. Due to its size I need to write the data for the chart to disk and reference it rather than embed in the Jupyter notebook I'm working in. I know I can enable the json data transformer like so:

> alt.data_transformers.enable('json')

However the problem I'm  running into is that my current working drive is not the same as the directory in which my notebook resides. Enabling the json data transformer and attempting to render a chart results in a blank chart. If I move the generated json file to the same file as the notebook the chart is then rendered correctly. 

I've tried exporting the data manually to json and referencing this new location like so:

> data_export_path = 'notebooks/chart_data.json'

> df.to_json(data_export_path, orient='records')

> alt.Chart(data_export_path).mark_bar().encode(
>     alt.X('X:Q', bin=True),
>     alt.Y('count(X):Q')
> )

But this renders a blank chart also. 

Any suggestions for what I'm doing wrong here? Thanks!

**Comment by jakevdp** [comment]
The easiest way would be to do
```
alt.renderers.enable('default', max_rows=None)
```
This will embed your data into the notebook regardless of its size, and should work correctly. Note, however, that each chart you create in the notebook will embed another copy of the full dataset, and so your notebook can grow very large if you make many charts.

The alternative is to serve your data from file: you just need to save the file at a place your Jupyter server can see, and then pass the correct URL to that file. I can't give you any one-size-fits-all recipe for how to do that, because it depends on how your Jupyter server was started and configured.

Hope that helps,

**Comment by safurrier** [comment]
Thanks!
 I'll embed the data until I've figured out the best way to serve it.

**Comment by deisi** [comment]
@safurrier if you are on a unix machine (linux or mac) you could softlink your data. On windows I dont know.

@jakevdp is this behaviour intended? Can it be related to https://github.com/altair-viz/jupyterlab_voyager/issues/46
I mean its strange that you can only open relative paths and not paths.

This means:

```pthon
# This url wont work
#url = '/home/malte/Nextcloud/Documents/Mica/analysis/data.json'
# This url  works
url = 'data.json'
c0 = alt.Chart(url).mark_point()
```

If this is not intended, I would sugest reopening the issue.

**Comment by jakevdp** [comment]
Altair does support fully-qualified URLs, but it would look something like ``http://localhost:8888/analysis/data.json`` (assuming you started your jupyter server in the ``Mica`` directory). What you specified above looks like a *system* filepath: the Jupyter webserver cannot access arbitrary system paths, and that is intended, though it's not something Altair has any control over.

Hope that clears things up.

**Comment by deisi** [comment]
Okay thx

Am 20. Juni 2018 16:49:54 MESZ schrieb Jake Vanderplas <notifications@github.com>:
>Altair does support fully-qualified URLs, but it would look something
>like ``http://localhost:8888/analysis/data.json`` (assuming you started
>your jupyter server in the ``Mica`` directory). What you specified
>above looks like a *system* filepath: the Jupyter webserver cannot
>access arbitrary system paths, and that is intended, though it's not
>something Altair has any control over.
>
>Hope that clears things up.
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/altair-viz/altair/issues/949#issuecomment-398778930

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by safurrier** [comment]
Trying to do this from Jupyter Lab, I've exported my data to json. Using the Jupyter Lab ability to pull a shareable link (right click the json file --> Copy Shareable Link) I believe I have a valid url. However when I pass this link to a chart (e.g. alt.Chart(json_url)), I still get a blank chart. Any ideas on what I'm doing wrong?

**Comment by jakevdp** [comment]
That shareable link is to a jupyterlab view of the file, which is not what you want here. You want the raw file: remove ``lab`` from the URL path and it should work... i.e. change ``http://localhost:8888/lab/tree/data.json`` to ``http://localhost:8888/tree/data.json``

**Comment by k0al4** [comment]
One question here. Why not make Altair to look for the source of data in the current folder? I believe it would be faster to work with and more straightfoward. Anyway, Altair is indeed beautiful, useful and much more time-efficient than others I've tried. And I thank so much the ppl working on it. However, finding solutions to some topics is really difficult and time consuming, considering I am not a developer (postdoc in accounting) and have never used Vega Lite before.

**Comment by jakevdp** [comment]
> Why not make Altair to look for the source of data in the current folder?

Altair does this if you're running locally. If you're running on a cloud backend, your browser does not have direct access to the current folder active in the backend.

**Comment by jakevdp** [comment]
> However, finding solutions to some topics is really difficult and time consuming

Documentation contributions are welcome; I do most of this work during work breaks and after my kids go to sleep. I'm sorry the docs are not more complete.

**Comment by k0al4** [comment]
No need for apologies. At all! It's a great tool and I will look for ways
to contribute a little bit. Thanks!

Em sex, 3 de mai de 2019 às 17:12, Jake Vanderplas <notifications@github.com>
escreveu:
