### ISSUE TITLE
log scale with zero data should give a better warning

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#953]
I had a column of data that I plotted on a log scale:

```
sh = Chart(df).mark_point().encode(
    x='Launch:T',
    y=Y('Pixel/unified shader count:Q',
        scale=Scale(type='log'),
        ),
```

and a zero snuck into the column that I didn't know about and the debugging of that took a really really long time. Here's what Altair output looked like:

![visualization](https://user-images.githubusercontent.com/976970/41682640-1d083dac-748d-11e8-9754-0748fbfc260c.png)

I guess I would have expected that the zeroes would be silently dropped OR the console would have thrown a warning ... anyway, the Altair output was perplexing. One zero out of several hundred data points made everything plot on a single line.

**Comment by jakevdp** [comment]
Agree this is confusing. It would be worth opening an issue in vega-lite: that's where something like this could be fixed.
