### ISSUE TITLE
Arbitrary sort from Vega-Lite

### ISSUE THREAD

**Issue by jploudre** [altair-viz/altair#955]
I’m trying to sort some person names on a graph. Vega-Lite says you can provide an array:

> 4) Sorting by preferred order of values by providing sort as an array of values that specify the order. Unspecified values will assume their original orders in the data source, preceded by the orders in the sort array.

But I can’t seem to brute force my way into making it work. Looking around, it seems like there might be changes in 2.2 for sorting.

If someone can show me how to sort by an array I provide, I’d be happy to write it up as example/documentation — how to set order manually.

**Comment by jakevdp** [comment]
Is this the kind of thing you're talking about?
```python
import altair as alt

df = pd.DataFrame({'Name': ['Peter', 'Paul', 'Mary'],
                   'Score': [94, 87, 96]})

alt.Chart(df).mark_bar().encode(
    x='Score',
    y=alt.Y('Name', sort=['Peter', 'Paul', 'Mary'])
)
```
![visualization 15](https://user-images.githubusercontent.com/781659/41724311-21db29bc-7522-11e8-9c7a-3476be8c4834.png)

**Comment by jploudre** [comment]
Yes, that's it. I was trying to set sort=alt.SortOrder and alt.SortField.

I think an example showing sorting by last names would be useful. I'll write it up if you agree. :-)

**Comment by jakevdp** [comment]
> I think an example showing sorting by last names would be useful

That would be great!

**Comment by aldanor** [comment]
This seems to break with layering, took me a long while to figure it out... wondering if it's a feature or a bug?

Consider this:

```python
df = pd.DataFrame({
    'x': ['a', 'b', 'c', 'a', 'b', 'c'],
    'y': [-1, 0, 1, 0, 1, -1],
    'c': [0, 1, 0, 1, 0, 1]
})
chart = alt.Chart(df).encode(
    x=alt.X('x:N', sort=['c', 'a', 'b']),
    y='y:Q',
    color='c:N'
)
chart1 = chart.mark_point(size=50)
chart2 = chart.mark_square(size=10)
chart3 = chart1 + chart2
for c in (chart1, chart2, chart3):
    display(c.configure_view(height=100))
```

which outputs:

![image](https://user-images.githubusercontent.com/2418513/41773369-be4a2af4-7613-11e8-8f87-7fd769484814.png)

![image](https://user-images.githubusercontent.com/2418513/41773334-a1605d6e-7613-11e8-931a-1b814bee38f0.png)

![image](https://user-images.githubusercontent.com/2418513/41773344-ad8cf8c2-7613-11e8-9424-991428956d42.png)

**Comment by jakevdp** [comment]
That's a known bug: see #698
