### ISSUE TITLE
Suggest Altair supports ISO-Standard day-of-week time unit transformation

### ISSUE THREAD

**Issue by coolum001** [altair-viz/altair#960]
According to international standard ISO 8601, Monday is the first day of the week.

Pandas has:
" DatetimeIndex.dayofweek

The day of the week with Monday=0, Sunday=6"

I suggest a new time unit transformation (say ```dayISO```, that has Monday as the first day of the week  (ie to align with Pandas).

This would have the advantage of grouping non-working days together, which might make some graphics produced by Altair easier to understand.

**Comment by jakevdp** [comment]
Thanks – I would suggest proposing this in the Vega-Lite repository. Altair has no control over what transforms are available.
