### ISSUE TITLE
Using mark_line() with a sorted axis?

### ISSUE THREAD

**Issue by aldanor** [altair-viz/altair#961]
If you sort an axis, then `mark_line()` will do a strange thing and follow the original order as seen in the example below.

Is there a way for the line marks to follow the new order? (would you ever want them not to?..)

```python
df = pd.DataFrame({'Name': ['Peter', 'Paul', 'Mary'],
                   'Score': [3, 1, 5]})
alt.Chart(df).mark_line().encode(
    x=alt.X('Name', sort=['Peter', 'Mary', 'Paul']),
    y='Score'
)
```

![image](https://user-images.githubusercontent.com/2418513/41777379-06a7572c-7623-11e8-9557-84d2542128f4.png)

**Comment by jakevdp** [comment]
Looks like https://github.com/vega/vega-lite/issues/1520 is the relevant issue.

**Comment by jimioke** [comment]
As I've found, a good workaround is to create another column with numeric order and then specify, `order = <column name>` and set `sort = None` in the `x` field. Then, you should get your desired path order.

**Comment by aldanor** [comment]
@jimioke Yes, this works but seems more like a workaround than a fix; sounds like vega should be able to natively handle this.

**Comment by enotspe** [comment]
> der

could you please give an example

**Comment by enotspe** [comment]
> As I've found, a good workaround is to create another column with numeric order and then specify, `order = <column name>` and set `sort = None` in the `x` field. Then, you should get your desired path order.

could you please give an example

**Comment by joelostblom** [comment]
@aldanor I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved in hte latest version of Altair so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.

![image](https://user-images.githubusercontent.com/4560057/108920135-fb112780-75e8-11eb-96aa-adc5556879be.png)
