### ISSUE TITLE
hconcat of more than 2 mark_geoshape() causes projection error

### ISSUE THREAD

**Issue by sidravi1** [altair-viz/altair#962]
Hi,

This is using the US population, engineers, hurricane data in the examples.

```
import altair as alt
from vega_datasets import data

states = alt.topo_feature(data.us_10m.url, 'states')
pop_eng_hur = data.population_engineers_hurricanes.url

variable_list = ['population', 'engineers', 'hurricanes']

base = alt.Chart(states).mark_geoshape().transform_lookup(
    lookup='id',
    from_=alt.LookupData(pop_eng_hur, 'id', variable_list)
).properties(
    width=100,
    height=100
)

row_chart = [] 
for field in variable_list: 
    field = field+":Q"
    row_chart.append(base.encode(
        color=alt.Color(field,legend=None),
    ).project(
        type='albersUsa'
    ))
    
alt.hconcat(*row_chart, resolve = alt.Resolve(scale=alt.LegendResolveMap(color=alt.ResolveMode('independent'))))
```

The output looks like this:

![image](https://user-images.githubusercontent.com/14125957/41785603-1a3200ce-7611-11e8-812d-4bfc20f9d8b9.png)

It works fine when I use .repeat() but I want to be able to arrange the plots as a grid (3 x 3) of plots and want to be able to customize it.

Looks like a vegalite problem to me since the json generated looks consistent for all the sub-maps. Has this been noticed and if so, is there an issue I can track?

**Comment by jakevdp** [comment]
Thanks – this is a known issue in Vega-Lite: see https://github.com/vega/vega-lite/issues/3544

**Comment by sidravi1** [comment]
Thank you. I'll track that issue.

**Comment by joelostblom** [comment]
@sidravi1 I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved in the latest version of Altair so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
