### ISSUE TITLE
Changing the y axis via dropdown (bind_select)

### ISSUE THREAD

**Issue by ajasja** [altair-viz/altair#965]
I would like to change the y-axis of a plot interactively (eg. via dropdown, similar to [this blog post](https://medium.com/@chekos/altair-and-ipywidgets-a-simple-example-f61269c72c02)).

![animation](https://raw.githubusercontent.com/Chekos/blog-posts/master/altair%20%2B%20ipywidgets/altair%20%2B%20ipywidgets.gif)

However if possible I'd like to do this all in javascript, so that I can distribute a single *.html.
I saw that vega-lite has [Input Element Binding](https://vega.github.io/vega-lite/docs/bind.html).

**Does this work in altair? Are there any examples?**

I did find some [documentation](https://altair-viz.github.io/user_guide/API.html?highlight=bind#altair.binding_select), but have not figured out, where the binding would go.

**Comment by ajasja** [comment]
For example I tried 

```python
import altair as alt
from vega_datasets import data
cars = data.cars()
bs = alt.binding_select(options=list(cars.columns))
alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='Miles_per_Gallon',
    color='Origin',
    shape='Origin'
).add_selection(
   bs  
)
```

But that only returns:
![image](https://user-images.githubusercontent.com/19926/41813941-d3fdad48-7740-11e8-8c81-f1972dd904c7.png)

**Comment by jakevdp** [comment]
You cannot change the encoded column via a selection box within vega-lite, but you can filter on the value of a column. So you can do something like what you want by reshaping the data and filtering on the column value. For example:
```python
import altair as alt
from vega_datasets import data

cars = pd.melt(data.cars(), ['Horsepower', 'Origin', 'Name', 'Year'])
cars.head()

select_box = alt.binding_select(options=list(cars['variable'].unique()))
selection = alt.selection_single(name='y_axis', fields=['variable'], bind=select_box)

alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='value',
    color='Origin',
    tooltip='Name'
).add_selection(
    selection
).transform_filter(
    selection
)
```
<img width="548" alt="screen shot 2018-06-24 at 10 39 43 am" src="https://user-images.githubusercontent.com/781659/41821818-f5ec79a2-779a-11e8-8411-fa3c9b9a80b0.png">

**Comment by jakevdp** [comment]
One of the items on the TODO list is to add more documentation & examples of these kinds of selection bindings; the only one we have currently is this: https://altair-viz.github.io/gallery/us_population_over_time.html

**Comment by ajasja** [comment]
Wow, thank you, this is very impressive! 

- Is it perhaps possible to change the axis label? I tired giving `alt.condition` to the axis label, but it did not go down well:)
- What is the initial value of the `binding_range`? It seems to be uninitialized
![image](https://user-images.githubusercontent.com/19926/41823277-a88c7c12-77fd-11e8-9b32-d55fba6e98d1.png) and then when I make the first move 
![image](https://user-images.githubusercontent.com/19926/41823283-b6bae756-77fd-11e8-8b03-e9b671594c62.png)
- Is it possible to have several bindings? I tried:

```python
select_box = alt.binding_select(options=list(cars['variable'].unique()))
selection = alt.selection_single(name='y_axis', fields=['variable'], bind=select_box)

slider_year = alt.binding_range(min=1970, max=1982, step=1)
selection_year = alt.selection_single(name='Year', fields=['Year'], bind=slider_year)

alt.Chart(cars).mark_point().encode(
    x='Horsepower',
    y='value',
    color='Origin',
    tooltip=['Horsepower', 'Origin', 'Name', 'Year']
).add_selection(
    selection,
    selection_year
).transform_filter(
    selection & selection_year
)
```

But that does not work. I guess  I have to combine them differently in the transform filter?

Should I make a pull request for a new example with bindings?
