### ISSUE TITLE
Rectangle zoom

### ISSUE THREAD

**Issue by ajasja** [altair-viz/altair#966]
Is it possible to zoom in using a rectangle selection?

Similar to bokeh [box_zoom](https://bokeh.pydata.org/en/latest/docs/user_guide/tools.html#userguide-tools-pandrag) tool.

(`interactive(bind_x=False)` did solve my particular use case, but I'm still curios:)

**Comment by jakevdp** [comment]
No, that's not supported in vega-lite.

**Comment by carolinadamata** [comment]
Is this still not supported?

**Comment by krlng** [comment]
I think this is the issue, we will need to up vote: https://github.com/vega/vega-lite/issues/4742

**Comment by eric-valente** [comment]
+1 here please!

**Comment by Episkiliski** [comment]
Was this closed because this feature has been developed?

**Comment by joelostblom** [comment]
This is closed because there is no action to take from the altair side of things. Once https://github.com/vega/vega-lite/issues/4742 is implemented in VL, the feature will be available in the next version of Altair.
