### ISSUE TITLE
pd.Timedelta is not JSON serializable

### ISSUE THREAD

**Issue by iliatimofeev** [altair-viz/altair#967]
In:
```python
td =  pd.timedelta_range(0,periods=3,freq='h')
alt.Chart(
    pd.DataFrame(dict(id=np.arange(td.size),timedelta = td))
).mark_bar(
).encode(
 x = 'timedelta',
 y ='id:O'
)
```
Out:
```python
~/anaconda/anaconda/envs/rr_dev/lib/python3.5/json/encoder.py in default(self, o)
    177 
    178         """
--> 179         raise TypeError(repr(o) + " is not JSON serializable")
    180 
    181     def encode(self, o):

TypeError: Timedelta('0 days 00:00:00') is not JSON serializable
```
In:
```python
print ('pandas',pd.__version__)
print ('altair',alt.__version__)
```
Out:

```python
pandas 0.23.0
altair 2.1.0
```
Expected, but I'm not sure that is  achievable without `timeUnit="hoursminutes"`.
![visualization 17](https://user-images.githubusercontent.com/11561581/41821223-01e72d06-77e6-11e8-9850-b8d61faad284.png)

**Comment by jakevdp** [comment]
Vega only supports time stamps, not time deltas. The best apporach to time deltas is to encode your data as a timestamp and extract the part of the date you want with a timeunit. For example:
```python
import altair as alt
import pandas as pd
import numpy as np

td =  pd.timedelta_range(0,periods=3,freq='h')
timestamp = pd.to_datetime('2018-01-01') + td

df = pd.DataFrame(dict(id=np.arange(td.size), time=timestamp))

alt.Chart(df).mark_bar().encode(
    x='hoursminutes(time)',
    y='id:O'
)
```
![visualization 19](https://user-images.githubusercontent.com/781659/41821886-19dd75ea-779c-11e8-8ef8-23bc1c29fb2f.png)

**Comment by iliatimofeev** [comment]
IMHO, will be great in that case at least throw `NotImplemented` with your answer it's more understandable than JSON error. 
Or just do what you propose while sanitizing DataFrame and parsing shorthand. It will involve some magic to understand what is appropriate precision for timedelta but field maximum value will give us that information.

**Comment by jakevdp** [comment]
I don't think it's appropriate to automatically convert timedeltas to time stamps, because it would be quite confusing. A different error might help, though. What would you suggest?

**Comment by jakevdp** [comment]
For what it's worth, the ``"is not JSON serializable"`` error comes from JSON, not from Altair, so the only way we get around that is to anticipate what types the user might pass to Altair and catch those errors earlier.

**Comment by jakevdp** [comment]
I don't think that silently dropping columns is a useful pattern, because that leads to even more obscure errors from within the Vega renderer.

**Comment by iliatimofeev** [comment]
I not a big fan of silently hiding errors. I meant that Jupiter (Lab) user will see the warning in output cell as `pandas` or `sklearn` do. `sklearn` sometimes warn users with something like `"use value  {value} of parameter {name} to have better results"` it is better than throwing exception after ten minutes calculation.

I guess if you drop it in `sanitize_dataframe` with printing warning into cell and throw exception in  `pars_shorthand`  it will cover most cases except user set directly a field parameter in encoding, but in that case user will see a warning before empty chart.

IMHO, It will have two advantages: first of all it will work out of the box in common cases, second it will give information on all incompatible columns in one call.

However I may overvalue  this functionality after few days in a loop: loading new table, receiving "Not JSON..", guessing what caused it, reporting an issue, finding work around and back to next table :) 

Looks like understanding what causes error will be enough for today.

**Comment by jakevdp** [comment]
The error for time deltas is much more specific now. If tou come across other situations that lead to a "not JSON serializable" error, please let us know.

**Comment by jonathangjertsen** [comment]
> Vega only supports time stamps, not time deltas. 

It would be nice to be able to use a dataframe with a timedelta field directly without having to do the conversion. What changes would be needed upstream in order to support this in a good way?

**Comment by jonathangjertsen** [comment]
For future reference, I ended up with a workaround like this:

```Python
def add_difference_column(data, column, difference_column):
    diffed = data[column].diff()

    # Special case for timestamps due to https://github.com/altair-viz/altair/issues/967
    if diffed.dtype.kind == "m":
        diffed = diffed.dt.total_seconds()

    data[difference_column] = diffed

add_difference_column(data, "temperature", "temperature_diff")
add_difference_column(data, "voltage", "voltage_diff")
add_difference_column(data, "time", "time_diff")
# etc
```

If Altair/Vega supported timedeltas out of the box, this could be reduced to

```Python
def add_difference_column(data, column, difference_column):
    data[difference_column] = data[column].diff()
```` 

(the helper function is not strictly needed in this reduced example, but in my actual usecase this is part of a more complex operation with some filtering and grouping before and after)
