### ISSUE TITLE
Geoshape border box can't be modified

### ISSUE THREAD

**Issue by coolum001** [altair-viz/altair#969]
```mark_geoshape``` appears to draw a border box (with color 221,221,221 - almost white) inside the specified padding.;

I cannot find a way to set the color of this border, or to suppress it  (it appears to NOT be an axis that can be adjusted with configure_axis call).  Other marks (eg mark_bar) do not appear to draw this border.

I would like to be able to remove this border, as (in my view) it adds no useful information to the graphic.  Happy to be told I am missing some key item in the documentation; happy to supply more info if needed.

Don

My environment is:
```
python version : 3.6.3 | packaged by conda-forge | (default, Nov  4 2017, 10:10:42) [MSC v.1900 64 bit (AMD64)]
python environment : root36
pandas version : 0.22.0
 ...
Notebook run on: Windows-10-10.0.17134-SP0

print(alt.__version__)
2.1.0
```

Example code is:

```
from vega_datasets import data
from altair.expr import datum

countries = alt.topo_feature(data.world_110m.url, 'countries')

base = alt.Chart(countries, background='blue', padding=50).mark_geoshape(
    fill='tan',
    stroke='red',
    color='black'
).properties(
    width=500,
    height=500
).configure_axis(
    gridColor='green',
    domainColor='yellow'
)

base
```

Result is:

![mapborder](https://user-images.githubusercontent.com/23631696/41828394-54711310-7878-11e8-8bdc-3325e740a1a5.png)

Another example is:

![ozborder](https://user-images.githubusercontent.com/23631696/41828601-85fd560e-7879-11e8-9833-49ee5d6618e5.png)

**Comment by jakevdp** [comment]
cc/ @kanitw @domoritz

**Comment by iliatimofeev** [comment]
```python
base.configure(style = dict(cell = alt.MarkConfig(strokeOpacity=0)))
```
![image](https://user-images.githubusercontent.com/11561581/41935557-c7bfcbd4-7992-11e8-9a70-6b62ecab35ac.png)

**Comment by iliatimofeev** [comment]
May be more appropriate way to do it is to define custom theme as described in 
[configuration doc](https://altair-viz.github.io/user_guide/configuration.html#defining-a-custom-theme).
Details on style definition you can find in  [vega-lite style doc](https://vega.github.io/vega-lite/docs/config.html#mark-config)
I don't know where documented that chart area has `cell` style but you can see it generated vega.
```python
def no_cell():
    return {
        'config': {
            'style': {
                'cell':{
                    'strokeOpacity':0
                } 
            }
        }
    }

# register the custom theme under a chosen name
alt.themes.register('no_cell', no_cell)
# enable the newly registered theme
alt.themes.enable('no_cell')
# draw the chart
base
```

**Comment by iliatimofeev** [comment]
Or as described in [view-configuration](https://altair-viz.github.io/user_guide/configuration.html#view-configuration)
```python
base.configure_view(strokeWidth=0)
```

**Comment by joelostblom** [comment]
@coolum001 I am going through Altair issues to find those that have been resolved and can be closed. It looks to me like this issue has been solved so I am closing it, but please feel free to reopen and add a comment if there is something you don't think is resolved yet.
