### ISSUE TITLE
TypeError: 'ellipsis' object is not iterable

### ISSUE THREAD

**Issue by iaindillingham** [altair-viz/altair#972]
I tried to import altair and fell at the first hurdle with `TypeError: 'ellipsis' object is not iterable` when I ran `import altair as alt` in a new Jupyter notebook.

I've followed the [Altair installation instructions][1] as well as [those for IPython Vega][2]. I'm running against Python 3.5 on Ubuntu. I see that Travis CI is testing and passing against Python 3.5, however.

Selected dependencies:

`altair` 2.1.0
`notebook` 5.5.0
`vega` 1.3.0

[1]: https://altair-viz.github.io/getting_started/installation.html#installation-notebook
[2]: https://github.com/vega/ipyvega

**Comment by jakevdp** [comment]
What code did you run to produce that error?

**Comment by iaindillingham** [comment]
`import altair as alt`

In a fresh Python 3.5 virtualenv, having followed the installation instructions that linked to above. I'm afraid I didn't get any further. Here's the [stack trace](https://github.com/altair-viz/altair/files/2136356/stacktrace.txt).

**Comment by jakevdp** [comment]
Looks like an issue in Python 3.5.2 that has been fixed in more recent releases: https://github.com/python/typing/issues/259

Please update to Python 3.5.3 or newer to fix this.

**Comment by iaindillingham** [comment]
Thanks for the speedy response.

**Comment by Demetrio92** [comment]
you guys maybe at least want to add a warning there to the package. In ubuntu 16.04 python 3.5.2 is still the default version.
