### ISSUE TITLE
manual size ranges

### ISSUE THREAD

**Issue by XaviFar** [altair-viz/altair#973]
If we get the natural disasters example, is there a way to manually select the size of the dots and also what they represent?
Let's say I want a 500k, 1000k, 2000k and 5000k, is there a parameter to select this manually?
A part from this, is there a way to change the labels of this legend? because in the plot I'm working on when a value is 0.001, it just shows 0.00 and I don't know how to format this.

These may be silly questions, but I'm struggling a little bit with the syntax.

Thanks!!

```python
import altair as alt
from altair.expr import datum
from vega_datasets import data

source = data.disasters.url

alt.Chart(source).mark_circle(
    opacity=0.8,
    stroke='black',
    strokeWidth=1
).encode(
    alt.X('Year:O', axis=alt.Axis(labelAngle=0)),
    alt.Y('Entity:N'),
    alt.Size('Deaths:Q',
        scale=alt.Scale(range=[0, 5000]),
        legend=alt.Legend(title='Annual Global Deaths')
    ),
    alt.Color('Entity:N', legend=None)
).properties(
    width=480,
    height=350
).transform_filter(
    datum.Entity != 'All natural disasters'
)
```

**Comment by jakevdp** [comment]
You can control what values appear in the legend using the ``values`` parameter of ``alt.Legend``. For example:
```python
legend=alt.Legend(title='Annual Global Deaths',
                          values=[500000, 1000000, 2000000, 5000000])
```

**Comment by jakevdp** [comment]
You can control the format of numbers in the legend using the ``format`` argument along with [d3 format codes](https://github.com/d3/d3-format). e.g.
```python
legend=alt.Legend(title='Annual Global Deaths',
                  format=".2s",
                  values=[500000, 1000000, 2000000, 5000000])
```

**Comment by XaviFar** [comment]
Awesome!
works like a charm!
