### ISSUE TITLE
Hide top and right axis (gray lines)

### ISSUE THREAD

**Issue by lincolnfrias** [altair-viz/altair#975]
They don't disappear when removing the grid lines. Is there any strategy to hide them?

```python
import pandas as pd
import altair as alt
budget = pd.read_csv("https://github.com/chris1610/pbpython/raw/master/data/mn-budget-detail-2014.csv")
budget_top_10 = budget.sort_values(by='amount',ascending=False)[:10]

alt.Chart(budget_top_10).mark_bar().encode(
    x='detail', 
    y='amount').configure_axis(
    grid=False
)
```

![image](https://user-images.githubusercontent.com/11890487/41944320-a891bcc8-797d-11e8-92c1-dc66e4390a10.png)

I also posted [this question on stackoverflow](https://stackoverflow.com/questions/51044941/hide-top-axis-in-altair).

**Comment by jakevdp** [comment]
That is part of the Chart's view box; you can adjust its appearance using ``configure_view``. For example:

```python
import pandas as pd
import altair as alt
budget = pd.read_csv("https://github.com/chris1610/pbpython/raw/master/data/mn-budget-detail-2014.csv")
budget_top_10 = budget.sort_values(by='amount',ascending=False)[:10]

alt.Chart(budget_top_10).mark_bar().encode(
    x='detail', 
    y='amount').configure_axis(
    grid=False
).configure_view(
    strokeOpacity=0
)
```
![visualization 23](https://user-images.githubusercontent.com/781659/41950806-c4a2f9b4-797c-11e8-86fb-50bccf5cb384.png)
