### ISSUE TITLE
Is there a way to hide the top and right border "axis" lines?

### ISSUE THREAD

**Issue by palewire** [altair-viz/altair#976]
If I export a transparent backed SVG from Altair it still carries a thin stroke on the top and right axes. Is there a way to remove them?

**Comment by iliatimofeev** [comment]
I guess recipe from #969 would help.

**Comment by lincolnfrias** [comment]
Use `.configure_view(strokeOpacity=0)`. See example in #975.

**Comment by palewire** [comment]
That worked,@lincolnfrias. Thank you. 

This should be documented at the very least. Where could that best go? I'd be happy to add it.

Also, am I crazy, or should there be a more directly API for this. If I can say `grid=False` should there be a similar option for this? Or perhaps the default should not have stroke?

**Comment by jakevdp** [comment]
This example could go in the configuration docs: https://altair-viz.github.io/user_guide/configuration.html

Source here: https://github.com/altair-viz/altair/blob/master/doc/user_guide/configuration.rst

Currently it mostly contains a list of available keywords, but adding some examples would be very useful.

**Comment by nemo-omen** [comment]
I know this is pretty old at this point, but I want to leave an answer here for anyone who's looking.

You can remove the axis borders by setting `domainOpacity=0`, in `configure_axis`, or one of its varients.

**Comment by dzonimn** [comment]
Hi, sorry to resurrect an old thread, but I found this to be the most relevant thread out of all the other similar ones that I've found. 

I'm trying to achieve something like this, but only on one specific chart type within a concatenated layered chart. If I specify `configure_view(strokeOpacity=0)` on the desired chart, it's not possible as concat charts would rather you specify top-level configurations at the end. If I specify it at the end, every single chart in the concatenation will be affected.

Perhaps I am approaching this the wrong way, so I think it would be more helpful to specify what I'm trying to do. I want to be able to generate a concatenated vertical chart like so:

## Title of VConcat Chart
### 1st Image and Subtitle (encoded as a mark_image + mark_text layered chart)
1st Chart (with view strokeOpacity = 1)
### 2nd Image and Subtitle
2nd Chart

and so on..

I have tried giving each of the chart objects a title, but that gives me no ability (to my knowledge) to append an image/icon to the front of the title. It also leads to strange alignment issues as the system I'm working with (Kibana) works on an older Vega spec that doesn't have text anchors, so I decided to try it this way. At worst, I will just set everything to strokeOpacity=0. I am curious if there is some other way to approach this.
