### ISSUE TITLE
scatter-matrix example don't fit into screen

### ISSUE THREAD

**Issue by iliatimofeev** [altair-viz/altair#988]
https://altair-viz.github.io/gallery/scatter_matrix.html#scatter-matrix
![image](https://user-images.githubusercontent.com/11561581/42128898-7df8a956-7cbe-11e8-8aa7-65e8621259c0.png)
```python
#...
).properties(
    width=150, # suggested instead of 250
    height=150 # suggested instead of 250
).repeat(
#...
```

**Comment by jakevdp** [comment]
Thanks – would you like to open a pull request?
