### ISSUE TITLE
adding a tooltip makes a legend 'undefined'

### ISSUE THREAD

**Issue by jowens** [altair-viz/altair#990]
I wanted to add a tooltip to an existing chart specification. The important line is at the bottom, `tooltip=['gpuinfo.name', 'm_teps', 'elapsed'],`. When I comment out this line, the graph looks as I expect:

![export 1](https://user-images.githubusercontent.com/976970/42140846-1c590402-7d59-11e8-8be5-a4e751d41a80.png)

but when I include this line, the legend becomes undefined:

![export](https://user-images.githubusercontent.com/976970/42140852-329c8dec-7d59-11e8-9a43-7b78d326a53b.png)

Here's the non-tooltip properly-defined-legend JSON: https://gist.github.com/jowens/0dda3fb38848aaf03f9b0b61247c0f29

and the tooltip undefined-legend JSON: https://gist.github.com/jowens/63b4f42c12fe31044f3648409f8ab948

Am I doing something wrong here?

```
chart = Chart(df).mark_point().encode(
    x=X('dataset:N',
        axis=Axis(
            title='Dataset',
        ),
        ),
    column=Column('algorithm:N',
                  header=Header(
                      title='Primitive'
                  ),
                  ),
    y=Y('m_teps',
        axis=Axis(
            title='MTEPS',
        ),
        scale=Scale(type='log'),
        ),
    color=Color('[gpuinfo.name]:N',  # brackets allow . in the field name
                legend=Legend(
                    title='GPU',
                ),
                ),
    shape=Shape('[gpuinfo.name]:N',
                legend=Legend(
                    title='GPU',
                ),
                ),
    # tooltip=['gpuinfo.name', 'm_teps', 'elapsed'],
).interactive()
```

**Comment by jakevdp** [comment]
Maybe try brackets in the tooltip encoding as well?

**Comment by jowens** [comment]
No joy there.

`ValueError: [gpuinfo.name] encoding field is specified without a type; the type cannot be inferred because it does not match any column in the data.`

for

`    tooltip=['[gpuinfo.name]', 'm_teps', 'elapsed'],`

**Comment by jakevdp** [comment]
If you modify the column name like that you'll have to specify the type explicitly as you did above. e.g. ``[gpuinfo.name]:N``.

**Comment by jowens** [comment]
That works:

`    tooltip=['[gpuinfo.name]:N', 'm_teps', 'elapsed'],`

It's pretty kludgey (i.e., unexpected), but a perfectly cromulent workaround.

**Comment by jakevdp** [comment]
Vega-lite needs to know the types of the encodings.

If the encodings exactly match a column in the provided dataframe and no type is specified, the type is inferred from the column's dtype.

Here the encoding does not exactly match the name of a column in the dataframe, so you need to specify the type explicitly.

The story is muddled a bit here by the strange syntax required by vega-lite to handle dots in column names.

Hope that clarifies things!

**Comment by jowens** [comment]
Well, I'd argue that `gpuinfo.name` does in fact precisely match the name of a column in the dataframe, just as `m_teps` and `elapsed` do ...

**Comment by jakevdp** [comment]
Yes, and then Altair gives it the correct type, but then Vega treats it as a hierarchical data reference because of the dot.

**Comment by jowens** [comment]
OK. Column names with dots need to be bracketed to avoid this Vega behavior, and (in this case) then also need to be appended with a type.

**Comment by jakevdp** [comment]
Yes. In general I recommend getting in the habit of always using explicit types, even in the cases that Altair will guess for you.

**Comment by jakevdp** [comment]
We could also make Altair's type inference properly handle bracketed column names, but going that route ends up with a lot of corner cases that would be even harder to explain than this :smile:

**Comment by jowens** [comment]
OK, that makes sense (and I generally do that!), but here I was following the example in https://altair-viz.github.io/gallery/scatter_tooltips.html?highlight=tooltip like a sucker.
