### ISSUE TITLE
MaxRows with Histogram

### ISSUE THREAD

**Issue by bernardocaldas** [altair-viz/altair#996]
I'm trying to use Altair for building a set of histograms from a fairly large dataframe (1M rows). However, after binning (100 bins), I have only one row per bin, so I shouldn't be running into MaxRows errors. Even after enabling the json transformer the plot fails to render. This is instantaneous with matplotlib.

I know I can sample before doing an histogram, but it strikes me as weird since the actual data that is plotted is fairly small.

Is there anything I can do to avoid sampling for a simple histogram?

**Comment by jakevdp** [comment]
You could pre-bin the data using numpy. The max rows error is not about how many marks are being rendered; it's about the fact that your 1M rows are being converted to JSON and serialized in the notebook output as part of the plot specification. The renderer must access all the data in order to bin it.

**Comment by bernardocaldas** [comment]
Got it. In terms of interactive use in a notebook env, would it make sense to have an Altair method to do this in one step, meaning pre-binning using pandas/numpy and then showing a bar plot?
________________________________

**Comment by jakevdp** [comment]
No, I don't think that would make sense within Altair's grammar.

**Comment by bernardocaldas** [comment]
Ok, thanks!

**Comment by fdabek1** [comment]
@jakevdp I am looking for a method in Altair that will take pre-binned data.  Currently using:

```
alt.Chart(df_tbi).mark_bar().encode(
    alt.X("PatientAge:Q", bin=True),
    y='count()',
)
```

But am trying to change that to the pre-binned data due to having a 3GB data file.  Any suggestions?
