### ISSUE TITLE
Domain legend gets squished when horizontal in colab vs vertical in vega-lite editor

### ISSUE THREAD

**Issue by zanarmstrong** [altair-viz/altair#998]
In colab, the legend gets squished so that the text is unreadable when there are multiple breakpoints. 

Code to reproduce: 
```python
import altair as alt
from vega_datasets import data

counties = alt.topo_feature(data.us_10m.url, 'counties')
unemp_data = data.unemployment.url

alt.Chart(counties).mark_geoshape().encode(
    color=alt.Color('rate:Q',
          scale=alt.Scale(type="linear",
              domain=[.02,.02,.035,.035,.05,.05,.065,.065,.08,.08,.095,.095,.11,.11,.125,.125,.14,.14,.155,.155],
                          range=    
    ["#5e4fa2","#5e4fa2",
     "#3288bd","#3288bd",
     "#66c2a5","#66c2a5",
     "#abdda4","#abdda4",
     "#e6f598","#e6f598",
     "#fee08b","#fee08b",
     "#fdae61","#fdae61",
     "#f46d43","#f46d43",
     "#d53e4f","#d53e4f",
     "#9e0142","#9e0142"])),

).transform_lookup(
    lookup='id',
    from_=alt.LookupData(unemp_data, 'id', ['rate'])
).project(
    type='albersUsa'
).properties(
    width=500,
    height=300
)
```

<img width="636" alt="screen shot 2018-07-04 at 12 02 13 pm" src="https://user-images.githubusercontent.com/7397271/42291718-559809d6-7f82-11e8-99b2-db3c9f568dbc.png">

In the vega-lite editor, this gets rendered as a vertical legend. 

<img width="577" alt="screen shot 2018-07-04 at 12 06 56 pm" src="https://user-images.githubusercontent.com/7397271/42291784-c85f0f00-7f82-11e8-89f7-f76de11e6c0e.png">

```json
{
  "config": {"view": {"width": 400, "height": 300}},
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/us-10m.json",
    "format": {"feature": "counties", "type": "topojson"}
  },
  "mark": "geoshape",
  "encoding": {
    "color": {
      "type": "quantitative",
      "field": "rate",
      "scale": {
        "domain": [
          0.02,
          0.02,
          0.035,
          0.035,
          0.05,
          0.05,
          0.065,
          0.065,
          0.08,
          0.08,
          0.095,
          0.095,
          0.11,
          0.11,
          0.125,
          0.125,
          0.14,
          0.14,
          0.155,
          0.155
        ],
        "range": [
          "#5e4fa2",
          "#5e4fa2",
          "#3288bd",
          "#3288bd",
          "#66c2a5",
          "#66c2a5",
          "#abdda4",
          "#abdda4",
          "#e6f598",
          "#e6f598",
          "#fee08b",
          "#fee08b",
          "#fdae61",
          "#fdae61",
          "#f46d43",
          "#f46d43",
          "#d53e4f",
          "#d53e4f",
          "#9e0142",
          "#9e0142"
        ],
        "type": "linear"
      }
    }
  },
  "height": 300,
  "projection": {"type": "albersUsa"},
  "transform": [
    {
      "lookup": "id",
      "from": {
        "data": {
          "url": "https://vega.github.io/vega-datasets/data/unemployment.tsv",
          "format": {"type": "tsv"}
        },
        "key": "id",
        "fields": ["rate"]
      }
    }
  ],
  "width": 500,
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json"
}
```

Incidentally, the legend is in the vega-lite editor is unfortunately also inaccurate, which I've reported on the vega-lite repo: https://github.com/vega/vega-lite/issues/3981

**Comment by zanarmstrong** [comment]
I don't love that there are so many fewer breakpoints shown in the Vega-lite example, but it's nice that the labels don't overlap. Perhaps the solution is a vertical legend, but with more breakpoints? I realize it probably doesn't help that I'm using some breakpoints multiple times to mimic a "threshold" effect. 

In short, I think there could be multiple different ways to achieve non-overlapping labels. Also, I realize that automatic text labels are a huge pain :).

**Comment by jheer** [comment]
Hi Zan, thanks for filing the issue! A few responses:

- The repeated breakpoint values should have no effect on a linear scale. When I remove them I still get identical output. Vega does support a `threshold` scale type that will provide a discretized color legend (if that is what you want). However, I don't think Vega-Lite (and hence Altair) supports this yet.
- You can change the number of requested tick marks for a gradient legend by adding `"legend": {"tickCount": 10}` to your color encoding.
- Thanks for pointing out the incorrect domain on the legend. This led me to an underlying Vega bug that I will fix soon!

**Comment by jakevdp** [comment]
Also relevant: the version of vega-lite in colab is older than the current release, and the current release substantially reworked legend appearance.

**Comment by jheer** [comment]
One more note: if you want complete control over legend labels, use this approach in VL:

```json
      "legend": {
        "values": [
          0.02,
          0.035,
          0.05,
          0.065,
          0.08,
          0.095,
          0.11,
          0.125,
          0.14,
          0.155
        ],
        "format": ".3f"
      },
```

**Comment by zanarmstrong** [comment]
Hi Jeff -

Thanks for the quick reply!

> "Vega does support a threshold scale type that will provide a discretized color legend (if that is what you want). However, I don't think Vega-Lite (and hence Altair) supports this yet."

Yes - I was trying to force a threshold scale type, since I saw it wasn't an option in Vega-Lite. Can I make a feature request? :)

> "change the number of requested tick marks" & "if you want complete control over legend labels"

sweet!

> This led me to an underlying Vega bug that I will fix soon!

Yay! Glad to hear it. 

> the version of vega-lite in colab is older than the current release

Alas!

**Comment by zanarmstrong** [comment]
For context, I'm prepping for SciPy next Thurs. Am planning to include a (cleaned-up) version of this colab in the links from my presentation: https://colab.research.google.com/drive/1PePamFUfrgvN3ZYaN8fWfP8ovIJ0gyre#scrollTo=R9bJgCqMGa8f

**Comment by zanarmstrong** [comment]
My thresholding hack is actually working, even if it's not supposed to :). 

I had mimicked what I would do in D3 to fake thresholding, assuming that eventually the domain/range were getting passed to d3.scaleLinear(). 

(note: these are not the most visually attractive charts, I made them quickly :)). 

A. Continuous

<img width="579" alt="screen shot 2018-07-04 at 3 18 55 pm" src="https://user-images.githubusercontent.com/7397271/42295301-9cb716b6-7f9d-11e8-8643-db9b260b7750.png">


B. Thresholded

<img width="577" alt="screen shot 2018-07-04 at 3 20 03 pm" src="https://user-images.githubusercontent.com/7397271/42295312-bf5d5f9a-7f9d-11e8-9698-60eecdaef6fb.png">


a. Spec for continuous 

```json
{
  "config": {"view": {"width": 400, "height": 300}},
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/us-10m.json",
    "format": {"feature": "counties", "type": "topojson"}
  },
  "mark": "geoshape",
  "encoding": {
    "color": {
      "type": "quantitative",
      "field": "rate",
      "scale": {
        "domain": [
          0.03,
          0.045,
          0.135,
          0.15
        ],
        "range": [
          "#5e4fa2",
          "#3288bd",
          "#66c2a5",
          "#9e0142"
        ],
        "type": "linear"
      }
    }
  },
  "height": 300,
  "projection": {"type": "albersUsa"},
  "transform": [
    {
      "lookup": "id",
      "from": {
        "data": {
          "url": "https://vega.github.io/vega-datasets/data/unemployment.tsv",
          "format": {"type": "tsv"}
        },
        "key": "id",
        "fields": ["rate"]
      }
    }
  ],
  "width": 500,
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json"
}
```

b. spec for thresholded

```json
{
  "config": {"view": {"width": 400, "height": 300}},
  "data": {
    "url": "https://vega.github.io/vega-datasets/data/us-10m.json",
    "format": {"feature": "counties", "type": "topojson"}
  },
  "mark": "geoshape",
  "encoding": {
    "color": {
      "type": "quantitative",
      "field": "rate",
      "scale": {
        "domain": [
          0.03,
          0.03,
          0.045,
          0.045,
          0.135,
          0.135,
          0.15,
          0.15
        ],
        "range": [
          "#5e4fa2",
          "#3288bd",
          "#3288bd",
          "#66c2a5",
          "#66c2a5",
          "#f46d43",
          "#f46d43",
          "#9e0142"
        ],
        "type": "linear"
      }
    }
  },
  "height": 300,
  "projection": {"type": "albersUsa"},
  "transform": [
    {
      "lookup": "id",
      "from": {
        "data": {
          "url": "https://vega.github.io/vega-datasets/data/unemployment.tsv",
          "format": {"type": "tsv"}
        },
        "key": "id",
        "fields": ["rate"]
      }
    }
  ],
  "width": 500,
  "$schema": "https://vega.github.io/schema/vega-lite/v2.4.3.json"
}
```

**Comment by domoritz** [comment]
Qupport for quantize and quantile legends in Vega-Lite is tracked in https://github.com/vega/vega-lite/issues/1092.

**Comment by jakevdp** [comment]
@zanarmstrong if you are using external colab, you can force it to render using a more recent version of vega & vega-lite using the following:

```python
from altair.vegalite.v2 import display
display.VEGALITE_VERSION = '2.6.0'
display.VEGA_VERSION = '4.0.0'
```

This will not work for jupyter, jupyterlab, or internal colab, because they use different rendering approaches.

**Comment by zanarmstrong** [comment]
Works like a charm - thanks!
